open-cluster-management/backlog#2427 -- quite a bit of rewrite after …
open-cluster-management/rhacm-docs pull request #1052
Opened 2020-08-04 01:43 UTC by bcpswope

…doc test, WIP

2020-08-04 11:26 UTC, bcpswope commented on manage_applications/deleting_channel.adoc
> +. Click on _Subscriptions_.
I didn't see Delete channel

2020-08-05 13:02 UTC, birsanv requested changes

2020-08-05 13:02 UTC, birsanv commented on manage_applications/managing_apps_console.adoc
> +The topology provides you with a visualization of your applications, clusters, relationships, and policies. The application topology includes a visualization of the components that comprise each appl
This was changed in 2.0, we don't the the app topology, we show app cards with application status

Change : 
The application topology includes a visualization of the components that comprise each application. 
with, sample:
The application topology includes a visualization of all applications cards showing application status

2020-08-05 13:02 UTC, birsanv commented on manage_applications/managing_apps_console.adoc
> +* You can select any component from the topology view to view more details.
The Topology tab for app doesn't show app topology, just app cards

2020-08-05 13:02 UTC, birsanv commented on manage_applications/managing_placement_rules.adoc
> +Define the placement rule at the placement rule level for multi-cluster deployments.
Define the placement rule at the **subscription** level

2020-08-05 13:02 UTC, birsanv commented on manage_applications/managing_placement_rules.adoc
> +Define the placement rule at the placement rule level for multi-cluster deployments.
subscription level

2020-08-05 13:02 UTC, birsanv commented on manage_applications/managing_placement_rules.adoc
> +You can define a placement rule as a separate resource or define the rule within the definition for a deployable or placement rule.
I thought we are not discussing deployables anymore .. the Placement Rule is always defined as a separate resource for app scenarios; the subscription references a placement rule

2020-08-05 13:02 UTC, birsanv commented on manage_applications/managing_placement_rules.adoc
> +For more information about creating the definition for a deployable or placement rules, see:
For more information about creating the definition for a  placement rule, see

2020-08-05 13:02 UTC, birsanv commented on manage_applications/managing_placement_rules.adoc
> +Your new placement rule does not display in this list until the rule is referenced by a placement rule that is used by an application.
until the rule is referenced by a **subscription**

2020-08-05 13:02 UTC, birsanv commented on manage_applications/managing_placement_rules.adoc
> +You can assign a placement rule to a deployable or placement rule.
take this out

2020-08-05 13:02 UTC, birsanv commented on manage_applications/managing_placement_rules.adoc
> +Include the following `placement` fields in your deployable or placement rule spec with the values to reference the placement rule:
in your subscription spec

2020-08-05 13:02 UTC, birsanv commented on manage_applications/managing_placement_rules.adoc
> +. From the expanded view for the application, you can see the available placement rules for each channel.
you can see the available subscriptions

2020-08-05 13:02 UTC, birsanv commented on manage_applications/managing_placement_rules.adoc
> +The details for each placement rule include any assigned placement rule.
The details for each subscription..

2020-08-05 13:02 UTC, birsanv commented on manage_applications/managing_placement_rules.adoc
> +If needed, you can select to view or edit the YAML for the placement rule, placement rule, and channel from this resource pipeline table.
the subscription, placement rule, and channel

2020-08-05 13:02 UTC, birsanv commented on manage_applications/managing_placement_rules.adoc
> +Within the table that lists your applications, expand the row for the application that includes the placement rule that is assigned the placement rule.
Too many occurrences where subscription was replaced by PR ..

expand the row for the application that includes the placement rule that is assigned the placement rule.

should be 

expand the row for the application that includes the subscription that is assigned the placement rule.

2020-08-06 14:32 UTC, bcpswope commented on manage_applications/managing_placement_rules.adoc
> +You can define a placement rule as a separate resource or define the rule within the definition for a deployable or placement rule.
@birsanv I keep getting back/forth information ... this file is about managing placement rules. If that is not what this file is for anymore, I need development to read and go over the doc again in another issue.

2020-08-06 16:43 UTC, bcpswope commented on manage_applications/deleting_channel.adoc
> +. Click on _Subscriptions_.
addressed

2020-08-06 16:45 UTC, bcpswope commented on manage_applications/managing_apps_console.adoc
> +The topology provides you with a visualization of your applications, clusters, relationships, and policies. The application topology includes a visualization of the components that comprise each appl
Changed

2020-08-06 16:45 UTC, bcpswope commented on manage_applications/managing_apps_console.adoc
> +* You can select any component from the topology view to view more details.
removed

2020-08-06 18:34 UTC, bcpswope commented on manage_applications/managing_placement_rules.adoc
> +Include the following `placement` fields in your deployable or placement rule spec with the values to reference the placement rule:
done

2020-08-06 18:34 UTC, bcpswope commented on manage_applications/managing_placement_rules.adoc
> +. From the expanded view for the application, you can see the available placement rules for each channel.
done, line 105 I pinged about.

2020-08-06 18:40 UTC, bcpswope commented on manage_applications/managing_placement_rules.adoc
> +Within the table that lists your applications, expand the row for the application that includes the placement rule that is assigned the placement rule.
Changed. But as I look at all these tasks, I think every task above "Delete placement rule" was not changed for the 2.0 UI. This has to be done in a refresh and we have to stay on top of it as the UI changes for 2.1. For this issue, I edited the Delete tasks only.

2020-08-06 18:52 UTC, bcpswope commented on manage_applications/managing_placement_rules.adoc
> +You can assign a placement rule to a deployable or placement rule.
I am not sure what you mean, then entire Assign a placement rule?

2020-08-06 18:56 UTC, bcpswope commented on manage_applications/managing_placement_rules.adoc
> +Define the placement rule at the placement rule level for multi-cluster deployments.
no idea what happened here lol, changed.

2020-08-06 20:34 UTC, birsanv approved these changes

2020-08-06 20:39 UTC, merged