Update known_issues.md
open-cluster-management/rhacm-docs pull request #1072
Opened 2020-08-10 14:15 UTC by dockerymick

https://github.com/open-cluster-management/backlog/issues/2757

Recreated PR on correct branch. Change is only applicable to 1.0

2020-08-10 14:19 UTC, chenz4027 approved these changes
Thanks!

2020-08-10 18:20 UTC, dhaiducek requested changes
Looks good, especially since it's only for 1.0.0. I've left comments about some of the lines of code, many that @chenz4027 can verify since she's seen the issue directly. 🙂

2020-08-10 18:20 UTC, dhaiducek commented on release_notes/known_issues.md
> +## Self-destruct script does not clean target clusters
I wasn't even aware there was a self-destruct script available until this issue. Do users know about it? If not, I think this should be titled something similar to `Managed clusters not clean after detaching from Hub` (and/or provide a link to the self-destruct script?)

@chenz4027 What do you think--do these steps cover the steps in the script so that we don't have to link to it?

2020-08-10 18:20 UTC, dhaiducek commented on release_notes/known_issues.md
> +   kubectl api-resources -o name --namespaced=true); do echo "===$api==="; kubectl get $api -n multicluster-endpoint
This command is missing some code to make it work. However, it looks like this dumps out a list of resources. Should we just remove this step? Either that or we can fix the code and maybe rename it to "List the remaining RHACM resources..." instead of "Remove your API resources..."

For reference, the code should be:
```
for api in $(kubectl api-resources -o name --namespaced=true); do echo "===$api==="; kubectl get $api -n multicluster-endpoint; done
```

@chenz4027 Was the purpose here to delete each of the remaining resources after listing them?

2020-08-10 18:20 UTC, dhaiducek commented on release_notes/known_issues.md
> +   kubectl get subscriptions.apps.open-cluster-management.io
This is namespaced, so we'll probably need:
```
kubectl get subscriptions.apps.open-cluster-management.io --all-namespaces
```

2020-08-10 18:20 UTC, dhaiducek commented on release_notes/known_issues.md
> +   kubectl delete subscriptions.apps.open-cluster-management.io
I think we'll need to add a namespace and resource:
```
kubectl delete subscriptions.apps.open-cluster-management.io -n <namespace> <subscription-name>
```

2020-08-10 18:20 UTC, dhaiducek commented on release_notes/known_issues.md
> +   kubectl delete apps.open-cluster-management.io
Since we're deleting CRDs, we'll need:
```
kubectl delete crd <apps-crd-name>
```

2020-08-10 18:20 UTC, dhaiducek commented on release_notes/known_issues.md
> +   kubectl get clusterrolebinding | grep ^endpoint | awk '{print $1}'
I think this line should be:
```
kubectl delete clusterrole $(kubectl get clusterrole | grep ^endpoint | awk '{print $1}')
```

Or, @chenz4027, is this to query for it first? And these should both be `clusterrole`, correct? In the original commands provided, the subshell says `clusterrolebinding`, so I wanted to make sure.

2020-08-10 18:20 UTC, dhaiducek commented on release_notes/known_issues.md
> +   kubectl get clusterrolebinding | grep ^endpoint | awk '{print $1}'
As above, this might need to be changed to (with confirmation from @chenz4027 about both commands):
```
kubectl delete clusterrolebinding $(kubectl get clusterrolebinding | grep ^endpoint | awk '{print $1}')
```

2020-08-11 15:11 UTC, dockerymick commented on release_notes/known_issues.md
> +## Self-destruct script does not clean target clusters
@dhaiducek thanks for your comment, that's a good point. There is a link for the self-destruct script: https://github.com/open-cluster-management/endpoint-operator/blob/master/hack/self-destruct.sh

@chenz4027 thoughts?

2020-08-11 15:14 UTC, dockerymick commented on release_notes/known_issues.md
> +## Self-destruct script does not clean target clusters
So far I have updated the title of the known issue and added the link for the self-destruct script

2020-08-11 15:17 UTC, chenz4027 commented on release_notes/known_issues.md
> +## Self-destruct script does not clean target clusters
yep that's the script I was referring. The master branch is for 2.0 and I think they have a branch for 1.x as https://github.com/open-cluster-management/endpoint-operator/blob/release-1.0.0/hack/self-destruct.sh

2020-08-11 15:17 UTC, chenz4027 commented on release_notes/known_issues.md
> +   kubectl api-resources -o name --namespaced=true); do echo "===$api==="; kubectl get $api -n multicluster-endpoint
yeah I think so - to delete the remaining resources. Do we have a combined command for delete maybe?

2020-08-11 15:33 UTC, dockerymick commented
@dhaiducek Thanks for the review, I revisited the issue and i misunderstood. I have updated the commands for the clusterrole and clusterrolebinding. @chenz4027 thanks for your response and review as well. May I ask for one more review from you both please? :)

2020-08-11 16:11 UTC, chenz4027 approved these changes
Looks good to me!

2020-08-11 17:23 UTC, dhaiducek commented on release_notes/known_issues.md
> +## Self-destruct script does not clean target clusters
Shooooot. I just noticed that `endpoint-operator` is a private repo, so we can't link to it at all from the docs. 🙁 

Okay, in that case we need to make sure these steps cover what the script is doing (or leave this issue as technical debt since we may not have a ton of 1.0 users?).

For the former, we could probably update the command in Step 1 to delete namespaced resources like this (haven't tested it yet):
```
for api in $(kubectl api-resources -o name --namespaced=true | grep multicloud.ibm); do echo "===$api==="; for resource in $(kubectl get $api -o name -n multicluster-endpoint); do kubectl delete ${resource} -n multicluster-endpoint --timeout=15s; done; done
```

2020-08-11 17:26 UTC, dhaiducek commented on release_notes/known_issues.md
> +   kubectl delete clusterrolebinding $(kubectl get clusterrole | grep ^endpoint | awk '{print $1}')
@chenz4027 Should this be `kubectl get clusterrolebinding` instead of `clusterrole` for the inner command?
```
kubectl delete clusterrolebinding $(kubectl get clusterrolebinding | grep ^endpoint | awk '{print $1}')
                                                ^^^here
```

2020-08-11 17:28 UTC, chenz4027 commented on release_notes/known_issues.md
> +   kubectl delete clusterrolebinding $(kubectl get clusterrole | grep ^endpoint | awk '{print $1}')
yep @dhaiducek Nice catch 

```
Kubectl delete clusterrolebinding $(kubectl get clusterrolebinding | grep ^endpoint | awk '{print $1}')
```

2020-08-11 19:09 UTC, dockerymick commented
@dhaiducek I removed the link to the repo and updated step 1

2020-08-12 14:09 UTC, dhaiducek requested changes
Couple minor things and then I think this will be fine.

2020-08-12 14:09 UTC, dhaiducek commented on release_notes/known_issues.md
> +1. Delete the namesapce resources for Advanced Cluster Management for Kubernetes resources by running the following command:
- "namespace" is misspelled
- We should provide an additional delete command here to delete the resources, like:
```
kubectl delete -n multicluster-endpoint <resource>
```

2020-08-12 19:31 UTC, merged