open-cluster-management/backlog#4172 Add vmware
open-cluster-management/rhacm-docs pull request #1183
Opened 2020-09-04 15:37 UTC by cadawson

2020-09-04 16:11 UTC, chrisahl commented on install/plan_capacity.adoc
> + ** Instance size: ??
VMware will not have an instance size.  This is what currently shows on the worker nodes
![image](https://user-images.githubusercontent.com/32707829/92261650-cf1db080-eea7-11ea-8bda-785e6e1b89d6.png)

2020-09-04 16:13 UTC, chrisahl commented on manage_cluster/create.adoc
> +* xref:../manage_cluster/create_azure.adoc#creating-a-cluster-on-vmware-vsphere[Creating a cluster on VMware vSphere] (Requires {ocp} version 4.5, or later)
One entry has {ocp} and one has {ocp-short} ?

2020-09-04 16:19 UTC, chrisahl commented on manage_cluster/prov_conn_vm.adoc
> +** Required static IP addresses for API and Ingress instances
I would like to move lines 19-22 to the create_vm doc prereq section since it pertains to each instance of VMware deployment.  The VIPs and and DNS entries are unique per instance.

2020-09-04 16:20 UTC, chrisahl commented on manage_cluster/create_vm.adoc
> +This name is used in the hostname of the cluster. Note: This value must match the name that you used to create the DNS records listed in the provider connection prerequisites section.
Note: can point to prereq on this page once you move the info...see comment below

2020-09-04 16:24 UTC, chrisahl commented on manage_cluster/create_vm.adoc
> +.. API VIP - The IP address to use for internal API communication. If not provided, the DNS must be pre-configured so that `api.` resolves correctly.
Add the following after the first sentence:
Note: This value must match the name that you used to create the DNS records listed in the prerequisites section.

2020-09-04 16:24 UTC, chrisahl commented on manage_cluster/create_vm.adoc
> +.. Ingress VIP - The IP address to use for ingress traffic. If not provided, the DNS must be pre-configured so that `test.apps.` resolves correctly.
Add the following after the first sentence:
Note: This value must match the name that you used to create the DNS records listed in the prerequisites section.

2020-09-04 16:35 UTC, chrisahl commented on manage_cluster/prov_conn_vm.adoc
> +. Add your VMware vCenter server fully-qualified host name or IP address. The value must be defined in the vCenter server root CA certificate.
Change to:

Add your _VMware vCenter server fully-qualified host name or IP address_. The value must be defined in the vCenter server root CA certificate.  Fully-qualified  host name is preferred.

2020-09-04 16:43 UTC, chrisahl commented on manage_cluster/prov_conn_vm.adoc
> +You can download the `download.zip` package with the certificate from the https:// vCenter address /certs/download.zip[VMware vCenter].
Need markdown help on this.  
```
You can download the `download.zip` package with the certificate from 
https://_VMware vCenter server fully-qualified host name or IP address_/certs/download.zip.  Unzip `download.zip` and use a certificate from certs/<platform>/*.0 
```

Here is what I have on my mac:
```
 ls certs
lin	mac	win

ls certs/mac
1a648cf0.0	1a648cf0.crt	1a648cf0.r1

ls certs/lin
1a648cf0.0	1a648cf0.r1


```

2020-09-04 17:10 UTC, chrisahl commented on troubleshooting/trouble_vm_cluster.adoc
> +[#troubleshooting-cluster-creation-on-vmware-vstream]
typo - vstream > vSphere

line 1 and 2

2020-09-04 20:02 UTC, cadawson reviewed
Resolved some things here.

2020-09-04 20:02 UTC, cadawson commented on install/plan_capacity.adoc
> + ** Instance size: ??
Updated

2020-09-04 20:02 UTC, cadawson commented on manage_cluster/create.adoc
> +* xref:../manage_cluster/create_azure.adoc#creating-a-cluster-on-vmware-vsphere[Creating a cluster on VMware vSphere] (Requires {ocp} version 4.5, or later)
Yes, good catch. {ocp} is the full name that we use on the first occurrence. {ocp-short} is the shorter version that we can use in later references.

2020-09-04 20:02 UTC, cadawson commented on manage_cluster/create_vm.adoc
> +.. Ingress VIP - The IP address to use for ingress traffic. If not provided, the DNS must be pre-configured so that `test.apps.` resolves correctly.
Updated

2020-09-04 20:02 UTC, cadawson commented on manage_cluster/create_vm.adoc
> +.. API VIP - The IP address to use for internal API communication. If not provided, the DNS must be pre-configured so that `api.` resolves correctly.
updated

2020-09-04 20:02 UTC, cadawson commented on manage_cluster/prov_conn_vm.adoc
> +** Required static IP addresses for API and Ingress instances
Makes sense, moved

2020-09-04 20:02 UTC, cadawson commented on manage_cluster/prov_conn_vm.adoc
> +. Add your VMware vCenter server fully-qualified host name or IP address. The value must be defined in the vCenter server root CA certificate.
Updated

2020-09-04 20:02 UTC, cadawson commented on manage_cluster/prov_conn_vm.adoc
> +You can download the `download.zip` package with the certificate from the https:// vCenter address /certs/download.zip[VMware vCenter].
See if this helps.

2020-09-04 20:02 UTC, cadawson commented on troubleshooting/trouble_vm_cluster.adoc
> +[#troubleshooting-cluster-creation-on-vmware-vstream]
Not sure where that came from. Thanks.

2020-09-05 00:34 UTC, chrisahl commented on manage_cluster/create_vm.adoc
> +This name is used in the hostname of the cluster. Note: This value must match the name that you used to create the DNS records listed in the provider connection prerequisites section.
I did not see this updated to:
```DNS records listed in the prerequisites section.```

2020-09-05 00:35 UTC, chrisahl commented on manage_cluster/prov_conn_vm.adoc
> +For example: `certs/lin 3a343545.0`
`certs/lin/3a343545.0`

2020-09-05 00:40 UTC, chrisahl commented on manage_cluster/scale.adoc
> +*Note:* Because {product-title-short} uses Hive for OpenShift to determine the number of nodes in the cluster, you must change the `MachineSet` parameter to change the number of nodes. If you just re
In this section you have both `MachineSet` and `MachineSets`.  I think it should just be the former

2020-09-05 00:41 UTC, chrisahl requested changes
Left a few more inline comments

2020-09-08 15:23 UTC, cadawson commented on manage_cluster/create_vm.adoc
> +This name is used in the hostname of the cluster. Note: This value must match the name that you used to create the DNS records listed in the provider connection prerequisites section.
It looks like it is, to me. I will check it when it is merged.

2020-09-08 16:56 UTC, cadawson commented on manage_cluster/scale.adoc
> +*Note:* Because {product-title-short} uses Hive for OpenShift to determine the number of nodes in the cluster, you must change the `MachineSet` parameter to change the number of nodes. If you just re
Changed to MachineSet

2020-09-08 16:56 UTC, cadawson commented on manage_cluster/prov_conn_vm.adoc
> +For example: `certs/lin 3a343545.0`
Updated the formatting

2020-09-09 01:08 UTC, chrisahl approved these changes

2020-09-09 15:03 UTC, dockerymick requested changes
I think the troubleshoot topics should be separated. The section titles and content looks bunched up. 

Also consider thinking about where the new files are first referenced. I imagine that this would be referenced from What's new first. Are there any other files where the user should be referenced to VMWare documentation?

2020-09-09 15:03 UTC, dockerymick commented on install/plan_capacity.adoc
> +* Creating an OpenShift cluster on VMware vSphere.
Add the conref for OpenShift: {ocp-short}

2020-09-09 15:03 UTC, dockerymick commented on manage_cluster/create.adoc
> +* xref:../manage_cluster/create_azure.adoc#creating-a-cluster-on-vmware-vsphere[Creating a cluster on VMware vSphere] (Requires {ocp} version 4.5, or later)
I think this statement "(Requires {ocp} version 4.5, or later)" makes the tilte too long. Can you only mention the requirement in the file?

2020-09-09 15:03 UTC, dockerymick commented on manage_cluster/create_vm.adoc
> +You can use the {product-title} console to deploy a {ocp} cluster on VMware vSphere.
You can use the {product-title} console to deploy **an** {ocp} cluster on VMware vSphere.

2020-09-09 15:03 UTC, dockerymick commented on manage_cluster/create_vm.adoc
> +You must have the following prerequisites before creating a cluster on vSphere:
Your ending punctuation in inconsistent. Some statements have periods, others don't. I suggest adding a period at the end of your bullet point statements.

2020-09-09 15:03 UTC, dockerymick commented on manage_cluster/create_vm.adoc
> +* vSphere provider connection - See xref:../manage_cluster/prov_conn_vm.adoc#prov_conn_vm[Creating a provider connection for VMware vSphere] for more information.
You must have a vSphere provider connection. See xref:../manage_cluster/prov_conn_vm.adoc#prov_conn_vm[Creating a provider connection for VMware vSphere] for more information.

2020-09-09 15:03 UTC, dockerymick commented on manage_cluster/create_vm.adoc
> +* A Red Hat OpenShift image pull secret.
Use the conref here

2020-09-09 15:03 UTC, dockerymick commented on manage_cluster/create_vm.adoc
> +* The following information for the VMware instance where you are deploying:
You must have the following information for the VMware instance where you are deploying:

2020-09-09 15:03 UTC, dockerymick commented on manage_cluster/create_vm.adoc
> +== Creating your cluster with the {product-title-short} console
the conref should be {product-title}

2020-09-09 15:03 UTC, dockerymick commented on manage_cluster/create_vm.adoc
> +Note: This procedure is for creating a cluster.
I would add asterisks around Note, is this note required tho? You mentioned that these were the steps to create a cluster when you prompted the user for the tasks. Maybe start the note from "If you have an existing cluster.."

2020-09-09 15:03 UTC, dockerymick commented on manage_cluster/create_vm.adoc
> +This name is used in the hostname of the cluster. Note: This value must match the name that you used to create the DNS records listed in the provider connection prerequisites section.
I would bold Note and Tip

2020-09-09 15:03 UTC, dockerymick commented on manage_cluster/create_vm.adoc
> +See xref:../manage_cluster/release_images.adoc#release-images[Release images] for more information about release images.
Since the "release images" is the title of the file, let's say See Release images for more information

2020-09-09 15:03 UTC, dockerymick commented on manage_cluster/create_vm.adoc
> +Note: Only versions 4.5.x and higher are supported.
Is this apart of the requirement that you mentioned in the manage_cluster/create.adoc  file? I think this note should come a little bit earlier in the doc. Also bold Note

2020-09-09 15:03 UTC, dockerymick commented on manage_cluster/create_vm.adoc
> +If you do not have one configured, or want to configure a new one, select *Add connection*. See https://github.com/open-cluster-management/rhacm-docs/blob/2.0_stage/manage_cluster/prov_conn.adoc
Update your link reference here. Change `See https://github.com/open-cluster-management/rhacm-docs/blob/2.0_stage/manage_cluster/prov_conn.adoc`

TO 

See xref:../manage_cluster/prov_conn.adoc[Creating a provider connection]  for more information.

2020-09-09 15:03 UTC, dockerymick commented on manage_cluster/create_vm.adoc
> +. Enter the base domain information that you configured for your vSphere account. If there is already a base domain associated with the selected provider connection, that value is populated in that f
Bold Note

2020-09-09 15:03 UTC, dockerymick commented on manage_cluster/create_vm.adoc
> +Worker pools: You can create one or more worker nodes in a worker pool to run the container workloads for the cluster.
It wasn't clear that you were going to define node and worker pools. These definitions would probably be more appropriate for Content files vs in the between steps.

2020-09-09 15:03 UTC, dockerymick commented on manage_cluster/create_vm.adoc
> +. Configure the cluster networking options.
Configure the cluster networking options. View the following definition list of  the networking options:

2020-09-09 15:03 UTC, dockerymick commented on manage_cluster/create_vm.adoc
> +Note: You do not have to run the `kubectl` command that is provided with the cluster details to import the cluster. When you create the cluster, it is automatically configured under the management of
Bold Note. 

I would switch the order of the sentences. I suggest the following update: "When you create the cluster, it is automatically configured under the management of {product-title-short}. It is not required to run the `kubectl` command that is provided with the cluster details to import the cluster."

2020-09-09 15:03 UTC, dockerymick commented on manage_cluster/create_vm.adoc
> +To access a cluster that is managed by Red Hat Advanced Cluster Management for Kubernetes, complete the following steps:
use the conref here

2020-09-09 15:03 UTC, dockerymick commented on manage_cluster/create_vm.adoc
> +Note these values to use when you log in to the cluster.
Remove this note. Update this statement, " Select *Reveal credentials* to view the user name and password for the cluster.
Note these values to use when you log in to the cluster."

TO 

Select *Reveal credentials* to view the user name and password for the cluster. Use the credentials when you log in to the cluster.

2020-09-09 15:03 UTC, dockerymick commented on manage_cluster/create_vm.adoc
> +. Select the _Actions_ menu for the cluster that you want to access.
Are you referring to the "Open and close list of options"? (3 vertical/horizontal dots)

Brandi and I refer to that image a the **Options** icon. Please update Actions to Options

2020-09-09 15:03 UTC, dockerymick commented on manage_cluster/create_vm.adoc
> +Tip: If you already know the log in credentials, you can access the cluster by selecting the _Actions_ menu for the cluster, and selecting *Launch to cluster*.
I think this Tip is not needed. It is repetitive. In the first step let's say, "If you do not have the log in credentials,  navigate to *Automate infrastructure* > *Clusters* from the console. 

Which cluster are they trying to access? Is it the OpenShift cluster? I am assuming if the user is able to navigate from the menu, they are already logged in, right?

2020-09-09 15:03 UTC, dockerymick commented on manage_cluster/create_vm.adoc
> +When you remove a {ocp-short} cluster from management that was created with {product-title-short}, you can either _Detach_ it or _Destroy_ it.
When you remove an {ocp-short}

2020-09-09 15:03 UTC, dockerymick commented on manage_cluster/create_vm.adoc
> +. Select the option menu beside the cluster that you want to delete.
Select the *Options* icon for the cluster that you want to delete.

2020-09-09 15:03 UTC, dockerymick commented on manage_cluster/prov_conn_vm.adoc
> +You need a provider connection to use {product-title} console to deploy and manage a {ocp-short} cluster on VMware vSphere. Note: Only {ocp-short} versions 4.5.x, and later, are supported.
**an** {ocp-short}.

Lets bold Note. Also let's put the notes together. Change Note to Notes and list them. For example: 

**Notes**:
* Only {ocp-short} versions 4.5.x, and later, are supported.
* This procedure must be done before you can create a cluster with {product-title-short}.

2020-09-09 15:03 UTC, dockerymick commented on manage_cluster/prov_conn_vm.adoc
> +You must have the following prerequisites before creating a provider connection:
You must have the following prerequisites before you create a provider connection:

2020-09-09 15:03 UTC, dockerymick commented on manage_cluster/prov_conn_vm.adoc
> +* Internet access for your {product-title-short} hub cluster so it can create the Kubernetes cluster on VMware vSphere
Inconsistent punctuation for the prereqs.

2020-09-09 15:03 UTC, dockerymick commented on manage_cluster/prov_conn_vm.adoc
> +.. Use the certificate from the `certs/<platform> directory that has a `.0` extension. *Tip:* You can use the `ls certs/<platform>` command to list all of the available certificates for your platform
Double check code block ticks here. looks like you need to add (`) after certs/platform>.

2020-09-09 15:03 UTC, dockerymick commented on manage_cluster/prov_conn_vm.adoc
> +.. Use the certificate from the `certs/<platform> directory that has a `.0` extension. *Tip:* You can use the `ls certs/<platform>` command to list all of the available certificates for your platform
I had to drop the less than sign bc it hides the info in my comment

2020-09-09 15:03 UTC, dockerymick commented on manage_cluster/prov_conn_vm.adoc
> +.. You can download your certificate in the `download.zip` package with the certificate from the https:// vCenter address /certs/download.zip[VMware vCenter].
There should be a URL link here.

2020-09-09 15:03 UTC, dockerymick commented on manage_cluster/prov_conn_vm.adoc
> +See https://docs.openshift.com/container-platform/4.3/installing/installing_aws/installing-aws-default.html#ssh-agent-using_installing-aws-default[Generating an SSH private key and adding it to the a
drop "about how to generate a key"

2020-09-09 15:03 UTC, dockerymick commented on manage_cluster/scale.adoc
> +*Note:* Because {product-title} uses Hive for OpenShift to determine the number of nodes in the cluster, you must change the `MachineSet` parameter to change the number of nodes. If you just remove o
{product-title-short}

2020-09-09 15:03 UTC, dockerymick commented on manage_cluster/scale.adoc
> +*Remember:* Because {product-title-short} uses Hive for OpenShift to determine the number of nodes in the cluster, you must change the `MachineSet` parameter to change the number of nodes. If you jus
conref for OpenShift

2020-09-09 15:03 UTC, dockerymick commented on troubleshooting/trouble_vm_cluster.adoc
> +== Managed cluster creation fails with unknown certificate authority
This section title is not building out.

2020-09-09 16:21 UTC, cadawson commented on install/plan_capacity.adoc
> +* Creating an OpenShift cluster on VMware vSphere.
Added

2020-09-09 16:30 UTC, cadawson commented on manage_cluster/create.adoc
> +* xref:../manage_cluster/create_azure.adoc#creating-a-cluster-on-vmware-vsphere[Creating a cluster on VMware vSphere] (Requires {ocp} version 4.5, or later)
I wanted them to see it immediately, as I link to this page. Might look better without it.

2020-09-09 16:33 UTC, cadawson commented on manage_cluster/create_vm.adoc
> +You can use the {product-title} console to deploy a {ocp} cluster on VMware vSphere.
The {ocp} resolved to "Red Hat OpenShift Container Platform." For that reason, a is the correct article for this one. Not that I might make the same mistake somewhere else, but...

2020-09-09 16:45 UTC, cadawson commented on manage_cluster/create_vm.adoc
> +You must have the following prerequisites before creating a cluster on vSphere:
Done

2020-09-09 16:47 UTC, cadawson commented on manage_cluster/create_vm.adoc
> +* vSphere provider connection - See xref:../manage_cluster/prov_conn_vm.adoc#prov_conn_vm[Creating a provider connection for VMware vSphere] for more information.
Done

2020-09-09 17:26 UTC, cadawson commented on manage_cluster/create_vm.adoc
> +* The following information for the VMware instance where you are deploying:
This is consistent with the format of the other bullets.

2020-09-09 20:11 UTC, dockerymick commented on manage_cluster/create_vm.adoc
> +* The following information for the VMware instance where you are deploying:
@cadawson ok, how about you say "The following information for the VMWare instance where you deploy to is required:"

2020-09-09 21:05 UTC, cadawson commented on manage_cluster/prov_conn_vm.adoc
> +.. You can download your certificate in the `download.zip` package with the certificate from the https:// vCenter address /certs/download.zip[VMware vCenter].
It is a conditional link. I tried to make that clearer.

2020-09-09 21:05 UTC, cadawson commented on manage_cluster/prov_conn_vm.adoc
> +See https://docs.openshift.com/container-platform/4.3/installing/installing_aws/installing-aws-default.html#ssh-agent-using_installing-aws-default[Generating an SSH private key and adding it to the a
Done

2020-09-09 21:19 UTC, cadawson commented on manage_cluster/scale.adoc
> +*Note:* Because {product-title} uses Hive for OpenShift to determine the number of nodes in the cluster, you must change the `MachineSet` parameter to change the number of nodes. If you just remove o
Done

2020-09-09 21:20 UTC, cadawson commented on manage_cluster/scale.adoc
> +*Remember:* Because {product-title-short} uses Hive for OpenShift to determine the number of nodes in the cluster, you must change the `MachineSet` parameter to change the number of nodes. If you jus
Done

2020-09-11 14:29 UTC, cadawson commented
Made most of peer changes. Want to see the best way to handle troubleshooting.

2020-09-11 14:29 UTC, merged