starting to make changes for cert policy controller
open-cluster-management/rhacm-docs pull request #1192
Opened 2020-09-08 18:21 UTC by dockerymick

https://github.com/open-cluster-management/backlog/issues/4286

2020-09-09 12:14 UTC, gparvin requested changes
See comments added.

2020-09-09 12:14 UTC, gparvin commented on security/cert_policy_ctrl.adoc
> +Certificate policy controller can be used to detect certificates that are close to expiring. Create time durations (hours) that are long, or contain DNS names that fail to match specified patterns to
I think it should be:
... close to expiring, have durations that are too long or contains DNS names that do no match specified patterns.

My notes for id:
Note that it does more than just check for expiration now.  Checking expiration is the default behavior, but you can add the new options to check the other things too.  There are probably lots of other checks we can keep adding in the future too -- so it might not be bad to consider a list format in the introduction paragraphs.

2020-09-09 12:14 UTC, gparvin commented on security/cert_policy_ctrl.adoc
> +When a certificate expires in less than the minimum duration amount of time, the policy becomes non-compliant.
The `minimumDuration` and minimumCADuration` are the only 2 options that deal with expiration now.  The other 4 options add in the extra features:
- checking the lifetime of the certificate
- checking DNS names against patterns

2020-09-09 12:14 UTC, gparvin commented on security/cert_policy_ctrl.adoc
> -The parameter value uses the time duration format from Golang.
We have to have the format and default value.  The format applies to several values so it should be specified in each or marked in some way to make it clear.

2020-09-09 15:06 UTC, dockerymick commented on security/cert_policy_ctrl.adoc
> +Certificate policy controller can be used to detect certificates that are close to expiring. Create time durations (hours) that are long, or contain DNS names that fail to match specified patterns to
@gparvin thanks for clarifying, it wasn't clear that these were multiple task done by the controller. My understanding was that time durations needed to be created, so that the controller can monitor the policy.

2020-09-09 19:15 UTC, dockerymick commented
@gparvin Thanks for the review, I have been able to make a few more edits based on your suggestions

2020-09-09 20:27 UTC, gparvin approved these changes
Note that I added one small comment.  Looks good though.

2020-09-09 20:27 UTC, gparvin commented on security/cert_policy_ctrl.adoc
> +The certificate policy controller is created on your hub cluster. The controller communicates with the local Kubernetes API server to get the list of secrets that contain certificates and determine a
The certificate policy controller is created on your hub cluster.
change to
The certificate policy controller is created on your managed clusters.

2020-09-10 11:09 UTC, bcpswope approved these changes
looks great!

2020-09-10 12:39 UTC, merged