Doc Gatekeeper policy
open-cluster-management/rhacm-docs pull request #1208
Opened 2020-09-10 22:35 UTC by dockerymick

2020-09-10 23:48 UTC, ycao56 commented on security/gatekeeper_ctrl.adoc
> +[#gatekeeper-policy-controller]
can we not call it gatekeeper policy controller? just call it something like `Apply gatekeeper/OPA policy and detect violation`?

2020-09-10 23:51 UTC, ycao56 commented on security/policy_controllers.adoc
> +* xref:../security/gatekeeper_ctrl.adoc#gatekeeper-policy-controller[Gatekeeper policy controller]
I suggest rename this chapter from`Policy controllers` to something else. Otherwise we will be very limit to just talk about policy controllers. The product is involving and we have many ways to integrate with 3rd party policies.

2020-09-10 23:52 UTC, ycao56 commented on security/gatekeeper_ctrl.adoc
> +[#gatekeeper-policy-controller]
Gatekeeper policy integration?

2020-09-10 23:54 UTC, ycao56 commented on security/gatekeeper_ctrl.adoc
> +Gatekeeper policy controller can be used to evaluate Kubernetes resource compliance. You can leverage an Open Policy Agent (OPA) as the policy engine, and use Rego as the policy language. The gatekee
The gatekeeper policy supports the following two use cases/scenarios

2020-09-10 23:55 UTC, ycao56 commented on security/gatekeeper_ctrl.adoc
> +[#gatekeeper-policy-controller]
If we call it integration, then we can talk about how we integration with gatekeeper with RHACM. This is done through configuration policy. Currently I don't see it being mentioned anywhere

2020-09-10 23:56 UTC, ycao56 commented on security/create_gatekeeper.adoc
> +  kubectl apply -f https://raw.githubusercontent.com/open-policy-agent/gatekeeper/master/deploy/gatekeeper.yaml
this command is how you install gatekeeper not gatekeeper policy

2020-09-10 23:58 UTC, ycao56 commented on security/gatekeeper_ctrl.adoc
> +* Admission resource, `policy-gatekeeper-admission` checks when a resource is created or updated to block new misconfigurations.
admission usecase/scenario, user can use gatekeeper/OPA policy to block any new misconfiguration

2020-09-10 23:58 UTC, ycao56 commented on security/gatekeeper_ctrl.adoc
> +* Audit resource, `policy-gatekeeper-audit` periodically checks and evaluates existing resources against the policies that are enforced to detect pre-exisiting miscongfigurations.
audit usecase/scenario, user can use gatekeeper/OPA policy to detect any existing misconfigurations

2020-09-11 00:04 UTC, ycao56 commented
@dockerymick I don't think the way we organize the gatekeeper policy doc is correct. This is not same as other policy controllers we ship. What we did was integration.
So this is how I would like to organized the content.

1. Gatekeeper overview
1. Gatekeeper policy integration
    1. gatekeeper integration prereq
    1. How to use RHACM to apply gatekeeper policy
    1. How to use RHACM to report gatekeeper policy violations
    1. Sample gatekeeper policy

2020-09-15 15:24 UTC, dockerymick commented
@ycao56 thanks for your feedback and clarification! Making a few updates now

2020-09-15 17:55 UTC, dockerymick commented on security/gatekeeper_ctrl.adoc
> +[#gatekeeper-policy-controller]
@ycao56 Sure, I updated the title by removing `controller`. I wanted to maintain a Content doc where we explain components of Gatekeeper and the structure. In the file, I point the user to our task-related doc called **Gatekeeper policy integration** (create_gatekeeper.adoc)

2020-09-15 18:00 UTC, dockerymick commented on security/policy_controllers.adoc
> +* xref:../security/gatekeeper_ctrl.adoc#gatekeeper-policy-controller[Gatekeeper policy controller]
@ycao56  Instead of renaming, can we consider creating a separate doc named Apply third-party policies or Integrate third-party policies? In my current changes, I added the open source community onto the GRC intro doc. I then point the user to the Gatekeeper topic. 

Let me know your thoughts

2020-09-15 18:00 UTC, dockerymick commented on security/gatekeeper_ctrl.adoc
> +Gatekeeper policy controller can be used to evaluate Kubernetes resource compliance. You can leverage an Open Policy Agent (OPA) as the policy engine, and use Rego as the policy language. The gatekee
Updated

2020-09-15 18:01 UTC, dockerymick commented on security/create_gatekeeper.adoc
> +  kubectl apply -f https://raw.githubusercontent.com/open-policy-agent/gatekeeper/master/deploy/gatekeeper.yaml
Is it ok to assume that this file might be similar to the blog? https://www.openshift.com/blog/how-to-integrate-open-policy-agent-with-red-hat-advanced-cluster-management-for-kubernetes-policy-framework

2020-09-15 18:01 UTC, dockerymick commented on security/gatekeeper_ctrl.adoc
> +* Admission resource, `policy-gatekeeper-admission` checks when a resource is created or updated to block new misconfigurations.
updated

2020-09-15 18:02 UTC, ycao56 commented on security/iam_policy_ctrl.adoc
> +The name for identifying the policy resource. Set to `iam-grc-policy`.
is this an oversight? the name can be anything. it doesn't have to be `iam-grc-policy`

2020-09-15 18:03 UTC, dockerymick commented
@ycao56 I suggest that we add `How to use RHACM to apply gatekeeper policy` and 
`How to use RHACM to report gatekeeper policy violations` sections onto the Gatekeeper policy integration file since they are task-related.

2020-09-15 18:07 UTC, ycao56 commented on security/policy_controllers.adoc
> +* xref:../security/gatekeeper_ctrl.adoc#gatekeeper-policy-controller[Gatekeeper policy controller]
consider the importance of gatekeeper integration, I still think it needs to be highlighted. Currently the link is inside `open source comunnity`, it's very hard to find. You can create a sibling called 3rd party integration and put gatekeeper there

2020-09-15 18:08 UTC, ycao56 commented on security/create_gatekeeper.adoc
> +  kubectl apply -f https://raw.githubusercontent.com/open-policy-agent/gatekeeper/master/deploy/gatekeeper.yaml
no

2020-09-15 18:08 UTC, ycao56 commented on security/create_gatekeeper.adoc
> +  kubectl apply -f https://raw.githubusercontent.com/open-policy-agent/gatekeeper/master/deploy/gatekeeper.yaml
maybe we should just point to gatekeeper doc for user to deploy gatekeeper https://github.com/open-policy-agent/gatekeeper#installation-instructions

2020-09-15 18:24 UTC, dockerymick commented on security/policy_controllers.adoc
> +* xref:../security/gatekeeper_ctrl.adoc#gatekeeper-policy-controller[Gatekeeper policy controller]
Gatekeeper policy will be seen first in What's New section. I will create the new file for third party integration. Can you confirm that Gatekeeper and ETCD policies should be added to the soon to be created doc, Integrate third-party policies, for 2.1

2020-09-15 18:25 UTC, dockerymick commented on security/create_gatekeeper.adoc
> +  kubectl apply -f https://raw.githubusercontent.com/open-policy-agent/gatekeeper/master/deploy/gatekeeper.yaml
@ycao56 I think that is fair, and then we add instructions to apply with RHACM

2020-09-15 18:26 UTC, dockerymick commented on security/iam_policy_ctrl.adoc
> +The name for identifying the policy resource. Set to `iam-grc-policy`.
yea it was, thanks for clarifying. i will update that file

2020-09-15 19:18 UTC, ycao56 commented on security/policy_controllers.adoc
> +* xref:../security/gatekeeper_ctrl.adoc#gatekeeper-policy-controller[Gatekeeper policy controller]
Gatekeeper is third party. Etcd policy is not. it is just a configuration policy. you can add it to configuration policy controller part.

2020-09-17 19:25 UTC, dockerymick commented
@ycao56 made some more progress on the draft.

2020-09-21 14:17 UTC, ycao56 commented on security/create_gatekeeper.adoc
> +// can users create the gatekeeper policy from the UI? Will it be an option in the action list when the user creates the policy?
no

2020-09-21 14:17 UTC, ycao56 commented on security/create_gatekeeper.adoc
> +    - objectDefinition:
this part and below is for admission. can you move it to separate section as a sibling of `=== Creating a gatekeeper policy for audit`?

2020-09-21 14:20 UTC, ycao56 commented on security/gatekeeper_policy.adoc
> +The name for identifying the policy resource. Set to `policy-gatekeeper`.
can be any name. `policy-gatekeeper` is just an example

2020-09-21 14:22 UTC, ycao56 commented on security/grc_intro.adoc
> +* *Policy store*: Use Kuberneters ETCD to store policies as CustomResourceDefinition (CRD) objects.
I don't think we need to highlight this. This would only confuse user. Can you remove it?

2020-09-21 14:23 UTC, ycao56 approved these changes
looks good with some minor comments

2020-09-22 21:24 UTC, cadawson requested changes
Some suggestions added. You are making me question my thoughts on that comma thing. You will know what I mean.  Thanks!

2020-09-22 21:24 UTC, cadawson commented on security/create_gatekeeper.adoc
> +You can create a YAML file for your gatekeeper policy from the command line interface (CLI). Use the {product-title} configuration policy to propagate the gatekeeper policy from the hub cluster to th
Should Gatekeeper be capitalized throughout?

2020-09-22 21:24 UTC, cadawson commented on security/create_gatekeeper.adoc
> +Use the {produtc-title-short} configuration policy to create a gatekeeper policy that looks for events that are generated by the gatekeeper admission webhook.
product-title-short

2020-09-22 21:24 UTC, cadawson commented on security/create_gatekeeper.adoc
> +Use the product configuration policy to create a gatekeeper policy that periodically checks, and evaluates existing resources against the gatekeeper policies. {product-title-short} configuration poli
checks and evaluates

2020-09-22 21:24 UTC, cadawson commented on security/create_gatekeeper.adoc
> +For more information about integrating third-party policies with the product, see xref:../security/third_party_policy.adoc[Integrating third-party policies].
I think you need: xref:../security/third_party_policy.adoc#integrating-third-party-policies[Integrating third-party policies]

2020-09-22 21:24 UTC, cadawson commented on security/gatekeeper_policy.adoc
> +The gatekeeper policy is created as a Kubernetes configuration policy. Gatekeeper policy include constraint templates (`ConstraintTemplates`), which are used to define specific constraints for your c
policies include, or policy includes

2020-09-22 21:24 UTC, cadawson commented on security/gatekeeper_policy.adoc
> +The gatekeeper policy is created as a Kubernetes configuration policy. Gatekeeper policy include constraint templates (`ConstraintTemplates`), which are used to define specific constraints for your c
I am lost on the `ConstraintTemplates` communicate... sentence.  I think there might be something too little or too much there.

2020-09-22 21:24 UTC, cadawson commented on security/gatekeeper_policy.adoc
> +.Parameter table
Would like to see how this renders. I would think the last sentence should be in a cell, but maybe there is something cool going on here.

2020-09-22 21:24 UTC, cadawson commented on security/gatekeeper_policy.adoc
> +The name for identifying the policy resource.
The name that identifies the policy resource?

2020-09-22 21:24 UTC, cadawson commented on security/gatekeeper_policy.adoc
> +| A security control category represent specific requirements for one or more standards.
represents?

2020-09-22 21:24 UTC, cadawson commented on security/gatekeeper_policy.adoc
> +| spec.severity
Noticed these are not on new lines after Required and Optional anymore. Does that matter?

2020-09-22 21:24 UTC, cadawson commented on security/gatekeeper_policy.adoc
> +&#8226; `mustonlyhave`: Indicates that an object must exist with the exact name and relevant fields.
Is the ASCII character number here going to cause problems?

2020-09-22 21:24 UTC, cadawson commented on security/gatekeeper_policy.adoc
> +&#8226; `mustnothave`: Indicated that an object with the same name or labels cannot exist and need to be deleted, regardless of the specification or rules.
I think I see what that is: a list within a table cell?

2020-09-22 21:24 UTC, cadawson commented on security/gatekeeper_policy.adoc
> +Refer to xref:../security/grc_intro.adoc[Governance and risk] for more topics on the security framework.
I think you need: xref:../security/grc_intro.adoc#governance-and-risk[Governance and risk]

2020-09-22 21:24 UTC, cadawson commented on security/grc_intro.adoc
> +You can create, view, and manage your security policies from the _Policies_ page. The following details are provided in the tablelist of violations: description, resources, severity, cluster, standar
I don't think tablelist is a word, is it?

2020-09-22 21:24 UTC, cadawson commented on security/grc_intro.adoc
> +You can filter the violation table view by policies or cluster violations. Customize your _Summary_ view by filtering the violations by categories or standards, collapse the summary to see less infor
You can customize your _Summary_ view by filtering the violations by categories or standards, collapse the summary to see less information, and search for policies. ?

2020-09-22 21:24 UTC, cadawson commented on security/grc_intro.adoc
> +** When a policy is propagated to a managed cluster, the replicated policy is named as `namespaceName.policyName`. When you create a policy, make sure that the length of the `namespaceName.policyName
is named as > is named

2020-09-22 21:24 UTC, cadawson commented on security/grc_intro.adoc
> +* *Policy-based governance framework:* Support policy creation and deployment to various managed clusters based on attributes associated with clusters, such as a geographical region. See the https://
policies and instructions

2020-09-22 21:24 UTC, cadawson commented on security/grc_intro.adoc
> +* *Policy controller*: Evaluates one or more policies on the managed cluster against your specified control, and generates Kubernetes events for violations. Violations are propagated to the hub clust
control and generates

2020-09-22 21:24 UTC, cadawson commented on security/grc_intro.adoc
> +* *Open source community*: {product-title-short} policy framework, policy controllers, and policies are apart of the `open-cluster-management` repository. Learn how to integrate third-party policies
are a part of the

2020-09-22 21:24 UTC, cadawson commented on security/grc_intro.adoc
> +* *Open source community*: {product-title-short} policy framework, policy controllers, and policies are apart of the `open-cluster-management` repository. Learn how to integrate third-party policies
xref:../security/third_party_policy.adoc#integrate-third-party-policies[Integrate third-party policies]

2020-09-22 21:24 UTC, cadawson commented on security/iam_policy_ctrl.adoc
> +View the following example of an IAM policy and review the parameters in the YAML table:
Should we spell out IAM on the first occurrence?

2020-09-22 21:24 UTC, cadawson commented on security/third_party_policy.adoc
> +Integrate third-party policies to create custom annotations within the policy templates to specify one or more compliance standard, control category, and control.
specify one or more compliance standards, control categories, and controls?

2020-09-23 20:33 UTC, dockerymick commented on security/create_gatekeeper.adoc
> +You can create a YAML file for your gatekeeper policy from the command line interface (CLI). Use the {product-title} configuration policy to propagate the gatekeeper policy from the hub cluster to th
@cadawson I capitalize Gatekeeper, only when I  mention the controller from OPA. When I mention the policy it is lowercase

2020-09-23 20:41 UTC, dockerymick commented on security/create_gatekeeper.adoc
> +Use the {produtc-title-short} configuration policy to create a gatekeeper policy that looks for events that are generated by the gatekeeper admission webhook.
Great catch

2020-09-23 20:42 UTC, dockerymick commented on security/create_gatekeeper.adoc
> +Use the product configuration policy to create a gatekeeper policy that periodically checks, and evaluates existing resources against the gatekeeper policies. {product-title-short} configuration poli
done

2020-09-23 20:43 UTC, dockerymick commented on security/create_gatekeeper.adoc
> +For more information about integrating third-party policies with the product, see xref:../security/third_party_policy.adoc[Integrating third-party policies].
added the anchor

2020-09-23 20:52 UTC, dockerymick commented on security/gatekeeper_policy.adoc
> +The gatekeeper policy is created as a Kubernetes configuration policy. Gatekeeper policy include constraint templates (`ConstraintTemplates`), which are used to define specific constraints for your c
I updated the sentence to the following: `ConstraintTemplates` informs which constraint template to enforce to the Gatekeeper.

2020-09-23 20:54 UTC, dockerymick commented on security/gatekeeper_policy.adoc
> +The name for identifying the policy resource.
Policies are resources. I can see how it is confusing tho. I will change this to "the name for identifying the policy."

2020-09-23 21:10 UTC, dockerymick commented on security/gatekeeper_policy.adoc
> +| spec.severity
no it doesn't matter, but i will move to the same line so that it is easier to read

2020-09-23 21:11 UTC, dockerymick commented on security/gatekeeper_policy.adoc
> +&#8226; `mustonlyhave`: Indicates that an object must exist with the exact name and relevant fields.
no this is the bullet number for the bullet point

2020-09-23 21:12 UTC, dockerymick commented on security/gatekeeper_policy.adoc
> +&#8226; `mustnothave`: Indicated that an object with the same name or labels cannot exist and need to be deleted, regardless of the specification or rules.
yes, this is a bulleted list

2020-09-23 21:14 UTC, dockerymick commented on security/grc_intro.adoc
> +You can create, view, and manage your security policies from the _Policies_ page. The following details are provided in the tablelist of violations: description, resources, severity, cluster, standar
it is missing a space

2020-09-23 21:29 UTC, dockerymick commented on security/iam_policy_ctrl.adoc
> +View the following example of an IAM policy and review the parameters in the YAML table:
I did on line 4. IAM is really long

2020-09-23 21:29 UTC, merged