open-cluster-management/backlog#5117 -- new topic on console
open-cluster-management/rhacm-docs pull request #1239
Opened 2020-09-18 03:17 UTC by bcpswope

2020-09-18 13:03 UTC, birsanv requested changes

2020-09-18 13:03 UTC, birsanv commented on manage_applications/app_console.adoc
> +* Add and edit channels, subscriptions, placement rules, and applications.
We don't have support in 2.1 to create channel, subs, PR by themself, they all get created under the cover when you create an application using the new dialog.
You can only view, edit channel, subs, PR ( UI to be done in sprint 4 ) . The pipeline is replaced by tables , with actions to view channel, subs, PR 

I would rephrase : Create and edit applications. Use the _Advanced configuration_ to view or edit channel, subs, PR , if you have the right access.

2020-09-18 13:03 UTC, birsanv commented on manage_applications/app_console.adoc
> +* Access a topology view that encompasses the new application resource definitions, including channels, subscriptions, placement rules, and Ansible Tower jobs.
I am not sure if we still want to talk about channels in the topology context. 
I would refer to Channel on when discussing the _Advanced configuration_ tab ( here also goes the notion on Subs, PR )

Proposed change:
Access a topology view that encompasses the new application resource definitions, including resource repositories, subscriptions, placement rules, and deployed resources including any optional pre and post deployment hooks using Ansible Tower tasks.

2020-09-18 13:03 UTC, birsanv commented on manage_applications/app_console.adoc
> +* Visualize deployed applications across your clusters, including any associated channels and subscriptions.
Change : ( I would not refer to channels in the single app topo context, just Advanced configuration tab )

Visualize deployed applications across your clusters, including any associated resource repositories subscriptions and placement configurations.

2020-09-18 13:03 UTC, birsanv commented on manage_applications/app_console.adoc
> +* The remote and local clusters where resources are deployed through a subscription
Then _number of_ remote and local clusters where resources are deployed through a subscription

2020-09-18 13:03 UTC, birsanv commented on manage_applications/app_console.adoc
> +* The date when the application was created
Date is the last column

2020-09-18 13:03 UTC, birsanv commented on manage_applications/app_console.adoc
> +* A Time window constraint, if any were added
You are missing the Repositories column: The list of repositories where the definitions for the resource deployed by the application where located.

2020-09-18 13:03 UTC, birsanv commented on manage_applications/app_console.adoc
> +* More actions, such as *Delete application*.
actions : Edit, View Search app 
Actions available ( active ) if the user can execute them

2020-09-18 13:03 UTC, birsanv commented on manage_applications/app_console.adoc
> +The topology provides a visual representation of all the applications and resources within a project, their build status, and the components and services associated with them.
The topology provides a visual representation of the application that was selected including the resources deployed by this application on target clusters.

2020-09-18 13:03 UTC, birsanv commented on manage_applications/app_console.adoc
> +* View the details for a pod by clicking on the nodes to open the properties view.
Remove this, pod is no longer showing

2020-09-18 13:03 UTC, birsanv commented on manage_applications/app_console.adoc
> +* View the details for a pod by clicking on the nodes to open the properties view.
In general : View the deployment details for any resource deployed by this application by clicking on the resource node to open the properties view

2020-09-18 13:03 UTC, birsanv commented on manage_applications/app_console.adoc
> +* View cluster CPU and memory.
From the cluster node , on the properties dialog view the CPU ..

2020-09-18 13:03 UTC, birsanv commented on manage_applications/app_console.adoc
> +*  View a successful Ansible Tower deployment. Additionally, you can see errors if your Ansible Tower deployment is not successful.
If using Ansible tasks as prehook or posthook for the deployed application, you see these tasks in the application topology.
Click on the .. and you can see the details about the Ansible task deployment, including Ansible Tower Job URL and template name.

2020-09-18 13:03 UTC, birsanv commented on manage_applications/app_console.adoc
> +* Click *Launch resource in Search* to search for related clusters.
Click *Launch resource in Search* to search for related resources.

2020-09-18 13:03 UTC, birsanv commented on manage_applications/app_console.adoc
> +If needed, you can also expand *Actions* menu in the search results for a resource to select to delete that resource.
Hm.. if the delete action is available, and the user has right access .. this should go under search doc

2020-09-18 13:03 UTC, birsanv commented on manage_applications/app_console.adoc
> +Click the resource name in the search results to open the YAML editor. Any changes that you save are applied to the resource immediately.
Not sure if we want to document this here , this is Search territory.

We would document that 
- you can click on _View Resource YAML_ from the topology property dialog on a resource and this takes you to the Search editor.
- you can click on _Launch resource in Search_ from the topology property dialog on a resource and takes you the Search page

2020-09-18 13:03 UTC, birsanv commented on manage_applications/app_console.adoc
> +Click the *Advanced configuration* to vbiew the summary of resources for all applications on different cards. These resource summary cards show the following information about your applications and r
Remove this, cards no longer show under Advanced configuration

2020-09-18 13:03 UTC, birsanv commented on manage_applications/app_console.adoc
> +Click the *Advanced configuration* to vbiew the summary of resources for all applications on different cards. These resource summary cards show the following information about your applications and r
This tab is changed completely, it shows Channel, Sub, PR tables

https://marvelapp.com/prototype/24ib00hg/screen/71747880

2020-09-28 15:29 UTC, bcpswope commented on manage_applications/app_console.adoc
> +If needed, you can also expand *Actions* menu in the search results for a resource to select to delete that resource.
it's in the search area and I changed it a bit

2020-09-28 17:31 UTC, birsanv approved these changes

2020-09-29 00:10 UTC, merged