open-cluster-management/backlog#4737 ts secret
open-cluster-management/rhacm-docs pull request #1250
Opened 2020-09-21 16:12 UTC by cadawson

2020-09-21 16:16 UTC, cadawson commented
@TheRealHaoLiu : Here is a draft of the troubleshooting topic for 4731, but I just saw that this is just closed. Is this not necessary now? Thanks!

2020-09-28 20:56 UTC, cadawson commented
Hi Han. Hao suggested that I ask you to take a look at this PR. Thanks!

2020-09-28 21:03 UTC, hanqiuzh commented on troubleshooting/trouble_import_fail_secret.adoc
> +. Run the following command to change to your project namespace:
feel `project namespace` is obscure, here is saying the ACM namespace. shall we say something like `ACM install namespace (default open-cluster-management)`?

2020-09-28 21:10 UTC, hanqiuzh requested changes

2020-09-28 21:10 UTC, hanqiuzh commented on troubleshooting/trouble_import_fail_secret.adoc
> +. Run the following command to determine if the `managedcluster-import-controller` is running:
the command is not checking if `managedcluster-import-controller` is running. 

The command is checking if `managedcluster-import-controller` has the required permission.

2020-09-28 21:10 UTC, hanqiuzh commented on troubleshooting/trouble_import_fail_secret.adoc
> +Replace _name_ with the name of the pod that you were trying to import.
this  line "Replace _name_ with the name of the pod that you were trying to import."  is not needed as the command can work without any name replaces

2020-09-28 21:13 UTC, hanqiuzh commented on troubleshooting/trouble_import_fail_secret.adoc
> +After an upgrade, your cluster import in the {product-title} console might fail with the following message:
shall we specify it's from 2.0.0 to 2.0.1, this issue only applies for 2.0.1

2020-09-28 21:14 UTC, hanqiuzh commented
@cadawson  hi, left some comment 👍

2020-09-30 16:50 UTC, hanqiuzh approved these changes

2020-09-30 16:51 UTC, cadawson commented on troubleshooting/trouble_import_fail_secret.adoc
> +. Run the following command to change to your project namespace:
Clarified

2020-09-30 16:52 UTC, cadawson commented on troubleshooting/trouble_import_fail_secret.adoc
> +. Run the following command to determine if the `managedcluster-import-controller` is running:
Fixed

2020-09-30 16:52 UTC, cadawson commented on troubleshooting/trouble_import_fail_secret.adoc
> +Replace _name_ with the name of the pod that you were trying to import.
Removed

2020-09-30 16:52 UTC, hanqiuzh commented on troubleshooting/trouble_import_fail_secret.adoc
> +After an upgrade, your cluster import in the {product-title} console might fail with the following message:
I think it's ok to keep it as it. For upgrade it has to be >2.0.0 😂

2020-09-30 16:52 UTC, hanqiuzh commented
Looks good to me

2020-09-30 16:54 UTC, hanqiuzh approved these changes

2020-09-30 16:55 UTC, cadawson commented on troubleshooting/trouble_import_fail_secret.adoc
> +After an upgrade, your cluster import in the {product-title} console might fail with the following message:
Added versions

2020-09-30 16:55 UTC, merged