open-cluster-management/backlog#4856 prep peer
open-cluster-management/rhacm-docs pull request #1287
Opened 2020-09-28 21:35 UTC by cadawson

2020-09-28 21:37 UTC, cadawson commented
Hi @dockerymick . Can you peer review this when you have a chance? It is new, and a long file, so you probably want to leave it until morning. Thank you!

2020-09-30 14:32 UTC, dockerymick requested changes
Thanks for your patience Chris!

2020-09-30 14:32 UTC, dockerymick commented on manage_cluster/cincinnati.adoc
>  . Create a ConfigMap in the `openshift-config` namespace.
Update the verbs: 

- Monitors -> Monitor
- Identifies -> Identify
- Notifies -> Notify 

Also add a period at the end of the statements. 


* I usually only bold Prereqs title instead of a section title, can we discuss this in our meeting today. For the record, i think making Prereqs a section header would be helpful so that users do not miss it.

2020-09-30 14:32 UTC, dockerymick commented on manage_cluster/cincinnati.adoc
>  . Create a ConfigMap in the `openshift-config` namespace.
In the first bullet of the prereqs remove "for details about how to configure restricted OLM". I would update it to "For more details, see ..."

The **Tip** is currently on the same line with the bullet. If you want it on a new line, add a line break between the last sentence and tip.

2020-09-30 14:32 UTC, dockerymick commented on manage_cluster/cincinnati.adoc
> +. Add your CA certificate under the key `cincinnati-registry`. {cincinnati-short} uses this setting to locate your certificate:
{cincinnati-short} uses the following setting to locate your certificate.

2020-09-30 14:32 UTC, dockerymick commented on manage_cluster/cincinnati.adoc
> +. Add your CA certificate under the key `cincinnati-registry`. {cincinnati-short} uses this setting to locate your certificate:
API to set the additionalTrustedCA field to the name of the ConfigMap that you created.

2020-09-30 14:32 UTC, dockerymick commented on manage_cluster/cincinnati.adoc
> +. Add your CA certificate under the key `cincinnati-registry`. {cincinnati-short} uses this setting to locate your certificate:
"The Cincinnati Operator will watch the image.config.openshift.io API and the ConfigMap you created in the openshift-config namespace for changes, then restart the deployment if the CA cert has changed."

Let's  remove "will" because it is future tense. Change "will watch" to "watches"


How do users restart the deployment? 

Should `init` be in codeblocks here? Or should there be a space in between (in it). "Create a file that contains the information for your graph data init."


In the **deploy the operator** section, bold `Tip`. 

Change "The operator should be in the running state." TO "Verify that the operator is in the running state."

2020-09-30 14:32 UTC, dockerymick commented on manage_cluster/cincinnati.adoc
> +. Add your CA certificate under the key `cincinnati-registry`. {cincinnati-short} uses this setting to locate your certificate:
"this instance is located where the images for the cluster upgrades are mirrored and made available to the disconnected managed cluster. Complete the following steps to deploy the instance:"

2020-09-30 14:32 UTC, dockerymick commented on manage_cluster/cincinnati.adoc
> +. Add your CA certificate under the key `cincinnati-registry`. {cincinnati-short} uses this setting to locate your certificate:
For the Deploy the service instance update the following statement: 

Paste the contents from your `Cinncinati` instance. Your YAML instance might resemble the following manifest:

2020-09-30 14:32 UTC, dockerymick commented on manage_cluster/cincinnati.adoc
> +. Add your CA certificate under the key `cincinnati-registry`. {cincinnati-short} uses this setting to locate your certificate:
update Governance and Risk to Govern risk


In the Deploy a policy to change the managed cluster parameter section update the following: "The returned content should look similar to the following content" TO "The returned content might resemble the following content:"

2020-09-30 14:32 UTC, dockerymick commented on manage_cluster/cincinnati.adoc
> +. Add your CA certificate under the key `cincinnati-registry`. {cincinnati-short} uses this setting to locate your certificate:
The results should look similar to the following content:

Remove should . Maybe you can say "Verify that the results resemble the following content"


After configuring the disconnnected registry, {product-title-short} and {cincinnati-short} use the disconnected registry to determine if **updates** are available.

Change update to upgrade

Add the following statement in the Upgrading the cluster section : "Complete the following steps to upgrade:

2020-10-01 18:24 UTC, cadawson commented on manage_cluster/cincinnati.adoc
>  . Create a ConfigMap in the `openshift-config` namespace.
My thought here is to make sure they know what the instructions are for (not deploying a cluster, but setting it up as a restricted network).

I was going to have the tip on the same line, but maybe it would be better not to.

2020-10-01 19:52 UTC, cadawson commented
Applied changes. Need to make some structure changes, so bypassing the re-review.

2020-10-01 19:52 UTC, merged