general rbac updates for 2.1
open-cluster-management/rhacm-docs pull request #1305
Opened 2020-10-01 20:58 UTC by ckandag

2020-10-05 20:47 UTC, dockerymick commented
Also referencing this issue: https://github.com/open-cluster-management/backlog/issues/4971

2020-10-05 21:10 UTC, ckandag reviewed
@dockerymick

2020-10-05 21:10 UTC, ckandag commented on security/rbac.adoc
> +* To limit the user access for `managedcluster X`, the following custom resources must be created:
I dont think this goes here ,  and previous bullets are examples of actual steps to perform a  task ,  while this is info about the new "ClusterSet"  feature. 

I suggest instead to add a line after the examples section,  to indicate that RHACM  allows user to  work with ClusterSets  and point a link to that doc page

2020-10-05 21:43 UTC, dockerymick commented on security/rbac.adoc
> +* To limit the user access for `managedcluster X`, the following custom resources must be created:
Updated the rbac doc @ckandag

2020-10-06 12:15 UTC, cadawson requested changes
A few minor changes requested. Feel free to push it when those are merged, or I can take a look again. Up to you. Thanks!

2020-10-06 12:15 UTC, cadawson commented on manage_cluster/custom_resource.adoc
> +Create a ManagedClusterSet resource to limit the user access on managed clusters. You must also create a ManagedClusterSetBinding resource to bind a ManagedClusterSet resource to a namespace.
You can create a  ManagedClusterSet resource...

2020-10-06 12:15 UTC, cadawson commented on manage_cluster/intro.adoc
> +* xref:../manage_cluster/custom_resource.adoc[Creating a ManagedClusterSet resource]
I think you need #creating-a-managedclusterset-resource.

2020-10-06 12:15 UTC, cadawson commented on release_notes/whats_new.adoc
> +* You can now group clusters and give user access to the group by creating ManagedClusterSet resources.  For more information, see link:../managed_cluster/custom_resource.adoc[Creating a ManagedClust
I think you need #creating-a-managedclusterset-resource.

2020-10-06 12:15 UTC, cadawson commented on security/rbac.adoc
>  View the following sections for  details of supported RBAC by component:
Extra space after "for".

2020-10-06 12:15 UTC, cadawson commented on security/rbac.adoc
> +| An user with cluster-wide binding to the `cluster-admin` role is an {ocp-short} super user, who has all access.
I typically use "a" before "user" because the "u" sounds like a "y". I see why you used "an", as I would say "an umbrella." I looked it up just now, and using the "a user" is more widely used. Please change these to "a user" for consistency. Thanks!

2020-10-06 12:15 UTC, cadawson commented on security/rbac.adoc
>  | An user with the `subscription-admin` role can create Git subscriptions that deploy resources to multiple namespaces. The resources are specified in Kubernetes resource YAMLs in the subscribed Git
YAML files

2020-10-06 12:15 UTC, cadawson commented on security/rbac.adoc
> +Learn about creating ManagedClusterSet resources to group clusters, see link:../managed_cluster/custom_resource.adoc[Creating ManagedClusterSets].
I think you need #creating-a-managedclusterset-resource.

2020-10-06 12:15 UTC, cadawson commented on security/rbac.adoc
> +To perform Application lifecycle tasks, users must have access to the namespace where the application is created and the `managedcluster` namespace. For example, the required access to create applica
To perform Application lifecycle tasks, users must have access to the namespace where the application is created and to the `managedcluster` namespace.

2020-10-06 12:15 UTC, cadawson commented on security/rbac.adoc
> +To perform Governance lifecylce operations, users must have access to the namespace where the policy is created, along with access to the `managedcluster` namespace where the policy is applied.
lifecycle

2020-10-07 14:28 UTC, merged