open-cluster-management/backlog#5745 Opt pull sec
open-cluster-management/rhacm-docs pull request #1350
Opened 2020-10-12 20:58 UTC by cadawson

2020-10-14 22:30 UTC, cadawson commented
Hi @joeg-pro . Can you take a quick look at this one when you can? The other one is the same for 2.1. Let me know if you have changes.  Thanks!

2020-10-15 17:44 UTC, joeg-pro requested changes
Please take a look at my comment on wording.

2020-10-15 17:44 UTC, joeg-pro commented on install/install_connected.adoc
> +. If you plan to import Kubernetes clusters that were not created by {ocp-short} or {product-title-short}, generate a pull secret to access the entitled content from the distribution registry. Pull s
Picky comments:
(1) Phrasing like "create a pull secret" is not really precise description of what the user needs to do because "pull secret" is not a kind of Kubernetes resource.  What the user has to do is to create a (Kubernetes) Secret that contains (as its secret stuff) the OCP 4 install pull secret they got from the Red Hat Open Cluster Manager web site they visited to get info and creds (OCP 4 install pull secret)  to allow them to install OCP 4 clusters.
(2) In the new wording, the word "generate" worries me because it seems like we are telling the user to go get a new pull secret.  That's not the case, per (1) we are telling them they need to create a Secret resource that contains the OCP 4 install pull secret they already have.

2020-10-20 18:31 UTC, cadawson commented
Made some updates from your comments, @joeg-pro . Can you see if this is better? Thanks!

2020-10-21 13:24 UTC, joeg-pro commented on install/install_connected.adoc
> +The secret requirements for {ocp-short} clusters are automatically resolved by {ocp-short} and {product-title-short}, so you do not have to generate the secret if you are not importing other types of
maybe "...create the secret..." rather than "...generate the secret..." in this sentence.

2020-10-21 13:24 UTC, joeg-pro commented on install/install_connected.adoc
> + .. Run the following command to compile your secret:
I would suggest "...to create your secret:" rather than "compile".

2020-10-21 13:25 UTC, joeg-pro commented on install/install_connected.adoc
> +. If you plan to import Kubernetes clusters that were not created by {ocp-short} or {product-title-short}, generate a secret that contains your {ocp-short} pull secret to access the entitled content
Maybe "...have to create the secret..." rather than "...have to generate the secret..."

2020-10-21 13:53 UTC, cadawson commented on install/install_connected.adoc
> +The secret requirements for {ocp-short} clusters are automatically resolved by {ocp-short} and {product-title-short}, so you do not have to generate the secret if you are not importing other types of
Done

2020-10-21 13:53 UTC, cadawson commented on install/install_connected.adoc
> + .. Run the following command to compile your secret:
Done

2020-10-21 13:53 UTC, cadawson commented on install/install_connected.adoc
> +. If you plan to import Kubernetes clusters that were not created by {ocp-short} or {product-title-short}, generate a secret that contains your {ocp-short} pull secret to access the entitled content
Done

2020-10-21 16:38 UTC, merged