Observability updates
open-cluster-management/rhacm-docs pull request #1383
Opened 2020-10-20 16:26 UTC by dockerymick

Making lots of updates to the install topic. Also working on adding the tasks to customize the install

2020-10-22 04:07 UTC, clyang82 requested changes

2020-10-22 04:07 UTC, clyang82 commented on observability/manage_observe.adoc
> +
> By default, the alert rules are defined in the `thanos-rule-default-rules` configuration map in the `open-cluster-management-observability` namespace. You can create multple rules in the configuration

Suggest to:
By default, the OOTB alert rules are defined in the `thanos-ruler-default-rules` ConfigMap in the `open-cluster-management-observability` namespace. You can create the `thanos-ruler-custom-rules` ConfigMap in the `open-cluster-management-observability` namespace to define multiple rules.

2020-10-22 04:07 UTC, clyang82 commented on observability/manage_observe.adoc
> +. You can access the Grafana dashboard from the _Clusters_ page. From the navigation menu, select *Automate infrastructure* > *Clusters* > *Grafana link*.
Suggest to mixin the above 2 items. for example:
From the navigation menu, select *Observe environments* > *Overview* > *Grafana link* (You can also access the Grafana dashboard from the _Clusters_ page. From the navigation menu, select *Automate infrastructure* > *Clusters* > *Grafana link*)

BTW, How about just use `Grafana` instead of `Grafana link`?

2020-10-22 04:07 UTC, clyang82 commented on observability/manage_observe.adoc
> +When you disable observability, the `multicluster-observability-operator` continues to run on the managed cluster, while the `metrics-collector` deployment is scaledd to zero. When a managed cluster
s/scaledd/scaled

2020-10-22 04:07 UTC, clyang82 commented on observability/observability_install.adoc
> +- You must install Grafana version 6.0 or later. For more information, see https://grafana.com/docs/grafana/latest/installation/[Install Grafana].
no need to install Grafana in Prerequisites

2020-10-22 04:07 UTC, clyang82 commented on observability/observability_install.adoc
> +- You must have {product-title} hub cluster installed as a managed cluster to use the observability feature.
That is not required. Suggest just mention ACM installed required.
The order I think is:
1. OCP installed
2. ACM installed.
3. Create Object storage.

2020-10-22 04:07 UTC, clyang82 commented on observability/observability_install.adoc
> +Enable the observability service by creating a `multicluster-observability` CustomResourceDefinition (CRD). Complete the following steps to enable the observability service:
s/`multicluster-observability` CustomResourceDefinition (CRD)/MultiClusterObservability CustomResourceDefinition instance

2020-10-22 04:07 UTC, clyang82 commented on observability/observability_install.adoc
> ++
remove the check for `observability-addons`

2020-10-22 04:07 UTC, clyang82 commented on observability/observability_install.adoc
>  ----
> Generate a pull-secret for the `observability` namespace by running the following command:

Generate a pull-secret for the `open-cluster-management-observability` namespace by running the following command

2020-10-22 04:07 UTC, clyang82 commented on observability/observability_install.adoc
> +. Create a `MultiClusterObservability` CRD by running the following command:
s/`MultiClusterObservability` CRD/`MultiClusterObservability` instance or resource

2020-10-22 04:07 UTC, clyang82 commented on observability/observability_install.adoc
> ++
Not CRD, it is CR. so just use instance or resource here

2020-10-22 04:07 UTC, clyang82 commented on observability/observability_install.adoc
>  kubectl create -f mco_cr.yaml
remove `kubectl create -f mco_cr.yaml` . create/apply do the same thing.

2020-10-22 04:07 UTC, clyang82 commented on observability/observability_install.adoc
> +After you install observability, all of the pods in your `open-cluster-management-observability` namespace for your object storage, Grafana, and AlertManager are automatically installed. All managed
s/your object storage/Thanos

2020-10-22 04:07 UTC, clyang82 commented on observability/observability_install.adoc
> +. Delete the `multicluster-observability-operator` resource instance with the following command:
s/multicluster-observability-operator/MultiClusterObservability

2020-10-22 04:07 UTC, clyang82 commented on observability/observability_install.adoc
> +kubectl delete multicluster-observability-operator observability
s/multicluster-observability-operator/MultiClusterObservability

2020-10-22 04:07 UTC, clyang82 commented on observability/observe_intro.adoc
> +The observability service requires data storage for the time series data. You must configure your object store to enable the observability service. {product-title-short} supports different types of s
We did not have tested the `Google Cloud Storage` and `Azure storage`. Suggest to just mention the `Amazon S3` only here. for example:
such as link:https://docs.aws.amazon.com/whitepapers/latest/aws-overview/storage-services.html[Amazon S3]. for more options, refer to link:https://thanos.io/v0.2/thanos/storage.md/[Thanos].

2020-10-22 04:07 UTC, clyang82 commented on observability/observability_install.adoc
> +When you delete the resource, the `multicluster-observability-operator` that run on {product-title-short} hub cluster, and the `multicluster-observability-addon` that run on all managed clusters are
> When you delete the resource, the `multicluster-observability-operator` that run on {product-title-short} hub cluster, and the `multicluster-observability-addon` that run on all managed clusters are removed. 

Suggestion:
When you delete the resource, the pods are in `open-cluster-management-observability` namespace on {product-title-short} hub cluster, and the pods in `open-cluster-management-addon-observability` namespace on all managed clusters are removed.

2020-10-22 04:10 UTC, clyang82 commented
Thanks @dockerymick I leave some comments. One general question: Do we have a tool to do grammar check for doc?

2020-10-22 04:22 UTC, dockerymick commented
@clyang, thanks for your review. Previously, we used Acrolinx but no longer have access to the licenses. I believe we can find an open source tool plugin

2020-10-22 05:40 UTC, RobDolares commented on observability/manage_observe.adoc
> +. You can access the Grafana dashboard from the _Clusters_ page. From the navigation menu, select *Automate infrastructure* > *Clusters* > *Grafana link*.
Agree with @clyang82 on combining, or at least an 'You can also' from new line if you have to.
Also, should we pluralize _dashboard_ --> 'dashboards'?

> "You can access the Grafana dashboards from..."

You do land on the overview dashboard, but there are numerous to choose from or drill down to.

2020-10-22 06:06 UTC, clyang82 commented
@dockerymick I am not if we evaluate https://github.com/client9/misspell or not.

2020-10-22 12:24 UTC, dockerymick commented on observability/manage_observe.adoc
> +
What does OOTB mean?

2020-10-22 13:32 UTC, RobDolares commented on observability/manage_observe.adoc
> +
@dockerymick - 'Out of the Box'

2020-10-22 14:27 UTC, dockerymick commented on observability/manage_observe.adoc
> +. You can access the Grafana dashboard from the _Clusters_ page. From the navigation menu, select *Automate infrastructure* > *Clusters* > *Grafana link*.
I wasn't sure if there were multiple dashboards. Thanks for clarifying. I update dashboard to dashboards

2020-10-22 14:27 UTC, dockerymick commented on observability/observability_install.adoc
> +- You must have {product-title} hub cluster installed as a managed cluster to use the observability feature.
I made the statement about ACM according to this comment: https://github.com/open-cluster-management/backlog/issues/4966#issuecomment-687171918

Should the statement for 4966 be added as a known issue instead? @subbarao-meduri may you help clarify ?

2020-10-22 14:27 UTC, dockerymick commented on observability/observability_install.adoc
> +Enable the observability service by creating a `multicluster-observability` CustomResourceDefinition (CRD). Complete the following steps to enable the observability service:
updated `multicluster-observability` to MultiClusterObservability CustomResource (CR) instance

2020-10-22 14:27 UTC, dockerymick commented on observability/observability_install.adoc
> +After you install observability, all of the pods in your `open-cluster-management-observability` namespace for your object storage, Grafana, and AlertManager are automatically installed. All managed
I think object storage is appropriate bc it is more generic. To my understanding Thanos is not a required storage solution. 

I can update the following statement: 

"After you install observability, all of the pods in your `open-cluster-management-observability` namespace for your object storage, Grafana, and AlertManager are automatically installed."

TO 

"Based on the previous resource example, all of the pods in your `open-cluster-management-observability` namespace Thanos, Grafana, and AlertManager are automatically installed after you install observability."

Thoughts?

2020-10-22 14:27 UTC, dockerymick commented on observability/observe_intro.adoc
> +The observability service requires data storage for the time series data. You must configure your object store to enable the observability service. {product-title-short} supports different types of s
Thanks for clarifying. I added the other storage options due to the statement from the What's new presentation. I will slack the link to the presentation

2020-10-22 14:28 UTC, dockerymick commented on observability/manage_observe.adoc
> +
Thanks!

2020-10-26 13:28 UTC, clyang82 commented on observability/observability_install.adoc
> +oc get managedclusteraddon -n test observability-controller -o yaml
Where is `test` namespace from? suggest to use `local-cluster` or just mentioned that `test` is a managed cluster namespace. the name should be `observability-addon` instead of `observability-controller`. @marcolan018 correct me if I am wrong

2020-10-26 13:30 UTC, clyang82 commented on observability/observe_intro.adoc
> +The observability service requires data storage for the time series data. You must configure your object store to enable the observability service. {product-title-short} supports different types of s
Let us add other storage options since we have them in What's new presentation. Thanks @dockerymick 
But we should remove Thanos which is not a storage.

2020-10-27 13:39 UTC, clyang82 approved these changes

2020-10-27 13:55 UTC, clyang82 requested changes

2020-10-27 13:55 UTC, clyang82 commented on observability/observability_install.adoc
> +oc get managedclusteraddon -n local-cluster observability-controller -o yaml
change it to `oc get observabilityaddon -n local-cluster observability-addon -o yaml`

2020-10-27 13:55 UTC, clyang82 commented on observability/observability_install.adoc
>    name: observability-controller
s/observability-controller/observability-addon

2020-10-27 13:55 UTC, clyang82 commented on observability/observability_install.adoc
>    name: observability-controller
```
apiVersion: observability.open-cluster-management.io/v1beta1
kind: ObservabilityAddon
```

2020-10-27 16:36 UTC, marcolan018 commented on observability/observability_install.adoc
> +oc get managedclusteraddon -n local-cluster observability-controller -o yaml
@clyang82 managedclusteraddon is the correct name. it's unify addon status report resource provided by klusterlet

2020-10-27 16:37 UTC, marcolan018 commented on observability/observability_install.adoc
>    name: observability-controller
same as above. Don't need to change to observability-addon

2020-10-28 01:07 UTC, clyang82 approved these changes

2020-10-28 14:10 UTC, subbarao-meduri commented on observability/observability_install.adoc
> +- You must have {product-title} hub cluster installed as a managed cluster to use the observability feature.
@dockerymick - It is not a requirement that a hub cluster must be installed as a managed cluster. 
We can document as a known issue that if a hub cluster is not configured as managed cluster, ACM will not collect metrics from the hub cluster. @bjoydeep please chime in with any additional comments.

2020-10-28 14:58 UTC, bjoydeep commented on observability/observability_install.adoc
> +- You must have {product-title} hub cluster installed as a managed cluster to use the observability feature.
Agreed with @subbarao-meduri and @clyang82 . It is NOT needed for Observability to function.

2020-10-28 15:23 UTC, bcpswope commented on observability/observe_intro.adoc
> +Observability is installed, but not enabled during the product installation. The observability service uses the `metrics-collector` pod on your managed cluster to "scrape" data from OpenShift Prometh
I would say what we say in components about "default".

By default, obs is Installed but not enabled...? Or something like that because we emphasize default behavior in other areas of the doc.

2020-10-28 16:04 UTC, bcpswope commented on security/rbac.adoc
> +To use the observability features: access managed cluster metrics, use the search component, use the Visual Web Terminal (VWT), a user must have access to the managed cluster. To create,update, and d
This one gets me a bit. Seems you are listing actions. but it gets buried... and the words may not be parallel. Maybe:

- Access managed cluster metrics
- Use the search component (OR Search for resources -- more active but up to you)
- Use the Visual Web Terminal (NO VWT--we are not using that abbreviation) if you have access to the managed cluster

Then start with a new line: To create, update (needs a space here). Also, "the user" here can just be:

To complete these actions, you must be assigned ___ or __ role...    

Use punctuation on all or none.

2020-10-28 16:04 UTC, bcpswope commented on security/rbac.adoc
>  Continue to learn more about securing your cluster, see xref:../security/security_intro.adoc#security[Security].
To continue..., see....

2020-10-28 16:05 UTC, bcpswope approved these changes
I will approve, as I am done committing the small changes I had. Great job and congrats on seeing a new component area from end-to-end in the doc!!! 

Please see: https://github.com/open-cluster-management/rhacm-docs/pull/1383/files#r513567837 where I got a bit confused and made some suggestions.

2020-10-28 19:43 UTC, dockerymick commented
All comments from reviews have been addressed, thank you everyone! I will continue to merge this PR and continue to make updates

2020-10-28 19:43 UTC, merged