open-cluster-management/backlog#4748 KI vm dest
open-cluster-management/rhacm-docs pull request #1394
Opened 2020-10-21 09:32 UTC by cadawson

2020-10-21 18:27 UTC, chrisahl commented on release_notes/known_issues.adoc
> +=== Process to destroy a vmWare vSphere cluster does not complete
vmWare should be VMware

2020-10-21 18:27 UTC, chrisahl commented on release_notes/known_issues.adoc
> +When you destroy a vmWare vSphere managed cluster, the status continues to display `Destroying`, and the cluster is not destroyed. To resolve this issue, manually remove the namespace of the managed
vmWare should be VMware

2020-10-21 18:31 UTC, chrisahl requested changes
comments inline

2020-10-21 18:53 UTC, cadawson commented on release_notes/known_issues.adoc
> +=== Process to destroy a vmWare vSphere cluster does not complete
Geez, yeah. Too early.

2020-10-21 18:53 UTC, cadawson commented on release_notes/known_issues.adoc
> +When you destroy a vmWare vSphere managed cluster, the status continues to display `Destroying`, and the cluster is not destroyed. To resolve this issue, manually remove the namespace of the managed
Thanks

2020-10-21 18:54 UTC, cadawson commented
Let's try that again @chrisahl . Thanks!

2020-10-21 20:38 UTC, cadawson commented
For some reason that didn't save the change. Now it is in @chrisahl .

2020-10-22 01:01 UTC, chrisahl approved these changes

2020-10-22 14:47 UTC, chrisahl commented on release_notes/known_issues.adoc
> +When you destroy a VMware vSphere managed cluster, the status continues to display `Destroying`, and the cluster is not destroyed. To resolve this issue, manually remove the namespace of the managed
Based on a recent bug found in Azure, we need to make a few edits to this. 
```
[#cluster-might-not-be-destroyed]
=== Process to destroy a cluster does not complete

// 2.1.0:4748

When you destroy a managed cluster, the status continues to display `Destroying` after one hour, and the cluster is not destroyed. To resolve this issue:
- manually ensure all the provider resources associated with the managed cluster are cleaned up  
- manually remove the namespace of the managed cluster by running the following command:
```

2020-10-22 14:48 UTC, chrisahl commented
@TheRealHaoLiu This is the doc item for VMware cleanup when deprovisioning gets stuck.   Add info you want doc'ed

2020-10-26 11:37 UTC, merged