open-cluster-management/backlog#4679 self mgd hub
open-cluster-management/rhacm-docs pull request #1424
Opened 2020-10-27 16:59 UTC by cadawson

2020-10-28 22:47 UTC, bcpswope commented on manage_cluster/import.adoc
> +*Note:* A hub cluster cannot manage _any_ other hub cluster. It is configured to automatically import and self-manage itself. You do not need to manually import the hub cluster.
@cadawson I need to add to this because of this issue. https://github.com/open-cluster-management/backlog/issues/5693

I don't think this is a note. This is a pretty big conversation and should actually be part of the authoritative documentation... please see if the edits I add work for you and the dev team.

2020-10-28 23:22 UTC, bcpswope commented on manage_cluster/import_cli.adoc
With line 12-14, can we validate issue: https://github.com/open-cluster-management/backlog/issues/5693

2020-10-29 15:00 UTC, showeimer commented on install/install_connected.adoc
>  +
@jpweiser @ckandag Does this read a little strangely?   While the information is true, I think our recommendation is that **no one** should be granted permissions directly to the `local-cluster` namespace because of the privilege escalation to ClusterAdmin; if that is the desire then just give the user ClusterAdmin directly.  Thoughts?

2020-10-29 15:00 UTC, showeimer commented on manage_cluster/import_gui.adoc
> +*Note:* The default setting for the hub cluster is to import itself and manage itself. You can change this setting by following the steps to change the `disableHubSelfManagement` value to `true`, as
Seems good; the re-import may not be immediate; because it will happen at the next reconcile of the MultiClusterHub controller

2020-10-29 20:35 UTC, jpweiser commented on install/install_connected.adoc
>  +
I agree.

2020-10-29 20:40 UTC, jpweiser requested changes
See https://github.com/open-cluster-management/rhacm-docs/pull/1424/files#r514325196

2020-11-03 10:44 UTC, cadawson commented
Updated the wording around this @jpweiser and @showeimer . Let me know how this works. Thanks!

2020-11-04 12:01 UTC, merged

2020-11-04 12:02 UTC, cadawson commented
Merging to add the updates.