open-cluster-management/backlog#6162
open-cluster-management/rhacm-docs pull request #1450
Opened 2020-10-31 14:47 UTC by bcpswope

--- buiding obs planning section

2020-11-02 17:35 UTC, marcolan018 requested changes

2020-11-02 17:35 UTC, marcolan018 commented on install/plan_capacity.adoc
> +* 10 clusters: RSS 9.84, working set 4.83
here should be the disk usage data? seems network usage data is put here now, it's wrong

2020-11-02 20:53 UTC, dockerymick requested changes
Curious, can we create a table for the data? Similar to https://github.com/open-cluster-management/multicluster-monitoring-operator/blob/master/docs/scale-perf.md

@bcpswope if you agree, i can help create the table

2020-11-02 20:53 UTC, dockerymick commented on install/plan_capacity.adoc
> +You need to plan your environment if you want to enable and use observability. The resource consumption later is not for single pod or single deployment, but for the {ocp-short} project where observa
I suggest you update the paragraph to the following statements:

You need to plan your environment if you want to nable and use the observability service.  The resource consumption later is for the {ocp-short} project where observability components are installed.  Values that you plan to use are sums for all observability components.



@marcolan018 is it required that we state the resource is not for single pod use?

2020-11-02 20:53 UTC, dockerymick commented on install/plan_capacity.adoc
> +The observability deployment uses the `High` value for availability and config, which means each Kubernetes deployment has 2 instances and each statefulset has 3 instances.
The observability deployment is configured for high availability environments. An high availability environment means that each Kubernetes deployment has two instance, and each stateful set has three instances.

2020-11-02 20:53 UTC, dockerymick commented on install/plan_capacity.adoc
> +
I suggest that we add an addition sign (+) on line 123 to help with alignment.

2020-11-02 20:53 UTC, dockerymick commented on install/plan_capacity.adoc
> +*Important:* Metrics are stored in `thanos-receive` until retention time of thanos-receive (four days) is reached.
Is `thanos-receive` a pod or deployment?

2020-11-02 20:53 UTC, dockerymick commented on install/plan_capacity.adoc
> +Other components do not require as much volume as `thanos-receivee` components.
`thanos-receivee` to `thanos-receive`

2020-11-02 20:53 UTC, dockerymick commented on install/plan_capacity.adoc
> +During tests, network transfer provided stability. See the sizes and network transfer values:
During tests, network transfers provide stability.

2020-11-02 20:53 UTC, dockerymick commented on install/plan_capacity.adoc
> +Total usage in S3, an Internet-based storage from Amazon.com, increases. The metrics data is stored in S3 until default rentation time (five days) is reached.
I suggest to drop `.com` and only say Amazon

2020-11-02 20:58 UTC, bcpswope commented
@dockerymick we cannot create a table because the other data is not in a table. I removed it to be consistent with the content that exists... it took quite a bit of time to make it flow as the other planning doc does.

2020-11-02 21:02 UTC, bcpswope commented on install/plan_capacity.adoc
> +Total usage in S3, an Internet-based storage from Amazon.com, increases. The metrics data is stored in S3 until default rentation time (five days) is reached.
that was from a resource, but you are right, not needed.

2020-11-02 21:09 UTC, bcpswope commented on install/plan_capacity.adoc
> +During tests, network transfer provided stability. See the sizes and network transfer values:
@dockerymick this was written in a certain tense, so do you mind looking at the topic as a whole? We are saying to this section that this is what was tested but not predicting that all tests will be the same.

2020-11-02 21:10 UTC, dockerymick commented on install/plan_capacity.adoc
> +*Important:* Metrics are stored in `thanos-receive` until retention time of thanos-receive (four days) is reached.
@marcolan018 ^

2020-11-02 21:20 UTC, bcpswope commented on install/plan_capacity.adoc
> +You need to plan your environment if you want to enable and use observability. The resource consumption later is not for single pod or single deployment, but for the {ocp-short} project where observa
that change is in.

2020-11-02 21:26 UTC, bcpswope commented on install/plan_capacity.adoc
> +The observability deployment uses the `High` value for availability and config, which means each Kubernetes deployment has 2 instances and each statefulset has 3 instances.
got it, few edits here, omit "an" and trying not using "means" (can have many meaning):

Added:

With a high availability environment, each Kubernetes deployment has two instances, and each stateful set has three instances.

2020-11-02 21:27 UTC, bcpswope commented on install/plan_capacity.adoc
> +
done

2020-11-02 21:27 UTC, bcpswope commented on install/plan_capacity.adoc
> +Other components do not require as much volume as `thanos-receivee` components.
done

2020-11-02 21:28 UTC, bcpswope commented on install/plan_capacity.adoc
> +During tests, network transfer provided stability. See the sizes and network transfer values:
I am just making sure it is in present tense across, but we should stress that this is results of a test and not every test??

2020-11-02 21:28 UTC, bcpswope commented on install/plan_capacity.adoc
> +Total usage in S3, an Internet-based storage from Amazon.com, increases. The metrics data is stored in S3 until default rentation time (five days) is reached.
done

2020-11-02 21:59 UTC, marcolan018 commented on install/plan_capacity.adoc
> +You need to plan your environment if you want to enable and use observability. The resource consumption later is not for single pod or single deployment, but for the {ocp-short} project where observa
@dockerymick @bcpswope 
cpu/memory/network consumptions are for the whole namespace open-cluster-management-observability where observability components located. maybe we need to add statement for that?

2020-11-02 23:34 UTC, dockerymick commented on install/plan_capacity.adoc
>  [discrete#worker-nodes-workloads]
I think we can remove "discrete"

2020-11-03 01:20 UTC, bcpswope commented on install/plan_capacity.adoc
>  [discrete#worker-nodes-workloads]
@dockerymick I am not sure why that is there or the purpose; since I didn't write it and it is not clear to me the usage, I did not remove it.

2020-11-03 01:37 UTC, dockerymick commented on install/plan_capacity.adoc
>  [discrete#worker-nodes-workloads]
it is not needed at all. There was a similar issue last release and Vikram said it was not needed. Let's leave it for GA and then we can remove it to see if the link is affected

2020-11-03 01:55 UTC, bcpswope commented on install/plan_capacity.adoc
>  [discrete#worker-nodes-workloads]
sounds good, if it builds, we can leave it and remove any remaining in 2.2

2020-11-03 13:33 UTC, bcpswope commented on install/perform_scale.adoc
> +
@dockerymick this is ready for final review

2020-11-03 13:34 UTC, bcpswope commented on install/plan_capacity.adoc
> +You need to plan your environment if you want to enable and use observability. The resource consumption later is not for single pod or single deployment, but for the {ocp-short} project where observa
@marcolan018 please look again, @dockerymick if you want to add the namespace statement, feel free to commit where you see fit.

2020-11-03 13:35 UTC, bcpswope commented on install/plan_capacity.adoc
> +
Moved this around, no + now bc not needed.

2020-11-03 14:00 UTC, dockerymick approved these changes
Made a couple of comments and made a small commit. Thanks for formatting the tables, it looks good :D

2020-11-03 14:00 UTC, dockerymick commented on install/perform_scale.adoc
> +In the test environment, hub clusters and managed clusters are located in Amazon Web Services cloud platform and have the following topology and configuration:
For consistency with the section heading, i would update this line to "In the sample environment"

2020-11-03 14:00 UTC, dockerymick commented on install/perform_scale.adoc
> +Total usage in S3 (Amazon Simple Storage Service) increases. The metrics data is stored in S3 until default rentation time (five days) is reached. See the following disk usages:
I would suggest: Toal usage in Amazon Simple Storage Service (S3) increases.


I understand that many would be familiar with S3, so I also agree that this does not need to change it, I am curious about what you think

2020-11-03 14:05 UTC, bcpswope commented on install/perform_scale.adoc
> +Total usage in S3 (Amazon Simple Storage Service) increases. The metrics data is stored in S3 until default rentation time (five days) is reached. See the following disk usages:
We can do that, may just need to change the header, though.

2020-11-04 18:17 UTC, marcolan018 approved these changes
lgtm

2020-11-04 18:32 UTC, merged