open-cluster-management/backlog#6865 Add errata
open-cluster-management/rhacm-docs pull request #1542
Opened 2020-11-17 17:10 UTC by cadawson

2020-11-17 17:19 UTC, bcpswope commented on release_notes/errata.adoc
> +
we have been able to keep the code block system here so I think `noncompliant` is better aligned with our doc/code?

2020-11-17 17:20 UTC, bcpswope approved these changes
Lovely, one comment. Thank you so much!

2020-11-17 18:00 UTC, dockerymick approved these changes

2020-11-17 18:00 UTC, dockerymick commented on release_notes/errata.adoc
> +* Fixed an issue that prevented subscription overrides from working when multiple subscriptions shared the same Git channel with the same branch. (GitHub 6476)
I would suggest that you state, "...on the same branch ".

2020-11-17 18:25 UTC, bcpswope commented on release_notes/errata.adoc
> +* Fixed an issue that prevented subscription overrides from working when multiple subscriptions shared the same Git channel with the same branch. (GitHub 6476)
Please be sure that Josh reviews this, especially line 20?

2020-11-17 18:25 UTC, bcpswope commented on release_notes/errata.adoc
> +* Fixed an issue that prevented subscription overrides from working when multiple subscriptions shared the same Git channel with the same branch. (GitHub 6476)
BC I actually think it should be "with" but want to be sure

2020-11-17 20:27 UTC, bcpswope commented on release_notes/errata.adoc
> +* Fixed an issue that prevented subscription overrides from working when multiple subscriptions shared the same Git channel with the same branch. (GitHub 6476)
Also in tech review, checking to see if this can be removed:

If your Helm subscription does not have `packageAlias` defined, the resource Topology displays remote cluster resources as `Not deployed`. 

See link:../manage_applications/package_overrides.adoc#configuring-package-overrides[Configuring package overrides] to define the appropriate `packageName` and the `packageAlias`.

2020-11-18 02:31 UTC, bcpswope requested changes
Added comments for quick need for tech review; pinged with the process (issue) reminders outlined in the 2.0.4 issue used to further gain a proficient, accurate pipeline to the release note. This was implemented for post - 2.0.4 Errata (see 2.0.5).

2020-11-18 20:47 UTC, bcpswope approved these changes

2020-11-30 15:37 UTC, bcpswope commented on release_notes/errata.adoc
> +* Fixed an issue that occurred when the Git webhook was enabled on channel/subscription but the subscribed resources were not applied to the target clusters. (GitHub 6785)
Please do not use slashes in technical documentation, use "and" and then a comma before "but."

2020-11-30 15:38 UTC, bcpswope commented on release_notes/errata.adoc
> +* Fixed an issue that caused the GRC dashboard to take a long time to load. (GitHub 6925)
We do not use GRC in the tech doc (see the navigation and doc for the official way our team presents GRC--we want to match console and doc.)

2020-11-30 15:40 UTC, bcpswope commented on release_notes/errata.adoc
> +
Line 77 is very confusing to me, trying to follow the description of the fix. If copied from developer summary, we often need to rewrite for clarity. Can this be changed a bit?

2020-11-30 15:53 UTC, bcpswope commented
Since there have been more entries and this is 2.1.1, I reviewed again it covers a lot of doc updates that I made for 2.1. I will need to watch those so that I can remove my known issues (if doc focal does not remove them for me; something I tried to do when creating the errata so known issues did not fall out of date).

2020-11-30 22:27 UTC, cadawson commented on release_notes/errata.adoc
> +
I actually did, and that makes more sense to me. I changed it, though, to see if I can make it more widely helpful.

2020-12-03 14:07 UTC, jnpacker commented on release_notes/errata.adoc
> +* Fixed an issue that prevented the complete destroying or detaching of a Microsoft Azure managed cluster after the addition of the cluster failed. (GitHub 6353)
Fixed an issue that prevented the complete clean up of...

2020-12-03 14:09 UTC, jnpacker commented on release_notes/errata.adoc
> +* Created the `placementrule` annotation, which fixed an issue that prevented the topology from displaying the correct nodes after it deployed a `helm` type application to `local-cluster` using subsc
Fixed an issue that prevented the application topology from displaying the correct resource nodes after it deployed a `helm` type application to `local-cluster`.  The application topology can now display  all type of applications.

2020-12-03 14:09 UTC, jnpacker commented on release_notes/errata.adoc
> +* Enabled the `packageOverrides` YAML content for the Git `kustomization.yaml` file to use the path that is identified in the annotation of the subscription by default. (GitHub 6476)
Application subscriptions: Enabled the ....

2020-12-03 14:12 UTC, jnpacker commented on release_notes/errata.adoc
> +* Fixed an issue that prevented the complete destroying or detaching of a Microsoft Azure managed cluster after the addition of the cluster failed. (GitHub 6353)
I find (Ln 18) the "... after closing, modifying and reopening an application. "
It was if you tried to edit an application that had Merge updates set, it would be unset.

2020-12-03 17:46 UTC, merged