open-cluster-management/backlog#6858 Rem observ
open-cluster-management/rhacm-docs pull request #1565
Opened 2020-12-02 13:31 UTC by cadawson

2020-12-02 20:24 UTC, dockerymick approved these changes
Changes look good Chris, thanks for the update. Quick question, after the MultiClusterObservability is removed, are users able to reinstall it later? I will ask the observability team, just wanted you to know what i curious about

2020-12-02 20:59 UTC, dislbenn commented on install/uninstall.adoc
> +.. Select *Delete MulticClusterObservability*.
I believe this should be **MultiClusterObservability**. There's an extra c.

2020-12-02 22:34 UTC, dockerymick commented on install/uninstall.adoc
>  == Deleting both components by using the console
When you say "both" are you referring to the CRD and operator?

2020-12-11 19:00 UTC, cadawson commented
@joeg-pro and @nathanweatherly : This PR is intended to resolve Issue #6858 (adding instructions for removing the Observability operator, if it is there) and add the installation clean-up script to the main uninstallation instructions. Let me know if you see any issues to be addressed. Thanks!

2020-12-11 19:09 UTC, cadawson commented on install/uninstall.adoc
>  == Deleting both components by using the console
Removed both, as it doesn't mean the same thing anymore. That is what it meant, but I think it becomes confusing now.

2020-12-14 17:57 UTC, joeg-pro commented on install/uninstall.adoc
> +oc delete multiclusterobservability --all
In some commands (like deleting the CSV) the doc includes `-n open-cluster-management` to force/indicate the target namespace.  I think we should be consistent and include that on all of these commands.

2020-12-14 18:01 UTC, joeg-pro requested changes
Just some minor changes to command examples.

2020-12-14 18:01 UTC, joeg-pro commented on install/uninstall.adoc
> +oc delete multiclusterobservability --all
n some commands (like deleting the CSV) the doc includes -n open-cluster-management to force/indicate the target namespace. I think we should be consistent and include that on all of these commands.

2020-12-14 18:01 UTC, joeg-pro commented on install/uninstall.adoc
>  oc get mch -o yaml
Add '-n open-cluster-management` here too.

2020-12-14 18:01 UTC, joeg-pro commented on install/uninstall.adoc
>  oc delete subs --all
Add '-n open-cluster-management` here too.

2020-12-14 18:01 UTC, joeg-pro commented on install/uninstall.adoc
> +oc delete clusterserviceversion -n open-cluster-management
I think this should have `--all` added to it at end.  (Not sure if it works as is.)

2020-12-14 22:06 UTC, cadawson commented on install/uninstall.adoc
> +oc delete multiclusterobservability --all
Thanks @joeg-pro . I added the namespaces. I think we are ok now.

2020-12-15 15:22 UTC, nathanweatherly commented on install/uninstall.adoc
> +oc delete multiclusterobservability --all
@joeg-pro I think technically it should be `-n <namespace>` with the note

```
Replace `<namespace>` in the script with the name of the namespace where {product-title-short} was installed.
```

2020-12-15 15:22 UTC, nathanweatherly commented on install/uninstall.adoc
>  oc get mch -o yaml
Same as above-- shoudl it be generic? `-n <namespace>`

2020-12-15 15:22 UTC, nathanweatherly commented on install/uninstall.adoc
>  oc delete subs --all
Same

2020-12-15 17:34 UTC, joeg-pro requested changes
See single comment.  Sorry for reversing my recommendation re -n optoins.

2020-12-15 17:34 UTC, joeg-pro commented on install/uninstall.adoc
> +oc delete multiclusterobservability --all -n open-cluster-management
In talking about this, Nathan pointed out something that I missed in making my first comments about adding `-n open-cluster-management`:  that fact that the first step of these instructions says to use `oc project` to switch the current namespace (which might typically be called open-cluster-management) means that its unnecessary to add the `-n` option on many of these commands.

I agree with Nathan's point.  Given step 1, the `oc` command examples shown for steps 2, 3, 5 and 6 don't need to have `-n open-cluster-management` on them.  Moreover, in light of us explicitly telling the customer to do step 1 then it seems silly to tell them also to put the `-n` on these commands.

So, sorry for the run-arround on this, but lets remove the `-n open-cluster-management` from the commands for steps 2, 3 5 and 6.  (Do not remove any `-n` options found in the "script" that is spelled out in step 4.)

2020-12-15 20:05 UTC, cadawson commented on install/uninstall.adoc
> +oc delete multiclusterobservability --all -n open-cluster-management
No problem. It is easy enough to fix. I was wondering about that, but there was also another place in the docs where someone asked to have that added, so I didn't worry about it. I removed them, and we should be ready to go. @joeg-pro @nathanweatherly

2020-12-16 19:12 UTC, nathanweatherly commented on install/uninstall.adoc
> +oc delete clusterserviceversion -all
--all (two dashes)

2020-12-16 19:17 UTC, nathanweatherly commented on install/uninstall.adoc
> +. Remove the MultiClusterObservability operator, if installed.
"Remove the MultiClusterObservability Custom Resource, if created/installed"

2020-12-16 19:17 UTC, nathanweatherly commented on install/uninstall.adoc
> +. Remove the MultiClusterHub operator.
"Remove the MultiClusterHub Custom Resource"

2020-12-16 19:18 UTC, nathanweatherly commented on install/uninstall.adoc
> +.. Select the _Options_ menu for the MultiClusterObservability operator.
"Select the _Options_ menu for the MultiClusterObservability." (I don't think work "operator" included)

2020-12-16 19:19 UTC, nathanweatherly commented on install/uninstall.adoc
> +.. Select the tab for _Multiclusterhub operator_.
"... tab for _Multiclusterhub_"

2020-12-16 19:19 UTC, nathanweatherly commented on install/uninstall.adoc
> +.. Select the _Options_ menu for the MultiClusterHub operator.
s/operator/custom resource

2020-12-16 19:20 UTC, nathanweatherly commented on install/uninstall.adoc
> +.. If the MultiClusterObservability operator is installed, select the tab for _MultiClusterObservability_.
If the MulticlusterObservability Custom Resource is installed, ...

2020-12-17 19:02 UTC, cadawson commented
Ok. I didn't like my option to create a new file. Here is what I did:
1. I moved the steps that were in the observability section to the uninstalling file.
2. I removed the important note about removing the observability cr, since it is now covered inline in the uninstallation steps. 
3. I left the section title in the observability section so people who are only trying to disable observability can find something there. In the section, I link to the procedure in the uninstallation topic that contains the steps. 
I think this might be a good option. Let me know what you think. Thanks! @bjoydeep @nathanweatherly

2020-12-17 20:04 UTC, bjoydeep commented on install/uninstall.adoc
> +
@cadawson I would swap steps 1 and 2...
you log into your cluster first
run `oc delete mco observability`
then - change to project namespace perhaps `oc project open-cluster-management`

2020-12-17 20:04 UTC, bjoydeep commented on observability/observability_install.adoc
therefore would say `See Step 1` Only and not step 2

2020-12-18 19:39 UTC, merged

2020-12-18 19:39 UTC, cadawson commented
FYI: @dockerymick After a couple of iterations, we moved the removal of the observability cr to the uninstallation topic. For those who look for it in the installing observability topic, we left a link to the uninstallation topic. This change was made in the 2.1 and 2.2 versions.