Doc gatekeeper operator 2.2
open-cluster-management/rhacm-docs pull request #1600
Opened 2020-12-10 23:30 UTC by dockerymick

https://github.com/open-cluster-management/backlog/issues/7433
https://github.com/open-cluster-management/backlog/issues/6274

2020-12-11 13:56 UTC, ycao56 commented on security/create_gatekeeper.adoc
> +* <<gatekeeper-operator,Creating a gatekeeper operator>>
this should appear first as it installs the gatekeeper. We can remove `Prerequisite` as this is what this policy does

2020-12-11 13:56 UTC, ycao56 commented on security/create_gatekeeper.adoc
> +* <<gatekeeper-operator,Creating a gatekeeper operator>>
I would rephrase the title to Install gatekeeper using gatekeeper operator policy

2020-12-11 13:58 UTC, ycao56 commented on security/create_gatekeeper.adoc
> +Use the governance framework to install the gatekeeper operator (`policy-gatekeeperoperator`). Gatekeeper operator is available in the link: https://operatorhub.io/[OperatorHub.io community].
RHACM provides gatekeeper operator policy for user to install gatekeeper on managed cluster. 
```
Gatekeeper operator is available in the link: https://operatorhub.io/[OperatorHub.io community].
```
The version we ship is Red Hat supported version not community version so we shouldn't point it to operatorhub

2020-12-11 13:59 UTC, ycao56 commented on security/create_gatekeeper.adoc
> +Gatekeeper operator policy is monitored by the Red Hat Advanced Cluster Management configuration policy controller, where `enforce` remediation action is supported. Gatekeeper policies are created au
`Gatekeeper operator policy` not `Gatekeeper policies`

2020-12-11 14:00 UTC, ycao56 commented on security/create_gatekeeper.adoc
> +. As you complete the form, select *GatekeeperOperator* from the _Specifications_ field. The parameter values for your policy are automatically populated.
the policy needs to be enforced in order to install gatekeeper

2020-12-11 14:15 UTC, ycao56 commented
We need to document more about `gatekeeper operator` e.g. how it works and all the parameters that we can configure. @cadawson was on the gatekeeper operator sync meeting call. @dockerymick can you sync with him to see what's our plan to document gatekeeper operator?

2021-01-05 17:32 UTC, dockerymick commented
> We need to document more about `gatekeeper operator` e.g. how it works and all the parameters that we can configure. @cadawson was on the gatekeeper operator sync meeting call. @dockerymick can you sync with him to see what's our plan to document gatekeeper operator?

@ycao How do you want to display the parameters? Usually, we create a YAML table with parameter definitions. Then we can reference the user to the Gatekeeper operator policy examples.

2021-01-07 16:32 UTC, willkutler requested changes

2021-01-07 16:32 UTC, willkutler commented on security/create_gatekeeper.adoc
> +During the install, the operator group and subscription pull the Gatekeeper operator to install it on to your hub cluster. Also consider that default values can be generated by the operator. See the
small change but you might want to specify that this is the YAML for the Gatekeeper custom resource, rather than the operator. Also, it could cause some confusion that this YAML contains a lot of fields that aren't in the custom resource that gets created by the `policy-gatekeeperoperator` policy in the UI - we should probably clarify that a lot of these fields are optional, since just using
```
              apiVersion: operator.gatekeeper.sh/v1alpha1
              kind: Gatekeeper
              metadata:
                name: gatekeeper
                namespace: gatekeeper-system
              spec:
                audit:
                  logLevel: INFO
                  replicas: 1
                image:
                  image: 'docker.io/openpolicyagent/gatekeeper:v3.2.2'
                validatingWebhook: Enabled
                webhook:
                  emitAdmissionEvents: Enabled
                  logLevel: INFO
                  replicas: 2
```
will still install gatekeeper.

2021-01-07 16:32 UTC, willkutler commented on security/create_gatekeeper.adoc
>  apiVersion: policy.open-cluster-management.io/v1
Any reason the audit and admission scenarios are split into two policies? Typically for sample gatekeeper policies we've just added the audit configurationpolicy as another policy-template to go along with the admissions one. If you'd like to split them up, both policies would need to contain the configurationPolicy:
```
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-gatekeeper-k8srequiredlabels
        spec:
          remediationAction: enforce # will be overridden by remediationAction in parent policy
          severity: low
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: templates.gatekeeper.sh/v1beta1
                kind: ConstraintTemplate
                metadata:
                  name: k8srequiredlabels
                spec:
                  crd:
                    spec:
                      names:
                        kind: K8sRequiredLabels
                      validation:
                        # Schema for the `parameters` field
                        openAPIV3Schema:
                          properties:
                            labels:
                              type: array
                              items: string
                  targets:
                    - target: admission.k8s.gatekeeper.sh
                      rego: |
                        package k8srequiredlabels
                        violation[{"msg": msg, "details": {"missing_labels": missing}}] {
                          provided := {label | input.review.object.metadata.labels[label]}
                          required := {label | label := input.parameters.labels[_]}
                          missing := required - provided
                          count(missing) > 0
                          msg := sprintf("you must provide labels: %v", [missing])
                        }
            - complianceType: musthave
              objectDefinition:
                apiVersion: constraints.gatekeeper.sh/v1beta1
                kind: K8sRequiredLabels
                metadata:
                  name: ns-must-have-gk
                spec:
                  match:
                    kinds:
                      - apiGroups: [""]
                        kinds: ["Namespace"]
                  parameters:
                    labels: ["gatekeeper"]
```
since that policy is the one that contains the Rego rule for gatekeeper to use - otherwise, it won't create the `K8sRequiredLabels` object that this policy is checking for violations.

2021-01-07 16:46 UTC, dockerymick commented on security/create_gatekeeper.adoc
>  apiVersion: policy.open-cluster-management.io/v1
Good idea, we wanted to highlight that there were more than one resource created in the gatekeeper policy. After taking a look again, we were assuming that the user knew that `kind: ConfigurationPolicy` was required. That isn't fair to the user, so I will add your suggestion

2021-01-07 17:28 UTC, dockerymick commented on security/create_gatekeeper.adoc
>  apiVersion: policy.open-cluster-management.io/v1
Re-reviewed the file and confirmed with @willkutler that the ConfigurationPolicy is present in both examples.

2021-01-07 17:29 UTC, dockerymick commented on security/create_gatekeeper.adoc
> +During the install, the operator group and subscription pull the Gatekeeper operator to install it on to your hub cluster. Also consider that default values can be generated by the operator. See the
Thanks, i've improved the statement

2021-01-07 17:29 UTC, dockerymick commented
@ycao56 when you have the opportunity, may you re-review the PR?

2021-01-07 17:39 UTC, willkutler approved these changes

2021-01-08 16:16 UTC, ycao56 commented on security/create_gatekeeper.adoc
> +Use the Gatekeeper operator to install the community version of Gatekeeper on a managed cluster. you can create and configure a Gatekeeper operator policy to monitor customer resources (CR) that are
The policy will be updated to RHACM supported one once we published it. So it should not say community version.

2021-01-08 16:21 UTC, ycao56 commented on security/create_gatekeeper.adoc
> += Install Gatekeeper using the gatekeeper operator policy
I think the title should be changed. Because what we are doing here is:
1.  Install gatekeeper operator on managed cluster
2. Gatekeeper operator then installs gatekeeper
3. create a gatekeeper policy
4.  report violations for audit and admission
So it is broader scope than `Install Gatekeeper using the gatekeeper operator policy`

2021-01-08 16:23 UTC, ycao56 commented on security/create_gatekeeper.adoc
> +During the install, the operator group and subscription pull the Gatekeeper operator to install it on to your hub cluster. Also consider that default values can be generated by the operator.
During the install, the operator group and subscription pull the Gatekeeper operator to install it on to your hub cluster. Then gatekeeper operator will install and configure gatekeeper based on Gatekeeper CR.

2021-01-08 16:24 UTC, ycao56 commented on security/create_gatekeeper.adoc
> +Use the governance framework to install the Gatekeeper operator (`policy-gatekeeperoperator`). Gatekeeper operator is available in the OpenShift Container Platform catalog. See _Adding Operators to a
I didn't find gatekeeper operator policy. Are we going to provide a link to it?

2021-01-08 16:28 UTC, ycao56 commented on security/create_gatekeeper.adoc
> +Create a YAML file for your gatekeeper policy. Run the following command:
the content in `Creating a gatekeeper policy` is not correct. 
The gatekeeper policy itself is missing. I am talking about https://github.com/open-cluster-management/policy-collection/blob/master/community/CM-Configuration-Management/policy-gatekeeper-sample.yaml#L12-L65 . This is how you can create a gatekeeper policy.

2021-01-08 16:28 UTC, ycao56 commented on security/create_gatekeeper.adoc
> +
the content in `Creating a gatekeeper policy` is not correct. 
The gatekeeper policy itself is missing. I am talking about https://github.com/open-cluster-management/policy-collection/blob/master/community/CM-Configuration-Management/policy-gatekeeper-sample.yaml#L12-L65 . This is how you can create a gatekeeper policy.

2021-01-08 19:30 UTC, dockerymick commented on security/create_gatekeeper.adoc
> += Install Gatekeeper using the gatekeeper operator policy
What do you think about `Integrating Gatekeeper`

2021-01-08 19:31 UTC, ycao56 commented on security/create_gatekeeper.adoc
> += Install Gatekeeper using the gatekeeper operator policy
sounds good

2021-01-08 19:42 UTC, dockerymick commented on security/create_gatekeeper.adoc
> +Use the governance framework to install the Gatekeeper operator (`policy-gatekeeperoperator`). Gatekeeper operator is available in the OpenShift Container Platform catalog. See _Adding Operators to a
Thanks for pointing that out, i have added the link to the policy in the community folder. Is that the correct link?

2021-01-11 22:26 UTC, dockerymick commented
@ycao56 I have made more updates to both files. I moved the information related to the content (i.e the gatekeeper table w/optional parameters). When you have an opportunity, may you re-review the PR

2021-01-11 22:39 UTC, ycao56 commented
LGTM. The only thing is the gatekeeper yaml in policy-collection repo will change. Currently the code snippet is referenced by lines. If the policy change in policy-colleciton repo, we will have to come back and update the doc

2021-01-11 22:54 UTC, ycao56 commented on security/gatekeeper_policy.adoc
> +Gatekeeper is a validating webhook that enforces CustomResourceDefinition (CRD) based policies that are run with the Open Policy Agent (OPA). You can install gatekeeper on your cluster by using the g
I suggest after this paragraph we add
I suggest we reorder the structure a little bit to better explain
1. Install gatekeeper using gatekeeper operator policy
2. Apply gatekeeper constraints and constraints template and monitor violation for audit and admission scenario

2021-01-13 22:56 UTC, dockerymick commented
@ycao56 may you re-review the PR, i have addressed the comments and updates

2021-01-14 13:39 UTC, ycao56 approved these changes

2021-01-14 13:39 UTC, ycao56 commented on security/gatekeeper_policy.adoc
> +- objectDefinition:
update the code snippet with https://github.com/open-cluster-management/policy-collection/blob/master/community/CM-Configuration-Management/policy-gatekeeper-sample.yaml#L67-L82

2021-01-14 13:40 UTC, ycao56 commented on security/gatekeeper_policy.adoc
> +- objectDefinition:
remove this line

2021-01-14 13:40 UTC, ycao56 commented on security/gatekeeper_policy.adoc
> +- objectDefinition:
remove this line

2021-01-14 13:40 UTC, ycao56 commented
@dockerymick looks good. just need to remove two lines in code snippets. approved!

2021-01-14 20:53 UTC, merged