open-cluster-management/backlog#6557 Add ts clust
open-cluster-management/rhacm-docs pull request #1684
Opened 2021-01-20 22:09 UTC by cadawson

2021-01-21 05:13 UTC, skeeey approved these changes

2021-01-21 12:25 UTC, cadawson commented
Thank you, @skeeey . Will this apply to 2.2, as well, or is it something that will not happen in 2.2? If it does, then I can add it.

2021-01-21 15:13 UTC, dockerymick requested changes
I made a suggestion for you. Let me know what you think. Otherwise the PR looks good to me! Links are functional

2021-01-21 15:13 UTC, dockerymick commented on troubleshooting/trouble_cluster_offline_avail.adoc
> +
I recommend that you move this explanation to the beginning of the file. The intro is repetitive to the symptom, so I would remove the _Identifying the problem_ section.  For example, I would update this to read: 


"Troubleshooting cluster status changing from offline to available

The status of a deployed cluster alternates from `offline` to `available` without any manual changes to the environment or cluster.

Symptom:

When the network that connects the managed cluster to the hub cluster is unstable, the status of the managed cluster that is reported by the hub cluster cycles between `offline` and `available`."

The rest of the file looks good to me!

2021-01-21 16:22 UTC, cadawson commented on troubleshooting/trouble_cluster_offline_avail.adoc
> +
Sounds good. I didn't like the repetition, but thought it might need to be there for structure. Glad you didn't think so, either. Thank you!

2021-01-21 17:30 UTC, dockerymick approved these changes
Made a small commit, changes look good!

2021-01-22 02:21 UTC, skeeey commented
> Thank you, @skeeey . Will this apply to 2.2, as well, or is it something that will not happen in 2.2? If it does, then I can add it.

@cadawson , yes, I think this also need to apply to 2.2, thank you

2021-01-22 17:56 UTC, merged

2021-01-22 18:00 UTC, cadawson commented
Sounds good, @skeeey . Added it to both releases.