Remove policy samples
open-cluster-management/rhacm-docs pull request #1687
Opened 2021-01-21 16:22 UTC by dockerymick

https://github.com/open-cluster-management/backlog/issues/8269

2021-01-21 19:49 UTC, dockerymick commented on security/config_policy_ctrl.adoc
> +See configuration policies samples that are supported by {product-title-short} from the link:https://github.com/open-cluster-management/policy-collection/blob/master/stable/SC-System-and-Communicatio
See the policy examples that use the NIST

2021-01-27 21:33 UTC, dockerymick commented
@ycao56 apologies for the long PR, I ran the spellcheck tool and decided to update Rolebinding to role binding. You can ignore the files related to that change. If it is ok with you, I would like to merge this PR and then I will address the comments you have made in the google doc. let me know what you think or prefer

2021-01-27 21:36 UTC, ycao56 approved these changes

2021-01-28 15:23 UTC, cadawson requested changes
Nice job! Looks like the links all work well. I added a few things to look at. After that, it looks good. Thanks!

2021-01-28 15:23 UTC, cadawson commented on security/create_rb_policy.adoc
>  NOTE: You can filter the table list of your policies by selecting the _Policies_ tab or _Cluster violations_ tab.
*Note:*

2021-01-28 15:23 UTC, cadawson commented on security/policy_sample_intro.adoc
> +* link:../security/role_policy.adoc#role-policy[Role policy]
Will this work? Let me know if it does...

2021-01-28 15:23 UTC, cadawson commented on security/psp_policy.adoc
> +See link:https://github.com/open-cluster-management/policy-collection/blob/master/stable/SI-System-and-Information-Integrity/policy-psp.yaml[`policy-psp.yaml`] to view the sample policy. View xref:..
...monitored by the controller.?

2021-01-28 15:23 UTC, cadawson commented on security/scc_policy.adoc
> +Apply an Security context constraints (SCC) policy to control permissions for pods by defining conditions in the policy. For more information see, link:https://docs.openshift.com/container-platform/4
Apply a Security context constraints (SCC) policy...

2021-01-28 15:23 UTC, cadawson commented on security/scc_policy.adoc
> +Apply an Security context constraints (SCC) policy to control permissions for pods by defining conditions in the policy. For more information see, link:https://docs.openshift.com/container-platform/4
Can we bump this link up to a later version of OCP? I verified that the same link exists for 4.4, 4.5, and 4.6. All you have to do is change the number in the URL. The reason is that 4.3 is going out of support.

2021-01-28 16:26 UTC, dockerymick commented on security/policy_sample_intro.adoc
> +* link:../security/role_policy.adoc#role-policy[Role policy]
I believe it will, i didn't notice it was like that tho. Thanks. I will maintain consistency and change to xref

2021-01-28 16:41 UTC, dockerymick commented
@cadawson thank you very much for your review, your feedback was very helpful. I have addressed your comments and will continue to merge this PR

2021-01-28 16:42 UTC, merged