Submariner draft 643122
open-cluster-management/rhacm-docs pull request #1697
Opened 2021-01-26 21:15 UTC by cadawson

2021-01-27 05:52 UTC, qiujian16 commented on manage_cluster/submariner.adoc
> +* Red Hat OpenShift Dedicated
@zhiweiyin318 do we support osd?

2021-01-27 05:52 UTC, qiujian16 commented on manage_cluster/submariner.adoc
> +* A {product-title-short} hub cluster that is running on {ocp} version 4.4, or later, with Kubernetes version 1.17, or later.
i believe it should be 4.5, submariner uses crd v1 which is not supported in 4.4

2021-01-27 05:52 UTC, qiujian16 commented on manage_cluster/submariner.adoc
> +* Two or more {ocp-short} managed clusters that are running on {ocp-short} version 4.4, or later, with Kubernetes version 1.17, or later, and are managed by the {product-title-short} hub cluster.
the supported ocp version should be confirmed @zhiweiyin318, same reason for crd v1

2021-01-27 05:52 UTC, qiujian16 commented on manage_cluster/submariner.adoc
> +* Firewall configuration across all nodes in each of the managed clusters must allow 4800/UDP in both directions.
I think we are going to configure it?

2021-01-27 05:52 UTC, qiujian16 commented on manage_cluster/submariner.adoc
> +* Firewall configuration on the Gateway nodes allows ingress 8080/TCP so the other nodes in the cluster can access it.
Why do we need this port? healthz?

2021-01-27 08:41 UTC, zhiweiyin318 commented on manage_cluster/submariner.adoc
> +* Red Hat OpenShift Dedicated
yes. submariner can run on osd clusters when user grant cluster-admin role.

2021-01-27 08:44 UTC, zhiweiyin318 commented on manage_cluster/submariner.adoc
> +* A {product-title-short} hub cluster that is running on {ocp} version 4.4, or later, with Kubernetes version 1.17, or later.
confirmed with submariner team, they moved back to CRD v1beta1 in d/s since they met issues using in the bundle CVP test.
so we can support OCP 4.4.

2021-01-27 08:46 UTC, zhiweiyin318 commented on manage_cluster/submariner.adoc
> +* Firewall configuration on the Gateway nodes allows ingress 8080/TCP so the other nodes in the cluster can access it.
8080 is added in submariner 0.8.0 to export metrics on the Gateway nodes.

2021-01-27 08:52 UTC, zhiweiyin318 commented on manage_cluster/submariner.adoc
> +* Firewall configuration across all nodes in each of the managed clusters must allow 4800/UDP in both directions.
on public clouds like aws, google cloud, azure  we are going to configure it (currently can only support AWS in this release) , but on private clouds like vSphere or bare metal we cannot configure their firewall of private networks.

2021-01-27 09:17 UTC, zhiweiyin318 commented on manage_cluster/submariner.adoc
> +Ensure that you have the following prerequisites before deploying the `submariner-addon`:
`submariner-addon` will be installed with ACM together by default. 
how about `Ensure that you have the following prerequisites before using the submariner:` ?

2021-01-27 09:17 UTC, zhiweiyin318 commented on manage_cluster/submariner.adoc
> +To prepare the clusters on your Google Cloud Platform for deploying the `Submariner-Addon` component, complete the following steps:
To prepare the clusters on your Google Cloud Platform for deploying the `Submariner` component

2021-01-27 09:17 UTC, zhiweiyin318 commented on manage_cluster/submariner.adoc
> +To prepare the clusters on your Microsoft Azure for deploying the `Submariner-Addon` component, complete the following steps:
To prepare the clusters on your Microsoft Azure for deploying the `Submariner` component

2021-01-27 09:17 UTC, zhiweiyin318 commented on manage_cluster/submariner.adoc
> +Complete the following steps to deploy `submariner-addon`:
Complete the following steps to deploy `submariner`:

2021-01-27 15:41 UTC, zhiweiyin318 commented on manage_cluster/submariner.adoc
> +* Red Hat OpenShift Dedicated
@cadawson could you please add the OSD part into the doc?
it is here https://github.com/open-cluster-management/submariner-addon/blob/master/docs/prerequisites.md#osd
I think there are some requirements when user configure on OSD.

2021-01-28 04:01 UTC, skeeey commented on manage_cluster/submariner.adoc
> +After the Submariner tool is deployed into the same environment as your managed clusters, you must discover the managed cluster service so the clusters can communicate. This example uses the `nginx`
> but you can discover any service

we may describe this more exactly, e.g.

but you can discover any Kubernetes `ClusterIP` service and headless service

2021-02-05 00:34 UTC, cadawson commented on manage_cluster/submariner.adoc
> +* Red Hat OpenShift Dedicated
Added this, but have some questions about the user ID that is explained. I think it might mean that you create a service user ID with that name because it is OSD. The way I read it was that the sections for AWS and GCP describe how to create that user ID, which I did not see. Can you provide some guidance? Thanks!

2021-02-05 00:34 UTC, cadawson commented on manage_cluster/submariner.adoc
> +* A {product-title-short} hub cluster that is running on {ocp} version 4.4, or later, with Kubernetes version 1.17, or later.
Left this at 4.4. Let me know if this changes.

2021-02-05 00:35 UTC, cadawson commented on manage_cluster/submariner.adoc
> +* Two or more {ocp-short} managed clusters that are running on {ocp-short} version 4.4, or later, with Kubernetes version 1.17, or later, and are managed by the {product-title-short} hub cluster.
Left this as 4.4. Let me know if it changes.

2021-02-05 00:43 UTC, cadawson commented on manage_cluster/submariner.adoc
> +* Firewall configuration across all nodes in each of the managed clusters must allow 4800/UDP in both directions.
Added a note to include this.

2021-02-05 00:44 UTC, cadawson commented on manage_cluster/submariner.adoc
> +Ensure that you have the following prerequisites before deploying the `submariner-addon`:
Updated this.

2021-02-08 03:07 UTC, skeeey approved these changes

2021-02-08 20:47 UTC, cadawson commented
Xie xie @skeeey . Can you provide any guidance to the question that I posted as a comment in the OSD question above? Thank you!

2021-02-09 02:28 UTC, zhiweiyin318 commented on manage_cluster/submariner.adoc
> +* Red Hat OpenShift Dedicated
@cadawson  the IAM user called “osdCcsAdmin” exists on AWS and the IAM service account called “osd-ccs-admin” is on GCP.   
you can get more info from here https://www.openshift.com/dedicated/ccs  but there is no gcp part on the website of osd. 
I have 2 snapshots from the creating OSD for you.
![image](https://user-images.githubusercontent.com/7592386/107307202-36780600-6ac1-11eb-8c0a-d3eabda2721e.png)

![image](https://user-images.githubusercontent.com/7592386/107307302-658e7780-6ac1-11eb-8c07-f17501d973f1.png)

2021-02-09 02:45 UTC, zhiweiyin318 commented
@cadawson, Wei Liu is on vacation. I append some info for your question about OSD. let me know if you have any question. thank you.

2021-02-09 13:00 UTC, mangelajo requested changes

2021-02-09 13:00 UTC, mangelajo commented on manage_cluster/submariner.adoc
> +* Firewall configuration on the Gateway nodes allows ingress 8080/TCP so the other nodes in the cluster can access it.
* Firewall open for UDP/4500 UDP/500 or any other ports used for the IPSEC traffic on the gateway nodes.

2021-02-09 17:43 UTC, nyechiel commented on manage_cluster/submariner.adoc
> +. Create a `ManagedClusterSet` on the hub cluster by using the instructions provided in xref:../manage_cluster/custom_resource.adoc#managedclustersets[ManagedClusterSets]. The `submariner-addon` crea
```suggestion
. Create a `ManagedClusterSet` on the hub cluster by using the instructions provided in xref:../manage_cluster/custom_resource.adoc#managedclustersets[ManagedClusterSets]. The `submariner-addon` creates a namespace called `submariner-clusterset-<clusterset-name>-broker` and deploys the Submariner Broker to it. The name of the ManagedClusterSet replaces <clusterset-name> in the namespace name. Your entry for the `ManagedClusterSet` should resemble the following content:
```

2021-02-09 17:43 UTC, nyechiel commented on manage_cluster/submariner.adoc
> +After the Submariner tool is deployed into the same environment as your managed clusters, you must discover the managed cluster service so the clusters can communicate. This example uses the `nginx`
This is a bit confusing. After Submariner is deployed, we have enabled secure IP routing between the Pod and Services across the connected clusters. However, further configuration is required in order to signify that a Service should be visible and discoverable to other clusters in the cluster set, which needs to be done via creation of a `ServiceExport` object. If multiple clusters export a Service with the same name and from the same namespace, they will be recognized as a single logical Service.

I think we should also mention that when a Service is exported, it becomes accessible as `<service>.<ns>.svc.clusterset.local` across the connected clusters.

2021-02-16 08:41 UTC, nyechiel approved these changes

2021-02-17 16:53 UTC, cadawson commented
Thank you @zhiweiyin318 , @nyechiel, and @mangelajo for covering while @skeeey is out of office. All of the updates are in now. Nir has already seen them, but wanted to make sure the rest of you had a chance. Thanks!

2021-02-22 17:22 UTC, dockerymick commented on manage_cluster/deploy_submariner.adoc
> +. Ensure that you hsve completed the applicable preparations. See xref:../manage_cluster/submariner.adoc#submariner[Submariner] for the requirements.
Update: hsve TO: `have`

2021-02-22 17:22 UTC, dockerymick commented on manage_cluster/submariner.adoc
> +* Firewall configuration across all nodes in each of the managed clusters must allow 4800/UDP in both directions. *Note:* This is configured automatically when your clusters are deployed in an Amazon
I recommend moving the note to a new line. Be sure to add a plus sign (+) on a new line that comes before the Note. 

Not a requirement, but it would help the note stand out

2021-02-22 17:22 UTC, dockerymick commented on manage_cluster/submariner.adoc
> +There are 2 ways that you can configure the {ocp-short} cluster that is hosted on Amazon Web Services to integrate with a Submariner deployment. Select one of these options to prepare for the
spell out 2: two

Also incomplete sentence

2021-02-22 17:22 UTC, dockerymick commented on manage_cluster/submariner.adoc
> +Create a yaml file that contains the following content:
Update: yaml TO: YAML

2021-02-22 17:22 UTC, dockerymick commented on manage_cluster/submariner.adoc
> +The format of `name` is the same as the credential secret name that you used to provision the cluster with {product-title-short}.
add italics to `name`

2021-02-22 17:22 UTC, dockerymick commented on manage_cluster/submariner.adoc
> +If you have already configured your Submariner cluster environment manually, include the configurations in the your `SubmarinerConfig` addition. In this example, the `IPSecIKEPort` is set to 501, and
add code mark around the parameter values too:

`501` and `4501`

2021-02-22 17:22 UTC, dockerymick commented on manage_cluster/submariner.adoc
> +You can use the script file, `prep_for_subm.sh`, that is provided on the Submariner web site to update your {ocp-short} installer-provisioned Amazon Web Services infrastructure for Submariner deploym
Update: web site To: website

2021-02-22 17:22 UTC, dockerymick commented on manage_cluster/submariner.adoc
> +. Create the inbound and outbound firewall rules on your Google Cloud Platform to open the IPsec IKE (by default 500/UDP) and NAT traversal ports (by default 4500/UDP) to enable Submariner communicat
Replace the period (.) with a colon (:)

2021-02-22 17:22 UTC, dockerymick commented on manage_cluster/submariner.adoc
> +. Create the inbound and outbound firewall rules on your Google Cloud Platform to open the 8080/TCP port to export metrics service from the Submariner Gateway nodes.
Replace the period (.) with a colon (:)

2021-02-22 17:22 UTC, dockerymick commented on manage_cluster/submariner.adoc
> +If you have already configured your Submariner cluster environment manually, include the configurations in the your `SubmarinerConfig` addition. In this example, the `IPSecIKEPort` is set to 501, and
Replace the period (.) with a colon (:)

2021-02-22 17:22 UTC, dockerymick commented on manage_cluster/submariner.adoc
> +. Create the inbound and outbound firewall rules on your Google Cloud Platform to open the 4800/UDP port to encapsulate Pod traffic from the worker and master nodes to the Submariner Gateway nodes.
Replace the period (.) with a colon (:) to prompt the user for the example

2021-02-22 17:22 UTC, dockerymick commented on manage_cluster/submariner.adoc
> +. Create the inbound and outbound firewall rules on your Microsoft Azure environment to open the IP security IKE (by default 500/UDP) and NAT traversal ports (by default 4500/UDP) to enable Submarine
Replace the period (.) with a colon (:)

2021-02-22 17:22 UTC, dockerymick commented on manage_cluster/submariner.adoc
> +. Create one load balancing inbound NAT rules to forward Submariner gateway metrics service request.
Replace the period (.) with a colon (:)

2021-02-22 17:22 UTC, dockerymick commented on manage_cluster/submariner.adoc
> +. Create NSG (network security groups) security rules on your Azure to open IPsec IKE (by default 500/UDP) and NAT traversal ports (by default 4500/UDP) for Submariner.
Replace the period (.) with a colon (:)

2021-02-22 17:22 UTC, dockerymick commented on manage_cluster/submariner.adoc
> +. Create NSG (network security groups) security rules on your Azure to open IPsec IKE (by default 500/UDP) and NAT traversal ports (by default 4500/UDP) for Submariner.
I would update: NSG (network security groups)

TO: network security groups (NSG)

2021-02-22 17:22 UTC, dockerymick commented on manage_cluster/submariner.adoc
> +. Create the NSG rules to open 4800/UDP port to encapsulate Pod traffic from the worker and master nodes to the Submariner Gateway nodes.
lowercase: pod

Replace the period (.) with a colon (:)

2021-02-22 17:22 UTC, dockerymick commented on manage_cluster/submariner.adoc
> +. Create the NSG rules to open 8080/TCP port to export metrics service from the Submariner Gateway nodes.
Replace the period (.) with a colon (:)

2021-02-22 17:22 UTC, dockerymick commented on manage_cluster/submariner.adoc
> +There are 2 kinds of Red Hat OpenShift Kubernetes Service (ROKS) on IBM Cloud: the classic cluster and the second generation of compute infrastructure in a virtual private cloud (VPC). Submariner can
spell out 2 : two

2021-02-22 17:22 UTC, dockerymick commented on manage_cluster/submariner.adoc
> +. Complete the prerequisites that are listed in the xref:/submariner.adoc#preparing-aws[Preparing Amazon Web Services to deploy Submariner].
add `../`

2021-02-22 17:22 UTC, dockerymick commented on manage_cluster/submariner.adoc
> +. Complete the prerequisites in xref:/submariner.adoc#preparing-gcp[Preparing Google Cloud Platform to deploy Submariner].
Broken link here: add `../`

2021-02-22 17:22 UTC, dockerymick commented on manage_cluster/serv_disc_submariner.adoc
> +After Submariner is deployed into the same environment as your managed clusters, the routes are configured for secure IP routing between the Pod and services across the clusters in the `ManagedCluste
Change Pod to pod

2021-02-22 17:22 UTC, dockerymick commented on manage_cluster/serv_disc_submariner.adoc
> +This example uses the `nginx` service in the `default` namespace, but you can discover any Kubernetes `ClusterIP` service or headless service.
Replace period (.) with a colon (:)

2021-02-22 17:22 UTC, dockerymick commented on manage_cluster/serv_disc_submariner.adoc
> +. Export the service by creating a `ServiceExport` entry that resembles the following content in the yaml file:
Change yaml to YAML

2021-02-22 17:22 UTC, dockerymick commented on manage_cluster/serv_disc_submariner.adoc
> +Replace _service-name_ with the name of the service that you are exporting. In this example, it is `nginx`.
Code ticks for service-name

2021-02-22 17:22 UTC, dockerymick commented on manage_cluster/serv_disc_submariner.adoc
> +Replace _service-namespace_ with the name of the namespace where the service is located. In this example, it is `default`.
Code ticks for service-namespace

2021-02-22 17:22 UTC, dockerymick commented on manage_cluster/serv_disc_submariner.adoc
> +Replace _service-namespace_ with the name of the namespace where the service is located. In this example, it is `default`.
Also add a sentence to conclude the section. Maybe something like:

The `nginx` service discovery is enabled for Submariner.

2021-02-22 21:33 UTC, dockerymick approved these changes

2021-02-22 21:49 UTC, merged