open-cluster-management/backlog#7313 -- live meeting changes.
open-cluster-management/rhacm-docs pull request #1711
Opened 2021-01-29 19:13 UTC by swopeb

2021-03-01 15:22 UTC, jnpacker approved these changes

2021-03-11 19:06 UTC, dockerymick requested changes

2021-03-11 19:06 UTC, dockerymick commented on manage_applications/manage_apps_git.adoc
> + - Subfolder `config/`: Used to subscribe configurations in `common-managed` with placement to `managed-clusters`.
should this be `common-managed` folder?

2021-03-11 19:06 UTC, dockerymick commented on manage_applications/manage_apps_git.adoc
> +. Subscriptions apply content from the `common-managed/` folder to `managed-clusters` that match the placement rules. This also applies common applications and confugirations to all `managed-clusters
Is the backslash required for the folder name. On line 74 and 75 there is no backslash

2021-03-11 19:06 UTC, dockerymick commented on manage_applications/manage_apps_git.adoc
> +* An example of the `common-managed` folder with application artifacts:vhttps://github.com/open-cluster-management/application-samples/tree/main/subscriptions/nginx[nginx-apps].
remove the `v` in https

2021-03-11 19:06 UTC, dockerymick commented on manage_applications/manage_apps_git.adoc
> +* An example of the `root-subscripition`: https://github.com/open-cluster-management/application-samples/tree/main/subscriptions/subscribe-all[application-subscribe-all].
See application-subscribe-all for an example of the `root-subscription`

2021-03-11 19:06 UTC, dockerymick commented on manage_applications/manage_apps_git.adoc
> +* An example of the `common-managed` folder with application artifacts:vhttps://github.com/open-cluster-management/application-samples/tree/main/subscriptions/nginx[nginx-apps].
I would say "See the `common-managed` folder for an example with application artifacts"

2021-03-11 19:12 UTC, swopebe commented on manage_applications/manage_apps_git.adoc
> + - Subfolder `config/`: Used to subscribe configurations in `common-managed` with placement to `managed-clusters`.
yes!

2021-03-11 19:13 UTC, swopebe commented on manage_applications/manage_apps_git.adoc
> +. Subscriptions apply content from the `common-managed/` folder to `managed-clusters` that match the placement rules. This also applies common applications and confugirations to all `managed-clusters
maybe not? I will examine.

2021-03-11 19:13 UTC, swopebe commented on manage_applications/manage_apps_git.adoc
> +* An example of the `common-managed` folder with application artifacts:vhttps://github.com/open-cluster-management/application-samples/tree/main/subscriptions/nginx[nginx-apps].
I just kept these as a list with colon.

2021-03-11 19:31 UTC, swopebe commented on manage_applications/manage_apps_git.adoc
> +. Subscriptions apply content from the `common-managed/` folder to `managed-clusters` that match the placement rules. This also applies common applications and confugirations to all `managed-clusters
keeping it for `root-subscription/` removing it from others.

2021-03-11 20:13 UTC, jnpacker approved these changes

2021-03-11 20:29 UTC, swopebe commented on manage_applications/manage_apps_git.adoc
> +* An example of the `root-subscripition`: https://github.com/open-cluster-management/application-samples/tree/main/subscriptions/subscribe-all[application-subscribe-all].
changed all those

2021-03-11 20:32 UTC, dockerymick approved these changes
2 comments, otherwise this looks good

2021-03-11 20:32 UTC, dockerymick commented on manage_applications/manage_apps_git.adoc
> +* For an example of `root-subscription`, see https://github.com/open-cluster-management/application-samples/tree/main/subscriptions/subscribe-all[application-subscribe-all].
`root-subscription` to `root-subscription/`

2021-03-11 20:32 UTC, dockerymick commented on manage_applications/manage_apps_git.adoc
> +* See policy examples in https://github.com/open-cluster-management/policy-collection[Policy collection].
Policy collection to policy-collection

2021-03-11 20:34 UTC, swopebe commented on manage_applications/manage_apps_git.adoc
> +* See policy examples in https://github.com/open-cluster-management/policy-collection[Policy collection].
We can name the URL after the URL or the title of the web page. Decided to go after the title of the page on this one.

2021-03-11 20:36 UTC, swopebe commented on manage_applications/manage_apps_git.adoc
> +* See policy examples in https://github.com/open-cluster-management/policy-collection[Policy collection].
could also say in the `policy-collection repository`, but both are OK. Link names we have a little freedom, depending on what we want to say.

2021-03-11 20:38 UTC, merged