Adding the table for observability pod cpu and memory requests
open-cluster-management/rhacm-docs pull request #1744
Opened 2021-02-09 21:20 UTC by dockerymick

https://github.com/open-cluster-management/backlog/issues/8834

2021-02-10 02:25 UTC, clyang82 requested changes

2021-02-10 02:25 UTC, clyang82 commented on observability/observe_intro.adoc
> +| Container  | CPU usage (mCPU)  | Memory usage (MiB) | CPU (mCPU) | Memory (Mi) | Replicas | Pod total CPU | Pod total memory
we do not need have column of CPU usage (mCPU)  and Memory usage (MiB)

Pod total CPU | Pod total memory should be Pod total CPU(mCPU) | Pod total memory(Mi)

2021-02-10 02:25 UTC, clyang82 commented on observability/observe_intro.adoc
> +Observability components require 5166mCPU and 11388Mi memory to install the observability service. View the following table of the pod capacity requests that has CPU usage from six managed clusters w
> View the following table of the pod capacity requests that has CPU usage from six managed clusters with `observability-addons` enabled

View the following table of the pod capacity requests that is for ten managed clusters with `observability-addons` enabled

2021-02-10 02:27 UTC, clyang82 commented
Thanks @dockerymick for working on this. Just let you know we may change the request capacity to fit for 5 managedcluster, because there is no sufficient resource for observability components running.

2021-02-10 22:13 UTC, dockerymick commented on observability/observe_intro.adoc
> +| Container  | CPU usage (mCPU)  | Memory usage (MiB) | CPU (mCPU) | Memory (Mi) | Replicas | Pod total CPU | Pod total memory
Thanks @clyang82 I removed the column

2021-02-10 22:14 UTC, dockerymick commented on observability/observe_intro.adoc
> +Observability components require 5166mCPU and 11388Mi memory to install the observability service. View the following table of the pod capacity requests that has CPU usage from six managed clusters w
Updated

2021-02-11 14:28 UTC, dockerymick commented
@clyang82 Thanks for your review Chun Lin, when you have an opportunity, may you re-review the PR?

2021-02-16 01:42 UTC, bjoydeep commented
@dockerymick  we are **re-reviewing** this setting. @subbarao-meduri is leading this effort. He should be focal point now as @clyang82 is out this week. And @subbarao-meduri will be working with @marcolan018 and @clyang82  on this.

2021-02-16 03:12 UTC, dockerymick commented
@bjoydeep Thanks for clarifying this!

2021-02-18 05:49 UTC, clyang82 commented on observability/observe_intro.adoc
> +Observability components require 5166mCPU and 11388Mi memory to install the observability service. View the following table of the pod capacity requests that is for five managed clusters with `observ
s/5166mCPU/3936mCPU

2021-02-18 05:49 UTC, clyang82 commented on observability/observe_intro.adoc
> +| 100
s/100/50

2021-02-18 05:49 UTC, clyang82 commented on observability/observe_intro.adoc
> +| 300
s/300/150

2021-02-18 05:49 UTC, clyang82 commented on observability/observe_intro.adoc
> +| 100
s/100/45

2021-02-18 05:49 UTC, clyang82 commented on observability/observe_intro.adoc
> +| 300
s/300/135

2021-02-18 05:49 UTC, clyang82 commented on observability/observe_intro.adoc
> +| 10
s/10/5

2021-02-18 05:49 UTC, clyang82 commented on observability/observe_intro.adoc
> +| 30
s/30/15

2021-02-18 05:49 UTC, clyang82 commented on observability/observe_intro.adoc
> +| 500
s/500/200

2021-02-18 05:49 UTC, clyang82 commented on observability/observe_intro.adoc
> +| 1500
s/1500/600

2021-02-18 05:51 UTC, clyang82 commented
@dockerymick We have to reduce the cpu requests so that the observability components can be deployed in 3*M4 cluster. Thanks.

2021-02-18 17:22 UTC, dockerymick commented on observability/observe_intro.adoc
> +Observability components require 5166mCPU and 11388Mi memory to install the observability service. View the following table of the pod capacity requests that is for five managed clusters with `observ
updated

2021-02-18 17:23 UTC, dockerymick commented on observability/observe_intro.adoc
> +| 100
updated

2021-02-18 17:23 UTC, dockerymick commented on observability/observe_intro.adoc
> +| 300
Updated

2021-02-18 17:23 UTC, dockerymick commented on observability/observe_intro.adoc
> +| 100
updated

2021-02-18 17:23 UTC, dockerymick commented on observability/observe_intro.adoc
> +| 300
updated

2021-02-18 17:23 UTC, dockerymick commented on observability/observe_intro.adoc
> +| 30
updated

2021-02-18 17:23 UTC, dockerymick commented on observability/observe_intro.adoc
> +| 1500
updated

2021-02-18 17:24 UTC, dockerymick commented
@clyang82 Thanks for the review, I have addressed your suggestions. When you have an opportunity, may you re-review this PR

2021-02-20 08:55 UTC, clyang82 commented
@dockerymick we should update the CPU column instead of memory. Do you mind me updating in you PR directly?

2021-02-22 17:51 UTC, dockerymick commented
@clyang82 thanks for your patience, I was on PTO. Sure you can update the PR directly

2021-02-24 16:37 UTC, dockerymick commented
Based on the changes provided by @clyang82 via slack, we can move forward and merge this PR

2021-02-24 16:37 UTC, merged