adding observability known issue
open-cluster-management/rhacm-docs pull request #1887
Opened 2021-03-09 16:57 UTC by dockerymick

https://github.com/open-cluster-management/backlog/issues/9937

2021-03-09 17:03 UTC, marcolan018 commented on release_notes/known_issues.adoc
> +When the managed cluster is not detached successfully, the `ObservabilityAddon` resource `_observability-addon_` in the cluster namespace is stuck in the _Terminating_ status and cannot be removed. A
Since the managed clusters will be detached forcely finally. Should we change "successfully" to "gracefully"?

2021-03-09 17:04 UTC, marcolan018 commented on release_notes/known_issues.adoc
> +//RESOURCE?
there is no command to do this.
The command to edit the observabilityaddon is
```
kubectl edit observabilityaddon observability-addon -n {CLUSTER_NAMESPACE}
```
{CLUSTER_NAMESPACE} is the cluster namespace for the detached cluster.

2021-03-09 17:07 UTC, dockerymick commented on release_notes/known_issues.adoc
> +When the managed cluster is not detached successfully, the `ObservabilityAddon` resource `_observability-addon_` in the cluster namespace is stuck in the _Terminating_ status and cannot be removed. A
Thanks for clarifying, I suggest that we say "When the managed cluster is detached forcefully, the  `ObservabilityAddon` resource `_observability-addon_` in the cluster namespace is stuck in the _Terminating_ status and cannot be removed."

Thoughts?

2021-03-09 19:07 UTC, dockerymick commented
@marcolan018 I have made a few more updates, may you rereview the PR please?

2021-03-09 19:22 UTC, cadawson requested changes
A couple of things that I noticed, but overall looks good! Thanks!

2021-03-09 19:22 UTC, cadawson commented on release_notes/known_issues.adoc
> +`_<CLUSTER_NAMESPACE>_` is the cluster namespace for the detached cluster.
You don't need the angle brackets in the bold monospace.

2021-03-09 19:22 UTC, cadawson commented on release_notes/known_issues.adoc
> +When the managed cluster is detached forcefully, the `ObservabilityAddon` resource `_observability-addon_` in the cluster namespace is stuck in the _Terminating_ status and cannot be removed. Also, t
Do we need both "ObservabilityAddon resource" and "observability-addon"? It seems redundant, but you might be specifying the name for a reason. In that case, would: ...the `ObservabilityAddon` resource (`_observability-addon_`) in the cluster namespace... work better?
Or:
 ...the `ObservabilityAddon` resource named `_observability-addon_` in the cluster namespace...

2021-03-09 19:32 UTC, dockerymick commented on release_notes/known_issues.adoc
> +When the managed cluster is detached forcefully, the `ObservabilityAddon` resource `_observability-addon_` in the cluster namespace is stuck in the _Terminating_ status and cannot be removed. Also, t
@cadawson I agree with you! Yes, `observability-addon` is the name of the `kind`, thanks

2021-03-10 17:49 UTC, marcolan018 approved these changes
lgtm

2021-03-10 17:56 UTC, merged