Swope trouble application (dev peer review needed)
open-cluster-management/rhacm-docs pull request #1909
Opened 2021-03-15 21:50 UTC by swopebe

2021-03-15 22:58 UTC, xiangjingli reviewed
The rest LGTM

2021-03-15 22:58 UTC, xiangjingli commented on troubleshooting/trouble_local_cluster.adoc
> +All managed clusters are selected with a placement rule, but the `local-cluster` is not. The placement rule user is not granted permission to create resources in the `local-cluster` namespace, while
The placement rule user is not granted permission to create  the `deployable` resources in the `local-cluster` namespace

2021-03-15 22:58 UTC, xiangjingli commented on troubleshooting/trouble_local_cluster.adoc
> +. Confirm that managed clusters do not include `local-cluster`. Run the following command and see the results:
Confirm that managed clusters do include `local-cluster`, but the placement rule decision list doesn't have it. Run the following command and see the results:

2021-03-15 22:58 UTC, xiangjingli commented on troubleshooting/trouble_local_cluster.adoc
> +To resolve this issue, you need to grant administrative permission in the `local-cluster` namespace. Then, create a `RoleBinding` to grant the placement rule user to the role.
To resolve this issue, you need to grant the deployable administrative permission in the `local-cluster` namespace

2021-03-16 14:57 UTC, swopebe commented
done, in peer review

2021-03-16 15:38 UTC, swopebe commented on troubleshooting/trouble_local_cluster.adoc
> +. Confirm that managed clusters do not include `local-cluster`. Run the following command and see the results:
fix typo here (note to self)

2021-03-16 15:48 UTC, dockerymick requested changes
Made some comments and suggestions. I made suggestions about the title to ensure that they weren't repetitive and that they reflected the information that is later explained.

2021-03-16 15:48 UTC, dockerymick commented on troubleshooting/trouble_local_cluster.adoc
> +The managed clusters are selected with a placement rule, but the `local-cluster` (hub cluster that is also managed) is not selected. The placement rule user is not granted to permission to create dep
The intro and the Symptom is repetitive

Change: "...is not granted to permission to create deployable resources in the local-cluster namespace."

TO 

"...is not granted permission to create deployable resources in the `local-cluster` namespace."

2021-03-16 15:48 UTC, dockerymick commented on troubleshooting/trouble_local_cluster.adoc
> +== Symptom: Troubleshooting local cluster not selected
I would update the title to read as the following title: 

Symptom: Permission not granted to deploy

Then also remove "All managed clusters are selected with a placement rule, but the `local-cluster` is not."

2021-03-16 15:48 UTC, dockerymick commented on troubleshooting/trouble_local_cluster.adoc
> +== Resolving the problem: Troubleshooting local cluster not selected
I suggest updating the title to read the following title:

Resolving the problem: Update administrative permission

2021-03-16 15:48 UTC, dockerymick commented on troubleshooting/trouble_local_cluster.adoc
> +To resolve this issue, you need to grant the deployable administrative permission in the `local-cluster` namespace.
Add "Complete the following steps:"

2021-03-16 15:48 UTC, dockerymick commented on troubleshooting/trouble_local_cluster.adoc
> +. Confirm that the list of managed clusters does not include `local-cluster`, and that the placement rule `decisions` list does not display the local cluster. Run the following command and to view th
Run the following command to view the results 

Or Run the following command and view the results

2021-03-16 15:48 UTC, dockerymick commented on troubleshooting/trouble_local_cluster.adoc
> +
Add a plus sign on line 18 to help with alignment. Each step is starting with the number 1

2021-03-16 15:48 UTC, dockerymick commented on troubleshooting/trouble_local_cluster.adoc
> +----
Add plus sign on line 22

2021-03-16 15:48 UTC, dockerymick commented on troubleshooting/trouble_local_cluster.adoc
> +
Plus needed here on Line 44

2021-03-16 15:48 UTC, dockerymick commented on troubleshooting/trouble_local_cluster.adoc
> +. Create a `RoleBinding` to grant the placement rule user to the role. See the following example:
I suggest the following update:


Create a `RoleBinding` resource to grant the placement rule user access to the `local-cluster` namespace.

2021-03-16 15:48 UTC, dockerymick commented on troubleshooting/trouble_local_cluster.adoc
> +
Add a plus sign on line 61

2021-03-16 16:55 UTC, swopebe commented on troubleshooting/trouble_local_cluster.adoc
> +== Resolving the problem: Troubleshooting local cluster not selected
I am not sure about this one. It is way too easy to get that in another file in this book, which would break the build since we cannot have two of the same headers in a book.

2021-03-16 16:56 UTC, swopebe commented on troubleshooting/trouble_local_cluster.adoc
> +== Symptom: Troubleshooting local cluster not selected
gonna leave headers as is until we decide how we are going to change the architecture of this book.

2021-03-16 17:41 UTC, swopebe commented on troubleshooting/trouble_local_cluster.adoc
> +== Symptom: Troubleshooting local cluster not selected
(slack discussion, decided to leave the template as-is and discuss on content call changes to the headers; for 2.2 keep process for now)

2021-03-16 17:44 UTC, swopebe commented on troubleshooting/trouble_local_cluster.adoc
> +== Resolving the problem: Troubleshooting local cluster not selected
decided to leave as-is in discussion.

2021-03-16 17:46 UTC, swopebe commented on troubleshooting/trouble_local_cluster.adoc
> +To resolve this issue, you need to grant the deployable administrative permission in the `local-cluster` namespace.
done

2021-03-16 17:46 UTC, swopebe commented on troubleshooting/trouble_local_cluster.adoc
> +
done

2021-03-16 17:46 UTC, swopebe commented on troubleshooting/trouble_local_cluster.adoc
> +----
done

2021-03-16 17:50 UTC, swopebe commented on troubleshooting/trouble_local_cluster.adoc
> +== Symptom: Troubleshooting local cluster not selected
More specific title to make it about placement rule not selected, the permission is more the reason and the fix. The issue occurs to user because they assign placement rule.

2021-03-16 17:58 UTC, swopebe commented on troubleshooting/trouble_local_cluster.adoc
> +. Confirm that managed clusters do not include `local-cluster`. Run the following command and see the results:
done

2021-03-16 17:58 UTC, swopebe commented on troubleshooting/trouble_local_cluster.adoc
> +The managed clusters are selected with a placement rule, but the `local-cluster` (hub cluster that is also managed) is not selected. The placement rule user is not granted to permission to create dep
done

2021-03-16 17:59 UTC, swopebe commented on troubleshooting/trouble_local_cluster.adoc
> +. Confirm that the list of managed clusters does not include `local-cluster`, and that the placement rule `decisions` list does not display the local cluster. Run the following command and to view th
yes, changed

2021-03-16 18:00 UTC, swopebe commented on troubleshooting/trouble_local_cluster.adoc
> +. Create a `RoleBinding` to grant the placement rule user to the role. See the following example:
did not see this comment

2021-03-16 18:00 UTC, dockerymick approved these changes

2021-03-16 18:02 UTC, swopebe commented on troubleshooting/trouble_local_cluster.adoc
> +. Create a `RoleBinding` to grant the placement rule user to the role. See the following example:
changed

2021-03-16 18:03 UTC, merged