no issue - update variable guidance
open-cluster-management/rhacm-docs pull request #1914
Opened 2021-03-16 16:43 UTC by cadawson

2021-03-16 16:56 UTC, cadawson commented
The angle brackets in the command are to set it apart, and is mainly consistent with what exists in the docs.
The italic style for the variable that is outside of the content is consistent with the IBM style, and further sets it apart from the rest of the text.

2021-03-16 16:58 UTC, swopebe commented
it is set apart with code, italics in the command is more important, I think. But style manual (see my issue comment) has both, so if we are going to just choose one, why outside of the command?

2021-03-16 18:34 UTC, swopebe commented on _pages/ui_text_writing.md
>  |Menu cascade|Bold, same as DITA|No `menu cascade` tag, build as **Multi-cluster** > **Pods**|
This is a new, extra step, discussing if necessary in Slack.

2021-03-16 18:34 UTC, swopebe commented on _pages/ui_text_writing.md
> +|Variable inside of a command or script sample|Still want to identify the variable.|No `varname` tag, so use angle brackets (<these>) to identify a variable. Surround the variable with the angle brac
We could get rid of the DITA stuff since this was for onboarding onto markdown, much of this is older content that is not relevant to our team now.

2021-03-16 18:36 UTC, swopebe commented on _pages/ui_text_writing.md
> +|Variable inside of a command or script sample|Still want to identify the variable.|No `varname` tag, so use angle brackets (<these>) to identify a variable. Surround the variable with the angle brac
the whole file seems to have older IBM links and stuff in it. Do you mind updating this one? Also, not really a UI topic anymore, we can rename it to "writing guidance" or something? (I have renamed and reorged other files in this branch to more align with our current process, but only when it is time to update it.)

2021-03-16 19:30 UTC, dockerymick commented on _pages/ui_text_writing.md
> +|Variable inside of a command or script sample|Still want to identify the variable.|No `varname` tag, so use angle brackets (<these>) to identify a variable. Surround the variable with the angle brac
I agree with removing the DITA info, otherwise this update is good to me

2021-03-16 19:30 UTC, dockerymick commented on _pages/ui_text_writing.md
>  |Menu cascade|Bold, same as DITA|No `menu cascade` tag, build as **Multi-cluster** > **Pods**|
Not sure on what has been decided yet. Using monospace only is the original process we have done. During the meeting, I understood that we should also add italics to a monospaced variable when it is outside of the code block. I think this is helpful to do to bring emphasis. The common denominator is to have the variable monospaced, so that might be the safest option

2021-03-16 19:31 UTC, dockerymick reviewed
Made a couple of comments

2021-03-16 21:28 UTC, swopebe commented on _pages/ui_text_writing.md
>  |Menu cascade|Bold, same as DITA|No `menu cascade` tag, build as **Multi-cluster** > **Pods**|
If it is working and we don't need the extra step every time we write one, I would rather stick with codeblock and <>, like we mostly have been doing. I just am struggling with the justification for a new step if we are not fully following the manual guidance (which is a bit dated) and it is not done in OCP doc.

2021-03-26 17:58 UTC, swopebe commented on _pages/ui_text_writing.md
>  |Menu cascade|Bold, same as DITA|No `menu cascade` tag, build as **Multi-cluster** > **Pods**|
so do we agree <this> in the command (like as is, mostly) -- the command is the important part that they copy, and `this` in text (no need for italics)? This has been working thus far and I am thinking we don't need the extra step. Lots of people just copy the command without reading, so highlighting it in the command is worth the extra step.

2021-03-26 18:36 UTC, dockerymick commented on _pages/ui_text_writing.md
>  |Menu cascade|Bold, same as DITA|No `menu cascade` tag, build as **Multi-cluster** > **Pods**|
Yea, that is fine. I agree to removing the extra step to italicize variables in the text, only monospace.

2021-03-26 18:52 UTC, swopebe requested changes
requesting changes based on the discussion.

2021-04-09 01:08 UTC, swopebe approved these changes

2021-04-09 13:46 UTC, dockerymick approved these changes
made a very small update. This looks good! Thanks for working through this and updating the file Chris!

2021-04-09 13:57 UTC, merged