Updating commands
open-cluster-management/rhacm-docs pull request #1920
Opened 2021-03-17 19:30 UTC by dockerymick

https://github.com/open-cluster-management/backlog/issues/10331

2021-03-17 21:46 UTC, dhaiducek requested changes

2021-03-17 21:46 UTC, dhaiducek commented on security/create_policy_ctrl.adoc
> +export WATCH_NAMESPACE=<cluster_namespace_on_hub> go run cmd/manager/main.go
This should be two lines:
```
export WATCH_NAMESPACE=<cluster_namespace_on_hub>
go run cmd/manager/main.go
```

2021-03-18 13:37 UTC, dhaiducek approved these changes

2021-03-18 14:54 UTC, ycao56 approved these changes

2021-03-18 15:23 UTC, merged