open-cluster-management/backlog#11389 add ki ver delay
open-cluster-management/rhacm-docs pull request #1993
Opened 2021-04-13 17:21 UTC by cadawson

2021-04-13 17:32 UTC, dhrpatel4 approved these changes
lgtm

2021-04-13 19:28 UTC, dhrpatel4 requested changes
Hi @cadawson , can you please add managed cluster/local-cluster.
I think it will affect both local and manged cluster.
Sorry I forgot to add it to the doc issue

2021-04-14 14:33 UTC, cadawson commented
Hi @dhrpatel4 . I changed it to reflect your request. Let me know if that covers it. Thanks!

2021-04-14 14:42 UTC, hanqiuzh approved these changes

2021-04-15 11:55 UTC, merged