open-cluster-management/backlog#10221 ansibleapi
open-cluster-management/rhacm-docs pull request #2004
Opened 2021-04-19 16:49 UTC by cadawson

2021-04-22 12:41 UTC, jnpacker commented on apis/AnsibleJob.json.adoc
> +This documentation is for the AnsibleJob resource for {product-title}. Clusterset resource has four possible requests: create, query, delete and update.
Clusterset = AnsibleJob

2021-04-22 12:42 UTC, jnpacker commented on apis/AnsibleJob.json.adoc
> +* cluster.open-cluster-management.io : Create and manage Clustersets
AnsibleJobs, not clustersets

2021-04-22 12:43 UTC, jnpacker requested changes
Clusterset is referenced twice in this document, which is incorrect

2021-04-26 13:52 UTC, jnpacker approved these changes
Is there also a definition in the API for defining an instance of the CR? @cadawson

2021-04-28 12:01 UTC, cadawson commented
There is not, but we can look at adding it.

2021-04-28 20:35 UTC, jnpacker commented
Do we show the CR's for any of our CRD's?  I'm getting to the fact that we should.

2021-08-17 15:46 UTC, swopebe commented
poke, @cadawson (looking at date opened, odd to have a PR open for this length of time, please let me know if you need help)

2021-08-20 11:27 UTC, cadawson commented
Need to rework, so closing.

2021-08-20 11:27 UTC, closed without merging