Adding search known issue for 2.0
open-cluster-management/rhacm-docs pull request #2034
Opened 2021-04-28 14:24 UTC by dockerymick

[Dev issue](https://github.com/open-cluster-management/backlog/issues/11862)
[Doc issue](https://github.com/open-cluster-management/backlog/issues/11923)

2021-04-28 15:04 UTC, drkho requested changes
@jlpadilla @dockerymick This bug actually happens for all resources in "Search panel"...not just for channel, subscription, and placement rule. We need to generalize the statement.

See:
![Screen Shot 2021-04-28 at 10 01 24 AM](https://user-images.githubusercontent.com/60408124/116426789-0828dd80-a809-11eb-98e9-e1f2c2f65786.png)
![Screen Shot 2021-04-28 at 10 01 33 AM](https://user-images.githubusercontent.com/60408124/116426792-08c17400-a809-11eb-96cb-d69d9dccc22b.png)

2021-04-28 15:14 UTC, swopebe approved these changes
Looks good!

2021-04-28 17:17 UTC, dockerymick commented on release_notes/known_issues.adoc
> +The _Show all_ link is not functional from the _Search_ page. To work around this issue, you must narrow your search by seleccting more filters.
@drkho how about this update?

2021-04-28 19:21 UTC, jlpadilla commented
@drkho The intention of the "Show all / hide" button is to hide the tiles when you have too many relationships.  It was not intended as a way to select all the tiles.

More details here: https://github.com/open-cluster-management/backlog/issues/11862#issuecomment-828711355

2021-04-28 20:38 UTC, dockerymick commented
@drkho based on @jlpadilla comment, I believe we don’t need to doc this known issue since it’s functioning as expected. I think it is fair to doc a helpful note possibly? Let me know your thoughts

2021-04-29 17:38 UTC, drkho commented
🆗 , thanks.

2021-05-04 18:51 UTC, dockerymick commented
Closing this PR based on the conversation in the dev issue: https://github.com/open-cluster-management/backlog/issues/11862

2021-05-04 18:51 UTC, closed without merging