remove availabilityConfig
open-cluster-management/rhacm-docs pull request #2072
Opened 2021-05-06 08:13 UTC by songleo

we do not support `availabilityConfig` config in the observability service. so we need to remove this config.
Signed-off-by: Song Song Li <ssli@redhat.com>

2021-05-06 08:14 UTC, songleo commented
@dockerymick @clyang82 Please help review it, thanks.

2021-05-06 08:15 UTC, songleo commented
/assign @clyang82

2021-05-06 08:16 UTC, songleo commented
/assign @dockerymick

2021-05-06 08:18 UTC, clyang82 requested changes

2021-05-06 08:18 UTC, clyang82 commented on observability/observability_enable.adoc
>    enableDownSampling: true # The default value is true. This is recommended as querying long-time ranges downsampled data is efficient and useful.
s/`enableDownSampling`/`enableDownsampling`/g

2021-05-06 08:18 UTC, clyang82 commented on observability/observability_enable.adoc
>    enableDownSampling: true # The default value is true. This is recommended as querying long-time ranges downsampled data is efficient and useful.
please also update `storageConfig` section.

2021-05-07 02:45 UTC, clyang82 commented
💯 Thanks
/lgtm

2021-05-07 19:12 UTC, dockerymick approved these changes
Thanks @songleo the changes look good! Is there a doc issue for this before we merge?

2021-05-08 01:38 UTC, songleo commented
> Thanks @songleo the changes look good! Is there a doc issue for this before we merge?

yes, it is a doc issue, we need to update doc due to api changed. thanks

2021-05-10 10:49 UTC, dockerymick commented
Thanks @songleo for confirming and creating the issue. This helps us to track the  reason for the updates

2021-05-10 10:50 UTC, merged