addding doc on deploying policies with GitOps
open-cluster-management/rhacm-docs pull request #2081
Opened 2021-05-07 12:27 UTC by dockerymick

https://github.com/open-cluster-management/backlog/issues/10780

2021-05-07 13:40 UTC, swopebe commented on risk_compliance/deploy_gitops.adoc
> +* It is recommend to remove the policies you are not planning to use.
Let's chat about this set up, since we should not recommend. Usually we would use *Best practice:*

2021-05-07 13:41 UTC, swopebe commented on risk_compliance/deploy_gitops.adoc
> +*Prerequsite*: Before you begin, be sure to create you own fork of the `policy-collection` repository.
Let's make this active: "...fork the ___ repository."

2021-05-07 13:43 UTC, swopebe commented on risk_compliance/deploy_gitops.adoc
> +The governance framework allows you to deploy a set of policies across a fleet of managed clusters. You can leverage the open source community, https://github.com/open-cluster-management/policy-colle
Try to make first sentence active (avoiding anthropomorphic where you can), leverage I am not sure we usually use, prepositions here may be off "By contributing **to...**. and using policies **in**.

2021-05-07 13:45 UTC, swopebe commented on risk_compliance/deploy_gitops.adoc
> +. Be sure that you are in your local `policy-collection` repository on your main default branch for GitOps. Create a new directory in the repository to hold the policies that you want to deploy. Run
Always start with the step itself, then the conditional or supplemental info. 

1. Create (the actual task).....   You can say: From your local repository....., create.....  User should know right after the step number that the task here is to **Create**.

2021-05-07 13:46 UTC, swopebe commented on risk_compliance/deploy_gitops.adoc
> +
What you did here ^^^^ is exactly what I mean, beautiful!

2021-05-07 13:47 UTC, swopebe commented on risk_compliance/deploy_gitops.adoc
> +Now that you have all of the policies in a single parent directory structure, you can make edits to the policies in your fork.
Concise here:

Instead of "you can make edits", just use the action word:

... you can edit.

2021-05-07 13:52 UTC, dhaiducek reviewed
Looks good to me, though "contributing policies" is mentioned in the title/link but never referenced. We should add a little blurb about contributing somewhere, maybe something like (shamelessly stolen from our blog):
>As you develop and use policies to manage clusters with Red Hat Advanced Cluster Management, you can contribute the policies that you refine and create back to the `policy-collection` repository to broaden and strengthen our policy collection.

And then we could link to our contributing doc: https://github.com/open-cluster-management/policy-collection/blob/main/CONTRIBUTING.md#contributing-a-custom-policy

2021-05-07 13:52 UTC, dhaiducek commented on risk_compliance/deploy_gitops.adoc
> +** Remediation Action: Does the policy only inform you of compliance, or enforce the policy and make changes? Look at spec.remediationAction. If changes are enforced, make sure you understand the fun
I think this should have code formatting:
spec.remediationAction --> \`spec.remediationAction\`

2021-05-07 13:52 UTC, dhaiducek commented on risk_compliance/deploy_gitops.adoc
> +** Placement: What clusters is the policy deployed to? By default, most policies target the clusters with the environment: dev label. Some policies may target OpenShift clusters or another label. You
Code block: \`environment: dev\`

2021-05-07 13:52 UTC, dhaiducek commented on risk_compliance/deploy_gitops.adoc
> +. Push the changes to the main default branch of your forked Git repository’s that is used for GitOps. Run the following command:
It doesn't actually have to be the `main` branch or the default branch of the repo, so we can probably rephrase:
> ...to the main default branch of your...

to:

> ...to the branch of your...

2021-05-07 13:52 UTC, dhaiducek commented on risk_compliance/deploy_gitops.adoc
> +The `deploy.sh` script creates `Channel` and `Subscription` resources in your hub cluster. The channel connects to the Git repository, and the subscription specifies the data to bring to the cluster
"subdirectory is created" --> "subdirectory are created"

2021-05-07 13:52 UTC, dhaiducek commented on risk_compliance/deploy_gitops.adoc
> +// user configure the CLI?
Unfortunately I don't readily find a good resource, though if someone has gotten this far they've probably already been dealing with Openshift, so it might be a safe assumption that they're comfortable logging in to their cluster?

2021-05-07 13:52 UTC, dhaiducek commented on risk_compliance/deploy_gitops.adoc
> +* Namespace: The namespace where the resources and policies are created on the hub cluster. These instructions use the `policy-namespace` namespace The default namespace is `policies`.
Missing a period:
>the `policy-namespace` namespace. The ...

2021-05-07 16:43 UTC, dockerymick commented
Thanks @dhaiducek and @swopebe for the review and comments!

2021-05-07 17:44 UTC, swopebe commented on risk_compliance/deploy_gitops.adoc
> +* Spend some time going through the policies to make sure you understand the following criteria for each policy:
Rather:

Learn about policies and the definition of the policies from the following list: 

(More concise and active)

2021-05-07 17:48 UTC, swopebe commented on risk_compliance/deploy_gitops.adoc
> +** Remediation Action: Does the policy only inform you of compliance, or enforce the policy and make changes? Look at spec.remediationAction. If changes are enforced, make sure you understand the fun
missing code block here and maybe if you agree, emphasis on inform and enforce. Normally we say View or See the `spec.remediationAction`...

View the _Validate_ section.

2021-05-07 17:56 UTC, swopebe commented on risk_compliance/deploy_gitops.adoc
> +** Placement: What clusters is the policy deployed to? By default, most policies target the clusters with the environment: dev label. Some policies may target OpenShift clusters or another label. You
code block on the label?

Red Hat OpenShift (we have a conref maybe use here)

Relative pronoun: Policy **that is** configured one way...

2021-05-07 18:05 UTC, swopebe commented on risk_compliance/deploy_gitops.adoc
> +
I have a gitops example in app, as well. I suggest we both do the same thing when presenting the examples since they are not hard-lined examples. If you agree, we can look at both in the content call.
Here is my set up:
[#gitops-pattern]
== GitOps pattern

Learn best practices for organizing a Git repository to manage clusters.

[#repo-git-ops]
===  GitOps example

2021-05-07 18:06 UTC, swopebe commented on risk_compliance/deploy_gitops.adoc
> +
I don't think desired is an approved word, it wasn't previously.

2021-05-07 18:06 UTC, swopebe commented on risk_compliance/deploy_gitops.adoc
> +. Commit the changes and customize the message as desired. Run the following command:
Can drop desired and just say "customize your message."

2021-05-07 18:07 UTC, swopebe commented on risk_compliance/deploy_gitops.adoc
> ++
Never possessive. 

Push the changes to the main default branch of your forked repository that is used for GitOps.

2021-05-07 18:18 UTC, swopebe commented on risk_compliance/deploy_gitops.adoc
> +
In this way

change to 

As a result, (or something)

Furthermore, subject verb disagreement in the middle sentence. Two spots need the relative pronouns.

2021-05-07 18:25 UTC, swopebe commented on risk_compliance/deploy_gitops.adoc
> +The policy is then copied down to the managed cluster from its respective managed cluster namespace on the hub. In that way, the policies in your Git repository are pushed to all managed clusters tha
Same thing with: In that way.

Get rid of copied down, just copied; hub _cluster_ ; _that are_ defined..

2021-05-07 18:26 UTC, swopebe commented on risk_compliance/deploy_gitops.adoc
> +. Create a namespace where your policies are created to control access and identify them readily. Run the following command:
Consider rewriting this line, as I read it:

Create a namespace where your policies are created to control access. (try also not to write "them")

2021-05-07 18:27 UTC, swopebe commented on risk_compliance/deploy_gitops.adoc
> ++
Looks like code blocks may be off here.

2021-05-07 18:27 UTC, swopebe commented on risk_compliance/deploy_gitops.adoc
> +*Note*: For reference, the full list of arguments for the deploy.sh script uses the following syntax:
`deploy.sh`

2021-05-07 18:27 UTC, swopebe commented on risk_compliance/deploy_gitops.adoc
> ++
user name

2021-05-07 18:28 UTC, swopebe commented on risk_compliance/deploy_gitops.adoc
> +
Can they verify this?

2021-05-07 18:28 UTC, swopebe commented on risk_compliance/deploy_gitops.adoc
> +GitOps annotations are valuable to see which subscription created the policy. You can also add your own labels to your policies, so that you can write runtime queries that select policies based on la
no comma here, can remove.

2021-05-07 18:30 UTC, swopebe commented on risk_compliance/deploy_gitops.adoc
> +
existing

2021-05-07 18:35 UTC, swopebe requested changes
See comments, questions, recommendations.

2021-05-07 18:35 UTC, swopebe commented on risk_compliance/deploy_gitops.adoc
> ++
This is not really a step. "Consider" because you are not telling them to do anything. We don't usually present questions in tech doc unless we do an FAQ blog or something. I would reword this and create a task for the user.

Similar to:

Check for the following policy details (or something like that).

2021-05-07 18:35 UTC, swopebe commented on risk_compliance/deploy_gitops.adoc
> +----
code seems off here

2021-05-10 12:03 UTC, dockerymick commented on risk_compliance/deploy_gitops.adoc
> +// user configure the CLI?
I took a look in the OCP docs. @dhaiducek would this link be an accurate reference??

2021-05-10 12:18 UTC, dockerymick commented on risk_compliance/deploy_gitops.adoc
> ++
From the Preview tabs, the alignment looks ok from my end

2021-05-10 12:23 UTC, dockerymick commented on risk_compliance/deploy_gitops.adoc
> +----
These are directory paths

2021-05-10 12:26 UTC, dockerymick commented
> Looks good to me, though "contributing policies" is mentioned in the title/link but never referenced. We should add a little blurb about contributing somewhere, maybe something like this (shamelessly stolen from our blog):
> 
> > As you develop and use policies to manage clusters with Red Hat Advanced Cluster Management, you can contribute the policies that you refine and create back to the `policy-collection` repository by submitting a Pull Request to broaden and strengthen our policy collection.
> 
> And then we could link to our contributing doc: https://github.com/open-cluster-management/policy-collection/blob/main/CONTRIBUTING.md#contributing-a-custom-policy

The title for this file is titled Deploy policies using GitOps. I do mention that the user can contribute to the policy, so I will add the reference link to the contributing guidelines

2021-05-10 12:40 UTC, dockerymick commented on risk_compliance/deploy_gitops.adoc
> +
Thanks for the suggestion @swopebe I took a look at your section. I like your descriptions of the how the directory is set up and how it should flow, however I don't agree with adding this info into the deploy_gitops file. I do like the intro statement that you use, my change might resemble the following statement: "Learn best practice for organizing a Git repository to deploy and manage your policies."

2021-05-10 23:06 UTC, swopebe commented on risk_compliance/deploy_gitops.adoc
> +
That sounds great.

2021-05-10 23:06 UTC, swopebe approved these changes
Looks great, M!

2021-05-11 16:52 UTC, dockerymick commented
Thank you for the review @swopebe @dhaiducek  ! I appreciate you both. Moving forward with the merge

2021-05-11 16:52 UTC, merged