open-cluster-management/backlog#11100 Upd prep sub
open-cluster-management/rhacm-docs pull request #2134
Opened 2021-05-17 16:48 UTC by cadawson

2021-05-18 07:39 UTC, skeeey commented on services/submariner.adoc
> +Using this method, you apply the `SubmarinerConfig` API to the {product-title-short} hub cluster. When you run this procedure and do not specify an IPSec IKE port or IPSec NATT port, the default port
I think we may need the type of ports, e.g. The default ports are (500/UDP) and (4500/UDP)

2021-05-18 07:42 UTC, skeeey commented on services/submariner.adoc
> ++
I thin we may only need to replace `<managed-cluster-name>`, because the suffix `-aws-creds` is fixed

2021-05-18 07:43 UTC, skeeey commented on services/submariner.adoc
> +Replace `<managed-cluster-name>-aws-creds` with your AWS credential secret, which you can find in the cluster namespace of your hub cluster.
I thin we may only need to replace <managed-cluster-name>, because the suffix -aws-creds is fixed

2021-05-18 07:43 UTC, skeeey commented on services/submariner.adoc
> +Replace `IKEPort` with the port that you want to use for your Internet Key Exchange port.
Replace `<IKEPort>` ?

2021-05-18 07:44 UTC, skeeey commented on services/submariner.adoc
> +Replace `NATTPort` with the port that you want to use for your network address translation - traversal port.
Replace `<NATTPort> ?

2021-05-18 07:47 UTC, skeeey commented on services/submariner.adoc
> +Replace `<aws-credential-secret-name>`` with the name of your credential secret file.
there are two `, it should be  `<aws-credential-secret-name>`

2021-05-18 07:49 UTC, skeeey commented on services/submariner.adoc
> +Replace `<managed-cluster-namespace>`` with the namespace of your managed cluster.
there are two apostrophes, it should be  `<managed-cluster-namespace>`

2021-05-18 07:52 UTC, skeeey commented on services/submariner.adoc
> +** If you want to use the default ports for `IPSecIKEPort` (port 500) and `IPSecNATTPort` (port 4500), create a file that contains information that is similar to the following example:
the following example is not a file, it is a command that can be run directly after the variables are replaced.

2021-05-18 07:52 UTC, skeeey commented on services/submariner.adoc
> +** If you want to customize your Internet Key Exchange (IKE) port or network address translation - traversal (NATT) port, create a file that contains information that is similar to the following exam
the following example is not a file, it is a command that can be run directly after the variables are replaced.

2021-05-18 07:54 UTC, skeeey commented on services/submariner.adoc
> +. Apply the `SubmarinerConfig` on your {product-title-short} hub cluster by creating a file that is similar to the following file:
the following example is not a file, it is a command that can be run directly after the variables are replaced.

2021-05-18 07:54 UTC, skeeey commented on services/submariner.adoc
> +. Create a file that contains information that is similar to the following example:
the following example is not a file, it is a command that can be run directly after the variables are replaced.

2021-05-18 07:55 UTC, skeeey commented on services/submariner.adoc
> +Replace `IKEPort` with the port that you want to use for your IKE port.
Replace `<IKEPort>` ?

2021-05-18 07:55 UTC, skeeey commented on services/submariner.adoc
> +Replace `NATTPort` with the port that you want to use for your NATT port.
Replace `< NATTPort >`

2021-05-18 07:57 UTC, skeeey commented on services/submariner.adoc
> +. Apply the `SubmarinerConfig` on your {product-title-short} hub cluster by creating a file that is similar to the following file:
the following example is not a file, it is a command that can be run directly after the variables are replaced

2021-05-18 08:01 UTC, skeeey commented on services/submariner.adoc
> +Using this method, you apply the `SubmarinerConfig` API to the {product-title-short} hub cluster. When you run this procedure and do not specify an IPSec IKE port or IPSec NATT port, the default port
I think we may need the type of ports, e.g. The default ports are (500/UDP) and (4500/UDP)

2021-05-18 08:10 UTC, skeeey commented on services/submariner.adoc
> +. Create a file that contains information that is similar to the following example:
the following example is not a file, it is a command that can be run directly after the variables are replaced

2021-05-18 08:12 UTC, skeeey commented on services/submariner.adoc
> +Replace `<managed-cluster-name>-gcp-creds` with your Google Cloud Platform credential secret, which you can find in the cluster namespace of your hub cluster.
we may only need to replace <managed-cluster-name>, because the suffix -gcp-creds is fixed

2021-05-18 08:12 UTC, skeeey commented on services/submariner.adoc
> +** If you want to customize your Internet Key Exchange (IKE) port or network address translation - traversal (NATT) port, create a file that contains information that is similar to the following exam
the following example is not a file, it is a command that can be run directly after the variables are replaced

2021-05-18 08:13 UTC, skeeey commented on services/submariner.adoc
> +Replace `IKEPort` with the port that you want to use for your Internet Key Exchange port.
`<IKEPort>` ?

2021-05-18 08:13 UTC, skeeey commented on services/submariner.adoc
> +Replace `NATTPort` with the port that you want to use for your network address translation - traversal port.
`<NATTPort>` ?

2021-05-18 08:14 UTC, skeeey commented on services/submariner.adoc
> +Replace `<managed-cluster-name>-gcp-creds` with your AWS credential secret, which you can find in the cluster namespace of your hub cluster.
we may only need to replace `<managed-cluster-name>`, because the suffix -gcp-creds is fixed

2021-05-18 08:15 UTC, skeeey commented on services/submariner.adoc
> +. Create a file that contains information that is similar to the following example:
the following example is not a file, it is a command that can be run directly after the variables are replaced

2021-05-18 08:17 UTC, skeeey commented on services/submariner.adoc
> +Replace `<gcp-credential-secret-name>`` with the name of your credential secret file.
there are two apostrophes, it should be `<gcp-credential-secret-name>`

2021-05-18 08:18 UTC, skeeey commented on services/submariner.adoc
> +Replace `<managed-cluster-namespace>`` with the namespace of your managed cluster.
there are two apostrophes, it should be `<managed-cluster-namespace>`

2021-05-18 08:18 UTC, skeeey commented on services/submariner.adoc
> +. Apply the `SubmarinerConfig` on your {product-title-short} hub cluster by creating a file that is similar to the following file:
the following example is not a file, it is a command that can be run directly after the variables are replaced

2021-05-18 08:18 UTC, skeeey commented on services/submariner.adoc
> +. Create a file that contains information that is similar to the following example:
the following example is not a file, it is a command that can be run directly after the variables are replaced

2021-05-18 08:19 UTC, skeeey commented on services/submariner.adoc
> +. Apply the `SubmarinerConfig` on your {product-title-short} hub cluster by creating a file that is similar to the following file:
the following example is not a file, it is a command that can be run directly after the variables are replaced

2021-05-18 08:19 UTC, skeeey commented on services/submariner.adoc
> +Replace `IKEPort` with the port that you want to use for your IKE port.
`<IKEPort>`?

2021-05-18 08:19 UTC, skeeey commented on services/submariner.adoc
> +Replace `NATTPort` with the port that you want to use for your NATT port.
`< NATTPort >`?

2021-05-18 08:54 UTC, skeeey commented on services/submariner.adoc
> +Submariner uses IP security (IPSec) to establish the secure tunnels between the clusters on the gateway nodes. It uses virtual extensible LAN (VXLAN) to encapsulate traffic when it moves from the wor
@cadawson for vsphere,  these ports are not opened by submariner-addon automatically, these ports are required to be opened on corporate firewalls by vsphere admin manually in advance, there are there ports are need
- For IPSec, the ports are `IPSecIKEPort` (500/UDP) and `IPSecNATTPort` (4500/UDP), these two ports can be customized
- For VXLAN, the port is 4800/UDP, the port is a fixed port

so for vsphere, user need to configure the firewalls to open the 4800/UDP for VXLAN
For IPSec, user can  customize the ports, e.g. user opened ports 501 for IPSecIKEPort and 4501 for IPSecNATTPort, after this, user need use `SubmarinerConfig` to tell submariner-addon which ports they are used

2021-05-18 09:03 UTC, skeeey commented on services/submariner.adoc
> +* If you want to use the default ports for `IPSecIKEPort` (port 500) and `VXLANPort` (port 4800), complete the following steps:
if user use the default ports, submariner-addon knows the default ports, so we don't need these parts

2021-05-18 09:04 UTC, skeeey commented on services/submariner.adoc
> +* If you want to customize your IKE port or VXLAN port, complete the following steps:
How about: if you customized your IPSec ports, complete the following steps:

2021-05-18 09:05 UTC, skeeey commented on services/submariner.adoc
> +. Create and run a file that contains information that is similar to the following example:
the following example is not a file, it is a command that can be run directly after the variables are replaced

2021-05-18 09:06 UTC, skeeey commented on services/submariner.adoc
> +    IPSecVXLANPort: <VXLANPort>
It should be `IPSecNATTPort `: `<nattPort>`

2021-05-18 09:06 UTC, skeeey commented on services/submariner.adoc
> +    credentialsSecret:
For vshpere, we don't need this field

2021-05-18 09:07 UTC, skeeey commented on services/submariner.adoc
> +Replace `IKEPort` with the port that you want to use for your Internet Key Exchange port.
`<ikePort>`?

2021-05-18 09:07 UTC, skeeey commented on services/submariner.adoc
> +Replace `VXLANPort` with the port that you want to use for your VXLAN port.
`<nattPort>`?

2021-05-18 09:08 UTC, skeeey commented on services/submariner.adoc
> +Replace `<managed-cluster-name>-vmware-creds` with your VMware credential secret, which you can find in the cluster namespace of your hub cluster.
We don't need this for vsphere

2021-05-18 09:12 UTC, skeeey commented on services/submariner.adoc
> +. Label at least one worker node on your managed cluster with the label: `submariner.io/gateway=true`.
We don't need this

2021-05-18 09:12 UTC, skeeey commented on services/submariner.adoc
> +. Create a file that contains information that is similar to the following example:
We don't need this for vsphere

2021-05-18 15:03 UTC, cadawson commented on services/submariner.adoc
> +Replace `NATTPort` with the port that you want to use for your network address translation - traversal port.
You are correct that I needed to make this consistent. I used these as a basis for the others. I removed the < and > from the other ones outside of the example. We discussed how to approach the style on our squad, and thought this would be a good way. Thanks!

2021-05-18 15:04 UTC, cadawson commented on services/submariner.adoc
> +Replace `<aws-credential-secret-name>`` with the name of your credential secret file.
Yes, there were some places that I added one, and VSCode kindly added one, as well. Thank you.

2021-05-18 15:13 UTC, cadawson commented on services/submariner.adoc
> +** If you want to use the default ports for `IPSecIKEPort` (port 500) and `IPSecNATTPort` (port 4500), create a file that contains information that is similar to the following example:
Ok. I changed this.

2021-05-18 18:50 UTC, cadawson commented on services/submariner.adoc
> +Submariner uses IP security (IPSec) to establish the secure tunnels between the clusters on the gateway nodes. It uses virtual extensible LAN (VXLAN) to encapsulate traffic when it moves from the wor
Thank you for the clarification here. That helps. I made some changes that I think should cover it.

2021-05-18 18:52 UTC, cadawson commented
Additional changes made. Please take a look @skeeey . Thanks!

2021-05-19 10:46 UTC, skeeey commented on services/submariner.adoc
> +*Note:* This is configured automatically when your clusters are deployed in an AWS, Google Cloud Platform, VMware vSphere, or bare metal environment, but must be configured manually for clusters on o
The platform does not include `VMware vSphere` and  `bare metal`, and we may move this to line `#45`, because for AWS and GCP, all required ports can be configured automatically by submariner-addon, for other platforms, user need to configure them manually

2021-05-19 10:48 UTC, skeeey commented on services/submariner.adoc
> ++
Replace `managed-cluster-name` with your managed cluster name, the name `<managed-cluster-name>-aws-creds` is your AWS credential secret name, which you can find in the cluster namespace of your hub cluster. 

the following are the same

2021-05-19 10:56 UTC, skeeey commented on services/submariner.adoc
> +. Label at least one worker node on your managed cluster with the label: `submariner.io/gateway=true`.
We can remove this, after the story #11580,  the submariner-addon will label the worker node automatically

2021-05-19 10:58 UTC, skeeey commented on services/submariner.adoc
> +Replace `managed-cluster-name` with your Google Cloud Platform credential secret, which you can find in the cluster namespace of your hub cluster.
Replace managed-cluster-name with your managed cluster name, the name <managed-cluster-name>-gcp-creds is your Google Cloud Platform credential secret name, which you can find in the cluster namespace of your hub cluster.

the following are the same

2021-05-19 11:04 UTC, skeeey commented on services/submariner.adoc
> +. Label at least one worker node on your managed cluster with the label: `submariner.io/gateway=true`.
We can remove this, after the story #11580, the submariner-addon will label the worker node automatically

2021-05-19 11:04 UTC, skeeey commented on services/submariner.adoc
> +spec:
spec: {}

2021-05-19 11:07 UTC, skeeey commented
@cadawson, looks good, I left a few comments, and  I noticed the `Prerequisites` part, we also need to update the OCP version of hub

> A {product-title-short} hub cluster that is running on {ocp} version 4.5, or later, with Kubernetes version 1.17, or later.

A {product-title-short} hub cluster that is running on {ocp} version 4.6, or later, with Kubernetes version 1.19, or later.

thank you

2021-05-20 21:03 UTC, cadawson commented on services/submariner.adoc
> +. Label at least one worker node on your managed cluster with the label: `submariner.io/gateway=true`.
Same with line 508, I guess: . Label a node that has the public gateway as `submariner.io/gateway=true` in the cluster.? Remove that, too?

2021-05-20 21:09 UTC, cadawson commented
Hello @skeeey. I added the updates: One question about removing line 508. We removed the other similar ones, so I wanted to make sure that this one should also be removed. Other than that, I think we should be in good shape. Thank you!

2021-05-24 20:49 UTC, cadawson commented
Hi @skeeey . Are we waiting on this one for updates, as well, or was that only for the deployment issue? If so, that is ok. If not, can you take a look at this, when you have a chance? I thought you might have thought this one was the other PR that is open at the same time. The other PR is the one that we talked about waiting until the changes are complete in the code. Let me know if it should be both. Thanks!

2021-05-25 09:53 UTC, skeeey commented
@cadawson, this pr is not dependent on the  deployment part, so we can merge this pr firstly

We introduce some new configurations in story #11580 and GUI team also update the ACM GUI to support this, so we still need to update this part, and because we have too many updates on this pr :),  I think we can merge this pr firstly, then we do other changes based on this pr, I approved this pr, if you feel fine, please merger this, thank you

2021-05-25 09:54 UTC, skeeey commented on services/submariner.adoc
> +. Label at least one worker node on your managed cluster with the label: `submariner.io/gateway=true`.
for line 508, it's a manual operator, we need keep it, for azure, ibm, we also need to add this step, but I think we can keep this on this pr for now, because we will still update this part,  I think we can update them later.

2021-05-25 09:54 UTC, skeeey approved these changes

2021-05-25 15:31 UTC, cadawson commented
I agree with your plan, @skeeey . As long as the updates will be smaller changes based on this information (rather than based on the original information), let's move forward with your plan. Thank you!

2021-05-25 20:58 UTC, dockerymick requested changes

2021-05-25 20:58 UTC, dockerymick commented on services/submariner.adoc
>  * A credential for accessing the hub cluster with `cluster administrator` permissions.
A credential to access the hub cluster with `cluster-admin` permissions

OR 

A credential to access the hub cluster with cluster administrator permissions.

2021-05-25 20:58 UTC, dockerymick commented on services/submariner.adoc
>  * Firewall configuration on the Gateway nodes allows ingress 8080/TCP so the other nodes in the cluster can access it.
should this be:

Firewall configuration on the Gateway nodes must allow ingress 8080/TCP so the other nodes in the cluster can access it.

2021-05-25 20:58 UTC, dockerymick commented on services/submariner.adoc
> +* Firewall configuration open for 4500/UDP, 500/UDP, and any other ports that are used for IPSec traffic on the gateway nodes (configured automatically for AWS and Google Cloud Platform).
Is this statement in parenthesis necessary since you mention it in the note??

2021-05-25 20:58 UTC, dockerymick commented on services/submariner.adoc
> +Before deploying Submariner with {product-title}, you must prepare the clusters on the hosting environment for the connection. The requirements vary for different hosting environments, so follow the
Before you deploy Submariner with .....

2021-05-25 20:58 UTC, dockerymick commented on services/submariner.adoc
> +You can use the `SubmarinerConfig` API to configure the Amazon Web Services (AWS) cluster to integrate with a Submariner deployment. There are two ways that you configure the {ocp-short} cluster that
Since you wrote out the entire  cluster provider previously in this file, I recommend writing:

You can use the `SubmarinerConfig` API to configure the AWS cluster to integrate with a Submariner deployment. There are two ways for you to configure {ocp-short}...

2021-05-25 20:58 UTC, dockerymick commented on services/submariner.adoc
> +* Method 1 - Managed cluster was created using {product-title-short}
I would add a colon at the end of this

2021-05-25 20:58 UTC, dockerymick commented on services/submariner.adoc
> +Using this method, you apply the `SubmarinerConfig` API to the {product-title-short} hub cluster. When you run this procedure and do not specify an IPSec IKE port or IPSec NATT port, the default port
Are the ports displayed with the parenthesis or were you trying to bring emphasis to it?

2021-05-25 20:58 UTC, dockerymick commented on services/submariner.adoc
> +Replace `NATTPort` with the port that you want to use for your network address translation - traversal port.
I wouldn't write out the entire name here, just write:

Replace `IKEPort` with the IKE port that you want to use.

Replace `NATTPort` with the NATT port that you want to use.

2021-05-25 20:58 UTC, dockerymick commented on services/submariner.adoc
> +* Method 2 - Managed cluster was not created with {product-title-short}
I suggest adding a colon after {product-title-short}

2021-05-25 20:58 UTC, dockerymick commented on services/submariner.adoc
> +You can use the `SubmarinerConfig` API to configure the Google Cloud Platform cluster to integrate with a Submariner deployment. There are two ways that you configure the {ocp-short} cluster that is
There are two ways for you to configure the OCP...

2021-05-25 20:58 UTC, dockerymick commented on services/submariner.adoc
> +* Method 1 - Managed cluster was created using {product-title-short}
Add a colon after the conref

2021-05-25 20:58 UTC, dockerymick commented on services/submariner.adoc
> +Using this method, you apply the `SubmarinerConfig` API to the {product-title-short} hub cluster. When you run this procedure and do not specify an IPSec IKE port or IPSec NATT port, the default port
Instead of parenthesis, maybe have the port values monospaced

2021-05-25 20:58 UTC, dockerymick commented on services/submariner.adoc
> +** If you want to customize your Internet Key Exchange (IKE) port or network address translation - traversal (NATT) port, enter a command that contains information that is similar to the following ex
Only acronym is needed here

2021-05-25 20:58 UTC, dockerymick commented on services/submariner.adoc
> +Replace `IKEPort` with the port that you want to use for your Internet Key Exchange port.
Replace `IKEPort` with the IKE port that you want to use.

2021-05-25 20:58 UTC, dockerymick commented on services/submariner.adoc
> +Replace `NATTPort` with the port that you want to use for your network address translation - traversal port.
Replace `NATTPort` with the NATT port that you want to use.

2021-05-25 20:58 UTC, dockerymick commented on services/submariner.adoc
> +Replace `IKEPort` with the port that you want to use for your IKE port.
similar update as previously suggested

2021-05-25 20:58 UTC, dockerymick commented on services/submariner.adoc
> +Replace `NATTPort` with the port that you want to use for your NATT port.
Same here

2021-05-25 20:58 UTC, dockerymick commented on services/submariner.adoc
> +Replace `nat-name` with your load balancing inbound NAT rule name.
Replace `nat-name` with the NAT rule name of the load balancing inbound.

2021-05-25 20:58 UTC, dockerymick commented on services/submariner.adoc
> +Submariner uses IP security (IPSec) to establish the secure tunnels between the clusters on the gateway nodes. You can either use the default IPSec ports, or you can specify other IPSec ports that yo
As mentioned in the previous suggestion, are the parenthesis necessary here?

2021-05-25 20:58 UTC, dockerymick commented on services/submariner.adoc
> +Submariner uses virtual extensible LAN (VXLAN) to encapsulate traffic when it moves from the worker and master nodes to the gateway nodes on the .The VXLAN port cannot be customized, and is always po
should "nodes on the " be removed?

2021-06-01 12:58 UTC, cadawson commented on services/submariner.adoc
> +* Firewall configuration open for 4500/UDP, 500/UDP, and any other ports that are used for IPSec traffic on the gateway nodes (configured automatically for AWS and Google Cloud Platform).
Probably not. I was making sure that they were aware of it, but might be too much.

2021-06-01 13:41 UTC, cadawson commented on services/submariner.adoc
> +* Method 1 - Managed cluster was created using {product-title-short}
Not sure about adding a colon here. Would like it to be more of a title than an intro.

2021-06-01 13:44 UTC, cadawson commented on services/submariner.adoc
> +Using this method, you apply the `SubmarinerConfig` API to the {product-title-short} hub cluster. When you run this procedure and do not specify an IPSec IKE port or IPSec NATT port, the default port
I don't think I need them here. I will leave them in other places where I am setting it apart, but will remove them.

2021-06-01 14:03 UTC, cadawson commented on services/submariner.adoc
> +Replace `nat-name` with your load balancing inbound NAT rule name.
Sounded like this was a little confusing, so I reworded it.

2021-06-01 14:19 UTC, cadawson commented
Thanks for the review @dockerymick !

2021-06-01 14:23 UTC, dockerymick approved these changes
Thanks for your explanation Chris! I left two more comments, otherwise the changes look good

2021-06-01 14:23 UTC, dockerymick commented on services/submariner.adoc
> +* Method 1 - Managed cluster was created using {product-title-short}
Gotchu, maybe use the H4 heading or bold it?

2021-06-01 14:23 UTC, dockerymick commented on services/submariner.adoc
> +. Before creating a cluster, specify subnets for pods and services, which avoids overlapping CIDRs with other clusters. Make sure there are no overlapping pods and services CIDRs between clusters if
Before you create a cluster

2021-06-03 18:02 UTC, merged