Adding doc for custom template functions
open-cluster-management/rhacm-docs pull request #2138
Opened 2021-05-20 12:36 UTC by dockerymick

https://github.com/open-cluster-management/backlog/issues/12034

2021-05-20 20:30 UTC, ckandag requested changes

2021-05-20 20:30 UTC, ckandag commented on release_notes/whats_new.adoc
> +* You can now add custom template functions for configuration policies. See link:../risk_compliance/custom_template.adoc#customizing-templates-for-config-policies[Customizing templates for configurat
You can now add/or include templates in configuration policies.

2021-05-20 20:30 UTC, ckandag commented on risk_compliance/custom_template.adoc
> +Configuration policies now support inclusion of Golang templates in the object definitions. These templates are resolved at runtime on the target managed cluster using configuration policies related
1.  Golang **text** templates.  

2.   These templates are resolved at runtime on the target managed cluster using configuration  related to that cluster.

"using configuration related to that cluster". or NOT "using configuration policies related to that cluster"

2021-05-20 20:30 UTC, ckandag commented on risk_compliance/custom_template.adoc
> +//or this link: https://golang.org/pkg/text/template/#hdr-Functions
yes, agree, I intended to add but missed it. Please use this link 
https://golang.org/pkg/text/template/

2021-05-20 20:30 UTC, ckandag commented on risk_compliance/custom_template.adoc
> +*Required access:* Not sure
nothing additional  for templates support,   access requirements would be on the configuration policies  on specifically templates included in the policies

2021-05-20 20:30 UTC, ckandag commented on risk_compliance/custom_template.adoc
> +
Perhaps, the previous sentence about syntax  could be the made the Pre-req  or NOT  - i,e "The template syntax must be conformed ...."

2021-05-20 20:30 UTC, ckandag commented on risk_compliance/custom_template.adoc
> +
no saying default template function is not correct.

resource specific include name of the resource in the function name like fromSecret , fromConfigmap etc 
generic is not tied a specific resource and can work with any kube resource.

You can remove this   part  if its confusing " , both resource-specific and generic template functions,"

2021-05-20 20:30 UTC, ckandag commented on risk_compliance/custom_template.adoc
> +Customize the template for your configuration policies.
this statement is not correct, pls remove it

2021-05-20 20:30 UTC, ckandag commented on risk_compliance/custom_template.adoc
> +//should it be "`base64` encode" OR "`base64encode`"; throughout the doc i've seen "`base64` encode"
here it is the function-name so needs to be as is `base64encode`

2021-05-20 20:30 UTC, ckandag commented on risk_compliance/custom_template.adoc
> +The resource-specific functions offered for this release make the references to the resources more accessible. The generic function, `lookup`, require you to input the reference to the resource. In a
This stmt doesnot capture the meaning accurately 

Replace the following with the below 
"The resource-specific functions offered for this release make the references to the resources more accessible. The generic function, `lookup`, require you to input the reference to the resource."

Replace to : The resource specific functions are for convenience and make accessing content of resources easy, while the generic lookup function is for an advanced user  who is familiar with the yaml structure  of the resource being looked up , location and type of the content  being referenced .


Here the idea is you can use the generic "lookup" function to achieve the same result as "fromSecret" function, but  with fromSecret  user doesnt  to worry about knowing the yaml structure of the Secret resource etc , it is done internally , hence making convenient to the user.

2021-05-20 20:30 UTC, ckandag commented on risk_compliance/custom_template.adoc
> +----
could you pls list what each param in the  function syntax is 

 input the namespace, name and the datakey of a k8s Secret resource

Please do this for the other functions as well

2021-05-20 20:30 UTC, ckandag commented on risk_compliance/custom_template.adoc
> +//instead of template can we call PASSWORD a parameter?
PASSWORD is a parameter but here  value for the  Password  data key is template

I think its fine the way it is now

2021-05-20 20:30 UTC, ckandag commented on risk_compliance/custom_template.adoc
> +//structure?
could you replace Unstructured struct with "JSON compatible map"

2021-05-20 20:30 UTC, ckandag commented on risk_compliance/custom_template.adoc
> +//should we show more of the policy example? Is there more content that we can add that benefit the user?
given we have full policy examples , it seemed unncessary the bury a small template in a large file

2021-05-20 20:30 UTC, ckandag commented on risk_compliance/custom_template.adoc
> += Customizing tempplates for configuration policies
This title doesnt sound correct.

I would vote for something like 

Templates in Configuration policies 

or Support for Templates in Configuration Policies

2021-05-24 15:29 UTC, dockerymick commented on risk_compliance/custom_template.adoc
> +*Required access:* Not sure
@ckandag would the user need to be cluster admin to add the templates?

2021-05-24 15:46 UTC, dockerymick commented on risk_compliance/custom_template.adoc
> +//should we show more of the policy example? Is there more content that we can add that benefit the user?
I think it would be best to show part of the policy so that the user sees that it is a part of a ConfigMap

2021-05-26 13:27 UTC, dockerymick commented on risk_compliance/custom_template.adoc
> +The resource-specific functions offered for this release make the references to the resources more accessible. The generic function, `lookup`, require you to input the reference to the resource. In a
Thanks for your explanation Chaitanya and clarification!

2021-05-26 13:33 UTC, dockerymick commented on risk_compliance/custom_template.adoc
> +//should we show more of the policy example? Is there more content that we can add that benefit the user?
I understand why it can seem unnecessary. Maybe we can just add the YAML section that it would be a part of, Maybe at the `objectDefinition`? Let me know your thoughts. I prefer to add at least a snippet of the YAML file for consistency throughout the doc. Alternatively, we can remove some parts out of the other YAML examples

2021-05-26 14:57 UTC, ckandag requested changes

2021-05-26 14:57 UTC, ckandag commented on risk_compliance/custom_template.adoc
> +== Text template functions
instead of Text template , could we say Custom Template functions.

2021-05-26 14:57 UTC, ckandag commented on risk_compliance/custom_template.adoc
> +Text template functions are available for referencing Kubernetes resources on the cluster. The resource-specific functions are for covenience and make content of the resources more accessible. If you
Same here , instead of Text template , could we say Custom Template functions , at the beginning of the stmt

2021-05-26 14:57 UTC, ckandag commented on risk_compliance/custom_template.adoc
> +Continue reading to view descriptions and examples for some of the text template functions that are supported.
please replace text template functions with either Custom template functions or just template functions.

While the golang pkg is called text/template.  I do not think the custom functions. need to be called text template functions.

2021-05-26 14:57 UTC, ckandag commented on risk_compliance/custom_template.adoc
> +When you use this function, enter the namespace, name, and data key of a Kubernetes `Secret` resource. You receive a policy violation if the secret or the data key does not exist on the target cluste
i think just template is enough instead of text template

2021-05-26 14:57 UTC, ckandag commented on risk_compliance/custom_template.adoc
> +When you use this function, enter the namespace, name, and data key of a Kubernetes `ConfigMap` resource. You receive a policy violation if the ConfigMap or the data key does not exist on the target
and the `log-level` from the `default` namespace. The default value for `log-level` is `ERROR`:

this part of the sentence doesn't sound right. Perhaps, change it to something like below

and value  of  `log-level` is set to  the data key `log-level`,  If the data key doesnt exists in the ConfigMap or if the value is empty then `log-level` defaults to the value `ERROR`

2021-05-26 14:57 UTC, ckandag commented on risk_compliance/custom_template.adoc
> +The `fromClusterClaim` function returns the value of the `SpecValue` in the `ClusterClaim` resource. View the following syntax for the function:
its `Spec.Value` not `SpecValue`

note the "."  between Spec and Value

2021-05-26 14:57 UTC, ckandag commented on risk_compliance/custom_template.adoc
> +//will the user receive a policy violation if a certain data key or resource is not existing?
no, user will not receive specific violation if data key or resource doesnt exists. That is why we made a note in the front that the lookup function is for a advanced or a power use who is familiar with the resource and yaml

2021-05-26 14:57 UTC, ckandag commented on risk_compliance/custom_template.adoc
> +The `lookup` function returns the configuration resource as a JSON compatible map. View the following syntax for the function:
its not configuration resource. pls replace with  kubernetes resource

2021-05-26 14:57 UTC, ckandag commented on risk_compliance/custom_template.adoc
> +When you use the function, enter the API version, kind, namespace, and name of the Kubernetes `ConfigMap` resource. View the following example of the configuration policy that enforces a Kubernetes `
When you use the function, enter the API version, kind, namespace, and name of the Kubernetes **`ConfigMap`** resource.

its not just a ConfigMap resource , can be any resource. ( just for the example i used configmap but can be any kube resource)

So replace the above with 
When you use the function, enter the API version, kind, namespace, and name of the Kubernetes  resource.

2021-05-26 14:57 UTC, ckandag commented on risk_compliance/custom_template.adoc
> +//are there other task like creating a text template possible for the user??
no, we did not test or support Users creating there own templates

2021-05-26 14:57 UTC, ckandag commented on risk_compliance/custom_template.adoc
> +//should we show more of the policy example? Is there more content that we can add that benefit the user?
ok

2021-05-27 14:13 UTC, dockerymick commented
@ckandag Thank you so much for your feedback and for understanding the need for consistency. I believe the last thing for this PR is to add more YAML contents for `base64enc`, `base64dec`, and `indent`

2021-06-03 14:56 UTC, ckandag requested changes

2021-06-03 14:56 UTC, ckandag commented on risk_compliance/custom_template.adoc
> += Support for custom templates in configuration policies
Please make this "Support for templates in configuration policies".  we have some custom templates but we support regular templates too.. So support for custom templates sounds incorrect.

2021-06-03 14:56 UTC, ckandag commented on release_notes/whats_new.adoc
> +* You can now add or include custom template functions in configuration policies. See link:../risk_compliance/custom_template.adoc#support-custom-templates-in-config-policies[Support for custom templ
Please make this "You can now add or include templates in configuration policies.". 
Just  "templates" NOT  "custom template functions" 
we have some custom templates functions but we support regular templates too.. So saying  custom templates sounds very incorrect.

2021-06-03 14:56 UTC, ckandag commented on risk_compliance/custom_template.adoc
> +*Required access:* Cluster administrator
this is incorrect, I dont believe i mentioned its cluster admin any where.    This infact is not even needed.   

whatever access is needed to create  configuration policies can do this too , there is no additional Access level just for templates.

2021-06-03 14:56 UTC, ckandag commented on risk_compliance/custom_template.adoc
> +
The above too is choppy and doesnt flow well. Like I had mentioned in my original draft documentation. 
I think you need say there are some like some resource-specific functions like   - ,- -  which are convenience. and a generic function , which is for advanced user who is already familiar with the yaml structure. 

Please read through and restructure this

2021-06-03 15:49 UTC, dockerymick commented on risk_compliance/custom_template.adoc
> +*Required access:* Cluster administrator
Thanks for clarifying. I confirmed with Yu Cao, that a cluster admin or admin is required to create config policies.

2021-06-03 16:09 UTC, dockerymick commented on risk_compliance/custom_template.adoc
> +
How about this: Custom template functions, such as resource-specific and generic template functions, are available for referencing Kubernetes resources on the cluster. The resource-specific functions are used for convenience and make content of the resources more accessible. If you use the generic function, `lookup`, it is best to be familiar with the YAML structure of the resource that is being looked up.

2021-06-07 17:07 UTC, ckandag commented on risk_compliance/custom_template.adoc
> +
@dockerymick : This looks better , one modification 
Custom template functions, such as resource-specific and generic   lookup functions, 

---while the generic function is named "lookup" the purpose of all of the functions is to lookup k8s resources. So I think saying "resource-specific and generic   lookup functions, "  makes more sense

2021-06-07 17:07 UTC, ckandag commented on release_notes/whats_new.adoc
> +* You can now add or include custom template functions in configuration policies. See link:../risk_compliance/custom_template.adoc#support-custom-templates-in-config-policies[Support for custom templ
@dockerymick : Please also make this change

2021-06-07 17:10 UTC, dockerymick commented on release_notes/whats_new.adoc
> +* You can now add or include custom template functions in configuration policies. See link:../risk_compliance/custom_template.adoc#support-custom-templates-in-config-policies[Support for custom templ
Done

2021-06-07 17:11 UTC, merged