add doc for BYO certificate support for alertmanager route.
open-cluster-management/rhacm-docs pull request #2141
Opened 2021-05-22 07:00 UTC by morvencao

ref:
- https://github.com/open-cluster-management/backlog/issues/12478
- https://github.com/open-cluster-management/backlog/issues/12728
Signed-off-by: morvencao <lcao@redhat.com>

2021-05-22 07:01 UTC, morvencao commented
/assign @dockerymick @clyang82

2021-06-01 21:48 UTC, dockerymick requested changes

2021-06-01 21:48 UTC, dockerymick commented on risk_compliance/certificates.adoc
> +You can replace alertmanager certificates by updating the alertmanager route if you do not want to use the OpenShift default ingress certificate. The steps to use your own certificates for alertmanag
@morvencao i like that you added a reference to the Replace management ingress certificates doc. I recommend that we keep this reference, but add the steps that they user would complete. It would be a cost to the user to jump to another page bc then we would have to think about how they get directed back to this certs page

2021-06-01 21:48 UTC, dockerymick commented on risk_compliance/certificates.adoc
> +*Note:* If you want to restore the default self-signed certificate for alertmanager route, you only need to delete two secrets in the `open-cluster-management-observability` namespace, the observabil
Great note, I think we should also add a reference link to the section, Restore the default self-signed certificate for management ingress

2021-06-02 08:04 UTC, morvencao commented on risk_compliance/certificates.adoc
> +You can replace alertmanager certificates by updating the alertmanager route if you do not want to use the OpenShift default ingress certificate. The steps to use your own certificates for alertmanag
Do we really want to do this?
I'm asking because there lots of duplicate stuff there, especially the `Example configuration file for generating a certificate`

2021-06-02 08:06 UTC, morvencao commented on risk_compliance/certificates.adoc
> +*Note:* If you want to restore the default self-signed certificate for alertmanager route, you only need to delete two secrets in the `open-cluster-management-observability` namespace, the observabil
thanks, added the reference link.

2021-06-02 08:08 UTC, morvencao commented on risk_compliance/certificates.adoc
> +You can replace alertmanager certificates by updating the alertmanager route if you do not want to use the OpenShift default ingress certificate. The steps to use your own certificates for alertmanag
Actually I added these steps in my local before I created the PR, then I found that the steps are too much similar, so I reverted that work.

2021-06-02 14:06 UTC, dockerymick commented on risk_compliance/certificates.adoc
> +You can replace alertmanager certificates by updating the alertmanager route if you do not want to use the OpenShift default ingress certificate. The steps to use your own certificates for alertmanag
Understandable. I think we can assume that the user would already have the configuration file that is needed to generate a certificate. With that in mind, I think that it would be helpful to the user if we had a step to open or access the configuration. I made some edits in the file. 

Is there a command that that the user can run to change the CN and SAN?

2021-06-02 14:07 UTC, dockerymick commented on risk_compliance/certificates.adoc
> +. Change the common name (`CN`) on the certificate to `alertmanager`.
Is there a command for this? Or can the user edit the configuration after running the command on line 183?

2021-06-03 02:20 UTC, morvencao commented on risk_compliance/certificates.adoc
> +. Change the common name (`CN`) on the certificate to `alertmanager`.
unfortunately no such command, we have to update the CN in the csr.conf and then generate the certificate.

2021-06-03 02:22 UTC, morvencao commented on risk_compliance/certificates.adoc
> +You can replace alertmanager certificates by updating the alertmanager route if you do not want to use the OpenShift default ingress certificate. The steps to use your own certificates for alertmanag
unfortunately no such command, 
since we guide the end user to use csr.conf, so they have to change the CN and SAN in the csr.conf and then generate the certificate.

2021-06-04 01:29 UTC, dockerymick commented
@morvencao thanks for your review and feedback. I have removed the comments. When you have a chance, may you rereview the PR?

2021-06-04 01:53 UTC, morvencao commented on risk_compliance/certificates.adoc
> +. Create the two following secrets in the `open-cluster-management-observability` namespace. `multicluster-observability-operator` creates the secret. Run the following command:
I found the sentence `'multicluster-observability-operator' creates the secret.` is confusing, I suggest to remove it.

2021-06-04 01:54 UTC, morvencao commented
Others looks good to me.

2021-06-04 02:05 UTC, dockerymick commented
I addressed @morvencao suggestions and since all looks good, I am going to merge this PR

2021-06-04 02:05 UTC, merged

2021-06-04 02:06 UTC, morvencao commented
thanks @dockerymick