open-cluster-management/backlog#12069 Add 217 errata
open-cluster-management/rhacm-docs pull request #2142
Opened 2021-05-23 14:52 UTC by cadawson

2021-05-24 16:16 UTC, blkingrh approved these changes

2021-05-25 12:41 UTC, dockerymick approved these changes
I added a reference link to the RBAC topic. I made a couple of suggestions as well. Other than that, this looks good to me. Thanks Chris!

2021-05-25 12:41 UTC, dockerymick commented on release_notes/errata.adoc
> +* Fixed an issue that caused the Hive controller log to show the incorrect version information. (GitHub 12014)
Change Fixed to Fixes (or maybe not, I believe we agreed to use present tense for 2.2 onward

2021-05-25 12:41 UTC, dockerymick commented on release_notes/errata.adoc
> +* Added authorization for users with `View` permissions to create and delete the `ManagedClusterView` resource, which also enables users with `View` permissions to access to view the YAML file of the
`view` permissions

also remove "to access"

2021-05-25 14:10 UTC, swopebe requested changes
small change requested

2021-05-25 14:10 UTC, swopebe commented on release_notes/errata.adoc
> +* *Important:* You must be runnning {ocp} version 4.6, or later, to upgrade to {product-title-short} version 2.1.7. If you cannot upgrade your {ocp} version 4.5 to a later version, you can continue t
Please change to: You must run (vs be running)

2021-05-25 14:10 UTC, swopebe commented on release_notes/errata.adoc
> +* Fixed an issue that caused the Hive controller log to show the incorrect version information. (GitHub 12014)
Yeah, he wanted to avoid going back and I support that! LOL

2021-05-25 15:50 UTC, cadawson commented
Thank you for the reviews!

2021-05-25 20:26 UTC, merged