Update observability.json.adoc
open-cluster-management/rhacm-docs pull request #2176
Opened 2021-06-03 03:34 UTC by dockerymick

https://github.com/open-cluster-management/backlog/issues/12943

2021-06-03 03:38 UTC, dockerymick commented on apis/observability.json.adoc
> +      "name": "thanos-object-storage",
This link does not work: https://thanos.io/storage.md/#configuration

2021-06-03 03:40 UTC, dockerymick commented on apis/observability.json.adoc
> +__required__|The key of the secret to select from. Must be a valid secret key. See NEED LINK currently broken|string
Link from https://github.com/open-cluster-management/multicluster-observability-operator/blob/main/docs/MultiClusterObservability-CRD.md is broken

2021-06-03 05:40 UTC, clyang82 commented on apis/observability.json.adoc
> +    "replicas":
there is no `replicas` here. need 2 space indent for `"resources"`

2021-06-03 05:40 UTC, clyang82 commented on apis/observability.json.adoc
> +|**grafan** +
s/grafan/grafana

2021-06-03 05:40 UTC, clyang82 commented on apis/observability.json.adoc
> +|**queryFrontend +
missed `**`

2021-06-03 05:40 UTC, clyang82 commented on apis/observability.json.adoc
> +      "name": "thanos-object-storage",
use this one https://thanos.io/tip/thanos/storage.md/

2021-06-03 05:41 UTC, clyang82 commented on apis/observability.json.adoc
> +__required__|The key of the secret to select from. Must be a valid secret key. See NEED LINK currently broken|string
it is available.

2021-06-03 05:41 UTC, clyang82 commented
some format error if you view the file

2021-06-03 05:45 UTC, clyang82 requested changes

2021-06-03 05:45 UTC, clyang82 commented on apis/observability.json.adoc
>  }
Suggest to replace ^^ request body with
```
{
  "apiVersion": "observability.open-cluster-management.io/v1beta2",
  "kind": "MultiClusterObservability",
  "metadata": {
    "name": "example"
  },
  "spec": {
    "observabilityAddonSpec": {}
    "storageConfig": {
      "metricObjectStorage": {
        "name": "thanos-object-storage",
        "key": "thanos.yaml"
       }
   }
}

2021-06-04 01:38 UTC, dockerymick commented on apis/observability.json.adoc
> +|**grafan** +
great catch

2021-06-04 01:39 UTC, dockerymick commented on apis/observability.json.adoc
> +|**queryFrontend +
Thanks!

2021-06-04 01:51 UTC, dockerymick commented
@clyang82 thanks for your review and feedback. When you have an opportunity, may you rereview the PR?

2021-06-08 06:54 UTC, clyang82 commented on apis/observability.json.adoc
> +**nodeSelector** +
need start with `|`

2021-06-08 06:54 UTC, clyang82 commented on apis/observability.json.adoc
> +__optional__|Max item size of Memcached. The default value is `1m, min:1k, max:1024m`.
append `|string`

2021-06-08 06:54 UTC, clyang82 commented on apis/observability.json.adoc
> +__optional__|Max simultaneous connections of Memcached.|integer
missed default value here.

2021-06-08 17:45 UTC, dockerymick commented on apis/observability.json.adoc
> +**nodeSelector** +
Great catch, thanks!

2021-06-08 17:51 UTC, dockerymick commented on apis/observability.json.adoc
> +__optional__|Max simultaneous connections of Memcached.|integer
@clyang82 the default value wasn't listed in the table for `connectionLimit`. 

https://github.com/open-cluster-management/multicluster-observability-operator/blob/main/docs/MultiClusterObservability-CRD.md#cacheconfig

2021-06-09 02:57 UTC, clyang82 commented on apis/observability.json.adoc
> +__optional__|Max simultaneous connections of Memcached.|integer
Gotcha. we do not set the default value. it is set by observatorium-operator. I am OK w/o default value here. Thanks.

2021-06-09 02:58 UTC, clyang82 approved these changes
/lgtm

2021-06-09 03:23 UTC, merged