open-cluster-management/backlog#12184 Add pools
open-cluster-management/rhacm-docs pull request #2252
Opened 2021-06-17 17:00 UTC by cadawson

2021-06-17 17:18 UTC, chrisahl commented on clusters/cluster_claim.adoc
> +You must have the following prerequisites before claiiming a cluster from a cluster pool:
Typo. And also wondering what content to put in here for the ???  @showeimer ?

2021-06-17 17:24 UTC, showeimer commented on clusters/cluster_claim.adoc
> +*Required access*: Cluster administrator
I think this will be `admin`

2021-06-17 17:24 UTC, showeimer commented on clusters/cluster_pool_destroy.adoc
> +If you created a cluster pool and determine that you no longer need it, you can destroy the cluster pool. When you destroy a cluster pool, you release the resources of the hibernating clusters that a
I think I understand the `release the resources` part here; but should it explicitly state that the clusters in the cluster pool will be destroyed?

2021-06-17 17:24 UTC, showeimer commented on clusters/cluster_pool_manage.adoc
> +*Required access*: Cluster administrator
I think this also should be `admin`

2021-06-17 17:24 UTC, showeimer commented on clusters/cluster_pool_rel_img_update.adoc
> +*Required access*: Cluster administrator
`edit`

2021-06-17 17:24 UTC, showeimer commented on clusters/cluster_pool_rel_img_update.adoc
> +// CD: Why would you select an earlier version of the release image?
They can select any version technically.  It's probably not likely they will select an earlier version, but they can.

2021-06-17 17:24 UTC, showeimer commented on clusters/cluster_pool_rel_img_update.adoc
> +*Note:* This procedure does not update clusters from the cluster pool that are already claimed. It updates the release images for all of the remaining hibernating clusters that are created from this
Not sure about the second sentence, what will end up happening is for example.  If you had two unclaimed clusters in the pool that are version 4.6.1, and you update the release image for the pool, those clusters will not changes to the new version.  Only after the release image is updated, any new clusters created after that will be the new version.

2021-06-17 17:41 UTC, showeimer commented on clusters/cluster_claim.adoc
> +You must have the following prerequisites before claiiming a cluster from a cluster pool:
Not sure there is really a concrete pre-req, but a cluster can only be claimed from the cluster pool once it's available; the UI indicates the clusters as available.  So if there are 0 available clusters to claim, the Claim cluster button will be removed.

2021-06-17 17:48 UTC, showeimer commented on clusters/cluster_pool_destroy.adoc
> +If you created a cluster pool and determine that you no longer need it, you can destroy the cluster pool. When you destroy a cluster pool, you release the resources of the hibernating clusters that a
Also I wonder if we should log a "known issue" that when you destroy a cluster pool, it will disappear from the UI even though all of the unclaimed clusters haven't finished destroying yet, so you lose ability to see them in UI.

2021-06-17 18:24 UTC, chrisahl commented on clusters/cluster_pool_rel_img_update.adoc
> +// CD: Are you limited to 4.8 images, or later for this, or can you use 4.7 versions?
Cluster pools will work with 4.7

2021-06-17 18:25 UTC, chrisahl commented on clusters/cluster_pool_rel_img_update.adoc
> +// CD: Why would you select an earlier version of the release image?
Some users need to use a specific OCP release image that is not necessarily the latest OCP image

2021-06-17 18:27 UTC, chrisahl requested changes
Looks pretty good.  Only had a few comments.

2021-06-17 20:56 UTC, chrisahl commented on clusters/cluster_pool_rel_img_update.adoc
> +*Note:* This procedure does not update clusters from the cluster pool that are already claimed. It updates the release images for all of the remaining hibernating clusters that are created from this
So this is my misunderstanding of what happens when the image it updated for the cluster pool.  

New proposal:
*Note:* This procedure does not update clusters from the cluster pool that are already claimed and it does not update clusters in the pool that are hibernating.   Only new clusters that are created for the cluster pool will use the new release image after you complete this procedure.

2021-06-18 15:06 UTC, cadawson commented on clusters/cluster_claim.adoc
> +*Required access*: Cluster administrator
In the docs, we are using either "cluster administrator" or "cluster-admin". In most cases, the "cluster administrator" format is used. I would prefer to leave these as they are, for consistency.

2021-06-18 15:06 UTC, cadawson commented on clusters/cluster_pool_destroy.adoc
> +If you created a cluster pool and determine that you no longer need it, you can destroy the cluster pool. When you destroy a cluster pool, you release the resources of the hibernating clusters that a
Is this a "problem" that is likely to be fixed, or is it working as designed? A known issue is normally something that is a problem that is likely to be fixed or change soon. This case sounds like it might be just how it works, so I added a sentence in the procedure to point that out. See if that addresses the concern, or if I am missing the point.

2021-06-18 15:06 UTC, cadawson commented on clusters/cluster_pool_rel_img_update.adoc
> +*Note:* This procedure does not update clusters from the cluster pool that are already claimed. It updates the release images for all of the remaining hibernating clusters that are created from this
I misunderstood this one, but it is updated now.

2021-06-18 15:12 UTC, cadawson commented on clusters/cluster_pool_manage.adoc
> +*Required access*: Cluster administrator
In the docs, we are using either "cluster administrator" or "cluster-admin". In most cases, the "cluster administrator" format is used. I would prefer to leave these as they are, for consistency.

2021-06-18 15:14 UTC, cadawson commented
Addressed your comments in this PR @chrisahl and @showeimer . I know you both might be out today, so don't stress about this today. but please take a look when you have a chance. Thanks!

2021-06-21 12:23 UTC, chrisahl commented on clusters/cluster_pool_destroy.adoc
> +If you created a cluster pool and determine that you no longer need it, you can destroy the cluster pool. When you destroy a cluster pool, you release the resources of the hibernating clusters that a
I think this is working as designed.  Would changing the description help?

If you created a cluster pool and determine that you no longer need it, you can destroy the cluster pool. When you destroy a cluster pool, all the unclaimed hibernating clusters will be destroyed and their resources will be released.

2021-06-21 13:12 UTC, chrisahl requested changes
I added a comment about destroy cluster pool

2021-06-21 13:30 UTC, showeimer commented on clusters/cluster_claim.adoc
> +*Required access*: Cluster administrator
So a `cluster-admin` and an `admin` are two distinct roles in OpenShift

2021-06-21 13:31 UTC, showeimer commented on clusters/cluster_pool_destroy.adoc
> +If you created a cluster pool and determine that you no longer need it, you can destroy the cluster pool. When you destroy a cluster pool, you release the resources of the hibernating clusters that a
@chrisahl it kind of is working as designed, but imo the UX is a bit odd that the cluster pool is disappeared from the screen before all the unclaimed clusters are destroyed, I have an enhancement opened for Hive:  https://issues.redhat.com/browse/HIVE-1557

2021-06-21 13:31 UTC, showeimer commented on clusters/cluster_pool_manage.adoc
> +*Required access*: Cluster administrator
See above.

2021-06-22 12:56 UTC, cadawson commented on clusters/cluster_claim.adoc
> +*Required access*: Cluster administrator
Understand that now. Thanks.

2021-06-22 12:56 UTC, cadawson commented on clusters/cluster_pool_manage.adoc
> +*Required access*: Cluster administrator
Got it now. Updated both of those.

2021-06-22 12:56 UTC, cadawson commented on clusters/cluster_pool_destroy.adoc
> +If you created a cluster pool and determine that you no longer need it, you can destroy the cluster pool. When you destroy a cluster pool, you release the resources of the hibernating clusters that a
Does the sentence that I added to the file cover this one: `The clusters in the destroyed cluster pool are removed from the console while they are destroyed.`?

2021-06-22 12:57 UTC, cadawson commented
New updates in @showeimer and @chrisahl . Hopefully, that resolves the requests. Thanks!

2021-06-22 14:24 UTC, chrisahl approved these changes

2021-06-22 18:13 UTC, cadawson commented on clusters/cluster_pool_destroy.adoc
> +If you created a cluster pool and determine that you no longer need it, you can destroy the cluster pool. When you destroy a cluster pool, you release the resources of the hibernating clusters that a
Sorry @chrisahl . I thought the issue there was based on the clusters disappearing from the UI. I tweaked the description a little to align more with your comment.

2021-06-22 19:23 UTC, chrisahl approved these changes

2021-06-22 21:12 UTC, showeimer approved these changes

2021-06-23 00:57 UTC, ldpliu commented on clusters/cluster_pool_manage.adoc
> +. Optional: Select a cluster set name if you want the RBAC roles for your cluster pool to share the role assignments of an existing cluster set.
Note: If you are non-cluster-admin, you must specify the clusterset, if not, the create request will be forbiden. if there is no clusterset can be selected, please connect cluster-admin,he need create a clusterset and give clusterset admin permission to you.

2021-06-23 00:57 UTC, ldpliu commented on clusters/cluster_pool_manage.adoc
> +. Enter the namespace where you want to create your cluster pool. You can select an existing namespace from the list, or type the name of a new one to create one. The cluster pool does not have to be
add note here: 
when you create a clusterpool in a clusterset, the whole namespace admin permission will be shared to clusterset admin users. the namespace view permission will be shared to clusterset view users.

2021-06-28 13:28 UTC, cadawson commented
Hi @ldpliu . I added the notes that you requested to clarify the permissions limitations. Please see if that addresses your concerns. Thank you!

2021-06-29 07:06 UTC, ldpliu commented on clusters/cluster_pool_manage.adoc
> +. Enter the namespace where you want to create your cluster pool. You can select an existing namespace from the list, or type the name of a new one to create one. The cluster pool does not have to be
As we still discuss the clusterpool namespace permission in https://github.com/open-cluster-management/backlog/issues/13734#issuecomment-869577198
So we may need to wait the solution done, then we can decide what should be add here.
@cadawson you could also merge it first, if there is something changed, I will submit another pr to trace it.

2021-07-01 03:50 UTC, ldpliu commented on clusters/cluster_pool_manage.adoc
> +. Enter the namespace where you want to create your cluster pool. You can select an existing namespace from the list, or type the name of a new one to create one. The cluster pool does not have to be
we will keep the current change, and we should add more notice in this part. So the desired description should be:
` 
When you create a cluster pool in a cluster set, the `namespace admin` permission is applied to all of the users with `clusterset admin` permissions for the namespace where you add the cluster pool. Similarly, the `namespace view` permission is applied to the users with `clusterset view` permissions. 

So as cluster admin, you should create one namespace for each team to create clusterpool.
`
@qiujian16 please also review the description here.

2021-07-06 16:45 UTC, cadawson commented on clusters/cluster_pool_manage.adoc
> +. Enter the namespace where you want to create your cluster pool. You can select an existing namespace from the list, or type the name of a new one to create one. The cluster pool does not have to be
I think this is resolved, @ldpliu , is that correct? @qiujian16 , are you ok with the updates?

2021-07-07 14:29 UTC, dockerymick requested changes

2021-07-07 14:29 UTC, dockerymick commented on clusters/cluster_claim.adoc
> +ClusterClaim resources are used to check out clusters from cluster pools. After a cluster is checked out from a cluster pool, the checked out cluster is brought to a ready state. The cluster pool aut
I recommend ClusterClaim be monospaced

2021-07-07 14:29 UTC, dockerymick commented on clusters/cluster_claim.adoc
> +*Required access*: admin
change admin to Administrator

2021-07-07 14:29 UTC, dockerymick commented on clusters/cluster_claim.adoc
> +* A cluster pool with available clusters to claim. See xref:../clusters/cluster_pool_manage.adoc#creating_a_cluster_pool.adoc[Creating a cluster pool] for information about how to create a cluster po
Since there is only one prerequisite, change Prerequisites to Prerequisite. 

I also recommend removing the bullet point:

You must have a cluster pool with available clusters to claim.

2021-07-07 14:29 UTC, dockerymick commented on clusters/cluster_claim.adoc
> +To checkout a cluster from the cluster pool, resume the cluster and claim it as one of your managed clusters.
Add "Complete the following steps to claim a cluster:"

2021-07-07 14:29 UTC, dockerymick commented on clusters/cluster_claim.adoc
> +. Select the *Cluster pools* tab.
Cluster pool should be italicized

2021-07-07 14:29 UTC, dockerymick commented on clusters/cluster_claim.adoc
> +. The claimed cluster comes out of hibernation and appears in the *Managed Cluster* tab with a status of `Resuming`.  After the cluster reaches a status of  `Ready`, the cluster is available for use.
Remove the period prior to "The". This works better as a concluding statement rather than another task.

2021-07-07 14:29 UTC, dockerymick commented on clusters/cluster_pool_destroy.adoc
> +. Select the *Cluster pools* tab.
Italicize Cluster pool

2021-07-07 14:29 UTC, dockerymick commented on clusters/cluster_pool_destroy.adoc
> +*Tip:* You can destroy multiple cluster pools with one action by selecting the box for each of the the cluster pools and using the _Actions_ menu to destroy the selected cluster pools.
I would move the tip to line 17 

Then I recommend adding a concluding sentence that reads: Your cluster pool is deleted.

2021-07-07 14:29 UTC, dockerymick commented on clusters/cluster_pool_manage.adoc
> +ClusterClaim resources are used to checkout clusters from cluster pools. After a cluster is checked out from a cluster pool, the checked out cluster is resumed and brought to a ready state. The clust
I recommend monospacing ClusterClaim

2021-07-07 14:29 UTC, dockerymick commented on clusters/cluster_pool_manage.adoc
> +ClusterClaim resources are used to checkout clusters from cluster pools. After a cluster is checked out from a cluster pool, the checked out cluster is resumed and brought to a ready state. The clust
Remove 'will' 

The cluster pool automatically creates a new hibernated cluster to replace the claimed one in the cluster pool.

2021-07-07 14:29 UTC, dockerymick commented on clusters/cluster_pool_manage.adoc
> +You must have the following prerequisites before creating a cluster pool:
I would move the Prerequisites before Creating a cluster pool. I would also add an inline link for prerequisites

Change admin to Administrator

2021-07-07 14:29 UTC, dockerymick commented on clusters/cluster_pool_manage.adoc
> +* A deployed {product-title} hub cluster
Add a period at the end of this statement

2021-07-07 14:29 UTC, dockerymick commented on clusters/cluster_pool_manage.adoc
> +. Select the *Cluster pools* tab to view cluster pools that you can access.
Italicize Cluster pool

2021-07-07 14:29 UTC, dockerymick commented on clusters/cluster_pool_manage.adoc
> +*Note:* If you do not have `cluster admin` permissions, you must select a cluster set. The request to create a cluster set is rejected as forbidden if you do not include the cluster set name in this
i recommend bolding optional, but i understand why you might choose not too considering the bold note that comes right after


The request to create a cluster set is rejected and forbidden if you do not include the cluster set name in this situation.

2021-07-07 14:29 UTC, dockerymick commented on clusters/cluster_pool_manage.adoc
> +10. After all of the information is entered, select *Create* to create the cluster pool. After at least one cluster is available in the pool, a *Claim cluster* button appears.
This step should be on line 64 and also remove `10`, there should only be a period prior to the task.

2021-07-07 14:29 UTC, dockerymick commented on clusters/cluster_pool_manage.adoc
> +
This inline links are not working. All of the links after Creating a cluster pool doesn't work. Were you attempting to link to the other files or are you planning to add more sections?

2021-07-07 14:29 UTC, dockerymick commented on clusters/cluster_pool_rel_img_update.adoc
> +. Select the *Cluster pools* tab.
Cluster pool should be italicized

2021-07-07 14:29 UTC, dockerymick commented on clusters/cluster_pool_rel_img_update.adoc
> +*Tip:* You can update the release image for multiple cluster pools with one action by selecting the box for each of the the cluster pools and using the _Actions_ menu to update the release image for
Move this tip to line 17 and conclude the doc with the following statement:

The cluster pool release image is updated.

2021-07-07 14:29 UTC, dockerymick commented on clusters/cluster_pool_scale.adoc
> +. Select the *Cluster pools* tab.
Cluster pools should be italicized

2021-07-07 14:29 UTC, dockerymick commented on clusters/cluster_pool_scale.adoc
> +. Select *Scale* to commit the change.
Add a conclusion statement similar to the following sentence: Your cluster pools are scaled.

2021-07-08 15:18 UTC, dockerymick reviewed
I completed a review of the PR yesterday, please let me know if you do not see my comments @cadawson

2021-07-09 06:49 UTC, qiujian16 commented
/approve

2021-07-09 06:49 UTC, qiujian16 commented
/lgtm

2021-07-12 16:25 UTC, cadawson commented on clusters/cluster_claim.adoc
> +*Required access*: admin
Admin is the name of the role. Are you still using administrator? Just want to be consistent. Changed to administrator.

2021-07-12 17:03 UTC, cadawson reviewed
Thank you for the review. Always appreciated!

2021-07-12 17:03 UTC, cadawson commented on clusters/cluster_claim.adoc
> +. The claimed cluster comes out of hibernation and appears in the *Managed Cluster* tab with a status of `Resuming`.  After the cluster reaches a status of  `Ready`, the cluster is available for use.
Good catch. It was intended to be the concluding sentence.

2021-07-12 17:03 UTC, cadawson commented on clusters/cluster_pool_destroy.adoc
> +*Tip:* You can destroy multiple cluster pools with one action by selecting the box for each of the the cluster pools and using the _Actions_ menu to destroy the selected cluster pools.
Trying to keep the procedure clean without adding the tip there. Added the conclusion.

2021-07-12 17:03 UTC, cadawson commented on clusters/cluster_pool_manage.adoc
> +
Was trying to link the files, but I will have to look at this.

2021-07-12 17:03 UTC, cadawson commented on clusters/cluster_pool_manage.adoc
> +*Note:* If you do not have `cluster admin` permissions, you must select a cluster set. The request to create a cluster set is rejected as forbidden if you do not include the cluster set name in this
Clarified this  a little.

2021-07-12 17:03 UTC, cadawson commented on clusters/cluster_pool_manage.adoc
> +10. After all of the information is entered, select *Create* to create the cluster pool. After at least one cluster is available in the pool, a *Claim cluster* button appears.
I agree with the 10. That was a miss. 
For the step, the references are tied to the information that they are entering in the second-to-last step. I think it is in the right order.

2021-07-12 17:03 UTC, cadawson commented on clusters/cluster_pool_rel_img_update.adoc
> +*Tip:* You can update the release image for multiple cluster pools with one action by selecting the box for each of the the cluster pools and using the _Actions_ menu to update the release image for
Added the conclusion. Trying to keep the procedure clean, so not moving the tip.

2021-07-15 14:19 UTC, merged