open-cluster-management/backlog#13052 Add hibernate
open-cluster-management/rhacm-docs pull request #2261
Opened 2021-06-18 18:12 UTC by cadawson

2021-06-22 13:06 UTC, showeimer commented on clusters/hibernating_a_cluster.adoc
> +*Tip:* You can resume multiple clusters by selecting the clusters that you want to resume on the _Clusters_ page, and selecting *Actions* > *Resume clusters*.
I think we should add how to do this from command line:

To Hibernate:

`oc edit clusterdeployment <name of cluster> -n <namespace of cluster>`

Change the `spec.powerState` value to `Hibernating`

To resume:

`oc edit clusterdeployment <name of cluster> -n <namespace of cluster>`

Change the `spec.powerState` value to `Running`

2021-06-22 13:07 UTC, showeimer commented on clusters/hibernating_a_cluster.adoc
> +*Tip:* You can resume multiple clusters by selecting the clusters that you want to resume on the _Clusters_ page, and selecting *Actions* > *Resume clusters*.
To check Hibernation status:

`oc get clusterdeployment <name of cluster> -n <namespace of cluster> -o yaml`

View the `status.conditions`, with `type=Hibernating`

2021-06-22 13:50 UTC, chrisahl commented on clusters/hibernating_a_cluster.adoc
> +*Tip:* You can resume multiple clusters by selecting the clusters that you want to resume on the _Clusters_ page, and selecting *Actions* > *Resume clusters*.
I agree, would be good to add non UI info

2021-06-22 14:53 UTC, cadawson commented on clusters/hibernating_a_cluster.adoc
> +*Tip:* You can resume multiple clusters by selecting the clusters that you want to resume on the _Clusters_ page, and selecting *Actions* > *Resume clusters*.
Added the non-UI steps.

2021-06-22 18:18 UTC, showeimer commented on clusters/hibernating_a_cluster.adoc
> +. Verify that the value of `status.conditions` for the cluster is `type=Hibernating` by entering the following command:
I think it's less about `verify the value`; the `status.conditions` contains a list of all kinds of conditions; and the one the user would look for is labeled as a `type` of `Hibernating`; and they can see what the status of the Hibernation is.

2021-06-22 19:02 UTC, chrisahl commented on clusters/hibernating_a_cluster.adoc
> +. Verify that the value of `status.conditions` for the cluster is `type=Hibernating` by entering the following command:
For example, looking at a ClusterDeployment for a running cluster: 
![image](https://user-images.githubusercontent.com/32707829/122983458-08a5a680-d36a-11eb-80ae-9bab268d1c8a.png)

In the process of hibernating:
![image](https://user-images.githubusercontent.com/32707829/122983734-4e626f00-d36a-11eb-983b-301687033201.png)

fully hibernated:
![image](https://user-images.githubusercontent.com/32707829/122984288-d6e10f80-d36a-11eb-944f-4394ee2819f1.png)

2021-06-28 12:28 UTC, cadawson commented
Tweaked the verification step of the CLI, as requested. See if the new step fits better. @showeimer

2021-06-28 12:30 UTC, chrisahl approved these changes

2021-07-07 15:58 UTC, jnpacker commented on clusters/hibernating_a_cluster.adoc
> +* VMware vSphere
This was my bad. VMware and OpenStack are not supported.

2021-07-07 16:53 UTC, dockerymick requested changes

2021-07-07 16:53 UTC, dockerymick commented on clusters/hibernating_a_cluster.adoc
> +You can hibernate a cluster that was created using {product-title} to conserve resources. A hibernating cluster requires significantly fewer resources than one that is running, so you can potentially
I would remove `easily` bc it seems subjective

2021-07-07 16:53 UTC, dockerymick commented on clusters/hibernating_a_cluster.adoc
> +. From the {product-title-short} navigation menu, select *Infrastructure* > *Clusters*. Ensure that the *Manage clusters* tab is selected.
Italicize Manage clusters

2021-07-07 16:53 UTC, dockerymick commented on clusters/hibernating_a_cluster.adoc
> +. Select *Hibernate cluster* from the the _Options_ menu for that cluster. *Note:* If the *Hibernate cluster* option is not available, you cannot hibernate the cluster. This can happen when the clust
I recommend italicizing Hibernate cluster in the Note only

Also update: This can happen when the cluster was imported, and not created by {product-title-short}.

TO 

This can happen when the cluster is imported, and not created by {product-title-short}.

2021-07-07 16:53 UTC, dockerymick commented on clusters/hibernating_a_cluster.adoc
> +*Tip:* You can hibernate multiple clusters by selecting the clusters that you want to hibernate on the _Clusters_ page, and selecting *Actions* > *Hibernate clusters*.
I recommend moving this tip to line 20

Also add a concluding sentence that reads, You set your cluster to hibernate from the {product-title-short} console.

2021-07-07 16:53 UTC, dockerymick commented on clusters/hibernating_a_cluster.adoc
> +. From the {product-title-short} navigation menu, select *Infrastructure* > *Clusters*. Ensure that the *Manage clusters* tab is selected.
Italicize Manage clusters

2021-07-07 16:53 UTC, dockerymick commented on clusters/hibernating_a_cluster.adoc
> +*Tip:* You can resume multiple clusters by selecting the clusters that you want to resume on the _Clusters_ page, and selecting *Actions* > *Resume clusters*.
I would move the tip to line 66 or it could be a part of line 65

2021-07-12 15:48 UTC, cadawson commented on clusters/hibernating_a_cluster.adoc
> +*Tip:* You can resume multiple clusters by selecting the clusters that you want to resume on the _Clusters_ page, and selecting *Actions* > *Resume clusters*.
I see your thought here. The reason that I didn't do that is to keep the procedure clean. The tip is a different path, so I didn't want to muddy the waters by adding it in the middle of the other procedure. By adding it at the end, I am hoping to avoid that confusion.

2021-07-12 15:50 UTC, cadawson commented on clusters/hibernating_a_cluster.adoc
> +* VMware vSphere
Removed VMware and OpenStack.

2021-07-12 16:00 UTC, cadawson commented on clusters/hibernating_a_cluster.adoc
> +. Select *Hibernate cluster* from the the _Options_ menu for that cluster. *Note:* If the *Hibernate cluster* option is not available, you cannot hibernate the cluster. This can happen when the clust
We should probably discuss whether to use italics or bold. Changed it for now.

2021-07-12 16:03 UTC, cadawson commented on clusters/hibernating_a_cluster.adoc
> +*Tip:* You can hibernate multiple clusters by selecting the clusters that you want to hibernate on the _Clusters_ page, and selecting *Actions* > *Hibernate clusters*.
Added a conclusion

2021-07-13 15:03 UTC, merged