update section of ODF storage config in observability
open-cluster-management/rhacm-docs pull request #2330
Opened 2021-07-06 12:55 UTC by hchenxa

Signed-off-by: hchenxa <huichen@redhat.com>

2021-07-06 12:56 UTC, hchenxa commented
@clyang82 please help to double review

2021-07-06 12:57 UTC, hchenxa commented
/assign @clyang82

2021-07-06 14:48 UTC, clyang82 commented
Thanks @hchenxa for your help to refine our document.

2021-07-06 14:49 UTC, clyang82 commented on observability/observability_enable.adoc
> +YOUR_ODF_ENDPOINT=${$(oc get noobaa -n openshift-storage noobaa -o jsonpath="{.status.services.serviceS3.externalDNS[*]}")#*//}
Does it have the same value as customer described here - https://bugzilla.redhat.com/show_bug.cgi?id=1919690?

2021-07-07 03:46 UTC, clyang82 commented
/lgtm

2021-07-08 07:05 UTC, clyang82 commented
The structure is wrong. the current structure has:
`a. View the following examples of secrets for the supported object stores:`
and `b. You can retrieve the S3 access key and secret key for your cloud providers with the following commands`

I do not think we need `b.`

@hchenxa Can you help to correct it? You current PR format is not correct. Thanks.

2021-07-08 08:49 UTC, clyang82 commented on observability/observability_enable.adoc
> +YOUR_ODF_ENDPOINT=${$(oc get noobaa -n openshift-storage noobaa -o jsonpath="{.status.services.serviceS3.externalDNS[*]}")#*//}
add ` echo $YOUR_ODF_BUCKET`

2021-07-08 08:49 UTC, clyang82 commented on observability/observability_enable.adoc
>  ----
add `echo $YOUR_ODF_BUCKET`

2021-07-08 10:06 UTC, hchenxa commented on observability/observability_enable.adoc
>  ----
updated

2021-07-08 12:57 UTC, clyang82 commented
/lgtm

2021-08-06 06:24 UTC, clyang82 commented
/lgtm

/assign @dockerymick

2021-08-06 06:25 UTC, hchenxa commented
@dockerymick could u help to double review?

2021-08-06 12:19 UTC, dockerymick commented on observability/observability_enable.adoc
> +.. For {product-title-short}, your secret might resemble the following file:
Since these are not ordered tasks, numbers are not required. Changing this back to bullet points.

2021-08-06 12:28 UTC, dockerymick commented on observability/observability_enable.adoc
> -.. You can retrieve the S3 access key and secret key for your cloud providers with the following commands:
@hchenxa This part was at the end bc I assumed that each object store would have similar instructions. I figured it would be repetitive. I see that you only documented how to retrieve the S3 access key and secret key for RHODF. 

For consistency, instructions to retrieve S3 access key and secret key for all of the examples. We should keep the length of this doc in mind.

2021-08-06 12:34 UTC, dockerymick commented on observability/observability_enable.adoc
> +You can retrieve the Red Hat OpenShift Data Foundation S3 access key and secret key for your cloud providers with the following commands:
I changed this from ODF to the full product name. According to the Official product list, the full product name must be written: https://docs.google.com/spreadsheets/d/1DLS_lS3VKidgZIvcLmLp9BoiqptkvqHWfe1D5FD2kfk/edit#gid=1259317633

2021-08-06 12:35 UTC, dockerymick requested changes
Thanks for creating this PR @hchenxa. Is there a doc issue created for this? I also left a couple of comments

2021-08-18 20:17 UTC, dockerymick approved these changes

2021-08-18 22:00 UTC, merged