Organize structure of observability
open-cluster-management/rhacm-docs pull request #2333
Opened 2021-07-06 18:42 UTC by dockerymick

Needed to create a new pr because there was a merge conflict

Ref open-cluster-management/backlog#13367

move observability-pod-capacity-requests to observability_enable.adoc page.
Users should know the resource consuming before enabling the service, so move it to this page makes more sense.
remove observability-certificates,Observability certificates .
Should we have a new page about observability cert? @marcolan018
remove overview-page-observe,Observe environments Overview page, it should be coverd by https://github.com/open-cluster-management/rhacm-docs/blob/2.3_stage/console/console.adoc#home . @jlpadilla

2021-07-06 20:42 UTC, swopebe commented on console/console.adoc
> +* Many clickable elements on the dashboard open a search for related resources. Click on a provider card to view information for clusters from a single provider.
I would say line 36 is not parallel with the others, in that a full, complete sentence in a list of brief and concise elements.

If you want to keep it, just take it out of the list? Like this:

* Pod status

Additionally, you can view many...

2021-07-06 20:42 UTC, swopebe approved these changes

2021-07-07 01:33 UTC, haoqing0110 requested changes
Plz also move https://github.com/open-cluster-management/rhacm-docs/pull/2333/files#diff-aac2a6cf3ce3ed1c0a1737fbcfa410c60c1d451e96920b7176fe0aa2492d3a77L68-L234 to  observability/observability_enable.adoc. Refer to orignal PR https://github.com/open-cluster-management/rhacm-docs/pull/2309/files#diff-100c4beedf58f685aa241b7dd2ad51cf33a128ec1390278895aa751b23e9f629R22

2021-07-07 01:59 UTC, haoqing0110 commented
@dockerymick plz ignore above comments, lgtm!

2021-07-07 01:59 UTC, dockerymick commented
I disagree with your suggestion bc the reader would see the table prior to reading the Enabling observability documentation. The navigation for 2.3 would be similar to the [2.2 documentation](https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.2/html-single/observing_environments/index?lb_target=production#observing-environments). 

I will also update the 2.2 doc so that the navigation displays all of the sections. This is how the 2.3 navigation appears:
![Screen Shot 2021-07-06 at 9 59 15 PM](https://user-images.githubusercontent.com/60616885/124688833-6fb47680-dea5-11eb-9443-cae751c0264c.png)

2021-07-07 01:59 UTC, haoqing0110 approved these changes
/approve

2021-07-07 02:27 UTC, dockerymick commented
@swopebe @haoqing0110 thanks for the reviews, suggestions, and approvals! Merging this PR

2021-07-07 02:27 UTC, merged