rhacm updates for power
open-cluster-management/rhacm-docs pull request #2339
Opened 2021-07-07 08:58 UTC by HashmathM

Reference 
https://docs.google.com/document/d/15j3xpkw7ZzMulHdvF0-j-7q29OyCMeNafcX5ib61BBM/edit?usp=sharing

QE- @jaywcarman 
Please review this RHACM Power updates for upcoming release 
Thanks

2021-07-07 13:16 UTC, swopebe commented
Please link this to the doc issue for us? Thank you.

2021-07-07 14:20 UTC, jaywcarman requested changes

2021-07-07 14:20 UTC, jaywcarman commented on install/plan_capacity.adoc
> +** vCPU: 4
On Power, minimum vCPUs is going to be dependent upon SMT level. I can provide a table later today. For reference, the [OCS Planning Documentation, section 6.3.1](https://access.redhat.com/documentation/en-us/red_hat_openshift_container_storage/4.7/pdf/planning_your_deployment/Red_Hat_OpenShift_Container_Storage-4.7-Planning_your_deployment-en-US.pdf) already has something similar.

2021-07-07 14:21 UTC, jaywcarman commented
@swopebe https://github.com/open-cluster-management/backlog/issues/11269

fyi @cadawson

2021-07-08 00:23 UTC, swopebe commented
@cadawson I will take this since they have been kind enough to send most of the changes. I flipped the issue to myself. You have so many so this is a clear one I can take.

2021-07-08 00:23 UTC, swopebe commented
Will review Thurs.

2021-07-08 13:55 UTC, swopebe commented on install/plan_capacity.adoc
> +** vCPU: 4
link changes here -- committed

2021-07-08 20:04 UTC, cadawson commented
Talked to Brandi. Taking this one back, because I have more history with it.

2021-07-08 20:06 UTC, cadawson commented
Compared the changes to the review comments. They are consistent. Changed the links to target the portal, since the OCP docs outside of the Customer Portal will be moving.

2021-07-08 20:35 UTC, jaywcarman commented on clusters/supported_clouds.adoc
> +* See https://access.redhat.com/documentation/en-us/openshift_container_platform/4.7/html/installing/installing-on-ibm-power-systems#installing-ibm-power[Installing a cluster on IBM Power Systems (Te
There have been some recent Power branding guideline updates, and I think `IBM Power` is preferred over `IBM Power Systems`. Since OCP uses `IBM Power Systems`, though, perhaps it would be best to be consistent. To be picky, it should actually be `IBM Power systems`, without `systems` capitalized.

Thoughts @cadawson and @jwcroppe ?

2021-07-08 20:35 UTC, jaywcarman commented on install/plan_capacity.adoc
> +** vCPU: 4
I was thinking something like this:
```
* Node count: 3                                                                                                                                                                                                                                               
* Availability zones: 3                                                                                                                                                                                                                                       
* Instance size:                                                                                                                                                                                                                                              
** Memory: 16 GB                                                                                                                                                                                                                                              
** Storage size: 120 GB                                                                                                                                                                                                                                       
** vCPU: IBM Power systems provide simultaneous multithreading levels of 1, 2, 4 or 8 for each core which correspond to the number of vCPUs recommended in the table below.                                                                                   
|===                                                                                                                                                                                                                                                          
|SMT level|SMT=1|SMT=2|SMT=4|SMT=8|                                                                                                                                                                                                                           
|recommended vCPUs|1|1|2|4|                                                                                                                                                                                                                                    
|===
```
disclaimer: I don't have adoc experience, so my table syntax might not be perfect.

Please double check my "Power math" @jwcroppe :)

2021-07-09 12:43 UTC, swopebe commented
I started on this because it sat without an assignee or reviewer @cadawson: https://github.com/open-cluster-management/backlog/issues/11269#issuecomment-876462585

2021-07-09 15:18 UTC, cadawson commented on clusters/supported_clouds.adoc
> +* See https://access.redhat.com/documentation/en-us/openshift_container_platform/4.7/html/installing/installing-on-ibm-power-systems#installing-ibm-power[Installing a cluster on IBM Power Systems (Te
I know that IBM Power changes its branding fairly frequently. I did a quick search, and most of the IBM sites still use IBM Power Systems. For example, https://www.ibm.com/partnerworld/systems/power, https://www.ibm.com/it-infrastructure/power. It's possible that they haven't gotten around to changing them yet. The trademarks list for IBM (https://www.ibm.com/legal/copytrade) only lists "Power" as a trademark, and not "Power Systems". I think we could use IBM Power Systems and be safe, but it would not be difficult to get ahead of IBM Power systems, if we need to. I don't know the details of the branding change. @jaywcarman

2021-07-09 15:46 UTC, jwcroppe commented on clusters/supported_clouds.adoc
> +* See https://access.redhat.com/documentation/en-us/openshift_container_platform/4.7/html/installing/installing-on-ibm-power-systems#installing-ibm-power[Installing a cluster on IBM Power Systems (Te
> I know that IBM Power changes its branding fairly frequently. I did a quick search, and most of the IBM sites still use IBM Power Systems. For example, https://www.ibm.com/partnerworld/systems/power, https://www.ibm.com/it-infrastructure/power. It's possible that they haven't gotten around to changing them yet. The trademarks list for IBM (https://www.ibm.com/legal/copytrade) only lists "Power" as a trademark, and not "Power Systems". I think we could use IBM Power Systems and be safe, but it would not be difficult to get ahead of IBM Power systems, if we need to. I don't know the details of the branding change. @jaywcarman

Just confirmed with marketing folks.  When referring to the "server family", the new name is **"IBM Power"** (i.e., no longer IBM Power Systems).  The architecture was originally called "POWER" and is now named **"Power"**.

Let's try to use the new names in the documentation.

2021-07-09 20:08 UTC, cadawson commented on clusters/supported_clouds.adoc
> +* See https://access.redhat.com/documentation/en-us/openshift_container_platform/4.7/html/installing/installing-on-ibm-power-systems#installing-ibm-power[Installing a cluster on IBM Power Systems (Te
The links that we have in this file is to a topic called, "...IBM Power Systems". To hopefully avoid confusing people with a topic that has a different name, I changed our links to "...IBM Power systems". They will probably eventually change that topic name, but I am not sure how long that will take. Sound ok? @jwcroppe and @jaywcarman

2021-07-09 21:36 UTC, jaywcarman commented on install/plan_capacity.adoc
> +** vCPU: 4
@jwcroppe helped me refine this to make the core/SMT/vCPU relationship more clear.

Also, I don't think availability zones applies since these are not specific to a cloud service.

```
 * Node count: 3
 * Instance size:
 ** Memory: 16 GB
 ** Storage size: 120 GB
 ** vCPU: 16

IBM Power systems provide simultaneous multithreading (SMT) levels of 1, 2, 4 or 8 for each core. The required 16 vCPUs can be achieved with different numbers of cores depending on the SMT level.

 *** 2 cores running in SMT-8 -> 16 vCPUs (default for PowerVM systems)
 *** 4 cores running in SMT-4 -> 16 vCPUs (e.g., for non-PowerVM systems)
 ```
 
 I pushed this version up to my fork in order to view it rendered:
 https://github.com/jaywcarman/rhacm-docs/blob/power-2/install/plan_capacity.adoc#settings-for-creating-an-ocp-cluster-on-ibm-power-systems

2021-07-12 14:17 UTC, cadawson commented on install/plan_capacity.adoc
> +** vCPU: 4
@jaywcarman @jwcroppe I drafted a section for this in the PR. See what you think of that, and let me know if that will work.

2021-07-12 14:47 UTC, jwcroppe commented on install/plan_capacity.adoc
> +** vCPU: 4
@cadawson I met with @jaywcarman last Friday to discuss this and I believe he has some suggestions in terms of how we can word this section.  Please refer to this - https://github.com/jaywcarman/rhacm-docs/blob/power-2/install/plan_capacity.adoc#settings-for-creating-an-ocp-cluster-on-ibm-power-systems

2021-07-13 11:25 UTC, jaywcarman commented on install/plan_capacity.adoc
> +** vCPU: 4
@cadawson @jwcroppe sorry for the confusion. The version Joe linked to in my fork is this:
```
 * Node count: 3
 * Instance size:
 ** Memory: 16 GB
 ** Storage size: 120 GB
 ** vCPU: 16

IBM Power systems provide simultaneous multithreading (SMT) levels of 1, 2, 4 or 8 for each core. The required 16 vCPUs can be achieved with different numbers of cores depending on the SMT level.

 *** 2 cores running in SMT-8 -> 16 vCPUs (default for PowerVM systems)
 *** 4 cores running in SMT-4 -> 16 vCPUs (e.g., for non-PowerVM systems)
```

@cadawson We're thinking the table with all of the SMT levels is a bit confusing. Users will probably only run in two ways: 2 cores @ SMT-8, or 4 cores @ SMT-4. So in the above version ^^ there are two bullet points showing this without the extra info.

(this is the version in the conversation above https://github.com/open-cluster-management/rhacm-docs/pull/2339#discussion_r667222760)

2021-07-14 20:18 UTC, cadawson commented on install/plan_capacity.adoc
> +** vCPU: 4
That was strange @jwcroppe and @jaywcarman . I saw Joe's comment about the new approach after I created the table. Anyway, take a look at the refreshed PR to see the updates. Should we keep the reference for more information about SMT, or is it unnecessary?

2021-07-14 20:37 UTC, jaywcarman approved these changes
LGTM

2021-07-14 22:46 UTC, jwcroppe commented on install/plan_capacity.adoc
> +*** 2 cores running on SMT-8 provides the required 16 vCPUs. This is the default configuration for systems that are running IBM PowerVM.
Maybe we can revise to...

*** 2 cores running on SMT-8 (default for PowerVM-based systems) provides the required 16 vCPUs.

2021-07-14 22:47 UTC, jwcroppe commented on install/plan_capacity.adoc
> +*** 4 cores running on SMT-4 provides the required 16 vCPUs. This is the default configuration for system that are not running IBM PowerVM.
Optimize to...

*** 4 cores running on SMT-4 provides the required 16 vCPUs.

2021-07-14 22:48 UTC, jwcroppe approved these changes
Embedded comments left - approve pending changes are made.

2021-07-15 19:57 UTC, cadawson commented
@swopebe : Can you review this, particularly because there is an update to the install/plan_capacity.adoc file. Thanks!

2021-07-15 21:09 UTC, jwcroppe commented
@cadawson Did the changes I proposed above make sense?  Thanks again in advance!

2021-07-16 12:23 UTC, cadawson commented on install/plan_capacity.adoc
> +*** 2 cores running on SMT-8 provides the required 16 vCPUs. This is the default configuration for systems that are running IBM PowerVM.
Ok. Made this change

2021-07-16 12:27 UTC, cadawson commented on install/plan_capacity.adoc
> +*** 4 cores running on SMT-4 provides the required 16 vCPUs. This is the default configuration for system that are not running IBM PowerVM.
Works for me!

2021-07-16 12:28 UTC, cadawson commented
Hi @jwcroppe . Yes, those changes work for me, and are merged now. Thank you!

2021-07-20 11:44 UTC, cadawson commented
@swopebe : Can you take a quick look to make sure you are ok with the additions to install/plan_capacity for Power in this PR?

2021-07-22 17:17 UTC, swopebe approved these changes
LOOKS GREAT!

2021-07-22 20:58 UTC, merged