open-cluster-management/backlog#13053 Add rbac
open-cluster-management/rhacm-docs pull request #2369
Opened 2021-07-13 20:55 UTC by cadawson

2021-07-14 13:35 UTC, dockerymick requested changes

2021-07-14 13:35 UTC, dockerymick commented on clusters/custom_resource.adoc
> +[#managedclustersets (Technology Preview)]
should the technology preview be in the section title rather than the anchor?

2021-07-14 13:35 UTC, dockerymick commented on clusters/custom_resource.adoc
> +=== Creating a ManagedClusterSet by using the console
I would italicize ManagedClusterSet bc it would normally be monospaced, but since it is in the section title, it should be italicized instead of monospace

2021-07-14 13:35 UTC, dockerymick commented on clusters/custom_resource.adoc
> +. Select the *Cluster sets* tab.
Italicize Cluster set

2021-07-14 13:35 UTC, dockerymick commented on clusters/custom_resource.adoc
> +. Select `Create cluster set`.
Is "Create cluster set" a button or an option in a menu list? If yes, this should be bold instead of monospaced.

2021-07-14 13:35 UTC, dockerymick commented on clusters/custom_resource.adoc
> +. Select `Create` to create the cluster set resource.
This seems like it is a Create button. Please bold Create instead of monospace

2021-07-14 13:35 UTC, dockerymick commented on clusters/custom_resource.adoc
> +=== Creating a ManagedClusterSet by using the command line
Italicize ManagedClusterSet as explained in my previous comment

2021-07-14 13:35 UTC, dockerymick commented on clusters/custom_resource.adoc
> +A `ManagedClusterSet` is a cluster-scoped resource, so you must have cluster administration permissions for the cluster where you are creating the `ManagedClusterSet`. A managed cluster cannot be inc
change command-line to command line

2021-07-14 13:35 UTC, dockerymick commented on clusters/custom_resource.adoc
>  == Adding clusters to a ManagedClusterSet
italicize ManagedClusterSet

2021-07-14 13:35 UTC, dockerymick commented on clusters/custom_resource.adoc
> +=== Adding clusters to a ManagedClusterSet by using the console
italicize ManagedClusterSet

2021-07-14 13:35 UTC, dockerymick commented on clusters/custom_resource.adoc
> +. Select the *Cluster sets* tab to view the available cluster sets.
Italicize _Cluster set_ tab

2021-07-14 13:35 UTC, dockerymick commented on clusters/custom_resource.adoc
> +=== Adding clusters to a ManagedClusterSet by using the command line
Italicize ManagedClusterSet

2021-07-14 13:35 UTC, dockerymick commented on clusters/custom_resource.adoc
> +=== Removing a managed cluster from a ManagedClusterSet by using the console
Italicize ManagedClusterSet

2021-07-14 13:35 UTC, dockerymick commented on clusters/custom_resource.adoc
> +. Select the *Cluster sets* tab to view the available cluster sets.
Italicize _Cluster set_ tab

2021-07-14 13:35 UTC, dockerymick commented on clusters/custom_resource.adoc
> +== Creating a ManagedClusterSetBinding resource
Italicize ManagedClusterSetBinding

2021-07-14 13:35 UTC, dockerymick commented on clusters/custom_resource.adoc
> +Create a `ManagedClusterSetBinding` resource to bind a `ManagedClusterSet` resource to a namespace. Application and policies that are created in the same namespace can only access managed clusters th
change command-line to command line

2021-07-14 13:35 UTC, dockerymick commented on clusters/custom_resource.adoc
> +=== Creating a ManagedClusterSetBinding by using the console
Italicize ManagedClusterSetBinding

2021-07-14 13:35 UTC, dockerymick commented on clusters/custom_resource.adoc
> +. Select the *Cluster sets* tab to view the available cluster sets.
italicize _Cluster sets_ tab

2021-07-14 13:35 UTC, dockerymick commented on clusters/custom_resource.adoc
> +. Select `Save` to submit your changes.
Instead of monospace, please bold "Save"

2021-07-14 13:35 UTC, dockerymick commented on clusters/custom_resource.adoc
> +=== Creating a ManagedClusterSetBinding by using the command line
Italicize ManagedClusterSetBinding

2021-07-14 13:35 UTC, dockerymick commented on clusters/custom_resource.adoc
> +. Create the `ManagedClusterSetBinding` resource in your `yaml` file. Your `ManagedClusterSetBinding` resource might resemble the following information:
I would move the statement from line 222 to 224 and combine them like this:

. Create the `ManagedClusterSetBinding` resource in your `yaml` file. When you create a managed cluster set binding, the name of the managed cluster set binding must match the name of the managed cluster set to bind. Your `ManagedClusterSetBinding` resource might resemble the following information:

2021-07-14 13:35 UTC, dockerymick commented on clusters/custom_resource.adoc
> +=== Assigning users or groups Role-Based Access Control permissions to your MnaagedClusterSet
Italicize ManagedClusterSet

2021-07-14 13:35 UTC, dockerymick commented on clusters/custom_resource.adoc
> +* Cluster set admin
monospace admin

2021-07-14 13:35 UTC, dockerymick commented on clusters/custom_resource.adoc
> +* Cluster set view
i recommend using monospace for view

2021-07-14 13:35 UTC, dockerymick commented on clusters/custom_resource.adoc
> +You can group managed clusters together in a managed cluster set to limit the user access on managed clusters.
You can remove the comment on Line 18, i added that when i was working on the RBAC topics.

2021-07-14 13:35 UTC, dockerymick commented on clusters/custom_resource.adoc
> +[#managedclustersets (Technology Preview)]
I recommend adding an inline link for sections that are H3 as well at the beg. There are a few added sections and it would be helpful to the user to know what sections are within the doc. For example: 

* <<creating-a-managedclusterset,Creating a ManagedClusterSet>>
** <<creating-a-managedclusterset-console,Creating a ManagedClusterSet by using the console>>
** <<creating-a-managedclusterset-cli,Creating a ManagedClusterSet by using the command line>>
* <<adding-clusters-to-a-managedclusterset,Adding clusters to a ManagedClusterSet>>

Also please be sure  that section title and anchors in the inline link match the associated section that you are referencing

2021-07-19 15:04 UTC, cadawson commented on clusters/custom_resource.adoc
> +Create a `ManagedClusterSetBinding` resource to bind a `ManagedClusterSet` resource to a namespace. Application and policies that are created in the same namespace can only access managed clusters th
When it is commend-line interface, the two words are strung together words to act as one adjective describing the interface. That is why it was hyphenated there. That said, I changed it to command line, as it is what I am using most of the time, anyway. Thanks!

2021-07-19 15:11 UTC, cadawson commented
Thanks for the review, @dockerymick !

2021-07-19 15:12 UTC, merged