open-cluster-management/backlog#11342 dev and peer review needed.
open-cluster-management/rhacm-docs pull request #2418
Opened 2021-07-21 19:43 UTC by swopebe

--argo edits, prep for review

2021-07-21 21:18 UTC, cadawson requested changes
Looks good! Only one place where I think there might have been an extra word or something.

2021-07-21 21:18 UTC, cadawson commented on applications/gitops_config.adoc
>  * You need to https://argoproj.github.io/argo-cd/getting_started/#1-install-argo-cd[Install Argo CD] or the https://access.redhat.com/documentation/en-us/openshift_container_platform/4.7/html/cicd/gi
Do you want 4.8 here, or leave 4.7?

2021-07-21 21:18 UTC, cadawson commented on applications/gitops_config.adoc
> +. You need to define a set of managed clusters for registration.
must instead of need to?

2021-07-21 21:18 UTC, cadawson commented on applications/gitops_config.adoc
>  . Save your changes. You can now update follow the GitOps workflow to manage your applications.
You can now follow the GitOps workflow to manage your applications?

2021-07-22 13:50 UTC, swopebe commented on applications/gitops_config.adoc
> +. You need to define a set of managed clusters for registration.
Need to is approved, not sure about must. See in the doc, I don't really use it. Was taught as an intern/grad student that it is not the best word to use for global English, but I would have to look at style manual and given our timeline, I will leave it for now.

I don't write must often.

2021-07-22 13:50 UTC, swopebe commented on applications/gitops_config.adoc
>  * You need to https://argoproj.github.io/argo-cd/getting_started/#1-install-argo-cd[Install Argo CD] or the https://access.redhat.com/documentation/en-us/openshift_container_platform/4.7/html/cicd/gi
Yes, you are correct.

2021-07-22 13:50 UTC, swopebe commented on applications/gitops_config.adoc
>  * You need to https://argoproj.github.io/argo-cd/getting_started/#1-install-argo-cd[Install Argo CD] or the https://access.redhat.com/documentation/en-us/openshift_container_platform/4.7/html/cicd/gi
(hopefully it is staying here for 4.8)

2021-07-22 13:51 UTC, swopebe commented on applications/gitops_config.adoc
>  . Save your changes. You can now update follow the GitOps workflow to manage your applications.
yes, typo, thanks for catching!

2021-07-22 15:14 UTC, rokej commented on applications/gitops_config.adoc
> +. Bind a _placement rule_ to the cluster with a `GitOpsCluster` custom resource, which registers the set of managed clusters from the _placement decision_ to the specified instance of Argo CD or {ocp
Replace _placement rule_  with _placement_  because the resource name is `placement`

2021-07-22 15:24 UTC, rokej commented on applications/gitops_config.adoc
Yes, we need a doc link to  https://github.com/open-cluster-management/backlog/issues/12767 for information on the new placement resource that was introduced in 2.3 and will be used by this GitOps configuration.

If we want to provide high-level end-to-end GitOps configuration steps here:

1. Create managed cluster sets.
2. Add managed clusters to managed cluster sets.
3. Create managed cluster set binding for a namespace to have access to the managed cluster set.
4. In the namespace used in managed cluster set binding, create a _Placement_ to select managed clusters from the managed cluster set.
5. In the namespace used in managed cluster set binding, create a _GitOpsCluster_ to register the selected managed clusters by the placement to a specified instance of ArgoCD or OpenShift GitOps.

Note to the doc developer: For steps 1 ~ 4, we need the doc link for  https://github.com/open-cluster-management/backlog/issues/12767 for details information.

2021-07-22 17:01 UTC, swopebe commented on applications/gitops_config.adoc
@rokej the file does not exist so depending on where the issue is, I may add these. -- will get back

2021-07-22 19:30 UTC, merged