open-cluster-management/backlog#13078 Merge files
open-cluster-management/rhacm-docs pull request #2421
Opened 2021-07-22 14:03 UTC by cadawson

2021-07-22 17:03 UTC, Randy424 approved these changes

2021-07-29 18:35 UTC, dockerymick requested changes
Lots of comments that I believe should also be applied to the original Ansible doc. As mentioned in our chat, let's point to your new topic from the original Ansible doc which will be treated as the "Ansible landing page"

2021-07-29 18:35 UTC, dockerymick commented on clusters/ansible_config_cluster.adoc
> +{product-title-short} is integrated with Ansible Tower automation so that you can create prehook and posthook AnsibleJob instances that occur before or after creating or upgrading your clusters. Conf
Add a comma:

Configuring prehook and posthook jobs for cluster destroy, and cluster scale actions are not supported.

2021-07-29 18:35 UTC, dockerymick commented on clusters/ansible_config_cluster.adoc
> +* Install the Ansible Automation Platform Resource Operator to connect Ansible jobs to the lifecycle of Git subscriptions. For best results when using the AnsibleJob to launch Ansible Tower jobs, the
Is AnsibleJob the value used for `kind` in the resource? If yes, I recommend that it be monospaced. If no, I suggest that you add a space: 

Ansible jobs

2021-07-29 18:35 UTC, dockerymick commented on clusters/ansible_config_cluster.adoc
> +Check `PROMPT ON LAUNCH` on the template for both INVENTORY and EXTRA VARIABLES. See https://docs.ansible.com/ansible-tower/latest/html/userguide/job_templates.html[Job templates] for more informatio
I recommend monospacing Inventory and extra variables. I would also use lowercase letters unless it is displayed like that in Ansible. I went to the doc and only saw one instance of EXTRA VARIABLES. It seemed like they were trying to bring attention to the word. I'm not sure tho, I'll leave to you

2021-07-29 18:35 UTC, dockerymick commented on clusters/ansible_config_cluster.adoc
> +The application subscription controller queues the reconcile request again in a 1 minute loop, where it checks the prehook AnsibleJob `status.ansibleJobResult`. When the prehook `status.ansibleJobRes
spell out 1: one

2021-07-29 18:35 UTC, dockerymick commented on clusters/ansible_config_cluster.adoc
> +When the app subscription status is updated, if the subscription status is subscribed or propagated to all target clusters in subscribed status, the app subscription controller searches all of the `A
When the application subscription status is updated and if the subscription status is subscribed.., the application subscription controller searches all of `Kind: AnsibleJob` CRs....

2021-07-29 18:35 UTC, dockerymick commented on clusters/ansible_config_cluster.adoc
> +When the Git subscription is created, all of the pre and post AnsibleJob resources are parsed and stored in memory as an object. The application subscription controller decides when to create the pre
I would monospace AnsibleJob

2021-07-29 18:35 UTC, dockerymick commented on clusters/ansible_config_cluster.adoc
> +You can configure Ansible Tower configurations with the following tasks:
Will there be tasks add after this or are you prompting the user to view the next few sections?

2021-07-29 18:35 UTC, dockerymick commented on clusters/ansible_config_cluster.adoc
> +Create the secret from the console by filling in the `Ansible Tower secret name` section. To create the secret using terminal, edit and apply the following `yaml`:
Since this is a field from the console, I recommend italicizing instead of monospacing it.

To create the secret using **the** terminal, edit and apply the following YAML.

I recommend displaying YAML with capital letters to maintain consistency in this file. In the other tasks, YAML is used.

2021-07-29 18:35 UTC, dockerymick commented on clusters/ansible_config_cluster.adoc
> +When the app subscription controller creates prehook and posthook AnsibleJobs, if the secret from subscription `spec.hooksecretref` is available, then it is sent to the AnsibleJob CR `spec.tower_auth
When the application subscription controller creates prehook and posthook `AnsibleJobs` and if the secret from....`AnsibleJob` CR.....

2021-07-29 18:35 UTC, dockerymick commented on clusters/ansible_config_cluster.adoc
> +For a main-sub subscription with prehook and posthook AnsibleJobs, the main-sub subscription should be reconciled after all prehook and posthook AnsibleJobs or main subscription are updated in the Gi
`main-sub` subscription

also, same suggestion about AnsibleJobs

2021-07-29 18:35 UTC, dockerymick commented on clusters/ansible_config_cluster.adoc
> +. Verify that the DONE subscription is updated. See the following output:
Should this read `DONE` since its the name of the subscription?

2021-07-29 18:35 UTC, dockerymick commented on clusters/ansible_config_cluster.adoc
> +As previously mentioned in the prehook and posthook AnsibleJob workflow, when the main subscription is updated in Git repository, a new prehook and posthook AnsibleJob instance is created. As a resul
Same comment about AnsibleJob

2021-07-29 18:35 UTC, dockerymick commented on clusters/ansible_config_cluster.adoc
> +- posthookJobsHistory: All the posthook AnsibleJobs history
Great consistency here

2021-07-29 18:35 UTC, dockerymick commented on clusters/ansible_config_cluster.adoc
> +* If you want to create a new template, click *Create Ansible template* and continue with step 3.
not sure if the number 3 should be spelled out since you are pointing to specific task

2021-07-29 18:35 UTC, dockerymick commented on clusters/ansible_config_cluster.adoc
> +* If you want to modify an existing template, click *Edit template* from the _Options_ menu of the template that you want to modify and continue with step 5.
Same comment previously mentioned

2021-07-29 18:35 UTC, dockerymick commented on clusters/ansible_config_cluster.adoc
> +. From the {product-title-short} navigation, select *Automation*. Any template in the list of templates that is not linked to a credential contains a *Link to credential* icon that you can use to lin
navigation menu

2021-07-29 18:35 UTC, dockerymick commented on clusters/ansible_config_cluster.adoc
> +== Creating and modifying an AnsibleJob template
I would italicize AnsibleJob based on my other suggestions to monospace it. Last i recall, we avoid using monospace in the section title

2021-07-29 18:35 UTC, dockerymick commented on clusters/ansible_config_cluster.adoc
> +. Enter a name for your template. It must be a unique name that contains lowercase, alphanumeric characters or `-`.
i suggest writing out the word hyphen. Suggesting the following update: 

...or a hypen (`-`).

2021-07-29 18:35 UTC, dockerymick commented on clusters/ansible_config_cluster.adoc
> +== Linking a credential to an AnsibleJob template
italicize AnsibleJob as suggested in the previous comment

2021-07-29 18:35 UTC, dockerymick commented on clusters/ansible_config_cluster.adoc
> +== Configuring an AnsibleJob template to run on a cluster by using the console
same comment about italicizing in the section title

2021-07-29 18:35 UTC, dockerymick commented on clusters/ansible_config_cluster.adoc
> +[#cconfiguring-an-ansible-job-for-a-managed-cluster-labels]
just a heads up, there is an extra c in the anchor

2021-07-29 18:35 UTC, dockerymick commented on clusters/ansible_config_cluster.adoc
> += Configuring an AnsibleJob template to run on a managed cluster by using labels
Italics needed in this section title

2021-07-30 17:47 UTC, cadawson commented on clusters/ansible_config_cluster.adoc
> +* If you want to create a new template, click *Create Ansible template* and continue with step 3.
Typically, if we are referring to steps. we use the number. If they weren't steps, I would agree.

2021-08-01 14:49 UTC, merged