open-cluster-management/backlog#13069 Add SNO
open-cluster-management/rhacm-docs pull request #2426
Opened 2021-07-23 20:51 UTC by cadawson

2021-07-26 12:49 UTC, chrisahl approved these changes

2021-08-02 12:42 UTC, chrisahl commented on clusters/single_node_openshift.adoc
> +You can create a Single-Node OpenShift (SNO) cluster that contains only a single node. In a standard cluster, there is a main node and separate worker nodes. This configuration can be helpful when yo
FROM
there is a main node
TO
there are master nodes

2021-08-02 12:43 UTC, chrisahl commented on clusters/single_node_openshift.adoc
> +. Complete the remaining steps of the cluster creation to create your SNO cluster. There is a known issue when you create a cluster pool with a SNO cluster, the cluster pools with the SNO enabled clu
Ahhh...this is what I was looking for but did not see for the Known Issue.   This looks good to me.

2021-08-02 12:45 UTC, chrisahl requested changes
Left comments inline

2021-08-02 12:48 UTC, cadawson commented on clusters/single_node_openshift.adoc
> +You can create a Single-Node OpenShift (SNO) cluster that contains only a single node. In a standard cluster, there is a main node and separate worker nodes. This configuration can be helpful when yo
Ok. I know we are trying to get away from master, but this might not be updated. I can make that change.

2021-08-02 12:50 UTC, cadawson commented on clusters/single_node_openshift.adoc
> +. Complete the remaining steps of the cluster creation to create your SNO cluster. There is a known issue when you create a cluster pool with a SNO cluster, the cluster pools with the SNO enabled clu
Thank you!

2021-08-02 12:51 UTC, cadawson commented on clusters/single_node_openshift.adoc
> +. Complete the remaining steps of the cluster creation to create your SNO cluster. There is a known issue when you create a cluster pool with a SNO cluster, the cluster pools with the SNO enabled clu
It is a little strange having to keep that all in the same file. Someday, we can split it up, if it still applies.

2021-08-03 14:55 UTC, cadawson commented
Approved through slack by Chris. Also approved in the issue by Han. Merging this.

2021-08-03 14:55 UTC, merged