open-cluster-management/backlog#12010 Add proxy
open-cluster-management/rhacm-docs pull request #2445
Opened 2021-07-26 20:40 UTC by cadawson

2021-07-28 17:42 UTC, jnpacker commented on clusters/proxy.adoc
> +[#enable-cluster-wide-proxy-existing]
@cadawson this is the part Philip provided?  I think we want to call out that this is for specifically make components proxy aware on the Managed Clusters.

For example to make the Application Manager (AppMgr) work behind a proxy, the following settings must be applied to its deployment.

2021-07-28 17:43 UTC, jnpacker commented on clusters/proxy.adoc
> +[#enable-cluster-wide-proxy-existing]
The content seems fine, we just need to better describe that the second section is for enabling a component from the managed cluster to work behind a proxy. Such as AppMgr.

2021-07-28 17:44 UTC, jnpacker commented
@cdoan1 Since you have the most experience with this configuration, do you mind review the documentation and making any adjustments you feel we should have.

The goal was to cover hub side and managed cluster side configurations.

2021-07-30 19:26 UTC, cadawson commented on clusters/proxy.adoc
> +[#enable-cluster-wide-proxy-existing]
Modified the text a bit, @jnpacker . Thanks.

2021-08-03 17:58 UTC, cdoan1 approved these changes

2021-08-03 17:58 UTC, cdoan1 commented on clusters/proxy.adoc
> +baseDomain: <domain>
This example needs the `Kind` to know what this is about?

2021-08-04 11:04 UTC, cadawson commented on clusters/proxy.adoc
> +baseDomain: <domain>
I added a kind: Proxy, @cdoan1 . Does that resolve this issue? Thanks!

2021-08-04 17:05 UTC, swopebe requested changes
few small things here and otherwise looks great

2021-08-04 17:05 UTC, swopebe commented on clusters/proxy.adoc
> +
Please don't use "they" here.... They, we, etc.... is not good for tech doc.

2021-08-04 17:05 UTC, swopebe commented on clusters/proxy.adoc
> +
You can reword to use what they actually means here.

2021-08-04 17:05 UTC, swopebe commented on clusters/proxy.adoc
> +
Since we named these infrastructure provider in the UI, should "cloud provider" change?

2021-08-04 17:05 UTC, swopebe commented on clusters/proxy.adoc
> +
After you add the previous values, the settings are applied to your clusters.

?
Previous orients a non-sighted user; sentence more specific and active....

2021-08-04 17:05 UTC, swopebe commented on clusters/proxy.adoc
> +When you enable the cluster-wide proxy feature, you have to make the components of the managed cluster aware so they can work behind the proxy. To enable the components like Application Manager, the
Application Manager is the name of the component? or do you mean something more specific here?

2021-08-04 17:05 UTC, swopebe commented on clusters/proxy.adoc
> +When you enable the cluster-wide proxy feature, you have to make the components of the managed cluster aware so they can work behind the proxy. To enable the components like Application Manager, the
Changing such as instead of "like"

2021-08-04 17:17 UTC, dockerymick commented on clusters/proxy.adoc
> +
I recommend writing, "{product-title} has a private network connection with the managed cluster that you are creating, which uses a proxy to reach the Internet." 

Maybe say access rather than reach? Both work in my opinion

2021-08-04 17:17 UTC, dockerymick commented on clusters/proxy.adoc
> +*Tip:* For several containers, you can create and run a file that resembles the following example on each of the containers:
Is the tip intended for Step 3 or the entire doc overall? If it is intended for step 3, I recommend adding a plus sign (+) on line 91

2021-08-04 17:51 UTC, cadawson commented on clusters/proxy.adoc
> +
Good point. Thanks!

2021-08-04 17:59 UTC, cadawson commented on clusters/proxy.adoc
> +When you enable the cluster-wide proxy feature, you have to make the components of the managed cluster aware so they can work behind the proxy. To enable the components like Application Manager, the
Component name

2021-08-04 18:02 UTC, cadawson commented on clusters/proxy.adoc
> +*Tip:* For several containers, you can create and run a file that resembles the following example on each of the containers:
It is actually for the overall topic. That was intentional.

2021-08-04 18:13 UTC, cadawson commented on clusters/proxy.adoc
> +
I see what you mean here. But it refers to both of them, and I think "which uses a proxy to reach the Internet" can be unclear whether it is both or just the managed cluster.

2021-08-04 18:14 UTC, merged