open-cluster-management/backlog#12767--peer review needed and final d…
open-cluster-management/rhacm-docs pull request #2481
Opened 2021-07-29 19:39 UTC by swopebe

…ev review.

2021-07-30 03:33 UTC, elgnay commented
The doc looks fine except some minor issues.

<img width="1164" alt="Screen Shot 2021-07-30 at 11 16 47 AM" src="https://user-images.githubusercontent.com/45344534/127595872-cb9b5408-2cbc-41c5-9cee-ccbc2c7d4055.png">

<img width="1180" alt="Screen Shot 2021-07-30 at 11 20 21 AM" src="https://user-images.githubusercontent.com/45344534/127595905-ba0c632d-3982-4c3f-8d6b-ee2476dc150f.png">

<img width="1171" alt="Screen Shot 2021-07-30 at 11 28 00 AM" src="https://user-images.githubusercontent.com/45344534/127595914-d7ff3cea-3bb2-4bfb-826e-122e88fc8de8.png">

2021-07-30 12:59 UTC, swopebe commented
@elgnay the important special tag is actually part of the overview, the list is information about Placement (so I named it overview.) But it may be better if I move it up, rather than place it at the end.

I actually created a section for placement binding and had examples under it I think in the first draft, but that was when I was writing them as steps. So I can make that change and the others make sense.

2021-07-30 15:35 UTC, cadawson requested changes
Thanks so much for working this one! A few comments and suggestions, but go with what you think. It looks good!

2021-07-30 15:35 UTC, cadawson commented on clusters/placement_managed.adoc
> -If not specified, all `ManagedClusters` that meet the placement requirements are selected
Ln 23: I was wondering whether this should be a note under the previous bullet, rather than a bullet of its own? 
Ln 30: "is bound" or "are bound"?
Ln 33: LOVE the way you worded this bullet! Very clear, and not easy to do.  Is "this set" clear enough, or would "the specified set" be more clear? 
Ln 37: I added a period here.

2021-07-30 15:35 UTC, cadawson commented on clusters/placement_managed.adoc
>  You need to bind a `ManagedClusterSet` to a namespace by creating a `ManagedClusterSetBinding` in that namespace. *Note:* You need role-based access to `CREATE` on the virtual sub-resource of `manage
Extra space at beginning. Will check this.

2021-07-30 15:35 UTC, cadawson commented on clusters/placement_managed.adoc
> +- You can select `ManagedClusters` with the `labelSelector`. See the following sample where the `labelSelector` only matches clusters with label `vendor: OpenShift`:
Removed "in" from "in the following example" from a couple of these to keep them consistent with the other ones. Add it back to all of them, if you prefer that way.

2021-07-30 15:35 UTC, cadawson commented on clusters/placement_managed.adoc
> +- If a `ManagedCluster` is selected and added to a `PlacementDecision`, components that consume this `Placement` might apply the workload on this `ManagedCluster`. After the `ManagedCluster` is no lo
- Changed "may" to "might".
- "After the `ManagedCluster` is no longer selected and it is removed..." > "After the `ManagedCluster` is no longer selected and is removed..."
- When we say it "should be removed...", we are implying doubt, in my opinion. Can we confidently say "is removed"?

2021-07-31 01:48 UTC, swopebe commented on clusters/placement_managed.adoc
> +- If a `ManagedCluster` is selected and added to a `PlacementDecision`, components that consume this `Placement` might apply the workload on this `ManagedCluster`. After the `ManagedCluster` is no lo
I am not sure about the last part, this section you can see in the draft in the issue.

2021-07-31 01:49 UTC, swopebe commented on clusters/placement_managed.adoc
> -If not specified, all `ManagedClusters` that meet the placement requirements are selected
33. If changes would use relative pronoun: the set that is specified.

Other changes I agree and will make, along with dev review. Thanks

2021-07-31 01:50 UTC, swopebe commented on clusters/placement_managed.adoc
> +- You can select `ManagedClusters` with the `labelSelector`. See the following sample where the `labelSelector` only matches clusters with label `vendor: OpenShift`:
I don't, it was left over from the draft. I thought I removed them. Thanks for catching it!

2021-08-01 20:49 UTC, merged