open-cluster-management/backlog#12103 -- AWS S3 Dev review
open-cluster-management/rhacm-docs pull request #2492
Opened 2021-07-31 04:10 UTC by swopebe

2021-08-02 15:20 UTC, mikeshng requested changes
- We need to replace all `xili` references with something like `sample`. I think a search and replace should be suffice. 
**DONE--bcs**
- Replace `9.28.236.243` with another sample IP address.
**DONE--bcs**
- Following the `You can continue to create other AWS subscription and placement rule objects.`, add the sample for placementrule and subscription. 
-**DONE--bcs**
```
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: towhichcluster
  namespace: obj-sub-ns
spec:
  clusterSelector: {}
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: obj-sub
  namespace: obj-sub-ns
spec:
  channel: ch-object-dev/object-dev
  placement:
    placementRef:
      kind: PlacementRule
      name: towhichcluster
```

I think the first 2 bullets should be done. For the 3rd bullet (sample yaml) lets wait for @xiangjingli feedback.

2021-08-03 16:18 UTC, xiangjingli commented
agree to add the sample yamls as @mikeshng suggested in the the 3rd item 

@swopebe   We also want to highlight the other 2 points for users:
- we support to subscribe all the objects under a specific subfolder in the object bucket.
To do it, add the subfolder annotation to the subscription that will force the object bucket subscription to only apply all the resources under the subfolder path.

Using the annotation below:
```
annotations:
  apps.open-cluster-management.io/bucket-path: <your bucket subfolder>
``` 

here is one sample yaml
```
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/bucket-path: subfolder1
  name: obj-sub
  namespace: obj-sub-ns
  labels:
    name: obj-sub
spec:
  channel: ch-object-dev/object-dev
  placement:
    placementRef:
      kind: PlacementRule
      name: towhichcluster
```

- object bucket subscription Known issue: For now we only support One yaml manifest per object file. Don't support multiple yaml manifests in the same object file yet

2021-08-04 14:40 UTC, swopebe commented on applications/manage_apps_object.adoc
> +----
@mikeshng see your recommended changes in the PR are added.

2021-08-04 14:41 UTC, swopebe commented on applications/manage_apps_object.adoc
> +*User required access:* A user role that can create applications.
@xiangjingli you think we can get a better role here, we normally can say admin or cluster admin.... do you know the lowest level needed?

2021-08-04 14:43 UTC, swopebe commented on applications/manage_apps_object.adoc
>  == Deploy resources from object storage
@xiangjingli thank you for the additional annotations that you gave me in the issue. Where is the best spot to add this part to the procedure?

Meaning the sub folder additions...

2021-08-04 18:16 UTC, xiangjingli commented on applications/manage_apps_object.adoc
> +*User required access:* A user role that can create applications.
admin or cluster admin is good. 

And  `A user role that can create applications` is the lowest level needed , user should at least have the permission to create/update app lifecycle related CRs (channel, subscription, placementrule, ) in the given Namespace.

2021-08-04 18:16 UTC, xiangjingli commented on applications/manage_apps_object.adoc
>  == Deploy resources from object storage
I think we can add a new item after  `Sample AWS subscription`, sth like

### Sample AWS subscription
...
### Subscribe to objects under a specific subfolder in the Minio and AWS object buckets 
.... // here we inform how to specify the subfolder annotation with a sample yaml

2021-08-04 19:30 UTC, xiangjingli approved these changes
lgtm

2021-08-04 19:31 UTC, merged