open-cluster-management/backlog#15628 Add 2.2.8 errata
open-cluster-management/rhacm-docs pull request #2661
Opened 2021-09-09 17:50 UTC by cadawson

2021-09-13 14:46 UTC, cadawson commented
Hi @anthonyfister. The four errata items that were marked are drafted in this PR. 
Question: Was the issue 14821 fixed, or is it being addressed as a known issue? It looked like a known issue, but there was no summary. If it is a known issue, we don't mention known issue additions in the errata. We focus on items where changes to the code fixed an issue. We can remove that one, if it is a known issue. Let me know if you have any updates. Thanks!

2021-09-13 18:51 UTC, dockerymick requested changes

2021-09-13 18:51 UTC, dockerymick commented on release_notes/errata.adoc
> +* Fixes an issue that caused an application to be deleted when it was reconciled. The deletion was caused by a bad application manifest, such as incorrect kustomization, in a subscribed Git repositor
Are there other situations where the application is "bad" , maybe we can say misconfigured? I suggest the following change (should kustomization start with a c?): 

The deletion was caused by an incorrect kustomization for the application manifest, in a subscribed Git repository. With this fix, an error message is displayed in the application topology user interface when there is a misconfigured manifest, but the deployed application is not deleted.

2021-09-13 18:51 UTC, dockerymick commented on release_notes/errata.adoc
> +* Decreases the number of unnecessary secrets that are created so the `cert manager` can start with less memory consumption. (GitHub 13127)
comma after created

2021-09-13 18:51 UTC, dockerymick commented on release_notes/errata.adoc
> +* Fixes an issue that caused some {ocp} version 4.8 observability metrics to not display in the Grafana console. (GitHub 14821)
I have an active [PR](https://github.com/open-cluster-management/rhacm-docs/pull/2667) to document this specific known issue. If there is a fix, it makes sense for me to not doc the known issue, unless there are still some metrics that are not displayed.

2021-09-13 18:54 UTC, dockerymick commented on release_notes/errata.adoc
> +* Fixes an issue that caused some {ocp} version 4.8 observability metrics to not display in the Grafana console. (GitHub 14821)
@clyang82 thoughts? ^

2021-09-13 18:59 UTC, dockerymick commented on release_notes/errata.adoc
> +* Fixes an issue that caused some {ocp} version 4.8 observability metrics to not display in the Grafana console. (GitHub 14821)
Honestly, the statement is only a few sentences. I think that it is fine to keep the known issue as is, plus it is approved.

2021-09-14 11:55 UTC, cadawson commented on release_notes/errata.adoc
> +* Fixes an issue that caused an application to be deleted when it was reconciled. The deletion was caused by a bad application manifest, such as incorrect kustomization, in a subscribed Git repositor
Thanks. Made some updates to this from your comments, for clarity.

2021-09-14 11:58 UTC, cadawson commented on release_notes/errata.adoc
> +* Fixes an issue that caused some {ocp} version 4.8 observability metrics to not display in the Grafana console. (GitHub 14821)
I'm trying to determine whether it was fixed or still an issue.

2021-09-14 12:49 UTC, anthonyfister approved these changes
Looks good.  Thanks.

2021-09-14 12:58 UTC, anthonyfister commented on release_notes/errata.adoc
> +* Fixes an issue that caused some {ocp} version 4.8 observability metrics to not display in the Grafana console. (GitHub 14821)
It was not fixed in 2.2.z.   It was too complex and would have required mucho refactoring.
We decided to fix forward (in the next release) and document as a known issue for 2.2.z.  It's hard to keep up with changing metrics each time OCP comes out with a new version.  
So... the line for GitHub 14821 should probably come out.

2021-09-14 13:04 UTC, merged

2021-09-14 13:19 UTC, cadawson commented on release_notes/errata.adoc
> +* Fixes an issue that caused some {ocp} version 4.8 observability metrics to not display in the Grafana console. (GitHub 14821)
Removed it.