Source column info add
open-cluster-management/rhacm-docs pull request #2710
Opened 2021-09-22 22:13 UTC by dockerymick

https://github.com/open-cluster-management/backlog/issues/15529

2021-09-23 20:18 UTC, KevinFCormier requested changes
Thanks @dockerymick! Please let me know if you have any questions about my comments.

2021-09-23 20:18 UTC, KevinFCormier commented on governance/deploy_gitops.adoc
> +. Locate the policies that you deployed in the table. Policies that are deployed using GitOps has a _Git_ label in the _Source_ column. Click the label to be directed to the source in the Git reposit
```suggestion
. Locate the policies that you deployed in the table. Policies that are deployed using GitOps have a _Git_ label in the _Source_ column. Click the label to view the details for the Git repository.
```

1. "have" goes with policies
2. It sounded like clicking the label would take me right to the repository, so I suggest a slightly different wording. But you could expand on that if you want to explicitly mention there is a link.

2021-09-23 20:18 UTC, KevinFCormier commented on governance/manage_policy_overview.adoc
> +The table of policies list the following details of a policy: _Policy name_, _Namespace_, _Status_, _Remediation_, _Cluster violations_, _Source_, _Controls_, _Automation_ and _Created_. You can edit
```suggestion
The table of policies lists the following details of a policy: _Policy name_, _Namespace_, _Status_, _Remediation_, _Cluster violations_, _Source_, _Controls_, _Automation_ and _Created_. You can edit, enable or disable, set remediation to inform or enforce, or remove a policy by selecting the *Actions* icon. You can view the categories and standards of a specific policy by selecting the drop-down arrow to expand the row.
```
1. "lists" goes with table; the table lists
2. Using "inform" as a verb on the policy seems strange and left out the "enforce" option.

2021-09-23 20:18 UTC, KevinFCormier commented on governance/manage_policy_overview.adoc
> +- _Details_: Select the _Details_ tab to view policy details and placement information. You can configure automation from the _Policy details_ section, select the **Configure** link. You can also sel
In the second sentence, should "You" be "to"?

The last sentence refers to **local-cluster** but this depends on which clusters have violations. See screenshot. Also, personally I don't like the term "violated cluster"... in general I would say "cluster with policy violations". In this case, the link allows you to view the compliance of the policy for the given cluster
![image](https://user-images.githubusercontent.com/42188127/134574659-44052c8f-e36a-41e8-a2ca-196f019cc8ef.png)

2021-09-23 20:18 UTC, KevinFCormier commented on governance/manage_policy_overview.adoc
> +- _Clusters_: Select the _Clusters_ tab to view a table list of violated clusters. Click the **View details** link to view the template details and YAML. You can also view related resources. To view
This change is related to https://github.com/open-cluster-management/backlog/issues/16329 right? There will be several more places to update related to the new tabs. 

- It's not only clusters with violations that will be shown.
![image](https://user-images.githubusercontent.com/42188127/134575397-956c0114-36b3-48b3-af85-6fb6992e7cb3.png)
- The history does not just include violations. 
![image](https://user-images.githubusercontent.com/42188127/134575711-eec3ce04-663e-4768-9d9c-c9d711c820f3.png)
- The "local cluster name" should just be the "name of the cluster". The history is for a specific cluster and policy template. For example, here is it for a different cluster.
![image](https://user-images.githubusercontent.com/42188127/134575991-16495315-97bf-4bbd-8021-2ead975faaad.png)

2021-09-23 20:18 UTC, KevinFCormier commented on governance/manage_policy_overview.adoc
> +- _Templates_: Select the _Templates_ tab to view the cluster that is related to the template.
The only difference between the _Clusters_ tab and the _Templates_ tab is that on the Clusters tab, you get a single table that lists each cluster and policy template that applies to it (from the given policy), whereas on the Templates tab, you get a separate table for each template. So I think the descriptions of these should be very similar, or maybe even combined.
![image](https://user-images.githubusercontent.com/42188127/134577013-2aa6f087-df4b-4344-9f3e-f8558e175850.png)

![image](https://user-images.githubusercontent.com/42188127/134577073-735b4cfa-a525-4a86-baab-b13848cc1635.png)

2021-09-28 16:03 UTC, dockerymick commented on governance/manage_policy_overview.adoc
> +- _Details_: Select the _Details_ tab to view policy details and placement information. You can configure automation from the _Policy details_ section, select the **Configure** link. You can also sel
Good catch @KevinFCormier. I updated, "You can configure automation from the _Policy details_ section, select the **Configure** link. You can also select the **local-cluster** link to view the compliance of the cluster with policy violations." 

TO 

"To configure automation from the _Policy details_ section, select the **Configure** link. You can also select the **local-cluster** link to view the compliance of the cluster with policy violations."

2021-09-28 16:14 UTC, dockerymick commented on governance/manage_policy_overview.adoc
> +- _Clusters_: Select the _Clusters_ tab to view a table list of violated clusters. Click the **View details** link to view the template details and YAML. You can also view related resources. To view
This PR is not related to issue https://github.com/open-cluster-management/backlog/issues/16329. My changes are related to what is described in issue [15529](https://github.com/open-cluster-management/backlog/issues/15529). I will make edits for #16329 in a different PR.

2021-10-01 13:41 UTC, KevinFCormier commented on governance/manage_policy_overview.adoc
> +- _Details_: Select the _Details_ tab to view policy details and placement information. You can configure automation from the _Policy details_ section, select the **Configure** link. You can also sel
We can't say "local-cluster" specifically because this is just the name of a cluster. Need to say something more like "In the placement table, the Compliance policy provides links to view the compliance of each matched cluster."

2021-10-01 13:44 UTC, KevinFCormier commented on governance/manage_policy_overview.adoc
> +- _Clusters_: Select the _Clusters_ tab to view a table list of violated clusters. Click the **View details** link to view the template details and YAML. You can also view related resources. To view
Can you please either address these comments or remove the changes and make them in a different PR for 16329?

2021-10-01 15:38 UTC, dockerymick commented on governance/manage_policy_overview.adoc
> +- _Clusters_: Select the _Clusters_ tab to view a table list of violated clusters. Click the **View details** link to view the template details and YAML. You can also view related resources. To view
@KevinFCormier We are on the same page, I will address your comments in a different PR for issue 16329

2021-10-04 13:51 UTC, KevinFCormier approved these changes

2021-10-04 14:12 UTC, dockerymick commented
@KevinFCormier Thanks for your approval! Merging this PR and will begin working on other updates related to https://github.com/open-cluster-management/backlog/issues/16329 in a different PR

2021-10-04 14:12 UTC, merged