updated whats new doc with observability service-level overview fleet…
open-cluster-management/rhacm-docs pull request #2720
Opened 2021-09-24 19:56 UTC by dislbenn

Issue: https://github.com/open-cluster-management/backlog/issues/14852 & https://github.com/open-cluster-management/backlog/issues/15902

2021-09-24 19:57 UTC, dislbenn commented
Doc updates for this issue: https://github.com/open-cluster-management/backlog/issues/16437.

2021-09-27 17:10 UTC, dislbenn commented
@dockerymick when you are available, I would like to ask for your help to review this PR.

2021-09-29 19:59 UTC, dockerymick requested changes

2021-09-29 19:59 UTC, dockerymick commented on observability/customize_observability.adoc
> +. View the _Top Cluster_ table to view the topk clusters _service-level objective_ within the cluster fleet.
What does _Top Cluster_ represent? It is best practice to avoid directional terms like up, down, left, right, top, bottom. Is the Top Cluster the cluster most recent cluster created? Latest cluster viewed or edited? Does the top cluster have more insights? 

I also suggest not italicizing service-level in this line bc it seems like we are mainly explaining what info is in the table vs stating the name of a parameter

2021-09-29 19:59 UTC, dockerymick commented on observability/customize_observability.adoc
> +. View the _Error Budget for 7 Days_ or _Error Budget for 30 Days_ gauge panels to see the _error budget_ for the past seven or 30-day period for the _service-level objective_. To see the _downtime r
I suggest the following changes: 

View the error budget for the past seven or 30-day period from the _Error Budget for 7 Days_ or _Error Budget for 30 Days_ gauge panels to see more details. To see the downtime remaining within the period for the service-level objective, view the _Downtime status_ panels.


Is this step a requirement or are we just letting the user know that this is an option?

2021-10-01 01:00 UTC, dislbenn commented on observability/customize_observability.adoc
> +. View the _Top Cluster_ table to view the topk clusters _service-level objective_ within the cluster fleet.
@dockerymick _Top Cluster_ represents the `bottomk` clusters within the cluster fleet. The data is sorted from the worst offending clusters to the clusters that are meeting the service-level objective. The section is named "top cluster" because it's getting the top clusters that are exceeding the SLO first and then displaying the clusters that are meeting their SLO. 

For example, if there are 50 clusters within a fleet, the customer can select the top(20) clusters (remember this is actually starting with the bottomk clusters, but it's displaying the top-bottom clusters). From the number that the customer selects, it will display the number of clusters within the table. So if there are 15/50 clusters that are violating the SLO, all 15 of those clusters will be displayed within the table from lowest to highest. Since the customer wanted to view the top 20 clusters, the remaining 5 clusters will be clusters that are meeting their SLO

2021-10-01 01:02 UTC, dislbenn commented on observability/customize_observability.adoc
> +. View the _Top Cluster_ table to view the topk clusters _service-level objective_ within the cluster fleet.
The top clusters listed within the table do provide more insights if the customer decides to drill down into one of the clusters for more details.

2021-10-04 03:37 UTC, dislbenn commented on observability/customize_observability.adoc
> +. View the _Error Budget for 7 Days_ or _Error Budget for 30 Days_ gauge panels to see the _error budget_ for the past seven or 30-day period for the _service-level objective_. To see the _downtime r
This step is a requirement. The end-user must view the gauge/status panels to see how much downtime they can afford for their service to be down or underperforming.

2021-10-04 03:52 UTC, dislbenn commented
@dockerymick I made the changes based upon your review. Are there any other changes that need to be implemented?

2021-10-04 13:54 UTC, dockerymick commented on observability/customize_observability.adoc
> +. View the _Top Cluster_ table to view the topk clusters _service-level objective_ within the cluster fleet.
@dislbenn Thanks for your detailed explanation! That was very helpful. Can we consider renaming Top Cluster to something more explicit? Or are there tool tips used in the Grafana dashboard (can there be?) that explains the Top cluster column? I think a user might be unclear as to what Top cluster is, I don't we need to change anything now, but i just want to keep that in mind

2021-10-04 13:56 UTC, dockerymick commented on observability/customize_observability.adoc
> +. View the _Top Cluster_ table to view the topk clusters _service-level objective_ within the cluster fleet.
I really like your description that you add for the Top cluster table, it's clear and explicit

2021-10-04 13:59 UTC, dislbenn commented on observability/customize_observability.adoc
> +. View the _Top Cluster_ table to view the topk clusters _service-level objective_ within the cluster fleet.
@dockerymick Currently, there is a tooltip explanation for the data within the table. The tooltip explains how the top cluster table data is being handled/sorted (from worst to best cluster).

2021-10-04 14:10 UTC, dockerymick approved these changes
Looks great Disaiah, thanks for starting the PR! I made a few more changes and made some comments for consideration. When you have an opportunity, may you re-review this PR and let me know if you agree with the changes. If yes, I'll move forward and merge this.

2021-10-04 14:21 UTC, dockerymick commented
@dislbenn based on our agreement of the changes in our Slack thread, i am merging this PR

2021-10-04 14:35 UTC, merged