Adding doc for backup and restore
open-cluster-management/rhacm-docs pull request #2731
Opened 2021-09-28 21:33 UTC by dockerymick

https://github.com/open-cluster-management/backlog/issues/15707

2021-09-30 18:00 UTC, birsanv requested changes

2021-09-30 18:00 UTC, birsanv commented on clusters/backup_and_restore.adoc
> +** Only managed clusters created using the `hive` API is automatically imported when the backup is restored on another hub cluster. All other managed clusters show up as _Pending Import_ and must be
small typo here :
- Only managed clusters created using the hive API **is** **(must be ARE )**automatically imported when the backup is restored on another hub cluster. All other managed clusters show up as Pending Import and must be **manually** **( add - manually - )** imported back on the new hub cluster.

2021-09-30 18:00 UTC, birsanv commented on clusters/backup_and_restore.adoc
> +**Note**: If you have any user defined private channels, you can include the channel secrets in this credentials backup if you set the `cluster.open-cluster-management.io/type` label selector to this
Typo : should be - Without this, channel secrets **will not be picked up by the cluster backup** and needs to be **manually** recreated on the restored cluster. -

2021-09-30 18:00 UTC, birsanv commented on clusters/backup_and_restore.adoc
> +View the following YAML sample of the operator:
View the following YAML sample of the operator should say : 
View the following YAML sample of the cluster restore resource. In this sample, all three types of backed up files are being restored, using the latest available backed up files.
Question 1 : 
- do we need to provide a similar sample for the backup section ? ..
- should we present here the other 2 options samples ( skip backup or use a backup by name ) ?

2021-09-30 18:00 UTC, birsanv commented on clusters/backup_and_restore.adoc
> +
I know this is missing from the Readme but I think we should add this extra info here ( I'll add it to the Readme next :) 
The restore.cluster.open-cluster-management.io resource will generate up to 3 restore velero files, one for each of the backup type you requested to be restored ( if skip is used for a backup type, no velero restore will be created )

The name of the velero Restore file is <`restore.cluster.open-cluster-management.io name`>-<`velero-backup-resource-name`>

- `restore.cluster.open-cluster-management.io name` is the name of the current restore resource
- `velero-backup-resource-name` is the name of the backup file used for restoring the data

2021-09-30 18:52 UTC, birsanv requested changes

2021-09-30 18:52 UTC, birsanv commented on clusters/backup_restore_install.adoc
> += Installing the backup and restore operator
Michaela, the installation doc is going be very different for ACM; ACM already packages the cluster backup operator, as a chart, so when you install ACM, there is a flag you can use to enable the chart

- We should remove lines 6 - 43 
- Replace them with : 
    ACM makes available the cluster backup operator as a technical preview but has the function disabled by default. To enable the cluster backup operator with ACM 2.4, when you create the MultiClusterHub resource, you should use the `Enable Cluster Backup` option and set it to `true`.  If the MultiClusterHub has been already created, you can install / uninstall the cluster backup chart by editing the MultiClusterHub and setting in the spec the `enableClusterBackup` to `true` ( install the cluster backup chart ) / `false` ( uninstall the cluster backup chart )
```
apiVersion: operator.open-cluster-management.io/v1
  kind: MultiClusterHub
  metadata:
    name: multiclusterhub
    namespace: open-cluster-management
  spec:
    availabilityConfig: High
    enableClusterBackup: true <-----
    imagePullSecret: multiclusterhub-operator-pull-secret
    ingress:
      sslCiphers:
      - ECDHE-ECDSA-AES256-GCM-SHA384
      - ECDHE-RSA-AES256-GCM-SHA384
      - ECDHE-ECDSA-AES128-GCM-SHA256
      - ECDHE-RSA-AES128-GCM-SHA256
    separateCertificateManagement: false
```

2021-09-30 18:52 UTC, birsanv commented on clusters/backup_restore_install.adoc
> +  veleroTtl: 72h # deletes scheduled backups after 72h; optional, backups never expires if option not set
Replace with : veleroTtl: 72h # deletes scheduled backups after 72h; optional, if not specified, the maximum default value set by velero is used - 720h

2021-09-30 18:52 UTC, birsanv commented on clusters/backup_restore_install.adoc
> +** `veleroTtl` is an optional property and defines the expiration time for a scheduled backup resource. A backup never expires if this property is not set.
`veleroTtl` is an optional property and defines the expiration time for a scheduled backup resource. If not specified, the maximum default value set by velero is used, which is 720h

2021-09-30 18:52 UTC, birsanv commented on clusters/backup_restore_install.adoc
> +. Create a `restore.cluster.open-cluster-management.io` resource on a different hub cluster to restore a backup. The resource restores the backup and runs any other post to restore operations, such a
Change section at line 87 with  : 
In a disaster scenario, the cluster where the backups were created becomes unavailable and data backed up needs to be moved to a new hub. This is done by running the cluster restore operation on the hub where the backed up data needs to be moved to. In this case, the restore operation is executed on a different hub than the one where the backup was created. 

There are also cases where you want to restore the data on the same hub where the backup was collected, in order to recover data from a previous snapshot. In this case both restore and backup operations are executed on the same hub.

To run a restore operation, create a `restore.cluster.open-cluster-management.io` resource on on the hub where you want to restore the data. The resource restores all resources backed up by the resource backup it is pointing to. Run the following command. 
Create the `restore.cluster.open-cluster-management.io` resource  and be sure to replace the `<oadp-operator-ns>` with the namespace name used to install the OADP Operator (the default value for the OADP Operator install namespace is `oadp-operator`):

2021-09-30 18:52 UTC, birsanv commented on clusters/backup_restore_install.adoc
> +apiVersion: cluster.open-cluster-management.io/v1beta1
This has changed .. use the new resource 

```
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Restore
metadata:
  name: restore-acm
spec:
  veleroManagedClustersBackupName: latest
  veleroCredentialsBackupName: latest
  veleroResourcesBackupName: latest
```

2021-09-30 18:52 UTC, birsanv commented on clusters/backup_restore_install.adoc
> +** The `backupName` represents the name of the `backup.velero.io` resource to be restored on the hub cluster, where the `restore.cluster.open-cluster-management.io` resource is created.
Changed to : 

The restore defines the following three required spec properties, where the restore logic is defined for the types of backed up files:

veleroManagedClustersBackupName is used to define the restore option for the managed clusters.

veleroCredentialsBackupName is used to define the restore option for the user credentials.

veleroResourcesBackupName is used to define the restore option for the hub cluster resources (Applications and Policy).

The valid options for the previously mentioned properties are following values:

latest - This property restores the last available backup file for this type of backup.

skip - This property does not attempt to restore this type of backup with the current restore operation.

<backup_name> - This property restores the specified backup pointing to it by name.

2021-09-30 18:52 UTC, birsanv commented on clusters/backup_restore_install.adoc
> +oc get restore -n <oadp-operator-ns>
To view the velero restore resource spun off by the `restore.restore.cluster.open-cluster-management.io` run 

`oc get restore.velero.io -n <oadp-operator-ns>`

2021-09-30 18:52 UTC, birsanv commented on clusters/backup_restore_install.adoc
> +** Restore a specific managed cluster:
Should say : Restore only managed cluster resources:

2021-09-30 18:52 UTC, birsanv commented on clusters/backup_restore_install.adoc
> +** Restore the managed clusters from the `acm-managed-clusters-schedule-20210902205438` backup:
Replace Restore the managed clusters from the `acm-managed-clusters-schedule-20210902205438` backup 

with 

Restore only he managed clusters resources, using the `acm-managed-clusters-schedule-20210902205438` backup

2021-09-30 18:52 UTC, birsanv commented on clusters/backup_restore_install.adoc
> +See xref:../clusters/backup_and_restore.adoc#restore-backup[Restore a backup] for a description of the required specification properties and the valid options. *Note*: The `restore.cluster.open-clust
Replace 
You must create a new `restore.cluster.open-cluster-management.io` resource.

With 
You must create a new `restore.cluster.open-cluster-management.io` resource to run a new restore operation.

2021-09-30 19:40 UTC, dockerymick commented on clusters/backup_and_restore.adoc
> +**Note**: If you have any user defined private channels, you can include the channel secrets in this credentials backup if you set the `cluster.open-cluster-management.io/type` label selector to this
Thanks for your suggestion! According to the style guide, we should avoid future tense (will)

I suggestion the follwing update: Without this, channel secrets are not identified by the cluster backup and needs to be manually recreated on the restored cluster.

Thoughts?

2021-09-30 19:55 UTC, dockerymick commented on clusters/backup_and_restore.adoc
> +View the following YAML sample of the operator:
I think that would be beneficial and increase consistency

2021-09-30 19:57 UTC, birsanv commented on clusters/backup_and_restore.adoc
> +**Note**: If you have any user defined private channels, you can include the channel secrets in this credentials backup if you set the `cluster.open-cluster-management.io/type` label selector to this
Looks great !

2021-09-30 21:01 UTC, dockerymick commented on clusters/backup_restore_install.adoc
> += Installing the backup and restore operator
Is "uninstalling the chart" similar to disabling the operator by setting the parameter to false? Are uninstall and disable different?

2021-09-30 21:25 UTC, dockerymick commented on clusters/backup_restore_install.adoc
> +. Create a `restore.cluster.open-cluster-management.io` resource on a different hub cluster to restore a backup. The resource restores the backup and runs any other post to restore operations, such a
Since this is an ordered list and I used similar language in the Restore a backup section in the backup_and_restore file, adding the description about the case seems disruptive to the list.  I think it might be best to put the info in the backup_and_restore file. 

Or should the following statement be updated:

In a usual restore scenario, the hub cluster where the backups are ran becomes unavailable, and the backed up data needs to be moved to a new hub cluster. This is done by running the cluster restore operation on the new hub cluster. In this case, the restore operation runs on a different hub cluster than the one where the backup is created.

TO 

In a disaster scenario, the cluster where the backups are ran becomes unavailable and the backed up data needs to be moved to a new hub cluster. This is done by running the cluster restore operation on the new hub cluster. In this case, the restore operation runs on a different hub cluster than the one where the backup is created.

2021-10-01 13:12 UTC, dockerymick commented on clusters/backup_restore_install.adoc
> +** The `backupName` represents the name of the `backup.velero.io` resource to be restored on the hub cluster, where the `restore.cluster.open-cluster-management.io` resource is created.
This information is in the `backup_and_restore` file, which focuses on the concept topics for the backup and restore operator. the file `backup_restore_enable` is a file for the tasks that can be completed with the operator

2021-10-01 14:54 UTC, birsanv requested changes

2021-10-01 14:54 UTC, birsanv commented on clusters/backup_and_restore.adoc
> +** Only managed clusters created using the `hive` API is automatically imported when the backup is restored on another hub cluster. All other managed clusters show up as _Pending Import_ and must be
I missed this from the initial review : 
This sentence 
Other namespace-scoped resources used to restore the following managed cluster details

Must be 
Other namespace-scoped resources used to restore the managed cluster details
( remove **following** )

2021-10-01 14:54 UTC, birsanv commented on clusters/backup_and_restore.adoc
> +**Note**: If you have any user defined private channels, you can include the channel secrets in this credentials backup if you set the `cluster.open-cluster-management.io/type` label selector to this
sorry .. this is still not accurate 
Without this, channel secrets are not identified by the cluster backup and needs to be manually recreated on the restored cluster.

It should be

Without this, channel secrets are not picked up (-or retrieved..-) by the acm-credentials-schedule backup and need to be manually recreated on the restored cluster.

2021-10-01 14:54 UTC, birsanv commented on clusters/backup_and_restore.adoc
Line 65, second sentence is not clear ..
This
You should also be able to verify the status of your hub cluster that the backed up resources contained, with the backup file that was created.

It should be something like
You should also be able to verify that the backed up resources contained by the backup are created.

2021-10-01 14:54 UTC, birsanv commented on clusters/backup_and_restore.adoc
line 67
This 
When the restore operation is complete you have to create a new `restore.cluster.open-cluster-management.io` resource.

Should be 
When the restore operation is complete, **if you want to run the same restore operation again**,  you have to create a new `restore.cluster.open-cluster-management.io` resource, with the same spec options.

2021-10-01 14:54 UTC, birsanv commented on clusters/backup_and_restore.adoc
Line 71 typo

The restore defines the **followiing**

2021-10-01 14:54 UTC, birsanv commented on clusters/backup_and_restore.adoc
> +The `restore.cluster.open-cluster-management.io` resource creates up to three `restore.velero.io` resources, one for each of the backup types that you requested to be restored. View the following des
This is not correct : 
View the following descriptions of the `restore.velero.io` parameters:

What we are trying to say here : 
The name of the `restore.velero.io` resources created by the `restore.cluster.open-cluster-management.io` resource is generated using the following rule ( template .. ) 
 `<restore.cluster.open-cluster-management.io name>-<velero-backup-resource-name>`, where : 
- `<restore.cluster.open-cluster-management.io name>` is the name of the `restore.cluster.open-cluster-management.io` resource triggering the restore.
- `<velero-backup-resource-name>` is the name of the velero backup file this is used for restoring the data.
For example, the `restore.cluster.open-cluster-management.io` resource named `restore-acm` creates `restore.velero.io` restore resources with the following name format: 
- `restore-acm-acm-managed-clusters-schedule-20210902205438` for restoring managed clusters backups. In this sample, the `backup.velero.io`  backup name used to restore the resource is `acm-managed-clusters-schedule-20210902205438`
- `restore-acm-acm-credentials-schedule-20210902206789` - for restoring credentials backups. In this sample, the `backup.velero.io`  backup name used to restore the resource is `acm-managed-clusters-schedule-20210902206789`
- `restore-acm-acm-resources-schedule-20210902201234` - for restoring applications and policies backups. In this sample, the `backup.velero.io`  backup name used to restore the resource is `acm-managed-clusters-schedule-20210902201234`

2021-10-01 14:54 UTC, birsanv commented on clusters/backup_restore_enable.adoc
> +Enable the cluster backup and restore operator by creating the `MultiClusterHub` resource and update the `enableClusterBackup` parameter to `true`.
I think it's better : 
The cluster backup and restore operator can be enabled when the `MultiClusterHub` resource is created first time. Use the `Enable Cluster Backup` ui option and set it to true.

2021-10-01 14:54 UTC, birsanv commented on clusters/backup_restore_enable.adoc
> +If the `MultiClusterHub` resource is already created, you can disable the cluster backup YAML by editing the `MultiClusterHub` resource. Set `enableClusterBackup` to `false`.
If the `MultiClusterHub` resource is already created, you can install or uninstall the cluster backup operator by editing the `MultiClusterHub` resource and updating the enableClusterBackup spec option. Set `enableClusterBackup` to `false` if you want to uninstall the cluster backup operator ; set the option to `true` if you want to install the operator.

2021-10-01 14:54 UTC, birsanv commented on clusters/backup_restore_enable.adoc
For line 49 

Run the following command. Be sure to replace the ..

Should be

You can use the cluster backup and restore operator `backupschedule.cluster.open-cluster-management.io` and `restore.cluster.open-cluster-management.io` resource samples available here (https://github.com/open-cluster-management/cluster-backup-operator/tree/main/config/samples) to create a backup or restore resource. Run the following command to create a `backupschedule.cluster.open-cluster-management.io` resource using the `cluster_v1beta1_backupschedule.yaml` sample file.

2021-10-01 14:54 UTC, birsanv commented on clusters/backup_restore_enable.adoc
>  View the following descriptions of the following properties:
Maybe : View the following descriptions of the `backupschedule.cluster.open-cluster-management.io` spec properties:

2021-10-01 14:54 UTC, birsanv commented on clusters/backup_restore_enable.adoc
>  . Check the status of your scheduled cluster backups, which displays the definition for the three `schedule.velero.io` resources. Run the following command:
Check the status of your `backupschedule.cluster.open-cluster-management.io` resource, which displays the definition and status for the three `schedule.velero.io` resources, created by this resource. Run the following command:

2021-10-01 14:54 UTC, birsanv commented on clusters/backup_restore_enable.adoc
>  +
Line 81, where we discuss the restore 

- we should present as we did with the backup, the fact that you can create the restore resource using the samples available : 
- 
Replace: 
Create a restore.cluster.open-cluster-management.io resource on a different hub cluster to restore a backup. The resource restores the backup and runs any other post to restore operations, such as registering restored remote clusters with the new hub cluster. Run the following command. Run the following command. Be sure to replace the <oadp-operator-ns> with the namespace name used to install the OADP Operator (the default value for the OADP Operator install namespace is oadp-operator):

With : 
In a usual restore scenario, the restore operation is executed on a different hub.  

To trigger a restore operation, create the `restore.cluster.open-cluster-management.io` on the hub where you want the backups to be restored.
You can use the cluster backup and restore operator `backupschedule.cluster.open-cluster-management.io` and `restore.cluster.open-cluster-management.io` resource samples available here (https://github.com/open-cluster-management/cluster-backup-operator/tree/main/config/samples) to create a backup or restore resource. Run the following command to create a `restore.cluster.open-cluster-management.io` resource using the `cluster_v1beta1_restore.yaml` sample file. Be sure to replace the `<oadp-operator-ns>` with the namespace name used to install the OADP Operator (the default value for the OADP Operator install namespace is oadp-operator):
`kubectl create -n <oadp-operator-ns> -f config/samples/cluster_v1beta1_restore.yaml`

2021-10-01 14:54 UTC, birsanv commented on clusters/backup_restore_enable.adoc
>  +
Same comment as for schedulebackup 

Replace : 
View the following description of the following property:

With : 
View the following descriptions of the restore.cluster.open-cluster-management.io spec properties:

2021-10-01 14:54 UTC, birsanv commented on clusters/backup_restore_enable.adoc
>    veleroResourcesBackupName: latest
This is outdated : 
veleroResourcesBackupName: latest

Replace with ( from the same PR , the previous file )

https://github.com/open-cluster-management/rhacm-docs/pull/2731/files/506428e7249ece389fdc9d71a44423afebad396e..3f0623880387e6ccf138430535d6a770366b3501#diff-a96e68937935c43b41df1454438d13f1f407999b329d06fd5733541d90b12763R35

2021-10-01 18:43 UTC, birsanv requested changes

2021-10-01 18:43 UTC, birsanv commented on clusters/backup_and_restore.adoc
> +You must install the OADP Operator. See link:https://github.com/openshift/oadp-operator/blob/master/docs/install_olm.md[Install OADP Operator using OperatorHub]. Be sure to complete the steps to link
The link to the Velero Resource should be https://github.com/openshift/oadp-operator/blob/master/docs/install_olm.md#create-the-velero-custom-resource

2021-10-01 18:43 UTC, birsanv commented on clusters/backup_and_restore.adoc
> +* `restore.cluster.open-cluster-management.io name` is the name of the current `restore.cluster.open-cluster-management.io` resource., which initiates the restore.
typo here ( . and , ) resource., which initiates the restore.

2021-10-01 18:43 UTC, birsanv commented on clusters/backup_restore_enable.adoc
> +*Note*: Be sure to follow the OADP Operator installation instructions to create the Velero resource, and to create a valid connection to a backup storage location, where the backups are stored. View
Use this link for the _View the installation and setup steps from the_ ...  https://github.com/openshift/oadp-operator/blob/master/docs/install_olm.md

2021-10-01 18:43 UTC, birsanv commented on clusters/backup_restore_enable.adoc
> +The resource restores the backup and runs any other post to restore operations, such as registering restored remote clusters with the new hub cluster. Run the following command. Run the following com
Line 90 should be removed completely ..

The resource restores the backup and runs any other post to restore operations,...

2021-10-01 18:43 UTC, birsanv commented on clusters/backup_restore_enable.adoc
> +** The `backupName` represents the name of the `backup.velero.io` resource to be restored on the hub cluster, where the `restore.cluster.open-cluster-management.io` resource is created.
backupName is not the right property. 

Find the doc where we describe the right spec , this : 

The restore defines the following three required spec properties, where the restore logic is defined for the types of backed up files:

veleroManagedClustersBackupName is used to define the restore option for the managed clusters.

veleroCredentialsBackupName is used to define the restore option for the user credentials.

veleroResourcesBackupName is used to define the restore option for the hub cluster resources (Applications and Policy).

The valid options for the previously mentioned properties are following values:

latest - This property restores the last available backup file for this type of backup.

skip - This property does not attempt to restore this type of backup with the current restore operation.

<backup_name> - This property restores the specified backup pointing to it by name.

2021-10-04 17:11 UTC, dockerymick commented on clusters/backup_and_restore.adoc
> +View the following YAML sample of the operator:
Since this is doc'ed and was discussed during live review

2021-10-04 17:25 UTC, dockerymick commented on clusters/backup_and_restore.adoc
> +
This feedback was applied and discussed during a live meeting. Marking this comment as resolved

2021-10-04 17:26 UTC, dockerymick commented on clusters/backup_restore_install.adoc
> += Installing the backup and restore operator
This was also discussed during the live meeting. When the backup operator is enabled, the backup chart is installed, when it is disabled it is uninstalled.

2021-10-04 17:29 UTC, dockerymick commented on clusters/backup_restore_install.adoc
> +. Create a `restore.cluster.open-cluster-management.io` resource on a different hub cluster to restore a backup. The resource restores the backup and runs any other post to restore operations, such a
This was also discussed during the live review. Marking this as resolved

2021-10-04 18:00 UTC, dockerymick commented on clusters/backup_and_restore.adoc
This is added in the Note on line 58

2021-10-04 19:39 UTC, birsanv requested changes

2021-10-04 19:39 UTC, birsanv commented on clusters/backup_restore_enable.adoc
> +Run the following command, be sure to replace the `<oadp-operator-ns>` with the namespace name used to install the OADP Operator (the default value for the OADP Operator install namespace is `oadp-op
Remove this, it is already mentioned above ( and there is no following command )

2021-10-04 19:55 UTC, birsanv approved these changes
looks good, thank you Mikela !

2021-10-05 18:29 UTC, cadawson approved these changes
Thanks Mikela! Looks good! I have a PR to your branch with nits, and comments in this fine that are more recommendations or questions here. Let me know if you have any questions. I am looking into the VolSync now, which might be a way to back up clusters. I would like to know how yours and mine are related, or if they even are. I can keep you posted on that. Here is a link to the PR: https://github.com/open-cluster-management/rhacm-docs/pull/2747. It should push the changes into your branch, not 2.4_stage. Thanks!

2021-10-05 18:29 UTC, cadawson commented on clusters/backup_and_restore.adoc
> +=== Schedule a cluster backup
Should this be a level under architecture, or at the same level?

2021-10-05 18:29 UTC, cadawson commented on clusters/backup_and_restore.adoc
> +**Note**: If you have any user defined private channels, you can include the channel secrets in this credentials backup if you set the `cluster.open-cluster-management.io/type` label selector to this
The sentence beginning "Without this," what is "this?" I think it might be "Without the channel secrets,..."

2021-10-05 18:29 UTC, cadawson commented on clusters/backup_and_restore.adoc
> +* `acm-resources-schedule`: This resource is used to schedule backups for the `Applications` and `Policy` resources, including any required resources, such as: `Channels`, `Subscriptions`, `Deployabl
This list confuses me a little: This resource is used to schedule backups for the `Applications` and `Policy` resources, including any required resources, such as: `Channels`, `Subscriptions`, `Deployables` and `PlacementRules` for `Applications` and `PlacementBindings`, `Placement`, `PlacementDecisions` for `Policy`.
Are they three categories, ie:
Applications: Channels, Subscriptions, Deployables, and PlacementRules
Policy: PlacementBindings, Placement, and PlacementDecisions. 
If so, maybe consider using a list for it, breaking it into two sentences, or maybe adding a comma after Deployables.

2021-10-05 18:29 UTC, cadawson commented on clusters/backup_and_restore.adoc
> +* `velero-backup-resource-name` is the name of the velero backup file that is used for restoring the data. For example, the `restore.cluster.open-cluster-management.io` resource named `restore-acm` c
I think I caught this, but make sure that Velero is capitalized if it is referring to the product. It is fine if it is in the resource name.

2021-10-05 18:29 UTC, cadawson commented on clusters/backup_restore_enable.adoc
> +** `veleroTtl` is an optional property and defines the expiration time for a scheduled backup resource. If not specified, the maximum default value set by Velero is used, which is `720h`.
This might be a camelcase double t, but wanted to make sure it was intentional.

2021-10-05 18:29 UTC, cadawson commented on clusters/backup_restore_enable.adoc
> +. Run the following command to create a `restore.cluster.open-cluster-management.io` resource using the `cluster_v1beta1_restore.yaml` sample file. Be sure to replace the `<oadp-operator-ns>` with th
Don't need the <> in the variable here. Just inside the tic marks.

2021-10-06 17:23 UTC, dockerymick commented on clusters/backup_and_restore.adoc
> +=== Schedule a cluster backup
Great catch, it should be H2

2021-10-06 17:25 UTC, dockerymick commented on clusters/backup_and_restore.adoc
> +**Note**: If you have any user defined private channels, you can include the channel secrets in this credentials backup if you set the `cluster.open-cluster-management.io/type` label selector to this
Without the `cluster.open-cluster-management.io/type` label selector, channel secrets..

2021-10-06 17:27 UTC, dockerymick commented on clusters/backup_and_restore.adoc
> +* `velero-backup-resource-name` is the name of the velero backup file that is used for restoring the data. For example, the `restore.cluster.open-cluster-management.io` resource named `restore-acm` c
Thanks!

2021-10-06 17:30 UTC, dockerymick commented on clusters/backup_restore_enable.adoc
> +** `veleroTtl` is an optional property and defines the expiration time for a scheduled backup resource. If not specified, the maximum default value set by Velero is used, which is `720h`.
Thanks for bringing this up. I double checked and confirmed that it is correct as is: https://github.com/open-cluster-management/cluster-backup-operator/blob/main/README.md#usage

2021-10-06 17:32 UTC, dockerymick commented on clusters/backup_restore_enable.adoc
> +. Run the following command to create a `restore.cluster.open-cluster-management.io` resource using the `cluster_v1beta1_restore.yaml` sample file. Be sure to replace the `<oadp-operator-ns>` with th
great catch, thank you

2021-10-06 17:38 UTC, dockerymick commented on clusters/backup_and_restore.adoc
> +* `acm-resources-schedule`: This resource is used to schedule backups for the `Applications` and `Policy` resources, including any required resources, such as: `Channels`, `Subscriptions`, `Deployabl
Great suggestion, i made the update

2021-10-06 17:45 UTC, dockerymick commented
@cadawson thanks for the suggestions, i merged your PR before I made other changes. @birsanv thanks for your patience. Merging this PR and will update the issue accordingly

2021-10-06 17:46 UTC, merged

2021-10-07 14:08 UTC, swopebe commented on clusters/backup_and_restore.adoc
> +
I know you merged this -- I needed to take a day off this week and could not finish review...

I am just going to leave a couple comments but we can address them another time.

Line 4 is a bit confusing and I think this can be part of the prereqs?

2021-10-07 14:09 UTC, swopebe commented on clusters/backup_and_restore.adoc
> +You must install the OADP Operator. See link:https://github.com/openshift/oadp-operator/blob/master/docs/install_olm.md[Install OADP Operator using OperatorHub]. Be sure to complete the steps to link
Wonder if we should first spell our OADP:
**OpenShift API for Data Protection **

2021-10-07 14:10 UTC, swopebe commented on clusters/backup_and_restore.adoc
> +
These sentences are pretty long and could be broken up concisely.

2021-10-07 14:11 UTC, swopebe commented on clusters/backup_and_restore.adoc
> +*** Secrets and ConfigMaps from the `hive` and `openshift-operator-lifecycle-manager` namespaces, and from all of the `ManagedClusters resources` namespaces created on the hub cluster.
This should not be bold. Let's reserve bold for special tags, headings.

2021-10-07 14:12 UTC, swopebe commented on clusters/backup_and_restore.adoc
> +
I feel we should spend some time on formatting here, I was pretty disoriented. Pulling out steps, less bold, and bullets only where needed will help.