Updating grc doc Status reorganization
open-cluster-management/rhacm-docs pull request #2744
Opened 2021-10-04 19:50 UTC by dockerymick

https://github.com/open-cluster-management/backlog/issues/16329

2021-10-05 20:21 UTC, KevinFCormier requested changes
I made a few suggestions. Let me know if you have any questions. Thanks!

2021-10-05 20:21 UTC, KevinFCormier commented on governance/create_compliance_operator.adoc
> +. View the policy violations by selecting the _Clusters_ tab.
You could also select the _Templates_ tab here... they are just slightly different ways of organizing the same information. The Clusters tab shows each combination of cluster and template with the compliance for each (whether or not there are violations). The Templates tab has a separate table for each template, but each table lists the applicable clusters and their compliance status. This comment applies to all similar changes in this PR.

2021-10-05 20:21 UTC, KevinFCormier commented on governance/create_etcd_pol.adoc
> +*Note*: You can filter the table list of your policies by selecting the _All policies_ tab or _Cluster violations_ tab.
I assume this is referring to these toggle buttons? Note that it just says "Policies" not "All policies"
![image](https://user-images.githubusercontent.com/42188127/136095524-7b296ecb-a0ac-4464-9dbc-c3e189b295f8.png)

2021-10-05 20:21 UTC, KevinFCormier commented on governance/manage_policy_overview.adoc
> +- _Details_: Select the _Details_ tab to view policy details and placement details. In the _Placement_ table, the _Compliance_ column provides links to view the compliance of the cluster that is disp
```suggestion
- _Details_: Select the _Details_ tab to view policy details and placement details. In the _Placement_ table, the _Compliance_ column provides links to view the compliance of the clusters that are displayed.
```

2021-10-05 20:21 UTC, KevinFCormier commented on governance/manage_policy_overview.adoc
> +- _Clusters_: Select the _Clusters_ tab to view a table list of clusters with policy violations. Click the **View details** link to view the template details and YAML. You can also view related resou
All clusters selected by the placement are shown, not just the ones with policy violations.
![image](https://user-images.githubusercontent.com/42188127/136095899-072d6d1f-0dff-4b6e-9e06-9d6b2132cec6.png)

In the last sentence, I would change "a timestamp" to just "time" since it is using phrases like "an hour ago" etc.

2021-10-05 20:21 UTC, KevinFCormier commented on governance/manage_policy_overview.adoc
> +- _Templates_: Select the _Templates_ tab to view a table list of clusters with policy violations for each template. You can view the compliance status, violation message, timestamp of the last repor
Same comments here - it's not only violations that are shown; compliant clusters are shown for each template. I would avoid using the term "timestamp", and I would mention the "View history" link here as well, where users can see recent changes in the compliance status.

2021-10-06 18:15 UTC, dockerymick commented on governance/create_compliance_operator.adoc
> +. View the policy violations by selecting the _Clusters_ tab.
Good point, I updated the step to read: 

View the policy violations by selecting the _Clusters_ or _Templates_ tab.

2021-10-06 18:23 UTC, dockerymick commented on governance/create_etcd_pol.adoc
> +*Note*: You can filter the table list of your policies by selecting the _All policies_ tab or _Cluster violations_ tab.
Yes, thanks!

2021-10-06 18:32 UTC, dockerymick commented on governance/manage_policy_overview.adoc
> +- _Clusters_: Select the _Clusters_ tab to view a table list of clusters with policy violations. Click the **View details** link to view the template details and YAML. You can also view related resou
Thanks for clarifying and suggestion here!

2021-10-07 23:11 UTC, KevinFCormier approved these changes

2021-10-08 14:35 UTC, dockerymick commented
Thanks for your approval @KevinFCormier !

2021-10-08 15:21 UTC, merged