open-cluster-management/backlog#16593 no fips pwr z
open-cluster-management/rhacm-docs pull request #2810
Opened 2021-10-21 20:55 UTC by cadawson

2021-10-22 05:02 UTC, rahularora19911 requested changes

2021-10-22 05:02 UTC, rahularora19911 commented on release_notes/fips_readiness.adoc
> +* {ocp} does not support FIPS on the IBM Power (`pp264le`) and IBM Z (`s390x`) architectures.
I guess it should be 'ppc64le' instead of 'pp264le'. @jaywcarman  can confirm this.
rest looks fine.
Thanks!

2021-10-22 10:22 UTC, jaywcarman commented on release_notes/fips_readiness.adoc
> +* {ocp} does not support FIPS on the IBM Power (`pp264le`) and IBM Z (`s390x`) architectures.
@cadawson - confirming that it should be `ppc64le`. (thanks @rahularora19911 !)

Also agree that it the change looks good to go once the typo is fixed.

2021-10-25 12:27 UTC, cadawson commented on release_notes/fips_readiness.adoc
> +* {ocp} does not support FIPS on the IBM Power (`pp264le`) and IBM Z (`s390x`) architectures.
Updated that. Thanks!

2021-10-25 12:27 UTC, merged