open-cluster-management/backlog#12254 Add sno z
open-cluster-management/rhacm-docs pull request #2827
Opened 2021-10-26 19:04 UTC by cadawson

2021-10-26 19:06 UTC, cadawson commented
Hi @CrystalChun and @rahularora19911 . I added some sizing and performance information for SNO clusters and IBM Z. If you will review the piece that you are most familiar with, I would appreciate it.

2021-10-28 06:59 UTC, rahularora19911 requested changes

2021-10-28 06:59 UTC, rahularora19911 commented on install/plan_capacity.adoc
> +IBM Z systems provide the ability to configure simultaneous multithreading (SMT), which extends the number of vCPUs that can run on each core. If you configured SMT, your SMT level determines how you
Hi @cadawson,
Can we replace this SMT stuff with the one below:

```
IBM Z systems provide the ability to configure simultaneous multithreading (SMT), which extends the number of vCPUs that can run on each core. If you configured SMT, One physical core (IFL) provides two logical cores (threads). The hypervisor can provide two or more vCPUs.

One vCPU is equivalent to one physical core when simultaneous multithreading (SMT), or hyperthreading, is not enabled. When enabled, use the following formula to calculate the corresponding ratio: (threads per core × cores) × sockets = vCPUs.

For more information about SMT, see https://www.ibm.com/docs/en/aix/7.2?topic=concepts-simultaneous-multithreading[Simultaneous multithreading].
```

I am just trying to be in sync with the OCP documentation here. 
https://access.redhat.com/documentation/en-us/openshift_container_platform/4.9/html-single/installing/index#minimum-resource-requirements_installing-ibm-z

Please let me know. Thanks!

2021-10-28 15:47 UTC, CrystalChun commented on install/perform_scale.adoc
> +|Node | Number | CPU: utilization | CPU: Logical cores | Memory: Utilization | Memory: GB consumed
I would recommend including the actual CPU and Memory values. Do you have these numbers Chris?

2021-10-28 15:48 UTC, CrystalChun commented on install/perform_scale.adoc
> +|Node | Number | CPU: utilization | CPU: Logical cores | Memory: Utilization | Memory: GB consumed
Also I don't think we should include the `Number` column. In this context, it doesn't mean much since we're only looking at the peak utilization of any node type.

2021-11-02 16:52 UTC, cadawson commented on install/plan_capacity.adoc
> +IBM Z systems provide the ability to configure simultaneous multithreading (SMT), which extends the number of vCPUs that can run on each core. If you configured SMT, your SMT level determines how you
Yep. I updated it.

2021-11-02 16:55 UTC, cadawson commented on install/perform_scale.adoc
> +|Node | Number | CPU: utilization | CPU: Logical cores | Memory: Utilization | Memory: GB consumed
@CrystalChun: After our discussion the other day, I think we decided to remove this until we have more current information. Let me know if that is not correct.

2021-11-02 18:10 UTC, CrystalChun commented on install/perform_scale.adoc
> +|Node | Number | CPU: utilization | CPU: Logical cores | Memory: Utilization | Memory: GB consumed
Yep, thanks Chris!

2021-11-05 07:30 UTC, rahularora19911 approved these changes
LGTM, Thanks!

2021-11-05 12:44 UTC, merged