Updating the insights doc and source parameter info
open-cluster-management/rhacm-docs pull request #2829
Opened 2021-10-26 22:23 UTC by dockerymick

https://github.com/open-cluster-management/backlog/issues/15926

2021-10-26 22:24 UTC, dockerymick commented
@xrajesh  when or if you have an opportunity, may you also take a look at this PR. i made some updates to for the policy reports doc and wanted to ensure that my changes are accurate.

2021-10-27 17:48 UTC, xrajesh approved these changes

2021-10-27 18:01 UTC, xrajesh requested changes

2021-10-27 18:01 UTC, xrajesh commented on observability/manage_insights.adoc
> +//should proably add documentation on creating a PolicyReport if that can be done, or is it only generated by the insights-client?
@dockerymick we should remove the comment above

2021-11-01 17:28 UTC, willkutler approved these changes

2021-11-01 17:37 UTC, dockerymick commented
@willkutler thanks for your approval ! @xrajesh thanks for your review as well! Merging this PR

2021-11-01 17:37 UTC, merged