Updating known issue for search-collector 2.4
open-cluster-management/rhacm-docs pull request #2894
Opened 2021-11-08 13:47 UTC by dockerymick

https://github.com/open-cluster-management/backlog/issues/17208

2021-11-08 20:37 UTC, SherinV requested changes

2021-11-08 20:37 UTC, SherinV commented on release_notes/known_issues.adoc
> +. If search is enabled on the hub cluster, which means the `search-redisgraph-pod` is deployed, increase the memory usage by editing the `search-collector` deployment.
If search is enabled on the hub cluster, which means the `search-redisgraph-pod` is deployed, increase the memory allocated by editing the memory limits on the `search-collector` deployment.

2021-11-08 21:47 UTC, dockerymick commented on release_notes/known_issues.adoc
> +. If search is enabled on the hub cluster, which means the `search-redisgraph-pod` is deployed, increase the memory usage by editing the `search-collector` deployment.
@SherinV I updated the sentence to read the following: If search is enabled on the hub cluster, which means the `search-redisgraph-pod` is deployed, increase the allocated memory by editing the `search-collector` deployment.

2021-11-09 04:07 UTC, SherinV commented on release_notes/known_issues.adoc
> +
reduce memory usage by scaling down the `search-collector` deployment to `0` replicas.

2021-11-09 13:28 UTC, dockerymick commented on release_notes/known_issues.adoc
> +
Updated

2021-11-09 14:16 UTC, SherinV approved these changes

2021-11-09 14:17 UTC, SherinV approved these changes

2021-11-09 20:53 UTC, merged