Edit Submariner overview and prereqs docs
open-cluster-management/rhacm-docs pull request #3009
Opened 2021-12-07 02:10 UTC by dfarrell07

Batch of small edits to the Submariner overview and prerequisites docs.

Signed-off-by: Daniel Farrell <dfarrell@redhat.com>

2021-12-07 17:18 UTC, dfarrell07 commented
/cc @nyechiel @skitt

2021-12-08 07:47 UTC, nyechiel commented
/lgtm

2021-12-08 13:59 UTC, cadawson requested changes
This looks good. Thank you. I made some minor edits and added a comment. Let me know if you have questions or concerns. Thanks!

2021-12-08 13:59 UTC, cadawson commented on services/submariner.adoc
> +* Non-overlapping Pod and Service Classless Inter-Domain Routing (CIDR) ranges for clusters. The upstream https://submariner.io/getting-started/architecture/globalnet/[Globalent] feature, which allow
If this feature is not supported, then I suggest we don't provide the link. Best case would be not to mention that feature at all, as we said that they could not be overlapping. If there is a compelling reason to mention it (like customers will definitely know about it and wonder specifically whether it is supported), we can state that it is not supported. I think the link provides an opportunity for them to link away to something that is not useful. Thoughts?

2021-12-08 14:12 UTC, cadawson commented
Is there an issue that we can use for this? If not, will you create an issue using the doc template for this, and assign it to me @dfarrell07 ? Thanks!

2021-12-09 03:47 UTC, dfarrell07 commented on services/submariner.adoc
> +* Non-overlapping Pod and Service Classless Inter-Domain Routing (CIDR) ranges for clusters. The upstream https://submariner.io/getting-started/architecture/globalnet/[Globalent] feature, which allow
Thanks for the review @cadawson! I do think users will know that Globalnet is a feature of Submariner, and will wonder if it's supported and why not. Fortually, as I understand it (@nyechiel can confirm), Globalnet is planned for ACM 2.5. I updated the proposed wording to remove the link and try to clarify for users that support coming, but without being too committed to details.

2021-12-09 03:59 UTC, dfarrell07 commented
> Is there an issue that we can use for this? If not, will you create an issue using the doc template for this, and assign it to me @dfarrell07 ? Thanks!

No Issue, I was just planning on sending some drive-by contributions to the Submariner docs. :nerd_face: 

We're talking about [this template](https://github.com/open-cluster-management/rhacm-docs/blob/2.4_stage/.github/ISSUE_TEMPLATE.md) I assume? Or should I follow that internal user process? (why is there a difference between the two? :sweat_smile:)

2021-12-14 16:14 UTC, cadawson commented on services/submariner.adoc
> +* Non-overlapping Pod and Service Classless Inter-Domain Routing (CIDR) ranges for clusters. The upstream https://submariner.io/getting-started/architecture/globalnet/[Globalent] feature, which allow
Thanks for the explanation @dfarrell07 . We will leave the mention, then. In the formal docs, we are very careful about preannouncing features and support. The reason is that we might decide in the end that we don't want to support a certain feature when the market changes. If we said we would, then someone might be able to claim that we misled them into a purchase based on that statement. 
Anyway, I tweaked the wording just a little. It mentions that it is not supported, but doesn't hint that it will be. When it is, we will just add it then. Will this work? Thanks!

2021-12-14 16:42 UTC, cadawson commented
Hi @dfarrell07 . Sorry to scare you. :-) That wasn't the intent. Typically we tie our doc PRs back to an issue. That might be a dev issue or, most often, a doc issue. I wasn't sure if you had one. I created one for this, just so we have a record. It is issue #18505 (https://github.com/open-cluster-management/backlog/issues/18505).

2021-12-14 18:03 UTC, dfarrell07 commented on services/submariner.adoc
> +* Non-overlapping Pod and Service Classless Inter-Domain Routing (CIDR) ranges for clusters. The upstream https://submariner.io/getting-started/architecture/globalnet/[Globalent] feature, which allow
That makes sense @cadawson, thanks for the explanation! Yes the new wording looks good to me. :heavy_check_mark:

2021-12-14 18:05 UTC, dfarrell07 commented
> I created one for this, just so we have a record. It is issue #18505 ([open-cluster-management/backlog#18505](https://github.com/open-cluster-management/backlog/issues/18505)).

Thanks @cadawson! Can I use that same Issue for other small Submariner docs fixes?

2021-12-14 20:16 UTC, cadawson commented
Yes, feel free to use it for additional minor updates. Thanks!

2021-12-15 15:02 UTC, merged