stolostron/backlog#19002 volsync updates
open-cluster-management/rhacm-docs pull request #3060
Opened 2022-01-13 18:33 UTC by cadawson

2022-02-01 16:28 UTC, tesshuflower commented
@cadawson the changes are looking really good to me!

It's a bit hard for me to tell looking at the PR, so I may have just missed it - but I think you have things like a source.yaml (for ReplicationSource) in the docs itself which is really nice - do you do the same for the ReplicationDestination?  I still see some references that talk about taking examples from `examples/rsync`.  Will we expect the user to pull files from github or will it all be converted to text in the doc?

2022-02-02 12:35 UTC, cadawson commented
Thanks @tesshuflower . I have examples of the text at the beginning of the steps. My thought was: Introduce step > show yaml sample for a look at what it should look like > provide the steps to get there. Does that sound reasonable? Thanks!

2022-02-02 14:56 UTC, tesshuflower commented
> Thanks @tesshuflower . I have examples of the text at the beginning of the steps. My thought was: Introduce step > show yaml sample for a look at what it should look like > provide the steps to get there. Does that sound reasonable? Thanks!

That sounds great!  Let me go through and look at it in more detail

2022-02-02 14:58 UTC, tesshuflower commented on clusters/volsync.adoc
> +. For Rsync-based replication, configure custom resources on the source and destination clusters. The custom resources use the `address` value to connect the source to the destination, and the `sshKe
Can we move this entire section outside of the "Installing VolSync on the managed clusters" section?  I think this is essentially a walkthrough of an example scenario of setting up pvc replication between managed clusters using rsync.

2022-02-02 15:01 UTC, tesshuflower commented on clusters/volsync.adoc
> +. For Rsync-based replication, configure custom resources on the source and destination clusters. The custom resources use the `address` value to connect the source to the destination, and the `sshKe
Is it possible to also add a description of the scenario?  something along the lines of "This example configures PVC replication from a managed cluster named `source` in namespace `source` to a managed cluster named `destination` in namespace `dest`. Wondering if we should actually name the clusters `source-cluster` and `destination-cluster`.

2022-02-02 15:02 UTC, tesshuflower commented on clusters/volsync.adoc
> +$ kubectl create -n dest -f examples/rsync/volsync_v1alpha1_replicationdestination_remotecluster.yaml
This line is telling the users to create the replicationdestination from a yaml file that doesn't exist.  Can we move this to after the explanation of the yaml in the next lines?  I.e. Show the user the replicationdestination - let them copy this yaml file and edit it, and then tell them to run the cmd to create the replicationdestination.

2022-02-02 15:04 UTC, tesshuflower commented on clusters/volsync.adoc
> +... Run the following command to copy the value of `.status.rsync.address`:
Maybe add some explanation here - after the replication destination is created, it should fill out the status with an address.  You can see in the volsync docs there is a bit of an explanation about replication destination and its fields - something like this would be helpful here.  https://volsync.readthedocs.io/en/stable/usage/rsync/index.html#destination-status

2022-02-02 15:07 UTC, tesshuflower commented on clusters/volsync.adoc
> +$ kubectl create -n source -f examples/source-database
If we're embedding the files in the doc, then we don't have this source database (user doesn't have these examples files).  Maybe a decision needs to be made here whether we run through this entire database example or simply tell them they can deploy their app which creates their source PVC on the source-cluster.

2022-02-02 15:12 UTC, tesshuflower commented on clusters/volsync.adoc
> +... Copy the SSH secret from the destination cluster by entering the following command on the destination cluster:
Need to be very explicit that this command should be done against the destination-cluster.  Maybe some consistent marker in the doc to indicate what commands run against what cluster?  I guess I don't like the wording "enter the command ON the destination cluster".  This command is assuming it's running on some system that is able to access both source and destination cluster.

Some docs mention explicitly things like:

```
Run command against the source cluster
# KUBECONFIG=source-cluster.config
# kubectl get ....

Run command against destination-cluster
# export KUBECONFIG=destination-cluster.config
# kubectl get
```

^ Just as an example - is it possible to see what is generally done in the ACM docs for this kind of thing?

2022-02-02 15:13 UTC, tesshuflower commented on clusters/volsync.adoc
> +$ sed -i "s/my.host.com/$ADDRESS/g" examples/rsync/volsync_v1alpha1_replicationsource_remotecluster.yaml
these files in examples do not exist, so instructions would need to be modified to tell the user to copy the sample replicationsource.yaml above, edit it and then run the sed and create commands

2022-02-02 20:19 UTC, cadawson commented on clusters/volsync.adoc
> +. For Rsync-based replication, configure custom resources on the source and destination clusters. The custom resources use the `address` value to connect the source to the destination, and the `sshKe
I created a new section out of this, and made it a separate list of steps

2022-02-02 20:47 UTC, cadawson commented on clusters/volsync.adoc
> +. For Rsync-based replication, configure custom resources on the source and destination clusters. The custom resources use the `address` value to connect the source to the destination, and the `sshKe
Added a description.

2022-02-02 21:11 UTC, cadawson commented on clusters/volsync.adoc
> +$ kubectl create -n dest -f examples/rsync/volsync_v1alpha1_replicationdestination_remotecluster.yaml
Moved some things around here. I think I understood what you meant.

2022-02-02 21:35 UTC, cadawson commented on clusters/volsync.adoc
> +$ sed -i "s/my.host.com/$ADDRESS/g" examples/rsync/volsync_v1alpha1_replicationsource_remotecluster.yaml
Tried to make this change.  Please review.

2022-02-02 21:42 UTC, cadawson commented on clusters/volsync.adoc
> +... Copy the SSH secret from the destination cluster by entering the following command on the destination cluster:
Updated this to be against.

2022-02-04 15:24 UTC, tesshuflower commented on clusters/volsync.adoc
> +.. Copy the following YAML content to create a new file called `replication_destination.yaml` on the destination cluster:
The file itself most likely won't be created on the destination cluster - can probably just end with at "... create a new file called replication_destination.yaml"

2022-02-04 15:27 UTC, tesshuflower commented on clusters/volsync.adoc
> +== Configiring Rsync replication across managed clusters
typo "Configiring"

2022-02-04 15:28 UTC, tesshuflower commented on clusters/volsync.adoc
> +This example provides the steps to configure an Rsync replication from a PVC on the `source` cluster in the `source` namespace to a PVC on a `destination` cluster in the `dest` namespace.
Possible to move this up to be the first thing under the "Configuring rsync replication accross managed clusters" header?

2022-02-04 15:31 UTC, tesshuflower commented on clusters/volsync.adoc
> +. Configure your destination cluster named `destination`.
Think we need to be consistent here throughout the example - later on we simply call this the `destination cluster`.  So maybe we can always refer to it as "the destination cluster" rather than saying "...destination cluster named destination".  This is probably my fault with some initial wording I gave you.

2022-02-04 15:37 UTC, tesshuflower commented on clusters/volsync.adoc
> +volsync-rsync-dst-src-database-destination
Let's change this example name to `volsync-rsync-dst-src-destination-name`

2022-02-04 15:38 UTC, tesshuflower commented on clusters/volsync.adoc
> +  name: <database-source>
can we change this to "name: <source_name>" to match what we have for the replicationdestination.yaml?

2022-02-04 15:38 UTC, tesshuflower commented on clusters/volsync.adoc
> +Replace `database_source` with a unique name for your replication.
change to `source_name`

2022-02-04 16:03 UTC, tesshuflower commented on clusters/volsync.adoc
> +.. On the source cluster, modify the `volsync_v1alpha1_replicationsource_remotecluster.yaml` file by replacing the value of the `address` and `sshKeys` in the `ReplicationSource` object with the valu
should be "..modify the `replication_source.yaml` file ..."

2022-02-04 16:09 UTC, tesshuflower commented on clusters/volsync.adoc
> +$ sed -i "s/my.host.com/$ADDRESS/g" replication_source.yaml
Our example yaml has <source.host.com> as the example address - so this instruction would need to change (same with sshkeys below).

Perhaps in the example.yaml we should use the following:

<my.host.com>
<mysshkeys>

And then the sed commands would be:
```
$ sed -i "s/my.host.com/$ADDRESS/g" replication_source.yaml
$ sed -i "s/mysshkeys/$SSHKEYS/g" replication_source.yaml
```

Note also above the instructions say to replace those fields already - we probably need to say at that point that there are additional instructions here to do that.

2022-02-04 16:11 UTC, tesshuflower commented on clusters/volsync.adoc
>  Replace `volsync-rsync-destination-src-database-destination` with the keys that you copied from the `.status.rsync.sshKeys` field of the `ReplicationDestination` when you configured it.
Should mention there are detailed steps for this below (the sed commands)

2022-02-04 16:11 UTC, tesshuflower commented on clusters/volsync.adoc
>  Replace `source.host.com` with the host address that you copied from the `.status.rsync.address` field of the `ReplicationDestination` when you configured it.
Should mention there are detailed steps for this below (the sed commands)

2022-02-14 14:08 UTC, tesshuflower commented on clusters/volsync.adoc
> +$ ADDRESS=`kubectl get replicationdestination database-destination -n dest --template={{.status.rsync.address}}`
in this command `database-destination` should be the name they used in their replication destination

2022-02-14 14:09 UTC, tesshuflower commented on clusters/volsync.adoc
> +Replace `destination_name` with the name of your destination volume.
This actually isn't the name of the destination volume, it's the name they want to name their replication destination CR.  Maybe we should just hardcode a name here and use it throughout the rest of this doc?  Something like `test-replication-destination`

2022-02-14 14:12 UTC, tesshuflower commented on clusters/volsync.adoc
> +  name: <source_name>
Maybe we should harcode a name here to make the example easier like I suggested with the replicationdestination.  something like `test-replication-source`

2022-02-14 21:51 UTC, cadawson commented on clusters/volsync.adoc
> +  name: <source_name>
As above: I'm not sure I understand the advantage of using a name here, rather than a variable. If we keep it consistent and hit all of the instances, the variables should be ok, no? See if I caught them all. Thanks!

2022-02-21 13:56 UTC, cadawson commented
@tesshuflower : Can we run through these instructions to determine if they work? If you think it is better, we can merge this and open a new issue with anything else that causes a problem. Thanks!

2022-02-22 15:30 UTC, tesshuflower commented
> @tesshuflower : Can we run through these instructions to determine if they work? If you think it is better, we can merge this and open a new issue with anything else that causes a problem. Thanks!

@cadawson the doc still references files in examples - I think we need to address that before we can merge it.  Could you look at the comments above related to examples?  The text would need to tell the user more generically to deploy their app that creates the PVC etc rather than telling them to deploy an example yaml we aren't providing in the doc.

2022-03-03 16:11 UTC, tesshuflower requested changes
Added some comments

2022-03-03 16:11 UTC, tesshuflower commented on clusters/volsync.adoc
> +  name: <source_name>
The problem is we have things like "Replace source_name with the name for your replication source CR. See step 3f for instructions on how to replace this automatically." - but there are no steps to replace the source_name.

Additionally other steps refer where we provide commands to extract fields from the replicationsource/destination, those commands need to use the name of the replication source -so you'd have to explain every time that the user needs to replace the name with whatever they provided earlier as `source_name` or `dest_name`.

An example is step 3g:

```
$ kubectl describe ReplicationSource -n source application-source
```

The name here needs to match the name they used for their replication source CR.  The example uses `application-source` which I don't think we've used anywhere else?

2022-03-03 16:11 UTC, tesshuflower commented on clusters/volsync.adoc
> +$ kubectl get replicationdestination database-destination -n dest --template={{.status.latestImage.name}}
`database-destination` should be the name of their replication destination, so need to say something like `<destination_name>` and tell them to replace.

Also, `dest` is the destination namespace, so same explanation needed - something like `<dest>` and instructions to replace. - edit: we call this <dest> in the replicationdestination example yaml, but then also use <dest_namespace> sometimes - should be consistent.

2022-03-03 16:11 UTC, tesshuflower commented on clusters/volsync.adoc
> +Replace `snapshot_to_replace` with the snapshot name that you found in the previous step.
Can we use `VolumeSnapshot` instead of `snapshot`?

2022-03-03 16:11 UTC, tesshuflower commented on clusters/volsync.adoc
> +. Validate that your persistent volume claim pod is running in the environment by entering the following command:
these instructions are about creating a PVC, so they need to validate that their "persistent volume clam has been created in the environment".  Please remove any mention of "pod".

2022-03-03 16:11 UTC, tesshuflower commented on clusters/volsync.adoc
> +$ kubectl get pods -n <dest-namespace>
should be `kubectl get pvc -n <dest-namespace>`

2022-03-03 16:11 UTC, tesshuflower commented on clusters/volsync.adoc
> +  namespace: <source>
It's confusing here as later on we mention `source` is the name of the source pvc and not the namespace?  Can we globally use something consistent for the source/dest namespaces?  I'd suggest using something like:
`source-namespace`, `destination-namespace`

2022-03-03 16:11 UTC, tesshuflower commented on clusters/volsync.adoc
> +Replace `source` with the name of the persistent volume claim where your source is located. See step 3f for instructions on how to replace this automatically.
This is actually the namespace, should be about replacing `source/source-namespace` with the namespace

2022-03-03 16:11 UTC, tesshuflower commented on clusters/volsync.adoc
> +Replace `persistent_volume_claim` with the name of your source claim.
I think the edit meant for here ended up on line 169 - can we call this "your source persistent volume claim" instead of "source claim"?

2022-03-03 16:11 UTC, tesshuflower commented on clusters/volsync.adoc
> +$ kubectl describe ReplicationSource -n source <pvc-source>
Another example here of the namespace (the -n parameter) being hardcoded - since we've given them instructions on how to change, we need to let them know to replace on every single command.  So source should be something like `<source>` (or `<source-namespace>` if we rename to that)

2022-03-03 16:11 UTC, tesshuflower commented on clusters/volsync.adoc
> +$ kubectl get secret -n dest $SSHKEYS -o yaml > /tmp/secret.yaml
Another example where dest namespace is just hardcoded in the cmd line example

2022-03-04 20:34 UTC, tesshuflower commented on clusters/volsync.adoc
> +You can update `resources.requests.storage` with a different value, but it is best proctice when the value is at least the same size as the initial source persistent volume claim.
typo: `proctice`

2022-03-04 20:48 UTC, tesshuflower commented on clusters/volsync.adoc
> +* Change the namespace to the namespace of your source cluster. For this example, it is `source`.
source probably should be source-ns to match the rest

2022-03-04 20:49 UTC, tesshuflower requested changes
looking really good! I only found a couple really small items

2022-03-07 20:03 UTC, cadawson commented on clusters/volsync.adoc
> +* Change the namespace to the namespace of your source cluster. For this example, it is `source`.
Missed that one.

2022-03-08 14:19 UTC, tesshuflower approved these changes
/lgtm

2022-03-08 17:22 UTC, cadawson commented
Thanks @tesshuflower !

2022-03-08 18:22 UTC, tesshuflower commented on clusters/volsync.adoc
> +*Note:* In this example, the source and the destination persistent volume claims are on the same server. If your persistent volume claims are not on the same server, then copy your secret file to the
@cadawson Sorry, I missed this before - I think this note is most likely not needed and may be confusing to the reader.

The example is talking about separate clusters, and we do give instructions on how to copy the secret from one cluster to the other - can we just remove this note (line 221)

2022-03-08 18:24 UTC, tesshuflower reviewed
sorry I missed it before, please see my comment about line 221

2022-03-08 18:48 UTC, cadawson commented
Removed the note from the source. Merging.

2022-03-08 18:48 UTC, merged