Remove console from Observability
open-cluster-management/rhacm-docs pull request #3070
Opened 2022-01-20 19:28 UTC by dockerymick

https://github.com/stolostron/backlog/issues/18625

2022-01-21 18:11 UTC, berenss commented on observability/customize_observability.adoc
> +After you enable observability, alerts from your {ocp-short} managed clusters are automatically sent to the hub cluster. You can use the `alertmanager-config` YAML file to configure alerts with an ex
@marcolan018 is this correct? do we configure each managed cluster to configure alert forward? the way I'm reading this seems like we have to enable alert forwarding 1 at a time... that doesn't seem right to me

2022-01-21 18:25 UTC, berenss requested changes
thx Mikela this is a great improvement!

2022-01-21 18:25 UTC, berenss commented on observability/customize_observability.adoc
> +From your hub cluster, select the managed cluster that you want to forward alerts. Select the {ocp-short} link to access and update the `alertmanager-config` secret. *Note*: If you make changes to th
@marcolan018 is this correct? do we configure each managed cluster to configure alert forward? the way I'm reading this seems like we have to enable alert forwarding 1 at a time... that doesn't seem right to me

2022-01-21 18:25 UTC, berenss commented on observability/customize_observability.adoc
> +View the data from your managed clusters by accessing Grafana from the hub cluster. You can query specific metrics and add filters for the query.
In the previous section we're talking about configuring alert forwarding, but the verbiage here talks about checking a specific metric. do we mean **alerts** here?

2022-01-21 18:25 UTC, berenss commented on observability/customize_observability.adoc
> +Select the Grafana link from your hub cluster to view the _etcd_ table data, which is collected from your hub cluster. The _Leader election changes_ across managed clusters are displayed.
It would be useful to answer 'why?' Why it is important to look at the etcd table? It's because we want to know the stability of the etcd as a datastore and whether or not it is performing well. This could be a sign of trouble..something like that. @bjoydeep any comment here?

2022-01-21 18:25 UTC, berenss commented on observability/customize_observability.adoc
> +View the total number of clusters that are exceeding or meeting the targeted _service-level objective_ (SLO) value for the past seven or 30-day period, offending and non-offending clusters, and API S
this is great. this shows the 'why'

2022-01-21 18:25 UTC, berenss commented on observability/customize_observability.adoc
> +View the error budget for the past seven or 30-day period, the remaining downtime, and trend.
this is good!

2022-01-21 18:25 UTC, berenss commented on observability/observability_enable.adoc
> +
lets make it clear that this is an optional/possible way to do it. this is just here for the convenience of the user, if they prefer it.

2022-01-21 18:46 UTC, dockerymick commented on observability/customize_observability.adoc
> +Select the Grafana link from your hub cluster to view the _etcd_ table data, which is collected from your hub cluster. The _Leader election changes_ across managed clusters are displayed.
Updated the statement

2022-01-21 18:49 UTC, marcolan018 commented on observability/customize_observability.adoc
> +From your hub cluster, select the managed cluster that you want to forward alerts. Select the {ocp-short} link to access and update the `alertmanager-config` secret. *Note*: If you make changes to th
@berenss 
you are right, this is not correct.
"alertmanager-config" is the one to config alertmanager in hub side. 
alert-forwarding from managed clusters to hub side is configured automatically when observability is enabled on the managed cluster. No manual action is required.

2022-01-21 20:10 UTC, dockerymick commented on observability/customize_observability.adoc
> +From your hub cluster, select the managed cluster that you want to forward alerts. Select the {ocp-short} link to access and update the `alertmanager-config` secret. *Note*: If you make changes to th
Thanks for the comments! I recently removed the entire statement: "From your hub cluster, select the managed cluster that you want to forward alerts. Select the {ocp-short} link to access and update the `alertmanager-config` secret. *Note*: If you make changes to the `alertmanager-config` secret, the evaluation interval is about one minute."

2022-01-25 20:28 UTC, dockerymick commented
@berenss @marcolan018 Thanks for both of yall's time and comments. When you both have an opportunity, may you re-review the PR?

2022-01-27 22:23 UTC, marcolan018 commented on observability/customize_observability.adoc
> +To verify that the alert rules are functioning appropriately, launch the Grafana dashboard, navigate to the *Explore* page, and query `ALERTS`.
The alert will only be available in Grafana dashboard only if the alert rule is triggered. I think we need explain this in the doc.

2022-01-27 22:25 UTC, marcolan018 commented on observability/customize_observability.adoc
> +Create a file named `observability-metrics-custom-allowlist.yaml` and add the name and recording rule of the custom metric to the `metrics_list.yaml` parameter. Your YAML for the ConfigMap might rese
I think it's not necessary to mention recording rule here. Just use the statement as below
```
add the name of the custom metric to the `metrics_list.yaml` parameter
```

2022-01-27 22:32 UTC, marcolan018 commented on observability/customize_observability.adoc
> +Verify that data from your custom metric is being collected by viewing the Grafana dashboard. For more information about viewing the dashboard, see xref:../observability/design_grafana.adoc#designing
I think this paragraph mentioned two things indeed.
1. To verify the custom metrics, just need to go to Explore in Grafana console to query the metrics directly.
2. You can also use the custom metrics in your own dashboards. For more information about design the custom dashboard, see xref:../observability/design_grafana.adoc#designing-your-grafana-dashboard[Designing your Grafana dashboard].

2022-01-27 22:34 UTC, marcolan018 commented on observability/customize_observability.adoc
> +If you want data to not be collected for a specific metric, remove the metric from the `observability-metrics-custom-allowlist.yaml` file. When you remove a metric, the stored data for the metric is
When you remove a metric, the stored data for the metric is deleted.

this is not true, when remove a metrics, the historic data for this metrics will not be deleted. The behavior is the metrics will not be collected in managed clusters.

2022-01-27 22:35 UTC, marcolan018 commented on observability/customize_observability.adoc
> +Edit the `MultiClusterObservability` CRD and add the `advanced` section with the following command: `oc edit mco observability -o yaml`. Your YAML file might resemble the following contents:
Edit the `MultiClusterObservability` CR, not CRD

2022-01-27 22:37 UTC, marcolan018 commented on observability/customize_observability.adoc
> +If your workload increases, increase the number of replicas of your observability pods. Navigate to the {ocp} console from your hub cluster. Locate the `multiclusterobservability` custom resource def
Locate the `multiclusterobservability` custom resource definition

should be 

Locate the `multiclusterobservability` custom resource

2022-01-27 22:39 UTC, marcolan018 commented on observability/customize_observability.adoc
> +If your workload increases, increase the number of replicas of your observability pods. Navigate to the {ocp} console from your hub cluster. Locate the `multiclusterobservability` custom resource def
update the `replicas` parameter value

better change to:

update the `replicas` parameter value under component which you wonder increase the replica number

2022-01-27 22:43 UTC, marcolan018 commented on observability/customize_observability.adoc
> +When you disable the `metrics-collector`, the deployment is scaled to zero and all managed clusters are disabled. Update the `multicluster-observability-operator` resource by setting `enableMetrics`
the deployment is scaled to zero

better change to

replica of the deployment is scaled to zero

2022-01-27 22:45 UTC, marcolan018 commented on observability/customize_observability.adoc
> +Disable the `metrics-collector` on specific managed clusters by adding the `observability: disabled` label to the `managedclusters.cluster.open-cluster-management.io` custom resource.
for this action, it's not "Disable the `metrics-collector` on specific managed clusters", the better description is "Remove observability components on specific managed clusters"

2022-01-28 14:03 UTC, dockerymick commented on observability/customize_observability.adoc
> +To verify that the alert rules are functioning appropriately, launch the Grafana dashboard, navigate to the *Explore* page, and query `ALERTS`.
I agree that it should be mentioned. Thanks!

2022-01-28 15:08 UTC, dockerymick commented
@marcolan018 Thanks for your feedback Marco! I recently made some updates. When you have an opportunity, may you re-review the PR ?

2022-02-03 15:58 UTC, merged