Bypass template processing 2.3
open-cluster-management/rhacm-docs pull request #3133
Opened 2022-02-10 03:25 UTC by dockerymick

https://github.com/stolostron/backlog/issues/18218

2022-02-10 03:34 UTC, gparvin reviewed
We didn't have hub templates support in ACM 2.3.  We did have the managed cluster templates support.  I'll have to let @ckandag comment on whether the annotation to disable the template processing was backported to 2.3.

2022-02-17 17:33 UTC, ckandag commented
yes, it was backported to 2.3

> We didn't have hub templates support in ACM 2.3. We did have the managed cluster templates support. I'll have to let @ckandag comment on whether the annotation to disable the template processing was backported to 2.3.

yes, it was backported to 2.3, while the hub templates are not in 2.4,  managedcluster templates can still be disabled by setting the annotation on the configuration policy definition

2022-02-17 17:43 UTC, ckandag commented on governance/custom_template.adoc
> +[#managed-templates]
this entire section needs to be removed for 2.3. as we do not support hub templates in 2.3, only the "bypassing" section should be included for 2.3

2022-02-17 17:44 UTC, ckandag commented on governance/custom_template.adoc
> +=== Bypass template processing
this section is the only thing that needs to be added to 2.3

2022-02-17 17:46 UTC, ckandag commented on governance/custom_template.adoc
> +To bypass template processing for your hub cluster, you must change `{{ template content }}` to `{{ '{{ template content }}' }}`.
to bypass policy template processing, you must change ....

no need to say "for your hub cluster". - it actually isnt just for hub cluster isnt for every /any cluster

2022-02-17 17:46 UTC, ckandag requested changes
pls see inline comments

2022-02-23 19:32 UTC, ckandag approved these changes

2022-02-23 20:54 UTC, dockerymick commented
Thanks for the approval @ckandag !

2022-02-23 20:54 UTC, merged