Update observability info
open-cluster-management/rhacm-docs pull request #3169
Opened 2022-03-01 23:11 UTC by dockerymick

https://github.com/stolostron/backlog/issues/19936

2022-03-03 18:29 UTC, ckandag commented on access_control/rbac.adoc
> +To use the observability features, you must be assigned the `view` role. View the following list of observability features:
I think this should be

To view  the observability metrics for a managed cluster, you must have  `view` access to that managed cluster on the Hub.

2022-03-03 18:31 UTC, ckandag commented on access_control/rbac.adoc
> +Users are denied access to managed cluster metrics, if they are not assigned to the `view` role in the same namespace of the managed cluster.
rewrite as below


Users are denied access to managed cluster metrics, if they are not assigned to the `view` role to the managed cluster's namespace on the Hub.

2022-03-03 19:03 UTC, ckandag requested changes
comments inline

2022-03-07 16:39 UTC, dockerymick commented
@ckandag thanks for your review and comments.

2022-03-07 16:56 UTC, ckandag commented on access_control/rbac.adoc
> +To view the observability metrics for a managed cluster, you must have `view` access to that managed cluster on the hubb cluster. View the following list of observability features:
hubb ->. hub

2022-03-07 17:10 UTC, dockerymick commented
@ckandag Thanks again for the review! Merging this

2022-03-07 17:10 UTC, merged