stolostron/backlog#19300 upd network
open-cluster-management/rhacm-docs pull request #3251
Opened 2022-03-17 16:20 UTC by cadawson

2022-07-12 14:57 UTC, thuyn-581 commented
lgtm

2022-07-12 15:02 UTC, thuyn-581 reviewed
lgtm

2022-07-12 15:03 UTC, thuyn-581 approved these changes
lgtm

2022-07-14 14:11 UTC, swopebe requested changes
peer review

2022-07-15 14:50 UTC, dockerymick approved these changes
left a comment, otherwise this looks good to me! Format is aligned well and links work well! 
<img width="1272" alt="Screen Shot 2022-07-15 at 10 50 13 AM" src="https://user-images.githubusercontent.com/60616885/179248339-36e3d974-3ed3-4aa3-8079-362c64e829aa.png">

2022-07-15 14:50 UTC, dockerymick commented on credentials/credential_bare.adoc
> +* A {product-title} hub cluster that is deployed. When managing bare metal clusters, you must have the hub cluster installed on {ocp} version 4.6 or later.
It seems like the statements are two separate prereqs. 

* A {product-title} hub cluster that is deployed.
* You must have the hub cluster installed on {ocp} version 4.6 or later when you manage bare metal clusters. 

Let me know your thoughts or if i am misunderstanding

2022-07-15 16:19 UTC, cadawson commented on credentials/credential_bare.adoc
> +* A {product-title} hub cluster that is deployed. When managing bare metal clusters, you must have the hub cluster installed on {ocp} version 4.6 or later.
I like your change. Thanks!

2022-07-15 16:20 UTC, merged