stolostron/backlog#20720 add subctl
open-cluster-management/rhacm-docs pull request #3276
Opened 2022-03-23 21:24 UTC by cadawson

2022-03-31 17:39 UTC, dfarrell07 requested changes
Thanks @cadawson, comments inline!

2022-03-31 17:39 UTC, dfarrell07 commented on services/submariner/submariner.adoc
> +| https://submariner.io/operations/deployment/subctl/#unexport[`unexport`] | When `service` is added, removes the `ServiceExport` resource for the specified service, which prevents other clusters in
I think it would make sense to treat these as `export service` and `unexport service`, as we only expect those args to be used together.

2022-03-31 17:39 UTC, dfarrell07 commented on services/submariner/submariner.adoc
> +| https://submariner.io/operations/deployment/subctl/#show[`show`] | Displays the list of different resources in a Submariner deployment.
```suggestion
| https://submariner.io/operations/deployment/subctl/#show[`show`] | Provides information about Submariner resources.
```

2022-03-31 17:39 UTC, dfarrell07 commented on services/submariner/submariner.adoc
> +| https://submariner.io/operations/deployment/subctl/#verify[`verify`] | Tests and confirms that the Submariner deployment is working across the clusters.
```suggestion
| https://submariner.io/operations/deployment/subctl/#verify[`verify`] | Verifies connectivity, service discovery, and other Submariner features across a pair of Submariner clusters.
```

2022-03-31 17:39 UTC, dfarrell07 commented on services/submariner/submariner.adoc
> +| https://submariner.io/operations/deployment/subctl/#benchmark[`benchmark`] | Runs benchmarking tests on throughput or latency in the clusters of a Submariner deployment.
```suggestion
| https://submariner.io/operations/deployment/subctl/#benchmark[`benchmark`] | Benchmarks throughput and latency across a pair of Submariner clusters or within a single cluster. 
```

2022-03-31 17:39 UTC, dfarrell07 commented on services/submariner/submariner.adoc
> +| https://submariner.io/operations/deployment/subctl/#cloud[`cloud`] | Prepares the {ocp} installer-provisioned infrastructure (IPI) on the specified cloud providers.
```suggestion
```

I think this should not be covered, as clusters that support cloud-prepare should be prepared through the console, not manually.

2022-03-31 17:40 UTC, dfarrell07 commented
/cc @sridhargaddam @skitt @tpantelis

2022-03-31 20:17 UTC, cadawson commented
Updated with your comments @dfarrell07 . Next time, I think I can just commit them directly.

2022-04-01 11:29 UTC, skitt approved these changes

2022-04-01 11:29 UTC, skitt commented on services/submariner/submariner.adoc
> +Submariner contains the `subctl` utility that provides additional commands that simplify running tasks on your Submariner environment. After adding the utility to your path, the following table brief
Do we need to explain how to install it? (We won’t be able to provide “nice” ways for OpenShift users to install `subctl` for 2.5, but perhaps we can discuss providing an RPM again later, after Submariner 0.13.)

2022-04-07 15:38 UTC, cadawson commented on services/submariner/submariner.adoc
> +Submariner contains the `subctl` utility that provides additional commands that simplify running tasks on your Submariner environment. After adding the utility to your path, the following table brief
@skitt Yes, that would be good. I was hoping it was installed with ACM, and will be available after ACM is installed.

2022-04-07 15:42 UTC, skitt commented on services/submariner/submariner.adoc
> +Submariner contains the `subctl` utility that provides additional commands that simplify running tasks on your Submariner environment. After adding the utility to your path, the following table brief
We make it available in a container image, I’ll check whether than can be used straightforwardly.

2022-04-07 19:32 UTC, cadawson commented on services/submariner/submariner.adoc
> +Submariner contains the `subctl` utility that provides additional commands that simplify running tasks on your Submariner environment. After adding the utility to your path, the following table brief
Sounds great. Thanks. Fingers crossed.

2022-04-07 21:29 UTC, dfarrell07 commented on services/submariner/submariner.adoc
> +Submariner contains the `subctl` utility that provides additional commands that simplify running tasks on your Submariner environment. After adding the utility to your path, the following table brief
Something like (from Steve) this is what I've seen to extract `subctl` from the container it's packaged in downstream.

```
# Download and extract subctl
oc image extract registry-proxy.engineering.redhat.com/rh-osbs/rhacm2-tech-preview-subctl-rhel8:${VERSION} --path=/dist/subctl-${VERSION}-linux-amd64.tar.xz:/tmp/ --confirm

tar -C /tmp/ -xf /tmp/subctl-${VERSION}-linux-amd64.tar.xz

alias subctl=/tmp/subctl-${VERSION}/subctl-${VERSION}-linux-amd64
```

2022-04-08 07:49 UTC, skitt commented on services/submariner/submariner.adoc
> +Submariner contains the `subctl` utility that provides additional commands that simplify running tasks on your Submariner environment. After adding the utility to your path, the following table brief
It can be simpler than that, the image can be used to run `subctl` directly:

   podman run --rm quay.io/submariner/subctl:devel subctl version

The main subtlety is that we need to add a volume mount to provide access to the kubeconfig.

2022-04-08 13:35 UTC, dfarrell07 commented
(I can't mark my inline comments as resolved due to permissions I guess, but they are resolved)

2022-05-06 15:56 UTC, dfarrell07 requested changes

2022-05-06 15:56 UTC, dfarrell07 commented on services/submariner/submariner.adoc
> +The `subctl` utility is provided as a container image. Complete the following steps to install the `subctl` utility:
```suggestion
The `subctl` utility is shipped in a container image. Complete the following steps to install the `subctl` utility locally: 
```

2022-05-06 15:56 UTC, dfarrell07 commented on services/submariner/submariner.adoc
> +. Download and extract the container image by entering the following command:
```suggestion
. Download the `subctl` container and extract a compressed version of the `subctl` binary to `/tmp` by entering the following command: 
```

2022-05-06 15:56 UTC, dfarrell07 commented on services/submariner/submariner.adoc
> +. Expand the file by entering the following command:
```suggestion
. Decompress `subctl` by entering the following command: 
```

2022-05-06 15:56 UTC, dfarrell07 commented on services/submariner/submariner.adoc
> +----
```suggestion
. Install `subctl` by entering the following command:
+
----
install -m744 /tmp/subctl-${VERSION}/subctl-${VERSION}-linux-amd64 /$HOME/.local/bin/subctl
----
```

2022-05-09 11:57 UTC, cadawson commented on services/submariner/submariner.adoc
> +. Download and extract the container image by entering the following command:
Committed

2022-05-09 11:59 UTC, cadawson commented on services/submariner/submariner.adoc
> +. Expand the file by entering the following command:
committed

2022-05-09 11:59 UTC, cadawson commented on services/submariner/submariner.adoc
> +----
committed

2022-05-09 12:05 UTC, cadawson commented on services/submariner/submariner.adoc
> +The `subctl` utility is provided as a container image. Complete the following steps to install the `subctl` utility:
committed

2022-05-09 18:28 UTC, dfarrell07 approved these changes
It would be good to verify this on a deployment, but the docs look good to me.

2022-05-20 15:59 UTC, merged