Adding section for protect function
open-cluster-management/rhacm-docs pull request #3282
Opened 2022-03-25 14:19 UTC by dockerymick

https://app.zenhub.com/workspaces/engineering-backlog-do-not-delete-604fab62d4b98d00150a2854/issues/stolostron/backlog/19357

2022-03-28 13:04 UTC, mprahl requested changes

2022-03-28 13:04 UTC, mprahl commented on governance/custom_template.adoc
> +The `protect` function enables you to encrypt a string in a hub cluster policy template. View the following example of the configuration policy that uses the `protect` function:
```suggestion
The `protect` function enables you to encrypt a string in a hub cluster policy template. It is automatically decrypted on the managed cluster when the policy is evaluated. View the following example of the configuration policy that uses the `protect` function:
```

2022-03-28 13:04 UTC, mprahl commented on governance/custom_template.adoc
>  | Functions
Could you please document that the `fromSecret` template function on the Hub will store the resulting value as an encrypted string on the replicated policy in the managed cluster namespace?

Essentially, it's the equivalent of calling `{{hub "(lookup "v1" "Secret" "default" "my-hub-secret").data.message | protect hub}}`.

2022-03-28 13:04 UTC, mprahl commented on governance/custom_template.adoc
> +[#protect-function]
Could you please document that the encryption algorithm used is AES-CBC using 256 bit keys? Each encryption key is unique per managed cluster and is automatically rotated every 30 days. To force an immediate rotation, delete the `policy.open-cluster-management.io/last-rotated` annotation on the `policy-encryption-key` Secret in the managed cluster namespace on the Hub.

2022-03-29 21:26 UTC, dockerymick commented
@mprahl Thanks for your feedback Matt, when you get an opportunity. May you re-review the PR?

2022-03-30 13:17 UTC, mprahl commented on governance/custom_template.adoc
> +To force an immediate rotation, delete the `policy.open-cluster-management.io/last-rotated` annotation on the `policy-encryption-key` Secret in the managed cluster namespace on the hub cluster. Polic
```suggestion
To force an immediate rotation, delete the `policy.open-cluster-management.io/last-rotated` annotation on the `policy-encryption-key` Secret in the managed cluster namespace on the hub cluster. Policies are then reprocessed to use the new encryption key. 
```

2022-03-30 13:18 UTC, mprahl commented on release_notes/whats_new.adoc
> +* You can use the `protect` function to secure sensitive data that is on your hub cluster policy template. See link:../governance/custom_template.adoc##protect-function[protect function] section for
Could you also please mention that `fromSecret` is available in Hub policy templates?

2022-03-30 13:19 UTC, mprahl commented
@dockerymick this looks great! I just left a couple of minor comments. After that is addressed, this can be merged from my perspective.

2022-03-30 13:57 UTC, dockerymick commented
Thanks Matt!

2022-03-30 14:20 UTC, dockerymick commented
@ckandag When you have an opportunity may you review as well?

2022-04-07 21:31 UTC, ckandag approved these changes

2022-04-08 19:34 UTC, dockerymick commented
Thanks for your review @ckandag ! Moving forward and merging this PR

2022-04-08 19:34 UTC, merged