Updating doc to install OADP
open-cluster-management/rhacm-docs pull request #3298
Opened 2022-03-31 17:18 UTC by dockerymick

https://app.zenhub.com/workspaces/engineering-backlog-do-not-delete-604fab62d4b98d00150a2854/issues/stolostron/backlog/20612

2022-03-31 17:48 UTC, birsanv requested changes

2022-03-31 17:48 UTC, birsanv commented on clusters/backup_and_restore.adoc
> +
@dockerymick can you add here some information on the fact the oadp operator only supports x86_64


Note:

The OADP Operator 1.0 has disabled building multi-arch builds and only produces x86_64 builds for the official release. This means that if you are using an architecture other than x86_64, the OADP Operator installed by the chart will have to be replaced with the right version. In this case, uninstall the OADP Operator and find the operator matching your architecture than install it.

2022-04-05 19:35 UTC, birsanv requested changes
I made a few comments

2022-04-05 19:35 UTC, birsanv commented on clusters/backup_and_restore.adoc
> +In an active passive configuration you have
This sentence doesn't seem to be complete dramatically `using the BackupSchedule.cluster.open-cluster-management.io resource
one or more passive hubs, which are continously retrieving the latest backups and restoring the passive data.`

2022-04-05 19:35 UTC, birsanv commented on clusters/backup_and_restore.adoc
> +
Since the image legend was taken out , I added a few comments for the diagram here https://github.com/stolostron/cluster-backup-operator#setting-up-an-active-passive-configuration

In the image below, the active hub manages the remote clusters and backs up hub data at regular intervals. The passive hubs restore this data, except for the managed clusters activation data, which would move the managed clusters to the passive hub. The passive hubs can restore the passive data [continously](https://github.com/stolostron/cluster-backup-operator#restoring-passive-resources-and-check-for-new-backups), or as a [one time operation](https://github.com/stolostron/cluster-backup-operator#restoring-passive-resources).

2022-04-05 19:46 UTC, birsanv requested changes
I put a few comments on your changes but the README has a few more content we should bring into the doc

2022-04-05 19:46 UTC, birsanv commented on clusters/backup_and_restore.adoc
> +The cluster backup and restore operator is not instaleld automatically. Enable the backup component by setting the `cluster-backup` parameter to `true`, in the `MultiClusterHub` resource. The OADP Op
typo namesapce

2022-04-05 19:46 UTC, birsanv commented on clusters/backup_restore_enable.adoc
>  == Prerequisites
Prereqs should be changed since the OADP operator is installed now by default 

I am copying here the Prereqs from the blog , I don't have a prereq in the README to use : 

---------
View the following prerequisites to follow along in this blog:

For both primary and passive hub:

- Advanced Cluster Management for Kubernetes Operator version 2.5.x is installed on your hub cluster
MultiClusterHub resource is created and has a status of Running; the MultiClusterHub resource should be automatically created when you install Advanced Cluster Management for Kubernetes Operator version 2.5.x
- The Cluster Back up and Restore Operator chart is not installed automatically. Enable the cluster-backup operator on the hub : edit the MultiClusterHub resource and set the cluster-backup to true. This installs the OADP operator in the same namespace with the backup chart.

For passive hub:

- Before running the restore operation on the passive hub, you need to manually configure the hub and install all operators as on the primary hub, using the same namespace as the primary hub operators.

- You have to install the Red Hat Advanced Cluster Management for Kubernetes operator, in the same namespace as the initial hub, then create the [DataProtectionApplication resource](https://github.com/openshift/oadp-operator/blob/master/docs/install_olm.md#create-the-dataprotectionapplication-custom-resource) and connect to the same storage location where the initial hub had backed up data.
- If the initial hub had any other operators installed, such as Ansible Automation Platform, Red Hat OpenShift GitOps, cert-manager you have to install them now, before running the restore operation. This ensure the new hub is configured in the same way as the initial hub.
- The passive hub must use the same namespace names as the old hub when installing the Red Hat Advanced Cluster Management for Kubernetes operator and any other operators configured on the previous hub.

2022-04-05 19:46 UTC, birsanv commented on clusters/backup_restore_enable.adoc
> +//should this be updated to six `schedule.velero.io` resources?
There are a lot of changes here
In README I refer to this as : Resources are backed up in 3 separate groups: https://github.com/stolostron/cluster-backup-operator#scheduling-a-cluster-backup

But I also added a lot of information about what is backed up, what is activation data, etc, all here https://github.com/stolostron/cluster-backup-operator#what-is-backed-up

2022-04-06 14:34 UTC, dockerymick commented
https://app.zenhub.com/workspaces/engineering-backlog-do-not-delete-604fab62d4b98d00150a2854/issues/stolostron/backlog/20920

2022-04-06 17:28 UTC, dockerymick commented on clusters/backup_and_restore.adoc
> +In an active passive configuration you have
Thanks, for this info I wasn't finished with the updates yet

2022-04-11 15:31 UTC, dockerymick commented on clusters/backup_restore_enable.adoc
>  == Prerequisites
@birsanv I'm confused when you say, "Red Hat Advanced Cluster Management for Kubernetes" operator". When you say that, are you referring to the backup and restore operator still? From my understanding, RHACM is the hub cluster and it can become a managed cluster. Can you clarify?

2022-04-11 16:04 UTC, birsanv commented on clusters/backup_restore_enable.adoc
>  == Prerequisites
@dockerymick I am referring to the ACM operator, NOT to the backup chart ( or as we also call it backup operator )

2022-04-11 16:09 UTC, dockerymick commented on clusters/backup_restore_enable.adoc
>  == Prerequisites
Can you help me understand why operator is being added after the product name? Is RHACM an operator option from the OCP console?

2022-04-11 16:46 UTC, birsanv commented on clusters/backup_restore_enable.adoc
>  == Prerequisites
I am referring to this ; it is an operator and the name is Red Hat Advanced Cluster Management for Kubernetes
<img width="1075" alt="Screen Shot 2022-04-11 at 12 45 24 PM" src="https://user-images.githubusercontent.com/43010150/162789902-526d46f2-dc32-4241-8e64-2023777a289e.png">

2022-04-12 17:22 UTC, dockerymick commented on clusters/backup_restore_enable.adoc
>  == Prerequisites
@birsanv Thanks for providing the screen capture

2022-04-12 18:58 UTC, birsanv commented
@sahare can you please help review

2022-04-12 19:48 UTC, birsanv requested changes

2022-04-12 19:48 UTC, birsanv commented on clusters/backup_and_restore.adoc
> +The cluster backup and restore operator provides disaster recovery solutions for when {product-title} hub cluster goes down and needs to be recreated. It runs on the hub cluster, and depends on the l
Change this
The OADP Operator is installed by default.

with
The OADP Operator is installed by default when the cluster backup and restore operator is installed and is installed in the same namespace with the cluster backup and restore operator.

2022-04-12 19:48 UTC, birsanv commented on clusters/backup_and_restore.adoc
> +The cluster backup and restore operator provides disaster recovery solutions for when {product-title} hub cluster goes down and needs to be recreated. It runs on the hub cluster, and depends on the l
Replace 
It runs on the hub cluster, and depends on the link:https://github.com/openshift/oadp-operator[OADP Operator] to create a connection to a backup storage location on the hub cluster.

with 
It runs on the hub cluster, and depends on the link:https://github.com/openshift/oadp-operator[OADP Operator] to install [Velero], which is the component that executes the backup and restore operations, and then creates a connection from the hub cluster to a backup storage location where the backup data is stored.

2022-04-12 19:48 UTC, birsanv commented on clusters/backup_and_restore.adoc
> +It supports backups of any third-party resources that extend to the hub cluster installation. With this backup solution, you can define cron-based backup schedules which runs at specified time interv
Is this correct ? ..
It supports backups of any third-party resources that extend to the hub cluster installation.

Maybe 
It supports backups of any third-party resources that extend the hub cluster installation.

And then from this: 
With this backup solution, you can define cron-based backup schedules which runs at specified time intervals or continuously. When the hub cluster goes down, a new hub cluster can be deployed and the backed up data is moved to the new hub cluster.

To:
With this backup solution, you can define cron-based backup schedules which **run** at specified time intervals >>**or continuously**<< **do we need this?** .

2022-04-12 20:03 UTC, sahare commented on clusters/backup_and_restore.adoc
>  [#prerequisites-backup-restore]
It seems that `You must install the latest version of the OADP Operator.` is still part of the Prerequisites, it needs to be updated.

2022-04-12 20:12 UTC, sahare commented on clusters/backup_restore_enable.adoc
> +** The cluster backup and restore operator must be installed manually. Enable the cluster backup and restore operator (`cluster-backup`). Edit the `MultiClusterHub` resource by setting the `cluster-b
In `[#enabling-backup-restore]` section , both in the text and the sample, the parameter to enable the cluster backup operator is called `enableClusterBackup` , it's changed to `cluster-backup` , so all occurances of `enableClusterBackup`  needs to be updated to `cluster-backup`

2022-04-13 18:18 UTC, sahare commented on clusters/backup_and_restore.adoc
> +Use the link:https://github.com/stolostron/cluster-backup-operator/blob/main/config/samples/cluster_v1beta1_restore_passive_sync.yaml[`restore-passive-sync`] sample to restore passive data, while con
typo in `resroe them automatically`

2022-04-13 18:18 UTC, sahare commented on clusters/backup_and_restore.adoc
> +Use the link:https://github.com/stolostron/cluster-backup-operator/blob/main/config/samples/cluster_v1beta1_restore_passive_sync.yaml[`restore-passive-sync`] sample to restore passive data, while con
typo in `resroe them automatically`

2022-04-13 18:19 UTC, sahare commented on clusters/backup_and_restore.adoc
> +When the activted managed cluster is becomes the primary hub cluster, the restore resource is set to `Finished` and the `syncRestoreWithNewBackups` is ignored, even if set to `true`.
`cluster is becomes the primary` is this correct?

2022-04-13 18:19 UTC, sahare commented on clusters/backup_and_restore.adoc
> +When the activted managed cluster is becomes the primary hub cluster, the restore resource is set to `Finished` and the `syncRestoreWithNewBackups` is ignored, even if set to `true`.
`cluster is becomes the primary` is this correct?

2022-04-13 18:25 UTC, sahare commented on clusters/backup_and_restore.adoc
> +When the `cluster.open-cluster-management.io/backup: cluster-activations` label is added to a resource the resource is automatically backed up in the `acm-resources-generic-schedule` backup resource.
`cluster-actvation` is not the right label

2022-04-13 18:28 UTC, sahare commented on clusters/backup_and_restore.adoc
> +The cluster backup and restore operator is not instaleld automatically. Enable the backup component by setting the `cluster-backup` parameter to `true`, in the `MultiClusterHub` resource. The OADP Op
typo in instaleld

2022-04-13 18:31 UTC, sahare commented on clusters/backup_and_restore.adoc
> +In the following diagram, the actuve hub cluster manages the local clusters and backs up the hub cluster data at regular intervals:
typo in the actuve hub cluster

2022-04-13 18:32 UTC, sahare commented on clusters/backup_and_restore.adoc
> +
typo in fo rmore details

2022-04-14 12:36 UTC, dockerymick commented
@sahare @birsanv Thanks to you both for your feedback! Thanks for your patience too!

2022-04-20 12:34 UTC, dockerymick commented on clusters/backup_and_restore.adoc
> +It supports backups of any third-party resources that extend to the hub cluster installation. With this backup solution, you can define cron-based backup schedules which runs at specified time interv
I don't think using continuously is required. it was in the README. I am fine with removing it

2022-04-20 12:36 UTC, dockerymick commented on clusters/backup_and_restore.adoc
>  [#prerequisites-backup-restore]
Should this bullet point be removed?

2022-04-20 12:42 UTC, dockerymick commented on clusters/backup_and_restore.adoc
> +When the activted managed cluster is becomes the primary hub cluster, the restore resource is set to `Finished` and the `syncRestoreWithNewBackups` is ignored, even if set to `true`.
updated the statement

2022-04-20 12:42 UTC, dockerymick commented on clusters/backup_and_restore.adoc
> +When the `cluster.open-cluster-management.io/backup: cluster-activations` label is added to a resource the resource is automatically backed up in the `acm-resources-generic-schedule` backup resource.
May you confirm what the correct label is

2022-04-20 13:47 UTC, sahare commented on clusters/backup_and_restore.adoc
>  [#prerequisites-backup-restore]
Yes, OADP Operator installation is not a manual step anymore, it will be installed automatically when cluster backup chart is installed by MCH.

2022-04-20 13:47 UTC, sahare commented on clusters/backup_and_restore.adoc
> +When the `cluster.open-cluster-management.io/backup: cluster-activations` label is added to a resource the resource is automatically backed up in the `acm-resources-generic-schedule` backup resource.
`cluster-activations` on line 173 is correct.

2022-04-20 17:15 UTC, sahare commented on clusters/backup_and_restore.adoc
> +When the `cluster.open-cluster-management.io/backup: cluster-activations` label is added to a resource the resource is automatically backed up in the `acm-resources-generic-schedule` backup resource.
@dockerymick seems `cluster-activations` on line 171 needs to be updated to `cluster-activation` as well, thanks!

2022-04-21 18:28 UTC, birsanv requested changes

2022-04-21 18:28 UTC, birsanv commented on clusters/backup_restore_enable.adoc
> +The cluster backup and restore operator can be enabled when the `MultiClusterHub` resource is created for the first time. From the {ocp-short} console, select the *Enable Cluster Backup switch* to en
The *Enable Cluster Backup switch* is not longer used in 2.5 ; see https://github.com/stolostron/backlog/issues/21839

2022-04-21 18:28 UTC, birsanv commented on clusters/backup_restore_enable.adoc
> +    cluster-backup: true <-----
This is not how the new spec looks like; this is the new version

```
spec:
  availabilityConfig: High
  enableClusterBackup: false << this is deprecated as of 2.5, no longer used
  imagePullSecret: multiclusterhub-operator-pull-secret
  ingress:
    sslCiphers:
      - ECDHE-ECDSA-AES256-GCM-SHA384
      - ECDHE-RSA-AES256-GCM-SHA384
      - ECDHE-ECDSA-AES128-GCM-SHA256
      - ECDHE-RSA-AES128-GCM-SHA256
  overrides:
    components:
      - enabled: true
        name: multiclusterhub-repo
      - enabled: true
        name: search
      - enabled: true
        name: management-ingress
      - enabled: true
        name: console
      - enabled: true
        name: insights
      - enabled: true
        name: grc
      - enabled: true
        name: cluster-lifecycle
      - enabled: true
        name: volsync
      - enabled: true
        name: multicluster-engine
      - enabled: false
        name: cluster-proxy-addon
      - enabled: true <<<<<<<<<
        name: cluster-backup 
  separateCertificateManagement: false
```

2022-05-02 16:47 UTC, dockerymick commented on clusters/backup_restore_enable.adoc
> +    cluster-backup: true <-----
Updated

2022-05-02 16:47 UTC, merged