stolostron/backlog#20771 dynamic plugin
open-cluster-management/rhacm-docs pull request #3302
Opened 2022-04-01 00:05 UTC by swopebe

--new doc for dynamic plugin

2022-04-14 18:18 UTC, KevinFCormier requested changes
Thanks @swopebe. Just a few corrections to make. Please see my comments.

2022-04-14 18:18 UTC, KevinFCormier commented on console/console.adoc
> +== {ocp-short} hybrid plug-ins
I'm not sure if the word "hybrid" will mean anything to the user here. I would probably say "console" instead.

2022-04-14 18:18 UTC, KevinFCormier commented on console/console.adoc
> +. From the list of _Configuration resources_, click the **Console** resource, which contains cluster-wide configuration for the web console.
There are 2 **Console** resources in the list.
<img width="927" alt="image" src="https://user-images.githubusercontent.com/42188127/163451494-8a553e13-de80-4852-a4e7-114f06391865.png">

We must specify that it is the second one here, with the API group `operator.openshift.io`

2022-04-14 18:18 UTC, KevinFCormier commented on console/console.adoc
> +. Click on the _Console plug-ins_ tab. Both the `acm` and `mce` plug-ins are listed.
I know the preferred form uses the hyphen for "plug-ins" but this is not what is used in the OCP UI:
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/42188127/163451742-7a91c6c9-8e23-4ce1-bbcb-508c16470943.png">

2022-04-14 18:18 UTC, KevinFCormier commented on console/console.adoc
> +. Click on the _Console plug-ins_ tab. Both the `acm` and `mce` plug-ins are listed.
I have been meaning to open an issue for the mismatch between their UI and their documentation. I will do that and see which they intend to change.

2022-04-14 18:18 UTC, KevinFCormier commented on console/console.adoc
> +For {ocp-short} 4.10 with the plug-ins enabled, you can access {product-title-short} within the {ocp-short} console from the cluster switcher by selecting *All clusters* from the drop-down menu. With
In the UI, they use a capital C for "All Clusters"
<img width="1222" alt="image" src="https://user-images.githubusercontent.com/42188127/163452025-7e1d834c-9976-450b-ad9b-1c5eec643927.png">

2022-04-14 18:18 UTC, KevinFCormier commented on release_notes/whats_new.adoc
> +* For {ocp-short} 4.10, with the https://docs.openshift.com/container-platform/4.10/release_notes/ocp-4-10-release-notes.html#ocp-4-10-dynamic-plugin-technology-preview[{ocp} 4.10 release] and a more
I'm not sure that it makes sense to link to this documentation here. ACM delivers a console plugin that customers can use. That documentation tells customers how to create their own plugins. Secondly, plugins are Tech Preview in general, but they are fully supported for Red Hat products like us. This link includes the term "technology preview" so it might make it seem like our plugins are a tech preview.

@showeimer do you agree?

2022-04-14 18:25 UTC, KevinFCormier commented on console/console.adoc
> +. Click on the _Console plug-ins_ tab. Both the `acm` and `mce` plug-ins are listed.
Opened BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2075634

2022-04-20 21:51 UTC, swopebe commented on console/console.adoc
> +== {ocp-short} hybrid plug-ins
Makes sense -- thanks, sorry for the delay, I was on PTO.

2022-04-20 21:54 UTC, swopebe commented on console/console.adoc
> +. Click on the _Console plug-ins_ tab. Both the `acm` and `mce` plug-ins are listed.
Thanks @KevinFCormier sometimes, especially with UI, the words don't match the style manual. Style manual rules what we do so they need to change that and I will mention to OCP writers (we often discuss style on our channel). I will leave as-is. In this case, they would need to change it, but we are correct.

2022-04-20 22:00 UTC, swopebe commented on console/console.adoc
> +For {ocp-short} 4.10 with the plug-ins enabled, you can access {product-title-short} within the {ocp-short} console from the cluster switcher by selecting *All clusters* from the drop-down menu. With
Again, style says use sentence format but OCP does headline format at times. I will also ask about this when I get a chance... not a big deal to change this one.

2022-04-20 22:01 UTC, swopebe commented on release_notes/whats_new.adoc
> +* For {ocp-short} 4.10, with the https://docs.openshift.com/container-platform/4.10/release_notes/ocp-4-10-release-notes.html#ocp-4-10-dynamic-plugin-technology-preview[{ocp} 4.10 release] and a more
I can be clearer that it is tech preview and to go here. We don't usually make a What's new entry without linking to a doc, but if you feel strongly about it...

2022-04-20 22:17 UTC, swopebe commented on console/console.adoc
> +. From the list of _Configuration resources_, click the **Console** resource, which contains cluster-wide configuration for the web console.
Changed to:

From the list of _Configuration resources_, click the **Console** resource with the `operator.openshift.io` API group, which contains cluster-wide configuration for the web console.

2022-04-20 22:19 UTC, swopebe commented on console/console.adoc
> +For {ocp-short} 4.10 with the plug-ins enabled, you can access {product-title-short} within the {ocp-short} console from the cluster switcher by selecting *All clusters* from the drop-down menu. With
*All Clusters* from the drop-down menu

2022-04-21 13:42 UTC, swopebe commented on release_notes/whats_new.adoc
> +* For {ocp-short} 4.10, with the https://docs.openshift.com/container-platform/4.10/release_notes/ocp-4-10-release-notes.html#ocp-4-10-dynamic-plugin-technology-preview[{ocp} 4.10 release] and a more
@KevinFCormier I edited a bit here. OCP team asked for us to link to their doc from our release note, and we agreed. I separated their plug and ours. See if this works.

2022-04-21 19:55 UTC, KevinFCormier commented on console/console.adoc
> +. Click on the _Console plug-ins_ tab. Both the `acm` and `mce` plug-ins are listed.
Good enough. Sounds like they might change it in the UI at some point.

2022-04-21 20:00 UTC, KevinFCormier commented on release_notes/whats_new.adoc
> +* For {ocp-short} 4.10, with the https://docs.openshift.com/container-platform/4.10/release_notes/ocp-4-10-release-notes.html#ocp-4-10-dynamic-plugin-technology-preview[{ocp} 4.10 release] and a more
@swopebe May I ask who from OCP requested this, or can I get some more explanation for the rationale? It's good that you removed the mention of tech preview since it does not apply to our use-case, but I still don't understand the motivation for linking to that documentation.

2022-04-21 20:49 UTC, swopebe commented on release_notes/whats_new.adoc
> +* For {ocp-short} 4.10, with the https://docs.openshift.com/container-platform/4.10/release_notes/ocp-4-10-release-notes.html#ocp-4-10-dynamic-plugin-technology-preview[{ocp} 4.10 release] and a more
@KevinFCormier the documentation team and manager wants us to point to theirs because they start reaching dynamic plug in from the OCP console and they want to point to our doc when we GA. I think it's not necessary but also not threatening in anyway.

2022-04-21 21:02 UTC, swopebe commented on release_notes/whats_new.adoc
> +* For {ocp-short} 4.10, with the https://docs.openshift.com/container-platform/4.10/release_notes/ocp-4-10-release-notes.html#ocp-4-10-dynamic-plugin-technology-preview[{ocp} 4.10 release] and a more
Can we merge, build, close?

2022-04-21 21:04 UTC, KevinFCormier approved these changes

2022-04-21 21:24 UTC, merged