Update gitops_config.adoc
open-cluster-management/rhacm-docs pull request #3307
Opened 2022-04-05 13:27 UTC by rokej

https://github.com/stolostron/backlog/issues/21254

2022-04-06 16:43 UTC, dockerymick requested changes
Your addition looks great! Thanks for including me, I made a suggestion

2022-04-06 16:43 UTC, dockerymick commented on applications/gitops_config.adoc
> +
Thanks for pulling me in. I will leave the updates to Brandi. Here are my suggestions:


When you integrate with the GitOps operator for every managed cluster bound to the GitOps namespace, through the placement and `ManagedClusterSetBinding` custom resources, a secret with a token to access the `ManagedCluster` is created in the namespace. This is required for the GitOps controller to sync resources to the remote managed cluster. When a user is given administrator access to a GitOps namespace to perform application lifecycle operations, the user also gains access to this secret and `admin` level to the managed cluster.

If this is not desired, instead of binding the user to the namespace-scoped `admin` role, use a more restrictive custom role with permissions required to work with application resources that can be created and used to bound the user. View the following example:

is remote cluster the same as saying local cluster?

2022-04-08 18:35 UTC, swopebe commented on applications/gitops_config.adoc
> +
Thanks @dockerymick 

I made the changes, but I still do agree that as far as we can tell "remote" and "managed" are the same. (local cluster is the hub when managed)....

@rokej can we remove `remote` or is there a reason for it? Thanks!

2022-04-08 18:49 UTC, rokej commented on applications/gitops_config.adoc
> +
You mean `remote managed cluster`? Yes we can remove `remote` and just say `managed cluster`

2022-04-12 17:17 UTC, dockerymick approved these changes
Thanks for accepting my suggestions. The changes look good to me! I will leave the merge to Brandi or Roke if all is well

2022-04-12 18:21 UTC, merged

2022-04-18 16:34 UTC, swopebe commented on applications/gitops_config.adoc
> +
Done, thanks @rokej