stolostron/backlog#20719 add Sub uninstall
open-cluster-management/rhacm-docs pull request #3345
Opened 2022-04-19 12:24 UTC by cadawson

2022-04-19 22:16 UTC, tpantelis requested changes

2022-04-19 22:16 UTC, tpantelis commented on services/submariner/submariner_uninstall.adoc
> +You can uninstall the Submariner components from your clusters. Select from the three methods that you can use based on your preference and the version of Submariner that you are removing. You can us
Most of the Submariner components in all versions are removed as a result of deleting the Submariner add-on component. Prior to 0.12 some data plane remnants (eg IP table chains/rules et al) were left behind but those are now automatically cleaned up in 0.12 .

```suggestion
You can uninstall the Submariner components from your clusters using the {product-title} console or the command-line if that is preferred. For Submariner versions prior to 0.12, additional steps are needed to completely remove all data plane components.
```

2022-04-19 22:16 UTC, tpantelis commented on services/submariner/submariner_uninstall.adoc
> +== Automatic method
The console method is also automatic.

```suggestion
== Command-line method  
```

2022-04-19 22:16 UTC, tpantelis commented on services/submariner/submariner_uninstall.adoc
> +. Confirm that you want to remove all of the Submariner components from the cluster.
`subctl uninstall` does not need to be run. Everything that this command does is also done by removing/deleting the Submariner add-on. So this section should describe how to manually delete the add-on resource via CLI. However I'm not sure if these docs instruct users to use `kubectl` or the Openshift CLI (`oc` I believe).

2022-04-19 22:16 UTC, tpantelis commented on services/submariner/submariner_uninstall.adoc
> +**Important:** Verify that all of the cloud resources are removed from the cloud provider to avoid additional charges by your cloud provider.
This section should describe the manual steps needed to do the additional cleanup prior to 0.12 after performing the Submariner add-on removal above. That is documented specifically here: https://submariner.io/operations/cleanup/#manual-uninstall, although really only sections 5-9 need to be preformed as 1-4 are done as part of the Submariner add-on removal.

2022-04-25 16:45 UTC, tpantelis requested changes

2022-04-25 16:45 UTC, tpantelis commented on services/submariner/submariner_uninstall.adoc
> +To uninstall Submariner version 0.12, or later, complete the following steps:
This applies to all versions.

2022-04-27 15:48 UTC, dfarrell07 commented on release_notes/whats_new.adoc
> +* Integrating Submariner multicluster networking service through {product-title-short} is generally available. See link:../services/submariner/submariner.adoc#submariner[Submariner multicluster netwo
Is this overall Submariner release note meant to be a part of this PR?

If so, I wonder if it should be a bit more qualified, as Submariner is GA in some situations and Tech Preview in others.

2022-04-27 15:48 UTC, dfarrell07 commented on services/submariner/submariner_uninstall.adoc
> +**Important:** Verify that all of the cloud resources are removed from the cloud provider to avoid additional charges by your cloud provider.
Should we add some details about what exactly to verify is uninstalled and how to verify it? There are three references like this in this PR, maybe all of them should refer to common "Uninstall verification" docs.

2022-04-27 15:48 UTC, dfarrell07 commented on services/submariner/submariner_uninstall.adoc
> +Replace `CLUSTER_NAME` with the name of the cluster.
```suggestion
Replace `<CLUSTER_NAME>` with the name of the cluster.
```

Right? Otherwise I could imagine people using `<my-cluster>` instead of `my-cluster`.

2022-05-04 19:10 UTC, tpantelis requested changes

2022-05-04 19:10 UTC, tpantelis commented on services/submariner/submariner_uninstall.adoc
> +When uninstalling versions of Submariner that are earlier than version 0.12, you must complete the additional steps that are provided in the  https://submariner.io/operations/cleanup/[Uninstalling Su
Since you provide the Submariner doc link anyway, why not just say to follow sections 5-8 instead of copying/duplicating the content here?

```suggestion
When uninstalling versions of Submariner that are earlier than version 0.12, you must complete the additional steps, 5-8, that are provided in the  https://submariner.io/operations/cleanup/#manual-uninstall/[Manual Uninstall] section in the Submariner documentation.  
```

2022-05-04 21:06 UTC, cadawson commented on release_notes/whats_new.adoc
> +* Integrating Submariner multicluster networking service through {product-title-short} is generally available. See link:../services/submariner/submariner.adoc#submariner[Submariner multicluster netwo
@dfarrell07 This is intended to announce that Submariner is GA in the What's new. I didn't realize that only parts of it are GA. If that is the case, then I agree that we should differentiate the GA and the Tech Preview. Do you have a list available?

2022-05-04 21:07 UTC, cadawson commented on services/submariner/submariner_uninstall.adoc
> +**Important:** Verify that all of the cloud resources are removed from the cloud provider to avoid additional charges by your cloud provider.
@dfarrell07 We could add a section to the end of this that lists the steps to verify this.

2022-05-04 21:15 UTC, cadawson commented on services/submariner/submariner_uninstall.adoc
> +Replace `CLUSTER_NAME` with the name of the cluster.
Good question. The convention that we use throughout the rest of the docs is: If a variable is in example font already (such as in the command), we add the <> for setting it apart. If a variable is outside of example font (as in the sentence about what to use in place of the variable), we only include it in the example font to set it apart. We are ok there.

2022-05-04 21:20 UTC, cadawson commented on services/submariner/submariner_uninstall.adoc
> +When uninstalling versions of Submariner that are earlier than version 0.12, you must complete the additional steps that are provided in the  https://submariner.io/operations/cleanup/[Uninstalling Su
@tpantelis : Reasonable point. I was leaning in that direction, but wanted to see if it made more sense to have it all conveniently located in the docs. How often do you think those steps will change?

2022-05-04 21:24 UTC, tpantelis commented on services/submariner/submariner_uninstall.adoc
> +When uninstalling versions of Submariner that are earlier than version 0.12, you must complete the additional steps that are provided in the  https://submariner.io/operations/cleanup/[Uninstalling Su
They won't change b/c they apply to older versions. In fact, since I believe we're GA'ing submariner with ACM 2.5 and submariner 0.12, do we even need to mention manual steps prior to 0.12? @dfarrell07

2022-05-05 11:39 UTC, cadawson commented on services/submariner/submariner_uninstall.adoc
> +When uninstalling versions of Submariner that are earlier than version 0.12, you must complete the additional steps that are provided in the  https://submariner.io/operations/cleanup/[Uninstalling Su
Sounds good. Certainly makes maintenance easier, having it in one place. Thanks!

2022-05-05 19:43 UTC, tpantelis commented
/lgtm

2022-05-17 14:00 UTC, manosnoam commented
@cadawson checkout https://qe-jenkins-csb-skynet.apps.ocp4.prod.psi.redhat.com/job/ACM-Upgrade-2.5.0-Submariner-0.12.1-AWS-GCP-Globalnet/2/Test-Report/

Under "Uninstalling previous Submariner":
```

$ subctl uninstall --yes
 • Checking if the connectivity component is installed on cluster "api-gcp-nmanos-cluster-c-1-gcp-subm-red-chesterfield-com:6443"  ...
 ✓ Checking if the connectivity component is installed on cluster "api-gcp-nmanos-cluster-c-1-gcp-subm-red-chesterfield-com:6443"
 ✓ The connectivity component is not installed on cluster "api-gcp-nmanos-cluster-c-1-gcp-subm-red-chesterfield-com:6443" - skipping
 • Checking if the service discovery component is installed on cluster "api-gcp-nmanos-cluster-c-1-gcp-subm-red-chesterfield-com:6443"  ...
 ✓ Checking if the service discovery component is installed on cluster "api-gcp-nmanos-cluster-c-1-gcp-subm-red-chesterfield-com:6443"
 ✓ The service discovery component is not installed on cluster "api-gcp-nmanos-cluster-c-1-gcp-subm-red-chesterfield-com:6443" - skipping
 • Deleting the Submariner cluster roles and bindings on cluster "api-gcp-nmanos-cluster-c-1-gcp-subm-red-chesterfield-com:6443"  ...
 ✓ Deleting the Submariner cluster roles and bindings on cluster "api-gcp-nmanos-cluster-c-1-gcp-subm-red-chesterfield-com:6443"
 ✓ Deleted the "submariner-gateway" cluster role and binding
 ✓ Deleted the "submariner-globalnet" cluster role and binding
 ✓ Deleted the "submariner-lighthouse-agent" cluster role and binding
 ✓ Deleted the "submariner-lighthouse-coredns" cluster role and binding
 ✓ Deleted the "submariner-networkplugin-syncer" cluster role and binding
 ✓ Deleted the "submariner-routeagent" cluster role and binding
 • Deleting the Submariner namespace "submariner-operator" on cluster "api-gcp-nmanos-cluster-c-1-gcp-subm-red-chesterfield-com:6443"  ...
 ✓ Deleting the Submariner namespace "submariner-operator" on cluster "api-gcp-nmanos-cluster-c-1-gcp-subm-red-chesterfield-com:6443"
 • Deleting the Submariner custom resource definitions on cluster "api-gcp-nmanos-cluster-c-1-gcp-subm-red-chesterfield-com:6443"  ...
 ✓ Deleting the Submariner custom resource definitions on cluster "api-gcp-nmanos-cluster-c-1-gcp-subm-red-chesterfield-com:6443"
 ✓ Deleted the "brokers.submariner.io" custom resource definition
 ✓ Deleted the "clusterglobalegressips.submariner.io" custom resource definition
 ✓ Deleted the "clusters.submariner.io" custom resource definition
 ✓ Deleted the "endpoints.submariner.io" custom resource definition
 ✓ Deleted the "gateways.submariner.io" custom resource definition
 ✓ Deleted the "globalegressips.submariner.io" custom resource definition
 ✓ Deleted the "globalingressips.submariner.io" custom resource definition
 ✓ Deleted the "servicediscoveries.submariner.io" custom resource definition
 ✓ Deleted the "submariners.submariner.io" custom resource definition
 • Unlabeling gateway nodes on cluster "api-gcp-nmanos-cluster-c-1-gcp-subm-red-chesterfield-com:6443"  ...
 ✓ Unlabeling gateway nodes on cluster "api-gcp-nmanos-cluster-c-1-gcp-subm-red-chesterfield-com:6443"


```

2022-05-24 12:51 UTC, tpantelis requested changes

2022-05-24 12:51 UTC, tpantelis commented on add-ons/submariner/submariner_uninstall.adoc
> +If the version of Submariner that you are removing is earlier than version 0.12, continue with xref:../services/submariner/submariner_uninstall.adoc#uninstalling-submariner-manual[Manual removal step
One minor thing...we mention this for the CLI method but not for the console method for which it also applies. Either we include this statement there as well or omit it. I think the latter is fine since we state this at the beginning on line 4.

2022-05-25 12:33 UTC, cadawson commented on add-ons/submariner/submariner_uninstall.adoc
> +If the version of Submariner that you are removing is earlier than version 0.12, continue with xref:../services/submariner/submariner_uninstall.adoc#uninstalling-submariner-manual[Manual removal step
Thank you, @tpantelis . Good point. I went ahead and added it to the console piece, because I think the link to the next steps makes it easier for the user. That should cover it.

2022-05-25 12:34 UTC, tpantelis approved these changes

2022-05-25 13:09 UTC, merged