stolostron/backlog#20928 rm fips note volsync
open-cluster-management/rhacm-docs pull request #3352
Opened 2022-04-20 17:22 UTC by cadawson

2022-04-20 18:33 UTC, tesshuflower approved these changes
/lgtm

Thanks for the quick update Chris!

2022-04-21 18:49 UTC, dockerymick requested changes
Thanks for pulling me in Chris. I left a couple of comments and questions

2022-04-21 18:49 UTC, dockerymick commented on release_notes/fips_readiness.adoc
> +** Hub of hubs (Developer preview)
Can you explain why we are placing a developer preview component in the product doc? It is also being listed after stating "which Technology preview" components are not FIPS ready

2022-04-21 18:49 UTC, dockerymick commented on release_notes/fips_readiness.adoc
> +FIPS with information text: Use the Federal Information Processing Standards (FIPS) modules provided with RHCOS instead of the default Kubernetes cryptography suite file before you deploy the new man
Should it be RHOCS? Should there also be a period at the end of this statement ?

2022-04-22 12:40 UTC, cadawson commented on release_notes/fips_readiness.adoc
> +** Hub of hubs (Developer preview)
I know that we don't document dev preview in the product docs. In this case, I thought that FIPS compliance would be a pretty big deal, even if you are using a dev preview version. You bring up a good point, though. They should not be using it for any production content if it is dev preview (or tech preview, for that matter). So maybe it is not necessary to mention here.

2022-04-22 12:50 UTC, cadawson commented on release_notes/fips_readiness.adoc
> +FIPS with information text: Use the Federal Information Processing Standards (FIPS) modules provided with RHCOS instead of the default Kubernetes cryptography suite file before you deploy the new man
In the UI today, it is RHOCS. You are correct that it should be Red Hat Enterprise Linux CoreOS. Randy made an update when we went through the UI, but I haven't seen it in the playback instance yet. I went ahead and changed it in the docs, as I think it will make it into the UI by GA. 
Yes, I added a period at the end. 
Thanks!

2022-04-22 12:52 UTC, gparvin commented on release_notes/fips_readiness.adoc
> +** Hub of hubs (Developer preview)
Yes, I think it's find to take it out.  I think we have other dev preview components too so since they likely wouldn't be FIPS compliant either we should probably not list dev preview items or have a general statement indicating dev preview items are not reviewed for FIPS readiness.

2022-04-22 16:12 UTC, dockerymick approved these changes
Thanks for answering my questions and pulling me in for the review. I believe the last change left is to remove the dev preview. Other than that, this looks good to me!

2022-04-25 14:59 UTC, cadawson commented
Hi @gparvin . I removed the Hub of hubs developer preview item, as we don't document dev preview items in the formal documentation. Did you want to take another look at this one before we merge? Thanks!

2022-04-25 15:13 UTC, gparvin commented
@cadawson We can only support fips on `x86_64`.  See the first sentence here: https://access.redhat.com/documentation/en-us/openshift_container_platform/4.10/html/installing/installing-fips
I think we should reword the sentence indicating that we only support x86_64 matching OpenShift instead of listing platforms we don't support FIPS on.

Other than that I think this looks good!  Thanks

2022-04-27 12:12 UTC, cadawson commented
Thanks @gparvin . I updated that bullet to which architectures it is supported on. Want one last look?

2022-04-27 12:22 UTC, gparvin approved these changes

2022-04-27 12:35 UTC, dockerymick commented
Based on the approvals and confirmation from Chris via Slack, I am merging this issue.

2022-04-27 12:35 UTC, merged