stolostron/backlog#20329--reorg the app topic, add placement
open-cluster-management/rhacm-docs pull request #3372
Opened 2022-04-26 20:16 UTC by swopebe

2022-04-26 20:55 UTC, chenz4027 requested changes

2022-04-26 20:55 UTC, chenz4027 commented on applications/app_console.adoc
> +* Click the *Advanced configuration* tab to view terminology and tables of resources for all applications. You can find resources and you can filter subscriptions, placement rules, and channels. If y
You can find resources and you can filter subscriptions, placement rules, and channels.
---------
Placement is missing from the description

2022-04-26 20:55 UTC, chenz4027 commented on applications/app_console.adoc
>  |===
I think we are also missing placement here. Should be:

Application resource | Kind (search parameter)
-- | --
Placement | Placement

2022-04-27 16:06 UTC, swopebe commented on applications/app_console.adoc
>  |===
Thanks for catching those, change is in.

2022-04-27 17:08 UTC, chenz4027 approved these changes
lgtm, thanks @swopebe

2022-04-27 18:44 UTC, merged