stolostron/backlog#20772
open-cluster-management/rhacm-docs pull request #3374
Opened 2022-04-27 11:00 UTC by swopebe

--wokring MCE plugin doc

2022-05-03 14:49 UTC, KevinFCormier requested changes
Thanks for adding this! I think there are a few spots that need clarification.

2022-05-03 14:49 UTC, KevinFCormier commented on multicluster_engine/console_mce.adoc
> +{ocp-short} console plug-ins are available with {ocp-short} 4.10 web console and can be integrated. To use this feature, the console plug-ins must remain enabled. The multicluster engine operator dis
We might want to mention that these features are the ones from ACM under the **Infrastructure** and **Credentials** navigation items.

2022-05-03 14:49 UTC, KevinFCormier commented on multicluster_engine/console_mce.adoc
> +. Click on the _Console plug-ins_ tab. Both the `acm` and `mce` plug-ins are listed.
`acm` is only listed if ACM is installed.

2022-05-03 14:49 UTC, KevinFCormier commented on multicluster_engine/console_mce.adoc
> +For {ocp-short} 4.10 with the plug-ins enabled, you can access {product-title-short} within the {ocp-short} console from the cluster switcher by selecting *All Clusters* from the drop-down menu. With
This part seems not relevant to multicluster engine. ACM would be available in the perspective switcher only if ACM is installed.

Last sentence is missing a period and seems vague. I'm not sure which scenario it is referring to.

2022-05-09 23:07 UTC, swopebe commented on multicluster_engine/console_mce.adoc
> +For {ocp-short} 4.10 with the plug-ins enabled, you can access {product-title-short} within the {ocp-short} console from the cluster switcher by selecting *All Clusters* from the drop-down menu. With
I think the install team wanted this part in--I don't remember who asked for it. They want users on 4.8 to understand why the view is different. 

I moved it to a note.

We can remove it or we can let OCP decide what to do with it when we send it off next release.

2022-05-09 23:08 UTC, swopebe commented on multicluster_engine/console_mce.adoc
> +. Click on the _Console plug-ins_ tab. Both the `acm` and `mce` plug-ins are listed.
The `mce` plug-in is listed. *Note:* If {product-title-short} is installed, it is also listed as `acm`.

2022-05-10 13:49 UTC, KevinFCormier commented on multicluster_engine/console_mce.adoc
> +For {ocp-short} 4.10 with the plug-ins enabled, you can access {product-title-short} within the {ocp-short} console from the cluster switcher by selecting *All Clusters* from the drop-down menu. With
OK, that's better since you removed the last sentence. With ACM, the feature set is not limited.

2022-05-10 15:42 UTC, KevinFCormier approved these changes

2022-05-10 15:46 UTC, merged