Updating backup and restore docs
open-cluster-management/rhacm-docs pull request #3391
Opened 2022-05-04 13:16 UTC by dockerymick

https://app.zenhub.com/workspaces/engineering-backlog-do-not-delete-604fab62d4b98d00150a2854/issues/stolostron/backlog/21861

2022-05-11 16:25 UTC, sahare requested changes
Thanks @dockerymick, I've added some comments.

2022-05-11 16:25 UTC, sahare commented on clusters/backup_and_restore.adoc
> +Velero currently skips existing backed up resources on the hub cluster. This limits the scenarios that can be used when you restore hub clsuter data on a new hub cluster. If the new hub cluster is no
typo in `clsuter data` on line 190

2022-05-11 16:25 UTC, sahare commented on clusters/backup_and_restore.adoc
> +** Only managed clusters created by the Hive API are automatically connected with the new hub cluster when the `acm-managed-clusters` backup, from the _managed clusters_ backup is restored on another
typo in `can bbe connected`

2022-05-11 16:25 UTC, sahare commented on clusters/backup_and_restore.adoc
> +When the `cluster.open-cluster-management.io/backup: cluster-activation` label is added to a resource the resource is automatically backed up in the `acm-resources-generic-schedule` backup resource.
The text that starts on line 264 and ends before the sample is very confusing, the right description can be:

`Managed clusters activation data or activation data, is backup data which when restored on a new hub will result in managed clusters being actively managed by the hub where the restore was executed. Activation data resources are stored by the managed clusters backup, and by the resources-generic backup, using the cluster.open-cluster-management.io/backup: cluster-activation label.

When you add the cluster.open-cluster-management.io/backup label to a resource, this resource is automatically backed up under the acm-resources-generic-schedule backup. If any of these resources need to be restored only when the managed clusters are moved to the new hub, so when the veleroManagedClustersBackupName:latest is used on the restored resource, then you have to set the label value to cluster-activation. This will ensure the resource is not restored unless the managed cluster activation is called.`

2022-05-11 16:25 UTC, sahare commented on release_notes/known_issues.adoc
> +To address the previously mentioned limitations, create a `restore.cluster.open-cluster-management.io` resource for the cluster backup and restore operator runs a set of steps, which cleans up the hu
Not sure if we should add this restore limitation part under known issues, it's basically explaining a limitation in Velero restore operation, so we have implemented a solution to resolve it, these limitations are taken from the section that you describe this Velero restore limitation and the cleanup options, but these are examples of that Velero limitation and doesn't make sense to be here on its own, the text below explains it better:

`Velero currently skips backed up resources if they are already installed on the hub. This limits the scenarios that can be used when restoring hub data on a new hub. Unless the new hub is not used and the restore is applied only once, the hub could not be relibly used as a passive configuration: the data on this hub is not reflective of the data available with the restored resources.

Restore limitations examples:

A Policy exists on the new hub, before the backup data is restored on this hub. After the restore of the backup resources, the new hub is not identical with the initial hub from where the data was restored. The Policy should not be running on the new hub since this is a Policy not available with the backup resources.

A Policy exists on the new hub, before the backup data is restored on this hub. The backup data contains the same Policy but in an updated configuration. Since Velero skips existing resources, the Policy will stay unchanged on the new hub, so the Policy is not the same as the one backed up on the initial hub.

A Policy is restored on the new hub. The primary hub keeps updating the content and the Policy content changes as well. The user reapplies the backup on the new hub, expecting to get the updated Policy. Since the Policy already exists on the hub - created by the previous restore - it will not be restored again. So the new hub has now a different configuration from the primary hub, even if the backup contains the expected updated content; that content is not updated by Velero on the new hub.

To address above limitations, when a Restore.cluster.open-cluster-management.io resource is created, the Cluster Back up and Restore Operator runs a prepare for restore set of steps which will clean up the hub, before Velero restore is called.`

2022-05-11 16:25 UTC, sahare commented on clusters/backup_and_restore.adoc
> +The cluster backup and restore operator provides disaster recovery solutions for when {product-title} hub cluster goes down and needs to be recreated. It runs on the hub cluster and depends on the li
It should be `The cluster backup and restore operator solution provides backup and restore support for all`

2022-05-13 00:44 UTC, dockerymick commented on clusters/backup_and_restore.adoc
> +Velero currently skips existing backed up resources on the hub cluster. This limits the scenarios that can be used when you restore hub clsuter data on a new hub cluster. If the new hub cluster is no
Great catch, thank you!

2022-05-13 01:08 UTC, dockerymick commented on release_notes/known_issues.adoc
> +To address the previously mentioned limitations, create a `restore.cluster.open-cluster-management.io` resource for the cluster backup and restore operator runs a set of steps, which cleans up the hu
What are your thoughts about me specifying that these are Velero restore limitations. I disagree with listing limitations in the topic. i think it is best to let the user know the recommended step rather than just stating what is wrong

2022-05-13 01:13 UTC, dockerymick commented on clusters/backup_and_restore.adoc
> +The cluster backup and restore operator provides disaster recovery solutions for when {product-title} hub cluster goes down and needs to be recreated. It runs on the hub cluster and depends on the li
Updated

2022-05-13 13:29 UTC, sahare commented on release_notes/known_issues.adoc
> +To address the previously mentioned limitations, create a `restore.cluster.open-cluster-management.io` resource for the cluster backup and restore operator runs a set of steps, which cleans up the hu
Sure, just this text still needs to be updated:
`To address the previously mentioned limitations, create a `restore.cluster.open-cluster-management.io` resource for the cluster backup and restore operator runs a set of steps, which cleans up the hub cluster before Velero restore begins. `

2022-05-16 13:18 UTC, dockerymick commented on release_notes/known_issues.adoc
> +To address the previously mentioned limitations, create a `restore.cluster.open-cluster-management.io` resource for the cluster backup and restore operator runs a set of steps, which cleans up the hu
@sahare thanks for your feedback. Why do you all have "prepare for restore" set of steps? Is that the name of a script? Should the following be monospaced: `prepare-for-restore` set of steps

2022-05-16 14:03 UTC, sahare commented on release_notes/known_issues.adoc
> +To address the previously mentioned limitations, create a `restore.cluster.open-cluster-management.io` resource for the cluster backup and restore operator runs a set of steps, which cleans up the hu
@dockerymick No, it's just a process in our code which runs a set of steps to prepare for restore by cleaning up the hub cluster before the Velero restore begins.

2022-05-16 14:13 UTC, dockerymick commented on release_notes/known_issues.adoc
> +To address the previously mentioned limitations, create a `restore.cluster.open-cluster-management.io` resource for the cluster backup and restore operator runs a set of steps, which cleans up the hu
@sahare Thanks for explaining! I think we are good on this PR now. May you do another review and let me know if i missed anything. If all is well, will you approve the PR?

2022-05-16 14:52 UTC, sahare approved these changes
Looks good to me, Thanks!

2022-05-16 16:19 UTC, merged