stolostron/backlog#21395 submar openstack
open-cluster-management/rhacm-docs pull request #3402
Opened 2022-05-09 17:07 UTC by cadawson

2022-05-13 20:02 UTC, aswinsuryan commented on services/submariner/submariner_prepare_hosts.adoc
> +. If you did not create the managed cluster with {product-title-short}, you must manually create a secret on your hub cluster in the namespace of your managed cluster that contains your Red Hat OpenS
In either case we need to create the secret manually. As the secret used by submariner has different requirements from the ACM one.

2022-05-13 20:06 UTC, aswinsuryan commented on services/submariner/submariner_prepare_hosts.adoc
> +auth_type: "v3applicationcredential"
The credential secret required by submariners takes these parameters.

    auth:
      auth_url: https://rhos-d.infra.prod.upshift.rdu2.redhat.com:13000
      application_credential_id: "<id>"
      application_credential_secret: "<secret>"
    region_name: "regionOne"
    interface: "public"
    identity_api_version: 3
    auth_type: "v3applicationcredential"

2022-05-24 15:22 UTC, aswinsuryan requested changes

2022-05-24 15:22 UTC, aswinsuryan commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +auth:
oh I missed this , the auth section is a part of clouds,yaml , the secret should be

apiVersion: v1
data:
  cloud: <cloudname>
  clouds.yaml:<clouds.yaml>
kind: Secret
metadata:
  name: <name>
  namespace: <namespace>
type: Opaque

and the clouds.yaml above should be base 64 encoded of 

clouds:
  openstack:
    auth:
      auth_url: <auth-url>
      application_credential_id: <application-credential-id>
      application_credential_secret: <application-credential-secret>
    region_name: "regionOne"
    interface: "public"
    identity_api_version: 3
    auth_type: "v3applicationcredential"

2022-05-25 10:06 UTC, cadawson commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +auth:
I think I have this covered now, @aswinsuryan . Please take a look. Thanks!

2022-05-29 15:03 UTC, cadawson commented
Is this one ready to merge @aswinsuryan ? Thanks!

2022-05-31 05:59 UTC, vthapar requested changes

2022-05-31 05:59 UTC, vthapar commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +oc apply -f submar_addon
```suggestion
oc apply -f submar_addon.yaml
```

2022-05-31 05:59 UTC, vthapar commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +[source.yaml]
Shouldn't this be [source,yaml] ?

2022-05-31 11:16 UTC, cadawson commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +[source.yaml]
Yes. Good catch. Changed.

2022-05-31 12:57 UTC, aswinsuryan approved these changes

2022-06-01 17:33 UTC, merged