stolostron/backlog#20721 add sub ts
open-cluster-management/rhacm-docs pull request #3452
Opened 2022-05-23 21:13 UTC by cadawson

2022-05-24 10:29 UTC, vthapar requested changes

2022-05-24 10:29 UTC, vthapar commented on troubleshooting/troubleshooting_intro.adoc
> +** xref:../troubleshooting/trouble_submariner_degraded.adoc#troubleshooting-submariner-degraded[Submariner add-on status is degraded after installing with the console]
Is this documentation only intended for installation through console? Do we need separate steps for deployments through CLI?

UI pulls information from `submariner` `ManagedClusterAddon`. Do we want to capture it somewhere? I can share a sample output.

2022-05-24 10:29 UTC, vthapar commented on troubleshooting/trouble_submariner_degraded.adoc
> +** Degraded: The connection is not ready, possibly because the steps are  still in progress.
During initial installation, it can happen because in progress, but later it can also happen if two clusters lose connectivity to each other. In case of multiple clusters, it will show Degraded if at least one cluster is in disconnected state.

It will also show which clusters are connected, and which ones are disconnected.

2022-05-24 10:29 UTC, vthapar commented on troubleshooting/trouble_submariner_degraded.adoc
> +
Should we list these in order of UI or in order of when each of these comes up? _Gateway nodes_ will be ready first, then _Agent status_ and then _Connection status_

2022-05-24 10:29 UTC, vthapar commented on troubleshooting/trouble_submariner_degraded.adoc
> +
We need some extra steps here. In case any of the above 3 are still degraded, there will be different troubleshooting steps based on which one of the 3 is in Degraded.

2022-05-24 10:29 UTC, vthapar commented on troubleshooting/trouble_submariner_degraded.adoc
> +. Use the `benchmark` command with the `subctl` tool to establish a base on which to compare when you run additional diagnostics.
We normally run benchmark once everything looks okay, to establish a performance baseline for future.

@sridhargaddam Thoughts?

2022-05-24 10:29 UTC, vthapar commented on troubleshooting/trouble_submariner_degraded.adoc
> +** Degraded: The Submariner agent is not running correctly, possibly because it is still in progress.
When you click on status it will show which particular submariner component is in error state. Next step would be to check status of that component's deployment and Pods.

2022-05-24 10:29 UTC, vthapar commented on troubleshooting/trouble_submariner_degraded.adoc
> +. You can use the `diagnose` command with the `subctl` utility to run some tests on the Submariner connections. See https://submariner.io/operations/deployment/subctl/#diagnose[`diagnose`] in the Sub
We normally run `diagnose` when:

1. Agent status or Connection Status is in Degraded. Diagnose will give more detailed analysis on what exactly is the issue.
2. Everything is green in UI but still things are not working. We run diagnose to make sure there are not any other connectivity/deployment issues not covered by UI. It is considered a good practice to run diagnostics after any deployment to catch such hidden issues.

2022-05-24 10:29 UTC, vthapar commented on troubleshooting/trouble_submariner_degraded.adoc
> +. If a problem continues with the `Connection status`, you can run the `verify` command with your `subctl` utility tool to test the connection between two Submariner clusters. The basic format for th
For problems in `Connection status` we still want to run `diagnose`.  `verify` is mainly run when everything looks good, including diagnose to test the actual connectivity between clusters with some test traffic. If any of the status in console or diagnose show any errors, verify will fail. At most it will give a bit more detailed information on what all are failing.

2022-05-24 10:42 UTC, cadawson commented on troubleshooting/troubleshooting_intro.adoc
> +** xref:../troubleshooting/trouble_submariner_degraded.adoc#troubleshooting-submariner-degraded[Submariner add-on status is degraded after installing with the console]
Good question, @vthapar . It is not required to be. for this one, I thought it applies more specifically to the console, since the messages are provided there. If it applies to both. we can remove that phrase.

2022-05-24 10:56 UTC, cadawson commented on troubleshooting/trouble_submariner_degraded.adoc
> +
I think it could go either way, but it is easy to change. Updated.

2022-05-24 10:59 UTC, cadawson commented on troubleshooting/trouble_submariner_degraded.adoc
> +. Use the `benchmark` command with the `subctl` tool to establish a base on which to compare when you run additional diagnostics.
Moved this one to the end of the list, assuming it might be the last step.

2022-05-31 06:22 UTC, vthapar requested changes
One thing I noticed missing in this doc is what to do once some issue is discovered and can't be resolved. The upstream doc provides a link to file an upstream issue which uses a fixed template on what information to collect. We need a similar link to Bugzilla and instructions on what information to gather. As of 2.5 we don't have submariner-addon information captured in ACM `must-gather` or `subctl gather`. So we need a section on what information to gather in case of failure.

2022-05-31 06:22 UTC, vthapar commented on troubleshooting/trouble_submariner_degraded.adoc
> +. If a problem continues with the `Connection status`, you can run the `verify` command with your `subctl` utility tool to test the connection between two Submariner clusters. The basic format for th
We normally run verify when `connection status` and `diagnose` both don't show any errors. So, run veriy if facing some issues even though Connection Status and diagnose give no errors. A good practice to run verify on a fresh deployment after running diagnose to catch any issues not caught by diagnose.

Way it is currentl worded, it looks like`verify` should be run only if some error in Connection Status, while it is the opposite. If there are errors in Connection Status or diagnose, no need to run verify as it will definitely fail.

2022-05-31 12:52 UTC, vthapar commented
Not sure if this doc is good place, but we need to provide information on what to do when users are unable to resolve/find issue with steps in this guide. Mainly:

1. Run `must-gather` on hub and managed clusters. Do we go into details on when to run where?
2. run `subctl gather` on all managed and hub clusters.
3. Capture `submarinerconfigs` and `brokers.submariner.io` on hub clusters. There is one SubmarinerConfig for each managedcluster in managedcluster namespace. There is one brokers object in broker namespace.

If we decide to add this information in this doc, I can provide commands for step 3.

2022-06-03 09:09 UTC, cadawson commented
Hi @vthapar . I was hoping to get something out that you had some time to look at. I added some general information to the PR. Will you take a look: https://github.com/stolostron/rhacm-docs/pull/3452? We can always add stuff to it after GA, if we need to,  but it should give a place to start. Thanks!

2022-06-03 13:08 UTC, vthapar requested changes

2022-06-03 13:08 UTC, vthapar commented on troubleshooting/trouble_submariner_general.adoc
> +.. Capture the `ManagedClusterAddon` Submariner and `SubmarinerConfig` Submariner from the `ManagedCluster` Namespace on the hub cluster.
```suggestion
.. Capture the `ManagedClusterAddon` `submariner` and `SubmarinerConfig` `submariner` from the `ManagedCluster` Namespace on the hub cluster.
```
Actual resource instance name is `submariner` so need to use that. Submariner with S capitalized refers to resource type called Submariner

2022-06-03 13:26 UTC, cadawson commented on troubleshooting/trouble_submariner_general.adoc
> +.. Capture the `ManagedClusterAddon` Submariner and `SubmarinerConfig` Submariner from the `ManagedCluster` Namespace on the hub cluster.
I changed that around a bit. See what you think.

2022-06-03 13:28 UTC, vthapar approved these changes

2022-06-06 11:50 UTC, merged