stolostron/backlog#20964 cim alt flow
open-cluster-management/rhacm-docs pull request #3475
Opened 2022-05-29 14:20 UTC by cadawson

2022-05-31 07:57 UTC, jelkosz commented
just one comment, otherwise looks good!

2022-05-31 07:57 UTC, jelkosz commented
just one comment, otherwise looks good!

2022-05-31 18:19 UTC, cadawson commented
Thanks @jelkosz . I don't see any new comments from you in the issue or the PR. Did you merge it into the PR already? I just want to make sure I don't miss it.

2022-06-01 06:47 UTC, jelkosz requested changes

2022-06-01 06:47 UTC, jelkosz commented on clusters/create_cluster_on_prem.adoc
> +* *Discover new hosts*: Retrieve a list of available hosts that might or might not be in an existing infrastructure environment.
nope, the hosts dont exist at this point yet. Id write something like: 
Dont use the hosts which are already present in an infrastructure environment, discover your own hosts instead.

2022-06-01 06:47 UTC, jelkosz commented
sorry @cadawson , forgot to submit them :(

2022-06-01 12:45 UTC, jelkosz commented
lgtm

2022-06-01 17:35 UTC, merged