stolostron/backlog#21626--enable klusterlet addon
open-cluster-management/rhacm-docs pull request #3480
Opened 2022-05-31 00:41 UTC by swopebe

2022-05-31 01:02 UTC, swopebe commented on add-ons/submariner/submariner_serv_disc.adoc
@cadawson need to make sure this is tech preview and if so, please use the syntax that we use across the doc.

2022-05-31 01:02 UTC, swopebe commented on add-ons/volsync/volsync.adoc
This looks like it should be the parent topic @cadawson but no links and there is no other topic...so maybe this needs the links?

2022-05-31 01:03 UTC, swopebe commented on add-ons/volsync/volsync_convert_backup.adoc
> +**Best practice:** You can update `resources.requests.storage` with a different value, when the value is at least the same size as the initial source persistent volume claim.
This is the correct way to label these.

2022-05-31 01:12 UTC, swopebe commented on add-ons/klusterlet_managed.adoc
> +[#add-ons-klusterlet]
@zhiweiyin318 can you review this doc, which is actually part of cluster and not MCE?

You can ignore the rest, which is a peer review.

Also, our template asks for a verification step, so can you please give me a last step to give users?

2022-05-31 15:06 UTC, zhiweiyin318 commented on add-ons/klusterlet_managed.adoc
> +[#add-ons-klusterlet]
looks great to me.  
yes,  the whole steps are on ACM not MCE since there is no `KlusterletAddonConfig` on MCE.

2022-06-01 14:05 UTC, swopebe commented on add-ons/klusterlet_managed.adoc
> +[#add-ons-klusterlet]
@zhiweiyin318 is there a verification step we can add?

2022-06-01 14:05 UTC, swopebe commented on add-ons/volsync/volsync.adoc
@cadawson poke

2022-06-06 13:29 UTC, swopebe commented on add-ons/klusterlet_managed.adoc
> +[#add-ons-klusterlet]
@zhiweiyin318 if not verification step, I will leave blank.

2022-06-06 13:58 UTC, zhiweiyin318 commented on add-ons/klusterlet_managed.adoc
> +[#add-ons-klusterlet]
yes, we can list the `managedClusterAddon` in the cluster namespace to verify whether the enabled `managedClusterAddons` are created after  the `KlusterletAddonConfig` is created.
```
oc get managedclusteraddons -n <cluster namespace>
```

2022-06-06 13:59 UTC, cadawson requested changes
Thanks for the review. Added suggestions.

2022-06-06 13:59 UTC, cadawson commented on add-ons/klusterlet_managed.adoc
> +The steps to enable the klusterlet add-ons for these managed clusters after the ACM is installed.
```suggestion
Complete the following steps to enable the klusterlet add-ons for the managed clusters after the {product-title-short} is installed:
```

2022-06-06 13:59 UTC, cadawson commented on add-ons/klusterlet_managed.adoc
> +. Apply the YAML by running the following command on the hub cluster.
```suggestion
. Apply the YAML by running the following command on the hub cluster:
```

2022-06-06 13:59 UTC, cadawson commented on add-ons/submariner/submariner.adoc
>  After adding the utility to your path, the following table briefly describes the available commands:
```suggestion
After adding the utility to your path, view the following table for a brief description of the available commands:
```

2022-06-06 13:59 UTC, cadawson commented on add-ons/submariner/submariner.adoc
>  After adding the utility to your path, the following table briefly describes the available commands:
Thanks. Good catch!

2022-06-06 13:59 UTC, cadawson commented on add-ons/volsync/volsync.adoc
Links are added in another PR that is out for review.

2022-06-06 13:59 UTC, cadawson commented on add-ons/volsync/volsync_replicate.adoc
>  VolSync does not create its own namespace, so it is in the same namespace as other {ocp-short} all-namespace operators. Any changes that you make to the operator settings for VolSync also affects the
```suggestion
VolSync does not create its own namespace, so it is in the same namespace as other {ocp-short} all-namespace operators. Any changes that you make to the operator settings for VolSync also affects the other operators in the same namespace, such as if you change to manual approval for channel updates. 
```

2022-06-07 23:22 UTC, swopebe commented on add-ons/klusterlet_managed.adoc
> +[#add-ons-klusterlet]
added as verification step

2022-06-08 09:30 UTC, cadawson commented on add-ons/submariner/submariner_serv_disc.adoc
removed. Thanks.

2022-06-08 17:17 UTC, cadawson approved these changes
Looks great! Thanks for the feedback!

2022-06-08 17:21 UTC, merged

2022-06-08 17:50 UTC, philipwu08 commented on add-ons/klusterlet_managed.adoc
> +**Note:** `policyController` controls the `governance-policy-framework` and `config-policy-controller` `managedClusterAddons`.
Not sure I understand this note. Maybe the `and` is at the wrong place?

2022-06-08 18:18 UTC, swopebe commented on add-ons/klusterlet_managed.adoc
> +**Note:** `policyController` controls the `governance-policy-framework` and `config-policy-controller` `managedClusterAddons`.
thanks, @zhiweiyin318 does that make sense?

2022-06-09 00:58 UTC, zhiweiyin318 commented on add-ons/klusterlet_managed.adoc
> +**Note:** `policyController` controls the `governance-policy-framework` and `config-policy-controller` `managedClusterAddons`.
yes, it's `and`.   `policyController` filed enable/disable the 2 addons .

2022-06-13 20:20 UTC, swopebe commented
@zhiweiyin318 can you better explain, not sure I understand what you mean by ^^^? Thanks so much.

2022-06-14 01:29 UTC, zhiweiyin318 commented
@swopebe  in 2.4 `policyController.enable` only enable/disable `policy-controller` addon. 
but in 2.5 `policy-controller`addon is divided into 2 addons `governance-policy-framework` and `config-policy-controller`, so `policyController` controls the `governance-policy-framework` and `config-policy-controller` `managedClusterAddons`.  there is no `policy-controller` addon in 2.5.

2022-06-15 19:37 UTC, swopebe commented
OK, still very confusing and will be confusing to the reader. In 2.5 doc, we don't want to discuss what was previous. I think I have an idea:

The policy-controller`addon is divided into two add-ons: `governance-policy-framework` and `config-policy-controller`. As a result, the `policyController` controls the `governance-policy-framework` and the `config-policy-controller` `managedClusterAddons`.