Document the evaluationInterval never value
open-cluster-management/rhacm-docs pull request #3487
Opened 2022-05-31 18:10 UTC by mprahl

2022-05-31 21:20 UTC, dhaiducek commented on governance/config_policy_ctrl.adoc
> +| Optional. Used to define how often the policy is evaluated when it is in the compliant state. The values must be in the format of a duration which is a sequence of numbers with time unit suffixes.
This should also be added to `spec.evaluationInterval.noncompliant`, correct?

2022-05-31 21:22 UTC, dhaiducek commented on governance/config_policy_ctrl.adoc
> +| Optional. Used to define how often the policy is evaluated when it is in the compliant state. The values must be in the format of a duration which is a sequence of numbers with time unit suffixes.
(Or at least summarized? Something like: "...time unit suffixes, and also accepts `never`.")

2022-06-01 13:20 UTC, mprahl commented on governance/config_policy_ctrl.adoc
> +| Optional. Used to define how often the policy is evaluated when it is in the compliant state. The values must be in the format of a duration which is a sequence of numbers with time unit suffixes.
You're right. I originally left it thinking it's not usually a good idea to set `evaluationInterval.noncompliant` to `never`, but we should leave that up to the user.

2022-06-01 14:33 UTC, dockerymick requested changes
Thanks for making these updates @mprahl I made a couple of comments. Is there an issue related to this?

2022-06-01 14:33 UTC, dockerymick commented on governance/config_policy_ctrl.adoc
> +| Optional. Used to define how often the policy is evaluated when it is in the compliant state. The values must be in the format of a duration which is a sequence of numbers with time unit suffixes.
It can also be set to `never` so that the policy is not reevaluated on the compliant  cluster, unless the policy `spec` is updated.

2022-06-01 14:33 UTC, dockerymick commented on governance/config_policy_ctrl.adoc
> +| Optional. Used to define how often the policy is evaluated when it is in the non-compliant state. Similar to the `evaluationInterval.compliant` parameter, the values must be in the format of a dura
It can also be set to `never` so that the policy is not reevaluated on the compliant  cluster, unless the policy `spec` is updated.

2022-06-01 15:28 UTC, mprahl commented
Thanks for the review @dockerymick! I just updated the PR based on your comments.

This is a followup on https://github.com/stolostron/backlog/issues/20519. I had just forgotten to tell you about the "never" option at the time.

2022-06-02 02:42 UTC, dockerymick approved these changes
Looks good !

2022-06-02 02:53 UTC, merged