stolostron/backlog#21192 list prioritizers 2.4
open-cluster-management/rhacm-docs pull request #3523
Opened 2022-06-04 17:49 UTC by cadawson

2022-06-06 02:53 UTC, haoqing0110 commented on clusters/placement_managed.adoc
> +****`name` is the name of a prioritizer. See the following list of valid names of the prioritizers:
miss blank space I think, the preview looks like below:
![Screen Shot 2022-06-06 at 10 52 00](https://user-images.githubusercontent.com/24226678/172086537-4d6466dc-3bbc-4e7a-8db1-b4e70e92d86c.png)

Expect to be https://open-cluster-management.io/concepts/placement/#score-based-prioritizer
![Screen Shot 2022-06-06 at 10 52 19](https://user-images.githubusercontent.com/24226678/172086557-9a3e99e5-c87b-4a82-a41c-9f2b0200fe0b.png)

2022-06-06 11:20 UTC, cadawson commented on clusters/placement_managed.adoc
> +****`name` is the name of a prioritizer. See the following list of valid names of the prioritizers:
Got it. Made those updates @haoqing0110 . Thanks!

2022-06-06 13:22 UTC, haoqing0110 commented on clusters/placement_managed.adoc
> +***`name` is the name of a prioritizer. See the following list of valid names of the prioritizers:
missed a blank space before `name`, ***`name` --> *** `name`

2022-06-06 13:22 UTC, haoqing0110 requested changes
A bit more comments.

2022-06-06 13:22 UTC, haoqing0110 commented on clusters/placement_managed.adoc
> +****`Steady`: Ensures that the existing decision is stabilized
missed a blank space before Steady, ***`Steady` --> *** `Steady`

2022-06-07 01:40 UTC, cadawson commented on clusters/placement_managed.adoc
> +****`Steady`: Ensures that the existing decision is stabilized
Good catches. Fixed. Thanks @haoqing0110 !

2022-06-07 01:50 UTC, haoqing0110 approved these changes
/approve
/lgtm

2022-06-07 14:33 UTC, merged