stolostron/backlog#22070 ts MCE rel images
open-cluster-management/rhacm-docs pull request #3526
Opened 2022-06-05 15:41 UTC by cadawson

2022-06-06 00:42 UTC, ldpliu commented on multicluster_engine/cluster_create_cli.adoc
> +When creating a cluster, you must add your release images to the https://github.com/stolostron/acm-hive-openshift-releases/tree/release-2.5/clusterImageSets[clusterImageSets] folder in the Git reposi
When creating a cluster, you must clone the https://github.com/stolostron/acm-hive-openshift-releases/tree/release-2.5/clusterImageSets/fast[clusterImageSets] and apply it to your hub cluster. After that, you can select the {ocp} release images when you create a cluster.

2022-06-06 10:14 UTC, cadawson commented on multicluster_engine/cluster_create_cli.adoc
> +When creating a cluster, you must add your release images to the https://github.com/stolostron/acm-hive-openshift-releases/tree/release-2.5/clusterImageSets[clusterImageSets] folder in the Git reposi
Thanks @ldpliu . Made the changes. Does it look ok?

2022-06-06 12:54 UTC, cadawson commented
fyi: @swopebe : This is an update for MCE. I followed what you did with troubleshooting in the other sections, but I thought you might want to know about it. Thanks!

2022-06-06 13:10 UTC, swopebe requested changes

2022-06-06 13:10 UTC, swopebe commented on multicluster_engine/cluster_create_cli.adoc
> +When creating a cluster, you must clone the https://github.com/stolostron/acm-hive-openshift-releases/tree/release-2.5/clusterImageSets/fast[clusterImageSets] repository and apply it to your hub clus
Though you may have been told this is troubleshooting, I would like to stop and think for a sec, what are we troubleshooting? Troubleshooting is a way to try to fix a problem before contacting support. This is part of the process to create a cluster. We need to think how the content fits into the big picture. I think it is better inside a task as a step.

2022-06-06 23:57 UTC, ldpliu approved these changes

2022-06-07 00:03 UTC, ldpliu commented on multicluster_engine/cluster_create_cli.adoc
> +When creating a cluster, you must add your release images to the https://github.com/stolostron/acm-hive-openshift-releases/tree/release-2.5/clusterImageSets[clusterImageSets] folder in the Git reposi
it's OK for me now. Thanks.

2022-06-07 00:41 UTC, ldpliu commented on multicluster_engine/cluster_create_cli.adoc
> +When creating a cluster, you must clone the https://github.com/stolostron/acm-hive-openshift-releases/tree/release-2.5/clusterImageSets/fast[clusterImageSets] repository and apply it to your hub clus
Actually, this is an [known issue](https://github.com/stolostron/backlog/issues/22070) for mce console. So I suggest add a known issue in https://github.com/stolostron/rhacm-docs/blob/2.5_stage/multicluster_engine/console_mce.adoc

2022-06-07 01:02 UTC, swopebe commented on multicluster_engine/cluster_create_cli.adoc
> +When creating a cluster, you must clone the https://github.com/stolostron/acm-hive-openshift-releases/tree/release-2.5/clusterImageSets/fast[clusterImageSets] repository and apply it to your hub clus
What is the known issue? Normally we have a header that there is an issue:

## Cluster fails unless you clone the repo

Enter text for how to get around that...

But why can we just not add a step to clone the repo and apply it:

1. Clone repo (link)
2. Run command to apply...

2022-06-07 01:12 UTC, ldpliu commented on multicluster_engine/cluster_create_cli.adoc
> +When creating a cluster, you must clone the https://github.com/stolostron/acm-hive-openshift-releases/tree/release-2.5/clusterImageSets/fast[clusterImageSets] repository and apply it to your hub clus
Normally, this should be a step to **create a cluster in mce console.**
But we have no doc about createing cluster in mce concole. and we do not know where should we put the step to .

2022-06-14 17:44 UTC, cadawson commented
I changed the presentation of the text. Hopefully, this addresses the comments. Please take a look @ldpliu and @swopebe . Thanks!

2022-06-15 00:40 UTC, ldpliu approved these changes

2022-06-22 17:29 UTC, swopebe requested changes
see issue comment

2022-06-22 17:29 UTC, swopebe commented on multicluster_engine/cluster_create_cli.adoc
> +When creating a cluster, you must clone the https://github.com/stolostron/acm-hive-openshift-releases/tree/release-2.5/clusterImageSets/fast[clusterImageSets] repository and apply it to your hub clus
@cadawson and @ldpliu that is because when this was written, **there was no console.** What I recommend if this is for MCE only is an update to this:

https://github.com/stolostron/rhacm-docs/blob/2.5_stage/multicluster_engine/cluster_create_cli.adoc

If this specific issue is for the UI only, **we can change the name of the file, drop the CLI** portion since we don't want to document the UI but we just need to add this:

**Creating a cluster in the console:**

1. You need to clone the https://github.com/stolostron/acm-hive-openshift-releases/tree/release-2.5/clusterImageSets/fast[clusterImageSets] repository.

2. Run the following to apply it to your hub cluster. 

3. Select the {ocp} release images when you create a cluster.

___________________________________
If you feel strongly about a known issue:

**Failing cluster in MCE**

You must clone the repository to create the cluster.

1. Blah

2. Blah

**(I just feel like this is necessary process and not a known issue)**

2022-06-23 03:19 UTC, ldpliu commented
@swopebe 
I am not sure which one is better. 
If we add a section `Creating a cluster in the console:` in this file, it's also confusing. The creating cluster need several steps, and this is just a pre-step for creating a cluster.
Anyway, I could provide the command for this steps:

You need to clone the [https://github.com/stolostron/acm-hive-openshift-releases/tree/release-2.5/clusterImageSets/fast [clusterImageSets]](https://github.com/stolostron/acm-hive-openshift-releases/tree/release-2.5/clusterImageSets/fast%5BclusterImageSets%5D) repository.

```
git clone git@github.com:stolostron/acm-hive-openshift-releases.git
cd acm-hive-openshift-releases
git checkout origin/release-2.5
```


    Run the following to apply it to your hub cluster.

```
oc apply -f clusterImageSets/fast/
```

    Select the {ocp} release images when you create a cluster.

2022-06-27 17:33 UTC, swopebe commented
Because this seems like a standard, traditional prereq, how a writer would treat is upon this presentation.

2022-07-05 20:35 UTC, swopebe approved these changes

2022-07-05 20:35 UTC, swopebe commented
@cadawson please see where I added that section

2022-07-05 22:40 UTC, merged