Add Submariner known issues
open-cluster-management/rhacm-docs pull request #3602
Opened 2022-06-14 19:57 UTC by dfarrell07

Signed-off-by: Daniel Farrell <dfarrell@redhat.com>

2022-06-14 19:58 UTC, dfarrell07 commented
/cc @cadawson @tpantelis @aswinsuryan

2022-06-14 20:31 UTC, aswinsuryan approved these changes

2022-06-15 03:02 UTC, sridhargaddam commented on release_notes/known_issues.adoc
> +Not all infrastructure providers ACM can manage are supported with Submariner. Please refer to the support matrix page for more details.
```suggestion
Not all infrastructure providers ACM can manage are supported with Submariner. Please refer to the [support matrix](link to support matrix page) page for more details.
```

Might be good to link the support matrix page.

2022-06-15 03:07 UTC, sridhargaddam commented on release_notes/known_issues.adoc
> +When using Headless Services with Globalnet, DNS resolution for local pods doesn’t work correctly.
```suggestion
When using Headless Services with Globalnet, DNS resolution for local pods doesn’t work correctly when using clusterset.local domain name.
```

2022-06-15 09:34 UTC, nyechiel commented on release_notes/known_issues.adoc
> +Not all infrastructure providers ACM can manage are supported with Submariner. Please refer to the support matrix page for more details.
Not sure what we do in other instances across the docs, but note that the support matrix page is going to change with each ACM version. So if we link the 2.5 matrix here, we also need to ensure we update the URL with each new ACM version. Unless we have a way to automate this, maybe it's better not to link for now?

2022-06-15 09:35 UTC, nyechiel commented
The content seems accurate to me, but we need a tech writer to review and edit for style and consistency, etc.

2022-06-15 10:43 UTC, sridhargaddam commented on release_notes/known_issues.adoc
> +Not all infrastructure providers ACM can manage are supported with Submariner. Please refer to the support matrix page for more details.
Okay in that case, agree we can leave it in the current state.

2022-06-15 11:56 UTC, cadawson requested changes
Thanks. I made some minor edits that should not have changed the technical meaning, but made it more consistent with our docs. Please take a look and make sure that it looks ok. 
Thanks!

2022-06-15 12:02 UTC, cadawson commented
I went ahead and added the link to the support matrix for convenience. It looks like we mention in the Submariner section of the docs which environments are supported for using Submariner at: https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.5/html/add-ons/add-ons-overview#submariner. Do we need this additional known issue to mention it? Thanks. @dfarrell07

2022-06-15 12:51 UTC, nyechiel commented
> I went ahead and added the link to the support matrix for convenience. It looks like we mention in the Submariner section of the docs which environments are supported for using Submariner at: https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.5/html/add-ons/add-ons-overview#submariner. Do we need this additional known issue to mention it? Thanks. @dfarrell07

IMO it's better to have this mentioned here as well.

2022-06-15 12:51 UTC, cadawson commented on release_notes/known_issues.adoc
> +Not all infrastructure providers ACM can manage are supported with Submariner. Please refer to the support matrix page for more details.
Added the link, for convenience. Question added to the comments.

2022-06-15 12:52 UTC, cadawson commented on release_notes/known_issues.adoc
> +When using Headless Services with Globalnet, DNS resolution for local pods doesn’t work correctly.
Made this change manually in the doc, so I covered the edits, as well.

2022-06-15 14:26 UTC, dfarrell07 commented
These edits look great to me, thanks @cadawson! Tangentially, I think this PR is a perfect example of how the process should work: dev write content they are expert in, docs writer makes it RH-style-compliant.

2022-06-15 15:23 UTC, sridhargaddam commented
/lgtm

2022-06-15 15:45 UTC, cadawson commented
Thanks all! I think this worked well, too. Time to start looking at the automation!

2022-06-15 15:46 UTC, cadawson approved these changes
Looks good! Thanks!

2022-06-15 15:46 UTC, merged

2022-06-15 15:48 UTC, cadawson commented
Issue #23508 created for this.