Update azure documentation
open-cluster-management/rhacm-docs pull request #3611
Opened 2022-06-15 18:41 UTC by aswinsuryan

* Changed steps to use a public IP for gateway node instead of reusing existing loadbalancer.
* Added steps to open all the ports required by submariner

2022-06-15 18:58 UTC, dfarrell07 commented
You can add `Closes stolostron/backlog#23540` if you'd like @aswinsuryan.

2022-06-20 06:50 UTC, sridhargaddam requested changes

2022-06-20 06:50 UTC, sridhargaddam commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +. Tag a node as a gateway node.
For all the other cloud providers with ACM, we are recommending a dedicated GW node. Should we do the same even for Azure?

2022-06-20 06:50 UTC, sridhargaddam commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +az network nsg create --name <gw-nsg-name> --resource-group <rescource group>
```suggestion
az network nsg create --name <gw-nsg-name> --resource-group <res-group>
```

Lets try to use the same names for readability.

2022-06-20 06:50 UTC, sridhargaddam commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +. Create network security groups rules on your Azure to open NAT traversal ports (by default 4500/UDP) Nat discovery port (by default 4490/UDP) and metrics port (by default 8080/TCP) for Submariner.
```suggestion
. Create network security groups rules on your Azure to open Tunnel port (by default 4500/UDP), NAT discovery port (by default 4490/UDP) and metrics port (by default 8080/TCP and 8081/TCP) for Submariner. This needs to be created in both inbound and outbound directions for each of the ports.
```

2022-06-20 06:50 UTC, sridhargaddam commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +--protocol <Protocol> --destination-port-ranges <ipsec-port>
```suggestion
--protocol udp --destination-port-ranges <vxlan-port>
```

Just like how we are using proper values for direction and some of the other fields, I feel we can use the protocol values which do not change in our examples.

2022-06-20 06:50 UTC, sridhargaddam commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +--protocol <Protocol> --destination-port-ranges <ipsec-port>
Same as above.

2022-06-20 06:50 UTC, sridhargaddam commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +az network nic ip-config update --name <name>  --nic-name <gw-vm-nic> --resource-group <res-group>  --public-ip-address <public-ip-name>
It would be good to provide some brief description below all the commands to explain about the argument that needs to be supplied as part of the command.

2022-06-24 20:49 UTC, aswinsuryan commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +. Tag a node as a gateway node.
This is a temporary solution for trying in tech preview , isn't creating machine set complicated ?

2022-06-24 21:01 UTC, aswinsuryan commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +az network nic ip-config update --name <name>  --nic-name <gw-vm-nic> --resource-group <res-group>  --public-ip-address <public-ip-name>
Give description for arguments that needs explanation.

2022-06-24 21:03 UTC, aswinsuryan commented
/Closes stolostron/backlog#23540

2022-07-05 11:50 UTC, cadawson commented
Can you review this again @sridhargaddam? This one should be ready to go, I hope. Thanks!

2022-07-06 02:44 UTC, aswinsuryan commented
/approve

2022-07-07 07:37 UTC, sridhargaddam commented
/lgtm
/approve

2022-07-07 13:23 UTC, dockerymick commented
Added myself as a reviewer based on request from @cadawson

2022-07-07 13:24 UTC, dockerymick approved these changes
This looks good! I also checked links which are all working, thanks for the changes

2022-07-07 14:28 UTC, merged