stolostron/backlog#23648--numerous known issues and task entry for ba…
open-cluster-management/rhacm-docs pull request #3634
Opened 2022-06-28 12:59 UTC by swopebe

…re metal

2022-06-28 17:44 UTC, swopebe commented on clusters/create_bare.adoc
> +When you create a cluster, note that the creation process uses the {ocp-short} installer with the Hive resource. If you have questions about cluster creation after completing this procedure, see http
dangling modifier here...will refresh the doc team with what that means. @cadawson

2022-06-29 21:19 UTC, KevinFCormier requested changes
A couple things to consider

2022-06-29 21:19 UTC, KevinFCormier commented on clusters/create_vm.adoc
> +
@swopebe Why is this one listed both in the known issues and under the related topic, but not the other 2? I'm just wondering if it will be difficult to remember to remove this note when it gets fixed.

2022-06-29 21:19 UTC, KevinFCormier commented on release_notes/known_issues.adoc
> +When creating a cluster by using the VMware vSphere or Red Hat OpenStack Platform providers and disconnected installation, if a certificate is required to access the mirror registry, you must enter i
I think it's important to distinguish between bare metal and VMware / OpenStack for this sentence: "You cannot enter them in the cluster create console editor." 

For bare metal, there is literally no place to do so. For the others, you can enter them, but they will be not be used.

2022-06-30 16:04 UTC, swopebe commented on clusters/create_vm.adoc
> +
When something is required, it really should be listed in the task. A known issue is something the user may come across. We can remove if you think it is temporary enough. @KevinFCormier Does the user need this in the task?

2022-06-30 18:07 UTC, KevinFCormier commented on clusters/create_vm.adoc
> +
I added a note to the original defect to have this removed when it is fixed. It is important, so it's fine to include it here. I just didn't want to lose track of it.

2022-06-30 20:34 UTC, KevinFCormier approved these changes

2022-06-30 20:36 UTC, merged