Adding known issue for insight-client
open-cluster-management/rhacm-docs pull request #3654
Opened 2022-07-01 17:12 UTC by dockerymick

https://app.zenhub.com/workspaces/engineering-backlog-do-not-delete-604fab62d4b98d00150a2854/issues/stolostron/backlog/21763

2022-07-07 19:39 UTC, willkutler requested changes

2022-07-07 19:39 UTC, willkutler commented on release_notes/known_issues.adoc
> +When the cluster ID is missing for a newly added managed cluster, the `insight-client` pod does not enlist Kubernetes clusters. Restart the `insight-client` pod by deleting the pod with the following
I actually don't think you need to mention cluster ID here since that variable name is more specific to the code. You could replace this with something like `When a new managed cluster that the insights-client cannot get CCX insights for is added, policy violations on that new cluster will not show up in the policyReport until the insights-client pod is restarted.`

2022-07-07 19:39 UTC, willkutler commented on release_notes/known_issues.adoc
> +oc delete po -n open-cluster-management insight-client
I think this should be oc delete **pod** -n open-cluster-management insight-client

2022-07-07 19:39 UTC, willkutler commented
Thanks! just added a few minor comments

2022-07-07 19:41 UTC, willkutler commented on release_notes/known_issues.adoc
> +oc delete po -n open-cluster-management insight-client
actually, that isn't the right command either. I'll add a comment with the correct one

2022-07-07 19:50 UTC, willkutler commented on release_notes/known_issues.adoc
> +oc delete po -n open-cluster-management insight-client
`oc get pods -n open-cluster-management --no-headers=true | awk '/insights-client/{print $1}'| xargs  oc delete -n open-cluster-management pod` use this one @dockerymick

2022-07-08 14:34 UTC, dockerymick commented
Thanks so much Will! @willkutler I'll make changes based on your comments shortly

2022-07-11 20:32 UTC, oafischer reviewed
Just saw some small typos that I left a comment for, looks good otherwise!

2022-07-11 20:32 UTC, oafischer commented on release_notes/known_issues.adoc
> +When there is a new managed cluster where the `insight-client` pod cannot retrieve CCX insights, policy violations for the new maaged cluster are not displayed in the policy report. CCX insight polic
Small typos: maaged -> managed; cluster -> clusters

2022-07-12 14:58 UTC, dockerymick commented on release_notes/known_issues.adoc
> +When there is a new managed cluster where the `insight-client` pod cannot retrieve CCX insights, policy violations for the new maaged cluster are not displayed in the policy report. CCX insight polic
Thanks! My `n` key is a little jammed lolol Will make this update soon!

2022-07-13 02:27 UTC, dockerymick commented
@willkutler @oafischer thank you both for your reviews. I have made the updates. When either of you have an opportunity, will you re-review this PR

2022-07-13 15:09 UTC, oafischer approved these changes
Looks good, thanks for taking this issue!

2022-07-14 13:38 UTC, xrajesh commented
@willkutler We fixed the issue in the 2.4 z stream . here ->https://github.com/stolostron/insights-client/pull/105

If its fixed do we want to add this doc?  @dockerymick

2022-07-14 15:00 UTC, dockerymick commented
@xrajesh if it is already fixed, it is not necessary to doc this known issue. I took a look at the [latest doc Errata](https://github.com/stolostron/rhacm-docs/blob/2.4_stage/release_notes/errata.adoc#errata-245) to check if anything was mentioned there. Should there be mentions of the fix for `insights-client`. 


If all is well and it is agreed that this known issue doesn't need to be documented, we can close this PR and the issue

2022-07-14 17:12 UTC, willkutler approved these changes

2022-07-19 13:50 UTC, dockerymick commented
Again, thank you all (@oafischer, @willkutler, and @xrajesh) for your reviews and confirmations. Based on the most recent [comment](https://github.com/stolostron/backlog/issues/21763#issuecomment-1186389995) from Xavier, I am going to close this PR and then close the issue. This was fixed in 2.4.5.

2022-07-19 13:50 UTC, closed without merging