stolostron#18194 rem intuit clust create
open-cluster-management/rhacm-docs pull request #3675
Opened 2022-07-07 20:07 UTC by cadawson

2022-07-13 03:23 UTC, ldpliu commented
/approve

2022-07-13 03:23 UTC, ldpliu approved these changes

2022-07-15 15:46 UTC, swopebe commented on clusters/create_azure.adoc
> +*Tip:* You can view the `YAML` content updates as you enter the information in the console by setting the _YAML_ switch to *ON*.
I thought we agreed as a team what tags to use and *Tip* is not one of them? I raised this issue after seeing only cluster/install at the time using these tags a few releases ago, this is still the case BTW. Please check the _larger doc_ and let's all move as a **team** on content standards--one voice. We agreed on Note and Information to cut down on various tag usage that is unnecessary since the move from DITA.

2022-07-15 15:47 UTC, swopebe commented on clusters/create_azure.adoc
> +* Region (optional): Where you want to run your node pools. You can select multiple zones within the region for a more distributed group of control plane nodes. A closer zone might provide faster per
First line is not a complete sentence, consider merging.

2022-07-15 15:47 UTC, swopebe commented on clusters/create_azure.adoc
> +* Region (optional): Where you want to run your node pools. You can select multiple zones within the region for a more distributed group of control plane nodes. A closer zone might provide faster per
Optional was also an agreed upon special tag, I think?

2022-07-15 15:48 UTC, swopebe commented on clusters/create_azure.adoc
> +When you review your information and optionally customize it before creating the cluster, you can click the *YAML* slider to *On* to view the `install-config.yaml` file content in the panel. You can
Please do not bold this entire line, big accessibility issue. Bold for clickable items but not emphasis.

2022-07-15 15:49 UTC, swopebe commented on clusters/create_azure.adoc
> +When you review your information and optionally customize it before creating the cluster, you can click the *YAML* slider to *On* to view the `install-config.yaml` file content in the panel. You can
(line 80 and 82)

2022-07-15 15:49 UTC, swopebe requested changes
Please see a few comments. A couple for quick discussion and some necessary recommendations for change.

2022-07-15 19:09 UTC, cadawson commented on clusters/create_azure.adoc
> +* Region (optional): Where you want to run your node pools. You can select multiple zones within the region for a more distributed group of control plane nodes. A closer zone might provide faster per
Correct. Optional was one, as well.

2022-07-15 19:29 UTC, cadawson commented on clusters/create_azure.adoc
> +*Tip:* You can view the `YAML` content updates as you enter the information in the console by setting the _YAML_ switch to *ON*.
Tip was one of them. https://github.com/stolostron/rhacm-docs/blob/gh-pages/_pages/team_writing_guidance.md.

2022-07-15 19:33 UTC, cadawson commented on clusters/create_azure.adoc
> +When you review your information and optionally customize it before creating the cluster, you can click the *YAML* slider to *On* to view the `install-config.yaml` file content in the panel. You can
This doesn't look like it is all bold. It looks bold above, but not in the built content. Not sure what is happening there.

2022-07-15 19:34 UTC, cadawson commented
Thanks for the review @swopebe !

2022-07-15 19:45 UTC, cadawson commented on clusters/create_azure.adoc
> +* Region (optional): Where you want to run your node pools. You can select multiple zones within the region for a more distributed group of control plane nodes. A closer zone might provide faster per
Updated the text in the items. Thank you!

2022-07-15 22:00 UTC, KevinFCormier commented
@Randy424 Would you mind taking a pass over this on Monday?

2022-07-16 00:55 UTC, swopebe commented on clusters/create_azure.adoc
> +
Changed to complete sentences and merged lines where links are--this is also done later in the topic so it is only following consistency within the same file. No reason to set those links off with a +.

2022-07-16 01:00 UTC, swopebe commented on clusters/create_azure.adoc
> +
I have no preference, just ask that the files be consistent with:

1. Complete sentences with subject, predicate, punctuation
2. Phrases

2022-07-16 01:01 UTC, swopebe commented on clusters/create_azure.adoc
> +When you review your information and optionally customize it before creating the cluster, you can click the *YAML* slider to *On* to view the `install-config.yaml` file content in the panel. You can
It's important to have clean code, so I will examine the cause so we don't have bold here.

2022-07-16 01:10 UTC, swopebe commented on clusters/create_azure.adoc
> +Continue with xref:../clusters/access_cluster.adoc#accessing-your-cluster[Accessing your cluster] for instructions for accessing your cluster.
As mentioned in meetings,  "Your X is Z" for our validation step is not true validation. I added validation step to the template for developers to give the customer a way of ensuring their procedure worked. It is not fair to the customer for us to assume that it did.

Think <step-result> from DITA days--this is what it did for the user. It is usually _You see X displayed..._ or _Run the following command to check..._. (Something like that.)

It feels a bit unethical to me to tell the user their cluster is created without actually knowing that it is. If they cannot see it in the console or run a command (you can test this), then we should probably leave that out. It's a lot like pre-announcing something. This is seeping into our doc, I have noticed. Asking that we remove these and avoid them in the future.

2022-07-16 01:17 UTC, swopebe commented on clusters/create_azure.adoc
> +When you review your information and optionally customize it before creating the cluster, you can click the *YAML* slider to *On* to view the `install-config.yaml` file content in the panel. You can
@cadawson the extra bolded lines went away when I built the note: **Note:** I notice our doc is all over the place (clearly why we need peer reviews) with how we build this:

I see:

*Note*:
**Note**:
*Note:*
**Note:**

(the colon should go inside the tag, of course) 

As a team we need to get on the same page for special tagging.

2022-07-16 01:21 UTC, swopebe commented on clusters/create_bare.adoc
>  Your cluster is created. Continue with xref:../clusters/access_cluster.adoc#accessing-your-cluster[Accessing your cluster] for instructions for accessing your cluster.
Please remove all these _Your cluster is created._

2022-07-16 01:21 UTC, swopebe commented on clusters/create_azure.adoc
> +When you review your information and optionally customize it before creating the cluster, you can click the *YAML* slider to *On* to view the `install-config.yaml` file content in the panel. You can
This went away when I changed the code, not sure if that is causing it.

2022-07-16 01:29 UTC, swopebe commented on clusters/create_ocp_aws.adoc
@cadawson the problem in your code here is the (*) -- this says BOLD in the code. If you are going to use this, try `*` so it doesn't send all the text after it into bold text. I tested this in one file and it worked. The others need the same.

Additionally, I simplified the YAML on text, which is consistent with other doc. The concise way: You can select *YAML: On*.

2022-07-16 01:30 UTC, swopebe commented on clusters/create_openstack.adoc
Same here

2022-07-16 01:39 UTC, swopebe commented on clusters/create_azure.adoc
> +
This is not consistent with the other lines you have about YAML. Let's make them consistent. It takes just a minute to examine the rest of the section. 

 Click the *YAML* slider to *On* (is how you wrote it elsewhere in this section), with YAML bold, and here you have it in italics. Since it is the same section, it's best to present it the same way for good UX.

2022-07-16 01:41 UTC, swopebe commented on clusters/create_cluster_on_prem.adoc
> +* _API VIP_: Specifies the IP address to use for internal API communication.
Why are these italics?

2022-07-16 01:47 UTC, swopebe commented on clusters/create_ocp_aws.adoc
Resolved across the branch.

2022-07-16 01:47 UTC, swopebe commented on clusters/create_openstack.adoc
resolved

2022-07-18 17:21 UTC, cadawson commented on clusters/create_ocp_aws.adoc
Thanks. I'm fine with the change, if that works.

2022-07-18 17:21 UTC, cadawson commented on clusters/create_openstack.adoc
Thanks. I'm fine with the change, if that works.

2022-07-18 18:58 UTC, swopebe commented on clusters/create_openstack.adoc
this change is inline with writing code references in technical doc. Use code blocks to reference code.

2022-07-18 19:01 UTC, swopebe commented on clusters/create_azure.adoc
> +*Tip:* You can view the `YAML` content updates as you enter the information in the console by setting the _YAML_ switch to *ON*.
Ok, I was looking for that. Since this is in the console, I don't write this as a tip. I write it in the actual task in the app area. I want to see what Observability does so that we are doing the same thing. Your section is the only one using tip for this and I am not sure it is a Tip. Either way, we should create one voice.

2022-07-18 19:02 UTC, swopebe commented on clusters/create_azure.adoc
> +* Region (optional): Where you want to run your node pools. You can select multiple zones within the region for a more distributed group of control plane nodes. A closer zone might provide faster per
Ok, so are you using **Optional:** like the guidance or (optional). I would just like it to be the same across the doc. It's different here. We can do either but the special tagging guidance is the first option.

2022-07-18 19:04 UTC, swopebe approved these changes
Approving though we need to revisit: Tagging, use of tip for a console editor in one book and not others, Note building, Verification step (removing them but also what they usually look like (<step_result>), concise YAML ON display, how to build lists.

2022-07-19 07:05 UTC, Randy424 approved these changes
/lgtm
Was a tedious review, awesome work

2022-07-19 12:22 UTC, cadawson commented on clusters/create_cluster_on_prem.adoc
> +* _API VIP_: Specifies the IP address to use for internal API communication.
Field names, but removed italics.

2022-07-19 17:58 UTC, swopebe commented on clusters/create_cluster_on_prem.adoc
> +* _API VIP_: Specifies the IP address to use for internal API communication.
If they have to enter a field name, then that makes sense. However, this is not consistent across the files @cadawson. I would rather we do that same thing across the files and not highlight, than to only highlight some. @cadawson 

"It's OK to be wrong if you are wrong everywhere" (I have shared my writing professors had this philosophy.)

2022-07-20 17:20 UTC, merged