stolostron/backlog#22884 cross arch rel img
open-cluster-management/rhacm-docs pull request #3682
Opened 2022-07-08 21:21 UTC by cadawson

2022-07-11 22:37 UTC, berenss approved these changes

2022-07-12 02:06 UTC, Randy424 approved these changes
/lgtm

2022-07-12 19:12 UTC, dockerymick requested changes
Made a few suggestions

2022-07-12 19:12 UTC, dockerymick commented on clusters/release_images.adoc
> +.. Pull the manifest lists for both architectures in your environment from the https://quay.io/repository/openshift-release-dev/ocp-release?tab=tags[Quay repository] using the following example comma
I usually add `link:` in front of the url, but either way is fine.

2022-07-12 19:12 UTC, dockerymick commented on clusters/release_images.adoc
> +$ podman login <private-repo>
I mentioned to Oliver that the `$` before the command. I mentioned that we should mention this during the doc architect call

2022-07-12 19:12 UTC, dockerymick commented on clusters/release_images.adoc
> +.. Create a `YAML` file that contains information that is similar to the following example:
remove the monospace from YAML. If you plan to use the monospace when YAML is mentioned as a file extension: `.yaml`

2022-07-12 19:12 UTC, dockerymick commented on clusters/release_images.adoc
> +Replace `file-name` with the name of the `YAML` file that you just created.
Same suggestion

2022-07-13 15:16 UTC, cadawson commented on clusters/release_images.adoc
> +.. Pull the manifest lists for both architectures in your environment from the https://quay.io/repository/openshift-release-dev/ocp-release?tab=tags[Quay repository] using the following example comma
Thanks. I thought that we came to the conclusion during a meeting that we will leave "link" on the ones that exist, but moving forward, we would not use link. Both work, but let me know if that is wrong for the sake of consistency.

2022-07-13 15:17 UTC, cadawson commented on clusters/release_images.adoc
> +$ podman login <private-repo>
I normally don't leave it. I can remove it from here. Thanks!

2022-07-13 15:22 UTC, cadawson commented on clusters/release_images.adoc
> +.. Create a `YAML` file that contains information that is similar to the following example:
Updated

2022-07-13 15:22 UTC, cadawson commented on clusters/release_images.adoc
> +Replace `file-name` with the name of the `YAML` file that you just created.
Updated. Thanks!

2022-07-13 15:39 UTC, dockerymick commented on clusters/release_images.adoc
> +.. Pull the manifest lists for both architectures in your environment from the https://quay.io/repository/openshift-release-dev/ocp-release?tab=tags[Quay repository] using the following example comma
That's cool with me!

2022-07-13 15:41 UTC, dockerymick approved these changes
Thanks for accepting my suggestion Chris! Approving

2022-07-18 14:44 UTC, merged