Clarify headless service use-case with Globalnet
open-cluster-management/rhacm-docs pull request #3683
Opened 2022-07-11 11:05 UTC by sridhargaddam

Signed-off-by: Sridhar Gaddam <sgaddam@redhat.com>

2022-07-11 14:54 UTC, swopebe commented
please assign a reviewer and link the issue so that we know what we are adding to the documentation. This will be slated for next Sprint.

2022-07-11 18:21 UTC, dfarrell07 commented
/cc @cadawson

2022-07-11 18:32 UTC, dfarrell07 approved these changes
This is the result of a report by a user here: https://app.slack.com/client/T027F3GAJ/C0134E73VH6/thread/C0134E73VH6-1656396243.142199

Doesn't the change itself, written by the main SME, capture what we're adding the documentation? Wouldn't it be a better use of our time to just review it for docs style and get it merged, shipped, and to the customers who are stumbling on this?

2022-07-11 18:44 UTC, dfarrell07 commented
Issue: https://github.com/stolostron/backlog/issues/24159

2022-07-12 05:29 UTC, sridhargaddam commented
Thanks for reporting the issue @dfarrell07

2022-07-13 08:55 UTC, vthapar approved these changes

2022-07-14 15:27 UTC, swopebe requested changes
see changes and comment

2022-07-14 15:27 UTC, swopebe commented on release_notes/known_issues.adoc
> +
Please see that I changed to **active voice** (industry standards) and **removed preannounce** to fix (industry standard). One more change that I was not sure about and need to clear up (because we have to be as clear as possible):

...in the same cluster **that uses the** `clusterset.local` domain name?

...in the same cluster **by using** `clusterset.local` domain name?

It can be read both ways, which is why I am calling for an edit here. I think you are saying the first option, let me know.

2022-07-14 15:51 UTC, dfarrell07 commented on release_notes/known_issues.adoc
> +
It's the second. The idea is that `app0.clusterset.local` will always resolve as a global IP, including from the cluster that hosts `app0`. That global IP will not be routable in the host cluster.

I'd suggest:

> ...in the same cluster __by using a__ `clusterset.local` domain name

2022-07-15 05:29 UTC, sridhargaddam commented on release_notes/known_issues.adoc
> +
As @dfarrell07 mentioned, its the second option.

2022-07-16 00:35 UTC, swopebe approved these changes

2022-07-16 00:41 UTC, swopebe commented on release_notes/known_issues.adoc
> +
asked for peer review, but taking a while. Merging.

2022-07-16 00:43 UTC, merged