Add new known issue in 2.5
open-cluster-management/rhacm-docs pull request #3684
Opened 2022-07-11 14:47 UTC by oafischer

https://github.com/stolostron/backlog/issues/22760#issue-1248630248

2022-07-11 14:53 UTC, swopebe commented on release_notes/known_issues.adoc
> +When you create ApplicationSet applications that deploy resources to a different namespace than the namespace defined in the ApplicationSet YAML, the resource status does not appear in the topology.
@dockerymick can you show where we use `these` for component names?

2022-07-11 16:15 UTC, dockerymick commented on release_notes/known_issues.adoc
> +When you create ApplicationSet applications that deploy resources to a different namespace than the namespace defined in the ApplicationSet YAML, the resource status does not appear in the topology.
@swopebe I'm not sure what component names you're referring to

2022-07-11 16:16 UTC, dockerymick requested changes

2022-07-11 16:16 UTC, dockerymick commented on release_notes/known_issues.adoc
> +When you create ApplicationSet applications that deploy resources to a different namespace than the namespace defined in the ApplicationSet YAML, the resource status does not appear in the topology.
Change:

When you create ApplicationSet applications that deploy resources to a different namespace than the namespace defined in the ApplicationSet YAML, the resource status does not appear in the topology.

TO

When you create `ApplicationSet` applications that deploy resources to a different namespace than the namespace defined in the `ApplicationSet` YAML, the resource status does not appear in the topology.

monospace the application names of the resources/files

2022-07-11 17:14 UTC, oafischer commented on release_notes/known_issues.adoc
> +When you create ApplicationSet applications that deploy resources to a different namespace than the namespace defined in the ApplicationSet YAML, the resource status does not appear in the topology.
Thanks for the clarifying. Also changed YAML because I saw it is monospaced in other areas of the documentation as well.

2022-07-12 14:28 UTC, dockerymick commented on release_notes/known_issues.adoc
> +When you create ApplicationSet applications that deploy resources to a different namespace than the namespace defined in the ApplicationSet YAML, the resource status does not appear in the topology.
When YAML is mentioned in all capitals, you shouldn't monospace it because it's the name of the programming language. However, when it is lowercase and mentioned as a file extension, it should be doc'ed as `.yaml`. 

Another great topic to bring up during our doc arch call. Let's add it to the agenda when we have a chance

2022-07-12 15:05 UTC, oafischer commented on release_notes/known_issues.adoc
> +When you create ApplicationSet applications that deploy resources to a different namespace than the namespace defined in the ApplicationSet YAML, the resource status does not appear in the topology.
Thanks for clarifying! Yeah let's definitely talk about it during our call so I can get up to speed on these things.

2022-07-12 19:20 UTC, dockerymick approved these changes
Looks good!

2022-07-12 19:22 UTC, merged

2022-07-12 19:23 UTC, swopebe commented
@dockerymick we did discuss this in an arch call a few releases ago and decided to handle them as such:

`ApplicationSet` unless we are talking about something generic like "application set" (as in a set of applications).

..outside of a title, which can cause build issues maybe?


We definitely have voted on this in the past.