stolostron/backlog#23648 mod sno create
open-cluster-management/rhacm-docs pull request #3688
Opened 2022-07-11 16:21 UTC by cadawson

2022-07-11 21:23 UTC, berenss approved these changes
Suggest we include review from a member of the Central Infrastructure Management team, perhaps @filanov or Avishay Traeger

2022-07-11 21:23 UTC, berenss commented on clusters/single_node_openshift.adoc
It stood out to me that, within the stream of text that describes SNO, we pivot and talk about a "standard cluster"

> In a standard cluster, there are control plane nodes and separate worker nodes.

Perhaps it would be better to state:
> The single node cluster is used for both the control plane services as well as user workloads.

2022-07-11 21:23 UTC, berenss commented on clusters/single_node_openshift.adoc
> +Complete the steps in the {product-title-short} console for creating a cluster in the bare metal environment. Because the bare metal assets feature is deprecated, it is best practice to use the Centr
I would suggest we leave out the:

> Because the bare metal assets feature is deprecated,

as it will potentially become something we need to come back to in the future and remove it (when indeed it gets pulled out of the code)

2022-07-12 14:17 UTC, cadawson commented on clusters/single_node_openshift.adoc
I see your point. I reworded a little to avoid this.

2022-07-12 14:19 UTC, cadawson commented on clusters/single_node_openshift.adoc
> +Complete the steps in the {product-title-short} console for creating a cluster in the bare metal environment. Because the bare metal assets feature is deprecated, it is best practice to use the Centr
I prefer your idea, as I thought the same way. I thought it would be better to lead them over during the transition, but I agree that it is somewhere that we can miss and update. I removed it. Thanks!

2022-07-12 15:15 UTC, berenss commented on clusters/single_node_openshift.adoc
>  ----
@filanov @jelkosz please review lines above to ensure technically accurate for CIM SNO flow. thx!

2022-07-12 15:29 UTC, filanov commented on clusters/single_node_openshift.adoc
Why only bare metal? vm can be an sno as well

2022-07-12 15:38 UTC, berenss commented on clusters/single_node_openshift.adoc
I see your point - the OCP doc seems updated now, to reflect it with OCP 4.10:
https://docs.openshift.com/container-platform/4.10/installing/installing_sno/install-sno-preparing-to-install-sno.html

> Supported platforms: Installing OpenShift Container Platform on a single node is supported on bare metal, vSphere, Red Hat OpenStack, and Red Hat Virtualization platforms. In all cases, you must specify the platform.none: {} parameter in the install-config.yaml configuration file.

2022-07-12 16:04 UTC, avishayt commented on clusters/single_node_openshift.adoc
> +In a bare metal environment, you can create a single node OpenShift (SNO) cluster. A SNO cluster contains only a single node, which serves as the control plane node and the user workloads. This confi
> A SNO cluster contains only a single node, which serves as the control plane node and the user workloads.
The wording is confusing here - to me, it reads that the node serves as the user workloads.  Maybe "which hosts the control plane and user workloads"?

2022-07-12 16:04 UTC, avishayt commented on clusters/single_node_openshift.adoc
> +In a bare metal environment, you can create a single node OpenShift (SNO) cluster. A SNO cluster contains only a single node, which serves as the control plane node and the user workloads. This confi
> This configuration can be helpful when you have many clusters that need to minimize their resource footprint.

Why many clusters?  It can be helpful when you have even one cluster that requires a small resource footprint.

2022-07-12 16:04 UTC, avishayt commented on clusters/single_node_openshift.adoc
> +* Credentials for accessing the bare metal server where you want your SNO cluster.
Same note as above about bare-metal focus.  Also, CIM doesn't require credentials for the servers as long as the user can boot the server with the discovery image.

2022-07-12 16:04 UTC, avishayt commented on clusters/single_node_openshift.adoc
> +Complete the steps in the {product-title-short} console for creating a cluster in the bare metal environment. It is best practice to use the Central Infrastructure Management method of creating a SNO
Seems weird to contrast an SNO cluster with an on-premises cluster, because SNO is on-prem in this case as well.

2022-07-12 16:35 UTC, berenss commented on clusters/single_node_openshift.adoc
> +In a bare metal environment, you can create a single node OpenShift (SNO) cluster. A SNO cluster contains only a single node, which serves as the control plane node and the user workloads. This confi
Agree with your rewrite, as it captures our intent: 
"which hosts the control plane services and also the user workloads"

2022-07-12 16:36 UTC, berenss commented on clusters/single_node_openshift.adoc
> +In a bare metal environment, you can create a single node OpenShift (SNO) cluster. A SNO cluster contains only a single node, which serves as the control plane node and the user workloads. This confi
agree - strikeout 'many' and we should be good.

2022-07-12 16:39 UTC, berenss commented on clusters/single_node_openshift.adoc
> +* Credentials for accessing the bare metal server where you want your SNO cluster.
Agree. perhaps all we need here then, is a reminder to define the On-Premises credential: https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.5/html/credentials/credentials#creating-a-credential-for-an-on-premises-environment

2022-07-12 16:40 UTC, berenss commented on clusters/single_node_openshift.adoc
> +Complete the steps in the {product-title-short} console for creating a cluster in the bare metal environment. It is best practice to use the Central Infrastructure Management method of creating a SNO
It's true. a great point overall. we have 2 topics,
[1.7.9. Creating a cluster in an on-premises environment](https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.5/html/clusters/managing-your-clusters#creating-a-cluster-on-premises)

[1.7.10. Creating a single node OpenShift cluster](https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.5/html/clusters/managing-your-clusters#single-node-openshift)

but ultimately, I'm not sure why. Perhaps the only need we have is to update 1.7.9 with a short message about how to deploy the SNO, which is to ensure the release image >=4.9 and check the box.

2022-07-22 13:30 UTC, dockerymick requested changes

2022-07-22 13:30 UTC, dockerymick commented on clusters/single_node_openshift.adoc
> +* Credentials for accessing the where you want your SNO cluster.
Credentials for accessing the provider where you want your SNO cluster.

2022-07-22 13:30 UTC, dockerymick commented on clusters/single_node_openshift.adoc
> +* An On-Premises credential defined and available to select when you create the cluster. See link:../credentials/credential_on_prem.adoc##creating-a-credential-for-an-on-premises-environment[Creating
An on-premises credential that is defined and available to select when you create the cluster. 

Remove the extra hashtag the comes before the anchor name 

change `##creating` to `#creating`

2022-07-22 13:30 UTC, dockerymick commented on clusters/single_node_openshift.adoc
>  = Creating a single node OpenShift cluster
Later in the doc, you write out single node OpenShift cluster as _Single-Node OpenShift cluster_

I took a look at OpenShift docs and they doc it as : `single-node OpenShift cluster`. I do not see the abbreviation used at all in their doc

To be consistent with OCP doc, I recommend updating the title from `Creating single node OpenShift cluster` to `Creating single-node OpenShift cluster`

2022-07-22 13:30 UTC, dockerymick commented on clusters/single_node_openshift.adoc
> +On VMware vSphere, Red Hat OpenStack, Red Hat Virtualization Platform, and in the bare metal environment, you can create a single node OpenShift (SNO) cluster. A SNO cluster contains only a single no
I would switch the wording around a bit: 

You can create a single-node OpenShift cluster on VMware vSphere, Red Hat OpenStack, Red Hat Virtualization Platform, and in the bare metal environment. 

I suggest that we don't use SNO at all to remain consistent with OCP docs

2022-07-22 18:59 UTC, berenss commented on clusters/single_node_openshift.adoc
> +On VMware vSphere, Red Hat OpenStack, Red Hat Virtualization Platform, and in the bare metal environment, you can create a single node OpenShift (SNO) cluster. A SNO cluster contains only a single no
people will be quickly searching for the word SNO. I suggest we have it somewhere

2022-07-25 20:59 UTC, cadawson commented on clusters/single_node_openshift.adoc
>  = Creating a single node OpenShift cluster
Changed the later one. Only an interface text reference remains. Thanks!

2022-07-25 20:59 UTC, cadawson commented on clusters/single_node_openshift.adoc
> +On VMware vSphere, Red Hat OpenStack, Red Hat Virtualization Platform, and in the bare metal environment, you can create a single node OpenShift (SNO) cluster. A SNO cluster contains only a single no
SNO appears to be one of those inconsistent things. There are some uses of it in the OpenShift documentation, but I don't see many. I will define it on the first occurrence and then just use SNO. Then we have both.

2022-07-25 20:59 UTC, cadawson commented on clusters/single_node_openshift.adoc
> +* Credentials for accessing the where you want your SNO cluster.
Correct. Thanks

2022-07-26 06:48 UTC, avishayt commented on clusters/single_node_openshift.adoc
> +* Credentials for accessing the provider where you want your SNO cluster.
Why are provider credentials required?  It's none platform.

2022-07-26 15:20 UTC, berenss commented on clusters/single_node_openshift.adoc
> +* Credentials for accessing the provider where you want your SNO cluster.
Essentially it is only these things:
- pull secret
- ssh
- base domain is optional
![image](https://user-images.githubusercontent.com/20711730/181045045-c2cc993c-cd21-4b5e-9501-6e957ee61cd8.png)

In the AI SaaS those are fields that the user populates in-line as they create the cluster... in ACM, we have Credentials that are defined for all infra types, On-Premises means they will be using ACM+AI in the CIM flow.

2022-07-26 19:10 UTC, avishayt commented on clusters/single_node_openshift.adoc
> +* Credentials for accessing the provider where you want your SNO cluster.
OK, I understand.  I read "provider credentials" as vSphere credentials, for example.

2022-07-26 19:16 UTC, berenss commented
My overall comment about the SNO topic remains:
- why do we insist on keeping the single_node_openshift.adoc topic? 
- to me, SNO is just a selection on the CIM create flow, and may not need to be covered as extensively in ACM, as it is very well covered with many details in the OCP doc.

2022-07-28 17:30 UTC, dockerymick approved these changes
Made a couple of suggestions, thanks for pulling me in

2022-07-28 17:30 UTC, dockerymick commented on clusters/create_cluster_on_prem.adoc
> +It is best practice for you to use this procedure for creating a single-node OpenShift (SNO) cluster. You can create a single-node OpenShift cluster on VMware vSphere, Red Hat OpenStack, Red Hat Virt
Add a comma in the following statement: A single-node OpenShift cluster contains only a single node, which hosts the control plane services and the user workloads.

2022-07-28 17:30 UTC, dockerymick commented on clusters/create_cluster_on_prem.adoc
> +[#dynamic-metrics-for-sno]
As discussed through Slack


"I agree with your suggestion to add Dynamic metrics for SNO clusters section to the  Observing environments documentation, It might be best to add the section after this section: https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.5/html/observability/observing-environments-intro#external-metric-query "

2022-07-28 20:53 UTC, cadawson commented on clusters/create_cluster_on_prem.adoc
> +[#dynamic-metrics-for-sno]
Thanks @dockerymick. Moved to suggested location.

2022-07-28 20:57 UTC, cadawson commented
I see your point @berenss and @avishayt . It was initially created as a separate file when it was tech preview, then became dev preview. We had to do some swizzling of some content, but I think we have it straight now. Moved SNO content to on premises cluster, and shifted the SNO data information to observability. See what you think. Thanks!

2022-07-28 22:02 UTC, berenss approved these changes
I like it!

2022-07-29 00:49 UTC, dockerymick approved these changes
I updated the link for the entry in What's new. This looks good, thanks Chris!

2022-07-29 12:17 UTC, cadawson commented
@filanov : Does this look good from a CIM standpoint, now? Thanks!

2022-08-02 12:40 UTC, cadawson commented
Adding @omertuc as a reviewer for Michael Filanov.

2022-08-02 12:44 UTC, omertuc commented on clusters/create_cluster_on_prem.adoc
> +It is best practice for you to use this procedure for creating a single-node OpenShift (SNO) cluster. You can create a single-node OpenShift cluster on VMware vSphere, Red Hat OpenStack, Red Hat Virt
>You can create a single-node OpenShift cluster on VMware vSphere, Red Hat OpenStack, Red Hat Virtualization Platform, and in a bare metal environment. 

It's worth mentioning that even though you can deploy single node on all of these platforms, it will be deployed with absolutely no platform integration ("none platform")

2022-08-02 12:54 UTC, omertuc commented on clusters/single_node_openshift.adoc
> +* Credentials for accessing the provider where you want your SNO cluster.
I agree, "credentials for accessing the provider" doesn't sound right

2022-08-02 13:12 UTC, omertuc commented on clusters/create_cluster_on_prem.adoc
> +When you select an OpenShift version that is 4.9 or later, an option to select *Install single node OpenShift (SNO)* is displayed. A single-node OpenShift cluster contains a single node which hosts t
If these docs are for 2.5, it's probably worth mentioning that adding additional nodes to a single node cluster is not supported, as that is only supported starting ACM 2.6 and OCP 4.11

2022-08-02 13:13 UTC, omertuc commented on clusters/create_cluster_on_prem.adoc
> +If you want your cluster to be a single-node OpenShift cluster, select the single-node OpenShift option. If you are creating a single-node OpenShift cluster, add the `spec:skipMachinePools` parameter
>add the `spec:skipMachinePools` parameter in the YAML content with a value of `true` by completing the following steps

Which YAML is this referring to? I've never heard about such requirement. Could you give me some more details about this?

2022-08-02 13:19 UTC, omertuc commented on clusters/single_node_openshift.adoc
> -*Important:* When you create an {ocp-short} SNO cluster on GCP, you must configure more CPU and memory resources than for a standard GCP cluster. The minimum requirements for a SNO cluster on GCP is
This paragraph was deleted, but I don't see it's getting re-added anywhere?

2022-08-02 16:07 UTC, cadawson commented on clusters/single_node_openshift.adoc
> -*Important:* When you create an {ocp-short} SNO cluster on GCP, you must configure more CPU and memory resources than for a standard GCP cluster. The minimum requirements for a SNO cluster on GCP is
@omertuc GCP is not listed as one of the supported platforms. Should we add it to the list and add this note back? Thanks! Added the note back, for now.

2022-08-02 19:25 UTC, omertuc commented on clusters/single_node_openshift.adoc
> -*Important:* When you create an {ocp-short} SNO cluster on GCP, you must configure more CPU and memory resources than for a standard GCP cluster. The minimum requirements for a SNO cluster on GCP is
Oh sorry, I only skimmed the paragraph and didn't notice it was talking about GCP specifically, I thought it was talking generally about SNO's exceptional requirements.

2022-08-02 19:29 UTC, omertuc commented on clusters/single_node_openshift.adoc
> -*Important:* When you create an {ocp-short} SNO cluster on GCP, you must configure more CPU and memory resources than for a standard GCP cluster. The minimum requirements for a SNO cluster on GCP is
Still I would expect there to be a general paragraph about how a SNO control-plane node needs 4 more CPU cores than a control-plane node in a multi-node control-plane cluster (8 cores rather than 4 cores)

2022-08-02 19:30 UTC, omertuc commented on clusters/single_node_openshift.adoc
> -*Important:* When you create an {ocp-short} SNO cluster on GCP, you must configure more CPU and memory resources than for a standard GCP cluster. The minimum requirements for a SNO cluster on GCP is
Not sure where this GCP stuff came from, I've never heard of that

2022-08-03 02:51 UTC, berenss commented on clusters/single_node_openshift.adoc
>  ----
I don’t think we need this and suggest we remove it.

2022-08-03 02:54 UTC, berenss commented on clusters/single_node_openshift.adoc
> -*Important:* When you create an {ocp-short} SNO cluster on GCP, you must configure more CPU and memory resources than for a standard GCP cluster. The minimum requirements for a SNO cluster on GCP is
All of it should be removed. 

We had a dev preview flag that would allow a checkbox for SNO to be created via Hive. It was never a customer facing flag, just for internal/lab use. I think this is where the guidance of this section must have come from (engineering may have suggested it not knowing for sure that it was never intended to be customer facing)

2022-08-03 02:55 UTC, berenss commented on clusters/create_cluster_on_prem.adoc
> +If you want your cluster to be a single-node OpenShift cluster, select the single-node OpenShift option. If you are creating a single-node OpenShift cluster, add the `spec:skipMachinePools` parameter
I have no idea. Suggest we remove it.

2022-08-03 02:56 UTC, berenss commented on clusters/create_cluster_on_prem.adoc
> +It is best practice for you to use this procedure for creating a single-node OpenShift (SNO) cluster. You can create a single-node OpenShift cluster on VMware vSphere, Red Hat OpenStack, Red Hat Virt
To be explicit, `platform=none`

2022-08-04 12:31 UTC, cadawson commented on clusters/single_node_openshift.adoc
> +* Credentials for accessing the provider where you want your SNO cluster.
Changed the phrasing to make it clearly a credential.

2022-08-04 12:45 UTC, cadawson commented on clusters/single_node_openshift.adoc
> -*Important:* When you create an {ocp-short} SNO cluster on GCP, you must configure more CPU and memory resources than for a standard GCP cluster. The minimum requirements for a SNO cluster on GCP is
Removed the GCP specific note. Added the note about the additional core requirement. 
Removed the skipMachinePools steps.

2022-08-04 12:49 UTC, cadawson commented
Thanks for your input on this @omertuc . I know you were pulled in at the end of it. I addressed your comments, and I think we are ok to move forward with this. Let me know if you see any other issues or if it looks ok. Thanks!

Thanks for your input, as well @berenss . Particularly because you are out of the office.

2022-08-04 12:49 UTC, omertuc commented on clusters/create_cluster_on_prem.adoc
> +*Note:* The single-node OpenShift control plane requires 4 additional CPU cores than a control plane node requires for a multinode control plane cluster. For example, the single-node OpenShift cluste
The +4 thing is not a "rule" and is not true in general, it just currently happens to be 4 more in SNO. So perhaps change the phrasing to something like:

```suggestion
*Note:* The single-node OpenShift control plane requires 8 CPU cores as opposed to a control plane node for a multinode control plane cluster which only requires 4 CPU cores.
```

2022-08-04 12:56 UTC, cadawson commented on clusters/create_cluster_on_prem.adoc
> +*Note:* The single-node OpenShift control plane requires 4 additional CPU cores than a control plane node requires for a multinode control plane cluster. For example, the single-node OpenShift cluste
Got it. Content updated. Thanks @omertuc .

2022-08-04 12:58 UTC, omertuc commented on clusters/single_node_openshift.adoc
> +* Credentials for accessing the provider where you want your SNO cluster.
I'm confused, this comment thread and the docs it comments on seem to be mixing the concepts of "ACM credentials" and "provider credentials".

SNO doesn't need any "provider credentials", because it has no platform integration

2022-08-04 12:58 UTC, omertuc commented on clusters/single_node_openshift.adoc
> +* Credentials for accessing the provider where you want your SNO cluster.
I believe the credentials that @berenss mentioned in https://github.com/stolostron/rhacm-docs/pull/3688/files#r930100187 are the credentials this document should be documenting, not provider credentials

2022-08-04 15:03 UTC, cadawson commented on clusters/single_node_openshift.adoc
> +* Credentials for accessing the provider where you want your SNO cluster.
Hi @omertuc . You are correct. Scott is referring to the ACM credential. I removed the reference to the "provider credentials" and now have a reference to the ACM credential with a link to a topic that provides instructions about how to create one.

2022-08-04 15:05 UTC, omertuc commented on clusters/single_node_openshift.adoc
> +* Credentials for accessing the provider where you want your SNO cluster.
The line still says "Credentials **for accessing the provider** where you want your SNO cluster."

2022-08-05 18:09 UTC, merged