stolostron/backlog#23682 Add S3 credential
open-cluster-management/rhacm-docs pull request #3731
Opened 2022-07-20 15:55 UTC by cadawson

2022-07-22 13:17 UTC, dockerymick requested changes

2022-07-22 13:17 UTC, dockerymick commented on clusters/hosted_control_plane_configure.adoc
> +. Because hosted control planes is a Technology Preview feature only on AWS, create an OIDC S3 credentials secret named `hypershift-operator-oidc-provider-s3-credentials` for the HyperShift operator.
seems like the term `HyperShift operatorSave` is misplaced. Do you mean to say, "Save the HyperShift operator secret in the managed cluster namespace, which is the..."?

2022-07-25 15:26 UTC, cadawson commented on clusters/hosted_control_plane_configure.adoc
> +. Because hosted control planes is a Technology Preview feature only on AWS, create an OIDC S3 credentials secret named `hypershift-operator-oidc-provider-s3-credentials` for the HyperShift operator.
Good catch. That was a miss on my part. Thanks!

2022-08-02 17:04 UTC, jnpacker commented on clusters/hosted_control_plane_configure.adoc
> +aws_access_key_id=ABCDEFGHIJKLMNOPQRST
Don't we usually include some text instead of a FAKE key?

2022-08-02 17:04 UTC, jnpacker commented on clusters/hosted_control_plane_configure.adoc
> +. Because hosted control planes is a Technology Preview feature only on AWS, create an OIDC S3 credentials secret named `hypershift-operator-oidc-provider-s3-credentials` for the HyperShift operator.
Instead of "save" we should use "apply" or "create"

2022-08-04 15:38 UTC, closed without merging

2022-08-04 15:40 UTC, cadawson commented
It was determined that his was not required. It is fixed in 2.5.2 and in 2.6.