Update subctl to 0.13 in 2.6
open-cluster-management/rhacm-docs pull request #3756
Opened 2022-07-26 13:29 UTC by oafischer

https://github.com/stolostron/backlog/issues/23717

2022-07-26 13:53 UTC, cadawson approved these changes
Looks good to me. Thanks!

2022-07-27 11:18 UTC, Jaanki requested changes
The first version would be 0.13.0.

2022-07-27 11:18 UTC, Jaanki commented on add-ons/submariner/submariner.adoc
> +oc image extract registry.redhat.io/rhacm2/subctl-rhel8:v0.13 --path=/dist/subctl-v0.13.1-linux-amd64.tar.xz:/tmp/ --confirm
```suggestion
oc image extract registry.redhat.io/rhacm2/subctl-rhel8:v0.13 --path=/dist/subctl-v0.13.0-linux-amd64.tar.xz:/tmp/ --confirm
```

The first version would be 0.13.0.

2022-07-27 11:18 UTC, Jaanki commented on add-ons/submariner/submariner.adoc
> +*Note:* You might have to change `subctl-v0.13.1-linux-amd64.tar.xz` to the version of Submariner that you are using.
```suggestion
*Note:* You might have to change `subctl-v0.13.0-linux-amd64.tar.xz` to the version of Submariner that you are using.  
```

2022-07-27 13:16 UTC, oafischer commented
Thanks for pointing that out @Jaanki, went ahead and committed your edits. Thank you for your help on this issue! Going ahead with the merge now.

2022-07-27 13:48 UTC, Jaanki requested changes
@oafischer Few more changes please.

2022-07-27 13:48 UTC, Jaanki commented on add-ons/submariner/submariner.adoc
> +tar -C /tmp/ -xf /tmp/subctl-v0.13-linux-amd64.tar.xz
```suggestion
tar -C /tmp/ -xf /tmp/subctl-v0.13.0-linux-amd64.tar.xz
```

2022-07-27 13:48 UTC, Jaanki commented on add-ons/submariner/submariner.adoc
> +install -m744 /tmp/subctl-v0.13/subctl-v0.13-linux-amd64 /$HOME/.local/bin/subctl
```suggestion
install -m744 /tmp/subctl-v0.13.0/subctl-v0.13.0-linux-amd64 /$HOME/.local/bin/subctl
```

2022-07-27 13:52 UTC, oafischer commented
Done @Jaanki, thanks again.

2022-07-27 13:59 UTC, merged