stolostron/backlog#24460 import hub
open-cluster-management/rhacm-docs pull request #3830
Opened 2022-08-08 20:31 UTC by cadawson

2022-08-15 13:48 UTC, KevinFCormier commented on clusters/import_gui.adoc
> +* link:../clusters/import_gui.adoc#import-kubeconfig[Kubeconfig file]
@cadawson This organization doesn't quite work, because the server URL and API token or the kubeconfig are entered before the user reviews and submits.

2022-08-15 13:50 UTC, KevinFCormier requested changes
Please see inline comment - if you are using one of the auto-import modes, you must enter the information before the form is submitted. Setting the cluster API address is something you can optionally do afterwards.

2022-08-22 20:30 UTC, cadawson commented
Hi @KevinFCormier . Thanks for the feedback. This is a challenging one. I think it is a little more straightforward now. Please take a look. Thanks!

2022-08-22 20:50 UTC, KevinFCormier commented on clusters/import_gui.adoc
> +If you want to configure a cluster API address, complete the steps in link:../multicluster_engine/cluster_lifecycle/import_gui.adoc#import-configure-cluster-api[Optional: Configure the cluster API ad
Did you mean to remove this? It appears in the middle of the list of the 3 import modes.

2022-08-22 20:52 UTC, KevinFCormier commented on clusters/import_gui.adoc
> +If you want to configure a cluster API address, continue with the steps in link:../clusters/import_gui.adoc#import-configure-cluster-api[Optional: Configure the cluster API address].
Third time this occurs... the first one I think is meant to be removed. Not sure if you wanted it repeated here.

2022-08-23 09:17 UTC, cadawson commented on clusters/import_gui.adoc
> +If you want to configure a cluster API address, complete the steps in link:../multicluster_engine/cluster_lifecycle/import_gui.adoc#import-configure-cluster-api[Optional: Configure the cluster API ad
@KevinFCormier: I went with treating each option as a path, since they don't have all of the same steps. For that reason, I included the statement that leads to that optional procedure with each of the selections.

2022-08-23 09:17 UTC, cadawson commented on clusters/import_gui.adoc
> +If you want to configure a cluster API address, continue with the steps in link:../clusters/import_gui.adoc#import-configure-cluster-api[Optional: Configure the cluster API address].
I was including it with each of the paths of the selections.

2022-08-23 12:49 UTC, KevinFCormier commented on clusters/import_gui.adoc
> +If you want to configure a cluster API address, complete the steps in link:../multicluster_engine/cluster_lifecycle/import_gui.adoc#import-configure-cluster-api[Optional: Configure the cluster API ad
So why does "You can specify a Red Hat Ansible Automation Platform template to run..." only occur twice? It doesn't matter which import mode you use; you can specify an Automation template in any case.

Also, the template is only used when the cluster is upgraded. Please remove "imported or" from that line.

2022-08-23 18:35 UTC, cadawson commented on clusters/import_gui.adoc
> +If you want to configure a cluster API address, complete the steps in link:../multicluster_engine/cluster_lifecycle/import_gui.adoc#import-configure-cluster-api[Optional: Configure the cluster API ad
Hi @KevinFCormier . I merged it in with the intro text for the manual steps. I added another sentence to it to make it more prominent. I removed the imported piece, as well. See if it looks ok. Thanks!

2022-08-23 20:20 UTC, KevinFCormier approved these changes
Thanks for the updates!

2022-09-01 17:47 UTC, oafischer approved these changes
lgmt, I think the rebase is needed because there was a separate issue for a missing "Hat" in Red Hat that I addressed and merged a day or two ago.

2022-09-01 18:14 UTC, merged