Add new troubleshooting for cluster import in 2.3
open-cluster-management/rhacm-docs pull request #3858
Opened 2022-08-11 21:06 UTC by oafischer

https://github.com/stolostron/backlog/issues/21628

2022-08-11 21:59 UTC, swopebe commented on troubleshooting/trouble_already_exists.adoc
> +If you are unable to import an OCP cluster into ACM `MultiClusterHub` and receive an _Already exists_ error, follow the procedure to troubleshoot the problem.
neither product name presented properly.

2022-08-11 21:59 UTC, swopebe commented on troubleshooting/trouble_already_exists.adoc
> +If you are unable to import an OCP cluster into ACM `MultiClusterHub` and receive an _Already exists_ error, follow the procedure to troubleshoot the problem.
error goes in `this` format.

2022-08-11 22:01 UTC, swopebe commented on troubleshooting/trouble_already_exists.adoc
> +
product name issues throughout

see:

https://docs.google.com/spreadsheets/d/1DLS_lS3VKidgZIvcLmLp9BoiqptkvqHWfe1D5FD2kfk/edit#gid=1375785039

2022-08-12 01:24 UTC, oafischer commented on troubleshooting/trouble_already_exists.adoc
> +
Fixed the names (I think). Thanks. Is everything OK in terms of the architecture? Talked with Chris and we were evenly split on whether this needs a new book or if we can squeeze it into [trouble_import_status.adoc](https://github.com/stolostron/rhacm-docs/blob/2.3_stage/troubleshooting/trouble_import_status.adoc) like suggested in the Bugzilla.

2022-08-15 06:09 UTC, skeeey commented on troubleshooting/trouble_already_exists.adoc
> +Run the following link:https://github.com/stolostron/deploy/blob/master/hack/cleanup-managed-cluster.sh[`cleanup-managed-cluster.sh`] script on the managed cluster to remove pre-existing ACM resource
@oafischer 

For this part, I think we can use below commands instead the script `cleanup-managed-cluster.sh`

```
oc delete namespaces open-cluster-management-agent open-cluster-management-agent-addon --wait=false
oc get crds | grep open-cluster-management.io | awk '{print $1}' | xargs oc delete crds --wait=false
oc get crds | grep open-cluster-management.io | awk '{print $1}' | xargs oc patch crds --type=merge -p '{"metadata":{"finalizers": []}}'
```

refer to https://github.com/stolostron/rhacm-docs/pull/3627/files#diff-95b70bbc800333108c43d82bb146c0d7db4936880433931163d98e89673b3fa4R79

2022-08-17 02:21 UTC, skeeey approved these changes

2022-08-18 12:53 UTC, dockerymick requested changes

2022-08-18 12:53 UTC, dockerymick commented on troubleshooting/trouble_already_exists.adoc
> +An error log shows up when importing an :ocp-short: cluster into :product-title-short: `MultiClusterHub`:
change `:ocp-short:` to `{ocp-short}`

same change for all of the conrefs

2022-08-18 18:32 UTC, dockerymick approved these changes
All of the conrefs look correct to me. I recommend that you make sure the conrefs render correctly in the preview doc, before officially closing the issue. Thanks for documenting this Oliver!

2022-08-18 18:38 UTC, merged