Update host upload options in 2.6
open-cluster-management/rhacm-docs pull request #3860
Opened 2022-08-12 02:14 UTC by oafischer

https://github.com/stolostron/backlog/issues/24570

2022-08-12 15:30 UTC, cadawson requested changes
Thanks Oliver. Looks good, but added a couple of comments. Looks good after those considerations.

2022-08-12 15:30 UTC, cadawson commented on multicluster_engine/add_hosts_infra_env.adoc
> +. Select *Using a Discovery ISO*, *With BMC form* or *By uploading a YAML* to enter the information for your host.
We generally include the Oxford comma.  Select *Using a Discovery ISO*, *With BMC form*, or *By uploading a YAML*.

2022-08-12 15:30 UTC, cadawson commented on multicluster_engine/add_hosts_infra_env.adoc
> +*Note:* The YAML option allows you to upload multiple hosts at once.
Suggestion: *Note:* You can upload multiple hosts at the same time when you use the YAML option.

2022-08-15 14:03 UTC, jelkosz commented
from technical perspective lgtm

2022-08-16 18:12 UTC, merged