GRC Updates - Draft 2
open-cluster-management/rhacm-docs pull request #3870
Opened 2022-08-15 14:37 UTC by dhaiducek

Alternative to:
- #3857

2022-08-22 13:42 UTC, dockerymick commented on governance/cert_policy_ctrl.adoc
> +//^instead on ANDing how about "combining". Is ANDing the name of a task? Will the user ever see "AND" as an option?
@dhaiducek

2022-08-22 14:05 UTC, dhaiducek commented on governance/cert_policy_ctrl.adoc
> +//^instead on ANDing how about "combining". Is ANDing the name of a task? Will the user ever see "AND" as an option?
I suppose "ANDing" isn't a word, huh? 😉 

How about "The resulting list is compiled by using the intersection of results from all parameters."?

For background, "combining" would work, but I'd like to make it clear that if a namespace is selected in by one selector but not by another, it won't be included.

2022-08-22 15:45 UTC, dockerymick commented on governance/image_vuln_policy.adoc
> +//* <<image-vulnerability-policy-yaml-table,Image vulnerability policy YAML table>>
@dhaiducek Can you clarify why the table was removed. Just want to be on the same page.

2022-08-22 21:02 UTC, dhaiducek commented on governance/image_vuln_policy.adoc
> +//* <<image-vulnerability-policy-yaml-table,Image vulnerability policy YAML table>>
This policy is very similar to the Compliance Operator, so I was thinking the policies that installed Operators could follow the same patterns.

2022-08-22 21:35 UTC, dhaiducek commented
@dockerymick The rebase to resolve conflicts got really messy. I think I captured all of the changes that were made, but we may both need to take another look to make sure I resolved the merge conflicts correctly. Sorry!

2022-08-23 13:30 UTC, dhaiducek commented on governance/etcd_encryption_policy.adoc
> +See https://github.com/stolostron/policy-collection/blob/main/stable/SC-System-and-Communications-Protection/policy-etcdencryption.yaml[`policy-etcdencryption.yaml`] for the policy sample. See xref:.
I added the links to highlight that there were more details and fields (like `namespaceSelector` and `evaluationInterval`). How about this wording?
```suggestion
See https://github.com/stolostron/policy-collection/blob/main/stable/SC-System-and-Communications-Protection/policy-etcdencryption.yaml[`policy-etcdencryption.yaml`] for the policy sample. See the xref:../governance/policy_example.adoc[Policy YAML documentation] and the xref:../governance/config_policy_ctrl.adoc#kubernetes-configuration-policy-controller[Kubernetes configuration policy controller] to view additional details on policy and configuration policy fields.
```

2022-08-23 19:27 UTC, dockerymick commented on governance/create_config_pol.adoc
> +If you have an existing Kubernetes manifest, the xref:../governance/policy_generator.adoc[policy generator] is also a useful tool to automatically wrap those manifests in a policy.
@dhaiducek I suggest that we write the following statement:

If you have an existing Kubernetes manifest, consider using the policy generator to automatically include the manifests in a policy. See the xref:../governance/policy_generator.adoc[Policy generator] documentation.

What do you mean when you say wrap? Is my suggestion somewhat accurate?

2022-08-23 19:35 UTC, dockerymick commented on governance/image_vuln_policy.adoc
> +//* <<image-vulnerability-policy-yaml-table,Image vulnerability policy YAML table>>
@dhaiducek Thanks for clarifying and pointing that out. I didn't realize that there wasn't a table. Should we add a parameter table to the compliance operator policy doc?

2022-08-23 19:49 UTC, dhaiducek commented on governance/image_vuln_policy.adoc
> +//* <<image-vulnerability-policy-yaml-table,Image vulnerability policy YAML table>>
We have some comments in the image vulnerability policy here that we could add there also that I think make things clear.

I'm of the opinion that the ConfigurationPolicy YAML is documented elsewhere and the Compliance Operator is also documented elsewhere and we provide links to them, so I'd personally want users to use those instead of pursuing our own table.

2022-08-23 19:50 UTC, dhaiducek commented on governance/create_config_pol.adoc
> +If you have an existing Kubernetes manifest, the xref:../governance/policy_generator.adoc[policy generator] is also a useful tool to automatically wrap those manifests in a policy.
Yes, your suggestion looks good to me!

2022-08-23 20:04 UTC, dhaiducek commented
/hold for edits and reviews

2022-08-23 20:04 UTC, dockerymick commented on governance/image_vuln_policy.adoc
> +//* <<image-vulnerability-policy-yaml-table,Image vulnerability policy YAML table>>
Thanks! What should be added?

2022-08-23 20:07 UTC, dockerymick commented on governance/image_vuln_policy.adoc
> +  object-templates:
Let me know what else you might want to add in this doc

2022-08-23 20:57 UTC, mprahl commented on governance/config_policy_ctrl.adoc
> +The configuration policy controller is created on the managed cluster during installation. Configuration policy controller supports the `enforce` feature to remediate when the configuration policy is
```suggestion
The configuration policy controller is created on the managed cluster during installation. The configuration policy controller supports the `enforce` feature to remediate when the configuration policy is non-compliant. When the `remediationAction` for the configuration policy is set to `enforce`, the controller applies the specified configuration to the target managed cluster.
```

2022-08-23 20:58 UTC, mprahl commented on governance/config_policy_ctrl.adoc
> +A Kubernetes object is defined (in whole or in part) in the `object-templates` array in the configuration policy, indicating to the configuration policy controller on the fields to compare with objec
```suggestion
A Kubernetes object is defined (in whole or in part) in the `object-templates` array in the configuration policy, indicating to the configuration policy controller of the fields to compare with objects on the managed cluster. The configuration policy controller communicates with the local Kubernetes API server to get the list of your configurations that are in your cluster. For more information about CRDs, see https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/[Extend the Kubernetes API with CustomResourceDefinitions].
```

2022-08-23 21:00 UTC, mprahl commented on governance/config_policy_ctrl.adoc
>      compliant:
Should these have values?

2022-08-23 21:04 UTC, mprahl commented on governance/config_policy_ctrl.adoc
>  | Used to list expected behavior for roles and other Kubernetes object that must be evaluated or applied to the managed clusters. You must use the following verbs as parameter values:
```suggestion
| Used to define the desired state of the Kubernetes object on the managed clusters. You must use one of the following verbs as the parameter value:
```

2022-08-23 21:06 UTC, mprahl commented on governance/config_policy_ctrl.adoc
> -| spec.remediationAction.complianceType
It'd be good to also document `metadataComplianceType`:
https://github.com/stolostron/config-policy-controller/blob/09e981ce5a35e6fb500b0c36962383b4cb18fa90/deploy/crds/policy.open-cluster-management.io_configurationpolicies.yaml#L140

2022-08-23 21:08 UTC, dockerymick commented on governance/config_policy_ctrl.adoc
>      compliant:
No, we choose to have an empty policy example so that users could see the framework

2022-08-23 21:08 UTC, mprahl commented on governance/config_policy_ctrl.adoc
> +Configuration policy controller can be used to configure any Kubernetes resource and apply security policies across your clusters. The configuration policy is provided in the `policy-templates` field
```suggestion
The configuration policy controller can be used to configure any Kubernetes resource and apply security policies across your clusters. The configuration policy is provided in the `policy-templates` field of the policy on the hub cluster, and is propagated to the selected managed clusters by the governance framework. See the xref:../governance/policy_example.adoc#policy-yaml-structure[policy YAML documentation] for more about the hub cluster policy.
```

2022-08-23 21:10 UTC, mprahl commented on governance/config_policy_ctrl.adoc
> +A Kubernetes object is defined (in whole or in part) in the `object-templates` array in the configuration policy, indicating to the configuration policy controller of the fields to compare with objec
Why are CRDs relevant here?

2022-08-23 21:12 UTC, mprahl commented on governance/create_config_pol.adoc
> +      include: ["default", "kube-*"]
The `kube-*` seems wrong since we usually never want a policy to target those namespaces.

2022-08-23 21:17 UTC, mprahl commented on governance/policy_generator.adoc
>  Note that all the fields in the `policyDefaults` section except for `namespace` can be overridden per policy.
Optional: It'd be nice to confirm that all the options are documented here that are in the Policy Generator reference:
https://github.com/stolostron/policy-generator-plugin/blob/main/docs/policygenerator-reference.yaml

2022-08-23 21:19 UTC, mprahl commented
Thanks so much @dhaiducek and @dockerymick! This change looks awesome.

2022-08-23 21:20 UTC, mprahl commented on governance/policy_generator.adoc
> +Return to the xref:../governance/thirf_party_policy.adoc#integrate-third-party-policy-controllers[Integrate third-party policy controllers] documentation or refer to the xref:../governance/grc_intro.
Seems like a typo `thirf_party_policy`

2022-08-26 20:45 UTC, dhaiducek commented on governance/policy_generator.adoc
>  Note that all the fields in the `policyDefaults` section except for `namespace` can be overridden per policy.
Updated--please take a peek! There's an experiment in the commit to have the root-level key span the row, but that can easily be updated if it's too unconventional.

2022-08-26 20:49 UTC, dhaiducek commented on governance/config_policy_ctrl.adoc
> +A Kubernetes object is defined (in whole or in part) in the `object-templates` array in the configuration policy, indicating to the configuration policy controller of the fields to compare with objec
I left those references in, but I agree they seem a bit too high-level for our docs. 

@dockerymick Do you have thoughts on the CRD links?

2022-08-29 12:28 UTC, mprahl commented on governance/policy_generator.adoc
>  Note that all the fields in the `policyDefaults` section except for `namespace` can be overridden per policy.
@dhaiducek I like the change, but I'll let @dockerymick be the final judge on it.  :laughing:

2022-08-29 15:20 UTC, dockerymick commented on governance/config_policy_ctrl.adoc
> +A Kubernetes object is defined (in whole or in part) in the `object-templates` array in the configuration policy, indicating to the configuration policy controller of the fields to compare with objec
@dhaiducek not really, just thought it would be helpful to add this reference in case a user was unfamiliar with Kubernetes. I am ok with removing this link reference

2022-08-30 14:36 UTC, oafischer commented on governance/cert_policy_ctrl.adoc
> +Certificate policy controller can be used to detect certificates that are close to expiring, time durations (hours) that are too long, or contain DNS names that fail to match specified patterns. The
...for more details on...

2022-08-30 14:46 UTC, dhaiducek commented on governance/cert_policy_ctrl.adoc
> +Certificate policy controller can be used to detect certificates that are close to expiring, time durations (hours) that are too long, or contain DNS names that fail to match specified patterns. The
Updated!

2022-08-30 14:49 UTC, oafischer commented on governance/config_policy_ctrl.adoc
> +The configuration policy controller can be used to configure any Kubernetes resource and apply security policies across your clusters. The configuration policy is provided in the `policy-templates` f
...for more details on...

2022-08-30 15:14 UTC, oafischer commented on governance/config_policy_ctrl.adoc
> +`musthave`: Indicates an object must exist with the same fields as specified in the objectDefinition. The fields in the template are a subset of what exists in the object. In general, array values ar
This is more for future reference but we generally try to use active voice where possible (I know it's not always possible).

2022-08-30 15:18 UTC, oafischer commented on governance/config_policy_ctrl.adoc
> +You can configure the concurrency of the configuration policy controller per managed cluster to change how many configuration policies it can evaluate at the same time. To change the default value of
-> You can configure the concurrency of the configuration policy controller for each managed cluster

(change for translation/accessibility)

2022-08-30 15:25 UTC, dhaiducek commented on governance/config_policy_ctrl.adoc
> +You can configure the concurrency of the configuration policy controller per managed cluster to change how many configuration policies it can evaluate at the same time. To change the default value of
Updated--thanks!

2022-08-30 15:25 UTC, oafischer commented on governance/create_gatekeeper.adoc
> +*Note:* Default values are generated by the operator. See https://github.com/open-policy-agent/gatekeeper/blob/master/charts/gatekeeper/README.md[Gatekeeper Helm Chart] for an explanation of the opti
For example, here active voice would be: The Operator generates (the) default values.

2022-08-30 15:29 UTC, dhaiducek commented on governance/create_gatekeeper.adoc
> +*Note:* Default values are generated by the operator. See https://github.com/open-policy-agent/gatekeeper/blob/master/charts/gatekeeper/README.md[Gatekeeper Helm Chart] for an explanation of the opti
I was just about to ask about an example of active voice--thanks!

2022-08-30 15:41 UTC, oafischer commented on governance/grc_intro.adoc
> +** When a policy is propagated to a managed cluster, it is first replicated to the cluster namespace on the hub cluster, is named `namespaceName.policyName`, and also labeled as such. When you create
Can we say the following?: When a policy is propagated to a managed cluster, it is first replicated to the cluster namespace on the hub cluster and is named and labeled `namespaceName.policyName`.

(we try to avoid referring to things with this, that, as such etc., also not always possible but it might work here)

2022-08-30 15:44 UTC, oafischer commented on governance/grc_intro.adoc
> +** When a policy is propagated to a managed cluster, it is first replicated to the cluster namespace on the hub cluster, is named `namespaceName.policyName`, and also labeled as such. When you create
...due to the Kubernetes length limit for label values.

2022-08-30 16:07 UTC, oafischer commented on governance/memory_policy.adoc
> +Kubernetes configuration policy controller monitors the status of the memory usage policy. Use the memory usage policy to limit or restrict your memory and compute usage. For more information, see _L
Does this need to start with "The Kubernetes..."? Saw it in one of the other files in this PR.

2022-08-30 16:11 UTC, oafischer commented on governance/namespace_policy.adoc
> +Kubernetes configuration policy controller monitors the status of your namespace policy. Apply the namespace policy to define specific rules for your namespace.
Same question as before about needing "The" in the beginning.

2022-08-30 16:13 UTC, oafischer commented on governance/namespace_policy.adoc
> +| Specifies the remediation of your policy. The parameter values are `enforce` and `inform`. This value is optional since it will override any values provided in `spec.policy-templates`.
We also generally try to use present tense. So here I would change to: This value is optional because it overrides any values provided in `spec.policy-templates`.

2022-08-30 16:16 UTC, oafischer commented on governance/policy_example.adoc
> +*Important*: Some policy kinds might not support the enforce feature.
-> **Important:**

(make colon bold)

2022-08-30 16:18 UTC, oafischer commented on governance/policy_generator.adoc
> +| Use the parameters `compliant` and `noncompliant` to specify the frequency for a policy to be evaluated when in a particular compliance state. When managed clusters have low CPU resources, the eval
Remove the extra "to"

2022-08-30 16:19 UTC, oafischer commented on governance/policy_generator.adoc
> +| Use the parameters `compliant` and `noncompliant` to specify the frequency for a policy to be evaluated when in a particular compliance state. When managed clusters have low CPU resources, the eval
Do not use e.g.

IBM style says replace e.g. with "that is", though I'd prefer if you just write around that so you don't need to use either.

2022-08-30 16:21 UTC, oafischer commented on governance/policy_generator.adoc
> +| When a policy is part of a policy set, by default, the generator does not generate the placement for this policy since a placement is generated for the policy set. If a placement should still be ge
Avoid using "should" by writing in a direct manner. I would change to something like: To generate a placement, set it to...

2022-08-30 16:26 UTC, oafischer commented on governance/policy_generator.adoc
> +| The placement configuration for the policy set. This defaults to a placement configuration that matches all clusters. See `policyDefaults.placement` for placement documentation, however `policyDefa
...do not apply to policy sets.

(active voice)

2022-08-30 16:31 UTC, oafischer requested changes
Thanks for the massive work on this! I've left a bunch of comments and suggestions.

2022-08-30 16:35 UTC, dhaiducek commented on governance/grc_intro.adoc
> +** When a policy is propagated to a managed cluster, it is first replicated to the cluster namespace on the hub cluster, is named `namespaceName.policyName`, and also labeled as such. When you create
Yes--could we say "named and labeled using `namespaceName.policyName`"?

The reason is that `namespaceName.policyName` is used in the label as `policy.open-cluster-management.io/root-policy=namespaceName.policyName`, so it's not the label key.

2022-08-30 16:36 UTC, dhaiducek commented on governance/memory_policy.adoc
> +Kubernetes configuration policy controller monitors the status of the memory usage policy. Use the memory usage policy to limit or restrict your memory and compute usage. For more information, see _L
Oh, nice catch!

2022-08-30 16:37 UTC, dhaiducek commented on governance/memory_policy.adoc
> +Kubernetes configuration policy controller monitors the status of the memory usage policy. Use the memory usage policy to limit or restrict your memory and compute usage. For more information, see _L
I'll go through and fix all of them--it's a common paragraph for the policy examples.

2022-08-30 16:44 UTC, dhaiducek commented on governance/policy_example.adoc
> +*Important*: Some policy kinds might not support the enforce feature.
Does this go for all bold things like this? If so, there are a lot of updates to make (which I am totally primed to attack!)

2022-08-30 16:48 UTC, dhaiducek commented on governance/policy_generator.adoc
> +| Use the parameters `compliant` and `noncompliant` to specify the frequency for a policy to be evaluated when in a particular compliance state. When managed clusters have low CPU resources, the eval
So would something like this work or is there a better way?
>These are in the format of durations like `"1h25m3s"`.

2022-08-30 17:08 UTC, oafischer commented on governance/grc_intro.adoc
> +** When a policy is propagated to a managed cluster, it is first replicated to the cluster namespace on the hub cluster, is named `namespaceName.policyName`, and also labeled as such. When you create
Got it, I was thinking it might be something like that so feel free to keep it as it if it's more accurate from a technical standpoint.

2022-08-30 17:09 UTC, oafischer commented on governance/policy_example.adoc
> +*Important*: Some policy kinds might not support the enforce feature.
This is only for special tags. See https://stolostron.github.io/rhacm-docs/wr_special_tag_guidance

2022-08-30 17:16 UTC, dhaiducek commented on governance/policy_example.adoc
> +*Important*: Some policy kinds might not support the enforce feature.
Cool, thanks! I've created another commit to address all the instances: https://github.com/stolostron/rhacm-docs/pull/3870/commits/473a6abba1bb006a9edaefddbc44848598f9be94

2022-08-30 17:24 UTC, oafischer commented on governance/policy_generator.adoc
> +| Use the parameters `compliant` and `noncompliant` to specify the frequency for a policy to be evaluated when in a particular compliance state. When managed clusters have low CPU resources, the eval
Hmm sometimes it's hard to write around. One option is to use a new sentence:

The interval is the format of durations. For example, `1h25m3s` represents 1 hour, 25 minutes and 3 seconds.

Alternatively, it's still OK to use "that is" to replace e.g., I just always try to write around it if possible.

2022-08-30 17:31 UTC, oafischer commented on governance/policy_example.adoc
> +*Important*: Some policy kinds might not support the enforce feature.
Awesome, thanks! There are a lot of places in the doc where it is inconsistent so our goal has just been to fix it whenever we happen to see it while working on issues. This definitely helps.

2022-08-30 17:41 UTC, dhaiducek commented on governance/policy_example.adoc
> +*Important*: Some policy kinds might not support the enforce feature.
If it helps, you can use VSCode to find/replace them all at once:
- Search for this RegEx (The `.*` option in Search): `((note|important|tip|optional|best practice)s?)\*:`
- Replace with the swapped asterisk and colon: `$1:*`
To explain, the stuff in parentheses gets captured (with an optional "s") and you can reference it using $1 (if there were more than one parentheses, the next group would be $2, and so on).

2022-09-01 19:56 UTC, dhaiducek commented
I think this PR is ready for another review if everyone could take one (hopefully last) peek...

2022-09-01 20:29 UTC, oafischer approved these changes
Looks good from a writing perspective. Thank you for also bolding the colons for special tags!

2022-09-01 20:31 UTC, dhaiducek commented
/unhold

2022-09-02 12:42 UTC, dockerymick approved these changes
Wheew, all files viewed and links checked in this PR

2022-09-02 14:02 UTC, dockerymick commented
@dhaiducek confirmed that he is ok with me merging this PR through Slack.

2022-09-02 14:02 UTC, merged