Add bind/view permission in 2.6
open-cluster-management/rhacm-docs pull request #3872
Opened 2022-08-15 15:33 UTC by oafischer

https://github.com/stolostron/backlog/issues/23820

2022-08-15 21:43 UTC, KevinFCormier commented on multicluster_engine/cluster_lifecycle/managedclustersets_assign_role.adoc
> +* Cluster set `bind`
You missed the line that @ldpliu added here: `Bind the cluster set to a namespace.`

This is important because it is the main point of this role. I think we should be a bit more explicit... something like: `Permission to bind the cluster set to a namespace by creating a ManagedClusterSetBinding. (The user or group must also have permission to create the ManagedClusterSetBinding in the target namespace.)`

2022-08-15 21:43 UTC, KevinFCormier requested changes
Please see inline comment. I have added @ldpliu for review as well.

2022-08-16 13:45 UTC, oafischer commented on multicluster_engine/cluster_lifecycle/managedclustersets_assign_role.adoc
> +* Cluster set `bind`
Thanks for explaining that in more detail @KevinFCormier. Would you say we should keep the other two bullet points about permissions?

2022-08-16 14:01 UTC, KevinFCormier commented on multicluster_engine/cluster_lifecycle/managedclustersets_assign_role.adoc
> +* Cluster set `bind`
Yes, but I will leave to @ldpliu to confirm that the role also includes those 2 other permissions.

2022-08-16 14:15 UTC, KevinFCormier approved these changes
Approving content-wise. I'm not really sure what the formatting will look like.

2022-08-16 14:18 UTC, oafischer commented
Thanks for your help on this and my other PRs @KevinFCormier! Much appreciated. Wanted to get the content correct first before opening this up for peer review for formatting etc.

2022-08-17 01:28 UTC, ldpliu commented on multicluster_engine/cluster_lifecycle/managedclustersets_assign_role.adoc
> +* Cluster set `bind`
Yes, The current change is ok for me

2022-08-17 01:29 UTC, ldpliu commented
/approve

2022-08-18 13:09 UTC, merged