Add automatic global set creation in 2.6
open-cluster-management/rhacm-docs pull request #3873
Opened 2022-08-15 19:33 UTC by oafischer

Link to the original issue: https://github.com/stolostron/backlog/issues/23495

2022-08-15 19:48 UTC, oafischer commented
@ldpliu I have added the global managed cluster set section to the file you originally wanted it in, but due to the MCE move, I wonder if it would be better to have this section here instead: https://github.com/stolostron/rhacm-docs/blob/2.6_stage/multicluster_engine/cluster_lifecycle/managedclustersets_create.adoc

Let me know what you think. Feel free to weigh in on this as well @KevinFCormier

2022-08-15 21:21 UTC, dockerymick requested changes

2022-08-15 21:21 UTC, dockerymick commented on multicluster_engine/cluster_lifecycle/managedclustersets_add_cluster.adoc
> +**Note:** <<#adding-clusters-to-a-managedclusterset,Adding a cluster to a ManagedClusterSet>> does not apply to the global cluster set. The `global` set always includes all managed clusters. See xref
Should these be two separate notes? If yes, I recommend reorganizing this statement to read as the following content:

**Notes**: 
+
* When you add a cluster to a managed cluster set, the action does not apply to the global cluster set. See Adding a cluster to a ManagedClusterSet for more details. 

* The `global` set always includes all managed clusters. See Global ManagedClusterSet.

2022-08-15 21:21 UTC, dockerymick commented on multicluster_engine/cluster_lifecycle/managedclustersets_intro.adoc
>  Each managed cluster must be a member of a `ManagedClusterSet`. When you install the hub cluster, a default `ManagedClusterSet` is created called `default`. All managed clusters that are not specific
Each managed cluster must be a member of a managed cluster set. When you install the hub cluster, a default `ManagedClusterSet` resource is created called `default`.

2022-08-15 21:21 UTC, dockerymick commented on multicluster_engine/cluster_lifecycle/managedclustersets_intro.adoc
> +**Note:** Cluster pools that are not specifically added to a `ManagedClusterSet` are not added to the default `ManagedClusterSet`. After a managed cluster is claimed from a cluster pool, it is added
Cluster pools that are not specifically added to a managed cluster set are not added to the default `ManagedClusterSet` resource. After a managed cluster is claimed from a cluster pool, it is added to the default `ManagedClusterSet` resource if it is not specifically added to another managed cluster set.

2022-08-15 21:21 UTC, dockerymick commented on multicluster_engine/cluster_lifecycle/managedclustersets_intro.adoc
> +When you create a managed cluster, the following are automatically created to ease management.
Add a colon ( : ) instead of a period at the end of this statement

2022-08-15 21:21 UTC, dockerymick commented on multicluster_engine/cluster_lifecycle/managedclustersets_remove_cluster.adoc
> +**Note:** <<#removing-a-managed-cluster-from-a-managedclusterset,Removing a managed cluster from a ManagedClusterSet>> does not apply to the global cluster set. The `global` set always includes all m
Similar to my previous comment, rearrange this statement. 

**Notes**: 
+
* When you remove a managed cluster from the managed cluster set, the action does not apply to the global cluster set. See Removing a managed cluster from a ManagedClusterSet for more details. 
* The `global` set always includes all managed clusters. See Global ManagedClusterSet for more details.

2022-08-15 22:00 UTC, KevinFCormier approved these changes
Thanks. Your changes addressed my concerns.

2022-08-15 22:00 UTC, KevinFCormier commented on multicluster_engine/cluster_lifecycle/managedclustersets_add_cluster.adoc
> +**Note:** <<#adding-clusters-to-a-managedclusterset,Adding a cluster to a ManagedClusterSet>> does not apply to the global cluster set. The `global` set always includes all managed clusters. See xref
I think the way this was stated initially makes more sense. This is not 2 separate notes. You cannot add a cluster to the global cluster set because it automatically includes all managed clusters.

2022-08-15 22:00 UTC, KevinFCormier commented on multicluster_engine/cluster_lifecycle/managedclustersets_remove_cluster.adoc
> +**Note:** <<#removing-a-managed-cluster-from-a-managedclusterset,Removing a managed cluster from a ManagedClusterSet>> does not apply to the global cluster set. The `global` set always includes all m
I think the way this was stated initially makes more sense. This is not 2 separate notes. You cannot remove a cluster from the global cluster set because it automatically includes all managed clusters.

2022-08-16 13:37 UTC, dockerymick commented on multicluster_engine/cluster_lifecycle/managedclustersets_remove_cluster.adoc
> +**Note:** <<#removing-a-managed-cluster-from-a-managedclusterset,Removing a managed cluster from a ManagedClusterSet>> does not apply to the global cluster set. The `global` set always includes all m
We typically do not lead statements with links. For accessibility reasons, we prompt the user for the link. I recommend the following: 

When you remove a managed cluster from the managed cluster set, the action does not apply to the global cluster set. See Removing a managed cluster from a ManagedClusterSet for more details.
The global set always includes all managed clusters. See Global ManagedClusterSet for more details.

2022-08-16 13:38 UTC, dockerymick commented on multicluster_engine/cluster_lifecycle/managedclustersets_add_cluster.adoc
> +**Note:** <<#adding-clusters-to-a-managedclusterset,Adding a cluster to a ManagedClusterSet>> does not apply to the global cluster set. The `global` set always includes all managed clusters. See xref
When you add a cluster to a managed cluster set, the action does not apply to the global cluster set. See Adding a cluster to a ManagedClusterSet for more details. The global set always includes all managed clusters. See Global ManagedClusterSet.

2022-08-16 13:45 UTC, KevinFCormier commented on multicluster_engine/cluster_lifecycle/managedclustersets_add_cluster.adoc
> +**Note:** <<#adding-clusters-to-a-managedclusterset,Adding a cluster to a ManagedClusterSet>> does not apply to the global cluster set. The `global` set always includes all managed clusters. See xref
@dockerymick The first sentence doesn't make sense to me. This section of the doc ("Adding a cluster to a ManagedClusterSet") does not apply to the global cluster set. When you are adding a cluster to a managed cluster set, of course the action does not apply to the global set because you cannot add a cluster to the global cluster set. All managed clusters are automatically members of the global set.

The second sentence is not needed because that is the section this note appears in.

2022-08-16 13:52 UTC, oafischer commented on multicluster_engine/cluster_lifecycle/managedclustersets_add_cluster.adoc
> +**Note:** <<#adding-clusters-to-a-managedclusterset,Adding a cluster to a ManagedClusterSet>> does not apply to the global cluster set. The `global` set always includes all managed clusters. See xref
@KevinFCormier Can you explain the original statements here in more detail? https://github.com/stolostron/backlog/issues/23495#issuecomment-1191510476

Might be more helpful since @dockerymick is trying to fix what I have in this PR, and what I have in this PR is based on that comment I linked. May be useful to go back to the source and make sure we understand that first.

2022-08-16 14:38 UTC, KevinFCormier commented on multicluster_engine/cluster_lifecycle/managedclustersets_add_cluster.adoc
> +**Note:** <<#adding-clusters-to-a-managedclusterset,Adding a cluster to a ManagedClusterSet>> does not apply to the global cluster set. The `global` set always includes all managed clusters. See xref
Within this section there are 2 subsections describing how to add a cluster to a managed cluster set using the console or command line. In the instructions for the console, notice that it mentions the **Manage resource assignments** action. You can do this on cluster sets you created your self, like `example` in the following screenshots, or even `default`, but it is not an option for the `global` set.

![image](https://user-images.githubusercontent.com/42188127/184906965-c0d28f49-4c0d-42cf-ae8f-6cb980aa9adf.png)
![image](https://user-images.githubusercontent.com/42188127/184907000-305ab818-8a26-4fb4-a941-a364d5b43e41.png)
![image](https://user-images.githubusercontent.com/42188127/184907032-1c82e149-f456-4f01-aea9-2c5927fc778a.png)

Via command-line, it appears there is no error if you add the label `cluster.open-cluster-management.io/clusterset: global` however, this has no effect on the cluster aside from removing it from a different cluster set if the label was already there with a different value. FYI @ldpliu

2022-08-16 17:52 UTC, oafischer commented on multicluster_engine/cluster_lifecycle/managedclustersets_add_cluster.adoc
> +**Note:** <<#adding-clusters-to-a-managedclusterset,Adding a cluster to a ManagedClusterSet>> does not apply to the global cluster set. The `global` set always includes all managed clusters. See xref
@KevinFCormier Thank you for explaining in detail, I think I understand what you meant with your original comment now.

Not sure what the best way to implement this is. Do we want a separate note for both GUI and command line procedures? A note for GUI, as far as I am concerned, would look something like this:

The *Manage resource assignments* option is not available for the `global` managed cluster set. See [Global ManagedClusterSet]() for more details.

A global note at the beginning of the topic might look something like this:

You cannot modify the `global` managed cluster set.

Not sure what the best way to express the limitation is. I want it to make sense for someone who doesn't have your detailed explanation above. Do you have some input @KevinFCormier?

2022-08-17 16:05 UTC, dockerymick commented on multicluster_engine/cluster_lifecycle/managedclustersets_add_cluster.adoc
> +**Note:** <<#adding-clusters-to-a-managedclusterset,Adding a cluster to a ManagedClusterSet>> does not apply to the global cluster set. The `global` set always includes all managed clusters. See xref
@KevinFCormier Thanks for explaining, I appreciate you. @oafischer I really like your suggestion to use the **Important** notice for the explanation

2022-08-17 20:34 UTC, oafischer commented on multicluster_engine/cluster_lifecycle/managedclustersets_add_cluster.adoc
> +**Note:** <<#adding-clusters-to-a-managedclusterset,Adding a cluster to a ManagedClusterSet>> does not apply to the global cluster set. The `global` set always includes all managed clusters. See xref
Given that this is the cleanest solution from a doc and user perspective, I'm going to move ahead with it. Thanks everyone for helping with this PR.

2022-08-18 00:11 UTC, dockerymick approved these changes
Last couple of suggestions

2022-08-18 00:11 UTC, dockerymick commented on multicluster_engine/cluster_lifecycle/managedclustersets_intro.adoc
> +----
To align the notice after the last bullet point, add a plus sign on line 18, and another on line 20.

2022-08-18 00:11 UTC, dockerymick commented on multicluster_engine/cluster_lifecycle/managedclustersets_intro.adoc
I recommend prompting the user for your upcoming list of references. I would add a statement that is similar to the following:

Continue reading to learn more on updating manage cluster sets:

2022-08-18 13:58 UTC, merged