Zettaset
open-cluster-management/rhacm-docs pull request #3875
Opened 2022-08-16 12:28 UTC by dockerymick

https://github.com/stolostron/backlog/issues/24886

2022-08-18 19:46 UTC, mprahl commented
@gparvin could you please review this since you were involved in that community contribution?

2022-08-25 04:06 UTC, gparvin requested changes
I saw one small change to make for this update.  Thanks

2022-08-25 04:06 UTC, gparvin commented on governance/zettaset_policy.adoc
> +Learn more details about SCC policies in the following sections:
I think `SCC` is supposed to be `ZettaSet` in this sentence.

2022-08-29 16:42 UTC, dockerymick commented on governance/zettaset_policy.adoc
> +//for yaml examples, we usually leave them empty. Which parameters require a value? Can you help with providing the best structure for the user. Is the PLacementBinding required in this example since
@gparvin should any values be removed from this sample?

2022-08-29 18:15 UTC, gparvin reviewed
Thanks @dockerymick, I added one comment just to help make this consistent with what I see in other documented policy sections.

2022-08-29 18:15 UTC, gparvin commented on governance/zettaset_policy.adoc
> +//for yaml examples, we usually leave them empty. Which parameters require a value? Can you help with providing the best structure for the user. Is the PLacementBinding required in this example since
To be consistent with out other examples I think we would have the following:

```
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-zts-cmc
spec:
  remediationAction: 
  disabled: 
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-zts-cmc-reloader-deployment
        spec:
          remediationAction: 
          severity: 
          namespaceSelector:
            exclude:
            include:
          object-templates:
            - complianceType: 
              objectDefinition:
                apiVersion: apps/v1
                kind: Deployment
                metadata:
                  name: reloader-reloader
                  labels:
                    app: 
                spec:
                  replicas: 
                  selector:
                    matchLabels:
                      app: 
                  template:
                    metadata:
                      labels:
                        app: 
                    spec:
                      containers:
                        - name: 
                          imagePullPolicy: 
                          image: 
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-zts-cmc
        spec:
          remediationAction:  
          severity: 
          namespaceSelector:
            exclude:
            include:
          object-templates:
            - complianceType: 
              objectDefinition:
                apiVersion: 
                kind: Deployment
                metadata:
                  annotations:
                    configmap.reloader.stakater.com/reload: 
                  name: zts-cmc-app-deploy
                  labels:
                    app: 
                spec:
                  replicas: 
                  selector:
                    matchLabels:
                      app: 
                  template:
                    metadata:
                      labels:
                        app: 
                    spec:
                      containers:
                        - name: 
                          imagePullPolicy: 
                          image: 
                          env:
                           - name: 
                             valueFrom:
                               configMapKeyRef:
                                 name: 
                                 key: 
                          ports:
                            - containerPort: 
                      imagePullSecrets:
                        - name: 
```

2022-08-30 00:12 UTC, dockerymick commented on governance/zettaset_policy.adoc
> +//for yaml examples, we usually leave them empty. Which parameters require a value? Can you help with providing the best structure for the user. Is the PLacementBinding required in this example since
Done

2022-08-30 00:13 UTC, dockerymick commented
@gparvin thanks for your feedback @mprahl @JustinKuli will either of you review this as well please?

2022-08-30 14:06 UTC, JustinKuli reviewed
Question for @gparvin, are the policies documented here supposed to match the policies supported by the UI wizard? Or should documented policies match the `stable` policies in the collection?

I ask because neither this new policy, nor the kyverno-related policies in the `stable` collection, are not supported in the policy wizard. And the kyverno policies in `stable` aren't documented here... so it's getting inconsistent.

2022-08-30 14:06 UTC, JustinKuli commented on governance/zettaset_policy.adoc
> +                    configmap.reloader.stakater.com/reload:
What's the rule for which values to include in this, and which ones to skip? Having this annotation key but not value just seems very arbitrary... If it's just to be consistent with other bits of the docs, I can accept that.

But since this YAML is not directly apply-able (it's missing required values), and not all of the missing values are documented below, I just don't understand what its purpose is.

2022-08-30 14:43 UTC, gparvin commented
So all stable policies should have e2e tests and should be documented.  If kyverno is missing I can open a doc issue though I thought I had done that.
The practice of adding it to the UI so far has taken the path of the policy only gets into the UI if there are no dependencies on other things for it to work.  Since kyverno, zettaset and even the compliance profiles require certain prerequisites they have not been added to the ui by default.  

I agree that the documentation for our policies does seem strange.  I wasn't going to try to address that at this time -- I wanted to see what Dale was doing in https://github.com/stolostron/rhacm-docs/pull/3870  before revisiting that concern -- but I completely agree we have a lot of complexity here that isn't useful.

2022-08-30 14:58 UTC, JustinKuli approved these changes

2022-08-30 18:41 UTC, oafischer commented on governance/zettaset_policy.adoc
> +Kubernetes configuration policy controller monitors the status of your `ZettaSet` policy. Apply a `ZettaSet` policy to deploy the Zettaset application. The `Zettaset` policy uses the ConfigMap reload
-> The Kubernetes configuration policy controller...

2022-08-30 18:51 UTC, oafischer approved these changes
See comments. Small changes so I don't need to see it again. Approving from writing perspective.

2022-08-30 18:51 UTC, oafischer commented on governance/zettaset_policy.adoc
> += ZettaSet policy
Is the S in ZettaSet supposed to be capitalized?

2022-08-31 16:12 UTC, dockerymick commented on governance/zettaset_policy.adoc
> += ZettaSet policy
It was my intention to capitalize it, but i was thinking about the policy `kind` when i named this doc. I am going to use a lowercase "s" instead. Thanks!

2022-08-31 19:05 UTC, dockerymick commented
@JustinKuli thanks for asking, it was for the sake of consistency. Thanks @gparvin for your clarification on how policies are added into the console. i look forward to improving our Governance docs!

2022-08-31 23:31 UTC, dockerymick commented
Moving forward with the merge since there are 2 approvals

2022-08-31 23:33 UTC, merged