Add OpenStack and hive troubleshooting in 2.6
open-cluster-management/rhacm-docs pull request #3879
Opened 2022-08-17 17:21 UTC by oafischer

https://github.com/stolostron/backlog/issues/24678

2022-08-17 17:31 UTC, oafischer commented
@ldpliu I had to fill in some gaps because it wasn't always clear if a file or parameter was being referenced. What I have now may be wrong so please check by comparing it to your original draft. Thanks.

2022-08-17 18:48 UTC, dockerymick approved these changes
Left a comment

2022-08-17 18:48 UTC, dockerymick commented on troubleshooting/trouble_openstack_cluster.adoc
> +. The size of the `ca.cert` file must be less than 63 thousand bytes.
This looks good to me. We definitely need to revisit the architecture of our troubleshoot topics. I would remove _Managed cluster creation fails with unknown authority error_ from the subtitles. However, maybe keep it as is until we can receive feedback from Chris and Brandi

2022-08-17 18:54 UTC, oafischer commented on troubleshooting/trouble_openstack_cluster.adoc
> +. The size of the `ca.cert` file must be less than 63 thousand bytes.
Thanks Mikela, sounds good. @swopebrandi1 and @cadawson, let us know what you think.

2022-08-18 02:59 UTC, ldpliu approved these changes

2022-08-18 02:59 UTC, ldpliu commented on troubleshooting/trouble_openstack_cluster.adoc
> +----
The code format should be updated follow: https://github.com/stolostron/backlog/issues/24678#issuecomment-1203433327

2022-08-18 02:59 UTC, ldpliu commented on troubleshooting/trouble_openstack_cluster.adoc
> +----
The code format should be updated follow: https://github.com/stolostron/backlog/issues/24678#issuecomment-1203433327

2022-08-19 01:21 UTC, ldpliu approved these changes

2022-08-19 13:00 UTC, cadawson requested changes
Thanks @oafischer . Looks good. I added a couple of comments.

2022-08-19 13:00 UTC, cadawson commented on troubleshooting/trouble_openstack_cluster.adoc
> += Troubleshooting cluster creation on OpenStack
There is only one troubleshooting issue here, so I would remove this header and make "Managed cluster creation fails on Red Hat OpenStack Platform with unknown authority error" the main title. Then Symptom and Resolving the problem: become sub-levels. 
For example:
= Managed cluster creation fails on Red Hat OpenStack Platform with unknown authority error
== Symptom: Managed cluster creation fails on Red Hat OpenStack Platform with unknown authority error
== Resolving the problem: Managed cluster creation fails on Red Hat OpenStack Platform with unknown authority error

Let me know if that doesn't make sense.

2022-08-19 13:00 UTC, cadawson commented on troubleshooting/trouble_openstack_cluster.adoc
> +If you experience a problem when creating a {ocp} cluster on OpenStack, see the following troubleshooting information to see if one of them addresses your problem.
According to the product title guidance, we should always use "Red Hat OpenStack Platform".

2022-08-19 13:04 UTC, oafischer commented on troubleshooting/trouble_openstack_cluster.adoc
> += Troubleshooting cluster creation on OpenStack
Thanks Chris! I went ahead and implemented your suggestions.

2022-08-20 01:04 UTC, dockerymick commented on troubleshooting/trouble_openstack_cluster.adoc
> +. The size of the `ca.cert` file must be less than 63 thousand bytes.
Let's bring this up in the doc arch call after GA maybe? I would move forward with the merge

2022-08-23 14:57 UTC, oafischer commented
Implemented suggested changes, moving forward with merge.

2022-08-23 14:57 UTC, merged