Add HyperShift known issue in 2.6
open-cluster-management/rhacm-docs pull request #3901
Opened 2022-08-19 15:59 UTC by oafischer

https://github.com/stolostron/backlog/issues/25156

2022-08-19 17:30 UTC, cadawson requested changes
A couple of comments, but nothing major. Thanks!

2022-08-19 17:30 UTC, cadawson commented on release_notes/known_issues.adoc
> +=== {ocp-short} 4.10.z does not support HyperShift clusters with proxy configuration
Make sure that we mean "HyperShift" specifically here. We are using "hosted control planes" for the overall concept. "HyperShift" is the operator that we are using to create the "hosting service cluster" (which is the hosted control plane equivalent of the hub cluster). We are using HyperShift to make that work right now, there might be other options in the future. For consistency, and to avoid getting trapped into using only HyperShift, we want to make sure that we are using the right terminology in the right place. We are referring to the managed clusters in hosted control planes as "hosted clusters". It might be fine, but just want to be sure that we are using the right terms.

2022-08-19 17:30 UTC, cadawson commented on release_notes/known_issues.adoc
> + When you create a HyperShift cluster with a cluster-wide proxy configuration on {ocp-short} 4.10.z, the `nodeip-configuration.service` service does not start on worker nodes.
Hosting service cluster? 

...on the worker nodes?

2022-08-19 17:49 UTC, oafischer commented on release_notes/known_issues.adoc
> +=== {ocp-short} 4.10.z does not support HyperShift clusters with proxy configuration
Might be a better question for @ldpliu. Can you confirm you meant HyperShift here?

2022-08-19 18:56 UTC, oafischer commented on release_notes/known_issues.adoc
> + When you create a HyperShift cluster with a cluster-wide proxy configuration on {ocp-short} 4.10.z, the `nodeip-configuration.service` service does not start on worker nodes.
I'll implement the second suggestion, thanks. Going to ping @ldpliu for help on the first suggestion.

2022-08-22 01:16 UTC, ldpliu commented on release_notes/known_issues.adoc
> +=== {ocp-short} 4.10.z does not support HyperShift clusters with proxy configuration
Thanks, I think @cadawson is right. and we should change "HyperShift" to "hosted control planes"

2022-08-22 01:23 UTC, ldpliu commented on release_notes/known_issues.adoc
> + When you create a HyperShift cluster with a cluster-wide proxy configuration on {ocp-short} 4.10.z, the `nodeip-configuration.service` service does not start on worker nodes.
Yes, we should change it.

2022-08-22 14:15 UTC, oafischer commented
Thanks for chiming in @ldpliu, you can review the changes again when you have a chance @cadawson.

2022-08-23 14:54 UTC, oafischer commented
Made the suggested changes, going ahead with merge.

2022-08-23 14:57 UTC, merged