Replace aarch64 with arm64 in 2.5
open-cluster-management/rhacm-docs pull request #3907
Opened 2022-08-19 19:15 UTC by oafischer

https://github.com/stolostron/backlog/issues/25060

2022-08-19 20:18 UTC, berenss approved these changes

2022-08-19 20:18 UTC, berenss requested changes
Do not make changes to the release_images - they need to stay as aarch64

2022-08-19 20:20 UTC, berenss commented
@gurnben @dtthuynh @jaywcarman please keep me honest here.

1. when we're talking about install-config.yaml options, in the controlPlane.architecture field it needs to be arm64
2. when we're talking about release images and the clusterImageSets we need to reference aarch64

2022-08-20 00:06 UTC, oafischer commented
Got it @berenss, thanks for pointing that out. I reverted all the changes in release_images.

2022-08-20 00:59 UTC, dockerymick requested changes

2022-08-20 00:59 UTC, dockerymick commented on clusters/create_vm.adoc
> +The node pools include the control plane pool and the worker pools. The control plane nodes share the management of the cluster activity. The information includes the _Architecture_ field:
It seems like there should be a period at the end of this instead of a colon

2022-08-20 00:59 UTC, dockerymick commented on clusters/create_vm.adoc
> +* Architecture: If the architecture type of the managed cluster is not the same as the architecture of your hub cluster, enter a value for the instruction set architecture of the machines in the pool
I recommend prompting the user for the definition of the _Architecture_ field. Add something along the lines of "View the following field description:"

 I took a look at the doc and i recommend we add some subsections. For example, after the first Tip, I would name add a subsection titled, **Adding your cluster to an existing cluster set**. Idk it just seems daunting to read and the information is cluttered in my opinion.

2022-08-20 00:59 UTC, dockerymick commented on clusters/create_virtualization.adoc
> +* Architecture: If the architecture type of the managed cluster is not the same as the architecture of your hub cluster, enter a value for the instruction set architecture of the machines in the pool
I recommend the same suggestion for each file. My suggestion is most likely a different effort and this PR is specifically created to update the value.

2022-08-22 14:40 UTC, oafischer commented on clusters/create_virtualization.adoc
> +* Architecture: If the architecture type of the managed cluster is not the same as the architecture of your hub cluster, enter a value for the instruction set architecture of the machines in the pool
Is there going to be a conflict? This PR is just addressing this issue: https://github.com/stolostron/backlog/issues/25060

2022-08-22 14:56 UTC, berenss approved these changes
lgtm

2022-08-22 14:56 UTC, berenss commented on clusters/create_azure.adoc
> + * *Optional* Architecture: If the architecture type of the managed cluster is not the same as the architecture of your hub cluster, enter a value for the instruction set architecture of the machines
this looks good to me.

2022-08-22 14:56 UTC, berenss commented on clusters/create_google.adoc
> +* Architecture: If the architecture type of the managed cluster is not the same as the architecture of your hub cluster, enter a value for the instruction set architecture of the machines in the pool
looks good to me.

2022-08-22 14:56 UTC, berenss commented on clusters/create_ocp_aws.adoc
> +* Architecture: If the architecture type of the managed cluster is not the same as the architecture of your hub cluster, enter a value for the instruction set architecture of the machines in the pool
looks good

2022-08-22 14:56 UTC, berenss commented on clusters/create_openstack.adoc
> +* *Optional* Architecture: If the architecture type of the managed cluster is not the same as the architecture of your hub cluster, enter a value for the instruction set architecture of the machines
yes looks good

2022-08-22 14:56 UTC, berenss commented on clusters/create_virtualization.adoc
> +* Architecture: If the architecture type of the managed cluster is not the same as the architecture of your hub cluster, enter a value for the instruction set architecture of the machines in the pool
looks good to me

2022-08-22 14:56 UTC, berenss commented on clusters/create_vm.adoc
> +* Architecture: If the architecture type of the managed cluster is not the same as the architecture of your hub cluster, enter a value for the instruction set architecture of the machines in the pool
looks good to me.

2022-08-22 15:10 UTC, oafischer commented on clusters/create_vm.adoc
> +* Architecture: If the architecture type of the managed cluster is not the same as the architecture of your hub cluster, enter a value for the instruction set architecture of the machines in the pool
@dockerymick I agree, went ahead and added that subsection. Also added your other suggestion.

2022-08-22 15:23 UTC, dockerymick commented on clusters/create_google.adoc
> +== Adding your cluster to an existing cluster set
Thanks for adding this! Add the childlink for this section in the TOC at the beginning of the file., where you list the sections within the file

2022-08-22 15:24 UTC, dockerymick commented on clusters/create_virtualization.adoc
> +The information for your node pools includes the number of Cores, Sockets, Memory, and Disk size for the the control plane pool. The three control plane nodes share the management of the cluster acti
add "View the following field description:" after "The information includes the _Architecture_ field."

2022-08-22 15:26 UTC, dockerymick commented on clusters/create_vm.adoc
> +
Update the TOC inn the file by adding the childlink (<<section-anchor,Title of section>>) at the beginning of the file

2022-08-22 15:27 UTC, dockerymick requested changes
Made a couple of suggestions

2022-08-22 15:56 UTC, dockerymick commented on clusters/create_openstack.adoc
> +== Adding your cluster to an existing cluster set
same change for this file. Whenever you add a new section in a file, remember to add the childlink in the TOC within the file

2022-08-22 15:56 UTC, dockerymick commented on clusters/create_virtualization.adoc
> +== Adding your cluster to an existing cluster set
Same

2022-08-22 16:59 UTC, oafischer commented
I think I got everything @dockerymick if you wanna give it one final check.

2022-08-22 19:22 UTC, oafischer commented
Thanks for catching that one @dockerymick, I did miss that one. Are we good to merge now?

2022-08-22 20:31 UTC, dockerymick approved these changes
All good! Thanks for your patience! Approving

2022-08-22 20:43 UTC, merged