Add whats new in 2.6
open-cluster-management/rhacm-docs pull request #3908
Opened 2022-08-19 20:03 UTC by oafischer

https://github.com/stolostron/backlog/issues/24809

2022-08-19 20:33 UTC, dockerymick requested changes

2022-08-19 20:33 UTC, dockerymick commented on release_notes/whats_new.adoc
> +* The permission Cluster set `bind` grants permission to bind the cluster set to a namespace by creating a `ManagedClusterSetBinding`. See link:../multicluster_engine/cluster_lifecycle/managedcluster
I recommend using a lowercase "c" 

The permission Cluster set `bind` grants permission to bind the cluster set to a namespace by creating a `ManagedClusterSetBinding`.

TO

The permission cluster set `bind` grants permission to bind the cluster set to a namespace by creating a `ManagedClusterSetBinding`. 


Also remove the extra hashtag from the link

2022-08-19 20:33 UTC, dockerymick commented on release_notes/whats_new.adoc
> +* When you create a managed cluster, a `ManagedClusterSet` called `global` is automatically created to ease management. You cannot edit the `global` managed cluster set. See link:../multicluster_engi
I would delete the following statement: "You cannot edit the `global` managed cluster set." bc the reader will read that in the doc that you reference. In the case that a user is not reading the doc, I wonder there will still be notified about the limitation. Do you know if there will be a note in the console about not being able to edit `global`?

Remove extra hashtag

2022-08-19 20:33 UTC, dockerymick commented on release_notes/whats_new.adoc
> +* You can add multiple hosts to an infrastructure environment at the same time by selecting the **By uploading a YAML** option. See link:../multicluster_engine/cluster_lifecycle/add_hosts_infra_env.a
Remove the extra hashtag

2022-08-20 00:11 UTC, oafischer commented on release_notes/whats_new.adoc
> +* When you create a managed cluster, a `ManagedClusterSet` called `global` is automatically created to ease management. You cannot edit the `global` managed cluster set. See link:../multicluster_engi
The button to edit is just missing in the console for that specific managed cluster set. There isn't anything extra to notify the user about the limitation.

2022-08-20 00:14 UTC, oafischer commented on release_notes/whats_new.adoc
> +* You can add multiple hosts to an infrastructure environment at the same time by selecting the **By uploading a YAML** option. See link:../multicluster_engine/cluster_lifecycle/add_hosts_infra_env.a
Whoops, guess I got too carried away with copy pasting the links.

2022-08-20 00:46 UTC, dockerymick commented on release_notes/whats_new.adoc
>  For other Clusters topics, see link:../clusters/intro.adoc#managing-your-clusters[Managing your clusters].
@oafischer Just a heads up, this link is broken. I know that this is due to the MCE changes. Should this entire link be removed?

2022-08-20 00:47 UTC, dockerymick approved these changes
I made a comment about a link. I plan to start on the link issue next week if you want to move forward with the merge. Wanted to make you and Brandi aware of the link

2022-08-22 16:26 UTC, cadawson commented
I think this link is fine. It looks like it should go to the right place when it is live.

2022-08-22 16:32 UTC, merged