Adding everyTime mode
open-cluster-management/rhacm-docs pull request #3931
Opened 2022-08-22 16:26 UTC by dockerymick

https://github.com/stolostron/backlog/issues/24365

2022-08-23 22:08 UTC, ChunxiAlexLuo commented
@dockerymick I update some information and please free to polish the words.

2022-08-23 22:09 UTC, ChunxiAlexLuo requested changes
@dockerymick I update some information and please free to polish the words.

https://github.com/stolostron/rhacm-docs/pull/3931/commits/e3f42d97eea17a97e258802c6f3141b5bff72d45

2022-08-24 14:05 UTC, oafischer commented on governance/ansible_grc.adoc
> +. Set the mode to either `once`, `everyEvent` or `disabled`.
Add comma after `everyEvent`

2022-08-24 14:07 UTC, oafischer approved these changes
Thanks Mikela, good catch on the special tag colon. Just left one small comment so I'm approving.

2022-08-24 14:26 UTC, ChunxiAlexLuo approved these changes
/lgtm

2022-08-24 14:41 UTC, dockerymick commented
@oafischer @ChunxiAlexLuo Thanks to you both for your feedback, contributions, and approval. Merging this PR

2022-08-24 14:41 UTC, merged