Rough draft for backup and restore paragraph
open-cluster-management/rhacm-docs pull request #3948
Opened 2022-08-24 14:45 UTC by dockerymick

https://github.com/stolostron/backlog/issues/25148

2022-08-24 15:34 UTC, oafischer approved these changes
Looks good to me!

2022-08-24 15:35 UTC, birsanv approved these changes
lgtm

2022-08-25 14:27 UTC, birsanv requested changes
the new content looks good but it's still missing https://github.com/stolostron/cluster-backup-operator#extending-backup-data and https://github.com/stolostron/cluster-backup-operator#resources-restored-at-managed-clusters-activation-time

2022-08-25 16:55 UTC, dockerymick commented
@birsanv thanks, I think i have added the correct info now. When you have a chance will you review again. @oafischer will you also rereview?

2022-08-25 17:11 UTC, birsanv approved these changes
lgtm thanks Mikela !

2022-08-25 17:39 UTC, dockerymick commented
Thank you! @birsanv

2022-08-25 17:44 UTC, oafischer commented on backup_restore/backup_and_restore.adoc
> +Aside of these activation data resources that are identified by using the `cluster.open-cluster-management.io/backup: cluster-activation` label and stored by the `acm-resources-generic-schedule` back
Aside from these... (?)

2022-08-25 17:45 UTC, oafischer commented
Looks good @dockerymick, just left a small comment.

2022-08-25 18:12 UTC, dockerymick commented
@oafischer @birsanv Thanks for yall review! Merging this PR

2022-08-25 18:12 UTC, merged