Add Ansible credentials known issue in 2.6
open-cluster-management/rhacm-docs pull request #3954
Opened 2022-08-25 14:27 UTC by oafischer

https://github.com/stolostron/backlog/issues/25265

2022-08-25 15:57 UTC, cadawson requested changes
Thanks Oliver! A couple of suggestions, and something to make sure we are saying the same thing across the statement.

2022-08-25 15:57 UTC, cadawson commented on release_notes/known_issues.adoc
> +You cannot use Ansible Tower credentials with a host URL containing an insecure protocol (http) to create automation templates. When you use an Ansible Tower credential with an insecure protocol in t
Suggestion here for translation ease. Also "dropdown" should be "drop-down menu".

When you create an Ansible Tower automation template with the console automation flow, the Ansible Tower credential that you use must specify a host URL that uses a secure protocol (https). When you try to use an Ansible Tower credential that specifies an insecure protocol, the job list cannot be populated in the drop-down menu. To work around this issue, use a secure protocol (https) in the host URL.

2022-08-25 15:57 UTC, cadawson commented on release_notes/known_issues.adoc
> +*Note:* The console prevents you from creating Ansible Tower credentials with a host URL containing an insecure protocol, but you can still manually create or patch a resource using an insecure proto
Suggestion:
While you cannot create Ansible Tower templates from credentials with a host URL that contains an insecure protocol using the console, you can still manually create or patch a resource using an insecure protocol.

CD: Check this one. It sounds like the first statement said that you can't create templates, and the Note says that you can't create a credential. At least that is how I read it.

2022-08-25 16:08 UTC, oafischer commented on release_notes/known_issues.adoc
> +*Note:* The console prevents you from creating Ansible Tower credentials with a host URL containing an insecure protocol, but you can still manually create or patch a resource using an insecure proto
Yes that's correct. I wasn't sure if it's worth including the note at all because this known issue can only occur if the user creates the credential manually to begin with. I figured it still provides good context though. We can leave it out but I'll let @Randy424 weigh in on that.

2022-08-26 19:20 UTC, Randy424 approved these changes
/lgtm

2022-08-26 19:29 UTC, merged