stolostron/backlog#24637 add rclone restic fips
open-cluster-management/rhacm-docs pull request #3964
Opened 2022-08-26 16:59 UTC by cadawson

2022-08-30 15:44 UTC, cadawson commented
Hi @tesshuflower. Can you look through this, when you have a chance? Thanks!

2022-08-30 17:11 UTC, tesshuflower requested changes
Looks great in general Chris!  I've just made some small suggestions.

2022-08-30 17:11 UTC, tesshuflower commented on add-ons/volsync/volsync_replicate.adoc
> +VolSync does not create its own namespace, so it is in the same namespace as other {ocp-short} all-namespace operators. Any changes that you make to the operator settings for VolSync also affects the
I think this (line 27) should be somewhere under the installation section for volsync

2022-08-30 17:11 UTC, tesshuflower commented on add-ons/volsync/volsync_replicate.adoc
> +[#rsync-backup-volsync]
rsync replication (for rsync I'd rather call it replication) was already documented back in acm 2-5 - can we still use that? We could still send them to the volsync docs for extra info.

 I think also I'd like to start with the install instructions before specific steps for rsync/rclone/restic

2022-08-30 17:11 UTC, tesshuflower commented on add-ons/volsync/volsync_replicate.adoc
> +== Configuring an Rclone backup
I think for rsync/rclone we should probably use the term `replication` instead of `backup`.  restic is the one where `backup` is appropriate.

2022-08-30 17:11 UTC, tesshuflower commented on add-ons/volsync/volsync_replicate.adoc
> +Replace `rclone-secret` with the name of the secret that contains your Rclone configuration information. This value must be contained within quotation marks.
I'm not sure we need to say it needs to be within quotation marks?  I think this part is just yaml standards - so for example for this secret name they would not need to use quotation marks normally.

2022-08-30 17:11 UTC, tesshuflower commented on add-ons/volsync/volsync_replicate.adoc
> +    volumeSnapshotClassName: my-vsc
This is called `my-vsc-name` on line 556.  Maybe to be consistent just use `<my-vsc>`  and use `<>`?

2022-09-01 11:52 UTC, cadawson commented on add-ons/volsync/volsync_replicate.adoc
> +[#rsync-backup-volsync]
Yes, we can. I left the same information in rsync from the previous version. I just moved it around a little to work with the others, as well. 

Moved the install to earlier.

2022-09-01 12:09 UTC, cadawson commented on add-ons/volsync/volsync_replicate.adoc
> +Replace `rclone-secret` with the name of the secret that contains your Rclone configuration information. This value must be contained within quotation marks.
If they don't need the quotation marks, then I would suggest we leave them off of the example. They might have been used to show a variable, but we show it other ways. Let me update.

2022-09-01 12:27 UTC, cadawson commented
Thanks for the review @tesshuflower. I've updated the content with your comments. Please take a look, when you can. Thanks!

2022-09-01 20:38 UTC, tesshuflower approved these changes
/lgtm

Thanks a lot Chris!  Looks great!

2022-09-02 16:22 UTC, merged