Document addition of Hypershift clusters in 2.6
open-cluster-management/rhacm-docs pull request #4014
Opened 2022-09-01 19:15 UTC by oafischer

https://github.com/stolostron/backlog/issues/24564

2022-09-02 08:31 UTC, jelkosz requested changes
@eranco74 could you please review it too from backend perspecitve?

2022-09-02 08:31 UTC, jelkosz commented on multicluster_engine/cluster_lifecycle/create_hosted.adoc
> +* The deployed {mce} hub cluster must be able to route to the provisioning network.
Im not sure, but this sounds more like an IPI requirement.
@eranco74 wdyt?

2022-09-02 08:31 UTC, jelkosz commented on multicluster_engine/cluster_lifecycle/create_hosted.adoc
> +The release image identifies the version of the {ocp-short} image that is used to create the cluster. If the image that you want to use is not a standard image, you can enter the URL to the image tha
2 notes here:
1: you cant pick a different release image in UI for the "host inventory" clusters - you have to use some of the ones which are already listed.
2: in 2.6 the hypershift only supports 4.11+ spoke clusters, others wont install

2022-09-02 08:31 UTC, jelkosz commented on multicluster_engine/cluster_lifecycle/create_hosted.adoc
> +You must have more than one network if you are using IPv6 addresses.
UI does not have dual stack exposed - but AFAIK you can pick a single ipv6 IP so I would just remove this line. @eranco74 would it work with IPv6?

2022-09-02 08:31 UTC, jelkosz commented on multicluster_engine/cluster_lifecycle/create_hosted.adoc
> +*Note:* You do not have to run the `kubectl` command that is provided with the cluster details to import the cluster. When you create the cluster, it is automatically configured with the management o
aaactually, the import does not work automatically with hosted clusters so you have to run the provided commands to import it

2022-09-02 08:31 UTC, jelkosz commented on multicluster_engine/cluster_lifecycle/create_hosted.adoc
> +* You need an {ocp-short} image pull secret. See https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html/images/managing-images#using-image-pull-secrets[Using image pull
somewhere into the prereqs I would add that you need an infra env with hosts discovered in it ready

2022-09-02 13:25 UTC, oafischer commented on multicluster_engine/cluster_lifecycle/create_hosted.adoc
> +The release image identifies the version of the {ocp-short} image that is used to create the cluster. If the image that you want to use is not a standard image, you can enter the URL to the image tha
Thanks, I'll update this section.

2022-09-02 13:25 UTC, oafischer commented on multicluster_engine/cluster_lifecycle/create_hosted.adoc
> +*Note:* You do not have to run the `kubectl` command that is provided with the cluster details to import the cluster. When you create the cluster, it is automatically configured with the management o
What re the provided commands?

2022-09-02 19:41 UTC, cadawson approved these changes
Looks good. Thanks!

2022-09-06 16:11 UTC, eranco74 commented on multicluster_engine/cluster_lifecycle/create_hosted.adoc
> +* The deployed {mce} hub cluster must be able to route to the provisioning network.
@jelkosz is right, in the context is hypershift with agent platform there is no need for such route.
In order for the agents to be discovered, they need a route to the assisted-service, since later we have "* You need an infrastructure environment with discovered hosts." I guess we can assume such a route exists or is mentioned as requirement elsewhere

2022-09-06 17:05 UTC, eranco74 commented on multicluster_engine/cluster_lifecycle/create_hosted.adoc
> +** The host, managed hosted cluster, and its related secret must be in the same namespace.
What's this about?
Where did this requirement come from?

2022-09-06 17:05 UTC, eranco74 commented on multicluster_engine/cluster_lifecycle/create_hosted.adoc
> +** If you change your cloud provider access key, you must manually update the provisioned cluster access key. For more information, see the known issue, link:../../release_notes/known_issues.adoc#aut
I don't think there's a need for cloud provider access key..

2022-09-06 17:14 UTC, oafischer commented on multicluster_engine/cluster_lifecycle/create_hosted.adoc
> +** The host, managed hosted cluster, and its related secret must be in the same namespace.
Looks like a carryover from a different cluster type, I'll remove it.

2022-09-06 17:17 UTC, oafischer commented
Implemented your suggestions @eranco74 and @jelkosz, thanks for the feedback. Let me know if it looks good now.

2022-09-07 07:02 UTC, eranco74 commented
/lgtm

2022-09-07 07:07 UTC, avishayt commented on multicluster_engine/cluster_lifecycle/create_hosted.adoc
> +When you review your information and optionally customize it before creating the cluster, you can select *YAML: On* to view the `install-config.yaml` file content in the panel. You can edit the YAML
It is not install-config.yaml

2022-09-07 09:33 UTC, jelkosz commented on multicluster_engine/cluster_lifecycle/create_hosted.adoc
> +Proxy information that is provided in the credential is automatically added to the proxy fields. You can use the information as it is, overwrite it, or add the information if you want to enable a pro
the credentials dont contain the proxy, the infra environment does.

2022-09-07 13:06 UTC, oafischer commented on multicluster_engine/cluster_lifecycle/create_hosted.adoc
> +When you review your information and optionally customize it before creating the cluster, you can select *YAML: On* to view the `install-config.yaml` file content in the panel. You can edit the YAML
What is it instead?

2022-09-07 13:09 UTC, oafischer commented
Made more requested changes. Let me know what the correct file is instead of `install-config.yaml`.

2022-09-07 13:16 UTC, jelkosz commented on multicluster_engine/cluster_lifecycle/create_hosted.adoc
> +When you review your information and optionally customize it before creating the cluster, you can select *YAML: On* to view the `install-config.yaml` file content in the panel. You can edit the YAML
maybe just "...to view the yamls the wizard generated" or "...to view / edit what will be exactly sent to the api" or something like that?

2022-09-07 13:20 UTC, oafischer commented on multicluster_engine/cluster_lifecycle/create_hosted.adoc
> +When you review your information and optionally customize it before creating the cluster, you can select *YAML: On* to view the `install-config.yaml` file content in the panel. You can edit the YAML
So it's still a YAML file in that location but the name is always different/auto-generated? In that case I would just say: "to view the YAML files in the panel" (please confirm that it is multiple YAML files, not just one).

2022-09-07 14:13 UTC, jelkosz commented on multicluster_engine/cluster_lifecycle/create_hosted.adoc
> +When you review your information and optionally customize it before creating the cluster, you can select *YAML: On* to view the `install-config.yaml` file content in the panel. You can edit the YAML
it is multiple objects, not sure I would call them files. Maybe just yamls?

2022-09-07 14:20 UTC, oafischer commented on multicluster_engine/cluster_lifecycle/create_hosted.adoc
> +When you review your information and optionally customize it before creating the cluster, you can select *YAML: On* to view the `install-config.yaml` file content in the panel. You can edit the YAML
Actually I think the easiest might be to just say:

"to view the YAML content in the panel"

This includes singular, plural and can mean files, objects etc. Should encompass everything.

2022-09-07 14:24 UTC, jelkosz commented on multicluster_engine/cluster_lifecycle/create_hosted.adoc
> +When you review your information and optionally customize it before creating the cluster, you can select *YAML: On* to view the `install-config.yaml` file content in the panel. You can edit the YAML
+1

2022-09-07 14:25 UTC, jelkosz commented
lgtm

2022-09-08 08:59 UTC, eranco74 commented
/lgtm

2022-09-08 09:12 UTC, avishayt commented
/lgtm

2022-09-08 12:40 UTC, merged