Add missing tech preview
open-cluster-management/rhacm-docs pull request #4064
Opened 2022-09-09 18:36 UTC by oafischer

https://github.com/stolostron/backlog/issues/25677

https://coreos.slack.com/archives/GVDCLR7A5/p1662741479229929

2022-09-09 18:50 UTC, berenss requested changes

2022-09-09 18:50 UTC, berenss commented on multicluster_engine/cluster_lifecycle/scale_managed.adoc
>  You can customize and resize your managed cluster specifications, such as virtual machine sizes and number of nodes.
For clusters that were created by {product-title-short}, you can customize and resize your managed cluster specifications, such as virtual machine sizes and number of nodes.

2022-09-09 18:51 UTC, swopebe commented on multicluster_engine/cluster_lifecycle/scale_managed.adoc
>  You can customize and resize your managed cluster specifications, such as virtual machine sizes and number of nodes.
We removed all RHACM references from this book.

2022-09-09 18:52 UTC, oafischer commented on multicluster_engine/cluster_lifecycle/scale_managed.adoc
>  You can customize and resize your managed cluster specifications, such as virtual machine sizes and number of nodes.
Whoops never mind then. Let me undo it.

2022-09-09 19:41 UTC, berenss requested changes

2022-09-09 19:41 UTC, berenss commented on multicluster_engine/cluster_lifecycle/scale_managed.adoc
> +You can customize and resize your managed cluster specifications, such as virtual machine sizes and number of nodes.
we can make a note that 'for clusters you created you can customize...'

2022-09-10 04:52 UTC, berenss approved these changes

2022-09-10 17:34 UTC, merged