Add GRC config policy metric in 2.6
open-cluster-management/rhacm-docs pull request #4107
Opened 2022-09-19 14:07 UTC by oafischer

https://github.com/stolostron/backlog/issues/25514

@gparvin Wasn't sure if a new topic made sense in governance_metric.adoc or not, since that would have required the overview topic name and link and I'm trying to avoid something like that with the link issues we had recently. Still, I'll ask my team and see what they say.

2022-09-19 14:49 UTC, mprahl commented on governance/governance_metric.adoc
> +The `config_policies_evaluation_duration_` histogram tracks the number of seconds it takes to process all configuration policies on the cluster. Use the following metrics to implement the histogram:
Could this be in a new subsection?

2022-09-19 14:50 UTC, mprahl commented on governance/governance_metric.adoc
> +The `config_policies_evaluation_duration_` histogram tracks the number of seconds it takes to process all configuration policies on the cluster. Use the following metrics to implement the histogram:
```suggestion
The `config_policies_evaluation_duration_` histogram tracks the number of seconds it takes to process all configuration policies that are ready to be evaluated on the cluster. Use the following metrics to query the histogram:
```

2022-09-19 15:16 UTC, oafischer commented on governance/governance_metric.adoc
> +The `config_policies_evaluation_duration_` histogram tracks the number of seconds it takes to process all configuration policies on the cluster. Use the following metrics to implement the histogram:
Absolutely, I was thinking about that. If we make it a new subsection, we also need to either rebrand the overview or make `policy_governance_info` its own subsection as well. Do you have any preference on that?

2022-09-19 15:47 UTC, mprahl commented on governance/governance_metric.adoc
> +Use `config_policies_evaluation_duration_` to change the `ConfigurationPolicy` `evaluationInterval` setting when the time to process policies exceeds the default interval of ten seconds. To receive i
This first sentence isn't quite right. This information can be used to determine if the `ConfigurationPolicy` `spec.evaluationInterval` should be adjusted on resource intensive policies that don't require as frequent evaluation. Alternatively, the concurrency (a link here would be good) can be increased at the cost of more resource utilization on the Kubernetes API server.

2022-09-19 15:48 UTC, mprahl commented on governance/governance_metric.adoc
> +The `config_policies_evaluation_duration_` histogram tracks the number of seconds it takes to process all configuration policies on the cluster. Use the following metrics to implement the histogram:
I prefer the latter option.

2022-09-19 17:35 UTC, oafischer commented
Thanks @mprahl, I've implemented your suggestions. @dockerymick do the titles look OK? Not sure if we should use colons or not. I also wasn't sure how to handle the variable metric since it has 3 options at the end.

2022-09-19 21:15 UTC, gparvin commented
Thanks, this looks good to me.  Holding for others to take a look too.
/hold
/lgtm

2022-09-20 13:52 UTC, dockerymick requested changes
left a couple of comments

2022-09-20 13:52 UTC, dockerymick commented on governance/governance_metric.adoc
> +- `config_policies_evaluation_duration_seconds_bucket`: The buckets are cumulative and represent seconds with the following possible entries: 1, 3, 9, 10.5, 15, 30, 90, 120, 300, 450, 600, and above.
remove "above"; change that to **greater**

2022-09-20 13:52 UTC, dockerymick commented on governance/governance_metric.adoc
> +Use `config_policies_evaluation_duration_` to determine if the `ConfigurationPolicy` `evaluationInterval` setting needs to be changed for resource intensive policies that do not need frequent evaluat
extra hashtag being used in the link reference

2022-09-20 13:52 UTC, dockerymick commented on observability/observe_environments.adoc
> +|
Not sure what labels and tags should be used. If it's not applicable, we might add a dash ( - ). i am checking the style guide to verify

2022-09-21 13:10 UTC, oafischer commented on observability/observe_environments.adoc
> +|
Saw that you asked Brandy and will use None like she suggested, thanks for looking into that!

2022-09-21 13:26 UTC, oafischer commented
Made some changes, please approve if it looks good now @dockerymick @gparvin @mprahl @bjoydeep. Thanks!

2022-09-21 15:28 UTC, mprahl commented on governance/governance_metric.adoc
> +- `config_policies_evaluation_duration_seconds_bucket`: The buckets are cumulative and represent seconds with the following possible entries: 1, 3, 9, 10.5, 15, 30, 90, 120, 300, 450, 600, and greate
```suggestion
- `config_policies_evaluation_duration_seconds_bucket`: The buckets are cumulative and represent seconds with the following possible entries: 1, 3, 9, 10.5, 15, 30, 60, 90, 120, 180, 300, 450, 600, and greater.
```

2022-09-21 15:30 UTC, mprahl commented on governance/governance_metric.adoc
> +To receive information about the time used to evaluate configuration policies, use a metric that resembles the following expression:
```suggestion
To receive information about the time used to evaluate configuration policies, perform a Prometheus query that resembles the following expression:
```

2022-09-21 17:57 UTC, mprahl approved these changes
/hold for other reviews

This looks great!

2022-09-23 02:18 UTC, dockerymick approved these changes
Looks great Oliver! Just a heads up for the future, when there are more than 2 sections on the page, consider creating a table of contents for the page

2022-09-23 17:55 UTC, gparvin approved these changes
Looks good!

2022-09-23 18:00 UTC, merged