Add kubeconfig troubleshooting in 2.6
open-cluster-management/rhacm-docs pull request #4164
Opened 2022-10-04 18:54 UTC by oafischer

https://github.com/stolostron/backlog/issues/25922

2022-10-05 11:16 UTC, cadawson requested changes

2022-10-05 11:16 UTC, cadawson commented on troubleshooting/main.adoc
>  include::trouble_cluster_import_fails.adoc[leveloffset=+2]
This might need to go into the mce docs, rather than/in addition to RHACM. @skeeey is out until this weekend, so he can let us know where it makes sense.

2022-10-05 11:16 UTC, cadawson commented on troubleshooting/trouble_cluster_reimport_fails.adoc
> +[#resolving-the-problem-openstack-fails]
This might be a copy-not-changed ID. If it is, it will probably result in an error when you build. I'm guessing you intended something like: #resolving-the-problem-cluster-reimport-kubeconfig?

2022-10-05 11:16 UTC, cadawson commented on troubleshooting/trouble_cluster_reimport_fails.adoc
> +The managed cluster admin must create a new valid `kubeconfig` file for your managed cluster.
Administrator? If you are referring to a role, it's good.

2022-10-05 13:00 UTC, oafischer commented on troubleshooting/trouble_cluster_reimport_fails.adoc
> +[#resolving-the-problem-openstack-fails]
Indeed! I actually already changed it after noticing, it may have been showing you an old version for some reason.

2022-10-05 13:00 UTC, oafischer commented on troubleshooting/trouble_cluster_reimport_fails.adoc
> +The managed cluster admin must create a new valid `kubeconfig` file for your managed cluster.
@skeeey Can you clarify?

2022-10-06 18:41 UTC, cadawson commented on troubleshooting/trouble_cluster_reimport_fails.adoc
> +[#resolving-the-problem-openstack-fails]
It looks like there might still be one that did not get updated. It is still showing up when I view the changed file, and is being flagged by the linter. Please take a look. Thanks!

2022-10-06 18:43 UTC, oafischer commented on troubleshooting/trouble_cluster_reimport_fails.adoc
> +[#resolving-the-problem-openstack-fails]
Hopefully that did the trick!

2022-10-08 05:27 UTC, skeeey commented on troubleshooting/trouble_cluster_reimport_fails.adoc
> +The managed cluster admin must create a new valid `kubeconfig` file for your managed cluster.
yeah, here should be Administrator, not referring to a role

2022-10-08 05:39 UTC, skeeey commented on troubleshooting/main.adoc
>  include::trouble_cluster_import_fails.adoc[leveloffset=+2]
yeah, this should be in the mce, because this is about cluster importing

2022-10-08 09:15 UTC, skeeey commented on troubleshooting/main.adoc
>  include::trouble_cluster_import_fails.adoc[leveloffset=+2]
@cadawson @oafischer 

And I think it's better to add this to acm 2.5 and 2.4, because this problem may also occur in these versions

2022-10-09 03:28 UTC, oafischer commented on troubleshooting/main.adoc
>  include::trouble_cluster_import_fails.adoc[leveloffset=+2]
Thanks for clarifying @skeeey, I'll switch 2.6 over to MCE and add it to 2.5 and 2.4 as well.

2022-10-11 12:22 UTC, oafischer commented
I'll close this and start over, seems easier.

2022-10-11 12:22 UTC, closed without merging