Add port 8081 in 2.6
open-cluster-management/rhacm-docs pull request #4166
Opened 2022-10-05 14:37 UTC by oafischer

https://github.com/stolostron/backlog/issues/26128

2022-10-10 13:08 UTC, vthapar commented on add-ons/submariner/submariner.adoc
> +| Globalnet port
```suggestion
| Globalnet Metrics port
```

2022-10-10 13:11 UTC, vthapar requested changes

2022-10-10 13:11 UTC, vthapar commented on add-ons/submariner/submariner.adoc
> +| No
Can we add an asterix or something? Need to indicate that this is only applicable if Globalnet is enabled.

2022-10-10 13:31 UTC, oafischer commented on add-ons/submariner/submariner.adoc
> +| No
I think with some restructuring and an additional column we can make it work, let make some changes real quick.

2022-10-10 20:05 UTC, swopebe approved these changes

2022-10-10 20:05 UTC, swopebe commented on add-ons/submariner/submariner.adoc
> +| No
Please remove what is causing bold in the source (likely an asterisk or code snippet?) 
The source should match the production, that is why we use asterisks and such sparingly, it can change the source somewhere before the table.

2022-10-10 20:05 UTC, swopebe commented on add-ons/submariner/submariner.adoc
> +.Submariner ports
I am not sure that this is the way we introduce a table, and that code would be causing the bold source. I see many things wrong with how this topic is built but will send an issue to @cadawson and raise the issues in Slack.

2022-10-10 20:05 UTC, swopebe commented on add-ons/submariner/submariner.adoc
> +.Submariner ports
If you can fix the code on this snippet, I will approve.

2022-10-10 20:07 UTC, oafischer commented
Merging since the one dev comment that was left has been addressed.

2022-10-10 20:07 UTC, merged

2022-10-17 23:24 UTC, swopebe commented
Reminder for myself to open an issue to 1. look at table titles and intros and 2. rebuild if source is still showing bold and find out why.