Document MSA feature in 2.7
open-cluster-management/rhacm-docs pull request #4223
Opened 2022-10-21 15:45 UTC by oafischer

https://github.com/stolostron/backlog/issues/26324

I added the topic at the end of the other restoring topics. Let me know if that makes sense. I also made some edits, please check for technical accuracy @birsanv. Thanks!

There is some similar information to the first paragraph already under Restoring a Backup, just as a heads up.

2022-10-21 17:00 UTC, dockerymick requested changes

2022-10-21 17:00 UTC, dockerymick commented on backup_restore/manage_backup_restore.adoc
> +Only managed clusters connected with the primary hub cluster using the Hive API are automatically connected with the new hub cluster where the activation data is restored. These clusters have been cr
Only managed clusters connected with the primary hub cluster using the Hive API are automatically connected with the new hub cluster, where the activation data is restored.

2022-10-21 17:00 UTC, dockerymick commented on backup_restore/manage_backup_restore.adoc
> +The hive managed clusters can be connected with the new hub cluster because hive stores the managed cluster 'kubeconfig' under the managed cluster's namespace on the hub. This is backed up and restor
The Hive managed clusters can be connected with the new hub cluster because Hive stores the managed cluster `kubeconfig` in the managed cluster namespace on the hub cluster.

Replace the 'single quotes' with the `backward tick mark`

change hive to Hive

2022-10-21 17:00 UTC, dockerymick commented on backup_restore/manage_backup_restore.adoc
> +To reconnect imported clusters on the new hub cluster, manually create the 'auto-import-secret' after the restore operation is executed. See link:../multicluster_engine/cluster_lifecycle/import_cli.a
To reconnect imported clusters on the new hub cluster, manually create the `auto-import-secret` resource after you start the restore operation.

2022-10-21 17:00 UTC, dockerymick commented on backup_restore/manage_backup_restore.adoc
> +Create the 'auto-import-secret' under the managed cluster namespace for each cluster in 'Pending Import' state using a 'kubeconfig' or token with enough permissions for the import component to start
remove under 

Create the `auto-import-secret` resource in the managed cluster namespace for each cluster in `Pending Import` state by using a `kubeconfig`, or token with enough permissions for the import component to start the automatic import on the new hub cluster.

2022-10-21 17:16 UTC, oafischer commented
Implemented your edits, thanks @dockerymick! Going to wait for technical review now.

2022-10-21 18:30 UTC, oafischer commented
I see now how it fits together, the paragraph I had concerns about is being address via this issue now: https://github.com/stolostron/backlog/issues/26005

So it will all work out.

2022-10-21 18:49 UTC, birsanv requested changes

2022-10-21 18:49 UTC, birsanv commented on backup_restore/manage_backup_restore.adoc
> +=== Restoring imported managed clusters (Technology Preview)
@oafischer Although this section content is valid, it is not talking about the Auto import feature implemented as Tech Preview in 2.7, [using the MSA ](https://github.com/stolostron/cluster-backup-operator#automatically-connecting-clusters-using-managedserviceaccount---tech-preview)

So you should remove the Technology Preview from the title; the current content is valid as a o workaround .. if you don't want or can't use the MSA account
We can have a quick chat if it's still not clear

2022-10-21 18:49 UTC, birsanv commented on backup_restore/manage_backup_restore.adoc
> +=== Restoring imported managed clusters (Technology Preview)
This content can go in bot 2.5, 2.6, 2.7
For 2.7 though we add [this](https://github.com/stolostron/cluster-backup-operator#automatically-connecting-clusters-using-managedserviceaccount---tech-preview). - [parent section being this ](https://github.com/stolostron/cluster-backup-operator#restoring-imported-managed-clusters)

2022-10-21 19:00 UTC, oafischer commented on backup_restore/manage_backup_restore.adoc
> +=== Restoring imported managed clusters (Technology Preview)
Makes sense, thanks for clarifying @birsanv! I already updated the other PR, I will update this one later and let you know once it's done for another review.

2022-10-24 13:52 UTC, oafischer commented
This depends on content from https://github.com/stolostron/rhacm-docs/pull/4224 so I'll close this PR and start over to avoid merge conflicts.

2022-10-24 13:52 UTC, closed without merging