Document auto-import in 2.7
open-cluster-management/rhacm-docs pull request #4224
Opened 2022-10-21 18:40 UTC by oafischer

https://github.com/stolostron/backlog/issues/26005

2022-10-21 18:44 UTC, birsanv approved these changes
lgtm

2022-10-23 20:21 UTC, dockerymick requested changes

2022-10-23 20:21 UTC, dockerymick commented on backup_restore/manage_backup_restore.adoc
> +** <<restore-imported-managed-clusters,Restoring imported managed clusters (Technology Preview)>>
Reminder to add this to the What's new section

2022-10-23 20:21 UTC, dockerymick commented on backup_restore/manage_backup_restore.adoc
> +The Hive managed clusters can be connected with the new hub cluster because Hive stores the managed cluster `kubeconfig` under the managed cluster's namespace on the hub cluster. This is backed up an
Remove "under" 
remove possessive (cluster's) : https://www.ibm.com/docs/en/ibm-style?topic=grammar-possessives

I recommend the following change: 

The Hive managed clusters can be connected with the new hub cluster because Hive stores the managed cluster `kubeconfig` in the managed cluster namespace on the hub cluster.

2022-10-23 20:21 UTC, dockerymick commented on backup_restore/manage_backup_restore.adoc
> +Create the `auto-import-secret` resource in the managed cluster namespace for each cluster in `Pending Import` state using a `kubeconfig` or token with enough permissions for the import component to
The first sentence seems like a run-on sentence

2022-10-23 20:21 UTC, dockerymick approved these changes
Left some comments, thanks for making the changes Oliver!

2022-10-24 13:53 UTC, merged