Document MSA feature in 2.7 (Fixed version)
open-cluster-management/rhacm-docs pull request #4234
Opened 2022-10-24 20:22 UTC by oafischer

https://github.com/stolostron/backlog/issues/26324

I have 2 concerns:

The limitations section seems like it should belong into known issues. Does it make sense to move it there? I left it in here for the moment.

This new section is rather long and quite convoluted. I think the entire file needs its architecture reevaluated. Some of these topics should probably go into their own files. Not something for now, but I'd like to discuss that in the future.

2022-10-25 14:23 UTC, dockerymick requested changes

2022-10-25 14:23 UTC, dockerymick commented on backup_restore/manage_backup_restore.adoc
> +==== Automatically connecting clusters by using a Managed Service Account (Technology Preview)
Be sure to add the childlink to the TOC at the beginning of the doc, I believe I also forgot to add a link to the "Restoring imported managed clusters" section. Can you add that to the list as well?

2022-10-25 14:23 UTC, dockerymick commented on backup_restore/manage_backup_restore.adoc
> +==== Automatically connecting clusters by using a Managed Service Account (Technology Preview)
does Managed Service Account need to the capitalized?

2022-10-25 14:23 UTC, dockerymick commented on backup_restore/manage_backup_restore.adoc
> +The backup controller implements a solution to automatically connect imported clusters on the new hub cluster. Automatic connection uses the link:../https://github.com/open-cluster-management-io/mana
Throughout the doc, we are using **backup component** and **backup operator** interchangeably. I would reconsider using "controller". Just want to be consistent. 

The link reference needs to be updated:

link:https://github.com/open-cluster-management-io/managed-serviceaccount[Managed Service Account]

I suggest the following change:

Use the Managed Service Account component on the primary hub cluster to automatically connect imported clusters to the new hub cluster.  You must create a token for each imported cluster, which is backed up in each managed cluster namespace. Update the `klusterlet-bootstrap-kubeconfig` `ClusterRole` to enable access to the token during the import operation. The `klusterlet-bootstrap-kubeconfig` `ClusterRole` can only get or update the `bootstrap-hub-kubeconfig` secret.

I recommend these changes based on the [Anthropomorphism guidance in the style guide](https://www.ibm.com/docs/en/ibm-style?topic=grammar-anthropomorphism)

2022-10-25 14:23 UTC, dockerymick commented on backup_restore/manage_backup_restore.adoc
> +When the activation data is restored on the new hub cluster, the restore controller runs a post restore operation and looks for all managed clusters in the `Pending Import` state. If there is a valid
Does the user have to run the restore operation manually or does it run automatically? 

(if manual) I recommend the following updates: 

When the activation data is restored on the new hub cluster, use the restore operator to run a post restore operation and view all managed clusters in the `Pending Import` state. If there is a valid token generated by the Managed Service Account, the controller creates an `auto-import-secret` by using the token. As a result, the import component tries to reconnect with the managed cluster. The token is only created if the managed cluster is accessible when you create the Managed Service Account, otherwise it is created later once the the managed cluster becomes available.

2022-10-25 14:23 UTC, dockerymick commented on backup_restore/manage_backup_restore.adoc
> +
Be sure to add this section to the TOC at the beginning of this doc

2022-10-25 14:23 UTC, dockerymick commented on backup_restore/manage_backup_restore.adoc
> +
I recommend the following update:

. Enable the Managed Service Account component by listing `managedserviceaccount-preview` in the `MultiClusterEngine` resource. See the following example:


How will the user view this resource? Will they need to run a specific command to access this resource? If yes, we should doc the command that they need to run

2022-10-25 14:23 UTC, dockerymick commented on backup_restore/manage_backup_restore.adoc
> +. Enable the automatic import feature for the `BackupSchedule.cluster.open-cluster-management.io` resource. See the following example:
I recommend the following update: 

Enable the automatic import feature for the `BackupSchedule.cluster.open-cluster-management.io` resource by setting the `useManagedServiceAccount` parameter to `true`. See the following example:

2022-10-25 14:23 UTC, dockerymick commented on backup_restore/manage_backup_restore.adoc
> +After you set `useManagedServiceAccount` to `true`, the backup controller starts processing imported managed clusters. The backup controller creates the following for each imported managed cluster:
I recommend the following update:

After you enable the automatic import feature, the backup component starts processing imported managed clusters.

2022-10-25 14:23 UTC, dockerymick commented on backup_restore/manage_backup_restore.adoc
> +The `ManagedServiceAccount` resource creates a token on the managed cluster that is also called `ManagedServiceAccount`. The token is then pushed to the hub cluster in the managed cluster namespace.
I recommend removing the following statement since something similar is mentioned earlier: 

"The token is only created if the managed cluster is accessible when you create the Managed Service Account, otherwise it is created later once the the managed cluster becomes available."

2022-10-25 14:23 UTC, dockerymick commented on backup_restore/manage_backup_restore.adoc
> +The default value is `false`. After setting the value to `false`, the backup controller removes all created resources, including `ManagedServiceAddon`, `ManagedServiceAccount`, and `ManifestWork`. Re
Removing the resources deletes the automatic import token on the hub cluster and managed cluster.

2022-10-25 14:23 UTC, dockerymick commented on backup_restore/manage_backup_restore.adoc
> +
I recommend that you move this section to the [Known issue and limitations doc. I would add it as a subsection to the [Backup and restore section](https://github.com/stolostron/rhacm-docs/blob/2.7_stage/release_notes/known_issues.adoc#backup-known-issues)

2022-10-25 14:45 UTC, oafischer commented on backup_restore/manage_backup_restore.adoc
> +==== Automatically connecting clusters by using a Managed Service Account (Technology Preview)
It's the name of the component and it's capitalized in its own docs so I just followed that.

2022-10-25 14:53 UTC, dockerymick commented on backup_restore/manage_backup_restore.adoc
> +==== Automatically connecting clusters by using a Managed Service Account (Technology Preview)
Gotchu, sounds good to me

2022-10-25 17:04 UTC, oafischer commented on backup_restore/manage_backup_restore.adoc
> +When the activation data is restored on the new hub cluster, the restore controller runs a post restore operation and looks for all managed clusters in the `Pending Import` state. If there is a valid
I checked again, it's not clear if it's manual or not. Maybe @birsanv can provide some insight?

2022-10-25 17:11 UTC, oafischer commented on backup_restore/manage_backup_restore.adoc
> +
@birsanv Does the user need to run a specific command here?

2022-10-25 17:17 UTC, oafischer commented
Thanks for the detailed feedback @dockerymick! I've addressed what I could and pulled in @birsanv where I need help.

2022-10-26 17:19 UTC, dockerymick approved these changes
Made one more comment, however I am good with your changes here.

2022-10-26 17:19 UTC, dockerymick commented on backup_restore/manage_backup_restore.adoc
> +*** <<auto-connect-clusters-managed-service-account-tech-pre,Automatically connecting clusters by using a Managed Service Account (Technology Preview)>>
I would reconsider shortening the anchor. Maybe just use `auto-connect-clusters-managed-service-account` or `auto-connect-clusters-msa`. If you do decide to update the anchor, remember to update the section too

2022-10-26 17:21 UTC, oafischer commented on backup_restore/manage_backup_restore.adoc
> +*** <<auto-connect-clusters-managed-service-account-tech-pre,Automatically connecting clusters by using a Managed Service Account (Technology Preview)>>
`auto-connect-clusters-msa` is a good one, I'll use that. Thanks!

2022-10-26 17:23 UTC, oafischer commented
Thanks @dockerymick! I'll wait for @birsanv to approve before merging.

2022-10-26 19:02 UTC, birsanv requested changes

2022-10-26 19:02 UTC, birsanv commented on backup_restore/manage_backup_restore.adoc
> +Use the link:https://github.com/open-cluster-management-io/managed-serviceaccount[Managed Service Account] component on the primary hub cluster to automatically connect imported clusters to the new h
@dockerymick I don't really agree with the way this information is presented .. 
It is as if the user must do all this things, which is not the case - this is the whole point, the backup component does all this for the user , automatically ..

By saying `You must create a token..` we lost the automatic , done for you by the controller story. It should say `The backup controller implements a solution to automatically connect imported clusters on the new hub.` 

Not sure how to better rephrase this, other then pointing to the readme :) 
https://github.com/stolostron/cluster-backup-operator#automatically-connecting-clusters-using-managedserviceaccount---tech-preview

_The backup controller implements a solution to automatically connect imported_ ...

2022-10-26 19:02 UTC, birsanv commented on backup_restore/manage_backup_restore.adoc
> +When the activation data is restored on the new hub cluster, the restore controller runs a post restore operation and looks for all managed clusters in the `Pending Import` state. If there is a valid
Restore is invoked by the user, by creating a `Restore` resource.
So I'd say the restore is still automatic .. 

I find this confusing : 
When the activation data is restored on the new hub cluster, use the restore operator to run a post restore operation and view all managed clusters in the Pending Import state.

`use the restore operator` - you are already using it since you said `When the activation data is restored`

2022-10-26 19:02 UTC, birsanv commented on backup_restore/manage_backup_restore.adoc
> +
@oafischer no specific command, just regular update of a resource, can be done through OCP ui or command line, nothing to document here.

@dockerymick why do we want to say `Enable the Managed Service Account component by listing` ? that option is already there, we just switch the `enabled` value to true or false

2022-10-26 19:19 UTC, oafischer commented on backup_restore/manage_backup_restore.adoc
> +Use the link:https://github.com/open-cluster-management-io/managed-serviceaccount[Managed Service Account] component on the primary hub cluster to automatically connect imported clusters to the new h
Hmm I think we can leave out "implements a solution" and just directly say

"The backup controller automatically connects imported clusters on the new hub cluster."

Does that work @birsanv @dockerymick?

2022-10-26 19:21 UTC, birsanv commented on backup_restore/manage_backup_restore.adoc
> +Use the link:https://github.com/open-cluster-management-io/managed-serviceaccount[Managed Service Account] component on the primary hub cluster to automatically connect imported clusters to the new h
@oafischer that would work for me

2022-10-26 19:23 UTC, birsanv commented on backup_restore/manage_backup_restore.adoc
> +Use the link:https://github.com/open-cluster-management-io/managed-serviceaccount[Managed Service Account] component on the primary hub cluster to automatically connect imported clusters to the new h
@oafischer I mean I assume this would be something like 

"The backup controller automatically connects imported clusters on the new hub cluster using the link:https://github.com/open-cluster-management-io/managed-serviceaccount[Managed Service Account] component... etc

2022-10-26 19:27 UTC, birsanv commented on backup_restore/manage_backup_restore.adoc
> +Use the link:https://github.com/open-cluster-management-io/managed-serviceaccount[Managed Service Account] component on the primary hub cluster to automatically connect imported clusters to the new h
What about 

"The backup controller automatically connects imported clusters on the new hub cluster using the link:[https://github.com/open-cluster-management-io/managed-serviceaccount[Managed](https://github.com/open-cluster-management-io/managed-serviceaccount%5BManaged) Service Account] component.
The MaangedServiceAccount creates a token for each imported cluster in each managed cluster namespace., which is backed up. This token is set to use a klusterlet-bootstrap-kubeconfig ClusterRole binding, which allows the token to be used by an auto import operation. The klusterlet-bootstrap-kubeconfig ClusterRole can only get or update the bootstrap-hub-kubeconfig secret.
When the activation data is restored on the new hub, the restore controller runs a post restore operation and looks for all managed clusters in Pending Import state. For these managed clusters, it checks if there is a valid token generated by the ManagedServiceAccount and if found, it creates an auto-import-secret using this token. As a result, the import component will try to reconnect the managed cluster and if the cluster is accessible the operation should be successful.

2022-10-26 19:43 UTC, dockerymick commented on backup_restore/manage_backup_restore.adoc
> +Use the link:https://github.com/open-cluster-management-io/managed-serviceaccount[Managed Service Account] component on the primary hub cluster to automatically connect imported clusters to the new h
@birsanv Thanks for clarifying ! From. my perspective, I wanted to put emphasis on the requirement. i agree that writing "You must.." suggests that the user needs to do some manual work, which is not the case for this. 

I like your suggestion. I recommend that we prompt the user for the link reference. The link might distract the reader. i recommend that we add the reference link for Managed Service Account be placed at the end of the paragraph.

Let's be sure to use "automatic import" instead of _auto import_

2022-10-26 19:47 UTC, oafischer commented on backup_restore/manage_backup_restore.adoc
> +Use the link:https://github.com/open-cluster-management-io/managed-serviceaccount[Managed Service Account] component on the primary hub cluster to automatically connect imported clusters to the new h
I implemented most of your suggestion, let me know if it looks good now. Thanks!

2022-10-26 19:49 UTC, birsanv commented on backup_restore/manage_backup_restore.adoc
> +When the activation data is restored on the new hub cluster, the restore controller runs a post restore operation and looks for all managed clusters in the `Pending Import` state. If there is a valid
small typo 

If there is a valid token generated by the Managed Service Account is found

should be 

If a valid token generated by the Managed Service Account is found

2022-10-26 19:49 UTC, dockerymick commented on backup_restore/manage_backup_restore.adoc
> +
Understood. I thought the user needed to update the resource to enable it, Thanks for clarifying. I recommend this instead:

Enable the Managed Service Account component by setting the `enabled` parameter to `true`.

2022-10-26 19:55 UTC, birsanv requested changes

2022-10-26 19:55 UTC, birsanv commented on backup_restore/manage_backup_restore.adoc
> +
@oafischer this is still not addressed 

why do we want to say Enable the Managed Service Account component by listing ? that option is already there, we just switch the enabled value to true or false

I suggest to replace 

Enable the Managed Service Account component by listing

with 

Enable the Managed Service Account component by setting the `managedserviceaccount-preview` component's enable option to `true`

2022-10-26 19:55 UTC, birsanv commented on release_notes/known_issues.adoc
> +- The auto import operation fails when you run the restore operation while the `auto-import-account` token is valid and backed up but the backup with the token has expired. The `restore.cluster.open-
This is confusing

I want to say : 
"If the auto-import-account secret token is valid and is backed up but the restore operation is run at a time when the token available with the backup has already expired"

2022-10-26 20:06 UTC, birsanv requested changes

2022-10-26 20:06 UTC, birsanv commented on release_notes/known_issues.adoc
> +- The auto import operation fails the `auto-import-account` secret token is valid and is backed up but the restore operation is run when the token available with the backup has already expired. The `
@oafischer small typo :) great otherwise !

This 
The auto import operation fails the ...

Should be 

The auto import operation fails IF the ...

2022-10-26 20:16 UTC, birsanv approved these changes
lgtm

2022-10-26 20:20 UTC, oafischer commented
Thanks @dockerymick and @birsanv for your help with this PR! I've also implemented the suggestions from here while this is open: https://github.com/stolostron/backlog/issues/26593

I think I addressed all the comments and typos as well. If either of you wants to take one last quick look at everything I'd appreciate it, otherwise I plan to merge tomorrow morning. Thanks again!

2022-10-26 20:23 UTC, birsanv requested changes

2022-10-26 20:23 UTC, birsanv commented on release_notes/known_issues.adoc
> +When a cluster is imported on the hub cluster, the `apiserver` is only set up automatically on {ocp} clusters You must set the `apiserver` manually on other types of managed clusters, such as EKS clu
Typo : 
You must

. You must

2022-10-26 20:23 UTC, birsanv commented on release_notes/known_issues.adoc
> +When a cluster is imported on the hub cluster, the `apiserver` is only set up automatically on {ocp} clusters You must set the `apiserver` manually on other types of managed clusters, such as EKS clu
As a result, the clusters remain in the `Pending Import` state when you moved them to the import hub cluster.

should be 

As a result, the clusters remain in the `Pending Import` state when you moved them to the restore hub cluster.

2022-10-26 20:33 UTC, birsanv approved these changes
lgtm

2022-10-27 12:36 UTC, merged