Update clean up in 2.7
open-cluster-management/rhacm-docs pull request #4242
Opened 2022-10-25 19:45 UTC by oafischer

https://github.com/stolostron/backlog/issues/26291

2022-10-25 20:03 UTC, birsanv requested changes

2022-10-25 20:03 UTC, birsanv commented on backup_restore/manage_backup_restore.adoc
> +- `CleanupRestored`: Clean up all resources created by a previous {product-title-short} restore that are not part of the currently restored backup.
sorry, @oafischer , I decided to add backup the `CleanupAll` option; it was used by a customer so I wanted to be backward compatible

As a result , add this content as a third bullet : 
- CleanupAll : clean up all resources on the hub which could be part of a {product-title-short} backup, even if they were not created as a result of a restore operation. This is to be used when content has been created on this hub before the restore operation is executed. Use this option with extreme caution as this will also cleanup resources on the hub created by the user, not just by a previously restored backup. It is strongly recommended to use the CleanupRestored option instead and to refrain from manually updating hub content when the hub is designated as a passive candidate for a disaster scenario. Use a clean hub as a passive cluster. Avoid situations where you have to swipe the cluster using the CleanupAll option; this is given as a last alternative.

2022-10-25 20:06 UTC, oafischer commented on backup_restore/manage_backup_restore.adoc
> +- `CleanupRestored`: Clean up all resources created by a previous {product-title-short} restore that are not part of the currently restored backup.
No worries! I'll add it back. Thanks for letting me know.

2022-10-26 16:38 UTC, dockerymick commented on backup_restore/manage_backup_restore.adoc
> +Velero updates existing resources if they have changed with the currently restored backup. Velero does not clean up delta resources, which are resources created by a previous restore and not part of
Is 'delta' a resource kind? Should this be monospaced?

Also I suggest the following update:

This limits the scenarios you can use when restoring hub cluster data on a new hub cluster.

2022-10-26 16:41 UTC, dockerymick commented on backup_restore/manage_backup_restore.adoc
> +- `CleanupAll`: Clean up all resources on the hub cluster that might be part of a {product-title-short} backup, even if they were not created as a result of a restore operation. This is to be used wh
I suggest the following update: 

This is to be used when extra content is created on a hub cluster before the restore operation starts.

2022-10-26 16:42 UTC, dockerymick approved these changes
Made a couple of comments. Thanks for making the changes !

2022-10-26 17:16 UTC, oafischer commented on backup_restore/manage_backup_restore.adoc
> +Velero updates existing resources if they have changed with the currently restored backup. Velero does not clean up delta resources, which are resources created by a previous restore and not part of
Couldn't find any references to delta resources in our or other docs for verification. @birsanv Can you chime in?

2022-10-26 17:19 UTC, birsanv commented on backup_restore/manage_backup_restore.adoc
> +Velero updates existing resources if they have changed with the currently restored backup. Velero does not clean up delta resources, which are resources created by a previous restore and not part of
Delta in not a resource;  delta resources = extra resources created by a previous restore and not part of the currently restored backup.

2022-10-27 12:52 UTC, oafischer commented
Addressed all the comments, does it look good now @birsanv?

2022-10-27 12:55 UTC, birsanv approved these changes
lgtm

2022-10-27 12:57 UTC, merged