Document ARO and ROSA deployment for Subm in 2.7
open-cluster-management/rhacm-docs pull request #4280
Opened 2022-11-02 20:18 UTC by oafischer

https://github.com/stolostron/backlog/issues/26428

I added these topics to the manual deployment section for now because it is still not clear if the corresponding UI changes will make it into the release.

2022-11-03 00:26 UTC, swopebe commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +
Ensure we are able to use ROSA -- see product guidance.

2022-11-03 00:36 UTC, swopebe approved these changes
A few edits:

One of the code blocks was off, when I fixed it, the code looks correct. I also removed a bullet a because there was not a bullet b- I just indented it. Looks great!

2022-11-03 01:13 UTC, oafischer commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +
ROSA is allowed but ARO isn't. I already reached out earlier about possibly having it changed but for now we'll have to spell out ARO.

2022-11-03 05:15 UTC, nyechiel commented
This looks great, thanks Oliver! @yboaron can you please review? 

Note: we may want to wait with merging this until we have more clarity on whether or not we have better console integration.

2022-11-03 05:18 UTC, nyechiel commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +* _Secret access key_
This one specifically is something we want to better address with Console integration, so that users won't have to enter "dummy" parameters.

2022-11-03 05:18 UTC, nyechiel commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +* *Tenant ID*
This one specifically is something we want to better address with Console integration, so that users won't have to enter "dummy" parameters.

2022-11-03 12:49 UTC, cadawson requested changes
Comment, and will edit some typo and style things. Thanks!

2022-11-03 12:49 UTC, cadawson commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +[#preparing-aro-tp]
Just a consideration here: By adding the "tp" to the target here, we might have to change it if it gets to GA version. Leaving is not a big deal, but it wouldn't make any sense anymore.

2022-11-03 13:15 UTC, cadawson requested changes
A few more comments. Otherwise, looks good! Thanks!

2022-11-03 13:15 UTC, cadawson commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +. Click *Next* to continue to the *Configure clusters* page and enter `dummy` in the following fields:
I see what we are doing with `dummy` here, but could we use a different term? Can we use something like `placeholder` or `null` or something that might be easier for translation and with a little kinder feeling? :-) If there is a reason for it, I can live with it.

2022-11-03 13:15 UTC, cadawson commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +. Click *Next* to continue to the *Configure clusters* page and enter `dummy` in the following fields:
Same as above: I see what we are doing with `dummy` here, but could we use a different term? Can we use something like `placeholder` or `null` or something that might be easier for translation and with a little kinder feeling? :-) If there is a reason for it, I can live with it.

2022-11-03 13:15 UTC, oafischer commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +[#preparing-aro-tp]
Good point, I'll remove it.

2022-11-03 13:17 UTC, oafischer commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +. Click *Next* to continue to the *Configure clusters* page and enter `dummy` in the following fields:
`dummy` might be a specific parameter, is there an alternative we can use @nyechiel @yboaron?

2022-11-03 13:39 UTC, yboaron commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +The Microsoft Azure Red Hat OpenShift service combines various tools and resources to help simplify the process of building conatiner-based applications. To prepare Azure Red Hat OpenShift clusters f
Generating Kubeconfig for ARO cluster is a common issue that isn't relevant only to Submariner. maybe we should just point to the relevant section of ARO official documentation?

2022-11-03 13:43 UTC, oafischer commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +The Microsoft Azure Red Hat OpenShift service combines various tools and resources to help simplify the process of building conatiner-based applications. To prepare Azure Red Hat OpenShift clusters f
We try to minimize linking as it interrupts the user whenever they have to click a link. Topics should also be self-contained and have all the information necessary to complete a task, so I'd prefer not to link to an external source in this case if that's OK.

2022-11-03 14:05 UTC, yboaron commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +. Click *Next* to continue to the *Configure clusters* page and enter `dummy` in the following fields:
No particular reason for choosing 'dummy' , in current Console code we must fill some string values in these fields (otherwise validation will fail) , IMHO 'null' is fine.

As Nir mentioned, when Console integration to better support ARO and ROSA is addressed, the user won't need to fill in these fields.

2022-11-03 14:22 UTC, oafischer commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +. Click *Next* to continue to the *Configure clusters* page and enter `dummy` in the following fields:
Thanks for clarifying that, I'll change it to `null` for now!

2022-11-03 14:54 UTC, yboaron commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +The Microsoft Azure Red Hat OpenShift service combines various tools and resources to help simplify the process of building conatiner-based applications. To prepare Azure Red Hat OpenShift clusters f
OK, anyhow this is the relevant link [1] ,  it isn't still in [learn.microsoft.com](http://learn.microsoft.com/) as it is still TP feature.

[1] 
 https://access.redhat.com/solutions/6971883

2022-11-03 15:02 UTC, yboaron commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +. Configure Submariner to use the LoadBalancer service by running the following command to edit the `submarinerconfig` CR on your Azure Red Hat OpenShift cluster:
The 'oc edit submarinerconfig -n <cluster-name> submariner' should run on the hub cluster (kubeconfig pointing to hub cluster) , we should edit the `submarinerconfig` CR representing  Azure Red Hat OpenShift cluster .

2022-11-03 15:29 UTC, oafischer commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +. Configure Submariner to use the LoadBalancer service by running the following command to edit the `submarinerconfig` CR on your Azure Red Hat OpenShift cluster:
Thanks, fixed it!

2022-11-03 15:57 UTC, yboaron commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +----
Maybe it worth to add also the 'Source and use the Kubeconfig' section from here : https://access.redhat.com/solutions/6971883

2022-11-03 16:08 UTC, sridhargaddam commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +. Run the following command to verfiy that the CLI extension is being used:
```suggestion
. Run the following command to verify that the CLI extension is being used:
```

2022-11-03 16:09 UTC, sridhargaddam commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +. Run the following command to verfiy that the CLI extension is being used:
```suggestion
. Run the following command to verify that the CLI extension is being used:
```

2022-11-03 16:17 UTC, sridhargaddam commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +. Download the link:https://aka.ms/az-aroext-latest.whl[Python wheel and CLI extension].
@yboaron do we have to download any specific version of the extension or can it work with the latest (to the best of your knowledge)?

Reason I'm asking this is because we had seen instances earlier (i think for Azure infra configuration) where the commands captured in the document were not working with the latest revision.

2022-11-03 16:34 UTC, sridhargaddam commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +. Import your Azure Red Hat OpenShift cluster to your cluster list by selecting *Infrastructure* > *Clusters* > *Import an existing cluster* from the {product-title-short} console.
```suggestion
. Import your Azure Red Hat OpenShift cluster to your cluster list by selecting *Infrastructure* > *Clusters* > *Import cluster* from the {product-title-short} console.
```

Just thought of sharing one observation. Otherwise, even in the current form its readable. 
I'm looking at the latest console and see that its "Import cluster" and not "Import an existing cluster"
![Screenshot from 2022-11-03 22-02-56](https://user-images.githubusercontent.com/6574656/199779719-8364656b-ffc1-4435-a97d-a32e8af18ed1.png)

2022-11-03 16:40 UTC, sridhargaddam commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +. Navigate to *Infrastructure* > *Clusters* > *Cluster sets* and select the *Cluster list* tab. Then, select the checkbox for your Azure Red Hat OpenShift cluster that you imported and click the *Sub
```suggestion
. Navigate to *Infrastructure* > *Clusters* > *Cluster sets* and select the *ClusterSet* name, which takes you to a new page where you can select the *cluster list*. Then, select the checkbox for your Azure Red Hat OpenShift cluster that you imported and click the *Submariner add-ons* tab. 
```

2022-11-03 17:10 UTC, sridhargaddam commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +. Configure Submariner to use the LoadBalancer service by running the following command on the hub cluster to edit the `submarinerconfig` CR representing your Azure Red Hat OpenShift cluster:
```suggestion
. Configure Submariner to use the LoadBalancer service by running the following command on the hub cluster by editing the `submarinerconfig` CR representing your Azure Red Hat OpenShift cluster:
```

2022-11-03 17:15 UTC, sridhargaddam commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +submariner-gateway   LoadBalancer   172.28.171.61   20.102.24.193   4500:32323/UDP,4490:30963/UDP   2m31s
```suggestion
submariner-gateway   LoadBalancer   172.28.171.61   xx.xx.xx.xx   4500:32323/UDP,4490:30963/UDP   2m31s
```

Generally its a good idea to avoid using/showing public-ips in the document.

2022-11-03 17:19 UTC, sridhargaddam commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +rosa create machinepool --cluster=<cluster_name> --name=sm-gw-mp --replicas=<number of Submariner gateway > --labels='submariner.io/gateway=true'
@yboaron did we test Loadbalancer with multiple Gateway nodes?

2022-11-03 17:23 UTC, sridhargaddam commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +. To verify that Submariner is using the LoadBalancer service, run the following command on your Azure Red Hat OpenShift cluster:
@yboaron we should manually label one (or more) of the nodes as Gateway node right?

2022-11-03 17:26 UTC, sridhargaddam commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +oc login https://api.ybb-rosa.ix7w.p1.openshiftapps.com:6443 --username cluster-admin --password <password>
```suggestion
oc login <rosa-cluster-url>:6443 --username cluster-admin --password <password>
```

@yboaron it should actually be replaced with the rosa-cluster-url right?

2022-11-03 17:26 UTC, sridhargaddam commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +. Import your ROSA cluster to your cluster list by selecting *Infrastructure* > *Clusters* > *Import an existing cluster* from the console.
as above

2022-11-03 17:28 UTC, sridhargaddam commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +. Navigate to *Infrastructure* > *Clusters* > *Cluster sets* and select the *Cluster list* tab. Then, select the checkbox for your ROSA cluster that you imported and click the *Submariner add-ons* ta
as above

2022-11-03 17:29 UTC, sridhargaddam commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +Follow the instructions in the console to complete the install.
```suggestion
Follow the instructions in the console to complete the installation.
```

2022-11-03 17:29 UTC, sridhargaddam commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +. Configure Submariner to use the LoadBalancer service by running the following command on the hub cluster to edit the `submarinerconfig` CR representing your ROSA cluster:
```suggestion
. Configure Submariner to use the LoadBalancer service by running the following command on the hub cluster by editing the `submarinerconfig` CR representing your ROSA cluster:
```

2022-11-04 03:26 UTC, oafischer commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +. Navigate to *Infrastructure* > *Clusters* > *Cluster sets* and select the *Cluster list* tab. Then, select the checkbox for your Azure Red Hat OpenShift cluster that you imported and click the *Sub
I just went through the console and realized it's actually even simpler. I rewrote the steps, let me know if they look good now. Thanks!

2022-11-06 09:08 UTC, yboaron commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +. Download the link:https://aka.ms/az-aroext-latest.whl[Python wheel and CLI extension].
As this issue isn't Submariner specific [I thought that we should point to the relevant ARO documentation](https://github.com/stolostron/rhacm-docs/pull/4280#discussion_r1012913194) to avoid incompatibility.

As per ARO documentation, this feature is still TP and it is documented [here](https://access.redhat.com/solutions/6971883) , and yeah as you mentioned ARO documentation pointing to latest version ('Install latest AZ CLI ARO extension') and not to specific minimum version

2022-11-06 09:17 UTC, yboaron commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +. To verify that Submariner is using the LoadBalancer service, run the following command on your Azure Red Hat OpenShift cluster:
Hmm, yeah, it makes sense, but I don't remember that I labeled a node when I tested it (maybe label was set when I tested it with subctl ).

Q: When Submariner is deployed using subctl we can label a node also at 'subctl join' phase, is there something equivalent also in ACM deployment path?

2022-11-06 09:47 UTC, yboaron commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +rosa create machinepool --cluster=<cluster_name> --name=sm-gw-mp --replicas=<number of Submariner gateway > --labels='submariner.io/gateway=true'
@sridhargaddam Yep, tested it on ROSA

2022-11-07 13:23 UTC, yboaron commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +. To verify that Submariner is using the LoadBalancer service, run the following command on your Azure Red Hat OpenShift cluster:
I just rechecked this issue and it seems that explicit node labeling to serve as Submariner gateway is needed as @sridhargaddam mentioned. so, user should also label one of the worker nodes by running the: 
$  oc  label nodes <node_name>  submariner.io/gateway=true

2022-11-07 17:41 UTC, sridhargaddam commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +. Download the link:https://aka.ms/az-aroext-latest.whl[Python wheel and CLI extension].
Okay, thanks for the details.

2022-11-07 17:47 UTC, sridhargaddam commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +. Navigate to *Infrastructure* > *Clusters* > *Cluster sets* and click your Azure Red Hat OpenShift cluster. Then, click the *Submariner add-ons* tab.
```suggestion
. Navigate to *Infrastructure* > *Clusters* > *Cluster sets* and click on the clusterSet. Then, click the *Submariner add-ons* tab. 
```

2022-11-07 17:50 UTC, sridhargaddam commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +. Navigate to *Infrastructure* > *Clusters* > *Cluster sets* and click your ROSA cluster. Then, click the *Submariner add-ons* tab.
```suggestion
. Navigate to *Infrastructure* > *Clusters* > *Cluster sets* and click on the clusterSet name. Then, click the *Submariner add-ons* tab. 
```

2022-11-07 18:15 UTC, oafischer commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +. Navigate to *Infrastructure* > *Clusters* > *Cluster sets* and click your Azure Red Hat OpenShift cluster. Then, click the *Submariner add-ons* tab.
Is clusterSet a button? Is it a general button or does it relate to the ARO cluster?

2022-11-08 13:14 UTC, yboaron commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +. Label one of the nodes as a Gateway node by running the following command.
This step should be done before deploying Submariner , should be between step 7 and step 8

2022-11-08 13:20 UTC, oafischer commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +. Label one of the nodes as a Gateway node by running the following command.
Fixed, thanks for catching that!

2022-11-08 13:20 UTC, nyechiel commented
@oafischer FYI here is the related console PR: https://github.com/stolostron/console/pull/2245. When it gets merged, the need to manually enter 'null' settings should go away.

2022-11-08 13:24 UTC, yboaron commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +. Click *Next* to continue to the *Configure clusters* page and enter `null` in the following fields:
After merging [this PR](https://github.com/stolostron/console/pull/2245) it will not be needed to fill in these fields

2022-11-08 13:24 UTC, oafischer commented
Thanks @nyechiel! I'll keep an eye on it.

2022-11-08 13:25 UTC, yboaron commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +. Click *Next* to continue to the *Configure clusters* page and enter `null` in the following fields:
After merging [this PR](https://github.com/stolostron/console/pull/2245) it will not be needed to fill in these fields

2022-11-11 06:07 UTC, sridhargaddam commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +. Navigate to *Infrastructure* > *Clusters* > *Cluster sets* and click your Azure Red Hat OpenShift cluster. Then, click the *Submariner add-ons* tab.
When we navigate to *Infrastructure* > *Clusters* > *Cluster sets*, it will list the current <clusterSets> on the Hub. So, the user is expected to click on the relevant "clusterSet" he is working on which will then display the *Submariner add-ons* tab associated with the "clusterSet"

2022-11-11 13:13 UTC, oafischer commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +. Navigate to *Infrastructure* > *Clusters* > *Cluster sets* and click your Azure Red Hat OpenShift cluster. Then, click the *Submariner add-ons* tab.
Hmm I don't seem to see any clusterSet here, just the default cluster. So I assume when the user has created an ARO cluster, it will appear there like the default cluster and you need to click it to get to the next step. At least that's how to get there with the default cluster. Is the ARO cluster different?

![image](https://user-images.githubusercontent.com/108426932/201347541-f4232f91-d810-4937-bd1f-3b2abf7d36ce.png)

2022-11-11 13:40 UTC, sridhargaddam commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +. Navigate to *Infrastructure* > *Clusters* > *Cluster sets* and click your Azure Red Hat OpenShift cluster. Then, click the *Submariner add-ons* tab.
In the above diagram "global" and "default" are clusterSets (probably they are created by default). Ideally, we should create a new ClusterSet (lets say myclusterset) and after doing that, click on the myclusterset which will take you to *Submariner add-ons* tab. 

Normally, the procedure is as follows.
1. Create a ClusterSet
2. Create/Import Clusters and add them into the ClusterSet as ManagedClusters.
3. Install submariner-addon on the ManagedClusters.

2022-11-11 13:43 UTC, oafischer commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +. Navigate to *Infrastructure* > *Clusters* > *Cluster sets* and click your Azure Red Hat OpenShift cluster. Then, click the *Submariner add-ons* tab.
I see, so would this newly created cluster-set just have a generic name or one that related to the ARO cluster?

Is it more accurate to say "your clusterSet" vs. "the clusterSet"? Meaning the user created it at some point, so it would be theirs?

2022-11-11 14:29 UTC, sridhargaddam commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +. Navigate to *Infrastructure* > *Clusters* > *Cluster sets* and click your Azure Red Hat OpenShift cluster. Then, click the *Submariner add-ons* tab.
>I see, so would this newly created ClusterSet just have a generic name or one that is related to the ARO cluster? Did the use choose the name at any point?

As you can see in the screenshot you shared above, there is an option "Create cluster set". When you click it, we can create a clusterSet with any name we want. ManagedClusters (like ROSA/ARO/AWS/GCP clusters) can then be added as members in the ManagedClusterSet. For more details, please refer to this doc - https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.6/html/multicluster_engine/multicluster_engine_overview#managedclustersets-intro

> Is it more accurate to say "your clusterSet" vs. "the clusterSet"? Meaning the user created it at some point, so it would be theirs?

Yes, its the user created clusterSet.

2022-11-11 14:37 UTC, oafischer commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +. Navigate to *Infrastructure* > *Clusters* > *Cluster sets* and click your Azure Red Hat OpenShift cluster. Then, click the *Submariner add-ons* tab.
Thanks for the detailed explanation. I'll go with "select the name of the cluster set you want to add" since that matches what we've done in other parts of the doc.

2022-11-13 08:37 UTC, yboaron commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +. Download the link:https://aka.ms/az-aroext-latest.whl[Python wheel and CLI extension].
If we don't want to point to ARO documentation from ACM documentation, I think we can resolve this comment.

2022-11-13 08:38 UTC, yboaron commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +. To verify that Submariner is using the LoadBalancer service, run the following command on your Azure Red Hat OpenShift cluster:
This comment was resolved.

2022-11-13 08:44 UTC, yboaron commented
PR looks good to me, I think we should wait and see if [PR that hides infra-related fields in UI for ROSA and ARO](https://github.com/stolostron/console/pull/2245) gets merged and then act accordingly.

2022-11-16 16:41 UTC, yboaron commented
> PR looks good to me, I think we should wait and see if [PR that hides infra-related fields in UI for ROSA and ARO](https://github.com/stolostron/console/pull/2245) gets merged and then act accordingly.

 [PR that hides infra-related fields in UI for ROSA and ARO](https://github.com/stolostron/console/pull/2245) got merged

2022-11-16 16:42 UTC, oafischer commented
@yboaron Awesome, thanks for keeping me updated! I'll make the necessary changes to this PR today.

2022-11-16 16:45 UTC, yboaron commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +. Click *Next* to continue to the *Configure clusters* page and enter `null` in the following fields:
We can delete step 11, just leave "Follow the instructions in the console to complete the install"

2022-11-16 16:48 UTC, yboaron commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +. Configure Submariner to use the LoadBalancer service by running the following command on the hub cluster to edit the `submarinerconfig` CR representing your Azure Red Hat OpenShift cluster:
We automated the loadbalancer mode setting in console, so for ARO and ROSA there is no need to set loadbalancedr mode manually .
This means we can delete steps 12-14

2022-11-16 16:50 UTC, yboaron commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +. Click *Next* to continue to the *Configure clusters* page and enter `null` in the following fields:
We should leave "Follow the instructions in the console to complete the installation" in step 8

2022-11-16 16:51 UTC, yboaron commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +. Configure Submariner to use the LoadBalancer service by running the following command on the hub cluster to edit the `submarinerconfig` CR representing your ROSA cluster:
We can delete steps 9-11 , check https://github.com/stolostron/rhacm-docs/pull/4280/files#r1024257448

2022-11-16 17:00 UTC, yboaron commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +. Import your Azure Red Hat OpenShift cluster to your cluster list by selecting *Infrastructure* > *Clusters* > *Import cluster* from the {product-title-short} console.
{product-title-short} ?

2022-11-16 17:51 UTC, oafischer commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +. Import your Azure Red Hat OpenShift cluster to your cluster list by selecting *Infrastructure* > *Clusters* > *Import cluster* from the {product-title-short} console.
[RHACM console](https://github.com/stolostron/rhacm-docs/blob/2.7_stage/modules/common-attributes.adoc), there's actually some discussion around that right now: https://github.com/stolostron/backlog/issues/26706#issuecomment-1317353957

But looks like it leaving it as is should be OK.

2022-11-16 18:13 UTC, yboaron commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +. Import your Azure Red Hat OpenShift cluster to your cluster list by selecting *Infrastructure* > *Clusters* > *Import cluster* from the {product-title-short} console.
Ack, 10x.
Maybe we should be consistent with the syntax for both ROSA and ARO (need to update also step 4 in ROSA )?

2022-11-16 18:15 UTC, oafischer commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +. Import your Azure Red Hat OpenShift cluster to your cluster list by selecting *Infrastructure* > *Clusters* > *Import cluster* from the {product-title-short} console.
That's a good catch, didn't see it. I'll add it there too, thanks!

2022-11-16 18:42 UTC, yboaron commented
Looks good to me.
Thanks @oafischer 
/lgtm

2022-11-16 18:43 UTC, yboaron approved these changes

2022-11-17 17:00 UTC, sridhargaddam commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +. Click the *Install Submariner add-ons* button and set your Azure Red Hat OpenShift cluster as your *Target clusters*. Follow the instructions in the console to complete the installation.
```suggestion
. Click the *Install Submariner add-ons* button and set your ROSA cluster as your *Target clusters*. Follow the instructions in the console to complete the installation.
```

2022-11-17 18:31 UTC, oafischer commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +. Click the *Install Submariner add-ons* button and set your Azure Red Hat OpenShift cluster as your *Target clusters*. Follow the instructions in the console to complete the installation.
Good catch, fixed. Thanks!

2022-11-17 19:28 UTC, sridhargaddam commented
Thanks @oafischer 

/lgtm

2022-11-17 21:24 UTC, merged

2022-11-17 21:40 UTC, swopebe commented on add-ons/submariner/submariner_prepare_hosts.adoc
> +. Click *Next* to continue to the *Configure clusters* page and enter `dummy` in the following fields:
@yboaron I would like to provide some resources for the replacement of dummy in code and doc (in this case, it would need to change in both @oafischer )

https://developers.google.com/style/inclusive-documentation (see the section about abliitlities)
https://blubracket.com/how-and-why-to-rid-software-of-insensitive-language/ 

Over quite a few years, content specialists have been working to replace what seems as harmless words with more unbiased words. This is one of those examples. Of course, no one means harm by these common terms, we know that. We are just slowly trying to eliminate where and what we can.