DR4Hub known issues update 2.7 stolostron/backlog#26797
open-cluster-management/rhacm-docs pull request #4309
Opened 2022-11-11 14:58 UTC by oafischer

https://github.com/stolostron/backlog/issues/26797

2022-11-11 19:19 UTC, dockerymick approved these changes
Thanks for making this change! I made a couple of suggestions

2022-11-11 19:19 UTC, dockerymick commented on release_notes/known_issues.adoc
> +Different deployments have different security context and different service accounts. The subscription operator cannot create an SCC automatically. Administrators control permissions for pods. A Secu
The subscription operator cannot create an SCC **CR** automatically.

2022-11-11 19:19 UTC, dockerymick commented on release_notes/known_issues.adoc
> +. Create an SCC CR in your namespace to assign the required permissions to the service account or accounts. See the following example where `kind: SecurityContextConstraints` is added:
See the following example **,** where `kind: SecurityContextConstraints` is added:

2022-11-11 19:19 UTC, dockerymick commented on release_notes/known_issues.adoc
> +A new hub cluster can have a different configuration than the active hub cluster if the new hub cluster where the data is restored has user-created resources. For example, this can include an existin
A new hub cluster can have a different configuration than the active hub cluster if the new hub cluster, where the data is restored, has user-created resources.

2022-11-14 14:09 UTC, birsanv requested changes
DR changes look perfect but there is one change (change 4) not addressed here; do you plan to add that to a new PR or you just missed it ?

Add this new section
Title : Imported managed clusters show a Pending Import status

2022-11-14 14:11 UTC, oafischer commented
@birsanv Change 4 is in line 1067, does it show up for you? Might be hard to see due to the AsciiDoc/GitHub issues in this file.

2022-11-14 14:13 UTC, birsanv approved these changes
got it, thanks!

lgtm

2022-11-14 14:16 UTC, merged

2022-11-14 14:17 UTC, birsanv commented
@oafischer sorry, found one more change 

Replace this
Avoid backup collisions by setting the BackupSchedule.cluster.open-cluster-management.io resource status to BackupCollision. 

With 

The controller avoids backup collisions by setting the BackupSchedule.cluster.open-cluster-management.io resource status to BackupCollision. 

(The user would not be able to set the status, it is set automatically)

2022-11-14 14:17 UTC, oafischer commented
Sorry, I'll add it in another PR! Thanks for catching that.

2022-11-14 14:21 UTC, oafischer commented
https://github.com/stolostron/rhacm-docs/pull/4327