Adding steps to configure observability with AWS Security
open-cluster-management/rhacm-docs pull request #4420
Opened 2022-12-06 17:31 UTC by dockerymick

https://github.com/stolostron/backlog/issues/26197

2022-12-12 20:39 UTC, swopebe approved these changes

2022-12-12 20:45 UTC, dockerymick commented on observability/observability_enable.adoc
> +//Adding view if we used bullet points, will receive feedback in peer review
@swopebe would it be best to list the steps as bullet points (197-202) or paragraph form (194)?

2022-12-12 21:18 UTC, cadawson requested changes
Some comments noted. Thanks!

2022-12-12 21:18 UTC, cadawson commented on observability/observability_enable.adoc
> +** For Amazon S3 or S3 compatible, you can also use short term, limited-privilege credentials generated with AWS Security Token Service (AWS STS). Refer to link:https://docs.aws.amazon.com/STS/latest
For Amazon S3 or S3 compatible ??storage?, you can...

2022-12-12 21:18 UTC, cadawson commented on observability/observability_enable.adoc
> +Generating access keys using AWS Security Service require additional steps, such as creating a IAM policy that limits access to a S3 bucket, creating a IAM role with a trust policy to generate JWT to
...an IAM policy... (x2)
...an S3 bucket...
...an IAM role...
...access to the S3 bucket...?
"The following example" instead of "Below".

2022-12-12 21:18 UTC, cadawson commented on observability/observability_enable.adoc
> +Generating access keys using AWS Security Service require the following additional steps:
requires

2022-12-12 21:18 UTC, cadawson commented on observability/observability_enable.adoc
> +- Create an IAM policy that limits access to a S3 bucket
an S3 bucket

2022-12-12 21:18 UTC, cadawson commented on observability/observability_enable.adoc
> +- Create an IAM role with a trust policy to generate JWT tokens for {ocp-short} service accounts, and
If you choose this approach, I would remove the ", and".

2022-12-12 21:18 UTC, cadawson commented on observability/observability_enable.adoc
> +- Specify annotations for the observability service accounts that require access to S3 bucket. You can find an example of how observability on Red Hat OpenShift Service on AWS (ROSA) cluster can be c
..the S3 bucket...?

2022-12-12 21:18 UTC, cadawson commented on observability/observability_enable.adoc
> +Complete the following steps to generate access keys using AWS Security Service:
...the AWS Security Service:?

2022-12-12 21:18 UTC, cadawson commented on observability/observability_enable.adoc
> +export CLUSTER_NAME=my-cluster
`<my-cluster>` if a variable

2022-12-12 21:18 UTC, cadawson commented on observability/observability_enable.adoc
> ++
I think we were trying to avoid the "cat <<EOF..." format for the yaml, for consistency. If you can do that here, it would be better, I think.

2022-12-12 21:18 UTC, cadawson commented on observability/observability_enable.adoc
> +----
Same as earlier...cat.

2022-12-12 21:18 UTC, cadawson commented on observability/observability_enable.adoc
> +The observability service is enabled. After you enable the observability service, the following functionalities are initiated:
following functions

2022-12-13 05:50 UTC, clyang82 commented
@subbarao-meduri I remembered we have an user story to address how to configure obs with STS. is my understanding correct? Thanks.

2022-12-13 14:26 UTC, dockerymick commented on observability/observability_enable.adoc
> +** For Amazon S3 or S3 compatible, you can also use short term, limited-privilege credentials generated with AWS Security Token Service (AWS STS). Refer to link:https://docs.aws.amazon.com/STS/latest
updated

2022-12-13 14:28 UTC, dockerymick commented on observability/observability_enable.adoc
> +Generating access keys using AWS Security Service require additional steps, such as creating a IAM policy that limits access to a S3 bucket, creating a IAM role with a trust policy to generate JWT to
Went with the bulleted list

2022-12-13 14:34 UTC, dockerymick commented on observability/observability_enable.adoc
> +Generating access keys using AWS Security Service require the following additional steps:
updated

2022-12-13 14:35 UTC, dockerymick commented on observability/observability_enable.adoc
> +- Create an IAM policy that limits access to a S3 bucket
Updated

2022-12-13 14:35 UTC, dockerymick commented on observability/observability_enable.adoc
> +- Create an IAM role with a trust policy to generate JWT tokens for {ocp-short} service accounts, and
Updated

2022-12-13 14:36 UTC, dockerymick commented on observability/observability_enable.adoc
> +- Specify annotations for the observability service accounts that require access to S3 bucket. You can find an example of how observability on Red Hat OpenShift Service on AWS (ROSA) cluster can be c
updated

2022-12-13 14:36 UTC, dockerymick commented on observability/observability_enable.adoc
> +Complete the following steps to generate access keys using AWS Security Service:
updated

2022-12-13 14:38 UTC, dockerymick commented on observability/observability_enable.adoc
> ++
thanks for the reminder!

2022-12-13 14:38 UTC, dockerymick commented on observability/observability_enable.adoc
> +----
updated

2022-12-13 14:39 UTC, dockerymick commented on observability/observability_enable.adoc
> +The observability service is enabled. After you enable the observability service, the following functionalities are initiated:
updated

2022-12-19 15:40 UTC, swopebe commented
Pinged: before you break there is any chance we can move on this or hand it off for someone to follow up?

2023-01-04 15:44 UTC, swopebe commented on observability/observability_enable.adoc
>  +
The source is changing as a result of lots of `*`, which I feel we are overusing across the doc. Gonna see where we can fix it.

2023-01-04 15:46 UTC, swopebe commented on observability/observability_enable.adoc
> +. To deploy on infrastructure machine sets, you must set a label for your set by updating the `nodeSelector` in the `MultiClusterObservability` YAML. Your YAML might resemble the following content:
we don't need the italicize `nodeSelector` on line 400, so I removed that

2023-01-04 16:03 UTC, swopebe commented
This  is an example of us not all doing the same thing with modular doc...I think this file could contain it all but in other sections, we are breaking our content to be more modular. It's been a lot of work to keep us all on the same page across teh books. @cadawson would this not be split up?

2023-01-04 16:04 UTC, swopebe requested changes
see conversation--a meeting about this, just 15 mins, may help

2023-01-04 16:33 UTC, swopebe commented on observability/observability_enable.adoc
> +- All the managed clusters that are connected to the {product-title-short} hub cluster are enabled to send alerts back to the {product-title-short} observability service. You can configure the {produ
This was causing the PR format to change; fixed now, it seems.

2023-01-04 16:34 UTC, swopebe commented on observability/observability_enable.adoc
Does this need to be a note? (line 436)

2023-01-04 18:59 UTC, dockerymick commented on observability/observability_enable.adoc
>  +
updated

2023-01-04 18:59 UTC, dockerymick commented on observability/observability_enable.adoc
> +- All the managed clusters that are connected to the {product-title-short} hub cluster are enabled to send alerts back to the {product-title-short} observability service. You can configure the {produ
Thanks for the fix!

2023-01-04 18:59 UTC, dockerymick commented on observability/observability_enable.adoc
fixed

2023-01-05 17:04 UTC, swopebe commented
let's discuss this in arch call tomorrow.

2023-01-06 18:47 UTC, swopebe commented on observability/observability_enable.adoc
> +$SCRATCH_DIR/s3-policy.json
Asking about line 230 @subbarao-meduri -- is this needed?

2023-01-06 18:47 UTC, swopebe commented on observability/observability_enable.adoc
> +$SCRATCH_DIR/TrustPolicy.json
same here

2023-01-06 18:49 UTC, swopebe commented
Still waiting on review, discussed some standards, tech debt open for modular doc fixes.

2023-01-10 16:45 UTC, subbarao-meduri commented on observability/observability_enable.adoc
> +$SCRATCH_DIR/s3-policy.json
@swopebe @dockerymick - this is just a json file name to create that was referenced in the script later. Perhaps we could instead represent it with  `cat << filename` so customers can directly copy the command while creating the ifle.

2023-01-10 16:47 UTC, subbarao-meduri commented on observability/observability_enable.adoc
> +$SCRATCH_DIR/s3-policy.json
Oops I just noticed your comment above that we are trying to avoid `cat << EOF.. ` format. All we are trying to say is that we must create `s3-policy.json` file with the file content below.

2023-01-10 16:47 UTC, subbarao-meduri commented on observability/observability_enable.adoc
> +$SCRATCH_DIR/TrustPolicy.json
Same as above, this is just a file name we are trying to create.

2023-01-11 20:58 UTC, dockerymick commented
@subbarao-meduri thanks for your review and clarification. Will you rereview the PR please?

2023-01-18 19:54 UTC, dockerymick commented
Adding @dislbenn as a reviewer. Thanks for volunteering!

2023-01-23 22:49 UTC, dislbenn commented
Looks good to me. @subbarao-meduri can you provide a review also?

/approve

2023-01-23 22:49 UTC, dislbenn approved these changes

2023-01-25 04:41 UTC, dockerymick commented
@dislbenn thanks for your approval

2023-01-25 04:43 UTC, dockerymick commented
This PR has received a peer review from doc team and approval from dev. Moving forward with merging this PR. I also ran the link check tool

2023-01-25 04:43 UTC, merged