stolostron/backlog#25050 add link to AI reqs
open-cluster-management/rhacm-docs pull request #4421
Opened 2022-12-06 18:39 UTC by cadawson

2022-12-20 01:09 UTC, swopebe commented on multicluster_engine/install_upgrade/install_connected.adoc
> +* If you plan to create managed clusters by using the Assisted Installer, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html/installing/installing-on-premis
I don't think we call it this in the doc. Also, I already made a 4.12 update so please check to see if this is covered? (So we don't clutter doc with bullets)

2022-12-20 01:10 UTC, swopebe commented on multicluster_engine/install_upgrade/install_connected.adoc
> +* Your Red Hat OpenShift Container Platform cluster must have access to the {mce} in the OperatorHub catalog from the OpenShift Container Platform console.
Some of these prereqs are covered by the OCP install. I would request that the install team take a look at this one.

2022-12-20 01:10 UTC, swopebe requested changes
couple things, this is an older PR so I wanted to get it moving.

2023-01-06 15:53 UTC, cadawson commented
Hi Jakob. Can you take a look at this and make sure that it looks ok from the installation perspective? Thanks!

2023-01-10 21:22 UTC, JakobGray approved these changes

2023-01-12 22:42 UTC, swopebe approved these changes

2023-01-13 12:46 UTC, merged