Redo HyperShift docs for MCE 2.2 in 2.7 stolostron/backlog#25594
open-cluster-management/rhacm-docs pull request #4425
Opened 2022-12-06 20:47 UTC by oafischer

https://github.com/stolostron/backlog/issues/25594

2022-12-06 21:04 UTC, oafischer commented on multicluster_engine/hosted_control_planes/hosted_control_planes_configure.adoc
> +* {mce} 2.2 and later installed on an {ocp-short} cluster. The {mce} is automatically installed when you install {product-title-short}. {mce} can also be installed without {product-title-short} as an
@JakobGray Can you or someone else from the Install team take a quick look at these lines? Would appreciate it, thanks!

2022-12-06 21:57 UTC, lahinson commented on multicluster_engine/hosted_control_planes/disable_hosted_control_planes.adoc
> +When disabling the hosted control plane cluster feature, you must destroy the HyperShift hosted cluster and the managed cluster resource on the multicluster engine. Deleting only the hosted cluster,
I'm honestly curious -- do we need the word "HyperShift" in the phrase "HyperShift hosted cluster"? Wondering if simply "you must destroy the hosted cluster" means the same thing.

2022-12-07 13:54 UTC, oafischer commented on multicluster_engine/hosted_control_planes/disable_hosted_control_planes.adoc
> +When disabling the hosted control plane cluster feature, you must destroy the HyperShift hosted cluster and the managed cluster resource on the multicluster engine. Deleting only the hosted cluster,
Good question, maybe Brandi can chime in. I left it as is but you are probably right that we can remove it. I don't recall seeing other instances where it is called HyperShift hosted cluster.

2022-12-07 19:23 UTC, swopebe requested changes
a few comments we can go over in a meeting

2022-12-07 19:23 UTC, swopebe commented on multicluster_engine/cluster_lifecycle/import_cli.adoc
> +cat <<EOF | oc apply -f -
we don't normally place this in commands: cat <<EOF and OEF (it is a shortcut that sometime sneaks in from dev... we want to break out the file and the command -- a first time user may not recognize all of it together that this is two steps in one)

usually just go with the apply command. So we break this out:

1. Create your `ManagedCluster` resource using the following sample YAML file: (Or something like that)

2. Run the following command to apply the resource. OR Run `insert command` to apply the resource. OR something like that.

2022-12-07 19:23 UTC, swopebe commented on multicluster_engine/cluster_lifecycle/import_cli.adoc
> ++
so just like this ^^^

2022-12-07 19:23 UTC, swopebe commented on multicluster_engine/cluster_lifecycle/import_gui.adoc
> +** <<run-import-commands-manually,Additional steps for running the import commands manually>>
so this needs to be parallel for tasks, the additionally steps can just be embedded I think to avoid a header, but let's look at that.. Please take optional out of the header here if it works. It is just a special tag for a step, we can look at that, as well.

2022-12-07 19:23 UTC, swopebe commented on multicluster_engine/cluster_lifecycle/import_gui.adoc
> +
I wonder if with some restructuring this can be a step instead of a header with just one step.

2022-12-07 19:23 UTC, swopebe commented on multicluster_engine/hosted_control_planes/disable_hosted_control_planes.adoc
>  ----
For commands, we don't usually say resembles bc the user needs to run that exact command. We need to be direct here. Only if there are variables like in samples would we use that. Then we normally tell them what goes in the replacements. Sometimes it is as simple as: replace with your credentials. Sometimes, like when we have multiple namespaces or cluster names, we need to be specific. The developer can help with that part.

2022-12-07 19:23 UTC, swopebe commented on multicluster_engine/hosted_control_planes/disable_hosted_control_planes.adoc
> +Replace `cluster_name` with the name of your cluster.
Like this! ^^^^

2022-12-07 20:10 UTC, lahinson approved these changes
Nice work, @oafischer! I added a few comments for you to consider. Let me know if you need more clarification on anything.

2022-12-07 20:10 UTC, lahinson commented on multicluster_engine/hosted_control_planes/disable_hosted_control_planes.adoc
> +. Delete the hosted cluster and its backend resources by running a command that resembles the following:
A couple of editing nits: 

- Per the ISG, when "backend" is used as an adjective, it should be hyphenated: "back-end".
- A colon should follow a noun, and in this case "following" is an adjective. Consider revising to something like, "...running a command that resembles the following example:"

2022-12-07 20:10 UTC, lahinson commented on multicluster_engine/hosted_control_planes/hosted_control_planes_configure.adoc
> +. If you plan to use service-level DNS for control plane services on the AWS platform, create an external DNS credential secret for the HyperShift operator and name it `hypershift-operator-external-d
The second sentence (starting with "It must reside in...") is a little hard to follow. Maybe something like this would work? `The secret must reside in the namespace of the managed cluster that is being used as the hosted cluster.`

2022-12-07 20:10 UTC, lahinson commented on multicluster_engine/hosted_control_planes/hosted_control_planes_configure.adoc
> +. Set environment variables that resemble the following example:
Consider this revision: `Set environment variables as follows, replacing variables as needed with your credentials:`

2022-12-07 20:10 UTC, lahinson commented on multicluster_engine/hosted_control_planes/hosted_control_planes_configure.adoc
> +You can now access your cluster. The access secrets are stored in the `hypershift-management-cluster` namespace. Learn about the following formats secret name formats:
Should the second sentence be `Learn about the following secret name formats:`?

2022-12-07 20:10 UTC, lahinson commented on multicluster_engine/release_notes/known_issues.adoc
> +If the annotation and `ManagedCluster` name do not match, the console displays the cluster as `Pending import`. The cluster cannot be used by the {mce}. The same issue happens when there is no annota
I'm wondering if `HostedCluster` `Infra-ID` might be difficult to read because of formatting. Maybe revise to something like this? "The same issue happens when there is no annotation and the `ManagedCluster` name does not match the `Infra-ID` value of the `HostedCluster` resource."

2022-12-07 20:16 UTC, oafischer commented on multicluster_engine/hosted_control_planes/hosted_control_planes_configure.adoc
> +You can now access your cluster. The access secrets are stored in the `hypershift-management-cluster` namespace. Learn about the following formats secret name formats:
Definitely makes more sense, good catch!

2022-12-12 14:40 UTC, JakobGray commented on multicluster_engine/hosted_control_planes/hosted_control_planes_configure.adoc
> +* {mce} 2.2 and later installed on an {ocp-short} cluster. The {mce} is automatically installed when you install {product-title-short}. {mce} can also be installed without {product-title-short} as an
lgtm

2022-12-16 15:56 UTC, oafischer commented
Implemented some large updates form multiple meetings, content needs both technical review and writing review.

2023-01-03 18:52 UTC, lahinson requested changes
Hi @oafischer - You've done a ton of work here, and I think the hosted control planes section is improved! Let me know if you have any questions about my comments. I'm happy to meet if that would be easier.

2023-01-03 18:52 UTC, lahinson commented on multicluster_engine/hosted_control_planes/hosted_intro.adoc
> += Hosted control planes (Technology Preview)
Just curious - Does the ACM docs team follow the Red Hat Supplementary Style Guide? If so, [this section](https://redhat-documentation.github.io/supplementary-style-guide/#technology-preview-guidance) of that guide contains boilerplate to add for Technology Preview features.

2023-01-03 18:52 UTC, lahinson commented on multicluster_engine/hosted_control_planes/hosted_intro.adoc
> +See the following advantages of hosted control plane clusters:
Because none of the list items in this list are complete sentences, they don't need to end with periods.

2023-01-03 18:52 UTC, lahinson commented on multicluster_engine/hosted_control_planes/hosted_intro.adoc
> +Continue reading the following topics to learn more about the {mce}:
Question: Does MCE take an article? That is, do we say, "...to learn more about the multicluster engine for Kubernetes operator" or "...to learn more about multicluster engine for Kubernetes operator"?

2023-01-03 18:52 UTC, lahinson commented on multicluster_engine/hosted_control_planes/hosted_intro.adoc
> +The {mce} {mce-version} can deploy {ocp} clusters by using two different control plane configurations. The standalone configuration uses multiple dedicated virtual machines or physical machines to ho
In the first sentence on line 4, consider spelling out the two configurations, just to make it crystal clear what they are. For example: "The {mce} {mce-version} can deploy {ocp} clusters by using two different control plane configurations: standalone or hosted control planes."

2023-01-03 18:52 UTC, lahinson commented on multicluster_engine/hosted_control_planes/hosted_intro.adoc
> +*Best practice:* Hosted control planes work best when the hub cluster and workers run on the same platform.
Again, I'm not sure if this team follows the Red Hat Supplementary Style Guide, but if so, this admonition label should probably be "Tip" instead of "Best practice". Reference: https://redhat-documentation.github.io/supplementary-style-guide/#admonitions

2023-01-03 18:52 UTC, lahinson commented on multicluster_engine/hosted_control_planes/hosted_intro.adoc
> +See the following advantages of hosted control plane clusters:
Suggested revision for the lead-in sentence: "Hosted control plane clusters offer several advantages:"

2023-01-03 18:52 UTC, lahinson commented on multicluster_engine/hosted_control_planes/configure_hosted.adoc
> +Configuring hosted control planes requires a hosting cluster and a hosted cluster. By deploying the HyperShift operator on an existing cluster, you can make that cluster into a hosting cluster and st
A couple of comments here:
* Suggested edit to engage the reader a little better: "To configure hosted control planes, you need a hosting cluster and a hosted cluster."
* In the OCP docs, we capitalize the word "operator" per the Red Hat Supplementary Style Guide. Not sure if you want to do that here to be consistent with the OCP docs or if the ACM docs tend to use lowercase "operator".

2023-01-03 18:52 UTC, lahinson commented on multicluster_engine/hosted_control_planes/configure_hosted.adoc
> +*Best practice:* Run hosted control planes and worker nodes on the same environment.
See my comment in hosted_intro.adoc about admonition labels. Not sure if this label should be "Best practice" or "Tip".

2023-01-03 18:52 UTC, lahinson commented on multicluster_engine/hosted_control_planes/configure_hosted.adoc
> +* {mce} 2.2 and later installed on an {ocp-short} cluster. The {mce} is automatically installed when you install {product-title-short}. {mce} can also be installed without {product-title-short} as an
The text here varies between using "the MCE" and "MCE". I'm not sure if it should take an article or not, but either way, it's best to be consistent. You can write around starting a sentence with lowercase "multicluster" in the third sentence by writing, "You can also install {mce} without {product-title-short} as an operator from the {ocp-short} OperatorHub."

2023-01-03 18:52 UTC, lahinson commented on multicluster_engine/hosted_control_planes/configure_hosted.adoc
> +| Contains an S3 bucket with public access to host OIDC discovery documents for your HyperShift clusters.
Check with Roke, but I think "HyperShift clusters" should be "hosted clusters".

2023-01-03 18:52 UTC, lahinson commented on multicluster_engine/hosted_control_planes/configure_hosted.adoc
> +| A reference to a file that contains the credentials of the `default` profile that can access the bucket. By default, HyperShift only uses the `default` profile to operate the `bucket`.
I think "HyperShift" should be "hosted control planes", but verify with Roke.

2023-01-03 18:52 UTC, lahinson commented on multicluster_engine/hosted_control_planes/configure_hosted.adoc
> +. Make sure the secret contains the following three fields:
Are lines 83 and 85 redundant?

2023-01-03 18:52 UTC, lahinson commented on multicluster_engine/hosted_control_planes/configure_hosted.adoc
> +| Optional when using the AWS DNS service and
Is "and" a typo?

2023-01-03 18:52 UTC, lahinson commented on multicluster_engine/hosted_control_planes/configure_hosted.adoc
> +The hosted control planes features is disabled by default. Enabling the feature automatically enables the HyperShift add-on as well. The following example shows the `spec.overrides` default template
The word "features" should be singular.

2023-01-03 18:52 UTC, lahinson commented on multicluster_engine/hosted_control_planes/configure_hosted.adoc
> +INSERT LINK
When it's live (on Jan. 17), the link will be: https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html/networking/hardware-networks#sriov-operator-hosted-control-planes_configuring-sriov-operator

2023-01-03 18:52 UTC, lahinson commented on multicluster_engine/hosted_control_planes/create_hosted.adoc
> +Maybe say you need to follow configure topic first
Be sure to update this :)

2023-01-03 18:52 UTC, lahinson commented on multicluster_engine/hosted_control_planes/configure_hosted.adoc
> +* The HyperShift binary as a plugin for `oc` to create and manage the hosted cluster in the {mce}. Use one of the following methods to get the binary:
Are the methods for getting the binary missing? Also, per IBM Style, "binary" should always be used as an adjective. For example, "binary file" or "binary number".

2023-01-03 18:52 UTC, lahinson commented on multicluster_engine/hosted_control_planes/create_hosted.adoc
> +. After importing, your hosted cluster becomes visible in the console. You can also check the status of your hosted cluster by running the following command:
The wording here implies that the hosted cluster imports something and then becomes visible. 
Suggested revisions: "After the hosted cluster is imported..." or "After the import process is complete..."

2023-01-03 18:52 UTC, lahinson commented on multicluster_engine/hosted_control_planes/destroy_hosted.adoc
> +Destroying hosted clusters does not disable the hosted control plane features. If want to disable the feature, you must first destroy both the hosted cluster and the managed cluster resource on the {
Sentence two should say "If you want to disable..."

2023-01-03 18:52 UTC, lahinson commented on multicluster_engine/hosted_control_planes/disable_hosted.adoc
> +*Note:* Deleting the `hypershift-addon` only removes the add-on agent from the managed cluster if there is at least one hosted cluster. If there is no hosted cluster, deleting the `hypershift-addon`
Suggested revision: 

*Note:* If at least one hosted cluster exists and you delete `hypershift-addon`, you remove only the add-on agent from the managed cluster. If no hosted cluster exists and you delete the `hypershift-addon`, you uninstall the HyperShift operator on the managed cluster as well.

2023-01-03 19:02 UTC, oafischer commented on multicluster_engine/hosted_control_planes/hosted_intro.adoc
> += Hosted control planes (Technology Preview)
We do use it to fill gaps where the IBM guide doesn't provide anything, although we have our own process for tech preview: https://stolostron.github.io/rhacm-docs/wr_special_tag_guidance

We don't use any templates like what you linked in our docs (I have seen them in other Red Hat product docs though, so I know what you are referring to). Maybe this is something we can revisit? @swopebe 

It's a process from before my time so @swopebe can explain in detail.

2023-01-03 19:04 UTC, oafischer commented on multicluster_engine/hosted_control_planes/hosted_intro.adoc
> +Continue reading the following topics to learn more about the {mce}:
I've generally seen it with the article so I've followed that. I'm inclined to use it with the article since it's classified as a technology, not a product, but this is probably a good point to bring up with the team in a meeting to make sure we are all on the same page.

2023-01-03 19:10 UTC, oafischer commented on multicluster_engine/hosted_control_planes/hosted_intro.adoc
> +*Best practice:* Hosted control planes work best when the hub cluster and workers run on the same platform.
Best practice is actually a pretty new one that I think @dockerymick came up with: https://stolostron.github.io/rhacm-docs/wr_special_tag_guidance

@dockerymick Do you think best practice is an appropriate tag here or would tip be better? I can see either working.

Most of our process/style was developed before my time but from my understanding there were gaps that we had to fill, so maybe new stuff was added since then and we might not need some of our stuff anymore @swopebe is probably the right person to take a look at this, though I can also bring it up in our next meeting.

2023-01-03 19:18 UTC, oafischer commented on multicluster_engine/hosted_control_planes/configure_hosted.adoc
> +| Contains an S3 bucket with public access to host OIDC discovery documents for your HyperShift clusters.
Agreed, missed that one, thanks!

2023-01-03 20:26 UTC, oafischer commented on multicluster_engine/hosted_control_planes/configure_hosted.adoc
> +Configuring hosted control planes requires a hosting cluster and a hosted cluster. By deploying the HyperShift operator on an existing cluster, you can make that cluster into a hosting cluster and st
So far we've been using operator, but since we are all trying to align better and create more consistency, I can bring this up with the team in a meeting.

2023-01-04 15:48 UTC, oafischer commented on multicluster_engine/hosted_control_planes/configure_hosted.adoc
> +INSERT LINK
What is the full name of the topic title going to be?

2023-01-04 16:13 UTC, lahinson commented on multicluster_engine/hosted_control_planes/configure_hosted.adoc
> +INSERT LINK
Deploying the SR-IOV Operator for hosted control planes

2023-01-04 17:07 UTC, oafischer commented on multicluster_engine/hosted_control_planes/configure_hosted.adoc
> +* The HyperShift binary as a plugin for `oc` to create and manage the hosted cluster in the {mce}. Use one of the following methods to get the binary:
The methods to get the binary come after that in a list, but I agree it's confusing and could be done better. It's mostly carried over from the old docs. Do you have ideas for better implementing the steps?

2023-01-04 17:09 UTC, oafischer commented on multicluster_engine/hosted_control_planes/configure_hosted.adoc
> +* {mce} 2.2 and later installed on an {ocp-short} cluster. The {mce} is automatically installed when you install {product-title-short}. {mce} can also be installed without {product-title-short} as an
Confirmed with Brandi that we should not be using an article, thanks for pointing this out! I've removed the article where it makes sense. I left it where it refers to a different component (like the MCE console).

2023-01-04 17:10 UTC, oafischer commented on multicluster_engine/hosted_control_planes/configure_hosted.adoc
> +*Best practice:* Run hosted control planes and worker nodes on the same environment.
Will confirm with Brandi if we want to continue using our own admonitions in the future but for 2.7 we will stick with them since.

2023-01-04 17:10 UTC, lahinson commented on multicluster_engine/hosted_control_planes/configure_hosted.adoc
> +* The HyperShift binary as a plugin for `oc` to create and manage the hosted cluster in the {mce}. Use one of the following methods to get the binary:
Now that I take a second look, I see that the next list items are indented bullet points. You can ignore my original question. I think the text should be clear enough. Thanks, and sorry for any unnecessary heartburn!

2023-01-04 17:12 UTC, oafischer commented on multicluster_engine/hosted_control_planes/hosted_intro.adoc
> +The {mce} {mce-version} can deploy {ocp} clusters by using two different control plane configurations. The standalone configuration uses multiple dedicated virtual machines or physical machines to ho
Fixed! Thanks!

2023-01-04 17:13 UTC, oafischer commented on multicluster_engine/hosted_control_planes/configure_hosted.adoc
> +| Optional when using the AWS DNS service and
Indeed! Good catch

2023-01-04 17:13 UTC, oafischer commented on multicluster_engine/hosted_control_planes/configure_hosted.adoc
> +The hosted control planes features is disabled by default. Enabling the feature automatically enables the HyperShift add-on as well. The following example shows the `spec.overrides` default template
Fixed!

2023-01-04 17:14 UTC, oafischer commented on multicluster_engine/hosted_control_planes/configure_hosted.adoc
> +. Make sure the secret contains the following three fields:
Yep, fixed it, thanks for catching that!

2023-01-04 17:16 UTC, oafischer commented on multicluster_engine/hosted_control_planes/configure_hosted.adoc
> +* The HyperShift binary as a plugin for `oc` to create and manage the hosted cluster in the {mce}. Use one of the following methods to get the binary:
No worries! I don't like adding steps to prereqs but I wasn't seeing a different solution at the time. Maybe I can revisit in the future and find a different way.

2023-01-04 18:26 UTC, swopebe commented on multicluster_engine/hosted_control_planes/hosted_intro.adoc
> +Continue reading the following topics to learn more about the {mce}:
We do use it when appropriate. The conref intentionally does not have an article...we discussed in a meeting a few months ago but the reason:

The (at the beginning of the sentence) and the (mid-sentence) requires a change to case. We don't normally put the articles in the conrefs because the writer should be aware of the context and know when to use The, the, a, A, an, An... so we left it our for simplicity.

2023-01-04 18:30 UTC, swopebe commented on multicluster_engine/hosted_control_planes/hosted_intro.adoc
> += Hosted control planes (Technology Preview)
Tech preview is mentioned after the heading as an initiative from the PMs, a specific request from them; that is why we do what we do in line 2. 

Also PMs and developers really disliked the format changes in the portal with special tagging. We follow the IBM format that our doc came with for all special tags to reduce format changes in the doc, and to ensure we are all doing the same thing. We can re-discuss after 2.7 but it was in 2020 that me decided to keep the simple structure that we have so far. I am going to vote for the simplest way if we can stick to that.

2023-01-04 19:08 UTC, dockerymick commented on multicluster_engine/hosted_control_planes/hosted_intro.adoc
> +*Best practice:* Hosted control planes work best when the hub cluster and workers run on the same platform.
@oafischer I think Tip also works, but i would still go with **Best practice**. I recommend the following revision:

**Best practice**: Be sure to run the hub cluster and workers on the same platform for hosted control planes. 

Let me know your thoughts

2023-01-04 19:11 UTC, oafischer commented on multicluster_engine/hosted_control_planes/hosted_intro.adoc
> +*Best practice:* Hosted control planes work best when the hub cluster and workers run on the same platform.
Thanks @dockerymick! I like your version and will add it to the PR.

2023-01-04 19:17 UTC, swopebe commented on multicluster_engine/hosted_control_planes/hosted_intro.adoc
> +*Best practice:* Hosted control planes work best when the hub cluster and workers run on the same platform.
**Best practice** is again something we brought from IBM to use instead of **recommendation**. Recommendations are frowned upon in tech doc because they are not _imperative_ (this is also IBM style guidance--imperative). We use this tag to make a step or action that is "recommended but important" highlighted for the user. (It was an official DITA tag and always highlighted with ACROLINX via IBM style and since it worked well, our team carried it over.

2023-01-04 19:27 UTC, lahinson commented on multicluster_engine/hosted_control_planes/hosted_intro.adoc
> +*Best practice:* Hosted control planes work best when the hub cluster and workers run on the same platform.
Thanks for answering my question about "Best practice"! It's interesting that it came over from your work at IBM, because one reason I questioned it was because IBM Style lists "best practice" is a term to use with caution.[1] If it's something that you all have been using consistently without issue, then by all means, carry on :)

[1] Reference: https://www.ibm.com/docs/en/ibm-style?topic=information-claims-recommendations

2023-01-04 20:40 UTC, swopebe commented on multicluster_engine/hosted_control_planes/hosted_intro.adoc
> +*Best practice:* Hosted control planes work best when the hub cluster and workers run on the same platform.
Yeah, that is def a change, then, because it was actually a tag they recommended instead of "recommendation. We can revisit these for 2.8.

2023-01-11 17:12 UTC, oafischer commented
@rokej Has updated the source docs and I have carried over some of the changes to this PR. We need to merge this PR soon, will wait on a response from Roke and hopefully merge this week still.

2023-01-11 20:20 UTC, oafischer commented
Merging, Roke will also take another look after the merge.

2023-01-11 20:21 UTC, merged