Clarifying where to install Ansible Automation to connect Ansible jobs
open-cluster-management/rhacm-docs pull request #4437
Opened 2022-12-12 23:29 UTC by dockerymick

https://github.com/stolostron/backlog/issues/26264

2022-12-12 23:33 UTC, dockerymick commented
Ignoring the Linter tool for now. I made updates to make fixes in [my other PR](https://github.com/stolostron/rhacm-docs/pull/4420#pullrequestreview-1214311620). Hopefully, my other PR is reviewed before this one

2022-12-13 15:19 UTC, dhaiducek reviewed
I don't think a namespace needs to be specified here. The Ansible Automation Platform Resource Operator can (I think?) be installed to any namespace and its default is not `open-cluster-management`, so it could be confusing to put the RHACM namespace here.

2022-12-13 15:20 UTC, dhaiducek commented
Oops--I just re-read the issue. Just a min--I'll leave another review.

2022-12-13 15:23 UTC, dhaiducek commented on governance/ansible_grc.adoc
> +* Install the Ansible Automation Platform Resource Operator on to your hub cluster to connect Ansible jobs to the governance framework, in the `open-cluster-management-hub` namespace. For best result
This wording reads to me as if governance-framework is in that namespace. How about a note? 
```suggestion
* Install the Ansible Automation Platform Resource Operator on to your hub cluster to connect Ansible jobs to the governance framework. For best results when using the AnsibleJob to launch Ansible Tower jobs, the Ansible Tower job template should be idempotent when it is run. If you do not have Ansible Automation Platform Resource Operator, you can find it from the {ocp} _OperatorHub_ page. *NOTE*: The Ansible Automation Platform Resource Operator must be installed either clusterwide or in the `open-cluster-management-hub` namespace in order to connnect with the governance framework.
```

2022-12-13 15:34 UTC, gparvin commented on governance/ansible_grc.adoc
> +* Install the Ansible Automation Platform Resource Operator on to your hub cluster to connect Ansible jobs to the governance framework, in the `open-cluster-management-hub` namespace. For best result
Can we just say the operator needs to be installed cluster wide?  Installing to `open-cluster-management-hub` doesn't sound like it would work to me.  Even if it did work, do we document a list of limitations for that installation scenario?  I bet that wording may have come from other ACM teams without considering GRC requirements for the automation existing in the same namespace as the policy.

2022-12-13 17:28 UTC, dockerymick commented
@dhaiducek @gparvin thanks for yall's review and feedback. I moved forward with Gus' suggestion. Will you all take another look please?

2022-12-13 17:32 UTC, dhaiducek approved these changes
Thanks for the update, @dockerymick!

2022-12-13 17:33 UTC, swopebe commented on governance/ansible_grc.adoc
> +* Install the Ansible Automation Platform Resource Operator cluster-wide to connect Ansible jobs to the governance framework. For best results when using the AnsibleJob to launch Ansible Tower jobs,
_Install the Ansible Automation Platform Resource Operator cluster-wide cluster-wide_ is a bit jarring.

Can be read Install the "Ansible Automation Platform Resource Operator cluster-wide..."

Install the Ansible Automation Platform Resource Operator on the entire cluster???? to connect...



**Best practice:** Ensure the the Ansible Tower job template idempotent when it is run.

2022-12-13 19:37 UTC, dockerymick commented on governance/ansible_grc.adoc
> +* Install the Ansible Automation Platform Resource Operator cluster-wide to connect Ansible jobs to the governance framework. For best results when using the AnsibleJob to launch Ansible Tower jobs,
Yea, to the entire hub cluster

2022-12-13 19:38 UTC, gparvin commented on governance/ansible_grc.adoc
> +* Install the Ansible Automation Platform Resource Operator cluster-wide to connect Ansible jobs to the governance framework. For best results when using the AnsibleJob to launch Ansible Tower jobs,
The text that you see in OLM when installing the Operator is:

Update Channel:
- stable-2.3-cluster-scoped
- stable-2.3

Installation Mode
- All namespace on the cluster (default)
Operator will be available in all Namespaces
- A specific namespace on the cluster
Operator will be available in a single namespace only


We need the user to pick the Update Channel that is `cluster-scoped` and pick the Installation Mode of `All namespaces on the cluster (default)`

2022-12-13 19:47 UTC, swopebe commented on governance/ansible_grc.adoc
> +* Install the Ansible Automation Platform Resource Operator cluster-wide to connect Ansible jobs to the governance framework. For best results when using the AnsibleJob to launch Ansible Tower jobs,
IMO it is better to use that exact terminology and in the code block, so the user is not trying to figure out if cluster-wide means the same as cluster-scope.

2022-12-13 19:52 UTC, dockerymick commented on governance/ansible_grc.adoc
> +* Install the Ansible Automation Platform Resource Operator cluster-wide to connect Ansible jobs to the governance framework. For best results when using the AnsibleJob to launch Ansible Tower jobs,
Based on this information, I suggest the following update:

* Install the Ansible Automation Platform Resource Operator from the Operator Lifecycle Manager. In the _Update Channel_ section, select **`stable-2.3-cluster-scoped`**. Select the **All namespace on the cluster (default)** installation mode.

@swopebe @gparvin thoughts?

2022-12-13 20:12 UTC, swopebe commented on governance/ansible_grc.adoc
> +* Install the Ansible Automation Platform Resource Operator cluster-wide to connect Ansible jobs to the governance framework. For best results when using the AnsibleJob to launch Ansible Tower jobs,
Beautiful. @dockerymick can you double check we are using the proper terminology based on what Kevin sent us:https://docs.google.com/document/d/1F9Nf9T1hu0lfQ6DJJ0YxHSfZeMVJLwG-D9goITOMEdg/edit#heading=h.x3o4crit7k59

It looks like we are but just want to keep it on everyone's mind:

2022-12-14 18:56 UTC, swopebe approved these changes

2022-12-14 18:57 UTC, dhaiducek requested changes

2022-12-14 18:57 UTC, dhaiducek commented on governance/ansible_grc.adoc
> +* Install the Ansible Automation Platform Resource Operator from the Operator Lifecycle Manager. In the _Update Channel_ section, select *`stable-2.3-cluster-scoped`. Select the *All namespace on the
```suggestion
* Install the Ansible Automation Platform Resource Operator from the Operator Lifecycle Manager. In the _Update Channel_ section, select *`stable-2.3-cluster-scoped`. Select the *All namespaces on the cluster (default)* installation mode.
```

2022-12-14 18:58 UTC, dhaiducek commented on governance/ansible_grc.adoc
> +* Install the Ansible Automation Platform Resource Operator from the Operator Lifecycle Manager. In the _Update Channel_ section, select *`stable-2.3-cluster-scoped`. Select the *All namespace on the
I'm also not sure about "Operator Lifecycle Manager". Should that be "OperatorHub"?

2022-12-14 19:22 UTC, dhaiducek commented on governance/ansible_grc.adoc
> +* Install the Ansible Automation Platform Resource Operator from the Operator Lifecycle Manager. In the _Update Channel_ section, select *`stable-2.3-cluster-scoped`. Select the *All namespace on the
And I'm also not sure about version compatibility. Should that be "stable-2.x-cluster-scoped" or do we only support Ansible v2.3, @gparvin?

2022-12-15 13:26 UTC, gparvin commented on governance/ansible_grc.adoc
> +* Install the Ansible Automation Platform Resource Operator from the Operator Lifecycle Manager. In the _Update Channel_ section, select *`stable-2.3-cluster-scoped`. Select the *All namespace on the
So we really want to encourage customers to use the most recent version of AAP rather than a specific version.  The cluster lifecycle documentation just says install the latest version.  We just need to make sure they pick the `...cluster-scoped` channel for policy automation to work.

2022-12-20 23:44 UTC, dockerymick commented
I definitely forgot that I received confirmation through Slack. Adding the screen capture here and merging the PR
<img width="446" alt="Screen Shot 2022-12-20 at 6 24 38 PM" src="https://user-images.githubusercontent.com/60616885/208787275-d97dea69-b91c-4a85-90be-fb41eaf97b1c.png">

2022-12-20 23:44 UTC, merged