stolostron/backlog#25868
open-cluster-management/rhacm-docs pull request #4442
Opened 2022-12-13 20:14 UTC by swopebe

--election leader GA doc WIP

2022-12-13 20:14 UTC, swopebe commented on applications/config_leader_election.adoc
> +
Would like maybe another line or two about why user wants to do this.

2022-12-13 20:15 UTC, swopebe commented on applications/config_leader_election.adoc
> +
Was not sure what to call this procedure...adding the flag (though I see no flag)? The topic is already titled configuring so we cannot repeat it.

2022-12-13 20:16 UTC, swopebe commented on applications/config_leader_election.adoc
> +
I need any not-obvious prereqs and the role is usually: Editor, Cluster adniminstrator, etc.... that we try to add to the docs. (RBAC requirement)

2022-12-13 20:17 UTC, swopebe commented on applications/config_leader_election.adoc
> +. Locate and specify a controller and insert a `- command:`  for a flag with a specified time in seconds. Search `name: <controller>`, for example: `name: multicluster-operators-hub-subscription`
I didn't really understand this part.

2022-12-13 20:17 UTC, swopebe commented on applications/config_leader_election.adoc
> +. Locate and specify a controller and insert a `- command:`  for a flag with a specified time in seconds. Search `name: <controller>`, for example: `name: multicluster-operators-hub-subscription`
and example would be good (with the seconds)

2022-12-13 20:17 UTC, swopebe commented on applications/config_leader_election.adoc
> +. Save the file. The controller restarts to apply the flag.
we don't need to run an apply command?

2022-12-13 20:17 UTC, swopebe commented on applications/config_leader_election.adoc
> +See the following example output of a successful flag:
example would be great.

2022-12-13 22:32 UTC, lennysgarage commented on applications/config_leader_election.adoc
> +
Regarding why a user may want to do this is not just for reducing etcd load, that was just the reasoning for choosing the default values. A user may want to increase/decrease the time a controller takes to acquire the LeaderElection lock to. This changes how often the controllers will make requests to choose a new leader in case of failure. A user may want to decrease the default time so in the case of a failure a leader is chosen quicker with the tradeoff being a decrease in overall system performance.

The required access for this would be, `Cluster administrator`

2022-12-13 22:33 UTC, lennysgarage commented on applications/config_leader_election.adoc
> +
Since what this is doing is editing the controller's flag options I think editing the controller is fine or possibly adding controller flags?

2022-12-13 22:34 UTC, lennysgarage commented on applications/config_leader_election.adoc
> +. Save the file. The controller restarts to apply the flag.
Since we're editing the csv directly when we save and exit, it will automatically restart the controller without needing to `oc apply`

2022-12-13 22:38 UTC, lennysgarage commented on applications/config_leader_election.adoc
> +See the following example output of a successful flag:
An example of the `multicluster-operators-hub-subscription` controller with all flags default time doubled:
```
containers:
- command:                                                                                                                                                                 
  - /usr/local/bin/multicluster-operators-subscription
  - --sync-interval=60
  - --retry-period=52
  - --leader-election-lease-duration=274
  - --renew-deadline-114
```

2022-12-13 22:41 UTC, lennysgarage commented on applications/config_leader_election.adoc
> +. Locate and specify a controller and insert a `- command:`  for a flag with a specified time in seconds. Search `name: <controller>`, for example: `name: multicluster-operators-hub-subscription`
Okay so we're not actually inserting  `- comamnd`, but a command under this section.
Under each of the above containers they already have a `- comamnd:` section and so we're simply adding new commands under this section. Any combination of `leaseDuration`, `renewDeadline`, `retryPeriod` can be added. So an example change to the `retryPeriod` of the `multicluster-operators-hub-subscription` controller would be first locating the controller:

0. Run the edit command to enter the csv
1. Locate controller we want to modify, searching `name: <controller>`
2. Head down to the `containers` section under the controller and insert a flag under `- command`
3. Inserting the `retryPeriod` flag itself doubling the default time it takes to retry for acquiring leaderElection.:
```
containers:
- command:                                                                                                                                                                 
  - /usr/local/bin/multicluster-operators-subscription
  - --sync-interval=60
  - --retry-period=52
```

2022-12-14 15:43 UTC, swopebe commented on applications/config_leader_election.adoc
> +See the following example output of a successful flag:
Ok, so I am not following and the user will not follow. We don't write "under" because that alienates users who cannot see. I will try to rewrite a bit.

2022-12-14 16:22 UTC, swopebe commented on applications/config_leader_election.adoc
> +
those changes are in

2022-12-14 16:22 UTC, swopebe commented on applications/config_leader_election.adoc
> +
changed

2022-12-14 16:23 UTC, swopebe commented on applications/config_leader_election.adoc
> +. From the containers section in the controller, insert a `- command` flag. For instance, instert `RetryPeriod`.
@lennysgarage we need to list these out in steps and this part is a bit confusing to me, so where does searching controller fit in? See my edits with what you gave me yesterday.

2022-12-14 21:01 UTC, lennysgarage commented on applications/config_leader_election.adoc
> +. From the containers section in the controller, insert a `- command` flag. For instance, instert `RetryPeriod`.
Okay these steps are good, the searching of the controller is just for locating where exactly to insert the desired commands. It's the first step after opening the csv and it will only appear once in the csv so by heading to `- name: <controller>` they will be in the correct place.

2022-12-14 23:42 UTC, swopebe commented on applications/config_leader_election.adoc
> +. From the containers section in the controller, insert a `- command` flag. For instance, instert `RetryPeriod`.
Ok, thanks @lennysgarage -- if you are good just approve the PR for me, then @dockerymick can approve as peer review.

2022-12-15 04:03 UTC, dockerymick requested changes

2022-12-15 04:03 UTC, dockerymick commented on applications/config_leader_election.adoc
> +. Run `oc get csv -n open-cluster-management` to locate the {product-title-short} `csv` file.
I recommend the following update:

Run the following command to locate the {product-title-short} `csv` file:

```
oc get csv -n open-cluster-management
```

or for consistency:

Locate the {product-title-short} `csv` file with the following command:

2022-12-15 04:03 UTC, dockerymick commented on applications/config_leader_election.adoc
> +. Edit the `csv` file by adding the `advanced-cluster-management` name to the `oc edit` command. For example, the command resembles `oc edit csv -n open-cluster-management advanced-cluster-management
I recommend that you change: 

For example, the command resembles `oc edit csv -n open-cluster-management advanced-cluster-management.v2.7.0`.

to

Your command might resemble the following example command:

 ```
oc edit csv -n open-cluster-management advanced-cluster-management.v2.7.0
```

2022-12-15 04:03 UTC, dockerymick commented on applications/config_leader_election.adoc
> +. From the containers section in the controller, insert a `- command` flag. For instance, insert `RetryPeriod`.
is _containers_ a parameter name? if yes, I recommend that you monospace it

2022-12-15 04:03 UTC, dockerymick commented on applications/config_leader_election.adoc
> +containers:
Remove `containers:` on line 34

2022-12-15 14:59 UTC, lennysgarage commented
/approve

2022-12-15 15:06 UTC, swopebe commented on applications/config_leader_election.adoc
> +. Edit the `csv` file by adding the `advanced-cluster-management` name to the `oc edit` command. For example, the command resembles `oc edit csv -n open-cluster-management advanced-cluster-management
I don't like command in the same line twice, but will break it out for ya.

2022-12-15 15:07 UTC, swopebe commented on applications/config_leader_election.adoc
> +. From the containers section in the controller, insert a `- command` flag. For instance, insert `RetryPeriod`.
not sure...it is a section, we could get away with both I think.

2022-12-15 15:08 UTC, swopebe commented on applications/config_leader_election.adoc
> +. Run `oc get csv -n open-cluster-management` to locate the {product-title-short} `csv` file.
Sometimes we embed command in the step, but I will break it out. It is more UX friendly.

2022-12-15 15:32 UTC, swopebe commented on applications/config_leader_election.adoc
> +. From the containers section in the controller, insert a `- command` flag. For instance, insert `RetryPeriod`.
I am going to keep as is bc I don't have the example or demo -- it wasn't on the playback. The developer called it a section.

2022-12-15 15:33 UTC, swopebe commented on applications/config_leader_election.adoc
> +. Run `oc get csv -n open-cluster-management` to locate the {product-title-short} `csv` file.
changed

2022-12-15 15:33 UTC, swopebe commented on applications/config_leader_election.adoc
> +. Edit the `csv` file by adding the `advanced-cluster-management` name to the `oc edit` command. For example, the command resembles `oc edit csv -n open-cluster-management advanced-cluster-management
changed

2022-12-15 15:34 UTC, swopebe commented
I think I got all the discussion and changes addressed. Dev approved. Waiting on peer review follow up.

2022-12-15 15:42 UTC, dockerymick approved these changes
Looks good to me! Thanks Brandi !

2022-12-15 15:42 UTC, merged