update clusterclaim and ref it to placement
open-cluster-management/rhacm-docs pull request #4457
Opened 2022-12-16 08:45 UTC by ldpliu

Signed-off-by: ldpliu <daliu@redhat.com>
https://github.com/stolostron/backlog/issues/27020
https://github.com/stolostron/backlog/issues/27039

2022-12-20 01:22 UTC, swopebe commented on multicluster_engine/multicluster_engine_overview.adoc
>  * xref:cluster_lifecycle/managedclustersets_intro.adoc#creating-a-managedclusterset[Creating and managing ManagedClusterSets]
I just removed the subtopics from this.

2022-12-20 01:31 UTC, swopebe commented on multicluster_engine/multicluster_engine_overview.adoc
>  * xref:cluster_lifecycle/managedclustersets_intro.adoc#creating-a-managedclusterset[Creating and managing ManagedClusterSets]
I am merging my PR, so please keep the subtopics from the overview, we can link to those in the intros.

2022-12-20 01:32 UTC, swopebe requested changes
please don't add the subtopics.

2022-12-20 15:41 UTC, cadawson commented on multicluster_engine/multicluster_engine_overview.adoc
>  * xref:cluster_lifecycle/managedclustersets_intro.adoc#creating-a-managedclusterset[Creating and managing ManagedClusterSets]
Preserved the removed subtopics on the overview page for this PR. Moved the subtopics in the intro page and main to match the requested change.

2022-12-20 15:52 UTC, cadawson commented
Hi @ldpliu. I'm not sure why, but I can't add you as a reviewer to this PR. Please review when you can. Thank you!

2022-12-22 03:13 UTC, ldpliu commented
Thanks @cadawson @swopebe 
It's ok to me, please help to merge it .

2023-01-04 15:16 UTC, cadawson commented on multicluster_engine/multicluster_engine_overview.adoc
>  * xref:cluster_lifecycle/managedclustersets_intro.adoc#creating-a-managedclusterset[Creating and managing ManagedClusterSets]
In other words, we are not adding the subtopics to the main overview page.

2023-01-04 15:17 UTC, merged

2023-01-04 15:17 UTC, cadawson reviewed
Looks good. Thanks!