Submariner doc architecture overhaul stolostron/backlog#27003
open-cluster-management/rhacm-docs pull request #4465
Opened 2022-12-19 21:50 UTC by oafischer

https://github.com/stolostron/backlog/issues/27003

2022-12-19 23:51 UTC, swopebe commented
I will return to this after the break...amazing work!

2022-12-20 06:51 UTC, sridhargaddam commented
Nice work @oafischer. I will take a look at it during this week.

2022-12-20 14:03 UTC, oafischer commented
Awesome, thanks @sridhargaddam! I will walk through some of the architecture stuff with @dfarrell07 as well but this is a great opportunity to review the whole docs for technical accuracy and such. I made some small content updates but I'm sure there's still stuff that is outdated or that could be improved, if you want to focus on that.

2023-01-06 20:10 UTC, swopebe commented on add-ons/submariner/deploy_subm_console.adoc
> +Submariner is now deployed on the seclected clusters.
spelling here line 87

2023-01-06 20:12 UTC, swopebe approved these changes
One small comment and I also think the #5 per style should be spelled out (I haven't looked at that in a while), but other than that, this is huge iterative improvements on this doc.

2023-01-09 09:26 UTC, sridhargaddam requested changes
Thanks @oafischer for the PR.

2023-01-09 09:26 UTC, sridhargaddam commented on add-ons/addon_overview.adoc
>  {product-title} add-ons can improve some areas of performance and add function to enhace your applications. The following sections provide a summary of the add-ons that are available for {product-tit
```suggestion
{product-title} add-ons can improve some areas of performance and add functionality to enhance your applications. The following sections provide a summary of the add-ons that are available for {product-title-short}:
```

2023-01-09 09:26 UTC, sridhargaddam commented on add-ons/submariner/deploy_subm_console.adoc
> +To deploy Submariner on other providers, follow the instructions in xref:../submariner/deploy_subm_manual.adoc#preparing-submariner-manual-deployment[Deploying Submariner hosts manually].
```suggestion
To deploy Submariner on other providers, follow the instructions in xref:../submariner/deploy_subm_manual.adoc#preparing-submariner-manual-deployment[Deploying Submariner manually].
```

2023-01-09 09:26 UTC, sridhargaddam commented on add-ons/submariner/deploy_subm_console.adoc
> +Before you deploy Submariner with {product-title}, you must prepare the clusters on the hosting environment for the connection. You can use the `SubmarinerConfig` API to automatically prepare cluster
```suggestion
Before you deploy Submariner with {product-title}, you must prepare the clusters on the hosting environment. You can use the `SubmarinerConfig` API or the {product-title} console to automatically prepare {ocp} clusters on the following providers:
```

2023-01-09 09:26 UTC, sridhargaddam commented on add-ons/submariner/deploy_subm_console.adoc
> +. See the fields in following table and enter the required information in the _Install Submariner add-ons_ editor:
```suggestion
. See the fields in the following table and enter the required information in the _Install Submariner add-ons_ editor:
```

2023-01-09 09:26 UTC, sridhargaddam commented on add-ons/submariner/deploy_subm_console.adoc
> +| The number of worker nodes that are used to deploy the Submariner gateway component on your managed cluster. The default value is `1`. If the value is greater than 1, the Submariner gateway High Av
JFYI, for the following cluster (AWS, GCP, Azure and OpenStack) we always create new dedicated Gateway nodes. Only for VmWare clusters we label one (or more) of the existing worker nodes as Gateway nodes.

```suggestion
| The number of gateway nodes to be deployed on the managed cluster. For AWS, GCP, Azure and OpenStack clusters dedicated Gateway nodes are deployed whereas for VmWare clusters, existing worker nodes are tagged as Gateway nodes. The default value is `1`. If the value is greater than 1, the Submariner gateway High Availability (HA) is automatically enabled.
```

2023-01-09 09:26 UTC, sridhargaddam commented on add-ons/submariner/deploy_subm_console.adoc
>  * `Gateway nodes labeled` indicates how many worker nodes are labeled with the Submariner gateway label: `submariner.io/gateway=true` on the managed cluster.
```suggestion
* `Gateway nodes labeled` indicates the number of gateway nodes on the managed cluster.
```

2023-01-09 09:26 UTC, sridhargaddam commented on add-ons/submariner/deploy_subm_manual.adoc
> +Before you deploy Submariner with {product-title}, you must prepare the clusters on the hosting environment for the connection. See xref:../submariner/submariner_prepare_hosts.adoc#preparing-selected
```suggestion
Before you deploy Submariner with {product-title}, you must prepare the clusters on the hosting environment for the connection. See xref:../submariner/submariner_prepare_hosts.adoc#preparing-selected-hosts-to-deploy-submariner[Deploying Submariner using? the console] to learn how to automatically deploy Submariner on supported clusters by using the console.
```

2023-01-09 09:26 UTC, sridhargaddam commented on add-ons/submariner/deploy_subm_manual.adoc
> +If your cluster does not support automatic deployment, see the following topics to prepare your selected hosting environment manually for deployment on Submariner. Each host has unique steps for prep
```suggestion
If your cluster is hosted on a provider that does not support automatic Submariner deployment, see the following sections to prepare the infrastructure manually. Each provider has unique steps for preparation, so make sure to select the correct one.
```

2023-01-09 09:26 UTC, sridhargaddam commented on add-ons/submariner/deploy_subm_manual.adoc
> +To configure the ROKS clusters on a VPC to use Submariner, complete the steps in the following links:
```suggestion
To configure the ROKS clusters on a VPC to use Submariner, complete the following steps:
```

2023-01-09 09:31 UTC, sridhargaddam commented on add-ons/submariner/deploy_subm_manual.adoc
> +. Before you create a cluster, specify subnets for pods and services, which avoids overlapping CIDRs with other clusters. Make sure there are no overlapping pods and services CIDRs between clusters i
```suggestion
. If you plan to install Submariner without Globalnet, make sure that pod and service CIDRs do not overlap between clusters in the clusterSet. See https://cloud.ibm.com/docs/openshift?topic=openshift-vpc-subnets#vpc_basics[VPC Subnets] for the procedure. For clusters with overlapping CIDRs, Globalnet can be enabled while installing Submariner.
```

2023-01-09 09:39 UTC, sridhargaddam commented on add-ons/submariner/deploy_subm_manual.adoc
> +. Create inbound rules for the default security group of the cluster by completing the steps in https://cloud.ibm.com/docs/openshift?topic=openshift-vpc-network-policy#security_groups_ui[Security Gro
```suggestion
. Create inbound rules for the default security group of the cluster by completing the steps in https://cloud.ibm.com/docs/openshift?topic=openshift-vpc-network-policy#security_groups_ui[Security Group]. Ensure that the firewall allows inbound and outbound traffic for external clients on 4500/UDP, 4490/UDP ports for the Gateway nodes, and allows inbound and outbound UDP/4800 traffic within the local cluster between the nodes.
```

2023-01-09 09:40 UTC, sridhargaddam commented on add-ons/submariner/deploy_subm_manual.adoc
> +. Label a node that has the public gateway as `submariner.io/gateway=true` in the cluster.
```suggestion
. Label the node selected as Gateway node in the previous step with the following label `submariner.io/gateway=true`.
```

2023-01-09 09:42 UTC, sridhargaddam commented on add-ons/submariner/deploy_subm_manual.adoc
> +. Ensure that the IPsec NATT and VXLAN ports are open.
```suggestion
. Ensure that the IPsec NATT (UDP/4500), NatDiscovery (UDP/4490) ports for external traffic and VxLAN (UDP/4800) ports within the local cluster are opened.
```

2023-01-09 15:38 UTC, swopebe commented on add-ons/submariner/deploy_subm_manual.adoc
> +Before you deploy Submariner with {product-title}, you must prepare the clusters on the hosting environment for the connection. See xref:../submariner/submariner_prepare_hosts.adoc#preparing-selected
by using (otherwise it looks like submariner is using the console)

2023-01-09 15:40 UTC, oafischer commented on add-ons/submariner/deploy_subm_manual.adoc
> +Before you deploy Submariner with {product-title}, you must prepare the clusters on the hosting environment for the connection. See xref:../submariner/submariner_prepare_hosts.adoc#preparing-selected
Can we say "with the console" since we seem to use that in our docs? Or should we change to "by using"?

2023-01-09 19:40 UTC, oafischer commented
Thanks for your review @sridhargaddam! I agreed with your changes and committed them with edits where necessary. Since this is a high priority PR, can you take one more look so that I can merge it soon? Some other Submariner work depends on these changes. Thanks again!

2023-01-09 19:56 UTC, swopebe commented on add-ons/submariner/deploy_subm_manual.adoc
> +Before you deploy Submariner with {product-title}, you must prepare the clusters on the hosting environment for the connection. See xref:../submariner/submariner_prepare_hosts.adoc#preparing-selected
Well, I think it can be read as:

Deploying Submariner with the console vs Deploying Submariner without the console... 

But we are using the console to deploy submariner, which is prob the reason for the change request. 

Per IBM Style, we should be writing "by using" for that clarity, so you may not find that consistency in the doc...but it is the goal.

2023-01-11 08:18 UTC, sridhargaddam requested changes
Thanks for addressing the previous comments @oafischer

2023-01-11 08:18 UTC, sridhargaddam commented on add-ons/submariner/deploy_subm_manual.adoc
> +. Ensure that the IPsec NATT and VXLAN ports are open.
At this step, we do not know the Gateway node, so lets add it as an extra step below.

2023-01-11 08:18 UTC, sridhargaddam commented on add-ons/submariner/deploy_subm_manual.adoc
> +
Please add this step 

. Identify the Gateway node configured by Submariner and enable firewall configuration to allow the IPsec NATT (UDP/4500), NatDiscovery (UDP/4490) ports for external traffic.

2023-01-11 08:18 UTC, sridhargaddam commented on add-ons/submariner/deploy_subm_console.adoc
> +
@aswinsuryan @vthapar do you remember the fields for the Azure clusters?

2023-01-11 08:18 UTC, sridhargaddam commented on add-ons/submariner/deploy_subm_console.adoc
> +| The Amazon Web Services EC2 instance type of the gateway node that is created on the managed cluster. The default value is `c5d.large`. This field is only visible when your managed cluster environm
The instance type is applicable for other clusters as well and not just AWS. If we want to capture the default value, IMO we have to do the same for all the other clusters. So, I personally feel that we can avoid capturing the default value here.

```suggestion
| The instance type of the gateway node that is created on the managed cluster.
```

2023-01-11 08:18 UTC, sridhargaddam commented on add-ons/submariner/deploy_subm_console.adoc
> +| The default value for the IPsec NAT traversal port is port `4500`. If your managed cluster environment is VMware vSphere, ensure that this port is opened on your firewalls.
```suggestion
| The default value for the IPsec NAT traversal port is port `4500`. If your managed cluster environment is VMware vSphere, ensure that this port is opened on your firewall.
```

2023-01-11 08:18 UTC, sridhargaddam commented on add-ons/submariner/deploy_subm_manual.adoc
> += Deploying Submariner hosts manually
```suggestion
= Deploying Submariner manually
```

2023-01-11 08:18 UTC, sridhargaddam commented on add-ons/submariner/deploy_subm_manual.adoc
> +. Ensure that inbound and oubound VxLAN (UDP/4800) traffic between the cluster nodes is allowed in the firewall configuration.
```suggestion
. Ensure that the firewall allows inbound/outbound traffic for external clients on 4500/UDP, 4490/UDP ports for the Gateway nodes, and allows inbound/outbound UDP/4800 traffic within the local cluster nodes.
```

2023-01-11 08:18 UTC, sridhargaddam commented on add-ons/submariner/deploy_subm_manual.adoc
> +. Create inbound rules for the default security group of the cluster by completing the steps in https://cloud.ibm.com/docs/openshift?topic=openshift-vpc-network-policy#security_groups_ui[Security Gro
```suggestion
. Create inbound rules for the default security group of the cluster by completing the steps in https://cloud.ibm.com/docs/openshift?topic=openshift-vpc-network-policy#security_groups_ui[Security Group]. Ensure that the firewall allows inbound/outbound traffic for external clients on 4500/UDP, 4490/UDP ports for the Gateway nodes, and allows inbound/outbound UDP/4800 traffic within the local cluster nodes.
```

2023-01-11 08:18 UTC, sridhargaddam commented on add-ons/submariner/deploy_subm_manual.adoc
> +Replace `managed-cluster-namespace` with the namespace of your managed cluster. The name of the `SubmarinerConfig` must be `submariner`, as shown in the example.
```suggestion
Replace `managed-cluster-namespace` with the name of your managed cluster. The name of the `SubmarinerConfig` must be `submariner`, as shown in the example.
```

2023-01-11 08:18 UTC, sridhargaddam commented on add-ons/submariner/deploy_subm_manual.adoc
> +This configuration uses the default network address translation - traversal (NATT) port (4500/UDP) for your Submariner and one worker node is labeled as the Submariner gateway on your bare metal clus
```suggestion
This configuration labels one of the worker node as the Submariner gateway on your bare metal cluster.
```

2023-01-11 08:18 UTC, sridhargaddam commented on add-ons/submariner/deploy_subm_manual.adoc
> +Submariner uses IP security (IPsec) to establish the secure tunnels between the clusters on the gateway nodes. You can either use the default IPsec NATT port, or you can specify a different port that
```suggestion
By default, Submariner uses IP security (IPsec) to establish the secure tunnels between the clusters on the gateway nodes. You can either use the default IPsec NATT port, or you can specify a different port that you configured. When you run this procedure without specifying an IPsec NATT port, 4500/UDP is used for the connections.
```

2023-01-11 08:18 UTC, sridhargaddam commented on add-ons/submariner/deploy_subm_manual.adoc
> +After manually preparing your selected hosting environment, you can deploy Submariner with the `ManagedClusterAddOn` API by complete the following steps:
```suggestion
After manually preparing your selected hosting environment, you can deploy Submariner with the `ManagedClusterAddOn` API by completing the following steps:
```

2023-01-11 08:18 UTC, sridhargaddam commented on add-ons/submariner/deploy_subm_manual.adoc
> +*Note:* The maximum length of the name of the Kubernetes namespace is 63 characters, so the maximum length of the `<managed-cluster-set-name>` is 56 characters. If the length of `<managed-cluster-set
```suggestion
*Note:* The maximum length of a Kubernetes namespace can be 63 characters. It is recommended that the maximum length of the `<managed-cluster-set-name>` is 56 characters or less. If the length of `<managed-cluster-set-name>` exceeds 56 chars, the `<managed-cluster-set-name>` is cut off from the head.
```

2023-01-11 08:18 UTC, sridhargaddam commented on add-ons/submariner/deploy_subm_manual.adoc
> +     globalnetEnabled: false
```suggestion
     globalnetEnabled: <true/false>
```

2023-01-11 08:18 UTC, sridhargaddam commented on add-ons/submariner/deploy_subm_manual.adoc
> +Replace `managed-cluster-namespace` with the namespace of your managed cluster.
A User may not be aware that we create a namespace for every managed cluster. Since a namespace is created with the same name as the managed cluster, shall we rephrase the sentence as below?

CC: @nyechiel @aswinsuryan @vthapar 

```suggestion
Replace `managed-cluster-namespace` with the name of your managed cluster.
```

2023-01-11 08:27 UTC, sridhargaddam commented on add-ons/submariner/subm_configure.adoc
> +* Firewall configuration across all nodes in each of the managed clusters must allow 4800/UDP in both directions.
```suggestion
* If your OCP clusters use OpenShift SDN CNI, the firewall configuration across all nodes in each of the managed clusters must allow 4800/UDP in both directions.
```

2023-01-11 08:29 UTC, sridhargaddam requested changes

2023-01-11 08:29 UTC, sridhargaddam commented on add-ons/submariner/subm_configure.adoc
> +* Firewall configuration on the Gateway nodes must allow ingress 8080/TCP so that the other nodes in the cluster can access it.
This step is no longer needed.

```suggestion
```

2023-01-11 08:30 UTC, sridhargaddam commented on add-ons/submariner/subm_configure.adoc
> +* Firewall configuration must be open for 4500/UDP and any other ports that are used for IPsec traffic on the gateway nodes.
```suggestion
* Firewall configuration must allow 4500/UDP, 4490/UDP on the gateway nodes for establishing tunnels between the managed clusters. 
```

2023-01-11 08:31 UTC, sridhargaddam commented on add-ons/submariner/subm_configure.adoc
> +*Note:* This is configured automatically when your clusters are deployed in an AWS or GCP environment, but must be configured manually for clusters on other environments and for the firewalls that pr
```suggestion
*Note:* This is configured automatically when your clusters are deployed in an AWS, GCP, Azure and Red Hat OpenStack environments, but must be configured manually for clusters on other environments and for the firewalls that protect private clouds.
```

2023-01-11 08:32 UTC, sridhargaddam commented on add-ons/submariner/subm_configure.adoc
> +
Please add one more entry as shown below.

| NAT discovery port
| 4490/UDP
| No
| Required

2023-01-11 08:34 UTC, sridhargaddam commented on add-ons/submariner/subm_configure.adoc
> +If there is a chance that your clusters running Submariner might have overlapping CIDRs, consider enabling Globalnet. When using the console, the `ClusterAdmin` can enable Globalnet for a cluster set
```suggestion
If there is a chance that your clusters running Submariner might have overlapping CIDRs, consider enabling Globalnet. When using the console, the `ClusterAdmin` can enable Globalnet for a clusterset by selecting the option *Enable Globalnet* when enabling the Submariner add-on for clusters in the clusterset. After you enable Globalnet, you cannot disable it without removing Submariner.
```

2023-01-11 15:04 UTC, oafischer commented on add-ons/submariner/deploy_subm_manual.adoc
> +
Added

2023-01-11 15:16 UTC, oafischer commented on add-ons/submariner/deploy_subm_manual.adoc
> +*Note:* The maximum length of the name of the Kubernetes namespace is 63 characters, so the maximum length of the `<managed-cluster-set-name>` is 56 characters. If the length of `<managed-cluster-set
As per IBM style, "can" indicates an ability. I'd consider the character limit more of a limit than an ability. I also wouldn't say that 56 characters or fewer is a recommendation if it's also a hard limitation. I'll make a couple changes to the wording but I think we need to keep most of it as is.

2023-01-11 15:32 UTC, oafischer commented on add-ons/submariner/subm_configure.adoc
> +If there is a chance that your clusters running Submariner might have overlapping CIDRs, consider enabling Globalnet. When using the console, the `ClusterAdmin` can enable Globalnet for a cluster set
We refer to it as cluster set in the docs, unless we are talking about a specific value or parameter.

2023-01-11 15:51 UTC, oafischer commented
@sridhargaddam Thanks for another review! I implemented most of your suggestions and fixed a number of broken links as well. Hoping we can merge this soon if you or @dfarrell07 or @nyechiel want to take a last look.

2023-01-12 10:14 UTC, MaxBab commented on add-ons/submariner/deploy_subm_console.adoc
> +
@sridhargaddam 

Azure clusters has the following fields:
`Base domain resource group name`
`Client ID`
`Client secret`
`Subscription ID`
`Tenant ID`

2023-01-12 11:03 UTC, MaxBab commented on add-ons/submariner/deploy_subm_console.adoc
> +|===
In additional to the above fields, the following new fields were introduced in ACM 2.7 release for every platform:

| `Disconnected cluster`
| Enable this option to instruct Submariner not to access any external servers for public IP resolution.

| `Globalnet CIDR`
| The Globalnet CIDR to be used for the managed cluster (If left blank, a CIDR will be allocated from clusterset pool).

*Note* - The `Globalnet CIDR` parameter appears only when *Globalnet* configuration selected on the clusterset.

2023-01-12 11:03 UTC, MaxBab commented on add-ons/submariner/deploy_subm_manual.adoc
> +== Preparing Microsoft Azure Red Hat OpenShift for Submariner (Technology Preview)
As far as I know ARO is not a tech preview and going to be fully supported in the upcoming release.
So need to remove the tech preview note.

@nyechiel ^^

2023-01-12 11:03 UTC, MaxBab commented on add-ons/submariner/install_subctl.adoc
> +oc image extract registry.redhat.io/rhacm2/subctl-rhel8:v0.13 --path=/dist/subctl-v0.13.0-linux-amd64.tar.xz:/tmp/ --confirm
Need to update the version of the subctl from v0.13 to v0.14 here and in the following lines below:
12, 17, 23

2023-01-12 14:24 UTC, oafischer commented on add-ons/submariner/deploy_subm_manual.adoc
> +== Preparing Microsoft Azure Red Hat OpenShift for Submariner (Technology Preview)
If it is fully supported we will need to update the support matrix as well, and one or two sections in this doc.

2023-01-12 15:01 UTC, oafischer commented on add-ons/submariner/deploy_subm_console.adoc
> +
Added the extra fields, table is kind of long, hope that's OK. Maybe in the future if it gets too long we can find a way to restructure.

2023-01-12 15:17 UTC, sridhargaddam commented on add-ons/submariner/deploy_subm_console.adoc
> +
thanks @MaxBab

2023-01-12 15:20 UTC, sridhargaddam commented on add-ons/submariner/deploy_subm_manual.adoc
> +== Preparing Microsoft Azure Red Hat OpenShift for Submariner (Technology Preview)
I'll let @nyechiel comment about it, but AFAIR both ARO/ROSA (which use SM LB mode) are tech preview.

2023-01-12 15:34 UTC, oafischer commented on add-ons/submariner/install_subctl.adoc
> +oc image extract registry.redhat.io/rhacm2/subctl-rhel8:v0.13 --path=/dist/subctl-v0.13.0-linux-amd64.tar.xz:/tmp/ --confirm
Done

2023-01-16 18:11 UTC, sridhargaddam approved these changes

2023-01-16 19:53 UTC, oafischer commented
Thanks for approving @sridhargaddam, I'm going to merge so I can work on other Submariner issues. If we still need to update some sections (like tech preview) we can fix them later (probably in a new issue).

2023-01-16 19:54 UTC, merged