Deprecated resources--upgrade known issue
open-cluster-management/rhacm-docs pull request #4467
Opened 2022-12-20 02:29 UTC by swopebe

2022-12-20 13:24 UTC, cadawson requested changes
Looks good! A few questions/suggestions, but nothing show-stopping. Approved after your consideration. Thanks!

2022-12-20 13:24 UTC, cadawson commented on release_notes/known_issues.adoc
> +=== Deprecated resources remain after upgrade to Errata versions
"Errata versions" makes me think of 2.4.5 > 2.4.6, for example. I know technically 2.4-2.5 is a y-stream errata, but I don't think we refer to them now as Errata versions. Would it be clearer to say "later versions" or similar? If there is a reason for it, it might be good for us to know what we mean by errata versions.

2022-12-20 13:24 UTC, cadawson commented on release_notes/known_issues.adoc
> +After you upgrade from 2.4.x to 2.5.x, and then to 2.6.x, the following deprecated resources in the managed cluster namespace might remain. You need to manually delete these deprecated resources if v
Suggestion: Change "..the following deprecated resources in the managed cluster namespace might remain." to "..some deprecated resources might remain in the managed cluster namespace." "The following" implies to me that it is directly introducing the list.

2022-12-20 13:24 UTC, cadawson commented on release_notes/known_issues.adoc
> +**Best practice:** Wait 30 minutes or more before you upgrade from version 2.5.x to version 2.6.x.
Is this a best practice, or an important note? It sounded like it might be a real issue if it is not done, but maybe it doesn't apply to every case.

2022-12-20 14:16 UTC, swopebe commented on release_notes/known_issues.adoc
> +=== Deprecated resources remain after upgrade to Errata versions
That is mentioned in the content, headers need to be simple. Is your feedback on the header or the content?

Simple is best for headers and SEO.

2022-12-21 00:33 UTC, zhiweiyin318 commented on release_notes/known_issues.adoc
> +**Best practice:** Wait 30 minutes or more before you upgrade from version 2.5.x to version 2.6.x.
I think this is an important note. it may meet this issue if the waiting time is too short.

2023-01-03 01:05 UTC, swopebe commented
Please see the other changes are implemented. I changed to Errata release -- instead of versions?

2023-01-05 21:04 UTC, cadawson approved these changes
I think the important note was removed from the end. Was that intentional? It might be good to add that back, unless you had a different opinion from someone. This line: 
*Important:* Wait 30 minutes or more before you upgrade from version 2.5.x to version 2.6.x.
Otherwise, it looks good. Thanks!

2023-01-05 21:04 UTC, cadawson commented on release_notes/known_issues.adoc
> +=== Deprecated resources remain after upgrade to Errata versions
My comment was on the header. Thinking "Deprecated resources remain after upgrade to later versions" might be simpler. I don't know that we refer to them as "Errata versions" anywhere. Maybe we are, and I missed it.

2023-01-05 21:18 UTC, merged