Updating the RBAC topic
open-cluster-management/rhacm-docs pull request #4473
Opened 2022-12-21 19:25 UTC by dockerymick

https://github.com/stolostron/backlog/issues/26917

2023-01-06 16:01 UTC, oafischer commented on access_control/rbac_implementation.adoc
> +- Create and administer cluster role bindings for all managed clusters. For example, create a cluster role binding to the cluster role `open-cluster-management:cluster-manager-admin` by entering the
I would try playing around with formatting here to fix the bold issues.

2023-01-06 16:30 UTC, dockerymick commented on access_control/rbac_implementation.adoc
> +- Create and administer cluster role bindings for all managed clusters. For example, create a cluster role binding to the cluster role `open-cluster-management:cluster-manager-admin` by entering the
Thanks Oliver!

2023-01-06 16:32 UTC, oafischer approved these changes
lgtm

2023-01-10 15:24 UTC, ckandag requested changes

2023-01-10 15:24 UTC, ckandag commented on access_control/rbac.adoc
>  * If a user does not have role access to a cluster, the cluster name is not visible. The cluster name is displayed with the following symbol: `-`.
The cluster name is displayed with the following symbol: `-`.   

This is not always correct, its mostly just not shown/displayed. e.g. when the user goes to view main Clusters overview - Only the clusters, user has access to, are displayed in the page.   The ones that are not accessible are simply Not shown at all.

There may be one or two UI pages where its displayed with '_'.

I would suggest changing to indicate something like ,    if the cluster name is showing as "-" then user may not have to it

2023-01-11 17:27 UTC, dockerymick commented
@ckandag thanks for your review. i have made updates based on your comment. Merging this PR

2023-01-11 17:27 UTC, merged