stolostron/backlog#27060 title update
open-cluster-management/rhacm-docs pull request #4483
Opened 2023-01-06 15:18 UTC by cadawson

2023-01-06 15:19 UTC, cadawson commented
Hi @xuezhaojun. Here is the title change for the second part of issue #27060. Let me know if it looks ok. Thanks!

2023-01-06 20:09 UTC, swopebe requested changes

2023-01-06 20:09 UTC, swopebe commented on multicluster_engine/cluster_lifecycle/import_clust_custom_image.adoc
> +There might be times when you need to override the registry images on the managed clusters that you are importing. You can do this by creating a `ManagedClusterImageRegistry` custom resource definiti
We may need to revisit some concise writing exercises in the arch call/scrum to help with this:

There might be times when you need to override

change to 

You might (_there may be times_ is wordy)

2023-01-06 20:09 UTC, swopebe commented on multicluster_engine/cluster_lifecycle/import_clust_custom_image.adoc
>    clusterSet: myClusterSet
Let's discuss titles and file names in the call today.

2023-01-06 20:09 UTC, swopebe commented on multicluster_engine/cluster_lifecycle/import_clust_custom_image.adoc
> +There might be times when you need to override the registry images on the managed clusters that you are importing. You can do this by creating a `ManagedClusterImageRegistry` custom resource definiti
Raised in the meeting today, we need anchors and file names to be intuitive to titles, especially since the portal does not show file names. This helps internally and externally.

All agreed to use words in the file names unless an abbreviation makes sense. (cluster)

Title option: 

Specifying registry images on managed clusters for import

2023-01-06 20:09 UTC, swopebe commented on multicluster_engine/cluster_lifecycle/import_clust_custom_image.adoc
>    clusterSet: myClusterSet
done

2023-01-06 22:14 UTC, swopebe commented on multicluster_engine/cluster_lifecycle/import_clust_custom_image.adoc
>  +
Confused about what "it is" here, could use some clarity and maybe even combining this sentence.

2023-01-06 22:15 UTC, dockerymick commented on multicluster_engine/cluster_lifecycle/import_clust_custom_image.adoc
> +There might be times when you need to override the registry images on the managed clusters that you are importing. You can do this by creating a `ManagedClusterImageRegistry` custom resource definiti
+1 for "Specifying registry images on managed clusters for import"

2023-01-06 22:16 UTC, swopebe commented on multicluster_engine/cluster_lifecycle/import_clust_custom_image.adoc
> +== Importing a cluster that has a ManagedClusterImageRegistry custom resource definition
Title a bit too long:

Importing a cluster that has a customized ManagedClusterImageRegistry

2023-01-09 06:04 UTC, xuezhaojun commented
/lgtm

2023-01-09 06:05 UTC, xuezhaojun reviewed
The new title `Specifying registry images with a ManagedClusterImageRegistry custom resource definition when importing` looks good to me!

2023-01-11 12:44 UTC, cadawson commented
Hi @xuezhaojun. The previous title was a little longer than we like them to be. The new one is a little shorter. Please take a look and see if that one works. Thanks!

2023-01-11 12:53 UTC, xuezhaojun commented
> Hi @xuezhaojun. The previous title was a little longer than we like them to be. The new one is a little shorter. Please take a look and see if that one works. Thanks!

Thanks for the update, it looks good to me!

2023-01-11 21:25 UTC, merged