Add opaque secret creation 2.7 stolostron/backlog#27002
open-cluster-management/rhacm-docs pull request #4494
Opened 2023-01-10 19:25 UTC by oafischer

https://github.com/stolostron/backlog/issues/27002

2023-01-12 19:38 UTC, swopebe approved these changes
Maybe make clearer that it is the one thing that cannot be done in the console.

2023-01-12 19:40 UTC, oafischer commented on multicluster_engine/credentials/credential_vm.adoc
> +    name: <managed-cluster-name>-vsphere-creds
Let's double check that the provider short name is indeed vsphere

2023-01-12 19:52 UTC, manosnoam requested changes

2023-01-12 19:52 UTC, manosnoam commented on multicluster_engine/credentials/credential_aws.adoc
> +data:
The data part is missing, it is unique to AWS platform.

2023-01-12 19:52 UTC, manosnoam commented on multicluster_engine/credentials/credential_azure.adoc
> +data:
The data part is missing, it is unique to Azure platform.

2023-01-12 19:52 UTC, manosnoam commented on multicluster_engine/credentials/credential_google.adoc
> +data:
The data part is missing, it is unique to GCP platform.

2023-01-12 19:52 UTC, manosnoam commented on multicluster_engine/credentials/credential_openstack.adoc
> +data:
The data part is missing, it is unique to Openstack platform.

2023-01-12 19:52 UTC, manosnoam commented on multicluster_engine/credentials/credential_vm.adoc
> +data:
The data part is missing, it is unique to VMware platform.

2023-01-12 19:59 UTC, oafischer commented on multicluster_engine/credentials/credential_aws.adoc
> +data:
Fixed

2023-01-12 20:00 UTC, oafischer commented on multicluster_engine/credentials/credential_azure.adoc
> +data:
Fixed

2023-01-12 20:01 UTC, oafischer commented on multicluster_engine/credentials/credential_google.adoc
> +data:
Fixed

2023-01-12 20:01 UTC, oafischer commented on multicluster_engine/credentials/credential_openstack.adoc
> +data:
Fixed

2023-01-12 20:02 UTC, oafischer commented on multicluster_engine/credentials/credential_vm.adoc
> +data:
Fixed

2023-01-12 22:20 UTC, manosnoam requested changes

2023-01-12 22:20 UTC, manosnoam commented on multicluster_engine/credentials/credential_azure.adoc
> +data:
Each platform has the data part **different**.

For example, on Azure I use:
```
data:
      baseDomainResourceGroupName: $(echo -n "${azure_resource_group_name}" | base64 -w0)
      osServicePrincipal.json: $(base64 -w0 "${AZURE_CRED_JSON}")

```
Where azure_resource_group_name is the relevant one for your cluster, as found in RG list, generated by command `az group show`.

Usually it is:
`azure_resource_group_name=${ocp_infra_id}-rg`

Where ocp_infra_id is retreived by:
`oc get -o jsonpath='{.status.infrastructureName}{"\n"}' infrastructure cluster`

2023-01-12 22:20 UTC, manosnoam commented on multicluster_engine/credentials/credential_google.adoc
> +data:
Same goes for GCP - the data is unique:

```
data:
        osServiceAccount.json: $(base64 -w0 "${GCP_CRED_JSON}")
```

2023-01-12 22:20 UTC, manosnoam commented on multicluster_engine/credentials/credential_openstack.adoc
> +data:
Same goes for Openstack - the data is unique:

```
data:
                clouds.yaml: $(base64 -w0 "${OSP_CRED_YAML}")
                cloud: $(echo -n "openstack" | base64 -w0)
```

2023-01-12 22:20 UTC, manosnoam commented on multicluster_engine/credentials/credential_vm.adoc
> +    name: <managed-cluster-name>-vsphere-creds
I'm quite sure for VMware the data is also unique.
Please check with CLC team.

2023-01-13 14:11 UTC, oafischer commented on multicluster_engine/credentials/credential_vm.adoc
> +    name: <managed-cluster-name>-vsphere-creds
@elgnay

2023-01-19 20:17 UTC, cadawson approved these changes
This looks good to me. I will reach out to Le tonight to see if he or someone else can close out the open questions. Thanks!

2023-01-20 10:31 UTC, elgnay commented on multicluster_engine/credentials/credential_vm.adoc
> +    name: <managed-cluster-name>-vsphere-creds
```
data:
      username: $(echo -n "${VMW_USERNAME}" | base64 -w0)
      password.json: $(base64 -w0 "${VMW_PASSWORD}")
```

2023-01-20 10:43 UTC, elgnay commented
I noticed that the guide in `Managing a credential by using the console` is to create user credential (secret A) in user namespace which can be used by ACM console to provision cluster later, while the guide in `Creating an opaque secret by using the API` is to create secret (secret B) in cluster namespace which will be used by Hive to provision cluster. Normally secret A contains more information than Secret B. When provision cluster with ACM console, Secret A will be copied to the cluster namespace as Secret B. Please make sure the reader know the difference.

2023-01-20 20:49 UTC, oafischer commented
Made some fixes, is this ready to merge @manosnoam?

2023-01-24 16:26 UTC, oafischer commented
I assume this is fine, merging. If we need more updates we can open another issue.

2023-01-24 16:26 UTC, merged