adding instructions to disable alert forwarding for managed clusters
open-cluster-management/rhacm-docs pull request #4509
Opened 2023-01-12 15:28 UTC by dockerymick

https://github.com/stolostron/backlog/issues/26981

2023-01-12 15:30 UTC, dockerymick commented on observability/customize_observability.adoc
> -* <<forward-alerts,Forwarding alerts>>
@marcolan018 I moved Forwarding alerts to be after the Configuring AlertManager section. Can you confirm if the doc info is still accurate with the section order change?

2023-01-12 16:57 UTC, dockerymick commented on observability/customize_observability.adoc
> -* <<forward-alerts,Forwarding alerts>>
@subbarao-meduri ^

2023-01-12 17:54 UTC, marcolan018 approved these changes
lgtm

2023-01-12 21:26 UTC, swopebe commented on observability/customize_observability.adoc
> +- <<export-metrics-to-external-endpoints,Export metrics to external endpoints>>
Can we make sure the verbs are all parallel here in this list of sections?

2023-01-12 21:26 UTC, swopebe commented on observability/customize_observability.adoc
> +- <<disable-observability,Disable observability>>
same thing here with Disable

2023-01-12 21:27 UTC, swopebe requested changes
couple comments regarding the anchors/sections.

2023-01-17 14:42 UTC, swopebe approved these changes

2023-01-17 15:43 UTC, dockerymick commented
Thanks for yall reviews and approvals! Merging this PR

2023-01-17 15:43 UTC, merged