Update troubleshoot
open-cluster-management/rhacm-docs pull request #4531
Opened 2023-01-16 20:31 UTC by oafischer

https://github.com/stolostron/backlog/issues/26892

2023-01-16 20:32 UTC, oafischer commented on multicluster_engine/support_troubleshooting/trouble_cluster_offline_cert_mce.adoc
> +oc create secret -n <cluster_name> <cluster_name>-import
@skeeey The draft you provided said `oc delete`. Is that correct or a typo?

2023-01-16 20:32 UTC, oafischer commented on troubleshooting/trouble_cluster_offline_cert.adoc
> +oc create secret -n <cluster_name> <cluster_name>-import
@skeeey The draft you provided said `oc delete`. Is that correct or a typo?

2023-01-17 01:22 UTC, skeeey commented on multicluster_engine/support_troubleshooting/trouble_cluster_offline_cert_mce.adoc
> +oc create secret -n <cluster_name> <cluster_name>-import
@oafischer here should be `oc delete`, user delete the secret, then our import controller will create the secret again with new hub info. thanks

2023-01-17 01:22 UTC, skeeey commented on troubleshooting/trouble_cluster_offline_cert.adoc
> +oc create secret -n <cluster_name> <cluster_name>-import
@oafischer here should be `oc delete`, user delete the secret, then our import controller will create the secret again with new hub info. thanks

2023-01-17 15:13 UTC, dockerymick requested changes

2023-01-17 15:13 UTC, dockerymick commented on multicluster_engine/support_troubleshooting/trouble_cluster_offline_cert_mce.adoc
> +If your managed cluster is `local-cluster`, or your managed cluster was created by using {mce}, your cluster resynchronizes every 10 minutes and you must 10 minutes or longer for your managed cluster
I recommend the following:

If your managed cluster is the `local-cluster` or your managed cluster was created by using {mce}, you must configure your cluster to resynchronize every 10 minutes or longer for your managed cluster to reimport.

2023-01-17 15:13 UTC, dockerymick commented on multicluster_engine/support_troubleshooting/trouble_cluster_offline_cert_mce.adoc
> +To reimport your managed cluster immediately, you can delete your managed cluster import secret on the hub cluster and reimport it by using {mce-short} by running the following command:
...and reimport it by using {mce-short}. Run the following command:

2023-01-17 15:13 UTC, dockerymick commented on multicluster_engine/support_troubleshooting/trouble_cluster_offline_cert_mce.adoc
> +If you want to reimport a managed cluster that was imported by using {mce-short}, run the following command to import the managed cluster again:
Incomplete, missing the command

2023-01-17 15:13 UTC, dockerymick commented on troubleshooting/trouble_cluster_offline_cert.adoc
> +If your managed cluster is `local-cluster`, or your managed cluster was created by using {product-title}, your cluster resynchronizes every 10 minutes and you must 10 minutes or longer for your manag
similar grammar suggestions from the previous file

2023-01-17 15:13 UTC, dockerymick commented on troubleshooting/trouble_cluster_offline_cert.adoc
> +. On the managed cluster, apply the `import.yaml` fileby running the following command:
Similar suggestions here as well

2023-01-17 15:31 UTC, oafischer commented on multicluster_engine/support_troubleshooting/trouble_cluster_offline_cert_mce.adoc
> +If your managed cluster is `local-cluster`, or your managed cluster was created by using {mce}, your cluster resynchronizes every 10 minutes and you must 10 minutes or longer for your managed cluster
Thanks for your suggestion! The user is not configuring resynchronization since this is set to 10 minutes regardless. Does the following sound OK instead?

If your managed cluster is the `local-cluster` or your managed cluster was created by using {mce}, you must wait 10 minutes or longer to reimport your managed cluster.

I think that should imply that resync is set at 10 minutes so we don't have to say it directly.

2023-01-17 15:34 UTC, oafischer commented on multicluster_engine/support_troubleshooting/trouble_cluster_offline_cert_mce.adoc
> +If you want to reimport a managed cluster that was imported by using {mce-short}, run the following command to import the managed cluster again:
Oops, was supposed to say "complete the following steps", thanks for catching that!

2023-01-20 20:54 UTC, merged