Create Submariner disconnected docs 2.7 stolostron/backlog#26975
open-cluster-management/rhacm-docs pull request #4536
Opened 2023-01-17 15:54 UTC by oafischer

https://github.com/stolostron/backlog/issues/26975

2023-01-17 16:04 UTC, nyechiel reviewed
LGTM, only one nit. @sridhargaddam please review as well

2023-01-17 16:04 UTC, nyechiel commented on add-ons/submariner/subm_disconnected.adoc
> +If you are manually installing Submariner by using the APIs, you must set the `airGappedDeployment` parameter to `true` in the `SubmarinerConfig` associated with your managed cluster.
```suggestion
If you are installing Submariner by using the APIs, you must set the `airGappedDeployment` parameter to `true` in the `SubmarinerConfig` associated with your managed cluster. 
```

2023-01-17 16:05 UTC, nyechiel commented on add-ons/submariner/subm_disconnected.adoc
> +If you are manually installing Submariner by using the APIs, you must set the `airGappedDeployment` parameter to `true` in the `SubmarinerConfig` associated with your managed cluster.
I don't think we need to refer to the API as "manual"; it's fully automated, just not via the UI.

2023-01-17 17:43 UTC, swopebe commented on add-ons/submariner/subm_disconnected.adoc
> +To deploy Submariner with {product-title} on clusters that are not connected to the internet (disconnected), you must first complete the steps outlined in link:../install/install_disconnected.adoc#in
This is very confusing to me: 

1. We can eliminate words for conciseness: 
To deploy Submariner with {product-title} on disconnected clusters...

2. With RHACM?  This can be viewed a few different ways. Are we saying deploy on to disconnected RHACM clusters or deploying "Submariner with RHACM"?

2023-01-17 17:51 UTC, swopebe commented on add-ons/submariner/subm_disconnected.adoc
> +To deploy Submariner with {product-title} on clusters that are not connected to the internet (disconnected), you must first complete the steps outlined in link:../install/install_disconnected.adoc#in
This is what I raised is missing from some of the cluster/MCE doc...good short descriptions...and we have had a few tickets opened as a result. Moving forward, I would like to understand why the user wants to do this.

2023-01-17 17:55 UTC, swopebe commented on add-ons/submariner/subm_disconnected.adoc
> +By default, `submariner-addon` looks for a `catalogSource` with the name `redhat-operators`. When using a `catalogSource` with a different name, you must update the value of the `SubmarinerConfig.Spe
**Use with caution look and feel**   noun
In technical information, use wording that more specifically expresses what you mean. (from the manual)

Not only is this technically anthropomorphism, which sometimes we cannot avoid easily, we don't normally use the word "look" in tech doc for the reasons I copied. If this cannot avoid it, I recommend a more industry-standard word like "search" if that works.

2023-01-17 17:55 UTC, swopebe commented on add-ons/submariner/subm_disconnected.adoc
> +
so that Submariner does not call external servers (more active and concise)

2023-01-17 17:56 UTC, swopebe commented on release_notes/whats_new.adoc
> +* Submariner has a new `LoadBalancer` mode that simplifies the deployment of Microsoft Azure Red Hat OpenShift clusters and Red Hat OpenShift Service on AWS  clusters. See link:../add-ons/submariner/
You can use the new Submariner `LoadBalancer` mode that. (extra space)

2023-01-17 17:57 UTC, swopebe commented on release_notes/whats_new.adoc
so that you can....(maybe just another line here about the benefit?)

2023-01-17 17:57 UTC, swopebe requested changes
few comments when you have a chance

2023-01-17 17:58 UTC, oafischer commented on add-ons/submariner/subm_disconnected.adoc
> +To deploy Submariner with {product-title} on clusters that are not connected to the internet (disconnected), you must first complete the steps outlined in link:../install/install_disconnected.adoc#in
I think it means "Submariner with RHACM". For your second comment, still waiting on content for that. This PR actually wasn't ready for peer review yet.

2023-01-17 18:02 UTC, oafischer commented on release_notes/whats_new.adoc
> +* Submariner has a new `LoadBalancer` mode that simplifies the deployment of Microsoft Azure Red Hat OpenShift clusters and Red Hat OpenShift Service on AWS  clusters. See link:../add-ons/submariner/
Will add once that info comes in (I asked for it in the main issue)

2023-01-17 18:02 UTC, oafischer commented on release_notes/whats_new.adoc
Will add once that info comes in (I asked for it in the main issue)

2023-01-17 19:46 UTC, swopebe approved these changes

2023-01-20 19:07 UTC, sridhargaddam reviewed
One small comment, otherwise LGTM. Thanks @oafischer

2023-01-20 19:07 UTC, sridhargaddam commented on add-ons/submariner/subm_disconnected.adoc
> +When installing `submariner-addon` on a managed cluster from the {product-title} console, you can select the *Disconnected cluster* option so that Submariner does not call external servers.
Instead of using "call", let us use "API queries"

```suggestion
When installing `submariner-addon` on a managed cluster from the {product-title} console, you can select the *Disconnected cluster* option so that Submariner does not make API queries to external servers.
```

2023-01-20 19:39 UTC, oafischer commented
Thanks for the review @sridhargaddam, can you share one or two quick reasons/benefits why the user would want to deploy Submariner on disconnected clusters? I want to add a little context to the what's new entry.

2023-01-21 06:25 UTC, sridhargaddam commented
> Thanks for the review @sridhargaddam, can you share one or two quick reasons/benefits why the user would want to deploy Submariner on disconnected clusters? I want to add a little context to the what's new entry.

Some customers prefer deployments in a disconnected environment mainly for security reasons. They do this to protect the clusters from external entities and malicious attacks. So the OCP clusters are in an Air-gapped deployment and we are installing Submariner to provide connectivity between the clusters while ensuring that Submariner works even when there is no access to public internet.

2023-01-21 06:26 UTC, sridhargaddam approved these changes

2023-01-21 16:44 UTC, nyechiel approved these changes

2023-01-23 15:27 UTC, merged