provision cluster in aws private link
open-cluster-management/rhacm-docs pull request #4553
Opened 2023-01-18 06:22 UTC by ldpliu

Signed-off-by: ldpliu <daliu@redhat.com>
https://github.com/stolostron/backlog/issues/27110

2023-01-18 06:25 UTC, ldpliu commented
@dtthuynh  Thanks for your [doc](https://docs.google.com/document/d/1vfb_bxoNnCm8xmSglevOmL29gut9F0IEhYhvhQl-CPI/edit#) about provision cluster in aws private.
I create this pr based on your doc and hive doc, please help to review it works fine.
@cadawson Please also help to review and change it. 
Thank you.

2023-01-18 21:34 UTC, dtthuynh commented on multicluster_engine/cluster_lifecycle/create_ocp_aws_private.adoc
> +* Subnets: Specify subnets for each availability zone that your cluster uses.
can specific to provide the private subnets

2023-01-18 21:39 UTC, dtthuynh commented on multicluster_engine/cluster_lifecycle/create_ocp_aws_private.adoc
> += Creating a cluster on Amazon Web Services Private
"Creating a private cluster on Amazon Web Services (AWS)" instead?
Not sure if we also want to specify if this will include other areas such as provisioning on AWS Gov region specifically.

2023-01-18 21:40 UTC, dtthuynh commented on multicluster_engine/cluster_lifecycle/create_ocp_aws_private.adoc
> +When you create a cluster, the creation process uses the {ocp-short} installer with the Hive resource. If you have questions about cluster creation after completing this procedure, see https://access
should we link it to the ocp doc for installing on private aws instead if this doc is around private?
e.g. https://docs.openshift.com/container-platform/4.11/installing/installing_aws/installing-aws-private.html

2023-01-19 21:13 UTC, swopebe requested changes
def think this is mot following modular doc

2023-01-19 21:13 UTC, swopebe commented on multicluster_engine/cluster_lifecycle/create_ocp_aws_private.adoc
> +When you create a cluster, the creation process uses the {ocp-short} installer with the Hive resource. If you have questions about cluster creation after completing this procedure, see https://access
portal link, yes

2023-01-19 22:19 UTC, cadawson commented
And, it looks like we ended up with 2 PRs. I tried merging this one into the other one, but it will take more work. I created that one to try to get it done before vacation. Here is that PR: https://github.com/stolostron/rhacm-docs/pull/4560. I would like to use that PR because I have some other changes to add the files, but hopefully we can successfully merge the information into a great doc! Thanks @ldpliu and @dtthuynh .

2023-01-20 00:56 UTC, swopebe commented
Please see the playbook guidance, where we ask for teams to use GH comments or links to other sources for major release changes, so that we can write and build the content as needed for the Portal. Small changes via PRs are great! 

The source for the doc process is always found in the Playbook:

https://docs.google.com/document/d/1YTqpZRH54Bnn4WJ2nZmjaCoiRtqmrc2w6DdQxe_yLZ8/edit#heading=h.9fvyr2rdriby

2023-01-26 21:45 UTC, cadawson commented
Would like to close this one as I merged the content in https://github.com/stolostron/rhacm-docs/pull/4560.

2023-01-28 01:40 UTC, closed without merging