Reorganizing and improving doc for search
open-cluster-management/rhacm-docs pull request #4598
Opened 2023-01-23 17:57 UTC by dockerymick

https://github.com/stolostron/backlog/issues/27109

2023-01-23 21:42 UTC, dockerymick commented
Please dont be intimidated by the number of files changed in this PR. Since I added a new file, I had to update links in multiple places. The main files that we will focus on during the review are `search_intro.adoc` and `manage_search.adoc`. 

I understand that the goal is to have modular doc. So basically, we want docs that have subsections to be split into separate files. Since GA is approaching, I will keep the file organization as is. I will recommend that we focus on making doc modular after 2.7 Release

2023-01-23 21:43 UTC, dockerymick commented
I also made a small update related to the way that we highlight the "Note: " tag

2023-01-23 21:48 UTC, dockerymick commented on observability/search_intro.adoc
> +//is there a specific name for the REST API?
Comment here. 

* I am concerned with naming consistency. Is the name of the `Search` custom resource `searchcustomization`, `search-v2-operator`, or just `Search` ? 

* Also is there a specific name for the REST API

* Does `apiVersion: search.open-cluster-management.io/v1alpha1` need to be updated ?

2023-01-24 15:20 UTC, cadawson requested changes
That was a bigger one. Most of the comments are editing and consistency, so nothing major. Let me know if you have any questions. Thanks!

2023-01-24 15:20 UTC, cadawson commented on backup_restore/manage_backup_restore.adoc
> +*Note:* If you have previously installed and used the OADP Operator on the hub cluster, in a namespace different from the backup component namespace, uninstall this version since the backup component
If you have previously installed and used the OADP Operator on the hub cluster in a namespace different from the backup component namespace, uninstall this version since the backup component now works with OADP installed in the component namespace. Use the same storage location for the link:https://github.com/openshift/oadp-operator/blob/master/docs/install_olm.md#create-the-dataprotectionapplication-custom-resource[`DataProtectionApplication`] resource that is owned by the OADP Operator installed with the backup component; it accesses the same backup data as the previous operator. Velero backup resources are now loaded within the new OADP Operator namespace on this hub cluster.

2023-01-24 15:20 UTC, cadawson commented on backup_restore/manage_backup_restore.adoc
> +*Note:* The _resources backup_ file contains managed cluster-specific resources, but does not contain the subset of resources that connect managed clusters to the hub cluster. The resources that conn
...all managed clusters that are created by using the Hive API...

Remove "At this time". Is it necessary?

2023-01-24 15:20 UTC, cadawson commented on clusters/about/rbac_mce.adoc
> +*Note:* As a `team-admin` and `team-user`, you have `admin` permission to the `clusterpool`, `clusterdeplyment`, and `clusterclaim`.
clusterdeployment

2023-01-24 15:20 UTC, cadawson commented on console/console.adoc
> +_Search_ is also available from the _Home_ tab. To learn about Search, see link:../observability/search_intro.adocsearching-in-the-console-intro[Searching in the console introduction].
...search_intro.adoc#searching-in-the-console-intro...

2023-01-24 15:20 UTC, cadawson commented on governance/ansible_grc.adoc
> +*Note:* Ensure that the {aap-short} job template is idempotent when it is run. If you do not have {aap-short}  Resource Operator, you can find it from the {ocp} _OperatorHub_ page.
...when it is run. or when you run it. CD: This might not be a correct change. 

I think there is an extra space after {aap-short}

2023-01-24 15:20 UTC, cadawson commented on governance/ansible_grc.adoc
>  For more information about installing and configuring {aap}, see link:../applications/ansible_config.adoc#setting-up-ansible[Setting up Ansible tasks]
End period

2023-01-24 15:20 UTC, cadawson commented on observability/customize_observability.adoc
> +Define custom rules with Prometheus to create alert conditions, and send notifications to an external messaging service. *Note:* When you update your custom rules, `observability-thanos-rule` pods ar
New line for the note?

2023-01-24 15:20 UTC, cadawson commented on observability/customize_observability.adoc
> +*Note:* If this is the first new custom rule, it is created immediately. For changes to the ConfigMap, the configuration is automatically reloaded. The configuration is reloaded due to the `config-re
...reloaded because of the `config-reload`...

2023-01-24 15:20 UTC, cadawson commented on observability/manage_insights.adoc
> +*Note:* After the issue is resolved, the Red Hat Insights are received by {product-title-short} every 30 minutes and Red Hat Insights is updated every two hours.
...every 30 minutes, and Red Hat Insights is..

2023-01-24 15:20 UTC, cadawson commented on observability/manage_search.adoc
> +- <<querying-in-the-console,Querying in the console>>
Extra ** here?

2023-01-24 15:20 UTC, cadawson commented on observability/manage_search.adoc
> +Run the following command to view search customization CRD:
custom resource definition

2023-01-24 15:20 UTC, cadawson commented on observability/manage_search.adoc
> +You can disable persistence by updating the `persistence` flag to `false` in the customization CR, which turns off saving search index to the file system. A status for persistence can be retrieved fr
custom resource (make all changes, won't mention again)

2023-01-24 15:20 UTC, cadawson commented on observability/manage_search.adoc
> +RedisGraph is an in-memory database that needs linear growth of memory as the number of objects are cached. A {product-title-short} cluster with many managed clusters, or with a large number of Kuber
...RedisGraph pod...?

2023-01-24 15:20 UTC, cadawson commented on observability/manage_search.adoc
> +For more specific search results, include the property selector in your search. You can combine related values for the property, for a more precise scope of your search. For example, search for `clus
...values for the property for a more precise...   remove comma

2023-01-24 15:20 UTC, cadawson commented on observability/manage_search.adoc
> +View the following steps to make queries with search:
Complete the following steps...

2023-01-24 15:20 UTC, cadawson commented on observability/manage_search.adoc
> +** You can also search with conditions by using characters, such as `+>, >=, <, <=, !=+`.
Does the double asterisk work here, or does the rendering show up as highlighting?

2023-01-24 15:20 UTC, cadawson commented on observability/manage_search.adoc
> +. Filter your query with the following values: `kind:application` and `apigroup:argoproj.io`
Ending period

2023-01-24 15:20 UTC, cadawson commented on observability/manage_search.adoc
> +To collect the Kubernetes objects from the managed clusters, the `search-collector` process is run on all the managed clusters where search is enabled. The deployment ran is the `klusterlet-addon-sea
The deployment that is run is the...

A managed cluster with a high number of resources...

2023-01-24 15:20 UTC, cadawson commented on observability/observability_enable.adoc
> +*Note:* When observability is enabled or disabled on {ocp-short} managed clusters that are managed by {product-title-short}, the observability endpoint operator updates the `cluster-monitoring-config
Remove monospace from ConfigMap to be consistent.

Should we add monospace to alertmanager?

Change to "automatically restarts the local Prometheus instance."?

2023-01-24 15:20 UTC, cadawson commented on observability/observability_enable.adoc
> +*Note:* The `QUERY_EXPRESSION` is the standard Prometheus query expression. For example, query the metrics `cluster_infrastructure_provider` by replacing the URL in the previously mentioned command,
Remove comma: ...previously mentioned command with the following URL...

Capital Prometheus in the end link.

2023-01-24 15:20 UTC, cadawson commented on observability/observe_environments.adoc
> +*Note:* The time series historical data is stored in object stores. Thanos uses object storage as the primary storage for metrics and meta data related to them. For more details about the object stor
metadata one word

Ending period

2023-01-24 15:20 UTC, cadawson commented on observability/search_intro.adoc
> +Search is enabled by default. Search is also enabled when you provision, or manually import a managed cluster. If you want to disable search on your managed cluster, see link:../clusters/modify_endpo
...when you provision or manually import a managed cluster. Remove comma.

2023-01-24 15:20 UTC, cadawson commented on observability/search_intro.adoc
> +The search operator watches the watches the `Search` custom resource, reconciles the changes to the custom resource, and updates active pods. View the following descriptions of the configurations:
"watches the"  duplicated.

2023-01-24 15:20 UTC, cadawson commented on observability/search_intro.adoc
> +- PostGres database storage:
Should this be PostgreSQL? (global)

2023-01-24 15:20 UTC, cadawson commented on observability/search_intro.adoc
> +Learn how to manage search, see xref:../observability/manage_search.adoc#managing-search[Managing search]. For more topics about the {product-title} console, see link:../console/console_intro.adoc#we
For instructions about how to manage search, see...

Consideration: Maybe make these two a bulleted list or just have them on separate lines?

2023-01-24 19:53 UTC, dockerymick commented on observability/manage_search.adoc
> +- <<querying-in-the-console,Querying in the console>>
That's intentional. It's a subsection

2023-01-24 19:55 UTC, dockerymick commented on observability/search_intro.adoc
> +//check 'within' vs 'among'
@cadawson @swopebe can you provide your opinion here? 

The `search-collector` also computes relationships for resources **within** the managed cluster and sends it to the `search-indexer`.

OR 

The `search-collector` also computes relationships for resources **among** the managed cluster and sends it to the `search-indexer`.

2023-01-24 19:57 UTC, dockerymick commented on observability/manage_search.adoc
> +//Anxhela checking if empty query is allowed
@Anxhela21

2023-01-24 19:57 UTC, dockerymick commented on observability/manage_search.adoc
> +//Xavier please review
@xrajesh

2023-01-24 19:57 UTC, dockerymick commented
Will address other comments after I return from class

2023-01-24 22:20 UTC, cadawson reviewed
Suggestions to make some comments easier.

2023-01-24 22:20 UTC, cadawson commented on backup_restore/manage_backup_restore.adoc
> +*Note:* The _resources backup_ file contains managed cluster-specific resources, but does not contain the subset of resources that connect managed clusters to the hub cluster. The resources that conn
```suggestion
*Note:* The _resources backup_ file contains managed cluster-specific resources, but does not contain the subset of resources that connect managed clusters to the hub cluster. The resources that connect managed clusters are called activation resources and are contained in the managed clusters backup. When you restore backups only for the _credentials_ and _resources_ backup on a new hub cluster, the new hub cluster shows all managed clusters that are created by using the Hive API in a detached state. However, the managed clusters that are imported on the primary hub cluster using the import operation appear only when the activation data is restored on the passive hub cluster. At this time, the managed clusters are still connected to the original hub cluster that created the backup files.
```

2023-01-24 22:20 UTC, cadawson commented on clusters/about/rbac_mce.adoc
> +*Note:* As a `team-admin` and `team-user`, you have `admin` permission to the `clusterpool`, `clusterdeplyment`, and `clusterclaim`.
```suggestion
*Note:* As a `team-admin` and `team-user`, you have `admin` permission to the `clusterpool`, `clusterdeployment`, and `clusterclaim`.
```

2023-01-24 22:20 UTC, cadawson commented on console/console.adoc
> +_Search_ is also available from the _Home_ tab. To learn about Search, see link:../observability/search_intro.adocsearching-in-the-console-intro[Searching in the console introduction].
```suggestion
_Search_ is also available from the _Home_ tab. To learn about Search, see link:../observability/search_intro.adoc#searching-in-the-console-intro[Searching in the console introduction].
```

2023-01-24 22:20 UTC, cadawson commented on governance/ansible_grc.adoc
> +*Note:* Ensure that the {aap-short} job template is idempotent when it is run. If you do not have {aap-short}  Resource Operator, you can find it from the {ocp} _OperatorHub_ page.
```suggestion
*Note:* Ensure that the {aap-short} job template is idempotent when it is run. If you do not have {aap-short} Resource Operator, you can find it from the {ocp} _OperatorHub_ page. 
```

2023-01-24 22:20 UTC, cadawson commented on observability/customize_observability.adoc
> +Define custom rules with Prometheus to create alert conditions, and send notifications to an external messaging service. *Note:* When you update your custom rules, `observability-thanos-rule` pods ar
```suggestion
Define custom rules with Prometheus to create alert conditions, and send notifications to an external messaging service. 

*Note:* When you update your custom rules, `observability-thanos-rule` pods are restarted automatically.
```

2023-01-24 22:20 UTC, cadawson commented on observability/customize_observability.adoc
> +*Note:* If this is the first new custom rule, it is created immediately. For changes to the ConfigMap, the configuration is automatically reloaded. The configuration is reloaded due to the `config-re
```suggestion
*Note:* If this is the first new custom rule, it is created immediately. For changes to the ConfigMap, the configuration is automatically reloaded. The configuration is reloaded because of the `config-reload` within the `observability-thanos-ruler` sidecar.
```

2023-01-24 22:20 UTC, cadawson commented on observability/manage_insights.adoc
> +*Note:* After the issue is resolved, the Red Hat Insights are received by {product-title-short} every 30 minutes and Red Hat Insights is updated every two hours.
```suggestion
*Note:* After the issue is resolved, the Red Hat Insights are received by {product-title-short} every 30 minutes, and Red Hat Insights is updated every two hours.
```

2023-01-24 22:20 UTC, cadawson commented on observability/manage_search.adoc
> +For more specific search results, include the property selector in your search. You can combine related values for the property, for a more precise scope of your search. For example, search for `clus
```suggestion
For more specific search results, include the property selector in your search. You can combine related values for the property for a more precise scope of your search. For example, search for `cluster:dev red` to receive results that match the string "red" in the `dev` cluster. 
```

2023-01-24 22:20 UTC, cadawson commented on observability/manage_search.adoc
> +View the following steps to make queries with search:
```suggestion
Complete the following steps to make queries with search:
```

2023-01-24 22:20 UTC, cadawson commented on observability/manage_search.adoc
> +. Filter your query with the following values: `kind:application` and `apigroup:argoproj.io`
```suggestion
. Filter your query with the following values: `kind:application` and `apigroup:argoproj.io`.
```

2023-01-24 22:20 UTC, cadawson commented on observability/observability_enable.adoc
> +*Note:* When observability is enabled or disabled on {ocp-short} managed clusters that are managed by {product-title-short}, the observability endpoint operator updates the `cluster-monitoring-config
```suggestion
*Note:* When observability is enabled or disabled on {ocp-short} managed clusters that are managed by {product-title-short}, the observability endpoint operator updates the `cluster-monitoring-config` ConfigMap by adding additional alertmanager configuration that automatically restarts the local Prometheus instance.
```

2023-01-24 22:20 UTC, cadawson commented on observability/observability_enable.adoc
> +*Note:* The `QUERY_EXPRESSION` is the standard Prometheus query expression. For example, query the metrics `cluster_infrastructure_provider` by replacing the URL in the previously mentioned command,
```suggestion
*Note:* The `QUERY_EXPRESSION` is the standard Prometheus query expression. For example, query the metrics `cluster_infrastructure_provider` by replacing the URL in the previously mentioned command with the following URL: `https://{PROXY_ROUTE_URL}/api/v1/query?query=cluster_infrastructure_provider`. For more details, see https://prometheus.io/docs/prometheus/latest/querying/basics/[Querying Prometheus].
```

2023-01-24 22:20 UTC, cadawson commented on observability/observe_environments.adoc
> +*Note:* The time series historical data is stored in object stores. Thanos uses object storage as the primary storage for metrics and meta data related to them. For more details about the object stor
```suggestion
*Note:* The time series historical data is stored in object stores. Thanos uses object storage as the primary storage for metrics and metadata related to them. For more details about the object storage and downsampling, see xref:../observability/observe_environments.adoc#enabling-observability-service[Enabling observability service].
```

2023-01-24 22:20 UTC, cadawson commented on observability/search_intro.adoc
> +//check 'within' vs 'among'
Good question. 
My understanding: 
Version 1: The resources whose relationships are being computed by the search-collector are inside the managed cluster.
Version 2: The resources are spread across multiple managed clusters.
Depending on what it is saying, maybe "The `search-collector` also identifies relationships for the resources that are within the managed cluster and sends the results to the `search-indexer`. ?

2023-01-24 22:20 UTC, cadawson commented on observability/search_intro.adoc
> +Learn how to manage search, see xref:../observability/manage_search.adoc#managing-search[Managing search]. For more topics about the {product-title} console, see link:../console/console_intro.adoc#we
```suggestion
For instructions about how to manage search, see xref:../observability/manage_search.adoc#managing-search[Managing search]. For more topics about the {product-title} console, see link:../console/console_intro.adoc#web-console[Web console].
```

2023-01-24 22:35 UTC, cadawson commented on observability/manage_search.adoc
> +- <<querying-in-the-console,Querying in the console>>
Got it. Switching up the syntax threw me off. Thanks.

2023-01-24 22:42 UTC, cadawson commented on governance/ansible_grc.adoc
>  For more information about installing and configuring {aap}, see link:../applications/ansible_config.adoc#setting-up-ansible[Setting up Ansible tasks]
```suggestion
For more information about installing and configuring {aap}, see link:../applications/ansible_config.adoc#setting-up-ansible[Setting up Ansible tasks].
```

2023-01-25 03:43 UTC, dockerymick commented on observability/search_intro.adoc
> +//is there a specific name for the REST API?
Answered during the live meeting

2023-01-25 03:46 UTC, dockerymick commented on backup_restore/manage_backup_restore.adoc
> +*Note:* If you have previously installed and used the OADP Operator on the hub cluster, in a namespace different from the backup component namespace, uninstall this version since the backup component
Updated

2023-01-25 03:48 UTC, dockerymick commented on backup_restore/manage_backup_restore.adoc
> +*Note:* The _resources backup_ file contains managed cluster-specific resources, but does not contain the subset of resources that connect managed clusters to the hub cluster. The resources that conn
Updated

2023-01-25 03:49 UTC, dockerymick commented on clusters/about/rbac_mce.adoc
> +*Note:* As a `team-admin` and `team-user`, you have `admin` permission to the `clusterpool`, `clusterdeplyment`, and `clusterclaim`.
accepted suggestion

2023-01-25 03:51 UTC, dockerymick commented on console/console.adoc
> +_Search_ is also available from the _Home_ tab. To learn about Search, see link:../observability/search_intro.adocsearching-in-the-console-intro[Searching in the console introduction].
accepted suggestion

2023-01-25 03:52 UTC, dockerymick commented on governance/ansible_grc.adoc
> +*Note:* Ensure that the {aap-short} job template is idempotent when it is run. If you do not have {aap-short}  Resource Operator, you can find it from the {ocp} _OperatorHub_ page.
updated

2023-01-25 03:56 UTC, dockerymick commented on observability/observe_environments.adoc
> +*Note:* The time series historical data is stored in object stores. Thanos uses object storage as the primary storage for metrics and meta data related to them. For more details about the object stor
accepted suggestion

2023-01-25 03:56 UTC, dockerymick commented on observability/search_intro.adoc
> +The search operator watches the watches the `Search` custom resource, reconciles the changes to the custom resource, and updates active pods. View the following descriptions of the configurations:
updated during live review

2023-01-25 03:57 UTC, dockerymick commented on observability/search_intro.adoc
> +- PostGres database storage:
yup, good catch. updated during the live review

2023-01-25 04:00 UTC, dockerymick commented on observability/manage_search.adoc
> +//Anxhela checking if empty query is allowed
verified through slack that the info is correct

2023-01-25 04:01 UTC, dockerymick commented on governance/ansible_grc.adoc
>  For more information about installing and configuring {aap}, see link:../applications/ansible_config.adoc#setting-up-ansible[Setting up Ansible tasks]
accepted suggestion

2023-01-25 04:02 UTC, dockerymick commented on observability/customize_observability.adoc
> +Define custom rules with Prometheus to create alert conditions, and send notifications to an external messaging service. *Note:* When you update your custom rules, `observability-thanos-rule` pods ar
Updated alignment and moved note to a new line

2023-01-25 04:02 UTC, dockerymick commented on observability/customize_observability.adoc
> +*Note:* If this is the first new custom rule, it is created immediately. For changes to the ConfigMap, the configuration is automatically reloaded. The configuration is reloaded due to the `config-re
accepted suggestion

2023-01-25 04:02 UTC, dockerymick commented on observability/manage_insights.adoc
> +*Note:* After the issue is resolved, the Red Hat Insights are received by {product-title-short} every 30 minutes and Red Hat Insights is updated every two hours.
accepted suggestion

2023-01-25 04:03 UTC, dockerymick commented on observability/manage_search.adoc
> +Run the following command to view search customization CRD:
updated

2023-01-25 04:04 UTC, dockerymick commented on observability/manage_search.adoc
> +You can disable persistence by updating the `persistence` flag to `false` in the customization CR, which turns off saving search index to the file system. A status for persistence can be retrieved fr
updated

2023-01-25 04:05 UTC, dockerymick commented on observability/manage_search.adoc
> +RedisGraph is an in-memory database that needs linear growth of memory as the number of objects are cached. A {product-title-short} cluster with many managed clusters, or with a large number of Kuber
updated

2023-01-25 04:06 UTC, dockerymick commented on observability/manage_search.adoc
> +For more specific search results, include the property selector in your search. You can combine related values for the property, for a more precise scope of your search. For example, search for `clus
updated

2023-01-25 04:07 UTC, dockerymick commented on observability/manage_search.adoc
> +View the following steps to make queries with search:
updated

2023-01-25 04:07 UTC, dockerymick commented on observability/manage_search.adoc
> +** You can also search with conditions by using characters, such as `+>, >=, <, <=, !=+`.
Looks good from my perspective

2023-01-25 04:08 UTC, dockerymick commented on observability/manage_search.adoc
> +. Filter your query with the following values: `kind:application` and `apigroup:argoproj.io`
Updated

2023-01-25 04:09 UTC, dockerymick commented on observability/manage_search.adoc
> +To collect the Kubernetes objects from the managed clusters, the `search-collector` process is run on all the managed clusters where search is enabled. The deployment ran is the `klusterlet-addon-sea
updated

2023-01-25 04:18 UTC, dockerymick commented on observability/observability_enable.adoc
> +*Note:* When observability is enabled or disabled on {ocp-short} managed clusters that are managed by {product-title-short}, the observability endpoint operator updates the `cluster-monitoring-config
updated

2023-01-25 04:19 UTC, dockerymick commented on observability/observability_enable.adoc
> +*Note:* The `QUERY_EXPRESSION` is the standard Prometheus query expression. For example, query the metrics `cluster_infrastructure_provider` by replacing the URL in the previously mentioned command,
updated

2023-01-25 04:21 UTC, dockerymick commented on observability/search_intro.adoc
> +Search is enabled by default. Search is also enabled when you provision, or manually import a managed cluster. If you want to disable search on your managed cluster, see link:../clusters/modify_endpo
updated during live review

2023-01-25 04:21 UTC, dockerymick commented on observability/search_intro.adoc
> +Learn how to manage search, see xref:../observability/manage_search.adoc#managing-search[Managing search]. For more topics about the {product-title} console, see link:../console/console_intro.adoc#we
updated

2023-01-25 04:23 UTC, dockerymick commented on observability/search_intro.adoc
> +//check 'within' vs 'among'
@xrajesh @Anxhela21 based on our conversation during the call, i believe version 2 is the intention? Can either of you verify please? For now, I updated the statement to say **among**

2023-01-25 14:34 UTC, Anxhela21 commented on observability/search_intro.adoc
> +//check 'within' vs 'among'
I think it can be either but maybe this is more simple - the `search collector` collects resources across all managed clusters and computes relationships. These results are sent to the `search-indexer`.

2023-01-25 14:47 UTC, dockerymick commented on observability/search_intro.adoc
> +//check 'within' vs 'among'
Thanks @Anxhela21 !

CURRENT
`search-collector`: Watches the Kubernetes resources, collects the resource metadata, and sends the collected data to the `search-indexer`. The `search-collector` also computes relationships for resources among the managed cluster and sends it to the `search-indexer`.

PROPOSED
`search-collector`: Watches the Kubernetes resources, collects the resource metadata, computes relationships for resources across all of your managed clusters, and sends the collected data to the `search-indexer`.

QUESTION
What are yall thoughts about adding the statement in the comma list ^

2023-01-25 15:37 UTC, dockerymick commented on observability/manage_search.adoc
> +//Xavier please review
Hey Xavier, when you get a chance can you share feedback?

If all looks good with the entries in the `whats_new.adoc`, agree with updates in the `search_intro.adoc`, and updates in the `manage_search.adoc` file, will you approve the PR?

2023-01-25 15:48 UTC, SherinV commented on install/perform_scale.adoc
> +For more information on how you can change the amount of memory used for the search component, see link:../observability/manage_search.adoc#increasing-redisgraph-memory[Increasing the RedisGraph memo
We won't have Redisgraph in 2.7 - search backend switched to Postgres.

2023-01-25 15:48 UTC, SherinV commented on observability/manage_search.adoc
> +- <<increasing-redisgraph-memory,Increasing the RedisGraph memory>>
Increasing the RedisGraph memory - not applicable in 2.7. Switched to Postgres backend.

2023-01-25 15:51 UTC, SherinV commented on observability/manage_search.adoc
> +You can disable persistence by updating the `persistence` flag to `false` in the customization custom resource, which turns off saving search index to the file system. A status for persistence can be
```suggestion

```
This is not valid in 2.7

2023-01-25 16:03 UTC, dockerymick commented on observability/manage_search.adoc
> +- <<increasing-redisgraph-memory,Increasing the RedisGraph memory>>
Thanks @SherinV! Should the entire section be removed or should i change RedisGraph to PostgreSQL?

2023-01-25 16:28 UTC, Anxhela21 commented on observability/manage_search.adoc
> +- <<increasing-redisgraph-memory,Increasing the RedisGraph memory>>
Is the intent to remove all redisgraph references from search doc? Postgres is under what's changed section.

2023-01-25 16:54 UTC, SherinV commented on observability/manage_search.adoc
> +- <<increasing-redisgraph-memory,Increasing the RedisGraph memory>>
I believe Redisgraph sections should be removed as it is not part of 2.7. Deferring to what the team decided on how to organize the docs. @xrajesh @Anxhela21

2023-01-25 17:24 UTC, Anxhela21 commented on observability/manage_search.adoc
> +- <<increasing-redisgraph-memory,Increasing the RedisGraph memory>>
Okay, confirmed with team we want no mention of redisgraph for 2.7 search docs (Unless in the context of explaining redisgraph will be replaced with Postgres).

2023-01-25 17:59 UTC, cadawson approved these changes
Looks good! Thanks for making those changes.

2023-01-25 18:09 UTC, dockerymick commented on install/perform_scale.adoc
> +For more information on how you can change the amount of memory used for the search component, see link:../observability/manage_search.adoc#increasing-redisgraph-memory[Increasing the RedisGraph memo
updated

2023-01-25 18:12 UTC, dockerymick commented on observability/manage_search.adoc
> +- <<increasing-redisgraph-memory,Increasing the RedisGraph memory>>
Confirmed that it is already documented: https://github.com/stolostron/rhacm-docs/blob/2.7_stage/release_notes/deprecate_remove.adoc#removals

2023-01-25 18:25 UTC, dockerymick commented on release_notes/whats_new.adoc
> +* Optimize search by editing the PostgreSQL database storage and configuration. See, link:../observability/search_intro.adoc#search-customization[Search customization and configurations].
@Anxhela21 Can you confirm this entry ?

2023-01-25 20:45 UTC, Anxhela21 commented on release_notes/whats_new.adoc
> +* Optimize search by editing the PostgreSQL database storage and configuration. See, link:../observability/search_intro.adoc#search-customization[Search customization and configurations].
lgtm

2023-01-25 21:17 UTC, SherinV commented on release_notes/whats_new.adoc
> +* Optimize search by editing the PostgreSQL database storage and configuration. See, link:../observability/search_intro.adoc#search-customization[Search customization and configurations].
Can we remove all mentions of search-customization as that was for Redisgraph?

2023-01-25 21:18 UTC, SherinV commented on release_notes/whats_new.adoc
> +* Optimize search by editing the PostgreSQL database storage and configuration. See, link:../observability/search_intro.adoc#search-customization[Search customization and configurations].
search-customization CR in particular.

2023-01-25 21:51 UTC, SherinV commented on release_notes/whats_new.adoc
> +* Optimize search by editing the PostgreSQL database storage and configuration. See, link:../observability/search_intro.adoc#search-customization[Search customization and configurations].
I see that is not being used in the CR context, but more as customizing and configuring search.
/lgtm

2023-01-25 22:17 UTC, Anxhela21 commented on observability/search_intro.adoc
> +You can update the `Placement` of search pods by using the `nodeSelector` parameter, or the `tolerations` parameter. View the following example configuration:
If we want to also include the `nodeSelector` parameter to the example below we can add:

```
spec:
 dbStorage:
  size: 10Gi
 deployments:
  collector: {}
  database: {}
  indexer: {}
  queryapi: {}
 nodeSelector:
  node-role.kubernetes.io/infra: ""
 tolerations:
 - effect: NoSchedule
  key: node-role.kubernetes.io/infra
  operator: Exists

```

2023-01-25 22:32 UTC, Anxhela21 commented on install/perform_scale.adoc
> +For more information on how you can change the amount of memory used for the search component, see link:../observability/manage_search.adoc#increasing-redisgraph-memory[Increasing the RedisGraph memo
I still see the redisgraph reference here. also the corresponding data table for memory is for redisgraph, right? Do we want to remove this for 2.7 docs? @dockerymick @SherinV

2023-01-25 22:36 UTC, Anxhela21 commented on observability/manage_search.adoc
> +- <<increasing-redisgraph-memory,Increasing the RedisGraph memory>>
okay, we should remove this mention of redisgraph

2023-01-25 22:37 UTC, Anxhela21 commented on observability/manage_search.adoc
> +RedisGraph is an in-memory database that needs linear growth of memory as the number of objects are cached. A {product-title-short} cluster with many managed clusters, or with a large number of Kuber
Should remove mention of redisgraph

2023-01-26 14:21 UTC, Anxhela21 commented
Thank you for the updates @dockerymick!
/lgtm
/hold

2023-01-30 16:10 UTC, dockerymick commented on observability/search_intro.adoc
> +//check 'within' vs 'among'
@Anxhela21 thanks for confirming

2023-01-30 16:50 UTC, dockerymick commented on backup_restore/manage_backup_restore.adoc
> +*Note:* The _resources backup_ file contains managed cluster-specific resources, but does not contain the subset of resources that connect managed clusters to the hub cluster. The resources that conn
updated

2023-01-30 16:50 UTC, dockerymick commented on observability/customize_observability.adoc
> +Define custom rules with Prometheus to create alert conditions, and send notifications to an external messaging service. *Note:* When you update your custom rules, `observability-thanos-rule` pods ar
updated

2023-01-30 16:51 UTC, dockerymick commented on observability/observability_enable.adoc
> +*Note:* When observability is enabled or disabled on {ocp-short} managed clusters that are managed by {product-title-short}, the observability endpoint operator updates the `cluster-monitoring-config
updated

2023-01-30 16:51 UTC, dockerymick commented on observability/observability_enable.adoc
> +*Note:* The `QUERY_EXPRESSION` is the standard Prometheus query expression. For example, query the metrics `cluster_infrastructure_provider` by replacing the URL in the previously mentioned command,
updated

2023-01-30 16:51 UTC, dockerymick commented on observability/search_intro.adoc
> +Learn how to manage search, see xref:../observability/manage_search.adoc#managing-search[Managing search]. For more topics about the {product-title} console, see link:../console/console_intro.adoc#we
updated

2023-01-30 16:54 UTC, dockerymick commented on observability/search_intro.adoc
> +You can update the `Placement` of search pods by using the `nodeSelector` parameter, or the `tolerations` parameter. View the following example configuration:
updated

2023-01-31 02:14 UTC, xrajesh commented on observability/manage_search.adoc
> +Run the following command to view search customization custom resource definition:
We Dont need lines 64 to 76 @dockerymick

2023-01-31 02:19 UTC, xrajesh commented on observability/search_intro.adoc
> +For {product-title}, search provides visibility into your Kubernetes resources across all of your clusters. Search indexes the Kubernetes resources and the relationships to other resources. You can u
` You can use the `searchcustomization` custom resource (CR) to define the storage settings for search persistence if you want to change the storage class and storage size. ` Can be deleted. Not valid anymore @dockerymick

2023-01-31 02:24 UTC, xrajesh commented on observability/search_intro.adoc
> +- `search-collector`: Watches the Kubernetes resources, collects the resource metadata, computes relationships for resources across all of your managed clusters, and sends the collected data to the `
@dockerymick  Please append this line - The search-collector process running on the managed clusters run as Pod named `klusterlet-addon-search`

2023-01-31 02:33 UTC, xrajesh commented on observability/search_intro.adoc
> +Search is configured by default on the hub cluster. When you provision or manually import a managed cluster, the `klusterlet-addon-search` is enabled. If you want to disable search on your managed cl
@dockerymick Check the link, it has a wrong version for on the klusterletaddonconfig sample.

2023-01-31 02:48 UTC, xrajesh commented on observability/search_intro.adoc
> +When you install {product-title-short}, the PostgreSQL database is configured to persist the search data in an empty directory (`emptyDir`) volume. You can back up the PostgreSQL data on a Persistent
@dockerymick  . update :  When you install {product-title-short}, the PostgreSQL database is configured to save the PostgreSQL data in an empty directory (`emptyDir`) volume. If the empty directory size is limited, PostgreSQL data can be saved on  Persistent Volume Claim (PVC)

2023-01-31 02:50 UTC, xrajesh commented on observability/search_intro.adoc
> +- Optimize PostgreSQL database configuration by using the previous ConfigMap. For example, add `tuning-config` as the parameter value:
@dockerymick The bullet here is not needed

2023-01-31 18:17 UTC, dockerymick commented on observability/manage_search.adoc
> +Run the following command to view search customization custom resource definition:
updated

2023-01-31 18:22 UTC, dockerymick commented on observability/search_intro.adoc
> +Search is configured by default on the hub cluster. When you provision or manually import a managed cluster, the `klusterlet-addon-search` is enabled. If you want to disable search on your managed cl
Great catch

2023-01-31 18:27 UTC, dockerymick commented on observability/search_intro.adoc
> +For {product-title}, search provides visibility into your Kubernetes resources across all of your clusters. Search indexes the Kubernetes resources and the relationships to other resources. You can u
updated

2023-01-31 18:28 UTC, dockerymick commented on observability/search_intro.adoc
> +Search is configured by default on the hub cluster. When you provision or manually import a managed cluster, the `klusterlet-addon-search` is enabled. If you want to disable search on your managed cl
Updated

2023-01-31 18:28 UTC, dockerymick commented on observability/search_intro.adoc
> +When you install {product-title-short}, the PostgreSQL database is configured to persist the search data in an empty directory (`emptyDir`) volume. You can back up the PostgreSQL data on a Persistent
Updated

2023-01-31 18:28 UTC, dockerymick commented on observability/search_intro.adoc
> +- Optimize PostgreSQL database configuration by using the previous ConfigMap. For example, add `tuning-config` as the parameter value:
Updated

2023-01-31 18:29 UTC, dockerymick commented
@xrajesh thank you for your review and feedback. When you have an opportunity, will you re-review and provide approval?

2023-01-31 19:15 UTC, xrajesh commented on release_notes/whats_new.adoc
> +* A new custom resource definition is added to the search feature, named `searches.search.open-cluster-management.io`. To further customize search, see link:../observability/search_intro.adoc#search-
@dockerymick Where do we say the previous `searchoperator` and `searchcustomization` will not be valid anymore  ?

2023-01-31 19:56 UTC, xrajesh commented on observability/manage_search.adoc
> +To collect the Kubernetes objects from the managed clusters, the `search-collector` process is run on all the managed clusters where search is enabled. The active deployment that is run is the `klust
@dockerymick This part is confusing , Need to clarify which resource is on HUB Vs managed . 
1. To collect the Kubernetes objects from the managed clusters, the `klusterlet-addon-search` pod is run on all the managed clusters where search is enabled. This deployment is run in the `open-cluster-management-agent-addon` namespace. A managed cluster with a high number of kubernetes resources might require more memory requirements for the `klusterlet-addon-search` deployment to function. 

Resource requirements for the `klusterlet-addon-search`  pod in a managed cluster can be specified in the `ManagedclusterAddon` custom resource present in ACM Hub. The ACM Hub has a namespace for each managed cluster, with the managed cluster's name. Edit the `ManagedclusterAddon` custom resource present in a namespace matching the managed cluster , with the following command:

2023-02-01 03:04 UTC, dockerymick commented on observability/observe_environments.adoc
> +*Note:* The _on-demand log_ provides access for engineers to get logs for a given pod in real-time. Logs from the hub cluster are not aggregated. These logs can be accessed with the search service an
Updating the support statement from [issue #26952](https://github.com/stolostron/backlog/issues/26952). 

If you can, I will appreciate a review from @berenss and @swopebe (doc architect purposes)

2023-02-01 18:47 UTC, dockerymick commented on release_notes/whats_new.adoc
> +* A new custom resource definition is added to the search feature, named `searches.search.open-cluster-management.io`. To further customize search, see link:../observability/search_intro.adoc#search-
Clarified during live review

2023-02-02 21:31 UTC, swopebe approved these changes
@dockerymick this looks amazing. The only thing I am unsure of is if the quick start guide is being built or still relevant.

2023-02-06 14:50 UTC, xrajesh approved these changes

2023-02-06 14:57 UTC, dockerymick commented
@xrajesh thanks for your approval! Thanks to everyone involved! Merging this PR

2023-02-06 14:57 UTC, merged