stolostron/backlog#27129
open-cluster-management/rhacm-docs pull request #4601
Opened 2023-01-23 19:51 UTC by oafischer

stolostron/backlog#27129

2023-01-23 22:04 UTC, birsanv requested changes

2023-01-23 22:04 UTC, birsanv commented on release_notes/known_issues.adoc
> +=== The _appliedmanifestwork_ is not removed after restoring the hub cluster
I think this should say : The _appliedmanifestwork_ is not removed **from the managed cluster** after restoring the hub cluster
( the reason : the issue happens on the managed cluster, not on the new, restored, hub cluster

2023-01-23 22:04 UTC, birsanv commented on release_notes/known_issues.adoc
> +If the placement rule for an application subscription is not a fixed cluster set, the `appliedmanifestwork` from the old hub cluster remains on the new hub cluster after restoring.
same comment here as above , should be 

If the placement rule for an application subscription is not a fixed cluster set, when the hub data is restored on the new hub, the `appliedmanifestwork` is not removed **from the managed clusters** matching this placement rule.

2023-01-24 15:48 UTC, oafischer commented
Thanks, implemented your suggestions @birsanv!

2023-01-24 15:50 UTC, birsanv approved these changes
lgtm

2023-01-24 15:56 UTC, swopebe commented on release_notes/known_issues.adoc
> +[#appliedmanifestwork-not-removed-after-restoring]
I would shorten this anchor to something easy to link to if needed--making these as simple as possible:

#manifestwork-not-removed (or something--as with file names, we want to keep concise and simple when and where we can)

2023-01-24 15:58 UTC, swopebe commented on release_notes/known_issues.adoc
> +
I read this and thought: huh 

Slightly hard to follow, run on sentence. I would offer an edit but in this case, I am not sure how to fix it bc I don't understand it.

2023-01-24 15:59 UTC, swopebe commented on release_notes/known_issues.adoc
> +This results in the application being orphaned when the managed cluster is detached from the restored hub cluster.
As a result, the application is orphaned...

2023-01-24 15:59 UTC, swopebe commented on release_notes/known_issues.adoc
> +
the rest looks good.

2023-01-24 16:00 UTC, swopebe requested changes
I got lost a bit on the issue explanation

2023-01-24 16:00 UTC, oafischer commented on release_notes/known_issues.adoc
> +
Yeah was thinking about that too and hoping a peer review might give me some idea, but I think I just came up with something that might help. Just updated it.

2023-01-24 16:04 UTC, oafischer commented
Moved it around a bit @swopebe, is it better now? Open to suggestions, not an easy one to fix.

2023-01-24 16:09 UTC, birsanv commented on release_notes/known_issues.adoc
> +When the hub cluster data is restored on the new hub cluster, the `appliedmanifestwork` is not removed from managed clusters that have a placement rule for an application subscription that is not a f
I agree with @swopebe that the initial sentence was hard to read. I was about to give a suggestion that looks just like yours Oliver : start with `When the hub cluster data is restored on the new hub cluster` .. looks good to me as it is now

2023-01-25 15:17 UTC, merged