Known issue stolostron/backlog#27156
open-cluster-management/rhacm-docs pull request #4671
Opened 2023-02-02 16:15 UTC by oafischer

stolostron/backlog#27156

2023-02-02 17:16 UTC, dhaiducek requested changes

2023-02-02 17:16 UTC, dhaiducek commented on release_notes/known_issues.adoc
> +The resolve th issue, disable the policy and compare the differences between `objectDefinition` in the policy and the object on the managed cluster. If the values are different, another controller or
```suggestion
To resolve the issue, disable the policy and compare the differences between `objectDefinition` in the policy and the object on the managed cluster. If the values are different, another controller or process might be updating them.
```

2023-02-02 17:16 UTC, dhaiducek commented on release_notes/known_issues.adoc
> +For PodSecurityPolicy, for example, Kubernetes removes keys with values set to `false`, which you can see in the resulting object on the managed cluster. Removing the keys from the `objectDefinition`
```suggestion
If the keys are different or missing, Kubernetes might have processed the keys before applying them to the object. For PodSecurityPolicy, for example, Kubernetes removes keys with values set to `false`, which you can see in the resulting object on the managed cluster. Removing the keys from the `objectDefinition` in the policy resolves the issue.
```

2023-02-02 17:16 UTC, dhaiducek commented on release_notes/known_issues.adoc
> +You can also look for process leftovers in the object, such as `metadata`. If the keys are different or missing, Kubernetes might have processed the keys before applying them to the object.
These are two separate points:
- The `metadata` reference refers to clues left by another controller or process. These controllers sometimes leave labels or annotations to signal that they've updated the object.
- The keys being different or missing goes with the PodSecurityPolicy point in the next paragraph.

2023-02-02 17:50 UTC, oafischer commented on release_notes/known_issues.adoc
> +You can also look for process leftovers in the object, such as `metadata`. If the keys are different or missing, Kubernetes might have processed the keys before applying them to the object.
Thanks for clarifying, might be clearer then to structure the scenario and resolution together. Let me update it.

2023-02-02 19:19 UTC, dockerymick requested changes

2023-02-02 19:19 UTC, dockerymick commented on release_notes/known_issues.adoc
> +- The `objectDefinition` in the `ConfigurationPolicy` does not match because Kubernetes is processing the object on apply.
"on apply" sounds interesting to me 

What about "processing the object when the policy is applied."

2023-02-02 19:19 UTC, dockerymick commented on release_notes/known_issues.adoc
> +If the keys are different or missing, Kubernetes might have processed the keys before applying them to the object. For PodSecurityPolicy, for example, Kubernetes removes keys with values set to `fals
monospace PodSecurityPolicy

2023-02-02 20:18 UTC, oafischer commented
Thanks for the comments @dhaiducek and @dockerymick, made some updates to hopefully make it clearer.

2023-02-02 20:36 UTC, dhaiducek requested changes
Thanks, @oafischer! It's looking good--I have a few more refinements to consider.

2023-02-02 20:36 UTC, dhaiducek commented on release_notes/known_issues.adoc
> +To resolve the issue, disable the policy and compare the differences between `objectDefinition` in the policy and the object on the managed cluster. If the values are different, another controller or
Adding something like might help users troubleshoot:

```suggestion
To resolve the issue, disable the policy and compare the differences between `objectDefinition` in the policy and the object on the managed cluster. If the values are different, another controller or process might be updating them. If this is the case, the controller or process may have left clues in the `metadata` of the object, such as a label or annotation, that can help identify what is making the changes.
```

2023-02-02 20:36 UTC, dhaiducek commented on release_notes/known_issues.adoc
> +To resolve the issue, remove the keys from the `objectDefinition` in the policy. If the keys are different or missing, Kubernetes might have processed the keys before applying them to the object. For
Removing keys might not be the only solution, so the first part should be more generic.

```suggestion
To resolve the issue, disable the policy and compare the differences between `objectDefinition` in the policy and the object on the managed cluster. If the keys are different or missing, Kubernetes might have processed the keys before applying them to the object. For `PodSecurityPolicy`, for example, Kubernetes removes keys with values set to `false`, which you can see in the resulting object on the managed cluster. In this case, remove these keys from the `objectDefinition` in the policy.
```

2023-02-02 20:44 UTC, oafischer commented on release_notes/known_issues.adoc
> +To resolve the issue, disable the policy and compare the differences between `objectDefinition` in the policy and the object on the managed cluster. If the values are different, another controller or
Not a huge fan of mentioning clues since it's a little vague. We mention two examples (label/annotation). Can we list more specific things like that to look out for?

2023-02-02 20:50 UTC, dhaiducek commented on release_notes/known_issues.adoc
> +To resolve the issue, disable the policy and compare the differences between `objectDefinition` in the policy and the object on the managed cluster. If the values are different, another controller or
That's fair. Unfortunately what a controller leaves on an object isn't consistent nor guaranteed. So we can leave it off if that's best practice for documentation.

2023-02-02 20:52 UTC, oafischer commented on release_notes/known_issues.adoc
> +To resolve the issue, disable the policy and compare the differences between `objectDefinition` in the policy and the object on the managed cluster. If the values are different, another controller or
@dockerymick What are your thoughts on this?

2023-02-03 14:53 UTC, dockerymick commented on release_notes/known_issues.adoc
> +To resolve the issue, disable the policy and compare the differences between `objectDefinition` in the policy and the object on the managed cluster. If the values are different, another controller or
I recommend stating: 

Check the `metadata` of the object to help identify why the values are different.

2023-02-03 19:19 UTC, merged

2023-02-03 20:10 UTC, dhaiducek commented
Thanks, @oafischer!