Improving policy generator doc and tips to manage ArgoCD
open-cluster-management/rhacm-docs pull request #4673
Opened 2023-02-02 19:03 UTC by dockerymick

https://github.com/stolostron/backlog/issues/26910
https://github.com/stolostron/backlog/issues/27146

2023-02-02 19:04 UTC, dockerymick commented on governance/policy_gen_install_operator.adoc
> +- <<manage-policy-definitions,Managing policy definitions with OpenShift GitOps (Argo CD)>>
@mprahl new section added here, changes are also related to improving the flow of the Policy generator doc

2023-02-02 19:07 UTC, oafischer commented on governance/policy_gen_install_operator.adoc
> +A common use of {product-title-short} policies is to install an Operator on one or more managed OpenShift clusters. Continue reading to learn how to install Operators with OpenShift GitOps installati
```suggestion
A common use of {product-title-short} policies is to install an Operator on one or more managed {ocp} clusters. Continue reading to learn how to install Operators with OpenShift GitOps installation modes:
```

2023-02-02 19:08 UTC, oafischer commented on governance/policy_gen_install_operator.adoc
> +Apply a policy that installs OpenShift GitOps using the policy generator. The OpenShift GitOps operator offers the _all namespaces_ installation mode. Create a `Subscription` manifest file called `op
```suggestion
Apply a policy that installs OpenShift GitOps bz using the policy generator. The OpenShift GitOps operator offers the _all namespaces_ installation mode. Create a `Subscription` manifest file called `openshift-gitops-subscription.yaml`, similar to the following example:
```

2023-02-02 19:12 UTC, oafischer commented on governance/policy_gen_install_operator.adoc
> +A policy generator configuration file called `policy-generator-config.yaml` is required. Use the following policy to install OpenShift GitOps on all OpenShift managed clusters:
```suggestion
A policy generator configuration file called `policy-generator-config.yaml` is required. Use the following policy to install OpenShift GitOps on all {ocp-short} managed clusters:
```

2023-02-02 19:13 UTC, oafischer commented on governance/policy_gen_install_operator.adoc
> +The last file that is required is the `kustomization.yaml` file. The `kustomization.yaml` file requires the following configuration:
Can probably shorten this to "The last required filed is..., which requires the following configuration:" or similar

2023-02-02 19:14 UTC, oafischer commented on governance/policy_gen_install_operator.adoc
> +== Installing the Compliance Operator using a policy
```suggestion
== Installing the Compliance Operator by using a policy
```

2023-02-02 19:16 UTC, oafischer commented on governance/policy_gen_install_operator.adoc
> +The last file that is required is the `kustomization.yaml` file. The following configuration is required in the `kustomization.yaml` file:
Can probably shorten this to "The last required filed is..., which requires the following configuration:" or similar

2023-02-02 19:17 UTC, oafischer commented on governance/policy_gen_install_operator.adoc
> +OpenShift GitOps, based on link:https://argoproj.github.io/argo-cd/[ArgoCD], can also be used to generate policies using the policy generator through GitOps. Since the policy generator does not come
```suggestion
OpenShift GitOps, based on link:https://argoproj.github.io/argo-cd/[ArgoCD], can also be used to generate policies by using the policy generator through GitOps. Since the policy generator does not come preinstalled in the OpenShift GitOps container image, some customization must take place. In order to follow along, you must have the OpenShift GitOps Operator installed on the {product-title-short} hub cluster and be sure to log into the hub cluster.
```

2023-02-02 19:23 UTC, oafischer commented on governance/policy_gen_install_operator.adoc
> +When a {product-title-short} policy definition is deployed with OpenShift GitOps, a copy of the policy is created in each managed cluster namespace. These copies are called replicated policies. For O
For the second sentence I recommend something like:

To prevent OpenShift GitOps from consistently/repeatedly deleting this replicated policy or showing the ArgoCD as out of sync...

2023-02-02 19:24 UTC, oafischer commented on governance/policy_generator.adoc
> +The policy generator and its integration with the {product-title-short} application lifecycle subscription GitOps workflow simplifies the distribution of Kubernetes resource objects to managed OpenSh
```suggestion
The policy generator and its integration with the {product-title-short} application lifecycle subscription GitOps workflow simplifies the distribution of Kubernetes resource objects to managed {ocp-short} clusters, and Kubernetes clusters through {product-title-short} policies. In particular, use the policy generator to complete the following actions:
```

2023-02-02 19:25 UTC, oafischer commented on governance/policy_generator.adoc
> +To use the plug-in, start by adding a `generators` section in a `kustomization.yaml` file. View the following example:
`plug-in` now gives me PTSD lol

2023-02-03 14:16 UTC, mprahl commented on governance/policy_gen_install_operator.adoc
> +=== Managing policy definitions with OpenShift GitOps (Argo CD)
This needs to be separate from the Policy Generator documentation. Some users will deploy ACM policies without  the Policy Generator and still use OpenShift GitOps/ArgoCD and we need to document that.

2023-02-03 14:18 UTC, mprahl commented on governance/policy_gen_install_operator.adoc
> +A common use of {product-title-short} policies is to install an Operator on one or more managed OpenShift clusters. Continue reading to learn how to install Operators with OpenShift GitOps installati
I don't think "install Operators with OpenShift GitOps installation modes" is quite right.

The documentation below is showing how to generate policies using the Policy Generator and the example does show how to install the OpenShift GitOps operator, but it's not being deployed by OpenShift GitOps.

2023-02-03 14:22 UTC, mprahl commented on governance/policy_gen_install_operator.adoc
> +== Installing OpenShift GitOps using a policy
The documentation is about generating a policy that installs OpenShift GitOps and not about installing OpenShift GitOps.

2023-02-03 14:25 UTC, mprahl commented on governance/policy_gen_install_operator.adoc
> +Apply a policy that installs OpenShift GitOps using the policy generator. The OpenShift GitOps operator offers the _all namespaces_ installation mode. Create a `Subscription` manifest file called `op
```suggestion
The example below uses the Policy Generator to generate a policy that installs OpenShift GitOps. The OpenShift GitOps operator offers the _all namespaces_ installation mode, which the example below uses. Create a `Subscription` manifest file called `openshift-gitops-subscription.yaml`, similar to the following example:
```

2023-02-03 14:26 UTC, mprahl commented on governance/policy_gen_install_operator.adoc
> +A policy generator configuration file called `policy-generator-config.yaml` is required. Use the following policy to install OpenShift GitOps on all OpenShift managed clusters:
I think the Policy Generator should be capitalized as such since we refer to it as "the Policy Generator" and not "a policy generator".

2023-02-03 14:26 UTC, mprahl commented on governance/policy_gen_install_operator.adoc
> +A policy generator configuration file called `policy-generator-config.yaml` is required. Use the following policy to install OpenShift GitOps on all OpenShift managed clusters:
The explicit file name is not required, but the contents of the file or similar are required.

2023-02-03 14:28 UTC, mprahl commented on governance/policy_gen_install_operator.adoc
> +{ocp-short} supports all generated policies.
I'm not quite following what this support statement means. Could you please elaborate?

2023-02-03 14:29 UTC, mprahl commented on governance/policy_gen_install_operator.adoc
> +== Installing the Compliance Operator using a policy
Same as above. This isn't about installing the Compliance operator, it's about using the Policy Generator to generate a policy that installs the Compliance operator.

2023-02-03 14:30 UTC, mprahl commented on governance/policy_gen_install_operator.adoc
> +A policy generator configuration file called `policy-generator-config.yaml` is also required. View the following `PolicyGenerator` policy example that installs the Compliance Operator on all OpenShif
Again, the name isn't required, but the contents are required. I would reword that to not emphasize that the name is required.

2023-02-03 14:32 UTC, mprahl commented on governance/policy_gen_install_operator.adoc
> +In order for OpenShift GitOps to have access to the policy generator when you run Kustomize, an Init Container is required to copy the policy generator binary from the {product-title-short} Applicati
```suggestion
In order for OpenShift GitOps to have access to the policy generator when you run Kustomize, an Init Container is required to copy the policy generator binary from the {product-title-short} Application Subscription container image to the OpenShift GitOps container. Additionally, OpenShift GitOps must be configured to provide the `--enable-alpha-plugins` flag when it runs Kustomize. Start editing the OpenShift GitOps `argocd` object with the following command:
```

2023-02-03 14:35 UTC, mprahl commented on governance/policy_gen_install_operator.adoc
> +Now that OpenShift GitOps can use the policy generator, OpenShift GitOps must be granted access to create policies on the {product-title-short} hub cluster. Create the following `ClusterRole` resourc
This text and below in the section is generic to deploying ACM policies using OpenShift GitOps and isn't particular to the Policy Generator. I would suggest not duplicating the content but rather point to the section that is about being able to deploy policies using OpenShift GitOps.

2023-02-03 14:35 UTC, mprahl commented on governance/policy_gen_install_operator.adoc
> +=== Managing policy definitions with OpenShift GitOps (Argo CD)
```suggestion
=== Managing policy definitions with OpenShift GitOps (ArgoCD)
```

2023-02-03 14:37 UTC, mprahl commented on governance/policy_generator.adoc
> -See the link:https://github.com/stolostron/policy-generator-plugin[`policy-generator-plugin`] repository for more details.
How is the user directed to the examples that were moved to a new page?

2023-02-03 15:36 UTC, dockerymick commented on governance/policy_gen_install_operator.adoc
> +A common use of {product-title-short} policies is to install an Operator on one or more managed OpenShift clusters. Continue reading to learn how to install Operators with OpenShift GitOps installati
Updating to read as the following: "A common use of {product-title-short} policies is to install an Operator on one or more {ocp} managed clusters.

2023-02-03 17:09 UTC, dockerymick commented on governance/policy_gen_install_operator.adoc
> +The last file that is required is the `kustomization.yaml` file. The `kustomization.yaml` file requires the following configuration:
Updated

2023-02-03 17:10 UTC, dockerymick commented on governance/policy_gen_install_operator.adoc
> +== Installing the Compliance Operator using a policy
Updated in the file

2023-02-03 17:11 UTC, dockerymick commented on governance/policy_gen_install_operator.adoc
> +The last file that is required is the `kustomization.yaml` file. The following configuration is required in the `kustomization.yaml` file:
Updated

2023-02-03 17:12 UTC, dockerymick commented on governance/policy_gen_install_operator.adoc
> +OpenShift GitOps, based on link:https://argoproj.github.io/argo-cd/[ArgoCD], can also be used to generate policies using the policy generator through GitOps. Since the policy generator does not come
Updated

2023-02-03 17:24 UTC, dockerymick commented on governance/policy_gen_install_operator.adoc
> +When a {product-title-short} policy definition is deployed with OpenShift GitOps, a copy of the policy is created in each managed cluster namespace. These copies are called replicated policies. For O
updated

2023-02-03 18:09 UTC, dockerymick commented on governance/policy_generator.adoc
> +The policy generator and its integration with the {product-title-short} application lifecycle subscription GitOps workflow simplifies the distribution of Kubernetes resource objects to managed OpenSh
Updated

2023-02-03 18:18 UTC, dockerymick commented on governance/policy_generator.adoc
> +To use the plug-in, start by adding a `generators` section in a `kustomization.yaml` file. View the following example:
oh man lmao

2023-02-03 18:20 UTC, dockerymick commented on governance/policy_gen_install_operator.adoc
> +A common use of {product-title-short} policies is to install an Operator on one or more managed OpenShift clusters. Continue reading to learn how to install Operators with OpenShift GitOps installati
Updated

2023-02-03 18:21 UTC, dockerymick commented on governance/policy_gen_install_operator.adoc
> +== Installing OpenShift GitOps using a policy
Updated

2023-02-03 18:22 UTC, dockerymick commented on governance/policy_gen_install_operator.adoc
> +Apply a policy that installs OpenShift GitOps using the policy generator. The OpenShift GitOps operator offers the _all namespaces_ installation mode. Create a `Subscription` manifest file called `op
Updated

2023-02-03 18:36 UTC, dockerymick commented on governance/policy_gen_install_operator.adoc
> +A policy generator configuration file called `policy-generator-config.yaml` is required. Use the following policy to install OpenShift GitOps on all OpenShift managed clusters:
@mprahl thanks, Your suggestion seems valid from my viewpoint. I took a look at the [IBM Style Guide](https://www.ibm.com/docs/en/ibm-style?topic=grammar-capitalization#headings-titles-and-banners) for more clarity, but i'm still not sure. Pulling in @oafischer @swopebe for their opinion

2023-02-03 18:39 UTC, dockerymick commented on governance/policy_gen_install_operator.adoc
> +A policy generator configuration file called `policy-generator-config.yaml` is required. Use the following policy to install OpenShift GitOps on all OpenShift managed clusters:
Updated

2023-02-03 18:40 UTC, swopebe commented on governance/policy_gen_install_operator.adoc
> +A policy generator configuration file called `policy-generator-config.yaml` is required. Use the following policy to install OpenShift GitOps on all OpenShift managed clusters:
If we are referring to it as a proper noun: Title case
If general, not title case

Like applications and Applications...if it can be both, we just need to pick and be consistent. Is this a concept that can be general or an actual title? If policy generator is the name of something exclusively titled as such, the capitalize.

2023-02-03 18:44 UTC, oafischer commented on governance/policy_gen_install_operator.adoc
> +A policy generator configuration file called `policy-generator-config.yaml` is required. Use the following policy to install OpenShift GitOps on all OpenShift managed clusters:
I agree consistency is important, you can also check if we already do it a certain way in the docs and just follow that.

2023-02-03 18:46 UTC, dockerymick commented on governance/policy_gen_install_operator.adoc
> +A policy generator configuration file called `policy-generator-config.yaml` is also required. View the following `PolicyGenerator` policy example that installs the Compliance Operator on all OpenShif
Updated

2023-02-03 18:46 UTC, dockerymick commented on governance/policy_gen_install_operator.adoc
> +In order for OpenShift GitOps to have access to the policy generator when you run Kustomize, an Init Container is required to copy the policy generator binary from the {product-title-short} Applicati
updated

2023-02-03 18:48 UTC, dockerymick commented on governance/policy_gen_install_operator.adoc
> +A policy generator configuration file called `policy-generator-config.yaml` is required. Use the following policy to install OpenShift GitOps on all OpenShift managed clusters:
In the previous release i used lower case

2023-02-03 18:56 UTC, dockerymick commented on governance/policy_generator.adoc
> -See the link:https://github.com/stolostron/policy-generator-plugin[`policy-generator-plugin`] repository for more details.
This part is at the end of the `policy_gen_install_operator.adoc` file

2023-02-03 19:01 UTC, mprahl commented on governance/policy_gen_install_operator.adoc
> +A policy generator configuration file called `policy-generator-config.yaml` is required. Use the following policy to install OpenShift GitOps on all OpenShift managed clusters:
We can stick with lowercase, but title case would be better since it's a proper noun.

2023-02-03 19:03 UTC, mprahl commented on governance/policy_gen_install_operator.adoc
> +A common use of {product-title-short} policies is to install an Operator on one or more managed {ocp} clusters. Continue reading to learn how to generate policies using the policy generator, and to i
```suggestion
A common use of {product-title-short} policies is to install an Operator on one or more managed {ocp} clusters. Continue reading to learn how to generate policies using the policy generator, and to install the OpenShift GitOps Operator with a generated policy:
```

2023-02-03 19:04 UTC, mprahl commented on governance/policy_gen_install_operator.adoc
> +- <<manage-policy-definitions,Managing policy definitions with OpenShift GitOps (Argo CD)>>
```suggestion
- <<manage-policy-definitions,Managing policy definitions with OpenShift GitOps (ArgoCD)>>
```

2023-02-03 19:36 UTC, dockerymick commented on governance/policy_gen_install_operator.adoc
> +A policy generator configuration file called `policy-generator-config.yaml` is required. Use the following policy to install OpenShift GitOps on all OpenShift managed clusters:
Sounds good, I updated it

2023-02-03 19:47 UTC, dockerymick commented on governance/policy_gen_install_operator.adoc
> +Now that OpenShift GitOps can use the policy generator, OpenShift GitOps must be granted access to create policies on the {product-title-short} hub cluster. Create the following `ClusterRole` resourc
it seems like i should remove the following statement:

Create the following `ClusterRole` resource called `openshift-gitops-policy-admin`, with access to create, read, update, and delete policies and placements. Your `ClusterRole` might resemble the following example: <plus the YAML contents>

Since i moved related resources to the end of the file, I recommend that we add a reference link to the topic: Deploying policies using GitOps

2023-02-03 19:50 UTC, dockerymick commented on governance/policy_gen_install_operator.adoc
> +{ocp-short} supports all generated policies.
I was working on making the previous statement concise. Here is the doc from 2.6:
![Screen Shot 2023-02-03 at 2 49 39 PM](https://user-images.githubusercontent.com/60616885/216694768-1d422b19-0e24-4e56-aa41-138b943cdbd1.png)

2023-02-06 01:31 UTC, dockerymick commented on governance/policy_gen_install_operator.adoc
> +{ocp-short} supports all generated policies.
@mprahl We can also remove the statement

2023-02-06 01:31 UTC, dockerymick commented on governance/policy_gen_install_operator.adoc
> +Now that OpenShift GitOps can use the policy generator, OpenShift GitOps must be granted access to create policies on the {product-title-short} hub cluster. Create the following `ClusterRole` resourc
Updated

2023-02-06 13:30 UTC, mprahl commented on governance/policy_gen_install_operator.adoc
> +{ocp-short} supports all generated policies.
@dockerymick the statement is to indicate that generated policies from manifests in the OpenShift documentation is supported. The key is that any configuration advice in the OpenShift documentation can be applied using a policy generated using the Policy Generator.

2023-02-06 13:56 UTC, dockerymick commented
@mprahl thanks for clarifying!

2023-02-06 15:26 UTC, mprahl commented on governance/policy_gen_install_operator.adoc
> +== Generating a policy that installs the Policy Generator on OpenShift GitOps (ArgoCD)
```suggestion
== Integrating the Policy Generator with OpenShift GitOps (ArgoCD)
```

2023-02-06 15:27 UTC, mprahl commented on governance/manage_policy_def.adoc
> +== Related resources
I think the only related resource should be the section `#policy-gen-install-on-openshift-gitops` since that's about integrating the Policy Generator in OpenShift GitOps. Every other aspect of the Policy Generator is not related to OpenShift GitOps.

2023-02-06 15:27 UTC, mprahl commented on governance/policy_gen_install_operator.adoc
> +== Generating a policy that installs the OpenShift GitOps
```suggestion
== Generating a policy that installs OpenShift GitOps
```

2023-02-06 15:28 UTC, mprahl commented on governance/policy_gen_install_operator.adoc
> +Generate a policy that installs OpenShift GitOps by using the policy generator. The OpenShift GitOps operator offers the _all namespaces_ installation mode. Create a `Subscription` manifest file call
I don't think it should be a command but rather a suggestion that it's possible.
```suggestion
You may generate a policy that installs OpenShift GitOps by using the policy generator. The OpenShift GitOps operator offers the _all namespaces_ installation mode. Create a `Subscription` manifest file called `openshift-gitops-subscription.yaml`, similar to the following example:
```

2023-02-06 15:29 UTC, mprahl commented on governance/policy_gen_install_operator.adoc
> +Generate a policy that installs OpenShift GitOps by using the policy generator. The OpenShift GitOps operator offers the _all namespaces_ installation mode. Create a `Subscription` manifest file call
```suggestion
Generate a policy that installs OpenShift GitOps by using the policy generator. The OpenShift GitOps operator offers the _all namespaces_ installation mode, which will be used in the example. Create a `Subscription` manifest file called `openshift-gitops-subscription.yaml`, similar to the following example:
```

2023-02-06 15:29 UTC, mprahl commented on governance/policy_gen_install_operator.adoc
> +A `PolicyGenerator` configuration file is required. Use the following policy to install OpenShift GitOps on all {ocp-short} managed clusters:
```suggestion
A `PolicyGenerator` configuration file is required. Use the following configuration file to generate a policy to install OpenShift GitOps on all {ocp-short} managed clusters:
```

2023-02-06 16:29 UTC, dockerymick commented on governance/policy_gen_install_operator.adoc
> +Generate a policy that installs OpenShift GitOps by using the policy generator. The OpenShift GitOps operator offers the _all namespaces_ installation mode. Create a `Subscription` manifest file call
made update according the writing style guide

2023-02-06 16:30 UTC, dockerymick commented on governance/policy_gen_install_operator.adoc
> +Generate a policy that installs OpenShift GitOps by using the policy generator. The OpenShift GitOps operator offers the _all namespaces_ installation mode. Create a `Subscription` manifest file call
Updated according to the style guide

2023-02-06 16:30 UTC, dockerymick commented on governance/policy_gen_install_operator.adoc
> +A `PolicyGenerator` configuration file is required. Use the following policy to install OpenShift GitOps on all {ocp-short} managed clusters:
updated according to style guide

2023-02-06 17:25 UTC, oafischer approved these changes

2023-02-07 00:33 UTC, dockerymick commented on governance/policy_gen_install_operator.adoc
> +{ocp-short} supports all generated policies.
updated

2023-02-07 00:33 UTC, dockerymick commented on governance/policy_gen_install_operator.adoc
> +== Installing the Compliance Operator using a policy
updated

2023-02-07 00:34 UTC, dockerymick commented on governance/manage_policy_def.adoc
> +== Related resources
updated

2023-02-07 15:40 UTC, dhaiducek commented on governance/policy_gen_install_operator.adoc
> +  namespace: policies
@mprahl I've been wondering. Should we recommend setting `policyDefaults.orderManifests` here so that the Subscription is guaranteed to be deployed before the OperatorGroup?

```suggestion
policyDefaults:
  namespace: policies
  orderManifests: true
```

2023-02-07 15:40 UTC, dhaiducek commented on governance/policy_gen_install_operator.adoc
> +== Integrating the Policy Generator with OpenShift GitOps (ArgoCD)
This section feels like it belongs under `manage_policy_def.adoc` rather than under the Operator installs.

2023-02-07 16:34 UTC, dhaiducek commented on governance/policy_gen_install_operator.adoc
> +  namespace: policies
@dockerymick I have a followup to this. We need to remove this from here since it could actually not work at all if the Subscription is deployed before the OperatorGroup (which is how this policy is set up right now). I'll add another suggestion in a bit.

2023-02-07 16:36 UTC, dockerymick commented on governance/policy_gen_install_operator.adoc
> +=== Managing policy definitions with OpenShift GitOps (Argo CD)
updated

2023-02-07 16:36 UTC, dockerymick commented on governance/policy_gen_install_operator.adoc
> +== Integrating the Policy Generator with OpenShift GitOps (ArgoCD)
@dhaiducek updated

2023-02-07 22:36 UTC, dhaiducek reviewed
Operator group suggestion added.

2023-02-07 22:36 UTC, dhaiducek commented on governance/policy_gen_install_operator.adoc
> +----
Please swap `Subscription` and `OperatorGroup` here. (Then it'll align with my new section.)
```suggestion
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: compliance-operator
  namespace: openshift-compliance
spec:
  targetNamespaces:
    - compliance-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: compliance-operator
  namespace: openshift-compliance
spec:
  channel: release-0.1
  name: compliance-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
----
```

2023-02-07 22:36 UTC, dhaiducek commented on governance/policy_gen_install_operator.adoc
> +----
```suggestion
----

[#using-policy-dependencies-with-operatorgroups]
== Using policy dependencies with `OperatorGroups`

When installing an operator with an `OperatorGroup` manifest, the `OperatorGroup` must exist on the cluster before the `Subscription` is created. In this case, you can use the policy dependency feature along with the Policy Generator to ensure that the `OperatorGroup` policy is compliant prior to enforcing the `Subscription` policy.

To set up dependencies, place the manifests in the order in which they should be created. For example, the namespace first, followed by the `OperatorGroup`, followed by the `Subscription`. Then, in the Policy Generator manifest, set `orderManifests: true` and `consolidateManifests: false` either under `policyDefaults` or under the policy in the `policies` array to automatically set up dependencies between the manifests so that each will be handled in the order provided.
```

2023-02-07 23:40 UTC, dockerymick commented on governance/policy_gen_install_operator.adoc
> +----
updated

2023-02-08 01:35 UTC, dhaiducek commented on governance/policy_gen_install_operator.adoc
> +  orderManifests: true
Now that we have the new section (Thanks!), let's take this back out.
```suggestion
```

2023-02-08 19:18 UTC, dhaiducek reviewed
I should defer to @mprahl for final approval, but I think this looks good from my perspective! Thanks for the updates!

2023-02-10 16:20 UTC, mprahl commented on governance/manage_policy_def.adoc
> +Now that OpenShift GitOps can use the policy generator, OpenShift GitOps must be granted access to create policies on the {product-title-short} hub cluster. Create the following `ClusterRole` resourc
This is a repeat from the previous section. Could you please refer back to the previous section as a prerequisite instead?

2023-02-10 16:23 UTC, mprahl commented on governance/policy_gen_install_operator.adoc
> +Enable the `orderManifests` parameter and disable `consolidateManifests` to automatically set up dependencies between the maniifests. Update the parameter values in the Policy Generator manifest to `
```suggestion
In the Policy Generator configuration manifest, enable the `policyDefaults.orderManifests` parameter and disable `policyDefaults.consolidateManifests` to automatically set up dependencies between the manifests.
```

2023-02-10 16:23 UTC, mprahl commented on governance/policy_gen_install_operator.adoc
> +* See link:https://docs.openshift.com/container-platform/4.10/nodes/containers/nodes-containers-init.html[Using Init Containers to perform tasks before a pod is deployed].
Should this be updated to 4.12?

2023-02-10 16:23 UTC, mprahl requested changes
A few small changes are needed, but this looks really good!

2023-02-10 19:52 UTC, mprahl commented on governance/policy_gen_install_operator.adoc
> +Enable the `orderManifests` parameter and disable `consolidateManifests` in the Policy Generator configuration manifest to automatically set up dependencies between the manifests.
```suggestion
Enable the `policyDefaults.orderManifests` parameter and disable `policyDefaults.consolidateManifests` in the Policy Generator configuration manifest to automatically set up dependencies between the manifests.
```

2023-02-12 03:03 UTC, dockerymick commented on governance/policy_gen_install_operator.adoc
> +* See link:https://docs.openshift.com/container-platform/4.10/nodes/containers/nodes-containers-init.html[Using Init Containers to perform tasks before a pod is deployed].
Updated ! Thanks !

2023-02-13 15:58 UTC, dockerymick commented on governance/policy_gen_install_operator.adoc
> +Enable the `orderManifests` parameter and disable `consolidateManifests` to automatically set up dependencies between the maniifests. Update the parameter values in the Policy Generator manifest to `
updated

2023-02-13 17:43 UTC, mprahl approved these changes

2023-02-13 19:12 UTC, merged