Adding known issues for policy templates
open-cluster-management/rhacm-docs pull request #4689
Opened 2023-02-06 16:43 UTC by dockerymick

https://github.com/stolostron/backlog/issues/27150

2023-02-06 16:43 UTC, dockerymick commented
Assigning @mprahl because he created the issue. Let me know if I should reassign

2023-02-06 20:56 UTC, oafischer commented on release_notes/known_issues.adoc
> +- When you rename your configuration policy to a new name, a copy of the configuration policy with the older name remains.
Do we want to start with a list right away? Might be better to have an intro paragraph or just a short prompt before that.

2023-02-06 20:56 UTC, oafischer approved these changes
Looks good, one suggestion but I'll leave it up to you.

2023-02-06 21:26 UTC, dockerymick commented on release_notes/known_issues.adoc
> +- When you rename your configuration policy to a new name, a copy of the configuration policy with the older name remains.
Thanks Oliver! I updated the file

2023-02-07 02:58 UTC, dhaiducek requested changes
Minor suggestions

2023-02-07 02:58 UTC, dhaiducek commented on release_notes/known_issues.adoc
> +- If you remove a configuration policy from your hub cluster, the configuration policy remains on your managed cluster. A status is not provided.
```suggestion
- If you remove a configuration policy from a policy on your hub cluster, the configuration policy remains on your managed cluster but its status is not provided.
```

2023-02-07 02:58 UTC, dhaiducek commented on release_notes/known_issues.adoc
> +To resolve this, disable your configuration and reenable it. You can also delete the entire policy.
```suggestion
To resolve this, disable your policy and reenable it. You can also delete the entire policy.
```

2023-02-07 04:16 UTC, dockerymick commented
@dhaiducek thanks so much Dale! I have accepted your suggestions.

2023-02-07 14:20 UTC, dhaiducek approved these changes

2023-02-07 14:23 UTC, dockerymick commented
Thanks for the approvals! @dhaiducek @oafischer 

Merging this PR

2023-02-07 14:23 UTC, merged