updating Observability support statement
open-cluster-management/rhacm-docs pull request #4732
Opened 2023-02-09 23:25 UTC by dockerymick

https://github.com/stolostron/backlog/issues/26952#issuecomment-1423324813

2023-02-09 23:55 UTC, berenss requested changes
please include the changes into 1.1.1 to mention Thanos

2023-02-09 23:55 UTC, berenss commented on observability/observability_enable.adoc
> -*Important:* When you configure your object store, ensure that you meet the encryption requirements necessary when sensitive data is persisted. For more information on Thanos supported object stores,
I'd say KEEP it here in this section.

2023-02-09 23:55 UTC, berenss commented on observability/observe_environments.adoc
While we get rid of the note from this section, lets be mindful to add it back into 1.1.1. I want to make sure the user/reader knows that we use Thanos in our Observability service:

> The observability service deploys an instance of Prometheus AlertManager, which enables alerts to be forwarded with third-party applications. It also includes an instance of Grafana to enable data visualization with dashboards (static) or data exploration. Red Hat Advanced Cluster Management supports version 8.1.3 of Grafana. You can also design your Grafana dashboard. For more information, see [Designing your Grafana dashboard]. You can customize the observability service by creating custom recording rules or alerting rules. 
eg add: 
For more information about our centralized long term metric data storage, please see https://thanos.io/tip/thanos/storage.md/#object-storage[Thanos documentation].

2023-02-13 16:35 UTC, cadawson approved these changes
One suggestion. Looks good! Thanks!

2023-02-13 16:35 UTC, cadawson commented on observability/observability_enable.adoc
> +*Important:* When you configure your object store, ensure that you meet the encryption requirements necessary when sensitive data is persisted. The observability service uses Thanos supported, stable
```suggestion
*Important:* When you configure your object store, ensure that you meet the encryption requirements that are necessary when sensitive data is persisted. The observability service uses Thanos supported, stable object stores.
```

2023-02-13 17:46 UTC, berenss approved these changes
looks good thank you!

2023-02-13 19:57 UTC, merged