ACM-3386 move lcl-clst ACM 2 mce
open-cluster-management/rhacm-docs pull request #4747
Opened 2023-02-15 21:02 UTC by cadawson

2023-02-15 21:52 UTC, cadawson commented
https://issues.redhat.com/browse/ACM-3386

Hi @ray-harris. Can you review the draft text for this issue in this PR? Thanks!

2023-02-26 20:24 UTC, cadawson commented
@JakobGray: Will you take a look at this draft? Thanks!

2023-02-27 19:58 UTC, JakobGray requested changes
Now that hub-self-management is treated as a component of MCE I think the section can more closely resemble those below it, like the Hypershift add-on section. In that vein it could go something like this:

> By default, the cluster running {mce-short} will manage itself. To install with this feature disabled, include the following in the `MultiClusterEngine` values in `spec.overrides`:
(yaml content but set enabled to false)

Everything after "If the setting is not included in the YAML" can be removed, because that is describing the old way to do it by manually creating the resource. The last line "A hub cluster that is managed by itself..." can stay.

2023-02-27 21:19 UTC, JakobGray commented on clusters/install_upgrade/adv_config_install.adoc
> +If the setting is not included in the YAML file that defines the custom resource, you need to add it. The hub cluster can only be managed with this option.
This line: "If the setting is not included in the YAML file that defines the custom resource, you need to add it. The hub cluster can only be managed with this option." can be deleted, and then I think this is good to go.

2023-02-28 15:16 UTC, cadawson commented on clusters/install_upgrade/adv_config_install.adoc
> +If the setting is not included in the YAML file that defines the custom resource, you need to add it. The hub cluster can only be managed with this option.
Made that update @JakobGray. Thanks! Does that need to be removed from the ACM version, as well, or is it ok there?

2023-03-01 21:12 UTC, oafischer approved these changes
lgtm

2023-03-03 12:27 UTC, merged