[ACM-3650]: Adding KubeVirt as a provider for hosted control planes
open-cluster-management/rhacm-docs pull request #4803
Opened 2023-03-08 20:12 UTC by lahinson

This PR adds documentation to the hosted control planes section about using KubeVirt as a provider. This will be Technology Preview for MCE 2.3.

Related Jira task: https://issues.redhat.com/browse/ACM-3650

2023-03-08 22:36 UTC, davidvossel reviewed
here's some preliminary feedback. i'll give this a more detailed look later this week.

2023-03-08 22:36 UTC, davidvossel commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> +//How do we verify cluster creation on KubeVirt?
I think two items i listed below give a good signal that the hosted cluster has created successfully.

1. Verify the HostedCluster has transitioned to "Completed"

```
oc get --namespace clusters hostedclusters ${CLUSTER_NAME}
NAMESPACE   NAME      VERSION   KUBECONFIG                 PROGRESS    AVAILABLE   PROGRESSING   MESSAGE
clusters    example   4.12.2    example-admin-kubeconfig   Completed   True        False         The hosted control plane is available

```

2. Verify all the cluster operators are online within the guest cluster

```
# get the guest cluster's kubeconfig
hypershift create kubeconfig --name $CLUSTER_NAME > $CLUSTER_NAME-kubeconfig

oc get co --kubeconfig=$CLUSTER_NAME-kubeconfig
NAME                                       VERSION   AVAILABLE   PROGRESSING   DEGRADED   SINCE   MESSAGE
console                                    4.10.26   True        False         False      2m38s
csi-snapshot-controller                    4.10.26   True        False         False      4m3s
dns                                        4.10.26   True        False         False      2m52s
image-registry                             4.10.26   True        False         False      2m8s
ingress                                    4.10.26   True        False         False      22m
kube-apiserver                             4.10.26   True        False         False      23m
kube-controller-manager                    4.10.26   True        False         False      23m
kube-scheduler                             4.10.26   True        False         False      23m
kube-storage-version-migrator              4.10.26   True        False         False      4m52s
monitoring                                 4.10.26   True        False         False      69s
network                                    4.10.26   True        False         False      4m3s
node-tuning                                4.10.26   True        False         False      2m22s
openshift-apiserver                        4.10.26   True        False         False      23m
openshift-controller-manager               4.10.26   True        False         False      23m
openshift-samples                          4.10.26   True        False         False      2m15s
operator-lifecycle-manager                 4.10.26   True        False         False      22m
operator-lifecycle-manager-catalog         4.10.26   True        False         False      23m
operator-lifecycle-manager-packageserver   4.10.26   True        False         False      23m
service-ca                                 4.10.26   True        False         False      4m41s
storage                                    4.10.26   True        False         False      4m43s
```

2023-03-09 15:11 UTC, lahinson commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> +//How do we verify cluster creation on KubeVirt?
Thanks, @davidvossel! I updated the file to add that info.

2023-03-09 22:40 UTC, davidvossel reviewed
hey, here's some more detailed feedback. I know a lot of the content has been pulled from resources I wrote. Since this is official documentation, we need to mention OpenShift Virtualization as the product that we're supporting hosted control planes with. I tried to sort through that a bit. It's a bit tricky.

2023-03-09 22:40 UTC, davidvossel commented on clusters/hosted_control_planes/hosted_intro.adoc
> +Hosted control planes for {ocp-short} are available as a Technology Preview feature on Amazon Web Services (AWS), bare metal or virtual environments, and KubeVirt. You can host the control planes on
On this line, I think we should say we support Technology Preview on `OpenShift Virtualization` instead of `KubeVirt`.

I haven't done a great job at making the distinction between these two terms in the various documentation floating around so far. In general, for our official documentation, we want to communicate that Hosted Control Planes are supported on OpenShift Virtualization and that the underlying technology that makes that possible is KubeVirt.

So
* `OpenShift Virtualization` when talking about the product we support Hosted Control Planes with
* `KubeVirt` when we're refering to the underlying technology or hypershift platform.

I'll point out though the rest of the document places where I think it makes sense to throw in OpenShift Virtualization in replacement of KubeVirt.

2023-03-09 22:40 UTC, davidvossel commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> += Creating hosted control plane clusters on KubeVirt (Technology Preview)
Creating hosted control plane clusters on `OpenShift Virtualization` (Technology Preview)

2023-03-09 22:40 UTC, davidvossel commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> +You can install a nested {ocp} cluster that runs on KubeVirt virtual machines within a management cluster.
Maybe we can differenciate the technology (kubevirt) and product (Hosted Control Planes and Openshift Virtualization) by structuring this sentence something like this.

`With Hosted Control Planes and OpenShift Virtualization, {ocp} clusters can be created with worker nodes hosted by KubeVirt virtual machines.`

2023-03-09 22:40 UTC, davidvossel commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> +You must meet the following prerequisites to create a hosting cluster on KubeVirt:
You must meet the following prerequisites to create an {ocp} cluster on `OpenShift Virtualization` using the hosted cluster's `KubeVirt` platform:

2023-03-09 22:40 UTC, davidvossel commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> +----
@rokej will we have the hypershift cli delivered in MCE 2.3 as a download so people don't need to build the hypershift cli tool themselves? If so, is that something we can document now?

2023-03-09 22:40 UTC, davidvossel commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> +== Prerequisites
Two things are missing from the Prerequisites.

1. do we need to outline how to install and enable the hypershift operator via MCE? Maybe there is there some documentation for that we can link to here?
2. load balancer support is required. Maybe we just link them to the load balancer section in this doc? I just want to make sure people know that's a prerequisite for their cluster to provision correctly.

2023-03-09 22:40 UTC, davidvossel commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> +=== Creating a hosted cluster on KubeVirt
`Creating a hosted cluster with the KubeVirt platform`

2023-03-09 22:40 UTC, davidvossel commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> +A guest cluster that is backed by KubeVirt virtual machines typically takes 10-15 minutes to be fully provisioned.
A guest cluster `with worker nodes` backed by KubeVirt virtual machines typically takes 10-15 minutes to be fully provisioned.

2023-03-09 22:40 UTC, davidvossel commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> +----
one small detail here. i kind of goofed up when I gave you this example. We need all those versions to change from `4.10.26` to `4.12.2` to align with the cluster version used in all the other examples.

2023-03-10 20:47 UTC, lahinson commented on clusters/hosted_control_planes/hosted_intro.adoc
> +Hosted control planes for {ocp-short} are available as a Technology Preview feature on Amazon Web Services (AWS), bare metal or virtual environments, and KubeVirt. You can host the control planes on
This is helpful -- thank you! I will make updates accordingly.

2023-03-10 20:51 UTC, rokej commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> +----
We currently have this doc on how to download and install the CLI https://github.com/stolostron/rhacm-docs/blob/2.8_stage/clusters/hosted_control_planes/configure_hosted_aws.adoc#installing-the-hosted-control-planes-cli. This should be a common step for all platforms.

2023-03-10 21:20 UTC, lahinson commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> +== Prerequisites
I updated the prereq about the CLI to point to the docs that Roke mentioned. The second half of that prereq mentions how to install the HyperShift Operator after you install the CLI.

I also added a prereq about configuring a load balancer and linked to the section further down the page.

2023-03-10 21:20 UTC, lahinson commented
Thanks for your feedback, @davidvossel and @rokej! I made a few updates based on your comments. When you can, let me know what you think.

2023-03-13 15:47 UTC, lahinson commented
I added a list of benefits to the introduction, based on this blog post: https://cloud.redhat.com/blog/effortlessly-and-efficiently-provision-openshift-clusters-with-openshift-virtualization

2023-03-16 18:30 UTC, davidvossel reviewed
I made a couple of more minor comments. I think this is getting close

2023-03-16 18:30 UTC, davidvossel commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> +----
This is another area where our upstream docs deviate from what we need to officially document.

The hypershift operator needs to be enabled via MCE, and not `hypershift install`. Its unfortunate that we even have functionality within the hypershift cli to do the install. that was meant as a way for developers to test hypershift operator and not meant for end users.

The [aws related doc ](https://github.com/stolostron/rhacm-docs/blob/2.8_stage/clusters/hosted_control_planes/configure_hosted_aws.adoc#enabling-the-hosted-control-planes-feature) has a section about how to enable the Hosted Control Planes feature, which enables the hypershift operator.

2023-03-16 18:30 UTC, davidvossel commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> +After you install the CLI, install the HyperShift Operator by entering the following command:
Two things here
1. I think we should reframe this as `Enabling the Hosted Control Plane` feature rather than talking about installing the hypershift operator.
2. for the official docs, we can't use the hypershift cli tool to install the hypershift operator. I have a more detailed comment below

2023-03-16 18:30 UTC, davidvossel commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> +. Create an address pool with an available range of IP addresses within the node network:
Can you add a note to `Replace the ip address ranges defined in the spec with unused pool of available ips in your network`

2023-03-16 19:17 UTC, lahinson commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> +----
Ah, okay. I'll replace that with a pointer to the docs to enable the hosted control planes feature. Thanks!

2023-03-16 19:25 UTC, rokej commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> +After you install the CLI, install the HyperShift Operator by entering the following command:
So https://github.com/stolostron/rhacm-docs/blob/lahinson-hcp-kubevirt/clusters/hosted_control_planes/configure_hosted_aws.adoc#enabling-the-hosted-control-planes-feature should be a pre-req as well. 

After enabling the hosted control place feature (which installs the hypershift operator too), then you follow https://github.com/stolostron/rhacm-docs/blob/lahinson-hcp-kubevirt/clusters/hosted_control_planes/configure_hosted_aws.adoc#installing-the-hosted-control-planes-cli to install the CLI binary.

2023-03-16 19:33 UTC, lahinson commented
@davidvossel I made a few more updates based on your feedback. Let me know what you think when you can!

2023-03-16 19:35 UTC, lahinson commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> +After you install the CLI, install the HyperShift Operator by entering the following command:
Thanks, @rokej! I just added a link to the doc to enable the hosted control planes feature. I'll add the link to the instructions about installing the CLI library now.

2023-03-17 14:49 UTC, davidvossel commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> +- You need to enable the hosted control planes feature. For information, see xref:../../clusters/hosted_control_planes/configure_hosted_aws.adoc#hosted-enable-feature-aws[Enabling the hosted control
I see this references the `hosted-enable-feature-aws`. Looking at that doc, it is not accurately describing only the steps required for enabling hosted control planes. It's describing a but of AWS related details as well, which are not related to OpenShift virtualization.

only this section is pertinent to enabling Hosted Control Planes for OpenShift Virtualization. https://github.com/stolostron/rhacm-docs/blob/2.8_stage/clusters/hosted_control_planes/configure_hosted_aws.adoc#enabling-the-hosted-control-planes-feature

2023-03-17 14:58 UTC, lahinson commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> +- You need to enable the hosted control planes feature. For information, see xref:../../clusters/hosted_control_planes/configure_hosted_aws.adoc#hosted-enable-feature-aws[Enabling the hosted control
Good catch! I updated the link.

2023-03-17 15:00 UTC, davidvossel commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> +- After you enable the hosted control planes feature, you need to xref:../../clusters/hosted_control_planes/configure_hosted_aws.adoc#installing-the-hosted-control-planes-cli[install the CLI binary].
One detail here, should we change `install the CLI binary` to `install the hypershift CLI binary`. That way if someone see's a reference to the `hypershift` cli later on in the doc, they'll be able to cross reference easily the step that involves installing that tool

2023-03-17 15:16 UTC, lahinson commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> +- After you enable the hosted control planes feature, you need to xref:../../clusters/hosted_control_planes/configure_hosted_aws.adoc#installing-the-hosted-control-planes-cli[install the CLI binary].
Good point. I updated the wording to match what we have in that section of the docs (i.e., "install the hosted control planes CLI binary").

2023-03-17 18:02 UTC, davidvossel commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> +- After you enable the hosted control planes feature, you need to xref:../../clusters/hosted_control_planes/configure_hosted_aws.adoc#installing-the-hosted-control-planes-cli[install the hosted contr
to make it clear that the `hypershift` cli is the hosted control plane cli, do you think it makes sense to clarify this relationship a bit. Something like `[install the hosted control plane (hypershift) CLI binary]`?

2023-03-17 18:08 UTC, lahinson commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> +- After you enable the hosted control planes feature, you need to xref:../../clusters/hosted_control_planes/configure_hosted_aws.adoc#installing-the-hosted-control-planes-cli[install the hosted contr
Sure. I added "(`hypershift`)" to the descriptive link text.

2023-03-20 20:47 UTC, davidvossel reviewed
/lgtm

Thanks!

2023-03-21 00:10 UTC, lahinson commented
@swopebrandi1 Do you have the bandwidth to peer review the new KubeVirt docs for hosted control planes sometime in the next week or so? David and Roke have already reviewed them.

2023-03-22 15:00 UTC, swopebe commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> ++
we usually say something like "See the following DNS:" to alert an nonsighted user in a case like this.

2023-03-22 15:01 UTC, swopebe commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> +- The management {ocp-short} cluster must be configured with OVNKubernetes as the default pod network CNI.
We usually write "Managed cluster." 

Is this the same?

The {ocp-short} managed cluster....

2023-03-22 15:01 UTC, swopebe commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> ++
The following example:

2023-03-22 15:02 UTC, swopebe commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> +- You need the {ocp-short} CLI (`oc`) or the Kubernetes CLI (`kubectl`).
(We stopped putting this is prereqs because with OCP install, we did not have to say this anymore. @rokej wouldn't the user already have `oc`? Per the install team, we stopped logging that in as prereqs as much. Let me know?

2023-03-22 15:05 UTC, swopebe commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> +Replace values as necessary.
We normally specify what to add as values here, not sure if we need to do that. I think the way we add the variables may differ from book to book, which I will address with the team:

Example:  `namespace: <target_managed_cluster>`
- Replace `target_managed_cluster` with the name of the managed cluster to which you are applying the `ManagedServiceAccount`.

2023-03-22 15:05 UTC, swopebe commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> ++
per changes to "for each" or something similar...

2023-03-22 15:05 UTC, swopebe commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> ++
per changes to "for each" or something similar...

2023-03-22 15:06 UTC, swopebe commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> +. To check the status of the guest cluster, see the corresponding HostedCluster resource. The following example output illustrates a fully provisioned HostedCluster object:
Throughout we write the resources: `HostedCluster` to represent how it would be added to the resource file.

2023-03-22 15:07 UTC, swopebe commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> +. To gain CLI access to the guest cluster, retrieve the guest cluster's kubeconfig environment variable. The following example shows how to retrieve the guest cluster's kubeconfig environment variabl
we remove possessives

2023-03-22 15:08 UTC, swopebe commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> +**Note:** For the default Ingress DNS to work properly, the underlying cluster that hosts the KubeVirt virtual machines must allow wildcard DNS routes. You can configure this behavior by entering the
We now use only one asterisks for Note, just to be on the same page.

2023-03-22 15:08 UTC, swopebe commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> ++
same here with possessive and maybe an accidental italics?

2023-03-22 15:09 UTC, swopebe commented on modules/common-attributes.adoc
> +:ocp-virt-short: OpenShift Virtualization
Thank you for this!

2023-03-22 15:14 UTC, swopebe requested changes
I asked for a number of changes but will note here some that may apply in various places:

We usually pull out the command from the file that needs to be applied:

1. Create a __ file similar to the following example, with the .... specification.
2. Run the `oc -apply <file` to apply your ___ file.

(Sometimes they are together in these sections)

We remove extra stuff like EOF which is located in a few spots.

(There may be some formatting issues, which are usually caused by an extra asterisks. I cannot easily tell but will check as we get closer to final.)

2023-03-22 15:25 UTC, lahinson commented
Thanks, Brandi! I will take a look at your comments this afternoon.

2023-03-22 15:29 UTC, rokej commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> +- The management {ocp-short} cluster must be configured with OVNKubernetes as the default pod network CNI.
I think the term `management cluster` is from SD environment where they have service (hub) and management (managed) clusters. We should change `management cluster` to 'managed cluster`. 

Also MCE currently supports only the hub cluster also known as `local-cluster`. No other remote managed cluster to host hypershift hosted clusters. So `management cluster` = `managed cluster` = `local-cluster` = MCE hub cluster = hypershift hosting cluster.

2023-03-22 15:29 UTC, lahinson commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> ++
Good catch. I'll update that to `- The management {ocp-short} cluster must have wildcard DNS routes enabled, as shown in the following DNS:`

2023-03-22 15:40 UTC, lahinson commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> +- The management {ocp-short} cluster must be configured with OVNKubernetes as the default pod network CNI.
In the OCP docs for hosted control planes, we've been using "management cluster". Here's an example of where that terminology is used: https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html/backup_and_restore/control-plane-backup-and-restore#dr-hosted-cluster-process

Whenever I've seen the term "managed," it's in the context of managed HyperShift, such as HyperShift on ROSA.  

@rokej Can you provide guidance here? It would be best for both doc sets to use the same terminology, whether that's "managed cluster" or "management cluster".

2023-03-22 15:42 UTC, lahinson commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> +- You need the {ocp-short} CLI (`oc`) or the Kubernetes CLI (`kubectl`).
Ah, okay. I can remove that. I'll wait for Roke to confirm.

2023-03-22 15:47 UTC, lahinson commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> ++
@davidvossel I need an accuracy check. Which revision is closest to your intended meaning?

1. "A default node pool is created for the cluster with two virtual machine worker replicas for each `--node-pool-replicas` flag."
2. "A default node pool is created for the cluster with two virtual machine worker replicas according to the `--node-pool-replicas` flag."

2023-03-22 15:57 UTC, rokej commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> +- You need the {ocp-short} CLI (`oc`) or the Kubernetes CLI (`kubectl`).
I am OK to remove this as well. Thanks.

2023-03-22 18:08 UTC, lahinson commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> +Replace values as necessary.
@davidvossel Do you think the intended user will know which values to add, or would it be helpful for us to specify which values to add, as Brandi mentioned?

2023-03-22 19:28 UTC, rokej commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> +- The management {ocp-short} cluster must be configured with OVNKubernetes as the default pod network CNI.
@lahinson Yes, I see that OCP doc uses `management cluster`. In MCE, `managed cluster` is a cluster you can configure to host multiple hypershift hosted control planes as @swopebe pointed out.  


https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.7/html/clusters/cluster_mce_overview#hosting-service-cluster-configure-aws

I think we should just simply change `The management {ocp-short} cluster must have {ocp-virt-short} installed on it.` to `The MCE cluster must have {ocp-virt-short} installed on it.`

2023-03-22 19:34 UTC, lahinson commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> +- The management {ocp-short} cluster must be configured with OVNKubernetes as the default pod network CNI.
@rokej After I saw your earlier response to Brandi, I updated all instances of "the management {ocp-short} cluster" to "the {ocp-short} managed cluster". Is that okay?

2023-03-22 19:42 UTC, rokej commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> +- The management {ocp-short} cluster must be configured with OVNKubernetes as the default pod network CNI.
Yes thank you

2023-04-06 15:41 UTC, chenz4027 commented
Hey @lahinson , the dev portion was merged.  https://github.com/stolostron/console/pull/2665

I used `${DOC_BASE_PATH}/clusters/index#hosted-control-planes-manage-kubevirt`, hope it remains the same here.

2023-04-06 15:52 UTC, lahinson commented
@chenz4027 That looks right to me. Thanks!

2023-04-06 15:53 UTC, chenz4027 commented
Perfect, thanks @lahinson for the quick confirmation :)

2023-04-10 14:37 UTC, lahinson commented
To do: Incorporate updates from https://github.com/openshift/hypershift/pull/2318/files

2023-04-10 20:44 UTC, davidvossel commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> +Replace values as necessary.
Someone who is familiar with linux command line tools will understand this as it's written now. If there's a way to represent the same information in a way that's more consistent with other parts of the documentation, that's fine as well.

2023-04-10 20:45 UTC, davidvossel commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> ++
`A default node pool is created for the cluster with two virtual machine worker replicas according to the --node-pool-replicas flag.` looks more accurate to me

2023-04-10 21:02 UTC, davidvossel reviewed
the content looks great. I left one comment about the formatting that i was unsure about

2023-04-10 21:02 UTC, davidvossel commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> +* <<hosting-service-cluster-configure-metallb-config,Optional: Configuring MetalLB>>
I want to double check that the formatting here will look correct. At first glance, it appears that the bullet points describing the benefits will also have the table of contents. Do the links to the separate parts of the doc need to be separated?

2023-04-11 14:13 UTC, lahinson commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> +* <<hosting-service-cluster-configure-metallb-config,Optional: Configuring MetalLB>>
Good catch, @davidvossel! You're right -- the two lists shouldn't be next to each other. I added a lead-in sentence above the TOC to separate them, and made a few more minor changes. Thanks so much for your review!

2023-04-11 14:14 UTC, lahinson commented
@swopebe When you're back from PTO, please take a look at the latest draft of the KubeVirt docs and let me know if we're ready to merge. Thank you!

2023-04-11 20:36 UTC, davidvossel reviewed
/lgtm

2023-04-12 21:02 UTC, dtthuynh commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> += Creating hosted control plane clusters on {ocp-virt-short} (Technology Preview)
Excuse the nitpick - should this match the title of this doc section? i.e. 'Managing' instead of 'Creating'
I think we use 'Managing' for aws/BM currently as well

2023-04-13 12:54 UTC, lahinson commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> += Creating hosted control plane clusters on {ocp-virt-short} (Technology Preview)
Sure, I can use "Managing" to be consistent with the other sections.

2023-04-19 17:04 UTC, swopebe approved these changes

2023-04-19 17:05 UTC, lahinson commented
Thanks, Brandi!

2023-04-19 17:05 UTC, merged