Update the generator docs
open-cluster-management/rhacm-docs pull request #4808
Opened 2023-03-10 22:28 UTC by dhaiducek

- Add `generate*Placement` fields
- Add `policySetDefaults`
- Add `copyPolicyMetadata`
- Update Placement fields for LabelSelectors

ref: https://issues.redhat.com/browse/ACM-3011

2023-03-13 12:57 UTC, mprahl approved these changes

2023-03-13 14:19 UTC, dockerymick commented
@dhaiducek thanks for creating this! I will review it today

2023-03-13 17:54 UTC, dockerymick commented
@dhaiducek Thanks again for starting this PR. I have made some updates to the descriptions, along with adding the What's new entry. Will you review when you have an opportunity? Also getting requesting peer review from a writer

2023-03-13 18:58 UTC, dockerymick reviewed
Based on my updates, I approve this PR. Awaiting peer review from another writer

2023-03-13 20:56 UTC, cadawson requested changes
A few smaller suggestions. I don't need to review it again. Thanks!

2023-03-13 20:56 UTC, cadawson commented on governance/policy_generator.adoc
> +| Copies the labels and annotations for all policies and add to a replica policy. Set to `true` by default. If set to `false`, only the policy framework specific policy labels and annotations are cop
This one is confusing me a bit:
Copies the labels and annotations for all policies and add them to a replica policy. (?)
Copies the labels and annotations for all policies and adds them to a replica policy.(?)

2023-03-13 20:56 UTC, cadawson commented on governance/policy_generator.adoc
> +| To reuse an existing placement, specify the path here relative to the `kustomization.yaml` file. If provided, this placement rule is used by all policies by default. See `_clusterSelectors_` to gen
```suggestion
| To reuse an existing placement, specify the path relative to the location of the `kustomization.yaml` file. If provided, this placement rule is used by all policies by default. See `_clusterSelectors_` to generate a new `Placement`.
```

2023-03-13 20:56 UTC, cadawson commented on governance/policy_generator.adoc
> +| Specify a placement by defining a cluster selector using either `key:value`, or providing `matchExpressions` and or `matchLabels` keys with appropriate values. See `_placementPath_` to specify an e
```suggestion
| Specify a placement by defining a cluster selector using either `key:value`, or by providing `matchExpressions`, `matchLabels` keys, or both, with appropriate values. See `_placementPath_` to specify an existing file.
```

2023-03-13 20:56 UTC, cadawson commented on governance/policy_generator.adoc
> +| To reuse an existing placement rule, specify the path here relative to the `kustomization.yaml` file. If provided, this placement rule is used by all policies by default. See `_labelSelector_` to g
```suggestion
| To reuse an existing placement rule, specify the path relative to the location of the `kustomization.yaml` file. If provided, this placement rule is used by all policies by default. See `_labelSelector_` to generate a new `PlacementRule`.
```

2023-03-13 20:56 UTC, cadawson commented on governance/policy_generator.adoc
> +| Specify a placement rule by defining a cluster selector using either `key:value`, or providing a `matchExpressions` and or `matchLabels` keys with appropriate values. See `_placementRulePath_` to s
```suggestion
| Specify a placement rule by defining a cluster selector using either `key:value`, or providing a `matchExpressions`, `matchLabels` keys, or both, with appropriate values. See `_placementRulePath_` to specify an existing file.
```

2023-03-13 20:56 UTC, cadawson commented on release_notes/whats_new.adoc
> +* You can now configure the Policy Generator to add a copy of meta data to replicas of your policies and policy sets, along with generate placement manifests for your policies and policy sets. See li
```suggestion
* You can now configure the Policy Generator to add a copy of metadata to replicas of your policies and policy sets, along with generate placement manifests for your policies and policy sets. See link:../governance/policy_generator.adoc#policy-gen-yaml-table[Policy Generator configuration reference table] for more details.
```

2023-03-14 00:41 UTC, dockerymick commented on governance/policy_generator.adoc
> +| Copies the labels and annotations for all policies and add to a replica policy. Set to `true` by default. If set to `false`, only the policy framework specific policy labels and annotations are cop
@cadawson thanks for your review, feedback, and suggestions!

2023-03-14 00:41 UTC, dockerymick commented
@dhaiducek I have updated the PR based on the peer review from Chris. When you have an opportunity, will you rereview the PR?

2023-03-14 20:38 UTC, dhaiducek reviewed
A couple wording things. I also realized that I swapped `labelSelector` and `clusterSelector` 🤦‍♂️ , so I've made those suggestions here also.

2023-03-14 20:38 UTC, dhaiducek commented on governance/policy_generator.adoc
> +| To reuse an existing placement, specify the path relative to the location of the `kustomization.yaml` file. If provided, this placement rule is used by all policies by default. See `_clusterSelecto
```suggestion
| To reuse an existing placement, specify the path relative to the location of the `kustomization.yaml` file. If provided, this placement rule is used by all policies by default. See `_labelSelector_` to generate a new `Placement`.
```

2023-03-14 20:38 UTC, dhaiducek commented on governance/policy_generator.adoc
> +| Specify a placement by defining a cluster selector using either `key:value`, or by providing `matchExpressions`, `matchLabels` keys, or both, with appropriate values. See `_placementPath_` to speci
```suggestion
| Specify a placement by defining a cluster selector using either `key:value`, or by providing `matchExpressions`, `matchLabels`, or both, with appropriate values. See `_placementRulePath_` to specify an existing file.
```

2023-03-14 20:38 UTC, dhaiducek commented on governance/policy_generator.adoc
> +| To reuse an existing placement rule, specify the path relative to the location of the `kustomization.yaml` file. If provided, this placement rule is used by all policies by default. See `_labelSele
```suggestion
| To reuse an existing placement rule, specify the path relative to the location of the `kustomization.yaml` file. If provided, this placement rule is used by all policies by default. See `_clusterSelector_` to generate a new `PlacementRule`.
```

2023-03-14 20:38 UTC, dhaiducek commented on governance/policy_generator.adoc
> +| Specify a placement rule by defining a cluster selector using either `key:value`, or providing a `matchExpressions`, `matchLabels` keys, or both, with appropriate values. See `_placementRulePath_`
```suggestion
| Specify a placement rule by defining a cluster selector using either `key:value`, or providing a `matchExpressions`, `matchLabels`, or both, with appropriate values. See `_placementPath_` to specify an existing file.
```

2023-03-14 20:38 UTC, dhaiducek commented on governance/policy_generator.adoc
> +| Any default value for a policy set. Any default value listed for this parameter is overridden by an entry in the `policySets` array.
```suggestion
| Default values for policy sets. Any default value listed for this parameter is overridden by an entry in the `policySets` array.
```

2023-03-14 20:38 UTC, dhaiducek commented on governance/policy_generator.adoc
> +| The list of policy sets to create that overrides to either the default values, or the values that are set in `policySetDefaults`. To include a policy in a policy set, use `policyDefaults.policySets
```suggestion
| The list of policy sets to create along with overrides to either the default values, or the values that are set in `policySetDefaults`. To include a policy in a policy set, use `policyDefaults.policySets`, `policies[].policySets`,  or `policySets.policies`. See `_policySetDefaults_` for additional fields and descriptions.
```

2023-03-14 20:38 UTC, dhaiducek commented on release_notes/whats_new.adoc
> +* You can now configure the Policy Generator to add a copy of metadata to replicas of your policies and policy sets, along with generate placement manifests for your policies and policy sets. See lin
```suggestion
* You can now configure the Policy Generator to remove extra metadata when replicating policies, along with specifying placement label selectors for your policies and policy sets. See link:../governance/policy_generator.adoc#policy-gen-yaml-table[Policy Generator configuration reference table] for more details.
```

2023-03-14 23:39 UTC, dockerymick commented on governance/policy_generator.adoc
> +| The list of policy sets to create that overrides to either the default values, or the values that are set in `policySetDefaults`. To include a policy in a policy set, use `policyDefaults.policySets
made an update related to this suggestion.

2023-03-14 23:40 UTC, dockerymick commented
@dhaiducek thanks for your suggestions! I accepted most and made a couple more updates.

2023-03-14 23:50 UTC, dockerymick approved these changes
I made a few more changes related to the doc team's effort to reduce the number of inline links. Thanks again for creating this PR, I appreciate you! From my perspective, this PR looks good to me.

2023-03-14 23:50 UTC, merged