https://issues.redhat.com/browse/ACM-4060
open-cluster-management/rhacm-docs pull request #4811
Opened 2023-03-14 13:52 UTC by oafischer

https://issues.redhat.com/browse/ACM-4060

Needs updated example outputs. Check examples for accuracy. Check if any of the process/flow for Rsync-TLS should be different from Rsync.

2023-03-14 13:57 UTC, oafischer commented on add-ons/volsync/volsync_replicate.adoc
> +a831264645yhrjrjyer6f9e4a02eb2-5592c0b3d94dd376.elb.us-east-1.amazonaws.com
Is this output still a good example?

2023-03-14 13:59 UTC, oafischer commented on add-ons/volsync/volsync_replicate.adoc
> +KEYSECRET=`oc get replicationdestination <destination> -n <destination-ns> --template={{.status.rsyncTLS.keySecret}}`
Is this still applicable to Rsync-TLS? I looked over the upstream docs and from what I can tell, the key secret works a little differently from the SSH key, so I'm not sure.

2023-03-28 19:36 UTC, tesshuflower commented on add-ons/volsync/volsync_replicate.adoc
> +a831264645yhrjrjyer6f9e4a02eb2-5592c0b3d94dd376.elb.us-east-1.amazonaws.com
This still looks good 👍

2023-03-28 19:37 UTC, tesshuflower commented on add-ons/volsync/volsync_replicate.adoc
> +  rsync:
This needs to be `rsyncTLS` rather than `rsync`

2023-03-28 19:46 UTC, tesshuflower commented on add-ons/volsync/volsync_replicate.adoc
> +volsync-rsync-dst-src-destination-name
Here's a better example output from the `echo $KEYSECRET` cmd:

`volsync-rsync-tls-destination-name`

2023-03-28 19:46 UTC, tesshuflower commented on add-ons/volsync/volsync_replicate.adoc
> +KEYSECRET=`oc get replicationdestination <destination> -n <destination-ns> --template={{.status.rsyncTLS.keySecret}}`
This individual command is good, but it seems like we're missing some steps here - this command will essentially just get the name of the keySecret secret.   I'll put some more comments a bit below ..

2023-03-28 19:55 UTC, tesshuflower commented on add-ons/volsync/volsync_replicate.adoc
> +volsync-rsync-dst-src-destination-name
Note that after this step all we've done is echo the secret name (i.e. `volsync-rsync-tls-destination-name` is the name of the secret that VolSync created.  It actually looks like the rsync docs have this same problem.  They don't cover the steps to actually copy the secret over (although line 191 above mentions the steps are how to find the secret and copy its contents).

To get the contents users would need to do something along the lines of:

```
$ oc get secret $KEYSECRET -n <destination-ns> -o yaml > /tmp/keysecret.yaml

# Now remove unnecessary fields:
$ vi /tmp/keysecret.yaml
$ ^^^ change the namespace to the source namespace where the replicationsource will be created
$ ^^^ remove unnecessary fields from .metadata (i.e. fields that are not name or namespace)

# Create the secret on the source cluster
$ oc create -f /tmp/keysecret.yaml


Note essentially the same steps are needed with rsync as well - I thought this was previously documented, but maybe I'm just imagining it?  Even though the contents of the secrets are different between rsync and rsync-tls, just copying over the secret is the same for each (other than the names themselves and how to get it from the status).

2023-03-28 19:57 UTC, tesshuflower commented on add-ons/volsync/volsync_replicate.adoc
> +*Note:* The source and destination must have access to the shared key for the TLS connection. You can find the key location in the `keySecret` field. If you do not provide a secret name in `.spec.rsy
If we're going to mention that the secret name can be provided, we probably need to document the format of the secret if the user wants to create it themselves.

You can find upstream documentation for the rsync-tls secret here:  https://volsync.readthedocs.io/en/latest/usage/rsync-tls/index.html

Look in the "Rsync-specific considerations > TLS authentication" section.  There is info on creating your own secret.

Note that the steps following this note show how to create the replicationdestination and let VolSync create the secret for you.

2023-03-28 19:59 UTC, tesshuflower commented on add-ons/volsync/volsync_replicate.adoc
> +. Identify the source persistent volume claim that you want to replicate.
Note that these steps may be taking place on another cluster. I.e. we have a destination cluster where we created the replicationdestination and now we have the source cluster where the pvc that we want to replicate lives.

2023-03-28 20:01 UTC, tesshuflower commented on add-ons/volsync/volsync_replicate.adoc
> +Replace `mykeysecret` with the keys that you copied from the `.status.rsyncTLS.keySecret` field of the `ReplicationDestination` when you configured it.
This should be replace `mykeysecret` with the name of the secret that was copied over from the destination cluster to the source cluster.  this will be the value of $KEYSECRET if they followed the steps above

2023-03-28 20:01 UTC, tesshuflower commented on add-ons/volsync/volsync_replicate.adoc
> +Replace `my.host.com` with the host address that you copied from the `.status.rsyncTLS.address` field of the `ReplicationDestination` when you configured it.
Should we mention this will be the value of $ADDRESS if they ran the cmd on line 181 above?

2023-03-28 20:02 UTC, tesshuflower commented on add-ons/volsync/volsync_replicate.adoc
> +.. Copy the key secret from the destination cluster by entering the following command against the destination cluster:
Oh, my bad!  This is where the copying of the secret is documented!  Sorry - Uh...I think maybe it just makes sense to move this higher up rather than after the section about creating the replicationsource?  I think they'd want to copy over the secret, then create their replicationsource.

2023-03-28 20:03 UTC, tesshuflower commented on add-ons/volsync/volsync_replicate.adoc
> +.. On the source cluster, modify the `replication_source.yaml` file by replacing the value of the `address` and `keySecret` in the `ReplicationSource` object with the values that you noted from the d
Maybe redundant since we told them to do this already above?  I guess the sed cmds below might be useful though

2023-03-28 20:04 UTC, tesshuflower commented on add-ons/volsync/volsync_replicate.adoc
> +KEYSECRET=`oc get replicationdestination <destination> -n <destination-ns> --template={{.status.rsyncTLS.keySecret}}`
Update: Sorry there actually are steps below about copying the secret over...maybe it makes sense to move them here instead.

2023-03-28 20:05 UTC, oafischer commented on add-ons/volsync/volsync_replicate.adoc
> +.. Copy the key secret from the destination cluster by entering the following command against the destination cluster:
Yes that's a good idea, stuff like this is why I wanted to essentially restructure and rewrite large parts of the VolSync doc. Chris actually ended up taking that issue, so he'll probably arrange a meeting to go over the existing docs and find all the places that need improvement.

2023-03-28 20:05 UTC, tesshuflower requested changes
Looking good so far!  I added some comments, please let me know if you have any questions or if anything I wrote doesn't make sense.

2023-03-29 14:41 UTC, oafischer commented on add-ons/volsync/volsync_replicate.adoc
> +*Note:* The source and destination must have access to the shared key for the TLS connection. You can find the key location in the `keySecret` field. If you do not provide a secret name in `.spec.rsy
It got really messy so I rearranged some stuff and hopefully the flow makes more sense now. I made the secret creation an optional step, given the content after it, as you said, shows you how to let the secret be created for you. Let me know if this works.

2023-03-29 14:43 UTC, oafischer commented on add-ons/volsync/volsync_replicate.adoc
> +volsync-rsync-dst-src-destination-name
I moved those steps further up as suggested. The whole topic is still a little convoluted and hard to follow, but that is something Chris will hopefully address with the rewrite soon-

2023-03-29 14:46 UTC, oafischer commented on add-ons/volsync/volsync_replicate.adoc
> +volsync-rsync-dst-src-destination-name
Fixed on both rsync topics, let me know if the order makes more sense now.

2023-03-29 14:57 UTC, oafischer commented on add-ons/volsync/volsync_replicate.adoc
> +Replace `my.host.com` with the host address that you copied from the `.status.rsyncTLS.address` field of the `ReplicationDestination` when you configured it.
If it helps the user or might otherwise be easy to miss/confusing, then let's add it.

2023-03-29 15:03 UTC, oafischer commented on add-ons/volsync/volsync_replicate.adoc
> +.. On the source cluster, modify the `replication_source.yaml` file by replacing the value of the `address` and `keySecret` in the `ReplicationSource` object with the values that you noted from the d
Is it worth keeping the sed commands? It's better to simply the topic if the user won't need them. If an advanced user might be interested, we can move the commands into an "Advanced config" topic and declutter the main procedure that way.

2023-03-29 15:05 UTC, oafischer commented
Made a round of edits, thanks for the review @tesshuflower. I think this needs a what's new entry as well so I'll add that soon. Left a couple of questions that we can address.

2023-03-29 17:53 UTC, tesshuflower commented on add-ons/volsync/volsync_replicate.adoc
> +Replace `destination-ns` with the namespace of the persistent volume claim where your destination is located.
Can we update to "Replace `destination-ns` with the namespace where your replication destination is located."

2023-03-29 17:55 UTC, tesshuflower commented on add-ons/volsync/volsync_replicate.adoc
> +Replace `my.host.com` with the host address that you copied from the `.status.rsyncTLS.address` field of the `ReplicationDestination` when you configured it.
Maybe we can just mention that there is an example of using sed commands below - i.e. what we tell them to do on line 191 we show how to do later on via cmds

2023-03-29 17:55 UTC, tesshuflower commented on add-ons/volsync/volsync_replicate.adoc
> +.. On the source cluster, modify the `replication_source.yaml` file by replacing the value of the `address` and `keySecret` in the `ReplicationSource` object with the values that you noted from the d
maybe we keep the cmds, as it's not really an advanced item, it's more like specific cmds to help users who are not as advanced.

2023-03-29 17:57 UTC, tesshuflower commented on add-ons/volsync/volsync_replicate.adoc
> +.. Run the following command to copy the name of the secret and the contents of the secret that are provided as the value of `.status.rsyncTLS.keySecret`.
Since we now have the optional section above on how to create their own secret - we may need to mention here that if they did that optional step, they just need to make sure the secret exists on both the source and destination clusters.

2023-03-29 18:01 UTC, tesshuflower commented on add-ons/volsync/volsync_replicate.adoc
> +Replace `destination-ns` with a name for the namespace that contains your destination persistent volume claim.
Can we change this to be consistent with other lines:

"Replace `destination-ns` with the namespace where your replication destination is located."

2023-03-29 18:02 UTC, tesshuflower commented on add-ons/volsync/volsync_replicate.adoc
> +*Note:* The source and destination must have access to the shared key for the TLS connection. You can find the key location in the `keySecret` field. If you do not provide a secret name in `.spec.rsy
I think this looks good - I just added a single comment about how we may need to reference this later on - as the steps later are assuming you didn't create the secret yourself

2023-03-29 18:32 UTC, oafischer commented
Thanks @tesshuflower, I think I addressed everything and added a what's new as well. Let me know if it looks good now.

2023-03-29 20:21 UTC, cadawson approved these changes
Looks good. A couple of suggestions. Thanks!

2023-03-29 20:21 UTC, cadawson commented on add-ons/volsync/volsync_replicate.adoc
> +See the following and examples to configure an Rsync-TLS replication from a persistent volume claim on the `source` cluster in the `source-ns` namespace to a persistent volume claim on a `destination
```suggestion
See the following information and examples to configure an Rsync-TLS replication from a persistent volume claim on the `source` cluster in the `source-ns` namespace to a persistent volume claim on a `destination` cluster in the `destination-ns` namespace. Replace the values where necessary:
```

2023-03-29 20:21 UTC, cadawson commented on add-ons/volsync/volsync_replicate.adoc
> +| `.status.rsyncTLS.keySecret` | Name of the secret containing the TLS key that authenticates the connection with the source cluster.
```suggestion
| `.status.rsyncTLS.address` 
| IP address of the destination cluster that is used to enable the source and destination clusters to communicate.

| `.status.rsyncTLS.keySecret` 
| Name of the secret containing the TLS key that authenticates the connection with the source cluster.
```

2023-03-30 19:41 UTC, tesshuflower requested changes
sorry, just a couple more nitpicks...

2023-03-30 19:41 UTC, tesshuflower commented on add-ons/volsync/volsync_replicate.adoc
> +Replace `mykeysecret` with the the name of the secret that you copied from the destination cluster to the source cluster (the value of `$KEYSECRET`.
Missing closing bracket )

2023-03-30 19:41 UTC, tesshuflower commented on add-ons/volsync/volsync_replicate.adoc
> +.. Run the following command to copy the name of the secret and the contents of the secret that are provided as the value of `.status.rsyncTLS.keySecret`. If you created your own secret, make sure th
I think this is still a bit confusing - We say "Run the following command to copy the name of the secret **and the contents of the secret** ..." But this is not true, the command only copies the name of the secret.

It's only later on down below where we have steps to export the secret as yaml (i.e. the contents of the secret) and save to /tmp/secret, edit it etc.

On more thing  is with the part about creating the secret on your own.  Something is still a bit awkward about this - If you create your own secret as we mention above then these steps are required at all - but instead, they need to set spec.rsyncRLS.keySecret in the replicationdestination spec instead.  It's maybe weird as we have steps to export the ADDRESS and KEYSECRET (name of the secret) to env vars, and then mention generally what to replace in the spec, and then later after that have specific steps on how to replace ADDRESS and KEYSECRET in the spec.

^ Not sure if that is clear, let me know if you'd rather discuss directly.

Perhaps instead we should have this example not mention creating your own secret at all.  And then only afterwards, we can mention or point to a section that has the instructions on creating your own secret and say if you do this, you ne

2023-03-30 19:48 UTC, oafischer commented on add-ons/volsync/volsync_replicate.adoc
> +.. Run the following command to copy the name of the secret and the contents of the secret that are provided as the value of `.status.rsyncTLS.keySecret`. If you created your own secret, make sure th
I think the main problem we are running into is that we want to cater to multiple solutions at the same time. Might be worth it to streamline by telling the user to either create their own secret, or telling them that the secret will be created for them and to just explain the rest of the procedure under that assumption. I assume it is preferred to have the secret be created for you? Would a typical user want to create their own secret? Or is that more of an advanced config thing?

2023-03-30 19:52 UTC, tesshuflower commented on add-ons/volsync/volsync_replicate.adoc
> +.. Run the following command to copy the name of the secret and the contents of the secret that are provided as the value of `.status.rsyncTLS.keySecret`. If you created your own secret, make sure th
I agree completely here - I think the easiest is to leave the instructions with letting VolSync create the secret for you.  And I do think it would be good to point to information if they want to create the secret themselves (but this could be afterwards or in some extra info at the bottom).  We can even link to the upstream docs for the user-created secret if that would be easier.

2023-03-30 20:24 UTC, oafischer commented on add-ons/volsync/volsync_replicate.adoc
> +.. Run the following command to copy the name of the secret and the contents of the secret that are provided as the value of `.status.rsyncTLS.keySecret`. If you created your own secret, make sure th
Sounds like a plan, we are currently overhauling parts of our doc to remove inline links and move them to an "Additional resources" topic at the end of every file. Sounds like it would be a good spot for a link to upstream or a separate topic if we create one ourselves. You can see an example here: https://github.com/stolostron/rhacm-docs/blob/2.8_stage/governance/config_policy_ctrl.adoc

Chris would probably follow that when working on the planned VolSync docs overhaul, but in the meantime, I'll implement just the let VolSync create it for you option.

2023-04-03 14:52 UTC, oafischer commented
Made more updates @tesshuflower, let me know if it looks good now.

2023-04-03 15:33 UTC, tesshuflower commented
> Made more updates @tesshuflower, let me know if it looks good now.

Great stuff - thanks a lot @oafischer !

2023-04-03 15:33 UTC, tesshuflower approved these changes
/lgtm

2023-04-03 19:08 UTC, tesshuflower commented on add-ons/volsync/volsync_replicate.adoc
> +- For additional information about the backup options, see https://volsync.readthedocs.io/en/latest/usage/restic/index.html#backup-options[Backup options] in the VolSync documentation.
sorry, I didn't notice this one before - should we say "For additional information about restic options" .... as it's pointing to a restic section of the docs

2023-04-03 19:16 UTC, oafischer commented on add-ons/volsync/volsync_replicate.adoc
> +- For additional information about the backup options, see https://volsync.readthedocs.io/en/latest/usage/restic/index.html#backup-options[Backup options] in the VolSync documentation.
I'll update it, also waiting for a QE review (new process we are trying to include in 2.8 for all new feature items in our docs).

2023-04-03 19:29 UTC, tesshuflower approved these changes
/lgtm

Thanks a lot Oliver!

2023-04-13 20:41 UTC, oafischer commented
Merging now as this is blocking work, recommend that QE look at the merged source code for their check.

2023-04-13 20:42 UTC, merged