Document the spec.copyPolicyMetadata Policy field
open-cluster-management/rhacm-docs pull request #4812
Opened 2023-03-14 17:09 UTC by mprahl

Related:
https://issues.redhat.com/browse/ACM-1690
https://issues.redhat.com/browse/ACM-4289

2023-03-14 17:20 UTC, dockerymick commented
Acknowledged! Will review soon, thanks Matt!

2023-03-14 18:44 UTC, dhaiducek reviewed
Minor wording suggestion

2023-03-14 18:44 UTC, dhaiducek commented on governance/manage_policy_def.adoc
> +For replicated policies to not show up at all in ArgoCD, you can set `spec.copyPolicyMetadata` to `false` on the {product-title-short} policy definition to prevent labels and annotations added by Arg
```suggestion
ArgoCD labels and annotates objects in order to track them. For replicated policies to not show up at all in ArgoCD, you can set `spec.copyPolicyMetadata` to `false` on the {product-title-short} policy definition to prevent these ArgoCD tracking labels and annotations from being copied to the replicated policy.
```

2023-03-14 18:55 UTC, dockerymick requested changes

2023-03-14 18:55 UTC, dockerymick commented on governance/manage_policy_def.adoc
> +ArgoCD labels and annotates objects in order to track them. For replicated policies to not show up at all in ArgoCD, you can set `spec.copyPolicyMetadata` to `false` on the {product-title-short} poli
I recommend the following minor update:

There are labels and annotations used by ArgoCD to track objects. For replicated policies to not show up at all in ArgoCD, you can set `spec.copyPolicyMetadata` to `false` on the {product-title-short} policy definition to prevent these ArgoCD tracking labels and annotations from being copied to the replicated policy.

2023-03-15 03:04 UTC, dockerymick approved these changes
Made a couple of changes. Thanks for starting this PR! This looks good to me!

2023-03-15 12:03 UTC, mprahl commented
@dockerymick and @dhaiducek thanks for the reviews!

2023-03-15 13:55 UTC, merged

2023-03-15 14:03 UTC, mprahl commented
@dockerymick could you please backport this to 2.7?

2023-03-15 14:29 UTC, dockerymick commented
@mprahl absolutely!