[ACM-4111]: Various updates to managing clusters on bare metal
open-cluster-management/rhacm-docs pull request #4857
Opened 2023-03-22 19:47 UTC by lahinson

Related Jira: https://issues.redhat.com/browse/ACM-4111

Various updates and improvements to the "Managing hosted control plane clusters on bare metal (Technology Preview)" docs.

2023-03-28 14:44 UTC, lahinson commented
Hi @avishayt and @rokej - When you can, PTAL at these minor updates to the bare metal docs and let me know if anything needs to change before I move forward with merging. Thank you!

2023-03-28 19:12 UTC, rokej reviewed
Looks good to me. Thank you @lahinson

2023-03-28 19:13 UTC, rokej commented
It looks good to me but I would like @avishayt to review as well so I am not adding LGTM.

2023-03-29 10:22 UTC, avishayt commented
/lgtm

2023-03-29 10:22 UTC, avishayt commented
@rokej Please LGTM, I am not listed as a collaborator

2023-03-29 11:52 UTC, rokej commented
/lgtm

2023-03-29 12:16 UTC, lahinson commented
Thanks, Roke and Avishay!

2023-03-29 14:04 UTC, dockerymick requested changes
Thanks for the changes Laura! Left some comments and suggestions

2023-03-29 14:04 UTC, dockerymick commented on clusters/hosted_control_planes/managing_hosted_bm.adoc
> +. If you check the nodes by entering the following command, you can see a new node in the cluster. In this example, `ocp-worker-0` is added to the cluster.
```suggestion
. If you check the nodes by entering the following command, the new node is displayed in the output. In this example, `ocp-worker-0` is added to the cluster.
```

2023-03-29 14:04 UTC, dockerymick commented on clusters/hosted_control_planes/managing_hosted_bm.adoc
> +. Verify that the remaining Agents are deployed by entering the following command. In this example, the spare agent, `d9198891-39f4-4930-a679-65fb142b108b`, is provisioned.
```suggestion
. Verify that the remaining Agents are deployed by entering the following command. In this example, the spare agent, `d9198891-39f4-4930-a679-65fb142b108b`, is provisioned:
```

2023-03-29 14:04 UTC, dockerymick commented on clusters/hosted_control_planes/managing_hosted_bm.adoc
> +.. Reach the {ocp-short} console by entering the following command:
```suggestion
.. Enter the following command to reach the {ocp-short} console:
```

2023-03-29 14:04 UTC, dockerymick commented on clusters/hosted_control_planes/managing_hosted_bm.adoc
> +. Set up https://docs.openshift.com/container-platform/4.13/networking/metallb/about-metallb.html[MetalLB] so that when you create a service of the LoadBalancer type, MetalLB adds an external IP addr
Just a reminder that we are reducing the number of inline links by moving links at the end of the file, in the _Additional resources_ section. I can tag team on this if you like, i don't mind! I would make updates after you make changes to avoid merge conflicts

```suggestion
. Set up link:https://docs.openshift.com/container-platform/4.13/networking/metallb/about-metallb.html[MetalLB] so that when you create a service of the `LoadBalancer` type, MetalLB adds an external IP address for the service.
```

Monospaced bc it was mentioned as a resource parameter value. Also promoting consistent link syntax ([Types of link referencing](https://stolostron.github.io/rhacm-docs/wr_linking))

2023-03-29 14:04 UTC, dockerymick commented on clusters/hosted_control_planes/managing_hosted_bm.adoc
> +----
In line 377, will you monospace "clusterversion" 

`clusterversion`

2023-03-29 14:04 UTC, dockerymick commented on clusters/hosted_control_planes/managing_hosted_bm.adoc
> +An InfraEnv is a environment where hosts that are starting the live ISO can join as Agents. In this case, the Agents are created in the same namespace as your hosted control plane.
```suggestion
An `InfraEnv` is a environment where hosts that are starting the live ISO can join as agents. In this case, the agents are created in the same namespace as your hosted control plane.
```

2023-03-29 14:04 UTC, dockerymick commented on clusters/hosted_control_planes/managing_hosted_bm.adoc
> +. To create an InfraEnv, enter the following commands:
```suggestion
. To create an `InfraEnv`, enter the following commands:
```

2023-03-29 15:15 UTC, lahinson commented on clusters/hosted_control_planes/managing_hosted_bm.adoc
> +. If you check the nodes by entering the following command, you can see a new node in the cluster. In this example, `ocp-worker-0` is added to the cluster.
Good suggestion!

2023-03-29 15:17 UTC, lahinson commented on clusters/hosted_control_planes/managing_hosted_bm.adoc
> +. Set up https://docs.openshift.com/container-platform/4.13/networking/metallb/about-metallb.html[MetalLB] so that when you create a service of the LoadBalancer type, MetalLB adds an external IP addr
Thanks! I can move the link.

2023-03-29 15:25 UTC, lahinson commented
Thanks so much for the review, @dockerymick! I incorporated your suggestions and made a couple of extra changes to keep the wording consistent with the changes (i.e., changing the capitalization of "Agent" to "agent" throughout).

2023-03-29 16:55 UTC, dockerymick commented
@lahinson Thanks for the updates!

2023-03-29 17:02 UTC, dockerymick approved these changes
Added a couple of more suggestions links. Otherwise, the updates look good to me!

2023-03-29 17:02 UTC, dockerymick commented on clusters/hosted_control_planes/managing_hosted_bm.adoc
> +* https://docs.openshift.com/container-platform/4.13/networking/metallb/about-metallb.html[MetalLB]
```suggestion
* Read the link:https://docs.openshift.com/container-platform/4.13/networking/metallb/about-metallb.html[{ocp-short} MetalLB documentation] for more details.
* Refer to the link:https://github.com/metal3-io/baremetal-operator/blob/main/docs/api.md#rootdevicehints[_rootDeviceHints_ section] for more details.
```

2023-03-29 17:02 UTC, dockerymick commented on clusters/hosted_control_planes/managing_hosted_bm.adoc
> +If you want to manually specify the installation disk, you can use the https://github.com/metal3-io/baremetal-operator/blob/main/docs/api.md#rootdevicehints[rootDeviceHints] in the BMH Spec. If rootD
```suggestion
If you want to manually specify the installation disk, you can use the `rootDeviceHints` in the BMH specification. If `rootDeviceHints` are not provided, the agent picks the installation disk that better suits the installation requirements.
```

2023-03-29 17:02 UTC, dockerymick commented on clusters/hosted_control_planes/managing_hosted_bm.adoc
> +. If you check the nodes by entering the following command, the new node is displayed in the output. In this example, `ocp-worker-0` is added to the cluster.
```suggestion
. If you check the nodes by entering the following command, the new node is displayed in the output. In this example, `ocp-worker-0` is added to the cluster:
```

2023-03-29 17:28 UTC, lahinson commented
Thanks again, @dockerymick! I incorporated your latest suggestions.

2023-03-29 17:39 UTC, lahinson commented
@dockerymick Do you need to add the lgtm label again before I merge?

2023-03-29 18:33 UTC, dockerymick commented
@lahinson I believe you are good to merge. i approved it

2023-03-29 18:45 UTC, merged