Making 'Configuring on AWS' book parallel with 'Configuring on bare metal' book
open-cluster-management/rhacm-docs pull request #4863
Opened 2023-03-27 17:55 UTC by lahinson

I don't have a Jira for this one. I noticed on 2.8 staging that in the hosted control planes book, the "Configuring on bare metal" info was in two places (1.7.1.2 and 1.7.3), and the "Configuring on AWS" book needed to be moved up one level.

2023-03-27 17:56 UTC, lahinson commented
I think at least part of this change will need to be backported to 2.7 prod, because the "Configuring on AWS" book needs to be moved up one level there.

2023-04-03 15:03 UTC, dockerymick requested changes
Made a couple of suggestions.

2023-04-03 15:03 UTC, dockerymick commented on clusters/hosted_control_planes/configure_hosted_aws.adoc
> +== Prerequisites
When there are more than two sections, we add a TOC within the file so that the user is aware of upcoming sections. I recommend adding that. I also noticed that there wasn't an additional resources section at the end of the file.

2023-04-03 15:05 UTC, lahinson commented on clusters/hosted_control_planes/configure_hosted_aws.adoc
> +== Prerequisites
Thanks, Mikela! Good suggestions.

2023-04-03 15:39 UTC, dockerymick approved these changes
Thanks for incorporating my suggestions! I also recommend moving the inline links to the Additional resources section. Let me know if you have questions or other thoughts

2023-04-03 15:39 UTC, dockerymick commented on clusters/hosted_control_planes/configure_hosted_aws.adoc
> +== Additional resources
After moving the resources to the end, I recommend that you italicize and remove the links for the page references throughout the doc.  



```suggestion
== Additional resources

* Refer link:https://hypershift-docs.netlify.app/getting-started/[Getting started] in the HyperShift documentation for more information about the secret.
* See link:https://hypershift-docs.netlify.app/how-to/aws/external-dns/[External DNS] in the HyperShift documentation for more information.
* See link:https://hypershift-docs.netlify.app/how-to/aws/deploy-aws-private-clusters/[Deploying AWS private clusters] in the HyperShift documentation for more information.
* You can now deploy the SR-IOV Operator. See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html/networking/hardware-networks#sriov-operator-hosted-control-planes_configuring-sriov-operator[Deploying the SR-IOV Operator for hosted control planes] to learn more about deploying the SR-IOV Operator.
```

2023-04-03 15:59 UTC, lahinson commented on clusters/hosted_control_planes/configure_hosted_aws.adoc
> +== Additional resources
Done!

2023-04-03 16:21 UTC, merged