acm-4374 update import instructions 2.8
open-cluster-management/rhacm-docs pull request #4905
Opened 2023-04-06 20:45 UTC by cadawson

2023-04-06 20:57 UTC, cadawson commented
Hi @KevinFCormier . Please take a look at this PR. I made some changes to the contents a little and added your comments. I had a question about the OCP-Dedicated procedure. Is that not required anymore? I remember it used to be different requirements for that. Thanks!

2023-04-13 17:51 UTC, KevinFCormier requested changes
Thanks for the updates. I left a few additional comments.

2023-04-13 17:51 UTC, KevinFCormier commented on clusters/cluster_lifecycle/import_gui.adoc
> +.. Add the cluster and automation information, and select *Generate command* and *Copy command* to copy the generated command and token to the clipboard.
I think this sentence is a little over-simplified. It might not be apparent that there are multiple screens in the wizard, and that there is a redirect after you click *Generate command* before you will see the *Copy command* button.

Could we say something like:
> Fill out the information in the form, leaving *Import mode* set to *Run import commands manually*. After you click *Generate command*, you will be redirected to the cluster overview page. Click *Copy command* to copy the generated command to the clipboard.

2023-04-13 17:51 UTC, KevinFCormier commented on clusters/cluster_lifecycle/import_gui.adoc
> +<1> Replace `cluster-name` with the name of the managed cluster.
Is there a precedent for this notation? It's not clear to me that the footnote reference is not part of the command. 

Also, it says to replace `cluster-name` suggesting that I leave the `<` and `>` in place, which would not be correct.

2023-04-14 19:06 UTC, KevinFCormier approved these changes

2023-04-14 20:30 UTC, cadawson commented
Thanks for the review and feedback, @KevinFCormier.

2023-04-14 20:59 UTC, oafischer commented on clusters/cluster_lifecycle/import_gui.adoc
>  . Edit the managed cluster entry for the cluster that you are importing by running the following command:
For single line commands Brandi recommends integrating the replacement prompt into the sentence. We can use the numbers for YAML or multiple replacements on a command.

2023-04-14 21:00 UTC, oafischer approved these changes
Looks good, one comment for consideration.

2023-04-18 18:53 UTC, merged