[ACM-4770]: Porting external DNS docs from upstream to ACM docs
open-cluster-management/rhacm-docs pull request #4912
Opened 2023-04-07 17:14 UTC by lahinson

Related Jira: https://issues.redhat.com/browse/ACM-4770

This PR removes one of the links to the upstream docs and ports over the relevant info about external DNS to the hosted control planes docs.

2023-04-07 19:39 UTC, lahinson commented
Hi @rokej - When you can, please take a look at this PR, which ports the external DNS docs from the upstream HyperShift docs to the official docs in ACM. Thank you!

2023-04-21 19:16 UTC, rokej commented on clusters/hosted_control_planes/configure_hosted_aws.adoc
> +External DNS is useful for setups with public endpoints, such as `Public` or `PublicandPrivate`. For a private setup, all endpoints must be accessible through `.hypershift.local`, which contains the
PublicandPrivate  --> PublicAndPrivate

2023-04-21 19:16 UTC, rokej commented on clusters/hosted_control_planes/configure_hosted_aws.adoc
> +The input for the `hostedCluster.spec.dns` dictates the Ingress for workloads within the hosted cluster. The input for `hostedCluster.spec.services.routePublishingStrategy.hostname` dictates the Ingr
I think `hostedCluster.spec.services.routePublishingStrategy.hostname` should be `hostedCluster.spec.services.servicePublishingStrategy.route.hostname`.

2023-04-21 19:16 UTC, rokej commented on clusters/hosted_control_planes/configure_hosted_aws.adoc
> +You can create the public DNS hosted zone in the AWS Route 53 management console:
You can create the public DNS hosted zone to be used as the external DNS domain-filter  in the AWS Route 53 management console:

2023-04-21 19:16 UTC, rokej commented on clusters/hosted_control_planes/configure_hosted_aws.adoc
> +. Enter the following commands:
Remove this step and the `hypershift install` command sample

2023-04-21 19:16 UTC, rokej commented
@enxebre could you please review as well? Thanks.

2023-04-21 19:37 UTC, lahinson commented on clusters/hosted_control_planes/configure_hosted_aws.adoc
> +External DNS is useful for setups with public endpoints, such as `Public` or `PublicandPrivate`. For a private setup, all endpoints must be accessible through `.hypershift.local`, which contains the
Good catch! Fixing now.

2023-04-21 19:38 UTC, lahinson commented on clusters/hosted_control_planes/configure_hosted_aws.adoc
> +The input for the `hostedCluster.spec.dns` dictates the Ingress for workloads within the hosted cluster. The input for `hostedCluster.spec.services.routePublishingStrategy.hostname` dictates the Ingr
Fixed

2023-04-21 19:41 UTC, lahinson commented on clusters/hosted_control_planes/configure_hosted_aws.adoc
> +. Enter the following commands:
done

2023-04-21 19:42 UTC, lahinson commented
Thanks so much for your review, @rokej! I incorporated your feedback.

2023-04-21 23:18 UTC, rokej commented
/lgtm

2023-04-21 23:18 UTC, rokej approved these changes
Thank you

2023-04-25 07:42 UTC, enxebre commented on clusters/hosted_control_planes/configure_hosted_aws.adoc
> +External DNS is useful for setups with public endpoints, such as `Public` or `PublicAndPrivate`. For a private setup, all endpoints must be accessible through `.hypershift.local`, which contains the
this changed a bit recently, even for private we create the public dns record in AWS cc @sjenning to corroborate

2023-05-08 15:46 UTC, sjenning commented on clusters/hosted_control_planes/configure_hosted_aws.adoc
> +External DNS is useful for setups with public endpoints, such as `Public` or `PublicAndPrivate`. For a private setup, all endpoints must be accessible through `.hypershift.local`, which contains the
Yes, it is true that for `Private` clusters, we do create a DNS record for `Services` that  have a publishing type of `Route` and a `route.hostname` set.  In the case of `Private`, the DNS record points to a private IP of a VPC Endpoint in the customer VPC.

2023-05-08 15:48 UTC, sjenning commented on clusters/hosted_control_planes/configure_hosted_aws.adoc
> +External DNS is useful for setups with public endpoints, such as `Public` or `PublicAndPrivate`. For a private setup, all endpoints must be accessible through `.hypershift.local`, which contains the
This is the PR that did that btw https://github.com/openshift/hypershift/pull/2286

Public DNS registration of private endpoints is only supported on the `APIServer` and `OAuth` services.

2023-05-08 16:16 UTC, lahinson commented on clusters/hosted_control_planes/configure_hosted_aws.adoc
> +External DNS is useful for setups with public endpoints, such as `Public` or `PublicAndPrivate`. For a private setup, all endpoints must be accessible through `.hypershift.local`, which contains the
Thanks @sjenning! Is this revision of line 119 accurate?

>External DNS is useful for setups with public endpoints, such as `Public` or `PublicAndPrivate`. For a private setup, the DNS record points to a private IP of a Virtual Private Cloud (VPC) endpoint in your VPC. Public DNS registration of private endpoints is supported only on the `APIServer` and `OAuth` services.

2023-05-08 16:37 UTC, sjenning commented on clusters/hosted_control_planes/configure_hosted_aws.adoc
> +External DNS is useful for setups with public endpoints, such as `Public` or `PublicAndPrivate`. For a private setup, all endpoints must be accessible through `.hypershift.local`, which contains the
How about this?
> External DNS creates name records for hosted cluster `Services` that specify a publishing type of `LoadBalanacer` or `Route` and provide a `hostname` for that publishing type. For hosted clusters with `Private` or `PublicAndPrivate` endpoint access types, only the `APIServer` and `OAuth` services support hostnames.  For `Private` hosted clusters, the DNS record resolves to a private IP of a Virtual Private Cloud (VPC) Endpoint in your VPC.

2023-05-08 18:33 UTC, swopebe commented on clusters/hosted_control_planes/configure_hosted_aws.adoc
> +When a DNS indirection layer is on top of the `LoadBalancer` and `Route` publishing types, a managed service operator can publish all public hosted cluster services by using a service-level domain. T
Can we say "is layered on the load balancer" here to eliminate "top"?

2023-05-08 18:34 UTC, swopebe commented on clusters/hosted_control_planes/configure_hosted_aws.adoc
> +
There is something in the code graying out the content here.

2023-05-08 18:35 UTC, swopebe commented on clusters/hosted_control_planes/configure_hosted_aws.adoc
> +
May be the ... in the YAML, which we don't have much in our doc, I don't think.

2023-05-08 18:36 UTC, swopebe commented on clusters/hosted_control_planes/configure_hosted_aws.adoc
> +
This whole section is doing the same thing.

2023-05-08 18:36 UTC, swopebe commented on clusters/hosted_control_planes/configure_hosted_aws.adoc
Same here

2023-05-08 19:08 UTC, swopebe requested changes

2023-05-08 19:08 UTC, swopebe commented on clusters/hosted_control_planes/configure_hosted_aws.adoc
>  * For more information about the AWS credential secret, see link:https://hypershift-docs.netlify.app/how-to/aws/deploy-aws-private-clusters/[Deploying AWS private clusters] in the HyperShift document
can we build this section like: https://github.com/stolostron/rhacm-docs/blob/2.8_stage/business_continuity/volsync/volsync_replicate.adoc#additional-resources

2023-05-09 13:13 UTC, lahinson commented on clusters/hosted_control_planes/configure_hosted_aws.adoc
> +When a DNS indirection layer is on top of the `LoadBalancer` and `Route` publishing types, a managed service operator can publish all public hosted cluster services by using a service-level domain. T
Sure! I'll update that wording.

2023-05-09 13:14 UTC, lahinson commented on clusters/hosted_control_planes/configure_hosted_aws.adoc
> +
I'll take a look

2023-05-09 13:19 UTC, lahinson commented on clusters/hosted_control_planes/configure_hosted_aws.adoc
>  * For more information about the AWS credential secret, see link:https://hypershift-docs.netlify.app/how-to/aws/deploy-aws-private-clusters/[Deploying AWS private clusters] in the HyperShift document
Sure. So you mean that you want one main lead-in sentence and then the list of resources?

2023-05-09 13:28 UTC, lahinson commented on clusters/hosted_control_planes/configure_hosted_aws.adoc
> +
hmm...removing the ellipsis doesn't seem to make a difference. I'll keep playing with it.

2023-05-09 13:41 UTC, lahinson commented on clusters/hosted_control_planes/configure_hosted_aws.adoc
fixed!

2023-05-09 13:42 UTC, lahinson commented on clusters/hosted_control_planes/configure_hosted_aws.adoc
> +
I figured it out! I had to remove the + from lines 220 and 222.

2023-05-09 13:43 UTC, lahinson commented
@swopebe Thanks so much for your review! I think I've incorporated all of your feedback. Let me know what you think when you can.

2023-05-16 14:06 UTC, lahinson commented
@swopebe When you can, PTAL and let me know if the latest changes I made to this PR look okay. I appreciate it!

2023-06-05 17:09 UTC, swopebe approved these changes
thanks for pulling me in!

2023-06-05 17:15 UTC, merged