https://issues.redhat.com/browse/ACM-4062 dr4hub arch
open-cluster-management/rhacm-docs pull request #4957
Opened 2023-04-20 13:32 UTC by oafischer

Need to fix dr4hub links in known issues still.

2023-04-20 13:37 UTC, swopebe commented on backup_restore/backup_activation.adoc
> +
If this is a task, and it seems it is, we may want to indicate that with a gerund as we are trying to do throughout the content.

2023-04-20 13:39 UTC, swopebe commented on backup_restore/backup_hub_config.adoc
> += Hub cluster configuration
This title could be a title for any feature within RHACM or OCP so I would try a more specific approach here:
Configuring active or passive hub cluster (remember the gerund)

2023-04-20 13:39 UTC, swopebe commented on backup_restore/backup_install.adoc
> += Installing the backup and restore operator
like this ^^^

2023-04-20 13:40 UTC, swopebe commented on backup_restore/backup_msa.adoc
> +
Connecting clusters automatically

2023-04-20 13:41 UTC, swopebe commented on backup_restore/backup_schedule.adoc
> +
see these are gerunds and for the most part on titles, sections, we want to try to be parallel unless we are dealing with a concept or reference.

2023-04-20 13:42 UTC, swopebe requested changes
Couple changes to titles--I didn't review content. 

I see you have an intro but didn't see it here....that will link to all this I assume?

Thanks!

2023-04-20 13:45 UTC, oafischer commented
Implemented the suggestions, thanks for the quick review. Yes, the intro topic has all the new structure with links. I think you need to click "load diff" to see it.

2023-04-20 13:52 UTC, swopebe approved these changes

2023-04-21 16:01 UTC, birsanv approved these changes
lgtm

2023-04-21 16:15 UTC, merged