[ACM-4609]: adding AWS and IAM permissions docs
open-cluster-management/rhacm-docs pull request #4979
Opened 2023-04-24 19:03 UTC by lahinson

Related Jira: https://issues.redhat.com/browse/ACM-4609

Porting over upstream docs about AWS infrastructure requirements and IAM permissions.

2023-04-26 09:53 UTC, jparrill reviewed
Looks good so far, added some clarifications.

2023-04-26 09:53 UTC, jparrill commented on clusters/hosted_control_planes/managing_hosted_aws.adoc
> +// Do we need to compare self-managed and managed? I'm thinking that customers who will access this documentation will be using self-managed and won't need to worry about comparing managed vs. self-m
Depend on the hierarchy doc sections you have, could make sense if the Management Cluster is located in AWS as we have our RootCI Openshift. Most of the customers will understand a "self-managed" openshift as a Bare Metal deployment (from my PoV).

2023-04-26 09:53 UTC, jparrill commented on clusters/hosted_control_planes/managing_hosted_aws.adoc
> +When your infrastructure is prerequired and unmanaged for the HyperShift Operator in an AWS account, the following infrastructure is required for a management cluster AWS account:
When your infrastructure is prerequired and unmanaged:

- Prerequired: Hypershift requires some AWS infra to properly work.
- Unmanaged: Not any operator/controller will create this infra for you.

The next inner sections will have the details about who creates the AWS resources.

2023-04-26 09:53 UTC, jparrill commented on clusters/hosted_control_planes/managing_hosted_aws.adoc
> +//Should this be Kube-OVN?
nope, as an example you can see this object from a real HostedCluster: `clusters-jz-test/datadir-ovnkube-master-0`

2023-04-26 09:53 UTC, jparrill commented on clusters/hosted_control_planes/managing_hosted_aws.adoc
> +//Should this be Kube-OVN?
Same comment as before

2023-04-26 09:53 UTC, jparrill commented on clusters/hosted_control_planes/managing_hosted_aws.adoc
> +  - key: kubernetes.io/cluster/cewong-dev-bz4j5
`cewong-dev` is the cluster name, so make sure if you modify this name by hand, to make sense with the rest of the references in the doc.

2023-04-26 15:13 UTC, lahinson commented on clusters/hosted_control_planes/managing_hosted_aws.adoc
> +// Do we need to compare self-managed and managed? I'm thinking that customers who will access this documentation will be using self-managed and won't need to worry about comparing managed vs. self-m
OK -- thanks for the clarification! I'll leave the text as is.

2023-04-26 15:14 UTC, lahinson commented on clusters/hosted_control_planes/managing_hosted_aws.adoc
> +//Should this be Kube-OVN?
Thanks for confirming! I had seen Kube-OVN before, but this is my first time seeing OVN-Kube.

2023-04-26 15:16 UTC, lahinson commented on clusters/hosted_control_planes/managing_hosted_aws.adoc
> +  - key: kubernetes.io/cluster/cewong-dev-bz4j5
@jparrill Will do. Would it make sense to replace `cewong-dev` with something generic like `example-cluster`?

2023-04-26 15:22 UTC, lahinson commented on clusters/hosted_control_planes/managing_hosted_aws.adoc
> +When your infrastructure is prerequired and unmanaged for the HyperShift Operator in an AWS account, the following infrastructure is required for a management cluster AWS account:
Thanks @jparrill! I updated the text. Please see lines 221-230 and let me know what you think.

2023-04-26 15:26 UTC, jparrill commented on clusters/hosted_control_planes/managing_hosted_aws.adoc
> +  - key: kubernetes.io/cluster/cewong-dev-bz4j5
yep, make sense

2023-04-26 15:27 UTC, jparrill commented on clusters/hosted_control_planes/managing_hosted_aws.adoc
> +When your infrastructure is prerequired and unmanaged for the HyperShift Operator in an AWS account, the following infrastructure is required for a management cluster AWS account:
Looks good so far :)

2023-04-26 15:27 UTC, jparrill commented
/lgtm

2023-04-26 19:17 UTC, swopebe commented on clusters/hosted_control_planes/managing_hosted_aws.adoc
> +
I would just reword to elimininate the who

2023-04-26 19:18 UTC, swopebe commented on clusters/hosted_control_planes/managing_hosted_aws.adoc
> +            "Effect": "Allow",
the astericks here is causing bold, since this is an example, maybe it can something else?

2023-04-26 19:18 UTC, swopebe commented on clusters/hosted_control_planes/managing_hosted_aws.adoc
> +}
same

2023-04-26 19:20 UTC, swopebe commented on clusters/hosted_control_planes/managing_hosted_aws.adoc
> +
I am going to ask for future, if these samples are in the open repo, do we have to have them in doc? I will raise this in scrum.

2023-04-26 19:22 UTC, swopebe commented on clusters/hosted_control_planes/managing_hosted_aws.adoc
> +----
Can we just say:

From the hosted cluster 

From the hosted cluster view

?

2023-04-26 19:23 UTC, swopebe commented on clusters/hosted_control_planes/managing_hosted_aws.adoc
> +The hosted cluster receives the ARN roles as input and the consumer creates an AWS permission configuration for each component. As a result, the component can authenticate through STS and preconfigur
Is consumer "you"? (I have never really used consumer, so asking)

2023-04-26 19:24 UTC, swopebe commented on clusters/hosted_control_planes/managing_hosted_aws.adoc
> +In the context of hosted control planes, the consumer, such as the command line interface or OpenShift Cluster Manager, is responsible to create the Amazon Resource Name (ARN) roles. Hosted control p
I am confused by use of the consumer.

2023-04-26 19:32 UTC, swopebe requested changes
Was it considered that this should maybe be in a single file (due to the length and numerous sections)? 

Couple things: "The consumer" is a bit confusing, some anthropomorphic language (I pointed out a couple spots, there may be more), and the bold changes.

2023-04-27 14:16 UTC, lahinson commented on clusters/hosted_control_planes/managing_hosted_aws.adoc
> +
I will change to `The following sections contain details about the creation of the AWS resources.`

2023-04-27 14:18 UTC, lahinson commented on clusters/hosted_control_planes/managing_hosted_aws.adoc
> +----
I will change to `from the hosted cluster`

2023-04-27 14:19 UTC, lahinson commented on clusters/hosted_control_planes/managing_hosted_aws.adoc
> +The hosted cluster receives the ARN roles as input and the consumer creates an AWS permission configuration for each component. As a result, the component can authenticate through STS and preconfigur
I don't think that the user is the consumer in this case. @jparrill Can you confirm?

2023-04-27 14:20 UTC, lahinson commented on clusters/hosted_control_planes/managing_hosted_aws.adoc
> +In the context of hosted control planes, the consumer, such as the command line interface or OpenShift Cluster Manager, is responsible to create the Amazon Resource Name (ARN) roles. Hosted control p
@jparrill Can you provide more details that I can use to better explain what the consumer is?

2023-04-27 14:21 UTC, lahinson commented on clusters/hosted_control_planes/managing_hosted_aws.adoc
> +            "Effect": "Allow",
@jparrill Several of the code examples contain this line, which is causing formatting issues because asciidoc thinks that the single asterisk `*` is actually a `<b>` tag. Can you suggest something else that we can replace the `*` with?

2023-04-27 14:50 UTC, jparrill commented on clusters/hosted_control_planes/managing_hosted_aws.adoc
> +            "Effect": "Allow",
It could be escaped? `"Resource": "\*"`

2023-04-27 14:50 UTC, jparrill commented on clusters/hosted_control_planes/managing_hosted_aws.adoc
> +
no objections

2023-04-27 14:53 UTC, jparrill commented on clusters/hosted_control_planes/managing_hosted_aws.adoc
> +The hosted cluster receives the ARN roles as input and the consumer creates an AWS permission configuration for each component. As a result, the component can authenticate through STS and preconfigur
Nope, it's an automated process to generate the permissions files using the ARN Roles.

2023-04-27 14:58 UTC, jparrill commented on clusters/hosted_control_planes/managing_hosted_aws.adoc
> +In the context of hosted control planes, the consumer, such as the command line interface or OpenShift Cluster Manager, is responsible to create the Amazon Resource Name (ARN) roles. Hosted control p
The same as I commented above, the consumer in this case could be the CLI or the Openshift Cluster Manager. With a series of arguments you're passing to the CLI it will try to create the ARN roles in AWS, that later will be used for the proper working of the HC.

consumer == operator or golang binary

2023-04-27 15:05 UTC, lahinson commented on clusters/hosted_control_planes/managing_hosted_aws.adoc
> +In the context of hosted control planes, the consumer, such as the command line interface or OpenShift Cluster Manager, is responsible to create the Amazon Resource Name (ARN) roles. Hosted control p
Thanks @jparrill!

@swopebe WDYT about this revision?
>In the context of hosted control planes, the consumer is responsible to create the Amazon Resource Name (ARN) roles. The _consumer_ is an automated process to generate the permissions files. The consumer might be the command line interface or OpenShift Cluster Manager.

2023-04-27 15:08 UTC, lahinson commented on clusters/hosted_control_planes/managing_hosted_aws.adoc
> +            "Effect": "Allow",
That seemed to fix the problem with the bold formatting. As long as `"Resource": "\*" won't create problems from a technical accuracy standpoint, I think we can use it.

2023-04-27 15:09 UTC, lahinson commented
@swopebe Thanks so much for your review! I incorporated your suggestions and had the engineer take another look and provide more input. As for whether this should be moved to a separate file, that was not discussed. I'm happy to move it to its own file if that aligns better with the conventions of the ACM team.

2023-04-27 18:36 UTC, lahinson commented
@swopebe I moved the AWS permissions doc to its own file. Let me know what you think when you can. Thanks!

2023-04-28 16:35 UTC, swopebe approved these changes

2023-04-28 18:31 UTC, merged