Add deprecation note for Gatekeeper in generator
open-cluster-management/rhacm-docs pull request #4986
Opened 2023-04-25 19:19 UTC by dhaiducek

Also adds deprecation notes for Placement in the generator.

ref: https://issues.redhat.com/browse/ACM-5160

2023-04-26 13:05 UTC, mprahl approved these changes

2023-04-28 19:33 UTC, dockerymick requested changes

2023-04-28 19:33 UTC, dockerymick commented on governance/policy_generator.adoc
>  | `policyDefaults.informGatekeeperPolicies`
I see I am using "configuration policy" throughout the doc. If we refer to the `kind` value of the policy, it is monospaced. The plus sign is added 
```suggestion
| `policyDefaults.informGatekeeperPolicies` (Deprecated)
| Optional
| Set `informGatekeeperPolicies` to false to use Gatekeeper manifests directly without defining it in a configuration policy.

When the policy references a violated Gatekeeper policy manifest, an additional configuration policy is generated in order to receive policy violations in {product-title-short}. The default value is `true`.

```

2023-04-28 19:33 UTC, dockerymick commented on governance/policy_generator.adoc
>  | `policyDefaults.placement.clusterSelector`
```suggestion
| `policyDefaults.placement.clusterSelector` (Deprecated)
| Optional
| `PlacementRule` is deprecated. Use `labelSelector` instead to generate a placement. 

Specify a placement by defining a cluster selector using either `key:value` or by providing `matchExpressions`, `matchLabels`, or both, with appropriate values. See `placementRulePath` to specify an existing file.

```

2023-04-28 19:33 UTC, dockerymick commented on governance/policy_generator.adoc
>  | `policyDefaults.placement.placementRuleName`
```suggestion
| `policyDefaults.placement.placementRuleName` (Deprecated)
| Optional
| `PlacementRule` is deprecated. Alternatively, use `placementName` to specify a placement.

To use an existing placement rule on the cluster, specify the name for this parameter. A `PlacementRule` is not created, but a `PlacementBinding` binds the policy to the existing `PlacementRule`.

```

2023-04-28 19:33 UTC, dockerymick commented on governance/policy_generator.adoc
>  | `policyDefaults.placement.placementRulePath`
```suggestion
| `policyDefaults.placement.placementRulePath` (Deprecated)
| Optional
| `PlacementRule` is deprecated. Alternatively, use `placementPath` to specify a placement.

To reuse an existing placement rule, specify the path relative to the location of the `kustomization.yaml` file. If provided, this placement rule is used by all policies by default. See `_clusterSelector_` to generate a new `PlacementRule`.

```

2023-05-01 17:12 UTC, dockerymick commented
@dhaiducek i made some updates to the PR. When you have an opportunity, will you review the PR? If you are fine with the updates, I will approve and merge

2023-05-01 21:56 UTC, dhaiducek reviewed
Thanks for the updates! I have one minor update that might help clarify.

2023-05-01 21:56 UTC, dhaiducek commented on governance/policy_generator.adoc
> +| `PlacementRule` is deprecated. Use `labelSelector` instead to generate a placement. Specify a placement by defining a cluster selector using either `key:value` or by providing `matchExpressions`, `
```suggestion
| `PlacementRule` is deprecated. Use `labelSelector` instead to generate a placement. Specify a placement rule by defining a cluster selector using either `key:value` or by providing `matchExpressions`, `matchLabels`, or both, with appropriate values. See `placementRulePath` to specify an existing file.
```

2023-05-02 12:52 UTC, dockerymick commented
@dhaiducek accepted your suggestion. Approving this PR and merging

2023-05-02 12:53 UTC, dockerymick approved these changes
Looks great! Thanks for the changes !

2023-05-02 12:53 UTC, merged