Search metrics 2.8
open-cluster-management/rhacm-docs pull request #4987
Opened 2023-04-25 20:47 UTC by dockerymick

https://issues.redhat.com/browse/ACM-4702

2023-04-26 15:31 UTC, cadawson requested changes
A couple of small things to look at. Otherwise looks fine. Thanks!

2023-04-26 15:31 UTC, cadawson commented on observability/search_intro.adoc
> +- `search-indexer` - Receives resource metadata from the collectors and writes to PostgreSQL database. The `search-indexer` also watches resources in the hub cluster to keep track of active managed c
Should this remain a colon to be consistent with the previous item? `search-indexer`: ?

2023-04-26 15:31 UTC, cadawson commented on observability/search_intro.adoc
> +- `search-postgres` - Stores collected data from all managed clusters in an instance of the PostgreSQL database.
Same question about the colon here.

2023-04-26 15:31 UTC, cadawson commented on release_notes/whats_new.adoc
> +For other topics for observability from the web console, see link:../observability/search_intro.adoc#[]
This link looks incomplete.

2023-04-27 15:21 UTC, dockerymick commented on observability/search_intro.adoc
> +- `search-indexer` - Receives resource metadata from the collectors and writes to PostgreSQL database. The `search-indexer` also watches resources in the hub cluster to keep track of active managed c
I will change previous item by using a hyphen instead

2023-04-27 15:27 UTC, dockerymick commented
@cadawson thanks for your review Chris! I made a few updates. When you have an opportunity, will you rereview?

2023-04-27 19:15 UTC, Anxhela21 commented on observability/search_intro.adoc
> +* `search_api_db_connection_failed_total` - The total number of database connection that failed.
```suggestion
* `search_api_db_connection_failed_total` - The total number of database connection attempts that failed.
```

2023-04-27 19:18 UTC, Anxhela21 approved these changes
Left a minor comment otherwise looks good. Thank you!
/lgtm
/hold

2023-05-01 16:58 UTC, dockerymick commented on observability/search_intro.adoc
> +- `search-postgres` - Stores collected data from all managed clusters in an instance of the PostgreSQL database.
@Anxhela21 it seems like we might also want to add the metrics to the [Metric types](https://github.com/stolostron/rhacm-docs/blob/2.8_stage/observability/observe_environments.adoc#metric-types) doc.

2023-05-02 15:53 UTC, Anxhela21 commented on observability/search_intro.adoc
> +- `search-postgres` - Stores collected data from all managed clusters in an instance of the PostgreSQL database.
@dockerymick Yes, I agree. Let's add the metrics to the metric types doc as well. I can open a new doc issue for that.

2023-05-02 15:53 UTC, Anxhela21 approved these changes
/lgtm

2023-05-02 16:11 UTC, dockerymick commented on observability/search_intro.adoc
> +- `search-postgres` - Stores collected data from all managed clusters in an instance of the PostgreSQL database.
@Anxhela21 let's continue to use the same issue. I'll make the update in the PR now

2023-05-02 18:32 UTC, Anxhela21 commented on observability/observe_environments.adoc
> +| `search-postgres`
This metric does not exist.

2023-05-02 18:32 UTC, Anxhela21 commented on observability/observe_environments.adoc
> +| `search-v2-api`
This metric doesn't exist.

2023-05-02 18:49 UTC, dockerymick commented on observability/search_intro.adoc
> +//suggestion instead of listing the components
@Anxhela21 let me know your thoughts about the table

2023-05-02 18:49 UTC, dockerymick commented on observability/observe_environments.adoc
> +| `search-postgres`
It's a component tho right?

2023-05-02 18:57 UTC, Anxhela21 commented on observability/search_intro.adoc
> +| `search-postgres`
We don't need to add `search-postgres`. This isn't a metric, it's the name of the postgres pod.

2023-05-02 18:59 UTC, Anxhela21 commented on observability/observe_environments.adoc
> +| `search-postgres`
Yes, but we don't currently expose metrics from Postgres.

2023-05-02 19:01 UTC, Anxhela21 commented on observability/observe_environments.adoc
> +| `search-postgres`
shouldn't be included in the metrics types table.

2023-05-02 19:02 UTC, Anxhela21 commented on observability/search_intro.adoc
> +| `search-postgres`
Ah, I see this is just space holder for the component - okay to keep!

2023-05-02 19:15 UTC, dockerymick commented on observability/search_intro.adoc
> +| `search-postgres`
Yup! The goal is to list the exposed metrics per component.

2023-05-02 19:18 UTC, Anxhela21 commented on observability/search_intro.adoc
> +//suggestion instead of listing the components
Looks great! Great way to show metrics per component and keep it compact.

2023-05-02 19:18 UTC, Anxhela21 approved these changes
/lgtm

2023-05-03 19:29 UTC, jlpadilla commented on observability/observe_environments.adoc
> +| `search_dbquery_duration_seconds`
```suggestion
| `search_api_dbquery_duration_seconds`
```

2023-05-03 19:31 UTC, jlpadilla commented on observability/observe_environments.adoc
> +| `search_api_requests`
Maybe this table should be sorted alphabetically?

2023-05-03 19:36 UTC, jlpadilla commented on observability/search_intro.adoc
> +.3+| `search-v2-api`
The `v2` part is mostly internal, so let's try to omit it when possible to keep it simple.
```suggestion
.3+| `search-api`
```

2023-05-03 19:36 UTC, jlpadilla commented on release_notes/whats_new.adoc
> +* The `search-v2-api` and `search_indexer` now expose metrics. Read link:../observability/search_intro.adoc#searching-in-the-console-intro[Searching in the console introduction].
```suggestion
* The `search-api` and `search_indexer` now expose metrics. Read link:../observability/search_intro.adoc#searching-in-the-console-intro[Searching in the console introduction]. 
```

2023-05-04 04:34 UTC, dockerymick commented on observability/observe_environments.adoc
> +| `search_api_requests`
It's not required, but still can be changed. Will complete in the AM

2023-05-04 12:51 UTC, cadawson approved these changes
Link looks good. The rest looks good to me, and the others were more clarifications. After confirming those, it looks good. Thanks!

2023-05-04 12:51 UTC, cadawson commented on observability/observe_environments.adoc
> +| It acts primarily as an API gateway and therefore does not need significant amounts of local disk space. It joins a Thanos cluster on startup and advertises the data it can access. It keeps a small
```suggestion
| It acts primarily as an API gateway and therefore does not need a significant amount of local disk space. It joins a Thanos cluster on startup and advertises the data it can access. It keeps a small amount of information about all remote blocks on local disk and keeps it in sync with the bucket. This data is generally safe to delete across restarts at the cost of increased startup times.
```

2023-05-04 12:51 UTC, cadawson commented on observability/observe_environments.adoc
>  | None.
Are we adding periods at the end of 'None' as a general item? It is consistent in here, which is good. It looks a little strange in a table with no following sentence.

2023-05-04 13:24 UTC, dockerymick commented on observability/observe_environments.adoc
>  | None.
Gotchu, i'll remove the periods

2023-05-04 13:30 UTC, dockerymick commented
@cadawson @jlpadilla @Anxhela21 thanks for the reviews, suggestions, and approvals. I organized the list to be in alphabetical order. Merging this PR

2023-05-04 13:30 UTC, merged