https://issues.redhat.com/browse/ACM-4890 OpenShift Platform Plus policy
open-cluster-management/rhacm-docs pull request #5034
Opened 2023-05-04 14:24 UTC by dockerymick

https://issues.redhat.com/browse/ACM-4890

2023-05-08 16:42 UTC, gparvin reviewed
Added some comments.  Thanks for putting this together!

2023-05-08 16:42 UTC, gparvin commented on governance/opp_policyset.adoc
> +- `policy-acs-central-ca-bundle`
I think if we list the policies we should group them by product and have some descriptions about what the policy is for.  I can help with that if you think it's a good idea.

2023-05-08 16:42 UTC, gparvin commented on governance/opp_policyset.adoc
> +* Install {ocp} 4.12 or newer.
this should be the first prerequisite and it should indicate OCP on AWS

2023-05-08 16:42 UTC, gparvin commented on governance/opp_policyset.adoc
> +. Install the Policy Generator Kustomize plugin. It is recommended to use Kustomize v4.5+. Complete the following steps:
There's a lot of information included about the Policy Generator here.  Does this already exist in another part of our documentation we can just reference?  I think we should just point to https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.7/html/governance/governance#policy-generator instead of showing how to use the generator from the CLI

2023-05-08 16:42 UTC, gparvin commented on governance/opp_policyset.adoc
> +OpenShift Platform Plus policy runs on your managed cluster. View the following sections to learn more:
I don't think we want this sentence -- or we could list the components of OPP and indicate what is on the managed cluster.  Something like:

OPP Components:
- OCP - Red Hat Kubernetes platform
- ACM - The management hub.  Manager of the managed clusters
- ODF - storage available for Hub components.  Used by ACM Observability and Quay
- Quay - Installed onto the ACM hub
- ACS - The Central server is installed onto the ACM hub, the ACS Secured Cluster services are installed on the ACM hub and the managed clusters

2023-05-08 16:42 UTC, gparvin commented on governance/opp_policyset.adoc
> +//I didnt see an example, is this the correct sample: https://github.com/open-cluster-management-io/policy-collection/blob/main/policygenerator/policy-sets/stable/openshift-plus/output.yaml
Yes, there is a key prerequisite that I haven't explained very well.  It can be described best by stating that OCP `nodes` must be provisioned for the ODF storage requirements.  An example policy that can be used to show how this prerequisite can be met is available here: https://github.com/open-cluster-management-io/policy-collection/tree/main/policygenerator/policy-sets/community/openshift-plus-setup

The thing to note about this example, in addition to showing how to setup the nodes it also shows how to setup the `ManagedClusterSetBinding` that you show above too.  I think you could consider pointing to this sample for both or what would be easiest for the customer to understand here?...

2023-05-08 20:38 UTC, dockerymick commented on governance/opp_policyset.adoc
> +. Install the Policy Generator Kustomize plugin. It is recommended to use Kustomize v4.5+. Complete the following steps:
Thanks, yea that's a good idea. I got these instructions from the is README: https://github.com/open-cluster-management-io/policy-collection/tree/main/policygenerator/policy-sets/stable/openshift-plus

2023-05-08 20:46 UTC, dockerymick commented on governance/opp_policyset.adoc
> +* Install {ocp} 4.12 or newer.
updated

2023-05-08 21:17 UTC, dockerymick commented on governance/opp_policyset.adoc
> +- `policy-acs-central-ca-bundle`
Great idea! I started the table for this information

2023-05-17 17:31 UTC, dockerymick commented on governance/opp_policyset.adoc
> +//I didnt see an example, is this the correct sample: https://github.com/open-cluster-management-io/policy-collection/blob/main/policygenerator/policy-sets/stable/openshift-plus/output.yaml
Yea, I agree that it might be best to link to the sample because it's a long YAML. I have a Component table, maybe we can add the specific YAML sections in the table? the new column can be named YAML sample. 

should the following statement be added to the Prerequisites section at the beginning of the file?

2023-05-18 12:51 UTC, gparvin reviewed
I added some more comments.  Thanks!

2023-05-18 12:51 UTC, gparvin commented on governance/opp_policyset.adoc
> +The Red Hat Advanced Cluster Security secured cluster services, the Compliance Operator, and OpenShift Platform Plus policy are deployed onto all of your {ocp-short} managed clusters.
```suggestion
The Red Hat Advanced Cluster Security secured cluster services and the Compliance Operator are deployed onto all of your {ocp-short} managed clusters.
```

2023-05-18 12:51 UTC, gparvin commented on governance/opp_policyset.adoc
> +| `policy-config-quay`
The table doesn't show up correctly when I tried to view the file.  The 3 quay policies should be grouped together as policies for the product "Red Hat Quay".  The policy `policy-ocm-observability` sets up ACM Observability so that one should be separate also.

2023-05-18 12:51 UTC, gparvin commented on governance/opp_policyset.adoc
> +//not sure if this is needed, other grc policy docs have these sections.
Since this solution uses the Policy Generator and PolicySets -- I would link to those 2 places as references where you could learn more.

2023-05-18 12:51 UTC, gparvin commented on governance/opp_policyset.adoc
> +//I didnt see an example, is this the correct sample: https://github.com/open-cluster-management-io/policy-collection/blob/main/policygenerator/policy-sets/stable/openshift-plus/output.yaml
The example was the entire project I was pointing to in the link in my comment.  The details are in the README.md file you see at that link: https://raw.githubusercontent.com/open-cluster-management-io/policy-collection/main/policygenerator/policy-sets/community/openshift-plus-setup/README.md

2023-05-18 15:16 UTC, dockerymick commented on governance/opp_policyset.adoc
> +| `policy-config-quay`
Updated the table more

2023-05-18 15:20 UTC, dockerymick commented on governance/opp_policyset.adoc
> +//not sure if this is needed, other grc policy docs have these sections.
updated additional resources section

2023-05-18 18:47 UTC, dockerymick commented
@gparvin thanks for clarifying. I made a few updates. When you have an opportunity, will you provide another review?

2023-05-23 23:24 UTC, dockerymick commented
@JustinKuli Will you also review this when you have an opportunity?

2023-05-24 14:30 UTC, JustinKuli reviewed
Maybe I'm being picky here 😅 I think overall it looks really good. I just want to make a few places more clear.

2023-05-24 14:30 UTC, JustinKuli commented on governance/opp_policyset_install.adoc
> +//added the full YAML bc this policy is in the community folder. Avoid linking to community policies
Just to note there's still a comment here. I think the yaml in the doc is good.

2023-05-24 14:30 UTC, JustinKuli commented on governance/opp_policyset_install.adoc
> +----
```suggestion
. Policies are installed to the `policies` namespace. You must bind that namespace to a ClusterSet. For example, copy and apply the following example YAML to bind the namespace to the default ClusterSet:
+
[source,yaml]
----
kind: ManagedClusterSetBinding
metadata:
    name: default
    namespace: policies
spec:
    clusterSet: default
----
```

My understanding is that the generator will handle all of the PlacementBindings details, so the user won't have to adjust any of that.

And I liked the "Copy and apply the following YAML" phrase from the earlier yaml; I think that's better than `oc apply -f managed-cluster.yaml` here.

2023-05-24 14:30 UTC, JustinKuli commented on governance/opp_policyset_install.adoc
> +*Note:* For any components of OpenShift Plus that you do not want to install, edit the `policyGenerator.yaml` file and remove or comment out the policies for those components.
I don't think this is clear - I believe to apply the set like this I would need to clone the policy collection, and navigate to the directory where this generator yaml is.

2023-05-30 15:59 UTC, dockerymick commented on governance/opp_policyset.adoc
> +//I didnt see an example, is this the correct sample: https://github.com/open-cluster-management-io/policy-collection/blob/main/policygenerator/policy-sets/stable/openshift-plus/output.yaml
Updated

2023-05-30 16:00 UTC, dockerymick commented on governance/opp_policyset_install.adoc
> +//added the full YAML bc this policy is in the community folder. Avoid linking to community policies
thanks!

2023-05-30 16:21 UTC, dockerymick commented on governance/opp_policyset_install.adoc
> +----
Great suggestion. I updated the file with most of your suggestion, but I think it would be helpful to keep the `apply` command. Pulling in doc peer for feedback

2023-05-30 16:23 UTC, dockerymick commented on governance/opp_policyset_install.adoc
> +*Note:* For any components of OpenShift Plus that you do not want to install, edit the `policyGenerator.yaml` file and remove or comment out the policies for those components.
Thanks for clarifying! Should I add the step to clone the repo on line 132?

2023-05-30 17:07 UTC, cadawson requested changes
Some suggestions, including updating the links to the Portal and version. Let me know if you have questions. I don't need to see it again, unless you want me to take a look. Thanks!

2023-05-30 17:07 UTC, cadawson commented on governance/opp_policyset.adoc
> +The OpenShift Plus policy set contains two `PolicySets` that are deployed. The OpenShift Plus policy set applies multiple policies that are set to install OpenShift Platform Plus products. The Red Ha
```suggestion
The OpenShift Platform Plus policy set contains two `PolicySets` that are deployed. The OpenShift Plus policy set applies multiple policies that are set to install OpenShift Platform Plus products. The Red Hat Advanced Cluster Security secured cluster services and the Compliance Operator are deployed onto all of your {ocp-short} managed clusters.
```

2023-05-30 17:07 UTC, cadawson commented on governance/opp_policyset.adoc
> +- Install {title-product} {version-prev} or newer.
Using this conref is fine as long as you will want it to change to version 4.13 when the next release GAs. If it will always be 2.7, then you might want to hardcode it.

2023-05-30 17:07 UTC, cadawson commented on governance/opp_policyset.adoc
> +- Install {title-product} {version-prev} or newer.
```suggestion
- Install {product-title} {version-prev} or newer.
```

2023-05-30 17:07 UTC, cadawson commented on governance/opp_policyset.adoc
> +- Install {title-product} {version-prev} or newer.
```suggestion
- Install {product-title-short} {version-prev} or newer.
```

2023-05-30 17:07 UTC, cadawson commented on governance/opp_policyset.adoc
> +| policy used to install the central server onto the {product-title} hub cluster and the managed clusters.
```suggestion
| Policy used to install the central server onto the {product-title} hub cluster and the managed clusters.
```

2023-05-30 17:07 UTC, cadawson commented on governance/opp_policyset_install.adoc
> +. Policies are installed to the `policies` namaespace. You must bind that namespace to a `ClusterSet`. For example, copy and apply the following example YAML to bind the namespace to the default `Clu
```suggestion
. Policies are installed to the `policies` namespace. You must bind that namespace to a `ClusterSet`. For example, copy and apply the following example YAML to bind the namespace to the default `ClusterSet`:
```

2023-05-30 17:07 UTC, cadawson commented on governance/opp_policyset_install.adoc
> +*Note:* For any components of OpenShift Plus that you do not want to install, edit the `policyGenerator.yaml` file and remove or comment out the policies for those components.
```suggestion
*Note:* For any components of OpenShift Platform Plus that you do not want to install, edit the `policyGenerator.yaml` file and remove or comment out the policies for those components.
```

2023-05-30 17:07 UTC, cadawson commented on governance/supported_policies.adoc
> +| Manage role permissions and bindings using Roles and Role Bindings. See the Kubernetes link:https://kubernetes.io/docs/reference/access-authn-authz/rbac/[RBAC documentation].
Should Role and Role Bindings be capitalized?

2023-05-30 17:07 UTC, cadawson commented on governance/supported_policies.adoc
> +| Manage workload permissions with Security Context Constraints. See the Openshift link:https://docs.openshift.com/container-platform/4.10/authentication/managing-security-context-constraints.html[Se
```suggestion
| Manage workload permissions with Security Context Constraints. See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.13/html/authentication_and_authorization/managing-pod-security-policies[Managing Security Context Constraints documentation] in the {ocp-short} documentation.
```

2023-05-30 17:07 UTC, cadawson commented on governance/supported_policies.adoc
> +| Ensure data security with etcd encryption. See the Openshift link:https://docs.openshift.com/container-platform/4.10/security/encrypting-etcd.html[etcd encryption documentation].
```suggestion
| Ensure data security with etcd encryption. See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.13/html/security_and_compliance/encrypting-etcd[Encrypting etcd data] in the {ocp-short} documentation.
```

2023-05-30 17:07 UTC, cadawson commented on governance/supported_policies.adoc
> +| Deploy the Compliance Operator to scan and enforce the compliance state of clusters leveraging OpenSCAP. See the Openshift link:https://docs.openshift.com/container-platform/4.11/security/complianc
```suggestion
| Deploy the Compliance Operator to scan and enforce the compliance state of clusters leveraging OpenSCAP. See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.13/html/security_and_compliance/compliance-operator#understanding-compliance-operator[Understanding the Compliance Operator] in the {ocp-short} documentation.
```

2023-05-30 17:07 UTC, cadawson commented on governance/supported_policies.adoc
> +| After applying the Compliance operator policy, deploy an Essential 8 (E8) scan to check for compliance with E8 security profiles. See the Openshift link:https://docs.openshift.com/container-platfor
```suggestion
| After applying the Compliance operator policy, deploy an Essential 8 (E8) scan to check for compliance with E8 security profiles. See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.13/html/security_and_compliance/compliance-operator#understanding-compliance-operator[Understanding the Compliance Operator] in the {ocp-short} documentation.
```

2023-05-30 17:07 UTC, cadawson commented on governance/supported_policies.adoc
> +| After applying the Compliance operator policy, deploy a Center for Internet Security (CIS) scan to check for compliance with CIS security profiles. See the Openshift link:https://docs.openshift.com
```suggestion
| After applying the Compliance operator policy, deploy a Center for Internet Security (CIS) scan to check for compliance with CIS security profiles. See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.13/html/security_and_compliance/compliance-operator#understanding-compliance-operator[Understanding the Compliance Operator] in the {ocp-short} documentation.
```

2023-05-30 17:07 UTC, cadawson commented on governance/supported_policies.adoc
> +| Deploy the Container Security Operator and detect known image vulnerabilities in pods running on the cluster. See the link:https://github.com/quay/container-security-operator#readme[Container Secur
```suggestion
| Deploy the Container Security Operator and detect known image vulnerabilities in pods running on the cluster. See the link:https://github.com/quay/container-security-operator#readme[Container Security Operator] GitHub repository.
```

2023-05-30 17:25 UTC, dockerymick commented on governance/supported_policies.adoc
> +| Manage role permissions and bindings using Roles and Role Bindings. See the Kubernetes link:https://kubernetes.io/docs/reference/access-authn-authz/rbac/[RBAC documentation].
Great catch, no they shouldn't be

2023-05-31 13:28 UTC, dockerymick commented on governance/opp_policyset.adoc
> +- Install {title-product} {version-prev} or newer.
Updated

2023-05-31 13:29 UTC, dockerymick commented on governance/opp_policyset.adoc
> +- Install {title-product} {version-prev} or newer.
Updated

2023-05-31 13:29 UTC, dockerymick commented on governance/supported_policies.adoc
> +| Manage role permissions and bindings using Roles and Role Bindings. See the Kubernetes link:https://kubernetes.io/docs/reference/access-authn-authz/rbac/[RBAC documentation].
updated

2023-05-31 13:53 UTC, JustinKuli reviewed
Just one last note from me, everything else looks good

2023-05-31 13:53 UTC, JustinKuli commented on governance/opp_policyset_install.adoc
> +----
The "copy and apply" from line 108 means that this section isn't necessary.

2023-05-31 14:01 UTC, dockerymick commented on governance/opp_policyset_install.adoc
> +----
It's best to still provide the command. It is best practice to not assume that the user knows how to apply the policy. I should add the apply command in the prerequisite section then. 

Question, does applying the policy from the CLI provide the same result as creating a policy from the console?

2023-05-31 14:01 UTC, dockerymick commented on governance/opp_policyset_install.adoc
> +
based on my other comment and to be consistent, I should add the apply command after the policy

2023-05-31 14:29 UTC, dockerymick commented on governance/opp_policyset_install.adoc
> +*Note:* For any components of OpenShift Plus that you do not want to install, edit the `policyGenerator.yaml` file and remove or comment out the policies for those components.
@JustinKuli ^

2023-05-31 15:44 UTC, JustinKuli commented on governance/opp_policyset_install.adoc
> +----
Applying from the CLI and creating from the console should have the same result.

2023-05-31 19:44 UTC, dockerymick commented on governance/opp_policyset_install.adoc
> +. To allow for subscriptions to be applied to your cluster, you must apply the `policy-configure-subscription-admin-hub.yaml` policy and set the remediation action to `enforce`. Copy and apply the fo
@JustinKuli I am suggesting this to avoid using the `apply` command. Thoughts? 

```suggestion
. To allow for subscriptions to be applied to your cluster, you must apply the `policy-configure-subscription-admin-hub.yaml` policy and set the remediation action to `enforce`. Copy and apply the following YAML from the console:
```

2023-05-31 19:51 UTC, JustinKuli commented on governance/opp_policyset_install.adoc
> +. To allow for subscriptions to be applied to your cluster, you must apply the `policy-configure-subscription-admin-hub.yaml` policy and set the remediation action to `enforce`. Copy and apply the fo
Yeah, that might be a step better. Although it brings up the question of "where in the console do I apply this?" ... to be clear, I think it is reasonable to assume the user knows where to apply this in the console, but I also think they should know how to apply YAML outside of the console without an extra command specified in the docs.

2023-06-01 12:54 UTC, dockerymick commented on governance/opp_policyset_install.adoc
> +. Run the following command to apply the `ManagedClusterSetBinding`:
```suggestion
. Run the following command to apply the `ManagedClusterSetBinding` resource from the command line interface:
```

2023-06-01 12:57 UTC, dockerymick commented on governance/opp_policyset_install.adoc
> +
```suggestion
+
. To apply the previous YAML from the command line interface, run the following command:
+
----
oc apply -f policy-configure-subscription-admin-hub.yaml
----
```

2023-06-01 12:59 UTC, dockerymick commented on governance/opp_policyset_install.adoc
> +
@JustinKuli is the correct command?

2023-06-01 17:14 UTC, JustinKuli commented on governance/opp_policyset_install.adoc
> +
Maybe say `oc apply -f policy-configure-subscription-admin-hub.yaml` to make it more clear.

2023-06-01 18:53 UTC, dockerymick commented on governance/opp_policyset_install.adoc
> +
@JustinKuli thanks! updated my suggestion and going to commit now.

2023-06-01 18:54 UTC, dockerymick commented on governance/opp_policyset_install.adoc
> +. To allow for subscriptions to be applied to your cluster, you must apply the `policy-configure-subscription-admin-hub.yaml` policy and set the remediation action to `enforce`. Copy and apply the fo
Came to agreement in a different comment. Accepting this suggestion

2023-06-01 18:55 UTC, dockerymick commented on governance/opp_policyset_install.adoc
> +----
Resolved

2023-06-01 19:34 UTC, JustinKuli commented on governance/opp_policyset_install.adoc
> +*Note:* For any components of OpenShift Plus that you do not want to install, edit the `policyGenerator.yaml` file and remove or comment out the policies for those components.
I changed my mind 😆  I think it's ok, since the link is listed before that, it's not necessary to explain how to clone the repo and make the edit.

2023-06-01 19:36 UTC, JustinKuli approved these changes
LGTM

2023-06-01 22:56 UTC, dockerymick commented
@JustinKuli thanks for your approval and help! @cadawson thanks to you too! Merging this PR

2023-06-01 22:56 UTC, merged