https://issues.redhat.com/browse/ACM-4965 Credential update
open-cluster-management/rhacm-docs pull request #5041
Opened 2023-05-05 18:57 UTC by oafischer

2023-05-05 19:54 UTC, dockerymick requested changes

2023-05-05 19:54 UTC, dockerymick commented on clusters/credentials/credential_google.adoc
> +. Add your _Google Cloud Platform project ID_ for your GCP account. _Log in to GCP_ to retrieve your settings.
```suggestion
. Add your _Google Cloud Platform project ID_ for your GCP account. See _Log in to GCP_ to retrieve your settings.
```

2023-05-05 19:54 UTC, dockerymick commented on clusters/credentials/credential_google.adoc
> +. Add your _Google Cloud Platform service account JSON key_. See the _Create service accounts_ to create your service account JSON key. Follow the steps for the GCP console.
```suggestion
. Add your _Google Cloud Platform service account JSON key_. See the _Create service accounts_ documentation to create your service account JSON key. Follow the steps for the GCP console.
```

2023-05-05 19:54 UTC, dockerymick commented on clusters/credentials/credential_google.adoc
> +. Enter your _Red Hat OpenShift pull secret_. See _Download your Red Hat OpenShift pull secret_ to download your pull secret.
```suggestion
. Enter your Red Hat OpenShift pull secret. See _Download your Red Hat OpenShift pull secret_ to download your pull secret.
```

2023-05-05 19:54 UTC, dockerymick commented on clusters/credentials/credential_openstack.adoc
> +. Enter your _Red Hat OpenShift pull secret_. See _Download your Red Hat OpenShift pull secret_ to download your pull secret.
```suggestion
. Enter your Red Hat OpenShift pull secret. See _Download your Red Hat OpenShift pull secret_ to download your pull secret.
```

2023-05-05 19:54 UTC, dockerymick commented on clusters/credentials/credential_vm.adoc
>  . [[disconnected-vm]]For disconnected installations only: Complete the fields in the *Configuration for disconnected installation* subsection with the required information:
This isn't bold when I preview the file, but the asterisk bold lines 59-69

2023-05-05 19:54 UTC, dockerymick commented on clusters/credentials/credential_vm.adoc
>  . [[disconnected-vm]]For disconnected installations only: Complete the fields in the *Configuration for disconnected installation* subsection with the required information:
I'm not sure what this is for: `[[disconnected-vm]]`

2023-05-05 19:54 UTC, dockerymick commented on clusters/credentials/credential_vm.adoc
> +. Enter your _Red Hat OpenShift pull secret_. See _Download your Red Hat OpenShift pull secret_ to download your pull secret.
```suggestion
. Enter your Red Hat OpenShift pull secret. See _Download your Red Hat OpenShift pull secret_ to download your pull secret.
```

2023-05-05 19:54 UTC, dockerymick commented on clusters/credentials/credential_aws.adoc
> +. Enter your _Red Hat OpenShift pull secret_. See _Download your Red Hat OpenShift pull secret_ to download your pull secret.
```suggestion
. Enter your Red Hat OpenShift pull secret. See _Download your Red Hat OpenShift pull secret_ to download your pull secret.
```

2023-05-05 19:54 UTC, dockerymick commented on clusters/credentials/credential_aws.adoc
> +- See link:https://docs.openshift.com/container-platform/4.13installing/installing_aws/installing-aws-account.html[Configuring an AWS account].
Broken link

2023-05-05 19:54 UTC, dockerymick commented on clusters/credentials/credential_openstack.adoc
> +- See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.13/html/installing/installing-on-openstack#installing-openstack-installer-custom[Installing a cluster on OpenSt
Broken link

2023-05-05 19:54 UTC, dockerymick commented on clusters/credentials/credential_openstack.adoc
> +- See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.13/html/installing/installing-on-openstack#ssh-agent-using_installing-openstack-installer-custom[Generating a k
Broken link

2023-05-05 19:54 UTC, dockerymick commented on clusters/credentials/credential_vm.adoc
> +- See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.13/html/installing/installing-on-vsphere#ssh-agent-using_installing-vsphere-installer-provisioned[Generating a
Broken link

2023-05-05 19:58 UTC, oafischer commented on clusters/credentials/credential_vm.adoc
>  . [[disconnected-vm]]For disconnected installations only: Complete the fields in the *Configuration for disconnected installation* subsection with the required information:
I'm not sure either lol. I'll check if @cadawson knows.

2023-05-05 20:03 UTC, cadawson commented on clusters/credentials/credential_vm.adoc
>  . [[disconnected-vm]]For disconnected installations only: Complete the fields in the *Configuration for disconnected installation* subsection with the required information:
That is an anchor for a link from the UI.

2023-05-05 20:03 UTC, oafischer commented on clusters/credentials/credential_aws.adoc
> +- See link:https://docs.openshift.com/container-platform/4.13installing/installing_aws/installing-aws-account.html[Configuring an AWS account].
Should unbreak when OCP releases their doc, though I agree it's somewhat of a gamble.

2023-05-05 20:06 UTC, oafischer commented on clusters/credentials/credential_vm.adoc
>  . [[disconnected-vm]]For disconnected installations only: Complete the fields in the *Configuration for disconnected installation* subsection with the required information:
Fixed the bold, thanks for catching that!

2023-05-05 20:39 UTC, chenz4027 approved these changes
/lgtm

Thanks!

2023-05-08 13:27 UTC, dockerymick approved these changes
Looks good, thanks for updates

2023-05-08 13:45 UTC, merged