[ACM-4125]: Docs about creating AWS infra and IAM resources separately
open-cluster-management/rhacm-docs pull request #5052
Opened 2023-05-09 16:14 UTC by lahinson

Related Jira: https://issues.redhat.com/browse/ACM-4125

This PR ports the upstream docs about creating AWS infra and IAM resources separately to the product docs.

2023-05-10 14:08 UTC, lahinson commented
/assign @csrwng

2023-05-10 14:19 UTC, csrwng reviewed
/lgtm
Thx @lahinson !

2023-05-11 16:40 UTC, dockerymick commented
Assigned @swopebe as the reviewer based on Slack updates. If need be, I can also review.

2023-05-15 13:54 UTC, swopebe commented
I am reviewing this today. :-)

2023-05-15 15:41 UTC, swopebe commented on clusters/hosted_control_planes/managing_aws_infra_iam.adoc
> +The default behavior of the `hypershift create cluster aws` command is to create cloud infrastructure along with the hosted cluster and apply it. You can create the cloud infrastructure portion separ
The rhacm team usually doesn't refer to behavior of a command, this would look completely different in our doc set, as we follow the guidelines to avoid anthropomorphism. 

By default, the `hypershift create cluster aws` command is used to create and apply cloud infrastructure along with the hosted cluster.

Not exactly sure what is meant by _along with the hosted cluster_. (applies with hosted cluster or applies it along side the hosted cluster?)

2023-05-15 15:43 UTC, swopebe requested changes
This looks great....one thing at the beginning...let me know if the revised comment is OK...then after we get that clearer, I will approve. Thanks for pulling us in.

2023-05-15 17:18 UTC, lahinson commented on clusters/hosted_control_planes/managing_aws_infra_iam.adoc
> +The default behavior of the `hypershift create cluster aws` command is to create cloud infrastructure along with the hosted cluster and apply it. You can create the cloud infrastructure portion separ
Good catch, @swopebe! I revised that line to "By default, the `hypershift create cluster aws` command creates cloud infrastructure with the hosted cluster and applies it."

2023-06-05 17:10 UTC, swopebe approved these changes

2023-06-05 17:10 UTC, swopebe approved these changes

2023-06-05 17:10 UTC, swopebe approved these changes

2023-06-05 17:10 UTC, swopebe approved these changes

2023-06-05 17:17 UTC, merged