https://issues.redhat.com/browse/ACM-5200 Adding tolerations for GitOps
open-cluster-management/rhacm-docs pull request #5053
Opened 2023-05-09 18:26 UTC by dockerymick

https://issues.redhat.com/browse/ACM-5200

2023-05-09 19:28 UTC, mikeshng reviewed
all looks good to me just one small suggestion

2023-05-09 19:28 UTC, mikeshng commented on applications/gitops_config.adoc
> +- In some unstable network scenarios, the managed clusters might be temporarily  placed in `Unavailable` state. See _Configuring placement tolerations for {product-title-short} and OpenShift GitOps_
```suggestion
- In some unstable network scenarios, the managed clusters might be temporarily placed in `Unavailable` state. See _Configuring placement tolerations for {product-title-short} and OpenShift GitOps_ for more details.
```

2023-05-09 21:14 UTC, cadawson requested changes
Some stuff noted here. Might be worth a discussion as a team, but might not affect this PR. See what you think. Let me know if you want to go through it quickly together. Thanks!

2023-05-09 21:14 UTC, cadawson commented on applications/gitops_config.adoc
> +. Create managed cluster sets and add managed clusters to those managed cluster sets. See the _Creating a ManagedClusterSet_ documentation for more information.
Discussion point: This is where it seems to me that we could use the link in the text. When I read it, here is what I'm thinking: 
1. It reads "for more information", but there really isn't any information provided. Maybe if it was, "See the _Creating a ManagedClusterSet_ documentation for the procedure," or similar.
2. There really isn't any indication that there is another section where I can find the link to this information. Should I find the doc in the navigation? This one might get clearer when people get used to our docs and we are fully consistent with it.

Not saying this is on you, but maybe we should try to discuss some criteria for these as a team.

2023-05-09 21:14 UTC, cadawson commented on applications/gitops_config.adoc
> +. Create managed cluster set binding to the namespace where Red Hat OpenShift GitOps is deployed. See the `multicloud-integrations managedclustersetbinding` example, which binds to the `openshift-git
```suggestion
. Create a managed cluster set binding to the namespace where Red Hat OpenShift GitOps is deployed. For an example of binding the managed cluster to the `openshift-gitops` namespace, see the `multicloud-integrations managedclustersetbinding` example. In the _Additional resources_ section, see _Creating a ManagedClusterSetBinding resource_ for more general information about creating a `ManagedClusterSetBinding`. 
```

2023-05-09 21:14 UTC, cadawson commented on applications/gitops_config.adoc
> +. Create managed cluster set binding to the namespace where Red Hat OpenShift GitOps is deployed. See the `multicloud-integrations managedclustersetbinding` example, which binds to the `openshift-git
Same question about how do I know that there is an additional resources section?

2023-05-09 21:14 UTC, cadawson commented on applications/gitops_config.adoc
> +. In the namespace that is used in managed cluster set binding, create a `Placement` custom resource to select a set of managed clusters to register to an {ocp-short} GitOps operator instance. Use th
```suggestion
. In the namespace that is used in managed cluster set binding, create a `Placement` custom resource to select a set of managed clusters to register to an {ocp-short} GitOps operator instance. Use the `multicloud-integration` placement example as a template. See _Using ManagedClusterSets with Placement_ for placement information. 
```

2023-05-09 21:14 UTC, cadawson commented on applications/gitops_config.adoc
> +<1> from the following sample that `placementRef.name` is `all-openshift-clusters`, and is specified as target clusters for the GitOps instance that is installed in `argoNamespace: openshift-gitops`.
```suggestion
<1> The `placementRef.name` value is `all-openshift-clusters`, and is specified as target clusters for the GitOps instance that is installed in `argoNamespace: openshift-gitops`. The `argoServer.cluster` specification requires the `local-cluster` value.
```

2023-05-09 21:14 UTC, cadawson commented on applications/gitops_config.adoc
> +<1> from the following sample that `placementRef.name` is `all-openshift-clusters`, and is specified as target clusters for the GitOps instance that is installed in `argoNamespace: openshift-gitops`.
Where is the `argoServer.cluster` value in the sample? Is this something that used to be in the sample, but is not now?

2023-05-09 21:14 UTC, cadawson commented on applications/tolerations_config.adoc
> +{product-title-short} provides a way for you to register managed clusters to Red Hat OpenShift GitOps, that deploy applications.
Do the managed clusters deploy applications or does the OpenShift GitOps deploy applications? Please reword to make it clear. 

Examples:
{product-title-short} provides a way for you to register managed clusters that deploy applications to Red Hat OpenShift GitOps.

or 

{product-title-short} provides a way for you to register managed clusters to Red Hat OpenShift GitOps. Red Hat OpenShift GitOps can then deploy applications.

2023-05-09 21:14 UTC, cadawson commented on applications/tolerations_config.adoc
> +In some unstable network scenarios, the managed clusters might be temporarily placed in `Unavailable` state. If a `Placement` resource is being used to facilitate the deployment of applications, add
```suggestion
In some unstable network scenarios, the managed clusters might be temporarily placed in `Unavailable` state. If a `Placement` resource is being used to facilitate the deployment of applications, add tolerations for the `Placement` resource to continue to include unavailable clusters. The following example shows a  `Placement` resource with tolerations:
```

2023-05-09 21:14 UTC, cadawson requested changes
Some stuff noted here. Might be worth a discussion as a team, but might not affect this PR. See what you think. Let me know if you want to go through it quickly together. Thanks!

2023-05-09 21:24 UTC, swopebe commented on applications/gitops_config.adoc
> +. Create managed cluster sets and add managed clusters to those managed cluster sets. See the _Creating a ManagedClusterSet_ documentation for more information.
Why is this going in app?

2023-05-09 21:25 UTC, swopebe commented on applications/gitops_config.adoc
> +. Create managed cluster sets and add managed clusters to those managed cluster sets. See the _Creating a ManagedClusterSet_ documentation for more information.
I think we need to make it clearer if this is an Application management function because the intro appears to me more like cluster lifecycle. (?)

2023-05-09 21:41 UTC, mikeshng commented on applications/gitops_config.adoc
> +. Create managed cluster sets and add managed clusters to those managed cluster sets. See the _Creating a ManagedClusterSet_ documentation for more information.
The resource related to app is `GitOpsCluster`. The `GitOpsCluster` spec refers to a `Placement`. The `Placement` only works if there is a `ManagedClusterSet` and `ManagedClusterSetBinding` which are cluster lifecycle resources. 

Just providing some extra context. I don't know if it's a good idea to talk about cluster lifecycle resources here or not.

2023-05-09 21:47 UTC, dockerymick commented
@swopebe @cadawson @mikeshng thanks for the reviews. I will be able to address the comments shortly

2023-05-10 14:22 UTC, swopebe commented on applications/gitops_config.adoc
> +. Create managed cluster sets and add managed clusters to those managed cluster sets. See the _Creating a ManagedClusterSet_ documentation for more information.
Right, I think this was placed since we have gitops content here, however, it is important @cadawson that we understand the concept of the function so we can write it well for the user...I am not sure this should be placed here but want to encourage a review of the playback and a quick Slack discussion or meeting with the dev team.

really with new content like this, a meeting with the dev team may need to be the first step since some of it crosses components.

2023-05-10 20:27 UTC, dockerymick commented on applications/gitops_config.adoc
> +. Create managed cluster set binding to the namespace where Red Hat OpenShift GitOps is deployed. See the `multicloud-integrations managedclustersetbinding` example, which binds to the `openshift-git
@cadawson updated your suggestion.

2023-05-10 20:45 UTC, dockerymick commented on applications/tolerations_config.adoc
> +{product-title-short} provides a way for you to register managed clusters to Red Hat OpenShift GitOps, that deploy applications.
Your first suggestion is most accurate, thanks for your feedback

2023-05-10 20:46 UTC, dockerymick commented on applications/tolerations_config.adoc
> +In some unstable network scenarios, the managed clusters might be temporarily placed in `Unavailable` state. If a `Placement` resource is being used to facilitate the deployment of applications, add
updated

2023-05-10 21:02 UTC, dockerymick commented on applications/gitops_config.adoc
> +. Create managed cluster sets and add managed clusters to those managed cluster sets. See the _Creating a ManagedClusterSet_ documentation for more information.
@swopebe thanks Brandi for calling this out. I agree that this might be better in the Clusters folder. I'll wait on confirmation before making this update  FYI @elgnay @rokej

2023-05-11 16:30 UTC, dockerymick commented on applications/gitops_config.adoc
> +<1> from the following sample that `placementRef.name` is `all-openshift-clusters`, and is specified as target clusters for the GitOps instance that is installed in `argoNamespace: openshift-gitops`.
@cadawson the value is shown on Lines 42 and 43

2023-05-15 07:02 UTC, elgnay commented on applications/gitops_config.adoc
> +. Create managed cluster sets and add managed clusters to those managed cluster sets. See the _Creating a ManagedClusterSet_ documentation for more information.
Although this doc involves lots of cluster lifecycle resources, I still think application is the right place for it because the whole doc describes the necessary configuration we need to support gitops.

2023-05-15 13:30 UTC, dockerymick commented on applications/gitops_config.adoc
> +. Create managed cluster sets and add managed clusters to those managed cluster sets. See the _Creating a ManagedClusterSet_ documentation for more information.
@elgnay thanks for confirming. @swopebe as you mentioned before, we should probably consider adding a GitOps folder. So far GitOps is referenced in the Apps folder and Governance folder

2023-05-15 13:53 UTC, swopebe commented on applications/gitops_config.adoc
> +. Create managed cluster sets and add managed clusters to those managed cluster sets. See the _Creating a ManagedClusterSet_ documentation for more information.
@dockerymick ok, it's something that we need to carefully look at...app is day two by comparison. I will set up an arch meeting.

I am not sure if the suggestion was to add an anchor for the "Additional information" section (I thought I saw a comment on that) and I don't think we need to go down that route, if so.

2023-05-15 14:52 UTC, dockerymick commented on applications/gitops_config.adoc
> +. Create managed cluster sets and add managed clusters to those managed cluster sets. See the _Creating a ManagedClusterSet_ documentation for more information.
I am suggesting that we create a GitOps book. I added Additional resources section myself, I guess it was self-requested lol

2023-05-17 15:52 UTC, netzzer requested changes

2023-05-17 15:52 UTC, netzzer commented on applications/tolerations_config.adoc
> +  tolerations:
Correct syntax as detailed in example https://github.com/stolostron/multicloud-integrations/blob/main/examples/placement.yaml#L7-L12:

```
tolerations:
  - key: cluster.open-cluster-management.io/unreachable
    operator: Exists
  - key: cluster.open-cluster-management.io/unavailable
    operator: Exists
```

2023-05-18 19:22 UTC, dockerymick commented
@swopebe @elgnay I made updates based on the comments and also updated the `tolerations` example that was requested by @netzzer 

Will you all provide another review?

2023-05-19 03:31 UTC, elgnay commented on applications/tolerations_config.adoc
> +apiVersion: cluster.open-cluster-management.io/v1alpha1
Please use `v1beta1` instead of `v1alpha1 `, which is no longer supported in 2.8.

2023-05-19 19:03 UTC, dockerymick commented on applications/tolerations_config.adoc
> +apiVersion: cluster.open-cluster-management.io/v1alpha1
updated

2023-05-31 15:18 UTC, dockerymick commented
@swopebe @elgnay will you both provide approval if you agree with the updates?

2023-05-31 15:28 UTC, dockerymick commented on applications/gitops_config.adoc
> +. Create managed cluster sets and add managed clusters to those managed cluster sets. See the _Creating a ManagedClusterSet_ documentation for more information.
Recently updated the titles in the `gitops_config.adoc` file and `tolerations_config.adoc` file with the updates from @mikeshng [PR](https://github.com/mikeshng/rhacm-docs/pull/1/files). Resolving this convo

2023-06-12 14:45 UTC, swopebe approved these changes
The only thing jumping out at me that I should have brought up earlier is that we should prob name all gitops files with "gitops" in the filename, this will make it easier to move them when it is time and to identify in the source code and in links as content related to gitops.

2023-06-12 18:36 UTC, merged