https://issues.redhat.com/browse/ACM-4959 Silence and suppress alerts + modularization
open-cluster-management/rhacm-docs pull request #5070
Opened 2023-05-11 20:45 UTC by dockerymick

https://issues.redhat.com/browse/ACM-4959

2023-05-16 14:45 UTC, dockerymick commented on observability/observability_alerts.adoc
> +//suppressing seems similar to silencing , is my explanation accurate?
@dislbenn

2023-05-16 16:05 UTC, cadawson requested changes
Some suggestions and minor things. Thanks!

2023-05-16 16:05 UTC, cadawson commented on observability/observability_alerts.adoc
> +When you set the annotation, the alert forwarding configuration on the managed clusters is reverted. Any changes made to the `ocp-monitoring-config` ConfigMap in the `openshift-monitoring` namespace
Suggestion: ...namespace are also reverted.

2023-05-16 16:05 UTC, cadawson commented on observability/observability_alerts.adoc
> +When the changes are reverted, a ConfigMap named `cluster-monitoring-reverted` is createde in the `open-cluster-management-addon-observability` namespace. Any new, manually added alert forward config
```suggestion
When the changes are reverted, a ConfigMap named `cluster-monitoring-reverted` is created in the `open-cluster-management-addon-observability` namespace. Any new, manually added alert forward configurations are not reverted from the ConfigMap. 
```

2023-05-16 16:05 UTC, cadawson commented on observability/observability_alerts.adoc
> +Add alerts that you do not want to recieve. You can silence alerts by the alert name, match label, or time duration. After you add the alert that you want to silence, an ID is created. your ID for yo
```suggestion
Add alerts that you do not want to receive. You can silence alerts by the alert name, match label, or time duration. After you add the alert that you want to silence, an ID is created. Your ID for your silenced alert might resemble the following string, `d839aca9-ed46-40be-84c4-dca8773671da`.
```

2023-05-16 16:05 UTC, cadawson commented on observability/observability_alerts.adoc
> +- To silence a {product-title-short} alert, you must have access to the `alertmanager-main` pod in the `open-cluster-management-observability` namespace. For eample, enter the following command in th
```suggestion
- To silence a {product-title-short} alert, you must have access to the `alertmanager-main` pod in the `open-cluster-management-observability` namespace. For example, enter the following command in the pod terminal to silence `SampleAlert`:
```

2023-05-16 16:05 UTC, cadawson commented on observability/observability_alerts.adoc
> +- If you do not require an alert to be silence, expire the silenced alert. To expire a specific silenced alert, run the following command:
```suggestion
- If you no longer want an alert to be silenced, expire the silenced alert by running the following command:
```

2023-05-16 16:05 UTC, cadawson commented on observability/observability_alerts.adoc
> +- To expire all silences, run the following command:
```suggestion
- To expire the silencing of all alerts, run the following command:
```

2023-05-16 16:05 UTC, cadawson commented on observability/observability_alerts.adoc
> +An inhibition rule mutes an alert by retrieving a set of parameter matches when an alert that matches another set of matchers exists. In order for the rule to take effect, both the target and source
The first sentence is confusing to me. Are we saying something like: An inhibition rule mutes an alert when it detects that a set of parameters matches a specified set of parameters.?

2023-05-16 16:05 UTC, cadawson commented on observability/observability_alerts.adoc
> +<1> The `inhibit_rule` parameter section is defined to look for alerts in the same namespace. When a `critical` alert is initiated within a namespace and if there are any other alerts that contain th
In the example, it is `inhibit_rules`, while the description contains `inhibit_rule`. They should probably both be the same.

2023-05-16 16:05 UTC, cadawson commented on observability/observability_alerts.adoc
> +<1> The `inhibit_rule` parameter section is defined to look for alerts in the same namespace. When a `critical` alert is initiated within a namespace and if there are any other alerts that contain th
```suggestion
<1> The `inhibit_rule` parameter section is defined to look for alerts in the same namespace. When a `critical` alert is initiated within a namespace and if there are any other alerts that contain the severity level `warning` or `info` in that namespace, only the `critical` alerts are routed to the AlertManager receiver. The following alerts might be displayed when there are matches:
```

2023-05-16 16:05 UTC, cadawson commented on observability/observability_alerts.adoc
> +<2>If the source and target alert matchers do not match, the alert is routed to the receiver:
It looks like we are using "alert matchers". I thought that was a typo earlier. If that is true, maybe consider using, "the value of the `source_match`, or something? If not, matchers might be ok.

2023-05-16 17:28 UTC, dockerymick commented on observability/observability_alerts.adoc
> +<1> The `inhibit_rule` parameter section is defined to look for alerts in the same namespace. When a `critical` alert is initiated within a namespace and if there are any other alerts that contain th
@cadawson Alertmanager is correct. That is how its referenced in the Prometheus docs: https://prometheus.io/docs/alerting/latest/alertmanager/

2023-05-17 14:35 UTC, dockerymick commented on observability/observability_alerts.adoc
> +When you set the annotation, the alert forwarding configuration on the managed clusters is reverted. Any changes made to the `ocp-monitoring-config` ConfigMap in the `openshift-monitoring` namespace
Updated

2023-05-17 18:04 UTC, dislbenn commented on observability/observability_alerts.adoc
> +//suppressing seems similar to silencing , is my explanation accurate?
@dockerymick I wouldn't say that the alert is suppressing duplicates. It's more on the line that if and when there is an alert that triggers, you can suppress/mute other alerts that match certain criteria.

For example, if I apply a policy on my cluster that has a `high` level severity, and if later on in the day that policy is violated, I would expect to get an alert. The inhibit rule would basically say, there is a `high` level severity alert that needs to be focused on; therefore, suppress any other alerts that are of lower severity, until this one is no longer firing.

2023-05-17 18:06 UTC, dislbenn commented on observability/observability_alerts.adoc
> +<1> The `inhibit_rule` parameter section is defined to look for alerts in the same namespace. When a `critical` alert is initiated within a namespace and if there are any other alerts that contain th
If `Alertmanager` is the correct spelling, then we will probably need to adjust the spelling above also, since there are a few occasions where it is spelled as `AlertManager`.

2023-05-22 17:27 UTC, dockerymick commented on observability/observability_alerts.adoc
> +<2>If the source and target alert matchers do not match, the alert is routed to the receiver:
we are using alert matchers

2023-05-22 17:55 UTC, dockerymick commented on observability/observability_alerts.adoc
> +<1> The `inhibit_rule` parameter section is defined to look for alerts in the same namespace. When a `critical` alert is initiated within a namespace and if there are any other alerts that contain th
Updated instances of Alertmanager

2023-05-22 17:55 UTC, dockerymick commented on observability/observability_alerts.adoc
> +//suppressing seems similar to silencing , is my explanation accurate?
Thanks! Updated!

2023-05-22 17:57 UTC, dockerymick commented
@dislbenn thanks for your feedback! When you have an opportunity, will you re-review the PR?

2023-05-22 17:58 UTC, dockerymick commented
@cadawson When you have an opportunity, will you also re-review?

2023-05-23 13:12 UTC, dislbenn approved these changes
Changes looks good to me! Thanks @dockerymick!

2023-05-23 14:09 UTC, cadawson approved these changes
Looks good. A few comments. Thanks!

2023-05-23 14:09 UTC, cadawson commented on observability/customize_observability.adoc
> +To verify that the alert rules are functioning appropriately, launch the Grafana dashboard, navigate to the *Explore* page, and query `ALERTS`. The alert is only available in Grafana if the alert is
```suggestion
To verify that the alert rules are functioning correctly, launch the Grafana dashboard, navigate to the *Explore* page, and query `ALERTS`. The alert is only available in Grafana if the alert is initiated. 
```

2023-05-23 14:09 UTC, cadawson commented on observability/observability_alerts.adoc
> +=== Disabling forward alerts for managed clusters
Disabling alert forwarding for managed clusters?

2023-05-23 14:09 UTC, cadawson commented on observability/observability_alerts.adoc
> +Disable alert forwarding for managed clusters. Add the following annotation to the `MultiClusterObservability` custom resource:
```suggestion
To disable alert forwarding for managed clusters, add the following annotation to the `MultiClusterObservability` custom resource:
```

2023-05-23 14:09 UTC, cadawson commented on observability/observability_alerts.adoc
> +*Important:* Metrics on your managed cluster are lost if you have a Prometheus instance with a persistent volume for metrics, and the Prometheus instance restarts. However, metrics from the hub clust
Suggestion: Not sure we need "However" here. Maybe just, "Metrics from the hub cluster are not affected."

2023-05-23 14:09 UTC, cadawson commented on observability/observability_alerts.adoc
> +- If you no longer want an alert to be silenced, expire the silenced alert by running the following command:
```suggestion
- If you no longer want an alert to be silenced, end the silenced alert by running the following command:
```

2023-05-23 14:09 UTC, cadawson commented on observability/observability_alerts.adoc
> +- To expire the silencing of all alerts, run the following command:
```suggestion
- To end the silencing of all alerts, run the following command:
```

2023-05-23 14:09 UTC, cadawson commented on observability/observability_alerts.adoc
> +- To expire the silencing of all alerts, run the following command:
If you want to keep "expire," that is ok. I think it looks a little strange, but I see where it might be more accurate in these cases.

2023-05-23 14:09 UTC, cadawson commented on observability/observability_alerts.adoc
> +<1> The `inhibit_rule` parameter section is defined to look for alerts in the same namespace. When a `critical` alert is initiated within a namespace and if there are any other alerts that contain th
I think these are still different. Is that intentional?

2023-05-23 14:23 UTC, dockerymick commented on observability/observability_alerts.adoc
> +<1> The `inhibit_rule` parameter section is defined to look for alerts in the same namespace. When a `critical` alert is initiated within a namespace and if there are any other alerts that contain th
no not intentional, just missed. thanks!

2023-05-23 16:48 UTC, dockerymick commented on observability/observability_alerts.adoc
> +=== Disabling forward alerts for managed clusters
Updated

2023-05-23 16:50 UTC, dockerymick commented
@cadawson @dislbenn thanks for the approvals. I made updates based on the suggestions. Merging this PR

2023-05-23 16:50 UTC, merged