https://issues.redhat.com/browse/ACM-5176 Configure QPS on config policy ctrl
open-cluster-management/rhacm-docs pull request #5100
Opened 2023-05-22 15:24 UTC by dockerymick

https://issues.redhat.com/browse/ACM-5176

2023-05-22 16:52 UTC, dockerymick commented
@JustinKuli great job with the issue and thanks for your patience! When you have an opportunity, will you review the PR? I left a couple of comments in the files.

2023-05-22 17:47 UTC, JustinKuli commented on governance/policy_ctrl_adv_config.adoc
> +Configure the rate of requests to the API server that the configuration policy controller makes on each managed cluster. A higher rate improves the responsiveness of the configuration policy controll
```suggestion
Configure the rate of requests to the API server that the configuration policy controller makes on each managed cluster. A higher rate improves the responsiveness of the configuration policy controller, but also increases the CPU and memory utilization of the Kubernetes API server and OpenShift API server. By default, the rate of requests scales with the `policy-evaluation-concurrency` setting and is set to `30` queries per second (QPS), with a `45` burst value, representing a higher number of requests over short periods of time.
```

I think using "but" instead of "and" is useful here, because it draws attention to the fact that this is a trade-off: there's a good thing - higher responsiveness, and a bad thing - higher resource usage. But if there's a rule to not use "but", I understand.

2023-05-22 17:47 UTC, JustinKuli commented on release_notes/whats_new.adoc
> +//We mention bursts in the doc, so I thought it was appropriate to add here.
Seems good.

2023-05-22 17:47 UTC, JustinKuli commented on governance/policy_ctrl_adv_config.adoc
> +//is there a link to the latest ocp doc?
I couldn't find a similar section in the latest OCP docs. Personally I don't think the link is required.

2023-05-22 17:47 UTC, JustinKuli commented on governance/policy_ctrl_adv_config.adoc
> +//in the issue you mentioned a parameter named `client-max-qps`, where the value is `75` Should that be added to the YAML? Would it be beneficial to list the maximum values?
The `client-qps` annotation here directly corresponds to a `--client-max-qps` argument that the addon-controller uses in the YAML it deploys to the managed cluster. Users generally don't look at that YAML, and they can't edit it (their edits would be overwritten), so I think mentioning `--client-max-qps` could be confusing. I only included it if there were going to be "verification" steps.

There's no limit to the value a user could put here.

2023-05-22 18:15 UTC, dockerymick commented on governance/policy_ctrl_adv_config.adoc
> +Configure the rate of requests to the API server that the configuration policy controller makes on each managed cluster. A higher rate improves the responsiveness of the configuration policy controll
@JustinKuli thanks for explaining that. At first, I didn't interpret increased CPU and memory usage as something negative. From my perspective, it more of a heads up. What are your thoughts about this statement:

A higher rate improves the responsiveness of the configuration policy controller, which also increases the CPU and memory utilization of the Kubernetes API server and OpenShift API server.

2023-05-22 18:15 UTC, dockerymick commented on governance/policy_ctrl_adv_config.adoc
> +//is there a link to the latest ocp doc?
Thanks for confirming, I will remove the link

2023-05-22 18:16 UTC, dockerymick commented on governance/policy_ctrl_adv_config.adoc
> +//in the issue you mentioned a parameter named `client-max-qps`, where the value is `75` Should that be added to the YAML? Would it be beneficial to list the maximum values?
Thanks for confirming, removing my comment

2023-05-22 19:03 UTC, JustinKuli commented on governance/policy_ctrl_adv_config.adoc
> +Configure the rate of requests to the API server that the configuration policy controller makes on each managed cluster. A higher rate improves the responsiveness of the configuration policy controll
That will work!

2023-05-23 13:28 UTC, dockerymick commented
@JustinKuli Thanks for your feedback ! When you have an opportunity, will you re-review the PR?

2023-05-23 13:35 UTC, JustinKuli approved these changes

2023-05-23 16:10 UTC, swopebe commented on governance/policy_ctrl_adv_config.adoc
> +You can configure the rate and burst by setting the `client-qps` and `client-burst` annotations with non-zero integers within quotes. You can set the value on the `ManagedClusterAddOn` object called
object called
changed to _object that is named_

2023-05-23 16:14 UTC, swopebe commented on governance/policy_ctrl_adv_config.adoc
> +You can configure the rate and burst by setting the `client-qps` and `client-burst` annotations with non-zero integers within quotes. You can set the value on the `ManagedClusterAddOn` object called
I just changed to name because that is exactly what it is, but I question the last part of this line, as well.

_in the managed cluster namespace of the hub cluster._ Looking at the YAML, the namespace is `cluster 1`.

Do we mean: ..._in the managed cluster namespace of the hub cluster that is named `cluster1` for this example._

2023-05-23 16:15 UTC, swopebe commented on governance/policy_ctrl_adv_config.adoc
> +You can configure the rate and burst by setting the `client-qps` and `client-burst` annotations with non-zero integers within quotes. You can set the value on the `ManagedClusterAddOn` object called
within quotes

changed to

within quotation marks

2023-05-23 16:20 UTC, swopebe commented on governance/policy_ctrl_adv_config.adoc
> +You can configure the rate and burst by setting the `client-qps` and `client-burst` annotations with non-zero integers within quotes. You can set the value on the `ManagedClusterAddOn` object called
Line 39 has a line in it that is a note in the section above it. 

If this line applies to all, I would 1. Consider placing it at the beginning of the topic and say it applies to all or 2. At minimum build it the same in all sections.

_An increased rate improves the responsiveness of the configuration policy controller, which also increases the CPU and memory utilization of the Kubernetes API server and OpenShift API server_

2023-05-23 16:25 UTC, swopebe commented on release_notes/whats_new.adoc
> +* You can configure the rate of requests and bursts for the API server to change the responsiveness of the configuration policy controller. Read, link:../governance/policy_ctrl_adv_config.adoc#config
no comma after read

2023-05-23 16:28 UTC, swopebe commented on governance/policy_ctrl_adv_config.adoc
you can also change line 17 to:

set `metadata.name` to `config-policy-controller` and namespace to `cluster1` 

or something. 

On these sections, I got a little lost looking at how it was worded and the actual YAML.

2023-05-23 16:28 UTC, swopebe requested changes
Made some small edits, some others discussed in comments

2023-05-23 16:30 UTC, swopebe commented on governance/policy_ctrl_adv_config.adoc
> +You can configure the rate and burst by setting the `client-qps` and `client-burst` annotations with non-zero integers within quotes. You can set the value on the `ManagedClusterAddOn` object called
Increased changed from "higher" because higher can alert a screen reader as a directional word at first...I try to avoid if I can (not always possible)

2023-05-23 23:35 UTC, dockerymick commented
@swopebe thanks so much for your review, suggestions, and changes. When you have an opportunity, will you re-review?

2023-05-24 17:41 UTC, swopebe approved these changes

2023-05-24 17:43 UTC, swopebe commented on release_notes/whats_new.adoc
> +* You can configure the rate of requests and bursts for the API server to change the responsiveness of the configuration policy controller. Read, link:../governance/policy_ctrl_adv_config.adoc#config
still see a comma here, not sure if changes are just not reaching me. Approved to not hold up progress.

2023-05-24 17:43 UTC, swopebe approved these changes
see comments

2023-05-24 18:21 UTC, dockerymick commented on release_notes/whats_new.adoc
> +* You can configure the rate of requests and bursts for the API server to change the responsiveness of the configuration policy controller. Read, link:../governance/policy_ctrl_adv_config.adoc#config
Thanks! I missed this yesterday

2023-05-24 18:37 UTC, dockerymick commented on governance/policy_ctrl_adv_config.adoc
updated

2023-05-24 18:38 UTC, dockerymick commented
Thanks for the approvals! I have made updates based on recent comments. Merging this PR

2023-05-24 18:38 UTC, merged