https://issues.redhat.com/browse/ACM-5166 navigation correction and deletion of YAML on 2.7
open-cluster-management/rhacm-docs pull request #5129
Opened 2023-05-25 18:13 UTC by faaden123

2023-05-25 18:19 UTC, chenz4027 requested changes

2023-05-25 18:19 UTC, chenz4027 commented on clusters/hosted_control_planes/managing_hosted_aws.adoc
I think you missed the deletion of "When you review your information and optionally customize it before creating the cluster, you can select YAML: On to view the YAML content in the panel. You can edit the YAML file with your custom settings, if you have any updates."

2023-05-25 18:26 UTC, faaden123 commented on clusters/hosted_control_planes/managing_hosted_aws.adoc
Thank you. Should be good now.

2023-05-25 18:30 UTC, chenz4027 approved these changes
/lgtm

2023-05-25 18:35 UTC, swopebe approved these changes
Looks great, thank you!

2023-05-26 14:54 UTC, rokej commented on clusters/hosted_control_planes/managing_hosted_aws.adoc
> +To create a hosted control plane cluster from the {mce-short} console, navigate to *Infrastructure* > *Clusters*. On the _Clusters_ page, click *Create cluster* > *Amazon Web Services* > *Hosted* and
The whole documentation after this line is not applicable to a hosted control plane cluster on AWS because there is no UI wizard to create a hosted control plane for AWS. The whole documentation after this line is only applicable to BareMetal Agent platform.

2023-05-26 14:56 UTC, rokej commented on clusters/hosted_control_planes/managing_hosted_aws.adoc
> +To create a hosted control plane cluster from the {mce-short} console, navigate to *Infrastructure* > *Clusters*. On the _Clusters_ page, click *Create cluster* > *Amazon Web Services* > *Hosted* and
So we should move the original content of `Creating a hosted control plane cluster on AWS with the console` into `managing_hosted_bm.adoc` right under the pre-req section and name the section `Creating a hosted control plane cluster on Bare Metal Agent with the console`. In the doc, there is also a section called `Creating a hosted cluster on bare metal`. We should name that section `Creating a hosted cluster on bare metal with CLI`.

2023-05-26 14:57 UTC, rokej commented on clusters/hosted_control_planes/managing_hosted_aws.adoc
> +To create a hosted control plane cluster from the {mce-short} console, navigate to *Infrastructure* > *Clusters*. On the _Clusters_ page, click *Create cluster* > *Amazon Web Services* > *Hosted* and
For BareMetal with Agent platform, we support both UI console and CLI for creating a hosted cluster.

2023-05-26 20:03 UTC, faaden123 commented on clusters/hosted_control_planes/managing_hosted_aws.adoc
> +To create a hosted control plane cluster from the {mce-short} console, navigate to *Infrastructure* > *Clusters*. On the _Clusters_ page, click *Create cluster* > *Amazon Web Services* > *Hosted* and
the steps indicated From the previous section" Important" and on detail the usage of the console with the UI providing more than just information. In this case, the UI only provides information on how to create a cluster.  but it does not walk you through it, which is the reason why these steps have been removed. Additionally, the console on bare metal does which is why this information needs to be moved to another document, which Roke has mentioned. This may need to be a separate request. I will tag @swopebe to confirm if this issue needs to be a separate one.

In terms of the note, @swopebe , I have added a mock note to indicate what I stated and what Roke has emphasized in our meeting about making sure the user knows this. I am unsure of a) the usage of the acronym UI, and my language usage in this sentence( It may need to be longer to make sure users understand this). I will look over the guide and come back with some edits, if any. I would appreciate your constructive criticism on this. 

@chenz4027, if you could go ahead and review the changes to this document as you see fit. Thank you all for your help on one of my very first issues here as an Intern:).  I look forward to your responses.

2023-05-29 14:11 UTC, chenz4027 approved these changes
/lgtm

2023-05-29 14:11 UTC, chenz4027 approved these changes
/lgtm

2023-05-29 15:18 UTC, swopebe commented
@rokej with your changes, coming in pretty late in the release schedule, this will take more time. I will review this with @faaden123 next week after the US holiday.

2023-06-08 14:44 UTC, rokej commented on clusters/hosted_control_planes/managing_hosted_aws.adoc
>  == Deploying a hosted cluster on AWS
Can we change this to `Deploying a hosted cluster on AWS with CLI`?

2023-06-08 14:44 UTC, rokej commented on clusters/hosted_control_planes/managing_hosted_bm.adoc
> +To create a hosted control plane cluster from the {mce-short} console, navigate to *Infrastructure* > *Clusters*. On the _Clusters_ page, click *Create cluster* > *Amazon Web Services* > *Hosted* and
It should be `Create cluster > Host inventory > Hosted control plane`

2023-06-08 14:52 UTC, rokej commented on clusters/hosted_control_planes/managing_hosted_aws.adoc
> +*Note:* After reaching the console, the UI will only provide information on how to create a cluster.
After reaching the console, the UI will only provide basic information on how to create a cluster with CLI. Currently there is no UI wizard to create a cluster.

2023-06-08 15:32 UTC, swopebe commented on clusters/hosted_control_planes/managing_hosted_aws.adoc
> +*Note:* After reaching the console, the UI will only provide information on how to create a cluster.
To avoid dangling modifier:

After you reach the console, use the basic information that is provided to create a cluster in the command line.


CLI is also something that we should not be using

2023-06-08 17:43 UTC, rokej approved these changes

2023-06-08 18:16 UTC, merged