Adding an additional step in automation template for user
open-cluster-management/rhacm-docs pull request #5130
Opened 2023-05-25 19:03 UTC by faaden123

This is an addition of an extra step to help with the template that explains how to create an automation. @robdolares if you could review this change, that would be great! Thank you so much!

2023-05-25 19:51 UTC, robdolares approved these changes
/lgtm

2023-05-26 13:54 UTC, swopebe requested changes

2023-05-26 13:54 UTC, swopebe commented on clusters/cluster_lifecycle/ansible_config_cluster.adoc
> +. Once a credential has been selected, you can select an Ansible inventory to use for all the jobs. To link an Ansible credential to an Ansible template, complete the following steps:
Here is where writing concisely, in active voice, sets tech writing apart. Please take some time to review the style manual here to see what is said about the word "Once" and avoiding past participles (has been).

Rewrite as such (but please do take a min to study the guide):

After you select a credential, ....

2023-05-26 17:36 UTC, faaden123 commented on clusters/cluster_lifecycle/ansible_config_cluster.adoc
> +. Once a credential has been selected, you can select an Ansible inventory to use for all the jobs. To link an Ansible credential to an Ansible template, complete the following steps:
Got it, Thank you.

2023-05-31 19:06 UTC, faaden123 commented on clusters/cluster_lifecycle/ansible_config_cluster.adoc
> +. Once a credential has been selected, you can select an Ansible inventory to use for all the jobs. To link an Ansible credential to an Ansible template, complete the following steps:
@swopebe If you have a chance to review this again as I made the necessary changes! Thank you:)

2023-06-02 14:30 UTC, swopebe approved these changes
Looks good

2023-06-02 14:37 UTC, merged