acm4861 add nodeselector and tolerations
open-cluster-management/rhacm-docs pull request #5137
Opened 2023-05-29 13:56 UTC by cadawson

2023-05-29 14:49 UTC, cadawson commented
Hi @skeeey and @elgnay. I have a draft of this content, but I also have a proposal. I propose that we add this procedure to the advanced configuration topics. If we do that, then we can have it placed in one place, and don't have to maintain it in multiple places. We can add it there, and add a reference to it in all of the creating a cluster groups, as I have added to the AWS file. The advanced configuration topic is still not created, and is in another PR right now. Does this sound ok? Thanks!

2023-05-30 09:24 UTC, skeeey commented
@cadawson +1, I think the config part is a common part for all types cluster and the cluster addons

2023-06-01 10:49 UTC, elgnay commented on clusters/cluster_lifecycle/import_gui.adoc
> +. Add the `tolerations` entry to the managed cluster YAML definition. The key of this annotation is: `open-cluster-management/tolerations`. The value of this annotation represents a [toleration](http
> list with json `formatAfter` adding the values. 

Looks weird. It might be

> list with json formatting.

2023-06-01 10:49 UTC, elgnay commented on clusters/cluster_lifecycle/import_gui.adoc
> +
Please remove the unnecessary blank line.

2023-06-05 02:53 UTC, elgnay commented
/lgtm

2023-06-06 20:04 UTC, swopebe commented on clusters/cluster_lifecycle/create_ocp_aws.adoc
>  The name of the cluster is used in the hostname of the cluster.
did we double check hostname or host name here?

2023-06-06 20:05 UTC, swopebe commented on clusters/cluster_lifecycle/import_gui.adoc
> +. Add the `nodeSelector` annotation to the managed cluster YAML definition. The key for this annotation is: `open-cluster-management/nodeSelector`. The value of this annotation is a string map with j
json or JSON?

2023-06-06 20:08 UTC, swopebe requested changes
couple minor questions/comments

2023-06-06 20:08 UTC, swopebe commented on clusters/cluster_lifecycle/import_gui.adoc
> +  # other metadata
Please see of you can clean up the #comments in the YAML samples, which clutter the doc. I checked with OCP and they usually try to clean them up, as well. You can usually just make an update before or after with the same info, which is what I have been doing with these.

2023-06-06 20:08 UTC, swopebe commented on clusters/release_notes/whats_new.adoc
> +- To add flexibility, you can now configure your managed cluster klusterlet to run on specific nodes by specifying the values for `nodeSelector` and `tolerations`. See xref:../cluster_lifecycle/impor
can you please add what the flexibility is for?

To add flexibility to your _____

2023-06-06 20:08 UTC, swopebe commented on clusters/cluster_lifecycle/import_gui.adoc
Wondering if these links should be in == Additional resources ? (the ones above, as well)

2023-06-12 09:34 UTC, elgnay commented
/lgtm

2023-06-12 14:00 UTC, oafischer commented on clusters/cluster_lifecycle/create_aws_govcloud.adoc
Is this PR using the newest 2.8_stage? There is a broken link it this file (Control access to VPC endpoints using endpoint policies) that was fixed last week in the link check issue.

2023-06-12 14:48 UTC, cadawson commented on clusters/cluster_lifecycle/create_aws_govcloud.adoc
Probably not. I pulled, but had to add a file that did not come over. @oafischer

2023-06-12 14:57 UTC, oafischer commented on clusters/cluster_lifecycle/create_aws_govcloud.adoc
I'll approve, just make sure to include any fixed cluster links from here: https://issues.redhat.com/browse/ACM-5801

I think there might only be one.

2023-06-12 14:57 UTC, oafischer approved these changes

2023-06-12 15:24 UTC, merged