https://issues.redhat.com/browse/ACM-5510 Updating object-templates-raw
open-cluster-management/rhacm-docs pull request #5141
Opened 2023-05-30 16:46 UTC by dockerymick

https://issues.redhat.com/browse/ACM-5510

2023-05-31 16:01 UTC, mprahl commented on governance/config_policy_ctrl.adoc
>    object-templates-raw: |
@dockerymick we can't have both `object-templates` and `object-templates-raw` defined in the same `ConfigurationPolicy`. This is why a separate example is required.

2023-06-01 15:18 UTC, dockerymick commented on governance/config_policy_ctrl.adoc
>    object-templates-raw: |
@mprahl understood, well i can remove the info out of object-templates-raw section in the YAML. I will only add the info in the table. I recommend that we keep the single, semi-empty sample and not add a separate example for object-templates-raw.

2023-06-01 18:53 UTC, dhaiducek commented on governance/config_policy_ctrl.adoc
>    object-templates-raw: |
@dockerymick That makes sense for this YAML sample. I think more examples of `object-templates-raw` are still desired in the documentation, so would that mean we should create a new section in one of these to flesh out more examples?
- https://github.com/stolostron/rhacm-docs/blob/2.8_stage/governance/template_support_intro.adoc
- https://github.com/stolostron/rhacm-docs/blob/2.8_stage/governance/template_functions.adoc
- https://github.com/stolostron/rhacm-docs/blob/2.8_stage/governance/adv_template_process.adoc

2023-06-01 19:05 UTC, dhaiducek requested changes
Thanks for the updates! I have a few more updates for this PR.

2023-06-01 19:05 UTC, dhaiducek commented on governance/config_policy_ctrl.adoc
There are a couple updates here:
- The note in the `spec.object-templates`/`spec.object-templates-raw` sections should not have the phrase "at least" since one or the other is required but can't have both.
- Remove the `spec.object-templates-raw.spec` row entirely since that field doesn't exist. `spec.object-templates-raw` is a string, so all doc about it should be there, but I think removing all of this content and moving the `object-templates-raw` example from the YAML sample to the table would work for now.

2023-06-01 19:21 UTC, dockerymick commented on governance/config_policy_ctrl.adoc
>    object-templates-raw: |
Thanks for the suggestions Dale. From my perspective, I would add the example and short description to the [Advanced template processing in configuration policies](https://github.com/stolostron/rhacm-docs/blob/2.8_stage/governance/adv_template_process.adoc) doc

2023-06-05 20:13 UTC, dockerymick commented on governance/config_policy_ctrl.adoc
>    object-templates-raw: |
Updated this resolving the conversation

2023-06-05 20:14 UTC, dockerymick commented on governance/config_policy_ctrl.adoc
Updated

2023-06-05 20:15 UTC, dockerymick commented
thanks for the suggestions and feedback. @mprahl @dhaiducek will either of you provide another review please?

2023-06-05 20:41 UTC, oafischer approved these changes
lgtm

2023-06-05 21:04 UTC, dockerymick commented
@oafischer thanks for your approval Oliver!

2023-06-06 12:42 UTC, mprahl commented on governance/adv_template_process.adoc
> +Set object templates with a raw YAML string. The `object-template-raw` parameter is an optional parameter that support if-else statements. You can specify conditions `object-templates` specification.
```suggestion
Set object templates with a YAML string representation. The `object-template-raw` parameter is an optional parameter that support if-else statements. You can specify conditions in the `object-templates` specification. The following example is defined to add the `species-category: mammal` label  to any ConfigMap in the `default` namespace that has a `name` key equal to `Sea Otter`:
```

2023-06-06 12:43 UTC, mprahl commented on governance/adv_template_process.adoc
> +    {{- end }}
This should all be indented.

2023-06-06 12:43 UTC, mprahl commented on governance/adv_template_process.adoc
> +object-templates:
You can't specify both object-templates and object-templates-raw.
```suggestion
```

2023-06-06 12:45 UTC, mprahl commented on governance/config_policy_ctrl.adoc
>    object-templates-raw: |
If this is the baseline sample, I think it should use `object-templates` like it used to. `object-templates-raw` is for advanced cases only.

2023-06-07 15:17 UTC, dockerymick commented on governance/config_policy_ctrl.adoc
>    object-templates-raw: |
@mprahl thanks for your feedback. So should I remove the entire `object-templates-raw` parameter and value from the sample and table?

2023-06-07 15:59 UTC, dockerymick commented on governance/adv_template_process.adoc
> +    {{- end }}
Updated based on the example that is provided in the issue

2023-06-08 00:28 UTC, dhaiducek commented on governance/config_policy_ctrl.adoc
>    object-templates-raw: |
@dockerymick Don't remove it from the table--just from the sample.

2023-06-08 00:34 UTC, dhaiducek commented on governance/adv_template_process.adoc
> +Set object templates with a YAML string representation. The `object-template-raw` parameter is an optional parameter that support if-else statements. You can specify conditions in the `object-templat
if-else is one example of many functions, so I think mentioning `range` and implying there are more would be good.
```suggestion
Set object templates with a YAML string representation. The `object-template-raw` parameter is an optional parameter that supports advanced templating use-cases such as if-else and the `range` function. The following example is defined to add the `species-category: mammal` label  to any ConfigMap in the `default` namespace that has a `name` key equal to `Sea Otter`:
```

2023-06-08 00:35 UTC, dhaiducek commented on governance/config_policy_ctrl.adoc
> +| Used to set object templates with a raw YAML string. Specify conditions for the object templates, where if-else statements are supported values. For example, add the following value to avoid duplic
```suggestion
| Used to set object templates with a raw YAML string. Specify conditions for the object templates, where advanced functions like if-else statements and the `range` function are supported values. For example, add the following value to avoid duplication in your `object-templates` definition:
```

2023-06-08 17:17 UTC, dockerymick commented
@dhaiducek thanks for your feedback. I removed the parameter from the sample. When you have an opportunity, will you re-review?

2023-06-08 20:06 UTC, dhaiducek requested changes
Looking good! One minor update to match the other notes from the table.

2023-06-08 20:06 UTC, dhaiducek commented on governance/adv_template_process.adoc
> +*Note:* While `spec.object-templates` and `spec.object-templates-raw` are optional, at least one of the two parameter fields must be set.
```suggestion
*Note:* While `spec.object-templates` and `spec.object-templates-raw` are optional, one of the two parameter fields must be set.
```

2023-06-09 15:25 UTC, dockerymick commented
@dhaiducek thank you again Dale! I accepted your suggestion, are you ok with us merging?

2023-06-12 12:50 UTC, mprahl approved these changes

2023-06-12 13:35 UTC, merged