https://issues.redhat.com/browse/ACM-4743 Adenf4743
open-cluster-management/rhacm-docs pull request #5151
Opened 2023-06-01 19:35 UTC by faaden123

Went ahead and changed this clarification on upgrades to match the one for RHACM. This was from a mock draft to kind of utilize what was already written by Brandi and adding some more information from the jira issue. 

Not sure if the " see upgrading for details" is the same for RHACM. This is information I may need further clarification on.

2023-06-08 15:15 UTC, dockerymick requested changes

2023-06-08 15:15 UTC, dockerymick commented on clusters/release_notes/whats_new.adoc
> +You can now rely on the {olm} `operatorcondition` resource to enforce an efficient {mce-short} upgrade procedure, which will prevent errors from attempts to skip releases. See link:../install_upgrade
Remember to use [active tone](https://www.ibm.com/docs/en/ibm-style?topic=grammar-verbs#tense). When I read "rely", i interpreted the procedure to be reliable as if it was a person, which is an example of Anthropomorphism: https://www.ibm.com/docs/en/ibm-style?topic=grammar-anthropomorphism

```suggestion
You can now use the {olm} `operatorcondition` resource to enforce the {mce-short} upgrade procedure, which prevent errors from attempts to skip releases. See link:../install_upgrade/upgrade_cluster.adoc#upgrading[Upgrading] for details.
```

2023-06-09 12:04 UTC, faaden123 commented on clusters/release_notes/whats_new.adoc
> +You can now rely on the {olm} `operatorcondition` resource to enforce an efficient {mce-short} upgrade procedure, which will prevent errors from attempts to skip releases. See link:../install_upgrade
Thank you for your review!

2023-06-09 14:09 UTC, JakobGray reviewed
I didn't see any more details in `install_upgrade/upgrade_cluster.adoc` and that looks to be about updating managed clusters rather than MCE version so I don't think that sentence is necessary. 

Based on the above line:
> If any new features exist for {mce-short} install only, you can view them in this section.
It sounds like a release note isn't necessary for MCE at all because the operatorcondition isn't MCE only.

2023-06-09 14:53 UTC, dockerymick approved these changes

2023-06-13 14:33 UTC, faaden123 commented
> I didn't see any more details in `install_upgrade/upgrade_cluster.adoc` and that looks to be about updating managed clusters rather than MCE version so I don't think that sentence is necessary.
> 
> Based on the above line:
> 
> > If any new features exist for {mce-short} install only, you can view them in this section.
> 
> It sounds like a release note isn't necessary for MCE at all because the operatorcondition isn't MCE only.

Ah- I see the sentence prior to this added note. 

> I didn't see any more details in `install_upgrade/upgrade_cluster.adoc` and that looks to be about updating managed clusters rather than MCE version so I don't think that sentence is necessary.
> 
> Based on the above line:
> 
> > If any new features exist for {mce-short} install only, you can view them in this section.
> 
> It sounds like a release note isn't necessary for MCE at all because the operatorcondition isn't MCE only.

I've taken the link out, but are you saying this note is not needed entirely?

2023-06-13 14:59 UTC, merged

2023-06-13 15:08 UTC, JakobGray commented
I would say nothing more needs to be added since the operatorcondition isn't user controlled anyway