acm5430 deploy cluster cli 2.8
open-cluster-management/rhacm-docs pull request #5153
Opened 2023-06-02 20:46 UTC by cadawson

2023-06-04 15:35 UTC, cadawson commented
Hi @carbonin and @berenss. Getting started with a draft of this content, as it sounds like it might be important for other issues. I am not sure if I will keep the section formatting or remove it in favor of steps as a list. I thought it would be good to get a start reviewing it asap. This is the 2.8 version. Take a look and see if it is what you think we need. Thanks!

2023-06-05 21:33 UTC, berenss approved these changes
This looks great to me but I have to be honest that I did not test any of these technical steps and I have not ever attempted this flow (usually a UI person here) so I cannot claim any technical review. Perhaps suggest another reviewer like @levenhagen that might like to try it out?

2023-06-06 13:13 UTC, carbonin commented on clusters/cluster_lifecycle/create_cluster_on_prem.adoc
> +  .dockerconfigjson: '{"auths":{"cloud.openshift.com":{"auth":"your-secret-here","email":"user@example.com"}}}'
This isn't quite correct. This needs to contain more than just `cloud.openshift.com` auth.

For example, I'd expect `quay.io` and `registry.redhat.io` auth as well in here.
Maybe it's best to just remove this sample text in favor of a single placeholder? Something like:

```
  .dockerconfigjson: 'your-pull-secret-json'
```

2023-06-06 13:13 UTC, carbonin commented on clusters/cluster_lifecycle/create_cluster_on_prem.adoc
> +               bla: aaa
@nmagnezi @filanov do you know if we need this?

Seems strange to put this in official documentation.

2023-06-06 13:13 UTC, carbonin commented on clusters/cluster_lifecycle/create_cluster_on_prem.adoc
> +         name: pull-secret  # Use the pull secret name mentioned in Cluster Prerequisites step 2
Indentation looks off here.

2023-06-06 13:13 UTC, carbonin commented on clusters/cluster_lifecycle/create_cluster_on_prem.adoc
> +  pullSecretRef: # currently ignored by InfraEnv controller
This is not true. This is very much used.

2023-06-06 13:13 UTC, carbonin commented on clusters/cluster_lifecycle/create_cluster_on_prem.adoc
> +The `Agent` resource is created automatically. It is registered to the cluster and represents a host that can boot from a discovery image.
```suggestion
The `Agent` resource is created automatically. It is registered to the cluster and represents a host that has booted from a discovery image. 
```

2023-06-12 10:51 UTC, filanov commented on clusters/cluster_lifecycle/create_cluster_on_prem.adoc
> +               bla: aaa
Agree, suggesting to put something more meaningful, for example location or something like that

2023-06-13 13:38 UTC, cadawson commented on clusters/cluster_lifecycle/create_cluster_on_prem.adoc
> +  .dockerconfigjson: '{"auths":{"cloud.openshift.com":{"auth":"your-secret-here","email":"user@example.com"}}}'
Should we include a list of what it might include, or is it clear enough with just the generic 'your-pull-secret-json'?

2023-06-21 12:22 UTC, carbonin commented on clusters/cluster_lifecycle/create_cluster_on_prem.adoc
> +  .dockerconfigjson: '{"auths":{"cloud.openshift.com":{"auth":"your-secret-here","email":"user@example.com"}}}'
I think the substitute is enough. I'm also not sure what all the different bits of this might be and those might change over time.

2023-07-21 19:20 UTC, dockerymick requested changes
suggestion to fix linter

2023-07-21 19:20 UTC, dockerymick commented on clusters/cluster_lifecycle/create_cluster_on_prem.adoc
> +    name: pull-secret
```suggestion
    name: pull-secret <2>
```

2023-07-24 10:54 UTC, cadawson commented
HI @carbonin. I made the requested changes. I asked QE to take a look at it to makes sure that it looks ok. Ramon requested that we look at adding an optional step or two that are required when deploying on Nutanix. Can you help with that piece? Thanks!

2023-07-24 12:32 UTC, carbonin commented on clusters/cluster_lifecycle/create_cluster_on_prem.adoc
> +<1> Add the name of your pull secret authentication file. For example, this can include a `cloud.openshift.com`, `quay.io`, or `registry.redhat.io` authentication.
This is not a file name, it's the actual pull secret content.

2023-07-24 12:32 UTC, carbonin commented on clusters/cluster_lifecycle/create_cluster_on_prem.adoc
> +<1> Your release image might change as you update your cluster.
This isn't relevant for update after the cluster is installed.

2023-07-24 12:32 UTC, carbonin commented on clusters/cluster_lifecycle/create_cluster_on_prem.adoc
> +<3> Optional: You can specify your ssh public key, which connects the hub to the machines that were booted from the discovery ISO.
This just allows the user access to the host when it is booted with the discovery iso.
It doesn't have anything to do with the hub accessing the host as we don't have the private key.

2023-07-24 12:32 UTC, carbonin commented on clusters/cluster_lifecycle/create_cluster_on_prem.adoc
> +kubectl -n sample-namespace patch agents.agent-install.openshift.io 07e80ea9-200c-4f82-aff4-4932acb773d4 -p '{"spec":{"approved":true}}' --type merge
`oc` rather than `kubectl` maybe?

2023-07-24 12:33 UTC, carbonin commented
>Ramon requested that we look at adding an optional step or two that are required when deploying on Nutanix. Can you help with that piece? Thanks!

Do you have a link to this request? I'm not familiar with exactly what you're talking about here.

2023-08-01 18:26 UTC, cadawson commented
Hi @carbonin. You can see the request in this document: https://docs.google.com/document/d/174bDNxKSep9l6skaRl2pwAOyWKZT8z8WKTeombSh6bA/edit. 

The request to cover Nutanix is https://issues.redhat.com/browse/MGMT-13374.

2023-08-01 18:28 UTC, carbonin commented
Okay I think we should handle Nutanix-specific stuff as a separate PR. Lets get the basics in first.

2023-08-07 14:30 UTC, chadcrum commented
Testing in progress by QE fyi

2023-08-07 14:54 UTC, chadcrum commented on clusters/cluster_lifecycle/create_cluster_on_prem.adoc
> +stringData:
`stringData:` should just be `data:`

2023-08-07 15:04 UTC, chadcrum commented on clusters/cluster_lifecycle/create_cluster_on_prem.adoc
> +stringData:
Actually nevermind - stringData works here. stringData will take the pull secret as a string, convert to base64, and move to the `data:` field.

2023-08-07 15:11 UTC, chadcrum approved these changes
Tested by QE - lgtm

2023-08-08 19:32 UTC, cadawson commented
Hi @carbonin. The QE team has kindly run through this as a test, and it worked. Are we ok to peer review and merge this content into 2.8? Are there changes required for 2.7 and 2.9, or is the procedure the same? Thanks!

2023-08-09 15:06 UTC, carbonin reviewed
A few minor comments. Looks good otherwise though!

2023-08-09 15:06 UTC, carbonin commented on clusters/cluster_lifecycle/create_cluster_on_prem.adoc
> +You can also create a single-node cluster without the console by using the assisted installer feature within the Central Infrastructure Management component. After you complete this procedure, you ca
Why say "single-node" here. We can create any size cluster.

2023-08-09 15:06 UTC, carbonin commented on clusters/cluster_lifecycle/create_cluster_on_prem.adoc
> +*Note:* If you plan to iclude the optional `NMStateConfig` custom resource, the `InfraEnv` custom resource must be created after you create and apply the `NMStateConfig` custom resource.
```suggestion
*Note:* If you plan to include the optional `NMStateConfig` custom resource, the `InfraEnv` custom resource must be created after you create and apply the `NMStateConfig` custom resource. 
```

2023-08-09 15:06 UTC, carbonin commented on clusters/cluster_lifecycle/create_cluster_on_prem.adoc
> +*Note:* If you plan to iclude the optional `NMStateConfig` custom resource, the `InfraEnv` custom resource must be created after you create and apply the `NMStateConfig` custom resource.
Also I'm pretty sure this isn't true. You should be able to create them in either order and edit the nmstate after the infraenv is created as long as you re-download the ISO after the change.

2023-08-09 15:06 UTC, carbonin commented on clusters/cluster_lifecycle/create_cluster_on_prem.adoc
> +<3> Optional: You can include your ssh public key.
Do you want to add an additional explanation here like you did you infraenv?

Maybe "which allows you to access the host after it is installed"?

2023-08-09 15:06 UTC, carbonin commented on clusters/cluster_lifecycle/create_cluster_on_prem.adoc
> +oc -n sample-namespace patch agents.agent-install.openshift.io 07e80ea9-200c-4f82-aff4-4932acb773d4 -p '{"spec":{"approved":true}}' --type merge
I think it should be obvious, but do we need to note that this uuid won't always be the same? Or just add a placeholder here like `<agent name>`?

Maybe move the note about how the agent resource is created before this section?

2023-08-09 20:04 UTC, cadawson commented on clusters/cluster_lifecycle/create_cluster_on_prem.adoc
> +*Note:* If you plan to iclude the optional `NMStateConfig` custom resource, the `InfraEnv` custom resource must be created after you create and apply the `NMStateConfig` custom resource.
Made a minor change to the wording, based on the comment.

2023-08-09 21:38 UTC, dockerymick approved these changes
Made some suggestions

2023-08-09 21:38 UTC, dockerymick commented on clusters/cluster_lifecycle/create_cluster_on_prem.adoc
> +- For additional information about how to use zero touch provisioning, see https://access.redhat.com/documentation/en-us/openshift_container_platform/4.13/html/scalability_and_performance/ztp-deployi
2 broken links

```suggestion
- For additional information about how to use zero touch provisioning, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.13/html/scalability_and_performance/ztp-deploying-disconnected[Clusters at the network far edge] in the {ocp-short} documentation.
```

<img width="1028" alt="Screenshot 2023-08-09 at 5 24 24 PM" src="https://github.com/stolostron/rhacm-docs/assets/60616885/511675d2-6ff7-47bb-a3c9-f7570816b308">

2023-08-09 21:38 UTC, dockerymick commented on clusters/cluster_lifecycle/create_cluster_on_prem.adoc
> +<3> You can specify your ssh public key, which enables you to access the host after it is installed.
ssh should be capital 
```suggestion
<3> You can specify your SSH public key, which enables you to access the host after it is installed. 
```

2023-08-09 21:38 UTC, dockerymick commented on clusters/cluster_lifecycle/create_cluster_on_prem.adoc
> +<1> Replace the `clusterDeployment` resource name from <<on-prem-creating-your-cluster-with-the-cli-clusterdeployment,Create the ClusterDeployment>>.
Instead of using the inline link can you italicize this? Because this is within the file, it doesn't need to go in Additional resources. Link references that direct the user to a different file or folder should be added to the Additional resources section

2023-08-09 21:38 UTC, dockerymick commented on clusters/cluster_lifecycle/create_cluster_on_prem.adoc
> +Continue with xref:../cluster_lifecycle/access_cluster.adoc#accessing-your-cluster[Accessing your cluster] to access your cluster.
I recommend that you italicize the link reference text and move this link to Additional resources. 
```suggestion
Continue with _Accessing your cluster_, which can be found in the _Additional resources_ section, to access your cluster.
```

Or something similar

2023-08-09 21:38 UTC, dockerymick commented on clusters/cluster_lifecycle/create_cluster_on_prem.adoc
> +You need a namespace for your resources. It is more convenient to keep all of the resources in a shared namespace. This example uses `sample-namespace` for the name of the namespace, but you can use
```suggestion
You need a namespace for your resources. It is more convenient to keep all of the resources in a shared namespace. This example uses `sample-namespace` for the name of the namespace, but you can use any name except `assisted-installer`. Create a namespace by creating and applying the following file:
```

2023-08-11 18:06 UTC, cadawson commented on clusters/cluster_lifecycle/create_cluster_on_prem.adoc
> +You need a namespace for your resources. It is more convenient to keep all of the resources in a shared namespace. This example uses `sample-namespace` for the name of the namespace, but you can use
This one seems easy to miss. Ha!

2023-08-11 18:07 UTC, cadawson commented on clusters/cluster_lifecycle/create_cluster_on_prem.adoc
> +Continue with xref:../cluster_lifecycle/access_cluster.adoc#accessing-your-cluster[Accessing your cluster] to access your cluster.
Leaving this, as it is the end of the procedure and the continuation from that point on.

2023-08-11 19:27 UTC, cadawson commented
Ok @carbonin, I think we are good with this one. Does it work with 2.7 and 2.9, as well? Please approve, if it looks ok. Thanks!

2023-08-17 12:47 UTC, carbonin approved these changes

2023-08-21 11:47 UTC, merged