https://issues.redhat.com/browse/ACM-5763
open-cluster-management/rhacm-docs pull request #5166
Opened 2023-06-07 15:36 UTC by faaden123

I have left out the potential of another addition to the known issues. It may need another addition on the difference in wording of label expression and cluster selector.

2023-06-07 15:40 UTC, oafischer commented on release_notes/known_issues_console.adoc
Make sure to remove any future tense.

2023-06-07 15:57 UTC, dockerymick requested changes

2023-06-07 15:57 UTC, dockerymick commented on release_notes/known_issues_console.adoc
> +[#editapplication set expand feature repeats]
anchors require a dash 
```suggestion
[#editapplicationset-expand-feature-repeats]
```

2023-06-07 15:57 UTC, dockerymick commented on release_notes/known_issues_console.adoc
> +== EditApplicationSet expand feature repeats
We typically italicize resource names in the section title. This is because the resource names are monospaced according to the IBM Style Guide. I recommend that you italicize "EditApplicationSet"

```suggestion
== _EditApplicationSet_ expand feature repeats
```

2023-06-07 15:57 UTC, dockerymick commented on release_notes/known_issues_console.adoc
> +When making edits to your ApplicationSet on placement, you may encounter the recurrence of "expand to enter expression" when you attempt to enter your cluster selector. You will be able to enter your
What is `ApplicationSet` on placement? ApplicationSet and Placement are both resource types. I read through the issue and saw some of the pictures 

```suggestion
When you add multiple label expressions or attempt to enter your cluster selector for your `ApplicationSet`, you might receive the following message repeatedly,  "Expand to enter expression". You can enter your cluster selection despite this issue.
```

2023-06-07 16:15 UTC, swopebe commented on release_notes/known_issues_console.adoc
> +[#editapplication set expand feature repeats]
I am not sure we typically write **To work around** or **As a work around**?

Let's eliminate "might not be able" here. We need to think of the most concise way (avoiding extra words) to phrase things.

Example: Active, concise

After you provision a hosted control plane cluster, you might lose part of the `ClusterVersionUpgradeable` parameter when you scroll horizontally in the cluster overview of the {product-title-short} console. 

To resolve this issue, zoom out by using your browser zoom controls, increase your console window size, or copy and paste the text to a different location.

2023-06-07 16:16 UTC, swopebe commented on release_notes/known_issues_console.adoc
> +[#editapplication set expand feature repeats]
mentioning product one time should suffice here in a short entry.

2023-06-07 16:17 UTC, swopebe commented on release_notes/known_issues_console.adoc
> +When making edits to your ApplicationSet on placement, you may encounter the recurrence of "expand to enter expression" when you attempt to enter your cluster selector. You will be able to enter your
That is also a good example of active voice @dockerymick , thanks for showing this.

2023-06-08 20:03 UTC, dockerymick approved these changes
looks good Faisa! Thanks for the update

2023-06-08 21:05 UTC, merged