Add disabling GRC known issue
open-cluster-management/rhacm-docs pull request #5180
Opened 2023-06-09 21:31 UTC by dhaiducek

It's rather detailed and technical, but let me know whether I might need to move it to Troubleshooting--I wasn't sure on that.

I also migrated a `2.7` item about `stringData` not being handled properly by GRC.

ref: https://issues.redhat.com/browse/ACM-5632

2023-06-12 12:46 UTC, mprahl commented on release_notes/known_issues_governance.adoc
> +- The `objectDefinition` in the `ConfigurationPolicy` does not match because Kubernetes processing the object when the policy is applied.
```suggestion
- The `objectDefinition` in the `ConfigurationPolicy` does not match because of Kubernetes processing the object when the policy is applied.
```

2023-06-12 12:46 UTC, mprahl commented on release_notes/known_issues_governance.adoc
> +| The `stringData` map is processed by Kubernetes to `data` with `base64` encoded values. Instead of using `stringData`, use `data` directly with `base64` encoded values instead of strings.
```suggestion
| The `stringData` map is converted by Kubernetes to `data` with `base64` encoded values. Instead of using `stringData`, use `data` directly with `base64` encoded values instead of strings.
```

2023-06-12 14:54 UTC, mprahl commented on release_notes/known_issues_governance.adoc
> +To resolve the issue, disable the policy and compare the differences between `objectDefinition` in the policy and the object on the managed cluster. If the keys are different or missing, Kubernetes m
After thinking about this, disabling the policy might be dangerous because of `pruneObjectBehavior`. Perhaps add a warning here or you could recommend increasing the evaluation interval.

2023-06-12 14:54 UTC, mprahl commented on release_notes/known_issues_governance.adoc
> +When disabling the Governance deployments, if Governance is disabled in the MultiClusterHub object, the deployments do not all get cleaned up properly. To disable Governance so that the deployments a
I'm not sure if this is required.
```suggestion
When disabling the Governance deployments, if Governance is disabled in the `MultiClusterHub` object, the deployments do not all get cleaned up properly. To disable Governance so that the deployments also get cleaned up:
```

2023-06-12 14:55 UTC, mprahl commented on release_notes/known_issues_governance.adoc
> +. Disable the `policyController` in the KlusterletAddonConfig for the managed cluster. If doing this for all managed clusters, this loop will handle it:
```suggestion
. Disable the `policyController` in the `KlusterletAddonConfig` for the managed cluster. If doing this for all managed clusters, this loop will handle it:
```

2023-06-12 15:18 UTC, dhaiducek commented on release_notes/known_issues_governance.adoc
> +When disabling the Governance deployments, if Governance is disabled in the MultiClusterHub object, the deployments do not all get cleaned up properly. To disable Governance so that the deployments a
Are you wondering whether disabling the `KlusterletAddonConfig` is required?

2023-06-12 15:58 UTC, mprahl commented on release_notes/known_issues_governance.adoc
> +When disabling the Governance deployments, if Governance is disabled in the MultiClusterHub object, the deployments do not all get cleaned up properly. To disable Governance so that the deployments a
Sorry, I meant the back ticks

2023-06-12 16:00 UTC, dhaiducek commented on release_notes/known_issues_governance.adoc
> +When disabling the Governance deployments, if Governance is disabled in the MultiClusterHub object, the deployments do not all get cleaned up properly. To disable Governance so that the deployments a
Ah, gotcha. I like them--I think it's good for consistency and to signal that it's a code reference.

2023-06-12 16:00 UTC, dhaiducek commented on release_notes/known_issues_governance.adoc
> +To resolve the issue, disable the policy and compare the differences between `objectDefinition` in the policy and the object on the managed cluster. If the keys are different or missing, Kubernetes m
That's a good point. I'll add a note.

2023-06-12 19:02 UTC, dockerymick commented
Will review this soon!

2023-06-13 15:17 UTC, dockerymick commented on release_notes/known_issues_governance.adoc
> +*NOTE:* If `pruneObjectBehavior` has been set to something other than `none`, disabling the policy will cause the objects to be cleaned up. In this case, set `prunObjectBehavior` to `none` so that th
```suggestion
*Note:* If `pruneObjectBehavior` is set to something other than `none`, disabling the policy causes the objects to be cleaned up. In this case, set `prunObjectBehavior` to `none` so that the objects exist after the policy is disabled.
```

2023-06-13 15:21 UTC, dockerymick commented on release_notes/known_issues_governance.adoc
> +|===
I really like the idea of using the table, but because there is only one example we should not use a table. In the case that we decide to list another example, let's go with the table approach.

```suggestion
For example, the `stringData` map in a `Secret` resource is converted by Kubernetes to `data` with `base64` encoded values. Instead of using `stringData`, use `data` directly with `base64` encoded values instead of strings.
```

2023-06-13 15:22 UTC, dockerymick commented on release_notes/known_issues_governance.adoc
> +When disabling the Governance deployments, if Governance is disabled in the `MultiClusterHub` object, the deployments do not all get cleaned up properly. To disable Governance so that the deployments
```suggestion
When you disable governance deployments in the `MultiClusterHub` object, the deployments do not all get cleaned up properly. Complete the following steps to disable governance so that the deployments also get cleaned up:
```

2023-06-13 15:24 UTC, dockerymick commented on release_notes/known_issues_governance.adoc
> +. Disable the `policyController` in the `KlusterletAddonConfig` for the managed cluster. If doing this for all managed clusters, this loop will handle it:
```suggestion
. Disable the `policyController` in the `KlusterletAddonConfig` for the managed cluster. If you do this for all managed clusters, run the following command:
```

2023-06-13 15:28 UTC, dockerymick commented on release_notes/known_issues_governance.adoc
> +. (For self-managed hubs only) A self-managed hub's `governance-policy-framework-uninstall` pod will go into `CrashLoopBackOff` because it is in conflict with the `governance-policy-propagator` pod.
```suggestion
. (For self-managed hub clusters only) Delete the `ManifestWork` for the self-managed hub cluster and remove the finalizer on the `ManagedClusterAddon` if the `governance-policy-framework-uninstall` pod of a self-managed hub cluster is in `CrashLoopBackOff`. Run the following commands:
```

2023-06-13 15:45 UTC, dockerymick commented on release_notes/known_issues_governance.adoc
> +. Now that Governance is disabled on the managed clusters, it can be disabled globally if required by setting the `grc` element under `spec.overrides` to `false` in the `MultiClusterHub` object:
```suggestion
. Now that governance is disabled on the managed clusters, you can disable globally if required by setting the `grc` element under `spec.overrides` to `false` in the `MultiClusterHub` object. Run the following command:
```

2023-06-13 15:46 UTC, dockerymick commented on release_notes/known_issues_governance.adoc
> +. (For self-managed hubs only) If there were any local-cluster policies, those can optionally be deleted:
```suggestion
. (For self-managed hubs only) If there are any local cluster policies, you can delete the policies by running the following command:
```

2023-06-13 15:50 UTC, dockerymick commented on release_notes/known_issues_governance.adoc
> +To re-enable Governance after doing this, re-enable the `grc` element under `spec.overrides` in the `MultiClusterHub` first and then run the loop with `"enabled":true` to re-enable Governance in the
```suggestion
. To reenable governance in the `KlusterletAddonConfig`, reenable the `grc` element of the `spec.overrides` in the `MultiClusterHub` first and then run the loop with `"enabled":true`. If the deployments are unsuccessful, the `governance-policy-addon-controller` might have a stale lease. Delete the lease by using the following command:
```

2023-06-13 15:51 UTC, dockerymick requested changes
Provided some suggestions

2023-06-13 16:49 UTC, dockerymick commented on release_notes/known_issues_governance.adoc
> +For example, the `stringData` map in a `Secret` resource is converted by Kubernetes to `data` with `base64` encoded values. Instead of using `stringData`, use `data` directly with `base64` encoded va
```suggestion

For example, the `stringData` map in a `Secret` resource is converted by Kubernetes to `data` with `base64` encoded values. Instead of using `stringData`, use `data` directly with `base64` encoded values instead of strings.
```

2023-06-13 16:52 UTC, dockerymick commented
@mprahl or @JustinKuli will either of you provide your review and approval? I accepted my own suggestions since Dale is on PTO, but let me know your thoughts.

2023-06-13 17:31 UTC, JustinKuli reviewed
The commands look right to me! Just some minor adjustments in the other section.

2023-06-13 17:31 UTC, JustinKuli commented on release_notes/known_issues_governance.adoc
> +*Note:* If `pruneObjectBehavior` is set to something other than `none`, disabling the policy causes the objects to be cleaned up. In this case, set `prunObjectBehavior` to `none` so that the objects
```suggestion
*Note:* If `pruneObjectBehavior` is set to something other than `None`, disabling the policy causes the objects to be cleaned up. In this case, set `pruneObjectBehavior` to `None` so that the objects exist after the policy is disabled.
```

2023-06-13 18:01 UTC, dockerymick commented on release_notes/known_issues_governance.adoc
> +*Note:* If `pruneObjectBehavior` is set to something other than `none`, disabling the policy causes the objects to be cleaned up. In this case, set `prunObjectBehavior` to `none` so that the objects
Great catch!

2023-06-13 18:24 UTC, swopebe requested changes
see comments

2023-06-13 18:24 UTC, swopebe commented on release_notes/known_issues_governance.adoc
> +When you disable governance deployments in the `MultiClusterHub` object, the deployments do not all get cleaned up properly. Complete the following steps to disable governance so that the deployments
I think we need another word here, other than gracefully. Like "deployments do not shut down completely" or "do not shut down without errors"....

Gracefully makes it seem like the deployments are dancing, but not gracefully.

2023-06-13 18:24 UTC, swopebe commented on release_notes/known_issues_governance.adoc
> +When you disable governance deployments in the `MultiClusterHub` object, the deployments do not all get cleaned up properly. Complete the following steps to disable governance so that the deployments
"Get cleaned up" is also a bit jarring.

What are we trying to say here? That they are not shut down completely?

2023-06-13 18:24 UTC, swopebe commented on release_notes/known_issues_governance.adoc
> +. (For self-managed hub clusters only) Delete the `ManifestWork` for the self-managed hub cluster and remove the finalizer on the `ManagedClusterAddon` if the `governance-policy-framework-uninstall`
This can be a line with a colon:

For self-managed hub clusters only: (or a comma instead of colon. I think we normally use the colon)

2023-06-13 18:24 UTC, swopebe commented on release_notes/known_issues_governance.adoc
> +. (For self-managed hub clusters only) Delete the `ManifestWork` for the self-managed hub cluster and remove the finalizer on the `ManagedClusterAddon` if the `governance-policy-framework-uninstall`
Isn't "self-managed hub cluster" called the local cluster?

2023-06-13 18:24 UTC, swopebe commented on release_notes/known_issues_governance.adoc
> +. Now that governance is disabled on the managed clusters, you can disable globally if required by setting the `grc` element under `spec.overrides` to `false` in the `MultiClusterHub` object. Run the
We don't need "Now that" or "next" or anything....that is all extra. We just give them the next step; that is the most imperative.

2023-06-13 18:24 UTC, swopebe commented on release_notes/known_issues_governance.adoc
> +. (For self-managed hubs only) If there are any local cluster policies, you can delete the policies by running the following command:
Same here with

For self-managed only: (Though I think we mean For the local cluster only?)

2023-06-13 18:24 UTC, swopebe commented on release_notes/known_issues_governance.adoc
> +. To reenable governance in the `KlusterletAddonConfig`, reenable the `grc` element of the `spec.overrides` in the `MultiClusterHub` first and then run the loop with `"enabled":true`. If the deployme
hmmm, wonder do we need re-enable?

2023-06-13 18:24 UTC, swopebe commented on release_notes/known_issues_governance.adoc
> +. To reenable governance in the `KlusterletAddonConfig`, reenable the `grc` element of the `spec.overrides` in the `MultiClusterHub` first and then run the loop with `"enabled":true`. If the deployme
This seems like multiple steps in one step that maybe should be broken out. If we say First and Next in one step, that is usually a sign that we are merging two steps in one and not great UX.

2023-06-13 18:24 UTC, swopebe commented on release_notes/known_issues_governance.adoc
>  == Pod security policies not supported on OpenShift 4.12 and later
I think we need {ocp-short} here for proper product reference.

2023-06-13 18:24 UTC, swopebe commented on release_notes/known_issues_governance.adoc
> +To resolve the issue, disable the policy and compare the differences between `objectDefinition` in the policy and the object on the managed cluster. If the keys are different or missing, Kubernetes m
a fair use of past participle that we may want to show Faisa, because once in a while we have to use it.

2023-06-13 18:24 UTC, swopebe commented on release_notes/known_issues_governance.adoc
> +- Another controller or process is also updating the object with different values.
I expected a list of "cases" but was interrupted with unexpected resolutions. How about introducing them differently?

See the following two possible causes and solutions for the error: 

Or something like that ^^^ to tell the user both are following (imagine a screen reader).

2023-06-13 18:25 UTC, swopebe commented on release_notes/known_issues_governance.adoc
> +When you disable governance deployments in the `MultiClusterHub` object, the deployments do not all get cleaned up properly. Complete the following steps to disable governance so that the deployments
Or that they do not shut down correctly?

2023-06-13 18:26 UTC, swopebe commented on release_notes/known_issues_governance.adoc
> +When you disable governance deployments in the `MultiClusterHub` object, the deployments do not all get cleaned up properly. Complete the following steps to disable governance so that the deployments
properly?

2023-06-13 19:07 UTC, dockerymick commented on release_notes/known_issues_governance.adoc
>  == Pod security policies not supported on OpenShift 4.12 and later
```suggestion
== Pod security policies not supported on {ocp-short} 4.12 and later
```

2023-06-13 19:09 UTC, dockerymick commented on release_notes/known_issues_governance.adoc
> +When you disable governance deployments in the `MultiClusterHub` object, the deployments do not all get cleaned up properly. Complete the following steps to disable governance so that the deployments
@swopebe from my perspective, "do not shut down without errors" is most accurate @JustinKuli thoughts?

2023-06-13 19:10 UTC, dockerymick commented on release_notes/known_issues_governance.adoc
> +. (For self-managed hub clusters only) Delete the `ManifestWork` for the self-managed hub cluster and remove the finalizer on the `ManagedClusterAddon` if the `governance-policy-framework-uninstall`
```suggestion
. For self-managed hub clusters only: Delete the `ManifestWork` for the self-managed hub cluster and remove the finalizer on the `ManagedClusterAddon` if the `governance-policy-framework-uninstall` pod of a self-managed hub cluster is in `CrashLoopBackOff`. Run the following commands:
```

2023-06-13 19:11 UTC, dockerymick commented on release_notes/known_issues_governance.adoc
> +. Now that governance is disabled on the managed clusters, you can disable globally if required by setting the `grc` element under `spec.overrides` to `false` in the `MultiClusterHub` object. Run the
```suggestion
. Disable governance globally, if required, by setting the `grc` element in the `spec.overrides` section to `false` in the `MultiClusterHub` object. Run the following command:
```

2023-06-13 19:12 UTC, dockerymick commented on release_notes/known_issues_governance.adoc
> +. (For self-managed hubs only) If there are any local cluster policies, you can delete the policies by running the following command:
```suggestion
. For self-managed hubs only: If there are any local cluster policies, you can delete the policies by running the following command:
```

2023-06-13 19:15 UTC, dockerymick commented on release_notes/known_issues_governance.adoc
> +. To reenable governance in the `KlusterletAddonConfig`, reenable the `grc` element of the `spec.overrides` in the `MultiClusterHub` first and then run the loop with `"enabled":true`. If the deployme
```suggestion
. To re-enable governance in the `KlusterletAddonConfig`, re-enable the `grc` element of the `spec.overrides` section in the `MultiClusterHub`. Run the following command:
+
[source,bash]
----
for CLUSTER in $(oc get managedclusters -o jsonpath='{.items[].metadata.name}'); do
  oc patch -n ${CLUSTER} klusterletaddonconfig ${CLUSTER} --type=merge --patch='{"spec":{"policyController":{"enabled":true}}}'
done
----

. If the deployments are unsuccessful, the `governance-policy-addon-controller` might have a stale lease. Delete the lease by using the following command:
```

2023-06-13 19:18 UTC, dockerymick commented on release_notes/known_issues_governance.adoc
> +. For self-managed hub clusters only: Delete the `ManifestWork` for the self-managed hub cluster and remove the finalizer on the `ManagedClusterAddon` if the `governance-policy-framework-uninstall` p
From @swopebe is self-managed hub cluster the local cluster? @JustinKuli

2023-06-13 19:41 UTC, dockerymick commented on release_notes/known_issues_governance.adoc
> +If a policy is set to `remediationAction: enforce` and is repeatedly updated, the {product-title-short} console shows repeated violations with successful updates. This might happen in the following t
```suggestion
If a policy is set to `remediationAction: enforce` and is repeatedly updated, the {product-title-short} console shows repeated violations with successful updates. See the following two possible causes and solutions for the error:
```

2023-06-13 19:41 UTC, dockerymick commented on release_notes/known_issues_governance.adoc
> +- Another controller or process is also updating the object with different values.
updated

2023-06-13 19:51 UTC, swopebe commented on release_notes/known_issues_governance.adoc
> +When you disable governance deployments in the `MultiClusterHub` object, the deployments do not all get cleaned up properly. Complete the following steps to disable governance so that the deployments
I think that is fair and should be technically correct.

2023-06-13 19:54 UTC, swopebe approved these changes
with conditions lol

2023-06-13 19:59 UTC, dockerymick commented on release_notes/known_issues_governance.adoc
> +== Governance deployments do not shut down gracefully when disabled
```suggestion
== Governance deployments do not shut down without error when disabled
```

2023-06-13 20:00 UTC, dockerymick commented on release_notes/known_issues_governance.adoc
> +When you disable governance deployments in the `MultiClusterHub` object, the deployments do not all get cleaned up properly. Complete the following steps to disable governance so that the deployments
```suggestion
When you disable governance deployments in the `MultiClusterHub` object, the deployments are not cleaned without errors. Complete the following steps to disable governance so that the deployments also get cleaned up:
```

2023-06-13 20:22 UTC, dockerymick commented on release_notes/known_issues_governance.adoc
> +== Governance deployments do not shut down without error when disabled
```suggestion
== Governance deployments do not shut down without errors when disabled
```

2023-06-14 13:25 UTC, JustinKuli commented on release_notes/known_issues_governance.adoc
> +. For self-managed hub clusters only: Delete the `ManifestWork` for the self-managed hub cluster and remove the finalizer on the `ManagedClusterAddon` if the `governance-policy-framework-uninstall` p
Yes. When the hub is self-managing, its name is always "local-cluster".

2023-06-15 19:29 UTC, dockerymick commented
@JustinKuli thanks for confirming. Merging this PR

2023-06-15 19:29 UTC, merged

2023-06-15 21:04 UTC, dockerymick commented
https://issues.redhat.com/browse/ACM-5866