https://issues.redhat.com/browse/ACM-5962 Known issue pruneObjectBeha…
open-cluster-management/rhacm-docs pull request #5204
Opened 2023-06-16 15:27 UTC by dockerymick

…vior
https://issues.redhat.com/browse/ACM-5962

2023-06-16 16:42 UTC, JustinKuli approved these changes
Sounds good to me.

2023-06-16 17:53 UTC, yiraeChristineKim commented on release_notes/known_issues_governance.adoc
> +- If you set `pruneObjectBehvior` to `None` or fail to set the parameter value, old objects might be unintentionally deleted on the managed cluster. Specifically, this occurs when a user changes the
should be `namespaceSelector`?!!

2023-06-16 17:53 UTC, yiraeChristineKim commented on release_notes/known_issues_governance.adoc
> +- If you set `pruneObjectBehvior` to `None` or fail to set the parameter value, old objects might be unintentionally deleted on the managed cluster. Specifically, this occurs when a user changes the
To me, **fail to set the parameter value** unclear, what does the **parameter value** indicate?

2023-06-16 17:53 UTC, yiraeChristineKim commented on release_notes/known_issues_governance.adoc
> +- If you set `pruneObjectBehvior` to `None` or fail to set the parameter value, old objects might be unintentionally deleted on the managed cluster. Specifically, this occurs when a user changes the
is that `name`, `namespace`, `kind`, or `apiversion`?

2023-06-16 17:54 UTC, JustinKuli requested changes

2023-06-16 17:54 UTC, JustinKuli commented on release_notes/known_issues_governance.adoc
> +- If you set `pruneObjectBehvior` to `None` or fail to set the parameter value, old objects might be unintentionally deleted on the managed cluster. Specifically, this occurs when a user changes the
```suggestion
- If you set `pruneObjectBehvior` to `None` or fail to set the parameter value, old objects might be unintentionally deleted on the managed cluster. Specifically, this occurs when a user changes the `name`, `namespace`, `kind`, or `apiversion` in the template. The parameter fields can dynamically change when the `object-templates-raw` or `namespaceSelector` parameters change. 
```

@yiraeChristineKim is keeping me honest and noticed this typo I missed

2023-06-16 18:42 UTC, cadawson requested changes
A couple of fixes and a question. Otherwise looks good. Thanks!

2023-06-16 18:42 UTC, cadawson commented on release_notes/known_issues_governance.adoc
> +- If you set `pruneObjectBehvior` to `DeleteAll` or `DeleteIfCreated`, old resources that were created before modifying are not cleaned correctly. Only new resources from policy creations and policy
```suggestion
- If you set `pruneObjectBehavior` to `DeleteAll` or `DeleteIfCreated`, old resources that were created before modifying are not cleaned correctly. Only new resources from policy creations and policy updates are tracked and deleted when you delete the configuration policy.
```

2023-06-16 18:42 UTC, cadawson commented on release_notes/known_issues_governance.adoc
> +- If you set `pruneObjectBehvior` to `None` or fail to set the parameter value, old objects might be unintentionally deleted on the managed cluster. Specifically, this occurs when a user changes the
```suggestion
- If you set `pruneObjectBehavior` to `None` or do not set the parameter value, old objects might be unintentionally deleted on the managed cluster. Specifically, this occurs when you change the `name`, `namespace`, `kind`, or `apiversion` in the template. The parameter fields can dynamically change when the `object-templates-raw` or `nameSelector` parameters change. 
```

2023-06-16 18:42 UTC, cadawson commented on release_notes/known_issues_governance.adoc
> +- If you set `pruneObjectBehvior` to `DeleteAll` or `DeleteIfCreated`, old resources that were created before modifying are not cleaned correctly. Only new resources from policy creations and policy
What are we modifying here? "...resources that you created before modifying the `pruneObjectBehavior` setting are not cleaned correctly"?

2023-06-16 19:38 UTC, dockerymick commented on release_notes/known_issues_governance.adoc
> +- If you set `pruneObjectBehvior` to `None` or fail to set the parameter value, old objects might be unintentionally deleted on the managed cluster. Specifically, this occurs when a user changes the
Great catch @yiraeChristineKim changing that now

2023-06-16 19:39 UTC, dockerymick commented on release_notes/known_issues_governance.adoc
> +- If you set `pruneObjectBehvior` to `None` or fail to set the parameter value, old objects might be unintentionally deleted on the managed cluster. Specifically, this occurs when a user changes the
From my perspective, the parameter values for `pruneObjectBehavior` are `None`, `DeleteAll`, and `DeleteIfCreated`

2023-06-16 19:41 UTC, dockerymick commented on release_notes/known_issues_governance.adoc
> +- If you set `pruneObjectBehvior` to `DeleteAll` or `DeleteIfCreated`, old resources that were created before modifying are not cleaned correctly. Only new resources from policy creations and policy
Modifying the configuration policy

2023-06-16 19:43 UTC, dockerymick commented on release_notes/known_issues_governance.adoc
> +- If you set `pruneObjectBehvior` to `DeleteAll` or `DeleteIfCreated`, old resources that were created before modifying are not cleaned correctly. Only new resources from policy creations and policy
@cadawson I edited your suggestion, did that clarify things?

2023-06-16 19:44 UTC, dockerymick commented on release_notes/known_issues_governance.adoc
> +- If you set `pruneObjectBehvior` to `None` or fail to set the parameter value, old objects might be unintentionally deleted on the managed cluster. Specifically, this occurs when a user changes the
Thanks! I updated this

2023-06-20 11:57 UTC, cadawson commented on release_notes/known_issues_governance.adoc
> +- If you set `pruneObjectBehvior` to `DeleteAll` or `DeleteIfCreated`, old resources that were created before modifying are not cleaned correctly. Only new resources from policy creations and policy
Yep. That works for me. Thanks!

2023-06-20 12:00 UTC, cadawson commented on release_notes/known_issues_governance.adoc
> +- If you set `pruneObjectBehvior` to `None` or fail to set the parameter value, old objects might be unintentionally deleted on the managed cluster. Specifically, this occurs when a user changes the
@dockerymick: Please make sure you add the missing "a" to "Behavior".

2023-06-20 13:20 UTC, yiraeChristineKim approved these changes

2023-06-20 13:43 UTC, dockerymick commented on release_notes/known_issues_governance.adoc
> +- If you set `pruneObjectBehvior` to `None` or fail to set the parameter value, old objects might be unintentionally deleted on the managed cluster. Specifically, this occurs when a user changes the
Updated

2023-06-20 13:48 UTC, dockerymick commented
@cadawson thanks for the reminder about the spelling. Are there any other changes or are you fine with me moving forward to merge?

2023-06-20 15:11 UTC, cadawson approved these changes
Looks good! Thanks!

2023-06-20 15:29 UTC, dockerymick commented
@cadawson Thanks for your approval. Merging this and will make updates for 2.7

2023-06-20 15:38 UTC, merged