[ACM-5665]: Restructure bare metal docs and clarify procedures and commands
open-cluster-management/rhacm-docs pull request #5211
Opened 2023-06-20 19:36 UTC by lahinson

See details in related Jira: https://issues.redhat.com/browse/ACM-5665

2023-06-21 18:21 UTC, lahinson commented
@rokej When you can, PTAL at this PR, which makes several changes to the bare metal docs. I summarized the changes in the first comment in the PR. If you have any questions, please feel free to reach out to me. 

@swopebe FYI - for your awareness

2023-06-21 19:55 UTC, rokej approved these changes

2023-06-23 16:34 UTC, lahinson commented
@avishayt @eranco74 When you can, I would really appreciate your feedback on these changes to the bare metal docs. A summary of the changes is in the [first comment](https://github.com/stolostron/rhacm-docs/pull/5211#issue-1766036266) in this PR. Please let me know if you have any questions for me. Thank you!

2023-06-25 08:23 UTC, avishayt reviewed
Started a review, will continue later

2023-06-25 08:23 UTC, avishayt commented on clusters/hosted_control_planes/hosted_bare_metal_access_cluster.adoc
> += Accessing the hosted cluster on bare metal (Technology Preview)
There shouldn't be anything specific to bare metal in this file.  It should say that to run "oc" or "kubectl" commands on the hosted cluster then they need to fetch the kubeconfig file.

2023-06-25 08:23 UTC, avishayt commented on clusters/hosted_control_planes/hosted_bare_metal_access_cluster.adoc
> +The hosted control plane is running and the agents are ready to join the hosted cluster. Before the agents join the hosted cluster, you need to access the hosted cluster.
These sentences are not needed.  The second one about needing access to the hosted cluster for agents to join is actually not correct.

2023-06-25 08:23 UTC, avishayt commented on clusters/hosted_control_planes/hosted_bare_metal_agents.adoc
> +. Download the live ISO and use it to start a node (bare metal or VM). At startup, the node communicates with the Assisted Service and registers as an agent in the same namespace as the `InfraEnv` re
1. We should specify that the URL for the live ISO can be found in the `InfraEnv` resource, under status.isoDownloadURL
2. We usually refer to a "node" as a host that is part of an OpenShift cluster.  I believe we should refer to it as "host" here.

2023-06-25 08:23 UTC, avishayt commented on clusters/hosted_control_planes/hosted_bare_metal_agents.adoc
> +//lahinson - June 2023 - We need to better clarify what the following command does
The "get agents" command lists the agents with some properties.

2023-06-25 08:23 UTC, avishayt commented on clusters/hosted_control_planes/hosted_bare_metal_agents.adoc
> +// lahinson - June 2023 - We need to better clarify what the following commands do
Here we are setting the installation disk and hostname, as well as approving the agent.  This is what's mentioned above on line 10.

2023-06-25 08:23 UTC, avishayt commented on clusters/hosted_control_planes/hosted_bare_metal_agents.adoc
> +oc -n ${HOSTED_CONTROL_PLANE_NAMESPACE} get agents
Now after the "patch" command above, we can see in the output below that the agents are approved for use.

2023-06-25 10:17 UTC, avishayt commented on clusters/hosted_control_planes/configure_hosted_bm.adoc
> +- To provision hosted control planes on bare metal, you can use the Agent platform. The Agent platform uses the Central Infrastructure Management (CIM) service to add worker nodes to a hosted cluster
Some comments on the text above - I can't add a comment on the necessary line.
1. On line 4, it says "you need a _hosting_ cluster and a _hosted_ cluster".  This is not accurate because we are creating the hosted cluster - at this point, the user needs the hosting cluster only.
2. Are we settled on the term "hosting cluster"?  I thought it was called "management cluster".
3. The term "hosting cluster" is defined on line 10 - it should be closer to line 4 where it was first used.

2023-06-25 10:17 UTC, avishayt commented on clusters/hosted_control_planes/hosted_bare_metal_agents.adoc
> +. Use the Assisted Service to create the custom ISO and the Baremetal Operator to perform the installation.
This line is inaccurate and can be removed.

2023-06-25 10:17 UTC, avishayt commented on clusters/hosted_control_planes/hosted_bare_metal_agents.adoc
> +//lahinson - June 2023 - Would it be clearer to add "by entering the following command:" to the end of line 44?
Yes, that would be clearer.

2023-06-25 10:17 UTC, avishayt commented on clusters/hosted_control_planes/hosted_bare_metal_agents.adoc
> +// lahinson - June 2023 - We need to better clarify this step. It says to "Wait", but then it provides a command. Is the user supposed to enter the command, or is the following text output?
The following line is a command that continuously checks the pod's status and returns once it is ready (or once it has reached a 10 second timeout).

2023-06-25 10:17 UTC, avishayt commented on clusters/hosted_control_planes/hosted_bare_metal_agents.adoc
> +----
Which "other two nodes"?  Maybe this text should say "Repeat for all other hosts"?

2023-06-25 10:17 UTC, avishayt commented on clusters/hosted_control_planes/configure_hosted_bm.adoc
> -
They also need to enable Central Infrastructure Management (CIM), as described here:
https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.8/html-single/clusters/index#enable-cim

2023-06-25 10:17 UTC, avishayt commented on clusters/hosted_control_planes/hosted_bare_metal_infraenv.adoc
> +. To generate a live ISO that allows virtual machines or bare metal machines to join as agents, enter the following command:
This command doesn't generate the live ISO, but rather it fetches the URL to download it from the InfraEnv resource.

2023-06-25 10:17 UTC, avishayt commented on clusters/hosted_control_planes/hosted_bare_metal_verifying_cluster.adoc
> += Verifying hosted cluster creation on bare metal (Technology Preview)
There is nothing specific to bare metal in this file - consider sharing it across platforms.

2023-06-25 13:05 UTC, eranco74 commented on clusters/hosted_control_planes/configure_hosted_bm.adoc
> +. xref:../hosted_control_planes/hosted_bare_metal_agents.adoc#hosted-bare-metal-adding-agents[Add agents to hosted control planes on bare metal]
1. This is actually just adding Agents to the infraEnv not to the hosted control plane.
2. This should be performed prior to creating a hosted control plane.
While creating a hosted control plane the user will configure nodepool (set the nuber or workers) as well, in order to have available agents to add there they need to create the agents first.

2023-06-25 13:05 UTC, eranco74 commented on clusters/hosted_control_planes/hosted_bare_metal_agents.adoc
> += Adding agents to hosted control planes on bare metal (Technology Preview)
This explains how adds agents to the infraEnv not to the hosted control plane.
There should be already documented for CIM

2023-06-26 07:01 UTC, avishayt commented on clusters/hosted_control_planes/hosted_bare_metal_agents.adoc
> += Adding agents to hosted control planes on bare metal (Technology Preview)
From what I saw, the CIM docs are only UI, and here is API.  Though we have UI here as well... @lahinson should we be documenting UI or console or both?

2023-06-26 14:05 UTC, lahinson commented on clusters/hosted_control_planes/hosted_bare_metal_access_cluster.adoc
> += Accessing the hosted cluster on bare metal (Technology Preview)
@avishayt So do the steps here work for any platform (i.e., AWS, bare metal, OpenShift Virtualization)? I ask because we have [separate docs on how to access the cluster on AWS](https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.8/html/clusters/cluster_mce_overview#hosting-service-cluster-access-aws), so now I'm wondering whether those are necessary.

2023-06-26 14:17 UTC, lahinson commented on clusters/hosted_control_planes/hosted_bare_metal_agents.adoc
> +. Use the Assisted Service to create the custom ISO and the Baremetal Operator to perform the installation.
@avishayt Is line 42 inaccurate, or line 44? Just want to double-check.

2023-06-26 14:21 UTC, lahinson commented on clusters/hosted_control_planes/hosted_bare_metal_agents.adoc
> += Adding agents to hosted control planes on bare metal (Technology Preview)
@avishayt If we expect that users will use either the UI or console, I think it's best to document both.

2023-06-26 14:42 UTC, lahinson commented on clusters/hosted_control_planes/configure_hosted_bm.adoc
> +- To provision hosted control planes on bare metal, you can use the Agent platform. The Agent platform uses the Central Infrastructure Management (CIM) service to add worker nodes to a hosted cluster
@avishayt I recently just asked Adel about "management cluster" vs. "hosting cluster". I'd prefer if we simply picked one term, but apparently both are used synonymously. For OCP 4.14, we're publishing a glossary of terms for hosted control planes that explains that the management cluster and hosting cluster are synonyms. I'll update the text in the intro of this file to incorporate your feedback here. Thank you!

2023-06-26 15:22 UTC, rokej commented on clusters/hosted_control_planes/hosted_bare_metal_access_cluster.adoc
> += Accessing the hosted cluster on bare metal (Technology Preview)
https://github.com/stolostron/rhacm-docs/blob/lahinson-acm-5665-restructure-bm-docs/clusters/hosted_control_planes/hosted_bare_metal_access_cluster.adoc works for any platform. https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.8/html/clusters/cluster_mce_overview#hosting-service-cluster-access-aws works for any platform as well and I think the two documents should be combined as a single doc section with two different options. 

https://github.com/stolostron/rhacm-docs/blob/lahinson-acm-5665-restructure-bm-docs/clusters/hosted_control_planes/hosted_bare_metal_access_cluster.adoc talks about one option where users use `hypershift` CLI to generate a kubeconfig file and access.

https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.8/html/clusters/cluster_mce_overview#hosting-service-cluster-access-aws talks about another option of getting the kubeconfig file and kubeadmin credential directly from resources.

2023-06-26 16:12 UTC, lahinson commented on clusters/hosted_control_planes/hosted_bare_metal_access_cluster.adoc
> += Accessing the hosted cluster on bare metal (Technology Preview)
Thanks @rokej!

> https://github.com/stolostron/rhacm-docs/blob/lahinson-acm-5665-restructure-bm-docs/clusters/hosted_control_planes/hosted_bare_metal_access_cluster.adoc works for any platform. https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.8/html/clusters/cluster_mce_overview#hosting-service-cluster-access-aws works for any platform as well and I think the two documents should be combined as a single doc section with two different options.

Will do

>https://github.com/stolostron/rhacm-docs/blob/lahinson-acm-5665-restructure-bm-docs/clusters/hosted_control_planes/hosted_bare_metal_access_cluster.adoc talks about one option where users use hypershift CLI to generate a kubeconfig file and access.
https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.8/html/clusters/cluster_mce_overview#hosting-service-cluster-access-aws talks about another option of getting the kubeconfig file and kubeadmin credential directly from resources.

That is helpful to know. I can add some wording to better differentiate those docs.

2023-06-26 18:09 UTC, avishayt commented on clusters/hosted_control_planes/hosted_bare_metal_agents.adoc
> +. Use the Assisted Service to create the custom ISO and the Baremetal Operator to perform the installation.
Just 44

2023-06-26 18:10 UTC, avishayt commented on clusters/hosted_control_planes/hosted_bare_metal_agents.adoc
> += Adding agents to hosted control planes on bare metal (Technology Preview)
I guess that can be a separate JIRA and PR

2023-06-27 13:30 UTC, lahinson commented on clusters/hosted_control_planes/hosted_bare_metal_access_cluster.adoc
> += Accessing the hosted cluster on bare metal (Technology Preview)
@rokej I combined the content from the two files here into `clusters/hosted_control_planes/managing_hosted_aws.adoc`. You can see the changes in the latest commit. I had a couple of questions, which start with `\\lahinson`. PTAL when you can. Thanks!

2023-06-27 20:34 UTC, rokej commented on clusters/hosted_control_planes/managing_hosted_aws.adoc
> +* To access the hosted cluster by getting the `kubeconfig` file and credentials directly from resources, you need to be familiar with the access secrets for hosted control plane clusters. The secrets
The secrets are stored in the `hypershift-management-cluster` namespace. ---> The secrets are stored in the hosted cluster (hosting) namespace. Note: The hosted cluster (hosting) namespace contains hosted cluster resources and the hosted control plane namespace is where the actual hosted control plane runs.

2023-06-27 20:34 UTC, rokej commented on clusters/hosted_control_planes/managing_hosted_aws.adoc
> +//lahinson - June 2023 - Does the user need to take any steps with the secrets to access the hosted cluster? The latter section seems incomplete.
The secret contains  base64 encoded `kubeconfig` field. This can be base64 decoded and saved into a file to be used with `oc --kubeconfig .. ` command to get access to the hosted cluster. This is equivalent to the next section about generating the `kubeconfig` file using `hypershift create kubeconfig` command.

2023-06-27 20:34 UTC, rokej commented on clusters/hosted_control_planes/managing_hosted_aws.adoc
> +. If you access the cluster by entering the following command, the output shows that you do not have any nodes and that the ClusterVersion is trying to reconcile the {ocp} release:
Replace the whole sentence with...

Once the `kubeconfig` file is saved, you can access the hosted cluster by entering the following example command.

2023-06-27 20:34 UTC, rokej commented on clusters/hosted_control_planes/managing_hosted_aws.adoc
> +oc --kubeconfig ${HOSTED_CLUSTER_NAME}.kubeconfig get clusterversion,nodes
oc --kubeconfig ${HOSTED_CLUSTER_NAME}.kubeconfig get nodes

2023-06-27 20:34 UTC, rokej commented on clusters/hosted_control_planes/managing_hosted_aws.adoc
> +----
Remove lines 150 ~ 160. This is not about accessing the cluster.

2023-06-27 20:34 UTC, rokej commented on clusters/hosted_control_planes/managing_hosted_aws.adoc
> +== Accessing the hosted cluster
@lahinson This section should be on its own and referenced by managing_hosted_aws, managing_hosted_bm, managing_hosted_kubevirt (where is this doc? :) ). In each doc after "creating a cluster" section.

2023-06-28 13:45 UTC, lahinson commented on clusters/hosted_control_planes/managing_hosted_aws.adoc
> +//lahinson - June 2023 - Does the user need to take any steps with the secrets to access the hosted cluster? The latter section seems incomplete.
@rokej Thanks for the additional information! I'm learning a lot :)

Would it make sense if I added the following text after line 134?

```
The secret contains a Base64-encoded `kubeconfig` field. To access the hosted cluster, you can decode the field and save it into a file to be used with the following command:

----
oc --kubeconfig ${HOSTED_CLUSTER_NAME}.kubeconfig get nodes
----
```

2023-06-28 17:54 UTC, rokej commented on clusters/hosted_control_planes/managing_hosted_aws.adoc
> +//lahinson - June 2023 - Does the user need to take any steps with the secrets to access the hosted cluster? The latter section seems incomplete.
@lahinson Yes, that sounds good. Sorry but we should say the same for the kubeadmin password that the secret's `data.password` field is base64-encoded and should be decoded.

2023-06-28 18:46 UTC, lahinson commented on clusters/hosted_control_planes/managing_hosted_aws.adoc
> +//lahinson - June 2023 - Does the user need to take any steps with the secrets to access the hosted cluster? The latter section seems incomplete.
@rokej Does this sound correct?

```
The `kubeconfig` secret contains a Base64-encoded `kubeconfig` field, and the `kubeadmin` password secret contains a Base64-encoded `data.password` field. To access the hosted cluster, you can decode the fields and save them into a file to be used with the following command:

----
oc --kubeconfig ${HOSTED_CLUSTER_NAME}.kubeconfig get nodes
----
```

2023-06-28 20:08 UTC, rokej commented on clusters/hosted_control_planes/managing_hosted_aws.adoc
> +//lahinson - June 2023 - Does the user need to take any steps with the secrets to access the hosted cluster? The latter section seems incomplete.
The `kubeconfig` can be saved into a file and used with `oc --kubeconfig ...` command. The decoded password can be used to log into the hosted cluster's console or API server. Thank you Laura.

2023-06-29 14:46 UTC, lahinson commented on clusters/hosted_control_planes/managing_hosted_aws.adoc
> +== Accessing the hosted cluster
@rokej Good catch.

For bare metal, I added references to this section from the following places:
- configure_hosted_bm
- hosted_create_bare_metal

The Kubevirt docs already contain a section about accessing the hosted cluster (https://github.com/stolostron/rhacm-docs/blob/2.8_stage/clusters/hosted_control_planes/managing_hosted_kubevirt.adoc#accessing-the-hosted-cluster). I can update the kubevirt docs to point to this section, but I think I'd prefer to do that in a separate PR.

2023-07-07 15:24 UTC, rokej commented on clusters/hosted_control_planes/managing_hosted_aws.adoc
> ++
We can remove lines 160 ~ 166 which answers your question in line 168. The example command above was to show user how to use the `kubeconfig` to run commands agains the hosted cluster, not for doing anything with the nodes.

2023-07-07 15:30 UTC, lahinson commented
@rokej Thanks again for your review! I just made the updates that we discussed.

2023-07-07 15:33 UTC, rokej approved these changes
Thank you @lahinson

2023-07-07 15:35 UTC, lahinson commented
@swopebe When you're back from PTO, I would appreciate your peer review on these changes. Thank you!

2023-07-16 12:51 UTC, avishayt commented
/lgtm

2023-07-19 19:03 UTC, swopebe requested changes

2023-07-19 19:03 UTC, swopebe commented on clusters/hosted_control_planes/configure_hosted_bm.adoc
This is gonna be so confusing because we have a "managed cluster" that the hub manages. I wonder if we can do this:

*Note:* The management cluster is not the same as _managed_ cluster. A managed cluster is a cluster that the hub cluster manages. 

or something...willing to brainstorm.

2023-07-19 19:03 UTC, swopebe commented on clusters/hosted_control_planes/configure_hosted_bm.adoc
> +You can enable a managed cluster to be a hosting cluster by using the `hypershift` add-on to deploy the HyperShift Operator on that cluster. Then, you can start to create the hosted cluster.
Here is where we switch to _managed_.

2023-07-19 19:03 UTC, swopebe commented on clusters/hosted_control_planes/configure_hosted_bm.adoc
Does the user at this point know what the `local cluster` is, if not, maybe something I have added in a couple other spots: `local-cluster`, which is a hub cluster that is managed... 

Up to you if you think the user was introduced to that by now.

2023-07-19 19:03 UTC, swopebe commented on clusters/hosted_control_planes/configure_hosted_bm.adoc
> +After you meet the prerequisites, take the following steps to configure hosted control planes on bare metal:
take I think would be better written as "complete," as I think take could be taken many ways in different languages

2023-07-19 19:03 UTC, swopebe commented on clusters/hosted_control_planes/hosted_bare_metal_agents.adoc
> +.Example output
I have been changing this when I see it to"

See the following example output: 

(if not too much trouble)

2023-07-19 19:03 UTC, swopebe commented on clusters/hosted_control_planes/hosted_bare_metal_agents.adoc
> ++
we usually write specification, avoiding the colloquial developer speak.

2023-07-19 19:03 UTC, swopebe commented on clusters/hosted_control_planes/hosted_bare_metal_agents.adoc
> +
might be a format issue here, as the codeblock is usually grayed out. I will play with it a bit.

2023-07-19 19:03 UTC, swopebe commented on clusters/hosted_control_planes/hosted_bare_metal_agents.adoc
> +.Example output
same comment here on line 37

2023-07-19 19:03 UTC, swopebe commented on clusters/hosted_control_planes/hosted_bare_metal_agents.adoc
> ++
will look at the format here, as well.

2023-07-19 19:03 UTC, swopebe commented on clusters/hosted_control_planes/hosted_bare_metal_agents.adoc
> +----
and here

2023-07-19 19:03 UTC, swopebe commented on clusters/hosted_control_planes/hosted_bare_metal_agents.adoc
> +----
and here

2023-07-19 19:03 UTC, swopebe commented on clusters/hosted_control_planes/hosted_bare_metal_agents.adoc
> ++
thank you for line 87

2023-07-19 19:03 UTC, swopebe commented on clusters/hosted_control_planes/hosted_bare_metal_agents.adoc
> +//lahinson -June 2023 - We need to replace this heredoc syntax with a substep to create the yaml file with the BareMetalHost object info and another substep to enter the command to create the object.
this comment seems to be off for format

2023-07-19 19:03 UTC, swopebe commented on clusters/hosted_control_planes/hosted_bare_metal_agents.adoc
> +----
as does this code

2023-07-19 19:03 UTC, swopebe commented on clusters/hosted_control_planes/hosted_bare_metal_dns.adoc
> +----
it's likely these pesky astericks

2023-07-19 19:03 UTC, swopebe commented on clusters/hosted_control_planes/hosted_bare_metal_infraenv.adoc
> +
comment seems visible, code blocks seem to not be grayed out further down.

2023-07-19 19:03 UTC, swopebe commented on clusters/hosted_control_planes/hosted_bare_metal_infraenv.adoc
> +----
here, too

2023-07-19 19:14 UTC, swopebe commented on clusters/hosted_control_planes/hosted_bare_metal_agents.adoc
> +----
until?

2023-07-19 19:18 UTC, swopebe requested changes

2023-07-19 19:18 UTC, swopebe commented on clusters/hosted_control_planes/hosted_bare_metal_agents.adoc
> +== Adding agents with Metal#
3

2023-07-19 19:31 UTC, lahinson commented on clusters/hosted_control_planes/configure_hosted_bm.adoc
I don't think it will hurt to add that for clarity. It's not obvious to me whether the user knows what the local cluster is at this point.

2023-07-19 19:35 UTC, lahinson commented on clusters/hosted_control_planes/hosted_bare_metal_agents.adoc
> +----
I agree that it's unusual to see a command start with `until`. I checked the source, though, and it starts with `until`, so I think it's supposed to be there.

2023-07-19 20:13 UTC, lahinson commented on clusters/hosted_control_planes/configure_hosted_bm.adoc
I added a note to explain the difference between management cluster and managed cluster. I'll be sure to do the same in the intro of any other files where we refer to "management cluster". I don't think there are many in RHACM.

2023-07-20 12:26 UTC, swopebe commented on clusters/hosted_control_planes/hosted_bare_metal_agents.adoc
> +----
ok, I will let dev and you address it and approve knowing confirmation will come before merge.

2023-07-20 12:34 UTC, swopebe approved these changes
Everything looks great. I know this wasn't easy to implement in the portal, thank you so much for your high standards on the doc.

2023-07-20 13:38 UTC, lahinson commented on clusters/hosted_control_planes/hosted_bare_metal_agents.adoc
> +----
Great. I'm just awaiting confirmation from the devs.

2023-07-20 13:56 UTC, lahinson commented on clusters/hosted_control_planes/hosted_bare_metal_agents.adoc
> +----
@swopebe You were right to question that command! The devs just confirmed that it's wrong and sent me an updated version. I just pushed the update.

2023-07-20 14:04 UTC, merged