https://issues.redhat.com/browse/ACM-5792 Policy automation known issue
open-cluster-management/rhacm-docs pull request #5213
Opened 2023-06-21 16:38 UTC by dockerymick

https://issues.redhat.com/browse/ACM-5792

2023-06-21 16:54 UTC, cadawson requested changes
Suggestion for clarification and possibly a next step (if necessary). Thanks!

2023-06-21 16:54 UTC, cadawson commented on release_notes/known_issues_governance.adoc
> +If you have a `PolicyAutomation` that is set to _Run once_ mode and disabled an extra Ansible job is created.
I wasn't sure if `disabled` is a setting, but looked at the issue. Suggestion: If you have a `PolicyAutomation` that is set to _Run once_ mode and the `disabled` option is selected, an extra Ansible job is created. 

What is the result of this? Does the second Ansible job run? Do you have to remove it? Maybe it doesn't matter, and it is just for information.

2023-06-21 18:28 UTC, dockerymick commented on release_notes/known_issues_governance.adoc
> +If you have a `PolicyAutomation` that is set to _Run once_ mode and disabled an extra Ansible job is created.
@cadawson great question! the disabled parameter is only within the policy, there isn't a option from the console. The user would have the `disabled` parameter set to `true` to disable the policy 

@yiraeChristineKim does the user need to remove the extra Ansible job? are they able to remove the extra

2023-06-23 18:22 UTC, yiraeChristineKim commented on release_notes/known_issues_governance.adoc
> +If you have a `PolicyAutomation` that is set to _Run once_ mode and disabled an extra Ansible job is created.
you don't have to remove it because it creates the same 2 ansible jobs. However "Run once" mode means it is supposed to make 1 ansibleJob. From a user's perspective, it makes the user confused.

2023-06-23 18:25 UTC, dockerymick commented on release_notes/known_issues_governance.adoc
> +If you have a `PolicyAutomation` that is set to _Run once_ mode and disabled an extra Ansible job is created.
Thanks for clarifying that it is not required to remove the Ansible job. If the user wants to remove it, how can they do that?

2023-06-23 18:30 UTC, yiraeChristineKim commented on release_notes/known_issues_governance.adoc
> +If you have a `PolicyAutomation` that is set to _Run once_ mode and disabled an extra Ansible job is created.
In addition Ansible plays “should” be idempotent, in other words, it is run to achieve a particular state. Let me double check with that

2023-06-23 18:41 UTC, yiraeChristineKim commented on release_notes/known_issues_governance.adoc
> +If you have a `PolicyAutomation` that is set to _Run once_ mode and disabled an extra Ansible job is created.
Surely the user is able to delete using CLI, in console, I tried but I don't have credential so I cannot create this. Sorry about this. I will ping Derek, let you know after I get an answer

2023-06-23 19:02 UTC, yiraeChristineKim commented on release_notes/known_issues_governance.adoc
> +If you have a `PolicyAutomation` that is set to _Run once_ mode and disabled an extra Ansible job is created.
In the console, the user cannot delete

2023-06-23 19:20 UTC, dockerymick commented on release_notes/known_issues_governance.adoc
> +If you have a `PolicyAutomation` that is set to _Run once_ mode and disabled an extra Ansible job is created.
Thanks! Can you share the command that the user should run to delete the extra Ansible job?

2023-06-27 15:23 UTC, yiraeChristineKim commented on release_notes/known_issues_governance.adoc
> +If you have a `PolicyAutomation` that is set to _Run once_ mode and disabled an extra Ansible job is created.
sure!  To get the ansiblejob list `kubectl get ansiblejob -n {namespace}` -> 
kubectl delete ansiblejob {ansiblejob name} -n {namespace}

2023-06-27 18:02 UTC, yiraeChristineKim commented on release_notes/known_issues_governance.adoc
> +If you have a `PolicyAutomation` that is set to _Run once_ mode and disabled an extra Ansible job is created. You can delete the extra Ansible job. Complete the following steps:
Do we need a comma between "disabled" and "an"?

2023-06-27 18:03 UTC, yiraeChristineKim approved these changes

2023-06-27 18:43 UTC, swopebe commented on release_notes/known_issues_governance.adoc
> +The duplicate Ansible job is deleted.
the last line I would avoid. Remember we discussed as a team to only put validation if there is a way for the user to validate.

_Run the following command to see the job is removed from the list._

Without a verification step, we cannot predict that the user may not continue to run into problems for some other reason. So I would consider just removing the line 196.

2023-06-27 18:43 UTC, dockerymick commented on release_notes/known_issues_governance.adoc
> +If you have a `PolicyAutomation` that is set to _Run once_ mode and disabled an extra Ansible job is created.
Updated

2023-06-27 18:44 UTC, swopebe approved these changes
see comment for consideration

2023-06-27 18:45 UTC, dockerymick commented on release_notes/known_issues_governance.adoc
> +The duplicate Ansible job is deleted.
Great point Brandi! thanks for the reminder

2023-06-27 18:46 UTC, merged