https://issues.redhat.com/browse/ACM-6001 Add RHCOS image limits
open-cluster-management/rhacm-docs pull request #5217
Opened 2023-06-22 18:58 UTC by cadawson

2023-06-22 19:46 UTC, cadawson commented
Hi @elsapassaro and @jelkosz . Can you review this quick update about RHCOS requirements? Thanks!

2023-06-23 08:45 UTC, jelkosz commented
@filanov PTAL

2023-06-28 09:09 UTC, filanov commented
LGTM

2023-07-06 07:44 UTC, elsapassaro commented
/approve

2023-07-14 13:01 UTC, jelkosz commented
adding @filanov for this one

2023-07-14 13:28 UTC, dockerymick requested changes
Made a couple of suggestions

2023-07-14 13:28 UTC, dockerymick commented on clusters/cluster_lifecycle/create_infra_env.adoc
> +*Important:* If you are using the late binding feature, the {ocp-short} release images that you use when creating your clusters must be version 4.13 or later when the `spec.osImages` releases that ar
```suggestion
*Important:* If you are using the late binding feature, the {ocp-short} release images that you use when creating your clusters must be version 4.13 or later when the `spec.osImages` releases that are specified in the `AgentServiceConfig` custom resource are version 4.13 or later. The Red Hat Enterprise Linux CoreOS images for version 4.13 and later are not compatible with images earlier than version 4.13.   
```

2023-07-14 13:28 UTC, dockerymick commented on clusters/cluster_lifecycle/create_infra_env.adoc
> +*Important:* If you are using the late binding feature, the {ocp-short} release images that you use when creating your clusters must be version 4.13 or later when the `spec.osImages` releases that ar
Alternative

```suggestion
*Important:* If you are using the late binding feature and the `spec.osImages` releases in the `AgentServiceConfig` custom resource are version 4.13 or later, the {ocp-short} release images that you use when creating your clusters must be version 4.13 or later. The Red Hat Enterprise Linux CoreOS images for version 4.13 and later are not compatible with images earlier than version 4.13.   
```

2023-07-14 13:43 UTC, cadawson commented
Like the suggestion. Thanks @dockerymick!

2023-07-14 14:10 UTC, dockerymick approved these changes

2023-07-25 17:57 UTC, merged