https://issues.redhat.com/browse/ACM-4933?page=com.docminer.jira.issue-links%3Acom.kintosoft.jira.links.tab-panel Updating certs doc
open-cluster-management/rhacm-docs pull request #5221
Opened 2023-06-22 20:20 UTC by dockerymick

https://issues.redhat.com/browse/ACM-4933?page=com.docminer.jira.issue-links%3Acom.kintosoft.jira.links.tab-panel

2023-06-30 21:17 UTC, dhaiducek reviewed
I unfortunately don't know tons about certificates and we might need other squads to give feedback on their certificates, but I've tossed in some of my thoughts here.

2023-06-30 21:17 UTC, dhaiducek commented on governance/cert_manage.adoc
> +oc delete po -n openshift-gatekeeper-system -l control-plane=controller-manager
I don't think we should use the `po` abbreviation in documentation
```suggestion
oc delete pod -n openshift-gatekeeper-system -l control-plane=controller-manager
```

2023-06-30 21:17 UTC, dhaiducek commented on governance/cert_manage.adoc
> +oc delete po -n open-cluster-management ocm-webhook-679444669c-5cg76
I don't think we should use the `po` abbreviation in documentation
```suggestion
oc delete pod -n multicluster-engine ocm-webhook-679444669c-5cg76
```

2023-06-30 21:17 UTC, dhaiducek commented on governance/cert_manage.adoc
> +oc delete secret -n open-cluster-management ocm-webhook-secret
I checked my `2.9` environment. This apparently moved to MCE.
```suggestion
oc delete secret -n multicluster-engine ocm-webhook-secret
```

2023-06-30 21:17 UTC, dhaiducek commented on governance/cert_manage.adoc
> +oc delete po -n open-cluster-management ocm-webhook-679444669c-5cg76
We'll have to check with the MCE team, but it might be nicer to use:
```
oc delete pod -n multicluster-engine -l control-plane=ocm-webhook
```

2023-06-30 21:17 UTC, dhaiducek commented on governance/cert_manage.adoc
> +*Note:* After you delete the secret, a new one is created. However, you must restart pods that use the secret manually so they can begin to use the new certificate.
This section feels oddly generic. Deleting a secret doesn't necessarily make it come back afterward. We need to figure out some specifics here, like how to find the "certificate you need to refresh" (sorry, I don't have the details on it at the moment).

2023-06-30 21:17 UTC, dhaiducek commented on governance/cert_manage.adoc
> +openssl x509  -noout -text -in ./observability.crt
Question for observability: Where do I get `observability.crt` from?

2023-06-30 21:17 UTC, dhaiducek commented on governance/cert_manage.adoc
> +. Change the SAN in the `csr.cnf` configuration file with the hostname for your alertmanager route.
Question for observability: What's the "`csr.cnf` configuration file"? If I'm here, would I already know what that is?

2023-06-30 21:17 UTC, dhaiducek commented on governance/cert_manage.adoc
> +//If we want to keep the previous statement^, we must provide a verification step for the user to conform that the cert was rotated successfully
I'll try to work on a verification step here.

2023-06-30 21:17 UTC, dhaiducek commented on governance/cert_manage.adoc
> +*Note:* If observability is enabled, there are additional namespaces where certificates are created.
Question for observability: Should this be more specific?

2023-06-30 21:17 UTC, dhaiducek commented on governance/certificates.adoc
> +* The `open-cluster-management-observability` namespace contain the following certificates:
```suggestion
* The `open-cluster-management-observability` namespace contains the following certificates:
```

2023-06-30 21:17 UTC, dhaiducek commented on governance/cert_manage.adoc
> +oc -n open-cluster-management-observability create secret tls alertmanager-byo-cert --cert ./ingress.crt --key ./ingress.key
Not sure whether we want to remove the blank line here?
```suggestion
oc -n open-cluster-management-observability create secret tls alertmanager-byo-ca --cert ./ca.crt --key ./ca.key
oc -n open-cluster-management-observability create secret tls alertmanager-byo-cert --cert ./ingress.crt --key ./ingress.key
```

2023-06-30 21:17 UTC, dhaiducek commented on governance/cert_byo.adoc
> += Bringing Your Own (BYO) Certificate Authority (CA) certificates
This page appears specific to Observability, so should that go in the title also?

2023-07-03 00:17 UTC, dockerymick commented on governance/cert_byo.adoc
> += Bringing Your Own (BYO) Certificate Authority (CA) certificates
if this is only for observability, yes. Will CAs for other features be provided in the future? If yes, then I would keep the title

2023-07-03 00:17 UTC, dockerymick commented on governance/cert_manage.adoc
> +oc delete secret -n open-cluster-management ocm-webhook-secret
@dhaiducek what would it be for 2.8? we haven't created our 2.9 branch, but we can create an issue to update this for 2.9. Specifically, a task Jira doc issue for 2.9 that is related to a dev feature issue or epic

2023-07-03 00:17 UTC, dockerymick commented on governance/cert_manage.adoc
> +oc delete po -n open-cluster-management ocm-webhook-679444669c-5cg76
Is this the correct command for 2.8
```suggestion
oc delete pod -n open-cluster-management ocm-webhook-679444669c-5cg76
```

2023-07-03 00:17 UTC, dockerymick commented on governance/cert_manage.adoc
> +openssl x509  -noout -text -in ./observability.crt
@subbarao-meduri ^

2023-07-03 00:17 UTC, dockerymick commented on governance/cert_manage.adoc
> +*Note:* After you delete the secret, a new one is created. However, you must restart pods that use the secret manually so they can begin to use the new certificate.
* finding a certificate that you need to refresh 
* updating certificates after they are replaced
* refreshing certificates manually if it is not propagated (this seems like a known issue)
@FDewaleyne

2023-07-03 00:17 UTC, dockerymick commented on governance/cert_manage.adoc
> +. Change the SAN in the `csr.cnf` configuration file with the hostname for your alertmanager route.
@subbarao-meduri ^

2023-07-03 00:17 UTC, dockerymick commented on governance/cert_manage.adoc
> ++
```suggestion
. Create the two following secrets in the `open-cluster-management-observability` namespace. Run the following commands:
+
```

2023-07-03 00:17 UTC, dockerymick commented on governance/cert_manage.adoc
> +oc -n open-cluster-management-observability create secret tls alertmanager-byo-cert --cert ./ingress.crt --key ./ingress.key
I would keep it to display that there are multiple commands

2023-07-03 00:17 UTC, dockerymick commented on governance/cert_manage.adoc
> +*Note:* If observability is enabled, there are additional namespaces where certificates are created.
@subbarao-meduri ^

2023-07-03 17:23 UTC, dockerymick commented on governance/cert_manage_overview.adoc
> +
```suggestion
Various certificates are created and used throughout {product-title}. You can also bring your own certificates. You must create a Kubernetes TLS Secret for your certificate. After you create your certificates, you can replace certain certificates that are created by the {product-title-short} installer.
```

2023-07-03 17:28 UTC, dockerymick commented on governance/cert_manage.adoc
> +oc delete secret -n open-cluster-management ocm-webhook-secret
Dale will get a 2.8 environment and confirm

2023-07-03 17:28 UTC, dockerymick commented on governance/cert_manage.adoc
> +oc delete po -n open-cluster-management ocm-webhook-679444669c-5cg76
same

2023-07-03 17:31 UTC, dockerymick commented on governance/cert_manage.adoc
> +*Note:* After you delete the secret, a new one is created. However, you must restart pods that use the secret manually so they can begin to use the new certificate.
Check for certificate validity and how can the user access the certificates

2023-07-03 17:34 UTC, dockerymick commented on governance/cert_manage.adoc
> +oc -n open-cluster-management-observability create secret tls alertmanager-byo-cert --cert ./ingress.crt --key ./ingress.key
agreed to keep as is

2023-07-03 17:36 UTC, dockerymick commented on governance/certificates.adoc
> +- Refer to link:../troubleshooting/trouble_cluster_offline_cert.adoc#troubleshooting-imported-clusters-offline-after-certificate-change[Troubleshooting imported clusters offline after certificate cha
Is this so common that we need to add this to the procedure doc? @swopebe

2023-07-05 14:18 UTC, dockerymick commented
@swopebe @dhaiducek @JustinKuli Good morning! @Xiang-Yin-ACM recommended a different QE contact. Are there any objections to merging this PR if it meets the modular doc goal? From my perspective, the architecture changes look good. I know that we (doc team) are looking to open our 2.9_stage branch at the start of Sprint 0.  We can address the hidden comments, command changes, and other updates in 2.9 and backport to 2.8 only

2023-07-05 14:53 UTC, dhaiducek commented
That works for me--however, I would like to verify the namespace of the `ocm-webhook` command first, which I'm working on right now. If it changed in `2.8`, it'd be nice to fix it now while we're updating these pages.

2023-07-05 16:00 UTC, gparvin commented
/cc @subbarao-meduri 
Subbarao should take a look at these changes too.  Thanks

2023-07-05 16:56 UTC, dockerymick commented
@dhaiducek sounds good ! @gparvin yes I agree. I plan to create another issue to address other changes outside of doc arch changes.

2023-07-05 20:11 UTC, gparvin commented on governance/certificates.adoc
> +All certificates required by services that run on {product-title-short} are created during the installation of {product-title-short}. You must create a Kubernetes TLS Secret for your certificate. Aft
```suggestion
All certificates required by services that run on {product-title-short} are created during the installation of {product-title-short}. Certificates are created and managed by the following components of the OpenShift platform:
```

2023-07-05 20:22 UTC, gparvin commented on governance/cert_manage.adoc
> +*Note:* After you delete the secret, a new one is created. However, you must restart pods that use the secret manually so they can begin to use the new certificate.
The table of certificate details in the "certificates.adoc" file was intended to capture the list of certificates that are not managed by one of the expected openshift certificate management mechanisms.  It seems that table and this procedure have moved away from each other -- it's certainly outdated now too so needs additional review

2023-07-05 20:52 UTC, dhaiducek commented on governance/cert_manage.adoc
> +oc delete secret -n open-cluster-management ocm-webhook-secret
I grabbed a `2.7` cluster, and the namespace is `multicluster-engine` there, so the namespace definitely should be updated.

2023-07-05 20:53 UTC, dhaiducek commented on governance/cert_manage.adoc
> +oc delete po -n open-cluster-management ocm-webhook-679444669c-5cg76
I grabbed a `2.7` cluster, and the namespace is `multicluster-engine` there, so the namespace definitely should be updated.

The label there is also `-l control-plane=ocm-webhook`, so let's move forward with this command:
```
oc delete pod -n multicluster-engine -l control-plane=ocm-webhook
```

2023-07-06 09:48 UTC, zhiweiyin318 commented on governance/cert_manage.adoc
> +oc delete secret -n open-cluster-management ocm-webhook-secret
the secret name is ocm-webhook, not ocm-webhook-secret. and from ACM 2.5 ocm-wehook was moved to MCE.

2023-07-06 09:49 UTC, zhiweiyin318 commented on governance/cert_manage.adoc
> +oc delete po -n open-cluster-management ocm-webhook-679444669c-5cg76
yes, we can use `oc delete pod -n multicluster-engine -l control-plane=ocm-webhook` to delete ocm-webhook pods.

2023-07-06 13:32 UTC, dockerymick commented on governance/cert_manage.adoc
> +*Note:* After you delete the secret, a new one is created. However, you must restart pods that use the secret manually so they can begin to use the new certificate.
Yes the tasks are moved to the cert_manage.adoc file

2023-07-06 13:56 UTC, dhaiducek commented on governance/cert_manage.adoc
> +oc delete secret -n open-cluster-management ocm-webhook-secret
Thanks, @zhiweiyin318!

@dockerymick in this case, the command should be:
```suggestion
oc delete secret -n multicluster-engine ocm-webhook
```

2023-07-06 13:57 UTC, dhaiducek commented on governance/cert_manage.adoc
> +oc delete secret -n open-cluster-management ocm-webhook-secret
Resolving in favor of the new thread: https://github.com/stolostron/rhacm-docs/pull/5221#discussion_r1254204180

2023-07-07 14:10 UTC, dockerymick commented on governance/certificates.adoc
> +| channels-apps-open-cluster-management-webhook-svc
@gparvin I believe this is the table you were referring to

2023-07-07 15:22 UTC, dhaiducek requested changes

2023-07-07 15:22 UTC, dhaiducek commented on governance/cert_manage.adoc
> +oc delete pod -n multicluster-engine ocm-webhook-679444669c-5cg76
```suggestion
oc delete pod -n multicluster-engine -l control-plane=ocm-webhook
```

2023-07-10 19:59 UTC, dockerymick commented on governance/cert_manage.adoc
> +//If we want to keep the previous statement^, we must provide a verification step for the user to conform that the cert was rotated successfully
@dhaiducek Just checking for the status of the verification step. I know the team is working hard on the FIPS updates.

2023-07-12 20:16 UTC, dockerymick commented on governance/cert_manage.adoc
> +//If we want to keep the previous statement^, we must provide a verification step for the user to conform that the cert was rotated successfully
@gparvin

2023-07-13 13:45 UTC, gparvin commented on governance/cert_manage.adoc
> +. Delete the following content in the `data` section: `ca.crt`, `ca.key`, tls.crt`, and `tls.key`.
```suggestion
. Delete the following content in the `data` section: `ca.crt`, `ca.key`, `tls.crt`, and `tls.key`.
```

2023-07-13 19:04 UTC, gparvin commented on governance/cert_manage.adoc
> +//If we want to keep the previous statement^, we must provide a verification step for the user to conform that the cert was rotated successfully
Verifying a certificate has been rotated is a general thing that applies to anything we're rotating in ACM -- not just the gatekeeper certificate.  Regardless of which certificate is involved, the scenario is "mostly" the same.  So the procedure would be:

1. Identify the secret containing the secret based on the details included in this section
2. Most secrets contain the certificate in the `tls.crt` key of secret data.  You should validate that is the case for your secret.
3. Run this command to display the certificate contents: `oc get secret multicluster-operators-application-svc-ca -o jsonpath='{.data.tls\.crt}' | base64 -d | openssl x509 -text -noout`
4. Check the Validity details in the output.  The "Not Before" value shows when the certificate was created which should correspond to the time you rotated the certificate.  Sample output:
   ```
           Validity
               Not Before: Jul 13 15:17:50 2023 GMT
               Not After : Jul 12 15:17:50 2024 GMT
   ```

2023-07-14 17:41 UTC, dockerymick commented on governance/cert_manage.adoc
> +- <<rotating-the-gatekeeper-webhook-certificate,Rotating the gatekeeper webhook certificate>>
I think we should consider creating a file specifically for rotating certificates. There should also be a section in that file titled, Verifying certificates. Gus mentioned that it was a general task in his [comment](https://github.com/stolostron/rhacm-docs/pull/5221#discussion_r1262954590)

2023-07-14 19:04 UTC, gparvin commented on governance/cert_manage.adoc
> +- <<rotating-the-gatekeeper-webhook-certificate,Rotating the gatekeeper webhook certificate>>
My draft document for rotating certificates that ACM manages is here: https://docs.google.com/document/d/1wGfnomebYViZe2vhKhN0RQfoMP0KIGRnhHQg_uXe6Bw/edit
I'm not sure if you want to think about this in this PR or another one.

2023-07-17 12:43 UTC, dockerymick commented on governance/cert_manage.adoc
> +- <<rotating-the-gatekeeper-webhook-certificate,Rotating the gatekeeper webhook certificate>>
@gparvin I will handle the changes based on your Google doc in this PR. Thanks again for starting this!

2023-07-19 13:34 UTC, dockerymick commented on governance/cert_manage.adoc
> +//If we want to keep the previous statement^, we must provide a verification step for the user to conform that the cert was rotated successfully
Recently added this section

2023-07-19 13:44 UTC, dockerymick commented on governance/cert_manage.adoc
> +openssl x509  -noout -text -in ./observability.crt
Added this as a hidden comment in the file so that we can move forward. this pr is for modular changes

2023-07-19 13:45 UTC, dockerymick commented on governance/cert_manage.adoc
> +. Change the SAN in the `csr.cnf` configuration file with the hostname for your alertmanager route.
Added question as a hidden comment

2023-07-19 13:49 UTC, dockerymick commented on governance/cert_manage.adoc
> +*Note:* If observability is enabled, there are additional namespaces where certificates are created.
added question as a hidden comment

2023-07-19 14:05 UTC, dockerymick commented on governance/cert_manage.adoc
> +<2> The `Not After` value is the date and time for the certificate expiration.
@gparvin I recently added the verifying section. When you have an opportunity, will you review? I added @dhaiducek questions as hidden comments in the file. After you review this section, I am comfortable with merging this PR. The modular updates are complete

2023-07-24 14:37 UTC, gparvin approved these changes
I validated the verification section you added looks good.  Thanks!

2023-07-24 14:39 UTC, dockerymick commented on governance/cert_manage.adoc
> +<2> The `Not After` value is the date and time for the certificate expiration.
reviewed

2023-07-24 14:43 UTC, dockerymick commented
merging this so changes are pulled in when we create 2.9 branch for doc

2023-07-24 15:31 UTC, merged