https://issues.redhat.com/browse/ACM-6269
open-cluster-management/rhacm-docs pull request #5276
Opened 2023-07-11 11:12 UTC by oafischer

Need guidance on the following:
- The accuracy of the YAML
- Does it make sense to have these examples in the doc?
- Are they in a useful section of the doc?

2023-07-11 15:25 UTC, fxiang1 requested changes

2023-07-11 15:25 UTC, fxiang1 commented on clusters/cluster_lifecycle/ansible_config_cluster.adoc
> +    posthook:
Make sure the indentation below is correct ie. only 2 spaces

```
posthook:
  - extra_vars: {}
     clusterName: test-inno
     type: post_check
     name: ACM Upgrade Checks
prehook:
    - extra_vars: {}
       clusterName: test-inno
       type: pre_check
       name: ACM Upgrade Checks
towerAuthSecret: awx
```
Also I removed the `{code}` after awx. Not sure what that's for?

2023-07-11 15:38 UTC, oafischer commented on clusters/cluster_lifecycle/ansible_config_cluster.adoc
> +    posthook:
Updated, thanks!

2023-07-11 15:46 UTC, fxiang1 approved these changes
LGTM! Thanks Oliver!

2023-07-11 16:02 UTC, cadawson commented on clusters/release_notes/whats_new.adoc
> +- ClusterCurator now supports specifying an Ansible inventory to use for all jobs, and this is available to {mce-short} users in the console as well. See xref:../clusters/cluster_lifecycle/ansible_co
```suggestion
- ClusterCurator now supports specifying an Ansible inventory to use for all jobs, and this is also available to {mce-short} users in the console. See xref:../clusters/cluster_lifecycle/ansible_config_cluster.adoc#specify-ansible-inventory[Specifying an Ansible inventory to use for all jobs] for more information. 
```

2023-07-11 16:03 UTC, cadawson approved these changes
Suggestion, but looks good. Thanks!

2023-07-11 16:11 UTC, dockerymick requested changes
From my perspective, it makes sense to add the section in the Ansible configuration docs. I left a suggestion

2023-07-11 16:11 UTC, dockerymick commented on clusters/release_notes/whats_new.adoc
> +- ClusterCurator now supports specifying an Ansible inventory to use for all jobs, and this is available to {mce-short} users in the console as well. See xref:../clusters/cluster_lifecycle/ansible_co
I checked the issue and didn't see a developer issue related to it. We do update What's new if it is feature work. I would ask for the dev issue for this feature before adding to What's new. 
```suggestion
- Use the `ClusterCurator` resource to specify an Ansible inventory to use for all jobs. This is also available to {mce-short} users in the console as well. See xref:../clusters/cluster_lifecycle/ansible_config_cluster.adoc#specify-ansible-inventory[Specifying an Ansible inventory to use for all jobs] for more information. 
```

2023-07-11 16:11 UTC, ch-stark commented on clusters/cluster_lifecycle/ansible_config_cluster.adoc
> +    posthook:
we could use higher OpenShift versions like 4.13 instead of 4.10

2023-07-11 21:10 UTC, oafischer commented on clusters/release_notes/whats_new.adoc
> +- ClusterCurator now supports specifying an Ansible inventory to use for all jobs, and this is available to {mce-short} users in the console as well. See xref:../clusters/cluster_lifecycle/ansible_co
Here are the related dev issues: https://issues.redhat.com/browse/ACM-4436

https://issues.redhat.com/browse/ACM-3842

I'll add them to the current issue and update this PR tomorrow. Thanks for the review!

2023-07-12 09:42 UTC, oafischer commented on clusters/cluster_lifecycle/ansible_config_cluster.adoc
> +    posthook:
Switched it to 4.13

2023-07-12 17:13 UTC, dockerymick commented on clusters/cluster_lifecycle/ansible_config_cluster.adoc
> +----
Is there a way to verify that the inventory is created?

2023-07-12 17:18 UTC, dockerymick approved these changes
Left a question, just curious. It's like this is a task-based file, might need to become modular in 2.9. I would recommend that we add the command for the user to create the ClusterCurator, and then add command or steps for verification

2023-07-12 17:30 UTC, fxiang1 commented on clusters/cluster_lifecycle/ansible_config_cluster.adoc
> +----
Option 1 is to login to Ansible tower and check that the inventory is in there.

Option 2 is to create an Ansible automation platform credential in ACM:
![image](https://github.com/stolostron/rhacm-docs/assets/38960034/8ed86c01-b3e6-42ff-9931-f83a1d63d1ad)

then go create an Automation template in ACM, once you specify the crendential then you will be able to see the list of inventories from the Ansible tower:
![image](https://github.com/stolostron/rhacm-docs/assets/38960034/7db1b27d-e191-422e-900d-8e8b79ae1304)

2023-07-12 17:32 UTC, fxiang1 commented on clusters/cluster_lifecycle/ansible_config_cluster.adoc
> +----
BTW the ClusterCurator resource doesn't actually create the inventory. Instead the ClusterCurator just runs Ansible jobs from the inventory.

2023-07-12 17:35 UTC, fxiang1 commented on clusters/cluster_lifecycle/ansible_config_cluster.adoc
> +----
For verification purposes, I would suggest looking at the ClusterCurator resource YAML. In the `status` field there will be messages specifying whether all jobs completed successfully or if there are any errors.

2023-07-13 14:56 UTC, merged