https://github.com/stolostron/rhacm-docs/pull/5290--known-issue-ingor…
open-cluster-management/rhacm-docs pull request #5291
Opened 2023-07-17 20:02 UTC by swopebe

…e-flag

2023-07-17 20:13 UTC, dhaiducek requested changes
Thanks @swopebrandi1! I have a minor suggestion/clarification.

2023-07-17 20:13 UTC, dhaiducek commented on release_notes/known_issues_governance.adoc
> +You can manually change the value if you need to implement the `ingorePending` function.
```suggestion
You can set `consolidateManifests: false` if you need to implement the `ignorePending` function.
```

2023-07-17 20:36 UTC, dhaiducek commented
Also, I'm assuming that URL in the PR title was meant to be a Jira issue instead of a different PR?

2023-07-18 13:20 UTC, dhaiducek approved these changes
LGTM! Thanks, @swopebe!

2023-07-18 13:48 UTC, cadawson approved these changes
Looks good. Thanks!

2023-07-18 13:53 UTC, merged