https://issues.redhat.com/browse/ACM-6365
open-cluster-management/rhacm-docs pull request #5294
Opened 2023-07-19 13:45 UTC by faaden123

PR for known issue in applications

2023-07-19 14:03 UTC, fxiang1 requested changes

2023-07-19 14:03 UTC, fxiang1 commented on release_notes/known_issues_application.adoc
> +== Application console does not support Argo CD
I would suggest changing this to:

`Application console does not support Argo CD pull model`

Otherwise it would sound like we don't support Argo CD at all which we do but just not the pull model.

2023-07-19 14:52 UTC, dockerymick requested changes

2023-07-19 14:52 UTC, dockerymick commented on release_notes/known_issues_application.adoc
> +The _Topology_  and _Console_ for _Application_ does not support displaying Argo CD applications deployed by the `Application Set` pull model.
I'm not sure why topology is mentioned. I don't see it in the issue. This is what was in the issue:

"UI does not support Argo CD pull model

ApplicationSet applications deployed using the Argo CD pull model will not display correctly in the topology as they are not supported currently."

**Console** does not support Argo CD pull model: I replaced UI with Console bc that is how it would be written in the product doc. Based on my change, it seems like the known issue should be in the Web console known issue. 

Is there a specific issue due to the ApplicationSet configuration/framework? 


```suggestion
When you deploy `ApplicationSet` applications using the Argo CD pull model, the application is displayed incorrectly from the _Topology_ page.
```

2023-07-19 14:57 UTC, fxiang1 commented on release_notes/known_issues_application.adoc
> +The _Topology_  and _Console_ for _Application_ does not support displaying Argo CD applications deployed by the `Application Set` pull model.
Nope, not an issue due to the ApplicationSet configuration/framework. It's because the ApplicationSet pull model is a new feature in ACM 2.8. The backend of the feature is done but we just didn't have the resources to work on the frontend/console part of the feature.

2023-07-19 15:29 UTC, faaden123 commented on release_notes/known_issues_application.adoc
> +The _Topology_  and _Console_ for _Application_ does not support displaying Argo CD applications deployed by the `Application Set` pull model.
I saw Topology in the Slack thread and believed it referred to the Topology UI as that what was in the message. 

Since it is not an issue with Applications, I'll go ahead and change the correct document, taking in the suggestions.

2023-07-19 16:51 UTC, dockerymick commented on release_notes/known_issues_application.adoc
> +The _Topology_  and _Console_ for _Application_ does not support displaying Argo CD applications deployed by the `Application Set` pull model.
@faaden123 my bad, i definitely read over topolgy lol. Thanks for making the update

2023-07-19 17:01 UTC, dockerymick commented on release_notes/known_issues_console.adoc
> +When you deploy `ApplicationSet` applications using the Argo CD pull model, the application will not display correctly from the _Topology_ page as they are no longer supported.
```suggestion
// 2.8.6365

When you deploy `ApplicationSet` applications using the Argo CD pull model, the application is displayed incorrectly from the _Topology_ page.
```

@fxiang1 should we also remove the following statement: "Click the Topology tab for visual representation of all the applications and resources in your project." from [Application console](https://github.com/stolostron/rhacm-docs/blob/2.8_stage/applications/app_console.adoc).

2023-07-19 17:45 UTC, fxiang1 commented on release_notes/known_issues_console.adoc
> +When you deploy `ApplicationSet` applications using the Argo CD pull model, the application will not display correctly from the _Topology_ page as they are no longer supported.
@dockerymick Nope, we don't need to change anything else in the docs as they should still be working for the ArgoCD push model and other application types.

2023-07-19 17:49 UTC, dockerymick commented on release_notes/known_issues_console.adoc
> +When you deploy `ApplicationSet` applications using the Argo CD pull model, the application will not display correctly from the _Topology_ page as they are no longer supported.
@fxiang1 thanks for confirming!

2023-07-20 15:53 UTC, fxiang1 requested changes

2023-07-20 15:53 UTC, fxiang1 commented on release_notes/known_issues_console.adoc
> +When you deploy `ApplicationSet` applications using the Argo CD pull model, the application will not display correctly from the _Topology_ page as they are no longer supported.
Thanks @faaden123, I think this looks really good now.

I just want to make one minor change which is to replace:
`no longer`
with
`not`

Reason being we never had this support before and we are planning to support this in future releases. Thanks!

2023-07-20 16:02 UTC, faaden123 commented on release_notes/known_issues_console.adoc
> +When you deploy `ApplicationSet` applications using the Argo CD pull model, the application will not display correctly from the _Topology_ page as they are no longer supported.
@fxiang1 Gotcha- fixed. Thank you for the clarification!

2023-07-20 17:02 UTC, fxiang1 approved these changes

2023-07-20 17:14 UTC, dockerymick requested changes

2023-07-20 17:14 UTC, dockerymick commented on release_notes/known_issues_console.adoc
> +When you deploy `ApplicationSet` applications using the Argo CD pull model, the application will not display correctly from the _Topology_ page as they are not supported.
```suggestion

When you deploy `ApplicationSet` applications using the Argo CD pull model, the application is displayed incorrectly from the _Topology_ page. Deploying `ApplicationSet` applications using the Argo CD pull model is not supported. 
```

2023-07-24 14:08 UTC, fxiang1 approved these changes

2023-07-24 15:30 UTC, dockerymick commented on release_notes/known_issues_console.adoc
> +When you deploy `ApplicationSet` applications using the Argo CD pull model, the application is displayed incorrectly from the _Topology_ page. Deploying `ApplicationSet` applications using the Argo C
One more update, otherwise this looks good

```suggestion
When you deploy `ApplicationSet` resources using the Argo CD pull model, the application is displayed incorrectly from the _Topology_ page. Deploying `ApplicationSet` applications using the Argo CD pull model is not supported. 
```

2023-07-24 15:31 UTC, dockerymick approved these changes
Take a look at the suggestion please

2023-07-24 20:20 UTC, merged