https://issues.redhat.com/browse/ACM-6250
open-cluster-management/rhacm-docs pull request #5309
Opened 2023-07-24 20:45 UTC by faaden123

Making necessary changes on 2.6

2023-07-25 13:08 UTC, swopebe requested changes

2023-07-25 13:08 UTC, swopebe commented on observability/observability_enable.adoc
> +*Important:* If you modify the global pull secret for your cluster using the {ocp-short} documentation, update the global pull secret in the observability namespace similarly.  See link:https://docs.
seems an extra space
_by using_ (if not it can be seen as the cluster is using)
_similarly_ is confusing here, can we just make it clearer by saying:

ensure you also.... or something?

2023-07-28 01:24 UTC, dockerymick requested changes

2023-07-28 01:24 UTC, dockerymick commented on observability/observability_enable.adoc
> +*Important:* If you modify the global pull secret for your cluster using the {ocp-short} documentation, update the global pull secret in the observability namespace similarly.  See link:https://docs.
```suggestion
*Important:* If you modify the global pull secret for your cluster by using the {ocp-short} documentation, be sure to also update the global pull secret in the observability namespace. See link:https://docs.openshift.com/container-platform/4.12/openshift_images/managing_images/using-image-pull-secrets.html#images-update-global-pull-secret_using-image-pull-secrets[Updating the global pull secret] for more details.
```

2023-07-28 01:24 UTC, dockerymick commented on observability/observability_enable.adoc
> +*Important:* If you modify the global pull secret for your cluster by using the {ocp-short} documentation, update the global pull secret in the observability namespace similarly.  See link:https://do
there is an extra space before "See"

similarly is confusing here, can we just make it clearer by saying:

If you modify the global pull secret for your cluster by using the {ocp-short} documentation,  ensure you also update the global pull secret in the observability namespace.

2023-07-28 13:52 UTC, dockerymick approved these changes
looks great!

2023-07-30 22:12 UTC, merged