https://issues.redhat.com/browse/ACM-6119
open-cluster-management/rhacm-docs pull request #5333
Opened 2023-07-31 13:41 UTC by faaden123

2023-07-31 13:41 UTC, faaden123 commented on networking/submariner/install_subctl.adoc
> +*Note*: Only the commands listed above support `subctl`.
```suggestion
*Note*: Only the the most relevant commands, including those listed above, support `subctl`. 
```

2023-07-31 13:42 UTC, faaden123 commented on networking/submariner/install_subctl.adoc
> +*Note*: Only the commands listed above support `subctl`.
This is a suggestion following @dfarrell07 suggestion from the previous PR.

2023-07-31 14:29 UTC, dockerymick requested changes

2023-07-31 14:29 UTC, dockerymick commented on networking/submariner/install_subctl.adoc
> +For more information about the `subctl` utility and its commands, see link:https://submariner.io/operations/deployment/subctl/[`subctl` in the Submariner documentation].
Looks like this is a duplicate statement. This statement is also on line 46.

2023-07-31 14:29 UTC, dockerymick commented on networking/submariner/install_subctl.adoc
> +*Note*: Only the commands listed above support `subctl`.
Improve this statement for accessibility: https://www.ibm.com/docs/en/ibm-style?topic=medium-accessibility

2023-07-31 17:25 UTC, faaden123 commented on networking/submariner/install_subctl.adoc
> +For more information about the `subctl` utility and its commands, see link:https://submariner.io/operations/deployment/subctl/[`subctl` in the Submariner documentation].
Thank you!

2023-07-31 17:26 UTC, faaden123 commented on networking/submariner/install_subctl.adoc
>  For more information about the `subctl` utility and its commands, see link:https://submariner.io/operations/deployment/subctl/[`subctl` in the Submariner documentation].
```suggestion

```

2023-07-31 18:20 UTC, dockerymick requested changes

2023-07-31 18:20 UTC, dockerymick commented on networking/submariner/install_subctl.adoc
> +*Note*: Only the commands listed above support `subctl`. For more information about the `subctl` utility and its commands, see link:https://submariner.io/operations/deployment/subctl/[`subctl` in the
Improve this statement for accessibility: https://www.ibm.com/docs/en/ibm-style?topic=medium-accessibility

2023-07-31 20:16 UTC, dfarrell07 commented on networking/submariner/install_subctl.adoc
> +*Note*: Only the commands listed above support `subctl`. For more information about the `subctl` utility and its commands, see link:https://submariner.io/operations/deployment/subctl/[`subctl` in the
```suggestion
*Note*: Red Hat's build of `subctl` only includes commands relevant to ACM deployments. For more information about the `subctl` utility and its commands, see link:https://submariner.io/operations/deployment/subctl/[`subctl` in the Submariner documentation].
```

Same feedback as on https://github.com/stolostron/rhacm-docs/pull/5252.

2023-08-02 19:27 UTC, faaden123 commented on networking/submariner/install_subctl.adoc
> +*Note*: `subctl` can only support commands relevant to {rhacm-short} deployments which are listed above. For more information about the `subctl` utility and its commands, see link:https://submariner.
{rhacm-short} . Need to locate where the shortened version of product names are in docs.

2023-08-04 12:24 UTC, dockerymick requested changes

2023-08-04 12:24 UTC, dockerymick commented on networking/submariner/install_subctl.adoc
> +*Note*: `subctl` can only support commands relevant to {product-title} deployments which are listed above. For more information about the `subctl` utility and its commands, see link:https://submarine
@dfarrell07 made a comment in the [previous PR](https://github.com/stolostron/rhacm-docs/pull/5252#discussion_r1262822375): 

<img width="794" alt="Screenshot 2023-08-04 at 8 21 53 AM" src="https://github.com/stolostron/rhacm-docs/assets/60616885/cb65326f-f712-4149-a843-54e37f618305">

Improve this statement for accessibility: https://www.ibm.com/docs/en/ibm-style?topic=medium-accessibility

Words like above, below, left, right should not be used in customer product doc.

2023-08-09 12:36 UTC, dockerymick commented on networking/submariner/install_subctl.adoc
> +*Note*: `subctl` can only support commands relevant to {product-title} deployments which are listed above. For more information about the `subctl` utility and its commands, see link:https://submarine
```suggestion
*Note*: The Red Hat build of `subctl` includes only the commands that are relevant to the previously mentioned {product-title} deployments. For more information about the `subctl` utility and its commands, see link:https://submariner.io/operations/deployment/subctl/[`subctl` in the Submariner documentation].
```

2023-08-09 12:41 UTC, dockerymick commented
@dfarrell07 @maayanf24 I have made updates to this PR. When you both have an opportunity, will you review it?

2023-08-09 12:46 UTC, cadawson commented on networking/submariner/install_subctl.adoc
> +*Note*: The Red Hat build of `subctl` includes only the commands that are relevant to {product-title}. For more information about the `subctl` utility and its commands, see link:https://submariner.io
```suggestion
*Note*: The Red Hat build of `subctl` only includes the commands that are relevant to {product-title}. For more information about the `subctl` utility and its commands, see link:https://submariner.io/operations/deployment/subctl/[`subctl` in the Submariner documentation].
```

2023-08-09 12:47 UTC, cadawson approved these changes
Looks good. Minor suggestion added. Thanks!

2023-08-10 14:11 UTC, dfarrell07 approved these changes

2023-08-13 07:21 UTC, maayanf24 approved these changes

2023-08-17 14:49 UTC, oafischer approved these changes

2023-08-17 14:49 UTC, merged