[ACM-6261]: Restructuring kubevirt and AWS files to reused 'Accessing a hosted cluster'
open-cluster-management/rhacm-docs pull request #5335
Opened 2023-07-31 17:50 UTC by lahinson

Related Jira: https://issues.redhat.com/browse/ACM-6261

2023-08-03 20:56 UTC, dockerymick requested changes
Started on the review, will continue

2023-08-03 20:56 UTC, dockerymick commented on clusters/hosted_control_planes/configure_hosted_bm.adoc
>  . xref:../hosted_control_planes/hosted_bare_metal_verifying_cluster.adoc#verifying-cluster-creation[Verify hosted cluster creation]
Broken link for Verified hosted cluster creation
<img width="1388" alt="Screenshot 2023-08-03 at 3 42 49 PM" src="https://github.com/stolostron/rhacm-docs/assets/60616885/a0e6f5be-f252-4276-b4d6-eaa5b25d4465">

2023-08-03 20:56 UTC, dockerymick commented on clusters/hosted_control_planes/create_hosted_aws.adoc
> +One `NodePool` resource is created for each zone. The node pool name is suffixed by the zone name. The private subnet for zone is set in `spec.platform.aws.subnet.id`.
I noticed that this file didn't use ordered steps, is there a reason why? Are these ordered tasks or just relevant info? If we choose to move forward with the ordered list, I would write it similar to this:


. Create a hosted control plane cluster from the {mce-short} console by navigating to *Infrastructure* > *Clusters*. 

. On the _Clusters_ page, click *Create cluster* > *Amazon Web Services* > *Hosted* and complete the steps in the console. 

*Important:* When you create a cluster, the {mce-short} controller creates a namespace for the cluster and its resources. Ensure that you include only resources for that cluster instance in that namespace. Destroying the cluster deletes the namespace and all of the resources in it.

. If you want to add your cluster to an existing cluster set, verify that you have `cluster-admin` permissions. You must have the correct permissions on the cluster set to add it. If you do not have `cluster-admin` privileges when you are creating the cluster, you must select a cluster set on which you have `clusterset-admin` permissions. If you do not have the correct permissions on the specified cluster set, the cluster creation fails. Contact your cluster administrator to provide you with `clusterset-admin` permissions if you do not have any cluster set options to select.

. Assign every managed cluster to a managed cluster set. Every managed cluster must be associated with a managed cluster set. If you do not assign the managed cluster to a `ManagedClusterSet` resource, it is automatically added to the `default` managed cluster set.

The transition from release images to proxy information is abrupt. Does the user need to complete a task?

2023-08-03 20:56 UTC, dockerymick commented on clusters/hosted_control_planes/create_hosted_clusters_kubevirt_scaling_node_pool.adoc
> +. You can manually scale a NodePool by using the `oc scale` command:
```suggestion
. You can manually scale a `NodePool` by using the `oc scale` command:
```

OR 

```suggestion
. You can manually scale a node pool by using the `oc scale` command:
```

2023-08-03 20:56 UTC, dockerymick commented on clusters/hosted_control_planes/create_hosted_clusters_kubevirt_default_ingress_dns.adoc
> +Every {ocp-short} cluster includes a default application Ingress controller, which must have an wildcard DNS record associated with it. By default, guest clusters that are created by using the HyperS
```suggestion
Every {ocp-short} cluster includes a default application Ingress controller, which must have an wildcard DNS record associated with it. By default, guest clusters that are created by using the HyperShift KubeVirt provider automatically become a subdomain of the {ocp-short} cluster that the KubeVirt virtual machines run on.
```

2023-08-03 20:56 UTC, dockerymick commented on clusters/hosted_control_planes/create_hosted_clusters_kubevirt_default_ingress_dns.adoc
> +As a result, a KubeVirt guest cluster that is named `guest` and that runs on that underlying {ocp-short} cluster has the following default Ingress:
Is a guest cluster a type of KubeVirt cluster? 

```suggestion
As a result, a KubeVirt cluster that is named `guest` and that runs on the {ocp-short} cluster has the following default Ingress:
```

2023-08-03 20:56 UTC, dockerymick commented on clusters/hosted_control_planes/create_hosted_clusters_kubevirt_default_ingress_dns.adoc
> +*Note:* For the default Ingress DNS to work properly, the underlying cluster that hosts the KubeVirt virtual machines must allow wildcard DNS routes. You can configure this behavior by entering the f
```suggestion
*Note:* For the default Ingress DNS to work properly, the cluster that hosts the KubeVirt virtual machines must allow wildcard DNS routes. You can configure this behavior by entering the following command: `oc patch ingresscontroller -n openshift-ingress-operator default --type=json -p '[{ "op": "add", "path": "/spec/routeAdmission", "value": {wildcardPolicy: "WildcardsAllowed"}}]'`
```

2023-08-04 14:35 UTC, lahinson commented on clusters/hosted_control_planes/configure_hosted_bm.adoc
>  . xref:../hosted_control_planes/hosted_bare_metal_verifying_cluster.adoc#verifying-cluster-creation[Verify hosted cluster creation]
Good catch! Will fix 👍

2023-08-04 14:37 UTC, lahinson commented on clusters/hosted_control_planes/configure_hosted_bm.adoc
>  . xref:../hosted_control_planes/hosted_bare_metal_verifying_cluster.adoc#verifying-cluster-creation[Verify hosted cluster creation]
@dockerymick On second thought, I think the link will work after this PR is merged. As part of this PR, I updated the file name and ID for "Accessing the hosted cluster", so I _think_ the link will work after those changes are merged. If I'm mistaken, please let me know!

2023-08-04 15:19 UTC, dockerymick requested changes

2023-08-04 15:19 UTC, dockerymick commented on clusters/hosted_control_planes/create_hosted_clusters_kubevirt_default_ingress_dns.adoc
> +If you do not want to use the default Ingress and DNS behavior, you can configure a KubeVirt guest cluster with a unique base domain at creation time. This option requires manual configuration steps
Is it necessary to call out those specific "main" tasks? 
```suggestion
If you do not want to use the default Ingress and DNS behavior, you can configure a KubeVirt guest cluster with a unique base domain at creation time. For this option, you must manually complete the configuration steps during creation and involves three main steps: cluster creation, load balancer creation, and wildcard DNS configuration.
```

2023-08-04 15:19 UTC, dockerymick commented on clusters/hosted_control_planes/create_hosted_clusters_kubevirt_default_ingress_dns.adoc
> +----
I recommend that you add the links back to the top of the page and then to the landing page that brought the user here.

2023-08-04 15:19 UTC, dockerymick commented on clusters/hosted_control_planes/create_hosted_clusters_kubevirt_default_ingress_dns.adoc
> +Set up the load balancer that routes to the KubeVirt VMs and assign a wildcard DNS entry to the load balancer IP address. You need to create a load balancer service that routes Ingress traffic to the
Strong description of what the task is and why it's important to the user

2023-08-04 15:19 UTC, dockerymick commented on clusters/hosted_control_planes/create_hosted_clusters_kubevirt_scaling_node_pool.adoc
> +----
Similar comment about links

2023-08-04 15:19 UTC, dockerymick commented on clusters/hosted_control_planes/creating_a_hosted_cluster_kubevirt.adoc
> +Replace values as necessary.
Should you add the explanations similar to the sample on this line: https://github.com/stolostron/rhacm-docs/pull/5335/files#diff-fafdc8d4d7a424d5525ee10b7a9466e296812b1823df0d2e9743e571c77c52a1R30

2023-08-04 15:19 UTC, dockerymick commented on clusters/hosted_control_planes/creating_a_hosted_cluster_kubevirt.adoc
> +After a few moments, you can verify that the hosted control plane pods are running by entering the following command:
```suggestion
After a few moments, verify that the hosted control plane pods are running by entering the following command:
```

2023-08-04 15:19 UTC, dockerymick commented on clusters/hosted_control_planes/creating_a_hosted_cluster_kubevirt.adoc
> +. To check the status of the guest cluster, see the corresponding `HostedCluster` resource:
```suggestion
. To check the status of the guest cluster, see the corresponding `HostedCluster` resource by using the following command:
```

2023-08-04 15:19 UTC, dockerymick commented on clusters/hosted_control_planes/creating_a_hosted_cluster_kubevirt.adoc
> +See the following example output:
```suggestion
The following example output illustrates a fully provisioned `HostedCluster` object. See the following example output:
```

2023-08-04 15:19 UTC, dockerymick commented on clusters/hosted_control_planes/creating_a_hosted_cluster_kubevirt.adoc
> +Next, you canaccess the hosted cluster by following the instructions in xref:../hosted_control_planes/hosting_service_cluster_access.adoc#access-hosted-cluster[Accessing the hosted cluster].
```suggestion
Next, you can access the hosted cluster by following the instructions in xref:../hosted_control_planes/hosting_service_cluster_access.adoc#access-hosted-cluster[Accessing the hosted cluster].
```

OR

```suggestion
[#additional-resources-kubevirt]
== Additional resources

* Access the hosted cluster by following the instructions in xref:../hosted_control_planes/hosting_service_cluster_access.adoc#access-hosted-cluster[Accessing the hosted cluster].
```

2023-08-04 15:19 UTC, dockerymick commented on clusters/hosted_control_planes/hosted_cluster_arm_aws.adoc
> +To run a hosted cluster on an ARM64 {ocp-short} cluster, take the following steps:
```suggestion
To run a hosted cluster on an ARM64 {ocp-short} cluster, complete the following steps:
```

2023-08-04 15:19 UTC, dockerymick commented on clusters/hosted_control_planes/hosted_cluster_arm_aws.adoc
> +For example, through the hosted control planes (`hypershift`) command line interface, enter the following commands, being careful to replace the bucket name, AWS credentials, and region with your inf
```suggestion
For example, through the hosted control planes (`hypershift`) command line interface, enter the following commands, and replace the bucket name, AWS credentials, and region with your information:
```

2023-08-04 15:19 UTC, dockerymick commented on clusters/hosted_control_planes/hosted_cluster_arm_aws.adoc
> +For example, through the hosted control planes (`hypershift`) command line interface, enter the following commands, being careful to replace the cluster name, node pool replicas, base domain, pull se
similar suggestion, remove "being careful"

2023-08-04 15:19 UTC, dockerymick commented on clusters/hosted_control_planes/hosted_cluster_arm_aws.adoc
> +. Add a 64-bit x86 `NodePool` object to the hosted cluster.
```suggestion
. Add a 64-bit x_86 `NodePool` object to the hosted cluster.
```

2023-08-04 15:19 UTC, dockerymick commented on clusters/hosted_control_planes/hosting_service_cluster_access.adoc
> += Accessing the hosted cluster
Match link reference: https://github.com/stolostron/rhacm-docs/pull/5335/files#diff-f77e0dd2b8708890abeec6cccaad4e1b69c1cdf02644366181b6fcc905ce3364R72
```suggestion
= Accessing a hosted cluster
```

2023-08-04 15:19 UTC, dockerymick commented on clusters/hosted_control_planes/hosting_service_cluster_access.adoc
> +You can access the hosted cluster by either getting the `kubeconfig` file and `kubeadmin` credential directly from resources or by using the `hypershift` command line interface to generate a `kubecon
```suggestion
You can access the hosted cluster by either getting the `kubeconfig` file and `kubeadmin` credential directly from resources, or by using the `hypershift` command line interface to generate a `kubeconfig` file.
```

2023-08-04 15:19 UTC, dockerymick commented on clusters/hosted_control_planes/hosting_service_cluster_access.adoc
> +//comment to ensure proper formatting
acknowledged, not sure if you made the comment tho

2023-08-04 15:19 UTC, dockerymick commented on clusters/hosted_control_planes/hosting_service_cluster_configure_metallb.adoc
> +. Create a MetalLB instance:
```suggestion
. Create a `MetalLB` resource instance:
```

2023-08-04 15:19 UTC, dockerymick commented on clusters/hosted_control_planes/hosting_service_cluster_configure_metallb.adoc
> +. Create an address pool with an available range of IP addresses within the node network. Replace the following IP address ranges with an unused pool of available IP addresses in your network.
```suggestion
. Create an address pool with an available range of IP addresses within the node network. Replace the following IP address ranges with an unused pool of available IP addresses in your network. Run the following command:
```

2023-08-04 15:19 UTC, dockerymick commented on clusters/hosted_control_planes/hosting_service_cluster_configure_metallb.adoc
> +. Advertise the address pool by using L2 protocol:
```suggestion
. Advertise the address pool by using L2 protocol. Run the following command:
```

2023-08-04 15:19 UTC, dockerymick commented on clusters/hosted_control_planes/configure_hosted_bm.adoc
>  . xref:../hosted_control_planes/hosted_bare_metal_verifying_cluster.adoc#verifying-cluster-creation[Verify hosted cluster creation]
Change: xref:../hosted_control_planes/hosted_bare_metal_verifying_cluster.adoc#verifying-cluster-creation[Verify hosted cluster creation]

TO 

xref:../hosted_control_planes/verifying_hosted_cluster.adoc#verifying-cluster-creation[Verify hosted cluster creation]

<img width="784" alt="Screenshot 2023-08-04 at 11 12 51 AM" src="https://github.com/stolostron/rhacm-docs/assets/60616885/7138899e-dba2-4060-9142-f7b90d6a675a">

2023-08-04 15:19 UTC, dockerymick commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> +* xref:../hosted_control_planes/hosting_service_cluster_configure_metallb_config.adoc#hosting-service-cluster-configure-metallb-config[Optional: Configuring MetalLB]
Came up as a broken link
<img width="1188" alt="Screenshot 2023-08-04 at 11 17 56 AM" src="https://github.com/stolostron/rhacm-docs/assets/60616885/cd04c8d1-620f-4f7f-9808-2928c459ed79">

2023-08-04 15:19 UTC, dockerymick commented on clusters/hosted_control_planes/verifying_cluster_creation_kubevirt.adoc
> +To verify that your hosted cluster was successfully created, take the following steps.
```suggestion
To verify that your hosted cluster was successfully created, complete the following steps:
```

2023-08-04 17:18 UTC, lahinson commented on clusters/hosted_control_planes/configure_hosted_bm.adoc
>  . xref:../hosted_control_planes/hosted_bare_metal_verifying_cluster.adoc#verifying-cluster-creation[Verify hosted cluster creation]
Ah - thanks! I was looking at the wrong thing. Will fix 👍

2023-08-04 17:25 UTC, lahinson commented on clusters/hosted_control_planes/create_hosted_aws.adoc
> +One `NodePool` resource is created for each zone. The node pool name is suffixed by the zone name. The private subnet for zone is set in `spec.platform.aws.subnet.id`.
@dockerymick Good question! That content was written before I was contributing to the docs, so I'm not sure what the reasoning was for not using ordered steps. I think ordered steps would be easier to follow. I like your suggested revision, so I'll make those changes and will look into the transition from release images to proxy info.

2023-08-04 17:27 UTC, lahinson commented on clusters/hosted_control_planes/create_hosted_clusters_kubevirt_default_ingress_dns.adoc
> +As a result, a KubeVirt guest cluster that is named `guest` and that runs on that underlying {ocp-short} cluster has the following default Ingress:
I don't think a guest cluster is a specific type of KubeVirt cluster, but I will check with engineering.

2023-08-04 18:05 UTC, lahinson commented on clusters/hosted_control_planes/create_hosted_clusters_kubevirt_default_ingress_dns.adoc
> +As a result, a KubeVirt guest cluster that is named `guest` and that runs on that underlying {ocp-short} cluster has the following default Ingress:
Engineering confirmed that we can use "a KubeVirt hosted cluster" here instead of "a KubeVirt guest cluster" to mean any OCP cluster that is hosted by KubeVirt VMs. I'll make that change in this file and throughout the KubeVirt docs for consistency.

2023-08-04 18:06 UTC, lahinson commented on clusters/hosted_control_planes/hosting_service_cluster_access.adoc
> +//comment to ensure proper formatting
I'll add my name and a date to the comment for clarity

2023-08-04 20:12 UTC, lahinson commented on clusters/hosted_control_planes/create_hosted_clusters_kubevirt_default_ingress_dns.adoc
> +----
@dockerymick Is there standard syntax that the RHACM docs use to include a "Back to top" link? Or do we just essentially code an anchor link back to the top of the file?

2023-08-04 20:25 UTC, lahinson commented on clusters/hosted_control_planes/creating_a_hosted_cluster_kubevirt.adoc
> +Replace values as necessary.
I don't have any additional info to add there.

2023-08-04 20:27 UTC, lahinson commented
@dockerymick Thanks so much for your thorough review! I made most of the changes that you suggested. One thing that's still outstanding is the link back to the top that you mentioned in a couple of files. I wasn't sure if we had some standard syntax to do that or if it's just an anchor link. Let me know when you can -- next week is fine.

2023-08-04 20:31 UTC, lahinson commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> +* xref:../hosted_control_planes/hosting_service_cluster_configure_metallb_config.adoc#hosting-service-cluster-configure-metallb-config[Optional: Configuring MetalLB]
fixed

2023-08-04 20:31 UTC, lahinson commented on clusters/hosted_control_planes/create_hosted_clusters_kubevirt_default_ingress_dns.adoc
> +If you do not want to use the default Ingress and DNS behavior, you can configure a KubeVirt guest cluster with a unique base domain at creation time. This option requires manual configuration steps
If I recall correctly from when we added this comment, the engineer wanted me to highlight those specific tasks.

2023-08-07 01:48 UTC, dockerymick commented on clusters/hosted_control_planes/create_hosted_clusters_kubevirt_default_ingress_dns.adoc
> +----
We do not have a standard, but I think that is fair to add to our internal docs. I usually say, "Return to the beginning of this topic, <<title-of-the-page,Title of the page>>."

2023-08-07 13:45 UTC, lahinson commented on clusters/hosted_control_planes/create_hosted_clusters_kubevirt_default_ingress_dns.adoc
> +----
Perfect - thanks! I'll follow your lead :)

2023-08-07 13:52 UTC, lahinson commented on clusters/hosted_control_planes/create_hosted_clusters_kubevirt_scaling_node_pool.adoc
> +----
Links added!

2023-08-07 13:54 UTC, lahinson commented
@dockerymick I think I've now incorporated all of your suggestions. Thanks again! Let me know if you think this is ready to merge.

2023-08-08 17:28 UTC, dockerymick approved these changes
Left a suggestion and comment to consider. The links look great, format of the docs look good, and Linter is working

Approving!

2023-08-08 17:28 UTC, dockerymick commented on clusters/hosted_control_planes/create_hosted_clusters_kubevirt_default_ingress_dns.adoc
> +*Note:* If your cluster is on bare metal, you might need MetalLB so that you can set up load balancer services. For more information, see _Optional: Configuring MetalLB_.
I saw that this link can be accessed from the Managing hosted control plane clusters on OpenShift Virtualization doc. I recommend that you add the link for Optional: Configuring MetalLB to the Additional resources section. Keep it italicized here, but add the reference link in the section

2023-08-08 17:28 UTC, dockerymick commented on clusters/hosted_control_planes/hypershift_cluster_destroy_kubevirt.adoc
> +Replace names where necessary.
Since there is only one step, I wonder if this can be added to a different file, just something to consider. I understand that you are still improving the docs for this

2023-08-08 17:32 UTC, lahinson commented on clusters/hosted_control_planes/create_hosted_clusters_kubevirt_default_ingress_dns.adoc
> +*Note:* If your cluster is on bare metal, you might need MetalLB so that you can set up load balancer services. For more information, see _Optional: Configuring MetalLB_.
Will do!

2023-08-08 17:36 UTC, merged