https://issues.redhat.com/browse/ACM-6511 DR4Hub links update 2.9
open-cluster-management/rhacm-docs pull request #5345
Opened 2023-08-03 10:02 UTC by oafischer

Also for 2.8 and 2.7

2023-08-03 13:12 UTC, birsanv requested changes

2023-08-03 13:12 UTC, birsanv commented on business_continuity/backup_restore/backup_adv_config.adoc
> +- Refer to the link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.13/html/backup_and_restore/application-backup-and-restore#default-velero-cloud-provider-plugins[Defaul
My bad, I put the wrong link, and as a result you also changed the text description

This is the link https://access.redhat.com/documentation/en-us/openshift_container_platform/4.13/html/backup_and_restore/application-backup-and-restore#oadp-setting-resource-limits-and-requests_installing-oadp-aws

So the text should be the same as before, just change the link

2023-08-04 08:41 UTC, oafischer commented on business_continuity/backup_restore/backup_adv_config.adoc
> +- Refer to the link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.13/html/backup_and_restore/application-backup-and-restore#default-velero-cloud-provider-plugins[Defaul
Updated, check if it's OK now. Thanks!

2023-08-04 12:50 UTC, birsanv requested changes
The link looks good now but you removed the second section :) requested in the task

[ ]- Add the following after the phrase  Refer to the [Velero resource requests and limits customization](https://github.com/openshift/oadp-operator/blob/master/docs/config/resource_req_limits.md) to find out more about the DataProtectionApplication parameters :

_Refer to the CPU and memory requirement for configurations([https://access.redhat.com/documentation/en-us/openshift_container_platform/4.13/html-single/backup_and_restore/index#cpu-and-memory-requirement-for-configurations|http://example.com/) for details on backup and restore CPU and memory requirements based on cluster usage.|http://example.com]%29/]_

2023-08-08 09:18 UTC, oafischer commented
Whoops, should be fixed now @birsanv :)

2023-08-08 13:10 UTC, birsanv requested changes

2023-08-08 13:10 UTC, birsanv commented on business_continuity/backup_restore/backup_adv_config.adoc
> +- Refer to the link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.13/html/backup_and_restore/application-backup-and-restore#oadp-setting-resource-limits-and-requests_in
This link is wrong

Should be  https://access.redhat.com/documentation/en-us/openshift_container_platform/4.13/html/backup_and_restore/application-backup-and-restore#default-velero-cloud-provider-plugins

2023-08-08 13:20 UTC, oafischer commented on business_continuity/backup_restore/backup_adv_config.adoc
> +- Refer to the link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.13/html/backup_and_restore/application-backup-and-restore#oadp-setting-resource-limits-and-requests_in
Third time's the charm :)

2023-08-08 13:21 UTC, birsanv approved these changes
lgtm thanks ! :)

2023-08-08 14:34 UTC, dockerymick approved these changes
links look good!

2023-08-08 16:13 UTC, dockerymick approved these changes

2023-08-10 14:31 UTC, merged