[ACM-6433]: Removing references to enabling the hosted control planes feature
open-cluster-management/rhacm-docs pull request #5397
Opened 2023-08-14 19:38 UTC by lahinson

Related Jira: https://issues.redhat.com/browse/ACM-6433

2023-08-14 19:46 UTC, lahinson commented
@rokej This PR removes any references to the "Enabling the hosted control planes feature" section of the ACM docs. PTAL when you can. 

I have a separate Jira in progress to remove the Technology Preview wording where appropriate: https://issues.redhat.com/browse/ACM-6859

Finally, I have one question: If hosted control planes on AWS will remain in Technology Preview for OCP 4.14/ACM 2.9, will HyperShift be enabled by default on that platform as well?

2023-08-24 18:02 UTC, rokej reviewed
@lahinson The change looks good to me. 

One suggestion is that under https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.8/html/clusters/cluster_mce_overview#hosted-control-planes-intro, we should document that the feature is enabled by default. 

And we should have a separate section called (disabling the hosted control planes feature). This section should be similar to the removed "hosted-enable-feature-aws" section but setting those components to "false" instead. The component name "hypershift-preview" is now changed to "hypershift".

2023-08-24 18:04 UTC, lahinson commented
> @lahinson The change looks good to me.
> 
> One suggestion is that under https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.8/html/clusters/cluster_mce_overview#hosted-control-planes-intro, we should document that the feature is enabled by default.
> 
> And we should have a separate section called (disabling the hosted control planes feature). This section should be similar to the removed "hosted-enable-feature-aws" section but setting those components to "false" instead. The component name "hypershift-preview" is now changed to "hypershift".

@rokej Good suggestions! I'll let you know when those updates are ready for review. Thank you!

2023-08-24 18:35 UTC, lahinson commented
@rokej I made the updates that you suggested. We already had a topic about how to disable the feature, so I updated it to refer to the `hypershift` feature instead of `hypershift-preview`, and I made sure that we linked to that doc from the `configure_hosted_aws.adoc` file.

2023-08-31 16:47 UTC, lahinson commented on clusters/hosted_control_planes/configure_hosted_aws.adoc
@rokej I just realized that the *Important* note on line 6 might cause concern once the feature is automatically enabled. Should we update that note to instruct users to disable the feature if the cluster is configured for FIPS mode or is in a disconnected environment?

2023-08-31 17:55 UTC, rokej commented on clusters/hosted_control_planes/configure_hosted_aws.adoc
@lahinson Good catch. We should remove the Important note. Hypershift should be supported in both environments.

2023-08-31 17:57 UTC, rokej approved these changes

2023-08-31 18:46 UTC, cadawson requested changes
It looks like there might be a broken link here.I've suggested what I think is the correct link. If the link is correct as it is, that file needs to be added to the main file. 

A couple of other minor things. 

Looks good! Thanks!

2023-08-31 18:46 UTC, cadawson commented on clusters/hosted_control_planes/enable_or_disable_hosted.adoc
> +*Tip:* You can also disable the `hypershift-addon` for the `local-cluster` from the {mce-short} console after disabling the `hypershift-addon`.
```suggestion
*Note:* You can also disable the `hypershift-addon` for the `local-cluster` from the {mce-short} console after disabling the `hypershift-addon`.
```

2023-08-31 18:46 UTC, cadawson commented on clusters/hosted_control_planes/enable_or_disable_hosted.adoc
> +*Tip:* You can also disable the `hypershift-addon` for the `local-cluster` from the {mce-short} console after disabling the `hypershift-addon`.
We are moving away from using a Tip.

2023-08-31 18:46 UTC, cadawson commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> +- You need to xref:../hosted_control_planes/configure_hosted_aws.adoc#hosted-install-cli[install the hcp command line interface binary].
Capitalize hcp?

2023-08-31 18:46 UTC, cadawson commented on clusters/hosted_control_planes/configure_hosted_aws.adoc
> +* To disable the hosted control planes feature, see xref:../hosted_control_planes/disable_hosted.adoc#hosted-disable-feature[Disabling the hosted control planes feature].
I don't think the disable_hosted.adoc file is listed in the main file. I think this link will break. Maybe the following: 

```suggestion
* To disable the hosted control planes feature, see xref:../hosted_control_planes/enable_or_disable_hosted.adoc#disable-hosted-control-planes[Disabling the hosted control planes feature].
```

2023-09-01 13:12 UTC, lahinson commented on clusters/hosted_control_planes/enable_or_disable_hosted.adoc
> +*Tip:* You can also disable the `hypershift-addon` for the `local-cluster` from the {mce-short} console after disabling the `hypershift-addon`.
Good catch!

2023-09-01 13:13 UTC, lahinson commented on clusters/hosted_control_planes/configure_hosted_aws.adoc
> +* To disable the hosted control planes feature, see xref:../hosted_control_planes/disable_hosted.adoc#hosted-disable-feature[Disabling the hosted control planes feature].
I'll fix that. Thanks!

2023-09-01 13:13 UTC, lahinson commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> +- You need to xref:../hosted_control_planes/configure_hosted_aws.adoc#hosted-install-cli[install the hcp command line interface binary].
I believe it stays lowercase. I can confirm with Roke.

2023-09-01 14:55 UTC, lahinson commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> +- You need to xref:../hosted_control_planes/configure_hosted_aws.adoc#hosted-install-cli[install the hcp command line interface binary].
I got confirmation that it's "hcp" -- lowercase.

2023-09-01 14:56 UTC, lahinson commented
Thanks so much for your review, @cadawson! I fixed the link and updated "Tip" to "Note". I also confirmed that "hcp" should be lowercase.

2023-09-01 17:32 UTC, merged