changed source to sources https://issues.redhat.com/browse/ACM-6811
open-cluster-management/rhacm-docs pull request #5456
Opened 2023-08-30 17:37 UTC by jc-berger

See Jira issue: https://issues.redhat.com/browse/ACM-6811

2023-08-30 19:28 UTC, dockerymick requested changes
This looks good. I ran the link check tool and noticed a broken link

<img width="1500" alt="Screenshot 2023-08-30 at 2 20 25 PM" src="https://github.com/stolostron/rhacm-docs/assets/60616885/8c484622-697c-486d-8df6-0592d6301940">

Will you make the following update (remove double asterisk in all instances to make sure the format is consistent. Double asterisks can affect the doc): 

Change: **Note:** For more details on the prerequisites for deploying `ApplicationSet`, see link:../gitops/gitops_config.adoc#gitops-register[Registering managed clusters to GitOps].


TO 

*Note:* For more details on the prerequisites for deploying `ApplicationSet`, see link:../gitops/gitops_registering.adoc#gitops-register[Registering managed clusters to GitOps].

2023-08-30 19:29 UTC, dockerymick commented
@jc-berger will you remove the documentation label? We don't use labels for PRs

2023-08-31 16:21 UTC, dockerymick approved these changes
Added suggestions and checked links. Remove the extra asterisks. Otherwise this looks good!

2023-08-31 16:21 UTC, dockerymick commented on applications/app_model.adoc
> +*Notes:** It is best practice to create each channel in a unique namespace. However, a Git channel can share a namespace with another type of channel, including Git, Helm, and Object storage.
```suggestion
*Notes:* It is best practice to create each channel in a unique namespace. However, a Git channel can share a namespace with another type of channel, including Git, Helm, and Object storage.
```

2023-08-31 16:21 UTC, dockerymick commented on applications/app_model.adoc
> +*Note:** For more details on the prerequisites for deploying `ApplicationSet`, see link:../gitops/gitops_registering.adoc#gitops-register[Registering managed clusters to GitOps].
```suggestion
*Note:* For more details on the prerequisites for deploying `ApplicationSet`, see link:../gitops/gitops_registering.adoc#gitops-register[Registering managed clusters to GitOps].
```

2023-08-31 17:54 UTC, chenz4027 commented on gitops/gitops_push_pull.adoc
> +        path: guestbook }
Would it be possible to move } to the next line?

2023-08-31 17:55 UTC, chenz4027 commented on applications/app_model.adoc
>          path: sample-application }
same as below

2023-09-01 13:30 UTC, chenz4027 approved these changes
/lgtm

2023-09-01 14:31 UTC, merged