[ACM-6950][ACM-7345] Update advanced config install
open-cluster-management/rhacm-docs pull request #5472
Opened 2023-09-06 17:39 UTC by dislbenn

Updating the `install advanced configuration` docs to reflect how to override ACM components and updating the `what's new` docs to show new toggleable components.

2023-09-06 18:41 UTC, jc-berger approved these changes
/lgtm

2023-09-07 15:49 UTC, dockerymick requested changes

2023-09-07 15:49 UTC, dockerymick commented on install/adv_config_install.adoc
> +| Name                       | Description | Enabled
Adding alt text for the table
```suggestion
.Table list of the deployed components
| Name | Description | Enabled
```

2023-09-07 15:49 UTC, dockerymick commented on install/adv_config_install.adoc
> +| cluster-backup             | Enables backup and restore support for all hub cluster resources such as managed clusters, applications, and policies restore. | false
should "policies restore" be changed to "restore policies", or should "restore" be removed? 

Also "Enables" seem repetitive since we have it as a column and leading verb for most of the descriptions. My thought process when reading: When this component is enabled, xyz can  For some of the descriptions, I attempted to use different verbs. Let me know if my suggestions are inaccurate. 

```suggestion
| app-lifecycle | Unifies and simplifies options for constructing and deploying applications and application updates. | True
| cluster-backup | Provides backup and restore support for all hub cluster resources such as managed clusters, applications, and policies. | False
```

2023-09-07 15:49 UTC, dockerymick commented on install/adv_config_install.adoc
> +| volsync                    | Enables asynchronous replication of persistent volumes within a cluster, or across clusters with storage types that are not otherwise compatible for replication. | true
```suggestion
| cluster-lifecycle | Provides cluster management capabilities for {ocp-short} and {product-title-short} hub clusters. | True
| cluster-permission |  Automatically distributes RBAC resources to managed clusters and manage the lifecycle of those resources. | True
| console | Enables {product-title-short} web console plug-in. | True
| grc | Enables the security enhancement for you to define policies for your clusters. | True
| insights | Identifies existing or potential problems in your clusters. | True
| multicluster-observability | Enables monitoring to gain further insights into the health of your managed clusters. | True
| search | Provides visibility into your Kubernetes resources across all of your clusters. | True
| submariner-addon | Enables direct networking and service discovery between two or more managed clusters in your environment, either on-premises or in the cloud. | True
| volsync | Supports asynchronous replication of persistent volumes within a cluster, or across clusters with storage types that are not otherwise compatible for replication. | True
```

2023-09-07 15:49 UTC, dockerymick commented on install/adv_config_install.adoc
> +{product-title} is installed by using an operator that deploys all of the required components. The operator works to deploy the following components:
```suggestion
{product-title} is installed by using an operator that deploys all of the required components. Some of the listed components are enabled by default. If a component is disabled, that resource is not deployed to the cluster until it is enabled. The operator works to deploy the following components:
```

2023-09-07 15:49 UTC, dockerymick commented on install/adv_config_install.adoc
> +**Important:** When {product-title-short} is installed onto the cluster, not all of the listed components are enabled by default.
I recommend that this Important note be removed. The statement should be moved before the table in my opinion. I made a suggestion on line 4

```suggestion
*Important:* When {product-title-short} is installed onto the cluster, not all of the listed components are enabled by default.
```

2023-09-07 15:49 UTC, dockerymick commented on install/adv_config_install.adoc
> +      enabled: true
```suggestion
[source,yaml]
----
apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  name: multiclusterhub <1>
  namespace: <namespace> <2>
spec:
  overrides:
    components:
    - name: console
      enabled: true 
----
+
1.  Replace `name` with the name of the component.
2. Replace `namespace` with the name of your project.
```

2023-09-07 15:49 UTC, dockerymick commented on install/adv_config_install.adoc
> +The following example displays the `spec.overrides` default template that you can use to enable or disable the component. Replace `namespace` with the name of your project and `name` with the name of
See next suggestion for where I would like to move the statement

```suggestion
The following example displays the `spec.overrides` default template that you can use to enable or disable the component:
```

2023-09-07 15:49 UTC, dockerymick commented on install/adv_config_install.adoc
> +{product-title-short} can be further configured during or after installation by adding one or more of the following attributes to the `MultiClusterHub` custom resource:
```suggestion
You can further configure {product-title-short}  during or after installation by adding one or more attributes to the `MultiClusterHub` custom resource. Continue reading for information about the attributes that can be added.
```

2023-09-07 15:49 UTC, dockerymick commented on install/adv_config_install.adoc
> +**Note** The console is forced to stay off if the {ocp} console is disabled. Similarly, if another component is disabled, that resource will not be deployed to the cluster until it is enabled.
Is "force" necessary ? I recommend moving part of this statement closer to the beginning of this file. 
```suggestion
*Note:* When the {ocp} console is disabled, the console is disabled.
```

2023-09-07 15:49 UTC, dockerymick commented on release_notes/whats_new.adoc
> +* MultiClusterHub now accepts `cluster-permission`, `multicluster-observability`, and `submariner-addon` as toggleable components within the MultiClusterHub CR. Users can choose to enable or disable
```suggestion
* You can now enable or disable the following components by updating the `MultiClusterHub` custom resource, `cluster-permission`, `multicluster-observability`, and `submariner-addon`.
```

2023-09-07 15:49 UTC, dockerymick commented on release_notes/whats_new.adoc
> +* With the migration of multicluster-observability and submariner-addon outside of the {product-title-short} bundle, the `MultiClusterObservability`, `SubmarinerConfig`, and `SubmarinerDiagnoseConfig
Is it important for the user to be aware of the migration? I recommend that we only mention that the tabs are moved to the OCP console page. Will you verify that the tab names match what the user will see in the console? Are the tab names camelcase? Also removing the monospace syntax and italicizing; this change is aligned with the IBM Style guide: 
```suggestion
* With the migration of multicluster-observability and submariner-addon out of the {product-title-short} installation, the _MultiClusterObservability_, _SubmarinerConfig_, and _SubmarinerDiagnoseConfig_ tabs are now removed from the Installed Operators page for {product-title-short} and moved to the {ocp-short} console page.
```

2023-09-07 17:24 UTC, dislbenn commented on install/adv_config_install.adoc
> +| cluster-backup             | Enables backup and restore support for all hub cluster resources such as managed clusters, applications, and policies restore. | false
We can remove "restore" from that line. I'm also in agreement that using "enables" is pretty repetitive, so we can remove that also! Thanks for rewording this section.

2023-09-07 17:28 UTC, dislbenn commented on install/adv_config_install.adoc
> +**Important:** When {product-title-short} is installed onto the cluster, not all of the listed components are enabled by default.
I agree with moving this statement to an earlier line. We can remove this note on this line.

2023-09-07 17:35 UTC, dislbenn commented on install/adv_config_install.adoc
> +      enabled: true
Good suggestion; however, for line 48: `name: multiclusterhub <1>`, we do not want to add the component name to this line. The `name` field on that line is for the name of the `MultiClusterHub` instance that is being created.

2023-09-07 17:35 UTC, dislbenn commented on install/adv_config_install.adoc
> +      enabled: true
I will update this area with the suggestion, but apply the changes to the other `name` field.

2023-09-07 17:43 UTC, dislbenn commented on install/adv_config_install.adoc
> +**Note** The console is forced to stay off if the {ocp} console is disabled. Similarly, if another component is disabled, that resource will not be deployed to the cluster until it is enabled.
"Force" is not necessary, we can just say that "When the console component is disabled, the {ocp} console is disabled."

2023-09-07 17:46 UTC, dislbenn commented on release_notes/whats_new.adoc
> +* With the migration of multicluster-observability and submariner-addon outside of the {product-title-short} bundle, the `MultiClusterObservability`, `SubmarinerConfig`, and `SubmarinerDiagnoseConfig
Mentioning the migration can be avoided; however, I would state the tabs were removed from the Installed Operators page.

2023-09-07 17:51 UTC, dislbenn commented on release_notes/whats_new.adoc
> +* With the migration of multicluster-observability and submariner-addon outside of the {product-title-short} bundle, the `MultiClusterObservability`, `SubmarinerConfig`, and `SubmarinerDiagnoseConfig
Also, the user will not see these tabs anymore, since they are removed from the console. If a user wanted to create or modify the operators CR, they would need to access the `Administration > CustomResourceDefinition` tab and find the CRD that they wish to update the CR for. Or they would need to update the resource using the CLI commands.

2023-09-07 20:01 UTC, jc-berger approved these changes
/lgtm

2023-09-11 13:53 UTC, dockerymick commented on install/adv_config_install.adoc
> +**Important:** When {product-title-short} is installed onto the cluster, not all of the listed components are enabled by default.
```suggestion
*Important:* When {product-title-short} is installed onto the cluster, not all of the listed components are enabled by default.
```

2023-09-11 15:35 UTC, dockerymick commented on install/adv_config_install.adoc
> +**Note:** When the `console` component is disabled, the {ocp} console is disabled.
```suggestion
*Note:* When the `console` component is disabled, the {ocp} console is disabled.
```

2023-09-11 15:36 UTC, dockerymick approved these changes
Looks good to me ! Thanks for yalls patience

2023-09-12 16:46 UTC, jc-berger approved these changes
/lgtm

2023-09-12 16:50 UTC, dockerymick commented
Confirmed that @jc-berger is fine with merging through Slack

2023-09-12 16:51 UTC, merged