https://issues.redhat.com/browse/ACM-7071 Remove API 2.9
open-cluster-management/rhacm-docs pull request #5501
Opened 2023-09-12 09:41 UTC by oafischer

Should we remove the deprecated entries for the 2 APIs as well?

2023-09-12 11:47 UTC, cadawson requested changes
I think we should remove the deprecation when it moves to the removed state. Other than that, it looks good. I don't need to review again. Thanks!

2023-09-12 15:14 UTC, dockerymick commented on release_notes/deprecate_remove.adoc
> +| ManagedClusterSets.cluster.open-cluster-management.io
```suggestion
| `ManagedClusterSets.cluster.open-cluster-management.io`
```

2023-09-12 15:14 UTC, dockerymick commented on release_notes/deprecate_remove.adoc
> +| ManagedClusterSetBindings.cluster.open-cluster-management.io
```suggestion
| `ManagedClusterSetBindings.cluster.open-cluster-management.io`
```

2023-09-14 09:26 UTC, haoqing0110 commented
/lgtm

2023-09-14 09:32 UTC, merged