[ACM-7527]: Adding note about flags in command to create a hosted cluster
open-cluster-management/rhacm-docs pull request #5519
Opened 2023-09-15 17:37 UTC by lahinson

Related Jira: https://issues.redhat.com/browse/ACM-7527

2023-09-18 14:42 UTC, lahinson commented on clusters/hosted_control_planes/create_hosted_aws.adoc
>  <1> The `--zones` flag must specify availability zones within the region that is specified by the `--region` flag. The `--zones` flag is also available on the `hypershift create infra aws` command th
@rokej Should I change the command mentioned on line 56 to `hcp create infra aws`?

2023-09-18 15:07 UTC, rokej commented on clusters/hosted_control_planes/create_hosted_aws.adoc
>  <1> The `--zones` flag must specify availability zones within the region that is specified by the `--region` flag. The `--zones` flag is also available on the `hypershift create infra aws` command th
Yes, In general, we should look for `hypershift create`, `hypershift destroy` and replace all of them with `hcp create` and `hcp destroy`. Thanks

2023-09-18 15:17 UTC, lahinson commented on clusters/hosted_control_planes/create_hosted_aws.adoc
>  <1> The `--zones` flag must specify availability zones within the region that is specified by the `--region` flag. The `--zones` flag is also available on the `hypershift create infra aws` command th
Thanks! Updated ✔️

2023-09-18 15:39 UTC, bryan-cox commented on clusters/hosted_control_planes/create_hosted_aws.adoc
> +For instructions to install the AWS Elastic File Service (EFS) CSI Driver Operator on a hosted cluster, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.13/html/s
nit: Do we want to point to 4.14 docs here?

2023-09-18 16:08 UTC, lahinson commented on clusters/hosted_control_planes/create_hosted_aws.adoc
> +For instructions to install the AWS Elastic File Service (EFS) CSI Driver Operator on a hosted cluster, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.13/html/s
Good catch! I can update that link.

2023-09-18 16:23 UTC, rokej approved these changes

2023-09-18 22:21 UTC, bryan-cox commented
/lgtm

2023-09-19 14:45 UTC, swopebe commented on clusters/hosted_control_planes/create_hosted_aws.adoc
> +. To import the cluster, run the `oc` command that the console provides with the cluster details. When you create the cluster, it is not automatically configured with the management of {product-title
To import the cluster, run the `oc` command that the console provides with the cluster details.

This line has a chance to confuse, especially after translation. Assuming we want them to run the command (which is provided) with the additional cluster details?

With the management of RHACM is a bit confusing, as well.

2023-09-19 15:23 UTC, swopebe requested changes

2023-09-19 15:23 UTC, swopebe commented on clusters/hosted_control_planes/create_hosted_aws.adoc
> +. To import the cluster, run the `oc` command that the console provides with the cluster details. When you create the cluster, it is not automatically configured with the management of {product-title
. The console provides an `oc` command. To import the cluster, run that `oc` command with the additional cluster details, since you cluster was not automatically configured with {product-title-short}.

Something like this...if that is accurate.

2023-09-19 15:23 UTC, swopebe commented on clusters/hosted_control_planes/create_hosted_aws.adoc
> +. To import the cluster, run the `oc` command that the console provides with the cluster details. When you create the cluster, it is not automatically configured with the management of {product-title
Usually we would have an example here, like:

`oc apply <cluster-name> <namespace>`

2023-09-19 15:23 UTC, swopebe commented on clusters/hosted_control_planes/create_hosted_aws.adoc
> +<1> The `--zones` flag must specify availability zones within the region that is specified by the `--region` flag.
The `--zones` flag must specify availability zones within the region, which is specified by the `--region` flag.

Does this work?

2023-09-19 15:23 UTC, swopebe commented on clusters/hosted_control_planes/create_hosted_aws.adoc
>  The following per-zone infrastructure is created for all specified zones:
per-zone? Can we find another way to say that?

2023-09-19 15:23 UTC, swopebe commented on clusters/hosted_control_planes/create_hosted_aws.adoc
> +//lahinson - sept. 2023 - including comment to ensure proper formatting
TY!

2023-09-19 15:23 UTC, swopebe commented on clusters/hosted_control_planes/create_hosted_aws.adoc
> +
I am having a hard time following this. I think an example command might help.

2023-09-19 15:23 UTC, swopebe commented on clusters/hosted_control_planes/create_hosted_aws.adoc
> +Because the secret contains the SSH keys, pull secret, base domain, and AWS credentials, you can use the `hcp create cluster aws` command with the `--secret-creds <my_aws_cred>` flag, where `<my_aws_
I think pulling out the example here is best practice and aligns with most of the content we write.

2023-09-19 15:23 UTC, swopebe commented on clusters/hosted_control_planes/create_hosted_aws.adoc
> +. To create the secret by using the MCE console, from the navigation menu, select *Credentials* and follow the credential creation steps in the console.
MCE conref here

2023-09-19 15:47 UTC, lahinson commented on clusters/hosted_control_planes/create_hosted_aws.adoc
> +. To import the cluster, run the `oc` command that the console provides with the cluster details. When you create the cluster, it is not automatically configured with the management of {product-title
@swopebe I updated the first sentence to `To import the cluster, run the `oc` command that is displayed in the console.`

I didn't write the second sentence about the management of RHACM. I wonder if that can be safely removed? I don't know what it means, either.

2023-09-19 17:37 UTC, lahinson commented on clusters/hosted_control_planes/create_hosted_aws.adoc
> +. To import the cluster, run the `oc` command that the console provides with the cluster details. When you create the cluster, it is not automatically configured with the management of {product-title
I'll use something similar to your suggestion and will ask Roke to check it for accuracy.

2023-09-19 17:42 UTC, lahinson commented on clusters/hosted_control_planes/create_hosted_aws.adoc
> +<1> The `--zones` flag must specify availability zones within the region that is specified by the `--region` flag.
I assume so. Roke and Bryan reviewed this line and didn't mention any issues with it.

2023-09-19 17:43 UTC, lahinson commented on clusters/hosted_control_planes/create_hosted_aws.adoc
>  The following per-zone infrastructure is created for all specified zones:
Changed to "For each specified zone, the following infrastructure is created:"

2023-09-19 17:47 UTC, lahinson commented on clusters/hosted_control_planes/create_hosted_aws.adoc
> +Because the secret contains the SSH keys, pull secret, base domain, and AWS credentials, you can use the `hcp create cluster aws` command with the `--secret-creds <my_aws_cred>` flag, where `<my_aws_
Will do.

2023-09-19 17:49 UTC, lahinson commented on clusters/hosted_control_planes/create_hosted_aws.adoc
> +. To create the secret by using the MCE console, from the navigation menu, select *Credentials* and follow the credential creation steps in the console.
Good catch! Will fix.

2023-09-19 17:51 UTC, lahinson commented on clusters/hosted_control_planes/create_hosted_aws.adoc
> +//lahinson - sept. 2023 - Can we provide an example here?
@rokej Can you think of an example that we can add to show how to use the `--aws-creds` flag to provide credentials?

2023-09-19 17:53 UTC, lahinson commented on clusters/hosted_control_planes/create_hosted_aws.adoc
> +//lahinson - sept. 2023 - Roke, can you confirm that the above statement is accurate?
@rokej Please see my comment on line 17. Thank you!

2023-09-19 17:53 UTC, lahinson commented on clusters/hosted_control_planes/create_hosted_aws.adoc
> +//lahinson - sept. 2023 - Roke, does the example command look correct?
@rokej Please see my comment on line 25. Thank you!

2023-09-21 15:09 UTC, rokej commented on clusters/hosted_control_planes/create_hosted_aws.adoc
> +<1> The `--zones` flag must specify availability zones within the region that is specified by the `--region` flag.
Yes, Brandi's suggestion works as well.

2023-09-21 15:09 UTC, rokej commented on clusters/hosted_control_planes/create_hosted_aws.adoc
> +
Example

```
hcp create cluster aws \
--name $CLUSTER_NAME \
--node-pool-replicas=3 \
--base-domain $BASE_DOMAIN \
--pull-secret $PULL_SECRET \
--aws-creds $AWS_CREDS \
--region $REGION \
```

2023-09-21 15:09 UTC, rokej commented on clusters/hosted_control_planes/create_hosted_aws.adoc
> +//lahinson - sept. 2023 - Can we provide an example here?
Example

```
hcp create cluster aws \
--name $CLUSTER_NAME \
--node-pool-replicas=3 \
--base-domain $BASE_DOMAIN \
--pull-secret $PULL_SECRET \
--aws-creds $AWS_CREDS \
--region $REGION \
```

2023-09-21 15:23 UTC, lahinson commented on clusters/hosted_control_planes/create_hosted_aws.adoc
> +<1> The `--zones` flag must specify availability zones within the region that is specified by the `--region` flag.
updated with Brandi's revision

2023-09-21 17:46 UTC, rokej approved these changes
Thank you @lahinson

2023-09-21 18:31 UTC, swopebe commented
lovely!

2023-09-21 18:32 UTC, swopebe approved these changes

2023-09-21 18:57 UTC, merged