https://issues.redhat.com/browse/ACM-6946 Updates after PM review
open-cluster-management/rhacm-docs pull request #5520
Opened 2023-09-19 03:30 UTC by dockerymick

https://issues.redhat.com/browse/ACM-6946

2023-09-19 18:00 UTC, berenss requested changes

2023-09-19 18:00 UTC, berenss commented on observability/observe_environments_intro.adoc
> +The observability component is a service you can use to understand the state of your clusters. The observability service is deployed by the `multiclusterhub-operator` pod, which is complete during th
The observability component is a service you can use to understand the health of the clusters across your fleet. By default, the Multicluster Observability Operator is enabled during the installation of {product-title-short}. As the  observability component requires a valid object store for metrics storage, it is necessary to follow te steps to configure observability on your hub cluster before you can begin using it. See "1.2. Enabling observability service"

2023-09-19 18:01 UTC, berenss commented on observability/observe_environments_intro.adoc
> +The observability component is a service you can use to understand the state of your clusters. The observability service is deployed by the `multiclusterhub-operator` pod, which is complete during th
..to understand the health and utilization of clusters across your fleet.

2023-09-19 18:01 UTC, berenss commented on observability/observe_environments_intro.adoc
> +The observability component is a service you can use to understand the state of your clusters. The observability service is deployed by the `multiclusterhub-operator` pod, which is complete during th
Multicluster Observability operator

2023-09-22 17:05 UTC, dockerymick commented on observability/customize_observability.adoc
> +//Configure: arrange or order the service task
```suggestion
//Configure: arrange or order the service task

```

2023-09-26 18:28 UTC, dockerymick commented on observability/observability_enable.adoc
> +=== Enabling observability from the {ocp} console
This will address the first request from ACM-7540

2023-09-26 18:28 UTC, dockerymick commented on observability/use_observability.adoc
> +
```suggestion

//this seems more like a configuration section
```

2023-09-26 19:27 UTC, dockerymick commented on observability/customize_observability.adoc
> +//which of these topics should be moved to Using observability?
```suggestion
//I moved some topics to Using observability, need to confirm if changes make sense
```

2023-09-26 19:36 UTC, dockerymick commented on release_notes/whats_new.adoc
> +== Observability
This was added to address Scott's comment: 

"Observability is not a Console feature. It is not part of the console itself, as it is a separate link that launches a new window which runs Grafana for visualizations. 
Generally speaking, we are likely to have updates/release notes into Observability more often than in the Console proper.

So, the Multicluster Observability Operator is enabled by default - this is a NO-OP to the end user; this means this is working like it did before, just a repackaging essentially.
What remains true is that the customer needs to Enable Multicluster Observability by following the usual doc topic : https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.8/html/observability/observing-environments-intro#enabling-observability-service

we want to make sure the user does not get confused by the new wording - the wording makes it seem like they would not need to run the steps in 1.2.2"

2023-09-26 19:38 UTC, dockerymick commented on observability/observe_environments_intro.adoc
> +The observability component is a service you can use to understand the health and utilization of clusters across your fleet. By default, multicluster observability operator is enabled during the inst
This update also addresses the comment from Scott in [ACM-6946](https://issues.redhat.com/browse/ACM-6946):

"So, the Multicluster Observability Operator is enabled by default - this is a NO-OP to the end user; this means this is working like it did before, just a repackaging essentially.
What remains true is that the customer needs to Enable Multicluster Observability by following the usual doc topic : https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.8/html/observability/observing-environments-intro#enabling-observability-service

we want to make sure the user does not get confused by the new wording - the wording makes it seem like they would not need to run the steps in 1.2.2"

2023-09-26 20:18 UTC, dockerymick commented on observability/observability_enable.adoc
> +=== Generating access keys using the AWS Security Service
This change addresses request 3. The info for GCP is on line 107. I will verify that it is updated in 2.8 and earlier

2023-09-26 20:22 UTC, dockerymick commented on observability/observability_enable.adoc
> +[#verifying-thanos-version]
Verify if this is a good location for this. I need help to determine where this step should be placed. There are a lot of substeps. After i receive dev confirmation about the steps, it will be more clear where to place the step

2023-09-26 20:23 UTC, dockerymick commented on observability/observability_enable.adoc
> +== Removing observability
This change is related to the 4th request from 7540

2023-09-26 21:07 UTC, dockerymick commented on observability/use_observability.adoc
> +- For more information, see link:https://prometheus.io/docs/concepts/remote_write_spec/[Prometheus Remote-Write specification].
```suggestion
- For more information, see link:https://prometheus.io/docs/concepts/remote_write_spec/[Prometheus Remote-Write specification].

- For more topics, return to xref:../observability/observe_environments_intro.adoc#observing-environments-intro[Observability service introduction].
```

2023-09-26 21:08 UTC, dockerymick commented on observability/use_observability.adoc
> +//* You can also replace certificates for the `rbac-query-proxy` route. See link:../governance/cert_mgmt_ingress.adoc#openssl-commands-for-generating-a-certificate[OpenSSL commands for generating a c
Need to address this hidden comment.

2023-09-26 21:09 UTC, dockerymick commented on observability/use_observability.adoc
> +//this information is similar syntax used in the API docs. This seems out of place
this needs to be addressed

2023-09-29 17:42 UTC, dockerymick commented on clusters/cluster_lifecycle/single_node_ocp.adoc
> +//this information is also in the customize_observability.adoc file should this be removed for the Customize obseravbility file?
@berenss @bjoydeep @subbarao-meduri It seems like it would be best to add a link reference to this file specifically (single_node_ocp.adoc) from the Customizing observability configuration doc (customize_observability.adoc)

2023-09-29 17:42 UTC, dockerymick commented on clusters/cluster_lifecycle/single_node_ocp.adoc
> +//this information is also in the customize_observability.adoc file should this be removed for the Customize obseravbility file?
```suggestion
//this information is also in the customize_observability.adoc file should this be removed from the Customize obseravbility file? 
```

2023-09-29 17:43 UTC, dockerymick commented on clusters/cluster_lifecycle/single_node_ocp.adoc
> +//this information is also in the customize_observability.adoc file should this be removed from the Customize obseravbility file?
@berenss @bjoydeep @subbarao-meduri It seems like it would be best to add a link reference to this file specifically (single_node_ocp.adoc) from the Customizing observability configuration doc (customize_observability.adoc)

2023-09-29 17:43 UTC, dockerymick commented on observability/observe_environments_intro.adoc
> +//I noticed that multicluster observability operator is capital in the comments, is that how the operator name is displayed from the console?
```suggestion

```

2023-09-29 17:44 UTC, dockerymick commented on observability/observe_environments_intro.adoc
> +The observability component is a service you can use to understand the health and utilization of clusters across your fleet. By default, multicluster observability operator is enabled during the inst
Resolved during live review

2023-10-02 19:10 UTC, swopebe requested changes

2023-10-02 19:10 UTC, swopebe commented on clusters/cluster_lifecycle/single_node_ocp.adoc
> +//this information is also in the customize_observability.adoc file should this be removed from the Customize obseravbility file?
I think we need to keep the Create a Single-Node Openshift topic, though that is a task and it has Dynamic metrics in the middle of it.

It seems creating is for all of cluster, Dynamic is just for observability? If that is the case, we have an observability topic inside MCE, which could present problems since that is more for RHACM.

2023-10-02 19:10 UTC, swopebe commented on observability/observe_environments_intro.adoc
>  * xref:../observability/search_intro.adoc#searching-in-the-console-intro[Searching in the console introduction]
I see there is enable, use, customize....

I think the word "use" can maybe be replaced with something more specific.

2023-10-02 19:10 UTC, swopebe commented on observability/use_observability.adoc
> +* To access the `rbac-query-proxy` route, you must have an OpenShift OAuth access token. The token should be associated with a user or service account, which has permission to get namespaces. For mor
Should these be steps and not bullets?

2023-10-02 19:10 UTC, swopebe commented on observability/use_observability.adoc
> ++
I think these should be broken into two commands/steps.

2023-10-02 19:10 UTC, swopebe commented on observability/use_observability.adoc
> +== Using the external metric query
Accessing?

2023-10-02 19:10 UTC, swopebe commented on observability/use_observability.adoc
> +Use observability to export metrics to external endpoints, which support the Prometheus Remote-Write specification in real time. Complete the following steps to export metrics to external endpoints:
Use observability to export metrics to external endpoints

change to

Export metrics to external endpoints

2023-10-02 19:10 UTC, swopebe commented on observability/use_observability.adoc
> +[#acm-provided-dashboards]
I think this may need to be a separate topic.

2023-10-02 19:11 UTC, swopebe commented on observability/use_observability.adoc
> +[#acm-provided-dashboards]
Viewing Dashboards seems to contain enough info to stand on it's own?

2023-10-03 17:11 UTC, dockerymick commented on observability/customize_observability.adoc
> +<1> The `uwl_metrics_list.yaml` is the key for the ConfigMap data.
```suggestion
<1> Enter the key for the ConfigMap data.
```

2023-10-03 17:11 UTC, dockerymick commented on observability/customize_observability.adoc
> +<2> The value of the ConfigMap data is in YAML format. The `names` section includes the list of metric names, which you want to collect from the `test` namespace. After you create the ConfigMap, the
```suggestion
<2> Enter the value of the ConfigMap data in YAML format. The `names` section includes the list of metric names, which you want to collect from the `test` namespace. After you create the ConfigMap, the specified metrics from the target namespace is collected by the observability collector and pushed to the hub cluster.
```

2023-10-03 17:13 UTC, dockerymick commented on observability/customize_observability.adoc
> +//recommend to remove this info and add reference link to the same section that is within the cluster lifecycle folder. | MJ | 09/29/23
@subbarao-meduri can you remind me if Is this applicable for both MCE and ACM?

2023-10-03 17:14 UTC, dockerymick commented on observability/customize_observability.adoc
> +== Updating the MultiClusterObservability custom resource replicas from the console
```suggestion
== Updating the _MultiClusterObservability_ custom resource replicas from the console
```

2023-10-03 17:15 UTC, dockerymick commented on observability/design_grafana.adoc
> +//@subbarao, can you remind me why users should reference this doc. I recall you said something along the lines of continuous configuration or something
@subbarao-meduri

2023-10-03 17:21 UTC, dockerymick commented on clusters/cluster_lifecycle/single_node_ocp.adoc
> +You can create a single-node OpenShift cluster that contains only a single node. In a standard cluster, there are control plane nodes and separate worker nodes. This configuration can be helpful when
add conref for single-node OpenShift. I suggest {sno}

2023-10-03 17:22 UTC, dockerymick commented on clusters/cluster_lifecycle/single_node_ocp.adoc
> +//this information is also in the customize_observability.adoc file should this be removed from the Customize obseravbility file? Brandi: I agree that this is misplaced if it is only for RHACM uses,
@subbarao-meduri @berenss does the mce user have observability at this point or even knows what it is? If not, they might not use it. Do we need this information in both areas? Where does the user come across this first? Where will the user interact with this first

2023-10-03 17:28 UTC, dockerymick commented on observability/customize_observability.adoc
> +//recommend to remove this info and add reference link to the same section that is within the cluster lifecycle folder. | MJ | 09/29/23
@subbarao-meduri

2023-10-03 21:43 UTC, dockerymick commented on observability/use_observability.adoc
> +//
```suggestion
//is this a substep if the user chooses to access the `rbac-query-proxy`?
```

2023-10-03 21:51 UTC, dockerymick commented on clusters/cluster_lifecycle/single_node_ocp.adoc
> +//this information is also in the customize_observability.adoc file should this be removed from the Customize obseravbility file? Brandi: I agree that this is misplaced if it is only for RHACM uses,
Making a comment here again so that we don't lose the conversation

2023-10-03 22:02 UTC, dockerymick commented on clusters/cluster_lifecycle/single_node_ocp.adoc
> +//this information is also in the customize_observability.adoc file should this be removed from the Customize obseravbility file? Brandi: I agree that this is misplaced if it is only for RHACM uses,
@bjoydeep can you help confirm this since Subbarao is on PTO

2023-10-03 22:04 UTC, dockerymick commented on observability/customize_observability.adoc
> +Add user workload metrics to the `observability-metrics-custom-allowlist` ConfigMape to collect the metrics in the `test` namespace. View the following example:
```suggestion
Add user workload metrics to the `observability-metrics-custom-allowlist` ConfigMap to collect the metrics in the `test` namespace. View the following example:
```

2023-10-03 22:05 UTC, dockerymick commented on observability/customize_observability.adoc
> +<1> In the `names` section, add the name of the custom metrics that is to be collected from the managed cluster.
```suggestion
<1>  Add the name of the custom metrics that are to be collected from the managed cluster.
```

2023-10-03 22:07 UTC, dockerymick commented on observability/customize_observability.adoc
> +<2> In the `rules` section, enter only one value for the `expr` and `record` parameter pair to define the query expression. The metrics are collected as the name that is defined in the `record` param
```suggestion
<2> *Optional:* Enter only one value for the `expr` and `record` parameter pair to define the query expression. The metrics are collected as the name that is defined in the `record` parameter from your managed cluster. The metric value returned are the results after you run the query expression.
```

2023-10-03 22:07 UTC, dockerymick commented on observability/customize_observability.adoc
> +<1>  Add the name of the custom metrics that are to be collected from the managed cluster.
```suggestion
<1> Add the name of the custom metrics that are to be collected from the managed cluster.
```

2023-10-03 22:09 UTC, dockerymick commented on observability/customize_observability.adoc
> +The `names` and `rules` sections are optional. You can use either one or both of the sections.
```suggestion
You can use either one or both of the sections.
```

2023-10-03 22:14 UTC, dockerymick commented on observability/observe_environments_intro.adoc
> +* xref:../observability/use_observability.adoc#using-observability[Using observability]
```suggestion
//looking to rename this section
* xref:../observability/use_observability.adoc#using-observability[Using observability]
```

2023-10-03 22:21 UTC, dockerymick commented on observability/use_observability.adoc
> +//is this a substep if the user chooses to access the `rbac-query-proxy`?
@bjoydeep i need your help confirming if these should be ordered steps or unordered options

2023-10-03 22:21 UTC, dockerymick commented on observability/use_observability.adoc
> ++
done

2023-10-06 21:52 UTC, berenss commented on clusters/cluster_lifecycle/single_node_ocp.adoc
> +//this information is also in the customize_observability.adoc file should this be removed from the Customize obseravbility file? Brandi: I agree that this is misplaced if it is only for RHACM uses,
MCE does not include the RHACM Observability components. It is impossible for the MCE user to deploy Observability - they of course can deploy RHACM first, and then could deploy RHACM Observability. So we do not want any of this to be in an MCE area.

2023-10-06 21:57 UTC, berenss commented on observability/design_grafana.adoc
> +//@subbarao, can you remind me why users should reference this doc. I recall you said something along the lines of continuous configuration or something
This is an odd section - it's a bit of a grab-bag.
The first item `See [uuidegen](https://man7.org/linux/man-pages/man1/uuidgen.1.html) for instructions to create a UUID.` is relevant to `2.3.1. Designing your Grafana dashboard with a ConfigMap` or perhaps maybe it was related to an Observability troubleshooting item. 
The next item is a mention for the ensuing topic `2.6. Using managed cluster labels in Grafana`
And then the last 2 are navigational links back to the top of the sub-topic and back to the top of the Obs topic.  so I'm wondering if we just need to only keep the first bullet, about uuidegen, but move it to Troubleshooting.

2023-10-06 21:58 UTC, berenss commented on observability/customize_observability.adoc
> +//recommend to remove this info and add reference link to the same section that is within the cluster lifecycle folder. | MJ | 09/29/23
This must stay in the RHACM Observability section. It is only possible to do with RHACM and Observability.

2023-10-06 22:01 UTC, berenss commented on observability/use_observability.adoc
> +//is this a substep if the user chooses to access the `rbac-query-proxy`?
I think it is another optional way to get the route and token.

2023-10-09 15:46 UTC, dockerymick commented on observability/use_observability.adoc
> +//* You can also replace certificates for the `rbac-query-proxy` route. See link:../governance/cert_mgmt_ingress.adoc#openssl-commands-for-generating-a-certificate[OpenSSL commands for generating a c
This was addressed during the live review

2023-10-09 15:46 UTC, dockerymick commented on observability/use_observability.adoc
> +//this information is similar syntax used in the API docs. This seems out of place
addressed during live review

2023-10-09 17:35 UTC, dockerymick commented on clusters/cluster_lifecycle/single_node_ocp.adoc
> +//this information is also in the customize_observability.adoc file should this be removed from the Customize obseravbility file? Brandi: I agree that this is misplaced if it is only for RHACM uses,
Removed this section

2023-10-09 17:37 UTC, dockerymick commented on observability/customize_observability.adoc
> +//recommend to remove this info and add reference link to the same section that is within the cluster lifecycle folder. | MJ | 09/29/23
Updated

2023-10-09 18:15 UTC, dockerymick commented on observability/design_grafana.adoc
> +//@subbarao, can you remind me why users should reference this doc. I recall you said something along the lines of continuous configuration or something
@berenss We are working on reducing the inline links, which can be distracting to the user. To work around that, I italicized "uuidegen" in the Designing your Grafana dashboard with a ConfigMap section. Using managed cluster labels in Grafana seemed like a related resource. The last two resources take the user back to the main topic that they were referenced from and to the beginning, in case the user chooses not to use the TOC 

Does that seem helpful? If not, I'm open to sharing and discussing. For the sake of the review of the TOC, I would like to make a comment about updating the Additional resources sections.

2023-10-09 18:26 UTC, dockerymick commented on observability/use_observability.adoc
> +//is this a substep if the user chooses to access the `rbac-query-proxy`?
Updated and added hidden comment

2023-10-09 18:27 UTC, dockerymick commented on observability/use_observability.adoc
> +//need to improve the flow here; should these steps be in a separate section? How is this related to querying external queries?
@subbarao-meduri @bjoydeep @berenss

2023-10-10 17:12 UTC, berenss commented on observability/design_grafana.adoc
> +//@subbarao, can you remind me why users should reference this doc. I recall you said something along the lines of continuous configuration or something
Maybe move Additional Resources to the end of the sub topic?

2023-10-10 17:15 UTC, berenss commented on observability/use_observability.adoc
> +//need to improve the flow here; should these steps be in a separate section? How is this related to querying external queries?
This is about using Observability in a different way - rather than the user opening a browser and loading ACM UI and clicking the Grafana link to view metrics graphics, well in this case, the user has decided they want to use their trusty terminal window and grab metrics using CLI methods.
So this is about 'using obs' and it is just a different approach to get what they need.

2023-10-12 00:07 UTC, dockerymick commented on observability/use_observability.adoc
> +- <<external-metric-query,Using the external metric query>>
```suggestion
- <<external-metric-query,Querying external metrics>>
```

2023-10-12 00:11 UTC, dockerymick commented on observability/use_observability.adoc
> +[#acm-provided-dashboards]
```suggestion

[#acm-provided-dashboards]
```

2023-10-12 00:11 UTC, dockerymick commented on observability/use_observability.adoc
> +//need to improve the flow here; should these steps be in a separate section? How is this related to querying external queries?
@berenss thanks for that explanation. i was referring to the lines 26-58. Should this be a subsection to Querying external metrics and named Creating secrets for observability proxy certificates ? Or Querying metrics from proxy certificates?

2023-10-12 00:13 UTC, dockerymick commented on clusters/cluster_lifecycle/single_node_ocp.adoc
> +. Select {ocp-short} 4.11, or later In the _Release image_ field. If you enabled the feature, an option to select *Single node OpenShift* is displayed. If you select an {ocp-short} version that is ea
```suggestion
. Select {ocp-short} 4.11, or later In the _Release image_ field. If you enabled the feature, an option to select *{sno}* is displayed. If you select an {ocp-short} version that is earlier than 4.11, the option to select _Single node OpenShift_ is not displayed. When you select *Single node OpenShift* during the creation process, the _Worker pools_ option is removed from the procedure because there are no worker nodes in a {sno} cluster. 
```

2023-10-12 00:14 UTC, dockerymick commented on clusters/cluster_lifecycle/single_node_ocp.adoc
> +. Select {ocp-short} 4.11, or later In the _Release image_ field. If you enabled the feature, an option to select *{sno}* is displayed. If you select an {ocp-short} version that is earlier than 4.11,
```suggestion
. Select {ocp-short} 4.11, or later In the _Release image_ field. If you enabled the feature, an option to select *{sno}* is displayed. If you select an {ocp-short} version that is earlier than 4.11, the option to select _{sno}_ is not displayed. When you select *{sno}* during the creation process, the _Worker pools_ option is removed from the procedure because there are no worker nodes in a {sno} cluster. 
```

2023-10-12 00:28 UTC, dockerymick commented on observability/use_observability.adoc
> +[#acm-provided-dashboards]
discussed during live review

2023-10-12 23:43 UTC, swopebe commented on observability/observability_enable.adoc
> +- For more related topics, return to the xref:../observability/observe_environments_intro.adoc#observing-environments-intro[Observability service introduction].
We aren't doing this last line consistently and not sure that we need to always have this at the end...

2023-10-12 23:45 UTC, swopebe commented on observability/observe_environments_intro.adoc
>  == Support
"Support"? We have a support section of the doc (troubleshooting) so I am trying to understand this intention of this section. Remember, we don't have to add everything to the doc just bc we are asked, we should consider the meaning of the links...we are basically sending them to the doc again here. Let's simplify the observability doc as much as we can?

2023-10-12 23:48 UTC, swopebe commented on observability/use_observability.adoc
> +[source,yaml]
We have a format issue here, likely due to the table bold tags, which we really can remove and put in code. That is what some of the tables are doing in our doc. So `insecure_skip_verify`

2023-10-12 23:50 UTC, swopebe commented on release_notes/whats_new.adoc
> +//team said nothing new this release, if that is the case, we can remove any section with no updates
Let's remove this comment and make any notes in the what's new issue, to keep comments down. I will know to remove this if there is no update.

2023-10-12 23:51 UTC, swopebe approved these changes
Gonna approve even though I don't want to merge with these internal comments and I want to chat about the "support" section there. We can discuss in Monday's meeting if we have time.

2023-10-16 16:17 UTC, dockerymick commented on observability/use_observability.adoc
> +[source,yaml]
@swopebe thanks for the callout. I removed the extra asterisks

2023-10-16 16:20 UTC, dockerymick commented
@swopebe thanks for approving the PR. I removed most of the hidden comments and fixed the format issue by removing double asterisks. I also understand that we want to take another look at the support section mentioned in the observability docs. Merging this PR so that we can receive a review and feedback from @berenss

2023-10-16 16:20 UTC, merged