https://issues.redhat.com/browse/ACM-7111 Train 06 agent reg API
open-cluster-management/rhacm-docs pull request #5522
Opened 2023-09-19 15:03 UTC by oafischer

2023-09-25 05:59 UTC, xuezhaojun commented
/lgtm

2023-09-25 11:50 UTC, cadawson requested changes
Looks pretty good. A couple of things to fix, but nothing major. Thanks!

2023-09-25 11:50 UTC, cadawson commented on clusters/cluster_lifecycle/import_agent.adoc
> +*Note:* If your hub is using a cluster-wide-proxy, make sure using the URL that managed cluster can access.
```suggestion
*Note:* If your hub cluster is using a cluster-wide-proxy, make sure that you are using the URL that managed cluster can access.
```

2023-09-25 11:50 UTC, cadawson commented on clusters/cluster_lifecycle/import_agent.adoc
> +. Get the token for the agent regsitration sever to authorize by applying the following YAML content:
```suggestion
. Get the token for the agent registration sever to authorize by applying the following YAML content:
```

2023-09-25 11:50 UTC, cadawson commented on clusters/cluster_lifecycle/import_agent.adoc
> +. Enable to automatic approval and patch the content to `cluster-manager` by running the following command:
```suggestion
. Enable the automatic approval and patch the content to `cluster-manager` by running the following command:
```

2023-09-25 11:50 UTC, cadawson commented on clusters/cluster_lifecycle/import_agent.adoc
> +. Switch to your managed cluster and get the cacert by running the following command. Replace
Something is missing here, I think.

2023-09-25 11:50 UTC, cadawson commented on clusters/cluster_lifecycle/import_agent.adoc
> +*Optional*: Replace `<klusterletconfigName>` with the name of your KlusterletConfig.
```suggestion
*Optional:* Replace `<klusterletconfigName>` with the name of your KlusterletConfig.
```

2023-09-25 11:50 UTC, cadawson commented on clusters/cluster_lifecycle/import_gui.adoc
> +. Add the `agent.open-cluster-management.io/klusterlet-config: `<klusterletconfigName>` annotation to the managed cluster, replacing `<klusterletconfigName>` with the name of your `KlusterletConfig`
```suggestion
. Add the `agent.open-cluster-management.io/klusterlet-config: `<klusterletconfigName>` annotation to the managed cluster, replacing `<klusterletconfigName>` with the name of your `KlusterletConfig`.
```

2023-09-25 11:50 UTC, cadawson commented on clusters/cluster_lifecycle/specify_img_registry.adoc
> +See link:../cluster_lifecycle/import_agent.adoc#importing-managed-cluster-agent[Importing a managed cluster by using the agent registration endpoint] to learn more.
```suggestion
See xref:../cluster_lifecycle/import_agent.adoc#importing-managed-cluster-agent[Importing a managed cluster by using the agent registration endpoint] to learn more.
```

2023-09-25 11:52 UTC, cadawson commented
I think adding it as a subtopic of CLI could work.

2023-09-26 09:45 UTC, oafischer commented
We discussed in a meeting a agreed to move forward with the third import option. Merging PR.

2023-09-26 20:28 UTC, cadawson approved these changes
Looks good to me. Thanks, Oliver!

2023-09-27 07:20 UTC, merged