https://issues.redhat.com/browse/ACM-7380 Remove some import steps
open-cluster-management/rhacm-docs pull request #5525
Opened 2023-09-19 17:59 UTC by cadawson

2023-09-19 18:00 UTC, cadawson commented
Hi @KevinFCormier. Here is the updated version. Does it look ok? Thanks!

2023-09-21 15:22 UTC, KevinFCormier approved these changes

2023-10-03 19:29 UTC, dockerymick approved these changes
This looks good to me. Thanks Chris!

2023-10-09 18:22 UTC, swopebe commented
Please do not merge this, needs some editing. TY

2023-10-09 18:25 UTC, swopebe commented on clusters/cluster_lifecycle/import_gui.adoc
> +For the {ocp-short} Dedicated environment only, complete the following steps:
@cadawson are we saying this whole section, manual steps, is for OCP dedicated only and if so, that really should be indicated towards the top, as it is an interruption to read after the initial step.

2023-10-09 18:27 UTC, swopebe commented on clusters/cluster_lifecycle/import_gui.adoc
> +. Install it in the `open-cluster-management` namespace or project that you created.
Per style manuals, we want to try to eliminate the "it" and "this" in our content and be more specific. 

Is the name of the operator simply "klusterlet" (what does the user see) @cadawson ?

2023-10-10 01:45 UTC, cadawson commented on clusters/cluster_lifecycle/import_gui.adoc
> +For the {ocp-short} Dedicated environment only, complete the following steps:
In addition to the standard running of the command, you have to do the steps listed after only for OCP Dedicated.

2023-10-10 02:36 UTC, cadawson commented on clusters/cluster_lifecycle/import_gui.adoc
> +. Install it in the `open-cluster-management` namespace or project that you created.
"Klusterlet operator" is the name of the operator in this context, @swopebe .

2023-10-10 15:05 UTC, dockerymick commented
@swopebe thanks for agreeing to take this issue. are you comfortable with merging this PR?

2023-10-13 00:00 UTC, swopebe requested changes
small comment to address before merge

2023-10-13 00:00 UTC, swopebe commented on clusters/cluster_lifecycle/import_gui.adoc
> +For the {ocp-short} Dedicated environment only, complete the following steps:
I don't think that is answering the question, just quite yet bc to me it seems that whole section is for OCP Dedicated. (?) If that is the case, we should say that earlier. Other than that small change, or editing to make it clearer what it applies to, I think this is done.

2023-10-13 00:00 UTC, swopebe commented on clusters/cluster_lifecycle/import_gui.adoc
> +. Install it in the `open-cluster-management` namespace or project that you created.
Yes, so we should say that.

2023-10-16 18:00 UTC, swopebe commented on clusters/cluster_lifecycle/import_gui.adoc
> +For the {ocp-short} Dedicated environment only, complete the following steps:
DM about this just now.

2023-10-18 17:06 UTC, cadawson commented on clusters/cluster_lifecycle/import_gui.adoc
> +For the {ocp-short} Dedicated environment only, complete the following steps:
Ok, I think the updates address the issue. I made it apply only to the dedicated environment. Thanks @swopebe .

2023-10-18 17:10 UTC, cadawson commented on clusters/cluster_lifecycle/import_gui.adoc
> +. Install it in the `open-cluster-management` namespace or project that you created.
I read too much into that one. Thanks.

2023-10-18 17:48 UTC, swopebe commented on clusters/cluster_lifecycle/import_gui.adoc
> +For the {ocp-short} Dedicated environment only, complete the following steps:
Oh, Ok, I was just going to move the content up higher but I think your solution works as well, I just wanted to make sure that is what you meant first.

2023-10-18 17:49 UTC, swopebe approved these changes
thanks for the edits.

2023-10-18 19:32 UTC, merged