added more content for argo cd push model
open-cluster-management/rhacm-docs pull request #5532
Opened 2023-09-20 18:06 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-7009

2023-09-25 17:26 UTC, dockerymick reviewed
@jc-berger it seems like there will be a few new files added for this PR. I recommend that you create a new file name cluster_permissions_intro.adoc. Add the background info there and then direct users to other new files cluster_permission_policy.adoc

The end of the Google doc says, "We are now ready to deploy apps to the managed clusters using our new managed-sa-sample service account and the permissions that we granted it." 

Which tasks are a part of the objective to Deploy applications by using the ManagedServiceAccount add-on?

2023-09-26 13:28 UTC, philipwu08 commented on gitops/gitops_push_pull.adoc
> +- Now, you can specify the different service account you want the Argo CD push model to use, based on your individual developer needs. Therefore, when the Argo CD  controller pushes resources from th
Instead of "Now", should be specify the actual release number, like ACM 2.9. In ACM 2.10, "now" gives the impression the feature is new.

2023-09-26 13:29 UTC, philipwu08 commented on gitops/gitops_push_pull.adoc
> +- Now, you can specify the different service account you want the Argo CD push model to use, based on your individual developer needs. Therefore, when the Argo CD  controller pushes resources from th
"you can specify the different service account" -> "you can specify a different service account"

2023-09-26 13:31 UTC, philipwu08 commented on gitops/gitops_push_pull.adoc
> +- Now, you can specify the different service account you want the Argo CD push model to use, based on your individual developer needs. Therefore, when the Argo CD  controller pushes resources from th
", based on your individual developer needs" 

Typically, I can it's based on the company's needs but not the individual developer. Might be better to just take this part out though.

2023-09-26 13:48 UTC, philipwu08 commented on gitops/gitops_push_pull.adoc
> +- Now, you can specify the different service account you want the Argo CD push model to use, based on your individual developer needs. Therefore, when the Argo CD  controller pushes resources from th
"Therefore, when the Argo CD  controller pushes resources from the hub to the managed cluster, you can use a different service account than the default application manager."

Maybe too push duplication here? Maybe a point on why they would want to use a different service account? Like: By using a different service account, you have full control over the permissions that is granted to this service account.

That is a good entry to talk about cluster permissions. Maybe add a sentence to introduce cluster permissions and how it could be used to customize the permissions for the service account, like:

The service account must exist on the managed cluster. You may want to use the managedserviceaccount resource, and the new clusterpermission resource, on the hub to facilitate with the creation of the service account with the associated permissions.

2023-09-26 13:58 UTC, philipwu08 commented on gitops/gitops_push_pull.adoc
> +- The Argo CD controller pushes resources from the centralized hub cluster to the managed cluster. For every managed cluster, there is an application manager add-on that runs on the managed cluster.
"The Argo CD controller pushes resources from the centralized hub cluster to the managed cluster"

Maybe this this out? It's seem to be a duplicate of the first bullet.

2023-09-26 14:13 UTC, philipwu08 commented on gitops/gitops_push_pull.adoc
> +- The Argo CD controller pushes resources from the centralized hub cluster to the managed cluster. For every managed cluster, there is an application manager add-on that runs on the managed cluster.
We may want to add a note on why the customer would want to use a different service account, like:

The application manager service account has a broad set of permissions since it’s used by the application subscription addon to deploy applications on the managed cluster. For some users, this may not be desirable, and prefer to use a service account with a limited set of permissions.

2023-09-26 15:21 UTC, xiangjingli commented on gitops/gitops_push_pull.adoc
> +- The Argo CD controller pushes resources from the centralized hub cluster to the managed cluster. For every managed cluster, there is an application manager add-on that runs on the managed cluster.
`The Argo CD controller` should be `The ArgoCD application controller` specifically.

2023-09-26 15:34 UTC, dockerymick commented on gitops/gitops_push_pull.adoc
> +- The Argo CD controller pushes resources from the centralized hub cluster to the managed cluster. For every managed cluster, there is an application manager add-on that runs on the managed cluster.
Based on the Argo CD doc, https://argo-cd.readthedocs.io/en/stable/, please keep my space between Argo and CD `Argo CD application controller

2023-10-03 16:49 UTC, swopebe requested changes

2023-10-03 16:49 UTC, swopebe commented on gitops/gitops_push_pull.adoc
> +- For every managed cluster, there is an application manager add-on that runs on the managed cluster. By default, the Argo CD controller uses the service account application manager to push these res
For every managed cluster, there is an application manager add-on that runs on the managed cluster.

Recommending concise:

An application manager add-on runs on each managed cluster. (No need to say "there is an" and I don't think we need to say managed cluster twice)

2023-10-03 16:49 UTC, swopebe commented on gitops/gitops_push_pull.adoc
> +- The application manager service account has a broad set of permissions because the application subscription add-on uses the application manager service to deploy applications on the managed cluster
The application manager service account uses a large set of permissions because the application subscription add-on uses the application manager service to deploy applications on the managed cluster. (concise from: has a broad set of, changes word usage and tone)

Do not use the application manager service account if you want a limited set of permissions. (imperative mood is a verb form used to make a demand, issue a warning, or give advice or instructions, better than "preference" and almost always the best choice for tech doc.)

2023-10-03 16:49 UTC, swopebe commented on gitops/gitops_push_pull.adoc
> +- You can specify a different service account you want the Argo CD push model to use. Therefore, when the Argo CD controller pushes resources from the centralized hub cluster to the managed cluster,
that you want the Argo CD...

Please take out Therefore, not needed.

please change: have full control over to a simple "can"

2023-10-03 16:49 UTC, swopebe commented on install/adv_config_install.adoc
> +//should this be Technology Preview? This is inconsistent with what is doc'ed in install_upgrade/adv_config_install.adoc. I think it isn't TP for 2.9, but we need to confirm
Good catch, please check with Chris who I think wrote this.

2023-10-03 16:49 UTC, swopebe commented on install/adv_config_install.adoc
> +//should this be Technology Preview? This is inconsistent with what is doc'ed in install_upgrade/adv_config_install.adoc. I think it isn't TP for 2.9, but we need to confirm
I see some inconsistency in naming (capital letters vs not). I wrote this to start and I think when it is not clear, the general rule is to do the same everywhere: 

Push model/push model
Pull model/pull model

2023-10-03 16:49 UTC, swopebe commented on gitops/gitops_service_account_argo_cd.adoc
> +* The application subscription addon, or application manager, must be installed on your managed cluster because it creates a secret in the managed cluster namespace. This secret contains the access t
we need to make sure we are writing add-on the same throughout the doc:

Preferred add-on noun
Write as shown: hyphenated.

2023-10-03 16:49 UTC, swopebe commented on gitops/gitops_service_account_argo_cd.adoc
> +* The application subscription addon, or application manager, must be installed on your managed cluster because it creates a secret in the managed cluster namespace. This secret contains the access t
I also think we were writing Application manager (not sure, let's look into that)

2023-10-03 16:49 UTC, swopebe commented on gitops/gitops_service_account_argo_cd.adoc
> +* You need a cluster admin role service account for your application manager service account. The application manager service account has a broad set of permissions since the account is used by the a
Same here, please rewrite for conciseness, but why do we say the same thing twice? (line 7)

2023-10-03 16:49 UTC, swopebe commented on gitops/gitops_service_account_argo_cd.adoc
> +Complete the following procedures in the following order:
we don't ever say "in order" as that is a given with the task.

2023-10-03 16:49 UTC, swopebe commented on gitops/gitops_service_account_argo_cd.adoc
> +To work around these limitations, use a customized service account on the managed clusters. Create a service account on a managed cluster by creating a `managedserviceaccount` resource on the hub. Th
what limitations? We don't usually discuss limitations in true procedures...we put those in the release notes. It seems this is a requirement? Simply: (please write out "hub cluster")

Create a service account on a managed cluster by creating a `managedserviceaccount` resource on the hub cluster. Then, use the `clusterpermission` resource to grant specific permissions to the service account.

2023-10-03 16:49 UTC, swopebe commented on gitops/gitops_service_account_argo_cd.adoc
> +By granting cluster permissions to your managed service accounts ,you can deploy applications across managed clusters.
space

2023-10-03 16:49 UTC, swopebe commented on gitops/gitops_service_account_argo_cd.adoc
> +. <<Creating a managed service account>>
<<Creating a managed service account, Creating a managed service account >> is how you build an anchor and our rule is if we have three or more sections, so this is great.

2023-10-03 16:49 UTC, swopebe commented on gitops/gitops_service_account_argo_cd.adoc
> +
There is usually a command to apply, as we would not just assume they have it?

2023-10-03 16:49 UTC, swopebe commented on gitops/gitops_service_account_argo_cd.adoc
> +.Verification
we don't usually use these ^^^ What is the benefit of this?

2023-10-03 16:49 UTC, swopebe commented on gitops/gitops_service_account_argo_cd.adoc
> +* You have completed <<Creating a managed service account>>
We don't need this, as it is understood in the procedure order.

2023-10-03 16:49 UTC, swopebe commented on gitops/gitops_service_account_argo_cd.adoc
> +
Usually there is a command in these examples with two steps. 

Create the YAML
Apply the file

2023-10-03 16:49 UTC, swopebe commented on gitops/gitops_service_account_argo_cd.adoc
> +. Create a NC  `mortage` if one does not already exist.
NC?

2023-10-03 16:49 UTC, swopebe commented on gitops/gitops_service_account_argo_cd.adoc
> +. To create a GitOpsCluster CR, run the following full YAML:
We spell out CR usually.

2023-10-03 16:49 UTC, swopebe commented on gitops/gitops_service_account_argo_cd.adoc
> +
we don't need this

2023-10-03 16:49 UTC, swopebe commented on gitops/gitops_service_account_argo_cd.adoc
> +. Log into the Argo CD UI.
Console, instead of UI

2023-10-03 16:50 UTC, swopebe commented
Some changes needed and some recommended, as well as link to voice and tone guidance. I think this needs to be structured into multiple files within the GitOps guide, not just for easier digest, but easier organization.

2023-10-05 17:00 UTC, jc-berger commented on gitops/gitops_service_account_argo_cd.adoc
> +* The application subscription addon, or application manager, must be installed on your managed cluster because it creates a secret in the managed cluster namespace. This secret contains the access t
Yes, I've made it `add-on` 

For now, I'm keeping it `application manager` because it's lowercased in our `gitops_push-pull.adoc` so I think lowercase in this doc would at least be consistent with other docs within the gitops folder. 

What do you think?

2023-10-05 17:19 UTC, jc-berger commented on gitops/gitops_service_account_argo_cd.adoc
> +
Philip, I didn't see a command in the Gdoc template, do you know if we have one?

2023-10-05 17:19 UTC, jc-berger commented on gitops/gitops_service_account_argo_cd.adoc
> +.Verification
I've removed them :)

2023-10-05 17:20 UTC, jc-berger commented on gitops/gitops_service_account_argo_cd.adoc
> +
Philip, again, I didn't see a command in the Gdoc template. Am I overlooking anything? Do you know if we have one to use here like Brandi suggests?

2023-10-05 17:21 UTC, jc-berger commented on gitops/gitops_service_account_argo_cd.adoc
> +. Create a NC  `mortage` if one does not already exist.
Philip, can `NC` be removed? Or does it stand for something and determines what kind of mortage the user will create?

2023-10-05 17:27 UTC, jc-berger commented on gitops/gitops_service_account_argo_cd.adoc
> +To work around these limitations, use a customized service account on the managed clusters. Create a service account on a managed cluster by creating a `managedserviceaccount` resource on the hub. Th
I've removed these bullets all together. 

What do you think? 

Philip and/or SMEs, is there important meaning loss by removing the content that I did?

2023-10-05 20:43 UTC, xiangjingli commented on gitops/gitops_service_account_argo_cd.adoc
> +
@philipwu08  @fmt47  I remember foundation has changed the way for deploying managed service account component.  Could you double check it and provide the new way if this is not working any more

2023-10-05 20:46 UTC, xiangjingli commented on gitops/gitops_service_account_argo_cd.adoc
> +== Creating a managed service account in GitOpsCluster
The title may be a bit confusing. The below description is accurate
```
Use the GitOpsCluster to create the Argo CD cluster secret using the `managed-sa-sample` service account.
```

2023-10-10 15:10 UTC, philipwu08 commented on gitops/gitops_push_pull.adoc
> +- The application manager service account uses a large set of permissions because the application subscription add-on uses the application manager service to deploy applications on the managed cluste
"The application manager service account uses a large set"

Instead of "uses", maybe use "has" or "is granted"

2023-10-10 15:25 UTC, philipwu08 commented on gitops/gitops_service_account_argo_cd.adoc
> += Creating a customized service account with Argo CD
"Creating a customized service account with Argo CD"

"With" seems to give the impression that ArgoCD is used to create the service account.

I think it's better either:
"Using a customized service account with the Argo CD push model" or "Creating a customized service account for use with the Argo CD push model"

2023-10-10 16:15 UTC, philipwu08 commented on gitops/gitops_service_account_argo_cd.adoc
> +By granting cluster permissions to your managed service accounts, you can deploy applications across managed clusters.
"you can deploy applications across managed clusters.", 

maybe more specific? ==>

"it will have the necessary permission to deploy the application resources on the managed clusters".

2023-10-10 16:17 UTC, philipwu08 commented on gitops/gitops_service_account_argo_cd.adoc
> +. <<Creating a managed service account in GitOpsCluster>>
<<Creating a managed service account in GitOpsCluster>> 

We're not creating the managed service account in the gitopscluster resource. We're "using" or "referencing" the service account in the gitopscluster resource.

2023-10-10 16:26 UTC, philipwu08 commented on gitops/gitops_service_account_argo_cd.adoc
> +Create a managed service account so you can have cluster permissions for your other service accounts. When you create a managed service account, you simultaneously create a secret with the same name
"Create a managed service account so you can have cluster permissions for your other service accounts."

Not sure if that's correct.  There must be existing doc in ACM that talks about managed service accounts already that we could reference: https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.5/html/multicluster_engine/managed-serviceaccount-addon#doc-wrapper

Basically, what we want to say here is something like:
The ManagedServiceAccount custom resource on the hub provides a convenient way to create ServiceAccounts on the managed clusters; When a ManagedServiceAccount custom resource is created in the <managed_cluster> namespace on the hub cluster, a ServiceAccount is created on the managed cluster.

2023-10-10 16:27 UTC, philipwu08 commented on gitops/gitops_service_account_argo_cd.adoc
> +Create a managed service account so you can have cluster permissions for your other service accounts. When you create a managed service account, you simultaneously create a secret with the same name
"When you create a managed service account, you simultaneously create a secret with the same name as the managed service account. This secret is in the cluster namespace for the hub cluster and contains the access token for the `managed-sa-sample` service account that is used in the Argo CD cluster secret."

This is implementation detail. I think we could omit this. Check with the team though.

2023-10-10 16:34 UTC, philipwu08 commented on gitops/gitops_service_account_argo_cd.adoc
> +. Ensure the `managedserviceaccount-preview` component is enabled by running, `oc edit mce multiclusterengine`.
Is it better to reference the managed service account doc here:
https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.5/html/multicluster_engine/managed-serviceaccount-addon#doc-wrapper

The doc above talks about enabling the ManagedClusterAddon for the managed-serviceaccount. It does not talk about enabling the managedserviceaccount-preview feature in MCE. Either case, I think we should reference the doc above on how to enable managed service account and create a managed service account.

We should ask the foundation team if the above doc is correct - is it missing the section to enable the managedserviceaccount-preview feature in MCE.

2023-10-10 16:35 UTC, philipwu08 commented on gitops/gitops_service_account_argo_cd.adoc
> +
We could provide an `oc patch` command to make it simplier, but might be better to take this out and reference the existing managed service account doc.

2023-10-10 16:37 UTC, philipwu08 commented on gitops/gitops_service_account_argo_cd.adoc
> +
@xiangjingli I could verify but I think this is another reason to reference the managed service account doc: https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.5/html/multicluster_engine/managed-serviceaccount-addon#doc-wrapper

This way we're not out-of-sync if there are changes in the future.

2023-10-10 16:42 UTC, philipwu08 commented on gitops/gitops_service_account_argo_cd.adoc
> +. To access the secret for your managed service account, run the following command:
"To access the secret for your managed service account, run the following command: "

I think we can skip this. This is detail I don't think the user needs know about.

2023-10-10 16:45 UTC, philipwu08 commented on gitops/gitops_service_account_argo_cd.adoc
> +To grant permissions to the new service account, use the `clusterpermission` resource. The `clusterpermission` resource helps you deploy your applications.
Maybe add in the beginning:

When the service account is created, is does not have any permission associated to it. To grant permissions ...

2023-10-10 16:51 UTC, philipwu08 commented on gitops/gitops_service_account_argo_cd.adoc
> +To grant permissions to the new service account, use the `clusterpermission` resource. The `clusterpermission` resource helps you deploy your applications.
"The `clusterpermission` resource helps you deploy your applications. "

clusterpermission does not help you deploy your application, it's basically a way to grant permission to your service account, so maybe something like this?

The clusterpermission resource is created in the managed cluster namespace on the hub. It provides a convenient way to create role, clusterrole resources on the managed clusters, and bind them to a service account through a
rolebinding or clusterrolebinding resource.

2023-10-10 16:54 UTC, philipwu08 commented on gitops/gitops_service_account_argo_cd.adoc
> +
You can wrap any yaml with the oc command, like this:
oc apply -f - <<EOF

yaml content in the middle

EOF

For example:
oc apply -f - <<EOF
apiVersion: rbac.open-cluster-management.io/v1alpha1
kind: ClusterPermission
metadata:
  name: clusterpermission-msa-subject-sample
  namespace: cluster1
spec:
  roles:
  - namespace: default
    rules:
    - apiGroups: ["apps"]
      resources: ["deployments"]
      verbs: ["get", "list", "create", "update", "delete", "patch"]
    - apiGroups: [""]
      resources: ["configmaps", "secrets", "pods", "podtemplates", "persistentvolumeclaims", "persistentvolumes"]
      verbs: ["get", "update", "list", "create", "delete", "patch"]
    - apiGroups: ["storage.k8s.io"]
      resources: ["*"]
      verbs: ["list"]
  - namespace: mortgage
    rules:
    - apiGroups: ["apps"]
      resources: ["deployments"]
      verbs: ["get", "list", "create", "update", "delete", "patch"]
    - apiGroups: [""]
      resources: ["configmaps", "secrets", "pods", "services", "namespace"]
      verbs: ["get", "update", "list", "create", "delete", "patch"]
  clusterRole:
    rules:
    - apiGroups: ["*"]
      resources: ["*"]
      verbs: ["get", "list"]
  roleBindings:
  - namespace: default
    roleRef:
      kind: Role
    subject:
      apiGroup: authentication.open-cluster-management.io
      kind: ManagedServiceAccount
      name: managed-sa-sample
  - namespace: mortgage
    roleRef:
      kind: Role
    subject:
      apiGroup: authentication.open-cluster-management.io
      kind: ManagedServiceAccount
      name: managed-sa-sample
  clusterRoleBinding:
    subject:
      apiGroup: authentication.open-cluster-management.io
      kind: ManagedServiceAccount
      name: managed-sa-sample
EOF

2023-10-10 16:58 UTC, philipwu08 commented on gitops/gitops_service_account_argo_cd.adoc
> +. To grant the `managed-sa-sample` service account permission to deploy your sample application, apply the following YAML:
To grant the `managed-sa-sample` service account permission to deploy your sample application

Instead of "your sample application", I think we could be more specific here and say "the sample mortgage application to the mortgage namespace on cluster1", since the permission here is specific to that application

2023-10-10 17:18 UTC, philipwu08 commented on gitops/gitops_service_account_argo_cd.adoc
> +. Create a NC  `mortage` if one does not already exist.
NC stands for namespace. So this needs a bit more explanation.

The sample clusterpermission above creates a role called clusterpermission-msa-subject-sample in the mortgage namespace. Double-checking if this is correct, that the namespace needs to be pre-created.

2023-10-10 17:19 UTC, philipwu08 commented on gitops/gitops_service_account_argo_cd.adoc
> +== Creating a managed service account in GitOpsCluster
Agree, see comment in line 12.

2023-10-10 17:31 UTC, philipwu08 commented on gitops/gitops_service_account_argo_cd.adoc
> +
Maybe a little intro here about the gitopscluster resource first?

The gitopscluster resource uses placement to import selected managed clusters into Argo CD. The includes the creation of the Argo CD cluster secrets, which contains info used to access the clusters. By default, the Argo CD cluster secret uses the application manager service account to access the managed clusters.

You could also reference the doc here: https://github.com/stolostron/rhacm-docs/blob/2.9_stage/gitops/gitops_registering.adoc

2023-10-10 17:31 UTC, philipwu08 commented on gitops/gitops_service_account_argo_cd.adoc
> +Use the GitOpsCluster to create the Argo CD cluster secret using the `managed-sa-sample` service account.
With the intro, we could remove this since it's not exactly correct.

2023-10-10 17:34 UTC, philipwu08 commented on gitops/gitops_service_account_argo_cd.adoc
> +. To update the GitOpsCluster resource to add the `managedServiceAccountRef`, run the following YAML:
To update the GitOpsCluster resource to use the managed service account , add the `managedServiceAccountRef`  property with the name of the managed service account, and run the following YAML.

The yaml could be wraped in the "oc apply -f - << EOF" to get the command

2023-10-10 17:37 UTC, philipwu08 commented on gitops/gitops_service_account_argo_cd.adoc
> +----
This gitopscluster resource yaml is not complete.

See doc: https://github.com/stolostron/rhacm-docs/blob/2.9_stage/gitops/gitops_registering.adoc

So, should look something like this:
apiVersion: apps.open-cluster-management.io/v1beta1
kind: GitOpsCluster
metadata:
  name: gitops-cluster-sample
  namespace: dev
spec:
  argoServer:
    argoNamespace: openshift-gitops
    cluster: local-cluster
  managedServiceAccountRef: managed-sa-sample
  placementRef:
    apiVersion: cluster.open-cluster-management.io/v1beta1
    kind: Placement
    name: aws-app-placement

2023-10-10 17:40 UTC, philipwu08 commented on gitops/gitops_service_account_argo_cd.adoc
> +apiVersion: apps.open-cluster-management.io/v1beta1
FYI, gitopslcuster resource is here already. we can take it out from line 170

2023-10-10 17:41 UTC, philipwu08 commented on gitops/gitops_service_account_argo_cd.adoc
> +Use your cluster secret to deliver an Argo CD application from the Argo CD UI. The Argo CD application is delivered by the managed service account, `managed-sa-sample`.
Is "deploy" better than "deliver"?

2023-10-11 19:14 UTC, jc-berger commented on gitops/gitops_service_account_argo_cd.adoc
> +
Please let me know if I applied the feedback correctly by adding the oc command to the yaml.

2023-10-11 19:14 UTC, jc-berger commented on gitops/gitops_service_account_argo_cd.adoc
> +To create a manages service account, see https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.5/html/multicluster_engine/managed-serviceaccount-addon#doc
Docs, please help me locate the proper file so I can link to it as an xref, not an external link.

2023-10-11 20:14 UTC, philipwu08 commented on gitops/gitops_service_account_argo_cd.adoc
> +
Need an EOF here (at the end)

2023-10-11 20:18 UTC, philipwu08 commented on gitops/gitops_service_account_argo_cd.adoc
> +----
Need an EOF here (at the end) 

Replace ----- with EOF

2023-10-11 20:18 UTC, philipwu08 commented on gitops/gitops_service_account_argo_cd.adoc
> +
Missing EOF at the end, see comment above for location

2023-10-11 20:26 UTC, philipwu08 commented on gitops/gitops_service_account_argo_cd.adoc
> +. The sample `clusterpermission` creates a role called `clusterpermission-msa-subject-sample` in the mortgage namespace. If one does not already exist, create a namespace `mortage`.
namespace `mortage` => namespace called `mortgage`

Note the missing `g` in mortgage.

2023-10-11 20:28 UTC, philipwu08 commented on gitops/gitops_service_account_argo_cd.adoc
> +The GitOpsCluster resource uses placement to import selected managed clusters into the Argo CD push model, including the the creation of the Argo CD cluster secrets which contains information used to
The GitOpsCluster resource uses placement to import selected managed clusters into the Argo CD push model

Remove "push model" at the end. We're importing the clusters into Argo CD only.

2023-10-11 20:29 UTC, philipwu08 commented on gitops/gitops_service_account_argo_cd.adoc
> +. To create a GitOpsCluster custom resource, run the following full YAML:
Insert empty line?

2023-10-11 20:30 UTC, philipwu08 commented on gitops/gitops_service_account_argo_cd.adoc
> +----
Duplicate, we can remove this

2023-10-11 20:31 UTC, philipwu08 commented on gitops/gitops_service_account_argo_cd.adoc
> +---
Do we want to be consistent and wrap this YAML is "oc apply -f - <<EOF

2023-10-11 20:36 UTC, philipwu08 commented on gitops/gitops_service_account_argo_cd.adoc
> +% oc get secrets -n openshift-gitops cluster1-managed-sa-sample-cluster-secret
In the samples we used "cluster1" for the managed cluster. Is this ok or do we use some place holder like {managed cluster}?

2023-10-11 20:48 UTC, philipwu08 commented on gitops/gitops_service_account_argo_cd.adoc
> +. To grant the `managed-sa-sample` service account permission to the sample mortgage application to the mortgage namespace on `cluster1`, apply the following YAML:
to the sample mortgage application to the mortgage namespace on `cluster1`

maybe 

to the sample mortgage application that is deployed to the mortgage namespace on `cluster1`

2023-10-11 20:52 UTC, philipwu08 commented on gitops/gitops_service_account_argo_cd.adoc
> +Use your cluster secret to deploy an Argo CD application from the Argo CD UI. The Argo CD application is deployed by the managed service account, `managed-sa-sample`.
Use your cluster secret to deploy an Argo CD application from the Argo CD UI.

The cluster secret is used automatically, so maybe just say:

Deploy an Argo CD application from the Argo CD UI using the push model.

2023-10-11 20:53 UTC, philipwu08 commented on gitops/gitops_service_account_argo_cd.adoc
> +Use your cluster secret to deploy an Argo CD application from the Argo CD UI. The Argo CD application is deployed by the managed service account, `managed-sa-sample`.
The Argo CD application is deployed by the managed service account,

Maybe replace "by" with "with" or "using"?

2023-10-11 20:56 UTC, philipwu08 commented on gitops/gitops_service_account_argo_cd.adoc
> +Use a single policy to create the managed service account and cluster permission for all the managed clusters. When the GitOpsCluster resource is updated with the `managedServiceAccountRef`, each man
Maybe take this out and add something to the end of the paragraph instead?

"Use a single policy to create the managed service account and cluster permission for all the managed clusters."

2023-10-11 20:57 UTC, philipwu08 commented on gitops/gitops_service_account_argo_cd.adoc
> +Use a single policy to create the managed service account and cluster permission for all the managed clusters. When the GitOpsCluster resource is updated with the `managedServiceAccountRef`, each man
"Therefore, use a single policy."

Something like:

This could be simplified using a policy to create the managed service account and cluster permission for all the managed clusters.

2023-10-11 21:33 UTC, philipwu08 commented on gitops/gitops_service_account_argo_cd.adoc
> +When you apply the `managedServiceAccount` and `clusterPermission` resources to the hub cluster, the placement of this policy is bound to the local cluster. You want to replicate those resources to t
Make take out the last part 

", making it easier to manage the namespaces and clusters"

2023-10-11 21:36 UTC, philipwu08 commented on gitops/gitops_service_account_argo_cd.adoc
> +Using a policy to create the `managedServiceAccount` and `clusterPermission` resources include the following benefits:
I'm not sure what is the right word here, but not "benfits". 

"behaviours", "attributes", ....

2023-10-11 21:39 UTC, philipwu08 commented on gitops/gitops_service_account_argo_cd.adoc
> +* Updating the `managedServiceAccount` and `clusterPermission` object templates in the policy results in updates to all the `managedServiceAccount` and `clusterPermission` resources.
to all the `managedServiceAccount` and `clusterPermission` resources

maybe more specific:

to the `managedServiceAccount` and `clusterPermission` resources in all the managed clusters.

2023-10-11 21:44 UTC, philipwu08 commented on gitops/gitops_service_account_argo_cd.adoc
> +* Updating directly to the `managedServiceAccount` and `clusterPermission` resources becomes reverted because it is enforced by the policy.
"Updating directly to the `managedServiceAccount` and `clusterPermission` resources becomes reverted"

maybe:

 "Updates to the `managedServiceAccount` and `clusterPermission` resources directly will be reverted back because

2023-10-11 21:45 UTC, philipwu08 commented on gitops/gitops_service_account_argo_cd.adoc
> +----
Should we be consistent and wrap it with 

oc apply -f - <<EOF

2023-10-11 21:46 UTC, philipwu08 commented on gitops/gitops_service_account_argo_cd.adoc
> +. In the object template of the policy, iterate through the placement decision of the GitOpsCluster associated placement and apply the following `managedServiceAccount` and `clusterPermission` templa
"In the object template of the policy, iterate through the placement decision of the GitOpsCluster associated placement and apply the following `managedServiceAccount` and `clusterPermission` templates"

maybe

In the object template of the policy, it iterates through the placement decision of the GitOpsCluster associated placement and applies the following `managedServiceAccount` and `clusterPermission` templates

2023-10-13 20:36 UTC, cadawson commented on gitops/gitops_service_account_argo_cd.adoc
> +To create a manages service account, see https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.5/html/multicluster_engine/managed-serviceaccount-addon#doc
```suggestion
To create a manages service account, see https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.5/html/multicluster_engine/managed-serviceaccount-addon#doc-wrapper[Enabling manageserviceaccount add-ons] 
```

2023-10-13 20:37 UTC, cadawson commented on gitops/gitops_service_account_argo_cd.adoc
> +To create a manages service account, see https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.5/html/multicluster_engine/managed-serviceaccount-addon#doc
```suggestion
To create a managed service account, see https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.5/html/multicluster_engine/managed-serviceaccount-addon#doc-wrapper[Enabling managederviceaccount add-ons] 
```

2023-10-13 21:05 UTC, cadawson commented on gitops/gitops_service_account_argo_cd.adoc
> +
Hi @philipwu08. You are correct that you can use the "EOF" format, but for consistency, we break it up in our docs. For example: 

. Create the following YAML file named `yaml.yaml`

----
yaml content here
----

. Apply the file by entering the following command:

----
oc apply -f yaml.yaml
----

2023-10-16 08:59 UTC, cadawson commented on gitops/gitops_service_account_argo_cd.adoc
> +. The sample `clusterpermission` creates a role called `clusterpermission-msa-subject-sample` in the mortgage namespace. If one does not already exist, create a namespace `mortage`.
```suggestion
. The sample `clusterpermission` creates a role called `clusterpermission-msa-subject-sample` in the mortgage namespace. If one does not already exist, create a namespace `mortgage`. 
```

2023-10-16 09:02 UTC, cadawson commented on gitops/gitops_service_account_argo_cd.adoc
> +Use your cluster secret to deploy an Argo CD application from the Argo CD UI. The Argo CD application is deployed by the managed service account, `managed-sa-sample`.
For consistency, we should probably console here instead of UI, unless there is a compelling reason not to do that.

2023-10-16 09:05 UTC, cadawson commented on gitops/gitops_service_account_argo_cd.adoc
> +When you apply the `managedServiceAccount` and `clusterPermission` resources to the hub cluster, the placement of this policy is bound to the local cluster. You want to replicate those resources to t
```suggestion
When you apply the `managedServiceAccount` and `clusterPermission` resources to the hub cluster, the placement of this policy is bound to the local cluster. Replicate those resources to the managed cluster namespace for all of the managed clusters in the placement of the GitOpsCluster resource, which makes it easier to manage the namespaces and clusters.
```

2023-10-16 12:16 UTC, swopebe commented on gitops/gitops_service_account_argo_cd.adoc
> +* The application subscription addon, or application manager, must be installed on your managed cluster because it creates a secret in the managed cluster namespace. This secret contains the access t
Sure, but it is probably wrong. :-)

2023-10-16 12:16 UTC, swopebe commented on gitops/gitops_service_account_argo_cd.adoc
> +
We don't usually write EOF in the docs, @philipwu08 bc we want the YAML as clean as possible, does it break the user here without it?

2023-10-16 12:18 UTC, swopebe commented on gitops/gitops_service_account_argo_cd.adoc
> +. Create a NC  `mortage` if one does not already exist.
We need to ensure we are not using shortcuts or "developer speak" and we write the same way across the whole docs, @philipwu08 -- so here would would write our namespace.

2023-10-16 12:20 UTC, swopebe commented on gitops/gitops_push_pull.adoc
> +- The application manager service account uses a large set of permissions because the application subscription add-on uses the application manager service to deploy applications on the managed cluste
either _contains_ or _has_ on line 86, it is already a bit wordy and hard to understand. We want to make it as concise as possible.

2023-10-16 12:25 UTC, swopebe commented on gitops/gitops_service_account_argo_cd.adoc
> += Creating a customized service account with Argo CD
The title needs to match the actual task. Please be careful with "Using" and we can end up calling everything "Using." :-) We also need to keep it concise, if possible.

Since the user is "Creating" in this task, we need to keep that in the title.

_Creating a customized service account for Argo CD push model_

Does this work?

We don't normally write: _for use with_

2023-10-16 12:29 UTC, swopebe commented on gitops/gitops_service_account_argo_cd.adoc
> +By granting cluster permissions to your managed service accounts, you can deploy applications across managed clusters.
_it will have the_ 

We should not use "to be" phrases in the doc for many reasons, that is why we take them out per our tech writing standards.

It really needs to be rewritten and straight to the point and probably added to the top of the file as the introduction. We tell the user why they need to do it AFTER we tell them what to do...I think we can flip that:

_Grant cluster permissions to your managed service accounts so that you can deploy applications across managed clusters._

Remember: Active voice almost always, and imperative almost always.

2023-10-16 12:30 UTC, swopebe commented on gitops/gitops_service_account_argo_cd.adoc
> +Create a managed service account so you can have cluster permissions for your other service accounts. When you create a managed service account, you simultaneously create a secret with the same name
I agree if it is in the doc, always we don't want to rewrite it.

2023-10-16 12:32 UTC, swopebe commented on gitops/gitops_service_account_argo_cd.adoc
> +. To grant the `managed-sa-sample` service account permission to deploy your sample application, apply the following YAML:
This only works if the sample does not change @philipwu08 -- if you guys change the sample, our doc is out of date.

2023-10-16 12:33 UTC, swopebe commented on gitops/gitops_service_account_argo_cd.adoc
> +. To update the GitOpsCluster resource to add the `managedServiceAccountRef`, run the following YAML:
Again, we don't want to use EOF in official doc

2023-10-16 12:33 UTC, swopebe commented on gitops/gitops_service_account_argo_cd.adoc
> +Use your cluster secret to deliver an Argo CD application from the Argo CD UI. The Argo CD application is delivered by the managed service account, `managed-sa-sample`.
please remove UI, as we need to use the word console

2023-10-16 12:34 UTC, swopebe commented on gitops/gitops_service_account_argo_cd.adoc
> +---
We want to clearly separate YAML samples and not use EOF in official doc

2023-10-16 12:36 UTC, swopebe commented on gitops/gitops_service_account_argo_cd.adoc
> +% oc get secrets -n openshift-gitops cluster1-managed-sa-sample-cluster-secret
@jc-berger you can see where and how it is done throughout the doc so that we are being consistent, but I think it is fair to add a placeholder. I think we normally do <managed-cluster> but please check and let me know if there is inconsistencies.

2023-10-16 12:39 UTC, swopebe commented on gitops/gitops_service_account_argo_cd.adoc
> +Use your cluster secret to deploy an Argo CD application from the Argo CD UI. The Argo CD application is deployed by the managed service account, `managed-sa-sample`.
console or terminal is how we use it in all of RHACM doc, never UI

2023-10-17 13:54 UTC, philipwu08 commented on gitops/gitops_service_account_argo_cd.adoc
> +
Yes, if we use `oc apply -f - <<EOF` then `EOF` is also needed at the end. Or we could change it to what Chris proposed, which is to just include the YAML content, then provide the command separately.

2023-10-17 13:57 UTC, philipwu08 commented on gitops/gitops_service_account_argo_cd.adoc
> +oc apply -f yaml.yaml
If we go with Chris's suggestion, this command needs to be moved after the yaml.

2023-10-17 13:59 UTC, philipwu08 commented on gitops/gitops_service_account_argo_cd.adoc
> +oc apply -f yaml.yaml
Move this command after the yaml for consistency

2023-10-17 14:00 UTC, philipwu08 commented on gitops/gitops_service_account_argo_cd.adoc
> +. To create a policy for a YAML to create a managed service account and cluster permission, run the following YAML:
Since the command comes after the YAML, maybe instead of "run the following YAML", 

==> "create a YAML with the following content"

We save this YAML as policy.yaml?

2023-10-17 14:02 UTC, philipwu08 commented on gitops/gitops_service_account_argo_cd.adoc
> +oc apply -f yaml.yaml
Move command after the YAML?

2023-10-17 14:06 UTC, philipwu08 commented on gitops/gitops_service_account_argo_cd.adoc
> +. To grant the `<managed-sa-sample>` service account permission to the sample mortgage application that is deployed to the mortgage namespace on `<managed cluster>`, apply the following YAML:
"apply the following YAML" 
 
maybe change to "create a YAML with the following content":

Our command "oc apply -f yaml.yaml", expects the YAML to be saved in a file called yaml.yaml. Maybe ask them to save the YAML to a file called "cluster-permission.yaml". This way the yaml will not conflict with other YAMLs they will be saving.

The command is then:
oc apply -f cluster-permission.yaml

2023-10-17 14:10 UTC, philipwu08 commented on gitops/gitops_service_account_argo_cd.adoc
> +. To create a GitOpsCluster custom resource, run the following full YAML:
Save this YAML as gitops.yaml, then the command after the YAML is:

oc apply -f gitops.yaml

2023-10-17 14:12 UTC, philipwu08 commented on gitops/gitops_service_account_argo_cd.adoc
> +oc apply -f yaml.yaml
This is not needed

2023-10-17 19:34 UTC, swopebe commented on gitops/gitops_service_account_argo_cd.adoc
> +
We can do this in another round but I agree that we need split the YAML like we do throughout the doc and provide clear steps to apply them. It seems there may be a formatting issue in the editor that may resolve when we do that or may not, we can investigate. Approving to get us closer to reorg steps.

2023-10-17 19:34 UTC, swopebe approved these changes
Commented

2023-10-18 14:17 UTC, philipwu08 commented on gitops/gitops_service_account_argo_cd.adoc
> +. Run `oc apply -f cluster-permission.yaml`.
We should probably ask them to save the YAML in a file called cluster-permission.yaml, since we're referring to a file by this name for the apply command.

2023-10-18 14:18 UTC, philipwu08 commented on gitops/gitops_service_account_argo_cd.adoc
> +. Run `oc apply -f policy.yaml`.
Same comment. We're referring to policy.yaml but we never asked user to save the YAML in a file with this name.

2023-10-18 14:19 UTC, philipwu08 commented on gitops/gitops_service_account_argo_cd.adoc
> +. Run `oc apply -f gitops.yaml`.
Ask user to save YAML to file called gitops.yaml

2023-10-18 21:28 UTC, xiangjingli commented on gitops/gitops_service_account_argo_cd.adoc
> +. The sample `<clusterpermission>` creates a role called `<clusterpermission-msa-subject-sample>` in the mortgage namespace. If one does not already exist, create a namespace `mortgage`.
Once the sample `<clusterpermission>` is created, the following resources are created in the given managed cluster
- one role called `<clusterpermission-msa-subject-sample>` in the default namespace
- one rolebinding called `<clusterpermission-msa-subject-sample>` in the default namespace for binding the role to the managed service account

- one role called `<clusterpermission-msa-subject-sample>` in the mortgage namespace
- one rolebinding called `<clusterpermission-msa-subject-sample>` in the mortgage namespace for binding the role to the managed service account

-  one clusterrole called `<clusterpermission-msa-subject-sample>`
- one clusterrolebinding called `<clusterpermission-msa-subject-sample>` for binding the clusterRole to the managed service account

2023-10-18 21:30 UTC, xiangjingli commented on gitops/gitops_service_account_argo_cd.adoc
> +. Run `oc apply -f cluster-permission.yaml`.
delete the two lines 
```
. Save the YAML file in a file called, `cluster-permission.yaml`.
. Run `oc apply -f cluster-permission.yaml`. 
```

2023-10-19 20:58 UTC, xiangjingli commented on gitops/gitops_service_account_argo_cd.adoc
> +When the service account is created, is does not have any permission associated to it. To grant permissions to the new service account, use the `clusterpermission` resource. The `clusterpermission` r
When the service account is created, **is** does not have any permission associated to it.
====>
When the service account is created, **it** does not have any permission associated to it.

2023-10-19 21:11 UTC, xiangjingli commented
just one typo left. Once it is fixed, it is good to merge. Great work! @jc-berger

2023-10-20 14:28 UTC, merged