https://issues.redhat.com/browse/ACM-6449 Adding reserved names
open-cluster-management/rhacm-docs pull request #5547
Opened 2023-09-27 19:14 UTC by cadawson

2023-10-10 10:14 UTC, clyang82 requested changes

2023-10-10 10:14 UTC, clyang82 commented on global_hub/global_hub_existing_components.adoc
> +* `client.crt`: See the _User authentication_ topic in the STRIMZI documentation for the steps to extract the `user.crt` certificate from the secret.
missing `Required,`

2023-10-10 10:14 UTC, clyang82 commented on global_hub/global_hub_existing_components.adoc
> +postgres-ha   LoadBalancer   172.30.227.58   xxxx.us-east-1.elb.amazonaws.com   5432:31442/TCP   128m
we need to correct the format to keep aligned.
<img width="987" alt="image" src="https://github.com/stolostron/rhacm-docs/assets/7711311/a67a1aea-4966-470a-9afa-321fa4f1e166">

2023-10-10 10:14 UTC, clyang82 commented on global_hub/global_hub_existing_components.adoc
> +
can we have official Grafana document link here
[export a dashboard](https://grafana.com/docs/grafana/latest/dashboards/manage-dashboards/#export-a-dashboard)
[import a dashboard](https://grafana.com/docs/grafana/latest/dashboards/manage-dashboards/#import-a-dashboard)

2023-10-10 10:14 UTC, clyang82 commented on global_hub/global_hub_reserved_names.adoc
> +[#global-hub-reserved-names]
we may not expose the reserved names in official document. It is more relative with engineer. I do not think the end user needs to care about it.

2023-10-10 14:54 UTC, dockerymick commented
The issue mentioned in the PR title is the parent issue. This PR addresses changes from: https://issues.redhat.com/browse/ACM-7369

2023-10-16 15:50 UTC, cadawson commented on global_hub/global_hub_reserved_names.adoc
> +[#global-hub-reserved-names]
**Peer reviewer:** Skip this file. It will not be displayed.

2023-10-16 17:51 UTC, dockerymick requested changes

2023-10-16 17:51 UTC, dockerymick commented on global_hub/global_hub_existing_components.adoc
> +into the `PostgresCluster` operand, and then get the EXTERNAL-IP from the `postgres-ha` service. For example:
seems like this is out of place

I also recommend that you add [source,bash] on linw 126

2023-10-16 17:51 UTC, dockerymick commented on global_hub/global_hub_existing_components.adoc
> ++
```suggestion
+
[source,bash]
```

2023-10-16 17:51 UTC, dockerymick commented on global_hub/global_hub_existing_components.adoc
> +* You should have a persistent volume created for your Kafka.
These notes seem like prerequisites

2023-10-16 17:51 UTC, dockerymick commented on global_hub/global_hub_existing_components.adoc
> +* The `ca.crt`, which is based on the `sslmode`. It is an optional value.
```suggestion
If you have your own PostgreSQL relational database, you can use it as the storage for multicluster global hub. You need to create a secret named `multicluster-global-hub-storage` in the `multicluster-global-hub` namespace. The secret must contain the following fields:

* `database_uri`:  It is used to create the database and insert data. Your value must resemble the following format,`postgres://<user>:<password>@<host>:<port>/<database>?sslmode=<mode>`. 
* `database_uri_with_readonlyuser`: It is used to query data by the instance of Grafana that is used by multicluster global hub. It is an optional value. Your value must resemble the following format, `postgres://<user>:<password>@<host>:<port>/<database>?sslmode=<mode>`. 
* The `ca.crt`, which is based on the `sslmode`, is an optional value.
```

2023-10-16 17:51 UTC, dockerymick commented on global_hub/global_hub_existing_components.adoc
> +----
```suggestion
[source,yaml]
----
```

2023-10-16 17:51 UTC, dockerymick commented on global_hub/global_hub_existing_components.adoc
> +**Notes:**
```suggestion
*Notes:*
```

2023-10-17 01:22 UTC, cadawson commented on global_hub/global_hub_existing_components.adoc
> +----
I don't think this is a yaml example.

2023-10-18 14:48 UTC, cadawson commented on global_hub/global_hub_existing_components.adoc
> +* You should have a persistent volume created for your Kafka.
Moved these up.

2023-10-18 14:49 UTC, cadawson commented on global_hub/global_hub_existing_components.adoc
> +into the `PostgresCluster` operand, and then get the EXTERNAL-IP from the `postgres-ha` service. For example:
I don't typically use that, but I can.

2023-10-18 15:23 UTC, dockerymick approved these changes
Some suggestions, thanks for updating this!

2023-10-18 15:23 UTC, dockerymick commented on global_hub/global_hub_existing_components.adoc
> +Multicluster global hub requires the middleware components Kafka and PostgreSQL, as well as the Grafana as the observability platform to provide the policy compliance view. Multicluster global hub pr
```suggestion
Multicluster global hub requires the middleware components Kafka and PostgreSQL, along with Grafana as the observability platform to provide the policy compliance view. Multicluster global hub provides versions of Kafka, PostgreSQL, and Grafana. You can also integrate your own existing Kafka, PostgreSQL, and Grafana.
```

2023-10-18 15:23 UTC, dockerymick commented on global_hub/global_hub_existing_components.adoc
> +If you have your own instance of Kafka, you can use it as the transport for multicluster global hub. Testing was completed on Kafka 3.3. Complete the following steps to integrate an instance of Kafka
Past tense
```suggestion
If you have your own instance of Kafka 3.3, you can use it as the transport for multicluster global hub. Complete the following steps to integrate an instance of Kafka: 
```

2023-10-18 15:23 UTC, dockerymick commented on global_hub/global_hub_existing_components.adoc
> +Create the secret by running the following command:
I recommend this if there is a way or direction for the user to confirm this.  
```suggestion
. Verify that your cluster has the minimum required storage size of 20GB. This amount can store 3 managed hubs with 250 managed clusters and 50 policies per managed hub for 18 months.

. Create the secret by running the following command:
```

2023-10-18 15:23 UTC, dockerymick commented on global_hub/global_hub_existing_components.adoc
> +* The minimum required storage size is 20GB. This amount can store 3 managed hubs with 250 managed clusters and 50 policies per managed hub for 18 months.
```suggestion
```

2023-10-18 15:23 UTC, dockerymick commented on global_hub/global_hub_existing_components.adoc
> +* PostgreSQL 13 was tested.
I recommend that you remove the note section and work the PostgreSQL version earlier in the file.

2023-10-18 15:23 UTC, dockerymick commented on global_hub/global_hub_existing_components.adoc
> +Using an existing Grafana instance might be helpful with multicluster global hub if you have been relying on your own Grafana to get metrics from multiple sources, like Prometheus, from different clu
Seems like a run-on 
```suggestion
Using an existing Grafana instance might be helpful with multicluster global hub if you have been relying on your own Grafana to get metrics from multiple sources, like Prometheus, from different clusters and have to aggregate the metrics yourself. To get multicluster global hub data into your own Grafana, you need to configure the data source and import the dashboards.
```
![Screenshot 2023-10-18 at 11 18 35 AM](https://github.com/stolostron/rhacm-docs/assets/60616885/f243ced1-fcde-461d-8d68-5a587d1de3fe)

2023-10-18 15:23 UTC, dockerymick commented on global_hub/global_hub_existing_components.adoc
> +After you add that content, then you can get the EXTERNAL-IP from the `postgres-ha` service. For example:
Suggesting this update because it is in the example. Will you add a new line between the `oc get svc postgres-ha -n multicluster-global-hub` command and results?
```suggestion
After you add that content, then you can get the `EXTERNAL-IP` from the `postgres-ha` service. For example:
```

2023-10-18 17:16 UTC, cadawson commented on global_hub/global_hub_existing_components.adoc
> +into the `PostgresCluster` operand, and then get the EXTERNAL-IP from the `postgres-ha` service. For example:
Out of place is fixed.

2023-10-18 17:32 UTC, merged