[ACM-7739]: Adding disconnected docs for bare metal and OpenShift Virtualization
open-cluster-management/rhacm-docs pull request #5548
Opened 2023-09-27 19:28 UTC by lahinson

Related Jira: https://issues.redhat.com/browse/ACM-7739

2023-10-04 14:14 UTC, jparrill reviewed
Dropped some comments, mostly answers to your comments/questions on the code

2023-10-04 14:14 UTC, jparrill commented on clusters/hosted_control_planes/dual_stack_dns.adoc
> +//lahinson - sept 2023 - strip comments out of file content
I would maintain this comment: `#log-queries` because it's quite useful for debugging, maybe you can add a note for that.

2023-10-04 14:14 UTC, jparrill commented on clusters/hosted_control_planes/dual_stack_hosted_cluster.adoc
> +//lahinson - sept 2023 - is the latter sentence necessary? I'm not sure if that's something most users need to know.
(IMHO) It's useful from the perspective to have multiple Nodepools based on different architectures x86 vs arm, also it can keep different versions among different Nodepools. I don't know if this is the right place for this, but definitively it's useful :).

2023-10-04 14:14 UTC, jparrill commented on clusters/hosted_control_planes/dual_stack_hosted_cluster.adoc
> +<3> The `autoRepair` field is set to `false` because the node will not be re-created if it is removed.
Regarding this point, we will not allow to set this to enable on Kubevirt and Baremetal for the GA, maybe make sense to mention it when a PR are in place but just to let you know.

2023-10-04 14:14 UTC, jparrill commented on clusters/hosted_control_planes/dual_stack_mgmt_cluster.adoc
> +| dual    | routed |   192.168.125.0/24  | False | hypershiftbm.lab | nat  |
s/dual/ipv4/

2023-10-04 14:14 UTC, jparrill commented on clusters/hosted_control_planes/dual_stack_web_server.adoc
> +//lahinson - sept 2023 - Do we need to mention how the user can access the OpenShift CI Release page?
I don't think it's necessary, you can extract those data fields with the `openshift-install` command and `jq` (lines 14-15). For that you need the the `openshift-install` binary which is in the release image you will use on the HC deployment. 

So, you can extract that binary from the release payload and execute the proper commands.

2023-10-04 14:14 UTC, jparrill commented on clusters/hosted_control_planes/ipv6_mgmt_cluster.adoc
> +| ipv6    | routed |   192.168.125.0/24  | False | hypershiftbm.lab | nat  |
s/ipv6/ipv4/

2023-10-06 18:44 UTC, lahinson commented on clusters/hosted_control_planes/dual_stack_mgmt_cluster.adoc
> +| dual    | routed |   192.168.125.0/24  | False | hypershiftbm.lab | nat  |
@jparrill Just to confirm, do you want me to swap `dual` with `ipv4` on both line 33 and line 34?

2023-10-10 08:34 UTC, tiraboschi commented on clusters/hosted_control_planes/ipv4_mirroring.adoc
> +  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.13
v4.14?

2023-10-10 08:34 UTC, tiraboschi commented on clusters/hosted_control_planes/ipv4_mirroring.adoc
> +    - name: metallb-operator
shouldn't `kubevirt-hyperconverged` be here for OpenShift Virtualization?

2023-10-10 08:34 UTC, tiraboschi commented on clusters/hosted_control_planes/ipv4_mirroring.adoc
> +
I think we should also add a section about how to mirror OLM catalogs and  then configure the hostedClusters to point to the mirror (see: `hypershift.openshift.io/olm-catalogs-is-registry-overrides` annotation on https://hypershift-docs.netlify.app/how-to/disconnected/automatically-initialize-registry-overrides/#control-plane-operator) because in this case the ICSP mechanism is not enough.

2023-10-12 15:23 UTC, lahinson commented on clusters/hosted_control_planes/dual_stack_hosted_cluster.adoc
> +//lahinson - oct 2023 - I think it would be wise for us to replace any text in the following steps and examples that mentions hypershiftbm.lab.
@jparrill See my comment on line 110. We need to go through the examples in these files and remove references to the lab. I'm happy to replace those references with an example, but I'm not sure what to use. Do you have any suggestions?

2023-10-12 15:25 UTC, lahinson commented on clusters/hosted_control_planes/dual_stack_hypervisor.adoc
> +//lahinson - sept 2023 - the upstream docs refer to this list as "bare metal requisites" even though the intro to the hypervisor section states that this section is for virtual machine environments o
@jparrill Please see my comment on line 11 and let me know what you think. Thanks!

2023-10-12 15:26 UTC, lahinson commented on clusters/hosted_control_planes/dual_stack_web_server.adoc
> +//lahinson -sept 2023 - Should the user run this script exactly as it is shown, or do they need to change anything? Also, do they need to run the script in a particular tool, or do they just run it i
@jparrill Please see my question on line 8. Thanks!

2023-10-12 15:29 UTC, lahinson commented on clusters/hosted_control_planes/ipv4_mirroring.adoc
> +  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.13
@jparrill Can you confirm that this should be 4.14?

2023-10-12 15:29 UTC, lahinson commented on clusters/hosted_control_planes/ipv4_mirroring.adoc
> +    - name: metallb-operator
@jparrill Please see @tiraboschi's question and let me know what you think.

2023-10-12 15:30 UTC, lahinson commented on clusters/hosted_control_planes/ipv4_mirroring.adoc
> +
I can plan to add that section.

2023-10-12 16:14 UTC, lahinson commented on clusters/hosted_control_planes/ipv4_mirroring.adoc
> +
@tiraboschi I added a section about OLM mirroring. Please see lines 126 - 145 and let me know if any changes are needed. Also, please let me know if I should add this new section to the dual_stack_mirroring.adoc and ipv6_mirroring.adoc files. Thanks@

2023-10-12 19:07 UTC, lahinson commented
@rokej I moved the content related to https://issues.redhat.com/browse/ACM-3981 into this PR, so that it will be published as part of the new section about disconnected. Please see [monitor_user_workload.adoc](https://github.com/stolostron/rhacm-docs/pull/5548/files#diff-da428b21ff4e52923a1039b28e40cb4c13903778b80bcf23fc5e317958975b28) to review the changes related to ACM-3981. Thank you!

2023-10-13 09:10 UTC, jparrill commented on clusters/hosted_control_planes/ipv4_mirroring.adoc
> +  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.13
yes, sorry, it should be 4.14

2023-10-13 09:10 UTC, jparrill commented on clusters/hosted_control_planes/dual_stack_mgmt_cluster.adoc
> +| dual    | routed |   192.168.125.0/24  | False | hypershiftbm.lab | nat  |
yes :)

2023-10-13 09:15 UTC, jparrill commented on clusters/hosted_control_planes/ipv4_mirroring.adoc
> +    - name: metallb-operator
Hello @tiraboschi, in the bare metal provider, this is not necessary, and furthermore, this is just a sample. Some of the operators or images from that file are not necessary at all, so don't take that literally. You can add it if you want.

2023-10-13 09:17 UTC, jparrill commented on clusters/hosted_control_planes/dual_stack_hosted_cluster.adoc
> +//lahinson - oct 2023 - I think it would be wise for us to replace any text in the following steps and examples that mentions hypershiftbm.lab.
yeah, sgtm.

2023-10-13 09:46 UTC, jparrill commented on clusters/hosted_control_planes/dual_stack_hypervisor.adoc
> +//lahinson - sept 2023 - the upstream docs refer to this list as "bare metal requisites" even though the intro to the hypervisor section states that this section is for virtual machine environments o
nice catch, you're right. Maybe you can put that in the index for each network topology. In the Upstream case I would put that in `Self-manage Labs > MCE and Agent > Dual Stack > index.md` 
![image](https://github.com/stolostron/rhacm-docs/assets/1569950/6e5376c6-ec19-4083-8a0f-1de4597293dd)

I'm not fully sure where do you need to put that in your side, maybe I can help you. Let me know :)

2023-10-13 10:01 UTC, jparrill commented on clusters/hosted_control_planes/dual_stack_web_server.adoc
> +//lahinson -sept 2023 - Should the user run this script exactly as it is shown, or do they need to change anything? Also, do they need to run the script in a particular tool, or do they just run it i
Humm I don't think they have the same folder structure as I had in my env, so I based the location in this tree https://github.com/jparrill/hypershift-disconnected/tree/main/assets/ipv6.

The important part is to have located the `openshift-install` binary which I use to extract the artefacts values as ${ROOTFS_IMG_URL} and ${LIVE_ISO_URL}. 

you can redirect them to https://access.redhat.com/solutions/5380841 which explains how to extract the `openshift-install` binary from the desired OCP release.

so assuming that the customers have downloaded the binary in the same folder as they are placed:

```
ROOTFS_IMG_URL="$(./openshift-install coreos print-stream-json | jq -r '.architectures.x86_64.artifacts.metal.formats.pxe.rootfs.location')"
LIVE_ISO_URL="$(./openshift-install coreos print-stream-json | jq -r '.architectures.x86_64.artifacts.metal.formats.iso.disk.location')"
```

2023-10-13 18:03 UTC, lahinson commented on clusters/hosted_control_planes/ipv4_mirroring.adoc
> +  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.13
updated

2023-10-13 18:04 UTC, lahinson commented on clusters/hosted_control_planes/ipv4_mirroring.adoc
> +    - name: metallb-operator
I can add `kubevirt-hyperconverged` here as I make other updates.

2023-10-13 18:50 UTC, lahinson commented on clusters/hosted_control_planes/dual_stack_mgmt_cluster.adoc
> +| dual    | routed |   192.168.125.0/24  | False | hypershiftbm.lab | nat  |
fixed

2023-10-13 18:51 UTC, lahinson commented on clusters/hosted_control_planes/ipv6_mgmt_cluster.adoc
> +| ipv6    | routed |   192.168.125.0/24  | False | hypershiftbm.lab | nat  |
fixed

2023-10-13 18:53 UTC, lahinson commented on clusters/hosted_control_planes/dual_stack_hypervisor.adoc
> +//lahinson - sept 2023 - the upstream docs refer to this list as "bare metal requisites" even though the intro to the hypervisor section states that this section is for virtual machine environments o
I moved the prereqs out of the Hypervisor file for each network and created a "Prerequisites for bare metal" file that will go at the top of each network's section. Thank you for confirming that the prereqs didn't belong in the Hypervisor file!

2023-10-14 00:51 UTC, lahinson commented on clusters/hosted_control_planes/dual_stack_hosted_cluster.adoc
> +//lahinson - oct 2023 - I think it would be wise for us to replace any text in the following steps and examples that mentions hypershiftbm.lab.
@jparrill Is `hypershiftibm.lab` the name of the DNS base domain? If so, would it make sense to replace instances of `hypershiftibm.lab` with something like `dns-base-domain-name`?

2023-10-20 15:05 UTC, jparrill commented on clusters/hosted_control_planes/dual_stack_hosted_cluster.adoc
> +//lahinson - oct 2023 - I think it would be wise for us to replace any text in the following steps and examples that mentions hypershiftbm.lab.
Yep, it is and yep that name makes sense to me.

2023-10-20 15:06 UTC, tiraboschi requested changes

2023-10-20 15:06 UTC, tiraboschi commented on clusters/hosted_control_planes/ipv4_mirroring.adoc
> +
lgtm

2023-10-20 15:06 UTC, tiraboschi commented on clusters/hosted_control_planes/ipv6_mirroring.adoc
> +  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.13
I still see `v4.13` here while I'd expect `v4.14`

2023-10-20 15:06 UTC, tiraboschi commented on clusters/hosted_control_planes/ipv4_mirroring.adoc
> +    - name: metallb-operator
OK, but where are we going to document the hypershift provider?
Are  we planning to add another section?

2023-10-20 15:07 UTC, lahinson commented on clusters/hosted_control_planes/ipv6_mirroring.adoc
> +  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.13
Good catch. I'll update that. Thanks!

2023-10-20 15:12 UTC, tiraboschi commented on clusters/hosted_control_planes/ipv4_mirroring.adoc
> +    - name: metallb-operator
In the title of the of the PR we have `... and OpenShift Virtualization`

2023-10-20 15:21 UTC, lahinson commented on clusters/hosted_control_planes/ipv6_mirroring.adoc
> +  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.13
Fixed

2023-10-20 16:12 UTC, jparrill commented on clusters/hosted_control_planes/ipv4_mirroring.adoc
> +    - name: metallb-operator
Hey @tiraboschi I don't know how different is the Kubevirt disconnected vs Baremetal. My take here is:

- If the processes are mostly different, I would add a section for each provider.
- If the processes are similar, I would add a disclaimer to remark that this procedure works for both providers.

WDYT?

2023-10-20 16:50 UTC, tiraboschi commented on clusters/hosted_control_planes/ipv4_mirroring.adoc
> +    - name: metallb-operator
We already have have a set of pre-requisites here:
https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.8/html/clusters/cluster_mce_overview#create-hosted-clusters-prereqs-kubevirt
The crucial one is:
> The OpenShift Container Platform managed cluster must have OpenShift Virtualization installed on it. For more information, see [Installing OpenShift Virtualization using the web console](https://docs.openshift.com/container-platform/4.13/virt/install/installing-virt-web.html).

Maybe simply a note for that here under the
`[#ipv4-mirroring-additional-resources]
== Additional resources`
 section to remember to mirror also `kubevirt-hyperconverged` for the management cluster if you intend to use Openshift virtualization?
 
Then shouldn't we explicitly ask the cluster admin to mirror also the CAPI image for Kubevirt and explicitly configure the `IMAGE_KUBEVIRT_CAPI_PROVIDER` env variable in the hypershift-operator to directly look for it on the local registry?

2023-10-20 19:50 UTC, lahinson commented on clusters/hosted_control_planes/configure_hosted_disconnected.adoc
> +// ADD DIAGRAM HERE. For a draft of the diagram, see https://deploy-preview-3008--hypershift-docs.netlify.app/reference/architecture/mce-and-agent/
FYI - This section won't make sense until we have a diagram ready. It looks like the designer has a Jira in progress to work on it and have it ready by the ACM/MCE doc freeze in November.

2023-10-20 19:57 UTC, lahinson commented on clusters/hosted_control_planes/dual_stack_mgmt_cluster.adoc
> +- quay.io/mavazque/trbsht:latest
@jparrill On lines 87 and 88, your user name, `jparrill`, and `mavazque` are shown. Would it be okay if I replaced those names with `user-name`?

2023-10-20 20:40 UTC, lahinson commented on clusters/hosted_control_planes/dual_stack_web_server.adoc
> +//lahinson -sept 2023 - Should the user run this script exactly as it is shown, or do they need to change anything? Also, do they need to run the script in a particular tool, or do they just run it i
@jparrill Thanks for the clarification. I updated `clusters/hosted_control_planes/dual_stack_web_server.adoc`. When you can, PTAL and let me know what you think.

2023-10-20 21:13 UTC, lahinson commented on clusters/hosted_control_planes/ipv4_mirroring.adoc
> +    - name: metallb-operator
Hi @tiraboschi - Just to clarify, should I point to https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.8/html/clusters/cluster_mce_overview#create-hosted-clusters-prereqs-kubevirt as a prerequisite for this mirroring task? If so, do those prerequisites apply only to this particular task, or should I create a separate "Prerequisites to configure hosted control planes in virtual environments" in the same way that I created prerequisite sections for bare metal (for an example, see https://github.com/stolostron/rhacm-docs/pull/5548/files#diff-2efa5000572c8c6d91f302d547d2446d242d6b5ae3357a95e507982f4d389662).

2023-10-23 14:21 UTC, tiraboschi commented on clusters/hosted_control_planes/ipv4_mirroring.adoc
> +    - name: metallb-operator
hi, no it's the opposite: in order to use the Kubevirt provider you have to accomplish all the prerequisites on https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.8/html/clusters/cluster_mce_overview#create-hosted-clusters-prereqs-kubevirt 
including

`The OpenShift Container Platform managed cluster must have OpenShift Virtualization installed on it.`

But in order to deploy it on a disconnected environment you have to mirror it first.

2023-10-23 14:53 UTC, lahinson commented on clusters/hosted_control_planes/ipv4_mirroring.adoc
> +    - name: metallb-operator
@tiraboschi Thanks for the clarification! In the `ipv4_mirroring.adoc` file, I added a reference to the KubeVirt prereqs. When you can, PTAL and let me know if that's what you're looking for. If so, I'll add a similar reference to the ipv6 and dual stack mirroring files.

2023-10-24 14:10 UTC, jparrill commented on clusters/hosted_control_planes/dual_stack_mgmt_cluster.adoc
> +- quay.io/mavazque/trbsht:latest
Yes, makes sense

2023-10-24 14:10 UTC, tiraboschi commented on clusters/hosted_control_planes/ipv4_mirroring.adoc
> +    - name: metallb-operator
thanks, it looks consistent to me now

2023-10-24 15:05 UTC, jparrill commented on clusters/hosted_control_planes/dual_stack_web_server.adoc
> +//lahinson -sept 2023 - Should the user run this script exactly as it is shown, or do they need to change anything? Also, do they need to run the script in a particular tool, or do they just run it i
Looks good :)

2023-10-24 17:13 UTC, lahinson commented on clusters/hosted_control_planes/dual_stack_dns.adoc
@jparrill I updated this file along with `ipv4_dns.adoc` and `ipv6_dns.adoc` to point to the existing documentation. PTAL and let me know if this looks ok. I've also added a comment to `hosted_bare_metal_dns.adoc`, where I've added some details for IPv6 and dual stack.

2023-10-24 17:13 UTC, lahinson commented on clusters/hosted_control_planes/hosted_bare_metal_dns.adoc
@jparrill PTAL at my updates to the existing DNS docs in this file and let me know if I need to add anything else. Thanks!

2023-10-24 17:28 UTC, jparrill commented on clusters/hosted_control_planes/hosted_bare_metal_dns.adoc
LGTM :)

2023-10-24 17:28 UTC, jparrill commented on clusters/hosted_control_planes/dual_stack_dns.adoc
LGTM

2023-10-24 17:28 UTC, jparrill commented
/lgtm

2023-10-24 17:33 UTC, lahinson reviewed
@rokej I made a few updates based on our chat today. PTAL when you can. Thank you!

2023-10-24 17:33 UTC, lahinson commented on clusters/hosted_control_planes/configure_hosted_disconnected.adoc
> +== Configuring hosted control planes in a disconnected environment
@rokej Based on our chat today, I updated lines 41 - 49. PTAL when you can. Thanks!

2023-10-24 17:33 UTC, lahinson commented on clusters/hosted_control_planes/hosted_intro.adoc
> +* xref:../hosted_control_planes/configure_hosted_disconnected.adoc#configure-hosted-disconnected[Configuring hosted control planes in a disconnected environment]
@rokej Added link in the hosted intro to the new disconnected docs section.

2023-10-24 17:33 UTC, lahinson commented on clusters/main.adoc
> +include::hosted_control_planes/monitor_user_workload_disconnected.adoc[leveloffset=+4]
@rokej In the ToC, the common monitoring topic for disconnected will be shown just after the first disconnected topic.

2023-10-24 17:40 UTC, rokej approved these changes
/lgtm

2023-10-27 02:06 UTC, dockerymick approved these changes
WHEW! Thanks Laura for your hard work and diligence! This was a big one and I know more improvements will come. I left a lot of suggestions and some questions. Approving to get the work in

2023-10-27 02:06 UTC, dockerymick commented on clusters/hosted_control_planes/configure_hosted_bm.adoc
> +- To provision hosted control planes on bare metal, you can use the Agent platform. The Agent platform uses the central infrastructure management service to add worker nodes to a hosted cluster. For
This link is correct, remember to also update the link reference on line 47

2023-10-27 02:06 UTC, dockerymick commented on clusters/hosted_control_planes/configure_hosted_disconnected.adoc
> +In the context of hosted control planes, a _disconnected_ environment is an {ocp-short} deployment that is not connected to the internet and that uses hosted control planes as a base.
I recommend that you remove the italics for disconnected. is there a reason why you want to put emphasis on the word? Based on the style guide, the italics should be removed: https://www.ibm.com/docs/en/ibm-style?topic=format-highlighting

2023-10-27 02:06 UTC, dockerymick commented on clusters/hosted_control_planes/configure_hosted_disconnected.adoc
> +// ADD DIAGRAM HERE. For a draft of the diagram, see https://deploy-preview-3008--hypershift-docs.netlify.app/reference/architecture/mce-and-agent/
@lahinson thanks Laura for the background. Is there also a doc issue for the diagram update? Or can you share the link from the Design Jira board?

2023-10-27 02:06 UTC, dockerymick commented on clusters/hosted_control_planes/configure_hosted_disconnected_dual_stack.adoc
> +To configure hosted control planes on a dual stack network, complete the following steps:
This is introduced as steps but currently listed as bullet points. Instead of a asterisk, use a period. I also want to keep in mind how many times the reader might be redirected

2023-10-27 02:06 UTC, dockerymick commented on clusters/hosted_control_planes/configure_hosted_disconnected_ipv4.adoc
> +To configure hosted control planes on an IPv4 network, complete the following steps:
same suggestion as before. The statement says following steps, but is displayed as a list

2023-10-27 02:06 UTC, dockerymick commented on clusters/hosted_control_planes/configure_hosted_disconnected_ipv6.adoc
> +To configure hosted control planes on an IPv6 network, complete the following steps:
Same suggestion. The steps are displayed as a list

2023-10-27 02:06 UTC, dockerymick commented on clusters/hosted_control_planes/dual_stack_bare_metal_prereqs.adoc
> +
This is the first time that I have seen Prerequisites as it's own file. We typically list the Prerequisites as a subsection where it is needed. Can you explain why a file is needed for this?

2023-10-27 02:06 UTC, dockerymick commented on clusters/hosted_control_planes/dual_stack_bare_metal_prereqs.adoc
> +Next, xref:../hosted_control_planes/dual_stack_dns.adoc#dual-stack-dns[configure the DNS] for a dual stack network.
Sometimes there are issues with using double asterisks. This will help with alignment:
 
```suggestion
* CPU: The number of CPUs provided determines how many hosted clusters can run concurrently. In general, use 16 CPUs for each node for 3 nodes. For minimal development, you can use 12 CPUs for each node for 3 nodes.
* Memory: The amount of RAM affects how many hosted clusters can be hosted. Use 48 GB of RAM for each node. For minimal development, 18 GB of RAM might be sufficient.
* Storage: Use SSD storage for {mce-short}. 
- Management cluster: 250 GB.
- Registry: The storage needed depends on the number of releases, operators, and images that are hosted. An acceptable number might be 500 GB, preferably separated from the disk that hosts the hosted cluster.
- Web server: The storage needed depends on the number of ISOs and images that are hosted. An acceptable number might be 500 GB.
* Production: For a production environment, separate the management cluster, the registry, and the web server on different disks. This example illustrates a possible configuration for production:
- Registry: 2 TB
- Management cluster: 500 GB
- Web server: 2 TB

Next, xref:../hosted_control_planes/dual_stack_dns.adoc#dual-stack-dns[configure the DNS] for a dual stack network.
```

2023-10-27 02:06 UTC, dockerymick commented on clusters/hosted_control_planes/dual_stack_bare_metal_prereqs.adoc
> +Next, xref:../hosted_control_planes/dual_stack_dns.adoc#dual-stack-dns[configure the DNS] for a dual stack network.
Why is "Next, xref:../hosted_control_planes/dual_stack_dns.adoc#dual-stack-dns[configure the DNS] for a dual stack network." not listed in the steps?

2023-10-27 02:06 UTC, dockerymick commented on clusters/hosted_control_planes/dual_stack_deploy_registry.adoc
> +For development environments, deploy a small, self-hosted registry by using a Podman container. For production environments, use a more reliable solution, such as Red Hat Quay, Nexus, or Artifactory.
I would remove "more reliable". 
```suggestion
For development environments, deploy a small, self-hosted registry by using a Podman container. For production environments, deploy an enterprise-hosted registry, such as Red Hat Quay, Nexus, or Artifactory.
```

2023-10-27 02:06 UTC, dockerymick commented on clusters/hosted_control_planes/dual_stack_deploy_registry.adoc
> +----
```suggestion
[source,bash]
----
```

2023-10-27 02:06 UTC, dockerymick commented on clusters/hosted_control_planes/dual_stack_deploy_registry.adoc
> +EOF
"EOF" should be removed. Is there a way to make this YAML more clean? We usually instruct users to create a YAML file and then apply it.

2023-10-27 02:06 UTC, dockerymick commented on clusters/hosted_control_planes/dual_stack_hosted_cluster.adoc
> +A _hosted cluster_ is an {ocp-short} cluster with its control plane and API endpoint hosted on a management cluster. The hosted cluster includes the control plane and its corresponding data plane.
I recommend not italicizing hosted cluster

2023-10-27 02:06 UTC, dockerymick commented on clusters/hosted_control_planes/dual_stack_hosted_cluster.adoc
> +* Network stack: Dual
Is there a reason why these values aren't monospaced?

2023-10-27 02:06 UTC, dockerymick commented on clusters/hosted_control_planes/dual_stack_hosted_cluster.adoc
> +    upgradeType: InPlace <2>
I would change the number reference

autoRepair: false <2>
    upgradeType: InPlace <3>

2023-10-27 02:06 UTC, dockerymick commented on clusters/hosted_control_planes/dual_stack_hosted_cluster.adoc
> +If you are working with virtual machines, you can complete the following steps to create empty worker nodes that the Metal3 Operator will consume. To do so, you use the `kcli` tool.
Be cautious of future tense

2023-10-27 02:06 UTC, dockerymick commented on clusters/hosted_control_planes/dual_stack_hypervisor.adoc
> +. After you create the file, add execution permissions by entering the following command:
is the term "execution" required? We usually don't use execution for translation

2023-10-27 02:06 UTC, dockerymick commented on clusters/hosted_control_planes/dual_stack_hypervisor.adoc
> +** For SELinux, enter the following command:
Remove the extra asterisks throughout the list
```suggestion
* For SELinux, enter the following command:
```

2023-10-27 02:06 UTC, dockerymick commented on clusters/hosted_control_planes/dual_stack_hypervisor.adoc
> ++
Make this update for all commands 
```suggestion
+
[source,bash]
```

2023-10-27 02:06 UTC, dockerymick commented on clusters/hosted_control_planes/dual_stack_hypervisor.adoc
> ++
Update for all commands
```suggestion
+
[source,bash]
```

2023-10-27 02:06 UTC, dockerymick commented on clusters/hosted_control_planes/dual_stack_mce.adoc
> +---
I assume that there are three dashes bc this is a partial YAML

2023-10-27 02:06 UTC, dockerymick commented on clusters/hosted_control_planes/dual_stack_mgmt_cluster.adoc
> +** `-c` specifies the CIDR for the network.
I recommend that you use single asterisk
```suggestion
* `-c` specifies the CIDR for the network.
```

2023-10-27 02:06 UTC, dockerymick commented on clusters/hosted_control_planes/dual_stack_mgmt_cluster.adoc
> +. After the network is created, see the following output:
```suggestion
. After the network is created, the following output is displayed:
```

2023-10-27 02:06 UTC, dockerymick commented on clusters/hosted_control_planes/dual_stack_mirroring.adoc
> +_Image mirroring_ is the process of fetching images from external registries, such as `registry.redhat.com` or `quay.io`, and storing them in your private registry.
Remove italics

2023-10-27 02:06 UTC, dockerymick commented on clusters/hosted_control_planes/dual_stack_tls_certs.adoc
> +** If the namespace contains that config map, enter the following command:
I recommend that you add a plus sign on line 17, only if it is a substep. I would also use one asterisk

2023-10-27 02:06 UTC, dockerymick commented on clusters/hosted_control_planes/dual_stack_web_server.adoc
> ++
Add this update for the commands
```suggestion
+
[source,bash]
```

2023-10-27 02:06 UTC, dockerymick commented on clusters/hosted_control_planes/ipv4_bare_metal_prereqs.adoc
> +*** Web server: 2 TB
```suggestion
- CPU: The number of CPUs provided determines how many hosted clusters can run concurrently. In general, use 16 CPUs for each node for 3 nodes. For minimal development, you can use 12 CPUs for each node for 3 nodes.
- Memory: The amount of RAM affects how many hosted clusters can be hosted. Use 48 GB of RAM for each node. For minimal development, 18 GB of RAM might be sufficient.
- Storage: Use SSD storage for {mce-short}. 
*Management cluster: 250 GB.
* Registry: The storage needed depends on the number of releases, operators, and images that are hosted. An acceptable number might be 500 GB, preferably separated from the disk that hosts the hosted cluster.
* Web server: The storage needed depends on the number of ISOs and images that are hosted. An acceptable number might be 500 GB.
- Production: For a production environment, separate the management cluster, the registry, and the web server on different disks. This example illustrates a possible configuration for production:
* Registry: 2 TB
* Management cluster: 500 GB
* Web server: 2 TB
```

2023-10-27 02:06 UTC, dockerymick commented on clusters/hosted_control_planes/ipv4_deploy_registry.adoc
> +openssl req -newkey rsa:4096 -nodes -sha256 -keyout /opt/registry/certs/domain.key -x509 -days 3650 -out /opt/registry/certs/domain.crt -subj "/C=US/ST=Madrid/L=San Bernardo/O=Karmalabs/OU=Guitar/CN=
Similar comment from before, remove EOF. Will this create a bug for the user if they don't use this exact example?

2023-10-27 02:06 UTC, dockerymick commented on clusters/hosted_control_planes/ipv4_deploy_registry.adoc
> ++
```suggestion
+
[source,bash]
```

2023-10-27 02:06 UTC, dockerymick commented on clusters/main.adoc
> +include::hosted_control_planes/ipv4_bare_metal_prereqs.adoc[leveloffset=+5]
This is my first time seeing us use level 5. We need to verify that the sections appear in the TOC, from the preview docs

2023-10-27 13:36 UTC, lahinson commented on clusters/main.adoc
> +include::hosted_control_planes/ipv4_bare_metal_prereqs.adoc[leveloffset=+5]
@dockerymick I was concerned about that, too. I will be sure to check staging to make sure everything looks ok!

2023-10-27 13:41 UTC, lahinson commented on clusters/hosted_control_planes/configure_hosted_disconnected.adoc
> +In the context of hosted control planes, a _disconnected_ environment is an {ocp-short} deployment that is not connected to the internet and that uses hosted control planes as a base.
@dockerymick Good question. I used italics because of the following guidance from IBM Style, which is in the same topic that you referred to:

![Screenshot 2023-10-27 at 9 39 12 AM](https://github.com/stolostron/rhacm-docs/assets/102675557/64d87b69-a045-4b8f-9215-767265b0945b)

I figured since I was defining was a disconnected environment is, I should italicize the term. I can remove the highlighting if we don't tend to use it in the ACM docs, though! I don't feel strongly about it.

2023-10-27 13:41 UTC, lahinson commented on clusters/hosted_control_planes/configure_hosted_bm.adoc
> +- To provision hosted control planes on bare metal, you can use the Agent platform. The Agent platform uses the central infrastructure management service to add worker nodes to a hosted cluster. For
Good catch!

2023-10-27 13:42 UTC, lahinson commented
I added a link to the Jira for the diagram in the first comment of this PR.

2023-10-27 13:45 UTC, lahinson commented on clusters/hosted_control_planes/configure_hosted_disconnected.adoc
> +// ADD DIAGRAM HERE. For a draft of the diagram, see https://deploy-preview-3008--hypershift-docs.netlify.app/reference/architecture/mce-and-agent/
https://issues.redhat.com/browse/DXD-489

2023-10-27 13:46 UTC, lahinson commented on clusters/hosted_control_planes/configure_hosted_disconnected_dual_stack.adoc
> +To configure hosted control planes on a dual stack network, complete the following steps:
Good catch! Will fix.

2023-10-27 16:03 UTC, dockerymick commented on clusters/hosted_control_planes/configure_hosted_disconnected.adoc
> +In the context of hosted control planes, a _disconnected_ environment is an {ocp-short} deployment that is not connected to the internet and that uses hosted control planes as a base.
LMAO I think it's hilarious that i missed that hahah thanks for the screen capture. Since italics for emphasis isn't used throughout the RHACM doc, I recommend to move forward with removing the italics.

2023-10-27 18:00 UTC, lahinson commented on clusters/hosted_control_planes/dual_stack_bare_metal_prereqs.adoc
> +
Good point. I can move the prereqs to the intro topics for each network (ipv4, ipv6, and dual stack) and then remove the separate files.

2023-10-27 18:16 UTC, lahinson commented on clusters/hosted_control_planes/dual_stack_deploy_registry.adoc
> +EOF
I can ask engineering.

2023-10-27 18:44 UTC, lahinson commented on clusters/hosted_control_planes/dual_stack_hosted_cluster.adoc
> +* Network stack: Dual
Fixed

2023-10-27 18:50 UTC, lahinson commented on clusters/hosted_control_planes/dual_stack_hosted_cluster.adoc
> +If you are working with virtual machines, you can complete the following steps to create empty worker nodes that the Metal3 Operator will consume. To do so, you use the `kcli` tool.
Fixed

2023-10-27 18:57 UTC, lahinson commented on clusters/hosted_control_planes/dual_stack_hypervisor.adoc
> +. After you create the file, add execution permissions by entering the following command:
I wonder if it will be okay if I simply remove "execution". I can check with engineering.

2023-10-30 18:02 UTC, lahinson commented on clusters/hosted_control_planes/dual_stack_hypervisor.adoc
> ++
fixed ✔️

2023-10-30 18:03 UTC, lahinson commented on clusters/hosted_control_planes/dual_stack_mce.adoc
> +---
yes

2023-10-30 18:05 UTC, lahinson commented on clusters/hosted_control_planes/dual_stack_mgmt_cluster.adoc
> +** `-c` specifies the CIDR for the network.
fixed

2023-10-30 18:19 UTC, lahinson commented on clusters/hosted_control_planes/ipv4_bare_metal_prereqs.adoc
> +*** Web server: 2 TB
fixed

2023-10-30 18:20 UTC, lahinson commented on clusters/hosted_control_planes/ipv4_deploy_registry.adoc
> +openssl req -newkey rsa:4096 -nodes -sha256 -keyout /opt/registry/certs/domain.key -x509 -days 3650 -out /opt/registry/certs/domain.crt -subj "/C=US/ST=Madrid/L=San Bernardo/O=Karmalabs/OU=Guitar/CN=
I'll check with engineering. Good catch!

2023-10-30 18:22 UTC, lahinson commented on clusters/hosted_control_planes/dual_stack_mgmt_cluster.adoc
> +. After the network is created, see the following output:
I changed this to "After the network is created, review the following output:". Otherwise, this step would not be written as an imperative.

2023-10-30 18:25 UTC, lahinson commented on clusters/hosted_control_planes/dual_stack_deploy_registry.adoc
> +For development environments, deploy a small, self-hosted registry by using a Podman container. For production environments, use a more reliable solution, such as Red Hat Quay, Nexus, or Artifactory.
Fixed for this file and the ipv4 and ipv6 versions.

2023-10-30 18:26 UTC, lahinson commented on clusters/hosted_control_planes/dual_stack_deploy_registry.adoc
> +----
fixed for dual stack, ipv4, and ipv6 versions of this file

2023-10-30 18:27 UTC, lahinson commented on clusters/hosted_control_planes/dual_stack_hosted_cluster.adoc
> +A _hosted cluster_ is an {ocp-short} cluster with its control plane and API endpoint hosted on a management cluster. The hosted cluster includes the control plane and its corresponding data plane.
fixed for dual stack, ipv4, and ipv6 versions of the file

2023-10-30 18:30 UTC, lahinson commented on clusters/hosted_control_planes/dual_stack_hosted_cluster.adoc
> +    upgradeType: InPlace <2>
Fixed in dual stack, ipv4, and ipv6 versions

2023-10-30 18:33 UTC, lahinson commented on clusters/hosted_control_planes/dual_stack_hypervisor.adoc
> +. After you create the file, add execution permissions by entering the following command:
@jparrill Per our style guidelines, we try to avoid the term "execution" where possible. Would it harm accuracy here if we removed the term "execution" and simply said, "After you create the file, add permissions by entering the following command:"?

2023-10-30 18:34 UTC, lahinson commented on clusters/hosted_control_planes/dual_stack_hypervisor.adoc
> +** For SELinux, enter the following command:
Fixed for dual stack, ipv4, and ipv6 versions

2023-10-31 18:25 UTC, lahinson commented on clusters/hosted_control_planes/dual_stack_deploy_registry.adoc
> +EOF
@jparrill Typically in the official docs, we instruct users to create a YAML file and then apply it. You can see an example here: https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.8/html/clusters/cluster_mce_overview#hosted-control-planes-create-infraenv.

Can you help me clean up this code to better meet the doc requirements?

2023-11-02 14:09 UTC, jparrill commented on clusters/hosted_control_planes/ipv4_deploy_registry.adoc
> +openssl req -newkey rsa:4096 -nodes -sha256 -keyout /opt/registry/certs/domain.key -x509 -days 3650 -out /opt/registry/certs/domain.crt -subj "/C=US/ST=Madrid/L=San Bernardo/O=Karmalabs/OU=Guitar/CN=
The EOF is the shell limiter which the script will look for to be parsed in the execution, this means that if you have set EOF at the beginning of the command you need to put the same in the end and without the spaces.

2023-11-02 18:00 UTC, lahinson commented on clusters/hosted_control_planes/dual_stack_deploy_registry.adoc
> +EOF
@dockerymick As far as I understand it, because the "EOF" syntax is part of a script, I don't know how to rewrite it like I usually would in the docs. Usually, I see it in the context of creating a YAML file with specific contents and then applying the YAML file by running a command. Since the YAML is embedded in the script here, I think it might need to stay that way.

2023-11-02 18:08 UTC, jparrill commented on clusters/hosted_control_planes/dual_stack_hypervisor.adoc
> +. After you create the file, add execution permissions by entering the following command:
yep, makes sense

2023-11-02 19:30 UTC, merged

2023-11-02 21:36 UTC, swopebe commented on clusters/hosted_control_planes/configure_hosted_disconnected.adoc
> +
Can we please remove these comments and instead open an issue if the plan is to put a diagram in the doc. We try not to use comments heavily.

2023-11-02 21:39 UTC, swopebe commented on clusters/hosted_control_planes/dual_stack_deploy_registry.adoc
> +EOF
We don't normally document scripts and that is why we ask them to remove EOF from things like YAML file samples, so Mikela is right.

2023-11-03 00:52 UTC, lahinson commented on clusters/hosted_control_planes/configure_hosted_disconnected.adoc
> +
@swopebe I had hoped that I'd have a diagram from Design by now, which is why I temporarily commented-out the text that should surround it. I can remove this text and copy it to a separate Jira that we can use to track the addition of the diagram when it's ready.

2023-11-03 00:59 UTC, lahinson commented on clusters/hosted_control_planes/dual_stack_deploy_registry.adoc
> +EOF
@swopebe When we meet on Monday, I'd like to better understand why we don't normally document scripts. I'm not sure what to do in this case, as the script is an important part of this procedure. I understand why we want to present YAML in a cleaner, clearer way, but I don't know how to do it in this case. I'd appreciate some help!