https://issues.redhat.com/browse/ACM-7523 Deprecate MSA API 2.9
open-cluster-management/rhacm-docs pull request #5552
Opened 2023-09-28 14:53 UTC by oafischer

2023-09-28 15:28 UTC, swopebe requested changes

2023-09-28 15:28 UTC, swopebe commented on clusters/api/managed_serviceaccount.json.adoc
If we are actually going to replace, essentially remove the former API, that is not a true deprecation. We should not be removing something from the doc that was not even deprecated. We can however deprecate it and put:

v1alpha is not removed, but is deprecated. Best practice: Use v1beta1 instead.

2023-09-28 15:50 UTC, swopebe approved these changes
Made one small change.

2023-10-09 03:23 UTC, zhujian7 commented
LGTM

2023-10-09 08:03 UTC, merged