added iam policy to table
open-cluster-management/rhacm-docs pull request #5572
Opened 2023-10-02 17:29 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-7754

Please see my comments in the PR, as I had some questions as I continue to work on this issue.

2023-10-02 17:30 UTC, jc-berger commented on governance/iam_policy_ctrl.adoc
> +V2.9: Deprecated
I know that the issue requires me to add the deprecation label to the IAM policy doc. 

I've never added a label to a doc in ascii doc before, so I followed these instructions from AsciiDoctor: https://docs.asciidoctor.org/asciidoc/latest/tables/customize-title-label/ 

Please let me know if I did it incorrectly or if there's an example I can look at.

2023-10-02 17:31 UTC, jc-berger commented on governance/iam_policy_ctrl.adoc
> +| Runs on your managed cluster, monitors the roles of the users of the cluster, and notifies you of non-compliant policies.
SMEs, I didn't know if the policy controller were required and what description would be best.

Please review.

2023-10-02 18:58 UTC, dockerymick requested changes
I checked the preview of the file to see if the ASCII Doc label would render. Nothing appeared, so I suggest removing it. We typically do not use ASCII labels
![Screenshot 2023-10-02 at 2 54 37 PM](https://github.com/stolostron/rhacm-docs/assets/60616885/23f1fedb-6f16-4c66-8e47-6b0039e48f4a)

2023-10-02 18:58 UTC, dockerymick commented on governance/iam_policy_ctrl.adoc
> +V2.9: Deprecated
```suggestion
= IAM policy controller (Deprecated)
```

2023-10-02 18:58 UTC, dockerymick commented on governance/iam_policy_ctrl.adoc
> +:version-label: Deprecated
```suggestion
```

2023-10-02 18:58 UTC, dockerymick commented on governance/iam_policy_ctrl.adoc
> +| Runs on your managed cluster, monitors the roles of the users of the cluster, and notifies you of non-compliant policies.
This row isn't required. It seems repetitive to what is explained in the overview, but feel free to improve the explanation is needed.

2023-10-03 02:25 UTC, dockerymick commented on governance/iam_policy_ctrl.adoc
> +| Runs on your managed cluster, monitors the roles of the users of the cluster, and notifies you of non-compliant policies.
Here is the link to the deprecations table: https://github.com/stolostron/rhacm-docs/blob/2.9_stage/release_notes/deprecate_remove.adoc#product-title-short-deprecations

2023-10-03 16:00 UTC, dockerymick commented on governance/iam_policy_ctrl.adoc
> +| Runs on your managed cluster, monitors the roles of the users of the cluster, and notifies you of non-compliant policies.
Here is also an example of adding the entry https://github.com/stolostron/rhacm-docs/pull/5552/files#diff-bddfa6e67ebe79d7e667fa5c1f09c323997d02702dbb350aab05029f5802575aR24-R29

2023-10-03 17:26 UTC, jc-berger commented on governance/iam_policy_ctrl.adoc
> +| Runs on your managed cluster, monitors the roles of the users of the cluster, and notifies you of non-compliant policies.
@dockerymick thanks for the feedback! Are you saying the IAM policy controller is not required. Therefore, should it even be in the table if it's not required and the explanation is redundant? 

Or do you mean, the explanation is redundant, and that's not required?

2023-10-03 18:17 UTC, dockerymick requested changes

2023-10-03 18:17 UTC, dockerymick commented on governance/iam_policy_ctrl.adoc
> += IAM policy controller
```suggestion
= IAM policy controller (Deprecated)
```

2023-10-03 18:17 UTC, dockerymick commented on governance/iam_policy_ctrl.adoc
> +
The entire entry here should be removed. Add a new row to the [Deprecations table](https://github.com/stolostron/rhacm-docs/blob/2.9_stage/release_notes/deprecate_remove.adoc#product-title-short-deprecations) for IAM policy controller
```suggestion
```

2023-10-03 18:18 UTC, dockerymick commented on governance/iam_policy_ctrl.adoc
> +| Runs on your managed cluster, monitors the roles of the users of the cluster, and notifies you of non-compliant policies.
Yes, it's redundant. It is best to revert the changes bc this table doesn't need to be updated

2023-10-04 17:34 UTC, ch-stark approved these changes
lgtm thank you

2023-10-04 19:17 UTC, dockerymick commented on release_notes/deprecate_remove.adoc
> +|
@jc-berger this is the table that I was referring to in my [comment](https://github.com/stolostron/rhacm-docs/pull/5572#discussion_r1344353718)

2023-10-04 19:18 UTC, dockerymick approved these changes
Left a comment for clarification and made an update. the table looks good when I select to view the Deprecation file. Let me know if you still have questions.

2023-10-05 04:27 UTC, dockerymick approved these changes
Left a hidden comment to be addressed. Otherwise, this looks good

2023-10-05 14:34 UTC, dockerymick commented on governance/policy_controllers.adoc
>  * xref:../governance/iam_policy_ctrl.adoc#iam-policy-controller[IAM policy controller]
```suggestion

* xref:../governance/config_policy_ctrl.adoc#kubernetes-configuration-policy-controller[Kubernetes configuration policy controller]
* xref:../governance/cert_policy_ctrl.adoc#certificate-policy-controller[Certificate policy controller]
* xref:../governance/iam_policy_ctrl.adoc#iam-policy-controller[IAM policy controller (Deprecated)]
```

2023-10-05 14:58 UTC, dockerymick commented
I suggest to update the title of the PR to "added iam policy to the deprecations table" @jc-berger

2023-10-05 15:48 UTC, merged