Swope changes ocm
open-cluster-management/rhacm-docs pull request #5573
Opened 2023-10-02 23:52 UTC by swopebe

2023-10-03 15:00 UTC, dockerymick requested changes

2023-10-03 15:00 UTC, dockerymick commented on governance/create_gatekeeper.adoc
> +- See the link:https://github.com/open-cluster-management/policy-collection/blob/main/community/CM-Configuration-Management/policy-gatekeeper-operator.yaml[`policy-gatekeeper-operator.yaml`] sample.
I recommend that we use this link instead: https://github.com/open-cluster-management-io/policy-collection/blob/main/stable/CM-Configuration-Management/policy-gatekeeper-operator-downstream.yaml

2023-10-03 15:00 UTC, dockerymick commented on governance/create_gatekeeper.adoc
> +- See the link:https://github.com/open-cluster-management/policy-collection/blob/main/community/CM-Configuration-Management/policy-gatekeeper-operator.yaml[`policy-gatekeeper-operator.yaml`] sample.
```suggestion
- See the link:https://github.com/open-cluster-management-io/policy-collection/blob/main/stable/CM-Configuration-Management/policy-gatekeeper-operator-downstream.yaml[`policy-gatekeeper-operator-downstream.yaml`] sample.
```

2023-10-03 15:00 UTC, dockerymick commented on governance/grc_intro.adoc
> +* *Open source community:* Supports community contributions with a foundation of the {product-title-short} policy framework. Policy controllers and third-party policies are also a part of the link:ht
```suggestion
* *Open source community:* Supports community contributions with a foundation of the {product-title-short} policy framework. Policy controllers and third-party policies are also a part of the link:https://github.com/open-cluster-management/policy-collection[`open-cluster-management/policy-collection` repository]. You can contribute and deploy policies using GitOps. For more information, see _Deploying policies by using GitOps_ in the _Manage security policies_ section. Learn how to integrate third-party policies with {product-title}.
```

2023-10-03 15:00 UTC, dockerymick commented on governance/kyverno_add_network_policy.adoc
> +The Kyverno add network policy configures a new `NetworkPolicy` resource called `default-deny` which denies all traffic when you create a new namespace. You must install Kyverno controller to use the
I did only see this in the community folder. @swopebe I remember that we said we wanted to point to stable policy examples. @mprahl is there another policy sample that we can provide?

2023-10-03 15:00 UTC, dockerymick commented on governance/kyverno_add_quota_policy.adoc
> +The Kyverno add quota policy configures new `ResourceQuota` and `LimitRange` resources when you create a new namespace. You must install Kyverno controller to use the Kyverno policy. See link:https:/
same comment

2023-10-03 15:00 UTC, dockerymick commented on governance/kyverno_sync_secrets_policy.adoc
> +The Kyverno sync secrets policy copies a secret called `regcred` which exists in the `default` namespace to new namespaces you create and updates the secret when changes are detected. You must instal
same comment about the community link

2023-10-09 22:01 UTC, swopebe commented on governance/kyverno_add_network_policy.adoc
> +The Kyverno add network policy configures a new `NetworkPolicy` resource called `default-deny` which denies all traffic when you create a new namespace. You must install Kyverno controller to use the
Agreed, @mprahl we either need to talk to PM to see if this should be part of the doc/product or remove this? @berenss do you have input on _install Kyverno controller to use the Kyverno policy_ (add to the official doc or remove link from official doc, as the doc should only be what goes through the feature>code>qe process.)

2023-10-09 22:01 UTC, swopebe commented on governance/kyverno_add_network_policy.adoc
> +The Kyverno add network policy configures a new `NetworkPolicy` resource called `default-deny` which denies all traffic when you create a new namespace. You must install Kyverno controller to use the
This link is in other areas of the doc.

2023-10-10 13:38 UTC, mprahl commented on governance/kyverno_add_network_policy.adoc
> +The Kyverno add network policy configures a new `NetworkPolicy` resource called `default-deny` which denies all traffic when you create a new namespace. You must install Kyverno controller to use the
Yes, that policy is broken and is a community policy that shouldn't be documented.

2023-10-10 14:18 UTC, berenss commented on governance/kyverno_add_network_policy.adoc
> +The Kyverno add network policy configures a new `NetworkPolicy` resource called `default-deny` which denies all traffic when you create a new namespace. You must install Kyverno controller to use the
Hi Brandi thank you - Looks like @ch-stark would be better aligned to comment here (and perhaps this is already resolved)

2023-10-11 13:20 UTC, dockerymick approved these changes
Links look good, thanks for this update!

2023-10-11 15:27 UTC, ch-stark commented
@dockerymick yesterday we decided in the Call to remove Kyverno-Policies from documentation.  Can we handle this here?  I can open a new Bug if needed

2023-10-11 15:36 UTC, swopebe commented
@ch-stark as part of the Done criteria for all the dev teams, they are required to review deprecations and removals. They do not open bugs, but they open tasks with all the references that need to be removed.

In this case, if it was added incorrectly and never used by the customer, we do not need to deprecate or add to the table, we just need to get it out of the doc because it causes problems.

Yes to a task from the dev team, which @dockerymick can bring up in their scrum.

2023-10-11 15:45 UTC, dockerymick commented
@swopebe thanks for confirming. Here is the related issue https://issues.redhat.com/browse/ACM-7893
I will go ahead and remove the Kyverno policies or we can reassign if necessary. I think it is still worth it to update the removals table to describe why it was removed

2023-10-11 16:12 UTC, swopebe commented
Well, if it was a mistake, I would rather we just remove it and not put it in the table, as that table is for active components that the customer is using. 

@dockerymick let's see if anyone has shown it to a RHACM subscriber or if it has intentionally been used, or if it just should not have been added. 

@ch-stark was this in production in the product or only mentioned in the doc?

2023-10-11 16:16 UTC, swopebe commented
I am gonna merge this bc I have to move on, we can cont the discussion in the new issue.

2023-10-11 16:16 UTC, dockerymick commented
@swopebe @ch-stark confirmed. Here is his response: 

"Mikela Jackson we never Supported Kyverno really, we just Support the PolicyGenerator part

We thought we might support it one time, this is why we created the Policies and wanted to make it official but it makes not so much sense as we do not provide a supported way to install Kyverno

just removing the 3 Policies is fine"

2023-10-11 16:21 UTC, merged