modified notes
open-cluster-management/rhacm-docs pull request #5576
Opened 2023-10-03 19:43 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-7807

2023-10-03 19:43 UTC, jc-berger commented on business_continuity/backup_restore/backup_install.adoc
> +- Even if you have not enabled the cluster backup and restore operator, the MultiClusterHub resource installs on the hub for the OADP Operator and Velero CRD resources. The MultiClusterHub reconciles
Am I correct that in this instance we should use past tense since the note is detailing what has happened? 

Happy to change verb tense if I am incorrect. Thanks!

2023-10-04 15:52 UTC, swopebe requested changes
couple small things.

2023-10-04 15:52 UTC, swopebe commented on business_continuity/backup_restore/backup_install.adoc
> +- Even if you have not enabled the cluster backup and restore operator, the MultiClusterHub resource installs on the hub for the OADP Operator and Velero CRD resources. The MultiClusterHub reconciles
I think you can switch to "If you did not enable" to remove the participle phrase, which is not really needed here and not as concise. (Sometimes participles are needed, often not; the best thing to do is tighten the verb tense without it when and where you can.)

MultiClusterHub as a resource we are writing within code like `MultiClusterHub`, if I am not mistaking.

Not sure we need: For this reason,

hub cluster (together always)

CRD resources? Is that Custom Resource Definition resources?

_that is_ used by the OADP....

2023-10-04 16:18 UTC, swopebe commented on business_continuity/backup_restore/backup_install.adoc
> +- The backup component works with OADP installed in the component namespace.
that is installed?

2023-10-04 16:19 UTC, jc-berger commented on business_continuity/backup_restore/backup_install.adoc
> +- Even if you have not enabled the cluster backup and restore operator, the MultiClusterHub resource installs on the hub for the OADP Operator and Velero CRD resources. The MultiClusterHub reconciles
awesome, thanks, see my changes!

2023-10-04 17:40 UTC, jc-berger commented on business_continuity/backup_restore/backup_install.adoc
> +- If you did not enable the cluster backup and restore operator, the `MultiClusterHub` resource installs on the hub cluster for the OADP Operator and Velero Custom Resource Definition (CRD) resources
SMEs 

Should it be `on the clusterhub` 

or, `on the hub on the cluster`?

2023-10-04 19:20 UTC, birsanv requested changes

2023-10-04 19:20 UTC, birsanv commented on business_continuity/backup_restore/backup_install.adoc
> +- If you did not enable the cluster backup and restore operator, the `MultiClusterHub` resource installs on the hub cluster for the OADP Operator and Velero Custom Resource Definition (CRD) resources
Here: >>If you did not enable the cluster backup and restore operator, the `MultiClusterHub` resource installs on the hub cluster for the OADP Operator and Velero Custom Resource Definition (CRD) resources.<< 

 I want to convey that **even if you don't have backup enabled on the MCH resource** , the OADP Operator and Velero Custom Resource Definition (CRD) resources are being installed on the hub cluster.
This is lost with the current wording :) I read that the CRDs are installed if you don't enable the backup

Can we reword it ?

2023-10-04 19:20 UTC, birsanv commented on business_continuity/backup_restore/backup_install.adoc
> +- If you did not enable the cluster backup and restore operator, the `MultiClusterHub` resource installs on the hub cluster for the OADP Operator and Velero Custom Resource Definition (CRD) resources
For this sentence : >> The `MultiClusterHub` reconciles the OADP and Velero CRD resources with the version that is used by the OADP Operator that was installed when you enabled the cluster backup and restore operator. You cannot install another version of OADP or Velero on the clusterhub, unless you use the same CRD resources that is used by the OADP Operator that was installed when you enabled the backup and restore operator. <<

1.  ( avoid _that_ twice .. )
The `MultiClusterHub` reconciles the OADP and Velero CRD resources with the version that is used by the OADP Operator **which is** installed when you enabled the cluster backup and restore operator. You cannot install another version of OADP or Velero on the clusterhub, unless you use the same CRD resources that is used by the OADP Operator that was installed when you enabled the backup and restore operator.

2. Should be hub cluster, not cluster hub (.. on the clusterhub, unless ..)

3. Change: 
..unless you use the same CRD resources that is used by the OADP Operator that was installed when you enabled the backup and restore operator.
 with : 
 ..unless **your version** uses the same CRD **definitions** as the OADP Operator installed when you enabled the backup and restore operator.
 
4. Is it possible to use the _As a result_  as I put in the jirra ?( I want to convey that because MCH reconciles the CRDs and replaces them with the version installed by the backup operator, as a result .. you can't install another OADP Operator unless it uses the same CRDs as the ones controlled by the MCH ). If it's not following the writing rule is fine but we loose this subtle connection between the MCH CRD and the fact that you can't install any version you like

Something like : The `MultiClusterHub` reconciles the OADP and Velero CRD resources with the version that is used by the OADP Operator **which is** installed when you enabled the cluster backup and restore operator. **As a result**, you cannot install another version of OADP...

2023-10-04 19:20 UTC, birsanv commented on business_continuity/backup_restore/backup_install.adoc
> +- The backup component works with OADP installed in the component namespace.
I would also suggest 

The backup component works with OADP Operator that is installed in the component namespace.

2023-10-06 14:54 UTC, birsanv requested changes

2023-10-06 14:54 UTC, birsanv commented on business_continuity/backup_restore/backup_install.adoc
> +- If you did not enable the cluster backup and restore operator on the MCH resource, the OADP Operator and Velero Custom Resource Definition (CRD) still installs on the hub cluster. The `MultiCluster
The message is the right one, just a few small comments : 

1. MCH should say MultiClusterHub - I don't think we shortname this in the docs
2. Change : the OADP Operator and Velero Custom Resource Definition (CRD) still installs on the hub cluster.
with : the OADP Operator and Velero Custom Resource Definition (CRD) are still installed on the hub cluster.

2023-10-06 15:05 UTC, birsanv approved these changes
looks good, thanks!

2023-10-06 17:09 UTC, dockerymick approved these changes
Left a suggestion. Otherwise, this looks good

2023-10-06 17:09 UTC, dockerymick commented on business_continuity/backup_restore/backup_install.adoc
> +- If you did not enable the cluster backup and restore operator on the `MultiClusterHub` resource, the OADP Operator and Velero Custom Resource Definition (CRD) are still installed on the hub cluster
```suggestion
- If you did not enable the cluster backup and restore operator on the `MultiClusterHub` resource, the OADP Operator and Velero custom resource definition are still installed on the hub cluster. The `MultiClusterHub` resource reconciles the OADP and Velero custom resource definitions with the version that is used by the OADP Operator, which is installed when you enabled the cluster backup and restore operator. As a result, you cannot install another version of OADP or Velero on the hub cluster, unless your version uses the same custom resource definitions as the OADP Operator that is installed when you enabled the backup and restore operator.
```

2023-10-09 17:52 UTC, dockerymick approved these changes

2023-10-09 18:28 UTC, merged