https://issues.redhat.com/browse/ACM-7680 Add backup collision topic
open-cluster-management/rhacm-docs pull request #5586
Opened 2023-10-05 15:23 UTC by oafischer

Also for 2.8 and 2.7.

2023-10-05 15:41 UTC, birsanv commented on business_continuity/backup_restore/backup_schedule.adoc
> +As a result, the latest backups are generated by a hub cluster that is no longer set as the primary hub cluster. This hub cluster still produces backups because the `BackupSchedule.cluster.open-clust
This is incorrect
This hub cluster still produces backups because the `BackupSchedule.cluster.open-cluster-management.io` resource is still enabled, but this hub cluster no longer writes backup data since it is not a primary hub cluster anymore.

I think you mean
This hub cluster still produces backups because the `BackupSchedule.cluster.open-cluster-management.io` resource is still enabled, but this hub cluster **should** no longer writes backup data since it is not a primary hub cluster anymore.

2023-10-05 15:45 UTC, oafischer commented on business_continuity/backup_restore/backup_schedule.adoc
> +As a result, the latest backups are generated by a hub cluster that is no longer set as the primary hub cluster. This hub cluster still produces backups because the `BackupSchedule.cluster.open-clust
Ah, I think in this case should means "is not supposed to" as in we don't want it to write data, as opposed to the other meaning of should? (i.e. I should not have any meetings later today)

Is that correct?

2023-10-05 20:00 UTC, birsanv requested changes

2023-10-05 20:00 UTC, birsanv commented on business_continuity/backup_restore/backup_schedule.adoc
> +Since the `BackupSchedule.cluster.open-cluster-management.io` resource is still enabled on Hub1, Hub1 resumes writing backups to the same storage location as Hub2. Both hub clusters are now writing b
This is wrong : Any managed cluster restoring the latest backups. ( managed clusters don't restore backups )

It should be : Any hub cluster restoring the latest backups

2023-10-05 20:00 UTC, birsanv commented on business_continuity/backup_restore/backup_schedule.adoc
> +. The administrator tests a disaster scenario by making Hub2 a primary hub cluster, which inlcudes the following conditions occuring:
typo: which inlcudes

2023-10-05 20:00 UTC, birsanv commented on business_continuity/backup_restore/backup_schedule.adoc
> +Since the `BackupSchedule.cluster.open-cluster-management.io` resource is still enabled on Hub2, it might write backups at the same storage location that corrupts the backup data. Any managed cluster
this : it might write backups

should be : it will write backups. ( 100% happening :)

2023-10-05 20:00 UTC, birsanv commented on business_continuity/backup_restore/backup_schedule.adoc
> +Since the `BackupSchedule.cluster.open-cluster-management.io` resource is still enabled on Hub2, it might write backups at the same storage location that corrupts the backup data. Any managed cluster
here again, replace : Any managed cluster restoring 

with : Any hub cluster restoring

2023-10-06 07:13 UTC, oafischer commented
Thanks for the review @birsanv! Made the requested changes, let me know if it looks good now.

2023-10-06 13:49 UTC, birsanv approved these changes
looks good, thanks !

2023-10-09 12:33 UTC, dockerymick commented
@oafischer thanks for your patience, reviewing this now

2023-10-09 13:16 UTC, dockerymick requested changes

2023-10-09 13:16 UTC, dockerymick commented on business_continuity/backup_restore/backup_schedule.adoc
> +As a result, the latest backups are generated by a hub cluster that is no longer set as the primary hub cluster. This hub cluster still produces backups because the `BackupSchedule.cluster.open-clust
the second part of the second sentence seems repetitive. 
```suggestion
As a result, the latest backups are generated by a hub cluster that is no longer set as the primary hub cluster. This hub cluster still produces backups because the `BackupSchedule.cluster.open-cluster-management.io` resource is still enabled.
```

2023-10-09 13:16 UTC, dockerymick commented on business_continuity/backup_restore/backup_schedule.adoc
> +** Hub1 is stopped.
Consider using the hyphen, to avoid the double-asterisk issue.

2023-10-09 13:16 UTC, dockerymick commented on business_continuity/backup_restore/backup_schedule.adoc
> +. The primary hub cluster fails unexpectedly, which inlcudes the following conditions occuring:
Or continue to use includes, just double check spelling
```suggestion
. The primary hub cluster fails unexpectedly, which causes the following conditions to occur:
```

2023-10-09 13:16 UTC, dockerymick commented on business_continuity/backup_restore/backup_schedule.adoc
> +** The primary hub cluster called Hub1 fails.
```suggestion
** Communication from the primary hub cluster to Hub1 fails.
```

2023-10-09 13:16 UTC, dockerymick commented on business_continuity/backup_restore/backup_schedule.adoc
> +. The administrator tests a disaster scenario by making Hub2 a primary hub cluster, which includes the following conditions occuring:
```suggestion
. The administrator tests a disaster scenario by making Hub2 a primary hub cluster, which causes the following conditions to occur:
```

2023-10-09 13:24 UTC, oafischer commented
Thanks for the review @dockerymick! Let me know if it looks good now.

2023-10-09 14:40 UTC, dockerymick approved these changes
Your changes look good. Thanks Oliver!

2023-10-10 08:23 UTC, merged