https://issues.redhat.com/browse/ACM-6522 CIM complete restructure
open-cluster-management/rhacm-docs pull request #5605
Opened 2023-10-09 16:04 UTC by oafischer

This restructure includes modularization of the entire CIM doc, a restructure that adheres to our best practices, renaming of file names and topics, as well as rewrites of select sections that required them the most.

The new intro has already been implemented. The other new content will be added later.

The plan is to backport this to 2.8 and 2.7, but I cannot guarantee that this will happen, given that restructures are not usually backported.

2023-10-10 08:26 UTC, oafischer commented on clusters/cluster_lifecycle/cim_adv_config.adoc
> +== Creating a host inventory by using the command line interface
Given that this topic is rather long I'll probably pull it out of advanced config.

2023-10-10 11:24 UTC, avishayt commented on clusters/cluster_lifecycle/cim_intro.adoc
> +You can use the console to create a host inventory, which is a pool of bare metal virtual machines that you can use to create on-premises {ocp-short} clusters. These clusters can be standalone, with
```suggestion
You can use the console to create a host inventory, which is a pool of bare metal or virtual machines that you can use to create on-premises {ocp-short} clusters. These clusters can be standalone, with dedicated machines for the control plane, or link:../clusters/hosted_control_planes/hosted_intro.adoc#hosted-control-planes-intro[hosted control planes], where the control plane runs as pods on a hub cluster. You can install standalone clusters by using the console, API, or GitOps by using Zero Touch Provisioning (ZTP). See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.13/html-single/scalability_and_performance/index#installing-disconnected-rhacm_ztp-preparing-the-hub-cluster[Installing GitOps ZTP in a disconnected environment] in the {ocp} documentation for more information on ZTP.
```

2023-10-10 11:24 UTC, avishayt commented on clusters/cluster_lifecycle/cim_intro.adoc
> +The host inventory management and on-premises cluster installation are available by using the {mce-short} Central Infrastructure Management (CIM) feature. CIM runs the Assisted Installer (also called
```suggestion
The host inventory management and on-premises cluster installation are available using the {mce-short} Central Infrastructure Management (CIM) feature. CIM runs the Assisted Installer (also called infrastructure operator) as an operator on the hub cluster.
```

2023-10-10 11:24 UTC, avishayt commented on clusters/cluster_lifecycle/cim_intro.adoc
> +You can install osts in the inventory as OpenShift nodes later. The agent writes the operating system to the disk, along with the necessary configuration and reboot the host.
```suggestion
You can install hosts in the inventory as OpenShift nodes later. The agent writes the operating system to the disk, along with the necessary configuration, and reboots the host.
```

2023-10-10 11:24 UTC, avishayt commented on clusters/cluster_lifecycle/cim_enable.adoc
> +- You need a configured instance of the Central Infrastructure Management (CIM) feature on your hub cluster.
How can they have a configured instance of CIM as a prerequisite for enabling CIM?

2023-10-10 11:24 UTC, avishayt commented on clusters/cluster_lifecycle/cim_enable.adoc
> +- You need your SSH key that is in your `id_rsa.pub` file by default. The default file path is `~/.ssh/id_rsa.pub`.
The pull secret and SSH key are prerequisites for creating an InfraEnv, not for enabling CIM.

2023-10-10 11:24 UTC, avishayt commented on clusters/cluster_lifecycle/cim_enable.adoc
> +If your hub cluster is on any other platform, continue at . If your hub cluster in installed on a platfrom from the previous list, modify the `Provisioning` resource to allow the Bare Metal Operator
"continue at ." ?

2023-10-10 11:24 UTC, avishayt commented on clusters/cluster_lifecycle/cim_enable.adoc
> +You can skip this topic if your hub cluster is installed on one of the following platforms:
```suggestion
You can skip this topic if your hub cluster is *not* installed on one of the following platforms:
```

2023-10-10 11:24 UTC, avishayt commented on clusters/cluster_lifecycle/cim_enable.adoc
> +If your hub cluster is on any other platform, continue at . If your hub cluster in installed on a platfrom from the previous list, modify the `Provisioning` resource to allow the Bare Metal Operator
I also think that this sentence isn't necessary because we already wrote before the list that they can skip this topic for other platforms.

2023-10-10 11:24 UTC, avishayt commented on clusters/cluster_lifecycle/cim_enable.adoc
> +- You must have the Bare Metal Operator installed on your hub cluster.
Only for clusters with platforms that support the baremetal operator - baremetal, OpenStack, vSphere, none.

2023-10-10 11:24 UTC, avishayt commented on clusters/cluster_lifecycle/cim_enable.adoc
> +*Important:* If you are using the late binding feature and the `spec.osImages` releases in the `AgentServiceConfig` custom resource are version 4.13 or later, the {ocp-short} release images that you
I don't think readers will understand what "late binding" is at this point, and the remainder of the sentence isn't very clear.

2023-10-10 11:24 UTC, avishayt commented on clusters/cluster_lifecycle/cim_enable.adoc
> +----
This shouldn't be needed.  It's created by the baremetal operator being installed, and we already had instructions above for adding "watchAllNamespaces: true".  Let's verify.

2023-10-10 11:24 UTC, avishayt commented on clusters/cluster_lifecycle/cim_configure.adoc
> += Configuring the Central Infrastructure Management (CIM) service
I don't understand what will go in this section.  The topics below on roles/network are related to configuring clusters, not to the CIM service itself.

2023-10-10 11:24 UTC, avishayt commented on clusters/cluster_lifecycle/cim_import.adoc
> += Importing an {ocp-short} cluster
This shouldn't go under the topic of CIM itself - it's part of configuring and installing clusters using CIM.

2023-10-10 12:22 UTC, jelkosz commented on clusters/cluster_lifecycle/cim_create.adoc
> +- Network type: Specifies which types of hosts can be added to your infrastructure environment.
More like: specifies how the host IPs will be configured

2023-10-10 12:22 UTC, jelkosz commented on clusters/cluster_lifecycle/cim_create.adoc
> +- Location: Specifies the geographic location of the host. The geographic location can be used to easily determine where your data on a cluster is stored when you are creating the cluster.
I would maybe not talk about the data - if you are using some external storage provider, the location of the hosts has no bearing on where the data will end up. Id maybe wrote something like:
"Specifies the geographic location of the hosts in this infra env. The geographic location can be used to, for example, define which datacenter are the hosts located."

2023-10-10 12:22 UTC, jelkosz commented on clusters/cluster_lifecycle/cim_enable.adoc
> +- You need a configured storage class.
I think the storage class needs to be set as a "default" in order it to work with CIM

2023-10-10 12:22 UTC, jelkosz commented on clusters/cluster_lifecycle/cim_enable.adoc
> +- You must have a deployed hub cluster on {ocp-short} version 4.11 or later.
by hub cluster you mean "ACM or MCE" I guess, right? Is it used to just call it hub cluster in the docs?

2023-10-10 12:27 UTC, avishayt commented on clusters/cluster_lifecycle/cim_create.adoc
> +- Network type: Specifies which types of hosts can be added to your infrastructure environment.
Should we leave this section as is and revise it in a followup PR, or do it here?  I have the revised version in google docs:
https://docs.google.com/document/d/1G4Qds_rs51C5DJwKpzJ3klJHAr48EiYTVQtT-5voCkQ/edit?usp=sharing

2023-10-10 12:27 UTC, avishayt commented on clusters/cluster_lifecycle/cim_enable.adoc
> +- You must have a deployed hub cluster on {ocp-short} version 4.11 or later.
These are ACM docs.  Hub cluster is the name for it in the docs.

2023-10-10 12:31 UTC, jelkosz commented on clusters/cluster_lifecycle/cim_enable.adoc
> +- You must have a deployed hub cluster on {ocp-short} version 4.11 or later.
ok

2023-10-10 12:34 UTC, filanov commented on clusters/cluster_lifecycle/cim_configure.adoc
> += Configuring the Central Infrastructure Management (CIM) service
i agree, configuring CIM sounds like "how to configure the infrastructure operator"

2023-10-10 12:34 UTC, filanov commented on clusters/cluster_lifecycle/cim_create.adoc
> += Creating a host inventory by using the console
does it worth mentioning that is will create late binding flow? 
@avishayt what do you think?

2023-10-10 12:34 UTC, filanov commented on clusters/cluster_lifecycle/cim_enable.adoc
> +- You must have a deployed hub cluster on {ocp-short} version 4.11 or later.
it depend on the ACM version, this part need to be aligned with existing docs like https://access.redhat.com/articles/7006295

2023-10-10 12:34 UTC, filanov commented on clusters/cluster_lifecycle/cim_enable.adoc
> +- You must have the Bare Metal Operator installed on your hub cluster.
we still need  a bmh CRD to exist, but we don't require ironic or baremetal operator to run

2023-10-10 12:34 UTC, filanov commented on clusters/cluster_lifecycle/cim_enable.adoc
> +*Important:* If you are using the late binding feature and the `spec.osImages` releases in the `AgentServiceConfig` custom resource are version 4.13 or later, the {ocp-short} release images that you
agree, it's mixing between the creation of the infra env and the creation of the operator

2023-10-10 12:34 UTC, filanov commented on clusters/cluster_lifecycle/cim_enable.adoc
> +<1> Replace `db_volume_size` with the volume size for the `databaseStorage` field, for example `1Gi`. This value specifies how much storage is allocated for storing files such as database tables and
i'm suggesting to increase the example to 10G

2023-10-10 12:37 UTC, oafischer commented on clusters/cluster_lifecycle/cim_enable.adoc
> +- You need a configured instance of the Central Infrastructure Management (CIM) feature on your hub cluster.
Good question, this is from the existing doc. I guess we can just remove this point?

2023-10-10 12:46 UTC, oafischer commented on clusters/cluster_lifecycle/cim_enable.adoc
> +If your hub cluster is on any other platform, continue at . If your hub cluster in installed on a platfrom from the previous list, modify the `Provisioning` resource to allow the Bare Metal Operator
I restructured this section, hopefully it is clearer now.

2023-10-10 12:49 UTC, oafischer commented on clusters/cluster_lifecycle/cim_enable.adoc
> +*Important:* If you are using the late binding feature and the `spec.osImages` releases in the `AgentServiceConfig` custom resource are version 4.13 or later, the {ocp-short} release images that you
If the user doesn't know what late binding is at this point, should we just remove this note?

2023-10-10 12:50 UTC, oafischer commented on clusters/cluster_lifecycle/cim_enable.adoc
> +----
Does everyone agree we can remove this topic?

2023-10-10 12:51 UTC, oafischer commented on clusters/cluster_lifecycle/cim_configure.adoc
> += Configuring the Central Infrastructure Management (CIM) service
It sounds like the CIM service cannot be configured? So we can remove this section?

2023-10-10 12:57 UTC, oafischer commented on clusters/cluster_lifecycle/cim_import.adoc
> += Importing an {ocp-short} cluster
I saw you recommended putting it create cluster on prem. The create cluster files are only for creating clusters, not importing. Is there a different section we could put it? It sounds like we need a new import file. Right now we have import via console, cli, and agent.

2023-10-10 12:58 UTC, oafischer commented on clusters/cluster_lifecycle/cim_create.adoc
> +- Network type: Specifies which types of hosts can be added to your infrastructure environment.
If you have a separate issue for that let's address it in a separate PR, we want to focus on structure in this PR.

2023-10-11 09:57 UTC, avishayt commented on clusters/cluster_lifecycle/cim_configure.adoc
> += Configuring the Central Infrastructure Management (CIM) service
Yes, we can remove it

2023-10-11 09:57 UTC, avishayt commented on clusters/cluster_lifecycle/cim_create.adoc
> += Creating a host inventory by using the console
I think we should leave it out for now.  If we see the need for it while updating the cluster installation section then we can add it with the context.

2023-10-11 09:57 UTC, avishayt commented on clusters/cluster_lifecycle/cim_create.adoc
> +- Network type: Specifies which types of hosts can be added to your infrastructure environment.
OK, so let's leave this comment for now.

2023-10-11 09:57 UTC, avishayt commented on clusters/cluster_lifecycle/cim_create.adoc
> +- Location: Specifies the geographic location of the host. The geographic location can be used to easily determine where your data on a cluster is stored when you are creating the cluster.
I updated it in the google doc.  We can make that change when we revise the section.
https://docs.google.com/document/d/1G4Qds_rs51C5DJwKpzJ3klJHAr48EiYTVQtT-5voCkQ/edit#heading=h.2hbi7jystquq

2023-10-11 09:57 UTC, avishayt commented on clusters/cluster_lifecycle/cim_enable.adoc
> +- You must have the Bare Metal Operator installed on your hub cluster.
Right

2023-10-11 09:57 UTC, avishayt commented on clusters/cluster_lifecycle/cim_enable.adoc
> +- You need a configured storage class.
So:
```suggestion
- You need a configured default storage class.
```

2023-10-11 09:57 UTC, avishayt commented on clusters/cluster_lifecycle/cim_enable.adoc
> +*Important:* If you are using the late binding feature and the `spec.osImages` releases in the `AgentServiceConfig` custom resource are version 4.13 or later, the {ocp-short} release images that you
@filanov What do you think?  Can you suggest something?

2023-10-11 09:57 UTC, avishayt commented on clusters/cluster_lifecycle/cim_enable.adoc
> +<1> Replace `db_volume_size` with the volume size for the `databaseStorage` field, for example `1Gi`. This value specifies how much storage is allocated for storing files such as database tables and
Sure.

2023-10-11 09:57 UTC, avishayt commented on clusters/cluster_lifecycle/cim_enable.adoc
> +----
@filanov ?

2023-10-11 09:57 UTC, avishayt commented on clusters/cluster_lifecycle/cim_import.adoc
> += Importing an {ocp-short} cluster
I think the doc flow that makes sense in the installation section is:
(1) Installing new clusters
(2) Importing existing clusters
(3) Adding nodes to clusters

2023-10-11 10:16 UTC, oafischer commented on clusters/cluster_lifecycle/cim_enable.adoc
> +- You must have a deployed hub cluster on {ocp-short} version 4.11 or later.
We need to update this every release, there are many instances like this one in the doc so we don't always catch. Let me know what the right ocp version is for 2.7, 2.8 and 2.9.

2023-10-12 09:48 UTC, oafischer commented on clusters/cluster_lifecycle/cim_import.adoc
> += Importing an {ocp-short} cluster
Agreed, but there is currently no section that can support the import process we are describing. I will discuss with my team when I pull them in for a peer review.

2023-10-16 12:11 UTC, swopebe requested changes
There is a lot going on here. If we get 85% better this first round, I think we did well for 2.9. Thank you for your hard work.

Import may need to be retitled  
Resources within the doc are not all set off with `code`
A note about adv config
some other comments and formatting questions

2023-10-16 12:11 UTC, swopebe commented on clusters/cluster_lifecycle/cim_adv_config.adoc
> +Advanced configuration for CIM.
Please write a short description because I do not understand what this topic is for, meaning are we placing something in "advanced config" because we don't have another place for it?

(Adv config should be used for what is beyond default that the use **may** want to enable (turning a flag on and off or enabling extra features). Creating via command line is usually not what we would place in adv config if it is something that most users will need to do, it is simply a task.

2023-10-16 12:11 UTC, swopebe commented on clusters/cluster_lifecycle/cim_adv_config.adoc
> +Draft
Please remove line 9. It doesn't appear to be hidden but we need to reduce hidden comments anyway, I am starting to see them more and more lol. We can use PR comments.

2023-10-16 12:11 UTC, swopebe commented on clusters/cluster_lifecycle/cim_create_console.adoc
> +
Prereqs?

2023-10-16 12:11 UTC, swopebe commented on clusters/cluster_lifecycle/cim_enable.adoc
> += Enabling the Central Infrastructure Management (CIM) service
Did we look at naming guidance to see if CIM is approved?

2023-10-16 12:11 UTC, swopebe commented on clusters/cluster_lifecycle/cim_enable.adoc
> +- You must have a deployed hub cluster on {ocp-short} version 4.11 or later.
We write this the same way in RHACM docs; the support matrix is separate. This is throughout the doc. Please do not rewrite the support matrix, but something like:

In the matrix, we have added:

## General support statement
* RHACM support includes the most current RHACM version, two previous versions, and all z-stream releases of those supported versions.
* RHACM support includes the current OCP version, two previous versions, and z-stream releases of those supported OCP versions.
* RHACM support also includes the very next OCP version that will be released for this current RHACM version.


But we don't want that in the docs because that is a nightmare to place all over and try to explain without the table.

You must have a deployed hub cluster on  {ocp-short} 4.11 or later with the support RHACM version....

(Something like this @filanov, we can edit it a bit.)

@oafischer I may start asking that we link to the support matrix for 2.9 and later only from the introduction files.

2023-10-16 12:11 UTC, swopebe commented on clusters/cluster_lifecycle/cim_enable.adoc
> +- You must have a deployed hub cluster on {ocp-short} version 4.11 or later.
ACM docs are for RHACM users and within we have "cluster lifecycle" docs. We demoed this in a RHACM playback to show our developers where the MCE doc. 

These are actually MCE docs, which are written to standalone from RHACM because the user at this point does not have RHACM features.

It's important to keep MCE docs only MCE without reference to RHACM. I can show this to you guys in a meeting if needed.

2023-10-16 12:11 UTC, swopebe commented on clusters/cluster_lifecycle/cim_enable.adoc
> ++
There may be a formatting issue here.

2023-10-16 12:11 UTC, swopebe commented on clusters/cluster_lifecycle/cim_import.adoc
> += Importing an {ocp-short} cluster
CIM docs need to stay all together because we have to have PRs from an outside team. (I met with our PM about this recently and we could not easily find what is related to CIM). It should be renamed to be clear that it is a CIM topic. If it is not a CIM topic, let's discuss.

2023-10-16 12:11 UTC, swopebe commented on clusters/cluster_lifecycle/cim_intro.adoc
> +You can use the console to create a host inventory, which is a pool of bare metal or virtual machines that you can use to create on-premises {ocp-short} clusters. These clusters can be standalone, wi
really long paragraph here with a lot of links. I think we need to break this up.

2023-10-16 12:11 UTC, swopebe commented on clusters/cluster_lifecycle/cim_intro.adoc
> +
Is this not a better short description, which would go at the top?

2023-10-16 12:15 UTC, oafischer commented on clusters/cluster_lifecycle/cim_adv_config.adoc
> +Advanced configuration for CIM.
This is a placeholder for issues such as ACM-7817. Hoping to discuss more with devs but I agree that CLI would just come after the console topic.

2023-10-16 12:18 UTC, oafischer commented on clusters/cluster_lifecycle/cim_enable.adoc
> += Enabling the Central Infrastructure Management (CIM) service
CIM does not appear in the guidance, I still need to reach out to Kristin to have some guidance added (even if it means not being able to use CIM).

2023-10-16 12:23 UTC, oafischer commented on clusters/cluster_lifecycle/cim_import.adoc
> += Importing an {ocp-short} cluster
So is this official confirmation to leave this topic where it is at the moment?

2023-10-16 12:33 UTC, avishayt commented on clusters/cluster_lifecycle/cim_import.adoc
> += Importing an {ocp-short} cluster
What does "CIM docs" or "CIM topic" mean?  There are a few parts of CIM:
1. Enabling CIM
2. Host inventory (creating an infra-env, booting the ISO, discovering hosts)
3. Installing standalone clusters (where I expect this import topic would go)

And then there is bare-metal hosted clusters which uses 1+2 but maybe isn't really "CIM" itself.

2023-10-16 12:34 UTC, oafischer commented on clusters/cluster_lifecycle/cim_intro.adoc
> +
Agreed, I'll switch it around and edit the other paragraph

2023-10-16 14:26 UTC, oafischer commented on clusters/cluster_lifecycle/cim_create_console.adoc
> +
Are there any prereqs @avishayt? Enabling CIM first?

2023-10-16 14:32 UTC, avishayt commented on clusters/cluster_lifecycle/cim_create_console.adoc
> +
Yes, enabling CIM, but that's true for every CIM topic

2023-10-17 13:52 UTC, oafischer commented on clusters/cluster_lifecycle/cim_import.adoc
Please review this file when you have a chance @elgnay, thanks!

2023-10-18 09:46 UTC, elgnay commented on clusters/cluster_lifecycle/cim_import.adoc
@xiangjingli You may want to take a look as well.

2023-10-18 14:09 UTC, oafischer commented on clusters/cluster_lifecycle/cim_import.adoc
FYI @elgnay @xiangjingli this PR needs to be merged because it is blocking other work, but please feel free to comment and review after it is merged. I will make sure to implement the suggestions in a new PR. Thanks!

2023-10-18 14:30 UTC, swopebe approved these changes

2023-10-18 14:33 UTC, avishayt commented
/approve

2023-10-18 14:35 UTC, merged