[ACM-7858]: Adding port limitation and KubeVirt troubleshooting docs
open-cluster-management/rhacm-docs pull request #5612
Opened 2023-10-11 16:20 UTC by lahinson

Related Jira: https://issues.redhat.com/browse/ACM-7858

2023-10-11 20:17 UTC, davidvossel commented on troubleshooting/trouble_hosted_clusters_kubevirt.adoc
> +* In the `kubeconfig` file of the hosted cluster, inspect the status of the hosted cluster:
`In the kubeconfig` reads more accurately as `Using the kubeconfig`"

2023-10-11 20:17 UTC, davidvossel commented on troubleshooting/trouble_hosted_clusters_kubevirt.adoc
> +* If a PVC is failing to attach to a pod, view the logs for the kubevirt-sci-node daemonset component within the hosted cluster to further investigate the problem. To identify the kubevirt-csi-node p
"kubevirt-sci-node" should be "kubevirt-csi-node"

2023-10-11 20:17 UTC, davidvossel commented on troubleshooting/trouble_hosted_clusters_kubevirt.adoc
> ++
For this section about accessing the VM console logs, the CNV team recently published an article on access.redhat.com outlining how to do this.

Maybe we can just reference the article? https://access.redhat.com/solutions/7037705 ?

Also, for now lets not mention the kubevirt 1.1.0 method. That will get released in 4.15 (MCE-2.5/OCP-4.15 time frame). So in a few months when we're preparing for 4.15, we'll update this doc and say something to the effect of

```
When using OpenShift Virt 4.14 follow this document https://access.redhat.com/solutions/7037705.

In OpenShift Virt 4.15 use `oc logs -n <namespace> <vmi_pod> -c guest-console-log`

```

2023-10-11 20:41 UTC, lahinson commented on troubleshooting/trouble_hosted_clusters_kubevirt.adoc
> +* In the `kubeconfig` file of the hosted cluster, inspect the status of the hosted cluster:
Fixed

2023-10-11 20:41 UTC, lahinson commented on troubleshooting/trouble_hosted_clusters_kubevirt.adoc
> +* If a PVC is failing to attach to a pod, view the logs for the kubevirt-sci-node daemonset component within the hosted cluster to further investigate the problem. To identify the kubevirt-csi-node p
Good catch!

2023-10-11 20:46 UTC, lahinson commented on troubleshooting/trouble_hosted_clusters_kubevirt.adoc
> ++
Noted and updated. Thanks!

2023-10-11 21:14 UTC, davidvossel reviewed
/lgtm

Thanks!

2023-10-12 18:26 UTC, swopebe requested changes

2023-10-12 18:26 UTC, swopebe commented on clusters/hosted_control_planes/create_hosted_clusters_kubevirt_default_ingress_dns.adoc
> +For the default Ingress DNS to work properly, the cluster that hosts the KubeVirt virtual machines must allow wildcard DNS routes. You can configure this behavior by entering the following command: `
I think we usually put these in codeblock on a separate line.

2023-10-12 18:26 UTC, swopebe commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> +* To troubleshoot hosted clusters on {ocp-virt}, see xref:../support_troubleshooting/trouble_hosted_clusters_kubevirt.adoc#troubleshooting-hosted-cluster-kubevirt[Troubleshooting hosted clusters on {
We don't normally link to Troubleshooting, with the idea that if it needs to be in the task, then it is best to write it as procedure. (Do you feel strongly that you need it here?)

2023-10-12 18:26 UTC, swopebe commented on clusters/support_troubleshooting/trouble_hosted_clusters_kubevirt.adoc
> +// In {ocp-virt} 4.15, enter the following command to access the VM console logs: `oc logs -n <namespace> <vmi_pod> -c guest-console-log`
This looks like it needs to be a few separate files, if we are following the format we have in the troubleshooting folder. Is it practice on your end to add them all to one doc?

2023-10-12 18:26 UTC, swopebe commented on clusters/support_troubleshooting/trouble_hosted_clusters_kubevirt.adoc
> +// In {ocp-virt} 4.15, enter the following command to access the VM console logs: `oc logs -n <namespace> <vmi_pod> -c guest-console-log`
we can discuss and revisit, just want to make sure we are all treating these scenarios similarly.

2023-10-16 17:22 UTC, lahinson commented on clusters/hosted_control_planes/create_hosted_clusters_kubevirt_default_ingress_dns.adoc
> +For the default Ingress DNS to work properly, the cluster that hosts the KubeVirt virtual machines must allow wildcard DNS routes. You can configure this behavior by entering the following command: `
Good catch -- will update.

2023-10-16 17:23 UTC, lahinson commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> +* To troubleshoot hosted clusters on {ocp-virt}, see xref:../support_troubleshooting/trouble_hosted_clusters_kubevirt.adoc#troubleshooting-hosted-cluster-kubevirt[Troubleshooting hosted clusters on {
I don't feel strongly about it. I can remove the link if we don't typically link to troubleshooting.

2023-10-16 17:23 UTC, lahinson commented on clusters/support_troubleshooting/trouble_hosted_clusters_kubevirt.adoc
> +// In {ocp-virt} 4.15, enter the following command to access the VM console logs: `oc logs -n <namespace> <vmi_pod> -c guest-console-log`
I'll split this into separate files by scenario. Thanks!

2023-10-16 18:39 UTC, swopebe approved these changes
looks amazing

2023-10-16 20:44 UTC, merged