ACM-7909: add a note about uniqueness of hosted cluster names
open-cluster-management/rhacm-docs pull request #5617
Opened 2023-10-11 21:37 UTC by rokej

This is for https://issues.redhat.com/browse/ACM-7563, https://issues.redhat.com/browse/ACM-7909.

We need to add a note about MCE's requirement that each hosted cluster must have a unique name to be managed by MCE or ACM.

2023-10-11 21:39 UTC, rokej commented
@lahinson Could you please refine and format my updates in this PR? Thank you.

2023-10-12 14:12 UTC, lahinson requested changes
@rokej I provided a few edits. Let me know if you have any questions. Thanks!

2023-10-12 14:12 UTC, lahinson commented on clusters/hosted_control_planes/managing_hosted_aws.adoc
> +You can use the hcp command line interface to create a {ocp} hosted cluster. The hosted cluster is automatically imported as a managed cluster. If you wish to disable this automatic import feature, r
```suggestion
You can use the hosted control plane command line interface (`hcp`) to create an {ocp-short} hosted cluster. The hosted cluster is automatically imported as a managed cluster. If you want to disable this automatic import feature, see xref:../hosted_control_planes/hosted_disable_auto_import.adoc#hosted-disable-auto-import[Disabling the automatic import of hosted clusters into {mce-short}].
```

2023-10-12 14:12 UTC, lahinson commented on clusters/hosted_control_planes/managing_hosted_aws.adoc
> +Note: Each hosted cluster must have a unique name in order of {mce-short} to manage it.
```suggestion
*Note:* Each hosted cluster must have a unique name in order for {mce-short} to manage it.
```

2023-10-12 14:12 UTC, lahinson commented on clusters/hosted_control_planes/managing_hosted_bm.adoc
> +You can use the {mce} console or the hcp command line interface to create a {ocp} hosted cluster. The hosted cluster is automatically imported as a managed cluster. If you wish to disable this automa
```suggestion
You can use the {mce-short} console or the hosted control plane command line interface (`hcp`) to create an {ocp-short} hosted cluster. The hosted cluster is automatically imported as a managed cluster. If you want to disable this automatic import feature, see xref:../hosted_control_planes/hosted_disable_auto_import.adoc#hosted-disable-auto-import[Disabling the automatic import of hosted clusters into {mce-short}].
```

2023-10-12 14:12 UTC, lahinson commented on clusters/hosted_control_planes/managing_hosted_bm.adoc
> +Note: Each hosted cluster must have a unique name in order of {mce-short} to manage it.
```suggestion
*Note:* Each hosted cluster must have a unique name in order for {mce-short} to manage it.
```

2023-10-12 14:12 UTC, lahinson commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> +You can use the hcp command line interface to create a {ocp} hosted cluster. The hosted cluster is automatically imported as a managed cluster. If you wish to disable this automatic import feature, r
```suggestion
You can use the hosted control plane command line interface (`hcp`) to create an {ocp-short} hosted cluster. The hosted cluster is automatically imported as a managed cluster. If you want to disable this automatic import feature, see xref:../hosted_control_planes/hosted_disable_auto_import.adoc#hosted-disable-auto-import[Disabling the automatic import of hosted clusters into {mce-short}].
```

2023-10-12 14:12 UTC, lahinson commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
> +Note: Each hosted cluster must have a unique name in order of {mce-short} to manage it.
```suggestion
*Note:* Each hosted cluster must have a unique name in order for {mce-short} to manage it.
```

2023-10-12 14:37 UTC, rokej commented
@lahinson Thank you.

2023-10-12 14:43 UTC, lahinson approved these changes

2023-10-12 14:54 UTC, merged