acm-2.9 (volsync v0.8) - volume populator update
open-cluster-management/rhacm-docs pull request #5620
Opened 2023-10-12 15:32 UTC by tesshuflower

Possible we can simply modify this existing section (which used to outline converting the snapshot in a ReplicationDestination's status.latestImage) into a PVC.

Now we can replace some steps to use the VolumePopulator instead.

This PR probably needs help with formatting and possibly wording too :)

2023-10-17 20:48 UTC, dockerymick commented
@tesshuflower thanks again for starting the PR. Reminder to writer: Update What's new

2023-10-26 04:00 UTC, dockerymick commented
@cadawson is this ready to be merged?

2023-10-27 17:37 UTC, cadawson commented
Hi @tesshuflower. Have you had a chance to take a look at the changes for this one? Thanks!

2023-10-27 19:20 UTC, tesshuflower commented
> Hi @tesshuflower. Have you had a chance to take a look at the changes for this one? Thanks!

Hey @cadawson sorry I didn't see your commit in this PR - I've looked at it and the changes look good to me!  👍  Thank you!

2023-10-30 19:05 UTC, swopebe requested changes
few comments and questions for consideration

2023-10-30 19:05 UTC, swopebe commented on business_continuity/volsync/volsync_convert_backup.adoc
Some of the titles in certain books are long. I would like us to explore when and where we can reduce wordy titles. Not sure if this is a candidate.

I am also concerned that the title and short description do not say the same thing. 

Title: Converting

Description (which should explain the title): Use, recover, create.

2023-10-30 19:05 UTC, swopebe commented on business_continuity/volsync/volsync_convert_backup.adoc
> +Here is an example:
Please change this (demonstrative) to: 

See the following YAML with `dataSourceRef`..... (or something explaining better the example)

2023-10-30 19:05 UTC, swopebe commented on business_continuity/volsync/volsync_convert_backup.adoc
> +Replace `destination-ns` with the namespace where the persistent volume claim (and `ReplicationDestination`) are located.
Parentheses are discouraged in the manual. This can simply be joined with a comma.

2023-10-30 19:05 UTC, swopebe commented on business_continuity/volsync/volsync_convert_backup.adoc
>  Your original backup image is running as the main persistent volume claim.
Is this verification? Are we assuming it is running? If we don't have a way to check, we should not assume it is working. I am not sure why some of the books took this direction for the "Verification" step, but we talked about not adding anything if there is no step to verify given by development.

2023-10-30 19:05 UTC, swopebe commented on business_continuity/volsync/volsync_convert_backup.adoc
> +
Plural

Remove "could" and "which might have been" for more active and concise language.

2023-10-30 19:07 UTC, swopebe commented
@cadawson I think writer editing still needed in a few spots to fit industry standards/Portal standards, please see comments.

2023-10-31 17:41 UTC, cadawson commented on business_continuity/volsync/volsync_convert_backup.adoc
>  Your original backup image is running as the main persistent volume claim.
Removed.

2023-10-31 17:42 UTC, cadawson commented on business_continuity/volsync/volsync_convert_backup.adoc
> +
Reworded. Thanks!

2023-10-31 17:43 UTC, cadawson commented
Thanks for the review @swopebe. Updates included.

2023-10-31 17:48 UTC, swopebe approved these changes

2023-11-02 14:08 UTC, dockerymick commented on business_continuity/volsync/volsync_convert_backup.adoc
> +is populated. The VolSync volume populator controller uses the `latestImage` from the `ReplicationDestination`. The `latestImage` is updated each time a replication completes
@cadawson will add the what's new entry and then merge

2023-11-03 15:48 UTC, merged