Acm 7922
open-cluster-management/rhacm-docs pull request #5647
Opened 2023-10-17 14:16 UTC by krishnanshruthi

2023-10-17 19:40 UTC, swopebe commented
Hi. For info:

We do need all of our PRs to be linked to the **RHACM doc issue** and **dev feature**, especially for new content so that we ensure that doc is only documenting what is prioritized for the release:

Please see that **process** on our playbook:
https://docs.google.com/document/d/1YTqpZRH54Bnn4WJ2nZmjaCoiRtqmrc2w6DdQxe_yLZ8/edit#heading=h.9fvyr2rdriby


This is because we maintain the repo, all bugs, build etc...

This big of a change should have gone come to us in the way of a known feature and been added by a RHACM writer, to help with the editing. Such a large PR will need to be accounted for in our scrums/release work. We work closely with development to maintain that process and work.

Please link the RHACM doc issue here along with the feature. Let's please discuss any future work like this that will be sent to the repo. 

@cadawson FYI.

2023-10-17 20:12 UTC, cadawson commented
The feature for this is: https://issues.redhat.com/browse/ACM-7922

2023-10-17 20:24 UTC, swopebe commented
@cadawson I am looking for the _RHACM_ doc issue that should have been opened for us? (per the process of adding new features) 

We need _PM and QE validation_, just as we treat all new features. 

(This late in the release, I would hope we had something like this slated in the train. There's a gap that hopefully Doc Guild can address in the future.) :-)

2023-10-18 13:04 UTC, swopebe commented
Discussion for short term:

We all agree that for the contribution from IBM, we do need confirmation and QE resources to say this has been tested, as the issues that come from this doc/feature will land in the RHACM doc/dev bucket. 

Not yet ready for support matrix or What's new, we will hold on this PR until we have more discussion.

Long term: feature process will be discussed in Doc Guild.

2023-10-30 19:11 UTC, swopebe commented
Note to consider. With this PR, I cannot easily check out to edit in VS Code. It is much easier to edit in VS Code in my opinion, so for large changes, I think it may be better to either not fork or to give us the content. I will edit in the browser for this one.

2023-10-31 02:05 UTC, swopebe requested changes
I am working this and seeing that it needs a lot of change. I am editing where it is clear and leaving comments. Please don't change anything just yet until I get through it. I am just keeping you updated. We probably need a meeting to address a few things. I will organize that when I get a chance.

2023-10-31 02:05 UTC, swopebe commented on clusters/hosted_control_planes/config_dns_bare-metal_ibmz.adoc
> +----
Question about the # and @ and $, as we don't typically add those in formal doc.

2023-10-31 02:05 UTC, swopebe commented on clusters/hosted_control_planes/config_dns_bare-metal_ibmz.adoc
> +*.apps                IN A 1xx.2x.2xx.1xx
`*.apps` throws off our PRs and we had a solution, I just have to remember or find what we did for that.

2023-10-31 02:05 UTC, swopebe commented on clusters/hosted_control_planes/config_dns_bare-metal_ibmz.adoc
> +For zvm, add additional IP addresses that correspond to the IP address of the agent.
What is zvm? We probably need to write this correctly either as code or a proper title.

2023-10-31 02:05 UTC, swopebe commented on clusters/hosted_control_planes/config_dns_bare-metal_ibmz.adoc
> +*.apps                IN A 1xx.2x.2xx.1xx
@krishnanshruthi we need to break this our as we did here:

https://github.com/stolostron/rhacm-docs/blob/2.9_stage/clusters/hosted_control_planes/create_hosted_clusters_kubevirt_default_ingress_dns.adoc?plain=1

Thanks @lahinson for that info.

2023-10-31 02:05 UTC, swopebe commented on clusters/hosted_control_planes/config_dns_bare-metal_ibmz.adoc
> +For zvm, add additional IP addresses that correspond to the IP address of the agent.
We also need to properly introduce what we are showing on line 28.

2023-10-31 02:05 UTC, swopebe commented on clusters/hosted_control_planes/configure_hosted_aws.adoc
> +//why is this https--bcs (internal link)
We need to link from within the doc here.

2023-10-31 02:05 UTC, swopebe commented on clusters/hosted_control_planes/configure_hosted_bm_ibmz.adoc
> +[#configuring-hosting-service-cluster-configure-ibmz]
Note for me to pick up here with removing note and labeling tech preview as the rest of the doc.

2023-10-31 02:05 UTC, swopebe commented on clusters/hosted_control_planes/configure_hosted_aws.adoc
> +* The xref:xref:../clusters/hosted_control_planes/hosted_install_cli.adoc#hosted-install-cli[Installing the hosted control plane command line interface].
link changed

2023-10-31 02:05 UTC, swopebe commented on clusters/hosted_control_planes/configure_hosted_bm_ibmz.adoc
> +[#configuring-hcp-bare-metal]
we title this configuring, but most of the topic is requirements, then the actual configuring is links to other topics, so let's explore changing this format.

2023-10-31 02:05 UTC, swopebe commented on clusters/hosted_control_planes/hosted-bm-agents-ibmz.adoc
> +
We definitely need a short description here.

2023-10-31 02:05 UTC, swopebe commented on clusters/hosted_control_planes/hosted-bm-agents-ibmz.adoc
> +- Boot zKVM and zVM with the downloaded PXE images from the 'InfraEnv' resource. Wait for the Agents to get created on the management cluster. At startup, the host communicates with the Assisted Serv
Is this a step? Not sure I understand what is going on in the beginning of this topic?

2023-10-31 02:05 UTC, swopebe commented on clusters/hosted_control_planes/hosted-bm-agents-ibmz.adoc
> +- Boot zKVM and zVM with the downloaded PXE images from the 'InfraEnv' resource. Wait for the Agents to get created on the management cluster. At startup, the host communicates with the Assisted Serv
When we give the user a command to run with lots of variables, we need to tell them what to replace. Do we need all of this in the command on line 9?

2023-10-31 02:05 UTC, swopebe commented on clusters/hosted_control_planes/hosted-bm-agents-ibmz.adoc
> +Following is the sample command for 'vswitch' network with fcp singlepath/ dasd disk:
what is meant by _fcp singlepath/ dasd disk_?

2023-10-31 02:05 UTC, swopebe commented on clusters/hosted_control_planes/hosted-bm-agents-ibmz.adoc
> +----
I am a bit disoriented in this file and not sure of the process. Let's revisit this and create 1. a solid description that tells the user what they are doing and why, and then clear steps, removing assumptions from abbreviations.

2023-10-31 02:05 UTC, swopebe commented on clusters/hosted_control_planes/managing_hosted_bm_ibmz.adoc
> += Managing hosted control plane clusters on bare metal (Technology Preview)
We need to revisit here bc its a file called _managing_ and it has _prereqs_ and _additional resources_, there is not really a task here to warrant a file...let's see how we can reformat, please?

2023-10-31 02:05 UTC, swopebe commented on clusters/hosted_control_planes/managing_hosted_bm_ibmz.adoc
> +
This section is for additional links, not follow on processes, so let's discuss moving this, though I think this whole file may need to be merged inside an actual task.

2023-10-31 04:57 UTC, Neeraj8418 commented on clusters/hosted_control_planes/configure_hosted_aws.adoc
> +* You can now deploy the SR-IOV Operator. For more information, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html/networking/hardware-networks#sriov-operat
https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html/networking/hardware-networks#sriov-operator-hosted-control-planes_configuring-sriov-operator ==> Is this the correct url?

2023-10-31 05:04 UTC, Neeraj8418 commented on clusters/hosted_control_planes/hosted-bm-agents-ibmz.adoc
> +vmur pun -r -u m1321006 -N kernel.img $INSTALLERKERNELLOCATION/<image name>
vmur pun -r -u <guest machine> -N kernel.img $INSTALLERKERNELLOCATION/<image name>. ==>remove the name of guest machine

2023-10-31 05:04 UTC, Neeraj8418 commented on clusters/hosted_control_planes/hosted-bm-agents-ibmz.adoc
> +vmur pun -r -u m1321006 -N generic.parm $PARMFILELOCATION/paramfilename
same as above

2023-10-31 05:04 UTC, Neeraj8418 commented on clusters/hosted_control_planes/hosted-bm-agents-ibmz.adoc
> +vmur pun -r -u m1321006 -N initrd.img $INSTALLERINITRAMFSLOCATION/<image name>
same as above

2023-10-31 05:07 UTC, Neeraj8418 commented on clusters/hosted_control_planes/hosted-bm-agents-ibmz.adoc
> +oc -n ${HOSTED_CONTROL_PLANE_NAMESPACE} patch agent 50c23cda-cedc-9bbd-bcf1-9b3a5c75804d -p '{"spec":{"installation_disk_id":"/dev/sda","approved":true,"hostname":"worker-zvm-0.hostedn.example.com"}}
oc -n ${HOSTED_CONTROL_PLANE_NAMESPACE} patch agent 50c23cda-cedc-9bbd-bcf1-9b3a5c75804d -p '{"spec":{"installation_disk_id":"/dev/sda","approved":true,"hostname":"worker-zvm-0.example.krnl.es"}}' --type merge. ==> The hostname can be different but change basedomain to krnl.es to avoid confusion

2023-10-31 10:07 UTC, swopebe commented on clusters/hosted_control_planes/configure_hosted_aws.adoc
> +* You can now deploy the SR-IOV Operator. For more information, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html/networking/hardware-networks#sriov-operat
I think so, but they aren't GA, yet. I think today?

2023-10-31 16:27 UTC, SNiemann15 commented on clusters/hosted_control_planes/hosted-bm-agents-ibmz.adoc
> +Following is the sample command for 'vswitch' network with fcp singlepath/ dasd disk:
FCP and DASD are disk types on IBM Z machines. Not sure what is meant with `singlepath`
vswitch is written as follows: VSwitch

2023-11-02 05:34 UTC, phani2898 commented on clusters/hosted_control_planes/config_dns_bare-metal_ibmz.adoc
> +The API Server for the hosted cluster is exposed as a 'NodePort' service. A DNS entry must exist for 'api.${HOSTED_CLUSTER_NAME}.${BASEDOMAIN}'' that points to the destination where the API Server ca
Extra ' is present in here `'api.${HOSTED_CLUSTER_NAME}.${BASEDOMAIN}''`

2023-11-02 05:34 UTC, phani2898 commented on clusters/hosted_control_planes/config_dns_bare-metal_ibmz.adoc
> +worker-0              IN A 1xx.2x.2xx.1yy
I think we should replace `worker` with `compute` in every documentation as being followed

2023-11-06 14:41 UTC, swopebe commented on clusters/hosted_control_planes/scaling_nodepool_hosted_ibmz.adoc
> +You add nodes to your hosted cluster by scaling the NodePool object.
Needs bit more short description here.

2023-11-06 14:42 UTC, swopebe commented on clusters/hosted_control_planes/scaling_nodepool_hosted_ibmz.adoc
> +. Scale the NodePool object to two nodes:
Run the following command to...

2023-11-06 14:42 UTC, swopebe commented on clusters/hosted_control_planes/scaling_nodepool_hosted_ibmz.adoc
> +----
Format issues here

2023-11-06 15:10 UTC, swopebe commented on clusters/hosted_control_planes/config_dns_bare-metal_ibmz.adoc
> +----
Break up command, output, and files from commands. Remove # cat if we can for formal doc.

2023-11-06 15:13 UTC, swopebe commented on clusters/hosted_control_planes/config_dns_bare-metal_ibmz.adoc
> +worker-0              IN A 1xx.2x.2xx.1yy
Worked in the past but may not apply here: 
```
[source,bash]
----
*.apps.mgmt-cluster.example.com
----
```

2023-11-06 15:17 UTC, swopebe commented on clusters/hosted_control_planes/hosted-bm-agents-ibmz.adoc
> ++
space here

2023-11-06 15:18 UTC, swopebe commented on clusters/hosted_control_planes/hosted-bm-agents-ibmz.adoc
> ++
This command I have questions about; needs to be cleaned up and explained.

2023-11-06 15:19 UTC, swopebe commented on clusters/hosted_control_planes/hosted-bm-agents-ibmz.adoc
> +----
format issue

2023-11-06 15:21 UTC, swopebe commented on clusters/hosted_control_planes/scaling_nodepool_hosted_ibmz.adoc
> +You add nodes to your hosted cluster by scaling the NodePool object.
Why does the user want to scale.

2023-11-06 15:22 UTC, swopebe commented on clusters/hosted_control_planes/scaling_nodepool_hosted_ibmz.adoc
> ++
following is a list and a command, not sure what is needed in this section

2023-11-06 15:23 UTC, swopebe commented on clusters/hosted_control_planes/scaling_nodepool_hosted_ibmz.adoc
> +Sample output:
format issue

2023-11-06 15:23 UTC, swopebe commented on clusters/hosted_control_planes/config_dns_bare-metal_ibmz.adoc
> +----
* .apps in this area will throw of our format in the PR, we try to fix that where we can. Laura/Brandi.

2023-11-06 15:29 UTC, swopebe commented on clusters/hosted_control_planes/config_dns_bare-metal_ibmz.adoc
> +
double check command on line 4

2023-11-06 15:33 UTC, swopebe commented on clusters/hosted_control_planes/configure_hosted_aws.adoc
>  The {mce-short} 2.4 supports only the default `local-cluster` and the hub cluster as the hosting cluster.
Remove this file in the fork.

2023-11-06 15:34 UTC, swopebe commented on clusters/hosted_control_planes/configure_hosted_bm.adoc
remove from PR

2023-11-06 15:43 UTC, swopebe commented on clusters/hosted_control_planes/hosted-bm-agents-ibmz.adoc
> +
Command format should include `<proper-style-syntax>`

2023-11-07 16:38 UTC, SNiemann15 commented on clusters/hosted_control_planes/managing_hosted_bm_ibmz.adoc
> +[#additional-resources-manage-bm]
```suggestion
[#additional-resources-manage-ibmz]
```

2023-11-07 16:40 UTC, SNiemann15 commented on clusters/hosted_control_planes/configure_hosted_bm_ibmz.adoc
> +[#hosting-service-cluster-configure-prereq]
```suggestion
[#hosting-service-cluster-configure-prereq-ibmz]
```

2023-11-08 04:16 UTC, krishnanshruthi commented on clusters/hosted_control_planes/managing_hosted_bm_ibmz.adoc
> +[#additional-resources-manage-bm]
a. I did not change this -it is what it was or has been from the beginning.
b. The additional resources is common and the link given in the content for additional resources is not specific to ibm Z. So why are we changing the ID.

@SNiemann15

2023-11-08 04:18 UTC, krishnanshruthi commented on clusters/hosted_control_planes/configure_hosted_bm_ibmz.adoc
> +[#hosting-service-cluster-configure-prereq]
Same comment as before - Additionally i noticed that the rest of the sub-headings, dont necessarily have IBMz suffixed to the titles.

@SNiemann15

2023-11-08 15:07 UTC, SNiemann15 requested changes

2023-11-08 15:07 UTC, SNiemann15 commented on clusters/hosted_control_planes/config_dns_bare-metal_ibmz.adoc
> +*Note:* In the previous example, `1xx.2x.2xx.1xx` is a load balancer IP address that handles ingress and egress traffic for hosted control plane.
Not sure if I'm correct but I think ..cat is the command and starting with  $TTL is the output. 
Tagging [source,text] should resolve the * issue 
```suggestion
[source,terminal]
----
$ cat /var/named/<example.krnl.es.zone>  
----
+
.Example Output 
[source,text]
----
$ TTL 900
@ IN  SOA bastion.example.krnl.es.com. hostmaster.example.krnl.es.com. (
      2019062002
      1D 1H 1W 3H )
  IN NS bastion.example.krnl.es.com.
;
;
api                   IN A 1xx.2x.2xx.1xx <1>
api-int               IN A 1xx.2x.2xx.1xx
;
;
*api.${HOSTED_CLUSTER_NAME}.${BASEDOMAIN}           IN A 1xx.2x.2xx.1xx
;
;EOF
----
<1> The record refers to the IP address of the API load balancer that handles ingress and egress traffic for hosted control planes.
```

2023-11-08 15:11 UTC, swopebe commented on clusters/hosted_control_planes/configure_hosted_bm_ibmz.adoc
> +[#hosting-service-cluster-configure-prereq]
Please use the IBM z so that our team when creating links and such can better see where this file belongs. It is not as easy here as it was at IBM where the filenames are in the URLs. Thanks.

2023-11-08 15:17 UTC, swopebe commented on clusters/hosted_control_planes/config_dns_bare-metal_ibmz.adoc
> +*Note:* In the previous example, `1xx.2x.2xx.1xx` is a load balancer IP address that handles ingress and egress traffic for hosted control plane.
Hi! 

The bold on line 33 needs to be removed, being caused by the asterisks. 

I am not completely convinced that we need an full _example output_ in the doc...I want to make sure we can pause and ask if this is necessary. 

We have to maintain these outputs...meaning if anything changes, we are out of date without someone creating an issue for us. It may be better to tell the user what to search for in an output, unless the step is: 

See the following example and ensure you have X, Y, Z. (This would indicate that they have to search for something from the example.)

Also please change to:

See the following example output: (line 19, as that is how we introduce an example).

We have a number of conflicts that I will have to try to address tomorrow or the next day...just noting.

2023-11-09 01:34 UTC, lahinson requested changes
@krishnanshruthi @SNiemann15 I provided several peer review comments along with @swopebe's comments. Let me know if you have any questions for me. Thanks!

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/config_dns_bare-metal_ibmz.adoc
> += Configure DNS for hosted control plane
```suggestion
= Configuring DNS for hosted control planes on IBM Z
```

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/config_dns_bare-metal_ibmz.adoc
> +The API Server for the hosted cluster is exposed as a 'NodePort' service. A DNS entry must exist for the `api.<hosted_cluster_name>.<base-domain>` that points to the destination where the API Server
```suggestion
The API server for the hosted cluster is exposed as a 'NodePort' service. A DNS entry must exist for the `api.<hosted_cluster_name>.<base-domain>` that points to the destination where the API server is reachable.
```
Unless there is a specific reason to capitalize "Server", the "s" in "API server" should be lowercase.

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/config_dns_bare-metal_ibmz.adoc
> +For IBM z/VM, add additional IP addresses that correspond to the IP address of the agent.
```suggestion
For IBM z/VM, add IP addresses that correspond to the IP address of the agent.
```
The phrase "add additional" can be simplified to "add".

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/configure_hosted_aws.adoc
> +* The xref:xref:../clusters/hosted_control_planes/hosted_install_cli.adoc#hosted-install-cli[Installing the hosted control plane command line interface].
```suggestion
* The xref:../clusters/hosted_control_planes/hosted_install_cli.adoc#hosted-install-cli[Installing the hosted control plane command line interface].
```

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/configure_hosted_bm_ibmz.adoc
> +**Technology Preview:** Configuring the hosting cluster on 'x86' bare metal is in a Technology Preview status with limited support.
On line 4, how are we intending to format "x86"? Should it be in monospace, as it is in the heading? If so, replace the single quotation marks with back ticks.

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/configure_hosted_bm_ibmz.adoc
> +*Note:* IBM Z does not support ISO boot.
Instead of placing two admonitions side by side, I suggest moving "IBM Z does not support ISO boot." to be the first bullet in the "Important" list.

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/configure_hosted_bm_ibmz.adoc
> +You can convert a managed cluster to a hosting cluster by using the `hypershift` add-on to deploy the HyperShift Operator on that cluster. Then, you can start to create the hosted cluster.
Is the statement on line 10 still true? I thought that since the HyperShift feature is now enabled by default, you don't have to explicitly do anything with the add-on anymore.

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/configure_hosted_bm_ibmz.adoc
> +- To provision hosted control planes on bare metal, you can use the Agent platform. The Agent platform uses the Central Infrastructure Management (CIM) service to add worker nodes to a hosted cluster
```suggestion
- To provision hosted control planes on bare metal, you can use the Agent platform. The Agent platform uses the central infrastructure management service to add worker nodes to a hosted cluster. For an introduction to the central infrastructure management service, see link:https://github.com/openshift/assisted-service/blob/master/docs/hive-integration/kube-api-getting-started.md[Kube API - Getting Started Guide].
```

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/configure_hosted_bm_ibmz.adoc
> +- Each IBM Z system host must be started with the PXE images provided by the CIM. After each host starts, it runs an Agent process to discover the details of the host and completes the installation.
```suggestion
- Each IBM Z system host must be started with the PXE images provided by the central infrastructure management service. After each host starts, it runs an Agent process to discover the details of the host and completes the installation. An Agent custom resource represents each host.
```

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/configure_hosted_bm_ibmz.adoc
> +- When you create a hosted cluster with the Agent platform, HyperShift installs the Agent Cluster API provider in the hosted control plane namespace.
On line 22, what do you mean by "HyperShift"? Are you referring to the HyperShift Operator? If so, please use "HyperShift Operator". If you're referring to the hosted control planes feature, use "hosted control planes".

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/configure_hosted_bm_ibmz.adoc
> +[source,terminal]
```suggestion
[source,bash]
```
I believe the RHACM docs team uses `[source,bash]` instead of `[source,terminal]`. The OCP docs use `[source,terminal]` for most commands and `[source,bash]` for bash scripts.

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/configure_hosted_bm_ibmz.adoc
> +* You need to enable Central Infrastructure Management (CIM). For more information, see xref:../cluster_lifecycle/create_infra_env.adoc#enable-cim[Enabling the Central Infrastructure Management servi
```suggestion
* You need to enable the central infrastructure management service. For more information, see xref:../cluster_lifecycle/create_infra_env.adoc#enable-cim[Enabling the Central Infrastructure Management service].
```

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/configure_hosted_bm_ibmz.adoc
> +== Configuring hosted control planes on 'x86' bare metal for IBM Z compute nodes
```suggestion
== Next steps
```
Per recent conversations with @swopebe, we decided to standardize on the "Next steps" heading in cases like this, where we're including links to next steps.

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/hosted-bm-agents-ibmz.adoc
> +Boot KVM on IBM Z and z/VM with the downloaded PXE images from the 'InfraEnv' resource. After the Agents are created, the host communicates with the Assisted Service and registers in the same namespa
```suggestion
Start KVM on IBM Z and IBM z/VM with the downloaded PXE images from the `InfraEnv` resource. After the Agents are created, the host communicates with the Assisted Service and registers in the same namespace as the `InfraEnv` resource on the management cluster.
```
Do we need to spell out "KVM"? I'm not sure what it refers to, but perhaps it's a term that most IBM Z users are familiar with. Just wanted to check.

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/hosted-bm-agents-ibmz.adoc
> +[source,terminal]
```suggestion
[source,bash]
```

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/hosted-bm-agents-ibmz.adoc
> +- For KVM on IBM Z, perform the boot by running the following command:
```suggestion
- For KVM on IBM Z, run the following command:
```
IBM Style Word Usage lists both "perform" and "boot" as terms to avoid, if possible.

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/hosted-bm-agents-ibmz.adoc
> +- For IBM z/VM, perform the boot by using the following procedure:
```suggestion
- For IBM z/VM, start KVM by completing the following procedure:
```

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/hosted-bm-agents-ibmz.adoc
> +. Update the paramfile to add `rootfs url`, `net type` and `disk type`.
```suggestion
. Update the paramfile to add the `rootfs url`, `net type` and `disk type` values. 
```

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/hosted-bm-agents-ibmz.adoc
> +Following is the sample command for 'VSwitch' network with fcp singlepath/ dasd disk:
```suggestion
+
The following example shows a  sample command for the `VSwitch` network with a `fcp singlepath/ dasd` disk:
```

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/hosted-bm-agents-ibmz.adoc
> +[source,terminal]
```suggestion
[source,bash]
```

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/hosted-bm-agents-ibmz.adoc
> +Following is the sample command for 'OSA' & 'Hipersocket' network with fcp singlepath/dasd disk:
```suggestion
+
The following example is a sample command for the `OSA` and `Hipersocket` networks with a `fcp singlepath/dasd` disk:
```

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/hosted-bm-agents-ibmz.adoc
> +[source,terminal]
```suggestion
[source,bash]
```

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/hosted-bm-agents-ibmz.adoc
> +Following is the sample command for 'ROCE' network with fcp singlepath/ dasdc disk:
```suggestion
+
The following example is a sample command for the `ROCE` network with a `fcp singlepath/ dasdc` disk:
```

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/hosted-bm-agents-ibmz.adoc
> +[source,terminal]
```suggestion
[source,bash]
```

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/hosted-bm-agents-ibmz.adoc
> +. Punch 'initrd',  kernel images and paramfile to guest VM by running following commands:
```suggestion
. Punch `initrd`,  kernel images, and the paramfile to the guest VM by running the following commands:
```
IBM Style warns against using terms that might be associated with violence, such as "punch". Can we change this line to something like this? "Move `initrd`, kernel images, and the paramfile to the guest VM by running the following commands:"

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/hosted-bm-agents-ibmz.adoc
> +[source,terminal]
```suggestion
[source,bash]
```

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/hosted-bm-agents-ibmz.adoc
> +
Is line 57 left blank intentionally?

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/hosted-bm-agents-ibmz.adoc
> +. Run the following command from the guest VM console to perform the boot.
```suggestion
. Run the following command from the guest VM console to start KVM:
```

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/hosted-bm-agents-ibmz.adoc
> +[source,terminal]
```suggestion
[source,bash]
```

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/hosted-bm-agents-ibmz.adoc
> ++
Add a blank line above the + to ensure proper formatting.

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/hosted-bm-agents-ibmz.adoc
> +[source,terminal]
```suggestion
[source,bash]
```

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/hosted-bm-agents-ibmz.adoc
> +oc -n ${HOSTED_CONTROL_PLANE_NAMESPACE} get agents
```suggestion
oc -n <hosted_control_plane_namespace> get agents
```

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/hosted-bm-agents-ibmz.adoc
> +.Example output
Add a blank line between the `----` on line 71 and `.Example output` on line 72 to ensure proper formatting.

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/hosted-bm-agents-ibmz.adoc
> +[source,terminal]
```suggestion
[source,bash]
```

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
I'm not sure why this file is included in this PR. I suspect it might have been included accidentally, as `configure_hosted_aws.adoc` and `configure.hosted.bm.adoc` were. I think we should remove this from the PR.

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/managing_hosted_bm_ibmz.adoc
> +
This seems to be a copy of the `managing_hosted_bm.adoc` file, only without any follow-on tasks. I agree with @swopebe that this file can be removed from this PR.

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/hosted-bm-agents-ibmz.adoc
> +
Is line 79 left blank intentionally?

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/hosted-bm-agents-ibmz.adoc
> +
Something strange is happening with the formatting starting around line 82. I'm happy to troubleshoot it after we can get some of the other comments resolved, as it will be easier for me to investigate then.

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/hosted-bm-agents-ibmz.adoc
> ++
Add a blank line between the step on line 84 and the + on line 85.

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/hosted-bm-agents-ibmz.adoc
> +[source,terminal]
```suggestion
[source,bash]
```

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/hosted-bm-agents-ibmz.adoc
> +oc -n ${HOSTED_CONTROL_PLANE_NAMESPACE} patch agent 50c23cda-cedc-9bbd-bcf1-9b3a5c75804d -p '{"spec":{"installation_disk_id":"/dev/sda","approved":true,"hostname":"worker-zvm-0.hostedn.example.com"}}
```suggestion
oc -n <hosted_control_plane_namespace> patch agent 50c23cda-cedc-9bbd-bcf1-9b3a5c75804d -p '{"spec":{"installation_disk_id":"/dev/sda","approved":true,"hostname":"worker-zvm-0.hostedn.example.com"}}' --type merge
```

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/hosted-bm-agents-ibmz.adoc
> +[source,terminal]
```suggestion
[source,bash]
```

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/hosted-bm-agents-ibmz.adoc
> ++
Add a blank line between lines 91 and 92 to ensure proper formatting.

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/hosted-bm-agents-ibmz.adoc
> +oc -n ${HOSTED_CONTROL_PLANE_NAMESPACE} get agents
```suggestion
oc -n <hosted_control_plane_namespace> get agents
```

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/hosted-bm-agents-ibmz.adoc
> +.Example output
Add a blank line between lines 96 and 97 to ensure proper formatting.

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/hosted-bm-agents-ibmz.adoc
> +[source,terminal]
```suggestion
[source,bash]
```

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/hosted-bm-agents-ibmz.adoc
> +. For IBM z/VM, an additional step is required to edit the agent patched in the last step and update installer 'args' under 'spec' section as follows:
```suggestion
. For IBM z/VM, edit the agent that you patched in the previous step and update the `installerArgs` setting in the `spec` section as follows:
```

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/hosted-bm-agents-ibmz.adoc
> +- For network types as VSwitch/ OSA & Hipersocket:
```suggestion
- For network types such as `VSwitch`, `OSA`, and `Hipersocket`, enter the following command:
```

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/hosted-bm-agents-ibmz.adoc
> +[source,terminal]
```suggestion
[source,bash]
```

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/hosted-bm-agents-ibmz.adoc
> +- For network type as ROCE:
```suggestion
- For network types such as `ROCE`, enter the following command:
```

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/hosted-bm-agents-ibmz.adoc
> +[source,terminal]
```suggestion
[source,bash]
```

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/hosted_infraenv_ibmz.adoc
> +oc -n ${HOSTED_CONTROL_PLANE_NAMESPACE} get InfraEnv ${HOSTED_CLUSTER_NAME} -o json
```suggestion
oc -n <hosted_control_plane_namespace> get InfraEnv <hosted_cluster_name> -o json
```

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/scaling_nodepool_hosted_ibmz.adoc
> +The NodePool object is created when creating a hosted cluster. By scaling the NodePool object, you can add more compute nodes to the Hosted Control Plane.
```suggestion
The `NodePool` object is created when you create a hosted cluster. By scaling the `NodePool` object, you can add more compute nodes to the hosted control plane.
```

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/scaling_nodepool_hosted_ibmz.adoc
> +. Run the following command to scale the NodePool object to two nodes:
```suggestion
. Run the following command to scale the `NodePool` object to two nodes:
```

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/scaling_nodepool_hosted_ibmz.adoc
> +[source,terminal]
```suggestion
[source,bash]
```

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/scaling_nodepool_hosted_ibmz.adoc
> +oc -n $<CLUSTERS_NAMESPACE> scale nodepool $<NODEPOOL_NAME> --replicas 2
```suggestion
oc -n <clusters_namespace> scale nodepool <nodepool_name> --replicas 2
```

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/scaling_nodepool_hosted_ibmz.adoc
> +The Cluster API agent provider randomly picks two agents that are then assigned to the hosted cluster. Those agents go through different states and finally join the hosted cluster as {ocp-short} node
```suggestion
The Cluster API agent provider randomly picks two agents that are then assigned to the hosted cluster. Those agents go through different states and finally join the hosted cluster as {ocp-short} nodes. The agents pass through the transition phases in the following order:
```

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/scaling_nodepool_hosted_ibmz.adoc
> ++
Add a blank line between lines 23 and 24 to ensure proper formatting.

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/scaling_nodepool_hosted_ibmz.adoc
> +[source,terminal]
```suggestion
[source,bash]
```

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/scaling_nodepool_hosted_ibmz.adoc
> +c -n ${HOSTED_CONTROL_PLANE_NAMESPACE} get agent -o jsonpath='{range .items[*]}BMH: {@.metadata.labels.agent-install\.openshift\.io/bmh} Agent: {@.metadata.name} State: {@.status.debugInfo.state}{"\n
```suggestion
oc -n <hosted_control_plane_namespace> get agent -o jsonpath='{range .items[*]}BMH: {@.metadata.labels.agent-install\.openshift\.io/bmh} Agent: {@.metadata.name} State: {@.status.debugInfo.state}{"\n"}{end}'
```

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/scaling_nodepool_hosted_ibmz.adoc
> +[source,terminal]
```suggestion
[source,bash]
```

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/scaling_nodepool_hosted_ibmz.adoc
> +[source,terminal]
```suggestion
[source,bash]
```

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/scaling_nodepool_hosted_ibmz.adoc
> +oc -n ${HOSTED_CONTROL_PLANE_NAMESPACE} get agent
```suggestion
oc -n <hosted_control_plane_namespace> get agent
```

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/scaling_nodepool_hosted_ibmz.adoc
> +[source,terminal]
```suggestion
[source,bash]
```

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/scaling_nodepool_hosted_ibmz.adoc
> +. Run the following command to generate the kubeconfig to access the hosted cluster.
```suggestion
. Run the following command to generate the `kubeconfig` file to access the hosted cluster:
```

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/scaling_nodepool_hosted_ibmz.adoc
> +[source,terminal]
```suggestion
[source,bash]
```

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/scaling_nodepool_hosted_ibmz.adoc
> +hypershift create kubeconfig --namespace ${CLUSTERS_NAMESPACE} --name ${HOSTED_CLUSTER_NAME} > ${HOSTED_CLUSTER_NAME}.kubeconfig
```suggestion
hypershift create kubeconfig --namespace <clusters_namespace> --name <hosted_cluster_namespace> > <hosted_cluster_name>.kubeconfig
```
Please check with your engineering contact to confirm that `hypershift create` is the correct command. In the bare metal and kubevirt docs, we no longer refer to the `hypershift` CLI commands and instead refer to the `hcp` CLI commands.

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/scaling_nodepool_hosted_ibmz.adoc
> +[source,terminal]
```suggestion
[source,bash]
```

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/scaling_nodepool_hosted_ibmz.adoc
> +oc --kubeconfig ${HOSTED_CLUSTER_NAME}.kubeconfig get nodes
```suggestion
oc --kubeconfig <hosted_cluster_name>.kubeconfig get nodes
```

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/scaling_nodepool_hosted_ibmz.adoc
> +[source,terminal]
```suggestion
[source,bash]
```

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/scaling_nodepool_hosted_ibmz.adoc
> +[source,terminal]
```suggestion
[source,bash]
```

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/scaling_nodepool_hosted_ibmz.adoc
> +oc -n ${HOSTED_CONTROL_PLANE_NAMESPACE} get machine.cluster.x-k8s.io
```suggestion
oc -n <hosted_control_plane_namespace> get machine.cluster.x-k8s.io
```

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/scaling_nodepool_hosted_ibmz.adoc
> +[source,terminal]
```suggestion
[source,bash]
```

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/scaling_nodepool_hosted_ibmz.adoc
> +[source,terminal]
```suggestion
[source,bash]
```

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/scaling_nodepool_hosted_ibmz.adoc
> +oc --kubeconfig ${HOSTED_CLUSTER_NAME}.kubeconfig get clusterversion,co
```suggestion
oc --kubeconfig <hosted_cluster_name>.kubeconfig get clusterversion,co
```

2023-11-09 01:34 UTC, lahinson commented on clusters/hosted_control_planes/scaling_nodepool_hosted_ibmz.adoc
> +[source,terminal]
```suggestion
[source,bash]
```

2023-11-09 08:59 UTC, krishnanshruthi commented on clusters/hosted_control_planes/configure_hosted_bm_ibmz.adoc
> +*Note:* IBM Z does not support ISO boot.
Done

2023-11-09 09:00 UTC, krishnanshruthi commented on clusters/hosted_control_planes/configure_hosted_bm_ibmz.adoc
> +- To provision hosted control planes on bare metal, you can use the Agent platform. The Agent platform uses the Central Infrastructure Management (CIM) service to add worker nodes to a hosted cluster
Done

2023-11-09 09:01 UTC, krishnanshruthi commented on clusters/hosted_control_planes/configure_hosted_bm_ibmz.adoc
> +- Each IBM Z system host must be started with the PXE images provided by the CIM. After each host starts, it runs an Agent process to discover the details of the host and completes the installation.
Done

2023-11-09 09:02 UTC, krishnanshruthi commented on clusters/hosted_control_planes/configure_hosted_bm_ibmz.adoc
> +[source,terminal]
Noted

2023-11-09 09:02 UTC, krishnanshruthi commented on clusters/hosted_control_planes/configure_hosted_bm_ibmz.adoc
> +* You need to enable Central Infrastructure Management (CIM). For more information, see xref:../cluster_lifecycle/create_infra_env.adoc#enable-cim[Enabling the Central Infrastructure Management servi
Done

2023-11-09 09:03 UTC, krishnanshruthi commented on clusters/hosted_control_planes/configure_hosted_bm_ibmz.adoc
> +== Configuring hosted control planes on 'x86' bare metal for IBM Z compute nodes
Done

2023-11-09 09:05 UTC, krishnanshruthi commented on clusters/hosted_control_planes/hosted-bm-agents-ibmz.adoc
> +Boot KVM on IBM Z and z/VM with the downloaded PXE images from the 'InfraEnv' resource. After the Agents are created, the host communicates with the Assisted Service and registers in the same namespa
Checked with team -z/VM and KVM are pretty familiar terms apparently. So, dont need to expand

2023-11-09 09:08 UTC, krishnanshruthi commented on clusters/hosted_control_planes/hosted-bm-agents-ibmz.adoc
> +- For IBM z/VM, perform the boot by using the following procedure:
Done

2023-11-09 09:17 UTC, krishnanshruthi commented on clusters/hosted_control_planes/hosted_infraenv_ibmz.adoc
> +oc -n ${HOSTED_CONTROL_PLANE_NAMESPACE} get InfraEnv ${HOSTED_CLUSTER_NAME} -o json
Done

2023-11-10 14:22 UTC, krishnanshruthi commented
Follow the new PR https://github.com/stolostron/rhacm-docs/pull/5792 for further updates. Closing this PR.
cc: @SNiemann15

2023-11-10 14:22 UTC, closed without merging

2023-11-10 14:22 UTC, krishnanshruthi commented
Follow the new PR https://github.com/stolostron/rhacm-docs/pull/5792 for further updates. Closing this PR.
cc: @SNiemann15