https://issues.redhat.com/browse/ACM-7816 Add CIM CLI docs
open-cluster-management/rhacm-docs pull request #5683
Opened 2023-10-20 13:22 UTC by oafischer

2023-10-22 08:40 UTC, filanov commented
/assign @avishayt

2023-10-22 08:56 UTC, filanov commented on clusters/cluster_lifecycle/cim_create_cli.adoc
> +- <<create-host-inventory-cli,Creating a host inventory>>
are you referring to `create-host-inventory-cli-steps`?

2023-10-22 08:56 UTC, filanov commented on clusters/cluster_lifecycle/cim_create_cli.adoc
> +<1> Use the same name for your namespace and your infrastructure environment to be able to monitor your inventory in the console.
it's optional, we don't require it anywhere

2023-10-22 08:56 UTC, filanov commented on clusters/cluster_lifecycle/cim_create_cli.adoc
> +<15> The version of the Red Hat CoreOS image to use for your `InfraEnv`. Make sure the version refers to the OS image specified in the `AgentServiceConfig`, and that `OSImageVersion` matches an {ocp-
AgentServiceConfig.spec.osImages

2023-10-22 08:56 UTC, filanov commented on clusters/cluster_lifecycle/cim_create_cli.adoc
> +oc describe
```suggestion
oc describe infraenv myinfraenv -n <your_namespace>
```

2023-10-22 08:56 UTC, filanov commented on clusters/cluster_lifecycle/cim_create_cli.adoc
> +See the following list of notable properties:
@nmagnezi please correct me if i'm wrong but if i remember correctly if the infra env has a cluster reference it will not be created until the cluster exists.

2023-10-22 09:26 UTC, avishayt commented on clusters/cluster_lifecycle/cim_create_cli.adoc
> +<1> Use the same name for your namespace and your infrastructure environment to be able to monitor your inventory in the console.
It is required by the console (UI) because that is how the console creates the resources.  Otherwise you won't be able to use the console for this InfraEnv.

2023-10-22 09:26 UTC, avishayt commented on clusters/cluster_lifecycle/cim_create_cli.adoc
> +    httpProxy: <http://user:password@ipaddr:port> <2>
You missed httpsProxy
```suggestion
    httpProxy: <http://user:password@ipaddr:port> <2>
    httpsProxy: <http://user:password@ipaddr:port> <3>
```

2023-10-22 09:26 UTC, avishayt commented on clusters/cluster_lifecycle/cim_create_cli.adoc
> +<8> Consolidates advanced network configuration such as static IPs, bridges, and bonds for the hosts. Each host network configuration is specified in an `NMStateConfig` resource with labels you choos
Sorry, my mistake - we no longer require each host to have a separate NMStateConfig.

```suggestion
<8> Consolidates advanced network configuration such as static IPs, bridges, and bonds for the hosts. The host network configuration is specified in one or more `NMStateConfig` resources with labels you choose. The `nmStateConfigLabelSelector` property is a Kubernetes label selector that matches your chosen labels. The network configuration for all `NMStateConfig` labels that match this label selector is included in the Discovery Image.  When you boot, each host compares each configuration to its network interfaces and applies the appropriate configuration. See link to section _Configuring advanced networking for a host inventory_. to learn more about advanced network configuration.
```

2023-10-22 09:26 UTC, avishayt commented on clusters/cluster_lifecycle/cim_create_cli.adoc
> +<10> Modifies the ignition configuration of the Red Hat CoreOS live image, such as adding files. Make sure to only use `ignitionConfigOverride` if you need it. Must use version 3.1.0, regardless of t
```suggestion
<10> Modifies the ignition configuration of the Red Hat CoreOS live image, such as adding files. Make sure to only use `ignitionConfigOverride` if you need it. Must use ignition version 3.1.0, regardless of the cluster version.
```

2023-10-22 09:26 UTC, avishayt commented on clusters/cluster_lifecycle/cim_create_cli.adoc
> +See the following list of notable properties:
You mean that you apply the InfraEnv yaml but it doesn't show up in 'oc describe'?  If it isn't created then we won't reconcile

2023-10-23 08:21 UTC, oafischer commented on clusters/cluster_lifecycle/cim_create_cli.adoc
> +- <<create-host-inventory-cli,Creating a host inventory>>
Good catch, fixing it

2023-10-23 08:25 UTC, oafischer commented on clusters/cluster_lifecycle/cim_create_cli.adoc
> +    httpProxy: <http://user:password@ipaddr:port> <2>
I thought https schemes were not supported at the moment?

2023-10-23 08:29 UTC, oafischer commented
Addressed most of the comments, let me know if there is anything else. Thanks!

2023-10-23 09:12 UTC, avishayt commented on clusters/cluster_lifecycle/cim_create_cli.adoc
> +    httpProxy: <http://user:password@ipaddr:port> <2>
Correct, that means you can't set the URL to "http**s**://user:password...", but the httpsProxy property is supported.  I know it's a bit confusing.

2023-10-23 09:14 UTC, oafischer commented on clusters/cluster_lifecycle/cim_create_cli.adoc
> +    httpProxy: <http://user:password@ipaddr:port> <2>
I see, I'll add it in that case, thanks for explaining.

2023-10-23 14:12 UTC, nmagnezi commented on clusters/cluster_lifecycle/cim_create_cli.adoc
> +See the following list of notable properties:
@filanov As a custom resource? IIRC, I think it will get created but will probably reflect some error in status.
meaning you will see it in `oc describe`

2023-10-24 05:37 UTC, avishayt commented on clusters/cluster_lifecycle/cim_create_cli.adoc
> +See the following list of notable properties:
If it can't find the clusterRef then it will be reflected in the conditions.

2023-10-24 05:37 UTC, avishayt commented
/lgtm

2023-10-24 10:06 UTC, oafischer commented
Just waiting on peer review now.

2023-10-24 10:49 UTC, oafischer commented
Ignore the linter, will be fixed in a separate PR.

2023-10-25 00:52 UTC, swopebe requested changes
see comments, not all require change.

2023-10-25 00:52 UTC, swopebe commented on clusters/cluster_lifecycle/cim_create_cli.adoc
> +You can create a host inventory (infrastructure environment) to discover physical or virtual machines that form your {ocp-short} clusters. Use the command line interface instead of the console for au
that form your clusters...I have not seen us describe anything like this. 

Create? Build?

For _an_ automated deployment?

2023-10-25 00:52 UTC, swopebe commented on clusters/cluster_lifecycle/cim_create_cli.adoc
> +
Since this list consists of sentence fragments and not complete sentences, I think we should remove the punctuation.

2023-10-25 00:52 UTC, swopebe commented on clusters/cluster_lifecycle/cim_create_cli.adoc
> +
I thought we were not adding this, we met and discussed not adding additional resources to this, but we can revisit.

2023-10-25 00:52 UTC, swopebe commented on clusters/cluster_lifecycle/cim_create_cli.adoc
> +- You have enabled the central infrastructure management service.
Enable the Central Infrastructure Management service. (We stay away from past tense most of the time, especially in prereqs.)

2023-10-25 00:52 UTC, swopebe commented on clusters/cluster_lifecycle/cim_create_cli.adoc
> +<1> Use the same name for your namespace and your infrastructure environment to be able to monitor your inventory in the console.
please eliminate _to be able_. It's just _environment to monitor your inventory in the console_.

2023-10-25 00:52 UTC, swopebe commented on clusters/cluster_lifecycle/cim_create_cli.adoc
> +<1> Add your pull secret.
since we call at that variable, we should also for namespace (line 66)

2023-10-25 00:52 UTC, swopebe commented on clusters/cluster_lifecycle/cim_create_cli.adoc
> ++
we have a format issue here, likely due to the note. I will mess with it for a min.

2023-10-25 00:52 UTC, swopebe commented on clusters/cluster_lifecycle/cim_create_cli.adoc
> +*Note:* If you modify the `InfraEnv` resource, make sure that the `InfraEnv` has created a new Discovery Image by looking at the `createdTime` property.  If you already booted hosts, boot them again
seems an extra space after property

2023-10-25 00:52 UTC, swopebe commented on clusters/cluster_lifecycle/cim_create_cli.adoc
> +- Return to <<create-host-inventory-console,Creating a host inventory by using the console>>
I don't know why some of us are adding the line to return. I don't see this in other doc but we can revisit.

2023-10-25 00:52 UTC, swopebe commented on clusters/cluster_lifecycle/cim_create_cli.adoc
> ++
The fix, put the note in the actual step as an independent clause with a comma. Format is fixed.

2023-10-25 06:22 UTC, avishayt commented on clusters/cluster_lifecycle/cim_create_cli.adoc
> +You can create a host inventory (infrastructure environment) to discover physical or virtual machines that form your {ocp-short} clusters. Use the command line interface instead of the console for au
Regarding "form": Maybe a better way to word it is "physical or virtual machines that make up your OCP clusters".  I intended to say that these machines are building blocks for clusters that they will create later.

Regarding automated deployment: I think it would be better to write "automated deployments" (plural)

2023-10-25 09:47 UTC, oafischer commented on clusters/cluster_lifecycle/cim_create_cli.adoc
> +<1> Use the same name for your namespace and your infrastructure environment to be able to monitor your inventory in the console.
Fixed

2023-10-25 09:48 UTC, oafischer commented on clusters/cluster_lifecycle/cim_create_cli.adoc
> +You can create a host inventory (infrastructure environment) to discover physical or virtual machines that form your {ocp-short} clusters. Use the command line interface instead of the console for au
How does "that allow you to create your ocp clusters" sound?

2023-10-25 09:49 UTC, oafischer commented on clusters/cluster_lifecycle/cim_create_cli.adoc
> +
Fixed

2023-10-25 09:50 UTC, oafischer commented on clusters/cluster_lifecycle/cim_create_cli.adoc
> +
I might have missed that meeting, what was the discussion about? Are we returning to using inline links?

2023-10-25 09:57 UTC, oafischer commented on clusters/cluster_lifecycle/cim_create_cli.adoc
> +<1> Add your pull secret.
Done

2023-10-25 09:58 UTC, oafischer commented on clusters/cluster_lifecycle/cim_create_cli.adoc
> +*Note:* If you modify the `InfraEnv` resource, make sure that the `InfraEnv` has created a new Discovery Image by looking at the `createdTime` property.  If you already booted hosts, boot them again
Good catch, fixed!

2023-10-25 10:01 UTC, oafischer commented on clusters/cluster_lifecycle/cim_create_cli.adoc
> +- Return to <<create-host-inventory-console,Creating a host inventory by using the console>>
We can discuss again, I think the idea is that with minimal inline links, the user might need to scroll down to additional resources to find the information they need, and then they likely want to return back to closer to the beginning of the topic where they left off.

But I don't mind removing this.

2023-10-25 10:15 UTC, avishayt commented on clusters/cluster_lifecycle/cim_create_cli.adoc
> +You can create a host inventory (infrastructure environment) to discover physical or virtual machines that form your {ocp-short} clusters. Use the command line interface instead of the console for au
Less good, in my opinion.  My goal for this sentence is to explain what this inventory is used for upfront.  Maybe we can say it is an inventory of hosts that will later become OpenShift nodes.  Or hosts that they will install OpenShift on.  I'm not sure which option is best.

2023-10-25 11:03 UTC, oafischer commented on clusters/cluster_lifecycle/cim_create_cli.adoc
> +You can create a host inventory (infrastructure environment) to discover physical or virtual machines that form your {ocp-short} clusters. Use the command line interface instead of the console for au
Maybe:

You can create a host inventory (infrastructure environment) to discover physical or virtual machines that you can install your {ocp-short} clusters on.

Is that OK?

2023-10-25 12:32 UTC, avishayt commented on clusters/cluster_lifecycle/cim_create_cli.adoc
> +You can create a host inventory (infrastructure environment) to discover physical or virtual machines that form your {ocp-short} clusters. Use the command line interface instead of the console for au
Works for me

2023-10-26 13:32 UTC, dockerymick approved these changes
Made some suggestions and there are some broken links.

2023-10-26 13:32 UTC, dockerymick commented on clusters/cluster_lifecycle/cim_create_cli.adoc
> +
Yea, we agreed to not list Additional resources, however we are still documenting Additional resources . I also recommend that you remove the inline links for the sections. 

Remove: - <<create-host-inventory-prereqs-cli,Prerequisites>>
- <<create-host-inventory-cli-steps,Creating a host inventory>>

2023-10-26 13:32 UTC, dockerymick commented on clusters/cluster_lifecycle/cim_create_cli.adoc
> +== Prerequisites
remove the "s" since there is only one requirement.

2023-10-26 13:32 UTC, dockerymick commented on clusters/cluster_lifecycle/cim_create_cli.adoc
> +- Enable the central infrastructure management service.
```suggestion
- You must enable the central infrastructure management service. See [add link reference]
```

2023-10-26 13:32 UTC, dockerymick commented on clusters/cluster_lifecycle/cim_create_cli.adoc
> +Your host inventory is created. To verify the status, run the following command:
I would add this as a step

```suggestion
.. To verify that your host inventory is created, check the status with the following command:
```

2023-10-26 13:32 UTC, dockerymick commented on clusters/cluster_lifecycle/cim_create_cli.adoc
> +- See xref:cim_enable.adoc#enable-cim[Enabling the central infrastructure management service].
The link works according to the link check too, but suggesting to update link syntax. 
```suggestion
- See xref:../cluster_lifecycle/cim_enable.adoc#enable-cim[Enabling the central infrastructure management service].
```

2023-10-26 13:32 UTC, dockerymick commented on clusters/cluster_lifecycle/cim_create_cli.adoc
> +- See xref:cim_adv_config.adoc#cim-configure-networking[Configuring advanced networking for a host inventory].
Broken link
```suggestion
- See xref:../cluster_lifecycle/cim_adv_config.adoc#cim-configure-networking[Configuring advanced networking for a host inventory].
```

2023-10-26 13:46 UTC, oafischer commented
Thanks for the reviews everyone, ready to merge since we need to move on with CIM content

2023-10-26 13:46 UTC, merged