https://issues.redhat.com/browse/ACM-8261#add-comment
open-cluster-management/rhacm-docs pull request #5684
Opened 2023-10-20 15:04 UTC by swopebe

2023-10-20 17:58 UTC, swopebe commented on observability/observability_enable.adoc
> +*Note:* Alert forwarding to the {product-title-short} hub cluster feature is only supported by managed clusters with {ocp} version 4.12. After you install {product-title-short} with observability ena
@berenss another weird one here--already outdated, so we need to specify anything here anymore?

2023-10-20 18:16 UTC, cadawson commented
Also added this to the issue:

If we remove "4.8 or later" and replace it with "4.12", aren't we limiting it only to version 4.12? What happens with 4.13 and 4.14? If it is specifically 4.12, then I think we should say that. I am not thinking we will support future versions, wouldn't we? Do we change that version after every release that goes EOL? It seems like a lot of work, but maybe I am missing something. 

I think updating the links themselves to not go to that version is a good move. I'm not sure we need to create more maintenance in the future by changing the text to a single version, though. Let me know if I am off base here.

2023-10-20 18:25 UTC, swopebe commented
That's why Scott said we should say at least 4.12. The main reason is that is what is tested and verified.

2023-10-23 16:16 UTC, cadawson requested changes
A couple of questions and link changes. Looks good, otherwise! Thank you!

2023-10-23 16:16 UTC, cadawson commented on clusters/cluster_lifecycle/import_cli.adoc
> +* The {ocp-short} CLI version 4.12 or later, to run `oc` commands. See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.13/html/cli_tools/openshift-cli-oc#cli-getting
Link to 4.12 maybe?

2023-10-23 16:16 UTC, cadawson commented on clusters/install_upgrade/upgrade_cluster_disconnected.adoc
> +* A deployed hub cluster that is running on {ocp} version 4.12 or later with restricted OLM configured. See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.13/html-s
Link to 4.12?

2023-10-23 16:16 UTC, cadawson commented on console/console_access.adoc
> +**Note:** Enable and disable the console. See link:../install/adv_config_install.adoc#advanced-config-hub[MultiClusterHub advanced] for information.
```suggestion
*Note:* To enable and disable the console, see link:../install/adv_config_install.adoc#advanced-config-hub[MultiClusterHub advanced] for information.
```

2023-10-23 16:16 UTC, cadawson commented on governance/compliance_operator_policy.adoc
> +The compliance operator policy is created as a Kubernetes configuration policy in {product-title-short}. {ocp-short} supports the compliance operator policy. For more information, see link:https://do
```suggestion
The compliance operator policy is created as a Kubernetes configuration policy in {product-title-short}. {ocp-short} supports the compliance operator policy. For more information, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html-single/security_and_compliance/index#compliance-operator-understanding[Managing the Compliance Operator] in the {ocp-short} documentation for more details.
```

2023-10-23 16:16 UTC, cadawson commented on governance/e8_scan_policy.adoc
> +The E8 scan policy is created as a Kubernetes configuration policy in {product-title-short}. {ocp-short} supports the E8 scan policy. For more information, see _Understanding the Compliance Operator_
```suggestion
The E8 scan policy is created as a Kubernetes configuration policy in {product-title-short}. {ocp-short} supports the E8 scan policy. For more information, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html-single/security_and_compliance/index#compliance-operator-understanding[Managing the Compliance Operator] in the {ocp-short} documentation for more details.
```

2023-10-23 16:16 UTC, cadawson commented on install/cluster_size.adoc
> +| See the link:https://docs.openshift.com/container-platform/4.12/installing/installing_aws/installing-aws-customizations.html#installing-aws-customizations[Amazon Web Services information in the {oc
```suggestion
| See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html/installing/installing-on-aws#installing-aws-customizations[Installing a cluster on AWS with customizations] in the {ocp-short} product documentation for more information.
```

2023-10-23 16:16 UTC, cadawson commented on install/cluster_size.adoc
> +| See the following link:https://docs.openshift.com/container-platform/4.12/installing/installing_azure/installing-azure-account.html[product documentation] for more details.
```suggestion
| See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html/installing/installing-on-azure#installing-azure-account[Configuring an Azure account] in the {ocp-short} documentation for more details.
```

2023-10-23 16:16 UTC, cadawson commented on install/install_disconnected.adoc
> +* A supported {ocp} version must be deployed in your environment, and you must be logged in with the command line interface (CLI). See the link:https://access.redhat.com/documentation/en-us/openshift
```suggestion
* A supported {ocp} version must be deployed in your environment, and you must be logged in with the command line interface (CLI). See the link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html/installing/index[{ocp-short} version 4.12 install documentation] for information on installing {ocp}. See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html/cli_tools/openshift-cli-oc[OpenShift CLI (oc)] for information about installing and configuring `oc` commands with the Red Hat OpenShift CLI.
```

2023-10-23 16:16 UTC, cadawson commented on install/upgrade_cluster_disconnected_policies.adoc
4.12 link?

2023-10-23 19:39 UTC, swopebe commented on clusters/install_upgrade/upgrade_cluster_disconnected.adoc
> +* A deployed hub cluster that is running on {ocp} version 4.12 or later with restricted OLM configured. See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.13/html-s
I wasn't done yet

2023-10-23 19:40 UTC, swopebe commented on clusters/cluster_lifecycle/import_cli.adoc
> +* The {ocp-short} CLI version 4.12 or later, to run `oc` commands. See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.13/html/cli_tools/openshift-cli-oc#cli-getting
yes, in my commits.

2023-10-24 18:03 UTC, cadawson requested changes
Now that I have looked through this and seen what is there (and left comments), I will try to summarize my thoughts. 
First, thank you for doing this. It was a lot of files and changes. 
My thoughts:
1. I think the links themselves are good, as long as they don't break when we change them. If they all go to 4.12, that should work. I don't think I made any changes to those. 
2. Where I question it is when we are giving the earliest version that it works on. Customers can still be running 4.09, even though it is not supported. Here were my thoughts as I went through it:
- For the recent versions like 4.10-4.13, just change them back to their original values. They are still supported on those versions, and the likelihood is pretty high that someone is using it. 
- For the older versions like 4.5-4.8, can we confirm that no one is using the really old versions? If so, replace it with 4.10, or the earliest version that people are using. 
- Alternatively, we could say, "supported {ocp} versions later than 4.5" or something similar. Then we still link to 4.12.
- We can also indicate in the release notes that the documentation only applies to supported releases of OpenShift, and was tested on 4.12.
4. I like the 4.x.1 that you used in certain places. Those seem to work well in those examples.

Some of those might not be possible. Let me know if you have questions. 

CD: Update:
After further Slack discussion with Brandi and Scott, it sounds like the right people are on board with moving the versions up to 4.12. That plan works for me, since the potential risk is underrstood.

2023-10-24 18:03 UTC, cadawson commented on business_continuity/volsync/volsync.adoc
> +VolSync is a Kubernetes operator that enables asynchronous replication of persistent volumes within a cluster, or across clusters with storage types that are not otherwise compatible for replication.
Here is one that gives me pause. "VolSync can only replicate persistent volume claims on {ocp} clusters that are at version 4.12 or later." In this case, it does support 4.11, because it was after the original version of 4.8. It is true that 4.11 will go out of service shortly after 4.14 goes out, but people might still be using it with ACM 2.9.
I agree that we want to be pushing them forward, but I can also see the stragglers calling to say, "Doesn't this work on 4.11 clusters anymore?" But, maybe they wouldn't be looking in the 2.9 docs for it? That is the challenge that I see.

2023-10-24 18:03 UTC, cadawson commented on business_continuity/volsync/volsync_replicate.adoc
This one looks like it was not changed, and it covers the case that I raised. In that case, maybe the previous one was changed inadvertently, and we just change it back.

2023-10-24 18:03 UTC, cadawson commented on clusters/cluster_lifecycle/addon_managed_service.adoc
> +- {ocp} version 4.12 or later must be deployed in your environment, and you must be logged in with the command line interface (CLI).
Here is another one that might be changed back.

2023-10-24 18:03 UTC, cadawson commented on clusters/cluster_lifecycle/ansible_config_cluster.adoc
> +* {ocp-short} 4.12 or later
Another change back?

2023-10-24 18:03 UTC, cadawson commented on clusters/cluster_lifecycle/cim_enable.adoc
> +- You must have a deployed hub cluster on {ocp-short} 4.12 or later with the supported {product-title} version.
Another change back?

2023-10-24 18:03 UTC, cadawson commented on clusters/cluster_lifecycle/cim_enable.adoc
>  - See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html/images/managing-images#using-image-pull-secrets[Using image pull secrets].
Should this be 4.12?

2023-10-24 18:03 UTC, cadawson commented on clusters/cluster_lifecycle/create_cluster_on_prem.adoc
> +When you select an OpenShift version that is 4.12 or later, an option to select *Install {sno}* is displayed. A {sno} cluster contains a single node which hosts the control plane services and the use
Can you still select versions 4.9-4.11? If so, maybe change back?

2023-10-24 18:03 UTC, cadawson commented on clusters/cluster_lifecycle/create_single_node_ocp_clusterpool.adoc
> +. While you create your cluster pool, you must select {ocp-short} 4.12 or later in the _Release image_ field. If you enabled the feature gate, an option to select *Single node OpenShift* is displayed
I think the note covers this one, though is 4.9 still an available option? If not, maybe we remove the note.

2023-10-24 18:03 UTC, cadawson commented on clusters/cluster_lifecycle/create_vm.adoc
> +*Note:* Only release images for {ocp-short} versions 4.12 and later are supported.
Does this need to be changed lower, maybe 4.9? We don't want to encourage really early ones.

2023-10-24 18:03 UTC, cadawson commented on clusters/cluster_lifecycle/import_agent.adoc
> +* A deployed hub cluster. If you are importing bare metal clusters, the hub cluster must be installed on {ocp-short} version 4.12 or later.
Change back?

2023-10-24 18:03 UTC, cadawson commented on clusters/cluster_lifecycle/import_cli.adoc
> +* A deployed hub cluster. If you are importing bare metal clusters, the hub cluster must be installed on {ocp-short} version 4.12 or later.
There are a lot of these. Any way of knowing if there are people still using the old versions? Rather than update the version, it would be nice just to remove the condition, if it no longer applies.

2023-10-24 18:03 UTC, cadawson commented on clusters/cluster_lifecycle/import_cli.adoc
> +* The {ocp-short} CLI version 4.12 or later, to run `oc` commands. See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html/cli_tools/openshift-cli-oc#cli-getting
Any way of knowing if there are people still using the old versions? Rather than update the version, it would be nice just to remove the condition, if it no longer applies.

2023-10-24 18:03 UTC, cadawson commented on clusters/cluster_lifecycle/import_gui.adoc
> +* A deployed hub cluster. If you are importing bare metal clusters, the hub cluster must be installed on {ocp} version 4.12 or later.
Any way of knowing if there are people still using the old versions? Rather than update the version, it would be nice just to remove the condition, if it no longer applies.

2023-10-24 18:03 UTC, cadawson commented on clusters/cluster_lifecycle/release_images_specify.adoc
> +{ocp-short} 4.12 and later supports multiple architectures by default. You can use the following `clusterImageSet` to provision a cluster, replacing `4.x.0` with the current version:
Change back?

2023-10-24 18:03 UTC, cadawson commented on clusters/cluster_lifecycle/single_node_ocp.adoc
> +* A {mce-short} 2.4 or later, hub cluster that is running on {ocp} version 4.12 or later.
Change back?

2023-10-24 18:03 UTC, cadawson commented on clusters/credentials/credential_openstack.adoc
> +- Only {ocp-short} versions 4.12 and later, are supported.
Any way of knowing if there are people still using the old versions? Rather than update the version, it would be nice just to remove the condition, if it no longer applies.

2023-10-24 18:03 UTC, cadawson commented on clusters/credentials/credential_openstack.adoc
> +* A deployed hub cluster on {ocp-short} version 4.12 or later.
Any way of knowing if there are people still using the old versions? Rather than update the version, it would be nice just to remove the condition, if it no longer applies.

2023-10-24 18:03 UTC, cadawson commented on clusters/credentials/credential_virtualization.adoc
> +* A deployed hub cluster on {ocp-short} version 4.12 or later.
Any way of knowing if there are people still using the old versions? Rather than update the version, it would be nice just to remove the condition, if it no longer applies.

2023-10-24 18:03 UTC, cadawson commented on clusters/credentials/credential_vm.adoc
> +- Only {ocp-short} versions 4.12, and later, are supported.
Any way of knowing if there are people still using the old versions? Rather than update the version, it would be nice just to remove the condition, if it no longer applies.

2023-10-24 18:03 UTC, cadawson commented on clusters/credentials/credential_vm.adoc
> +* A deployed hub cluster on {ocp-short} version 4.12 or later.
Any way of knowing if there are people still using the old versions? Rather than update the version, it would be nice just to remove the condition, if it no longer applies.

2023-10-24 18:03 UTC, cadawson commented on clusters/install_upgrade/install_connected.adoc
> +* {ocp-short} 4.12 or later, must be deployed in your environment, and you must be logged into with the {ocp-short} CLI. See the following install documentation for {ocp-short}:
Any way of knowing if there are people still using the old versions? Rather than update the version, it would be nice just to remove the condition, if it no longer applies.

2023-10-24 18:03 UTC, cadawson commented on clusters/install_upgrade/install_disconnected.adoc
> +* {ocp} version 4.12 or later must be deployed in your environment, and you must be logged in with the command line interface (CLI).
Any way of knowing if there are people still using the old versions? Rather than update the version, it would be nice just to remove the condition, if it no longer applies.

2023-10-24 18:03 UTC, cadawson commented on clusters/install_upgrade/install_disconnected.adoc
> +*Note:* For managing bare metal clusters, you must have {ocp-short} version 4.12 or later.
Any way of knowing if there are people still using the old versions? Rather than update the version, it would be nice just to remove the condition, if it no longer applies.

2023-10-24 18:03 UTC, cadawson commented on clusters/install_upgrade/install_disconnected.adoc
> +* Your {ocp} CLI must be version 4.12 or later, and configured to run `oc` commands.
Any way of knowing if there are people still using the old versions? Rather than update the version, it would be nice just to remove the condition, if it no longer applies.

2023-10-24 18:03 UTC, cadawson commented on clusters/install_upgrade/upgrade_cluster_disconnected.adoc
> +* A deployed hub cluster that is running on {ocp} version 4.12 or later with restricted OLM configured. See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html-s
Any way of knowing if there are people still using the old versions? Rather than update the version, it would be nice just to remove the condition, if it no longer applies.

2023-10-24 18:03 UTC, cadawson commented on governance/ansible_grc.adoc
> +* {ocp} 4.12 or later
Any way of knowing if there are people still using the old versions? Rather than update the version, it would be nice just to remove the condition, if it no longer applies.

2023-10-24 18:03 UTC, cadawson commented on install/install_connected.adoc
> +* {ocp-short} version 4.12 or later must be deployed in your environment, and you must be logged into with the {ocp-short} CLI. See the following install documentation for {ocp-short} and change to e
Change back?

2023-10-24 18:03 UTC, cadawson commented on install/master.html
>  See the <a href="https://docs.openshift.com/container-platform/4.3/welcome/index.html">OpenShift version 4.3 documentation</a> or <a href="https://docs.openshift.com/container-platform/4.4/welcome/in
Change this link to 4.12.

2023-10-24 18:03 UTC, cadawson commented on install/master.html
>  See <a href="https://docs.openshift.com/container-platform/4.3/cli_reference/openshift_cli/getting-started-cli.html">Getting started with the CLI</a> for information about installing and configuring
Change this link to 4.12

2023-10-24 18:03 UTC, cadawson commented on install/master.html
>  See the <a href="https://docs.openshift.com/container-platform/4.3/welcome/index.html">OpenShift version 4.3 documentation</a> or <a href="https://docs.openshift.com/container-platform/4.4/welcome/in
Change this link to 4.12

2023-10-24 18:03 UTC, cadawson commented on install/master.html
>  See <a href="https://docs.openshift.com/container-platform/4.3/cli_reference/openshift_cli/getting-started-cli.html">Getting started with the CLI</a> for information about installing and configuring
Change this link to 4.12

2023-10-24 18:03 UTC, cadawson commented on install/upgrade_cluster_disconnected_policies.adoc
> +* A deployed hub cluster that is running on {ocp} version 4.12 or later with restricted OLM configured. See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html-s
Any way of knowing if there are people still using the old versions? Rather than update the version, it would be nice just to remove the condition, if it no longer applies.

2023-10-24 18:03 UTC, cadawson commented on networking/master.html
>  See the <a href="https://docs.openshift.com/container-platform/4.3/welcome/index.html">OpenShift version 4.3 documentation</a> or <a href="https://docs.openshift.com/container-platform/4.4/welcome/in
Change link to 4.12

2023-10-24 18:03 UTC, cadawson commented on networking/master.html
>  See <a href="https://docs.openshift.com/container-platform/4.3/cli_reference/openshift_cli/getting-started-cli.html">Getting started with the CLI</a> for information about installing and configuring
Change link to 4.12

2023-10-24 18:03 UTC, cadawson commented on networking/master.html
>  See the <a href="https://docs.openshift.com/container-platform/4.3/welcome/index.html">OpenShift version 4.3 documentation</a> or <a href="https://docs.openshift.com/container-platform/4.4/welcome/in
Change link to 4.12

2023-10-24 18:03 UTC, cadawson commented on networking/master.html
>  See <a href="https://docs.openshift.com/container-platform/4.3/cli_reference/openshift_cli/getting-started-cli.html">Getting started with the CLI</a> for information about installing and configuring
Change link to 4.12

2023-10-24 18:03 UTC, cadawson commented on observability/observability_enable.adoc
> +*Note:* Alert forwarding to the {product-title-short} hub cluster feature is only supported by managed clusters with {ocp} version 4.12 or later. After you install {product-title-short} with observab
Any way of knowing if there are people still using the old versions? Rather than update the version, it would be nice just to remove the condition, if it no longer applies.

2023-10-24 18:33 UTC, swopebe commented on business_continuity/volsync/volsync.adoc
> +VolSync is a Kubernetes operator that enables asynchronous replication of persistent volumes within a cluster, or across clusters with storage types that are not otherwise compatible for replication.
This is treated the same as others, because we cannot keep putting in our doc all the possibilities, @cadawson -- we have to make our lives simpler. I have gotten 4-5 bugs just for this type of stuff. I know it is a different way of thinking. The idea is (and kinda should have always been) that in 2.9 doc, we are moving forward with 4.12. On many other cases, as scott said, the user can be on other versions. That's not uncommon, but we don't have to keep up with it in the doc. This pause can be the same for many instances.

2023-10-24 18:34 UTC, swopebe commented on clusters/cluster_lifecycle/addon_managed_service.adoc
> +- {ocp} version 4.12 or later must be deployed in your environment, and you must be logged in with the command line interface (CLI).
@cadawson we are saying for 2.9 and we want the user to have 4.12 or later. I am not sure what the question is on this one?

2023-10-24 18:35 UTC, swopebe commented on clusters/cluster_lifecycle/cim_enable.adoc
>  - See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html/images/managing-images#using-image-pull-secrets[Using image pull secrets].
yes

2023-10-24 18:35 UTC, swopebe commented on clusters/cluster_lifecycle/create_single_node_ocp_clusterpool.adoc
> +. While you create your cluster pool, you must select {ocp-short} 4.12 or later in the _Release image_ field. If you enabled the feature gate, an option to select *Single node OpenShift* is displayed
we are saying 4.12 and later in the 2.9 doc.

2023-10-24 18:35 UTC, swopebe commented on clusters/cluster_lifecycle/import_agent.adoc
> +* A deployed hub cluster. If you are importing bare metal clusters, the hub cluster must be installed on {ocp-short} version 4.12 or later.
4.12 or later.

2023-10-24 18:38 UTC, swopebe commented on clusters/cluster_lifecycle/import_cli.adoc
> +* The {ocp-short} CLI version 4.12 or later, to run `oc` commands. See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html/cli_tools/openshift-cli-oc#cli-getting
People are on older versions. We are saying for 2.9 that we point to 4.12 across the board. That doesn't mean people are not on older versions. It means we are simplifying the doc and our job. :-)

2023-10-24 18:40 UTC, swopebe commented on clusters/cluster_lifecycle/create_vm.adoc
> +*Note:* Only release images for {ocp-short} versions 4.12 and later are supported.
1. Lower and higher should never be in the doc, it will come through as an accessibility violation potentially. 

I don't want to put 4.9, since we use 4.12 as a prereq, we can potentially remove this. I will check with Scott.

2023-10-24 18:41 UTC, swopebe commented on clusters/cluster_lifecycle/import_cli.adoc
> +* A deployed hub cluster. If you are importing bare metal clusters, the hub cluster must be installed on {ocp-short} version 4.12 or later.
This was a major change with this issue, yes, there are a lot. We need to say 4.12 or later. 2.9 is tested with 4.12.

2023-10-24 18:46 UTC, swopebe commented on networking/master.html
>  See the <a href="https://docs.openshift.com/container-platform/4.3/welcome/index.html">OpenShift version 4.3 documentation</a> or <a href="https://docs.openshift.com/container-platform/4.4/welcome/in
This is a master file that will correct itself.

2023-10-24 18:46 UTC, swopebe commented on networking/master.html
>  See <a href="https://docs.openshift.com/container-platform/4.3/cli_reference/openshift_cli/getting-started-cli.html">Getting started with the CLI</a> for information about installing and configuring
again, a master file

2023-10-24 18:46 UTC, swopebe commented on observability/observability_enable.adoc
> +*Note:* Alert forwarding to the {product-title-short} hub cluster feature is only supported by managed clusters with {ocp} version 4.12 or later. After you install {product-title-short} with observab
they are, pulling in @berenss

2023-10-24 18:55 UTC, swopebe commented on business_continuity/volsync/volsync.adoc
> +VolSync is a Kubernetes operator that enables asynchronous replication of persistent volumes within a cluster, or across clusters with storage types that are not otherwise compatible for replication.
It is a terrible idea to say 4.5 and link to later docs, I do not recommend that. These are going our of service anyway. We cannot keep documenting all possibilities.

2023-10-24 18:58 UTC, cadawson commented on business_continuity/volsync/volsync.adoc
> +VolSync is a Kubernetes operator that enables asynchronous replication of persistent volumes within a cluster, or across clusters with storage types that are not otherwise compatible for replication.
If we are saying 4.5 or later, then it should be fine to link to later docs. The 4.12 version is later than 4.5. Not terrible at all.

2023-10-24 19:11 UTC, swopebe commented on business_continuity/volsync/volsync.adoc
> +VolSync is a Kubernetes operator that enables asynchronous replication of persistent volumes within a cluster, or across clusters with storage types that are not otherwise compatible for replication.
disagree 

4.5 support ended already anyway: https://access.redhat.com/support/policy/updates/openshift#ocp4_phases

We don't need to cover all this in our docs. We can let go. :-)

2023-10-24 19:20 UTC, cadawson commented on clusters/cluster_lifecycle/addon_managed_service.adoc
> +- {ocp} version 4.12 or later must be deployed in your environment, and you must be logged in with the command line interface (CLI).
We want them to have 4.12 or later, but are we going to limit them to that? If we are willing to move that limit up, then I am ok with it. I wouldn't want to lose customers because they are still running on 4.11 and don't think this will work. Maybe that is not an issue. If not, I'm good with it.

2023-10-24 19:36 UTC, swopebe commented on clusters/cluster_lifecycle/addon_managed_service.adoc
> +- {ocp} version 4.12 or later must be deployed in your environment, and you must be logged in with the command line interface (CLI).
Scott Berens Slack:
would it be safe to say “at least version 4.12” - hence, this aligns with the support matrix (which covers 4.12 - 4.14, 4.15) and indicates the lowest level that we’re willing to accept at this version of DOC

2023-10-24 19:38 UTC, cadawson approved these changes
I will roll this over to an approval with suggestions, given our further discussion about the docs and customer potential issues (though they might be unlikely). Thanks for the clarification!

2023-10-24 19:42 UTC, swopebe commented on business_continuity/volsync/volsync.adoc
> +VolSync is a Kubernetes operator that enables asynchronous replication of persistent volumes within a cluster, or across clusters with storage types that are not otherwise compatible for replication.
This issue went into this discussion and we had open chats on this, as well. I also took into account OCP ELO versions that needed to be removed (4.5-4.10). Since 2.9 is not tested on 4.11, as you see in the conversations, we needed to start with what was tested. 

https://access.redhat.com/support/policy/updates/openshift#ocp4_phases

Some facts I would like us to start adopting as a team: What is the staged version tested on, what is EOL or has limited support. We can eliminate and include based on those two items, safely, with PM and Support looking to the support matrix for outliers when needed.

2023-10-24 20:08 UTC, swopebe commented on clusters/cluster_lifecycle/create_cluster_on_prem.adoc
> +When you select an OpenShift version that is 4.12 or later, an option to select *Install {sno}* is displayed. A {sno} cluster contains a single node which hosts the control plane services and the use
This  was written when it was new, I actually think we should remove the version all together. This has been out since 4.9 and 2.9 doc already is based on 4.12.

2023-10-24 20:24 UTC, swopebe commented on install/master.html
>  See <a href="https://docs.openshift.com/container-platform/4.3/cli_reference/openshift_cli/getting-started-cli.html">Getting started with the CLI</a> for information about installing and configuring
I think this changes automatically....I will build and check.

2023-10-24 20:38 UTC, merged