https://issues.redhat.com/browse/ACM-7770
open-cluster-management/rhacm-docs pull request #5691
Opened 2023-10-25 14:51 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-7770

2023-10-25 15:00 UTC, thuyn-581 approved these changes
lgtm

2023-10-25 17:51 UTC, dockerymick requested changes

2023-10-25 17:51 UTC, dockerymick commented on business_continuity/backup_restore/backup_install.adoc
> +*Warning:*
Based on the [Special tagging doc](https://github.com/stolostron/rhacm-docs/blob/gh-pages/_pages/wr_special_tag_guidance.md), i would change this to "Important"

2023-10-25 17:51 UTC, dockerymick commented on business_continuity/backup_restore/backup_install.adoc
> + * If you try to manually install the OADP  Operator on the hub cluster, your OADP Operator and Velero custom resource definition (CRD) versions must exactly match the `MultiClusterHub` OADP Operator
```suggestion
 * If you try to manually install the OADP Operator on the hub cluster, your OADP Operator and Velero custom resource definition versions must exactly match the `MultiClusterHub` OADP Operator and Velero custom resource definition versions. If these versions do not exactly match one another, you encounter problems. 
```

2023-10-25 17:51 UTC, dockerymick commented on business_continuity/backup_restore/backup_install.adoc
> + * CRDs are cluster-scoped, so you cannot have two different versions of an OADP Operator or Velero CRD installed on the same cluster. If you have two different versions, one version runs with the wr
It seems like this is similar to the first bullet point. Is the second bullet point suppose to be extra info to explain the requirement? 

would it be helpful to combine the statements?

"*Important:* If you manually install the OADP operator, the custom resource definition version of the OADP operator and Velereo must exactly match. If these versions do not exactly match one another, you encounter problems. If you have previously installed and used the OADP Operator on the hub cluster in a namespace different from the backup component namespace, uninstall this version.

2023-10-27 14:50 UTC, dockerymick reviewed
Left a suggestion

2023-10-27 14:50 UTC, dockerymick commented on business_continuity/backup_restore/backup_install.adoc
> +If you manually install the OADP operator, the custom resource definition version of the OADP operator and Velereo must exactly match. If these versions do not exactly match one another, you encounte
```suggestion
If you manually install the OADP operator, the custom resource definition version of the OADP operator and Velereo must exactly match. If these versions do not exactly match one another, you encounter problems. If you have previously installed and used the OADP Operator on the hub cluster in a namespace different from the backup component namespace, uninstall this version.
```

2023-10-27 15:55 UTC, dockerymick approved these changes

2023-10-27 18:28 UTC, merged