https://issues.redhat.com/browse/ACM-8258
open-cluster-management/rhacm-docs pull request #5705
Opened 2023-10-27 13:53 UTC by jc-berger

For 2.9. 

See Jira: https://issues.redhat.com/browse/ACM-8258

2023-10-27 15:15 UTC, dockerymick requested changes

2023-10-27 15:15 UTC, dockerymick commented on governance/policy_ctrl_adv_config.adoc
> +*Note:* Reducing the volume of debug logs can make issues more difficult to debug.
I recommend that this note be removed. It seems like this should be known issue. What issues might the use encounter? @JustinKuli

2023-10-27 15:49 UTC, JustinKuli commented on governance/policy_ctrl_adv_config.adoc
> +*Note:* Reducing the volume of debug logs can make issues more difficult to debug.
I wouldn't call it a "known issue" - it feels different to me than what we have in that section. This is just a risk that the user should be aware of, but it is a natural consequence of this configuration. When configuring the log level, the user is making a decision between being able to debug issues more accurately (higher level) or not having too many logs cluttering up their system (lower level).

In my mind, it fits in the same category of the user configuring the `evaluationInterval` for a policy; by increasing the time between evaluations, they may save some CPU cycles, but they should understand that their compliance history is less accurate (the cluster might be noncompliant for longer before the policy notices). Both are natural trade-offs.

I think usually the user will not be debugging problems themselves by digging through their logs. But if their log level is too low when they have a problem, they would just need to re-configure it, and recreate whatever problem they previously had.

2023-10-27 15:51 UTC, JustinKuli commented on governance/policy_ctrl_adv_config.adoc
> +When you configure and collect debug logs for each policy controller, the default log level might take up more space than you want. In {product-title-short} 2.9, you can reduce the volume of debug lo
This leads with the new feature, but I think it could be more general. Something like "The default log level might cause fewer or more logs than you want. In {product-title-short} 2.9, you can either increase or reduce the volume of debug logs from the default setting."

2023-10-27 15:53 UTC, JustinKuli commented on governance/policy_ctrl_adv_config.adoc
> +You can reduce the debug logs emitted by the policy controllers to be `error-only`. To reduce the debug logs, set the debug log value to `-1` in the annotation.
"error-only" isn't a name/code/setting thing, so I would prefer it isn't formatted like that.
```suggestion
You can reduce the debug logs emitted by the policy controllers to just be when an error occurs. To reduce the debug logs, set the debug log value to `-1` in the annotation. 
```

2023-10-27 17:51 UTC, dockerymick requested changes

2023-10-27 17:51 UTC, dockerymick commented on governance/policy_ctrl_adv_config.adoc
> +*Note:* Reducing the volume of debug logs can make issues more difficult to debug.
@JustinKuli thanks for explaining that. So it seems like users would only know if the log level is too low through trial and error? 

```suggestion
*Note:* Reducing the volume of debug logs means there is less information displayed from the logs.
```

2023-10-27 17:51 UTC, dockerymick commented on governance/policy_ctrl_adv_config.adoc
> +You can reduce the debug logs emitted by the policy controllers to be `error-only`. To reduce the debug logs, set the debug log value to `-1` in the annotation.
Whats the log level range? so far i see [-1 to 2]

-1: error-only logs
0: informative messages
1: first level of debugging information
2: second level of debugging information

Would it be helpful to list what the values represent? 

```suggestion
You can reduce the debug logs emitted by the policy controllers to be display error-only bugs in the logs. To reduce the debug logs, set the debug log value to `-1` in the annotation. 
```

2023-10-27 17:51 UTC, dockerymick commented on governance/policy_ctrl_adv_config.adoc
> +When you configure and collect debug logs for each policy controller, the default log level might take up more space than you want. In {product-title-short} 2.9, you can reduce the volume of debug lo
Remember to update the What's new - Governance topic: "You can now increase or reduce the volume of debug logs from the default settings. For more details, see Configure debug log"

```suggestion
When you configure and collect debug logs for each policy controller, you can adjust the log level. 
```

2023-10-30 13:26 UTC, JustinKuli commented on governance/policy_ctrl_adv_config.adoc
> +*Note:* Reducing the volume of debug logs can make issues more difficult to debug.
Yes.

2023-10-30 13:29 UTC, JustinKuli commented on governance/policy_ctrl_adv_config.adoc
> +You can reduce the debug logs emitted by the policy controllers to be `error-only`. To reduce the debug logs, set the debug log value to `-1` in the annotation.
I'd call them:
-1: error logs only
0: informative logs
1: debug logs
2: verbose debugging logs

I don't think we directly write any logs at a higher level than that, although the user could specify a higher value, and some libraries we use might emit more logs.

2023-11-01 19:00 UTC, dockerymick approved these changes
One more suggestion. Otherwise, this looks good!

2023-11-01 19:00 UTC, dockerymick commented on governance/policy_ctrl_adv_config.adoc
> +- `2`: verbose debugging logs.
I like that you were consistent with the punctuation! However, I recommend that you remove periods since these are complete sentences.

2023-11-02 13:43 UTC, JustinKuli approved these changes
LGTM

2023-11-02 18:20 UTC, merged