IBM Power documentation for HCP
open-cluster-management/rhacm-docs pull request #5712
Opened 2023-10-27 15:03 UTC by alishaIBM

2023-10-28 02:36 UTC, mkumatag requested changes

2023-10-28 02:36 UTC, mkumatag commented on clusters/hosted_control_planes/hosted-bm-agents-ibmpower.adoc
> +[#hosted-bare-metal-adding-agents-metal3-ibmpower]
we don't support the metal3 on power, lets remove all the references for this option

2023-10-30 11:32 UTC, alishaIBM commented on clusters/hosted_control_planes/hosted-bm-agents-ibmpower.adoc
> +[#hosted-bare-metal-adding-agents-metal3-ibmpower]
Okay. Removed all the metal3 references.

2023-11-14 12:01 UTC, mkumatag commented
/cc swopebe lahinson

2023-11-14 12:05 UTC, mkumatag commented
@swopebe @lahinson this PR contains the similar content for power platform, ptal

2023-11-16 17:33 UTC, lahinson requested changes
I added a few comments and suggestions.

2023-11-16 17:33 UTC, lahinson commented on clusters/hosted_control_planes/config_dns_ibmpower.adoc
> += Configure DNS for hosted control plane with IBM Power
```suggestion
= Configuring DNS for hosted control planes on IBM Power
```

2023-11-16 17:33 UTC, lahinson commented on clusters/hosted_control_planes/config_dns_ibmpower.adoc
> +The API Server for the hosted cluster is exposed. A DNS entry must exist for the `api.<hosted_cluster_name>.<base-domain>` that points to the destination where the API server is reachable.
```suggestion
The API server for the hosted cluster is exposed. A DNS entry must exist for the `api.<hosted_cluster_name>.<base-domain>` entry that points to the destination where the API server is reachable.
```

2023-11-16 17:33 UTC, lahinson commented on clusters/hosted_control_planes/config_dns_ibmpower.adoc
> +The entry can also point to a load balancer that is deployed to redirect incoming traffic to the Ingress pods.
```suggestion
The entry can also point to a load balancer that is deployed to redirect incoming traffic to the ingress pods.
```
The term "ingress" needs to be capitalized only in reference to the Ingress object.

2023-11-16 17:33 UTC, lahinson commented on clusters/hosted_control_planes/configure_hosted_bm_ibmpower.adoc
Per conversations with @swopebe during the work on the IBM Z docs, it might be best to rename this file to something that indicates that it's the intro file for the IBM Power docs. Maybe something like, `hosted_ibmpower_intro.adoc`?

2023-11-16 17:33 UTC, lahinson commented on clusters/hosted_control_planes/configure_hosted_bm_ibmpower.adoc
> += Configuring the hosting cluster on 'x86' OCP cluster to create hosted control plane with IBM Power compute nodes (Technology Preview)
```suggestion
= Configuring the hosting cluster on a 64-bit x86 OpenShift Container Platform cluster to create hosted control planes for IBM Power compute nodes (Technology Preview)
```
Per the [Supplementary Style Guide](https://redhat-documentation.github.io/supplementary-style-guide/#bit-64-x86), I believe this reference to x86 should be `64-bit x86`.

2023-11-16 17:33 UTC, lahinson commented on clusters/hosted_control_planes/configure_hosted_bm_ibmpower.adoc
> +**Technology Preview:** Configuring the hosting cluster on `x86` bare metal for IBM Power (`ppc64le`) compute nodes is in a Technology Preview status with limited support.
```suggestion
**Technology Preview:** Configuring the hosting cluster on 64-bit x86 bare metal for IBM Power (`ppc64le`) compute nodes is a Technology Preview feature.
```
For Technology Preview features, we are not supposed to refer to any kind of support, even limited.

2023-11-16 17:33 UTC, lahinson commented on clusters/hosted_control_planes/configure_hosted_bm_ibmpower.adoc
> +You can enable a managed cluster to be a hosting cluster by using the `hypershift` add-on to deploy the HyperShift Operator on that cluster. Then, you can start to create the hosted cluster.
It appears that this text was copied from an older version of the bare metal docs. The statements on line 10 are no longer true. Please remove the text on line 10.

2023-11-16 17:33 UTC, lahinson commented on clusters/hosted_control_planes/configure_hosted_bm_ibmpower.adoc
> +- To provision hosted control planes on bare metal, you can use the Agent platform. The Agent platform uses the central infrastructure management (CIM) service to add worker nodes to a hosted cluster
```suggestion
- To provision hosted control planes on bare metal, you can use the Agent platform. The Agent platform uses the central infrastructure management service to add worker nodes to a hosted cluster. For an introduction to the central infrastructure management service, see xref:../cluster_lifecycle/cim_intro.adoc#cim-intro[Creating a host inventory].
```

2023-11-16 17:33 UTC, lahinson commented on clusters/hosted_control_planes/configure_hosted_bm_ibmpower.adoc
> +- When you create a hosted cluster with the Agent platform, HyperShift installs the Agent Cluster API provider in the hosted control plane namespace.
Note to self: Line 20 contains an unclear reference to "HyperShift", and it seems to be a copy-paste from the configuring bare metal file. I will check with development to get some clarity on what they meant by "HyperShift" and will plan to update the bare metal file and this one.

2023-11-16 17:33 UTC, lahinson commented on clusters/hosted_control_planes/configure_hosted_bm_ibmpower.adoc
> +* DNS: The API and Ingress endpoints must be routable.
```suggestion
* DNS: The API and ingress endpoints must be routable.
```

2023-11-16 17:33 UTC, lahinson commented on clusters/hosted_control_planes/configure_hosted_bm_ibmpower.adoc
> +. xref:../hosted_control_planes/config_dns_bare-metal_ibmz.adoc#configuring-dns-hosted-control-plane-ibmpower[Configure DNS for Hosted Control Plane for IBM Power]
```suggestion
. xref:../hosted_control_planes/config_dns_bare-metal_ibmz.adoc#configuring-dns-hosted-control-plane-ibmpower[Configuring DNS for hosted control planes on IBM Power]
```

2023-11-16 17:33 UTC, lahinson commented on clusters/hosted_control_planes/configure_hosted_bm_ibmpower.adoc
> +. xref:../hosted_control_planes/hosted_infraenv_ibmz.adoc#hosted-control-planes-create-infraenv-ibmpower[Creating an InfraEnv resource for hosted control planes on x86 bare metal for IBM Power comput
```suggestion
. xref:../hosted_control_planes/hosted_infraenv_ibmz.adoc#hosted-control-planes-create-infraenv-ibmpower[Creating an InfraEnv resource for hosted control planes on 64-bit x86 bare metal for IBM Power compute nodes]
```

2023-11-16 17:33 UTC, lahinson commented on clusters/hosted_control_planes/hosted-bm-agents-ibmpower.adoc
> +oc -n ${HOSTED_CONTROL_PLANE_NAMESPACE} get agents
```suggestion
oc -n <hosted-control-plane-namespace> get agents
```

2023-11-16 17:33 UTC, lahinson commented on clusters/hosted_control_planes/hosted-bm-agents-ibmpower.adoc
> +oc -n ${HOSTED_CONTROL_PLANE_NAMESPACE} patch agent 86f7ac75-4fc4-4b36-8130-40fa12602218 -p '{"spec":{"installation_disk_id":"/dev/sda","approved":true,"hostname":"worker-0.example.krnl.es"}}' --type
```suggestion
oc -n <hosted-control-plane-namespace> patch agent 86f7ac75-4fc4-4b36-8130-40fa12602218 -p '{"spec":{"installation_disk_id":"/dev/sda","approved":true,"hostname":"worker-0.example.krnl.es"}}' --type merge
```

2023-11-16 17:33 UTC, lahinson commented on clusters/hosted_control_planes/hosted-bm-agents-ibmpower.adoc
> +oc -n ${HOSTED_CONTROL_PLANE_NAMESPACE} patch agent 23d0c614-2caa-43f5-b7d3-0b3564688baa -p '{"spec":{"installation_disk_id":"/dev/sda","approved":true,"hostname":"worker-1.example.krnl.es"}}' --type
```suggestion
oc -n <hosted-control-plane-namespace> patch agent 23d0c614-2caa-43f5-b7d3-0b3564688baa -p '{"spec":{"installation_disk_id":"/dev/sda","approved":true,"hostname":"worker-1.example.krnl.es"}}' --type merge
```

2023-11-16 17:33 UTC, lahinson commented on clusters/hosted_control_planes/hosted-bm-agents-ibmpower.adoc
> +oc -n ${HOSTED_CONTROL_PLANE_NAMESPACE} get agents
```suggestion
oc -n <hosted-control-plane-namespace> get agents
```

2023-11-16 17:33 UTC, lahinson commented on clusters/hosted_control_planes/hosted_infraenv_ibmpower.adoc
> += Creating an InfraEnv resource for hosted control planes on x86 bare metal for IBM Power compute nodes
```suggestion
= Creating an InfraEnv resource for hosted control planes on 64-bit x86 bare metal for IBM Power compute nodes
```

2023-11-16 17:33 UTC, lahinson commented on clusters/hosted_control_planes/hosted_infraenv_ibmpower.adoc
> +See the following procedure to create an `InfraEnv` resource:
```suggestion
To create an `InfraEnv` resource, complete the following steps:
```

2023-11-16 17:33 UTC, lahinson commented on clusters/hosted_control_planes/hosted_infraenv_ibmpower.adoc
> +. Create a YAML file to contain the configuration: See the following example:
```suggestion
. Create a YAML file to contain the configuration. See the following example:
```

2023-11-16 17:33 UTC, lahinson commented on clusters/hosted_control_planes/managing_hosted_bm_ibmpower.adoc
> += Managing the hosted control plane clusters on x86 bare metal to attach IBM Power compute nodes (Technology Preview)
```suggestion
= Managing hosted control plane clusters on 64-bit x86 bare metal to attach to IBM Power compute nodes (Technology Preview)
```

2023-11-16 17:33 UTC, lahinson commented on clusters/hosted_control_planes/managing_hosted_bm_ibmpower.adoc
> +You must configure hosted control planes for bare metal before you can create hosted control plane clusters. See xref:..//hosted_control_planes/configure_hosted_bm_ibmpower.adoc#configuring-hosting-s
```suggestion
You must configure hosted control planes for bare metal before you can create hosted control plane clusters. For more information, see xref:../hosted_control_planes/configure_hosted_bm_ibmpower.adoc#configuring-hosting-service-cluster-configure-ibmpower[Configuring the hosting cluster on a 64-bit x86 OpenShift Container Platform cluster to create hosted control planes for IBM Power compute nodes (Technology Preview)].
```

2023-11-16 17:33 UTC, lahinson commented on clusters/hosted_control_planes/managing_hosted_bm_ibmpower.adoc
> +You can use the {mce} to create and manage a Red Hat {ocp-short} hosted cluster. Hosted control planes are available as a Technology Preview on bare metal with IBM Power.
```suggestion
You can use the {mce-short} to create and manage an {ocp-short} hosted cluster. Hosted control planes are available as a Technology Preview on bare metal with IBM Power.
```

2023-11-16 17:33 UTC, lahinson commented on clusters/hosted_control_planes/managing_hosted_bm_ibmpower.adoc
> +
I don't think that the link in the Additional resources section applies to the IBM Power docs, so I would remove the Additional resources section from this file.

2023-11-16 17:33 UTC, lahinson commented on clusters/hosted_control_planes/managing_hosted_bm_ibmpower.adoc
After the Prerequisites section in this file, add a Next steps section with a link to the `scaling_nodepool_hosted_ibmpower.adoc` file.

2023-11-16 17:33 UTC, lahinson commented on clusters/hosted_control_planes/scaling_nodepool_hosted_ibmpower.adoc
> +. Run the following command to check the `clusterversion` and cluster operator status:
```suggestion
. Run the following command to check the cluster version and cluster operator status:
```
Check with @SNiemann15 about whether we need to add an additional command here to check the cluster operator status. See https://github.com/stolostron/rhacm-docs/pull/5857.

2023-11-16 17:33 UTC, lahinson commented on clusters/hosted_control_planes/scaling_nodepool_hosted_ibmpower.adoc
> ++
The output in the following code block likely needs to be divided into two separate code blocks. @SNiemann15 is familiar with the discussion about the formatting here.

2023-11-16 17:33 UTC, lahinson commented on clusters/hosted_control_planes/scaling_nodepool_hosted_ibmpower.adoc
After this content is merged, if some of the formatting looks incorrect on the staging build, see https://github.com/stolostron/rhacm-docs/pull/5857 for possible solutions.

2023-11-16 17:33 UTC, lahinson commented on clusters/hosted_control_planes/scaling_nodepool_hosted_ibmpower.adoc
> +Cluster Operators start to reconcile by adding workloads to the nodes.
The statement on line 91 could be clearer. The act of reconciliation requires at least two parties. What do the cluster Operators start to reconcile with? Each other? Something else?

2023-11-20 15:19 UTC, alishaIBM commented on clusters/hosted_control_planes/managing_hosted_bm_ibmpower.adoc
> +
Removed the Additional resources section.

2023-11-20 15:26 UTC, alishaIBM commented on clusters/hosted_control_planes/managing_hosted_bm_ibmpower.adoc
Added a Next steps section with a link to the scaling_nodepool_hosted_ibmpower.adoc file.

2023-11-21 00:57 UTC, swopebe commented on clusters/hosted_control_planes/configure_hosted_bm_ibmpower.adoc
@lahinson thanks for that. I think we pause on this for now until next week because we need to make sure the intro files are only files that have a description and contain the collection for that sections. 

example: https://github.com/stolostron/rhacm-docs/blob/2.9_stage/access_control/access_intro.adoc

I think we have lost that a bit in other areas of the doc.

2023-11-21 00:58 UTC, swopebe commented on clusters/hosted_control_planes/configure_hosted_bm_ibmpower.adoc
> +[#configuring-hosting-service-cluster-configure-ibmpower]
I am going to reduce these anchors and titles because when they are very long, it makes URLs and such more difficult. I will do this in VS code.

2023-11-21 00:59 UTC, swopebe commented on clusters/hosted_control_planes/configure_hosted_bm_ibmpower.adoc
> +
We prob can do away with saying twice that it is TP in this line; I will just say "with limited support"

2023-11-21 01:00 UTC, swopebe commented on clusters/hosted_control_planes/hosted-bm-agents-ibmpower.adoc
> +You can add agents by manually configuring the machine to start with the live ISO.
wonder if we should spell out ISO, at least first

2023-11-21 01:02 UTC, swopebe commented on clusters/hosted_control_planes/managing_hosted_bm_ibmpower.adoc
> +
Thinking line 14 is _Additional resources._

2023-11-21 01:04 UTC, swopebe commented on clusters/main.adoc
>  include::hosted_control_planes/managing_hosted_bm.adoc[leveloffset=+3]
Overall this is really good. Noting to reduce anchors and make titles concise if possible, clean up a few small items here and there. If time allows, I may create an intro file that will contain all the files listed from 118-123. Note also to make filenames consistent. 

I will resume this Tuesday, as GA resumes. (still not GA -- delayed!)

2023-11-21 16:40 UTC, alishaIBM commented on clusters/hosted_control_planes/hosted-bm-agents-ibmpower.adoc
> +You can add agents by manually configuring the machine to start with the live ISO.
You can add agents by manually configuring the machine to start with the live ISO (International Organization for Standardization) image.
@mkumatag could you confirm if above statement looks good ? Thanks.

2023-11-21 16:45 UTC, alishaIBM commented on clusters/hosted_control_planes/managing_hosted_bm_ibmpower.adoc
> +
@swopebe as per @lahinson 's comment [here](https://github.com/stolostron/rhacm-docs/pull/5712#discussion_r1396088555) have added a Next steps section with a link to the `scaling_nodepool_hosted_ibmpower.adoc` file.
Request you to check once and let me know if we still need an update here. Thanks.

2023-11-21 16:48 UTC, alishaIBM commented on clusters/hosted_control_planes/configure_hosted_bm_ibmpower.adoc
> +
@swopebe can you please confirm if below statement looks good ?

`**Technology Preview:** Configuring the hosting cluster on 64-bit x86 bare metal for IBM Power (`ppc64le`) compute nodes has limited support.`

2023-11-21 16:51 UTC, alishaIBM commented on clusters/hosted_control_planes/scaling_nodepool_hosted_ibmpower.adoc
> +Cluster Operators start to reconcile by adding workloads to the nodes.
@mkumatag request your input/thoughts on above comment.

2023-11-21 17:29 UTC, mkumatag commented on clusters/hosted_control_planes/hosted-bm-agents-ibmpower.adoc
> +You can add agents by manually configuring the machine to start with the live ISO.
I feel ISO is enough, its pretty standard term is been used in the industry. e.g: https://github.com/stolostron/rhacm-docs/blob/f1e66593fa1a1fac449e2b53e186ebfad163a14c/clusters/hosted_control_planes/hosted_bare_metal_agents.adoc?plain=1#L4

2023-11-21 17:36 UTC, mkumatag commented on clusters/hosted_control_planes/scaling_nodepool_hosted_ibmpower.adoc
> +Cluster Operators start to reconcile by adding workloads to the nodes.
we don't need this statement here, we can just remove this from here to avoid any confusion.

2023-11-23 09:58 UTC, alishaIBM commented on clusters/hosted_control_planes/scaling_nodepool_hosted_ibmpower.adoc
> +Cluster Operators start to reconcile by adding workloads to the nodes.
Agree. Thank you.

2023-11-23 17:34 UTC, swopebe commented on clusters/hosted_control_planes/configure_hosted_bm_ibmpower.adoc
> +
Looks great!

2023-11-23 17:36 UTC, swopebe commented on clusters/hosted_control_planes/hosted-bm-agents-ibmpower.adoc
> +You can add agents by manually configuring the machine to start with the live ISO.
Per IBM Style manual, RH Style manual, we are discouraged from using acronyms without defining it, but if it is as common as, say, CPU, then it's fine.

2023-11-23 17:41 UTC, swopebe commented on clusters/hosted_control_planes/managing_hosted_bm_ibmpower.adoc
> +
I will update if needed. Next steps are required for the topic, Additional resources are links for more information, something we added to reduce in-line links. I asked for next steps because we have full tasks with links as steps. Hypershift is the only guide that is doing that. 

The compromise was "Next steps" for required links to complete the task, but it should not be used for follow on tasks or information. We need to make sure we look at the rest of the RHACM doc to see how we are using Additional resources.


I think because this book has multiple contributors now, it is going a different direction than the rest of RHACM. I plan to discuss this as a team on Monday, but for now, we can leave it here.

2023-11-23 17:44 UTC, swopebe commented on clusters/hosted_control_planes/configure_hosted_bm_ibmpower.adoc
> +[#configuring-hosting-service-cluster-configure-ibmpower]
changed to: `[#config-hosting-cluster-ibmpower]`. -- we have to change in any URLs.

2023-11-23 17:50 UTC, swopebe commented on clusters/hosted_control_planes/hosted-bm-agents-ibmpower.adoc
> +== Manually adding agents
We have an extra header and section for adding **manually** but that is the only task I see here. If the whole topic about adding manually, we do not need to specify because there is no other way mentioned in the topic, the original title would be "manually" and we can reduce it to just one task/header.

2023-11-23 17:53 UTC, swopebe commented on clusters/hosted_control_planes/config_hosted_bm_ibmpower.adoc
> +== Next steps
Here we have next steps under a header. I think we can revisit this.

2023-11-23 17:58 UTC, swopebe commented on clusters/hosted_control_planes/config_hosted_bm_ibmpower.adoc
> +== Next steps
Also, there is an issue here. We are pointing in next steps that are IBM z topics. This is an IBM Power task; that might be a mistake so I won't mess with it and let you guys change.

2023-11-27 13:31 UTC, alishaIBM commented on clusters/hosted_control_planes/config_hosted_bm_ibmpower.adoc
> +== Next steps
@swopebe agree.
One link is incorrect.
It should be:
```
. xref:../hosted_control_planes/config_dns_ibmpower.adoc#configuring-dns-hosted-control-plane-ibmpower[Configuring DNS for hosted control planes on IBM Power]
```

2023-11-27 13:41 UTC, SNiemann15 commented on clusters/hosted_control_planes/config_hosted_bm_ibmpower.adoc
> +. xref:../hosted_control_planes/hosted_infraenv_ibmz.adoc#hosted-control-planes-create-infraenv-ibmpower[Creating an InfraEnv resource for hosted control planes on 64-bit x86 bare metal for IBM Power
```suggestion
. xref:../hosted_control_planes/hosted_infraenv_ibmpower.adoc#hosted-control-planes-create-infraenv-ibmpower[Creating an InfraEnv resource for hosted control planes on 64-bit x86 bare metal for IBM Power compute nodes]
```

2023-11-27 13:44 UTC, SNiemann15 commented on clusters/hosted_control_planes/hosted_infraenv_ibmpower.adoc
> +  pullSecretRef:
```suggestion
spec:
  cpuArchitecture: ppc64le
  pullSecretRef:
```

2023-11-27 13:46 UTC, SNiemann15 commented on clusters/hosted_control_planes/scale_nodepool_hosted_ibmpower.adoc
> +hosted-forwarder-79558597ff-5tbqp   hosted-forwarder-crqq5   worker-zvm-0.hostedn.example.com   agent://50c23cda-cedc-9bbd-bcf1-9b3a5c75804d   Running   41h   4.14.0-ec.2
```suggestion
hosted-forwarder-79558597ff-5tbqp   hosted-forwarder-crqq5   worker-zvm-0.hostedn.example.com   agent://50c23cda-cedc-9bbd-bcf1-9b3a5c75804d   Running   41h   4.14.0
```

2023-11-27 13:46 UTC, SNiemann15 commented on clusters/hosted_control_planes/scale_nodepool_hosted_ibmpower.adoc
> +hosted-forwarder-79558597ff-lfjfk   hosted-forwarder-crqq5   worker-zvm-1.hostedn.example.com   agent://5e498cd3-542c-e54f-0c58-ed43e28b568a   Running   41h   4.14.0-ec.2
```suggestion
hosted-forwarder-79558597ff-lfjfk   hosted-forwarder-crqq5   worker-zvm-1.hostedn.example.com   agent://5e498cd3-542c-e54f-0c58-ed43e28b568a   Running   41h   4.14.0
```

2023-11-27 13:47 UTC, SNiemann15 commented on clusters/hosted_control_planes/scale_nodepool_hosted_ibmpower.adoc
> +oc --kubeconfig <hosted_control_plane_names>.kubeconfig get clusterversion,co
```suggestion
oc --kubeconfig <hosted_cluster_name>.kubeconfig get clusterversion,co
```

2023-11-27 13:49 UTC, SNiemann15 commented on clusters/hosted_control_planes/scale_nodepool_hosted_ibmpower.adoc
> +clusterversion.config.openshift.io/version   4.14.0-ec.2   True        False         40h     Cluster version is 4.14.0-ec.2
```suggestion
clusterversion.config.openshift.io/version   4.14.0   True        False         40h     Cluster version is 4.14.0
```
Remove `-ec.2` in the entire example

2023-11-27 16:57 UTC, alishaIBM commented on clusters/hosted_control_planes/config_hosted_bm_ibmpower.adoc
> +== Next steps
Updated with the correct link.  Hence, resolving the conversation. Thanks.

2023-11-27 17:01 UTC, alishaIBM commented on clusters/hosted_control_planes/configure_hosted_bm_ibmpower.adoc
> +
Updated.

2023-11-27 17:29 UTC, alishaIBM commented on clusters/hosted_control_planes/hosted-bm-agents-ibmpower.adoc
> +== Manually adding agents
Agree. Updated the PR. Thus, resolving the comment. Thanks.

2023-11-27 21:43 UTC, swopebe commented on clusters/hosted_control_planes/configure_hosted_bm_ibmpower.adoc
I will make an intro in a separate PR after we merge this one, as we discussed this as a team and we need to keep the source easy-to-find. We also discussed shorter filenames as a team and shorter identities in header titles, as this will make building the URLs easier.

2023-11-27 21:45 UTC, swopebe commented on clusters/hosted_control_planes/managing_hosted_bm_ibmpower.adoc
> +
@lahinson we discussed so much but I forget to get to this. I think this is additional resources rather than next steps....I think next steps might be a bit confusing.

2023-11-27 21:46 UTC, swopebe commented
I think we just have a couple small things to go over before we can merge this one.

2023-11-28 01:32 UTC, lahinson commented on clusters/hosted_control_planes/managing_hosted_bm_ibmpower.adoc
> +
@swopebe I might be misunderstanding what the intent is here, but I thought that after I read this topic, the next step was to complete the "Scaling the NodePool object for a hosted cluster on IBM Power" procedure. If that's not the intent, then I agree that the link should be listed as an additional resource instead of a next step.

2023-11-28 05:36 UTC, alishaIBM commented on clusters/hosted_control_planes/scaling_nodepool_hosted_ibmpower.adoc
> ++
Done.

2023-11-29 12:10 UTC, alishaIBM commented on clusters/hosted_control_planes/managing_hosted_bm_ibmpower.adoc
> +
@swopebe @lahinson updated it as shown below:
```
[#additional-resources-manage-bm-ibmpower]
=== Additional resources
```
Please let me know if it needs any further correction. Thanks.

2023-11-29 12:56 UTC, swopebe commented on clusters/hosted_control_planes/managing_hosted_bm_ibmpower.adoc
> +
I think that is great.

2023-11-29 14:38 UTC, swopebe approved these changes
I think we can merge.

2023-11-29 14:40 UTC, lahinson approved these changes

2023-11-29 14:58 UTC, merged