https://issues.redhat.com/browse/ACM-7151 Auto add hosts
open-cluster-management/rhacm-docs pull request #5730
Opened 2023-10-31 11:42 UTC by oafischer

2023-11-02 12:41 UTC, avishayt commented on clusters/cluster_lifecycle/cim_auto_add_host.adoc
> +<7> *Optional:* Select the installation disk. See for the available root device hints. After the host is booted with the Discovery Image and the corresponding agent resource is created, the installat
Missing reference here

2023-11-02 12:43 UTC, oafischer commented on clusters/cluster_lifecycle/cim_auto_add_host.adoc
> +<7> *Optional:* Select the installation disk. See for the available root device hints. After the host is booted with the Discovery Image and the corresponding agent resource is created, the installat
Do you have the link? I think I removed it because it was pointing to docs.openshift, which we cannot use. Forgot to make a note to update it.

2023-11-02 13:50 UTC, avishayt commented on clusters/cluster_lifecycle/cim_auto_add_host.adoc
> +<7> *Optional:* Select the installation disk. See for the available root device hints. After the host is booted with the Discovery Image and the corresponding agent resource is created, the installat
https://docs.openshift.com/container-platform/4.14/installing/installing_bare_metal_ipi/ipi-install-installation-workflow.html#root-device-hints_ipi-install-installation-workflow

2023-11-02 13:58 UTC, oafischer commented on clusters/cluster_lifecycle/cim_auto_add_host.adoc
> +<7> *Optional:* Select the installation disk. See for the available root device hints. After the host is booted with the Discovery Image and the corresponding agent resource is created, the installat
We cannot use docs.openshift.com, do you have a portal link? I searched for that topic on the portal but couldn't find it.

2023-11-02 14:13 UTC, avishayt commented on clusters/cluster_lifecycle/cim_auto_add_host.adoc
> +<7> *Optional:* Select the installation disk. See for the available root device hints. After the host is booted with the Discovery Image and the corresponding agent resource is created, the installat
Is this better?
https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html/post-installation_configuration/post-install-bare-metal-configuration

2023-11-02 14:15 UTC, oafischer commented on clusters/cluster_lifecycle/cim_auto_add_host.adoc
> +<7> *Optional:* Select the installation disk. See for the available root device hints. After the host is booted with the Discovery Image and the corresponding agent resource is created, the installat
Yes we can use that link, is that the topic we want to link to in this section?

2023-11-02 14:28 UTC, avishayt commented on clusters/cluster_lifecycle/cim_auto_add_host.adoc
> +<7> *Optional:* Select the installation disk. See for the available root device hints. After the host is booted with the Discovery Image and the corresponding agent resource is created, the installat
Yes, RootDeviceHints are described in Table 3.1. (BareMetalHost spec)

2023-11-02 14:32 UTC, oafischer commented on clusters/cluster_lifecycle/cim_auto_add_host.adoc
> +<7> *Optional:* Select the installation disk. See for the available root device hints. After the host is booted with the Discovery Image and the corresponding agent resource is created, the installat
Added, thanks for finding that!

2023-11-05 07:08 UTC, avishayt commented on clusters/hosted_control_planes/hosted_bare_metal_agents.adoc
> +*Important:* Because the `BareMetalHost` objects are created outside the baremetal-operator namespace, you must configure the Operator to watch all namespaces.
We can remove this file and point to 
* xref:../cluster_lifecycle/cim_add_host.adoc#add-host-host-inventory[Adding hosts to the host inventory by using the Discovery Image]
* xref:../cluster_lifecycle/cim_auto_add_host.adoc#auto_add-host-host-inventory[Automatically adding bare metal hosts to the host inventory]

2023-11-06 08:36 UTC, oafischer commented on clusters/hosted_control_planes/hosted_bare_metal_agents.adoc
> +*Important:* Because the `BareMetalHost` objects are created outside the baremetal-operator namespace, you must configure the Operator to watch all namespaces.
@lahinson

2023-11-06 15:10 UTC, lahinson commented on clusters/hosted_control_planes/hosted_bare_metal_agents.adoc
> +*Important:* Because the `BareMetalHost` objects are created outside the baremetal-operator namespace, you must configure the Operator to watch all namespaces.
@avishayt I opened the following PR to replace any other references to `hosted_bare_metal_agents.adoc` with the two files that you mentioned. When you can, PTAL. Thanks!

2023-11-06 18:03 UTC, dockerymick requested changes

2023-11-06 18:03 UTC, dockerymick commented on clusters/cluster_lifecycle/cim_auto_add_host.adoc
> +After creating your host inventory (infrastructure environment) you can discover your hosts and add them to your inventory. You can automate booting the Discovery Image of your infrastructure environ
Should baremetal-operator be monospaced? Is this a pod name? if not, I recommend changing it to read as "bare metal operator"

2023-11-06 18:03 UTC, dockerymick commented on clusters/hosted_control_planes/hosted_bare_metal_agents.adoc
>  +
```suggestion
+
[source,bash]
```

2023-11-06 18:03 UTC, dockerymick commented on clusters/support_troubleshooting/trouble_network_config_bm.adoc
> +. Create the `BareMetalHost` object of the node with the following annotation:
```suggestion
. Create the `BareMetalHost` object of the node with the following annotation: 
+
[source,bash]
```

2023-11-07 07:12 UTC, avishayt commented on clusters/hosted_control_planes/hosted_bare_metal_agents.adoc
> +*Important:* Because the `BareMetalHost` objects are created outside the baremetal-operator namespace, you must configure the Operator to watch all namespaces.
Excellent thanks!

2023-11-07 08:50 UTC, oafischer commented on clusters/cluster_lifecycle/cim_auto_add_host.adoc
> +After creating your host inventory (infrastructure environment) you can discover your hosts and add them to your inventory. You can automate booting the Discovery Image of your infrastructure environ
Updated

2023-11-07 09:08 UTC, avishayt commented
LGTM

2023-11-07 11:54 UTC, oafischer commented
Merging since all comments addressed

2023-11-07 11:55 UTC, merged