https://issues.redhat.com/browse/ACM-7118
open-cluster-management/rhacm-docs pull request #5748
Opened 2023-11-02 18:16 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-7118

2023-11-02 20:08 UTC, swopebe requested changes
I did a pass through the content and left a couple comments. If this is for observability, it will likely move, but since the content will stay the same, I started a review,

2023-11-02 20:08 UTC, swopebe commented on clusters/release_notes/known_issues.adoc
This is MCE doc, wondering why we are putting this here @dockerymick

2023-11-02 20:08 UTC, swopebe commented on clusters/cluster_lifecycle/specify_img_registry.adoc
> ++
When the YAML is bold in the PR, there is a format error. Typically it's a spacing error or a misplaced asterisks.

2023-11-02 20:08 UTC, swopebe commented on clusters/cluster_lifecycle/specify_img_registry.adoc
> +.Prerequisite
Can we switch line 158 to a header?

2023-11-02 20:08 UTC, swopebe commented on clusters/cluster_lifecycle/specify_img_registry.adoc
> ++
line 176 and 177 should simple be callouts within the YAML:

<1> Specify the same name for the HTTP and HTTPS. (_I erased the example because it is just repeating exactly what is in the YAML file_.)
<2> Include the IP address of the `kube-apiserver`. Run the following command on your managed cluster to get the IP address: `oc -n default describe svc kubernetes | grep IP:`.

The the next step:

**Step#**: Go to the `ManagedClusterAddOn`. (I think that should not be a step on it's own unless there is a task to go to it, _go to_ is not telling me much. How does one go to?)

Looking at the YAML, let's walk through like this:

1. In `AddOnDeploymentConfig`, add `spec.configs`, as displayed in the following example: (though this doesn't look right). 

Are we saying add `spec.proxyConfig` ? (That is what is in the YAML, so better to be specific)

With these situations, trying to walk through the steps to make sure they match the YAML can help prevent bugs and negative customer feedback.

2023-11-02 22:28 UTC, dockerymick commented on clusters/release_notes/known_issues.adoc
I made a mistake. It's understood that this should not be added to the MCE/Cluster lifecycle known issues. It should be added to the observability known issues.

2023-11-03 15:00 UTC, dockerymick commented on clusters/cluster_lifecycle/specify_img_registry.adoc
> +[#configure-proxy-settings-for-observability-add-ons]
Met earlier this morning and agreed that it is best to add this section to [Customizing observability](https://github.com/stolostron/rhacm-docs/blob/2.9_stage/observability/customize_observability.adoc#customizing-observability).

2023-11-03 15:02 UTC, dockerymick commented on clusters/cluster_lifecycle/specify_img_registry.adoc
> +[#configure-proxy-settings-for-observability-add-ons]
Is this action required or optional for the user? At what point will the user need to configure the proxy settings?

2023-11-03 16:30 UTC, jc-berger commented on clusters/release_notes/known_issues.adoc
Moved the location. Please see new commit and let me know if y'all have more thoughts on where the content ought to go.

2023-11-03 16:31 UTC, jc-berger commented on clusters/cluster_lifecycle/specify_img_registry.adoc
> ++
Thanks! MAde a new commit and directed SMEs to take a look to help clarify the YAMLs we're providing.

2023-11-03 17:23 UTC, dockerymick requested changes

2023-11-03 17:23 UTC, dockerymick commented on release_notes/known_issues_observability.adoc
> +//2.5.7118
```suggestion
//2.9:7118
```

2023-11-03 17:23 UTC, dockerymick commented on observability/customize_observability.adoc
> +- You have a hub cluster.
```suggestion

- You have a hub cluster. 
```

2023-11-03 17:23 UTC, dockerymick commented on observability/customize_observability.adoc
> +. Create an `AddOnDeploymentConfig` with the proxy settings by adding a `spec.proxy.Config`. View the following YAML example:
```suggestion
. Create an `AddOnDeploymentConfig` resource with the proxy settings by adding a `spec.proxyConfig` parameter. View the following YAML example:
```

2023-11-03 17:23 UTC, dockerymick commented on observability/customize_observability.adoc
> +[source,yaml]
Should these steps be a part of the YAML explanation or are the steps a part of the configuring procedure? 

```suggestion
<2> Include the IP address of the `kube-apiserver`. 

. To get the IP address, run following command on your managed cluster: 
+
[source,bash]
----
oc -n default describe svc kubernetes | grep IP:
----
 
. Go to the `ManagedClusterAddOn` resource and reference the `AddOnDeploymentConfig` you made by adding an item in `spec.configs`. View the following YAML example: 
+
[source,yaml]
```

2023-11-03 17:24 UTC, dockerymick commented on release_notes/known_issues_observability.adoc
> +=== Lack of support for proxy settings
```suggestion
== Lack of support for proxy settings
```

2023-11-06 08:41 UTC, elgnay commented on observability/customize_observability.adoc
> +<1> Specify the same name for the HTTP and HTTPS proxy.
> <1> Specify the same name for the HTTP and HTTPS proxy.

It not clear here. What I want to say here is you are able to specify either a HTTP proxy (http://<username>:<password>@<ip>:<port>) or a HTTPS proxy (https://<username>:<password>@<ip>:<port>) for this field.

2023-11-06 08:50 UTC, elgnay commented on observability/customize_observability.adoc
> +  namespace: <managed-cluster-name>
This is not the yaml of the sample `ManagedClusterAddOn`.

2023-11-06 08:53 UTC, elgnay commented on observability/customize_observability.adoc
> +If your development needs change, you might need to disable the Observability add-ons you configured for the hub cluster and managed cluster. You can disable the Observability add-on at any time. ,
Here we're going to disable the proxy settings for the Observability add-on, not to disable the add-on itself.

2023-11-06 08:57 UTC, elgnay commented on release_notes/known_issues_observability.adoc
> +The Prometheus `AdditionalAlertManagerConfig`` of the Observability add-on does not support proxy settings. You must disable the Observability alert forwarding feature.
I remember there is one more limitation for the proxy settings of the Observability add-on. In 2.9, https proxy with self-signed CA certificate is not supported. @subbarao-meduri Could you please provide a more precise description for this?

2023-11-07 15:16 UTC, jc-berger commented on release_notes/known_issues_observability.adoc
> +The Prometheus `AdditionalAlertManagerConfig`` of the Observability add-on does not support proxy settings. You must disable the Observability alert forwarding feature.
Thanks, Le! I've included extra content, specifying the additional 2.9 limitation. I'll stand by if @subbarao-meduri has more content for me to add.

2023-11-07 15:17 UTC, dockerymick commented on release_notes/known_issues_observability.adoc
> +The Prometheus `AdditionalAlertManagerConfig`` of the Observability add-on does not support proxy settings. You must disable the Observability alert forwarding feature.
```suggestion
The Prometheus `AdditionalAlertManagerConfig` of the Observability add-on does not support proxy settings. You must disable the Observability alert forwarding feature.
```

2023-11-08 09:11 UTC, elgnay commented on release_notes/known_issues_observability.adoc
> +In 2.9, the HTTPS proxy with a self-signed CA certificate is not supported.
> The HTTPS proxy with a self-signed CA certificate is not supported. 

It's the doc for 2.9 release, we might not need to highlight it here.

2023-11-08 09:14 UTC, elgnay commented on observability/customize_observability.adoc
> +<1> For this field, you can specify either a HTTP proxy, `http://:@:`, or a HTTPS proxy, `https://:@:`.
> <1> For this field, you can specify either a HTTP proxy, `http://:@:`, or a HTTPS proxy, `https://:@:`.

Change to

> <1> For this field, you can specify either a HTTP proxy or a HTTPS proxy.

2023-11-09 18:37 UTC, dockerymick requested changes

2023-11-09 18:37 UTC, dockerymick commented on clusters/cluster_lifecycle/specify_img_registry.adoc
> +. Copy and run the import commands on the managed cluster after the label `open-cluster-management.io/image-registry=myNamespace.myImageRegistry` is added to the managed cluster.
```suggestion
. Copy and run the import commands on the managed cluster after the `open-cluster-management.io/image-registry=myNamespace.myImageRegistry` label is added to the managed cluster.
```

2023-11-09 18:37 UTC, dockerymick commented on observability/customize_observability.adoc
> +Configure the proxy settings to allow the communications from the managed cluster to access the hub cluster through a HTTP and HTTPS proxy server. Typically, add-ons do not need any special configura
```suggestion
Configure the proxy settings to allow the communications from the managed cluster to access the hub cluster through a HTTP and HTTPS proxy server. Typically, add-ons do not need any special configuration to support HTTP and HTTPS proxy servers between a hub cluster and a managed cluster. But if you enabled the observability add-on, you must complete the proxy configuration. 
```

2023-11-09 18:37 UTC, dockerymick commented on observability/customize_observability.adoc
> +=== Prerequisite
```suggestion
== Prerequisite 
```

2023-11-09 18:37 UTC, dockerymick commented on observability/customize_observability.adoc
> +. Go to the cluster namespace on your hub cluster.
```suggestion
Complete the following steps to configure the proxy settings for the observability add-on:

. Go to the cluster namespace on your hub cluster. 
```

2023-11-09 18:37 UTC, dockerymick commented on observability/customize_observability.adoc
> +. Go to the `ManagedClusterAddOn` resource and reference the `AddOnDeploymentConfig` you made by adding an item in `spec.configs`. View the following YAML example:
```suggestion
. Go to the `ManagedClusterAddOn` resource and update it by referencing the `AddOnDeploymentConfig` resource that you made. View the following YAML example:

2023-11-09 18:37 UTC, dockerymick commented on observability/customize_observability.adoc
> +
How can the user verify that the proxy settings are configured correctly? Do they have to attempt to communicate to the hub cluster from the managed cluster ?

2023-11-09 18:37 UTC, dockerymick commented on observability/customize_observability.adoc
> +If your development needs change, you might need to disable the proxy setting for the observability add-ons you configured for the hub cluster and managed cluster. You can disable the proxy settings
```suggestion
If your development needs change, you might need to disable the proxy setting for the observability add-ons you configured for the hub cluster and managed cluster. You can disable the proxy settings for the observability add-on at any time. Complete the following steps:
```

2023-11-09 18:37 UTC, dockerymick commented on observability/customize_observability.adoc
> +. Go to the `ManagedClusterAddOn`.
```suggestion
. Go to the `ManagedClusterAddOn` resource.
```

2023-11-09 18:37 UTC, dockerymick commented on observability/customize_observability.adoc
> +    resource: addondeploymentconfigs
Should the resource match the `kind` of the configuration? 
```suggestion
    resource: AddonDeploymentConfig
```

2023-11-09 18:37 UTC, dockerymick commented on observability/customize_observability.adoc
> +. Remove the referenced `AddOnDeploymentConfig`.
Should the entire `config.group` be removed or only the `resource` contents?
```suggestion
. Remove the referenced `AddOnDeploymentConfig` resource.
```

2023-11-09 18:37 UTC, dockerymick commented on release_notes/known_issues_observability.adoc
> +The Prometheus `AdditionalAlertManagerConfig` of the Observability add-on does not support proxy settings. You must disable the Observability alert forwarding feature.
I recommend that you add the instruction on how to disable alert forwarding: https://github.com/stolostron/rhacm-docs/blob/2.9_stage/observability/observability_alerts.adoc#disabling-alert-forwarding-for-managed-clusters

I recommend that you add the step to avoid taking the user to a different topic. Also check for verification step to ensure alert forwarding is disabled.  
```suggestion
The Prometheus `AdditionalAlertManagerConfig` resource of the observability add-on does not support proxy settings. You must disable the observability alert forwarding feature. 

Complete the following steps to disable alert forwarding:

. Go to the `MultiClusterObservability` resource.
. Update the `mco-disabling-alerting` parameter value to `true`
```

2023-11-09 19:24 UTC, jc-berger commented on observability/customize_observability.adoc
> +
@elgnay may I please get your insight and help here to answer Mikela's question on verification?

2023-11-10 06:47 UTC, elgnay commented on observability/customize_observability.adoc
> +
If the proxy settings are configured correctly, the metric collector deployed by the obs add-on agent on the managed cluster will send metrics data to the hub. And then user is able to view the metrics from that managed cluster on the Grafana dashboard from the hub cluster.

2023-11-10 07:01 UTC, elgnay commented on observability/customize_observability.adoc
> +    httpsProxy: "https://<username>:<password>@<ip>:<port>" <1>
Considering the HTTPS proxy is not supported in this release, it's better to use `http://<username>:<password>@<ip>:<port>` instead of `https://<username>:<password>@<ip>:<port>` here.

2023-11-10 07:01 UTC, elgnay commented
LGTM

2023-11-10 16:18 UTC, jc-berger commented on observability/customize_observability.adoc
> +If you successfully configured the proxy settings, the metric collector deployed by the observability add-on agent on the managed cluster sends the data to the hub cluster.
Reviewers, please let me know what you think of the new verification section.

2023-11-10 18:32 UTC, dockerymick commented on observability/customize_observability.adoc
> +Complete the following steps to verify the proxy settings:
I would make this a step

```suggestion
. Verify the proxy settings. If you successfully configured the proxy settings, the metric collector deployed by the observability add-on agent on the managed cluster sends the data to the hub cluster.  Complete the following steps:
```

2023-11-10 18:33 UTC, dockerymick approved these changes
Left a suggestion, thanks for the updates!

2023-11-10 20:52 UTC, dockerymick commented on observability/customize_observability.adoc
> +. Verify the proxy settings. If you successfully configured the proxy settings, the metric collector deployed by the observability add-on agent on the managed cluster sends the data to the hub cluste
```suggestion
. Verify the proxy settings. If you successfully configured the proxy settings, the metric collector deployed by the observability add-on agent on the managed cluster sends the data to the hub cluster. Complete the following steps:
```

2023-11-10 21:55 UTC, dockerymick approved these changes
One more suggestion, otherwise this looks good. Feel free to merge

2023-11-10 21:55 UTC, dockerymick commented on observability/customize_observability.adoc
> +. View the metrics for the proxy settings.
Creating substeps
```suggestion
.. Go to the hub cluster then the managed cluster on the Grafana dashboard. 
.. View the metrics for the proxy settings. 
```

2023-11-13 13:31 UTC, merged