https://issues.redhat.com/browse/ACM-7118
open-cluster-management/rhacm-docs pull request #5762
Opened 2023-11-06 18:28 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-7118 

See similar PR but for ACM changes: https://github.com/stolostron/rhacm-docs/pull/5748

2023-11-07 07:20 UTC, elgnay commented on clusters/cluster_lifecycle/adv_config_cluster.adoc
> +- You have a HTTP or HTTPS proxy server that can reach the managed clusters and can access the MCE hub cluster.
The managed cluster can reach the proxy server and the proxy server can access the hub cluster.

2023-11-07 07:26 UTC, elgnay commented on clusters/cluster_lifecycle/adv_config_cluster.adoc
> +*Note:* A CA certificate is required if the HTTPS proxy server is severing with a self-signed server certificate. The HTTPS proxy is used if both HTTP proxy and HTTPS proxy are specified.
> A CA certificate is required if the HTTPS proxy server is severing with a self-signed server certificate.

Change the above to 
> A CA certificate is required when the HTTPS proxy server is configured.

2023-11-07 07:27 UTC, elgnay commented on clusters/cluster_lifecycle/adv_config_cluster.adoc
> +. When creating a managed cluster, chose the `KlusterletConfig` by adding an annotation and referring to the `ManagedCluster`. See the following example:
The annotation refers to `KlusterletConfig` instead of `ManagedCluster`

2023-11-07 16:29 UTC, dockerymick requested changes
Thanks for your work on this Jake! Let me know when you are ready for a re-review

2023-11-07 16:29 UTC, dockerymick commented on clusters/cluster_lifecycle/adv_config_cluster.adoc
> +== Configuring HTTP or HTTPS proxy between hub cluster and managed cluster
I recommend that we shorten the anchor and update the title 
```suggestion
[#configuring-proxy-hub-and-managed-cluster]
== Configuring the proxy between hub cluster and managed cluster
```

2023-11-07 16:29 UTC, dockerymick commented on clusters/cluster_lifecycle/adv_config_cluster.adoc
> +To register a managed cluster to your Multicluster Engine (MCE) hub cluster, you need to transport the  managed cluster to your MCE hub cluster. Sometimes your managed cluster cannot directly reach y
Remember to use the conrefs for product names, which can be found in the [common-attributes.adoc file](https://github.com/stolostron/rhacm-docs/blob/2.9_stage/modules/common-attributes.adoc)
```suggestion
To register a managed cluster to your {mce-short} hub cluster, you need to transport the  managed cluster to your {mce-short} hub cluster. Sometimes your managed cluster cannot directly reach your {mce-short} hub cluster. In this instance, configure the proxy settings to allow the communications from the managed cluster to access the {mce-short} hub cluster through a HTTP or HTTPS proxy server.
```

2023-11-07 16:29 UTC, dockerymick commented on clusters/cluster_lifecycle/adv_config_cluster.adoc
> +For example, the MCE hub cluster is in a public cloud, and the managed cluster is in a private cloud environment behind firewalls. The communications out of the private cloud can only go through a HT
use the conref for multicluster engine operator

2023-11-07 16:29 UTC, dockerymick commented on clusters/cluster_lifecycle/adv_config_cluster.adoc
> +=== Prerequisites
Throughout the doc, Prerequisites are Header 2 (H2). There are a couple of file that have Prerequisites at H3, and I would like to check on that post GA
```suggestion
== Prerequisites
```

2023-11-07 16:29 UTC, dockerymick commented on clusters/cluster_lifecycle/adv_config_cluster.adoc
> +- You have a HTTP or HTTPS proxy server running that supports HTTP tunnels. For example, HTTP connect method.
```suggestion

- You have a HTTP or HTTPS proxy server running that supports HTTP tunnels. For example, HTTP connect method. 
```

2023-11-07 16:29 UTC, dockerymick commented on clusters/cluster_lifecycle/adv_config_cluster.adoc
> +- You have a manged cluster that can reach the HTTP or HTTPS proxy server, and the proxy server can access the MCE hub cluster.
use the conref here for multicluster engine operator

2023-11-07 16:29 UTC, dockerymick commented on clusters/cluster_lifecycle/adv_config_cluster.adoc
> +. Create a `KlusterConfig` with proxy settings.
```suggestion
. Create a `KlusterConfig` resource with proxy settings. 
```

2023-11-07 16:29 UTC, dockerymick commented on clusters/cluster_lifecycle/adv_config_cluster.adoc
> +. When creating a managed cluster, chose the `KlusterletConfig` by adding an annotation that refers to the `KlusterletConfig`. See the following example:
```suggestion

. When creating a managed cluster, choose the `KlusterletConfig` resource by adding an annotation that refers to the `KlusterletConfig` resource. See the following example:
```

2023-11-07 16:29 UTC, dockerymick commented on clusters/cluster_lifecycle/adv_config_cluster.adoc
> +*Note:* You might need to toggle the yaml view to add the annotation to the `ManagedCluster` when you operate on the MCE UI console.
```suggestion
*Note:* You might need to toggle the YAML view to add the annotation to the `ManagedCluster` resource when you operate on the {mce-short} console.
```

2023-11-07 16:29 UTC, dockerymick commented on clusters/cluster_lifecycle/adv_config_cluster.adoc
> +== Disabling HTTP or HTTPS proxy between hub cluster and managed cluster
Similar to an earlier suggestion, shorten the anchor and update the title
```suggestion
[#disabling-proxy-between-hub-and-managed-cluster]
== Disabling the proxy between hub cluster and managed cluster
```

2023-11-07 16:29 UTC, dockerymick commented on clusters/cluster_lifecycle/adv_config_cluster.adoc
> +If your development needs change, you might need to disable the HTTP or HTTPS proxy.
needs to change 

OR 

If your development changes, you might...

2023-11-07 16:29 UTC, dockerymick commented on clusters/cluster_lifecycle/adv_config_cluster.adoc
> +. Go to `ManagedCluster`.
Where can the resource be accessed? Is there a tab that the user needs to select? 
```suggestion
. Go to `ManagedCluster` resource.
```

2023-11-07 16:29 UTC, dockerymick commented on clusters/release_notes/known_issues.adoc
> +The cluster proxy add-on does not support proxy settings between the MCE hub cluster and the managed cluster. If there is a proxy server sitting between the MCE hub cluster and the managed cluster, y
use conref for multicluster engine operator. i also recommend that you remove the word "sitting"

How does the user disable the proxy add-on? I would add the following statement:

Remove the `agent.open-cluster-management.io/klusterlet-config` annotation from the `ManagedCluster` resource.

2023-11-08 09:03 UTC, elgnay commented on clusters/release_notes/known_issues.adoc
> +The cluster proxy add-on does not support proxy settings between the {mce-short} hub cluster and the managed cluster. If there is a proxy server  between the {mce-short} hub cluster and the managed c
> you must disable the cluster proxy add-on

change to
> you can disable the cluster proxy add-on

It's harmless to keep the cluster proxy add-on running although it can not work. User is able to disable the add-on globally, that means no cluster can has this add-on enabled, even for the one who has no proxy configuration.


>  Remove the `agent.open-cluster-management.io/klusterlet-config` annotation from the `ManagedCluster` resource.

Please remove the above sentence. That's not the way to disable the add-on globally. Instead it just removes the cluster proxy settings between hub and cluster.

2023-11-10 06:56 UTC, elgnay commented on clusters/release_notes/known_issues.adoc
> +The cluster proxy add-on does not support proxy settings between the {mce-short} hub cluster and the managed cluster. If there is a proxy server  between the {mce-short} hub cluster and the managed c
Please remove the redundant space.

2023-11-10 06:57 UTC, elgnay commented
LGTM

2023-11-10 18:44 UTC, dockerymick approved these changes
ONe suggestion. Otherwise this looks good

2023-11-10 18:44 UTC, dockerymick commented on clusters/cluster_lifecycle/adv_config_cluster.adoc
> +
```suggestion

Complete the following steps to configure the proxy settings:

```

2023-11-10 20:12 UTC, merged