HCP for IBM Z
open-cluster-management/rhacm-docs pull request #5792
Opened 2023-11-09 09:29 UTC by krishnanshruthi

Old PR link for reference: https://github.com/stolostron/rhacm-docs/pull/5647/files#

Creating this PR so that we can start clean - the old PR was starting to get confusing.

cc: @SNiemann15

2023-11-09 12:30 UTC, SNiemann15 commented on clusters/hosted_control_planes/configure_hosted_bm_ibmz.adoc
> +**Technology Preview:** Configuring the hosting cluster on `x86` bare metal is in a Technology Preview status with limited support.
```suggestion
**Technology Preview:** Configuring the hosting cluster on `x86` bare metal for IBM Z (`390x`) compute nodes is in a Technology Preview status with limited support.
```

2023-11-09 12:32 UTC, SNiemann15 commented on clusters/hosted_control_planes/configure_hosted_bm_ibmz.adoc
> +The {mce-short} 2.4 supports only the default `local-cluster`, which is a hub cluster that is managed, and the hub cluster as the hosting cluster.
Change this to 2.5? or remove sentence?

2023-11-09 12:33 UTC, SNiemann15 commented on clusters/hosted_control_planes/configure_hosted_bm_ibmz.adoc
> +* {mce} version 2.4 or later must be installed on an {ocp-short} cluster. The {mce-short} is installed automatically when you install {product-title-short}. You can also install {mce-short} without {
```suggestion
* {mce} version 2.5 or later must be installed on an {ocp-short} cluster. The {mce-short} is installed automatically when you install {product-title-short}. You can also install {mce-short} without {product-title-short} as an Operator from the {ocp-short} OperatorHub.
```

2023-11-09 12:39 UTC, SNiemann15 commented on clusters/hosted_control_planes/configure_hosted_bm_ibmz.adoc
> +* You need the {mce-short} must have at least one managed {ocp-short} cluster. The `local-cluster` is automatically imported in {mce-short} 2.4 and later. See xref:../install_upgrade/adv_config_insta
@lahinson Something was grammatically incorrect here (also in bare metal) is it technically still correct like this? 
```suggestion
* The {mce-short} must have at least one managed {ocp-short} cluster. The `local-cluster` is automatically imported in {mce-short} 2.4 and later. See xref:../install_upgrade/adv_config_install.adoc#advanced-config-engine[Advanced configuration] for more information about the `local-cluster`. You can check the status of your hub cluster by running the following command:
```

2023-11-09 12:42 UTC, SNiemann15 commented on clusters/hosted_control_planes/configure_hosted_bm_ibmz.adoc
> +. xref:../hosted_control_planes/config_dns_bare-metal_ibmz.adoc#configuring-dns-hosted-control-plane-ibmz[Configure DNS for Hosted Control Plane for IBM Z]
```suggestion
. xref:../hosted_control_planes/config_dns_bm_ibmz.adoc#configuring-dns-hosted-control-plane-ibmz[Configure DNS for Hosted Control Plane for IBM Z]
```

2023-11-09 12:53 UTC, SNiemann15 commented on clusters/hosted_control_planes/hosted_bm_agents_ibmz.adoc
> +Start KVM on IBM Z and IBM z/VM with the downloaded PXE images from the 'InfraEnv' resource. After the Agents are created, the host communicates with the Assisted Service and registers in the same na
```suggestion
Start your IBM Z environment with the downloaded PXE images from the 'InfraEnv' resource. After the Agents are created, the host communicates with the Assisted Service and registers in the same namespace as the `InfraEnv` resource on the management cluster.
```

2023-11-09 12:55 UTC, SNiemann15 commented on clusters/hosted_control_planes/hosted_bm_agents_ibmz.adoc
> +Start KVM on IBM Z and IBM z/VM with the downloaded PXE images from the 'InfraEnv' resource. After the Agents are created, the host communicates with the Assisted Service and registers in the same na
I think we should have a note either here or at the beginning of `configure_hosted_bm_ibmz.adoc` 

Note: Unless stated otherwise, these practices apply to both z/VM and RHEL KVM installations on IBM Z and IBM LinuxONE.

2023-11-09 12:57 UTC, SNiemann15 commented on clusters/hosted_control_planes/hosted_bm_agents_ibmz.adoc
> +- For KVM on IBM Z, run the following command:
```suggestion
- For IBM Z with KVM, run the following command:
```

2023-11-09 12:58 UTC, SNiemann15 commented on clusters/hosted_control_planes/hosted_bm_agents_ibmz.adoc
> +- For IBM z/VM, start KVM by completing the following procedure:
```suggestion
- For IBM with z/VM, start KVM by completing the following procedure:
```

2023-11-09 12:59 UTC, SNiemann15 commented on clusters/hosted_control_planes/hosted_bm_agents_ibmz.adoc
> +. Update the paramfile to add the `rootfs url`, `net type` and `disk type`.
```suggestion
. Update the parameter file to add the `rootfs url`, `net type` and `disk type`. 
```

2023-11-09 13:27 UTC, SNiemann15 commented on clusters/hosted_control_planes/hosted_bm_agents_ibmz.adoc
> +----
```suggestion
rd.neednet=1 \ 
console=ttysclp0  \
coreos.live.rootfs_url=<rootfs_url> \
ip=<IP for guest vm>::<nameserver>:255.255.255.0::<network adaptor>:none \
nameserver=<nameserver> \ 
zfcp.allow_lun_scan=0 \
rd.znet=qeth,<network adaptor range>,layer2=1 \
rd.<disk_type>=<storage> random.trust_cpu=on \ <1>
rd.luks.options=discard \ 
ignition.firstboot ignition.platform.id=metal \ 
console=tty1 console=ttyS1,115200n8 \
coreos.inst.persistent-kargs="console=tty1 console=ttyS1,115200n8
----
<1> For installations on DASD-type disks, use `rd.dasd=` to specify the installation disk. For installations on FCP-type disks, use `rd.zfcp=`.
```

2023-11-09 13:29 UTC, SNiemann15 commented on clusters/hosted_control_planes/hosted_bm_agents_ibmz.adoc
> +The following example shows a  sample command for the `VSwitch` network with a `fcp singlepath/ dasd` disk:
```suggestion
.Example parameter file for the `VSwitch` network
```

2023-11-09 13:31 UTC, SNiemann15 commented on clusters/hosted_control_planes/hosted_bm_agents_ibmz.adoc
> +. Update the paramfile to add the `rootfs url`, `net type` and `disk type`.
Not sure what "net type" is? Please verify with SMEs

2023-11-09 13:36 UTC, SNiemann15 commented on clusters/hosted_control_planes/hosted_bm_agents_ibmz.adoc
> +----
Do any of the other variables require callouts? Please clarify

2023-11-09 14:23 UTC, SNiemann15 commented on clusters/hosted_control_planes/hosted_bm_agents_ibmz.adoc
> +The following example is a sample command for the `OSA` and `Hipersocket` networks with a `fcp singlepath/dasd` disk:
This and the following parameter file examples should be cleaned up like above. But before putting more effort into this we need a decision, which ones are really required.

2023-11-09 14:25 UTC, SNiemann15 commented on clusters/hosted_control_planes/managing_hosted_bm_ibmz.adoc
> +You can use the {mce} to create and manage a Red Hat {ocp-short} hosted cluster. Hosted control planes are available as a Technology Preview on bare metal.
```suggestion
You can use the {mce} to create and manage a Red Hat {ocp-short} hosted cluster. Hosted control planes are available as a Technology Preview on bare metal with IBM Z.
```

2023-11-09 15:03 UTC, lahinson commented on clusters/hosted_control_planes/configure_hosted_bm_ibmz.adoc
> +* You need the {mce-short} must have at least one managed {ocp-short} cluster. The `local-cluster` is automatically imported in {mce-short} 2.4 and later. See xref:../install_upgrade/adv_config_insta
@SNiemann15 Good catch. You're right -- the wording in the bare metal file is grammatically incorrect. I'll fix that. I think the suggested change here looks good.

2023-11-09 15:07 UTC, lahinson commented on clusters/hosted_control_planes/managing_hosted_bm_ibmz.adoc
It looks like the intention is for this file, `managing_hosted_bm_ibmz.adoc`, to be the parent topic for `scaling_nodepool_hosted_ibmz.adoc`. Do we expect that more topics will be added as child topics under `managing_hosted_bm_ibmz.adoc`? If not, I would move the content from the scaling topic to the managing topic. If so, add a `==Next steps` section in the managing file that points to the scaling topic.

2023-11-09 15:32 UTC, SNiemann15 commented on clusters/hosted_control_planes/configure_hosted_bm_ibmz.adoc
> +- IBM Z does not support ISO boot.
Need to discuss with IBM Z team if ISO boot restriction can be removed.

2023-11-10 08:37 UTC, SNiemann15 commented on clusters/hosted_control_planes/config_dns_bm_ibmz.adoc
> +*api.${HOSTED_CLUSTER_NAME}.${BASEDOMAIN}           IN A 1xx.2x.2xx.1xx
```suggestion
api.${HOSTED_CLUSTER_NAME}.${BASEDOMAIN}           IN A 1xx.2x.2xx.1xx
```

2023-11-10 09:03 UTC, SNiemann15 commented on clusters/hosted_control_planes/hosted_bm_agents_ibmz.adoc
> +The following example shows a  sample command for the `VSwitch` network with a `fcp singlepath/ dasd` disk:
Maybe have a note that multipathing is not supported.

2023-11-10 09:06 UTC, SNiemann15 commented on clusters/hosted_control_planes/hosted_bm_agents_ibmz.adoc
> +----
Clean up formatting

2023-11-10 09:07 UTC, SNiemann15 commented on clusters/hosted_control_planes/hosted_bm_agents_ibmz.adoc
> +----
Clean up formatting

2023-11-10 09:07 UTC, SNiemann15 commented on clusters/hosted_control_planes/hosted_bm_agents_ibmz.adoc
> +[source,bash]
Clean up formatting

2023-11-10 09:09 UTC, SNiemann15 commented on clusters/hosted_control_planes/hosted_bm_agents_ibmz.adoc
> +----
Use one command with callouts and clean up formatting

2023-11-10 09:20 UTC, SNiemann15 commented on clusters/hosted_control_planes/scaling_nodepool_hosted_ibmz.adoc
> +
```suggestion
```

2023-11-10 09:20 UTC, SNiemann15 commented on clusters/hosted_control_planes/scaling_nodepool_hosted_ibmz.adoc
> +
Also remove extra lines before + below

2023-11-10 09:23 UTC, SNiemann15 commented on clusters/hosted_control_planes/scaling_nodepool_hosted_ibmz.adoc
> +[source,bash]
This example also appears in bm docs if removed there remove here.

2023-11-10 09:55 UTC, krishnanshruthi commented on clusters/hosted_control_planes/config_dns_bm_ibmz.adoc
> +*api.${HOSTED_CLUSTER_NAME}.${BASEDOMAIN}           IN A 1xx.2x.2xx.1xx
Done

2023-11-10 09:55 UTC, krishnanshruthi commented on clusters/hosted_control_planes/configure_hosted_bm_ibmz.adoc
> +**Technology Preview:** Configuring the hosting cluster on `x86` bare metal is in a Technology Preview status with limited support.
Done

2023-11-10 11:49 UTC, SNiemann15 commented on clusters/hosted_control_planes/scaling_nodepool_hosted_ibmz.adoc
> +----
```suggestion
----

```

2023-11-10 11:49 UTC, SNiemann15 commented on clusters/hosted_control_planes/scaling_nodepool_hosted_ibmz.adoc
> +----
```suggestion
----

```

2023-11-10 12:01 UTC, SNiemann15 commented on clusters/hosted_control_planes/scaling_nodepool_hosted_ibmz.adoc
> +. Run the following command to see the status of a specific scaled agent:
```suggestion
.. Run the following command to see the status of a specific scaled agent:
```

2023-11-10 12:02 UTC, SNiemann15 commented on clusters/hosted_control_planes/scaling_nodepool_hosted_ibmz.adoc
> +. Run the following command to see the transition phases:
```suggestion
.. Run the following command to see the transition phases:
```

2023-11-10 12:04 UTC, SNiemann15 commented on clusters/hosted_control_planes/scaling_nodepool_hosted_ibmz.adoc
> +
```suggestion
```

2023-11-10 12:06 UTC, SNiemann15 commented on clusters/hosted_control_planes/scaling_nodepool_hosted_ibmz.adoc
> +----
```suggestion
----

```

2023-11-10 18:20 UTC, Neeraj8418 commented on clusters/hosted_control_planes/hosted_bm_agents_ibmz.adoc
For network type is vswitch add zfcp.allow_lun_scan=0 in paramfile


For installations on DASD-type disks, use rd.dasd= to specify the installation disk. For installations on FCP-type disks, use rd.zfcp=.

2023-11-10 18:21 UTC, Neeraj8418 commented on clusters/hosted_control_planes/hosted_bm_agents_ibmz.adoc
remove zfcp.allow_lun_scan=0  from paramfile.

2023-11-11 01:06 UTC, swopebe commented on clusters/hosted_control_planes/config_dns_bm_ibmz.adoc
> +.Example Output
This needs to be changed (line 17)-- I will change it.

2023-11-11 01:06 UTC, swopebe commented on clusters/hosted_control_planes/configure_hosted_bm_ibmz.adoc
> +
Noting a format issue maybe. I will fix this part.

2023-11-11 01:07 UTC, swopebe commented on clusters/hosted_control_planes/hosted_bm_agents_ibmz.adoc
> ++
Format issue, this is prob not suppose to be a bullet...I will play with it.

2023-11-11 01:07 UTC, swopebe commented on clusters/hosted_control_planes/hosted_bm_agents_ibmz.adoc
> ++
Need to change 31. -- I will fix.

2023-11-11 01:07 UTC, swopebe commented on clusters/hosted_control_planes/hosted_bm_agents_ibmz.adoc
> +<1> TBD
Note to come back to this line 48 Monday.

2023-11-11 01:08 UTC, swopebe commented on clusters/hosted_control_planes/hosted_bm_agents_ibmz.adoc
> +.Example output
Note to change line 75

2023-11-11 01:10 UTC, swopebe commented on clusters/hosted_control_planes/managing_hosted_bm_ibmz.adoc
> +
This is not additional resources, this is a next step. We use additional resources for links that were once or would be in-line links.

2023-11-11 01:10 UTC, swopebe commented on clusters/hosted_control_planes/scaling_nodepool_hosted_ibmz.adoc
> +----
format issue-- I will fix.

2023-11-11 01:10 UTC, swopebe commented on clusters/hosted_control_planes/scaling_nodepool_hosted_ibmz.adoc
> ++
77 I will change

2023-11-11 03:19 UTC, swopebe commented
Most recent update from me (Fri evening):

I made many formatting changes, they were simple. I could easily do this by checking out the branch, so I think that is the best way to go, branching over forking. I made one comment for consideration in the main.adoc file. I see we also have some TBDs to handle. We can meet on Monday and we need to merge after that. Monday is the last day for any changes.

2023-11-13 09:20 UTC, SNiemann15 commented on clusters/hosted_control_planes/hosted_bm_agents_ibmz.adoc
> ++
It's something the user has to do depending if he has a KVM or z/VM (line 27) setup.

2023-11-13 10:12 UTC, SNiemann15 commented on clusters/hosted_control_planes/managing_hosted_bm_ibmz.adoc
Discussed with the team. They plan to add further topics in the next releases .

2023-11-13 12:16 UTC, SNiemann15 commented on clusters/hosted_control_planes/hosted_bm_agents_ibmz.adoc
> +installerArgs: '[ "--append-karg", "rd.neednet=1", "--append-karg", "ip=<Guest vm ip>::<nameserver>:255.255.255.0:<hostname>:<network adaptor>:none", "--append-karg", "nameserver=<nameserver>", "--ap
```suggestion
[source,bash]
----
installerArgs: 
--append-karg rd.neednet=1 \
--append-karg ip=<IP_guest_vm>::<nameserver>:255.255.255.0:<hostname>:<network_adaptor>:none \
--append-karg nameserver=<nameserver> \
--append-karg rd.znet=qeth,<network_adaptor_range>,layer2=1 \
--append-karg rd.<storage_type>=<storage>
```

2023-11-13 12:17 UTC, SNiemann15 commented on clusters/hosted_control_planes/hosted_bm_agents_ibmz.adoc
> +zfcp.allow_lun_scan=0 \
```suggestion
ip=<IP_guest_vm>::<nameserver>:255.255.255.0::<network_adaptor>:none \ 
nameserver=<nameserver> \ 
zfcp.allow_lun_scan=0 \ <1>
```

2023-11-13 12:18 UTC, SNiemann15 commented on clusters/hosted_control_planes/hosted_bm_agents_ibmz.adoc
> +<1> TBD
```suggestion
<1> For installations with VSwitch add `zfcp.allow_lun_scan=0`. Omit this entry for installations with OSA, Hipersockets, and RoCE.
```

2023-11-13 13:59 UTC, swopebe requested changes

2023-11-13 13:59 UTC, swopebe commented on clusters/hosted_control_planes/hosted_bm_agents_ibmz.adoc
> +
We still need a short description here: Why does the user want to do this?

Usually something like:

You can add IBM Z agents too...... for.......

2023-11-13 13:59 UTC, swopebe commented on clusters/hosted_control_planes/hosted_bm_agents_ibmz.adoc
> +**Note:** Unless stated otherwise, these practices apply to both z/VM and RHEL KVM installations on IBM Z and IBM LinuxONE.
changing practices to procedures

2023-11-13 13:59 UTC, swopebe commented on clusters/hosted_control_planes/managing_hosted_bm_ibmz.adoc
Yes, I would rather we not merge this as it is...it is technically not a task at all...I think as it is, it needs to move to either another file--maybe an intro file to this IBM z function?

2023-11-13 14:01 UTC, swopebe commented on clusters/hosted_control_planes/hosted_bm_agents_ibmz.adoc
> +
Why do this?

2023-11-13 14:01 UTC, swopebe commented on clusters/hosted_control_planes/hosted_bm_agents_ibmz.adoc
> ++
Done

2023-11-13 14:35 UTC, SNiemann15 commented on clusters/hosted_control_planes/hosted_bm_agents_ibmz.adoc
> +
```suggestion

Adding agents in an IBM Z environment requires additional steps, which are described in detail in this section. 

```

2023-11-13 15:01 UTC, lahinson approved these changes

2023-11-13 15:23 UTC, SNiemann15 commented
/approve

2023-11-13 16:01 UTC, swopebe approved these changes

2023-11-13 16:02 UTC, swopebe commented on clusters/hosted_control_planes/configure_hosted_bm_ibmz.adoc
> +
Just caught two invalid links that have to be fixed before merge.

2023-11-13 16:04 UTC, swopebe commented on clusters/hosted_control_planes/configure_hosted_bm_ibmz.adoc
> +
Broken:

You need to enable the central infrastructure management service. For more information, see [Enabling the Central Infrastructure Management service 404](https://github.com/stolostron/rhacm-docs/blob/cc3a7e274b40f130a6e91a6421025a9577b33cf0/clusters/cluster_lifecycle/create_infra_env.adoc#enable-cim).

You need to install the hosted control plane command line interface. See [Installing the hosted control plane command line interface 404](https://github.com/stolostron/rhacm-docs/blob/cc3a7e274b40f130a6e91a6421025a9577b33cf0/clusters/clusters/hosted_control_planes/hosted_install_cli.adoc).

2023-11-13 16:12 UTC, SNiemann15 commented on clusters/hosted_control_planes/configure_hosted_bm_ibmz.adoc
> +* You need to enable the central infrastructure management service. For more information, see xref:../cluster_lifecycle/create_infra_env.adoc#enable-cim[Enabling the Central Infrastructure Management
```suggestion
* You need to enable the central infrastructure management service. For more information, see  xref:../cluster_lifecycle/cim_enable.adoc#enable-cim[Enabling the central infrastructure management service].
```

2023-11-13 16:24 UTC, SNiemann15 commented on clusters/hosted_control_planes/hosted_bm_agents_ibmz.adoc
> +. Start your IBM Z environment with the downloaded PXE images from the `InfraEnv`` resource. After the Agents are created, the host communicates with the Assisted Service and registers in the same na
```suggestion
. Start your IBM Z environment with the downloaded PXE images from the `InfraEnv` resource. After the Agents are created, the host communicates with the Assisted Service and registers in the same namespace as the `InfraEnv` resource on the management cluster.
```

2023-11-13 16:29 UTC, holgwolf commented
LGTM

2023-11-13 16:35 UTC, merged

2023-11-14 12:03 UTC, mkumatag commented
we would have avoided pushing these binary files `clusters/.DS_Store` and `.DS_Store`