https://issues.redhat.com/browse/ACM-8498 Default alerts thanos
open-cluster-management/rhacm-docs pull request #5799
Opened 2023-11-09 16:30 UTC by dockerymick

https://issues.redhat.com/browse/ACM-8498

In the diagram, we have Thanos infrastructure. In the issue, Thanos compactor is mentioned. Are the infrastructure and compactor the same? Is the compactor a part of the infrastructure?

2023-11-09 20:01 UTC, dockerymick commented on release_notes/whats_new.adoc
> +* The following alerts are now the default alerts for the Thanos infrastructure: `ACMThanosCompactHalted`, `ACMThanosCompactHighCompactionFailures`, `ACMThanosCompactBucketHighOperationFailures`, `AC
```suggestion
* The following default alerts are provided for the Thanos compactor: `ACMThanosCompactHalted`, `ACMThanosCompactHighCompactionFailures`, `ACMThanosCompactBucketHighOperationFailures`, `ACMThanosCompactHasNotRun`. See link:../observability/observability_arch.adoc#observability-arch[Observability architecture].
```

2023-11-10 12:55 UTC, douglascamata commented
> In the diagram, we have Thanos infrastructure. In the issue, Thanos compactor is mentioned. Are the infrastructure and compactor the same? Is the compactor a part of the infrastructure?

That's correct, @dockerymick. Thanos Compactor is part of the Thanos infrastructure. To put it in the language used in the Thanos project, Compactor is one of the components in Thanos. 👍

2023-11-10 12:57 UTC, douglascamata requested changes

2023-11-10 12:57 UTC, douglascamata commented on observability/observability_arch.adoc
> +- The Thanos infrastructure, includes the Thanos compactor, which is deployed by the `multicluster-observability-operator` pod. The Thanos compactor ensures that queries are performing well by using
I suggest to capitalize `compactor` here. In official Thanos documentation, `Compactor` is always referred to like so. It's the proper name of the component.

2023-11-10 15:55 UTC, swopebe commented on observability/observability_arch.adoc
> ++
Beautiful description!

2023-11-10 15:56 UTC, swopebe commented on observability/observability_arch.adoc
> +| ACMThanosCompactHalted
These should be coded: `ACMThanosCompactHalted`

this will also help with translation tools, as they won't be scanned as actual words that people have to translate.

2023-11-10 15:58 UTC, swopebe approved these changes
made some small changes.

2023-11-10 15:59 UTC, swopebe commented on observability/observability_arch.adoc
> +| An alert is sent when the compaction failure rate is greater than 5%.
check to see if we should be writing out percent???

2023-11-10 21:07 UTC, dockerymick commented on observability/observability_arch.adoc
> +| An alert is sent when the compaction failure rate is greater than 5%.
I checked the style guide and there were no requirements mentioned. However, I agree with the update
```suggestion
| An alert is sent when the compaction failure rate is greater than 5 percent.
```

2023-11-13 10:46 UTC, douglascamata approved these changes
/lgtm

2023-11-13 13:27 UTC, dockerymick commented
@douglascamata @swopebe thanks for the reviews and approvals! Merging this PR

2023-11-13 13:27 UTC, merged