https://issues.redhat.com/browse/ACM-8497
open-cluster-management/rhacm-docs pull request #5800
Opened 2023-11-09 18:29 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-8497

2023-11-09 18:30 UTC, jc-berger commented on troubleshooting/trouble_cinder_csi_driver_volsync.adoc
> +If you use the VolSync, it can create a `replicationsource/destination` that uses a cinder CSI driver. Within the cinder CSI driver, there is a parameter on the `volumesnapshotclass` called `force-cr
In the Jira, I didn't see an exact correlation between the `replicationsource/destination` inside the CSI driver and the `volumesnapshotclass`. Therefore, it's my inference that this `volumesnapshotclass` is insie the CSI driver. 

Please correct me if I am incorrect.

2023-11-09 18:31 UTC, jc-berger commented on troubleshooting/trouble_cinder_csi_driver_volsync.adoc
> +  force-create: 'true'
In the Jira, the sample YAML I was given had the value set to `false`. 

However, I changed it to `true` because that's what we tell users to do as part of the troubleshooting. 

Please correct me if I am missing something.

2023-11-09 18:32 UTC, jc-berger commented on troubleshooting/trouble_cinder_csi_driver_volsync.adoc
> +For more information, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html-single/storage/index#persistent-storage-csi-snapshots[CSI Volume Snapshots].
There was some back and forth about what link, if any, we'd provide users. Reviewers, please let me know what you think.

2023-11-09 19:10 UTC, tesshuflower commented on troubleshooting/trouble_cinder_csi_driver_volsync.adoc
> +.. *Optional*: If you prefer, update an existing `volumesnapshot`.
I think we need to remove this "update an existing volumesnapshot" - maybe instead we can say create a new `volumesnapshotclass` for cinder-csi or update the existing one.

2023-11-09 19:10 UTC, tesshuflower commented on troubleshooting/trouble_cinder_csi_driver_volsync.adoc
> +  force-create: 'true'
You got it!

2023-11-09 19:13 UTC, tesshuflower commented on troubleshooting/trouble_cinder_csi_driver_volsync.adoc
> +For more information, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html-single/storage/index#persistent-storage-csi-snapshots[CSI Volume Snapshots].
I don't think we should use this link, as this is just generic documentation about CSI.  This configuration setting is not a generic CSI thing, but something specific to the cinder implementation.  The only place I can find mention of cinder setting this is the original link upstream here: https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/cinder-csi-plugin/using-cinder-csi-plugin.md

2023-11-09 19:17 UTC, tesshuflower commented on troubleshooting/trouble_cinder_csi_driver_volsync.adoc
> +If you use the VolSync, it can create a `replicationsource/destination` that uses a cinder CSI driver. Within the cinder CSI driver, there is a parameter on the `volumesnapshotclass` called `force-cr
I'm not sure the best way to explain it, but a volsync `ReplicationSource` or `ReplicationDestination` can be configured to use snapshots - you can configure the storageclass & volumesnapshotclass in the ReplicationSource/ReplicationDestination - or you can let the system decide (i.e. whatever is set as the system default).

Essentially it boils down to: if you're using VolSync to create volumesnapshots using a cinder-csi driver - you could encounter this error for PVCs that are in use.

Note that this can also happen without VolSync (if you just create the volumesnapshot yourself) using that same cinder-csi driver.

2023-11-09 19:47 UTC, swopebe requested changes

2023-11-09 19:47 UTC, swopebe commented on troubleshooting/trouble_cinder_csi_driver_volsync.adoc
> +For more information, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html-single/storage/index#persistent-storage-csi-snapshots[CSI Volume Snapshots].
Pause on using this link...is this repo validated by QE? As technical writers, we cannot link to random open repos and such because they can change without notice...that is why it is better to link to official documentation. 

Let's get a QE-ack at minimum on this link so that is support opens an issue, we can at least say this was tested. 

This is RH standard.

2023-11-09 19:47 UTC, swopebe commented on troubleshooting/trouble_cinder_csi_driver_volsync.adoc
> +----
@jc-berger this looks great but there is a format issue on this PR, line 18 and the rest of YAML should be grayed out. We usually need an extra space to fix that, so if you don't see it grayed out, just see if adding a space helps. I will do that now.

2023-11-09 19:48 UTC, swopebe commented on troubleshooting/trouble_cinder_csi_driver_volsync.adoc
> +----
yes, that was the fix. All good now.

2023-11-10 17:24 UTC, jc-berger commented on troubleshooting/trouble_cinder_csi_driver_volsync.adoc
> +If you use the VolSync, it can create a `replicationsource/destination` that uses a cinder CSI driver. Within the cinder CSI driver, there is a parameter on the `volumesnapshotclass` called `force-cr
Please see the revised intro and let me know what you think.

2023-11-10 17:25 UTC, jc-berger commented on troubleshooting/trouble_cinder_csi_driver_volsync.adoc
> +For more information, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html-single/storage/index#persistent-storage-csi-snapshots[CSI Volume Snapshots].
Okay, I removed the link entirely. I know a lot of RH writers, like my previous products, were pretty loath to include links to documentation outside our repo.

2023-11-10 17:26 UTC, jc-berger commented on troubleshooting/trouble_cinder_csi_driver_volsync.adoc
> +----
Okay added an extra space before the + and yaml. 

Did you mean space in between the + and the yaml?

I wonder why the spacing was weird, because in our other files, it's just the one space before the yaml.

2023-11-10 17:31 UTC, swopebe commented on troubleshooting/trouble_cinder_csi_driver_volsync.adoc
> +----
well now you have two lol, I added one and it was fixed.

a break between a paragraph and this:
```
+
[source,yaml]
```

2023-11-10 17:31 UTC, swopebe approved these changes
looks great.

2023-11-13 13:43 UTC, tesshuflower commented on troubleshooting/trouble_cinder_csi_driver_volsync.adoc
> +You can configure a VolSync `ReplicationSource` or `ReplicationDestination` to use snapshots. Also, you can configure the `storageclass` and `volumesnapshotclass` in the `ReplicationSource` and `Repl
Just to be very clear, can we say "There is a parameter on the `cinder` volumesnapshotclass called force-create?"

2023-11-13 13:54 UTC, tesshuflower commented
/lgtm

2023-11-13 14:18 UTC, merged