https://issues.redhat.com/browse/ACM-8432--new content
open-cluster-management/rhacm-docs pull request #5806
Opened 2023-11-10 03:05 UTC by swopebe

2023-11-10 11:53 UTC, cadawson approved these changes
Looks great! Thanks!

2023-11-13 14:52 UTC, birsanv requested changes

2023-11-13 14:52 UTC, birsanv commented on business_continuity/backup_restore/backup_validate.adoc
> +*Note:* A hub cluster is set to `automanage` by default. If you disable it by setting `disableHubSelfManagement=true`, the `backup-restore-enabled` policy is not placed on the hub cluster and does no
I was looking at this section to make sure we use the same terms .. https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.8/html/install/installing

Based on this I suggest these changes:

A hub cluster is automatically imported and managed by itself using the `local-cluster` managed cluster. If you disable this by setting `disableHubSelfManagement=true` on the MultiClusterHub resource, the `backup-restore-enabled` policy is not placed on the hub cluster and as a result the policy templates do not produce any reports.

2023-11-13 15:41 UTC, birsanv approved these changes
lgtm

2023-11-13 16:00 UTC, merged