https://issues.redhat.com/browse/ACM-8488 Metrics known issue
open-cluster-management/rhacm-docs pull request #5808
Opened 2023-11-10 11:00 UTC by oafischer

Also for 2.8

2023-11-10 14:06 UTC, douglascamata requested changes

2023-11-10 14:06 UTC, douglascamata commented on release_notes/known_issues_observability.adoc
> +//2.9:1ACM-8488
Is this a typo?

```suggestion
//2.9:ACM-8488
```

2023-11-10 14:06 UTC, douglascamata commented on release_notes/known_issues_observability.adoc
> +A proxy configuration in a managed cluster that you configure by using the `addonDeploymentConfig` is not detected by the metrics collector. HTTPS proxy configuration with a custom CA bundle is not s
Could we split this paragraph into a few bullet points? I think it would be much easier to understand the different scenarios here.

2023-11-10 14:09 UTC, oafischer commented on release_notes/known_issues_observability.adoc
> +//2.9:1ACM-8488
Indeed, fixed, thanks!

2023-11-10 14:13 UTC, oafischer commented on release_notes/known_issues_observability.adoc
> +A proxy configuration in a managed cluster that you configure by using the `addonDeploymentConfig` is not detected by the metrics collector. HTTPS proxy configuration with a custom CA bundle is not s
If we add an explanatory sentence, sure. Maybe:

A proxy configuration in a managed cluster that you configure by using the `addonDeploymentConfig` is not detected by the metrics collector because of the following limitations:

- HTTPS proxy configuration with a custom CA bundle is not supported.
- HTTP proxy configuration is only supported with manual configuration.

Does that work?

2023-11-10 17:05 UTC, douglascamata commented on release_notes/known_issues_observability.adoc
> +A proxy configuration in a managed cluster that you configure by using the `addonDeploymentConfig` is not detected by the metrics collector. HTTPS proxy configuration with a custom CA bundle is not s
The detection problem is separate of the lack of support for HTTPS + custom CA bundle. In this text they seem mixed up. Here's my rough suggestion:

```
==Metrics collector does not detect proxy configuration

A proxy configuration in a managed cluster that you configure by using the `addonDeploymentConfig` is not detected by the metrics collector. 

You can enable it by the removing the managed cluster `ManifestWork`. Removing the `ManifestWork` forces the changes in the `addonDeploymentConfig` to be applied.

==HTTPS proxy with custom CA bundle is not supported

A proxy configuration in a managed cluster will not work properly when a custom CA bundle is needed. Currently there is no workaround.
```

As a custom CA bundle would only make sense with HTTPS proxy and not HTTP proxy, I avoid mentioning HTTP proxy in the last point.

2023-11-13 10:09 UTC, oafischer commented on release_notes/known_issues_observability.adoc
> +A proxy configuration in a managed cluster that you configure by using the `addonDeploymentConfig` is not detected by the metrics collector. HTTPS proxy configuration with a custom CA bundle is not s
I see, you are treating them as 2 issues. That makes sense. I updated the file @douglascamata, let me know if that looks good now. Thanks!

2023-11-13 10:14 UTC, douglascamata approved these changes
/lgtm

2023-11-13 10:42 UTC, cadawson approved these changes
Looks good. Thanks!

2023-11-13 10:42 UTC, cadawson commented on release_notes/known_issues_observability.adoc
> +Your query data appears from the Grafana dashboard.
Appears _in_ the Grafana dashboard?

2023-11-13 10:47 UTC, oafischer commented on release_notes/known_issues_observability.adoc
> +Your query data appears from the Grafana dashboard.
Not sure, didn't work on that section, I'd rather leave it for now. Thanks for the review!

2023-11-13 11:19 UTC, merged