https://issues.redhat.com/browse/ACM-8506 OCP 3.11 unsupported
open-cluster-management/rhacm-docs pull request #5852
Opened 2023-11-14 15:54 UTC by dockerymick

https://issues.redhat.com/browse/ACM-8506

2023-11-14 15:58 UTC, oafischer approved these changes
lgtm

2023-11-20 14:16 UTC, birsanv requested changes

2023-11-20 14:16 UTC, birsanv commented on release_notes/known_issues_continuity.adoc
> +If you have {ocp-short} 3.11 managed clusters and you restore the cluster, the restored data is not connected to the new hub cluster automatically.
Change this

If you have {ocp-short} 3.11 managed clusters and you restore the cluster, the restored data is not connected to the new hub cluster automatically.

to 

If you have {ocp-short} 3.11 managed clusters and you restore the cluster, the managed cluster is not connected to the new hub cluster automatically.

2023-11-20 14:16 UTC, xiangjingli commented
/lgtm

2023-11-20 14:18 UTC, dockerymick commented on release_notes/known_issues_continuity.adoc
> +If you have {ocp-short} 3.11 managed clusters and you restore the cluster, the restored data is not connected to the new hub cluster automatically.
@birsanv thanks ! Adding the suggestion to make the change 

```suggestion
If you have {ocp-short} 3.11 managed clusters and you restore the cluster, the managed cluster is not connected to the new hub cluster automatically. 
```

2023-11-20 14:19 UTC, dockerymick commented on release_notes/known_issues_continuity.adoc
> +If you have {ocp-short} 3.11 managed clusters and you restore the cluster, the restored data is not connected to the new hub cluster automatically.
Updated

2023-11-20 14:21 UTC, birsanv approved these changes
lgtm

2023-11-20 14:23 UTC, merged