https://issues.redhat.com/browse/ACM-8583
open-cluster-management/rhacm-docs pull request #5863
Opened 2023-11-20 16:22 UTC by jc-berger

2023-11-20 17:14 UTC, fxiang1 requested changes

2023-11-20 17:14 UTC, fxiang1 commented on clusters/cluster_lifecycle/ansible_config_cluster.adoc
> +* Special keys `cluster_deployment` and `machine_pool` are passed automatically as extra variables, containing data on general information about the cluster and details about the worker nodes being c
Sorry @jc-berger I made the mistake of mentioning `machine_pool` it should be `install_config` instead.
Please change this line to:

* Special keys `cluster_deployment` and `install_config` are passed automatically as extra variables, containing data on general information about the cluster and details about the cluster install configuration.

2023-11-20 18:50 UTC, jc-berger commented on clusters/cluster_lifecycle/ansible_config_cluster.adoc
> +* Special keys `cluster_deployment` and `machine_pool` are passed automatically as extra variables, containing data on general information about the cluster and details about the worker nodes being c
Thanks @fxiang1 ! I've applied your feedback. Would you please let me know if you think it looks good to merge now?

2023-11-20 18:54 UTC, fxiang1 approved these changes
LGTM! Thanks Jake for the quick change!

2023-11-22 14:45 UTC, cadawson approved these changes
Looks good. A couple of minor suggestions to consider. Thanks!

2023-11-22 14:45 UTC, cadawson commented on clusters/cluster_lifecycle/ansible_config_cluster.adoc
> +* Use the `Extra variables` field to pass data to the `AnsibleJob` resource in the form of `key=value` pairs.
```suggestion
* Use the *Extra variables* field to pass data to the `AnsibleJob` resource in the form of `key=value` pairs. 
```

2023-11-22 14:45 UTC, cadawson commented on clusters/cluster_lifecycle/ansible_config_cluster.adoc
> +* Use the `Extra variables` field to pass data to the `AnsibleJob` resource in the form of `key=value` pairs.
IBM style has field names as bold, but we might not always use it that way. If you see this somewhere else in the file, please make it consistent.

2023-11-22 14:45 UTC, cadawson commented on clusters/cluster_lifecycle/ansible_config_cluster.adoc
> +* Special keys `cluster_deployment` and `install_config` are passed automatically as extra variables, containing data on general information about the cluster and details about the cluster install co
```suggestion
* Special keys `cluster_deployment` and `install_config` are passed automatically as extra variables. They contain general information about the cluster and details about the cluster installation configuration. 
```

2023-11-22 14:45 UTC, cadawson commented on clusters/cluster_lifecycle/ansible_config_cluster.adoc
> +* Special keys `cluster_deployment` and `install_config` are passed automatically as extra variables, containing data on general information about the cluster and details about the cluster install co
Just a thought here to break this up.

2023-11-22 15:02 UTC, merged