https://issues.redhat.com/browse/ACM-8583
open-cluster-management/rhacm-docs pull request #5865
Opened 2023-11-20 16:41 UTC by jc-berger

See PR for 2.9: https://github.com/stolostron/rhacm-docs/pull/5863/files

2023-11-20 17:15 UTC, fxiang1 requested changes

2023-11-20 17:15 UTC, fxiang1 commented on clusters/cluster_lifecycle/ansible_config_cluster.adoc
> +* Special keys `cluster_deployment` and `machine_pool` are passed automatically as extra variables, containing data on general information about the cluster and details about the worker nodes being c
Sorry @jc-berger I made the mistake of mentioning `machine_pool` it should be `install_config` instead.
Please change this line to:

* Special keys `cluster_deployment` and `install_config` are passed automatically as extra variables, containing data on general information about the cluster and details about the cluster install configuration.

2023-11-20 18:46 UTC, jc-berger commented on clusters/cluster_lifecycle/ansible_config_cluster.adoc
> +* Special keys `cluster_deployment` and `machine_pool` are passed automatically as extra variables, containing data on general information about the cluster and details about the worker nodes being c
Thanks @fxiang1 ! I applied your feedback. Please let me know if you think it looks good to merge now!

2023-11-20 18:53 UTC, fxiang1 approved these changes
LGTM! Thanks Jake for the quick change!

2023-11-22 14:46 UTC, cadawson approved these changes
Looks good. See suggestions in the 2.9 version. If you made changes there, you might want to make them here, too. Thanks!

2023-11-22 15:07 UTC, merged