https://issues.redhat.com/browse/ACM-8558--arm known issue
open-cluster-management/rhacm-docs pull request #5877
Opened 2023-11-21 23:53 UTC by swopebe

2023-11-21 23:55 UTC, swopebe commented on release_notes/known_issues_install.adoc
> +== Infrastructure operator error with ARM converged flow
@cadawson do we use another term for "arm"?

2023-11-22 06:46 UTC, filanov commented on release_notes/known_issues_install.adoc
> +When you install the `infrastructure-operator`, converged flow with ARM does not work. Set `ALLOW_CONVERGED_FLOW` to `false` to resolve this issue.
I'm not sure that a lot of users are familiar  with how to set the env var, the user will need to do that by defining a config map https://github.com/openshift/assisted-service/blob/master/docs/operator.md#specifying-environmental-variables-via-configmap

2023-11-27 18:37 UTC, swopebe commented on release_notes/known_issues_install.adoc
> +When you install the `infrastructure-operator`, converged flow with ARM does not work. Set `ALLOW_CONVERGED_FLOW` to `false` to resolve this issue.
@filanov since this is not official doc, we cannot link to it. We would need to place the step in the known issue, which I can do.

2023-11-27 19:14 UTC, swopebe commented on release_notes/known_issues_install.adoc
> +When you install the `infrastructure-operator`, converged flow with ARM does not work. Set `ALLOW_CONVERGED_FLOW` to `false` to resolve this issue.
Would like a cleaner version of this where we breal the command from the file, as we don't skip that step in the docs:

Run the following command to create a `ConfigMap`:
```
kubectl create -f -
```
See the following file with .... (this doesn't have a "converged flow" --do we need to add that spec here?)
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-assisted-service-config
  namespace: assisted-installer
data:
  LOG_LEVEL: "debug"
```

2023-12-05 17:38 UTC, filanov commented on release_notes/known_issues_install.adoc
> +When you install the `infrastructure-operator`, converged flow with ARM does not work. Set `ALLOW_CONVERGED_FLOW` to `false` to resolve this issue.
You don't need to link the unofficial link but explaining how to create the configmap can really help. 
@carbonin is there another way to avoid converged flow besides using the unsupported configmap?

2023-12-05 18:12 UTC, carbonin commented on release_notes/known_issues_install.adoc
> +When you install the `infrastructure-operator`, converged flow with ARM does not work. Set `ALLOW_CONVERGED_FLOW` to `false` to resolve this issue.
Not that I recall.

2023-12-05 18:17 UTC, swopebe commented on release_notes/known_issues_install.adoc
> +When you install the `infrastructure-operator`, converged flow with ARM does not work. Set `ALLOW_CONVERGED_FLOW` to `false` to resolve this issue.
If you guys are all ok with this draft, I will add it: https://github.com/stolostron/rhacm-docs/pull/5877#discussion_r1406633807

2023-12-06 12:23 UTC, filanov commented on release_notes/known_issues_install.adoc
> +When you install the `infrastructure-operator`, converged flow with ARM does not work. Set `ALLOW_CONVERGED_FLOW` to `false` to resolve this issue.
yes from my side, for the example i would suggest to put `ALLOW_CONVERGED_FLOW: false` for the example

2023-12-06 16:07 UTC, swopebe commented on release_notes/known_issues_install.adoc
> +When you install the `infrastructure-operator`, converged flow with ARM does not work. Set `ALLOW_CONVERGED_FLOW` to `false` to resolve this issue.
@filanov I just need to know where in the sample to add that:

apiVersion: v1
kind: ConfigMap
metadata:
  name: my-assisted-service-config
  namespace: assisted-installer
data:
  LOG_LEVEL: "debug"
  
  
  Can you place it?

2023-12-06 20:24 UTC, carbonin commented on release_notes/known_issues_install.adoc
> +When you install the `infrastructure-operator`, converged flow with ARM does not work. Set `ALLOW_CONVERGED_FLOW` to `false` to resolve this issue.
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-assisted-service-config
  namespace: assisted-installer
data:
  ALLOW_CONVERGED_FLOW: false
```

2023-12-06 20:44 UTC, swopebe commented on release_notes/known_issues_install.adoc
> +When you install the `infrastructure-operator`, converged flow with ARM does not work. Set `ALLOW_CONVERGED_FLOW` to `false` to resolve this issue.
That's in and ready for review. I should have caught this earlier...mostly we are using `oc` instead of `kubectl` but does that not apply here?

2023-12-06 20:49 UTC, carbonin commented on release_notes/known_issues_install.adoc
> +. Run the following command to create a `ConfigMap`:
You also need to annotate the agentserviceconfig:

```
oc annotate --overwrite AgentServiceConfig agent unsupported.agent-install.openshift.io/assisted-service-configmap=my-assisted-service-config
```

2023-12-06 21:20 UTC, swopebe commented on release_notes/known_issues_install.adoc
> +. Run the following command to create a `ConfigMap`:
Ok, that would be step 3, I assume? I will add it and let me know. (Future: if we can get draft procedures in the template before we accept the issue, we can prevent some delay.)

2023-12-06 21:24 UTC, swopebe commented on release_notes/known_issues_install.adoc
> +. Run the following command to create a `ConfigMap`:
I went ahead and made both commands `oc`.

2023-12-07 04:39 UTC, dockerymick requested changes

2023-12-07 04:39 UTC, dockerymick commented on release_notes/known_issues_install.adoc
> +== Infrastructure operator error with ARM converged flow
There is a conref for Infrastructure Operator for Red Hat OpenShift ({assist-install}). is this another name for CIM?

2023-12-07 04:39 UTC, dockerymick commented on release_notes/known_issues_install.adoc
> +. Run the following command to create a `ConfigMap`:
ConfigMap doesn't need to be monospaced

2023-12-07 04:39 UTC, dockerymick commented on release_notes/known_issues_install.adoc
> +
How does the user know that the issue is resolved?

2023-12-07 07:47 UTC, filanov commented on release_notes/known_issues_install.adoc
> +. Run the following command to create a `ConfigMap`:
he will see the agent appear in the inventory

2023-12-07 19:09 UTC, swopebe commented on release_notes/known_issues_install.adoc
> +== Infrastructure operator error with ARM converged flow
I don't think so; it's worth checking in the near future. CIM is the _infrastructure operator_ but it is just called that in the doc; but we need to look at conrefs in general. I notice there are some confusing ones like "cincinatti" that need to be named better. We need to have conref additions peer reviewed like other repo additions.

2023-12-07 19:12 UTC, swopebe commented on release_notes/known_issues_install.adoc
> +
We don't always tell them that in a known issue, so if there is nothing for them to check, we keep it blank.

2023-12-07 19:13 UTC, swopebe commented on release_notes/known_issues_install.adoc
> +. Run the following command to create a `ConfigMap`:
@dockerymick this is correctly monospaced. It is referring to the `kind` that is named `ConfigMap`. I will ensure we revisit this in our doc meetings. Yes you can just call it a generic config map, but I coded it because we literally give them a `ConfigMap` sample. 

https://redhat-internal.slack.com/archives/CUHCCV19P/p1701112320733399

2023-12-07 19:15 UTC, swopebe commented on release_notes/known_issues_install.adoc
> +. Run the following command to create a `ConfigMap`:
Will add: The agent appears in the inventory when the issue is resolved.

2023-12-07 19:16 UTC, swopebe commented on release_notes/known_issues_install.adoc
> +
addressed in line 64.

2023-12-07 19:20 UTC, swopebe commented on release_notes/known_issues_install.adoc
> +. Run the following command to create a `ConfigMap` resource:
added resource to align with what the step is for and the `kind`

2023-12-07 19:21 UTC, swopebe commented on release_notes/known_issues_install.adoc
> +. See the following file sample with `ALLOW_CONVERGED_FLOW` set to `false`:
We prob need to apply this with a command, right @filanov ?

2023-12-07 19:34 UTC, dockerymick approved these changes
Thanks Brandi, this looks good to me!

2023-12-07 21:24 UTC, filanov approved these changes
LGTM from me

2023-12-07 21:24 UTC, filanov commented on release_notes/known_issues_install.adoc
> +. See the following file sample with `ALLOW_CONVERGED_FLOW` set to `false`:
yes

2023-12-11 15:58 UTC, swopebe commented on release_notes/known_issues_install.adoc
> +. See the following file sample with `ALLOW_CONVERGED_FLOW` set to `false`:
@filanov can I assume the command is `oc apply -f` ?

2023-12-11 19:38 UTC, carbonin commented on release_notes/known_issues_install.adoc
> +. See the following file sample with `ALLOW_CONVERGED_FLOW` set to `false`:
yes, that will work.

2023-12-12 21:31 UTC, merged