post-release corrections
open-cluster-management/rhacm-docs pull request #5878
Opened 2023-11-22 11:22 UTC by krishnanshruthi

@swopebrandi1 Pls review the changes that were suggested by the IBM Z team after going through the released documentation page.

cc: @SNiemann15

2023-11-24 10:45 UTC, veera-damisetti commented on clusters/hosted_control_planes/config_dns_bm_ibmz.adoc
> +*.apps ${HOSTED_CLUSTER_NAME}.${BASEDOMAIN}           IN A 1xx.2x.2xx.1xx
this line should be **`*.apps        IN A 1xx.2x.2xx.1xx`**

2023-11-24 10:47 UTC, veera-damisetti commented on clusters/hosted_control_planes/hosted_create_bare_metal.adoc
> +export OCP_RELEASE=4.14.0-multi
As we are changing the version here , 
we need to change the version in rest of the doc also . 
4.14.0-ec.2-multi --> 4.14.0-multi

2023-11-27 13:54 UTC, SNiemann15 commented on clusters/hosted_control_planes/hosted_create_bare_metal.adoc
> +    --api-server-address=api.${HOSTED_CLUSTER_NAME}.${BASEDOMAIN}
@swopebe This is Z specific (not sure about Power @alishaIBM? ) 

Should we add those lines with callouts? Add a second IBM Z only example? Or even have a new file `hosted_create_bare_metal_ibmz.adoc`

2023-11-27 18:31 UTC, swopebe commented on clusters/hosted_control_planes/hosted_create_bare_metal.adoc
> +    --api-server-address=api.${HOSTED_CLUSTER_NAME}.${BASEDOMAIN}
These {ETCD_STORAGE} should be <ETCD_STORAGE> and yes, if you think the use needs more information about that variable, you can add callouts. It depends on if the variable you add, like <HOSTED_CLUSTER_NAME> (we normally lower case these) is self explanatory.

2023-11-27 18:32 UTC, swopebe commented on clusters/hosted_control_planes/scaling_nodepool_hosted_ibmz.adoc
>  ----
awesome change here on line 117

2023-11-27 18:34 UTC, swopebe commented on clusters/hosted_control_planes/scaling_nodepool_hosted_ibmz.adoc
>  NAME                                                                           VERSION       AVAILABLE   PROGRESSING   DEGRADED   SINCE   MESSAGE
This is where I fear we are documenting too much. I don't think we need all these lines....all these versions would have to change and we have to remember to go and change them. I think we need to instead give the user what to look for in the output instead of putting a whole output here that we will have to maintain. 

Is the purpose of the output to check for status? I feel we can say that without putting the whole table here, as we are trying to simplify the docs where we can.

Thoughts? @cadawson this is an example I mentioned.

2023-11-27 18:36 UTC, swopebe requested changes
Comments for consideration

2023-11-27 20:13 UTC, cadawson commented on clusters/hosted_control_planes/scaling_nodepool_hosted_ibmz.adoc
>  NAME                                                                           VERSION       AVAILABLE   PROGRESSING   DEGRADED   SINCE   MESSAGE
I agree that looks like a lot of lines. Can we summarize with something like: The resulting output shows that all of the operators are available and no longer progressing? That might not work if we are trying to list all of the required operators (which I am not sure we want to do here). Trimming this would be helpful if it is possible.

2023-11-28 05:48 UTC, veera-damisetti commented on clusters/hosted_control_planes/hosted_create_bare_metal.adoc
> +    --api-server-address=api.${HOSTED_CLUSTER_NAME}.${BASEDOMAIN}
{ETCD_STORAGE}  ... this we are not not updating anything related to that in this PR i think .

2023-11-28 16:08 UTC, SNiemann15 commented on clusters/hosted_control_planes/scaling_nodepool_hosted_ibmz.adoc
>  NAME                                                                           VERSION       AVAILABLE   PROGRESSING   DEGRADED   SINCE   MESSAGE
@swopebe @cadawson I would like to stay in sync with the x86 docs, where this and other examples are also present. For example [here](https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.9/html/clusters/cluster_mce_overview#hosted-control-planes-manage-bm). 
Shouldn't we leave it in the PR for the moment and get this one and Power merged asap. Next step find a solution for the entire doc set and change in sync across all architectures.

2023-11-28 19:21 UTC, swopebe commented on clusters/hosted_control_planes/hosted_create_bare_metal.adoc
> +    --api-server-address=api.${HOSTED_CLUSTER_NAME}.${BASEDOMAIN}
Right, for our doc, across the board, this is what needs to change.

2023-11-28 19:29 UTC, swopebe commented on clusters/hosted_control_planes/hosted_create_bare_metal.adoc
> +    --api-server-address=api.${HOSTED_CLUSTER_NAME}.${BASEDOMAIN}
Please see the standards here: https://www.ibm.com/docs/en/ibm-style?topic=elements-commands

The entire RHACM doc needs to fit these standards, so that one guide doesn't look different from the other. IBM Tech writers and RH tech writers use this manual and these standards for many years now, but sometimes things slip. 

With contributions coming from different directions, we are working to ensure IBM and RH standards are met. These standards are set for UX, Accessibility, Translation, etc... 

See the overview and reasons for the manuals here: https://www.ibm.com/docs/en/ibm-style?topic=style-overview

I will remind my team, as well, though we just had a meeting and agreed this is what we should be doing so that we are consistent.

2023-11-28 19:33 UTC, swopebe commented on clusters/hosted_control_planes/hosted_create_bare_metal.adoc
> +    --api-server-address=api.${HOSTED_CLUSTER_NAME}.${BASEDOMAIN}
If we want to merge, I will open an issue and this can be changed for another refresh?

2023-11-29 14:05 UTC, swopebe approved these changes
approving to merge

2023-11-29 21:38 UTC, swopebe commented
I cannot merge this because of the conflict. I cannot resolve in a fork.

2023-11-30 13:01 UTC, swopebe commented on clusters/hosted_control_planes/scaling_nodepool_hosted_ibmz.adoc
>  NAME                                                                           VERSION       AVAILABLE   PROGRESSING   DEGRADED   SINCE   MESSAGE
The problem is that Hypershift has many contributors at this point and so we don't want to keep propagating things that will make life harder and are not beneficial. 

My goal is to always simplify the doc, given all our team is keeping up with, with PM and engineering help. I have more support now that might not have been there before to keep things simpler.

 We may have some instances where things get merged without question; we are thinking more critically about what we add to the doc more now. Even with outside contributions, our team has to maintain these documents, release notes, and everything that comes with it, so with outputs, I just asked the team to consider how much we need from the output and what does the user have to see.

2023-12-01 17:38 UTC, closed without merging