https://issues.redhat.com/browse/ACM-8724
open-cluster-management/rhacm-docs pull request #5884
Opened 2023-11-28 16:09 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-8724

2023-11-28 16:09 UTC, jc-berger commented on business_continuity/backup_restore/backup_install.adoc
> +=== For default secrets
The Jira had discussion around organization and layout of content. 

Reviewers, please let me know what you think of my changes to make each "section" of the prereqs it's own heading, including steps for the user to take.

2023-11-28 16:13 UTC, birsanv commented on business_continuity/backup_restore/backup_hub_config.adoc
> +*Note:* To backup the primary hub data, you do not need an `active-passive` configuration. You can simply backup and store the hub data. This way, if there is an issue or failure, you can deploy a ne
looks good

2023-11-28 16:28 UTC, birsanv requested changes

2023-11-28 16:28 UTC, birsanv commented on business_continuity/backup_restore/backup_install.adoc
> +=== For default secrets
For default secrets is confusing ; you don't do. this step for the benefit of the default secret .. you just create the secret

Suggest :
=== Create the storage location secret

2023-11-28 16:28 UTC, birsanv commented on business_continuity/backup_restore/backup_install.adoc
> +=== For both active and passive hub clusters
This doesn't work at all.. the content was changed slightly and this makes it incorrect;  let's not change that 

For example : Manually install the cluster backup and restore operator. is not a step ; you basically manually enable the operator by editing `MultiClusterHub` resource by setting the `cluster-backup` ...

2023-11-28 16:28 UTC, birsanv commented on business_continuity/backup_restore/backup_install.adoc
> +=== For created secrets when you create a `DataProtectionApplication` resource
same comment as the secret section ; this should be

=== Create a `DataProtectionApplication` resource

2023-11-28 16:28 UTC, birsanv commented on business_continuity/backup_restore/backup_install.adoc
> +=== For both active and passive hub clusters
Instead of 

=== For both active and passive hub clusters

I would suggest not calling what hub you are on , just summarize the step

=== Enable backup operator

2023-11-28 16:28 UTC, birsanv commented on business_continuity/backup_restore/backup_install.adoc
> +. From your {ocp} cluster, install the {product-title} operator version {product-version}.x. The `MultiClusterHub` resource is automatically created when you install {product-title-short} and display
Keep the content as it was before

2023-11-28 16:28 UTC, birsanv commented on business_continuity/backup_restore/backup_install.adoc
> +=== For passive hub clusters only
Add this under the === Enable backup operator ( what you call === For both active and passive hub clusters )

2023-11-28 19:46 UTC, birsanv approved these changes
lgtm; thanks !

2023-11-29 14:30 UTC, dockerymick requested changes
Will you explain why the change from bullet point to header in the Prerequisites section? I noticed that "For both active and passive hub clusters" and "For passive hub clusters" was removed. 

Here is a screen capture of what i see 
<img width="1690" alt="Screenshot 2023-11-29 at 9 06 11 AM" src="https://github.com/stolostron/rhacm-docs/assets/60616885/acacebfc-3690-4240-ab79-8bb5838e3a2c">

2023-11-29 14:30 UTC, dockerymick commented on business_continuity/backup_restore/backup_hub_config.adoc
> +*Note:* To backup the primary hub data, you do not need an `active-passive` configuration. You can simply backup and store the hub data. This way, if there is an issue or failure, you can deploy a ne
```suggestion
*Note:* To backup the primary hub cluster data, you do not need an `active-passive` configuration. You can simply backup and store the hub cluster data. This way, if there is an issue or failure, you can deploy a new hub cluster and restore your primary hub cluster data on this new hub cluster. To reduce the time to recover the primary hub cluster data, you can use an `active passive` configuration; however, it is not a necessity.                                                        
```

2023-11-29 14:30 UTC, dockerymick commented on business_continuity/backup_restore/backup_install.adoc
> +You must meet the following prerequisites to enable and use the backup and restore operator.
```suggestion
You must meet the following prerequisites to enable and use the backup and restore operator:
```

2023-11-29 14:30 UTC, dockerymick commented on business_continuity/backup_restore/backup_install.adoc
> +=== Create the storage location secret
This is throwing me off because it is rendering as a step. Is this a prereq for both the active and passive hub cluster? When we list prereqs, it is usually an unordered list. 
```suggestion
- Create the storage location secret. Complete the steps for link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html/backup_and_restore/oadp-application-backup-and-restore#oadp-creating-default-secret_installing-oadp-aws[Creating a default Secret] for the cloud storage where the backups are saved. You must create the secret resource in the OADP Operator namespace, which is located in the backup component namespace.
```

2023-11-29 14:30 UTC, dockerymick commented on business_continuity/backup_restore/backup_install.adoc
> +. Complete the steps for link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html/backup_and_restore/oadp-application-backup-and-restore#oadp-creating-default-secret_
```suggestion
```

2023-11-29 14:30 UTC, dockerymick commented on business_continuity/backup_restore/backup_install.adoc
> +=== Enable backup operator
```suggestion
=== For both active and passive hub clusters

. Enable backup operator for both your active and passive hub clusters.
+
```

2023-11-29 14:30 UTC, dockerymick commented on business_continuity/backup_restore/backup_install.adoc
> +=== Create a `DataProtectionApplication` resource
```suggestion
. Create a `DataProtectionApplication` resource for your passive hub cluster.
+
```

2023-11-29 14:30 UTC, dockerymick commented on business_continuity/backup_restore/backup_install.adoc
> +. Before you run the restore operation on the passive hub cluster, manually configure the hub cluster and install all operators on the active hub cluster and in the same namespace as the active hub c
```suggestion

=== For passive hub clusters

. Before you run the restore operation on the passive hub cluster, manually configure the hub cluster and install all operators on the active hub cluster and in the same namespace as the active hub cluster. 
```

2023-11-30 16:01 UTC, swopebe commented on business_continuity/backup_restore/backup_install.adoc
I think we need to have a quick hang out on this topic.

2023-12-04 17:12 UTC, swopebe approved these changes
same question as the other

2023-12-05 22:00 UTC, dockerymick approved these changes
Since you updated the anchor/ID (hashtag before the subtitles), be mindful to update the anchor for link references throughout the doc. This prevents broken links. I did a search in VSC for `#install-backup-and-restore` and noticed that there were link references in the following files:

business_cont_overview.adoc
backup_intro.adoc
known_issues_continuity.adoc (2 link references)


change install-backup-and-restore --> dr4hub-install-backup-and-restore

2023-12-06 18:30 UTC, dockerymick approved these changes
Verified that the links work as expected. Thanks Jake!

2023-12-06 19:07 UTC, merged