changes for 2.8
open-cluster-management/rhacm-docs pull request #5885
Opened 2023-11-28 16:23 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-8724 

See PR for 2.9: https://github.com/stolostron/rhacm-docs/pull/5884/files

2023-11-28 19:47 UTC, birsanv approved these changes
lgtm

2023-12-01 16:08 UTC, swopebe commented on business_continuity/backup_restore/backup_install.adoc
> +=== Create the storage location secret
creating

2023-12-04 17:11 UTC, swopebe approved these changes
This looks so much more organized. One question, the inner level headers, do those not need identifiers on them for the build? Like this: `[#dr4hub-config]`. Approving.

2023-12-04 23:12 UTC, birsanv requested changes

2023-12-04 23:12 UTC, birsanv commented on business_continuity/backup_restore/backup_hub_config.adoc
> +*Note:* To backup the primary hub cluster data, you do not need an `active-passive` configuration. You can simply backup and store the hub cluster data. This way, if there is an issue or failure, you
small typo : it is not a necessity.

should be probably : this is not necessary.

2023-12-04 23:12 UTC, birsanv commented on business_continuity/backup_restore/backup_install.adoc
> +. Enable backup operator for both your active and passive hub clusters.
why do we have this here ?.. >> Enable backup operator for both your active and passive hub clusters.
It's what the title says, nothing extra, just repeating

2023-12-04 23:12 UTC, birsanv commented on business_continuity/backup_restore/backup_install.adoc
> +. Ensure that the {product-title-short} operator is installed in the same namespace as the initial hub cluster. Then create the `DataProtectionApplication` resource and connect to the same storage lo
This is not right : it makes you feel that the creation of  the `DataProtectionApplication` resource is somehow linked with the passive cluster only ( **and connect to the same storage location where the initial hub cluster backed up the data.** )

Line 47 should be : 

Create the `DataProtectionApplication` resource.  When this is done on the passive hub cluster, make sure you connect to the same storage location where the initial hub cluster backed up the data.

This is not needed ( bc the operator is always installed in the same ns, there is no option to change it ) : _Ensure that the {product-title-short} operator is installed in the same namespace as the initial hub cluster._

2023-12-04 23:12 UTC, birsanv commented on business_continuity/backup_restore/backup_install.adoc
>  ** The passive hub cluster must use the same namespace names as the initial hub cluster when you install the backup and restore operator, and any other operators that are configured on the previous h
These 2 are now under the DPA section .. they should go under the >> _Before you run the restore operation on the passive hub cluster._. line 46

Before you run the restore operation, verify that other operators, such as {aap-short}, {ocp} GitOps, or certificate manager are installed. This ensures that the new hub cluster is configured the same way as the initial hub cluster.

The passive hub cluster must use the same namespace names as the initial hub cluster when you install the backup and restore operator, and any other operators that are configured on the previous hub cluster.

2023-12-05 19:48 UTC, jc-berger commented on business_continuity/backup_restore/backup_install.adoc
> +. Enable backup operator for both your active and passive hub clusters.
Thanks! Let me know if you think it's too redundant. From an accessibility standpoint, like a screenreader, we want to proceed most all instructions with a prompt for the user to complete the instructions. It makes it more accessible for all users to understand they are about to be expected to complete a series of actions or tasks.

2023-12-05 19:49 UTC, jc-berger commented on business_continuity/backup_restore/backup_install.adoc
> +. Ensure that the {product-title-short} operator is installed in the same namespace as the initial hub cluster. Then create the `DataProtectionApplication` resource and connect to the same storage lo
Thanks, Valentina! Let me know what you think of the revisions!

2023-12-05 20:25 UTC, birsanv requested changes
I made a comment on line 43; everything else is fine

You can have my approval with or without that change; I didn't want to approve directly so you don't miss this last comment

2023-12-05 20:25 UTC, birsanv commented on business_continuity/backup_restore/backup_install.adoc
> +. Enable backup operator for both your active and passive hub clusters.
I would take this out since it doesn't say anything other than repeats the title ( Enable backup operator for both your active and passive hub clusters. )
I made the same comment before so maybe there is a good reason you kept this in :) I don't have a strong opinion it's just that it doesn't help in any way 

Everything else looks good

2023-12-05 20:50 UTC, birsanv approved these changes
lgtm thanks!

2023-12-06 18:32 UTC, dockerymick approved these changes
Verified that the links are working as expected. Thanks again Jake!

2023-12-06 19:07 UTC, merged