https://issues.redhat.com/browse/ACM-8832
open-cluster-management/rhacm-docs pull request #5919
Opened 2023-12-04 17:37 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-8832

2023-12-04 17:38 UTC, jc-berger commented on clusters/release_notes/known_issues.adoc
> +These error messages have no impact on {mce-short} and {product-title-short}. Therefore, you do not need to take any action to resolve these errors.
Doc reviewers, please help me confirm I am using the proper prod references here for MCE and ACM.

2023-12-04 17:38 UTC, jc-berger commented on clusters/release_notes/known_issues.adoc
> +When you upgrade from {mce-short} to MCE 2.4.1, you might find a `StorageVersionMigration` error in the log of the cluster-manager pods under the namespace of {mce-short}. See the following sample of
Doc reviewers, I need to say, from MCE 2.4.0 to MCE 2.4.1. 

Would we have different product references for the different versions?

2023-12-04 18:05 UTC, swopebe requested changes

2023-12-04 18:05 UTC, swopebe commented on clusters/release_notes/known_issues.adoc
> +When you upgrade from {mce-short} to MCE 2.4.1, you might find a `StorageVersionMigration` error in the log of the cluster-manager pods under the namespace of {mce-short}. See the following sample of
You can say that, to ensure you don't mean from 2.3.0 or something, unless that is included. If it is specific to 2.4.0, then yes. If `cluster-manager` is a resource, it should be coded. We won't use directional language like under--best to always rephrase that as _from the namespace_, or _within the namespace_. I am not sure about that whole line:

namespace of {mce-short}    (What is the namespace, and let's write it here)

The `<instert-variable>` namespace 

Example from other docs: ...is available in the `openshift-monitoring` namespace.

2023-12-05 07:43 UTC, elgnay commented on clusters/release_notes/known_issues.adoc
> +When you upgrade from {mce-short} to MCE 2.4.1, you might find a `StorageVersionMigration` error in the log of the cluster-manager pods under the namespace of {mce-short}. See the following sample of
This issue only happens when upgrading from 2.4.0 to 2.4.1. 

`cluster-manager` is the component name and it runs in `multicluster-engine` namespace.

2023-12-05 21:05 UTC, swopebe commented on clusters/release_notes/known_issues.adoc
> +These error messages have no impact on {mce-short} and {product-title-short}. Therefore, you do not need to take any action to resolve these errors.
Yes, the references are fine, however line 55 mentions RHACM and this is MCE (cluster) doc where the user may not have RHACM yet. Not sure we need to have {product-title-short}. I would put early in the description that the error messages do not require resolution, instead of the bottom. I will approve with those suggestions.

2023-12-05 21:05 UTC, swopebe approved these changes

2023-12-05 21:07 UTC, swopebe commented on clusters/release_notes/known_issues.adoc
> +
Wait, sorry, I missed this...we still need to change: that run in the namespace of {mce-short} to fit normal references of namespace in Kubernetes products.

2023-12-05 21:07 UTC, swopebe requested changes
sorry, I see a change still needed that I mentioned earlier.

2023-12-05 21:09 UTC, swopebe commented on clusters/release_notes/known_issues.adoc
> +When you upgrade from {mce-short} to MCE 2.4.1, you might find a `StorageVersionMigration` error in the log of the cluster-manager pods under the namespace of {mce-short}. See the following sample of
@jc-berger see the statement above with the actual namespace. 

runs in `multicluster-engine` namespace (Namespace name is not the same as the product name {mce-short}.

2023-12-06 18:52 UTC, swopebe commented on clusters/release_notes/known_issues.adoc
> +
Ok, I think we should meet.

2023-12-06 19:01 UTC, swopebe approved these changes
chatted for a moment, approving.

2023-12-06 19:07 UTC, merged