https://issues.redhat.com/browse/ACM-8727
open-cluster-management/rhacm-docs pull request #5927
Opened 2023-12-05 20:41 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-8727

2023-12-05 20:54 UTC, xiangjingli commented
/lgtm

2023-12-05 20:55 UTC, xiangjingli commented
/approve

2023-12-05 21:11 UTC, swopebe commented on release_notes/known_issues_application.adoc
> +The helm chart with secret dependencies is only supported in the helm binary CLI. It is not supported in the operator SDK helm library. The {product-title-short} subscription controller applies the o
see third-party doc to get the product names documented correctly: https://helm.sh/

2023-12-06 16:08 UTC, swopebe requested changes

2023-12-06 16:08 UTC, swopebe commented on release_notes/known_issues_application.adoc
> +The username and password are given by the referred Kubernetes secret resource `dbsecret`. For example, see the following sample `value.yaml`:
This needs to be completed:

See the `value.yaml` file.

2023-12-06 16:08 UTC, swopebe commented on release_notes/known_issues_application.adoc
> +Using helm chart, you can define privacy data in a Kubernetes secret and refer to this secret within the `value.yaml` of the helm chart.
`value.yaml` file. I think this is mentioned in IBM manual, as well.

2023-12-06 16:08 UTC, swopebe commented on release_notes/known_issues_application.adoc
> +//2.9:ACM-8727
Is it just the "RHACM" subscription @xiangjingli ?  (Or does it have another name?)

2023-12-06 16:08 UTC, swopebe commented on release_notes/known_issues_application.adoc
> +Using helm chart, you can define privacy data in a Kubernetes secret and refer to this secret within the `value.yaml` of the helm chart.
https://www.ibm.com/docs/en/ibm-style?topic=elements-files-directories

2023-12-06 17:12 UTC, xiangjingli commented on release_notes/known_issues_application.adoc
> +The helm chart with secret dependencies is only supported in the helm binary CLI. It is not supported in the operator SDK helm library. The {product-title-short} subscription controller applies the o
The `operator SDK helm library`  seems appropriate term 

It is from the operator SDK project https://github.com/operator-framework/operator-sdk
and the helm library we leveraged is from its internal helm lib

https://github.com/operator-framework/operator-sdk/tree/master/internal/helm

2023-12-06 17:20 UTC, xiangjingli commented on release_notes/known_issues_application.adoc
> +//2.9:ACM-8727
Yes, it is just the issue in the RHACM subscription

2023-12-06 19:13 UTC, swopebe commented on release_notes/known_issues_application.adoc
> +Using helm chart, you can define privacy data in a Kubernetes secret and refer to this secret within the `value.yaml` of the helm chart.
This should be as shown in the style guide:

... within the `value.yaml` _file._

2023-12-06 19:13 UTC, swopebe commented on release_notes/known_issues_application.adoc
> +Using helm chart, you can define privacy data in a Kubernetes secret and refer to this secret within the `value.yaml` of the helm chart.
File only italicized for emphasis here, not in the actual doc.

2023-12-06 19:14 UTC, swopebe commented on release_notes/known_issues_application.adoc
> +The username and password are given by the referred Kubernetes secret resource `dbsecret`. For example, see the following sample `value.yaml`:
same here.

2023-12-06 19:16 UTC, swopebe approved these changes
Looks great, it took a while for me to see your changes but I finally did. Made one small change to the operator name bc one instance was lower case, the other was not. Either way, we should be consistent.

2023-12-06 19:20 UTC, merged