https://issues.redhat.com/browse/ACM-8880
open-cluster-management/rhacm-docs pull request #5935
Opened 2023-12-06 14:46 UTC by oafischer

2023-12-06 14:51 UTC, dockerymick approved these changes
Made some comments

2023-12-06 14:51 UTC, dockerymick commented on troubleshooting/trouble_observability.adoc
> +. If you create your own storageClass for a Bare Metal cluster, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/storage/index#persistent-storage-u
ACM 2.9 was tested on OCP 4.12. However, we can link to OCP 4.14 from the HyperShift docs. I have to find that convo, I forget if you were on PTO when this was discussed. 

```suggestion
. If you create your own storageClass for a Bare Metal cluster, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html-single/storage/index#persistent-storage-using-nfs[Persistent storage using NFS].
```

2023-12-06 14:51 UTC, dockerymick commented on troubleshooting/trouble_observability.adoc
>  . To ensure that the observability component can find the default storageClass, update the `storageClass` parameter in the `multicluster-observability-operator` CRD. Your parameter might resemble the
Will you also update the "CRD" instance. Change to custom resource definition
```suggestion
. To ensure that the observability component can find the default storageClass, update the `storageClass` parameter in the `multicluster-observability-operator` custom resource definition. Your parameter might resemble the following value:
```

2023-12-06 14:51 UTC, swopebe requested changes

2023-12-06 14:51 UTC, swopebe commented on troubleshooting/trouble_observability.adoc
> +. If you create your own storageClass for a Bare Metal cluster, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/storage/index#persistent-storage-u
I think like most of the doc, we shoul d be pointing to 4.12, remember PM focus to link to 4.12 as what is known -- only Hypershift links to later.

2023-12-06 14:54 UTC, oafischer commented on troubleshooting/trouble_observability.adoc
> +. If you create your own storageClass for a Bare Metal cluster, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/storage/index#persistent-storage-u
Updated

2023-12-06 16:16 UTC, dockerymick approved these changes

2023-12-07 20:09 UTC, berenss approved these changes
lgtm

2023-12-08 08:25 UTC, merged