[ACM-8923]: Update units of measurement in hosted sizing guidance
open-cluster-management/rhacm-docs pull request #5936
Opened 2023-12-06 16:16 UTC by lahinson

Related Jira: https://issues.redhat.com/browse/ACM-8923

2023-12-06 16:21 UTC, zanetworker commented
/lgtm thank you for the swift handling Laura, as always :)

2023-12-06 16:31 UTC, jeniferh commented
LGTM thanks!

2023-12-06 23:32 UTC, gqlo commented
/lgtm  Thansk Laura :)

2023-12-06 23:32 UTC, gqlo approved these changes

2023-12-06 23:33 UTC, gqlo approved these changes

2023-12-07 16:12 UTC, dockerymick commented on clusters/hosted_control_planes/hosted_sizing_guidance.adoc
> +| Number of worker vCPUs / 5 total vCPU requests per hosted control plane
the backslash is a bit confusing for me. Based on the other rows it seems it seems like a math problem. I am taking a look at the [Mathematical equations](https://www.ibm.com/docs/en/ibm-style?topic=measurement-mathematical-equations) section from the Style guide
```suggestion
| Number of worker vCPUs divided by 5 total vCPU requests per hosted control plane
```

2023-12-07 16:18 UTC, dockerymick requested changes

2023-12-07 16:18 UTC, dockerymick commented on clusters/hosted_control_planes/hosted_sizing_guidance.adoc
> +| Number of worker vCPUs / 5 total vCPU requests per hosted control plane
the backslash is a bit confusing for me. Based on the other rows it seems it seems like a math problem. I am taking a look at the [Mathematical equations](https://www.ibm.com/docs/en/ibm-style?topic=measurement-mathematical-equations) section from the Style guide
```suggestion
| Number of worker vCPUs divided by 5 total vCPU requests per hosted control plane
```

2023-12-07 16:18 UTC, dockerymick commented on clusters/hosted_control_planes/hosted_sizing_guidance.adoc
> +| Number of vCPUS / (2.9 measured idle vCPU usage + (QPS target rate / 1000) * 9.0 measured vCPU usage per 1000 QPS increase)
is 2.9 the explicit number or are you referring to ACM 2.9 vCPU usage?
```suggestion
| Number of vCPUS/(2.9 measured idle vCPU usage + (QPS target rate/1000) * 9.0 measured vCPU usage per 1000 QPS increase)
```

2023-12-07 16:42 UTC, lahinson commented on clusters/hosted_control_planes/hosted_sizing_guidance.adoc
> +| Number of worker vCPUs / 5 total vCPU requests per hosted control plane
Good point! Because we use mathematical symbols in other places in that table, I think we should replace the slash with the division sign, as it looks like the division sign is used in the Mathematical equations topic in IBM Style.

2023-12-07 17:05 UTC, lahinson commented
@dockerymick I replaced the slashes in the equations with division signs (÷), which aligns with what IBM Style uses. Thanks!

2023-12-07 17:22 UTC, dockerymick approved these changes
One more question. Otherwise, this looks good

2023-12-07 17:22 UTC, dockerymick commented on clusters/hosted_control_planes/hosted_sizing_guidance.adoc
> +| Number of worker vCPUs  5 total vCPU requests per hosted control plane
Should there be a comma or semicolon here?

2023-12-07 17:22 UTC, dockerymick commented on clusters/hosted_control_planes/hosted_sizing_guidance.adoc
> +| Number of vCPUS ÷ (2.9 measured idle vCPU usage + (QPS target rate ÷ 1000) * 9.0 measured vCPU usage per 1000 QPS increase)
It seems like you should use the regular multiplication sign (×) 
I copied the symbol from the SG

What are your thoughts?

2023-12-07 17:41 UTC, lahinson commented on clusters/hosted_control_planes/hosted_sizing_guidance.adoc
> +| Number of worker vCPUs  5 total vCPU requests per hosted control plane
oops! there was supposed to be a division sign there. I'll add that.

2023-12-07 17:41 UTC, lahinson commented on clusters/hosted_control_planes/hosted_sizing_guidance.adoc
> +| Number of vCPUS ÷ (2.9 measured idle vCPU usage + (QPS target rate ÷ 1000) * 9.0 measured vCPU usage per 1000 QPS increase)
Yep, you're right. IBM Style says to use the multiplication sign (x). I'll make that update.

2023-12-07 17:44 UTC, dockerymick commented on clusters/hosted_control_planes/hosted_sizing_guidance.adoc
> +| Number of vCPUS ÷ (2.9 measured idle vCPU usage + (QPS target rate ÷ 1000) * 9.0 measured vCPU usage per 1000 QPS increase)
Instead of using the "x" i would use the Unicode character that i have in the suggestion. It can be confusing to see an "x" during translation 
```suggestion
| Number of vCPUS ÷ (2.9 measured idle vCPU usage + (QPS target rate ÷ 1000) × 9.0 measured vCPU usage per 1000 QPS increase)
```

2023-12-07 17:56 UTC, lahinson commented on clusters/hosted_control_planes/hosted_sizing_guidance.adoc
> +| Number of vCPUS ÷ (2.9 measured idle vCPU usage + (QPS target rate ÷ 1000) * 9.0 measured vCPU usage per 1000 QPS increase)
@dockerymick I replaced the asterisks (*) with the unicode for the multiplication sign. In GitHub, the unicode doesn't render, so we'll need to check on staging to make sure that everything looks ok.

2023-12-07 18:04 UTC, merged

2023-12-07 18:07 UTC, dockerymick commented on clusters/hosted_control_planes/hosted_sizing_guidance.adoc
> +| Number of vCPUS ÷ (2.9 measured idle vCPU usage + (QPS target rate ÷ 1000) * 9.0 measured vCPU usage per 1000 QPS increase)
Thank you!