https://issues.redhat.com/browse/ACM-8639 CIM update reqs
open-cluster-management/rhacm-docs pull request #5963
Opened 2023-12-12 08:31 UTC by oafischer

Also for 2.8 and 2.7.

2023-12-12 11:41 UTC, avishayt commented on clusters/cluster_lifecycle/cim_enable.adoc
> +. Modify the `Provisioning` resource to allow the Bare Metal Operator to watch all namespaces by running the following command:
This is only needed if the provisioning resource was found.

So:
1. Check if the provisioning resource exists
2. If not, create it
3. If yes, modify it

2023-12-12 11:42 UTC, avishayt reviewed
One small comment, otherwise looks good!

2023-12-12 11:43 UTC, oafischer commented on clusters/cluster_lifecycle/cim_enable.adoc
> +. Modify the `Provisioning` resource to allow the Bare Metal Operator to watch all namespaces by running the following command:
Ah I see, I'll restructure this section then.

2023-12-12 15:01 UTC, oafischer commented
Updated, this one is a little convoluted, if someone sees a way to simplify all the checks the user has to do feel free to make suggestions.

2023-12-12 15:38 UTC, swopebe commented on clusters/cluster_lifecycle/cim_enable.adoc
There should always be a phrase between a header and the content.

2023-12-12 15:40 UTC, swopebe commented on clusters/cluster_lifecycle/cim_enable.adoc
> +You can check if you already have a bare metal host custom resource definition by running the following command:
I feel these are steps, and should reflect a task, even though they are technical contingent on the environment. You get around that by using a description between the header and the task.

2023-12-12 15:40 UTC, swopebe commented on clusters/cluster_lifecycle/cim_enable.adoc
> +If you do not have a `Provisioning` resource, you must create the resource. If you already have a `Provisioning` resource, you must modify the resource if your hub cluster is installed on one of the
Same here.

2023-12-12 15:40 UTC, swopebe commented on clusters/cluster_lifecycle/cim_enable.adoc
same here.

2023-12-12 15:45 UTC, swopebe requested changes
I think the wording is great, the format should probably be more like a task and you can get some ideas here: https://www.ibm.com/docs/en/ibm-style?topic=format-procedures#indicating-optional-and-conditional-steps

2023-12-12 15:45 UTC, swopebe commented on clusters/cluster_lifecycle/cim_enable.adoc
See this for conditional steps.

2023-12-12 16:23 UTC, oafischer commented
Updated again, thanks for the link to that IBM Style topic @swopebe, it was helpful but I had to do some rearranging to conform with it. Let me know how it looks now.

2023-12-12 16:46 UTC, swopebe approved these changes
Works for me, the only thing I see is there is a section with one step...now with the new format, that can stand on it's own with the bulleted options--if it works. If not, I am not gonna fuss about it because it is tricky.

2023-12-14 10:25 UTC, avishayt commented
LGTM

2023-12-14 10:26 UTC, merged