added known issue for nmstate limitation
open-cluster-management/rhacm-docs pull request #6007
Opened 2024-01-09 19:18 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-9128

2024-01-09 20:53 UTC, swopebe commented on clusters/release_notes/known_issues.adoc
> +=== Limitation with `nmstate`
I am making an update to our internal docs to remind us all that instead of codeblock here in headers, we use _italics_. (It's because of the rendering, which we can revisit, but that was decided as a team a while ago.)

2024-01-09 20:55 UTC, swopebe commented on clusters/release_notes/known_issues.adoc
> +Make your development quicker by configuring copy and paste features. To configure the `copy-from-mac` feature in the the `assisted-installer`, complete the following steps:
Make your development quicker 

to 

Develop quicker

Some examples of voice and verb usage here: https://www.ibm.com/docs/en/ibm-style?topic=grammar-verbs

2024-01-09 20:56 UTC, swopebe commented on clusters/release_notes/known_issues.adoc
> +
This issue is the `nmstate` limitation.

??? 

Is this referring to the entry in the doc, which is a "limitation" in the doc? I think this is clear already and is redundant. It seems like ending a task with: This is the procedure. (?)

2024-01-09 20:57 UTC, swopebe requested changes
See comments.

2024-01-10 08:15 UTC, filanov commented on clusters/release_notes/known_issues.adoc
> +
it's not really an nmstate limitation, it's the way assisted is using nmstate, we are using configuration generation  that doesn't support this option, but there is a workaround that is worth mentioning. 
Ori will provide the details

2024-01-10 08:19 UTC, ori-amizur commented on clusters/release_notes/known_issues.adoc
> +
It is nmstate limitation.  It needs the mac-address in the interface to copy the mac-address from.

2024-01-15 18:38 UTC, jc-berger commented on clusters/release_notes/known_issues.adoc
> +. Go to the `nmstate` definition interface.
So, am I right these are steps to configure `copy-from-mac`? 

Or, are these steps the workaround for the `nmstate` limitation?

2024-01-16 08:40 UTC, ori-amizur commented on clusters/release_notes/known_issues.adoc
> +If the `mac-address` is provided outside the `nmstate` definition, the `nmstate` cannot implement the `copy-from-mac` feature.
In order to use `copy-from-mac` the mac-address must be part of the nmstate definition.
The same mac-address must be part of the interface-mac mapping which is provided outside of nmstate definition.
It means that if we want to use `copy-from-mac` we need to provide the mac-address twice.

2024-01-16 08:43 UTC, ori-amizur commented on clusters/release_notes/known_issues.adoc
> +. Go to the `nmstate` definition interface.
The mac-address today doesn't exist in the nmstate definition.  It needs to be copied from the interface-mac mapping.

2024-01-17 15:55 UTC, oafischer approved these changes
lgtm

Optional: Use "As a result" instead of "therefore". Translation of "therefore" can be a little weird/have different meanings in some languages.

2024-01-17 16:16 UTC, merged