https://issues.redhat.com/browse/ACM-9296 Nutanix prereq
open-cluster-management/rhacm-docs pull request #6030
Opened 2024-01-17 12:34 UTC by oafischer

2.9 only

2024-01-17 13:02 UTC, jelkosz commented
lgtm

2024-01-17 14:17 UTC, dockerymick requested changes
Thanks for making the updates! I made some suggestions

2024-01-17 14:17 UTC, dockerymick commented on clusters/cluster_lifecycle/create_cluster_cli.adoc
> +*Note:* If you use the Nutanix platform, make sure that the `ClusterImageSet` that you want to use for the Nutanix deployment has a `x86_64` `releaseImage` and that the `visible` annotation has the `
```suggestion
*Note:* If you use the Nutanix platform, be sure to use `x86_64` architecture for the `releaseImage` in the `ClusterImageSet` resource and set the `visible` annotation value to `true`. See the following example:
```

2024-01-17 14:17 UTC, dockerymick commented on clusters/cluster_lifecycle/create_cluster_cli.adoc
> +[source,YAML]
all instances throughout the doc uses lowercase. Link to ASCII doc source block: https://docs.asciidoctor.org/asciidoc/latest/verbatim/source-blocks/ 
```suggestion
[source,yaml]
```

2024-01-17 14:17 UTC, dockerymick commented on clusters/cluster_lifecycle/create_cluster_cli.adoc
> +    visible: 'true'
Will you verify if the single quotes are required? I believe this is another clean up that we need to do (Remove quotation marks out of YAML samples)
```suggestion
    visible: true
```

2024-01-17 14:21 UTC, oafischer commented on clusters/cluster_lifecycle/create_cluster_cli.adoc
> +    visible: 'true'
@jelkosz ?

2024-01-18 11:28 UTC, jelkosz commented on clusters/cluster_lifecycle/create_cluster_cli.adoc
> +    visible: 'true'
The apostrophe has to be there, the type is string here.

2024-01-18 11:32 UTC, oafischer commented on clusters/cluster_lifecycle/create_cluster_cli.adoc
> +    visible: 'true'
Thanks for confirming! And thanks for reviewing @dockerymick, let me know if it looks good now.

2024-01-18 13:08 UTC, dockerymick commented on clusters/cluster_lifecycle/create_cluster_cli.adoc
> +    visible: 'true'
Thanks Oliver! Taking a look now

2024-01-18 13:10 UTC, dockerymick approved these changes
Added the single quotes back after feedback from @jelkosz 
Other than that, this looks good to me !

2024-01-18 13:10 UTC, dockerymick commented on clusters/cluster_lifecycle/create_cluster_cli.adoc
> +*Note:* If you use the Nutanix platform, be sure to use `x86_64` architecture for the `releaseImage` in the `ClusterImageSet` resource and set the `visible` annotation value to `true`. See the follow
Adding single quote back to the value  @oafischer 
```suggestion
*Note:* If you use the Nutanix platform, be sure to use `x86_64` architecture for the `releaseImage` in the `ClusterImageSet` resource and set the `visible` annotation value to `'true'`. See the following example:
```

2024-01-18 13:20 UTC, merged