https://issues.redhat.com/browse/ACM-8899 - sync
open-cluster-management/rhacm-docs pull request #6040
Opened 2024-01-18 20:02 UTC by swopebe

2024-01-18 21:56 UTC, dockerymick requested changes

2024-01-18 21:56 UTC, dockerymick commented on governance/create_gatekeeper.adoc
> +* <<gatekeeper-operator-sample,Gatekeeper operator custom resource>>
The references to subsections should be removed from the TOC, it'll appear in the TOC of the product doc

2024-01-18 21:56 UTC, dockerymick commented on governance/create_gatekeeper.adoc
> +The gatekeeper operator exposes a setting in the CRD within the `auditFromCache` audit, which is disabled by default. If you set it to `Enabled`, you break your constraints because the cache requires
change gatekeeper operator to Gatekeeper Operator

https://github.com/gatekeeper/gatekeeper-operator

@mprahl would you help confirm? I can also add this task to my clean up issue @swopebe

2024-01-18 21:56 UTC, dockerymick commented on governance/create_gatekeeper.adoc
> +. Set `auditFromCache` to `Automatic` in the `operator.gatekeeper.sh/v1alpha1` API, as displayed in the following example:
```suggestion
. Set `auditFromCache` to `Automatic` in the `Gatekeeper` resource, as displayed in the following example:
```

2024-01-18 21:56 UTC, dockerymick commented on governance/create_gatekeeper.adoc
> +kind: Gatekeeper metadata:
This example seems a little off. metadata should be in a new line. @yiraeChristineKim will you confirm?

2024-01-18 21:56 UTC, dockerymick commented on governance/create_gatekeeper.adoc
> +See that the Gatekeeper operator adds `syncOnlys` to the config file in the following example:
```suggestion
See that the Gatekeeper operator adds `syncOnlys` parameter section to the config file in the following example:
```

2024-01-18 21:56 UTC, dockerymick commented on governance/create_gatekeeper.adoc
> +
I assume that the explanation of the setting is displayed from the users screen? Is there a verification step?

2024-01-19 13:37 UTC, mprahl commented on governance/create_gatekeeper.adoc
> +The gatekeeper operator exposes a setting in the CRD within the `auditFromCache` audit, which is disabled by default. If you set it to `Enabled`, you break your constraints because the cache requires
I think at the very least that Gatekeeper should be capitalized. I'm not sure about "operator" though.

2024-01-19 19:24 UTC, swopebe commented on governance/create_gatekeeper.adoc
> +* <<gatekeeper-operator-sample,Gatekeeper operator custom resource>>
I agree, but there already was one here. We decided not to add them, yes?

2024-01-19 19:32 UTC, swopebe commented on governance/create_gatekeeper.adoc
> +The gatekeeper operator exposes a setting in the CRD within the `auditFromCache` audit, which is disabled by default. If you set it to `Enabled`, you break your constraints because the cache requires
operator is not caps, correct. Actually the other operators that we conref are also not capped...(MCE, GH)

2024-01-19 19:33 UTC, swopebe commented on governance/create_gatekeeper.adoc
> +The gatekeeper operator exposes a setting in the CRD within the `auditFromCache` audit, which is disabled by default. If you set it to `Enabled`, you break your constraints because the cache requires
This doc linked doesn't follow the IBM or RH format, so I don't think that is what we should use for standards. I can see if it is officially in a source for naming guidance, however.

2024-01-19 19:35 UTC, swopebe commented on governance/create_gatekeeper.adoc
> +
@dockerymick actually if we are going to say Gatekeeper resource, I would rather write it as it is in the yaml: name: gatekeeper.

2024-01-19 19:37 UTC, swopebe commented on governance/create_gatekeeper.adoc
> +
I was not given verification, actually I wasn't give this as a task. This is all the tempalte provided.

2024-01-19 19:50 UTC, swopebe commented on governance/create_gatekeeper.adoc
> +See the following procedure to create the policy from the console:
I also changed this section because it was a task, but presented in paragraph form and needed a short description.

2024-01-19 19:51 UTC, swopebe commented on governance/create_gatekeeper.adoc
> +See the following procedure to create the policy from the console:
feel free to change short description on line 29.

2024-01-19 19:52 UTC, swopebe commented on governance/create_gatekeeper.adoc
> + name: config
please check the YAML here-- placement of name on both samples.

2024-01-20 18:40 UTC, dockerymick commented on governance/create_gatekeeper.adoc
> +* <<gatekeeper-operator-sample,Gatekeeper operator custom resource>>
Correct, we did agree to not list subsections in the TOC of the file

2024-01-20 18:41 UTC, dockerymick commented on governance/create_gatekeeper.adoc
> +The gatekeeper operator exposes a setting in the CRD within the `auditFromCache` audit, which is disabled by default. If you set it to `Enabled`, you break your constraints because the cache requires
Sounds good, thanks for confirming ! We are on the same page to use "Gatekeeper operator".

2024-01-22 09:34 UTC, yiraeChristineKim commented on governance/create_gatekeeper.adoc
> +
User type `oc explain gatekeeper.spec.audit.auditFromCache` on own terminal

2024-01-22 09:41 UTC, yiraeChristineKim commented on governance/create_gatekeeper.adoc
> +See that the Gatekeeper operator adds `syncOnlys` parameter section to the config file in the following example:
`The gatekeeper operator collects the resources from Constraints that users installed and then inserts them into the Config resource. The gatekeeper operator will create config resources if it does not exist.
`
Can we add this? I think we need to explain where syncOnlys are from

2024-01-22 10:10 UTC, yiraeChristineKim commented on governance/create_gatekeeper.adoc
> + namespace: "gatekeeper-system"
Could you change this to `openshift-gatekeeper-system`

2024-01-22 10:20 UTC, yiraeChristineKim commented on governance/create_gatekeeper.adoc
> +kind: Gatekeeper metadata:
@dockerymick right. `metadata` should be in the new line Thanks!

2024-02-06 02:18 UTC, closed without merging