added content on restoring data
open-cluster-management/rhacm-docs pull request #6051
Opened 2024-01-22 18:51 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-7900

2024-01-22 18:52 UTC, jc-berger commented
@birsanv , thanks for providing awesome content for me to work with! 

I made changes based off Red Hat style guides and language standards. Please let me know if I unintentionally altered meaning with my word changes and edits. Thanks!

2024-01-23 18:09 UTC, jc-berger commented on business_continuity/backup_restore/backup_restore.adoc
> +When you need to use a passive hub cluster, create a new passive hub cluster. If you use an existing passive hub cluster that already has data, then the data on this hub cannot reflect the data avail
something like:

when you need to restore passive data on a cluster, create a new cluster

2024-01-23 18:14 UTC, jc-berger commented on business_continuity/backup_restore/backup_restore.adoc
> +When you need to use a passive hub cluster, create a new passive hub cluster. If you use an existing passive hub cluster that already has data, then the data on this hub cannot reflect the data avail
no need to always say passive. 

"if you use an exisitng hub cluster..."

see nots to help rewrite this section:

Velero updates existing resources if they have changed with the currently restored backup. It does not clean up delta resources, which are resources created by a previous restore and not part of the currently restored backup. This limits the scenarios that can be used when restoring hub data on a new hub. Unless the restore is applied only once, the new hub could not be relibly used as a passive configuration: the data on this hub is not reflective of the data available with the restored resourc

basically, the data is not reflective of what you'd expect on the hub. the hub needs to match the data exactly from the intial hub where the backup originally happened. 

scenario: if you have an exiting hub and your have 3 applications, and you want to use a backup restore hub, then you get the data from the restore and these three applications. So you have lots of data that's not matching the intital hub.

2024-01-23 18:15 UTC, jc-berger commented on business_continuity/backup_restore/backup_restore.adoc
> +When you need to use a passive hub cluster, create a new passive hub cluster. If you use an existing passive hub cluster that already has data, then the data on this hub cannot reflect the data avail
say "cleaned up" INSTEAD of "updated" Clean up is an actual option for the user!

2024-01-23 18:17 UTC, jc-berger commented on business_continuity/backup_restore/backup_restore.adoc
> +When you need to use a passive hub cluster, create a new passive hub cluster. If you use an existing passive hub cluster that already has data, then the data on this hub cannot reflect the data avail
last three sentences of the first paragraph could probably be condensed to one sentence: "The restore cleans up resources created by a previous backup but will not clean up user resources."

2024-01-23 18:21 UTC, jc-berger commented on business_continuity/backup_restore/backup_restore.adoc
> +Use an existing passive hub cluster during a disaster recovery test. In a recovery test, you are only testing the hub backup scenario. Therefore, you want to go back to the primary passive hub cluste
first sentence should be somethign like: 

a disaster recoery test is an example situation where a user would use an exisitng hub cluster for a restore operation.

2024-01-23 18:23 UTC, jc-berger commented on business_continuity/backup_restore/backup_restore.adoc
> +Use an existing passive hub cluster during a disaster recovery test. In a recovery test, you are only testing the hub backup scenario. Therefore, you want to go back to the primary passive hub cluste
remove the "passive" :)

2024-01-23 18:25 UTC, jc-berger commented on business_continuity/backup_restore/backup_restore.adoc
> +When you need to use a passive hub cluster, create a new passive hub cluster. If you use an existing passive hub cluster that already has data, then the data on this hub cannot reflect the data avail
for more help, see the readme for cleaning up hub restore: https://github.com/stolostron/cluster-backup-operator?tab=readme-ov-file#cleaning-up-the-hub-before-restore

2024-01-25 19:20 UTC, jc-berger commented
THanks, @birsanv for your awesome feedback. I've kept my comments in case I need to refer back to them. Otherwise, the new commit is up for review. Thanks!

2024-01-25 20:02 UTC, birsanv requested changes

2024-01-25 20:02 UTC, birsanv commented on business_continuity/backup_restore/backup_restore.adoc
> +A disaster recovery test is an example situation where you would use an existing hub cluster for a restore operation.  In a recovery test, you are only testing the hub backup scenario. Therefore, you
change A disaster recovery test is an example situation where you would use an existing hub cluster
with A disaster recovery test is an example situation where you **could** use an existing hub cluster

2024-01-25 20:02 UTC, birsanv commented on business_continuity/backup_restore/backup_restore.adoc
> +A disaster recovery test is an example situation where you would use an existing hub cluster for a restore operation.  In a recovery test, you are only testing the hub backup scenario. Therefore, you
remove : Therefore, you want to go back to the primary passive hub cluster after it restored the backup data.

2024-01-25 20:02 UTC, birsanv commented on business_continuity/backup_restore/backup_restore.adoc
> +When you need to restore passive data on a cluster, create a new cluster. Velero updates your existing resources if they have changed with the currently restored backup. Velero does not clean up `del
I would change this paragraph with this 

When you need to restore backup data on a cluster, create a new cluster. During the hub restore operation, you can configure the hub backup restore to clean up the existing resources if these resources are not part of the backup data being restored. The restore cleans up resources created by an earlier backup but does not clean up user resources. As a result, resources created by the user on this hub will not be cleaned up so the on this hub is not reflective of the data available with the restored resource.

2024-01-29 16:10 UTC, dockerymick approved these changes
made a suggestion

2024-01-29 16:10 UTC, dockerymick commented on business_continuity/backup_restore/backup_restore.adoc
> +A disaster recovery test is an example situation where you could use an existing hub cluster. In a recovery test, you are only testing the hub backup scenario. In this situation, the initial primary
```suggestion
When you need to restore backup data on a cluster, create a new cluster. During the hub cluster restore operation, you can configure the hub cluster backup restore to clean up the existing resources, if these resources are not part of the backup data being restored. The restore cleans up resources created by an earlier backup but does not clean up user resources. As a result, resources created by the user on this hub cluster are not cleaned up, so the data on this hub cluster is not reflective of the data available with the restored resource.

A disaster recovery test is an example situation where you can use an existing hub cluster. In a recovery test, you are only testing the hub backup scenario. In this situation, the initial primary hub cluster does not create new resources. Instead, the backup data has temporarily changed sides from the primary hub cluster to the passive hub cluster.  
```

2024-01-30 15:09 UTC, dockerymick commented
@jc-berger just noticed that this is going into 2.9_prod branch. Please close this PR and create one for 2.9_stage. The base branch updated automatically after i merged my PR
![Screenshot 2024-01-30 at 10 08 15 AM](https://github.com/stolostron/rhacm-docs/assets/60616885/b5849e27-4363-4e06-8577-8287fcc29687)

I'm not sure why that happened. We can bring it up during the scrum

2024-01-30 16:43 UTC, dockerymick requested changes
Removing approval to bring notice to the base branch change. This was complete due to an automation. Jake is on PTO today and will make updates throughout the week. Thanks!

2024-01-30 17:07 UTC, swopebe commented
No not merge this to PROD, but to STAGE

2024-01-31 15:48 UTC, birsanv approved these changes
lgtm

2024-01-31 15:48 UTC, jc-berger commented
Due to complications with this PR to prod, I will close it. 

See the content in the new PR for 2.10_stage: https://github.com/stolostron/rhacm-docs/pull/6083

2024-01-31 15:48 UTC, closed without merging