OSDOCS#9358: HCP: Document Agent provisioning flow for non BM machines
open-cluster-management/rhacm-docs pull request #6073
Opened 2024-01-30 08:54 UTC by xenolinux

https://issues.redhat.com/browse/OSDOCS-9358

2024-02-15 19:26 UTC, CrystalChun commented on clusters/hosted_control_planes/destroy_hosted_non_bm.adoc
> +oc delete managedcluster <cluster_name>
Quick Q: does a `managedcluster` always get created when running `hcp create cluster`?

2024-02-15 19:27 UTC, CrystalChun commented on clusters/hosted_control_planes/create_cluster_non_bm.adoc
> +    --agent-namespace=${HOSTED_CONTROL_PLANE_NAMESPACE} \
If a note could be added here to ensure this is the namespace where your `Agent` CRs exist (which can be found by `oc get agent -n <this namespace>`

2024-02-15 19:27 UTC, CrystalChun commented on clusters/hosted_control_planes/create_cluster_non_bm.adoc
> +    --agent-namespace=${HOSTED_CONTROL_PLANE_NAMESPACE} \
Might also be nice to have a link or reference to how they can create Agents too

2024-02-15 19:47 UTC, CrystalChun commented on clusters/hosted_control_planes/non_bm_intro.adoc
> +- When you scale down a node pool, Agents are unbound from the corresponding cluster. Before you can reuse the clusters, you must restart them by using the Discovery image to update the number of nod
```suggestion
- When you scale down a node pool, Agents are unbound from the corresponding cluster. Before you can reuse the Agents, you must restart them by using the Discovery image to update the number of nodes.
```

2024-02-15 20:08 UTC, CrystalChun commented on clusters/hosted_control_planes/non_bm_intro.adoc
> +- Each host must be started manually with a Discovery Image that the central infrastructure management provides.
```suggestion
- Each non bare metal host must be booted manually with a Discovery Image ISO that the central infrastructure management provides.
```

2024-02-15 20:10 UTC, CrystalChun commented on clusters/hosted_control_planes/non_bm_intro.adoc
> +- When you scale up a node pool, a machine is created. The Cluster API provider finds an Agent that is approved, is passing validations, is not currently in use, and meets the requirements that are s
```suggestion
- A machine is created for every replica you scale the node pool up by. For every machine, the Cluster API provider finds and installs an Agent that is approved, is passing validations, is not currently in use, and meets the requirements that are specified in the node pool specification. You can monitor the installation of an Agent by checking its status and conditions.
```

2024-02-15 20:12 UTC, CrystalChun commented on clusters/hosted_control_planes/destroy_hosted_non_bm.adoc
> +oc delete managedcluster <cluster_name>
And if it does, how come it's not automatically deleted when running `hcp destroy cluster`?

2024-02-16 01:52 UTC, xenolinux commented on clusters/hosted_control_planes/create_cluster_non_bm.adoc
> +    --agent-namespace=${HOSTED_CONTROL_PLANE_NAMESPACE} \
@CrystalChun Do you have any resource link handy to provide it here? I couldn't find one

2024-02-16 02:02 UTC, xenolinux commented on clusters/hosted_control_planes/destroy_hosted_non_bm.adoc
> +oc delete managedcluster <cluster_name>
TBH I am not sure. But I noticed that we use the `oc delete managedcluster <cluster_name>` command to destroy hosted clusters on [aws](https://github.com/stolostron/rhacm-docs/blob/2.10_stage/clusters/hosted_control_planes/destroy_cluster_aws.adoc), [OpenShift Virtualization](https://github.com/stolostron/rhacm-docs/blob/2.10_stage/clusters/hosted_control_planes/destroy_cluster_kubevirt.adoc), [bare metal](https://github.com/stolostron/rhacm-docs/blob/2.10_stage/clusters/hosted_control_planes/destroy_hosted_bm.adoc#destroying-a-hosted-cluster-on-bare-metal-by-using-the-command-line) as well. Should it just be this`hcp destroy cluster agent --name <cluster_name>` then?

2024-02-16 02:03 UTC, xenolinux commented on clusters/hosted_control_planes/destroy_hosted_non_bm.adoc
> +oc delete managedcluster <cluster_name>
I can update other sections too if required

2024-02-16 10:03 UTC, jparrill requested changes
Looking good :). Dropped some comments.

2024-02-16 10:03 UTC, jparrill commented on clusters/hosted_control_planes/autoscale_node_hosted_cluster_non_bm.adoc
> +oc --kubeconfig ${HOSTED_CLUSTER_NAME}.kubeconfig get nodes
I don't know if this was mentioned before, but you will need to extract the `admin-kubeconfig` secret of the HostedCluster previous to these commands executions. If that was mentioned before, perfect :), if not, this is the command:

```
oc extract -n clusters secret/hosted-admin-kubeconfig --to=./hostedcluster-secrets --confirm
```

output:
```
hostedcluster-secrets/kubeconfig
```

2024-02-16 10:03 UTC, jparrill commented on clusters/hosted_control_planes/create_cluster_non_bm.adoc
> +export OCP_RELEASE=4.14.0-multi
I would change this by an official stable 4.14 version (e.g `4.14.13-x86_64`)

2024-02-16 10:03 UTC, jparrill commented on clusters/hosted_control_planes/destroy_hosted_non_bm.adoc
> +oc delete managedcluster <cluster_name>
We recommend to manage HostedClusters in the same way from creation to deletion. 

e.g: if you create the clusters using manifests, delete them using manifests with `oc apply -f <file>` and `oc delete -f <file>` andalso with `hcp` CLI.

If you use the `hcp` CLI to create the HostedCluster, a new finalizer is included in the HC, so if you creates the HC using the CLI and deletes it using `oc delete xxxx` it will get stuck in deletion.

2024-02-16 10:03 UTC, jparrill commented on clusters/hosted_control_planes/handle_ingress_non_bm.adoc
> +kind: BGPAdvertisement
The BGPAdvertisement works for you? In my env I've only make the L2Advertisement work properly.

2024-02-16 10:03 UTC, jparrill commented on clusters/hosted_control_planes/handle_ingress_non_bm.adoc
> +clusterversion.config.openshift.io/version   4.12z    True        False         3m32s   Cluster version is 4.12z
I would change the 4.12z to the version you mentioned at the beginning of the PR. Have in mind to do that also in the nexts ones.

2024-02-16 10:03 UTC, jparrill commented on clusters/hosted_control_planes/non_bm_intro.adoc
> +- Each non bare metal host must be booted manually with a Discovery Image ISO that the central infrastructure management provides.
put emphasis that this boot should be bootOnce, if not the customer will stay in a loop when the workers get rebooted by the first time.

2024-02-16 10:55 UTC, xenolinux commented on clusters/hosted_control_planes/handle_ingress_non_bm.adoc
> +kind: BGPAdvertisement
sry, I haven't tried `BGPAdvertisement`. This module is copied from the [pre-existing bare metal section](https://github.com/stolostron/rhacm-docs/blob/2.10_stage/clusters/hosted_control_planes/handle_ingress_bm.adoc)

2024-02-16 10:59 UTC, xenolinux commented on clusters/hosted_control_planes/handle_ingress_non_bm.adoc
> +clusterversion.config.openshift.io/version   4.12z    True        False         3m32s   Cluster version is 4.12z
Updated `4.12.z` to `4.14.13-x86_64`

2024-02-16 11:02 UTC, xenolinux commented on clusters/hosted_control_planes/non_bm_intro.adoc
> +- Each non bare metal host must be booted manually with a Discovery Image ISO that the central infrastructure management provides.
Is the `bootOnce` a value that can be set somewhere while booting? Or just mentioning "Each non bare metal host must be booted manually only once with a Discovery Image....." is enough?

2024-02-16 11:05 UTC, xenolinux commented on clusters/hosted_control_planes/destroy_hosted_non_bm.adoc
> +oc delete managedcluster <cluster_name>
Ack'ed. Thanks for the confirmation. I removed the  `oc delete managedcluster <cluster_name>` command.

2024-02-16 11:16 UTC, jparrill commented on clusters/hosted_control_planes/non_bm_intro.adoc
> +- Each non bare metal host must be booted manually with a Discovery Image ISO that the central infrastructure management provides.
No, it's just a way to boot a node. Is enough just to mention it, the bootOnce procedure is just a helper for the user but a parameter or flag in any place. This will depend in the customers BMC, Virtualiser, etc.. so just mentioning that should be enough

sample:

"Make sure you mount the LiveISO in the worker node in BootOnce mode. If not you will need to unmount that LiveISO from the worker once the first reboot happens."

2024-02-16 11:31 UTC, jparrill commented
/lgtm

2024-02-16 16:18 UTC, CrystalChun commented on clusters/hosted_control_planes/create_cluster_non_bm.adoc
> +    --agent-namespace=${HOSTED_CONTROL_PLANE_NAMESPACE} \
Yes here you go! https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.9/html/clusters/cluster_mce_overview#add-host-host-inventory 
Will defer to you and your team for where to best link this!

2024-02-16 16:23 UTC, CrystalChun commented on clusters/hosted_control_planes/autoscale_node_hosted_cluster_non_bm.adoc
> +If 10 minutes pass without requiring the additional capacity, the worker node is removed. On the Agent platform, the agent is decommissioned and can be reused.
I wonder if this line should be moved down here https://github.com/stolostron/rhacm-docs/pull/6073/files#diff-241549552c1d12c34d4987d8dfbf5c0c48a17e05fb2854a527bd2464cb3f61bdR101 wdyt?

2024-02-16 16:24 UTC, CrystalChun commented on clusters/hosted_control_planes/autoscale_node_hosted_cluster_non_bm.adoc
> +The command removes `"spec.autoScaling"`` from the YAML file, adds `"spec.replicas"`, and sets `"spec.replicas"` to the value that you specify.
```suggestion
The command removes `"spec.autoScaling"` from the YAML file, adds `"spec.replicas"`, and sets `"spec.replicas"` to the value that you specify.
```

2024-02-16 16:30 UTC, CrystalChun commented on clusters/hosted_control_planes/create_cluster_non_bm.adoc
> +<2> Ensure that agents are available in the `${HOSTED_CONTROL_PLANE_NAMESPACE}`. You can find the list of agents by using the `oc get agent -n ${HOSTED_CONTROL_PLANE_NAMESPACE}` command.
Sorry, I realize now that having a note in the command the user would run is not such a great idea 😅 Suggestion to merge it into <1> but feel free to do what you think is best!
```suggestion
<1> Typically, the namespace is created by the HyperShift Operator, but agent cluster creation generates a cluster API provider role that needs the namespace to already exist. In the command below, it is also used as the `agent-namespace` flag. Ensure that agents are available in the `${HOSTED_CONTROL_PLANE_NAMESPACE}`. You can find the list of agents by using the `oc get agent -n ${HOSTED_CONTROL_PLANE_NAMESPACE}` command.
```

2024-02-16 16:37 UTC, CrystalChun commented on clusters/hosted_control_planes/scale_nodepool_hosted_non_bm.adoc
> +. After the agents reach the `added-to-existing-cluster` state, verify that you can see the {ocp-short} nodes by entering the following command:
```suggestion
. After the agents reach the `added-to-existing-cluster` state, verify that you can see the {ocp-short} nodes in the hosted cluster by entering the following command:
```

Or maybe mentioning to extract the hosted cluster kubeconfig prior to this?

2024-02-16 16:45 UTC, CrystalChun commented on clusters/hosted_control_planes/scale_nodepool_hosted_non_bm.adoc
> +. To create a node pool, enter the following information. In this example, the node pool uses agents with the `"size" : "medium"` label:
Could we mention this label selector flag is optional?

2024-02-16 16:47 UTC, CrystalChun commented on clusters/hosted_control_planes/scale_nodepool_hosted_non_bm.adoc
> +oc --kubeconfig $CLUSTER_NAME-kubeconfig get nodes
Similar to https://github.com/stolostron/rhacm-docs/pull/6073/files#r1492723187
maybe mentioning to extract the hosted cluster kubeconfig

2024-02-16 16:48 UTC, CrystalChun commented on clusters/hosted_control_planes/scale_nodepool_hosted_non_bm.adoc
> +. Verify that the node pool is in the status that you expect by entering this command:
Maybe adding expected status output or stating that the number of available nodes matches the number of expected nodes?

2024-02-16 16:50 UTC, CrystalChun commented on clusters/hosted_control_planes/verify_hosted_cluster_non_bm.adoc
> +oc extract -n kni21 secret/kni21-admin-kubeconfig --to=- > kubeconfig-kni21
Maybe for consistency with the rest of the docs to let the user know which fields to replace such as:

```suggestion
oc extract -n <hosted cluster namespace> secret/<hosted cluster name>-admin-kubeconfig --to=- > kubeconfig-<hosted cluster name>
```

2024-02-16 16:50 UTC, CrystalChun commented on clusters/hosted_control_planes/verify_hosted_cluster_non_bm.adoc
> +oc get co --kubeconfig=kubeconfig-kni21
```suggestion
oc get co --kubeconfig=kubeconfig-<hosted cluster name>
```

2024-02-16 16:50 UTC, CrystalChun commented on clusters/hosted_control_planes/verify_hosted_cluster_non_bm.adoc
> +oc get pods -A --kubeconfig=kubeconfig-kni21
```suggestion
oc get pods -A --kubeconfig=kubeconfig-<hosted cluster name>
```

2024-02-18 09:17 UTC, avishayt commented on clusters/hosted_control_planes/autoscale_node_hosted_cluster_non_bm.adoc
> +. If 10 minutes pass without requiring the additional capacity, the worker node is removed. On the Agent platform, the agent is decommissioned and can be reused. You can confirm that the node was rem
I don't think we should promise exactly 10 minutes.  More like "Once the system has seen that capacity is not needed for a long enough time..."

2024-02-18 09:18 UTC, avishayt commented
Overall, it looks OK.  Are we sure that we want to copy-paste all of these sections?  I'm worried that we'll update one copy and not the other, leading to diverging instructions that are 99.9% the same.

2024-02-19 08:01 UTC, xenolinux commented on clusters/hosted_control_planes/autoscale_node_hosted_cluster_non_bm.adoc
> +. If 10 minutes pass without requiring the additional capacity, the worker node is removed. On the Agent platform, the agent is decommissioned and can be reused. You can confirm that the node was rem
Addressed by rewording the sentence a bit.

2024-02-19 08:23 UTC, xenolinux commented
> Overall, it looks OK. Are we sure that we want to copy-paste all of these sections?
@avishayt The copy-paste looks like a feasible option here considering this repo does not use assembly files and we need a separate section for non bare metal use case. 

> I'm worried that we'll update one copy and not the other, leading to diverging instructions that are 99.9% the same.
You mean the bare metal copy and non bare metal copy being different from one another?

2024-02-19 11:15 UTC, avishayt commented
> You mean the bare metal copy and non bare metal copy being different from one another?

Yes, we need to make sure to always update both

2024-02-19 11:23 UTC, xenolinux commented
> > You mean the bare metal copy and non bare metal copy being different from one another?
> 
> Yes, we need to make sure to always update both

Yes I have plans to update that section as well. Once reviews are done, I will raise a PR for updating bare metal sections.

2024-02-19 17:21 UTC, CrystalChun commented on clusters/hosted_control_planes/scale_nodepool_hosted_non_bm.adoc
> +----
Minor: let's match the name kubeconfig file name to the filename of the one that's extracted? 
```suggestion
oc extract -n <hosted-cluster-namespace> secret/<hosted-cluster-name>-admin-kubeconfig --to=- > kubeconfig-<hosted-cluster-name>
----

. After the agents reach the `added-to-existing-cluster` state, verify that you can see the {ocp-short} nodes in the hosted cluster by entering the following command:

+
----
oc --kubeconfig kubeconfig-<hosted-cluster-name> get nodes
----
```

2024-02-19 17:21 UTC, CrystalChun commented on clusters/hosted_control_planes/scale_nodepool_hosted_non_bm.adoc
> +oc --kubeconfig <hosted-cluster-name>.kubeconfig get clusterversion,co
```suggestion
oc --kubeconfig kubeconfig-<hosted-cluster-name> get clusterversion,co
```

2024-02-19 17:22 UTC, CrystalChun commented on clusters/hosted_control_planes/scale_nodepool_hosted_non_bm.adoc
> +oc --kubeconfig $CLUSTER_NAME-kubeconfig get nodes
Similar, match name of kubeconfig file to the one that is extracted.
```suggestion
oc --kubeconfig ./hostedcluster-secrets get nodes
```

2024-02-19 17:23 UTC, CrystalChun commented on clusters/hosted_control_planes/create_cluster_non_bm.adoc
> +<2> Ensure that agents are available in the `${HOSTED_CONTROL_PLANE_NAMESPACE}`. You can find the list of agents by using the `oc get agent -n ${HOSTED_CONTROL_PLANE_NAMESPACE}` command.
Checking if this change was meant to occur, if it wasn't, feel free to ignore this comment!

2024-02-19 18:22 UTC, CrystalChun commented on clusters/hosted_control_planes/create_cluster_non_bm.adoc
> +<1> Required by the agent cluster API provider and must already exist. You can use the `--agent-namespace` flag in the `hcp create cluster` command. Ensure that agents are available in this namespace
```suggestion
export CLUSTERS_NAMESPACE="clusters"
export HOSTED_CLUSTER_NAME="example"
export HOSTED_CONTROL_PLANE_NAMESPACE="${CLUSTERS_NAMESPACE}-${HOSTED_CLUSTER_NAME}" <1>
export BASEDOMAIN="krnl.es"
export PULL_SECRET_FILE=$PWD/pull-secret
export MACHINE_CIDR=192.168.122.0/24
export ETCD_STORAGE="lvm-storageclass"
export OCP_RELEASE=4.14.13-x86_64
export SSH_KEY=${HOME}/.ssh/id_rsa.pub
oc create ns ${HOSTED_CONTROL_PLANE_NAMESPACE}

hcp create cluster agent \
    --name=${HOSTED_CLUSTER_NAME} \
    --pull-secret=${PULL_SECRET_FILE} \
    --agent-namespace=${HOSTED_CONTROL_PLANE_NAMESPACE} \
    --base-domain=${BASEDOMAIN} \
    --api-server-address=api.${HOSTED_CLUSTER_NAME}.${BASEDOMAIN} \
    --etcd-storage-class=${ETCD_STORAGE} \
    --ssh-key  ${SSH_KEY} \
    --namespace ${CLUSTERS_NAMESPACE} \
    --control-plane-availability-policy SingleReplica \
    --release-image=quay.io/openshift-release-dev/ocp-release:${OCP_RELEASE} \
    --api-server-address=api.${HOSTED_CLUSTER_NAME}.${BASEDOMAIN}
----

+
<1> Required by the agent cluster API provider and must already exist. Use this as the `--agent-namespace` flag in the `hcp create cluster` command. Ensure that agents are available in this namespace. You can find the list of agents by using the `oc get agent -n ${HOSTED_CONTROL_PLANE_NAMESPACE}` command.
```

2024-02-19 18:29 UTC, CrystalChun approved these changes
/lgtm

2024-02-20 10:28 UTC, oafischer commented on clusters/hosted_control_planes/autoscale_node_hosted_cluster_non_bm.adoc
> +. To enable auto-scaling, enter the following command. In this case, the minimum number of nodes is 2, and the maximum is 5. The maximum number of nodes that you can add might be bound by your platfo
```suggestion
. To enable auto-scaling, enter the following command. In the example, the minimum number of nodes is 2, and the maximum is 5. The maximum number of nodes that you can add might be bound by your platform. For example, if you use the Agent platform, the maximum number of nodes is bound by the number of available agents:
```

2024-02-20 10:29 UTC, oafischer commented on clusters/hosted_control_planes/autoscale_node_hosted_cluster_non_bm.adoc
> +.. Create a YAML file that contains the workload configuration, as shown in the following example:
You can probably avoid passive voice here if you replace "as shown" with "by using"

2024-02-20 10:31 UTC, oafischer commented on clusters/hosted_control_planes/autoscale_node_hosted_cluster_non_bm.adoc
> +----
We can shorten this by just stating what the use should look for if they want to verify success. I assume we are looking for the `Ready` status of the worker nodes, so I don't think we need this output table.

2024-02-20 10:35 UTC, oafischer commented on clusters/hosted_control_planes/autoscale_node_hosted_cluster_non_bm.adoc
> +----
Same here, we usually try to be sparing with example outputs

2024-02-20 10:39 UTC, oafischer commented on clusters/hosted_control_planes/create_cluster_non_bm.adoc
> +----
This is definitely an output that is too long and can be replaced by a sentence telling the user to check the `STATUS` of their pods, if they need verification.

2024-02-20 10:43 UTC, oafischer commented on clusters/hosted_control_planes/create_cluster_non_bm.adoc
> +. Click **Infrastructure -> Clusters**.
```suggestion
. Click **Infrastructure > Clusters**.
```

We just use a simple `>` for these, make sure to replace them in the rest of the PR as well.

2024-02-20 10:45 UTC, oafischer commented on clusters/hosted_control_planes/create_cluster_non_bm.adoc
> +== Creating a hosted cluster on non bare metal agent machines by using the console
We have some topics that document console processes, but we generally try to avoid documenting the console. I'm not sure if this would be considered too much, what do you think @swopebe?

2024-02-20 10:48 UTC, oafischer commented on clusters/hosted_control_planes/handle_ingress_non_bm.adoc
> +Every {ocp-short} cluster comes set up with a default application Ingress Controller that is expected have an external DNS record associated with it. For example, if you create a HyperShift cluster n
```suggestion
Every {ocp-short} cluster has a default application Ingress Controller that is expected to have an external DNS record associated with it. For example, if you create a HyperShift cluster named `example` with the base domain `krnl.es`, you can expect the wildcard domain
```

2024-02-20 10:49 UTC, oafischer commented on clusters/hosted_control_planes/handle_ingress_non_bm.adoc
> +You can set up a load balancer and wildcard DNS record for the `*.apps`. This process requires deploying MetalLB, configuring a new load balancer service that routes to the ingress deployment, and as
```suggestion
You can set up a load balancer and wildcard DNS record for the `*.apps`. The process requires deploying MetalLB, configuring a new load balancer service that routes to the ingress deployment, and assigning a wildcard DNS entry to the load balancer IP address. Complete the following steps:
```

2024-02-20 10:55 UTC, oafischer commented on clusters/hosted_control_planes/handle_ingress_non_bm.adoc
> +----
Not sure what we are looking for here but we need to shorten/remove this output as well and let the user know what they need to look for.

2024-02-20 10:56 UTC, oafischer commented on clusters/hosted_control_planes/non_bm_intro.adoc
> += Configuring hosted control plane clusters using non bare metal agent machines (Tech Preview)
New tech preview items should also have an entry in the what's new file in the release notes section.

2024-02-20 11:53 UTC, xenolinux commented on clusters/hosted_control_planes/non_bm_intro.adoc
> += Configuring hosted control plane clusters using non bare metal agent machines (Tech Preview)
Done https://github.com/stolostron/rhacm-docs/pull/6154

2024-02-20 14:10 UTC, swopebe commented on clusters/hosted_control_planes/create_cluster_non_bm.adoc
> +== Creating a hosted cluster on non bare metal agent machines by using the console
Yes, we don't write UI steps unless 1. We have to document how to use a third-party console (Grafana) or 2. The console is not intuitive.

I think by using "follow the prompts" that this may be as concise as it can be, not sure the user could go to "create cluster" without these bold steps. 

I see some changes that need to be made, so I will review this in the afternoon, as well.

2024-02-20 14:11 UTC, swopebe commented on clusters/hosted_control_planes/create_cluster_non_bm.adoc
> +. Wait until the control plane components are ready. This process can take a few minutes.
Wait is not really a step, so that should be with the other steps. I will play with it.

2024-02-20 14:13 UTC, swopebe commented on clusters/hosted_control_planes/non_bm_intro.adoc
> +- Each host must be started manually with a Discovery Image that the central infrastructure management provides.
non bare metal probably should not be used. 

RECOMMEND: All hosts that are not bare metal require a manual boot with a...

2024-02-20 14:14 UTC, xenolinux commented on clusters/hosted_control_planes/create_cluster_non_bm.adoc
> +== Creating a hosted cluster on non bare metal agent machines by using the console
IMO, since we cover creating hosted clusters using console for bare metal, the console procedure would make sense here for non bare metal as well.

2024-02-20 14:15 UTC, swopebe commented on clusters/hosted_control_planes/non_bm_intro.adoc
> +- When you scale up a node pool, a machine is created. The Cluster API provider finds an Agent that is approved, is passing validations, is not currently in use, and meets the requirements that are s
@CrystalChun we have to try to write active voice and not passive voice. That is why the first line is preferred. Is the original line incorrect somehow? 

When you scale up a node pool, a machine is created.

Can say _Each time you scale..._

2024-02-20 14:16 UTC, xenolinux commented on clusters/hosted_control_planes/create_cluster_non_bm.adoc
> +== Creating a hosted cluster on non bare metal agent machines by using the console
> Yes, we don't write UI steps unless 1. We have to document how to use a third-party console (Grafana) or 2. The console is not intuitive.
> 
> I think by using "follow the prompts" that this may be as concise as it can be, not sure the user could go to "create cluster" without these bold steps.
> 
> I see some changes that need to be made, so I will review this in the afternoon, as well.

Sure thanks

2024-02-20 14:20 UTC, xenolinux commented on clusters/hosted_control_planes/non_bm_intro.adoc
> +- Each host must be started manually with a Discovery Image that the central infrastructure management provides.
Addressed

2024-02-20 23:20 UTC, swopebe commented on clusters/hosted_control_planes/non_bm_intro.adoc
> +- Each host must be started manually with a Discovery Image that the central infrastructure management provides.
I see the file name is even non bm, so we may need to keep it. We are trying to shorten filenames in hosted cluster, though.

2024-02-20 23:20 UTC, swopebe commented on clusters/hosted_control_planes/create_cluster_non_bm.adoc
> +export OCP_RELEASE=4.14.0-multi
How we are writing these, to avoid creating bugs when we can, is with a variable:

`OCP_RELEASE=4.x.0-multi`

With either a call out or a simple line that says, "Replace 4.x.0 with the supported version" (or something like that, there are examples in the doc that we recently changed).

2024-02-20 23:21 UTC, swopebe commented on clusters/hosted_control_planes/handle_ingress_non_bm.adoc
> +clusterversion.config.openshift.io/version   4.12z    True        False         3m32s   Cluster version is 4.12z
Same here, we are using variables when we can.

2024-02-21 09:54 UTC, xenolinux commented on clusters/hosted_control_planes/non_bm_intro.adoc
> +- When you scale up a node pool, a machine is created. The Cluster API provider finds an Agent that is approved, is passing validations, is not currently in use, and meets the requirements that are s
We have the first sentence[1] already present in the bm_intro.adoc file as well. So IMO, the sentence must not be inaccurate. 
Hence, I changed it to : 
When you scale up the node pool, a machine is created for every replica.

2024-02-21 10:14 UTC, xenolinux commented
Thank you for the review. I addressed all the suggestions and comments -- I will proceed with merging this PR. This content is intended to go in the OpenShift docs 4.15 welcome page (OCP 4.15 docs merge freeze date: 22nd Feb 2024)

If there are any minor comments/suggestions from the peer review perspective, I will make sure to open a follow up PR to address those changes.

2024-02-21 10:14 UTC, merged

2024-02-21 12:26 UTC, swopebe commented on clusters/hosted_control_planes/non_bm_intro.adoc
> +- When you scale down a node pool, Agents are unbound from the corresponding cluster. Before you can reuse the clusters, you must restart them by using the Discovery image to update the number of nod
This was merged but I was in the middle of a peer review, will reach out over slack.

2024-02-21 12:56 UTC, oafischer commented
The example outputs still need to be removed, we definitely can't include the long ones. The shorter ones can remain for now to keep things simple.