Add `recordDiff` to ConfigPolicy and generator
open-cluster-management/rhacm-docs pull request #6095
Opened 2024-02-01 21:25 UTC by dhaiducek

ref: https://issues.redhat.com/browse/ACM-9774

/cc @dockerymick @gparvin @mprahl @yiraeChristineKim @JustinKuli

2024-02-05 15:00 UTC, JustinKuli approved these changes
Contents look right to me!

2024-02-06 04:11 UTC, dockerymick commented
@dhaiducek thanks for creating the PR, I will review this soon

2024-02-28 14:14 UTC, dockerymick requested changes
@dhaiducek thank you so much for your patience and work on this. I left suggestions, reminder that we need to add a what's new entry: https://github.com/stolostron/rhacm-docs/blob/2.10_stage/release_notes/whats_new.adoc#governance-whats-new

2024-02-28 14:14 UTC, dockerymick commented on governance/config_policy_ctrl.adoc
> +| Specifies whether (and where) to log the difference between the object on the cluster and the `objectDefinition` in the policy. Set to "Log" to log the difference in the controller logs or "None" t
I monospaced the parameter values. Are the quotation marks required? 
```suggestion
| Specifies if and where to log the difference between the object on the cluster and the `objectDefinition` in the policy. Set to `Log` to log the difference in the controller logs or `None` to not log the difference. By default, this parameter is empty to not log the difference.
```

2024-02-28 14:14 UTC, dockerymick commented on governance/policy_ctrl_adv_config.adoc
> +Additionally, for each `spec.object-template[]` in a `ConfigurationPolicy`, you can set the parameter `recordDiff` to "Log". The difference between the `objectDefinition` and the object on the manage
Is this info apart of the YAML: 

Logging the diff:
--- default/my-configmap : existing
+++ default/my-configmap : updated
@@ -2,3 +2,3 @@

```suggestion
Additionally, for each `spec.object-template[]` in a `ConfigurationPolicy` resource, you can set the parameter `recordDiff` to `Log`. The difference between the `objectDefinition` and the object on the managed cluster is logged in the `config-policy-controller` pod on the managed cluster. View the following example:
```

2024-02-28 14:14 UTC, dockerymick commented on governance/policy_ctrl_adv_config.adoc
> +*NOTE:* Use caution to not log the difference for a secure object. The difference is logged in plain text.
I changed this to important, so that users understand the severity.
```suggestion
*Important:* Avoid logging the difference for a secure object. The difference is logged in plain text.
```

2024-02-28 14:14 UTC, dockerymick commented on governance/policy_generator.adoc
> +| Specifies whether (and where) to log the difference between the object on the cluster and the `objectDefinition` in the policy. Set to "Log" to log the difference in the controller logs or "None" t
```suggestion
| Specifies if and where to log the difference between the object on the cluster and the `objectDefinition` in the policy. Set to `Log` to log the difference in the controller logs or `None` to not log the difference. By default, this parameter is empty to not log the difference.
```

2024-02-28 14:14 UTC, dockerymick commented
@dhaiducek I can add the entry too, just let me know

2024-02-28 16:16 UTC, dhaiducek commented on governance/config_policy_ctrl.adoc
> +| Specifies whether (and where) to log the difference between the object on the cluster and the `objectDefinition` in the policy. Set to "Log" to log the difference in the controller logs or "None" t
Nope, monospacing without quotation marks works! Thanks!

2024-02-28 16:17 UTC, dhaiducek commented on governance/policy_ctrl_adv_config.adoc
> +Additionally, for each `spec.object-template[]` in a `ConfigurationPolicy`, you can set the parameter `recordDiff` to "Log". The difference between the `objectDefinition` and the object on the manage
> Is this info apart of the YAML:
> 
> Logging the diff: --- default/my-configmap : existing +++ default/my-configmap : updated @@ -2,3 +2,3 @@

No, not part of the YAML--that's what the logs look like in the `config-policy-controller` Pod when the diff is logged.

2024-02-28 16:24 UTC, dhaiducek commented on governance/policy_ctrl_adv_config.adoc
> +Additionally, for each `spec.object-template[]` in a `ConfigurationPolicy`, you can set the parameter `recordDiff` to "Log". The difference between the `objectDefinition` and the object on the manage
Oh actually, I see what you mean. It'd probably be clearer to have a YAML example and then the log example. I'll add one.

2024-02-28 16:50 UTC, dhaiducek commented
@dockerymick Thanks for the review--I've added a bullet to "What's New" and also added YAML to the advanced configuration doc.

2024-02-28 19:20 UTC, dockerymick commented on governance/policy_ctrl_adv_config.adoc
> +[source]
the source syntax is not needed here I think. Or maybe we use bash? Is it accurate to say this is bash syntax @dhaiducek 
```suggestion
[source,bash]
```

2024-02-29 18:32 UTC, dhaiducek commented on governance/policy_ctrl_adv_config.adoc
> +[source]
Ah, I didn't realize that wasn't necessary. It's not really bash, so I'll just remove it. Thanks!

2024-03-01 14:12 UTC, dockerymick commented on governance/policy_ctrl_adv_config.adoc
> +If the `ConfigMap` resource on the cluster had `fieldToUpdate: "1"`, then the diff would appear in the `config-policy-controller` Pod logs as:
```suggestion
If the `ConfigMap` resource on the cluster lists `fieldToUpdate: "1"`, then the diff appears in the `config-policy-controller` pod logs with the following information:
```

2024-03-01 14:12 UTC, dockerymick approved these changes
This looks good to me! Thanks @dhaiducek . Reaching out to the team for a peer review

2024-03-01 16:51 UTC, jc-berger approved these changes
/lgtm

2024-03-01 19:15 UTC, dockerymick commented on release_notes/whats_new.adoc
> +* You can enable diff logging for `ConfigurationPolicy` resources using the `recordDiff` parameter in the `ConfigurationPolicy`. The difference between the `object-template` and the object on the man
```suggestion
* You can enable diff logging for `ConfigurationPolicy` resources using the `recordDiff` parameter in the `ConfigurationPolicy` resource. The difference between the `object-template` and the object on the managed cluster is logged inside the `config-policy-controller` pod on the managed cluster. See link:../governance/policy_ctrl_adv_config.adoc[Configure debug log] for details.
```

2024-03-01 19:15 UTC, dockerymick approved these changes

2024-03-01 19:16 UTC, dockerymick commented
@jc-berger thanks for the review and approval. @dhaiducek thanks again for being familiar with the doc! You are valuable and very helpful! Thanks for your patience. Merging this PR

2024-03-01 19:16 UTC, merged