ACM#9626: Update the  command params
open-cluster-management/rhacm-docs pull request #6097
Opened 2024-02-02 10:17 UTC by xenolinux

This PR fixes the following Jiras:
- https://issues.redhat.com/browse/ACM-9625
- https://issues.redhat.com/browse/ACM-9626

This PR updates the parameters in the `hcp create nodepool agent` command.

2024-02-07 20:07 UTC, dockerymick requested changes
Please see my comment. Thanks for the updates!

2024-02-07 20:07 UTC, dockerymick commented on clusters/hosted_control_planes/scale_nodepool_hosted_bm.adoc
> +. To create a node pool, enter the following information. In this example, the node pool uses agents with the 'size=large,zone notin (az1,az2)' label:
use backticks to create monospace
```suggestion
. To create a node pool, enter the following information. In this example, the node pool uses agents with the `'size=large,zone notin (az1,az2)'` label:
```

2024-02-08 09:54 UTC, avishayt commented
LGTM

2024-02-08 10:51 UTC, xenolinux commented on clusters/hosted_control_planes/scale_nodepool_hosted_bm.adoc
> +. To create a node pool, enter the following information. In this example, the node pool uses agents with the 'size=large,zone notin (az1,az2)' label:
Addressed, ty

2024-02-08 14:36 UTC, merged

2024-02-08 16:33 UTC, dockerymick approved these changes
I realize that i didn't submit my review. My apologies. I left 1 suggestion

2024-02-08 16:33 UTC, dockerymick commented on clusters/hosted_control_planes/scale_nodepool_hosted_bm.adoc
> +You add nodes to your hosted cluster by scaling the `NodePool` object.
```suggestion
To add nodes to your hosted cluster, scale the `NodePool` object. Complete the following steps:
```

2024-02-15 16:37 UTC, xenolinux commented on clusters/hosted_control_planes/scale_nodepool_hosted_bm.adoc
> +You add nodes to your hosted cluster by scaling the `NodePool` object.
Suggestion is addressed in https://github.com/stolostron/rhacm-docs/pull/6139