ACM#9564: Update examples for configuting metallb
open-cluster-management/rhacm-docs pull request #6099
Opened 2024-02-02 12:40 UTC by xenolinux

Jira: https://issues.redhat.com/browse/ACM-9564
This PR updates the YAML block examples for the "Optional: Configuring MetalLB" section

2024-02-08 15:16 UTC, jeniferh commented
Thanks, LGTM

2024-02-09 10:51 UTC, oafischer commented on clusters/hosted_control_planes/config_metallb_bm.adoc
> +cat << EOF| oc create -f -
We do not use EOF in our docs, I recommend separating the commands.

1. oc create filename
2. Add a step explaining that a user can add the sample YAML content to the file
3. oc apply filename

2024-02-09 15:36 UTC, dockerymick requested changes
Excuse the delay, I completed a review but didn't submit it

2024-02-09 15:36 UTC, dockerymick commented on clusters/hosted_control_planes/config_metallb_bm.adoc
> +cat << EOF| oc create -f -
EOF needs to be removed. Will you confirm with development what command should be used? For example:

```
. Create a `MetalLB` resource with the following command:
+
[source,bash]
----
oc create -f -MetalLB
----

Your file might resemble the following content:
+
[source,yaml]
----
apiVersion: metallb.io/v1beta1
kind: MetalLB
metadata:
  name: metallb
  namespace: metallb-system
----

```

Same suggestion for the other steps

2024-02-14 13:27 UTC, dockerymick commented on clusters/hosted_control_planes/config_metallb_bm.adoc
> +
Is there anything displayed on the users screen after the configuration is complete?

2024-02-14 15:53 UTC, jeniferh commented on clusters/hosted_control_planes/config_metallb_bm.adoc
> +cat << EOF| oc create -f -
The first 'oc create' steps will fail since it is referencing a file that does not exist yet, the flow should be something like this example (step 3 & 4): https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.9/html/clusters/cluster_mce_overview#installing-from-the-cli-mce
"Create a YAML file [...]"
<< Example YAML file code box >>
Create the object:
$ oc apply -f <file_name>.yaml

(Looking through the docs, it seems 'oc apply' is preferred more than 'oc create')

2024-02-14 15:59 UTC, xenolinux commented on clusters/hosted_control_planes/config_metallb_bm.adoc
> +
@jeniferh Can you please help to identify if anything is displayed on the users screen after the configuration is complete?

2024-02-14 16:00 UTC, jeniferh commented on clusters/hosted_control_planes/config_metallb_bm.adoc
> +
ex. output for each step:
# oc apply -f configure-metallb.yaml
metallb.metallb.io/metallb created

# oc apply -f l2advertisement.yaml
l2advertisement.metallb.io/metallb created

# oc apply -f create-ip-address-pool.yaml
ipaddresspool.metallb.io/metallb created

2024-02-14 16:18 UTC, jeniferh commented
The steps look correct now w/ latest commit, thanks!

2024-02-14 16:19 UTC, xenolinux commented on clusters/hosted_control_planes/config_metallb_bm.adoc
> +
Thannks @jeniferh Addressed all the suggestions

2024-02-14 16:37 UTC, dockerymick approved these changes
@xenolinux thanks for the updates ! This look great to me!

2024-02-15 07:42 UTC, merged