ACM#9464: Add instructions to download  by using the CLI
open-cluster-management/rhacm-docs pull request #6100
Opened 2024-02-02 13:16 UTC by xenolinux

Jira: https://issues.redhat.com/browse/ACM-9464

This PR adds the instructions to install the `hcp` binary by using the CLI.

2024-02-15 14:23 UTC, elsapassaro commented on clusters/hosted_control_planes/install_hcp_cli.adoc
> +[#hosted-install-console]
Just a minor comment, wouldn't it be better to switch the anchors of the two section for consistency? 
I.e. use `[#hosted-install-cli]` for this section to download from CLI and  `[#hosted-install-console]` for the previous section (line 1) to download it from console

2024-02-15 14:26 UTC, xenolinux commented on clusters/hosted_control_planes/install_hcp_cli.adoc
> +[#hosted-install-console]
oops yes makes sense; updated the PR

2024-02-15 14:29 UTC, elsapassaro approved these changes
/lgtm

2024-02-16 14:29 UTC, dockerymick requested changes

2024-02-16 14:29 UTC, dockerymick commented on clusters/hosted_control_planes/install_hcp_cli.adoc
> +[#hosted-install-console]
I'm not sure why the anchor is being changed. It would be inaccurate to change the anchor to console. Also keep in mind that if the anchor is changed here, we have to search for other instances and also update them. The anchor should remain the same
```suggestion
[#hosted-install-cli]
```

2024-02-16 14:38 UTC, xenolinux commented on clusters/hosted_control_planes/install_hcp_cli.adoc
> +[#hosted-install-console]
Addressed

2024-02-17 10:36 UTC, merged