minor changes based off dev input
open-cluster-management/rhacm-docs pull request #6103
Opened 2024-02-02 18:33 UTC by jc-berger

see Jira: https://issues.redhat.com/browse/ACM-9733

2024-02-02 18:43 UTC, birsanv requested changes

2024-02-02 18:43 UTC, birsanv commented on business_continuity/backup_restore/backup_arch.adoc
> +- Back up all custom resource definitions with an API version suffixed by `.open-cluster-management.io` and `.hive.openshift.io`. These suffixes indicate that all {product-title-short} resources are
replace Back up all custom resource definitions
with Back up all resources

2024-02-02 18:43 UTC, birsanv commented on business_continuity/backup_restore/backup_arch.adoc
> +- Back up all custom resource definitions from the following API groups: `argoproj.io`, `app.k8s.io`, `core.observatorium.io`, `hive.openshift.io`. These API groups are under the resources backup, an
replace Back up all custom resource definitions from the following API groups: `argoproj.io`, `app.k8s.io`, `core.observatorium.io`, `hive.openshift.io` and `agent-install.openshift.io`.
with Back up all resources from  `argoproj.io`, `app.k8s.io`, `core.observatorium.io`, `hive.openshift.io`.

2024-02-02 18:43 UTC, birsanv commented on business_continuity/backup_restore/backup_arch.adoc
> +- Back up all custom resource definitions from the following API groups: `argoproj.io`, `app.k8s.io`, `core.observatorium.io`, `hive.openshift.io`. These API groups are under the resources backup, an
replace : These API groups are under the resources backup, and all the CRDs from the group, `agent-install.openshift.io`, are under the managed clusters backup.

with: 
These resources are backed up under the `acm-resources-schedule` backup, with the exception of resources from the `agent-install.openshift.io` API group, which are backed up under the `acm-managed-clusters-schedule` backup.

2024-02-02 18:43 UTC, birsanv commented on business_continuity/backup_restore/backup_arch.adoc
> +- Exclude all custom resource definitions from the following API groups: `internal.open-cluster-management.io`, `operator.open-cluster-management.io`, `work.open-cluster-management.io`, `search.open-
replace Exclude all custom resource definitions
with Exclude all resources

2024-02-02 18:43 UTC, birsanv commented on business_continuity/backup_restore/backup_arch.adoc
>  - Exclude the following custom resource definitions that are a part of the included API groups, but are either not needed or are being recreated by owner resources, which are also backed up: `cluster
replace Exclude all custom resource definitions
with Exclude all resources

2024-02-05 12:01 UTC, swopebe commented on business_continuity/backup_restore/backup_arch.adoc
> +- Back up all custom resource definitions from the following API groups: `argoproj.io`, `app.k8s.io`, `core.observatorium.io`, `hive.openshift.io`. These API groups are under the resources backup, an
Let's find a better word for "under" here, as we try to keep direction language out tech doc.

2024-02-05 12:02 UTC, swopebe approved these changes
approve, pending developer changes and one comment for change. @jc-berger

2024-02-08 15:23 UTC, birsanv approved these changes
lgtm thanks!

2024-02-09 17:02 UTC, merged