https://issues.redhat.com/browse/ACM-9681 known issue with Kube/API
open-cluster-management/rhacm-docs pull request #6110
Opened 2024-02-06 20:59 UTC by swopebe

https://issues.redhat.com/browse/ACM-9681

2024-02-06 21:00 UTC, swopebe commented on release_notes/known_issues_observability.adoc
> +
these are confusing to me, we are telling the user to go through 1 step to 0 and one back to 2 or N? In that order? Or are these two different methods?

2024-02-06 21:07 UTC, subbarao-meduri commented on release_notes/known_issues_observability.adoc
> +
@swopebe
The deployment name is `observability-observatorium-api`. By default, they are deployed as 2 instances. However, customer could have changed number of instances to more than 2 if scaling is needed. The fix is
1. Scale down  number of instances from N -> 0 
2. Scale up number of instances from 0 -> N 
(N = 2 by default, but could be > 2 in some environments, if custom configuration is used)

2024-02-06 22:55 UTC, subbarao-meduri approved these changes
/lgtm

2024-02-07 12:45 UTC, dockerymick requested changes

2024-02-07 12:45 UTC, dockerymick commented on release_notes/known_issues_observability.adoc
> +== Observatorium API gateway pods in a restored hub cluster might have stale tenant data
```suggestion

[#permission-to-managed-cluster-monitoring-denied]
== Observatorium API gateway pods in a restored hub cluster might have stale tenant data
```

2024-02-07 12:45 UTC, dockerymick commented on release_notes/known_issues_observability.adoc
> +The Observatorium API gateway pods in a restored hub cluster might contain stale tenant data after a backup and restore procedure because of a Kubernetes limitation. See link:https://kubernetes.io/do
I see that "ConfigMap" is used. If I am recalling correctly, I believe that is why we had instances of `ConfigMap`. We wanted to be consistent with Kubernetes. With seeing this, we should be aligned with Kubernetes. Let's discuss with the team

2024-02-07 12:45 UTC, dockerymick commented on release_notes/known_issues_observability.adoc
> +----
```suggestion
[source,bash]
----
```

2024-02-07 12:45 UTC, dockerymick commented on release_notes/known_issues_observability.adoc
> +----
```suggestion
[source,bash]
----
```

2024-02-07 15:59 UTC, swopebe commented on release_notes/known_issues_observability.adoc
> +The Observatorium API gateway pods in a restored hub cluster might contain stale tenant data after a backup and restore procedure because of a Kubernetes limitation. See link:https://kubernetes.io/do
@dockerymick  ConfigMap can be used, but what we don't want is configmap or configMap or anything else we try here.

2024-02-07 16:05 UTC, swopebe commented on release_notes/known_issues_observability.adoc
> +The Observatorium API gateway pods in a restored hub cluster might contain stale tenant data after a backup and restore procedure because of a Kubernetes limitation. See link:https://kubernetes.io/do
Here is the guidance: yes[ config map (noun)](https://redhat-documentation.github.io/supplementary-style-guide/#config-map)
Description: In Red Hat OpenShift, a config map holds configuration data for pods to consume. The API object for a config map is ConfigMap.

So you are right, we need to code it or write it out.

2024-02-07 16:08 UTC, swopebe commented on release_notes/known_issues_observability.adoc
> +----
Not so sure about this one, we actually decided not to do this but I see it here and there in the doc now; I think some folks started doing on on their own. I think this is valid for a bash command. This is an error, however. I am going to reject this and bring it up again tomorrow.

2024-02-07 16:09 UTC, swopebe commented on release_notes/known_issues_observability.adoc
> +----
same, it is an error and not a bash command. (???) Interested in the reason for _source, bash_ here, but we have not discussed using this across the team. Let's chat about it tomorrow.

2024-02-07 16:11 UTC, swopebe commented on release_notes/known_issues_observability.adoc
> +The Observatorium API gateway pods in a restored hub cluster might contain stale tenant data after a backup and restore procedure because of a Kubernetes limitation. See link:https://kubernetes.io/do
@dockerymick I am going to leave the title the way it is here, but normally, yes we would code. Here is why:

This is the exact title of the third part documentation, it isn't our content.

2024-02-07 16:34 UTC, dockerymick commented on release_notes/known_issues_observability.adoc
> +----
My reason is because it is displayed from the terminal. I considered CLI views as "bash"

2024-02-07 16:34 UTC, dockerymick approved these changes

2024-02-07 16:52 UTC, swopebe commented on release_notes/known_issues_observability.adoc
> +----
Ok, I understand, but want to see what others use for errors. These would potentially build with a copy block but and error would not need that.

2024-02-07 18:42 UTC, merged