https://issues.redhat.com/browse/ACM-8532 Remove BMH docs
open-cluster-management/rhacm-docs pull request #6121
Opened 2024-02-08 10:42 UTC by oafischer

2.10 only

2024-02-08 13:52 UTC, carbonin requested changes

2024-02-08 13:52 UTC, carbonin commented on clusters/cluster_lifecycle/cim_auto_add_host.adoc
> +To remove bare metal hosts from the provisioner node, you need a hub cluster that is running {ocp-short} version 4.13 or later. Any static networking configuration required for the node to boot must
Not sure what "provisioner node" is supposed to mean here.

This will remove the node from the spoke cluster and delete the BMH and agent in the hub.

2024-02-08 13:52 UTC, carbonin commented on clusters/cluster_lifecycle/cim_auto_add_host.adoc
> +== Removing bare metal hosts by using the command line interface
I think this should be `Removing spoke cluster nodes by using the command line interface`.

Then the two sections should be how to do this with and without a BMH in the hub.

2024-02-08 13:52 UTC, carbonin commented on clusters/cluster_lifecycle/cim_auto_add_host.adoc
> +=== Removing bare metal hosts without using GitOps
This has nothing to do with GitOps.
The distinction between the two cases is whether or not a BareMetalHost is present for the node in the hub cluster.

2024-02-08 13:52 UTC, carbonin commented on clusters/cluster_lifecycle/cim_auto_add_host.adoc
> +After completing the steps in _Removing bare metal hosts by using the command line interface_, follow the link:https://docs.openshift.com/container-platform/4.13/nodes/nodes/nodes-nodes-working.html#
No, this is in place of those steps, not in after them.

2024-02-08 16:10 UTC, oafischer commented
Thanks for the review @carbonin, I've updated based on your comments. Let me know if it looks good now.

2024-02-08 16:30 UTC, carbonin approved these changes

2024-02-15 15:03 UTC, jc-berger approved these changes
/lgtm

2024-02-15 15:03 UTC, merged

2024-02-15 15:15 UTC, dockerymick commented on clusters/cluster_lifecycle/cim_auto_add_host.adoc
> +- To learn more about scaling compute machines, see link:https://docs.openshift.com/container-platform/4.13/machine_management/manually-scaling-machineset.html[Manually scaling a compute machine set]
@jc-berger thanks for reviewing and merging this PR. I know this was not a part of the changes, but will you go into the cim_auto_add_host.adoc file to update the link for "The BaremetalHost spec". It came up as broken 

<img width="1159" alt="Screenshot 2024-02-15 at 10 13 37 AM" src="https://github.com/stolostron/rhacm-docs/assets/60616885/8d4fdc59-17f2-4d8a-a251-148e8380374d">