ACM#9621: Hosted control planes: Managing a node pool
open-cluster-management/rhacm-docs pull request #6122
Opened 2024-02-08 10:47 UTC by xenolinux

https://issues.redhat.com/browse/ACM-9621

2024-02-14 18:24 UTC, davidvossel reviewed
nice! I made a few comments that might help add some clarity for people

2024-02-14 18:24 UTC, davidvossel commented on modules/schedule_node_pool_kubevirt.adoc
> ++
One thing that would be worth clarifying in this text is that the node selectors are meant to work on a set of nodes, and not necessarily on a single node (even though that is possible).

So, it's more accurate to say something similar to "you can schedule VMs within a NodePool to a specific set of nodes using the ``vm-node-selector` argument"

2024-02-14 18:24 UTC, davidvossel commented on modules/perf_tuning_node_pool_kubevirt.adoc
> +By default, KubeVirt virtual machines (VMs) use maximum resource requests for CPU. The high CPU consumption might impact performance of a VM. To avoid this, you can request guaranteed CPU resources.
This isn't accurate.  The VMs may or may not use the maximum resources requests for CPU. The point of the `--qos-class=Guaranteed` isn't necessarily related to how much cpu the VMs use, but instead it's about the potential performance impact VMs may experience when sharing cpus with other workloads on a node.

So, the `--qos-class=Guaranteed` argument is meant as a way to guarantee a VM has "exclusive" access to it's cores rather than shared access.

2024-02-14 18:24 UTC, davidvossel commented on modules/add_network_node_pool_kubevirt.adoc
> +. To add multiple networks to nodes, use the `--additional-network` argument, as shown in the following example:
It would be nice to note that the value of the `--additional-network` cli arg is the namespace/name of a NetworkAttachmentDefinition. Readers might be able to infer this information, but it would be good to be explicit about it i think.

2024-02-15 14:40 UTC, davidvossel reviewed
/lgtm

2024-02-16 15:54 UTC, dockerymick requested changes

2024-02-16 15:54 UTC, dockerymick commented on clusters/hosted_control_planes/managing_nodepools_kubevirt.adoc
> +If you need to configure additional networks for nodepools, request a guaranteed CPU access for VMs, or manage scheduling of KubeVirt virtual machines (VMs), see the following procedures.
I checked IBM style guide and there were no mentions of how Virtual Machine should be referenced. Virtual Machine seems like it would be a common term to our audience so using the abbreviation after the first instance works here.
```suggestion
If you need to configure additional networks for node pools, request a guaranteed CPU access for Virtual Machines (VM), or manage scheduling of KubeVirt VM, see the following procedures.
```

2024-02-16 15:54 UTC, dockerymick commented on clusters/hosted_control_planes/managing_nodepools_kubevirt.adoc
> +By default, nodes generated by a node pool are attached to the pod network. You can attach additional networks to the nodes by using Multus and link:https://docs.openshift.com/container-platform/late
Update to link to be customer portal link: https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14

I attempted to look through, but didn't locate the Network APIs

2024-02-16 15:54 UTC, dockerymick commented on clusters/hosted_control_planes/managing_nodepools_kubevirt.adoc
> +
To help with alignment
```suggestion
+
```

2024-02-16 15:54 UTC, dockerymick commented on clusters/hosted_control_planes/managing_nodepools_kubevirt.adoc
> +
What is expected to be displayed after the resource is updated?

2024-02-16 15:54 UTC, dockerymick commented on clusters/hosted_control_planes/managing_nodepools_kubevirt.adoc
> +----
Same suggestion, add what might be displayed from the screen or add a verification step

2024-02-16 15:54 UTC, dockerymick commented on clusters/main.adoc
> +include::hosted_control_planes/managing_nodepools_kubevirt.adoc[leveloffset=+4]
Consider adding this link to the Hosted control planes doc: https://github.com/stolostron/rhacm-docs/blob/2.10_stage/clusters/hosted_control_planes/hosted_intro.adoc

reminder to also add an entry to the MCE what's new: https://github.com/stolostron/rhacm-docs/blob/2.10_stage/clusters/release_notes/whats_new.adoc

2024-02-17 10:51 UTC, xenolinux commented on clusters/hosted_control_planes/managing_nodepools_kubevirt.adoc
> +----
@davidvossel Can you help with the output displayed on the terminal or a verification step?

2024-02-17 10:52 UTC, xenolinux commented on clusters/hosted_control_planes/managing_nodepools_kubevirt.adoc
> +
@davidvossel Can you help with the output displayed on the terminal or a verification step?

2024-02-17 11:02 UTC, xenolinux commented on clusters/hosted_control_planes/managing_nodepools_kubevirt.adoc
> +By default, nodes generated by a node pool are attached to the pod network. You can attach additional networks to the nodes by using Multus and link:https://docs.openshift.com/container-platform/late
The folder API reference seems to be absent in the customer portal. I too could not find the network APIs page. For now I removed the link.

2024-02-19 09:53 UTC, xenolinux commented on clusters/main.adoc
> +include::hosted_control_planes/managing_nodepools_kubevirt.adoc[leveloffset=+4]
I will create new PR for all whats new entries

2024-02-19 20:24 UTC, davidvossel commented on clusters/hosted_control_planes/managing_nodepools_kubevirt.adoc
> +
in both this case `--qos-class` and the `--vm-node-selector` case, the result of this command is that a new HCP cluster is being created. The verification of how to determine the health and progress of a new cluster is already covered here, https://github.com/stolostron/rhacm-docs/blob/48ed8e5317d09c7aff4db646bb4f96602ae3f8b9/clusters/hosted_control_planes/create_cluster_kubevirt.adoc?plain=1#L39

2024-02-19 20:24 UTC, davidvossel commented on clusters/hosted_control_planes/managing_nodepools_kubevirt.adoc
> +----
see my response here, https://github.com/stolostron/rhacm-docs/pull/6122#discussion_r1494987956

2024-02-20 07:46 UTC, xenolinux commented on clusters/hosted_control_planes/managing_nodepools_kubevirt.adoc
> +
Thanks for confirming!!

2024-02-20 08:04 UTC, merged

2024-02-20 11:53 UTC, xenolinux commented on clusters/main.adoc
> +include::hosted_control_planes/managing_nodepools_kubevirt.adoc[leveloffset=+4]
Done https://github.com/stolostron/rhacm-docs/pull/6154