https://issues.redhat.com/browse/ACM-9832 MSA default change docs
open-cluster-management/rhacm-docs pull request #6123
Opened 2024-02-09 11:52 UTC by oafischer

2.10/2.5 only.

2024-02-20 09:40 UTC, zhujian7 commented
@oafischer could you also help remove the [first limitation of the managed service account addon](https://github.com/stolostron/rhacm-docs/blob/2.10_stage/clusters/release_notes/known_issues.adoc#the-managed-serviceaccount-does-not-support-ocp-short-311):

> The managed-serviceaccount does not support {ocp-short} 3.11
The managed-serviceaccount add-on crashes if you run it on {ocp-short} 3.11.

Because in 2.10, we did some enhancement and now the msa addon can run on ocp 311.
story: https://issues.redhat.com/browse/ACM-9655

2024-02-20 09:44 UTC, zhujian7 commented on clusters/release_notes/whats_new.adoc
> +- The `ManagedServiceAccount` add-on is now enabled by default. See
There seems to be a link missing after "See", or delete the "See"?

2024-02-20 09:56 UTC, zhiweiyin318 commented
Please review when you have a chance @joeg-pro .

2024-02-20 10:17 UTC, oafischer commented on clusters/release_notes/whats_new.adoc
> +- The `ManagedServiceAccount` add-on is now enabled by default. See
Fixed!

2024-02-21 14:32 UTC, joeg-pro requested changes
See 1 comment.

2024-02-21 14:32 UTC, joeg-pro commented on clusters/cluster_lifecycle/addon_managed_service.adoc
> +When you install the {mce-short} version 2.5 or later, the `ManagedServiceAccount` add-on is enabled by default. If you upgrade your hub cluster from {mce-short} version 2.4 and did not enable the `M
I think we should be explicit in noting the change in behavior.   So, I suggest that after the "When you install..." setence, we add a new one that reads  "This is a change from version 2.4 and earlier where ManagedServiceAccount add-on was disabled by default."

2024-02-21 14:39 UTC, oafischer commented on clusters/cluster_lifecycle/addon_managed_service.adoc
> +When you install the {mce-short} version 2.5 or later, the `ManagedServiceAccount` add-on is enabled by default. If you upgrade your hub cluster from {mce-short} version 2.4 and did not enable the `M
Updated, thanks!

2024-02-26 14:39 UTC, dockerymick approved these changes
Made a couple of suggestions. Other than that, this looks good to me!

2024-02-26 14:39 UTC, dockerymick commented on clusters/cluster_lifecycle/addon_managed_service.adoc
> +When you install the {mce-short} version 2.5 or later, the `ManagedServiceAccount` add-on is enabled by default. In {mce-short} version 2.4 and earlier, the `ManagedServiceAccount` add-on was disable
From my perspective, it is unnecessary to mention this statement, and it's past tense: In {mce-short} version 2.4 and earlier, the `ManagedServiceAccount` add-on was disabled by default.

```suggestion
When you install the {mce-short} version 2.5 or later, the `ManagedServiceAccount` add-on is enabled by default. If you upgrade your hub cluster from {mce-short} version 2.4 and did not enable the `ManagedServiceAccount` add-on before upgrading, you must enable the add-on manually.
```

2024-02-26 14:45 UTC, oafischer commented on clusters/cluster_lifecycle/addon_managed_service.adoc
> +When you install the {mce-short} version 2.5 or later, the `ManagedServiceAccount` add-on is enabled by default. In {mce-short} version 2.4 and earlier, the `ManagedServiceAccount` add-on was disable
Joe wanted us to have that sentence. Not sure how to proceed here.

2024-02-28 11:13 UTC, merged