added content on policy
open-cluster-management/rhacm-docs pull request #6127
Opened 2024-02-13 18:24 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-9852

2024-02-13 18:25 UTC, jc-berger commented on business_continuity/backup_restore/backup_validate.adoc
> +On your hub cluster, install the cluster backup and restore operator Helm chart and the `cluster-backup-chart`. These charts then install the `backup-restore-enabled` and `backup-restore-auto-import`
Doc reviewers, would this content necessitate an entry in the `What's New` doc?

2024-02-13 18:44 UTC, swopebe commented on business_continuity/backup_restore/backup_validate.adoc
> +On your hub cluster, install the cluster backup and restore operator Helm chart and the `cluster-backup-chart`. These charts then install the `backup-restore-enabled` and `backup-restore-auto-import`
Please look at the issue that is linked to get the answer to this question this time. In this industry, in general, a _new release note_ would be required for any new feature.

2024-02-13 18:44 UTC, swopebe commented on business_continuity/backup_restore/backup_validate.adoc
> +** The `auto-import-account-secret` template checks whether a `ManagedServiceAccount` secret is created under managed cluster namespaces other than the `local-cluster`. The backup controller regularl
please remove "under"

2024-02-13 18:50 UTC, swopebe commented on business_continuity/backup_restore/backup_validate.adoc
> +On your hub cluster, install the cluster backup and restore operator Helm chart and the `cluster-backup-chart`. These charts then install the `backup-restore-enabled` and `backup-restore-auto-import`
**Remember:** Features, identified by Train labels, are new items= What's new. Is it new for 2.10? You can tell this by opening the issues and also making sure your issues are labeled appropriately.

2024-02-13 18:53 UTC, swopebe approved these changes
Remove the directional language. _Within_ or _for_ or something would suffice....think of what a namespace is used for and you can prob describe it without using "under."

Otherwise this looks great. I am approving but asking for that change.

2024-02-13 19:36 UTC, sahare requested changes

2024-02-13 19:36 UTC, sahare commented on business_continuity/backup_restore/backup_validate.adoc
> +On your hub cluster, install the cluster backup and restore operator Helm chart and the `cluster-backup-chart`. These charts then install the `backup-restore-enabled` and `backup-restore-auto-import`
@jc-berger This change is confusing for the users because they don't install the cluster backup and restore operator Helm chart, the chart is installed by MCE when the cluster-backup option is set to true on the MultiClusterHub resource.

2024-02-20 18:29 UTC, sahare requested changes

2024-02-20 18:29 UTC, sahare commented on business_continuity/backup_restore/backup_validate.adoc
> +When you set the `cluster-backup` option to `true` on the `MultiClusterHub` resource, {mce-short} installs the cluster backup and restore operator Helm chart and the `cluster-backup-chart`. These cha
installs the cluster backup and restore operator Helm chart and the `cluster-backup-chart`. These charts ...
cluster-backup-chart is the name of the cluster backup and restore operator Helm chart, there is only one chart

2024-02-20 18:29 UTC, sahare commented on release_notes/whats_new.adoc
> +
When you enable the backup component on the MultiClusterHub, the cluster backup and restore operator Helm chart installs some ACM policies used to inform on issues with the backup and restore component. With ACM version 2.10, a new policy named `backup-restore-auto-import` is being installed used to inform on issues with automatic managed clusters import feature.

2024-02-26 16:09 UTC, sahare approved these changes
Thanks Jake for patiently applying all the changes, looks great now, just one last request is please add it to the end of this section before `1.1.7.1. Protecting data using server-side encryption` , the backup-restore-enabled is better to be explained first, Thanks!

2024-02-26 21:53 UTC, sahare commented on business_continuity/backup_restore/backup_validate.adoc
> +
The above section is explaining `backup-restore-enabled` and `backup-restore-auto-import` policies, it should come first as a parent for two sub sections, first one explaining the `backup-restore-enabled` and the second one (which is a new sub section) explaining the `backup-restore-auto-import`, so this whole part should look exactly like what we currently have in the doc, only add a sub section containing below lines from 58 to 63 (The `backup-restore-auto-import` policy at the end.

2024-02-27 19:02 UTC, sahare commented
@jc-berger so this part : 
When you set the cluster-backup option to true on the MultiClusterHub resource, {mce-short} installs the cluster backup and restore operator Helm chart that is named the cluster-backup-chart. This chart then installs the backup-restore-enabled and backup-restore-auto-import policies. Use these policies to view information about issues with your backup and restore components.

should come right after ` Validating your backup or restore configurations` where it was originally, it's explaining about both policies, so should come first before detailed information of each policy.

2024-02-28 18:18 UTC, swopebe commented on business_continuity/backup_restore/backup_validate.adoc
> +
approving but with request to replace "triggers"

2024-02-28 18:20 UTC, sahare requested changes

2024-02-28 18:20 UTC, sahare commented on business_continuity/backup_restore/backup_validate.adoc
> +
@jc-berger This section should start with `When you set the `cluster-backup` option to `true` on the `MultiClusterHub` resource, {mce-short} installs the cluster backup and restore operator Helm chart that is named the `cluster-backup-chart`. This chart then installs the `backup-restore-enabled` and `backup-restore-auto-import` policies. Use these policies to view information about issues with your backup and restore components.` right after `Validating your backup or restore configurations` exactly as it was before the changes in this PR, Thanks.

2024-02-28 18:46 UTC, sahare approved these changes
Looks good to me, Thanks!

2024-02-28 18:54 UTC, merged