added content on oadp validation
open-cluster-management/rhacm-docs pull request #6128
Opened 2024-02-13 18:43 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-9857

2024-02-13 19:02 UTC, swopebe requested changes

2024-02-13 19:02 UTC, swopebe commented on business_continuity/backup_restore/backup_validate.adoc
> +* When you enable the backup component on the Multicluster Hub (MCH), the cluster backup and restore operator Helm chart installs the OADP operator. The `OADP-channel` template checks if the installe
Do not use **MCH** and also, look at the correct way to write _Multicluster Hub_ for the product, you can prob find it in the doc.

This is a very long paragraph and readers won't want to sift through this; recommending you create a little space in between concepts for concise presentation and easier reading. Right now it more resembles prose.

**Example:** Please improve the following line, with to be verb, passive language, also should be writing hub cluster in most cases, we don't generally just say "hub" except for global hub._

_is found to be installed on the hub but does not match the version installed by the {prod-short} cluster backup and restore operator Helm chart._

**Example:** is found to be installed

**We should be writing concicely**: is installed, was installed, etc...

There are some other things that could change to make this and any content like it more concise, so please implement when you can. You may get drafts like these; it is on us to make it fit for technical writing standards.

2024-02-13 20:59 UTC, swopebe commented on business_continuity/backup_restore/backup_validate.adoc
> +* When you enable the backup component on the Multicluster Hub (MCH), the cluster backup and restore operator Helm chart installs the OADP operator. The `OADP-channel` template checks if the installe
The resource in the doc is:  MultiClusterHub (so that might apply here)

2024-02-20 17:56 UTC, sahare requested changes

2024-02-20 17:56 UTC, sahare commented on business_continuity/backup_restore/backup_validate.adoc
> +* The template shows violations if it finds an installed Red Hat OADP Operator on the hub cluster, but the Red Hat OADP Operator does not match the version installed by the {prod-short} cluster backu
The current text: The violation shows that the OADP and Velero Custom Resource Definitions (CRDs) are `cluster-scoped` is not correct. The violation shows that a wrong version of OADP operator is found on the cluster. The reason for considering it as a violation is that OADP and Velero Custom Resource Definitions (CRDs) are `cluster-scoped` so we can't have multiple versions of them installed in the same cluster, so only the right version must be installed on the cluster.

2024-02-20 17:56 UTC, sahare commented on business_continuity/backup_restore/backup_validate.adoc
> +** The OADP version installed by `MultiClusterHub` is uninstalled then manually installed.
It should be: The OADP version installed by `MultiClusterHub` is uninstalled then a different version is manually installed.

2024-02-20 18:23 UTC, sahare commented on release_notes/whats_new.adoc
> +When you enable the backup component on the `MultiClusterHub`, the cluster backup and restore operator Helm chart installs the OADP operator. The `OADP-channel` template checks if the installed Red H
When you enable the backup component on the `MultiClusterHub`, the cluster backup and restore operator Helm chart installs the backup-restore-enabled Policy, used to inform on issues with the backup and restore component. With ACM version 2.10, a new policy template named `OADP-channel` is added to backup-restore-enabled Policy. The `OADP-channel` template checks if the installed Red Hat OADP Operator version matches the version set by the {prod-short} cluster backup and restore operator. The  `OADP-channel` template helps you prevent your back and restore operator from running with the wrong custom resource definitions (CRDs).

2024-02-26 16:47 UTC, sahare commented on business_continuity/backup_restore/backup_validate.adoc
> +** The OADP version installed by `MultiClusterHub` is uninstalled, then you must manually install a different version.
This part : `then you must manually install a different version` to me sounds like user must do this task, but what we meant here is: `If OADP version installed by MCH is uninstalled and a different version is manually installed by the user` then the backup operator could run with wrong CRDs.

2024-02-26 16:49 UTC, sahare commented on release_notes/whats_new.adoc
> +
OADP operator. The `OADP-channel` template checks if the installed Red Hat OADP Operator version matches the version set by the {prod-short} cluster backup and restore operator. The  `OADP-channel` template helps you prevent your operator from running with the wrong custom resource definitions (CRDs). 

I think the above part is not needed here, seems like a duplicate to me.

2024-02-26 16:51 UTC, sahare approved these changes
Thanks Jake for the updates, Please see the comments I added, I'm approving this PR but putting on-hold for the changes to be made. Thanks!

2024-02-26 20:49 UTC, sahare commented
Thanks @jc-berger , looks good to me!

2024-02-27 14:48 UTC, sahare commented on business_continuity/backup_restore/backup_validate.adoc
> +
This part : `, then the backup operator might run wih the wrong CRDs. ` is redundant, please remove it.

2024-02-27 19:23 UTC, sahare commented
Thanks @jc-berger , Looks good to me!

2024-02-27 20:09 UTC, swopebe requested changes

2024-02-27 20:09 UTC, swopebe commented on release_notes/whats_new.adoc
> +When you enable the backup component on the `MultiClusterHub`, the cluster backup and restore operator Helm chart installs the `backup-restore-enabled` policy. This policy informs you about issues wi
This is a really long what's new entry, @jc-berger -- we mostly just introduce it and point to the new doc. I would say this area would be placed in the actual doc:

With {prod-short} 2.10 or later, the `backup-restore-enabled` policy includes a new policy template named, `OADP-channel`. The `OADP channel` template checks if the installed OADP Operator version matches the version set by the {prod-short} cluster backup and restore operator. Use the `OADP-channel` template to prevent your backup and restore operator from running with the wrong custom resource definitions (CRDs).

It's not usualy to have so much in a what's new entry...do you mind playing with this a bit?

2024-02-27 20:09 UTC, swopebe commented on business_continuity/backup_restore/backup_validate.adoc
> +
incorrect conref on line 17?

2024-02-27 20:34 UTC, swopebe commented on release_notes/whats_new.adoc
> +When you enable the backup component on the `MultiClusterHub`, the cluster backup and restore operator Helm chart installs the `backup-restore-enabled` policy. This policy informs you about issues wi
check conref here?

2024-02-28 18:14 UTC, swopebe approved these changes

2024-03-01 17:42 UTC, closed without merging