added content on dashboard alerts
open-cluster-management/rhacm-docs pull request #6156
Opened 2024-02-20 18:56 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-8379

2024-02-22 07:00 UTC, quchangl-github approved these changes

2024-02-22 07:10 UTC, quchangl-github commented
/approve

2024-02-27 17:26 UTC, dockerymick requested changes

2024-02-27 17:26 UTC, dockerymick commented on observability/design_grafana.adoc
> +Use Grafana dashboards to view hub cluster and managed cluster metrics. The data displayed in the Grafana alerts dashboard relies on `alerts` metrics, originating from managed clusters. The `alerts`
The correct conref for the product is `{product-title-short}`. The conrefs are listed in any of the `common-attributes.adoc` files in the rhacm-docs repo.

```suggestion
Use Grafana dashboards to view hub cluster and managed cluster metrics. The data displayed in the Grafana alerts dashboard relies on `alerts` metrics, originating from managed clusters. The `alerts` metric does not affect managed clusters forwarding alerts to {product-title-short} alert manager on the hub cluster. Therefore, the metrics and alerts have distinct propagation mechanisms and follow separate code paths. 
```

2024-02-27 17:26 UTC, dockerymick commented on observability/design_grafana.adoc
> +Even if you see data in the Grafana alerts dashboard, that does not guarantee that the managed cluster alerts are successfully forwarding to the {prod-short} hub cluster alert manager. If the metrics
```suggestion
Even if you see data in the Grafana alerts dashboard, that does not guarantee that the managed cluster alerts are successfully forwarding to the {product-title-short} hub cluster alert manager. If the metrics are propagated from the managed clusters, you can view the data displayed in the Grafana alerts dashboard. 
```

2024-02-27 17:57 UTC, dockerymick approved these changes
Thanks for the updates Jake. this looks good to me!

2024-02-27 18:07 UTC, merged