https://issues.redhat.com/browse/ACM-10095 Operator policy controller docs
open-cluster-management/rhacm-docs pull request #6173
Opened 2024-02-27 10:00 UTC by oafischer

2.10 only

2024-02-27 14:28 UTC, JustinKuli requested changes
Sounds good to me overall! I'm glad that the description & example is sufficient - the tables feel hard to maintain and kind of noisy.

2024-02-27 14:28 UTC, JustinKuli commented on governance/policy_controllers_intro.adoc
> +* xref:../governance/policy_operator.adoc#policy-operator#policy-operator[Operator policy controller]
I don't know how these details work on the page, but my spidey senses are tingling about the doubled `#policy-operator`. Does the link work as expected? I don't know where to check it.

2024-02-27 14:28 UTC, JustinKuli commented on governance/policy_operator.adoc
> +You can use the `spec.versions` field in an operator policy to declare which versions of the operator are compliant. If the field is empty, any version running on the cluster is considered compliant.
```suggestion
You can use the `spec.versions` field in an operator policy to declare which versions of the operator are compliant. If the field is empty, any version running on the cluster is considered compliant. If the field is not empty, the version on the managed cluster must match one of the versions in the list for the policy to be compliant. If the policy is in `enforce` mode, it only approves updates to versions that are compliant.
```

Saying "any of the fields" feels too vague, but I'm open to other options.

2024-02-27 14:29 UTC, oafischer commented on governance/policy_operator.adoc
> +You can use the `spec.versions` field in an operator policy to declare which versions of the operator are compliant. If the field is empty, any version running on the cluster is considered compliant.
That works too, thanks!

2024-02-27 14:31 UTC, oafischer commented on governance/policy_controllers_intro.adoc
> +* xref:../governance/policy_operator.adoc#policy-operator#policy-operator[Operator policy controller]
Good catch, classic copy paste error. Fixed now. Thanks!

2024-02-27 15:39 UTC, JustinKuli approved these changes
LGTM, thanks!

2024-02-28 14:14 UTC, jc-berger approved these changes
/lgtm

2024-02-28 14:14 UTC, jc-berger commented on governance/policy_operator.adoc
> +The operator policy controller allows you to monitor or install Operator Lifecycle Manager (OLM) operators across your clusters. You can monitor the health of various pieces of the operator and you c
Is it "or" or "and"? That is, do users need to choose which action or can they use both? If the latter, I would change to "and" : 

```suggestion
The operator policy controller allows you to monitor and install Operator Lifecycle Manager (OLM) operators across your clusters. You can monitor the health of various pieces of the operator and you can specify how to automatically handle updates to the operator. You can also distribute an operator policy to managed clusters by using the governance framework and adding the policy to the `policy-templates` field of a policy on the hub cluster.
```

2024-02-28 14:14 UTC, jc-berger commented on governance/policy_operator.adoc
> +The operator policy controller allows you to monitor or install Operator Lifecycle Manager (OLM) operators across your clusters. You can monitor the health of various pieces of the operator and you c
"You can" can be redundant. What do you think of this rewrite that's a little more user action focused too : 

```suggestion
The operator policy controller allows you to monitor or install Operator Lifecycle Manager (OLM) operators across your clusters. Use the operator policy controller to monitor the health of various pieces of the operator and to specify how you want to automatically handle updates to the operator. You can also distribute an operator policy to managed clusters by using the governance framework and adding the policy to the `policy-templates` field of a policy on the hub cluster.
```

2024-02-28 14:27 UTC, dockerymick commented on governance/policy_operator.adoc
> +----
I recommend considering the additional resources section, if it is needed

2024-02-28 14:42 UTC, oafischer commented on governance/policy_operator.adoc
> +----
Added!

2024-02-28 14:43 UTC, dockerymick commented on governance/policy_operator.adoc
> +----
Thanks Oliver! i would also take the user back to the Policy controller intro since they were directed from there.

2024-02-28 14:45 UTC, oafischer commented on governance/policy_operator.adoc
> +----
I believe we agreed to not add the _return to_ links in additional resources. But we can bring this up to the team again

2024-02-28 14:53 UTC, dockerymick commented on governance/policy_operator.adoc
> +----
My understanding that we agreed to not return to the beginning of the same file. It's fine tho, not a big deal at all. If someone shouts about it we can easily add the link whenever. Thanks! I'm good with your current changes !

2024-02-28 14:55 UTC, oafischer commented on governance/policy_operator.adoc
> +----
OK, let's clarify in our channel though, maybe I misunderstood. I'll merge this for now, thanks!

2024-02-28 14:56 UTC, merged