https://issues.redhat.com/browse/ACM-9870 FIPS updates
open-cluster-management/rhacm-docs pull request #6177
Opened 2024-02-27 20:17 UTC by dockerymick

https://issues.redhat.com/browse/ACM-9870

2024-02-29 18:01 UTC, gparvin commented on release_notes/fips_readiness.adoc
> +If you plan to manage clusters with FIPS enabled, you must install {product-title-short} on an {ocp-short} cluster configured to operate in FIPS mode. You must also have a FIPS-ready hub cluster beca
Some aspects of this are not clear.  The ACM Hub needs to be installed on a cluster that has FIPS enabled is one point.  It's a second point to mention provisioning managed clusters and enabling FIPS for those.
```suggestion
If you plan to manage clusters with FIPS enabled, you must install {product-title-short} on an {ocp-short} cluster configured to operate in FIPS mode. The hub cluster requires FIPS mode because cryptography that is created on the hub cluster is stored on the managed cluster. 

To enable FIPS mode on your managed clusters, set the following parameter when you provision your {ocp-short} managed cluster: `fips: true`. You cannot enable FIPS after you provision your cluster. For more information, see {ocp-short} documentation, link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/installing/index#installing-preparing-security[Do you need extra security for your cluster?]
```

2024-03-04 18:29 UTC, dockerymick commented
@gparvin thanks for reviewing and making a suggestion. I accepted the suggestion. Will you re-review the PR?

2024-03-04 18:54 UTC, swopebe commented on release_notes/fips_readiness.adoc
> +To enable FIPS mode on your managed clusters, set the following parameter when you provision your {ocp-short} managed cluster: `fips: true`. You cannot enable FIPS after you provision your cluster. F
@dockerymick 2 things:


For more information, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/installing/index#installing-preparing-security[Do you need extra security for your cluster?] in the {ocp-short} documentation?

2024-03-04 18:56 UTC, swopebe commented on release_notes/fips_readiness.adoc
> +To enable FIPS mode on your managed clusters, set the following parameter when you provision your {ocp-short} managed cluster: `fips: true`. You cannot enable FIPS after you provision your cluster. F
Can we merge a bit here for clarity and conciseness:

...set `fips: true` when you provision your {ocp-short} managed cluster.

2024-03-04 18:56 UTC, swopebe commented on release_notes/fips_readiness.adoc
> +To enable FIPS mode on your managed clusters, set the following parameter when you provision your {ocp-short} managed cluster: `fips: true`. You cannot enable FIPS after you provision your cluster. F
Also, can we point to 4.13 here or does it not exist for 4.13?

2024-03-04 18:57 UTC, swopebe requested changes
I have not figured out how to "make suggestions" -- see comments.

2024-03-04 19:40 UTC, dockerymick commented on release_notes/fips_readiness.adoc
> +To enable FIPS mode on your managed clusters, set the following parameter when you provision your {ocp-short} managed cluster: `fips: true`. You cannot enable FIPS after you provision your cluster. F
Yea it exists and to make a suggestion, select the "Add a suggestion" icon. it is next to the Preview tab of the comment box. 

<img width="484" alt="Screenshot 2024-03-04 at 2 38 45 PM" src="https://github.com/stolostron/rhacm-docs/assets/60616885/812b9b75-33cf-472e-912d-3341fa3fec62">
```suggestion
To enable FIPS mode on your managed clusters, set `fips: true` when you provision your {ocp-short} managed cluster. You cannot enable FIPS after you provision your cluster. For more information, see {ocp-short} documentation, link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.13/html-single/installing/index#installing-preparing-security[Do you need extra security for your cluster?]
```

2024-03-05 16:53 UTC, dockerymick commented
@gparvin @swopebe thanks for yall reviews. When yall have a chance, will you both rereview?

2024-03-06 21:01 UTC, gparvin commented on release_notes/fips_readiness.adoc
> +If you plan to manage clusters with FIPS enabled, you must install {product-title-short} on an {ocp-short} cluster configured to operate in FIPS mode. The hub cluster must be in FIPS mode because cry
```suggestion
If you plan to manage clusters with FIPS enabled, you must install {product-title-short} on an {ocp-short} cluster configured to operate in FIPS mode. The hub cluster must be in FIPS mode because cryptography that is created on the hub cluster is used on managed clusters. 
```

2024-03-06 21:41 UTC, gparvin approved these changes
Thanks for pulling in my previous update.  This looks good to me.

2024-03-07 16:57 UTC, swopebe approved these changes

2024-03-07 17:29 UTC, dockerymick commented
Thanks for the re-reviews and approvals. Merging this PR

2024-03-07 17:29 UTC, merged