IBM Z documentation updates for ACM-10187
open-cluster-management/rhacm-docs pull request #6190
Opened 2024-03-04 06:08 UTC by krishnanshruthi

Issue: https://issues.redhat.com/browse/ACM-10187

2024-03-04 06:15 UTC, veera-damisetti commented
/lgtm

2024-03-04 06:16 UTC, veera-damisetti commented
/approve

2024-03-04 14:15 UTC, swopebe requested changes
see comment

2024-03-04 14:15 UTC, swopebe commented on clusters/hosted_control_planes/ibmz_intro.adoc
> +. xref:../hosted_control_planes/scale_nodepool_hosted_ibmpower.adoc#scaling-the-nodepool-ibmz[Scaling the NodePool object for a hosted cluster on IBM Z]
@krishnanshruthi we have asked to work with branches rather than forks because we need to often edit and it's easier to check out and edit in VS code when we have a branch to check out.

On line 65, I see a reference to IBM Power in the file name but the title and work is for IBM Z.

2024-03-05 06:50 UTC, krishnanshruthi commented on clusters/hosted_control_planes/ibmz_intro.adoc
> +. xref:../hosted_control_planes/scale_nodepool_hosted_ibmpower.adoc#scaling-the-nodepool-ibmz[Scaling the NodePool object for a hosted cluster on IBM Z]
@swopebrandi1 Fixed Line 65 - check the latest commit.

I somehow remember that we were asked to work on forked repo - I will make a note to work out of branch going forward. Thanks!

2024-03-06 12:29 UTC, swopebe approved these changes
Thanks so much!

2024-03-06 13:43 UTC, merged