added backup and restore to global hub
open-cluster-management/rhacm-docs pull request #6220
Opened 2024-03-07 22:35 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-9704

2024-03-08 06:52 UTC, ldpliu commented on global_hub/global_hub_backup_and_restore.adoc
> +To give access to helpful and basic resources, {global-hub} backup and restore uses the {product-title-short} backup and restore features. Use the backup and restore feature to:
I thinks the following description is better, and the hyperlink to backup page is necessary.
`{global-hub} backup and restore uses the [{product-title-short} backup and restore](https://github.com/stolostron/rhacm-docs/blob/2.10_stage/business_continuity/backup_restore/backup_intro.adoc) to backup basic resources`

2024-03-08 06:52 UTC, ldpliu commented on global_hub/global_hub_backup_and_restore.adoc
> +VolSync version must >= 0.9.0
12-13 could be deleted

2024-03-08 06:52 UTC, ldpliu commented on global_hub/global_hub_backup_and_restore.adoc
> +{global-hub} also supports the `backup postgres pvc` by using the `acm-hub-pvc-backup`. To ensure your {global-hub} can support the `backup postgres pvc`, you must have at least the following version
It should be:
`{global-hub} also supports  backup` postgres pvc` by using the `acm-hub-pvc-backup`(https://github.com/open-cluster-management-io/policy-collection/tree/main/community/CM-Configuration-Management/acm-hub-pvc-backup). To ensure your {global-hub} can support the `backup postgres pvc`, you must have at least the following versions of VolySync and {product-title-short}: `

2024-03-08 06:52 UTC, ldpliu commented on global_hub/global_hub_backup_and_restore.adoc
> +When you create a new a hub cluster, you might need to restore your {global-hub} cluster. To restore your {global-hub}, install the {global-hub} operator but do not create the {global-hub} custom res
Changed to:
`If you need to restore your {global-hub} cluster. When [Preparing the new hub cluster](../business_continuity/backup_restore/backup_intro.adoc#preparing-the-new-hub-cluster), please install the {global-hub} operator but do not create the {global-hub} custom resource (CR) because the CR is automatically restored.  `

2024-03-08 06:52 UTC, ldpliu commented on global_hub/global_hub_backup_and_restore.adoc
> +== Additional resources
The 22-23 should be removed.

2024-03-08 06:52 UTC, ldpliu commented on release_notes/known_issues_global.adoc
> +If your original {global-hub} cluster crashes, and you create a new one, you might have the following issues:
It should be:
`During the original {global-hub} cluster crashes, and new hub cluster restored,  you might have the following issues:`

2024-03-08 06:52 UTC, ldpliu commented on release_notes/known_issues_global.adoc
> +* If hte cron job does not run, then you must manually execute the cron job.
`hte` --> `the`

2024-03-08 18:40 UTC, jc-berger commented on global_hub/global_hub_backup_and_restore.adoc
> +{global-hub} also supports the `backup postgres pvc` by using the `acm-hub-pvc-backup`. To ensure your {global-hub} can support the `backup postgres pvc`, you must have at least the following version
So, I made all your changes, but I didn't include the link you have here. 

Typically, we are very careful about linking to docs _outside_ our repo's documentation. I'm hesitant to link users to a doc outside the ACM repo, because we ACM writers don't have control over that documentation. 

Do you think this doc is very necessary?

2024-03-08 18:41 UTC, jc-berger commented
@ldpliu thank you so much for your awesome review! I made your changes, and left a comment on one of your suggested changes. Please let me know what you think, thanks!

2024-03-11 00:50 UTC, ldpliu commented on global_hub/global_hub_backup_and_restore.adoc
> +[#backup-and-restore-for-global-hub]
This is a TP feature, so we need to high light it, like:

`[#backup-and-restore-for-global-hub](Technology Preview)`

2024-03-11 00:50 UTC, ldpliu commented on global_hub/global_hub_backup_and_restore.adoc
> +To backup basic resources, {global-hub} backup and restore uses the {product-title-short} xref:../business_continuity/backup_restore/backup_intro.adoc#backup-intro[backup and restore]. Use the backup
The description is not very accurate, so I propose remove[ line 6-7](https://github.com/stolostron/rhacm-docs/pull/6220/files#diff-252b7f2bcea9f00e1ab3f0c1a5440f71784076319cd47d339104f945823b915bR6-R7)
And update [Line 4](https://github.com/stolostron/rhacm-docs/pull/6220/files#diff-252b7f2bcea9f00e1ab3f0c1a5440f71784076319cd47d339104f945823b915bR4) to :

`To backup basic resources, {global-hub} backup and restore uses the {product-title-short} xref:../business_continuity/backup_restore/backup_intro.adoc#backup-intro[backup and restore]. 
`

2024-03-11 00:50 UTC, ldpliu commented on global_hub/global_hub_backup_and_restore.adoc
> +{global-hub} also supports the `backup postgres pvc` by using the `acm-hub-pvc-backup`. To ensure your {global-hub} can support the `backup postgres pvc`, you must have at least the following version
The link is very necessary, it provide the detail steps to backup data, if we do not  provide it here, the customer will be very confused.

2024-03-11 02:21 UTC, ldpliu commented
/cc @hchenxa @yahliu @clyang82 Please also help to review it.

2024-03-11 19:08 UTC, swopebe commented on global_hub/global_hub_backup_and_restore.adoc
> +
Can we please shorten the file name? Check out the folders for some examples or ideas. Can even just remove restore.

2024-03-11 19:09 UTC, swopebe commented on global_hub/global_hub_backup_and_restore.adoc
> +If you need to restore your {global-hub} cluster, you must xref:../business_continuity/backup_restore/backup_intro.adoc#preparing-the-new-hub-cluster[prepare the new hub cluster]. Install the {global
I think this would be better not as an embedded phrase, but as a signal to go to the doc to do this.

2024-03-11 19:24 UTC, swopebe requested changes
See comments and some brainstorming...

2024-03-11 19:24 UTC, swopebe commented on global_hub/global_hub_backup_and_restore.adoc
> +
This line to me is not really a short description of what the function is, but it is the place of a short description. Can you play with this?

`To backup basic resources, {global-hub} backup and restore uses the {product-title-short} [backup and restore](https://github.com/stolostron/rhacm-docs/blob/174be664f104406ddf6c7e08f9e615a59b9801f6/business_continuity/backup_restore/backup_intro.adoc#backup-intro). `

And it repeats backup a lot. Also the first backup should prob be "back up"

2024-03-11 19:24 UTC, swopebe commented on global_hub/global_hub_backup_and_restore.adoc
> +If you need to restore your {global-hub} cluster, you must xref:../business_continuity/backup_restore/backup_intro.adoc#preparing-the-new-hub-cluster[prepare the new hub cluster]. Install the {global
Meaning:

If you need to ....  see [prepare the new hub cluster].

2024-03-11 19:24 UTC, swopebe commented on global_hub/global_hub_overview.adoc
> +- xref:../global_hub/global_hub_backup_and_restore.adoc#backup-and-restore-for-global-hub[Backup and restore for {global-hub}]
Logically here, when does this happen. Let's stop and think of the best order for the user. 

They need intro info, tasks, etc... presented in such a way that mirrors their knowledge and behavior. Having back up at the beginning in front of architecture and requirements... not sure that is the best place.

2024-03-11 19:24 UTC, swopebe commented on release_notes/known_issues_global.adoc
> +* If new events data, like policy compliance events, are generated, then these events data might get lost and not be written to the database.
See word usage here for "like", also I think it's best not to break up that phrase...

If new events data are generated, such as..... then these events data might


`get lost and not be written to the database.` (can we make this clearer, active, and more concise?)

then you might lose data that would appear in the database.... (you can play with that a bit if you want.)

2024-03-11 19:24 UTC, swopebe commented on release_notes/known_issues_global.adoc
> +* If the cron job does not run, then you must manually run the cron job.
Do they know how to do that?

2024-03-12 00:48 UTC, ldpliu approved these changes

2024-03-12 01:01 UTC, ldpliu commented on release_notes/known_issues_global.adoc
> +If your original {global-hub} cluster crashes, and you restore the new hub cluster, you might have the following issues:
As global hub will lost the  events and cron jobs which are generated during the global-hub cluster crash. And after the new hub cluster ready, they will also not be restored.  
There is a workaround to manually run the cron job: https://github.com/stolostron/multicluster-global-hub/blob/main/doc/how_global_hub_works.md#running-the-summarization-process-manually

2024-03-12 15:19 UTC, swopebe commented on global_hub/global_hub_backup.adoc
> +To give recovery solutions and access to basic resources, {global-hub} backup and restore uses the {product-title-short} backup and restore features. To learn more about how these features help you,
You can use {global-hub} with {product-title-short} backup and restore features for recovery solutions and to access to basic resources. (Or something)

Much shorter and easier to understand, also this is active voice. Some of this review is in the style manuals, with examples that may help.

2024-03-12 15:21 UTC, swopebe commented on release_notes/known_issues_global.adoc
> +* Your cron job does not automatically run.
This is still off to me. If it doesn't automatically run, there is usually directions to manually run it. It's uncommon to have a known issue with no workaround. (?) 

Are we saying there are no workarounds? Look at other examples of known issues for some ideas, but the engineers have this info usually.

2024-03-12 15:22 UTC, swopebe requested changes
One suggestion for short description and another question of known issue completeness, otherwise almost there!

2024-03-12 15:58 UTC, swopebe approved these changes

2024-03-12 17:18 UTC, merged