added business continuity known issue
open-cluster-management/rhacm-docs pull request #6226
Opened 2024-03-12 22:22 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-10292

2024-03-13 14:42 UTC, swopebe requested changes
couple things, otherwise looks good!

2024-03-13 14:42 UTC, swopebe commented on release_notes/known_issues_continuity.adoc
> +=== The _open-cluster-management-backup_ namespace is stuck in the _Terminating_ state, disabling the component cluster backup in _MultiClusterHub_
I think we can cut down this ID and title. We don't have to have the whole phrase.

`_open-cluster-management-backup_ namespace stuck component cluster backup disabled`


`#open-cluster-namespace-stuck-disabled-mch` (or even shorter than this)

2024-03-13 14:42 UTC, swopebe commented on release_notes/known_issues_continuity.adoc
> +* If you have a cluster hub where you run a {product-title-short} restore operation.
cluster hub?

2024-03-13 17:38 UTC, swopebe approved these changes
Thanks for the quick edits!

2024-03-15 14:36 UTC, birsanv requested changes

2024-03-15 14:36 UTC, birsanv commented on release_notes/known_issues_continuity.adoc
> +When the `open-cluster-management-backup` namespace is stuck in the `Terminating` state, it disables the component cluster backup in `MultiClusterHub`. The namespace is stuck in the following instanc
replace 39-42 with :

When the `cluster-backup` component is disabled on the `MultiClusterHub` resource, the `open-cluster-management-backup` namespace is stuck in the `Terminating` state if you have a Velero restore resource created by a {product-title-short} restore operation.

2024-03-15 15:04 UTC, birsanv approved these changes
lgtm

2024-03-15 16:03 UTC, merged