added note for restore resources
open-cluster-management/rhacm-docs pull request #6227
Opened 2024-03-13 16:13 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-10208

2024-03-14 02:53 UTC, zhujian7 commented on business_continuity/backup_restore/backup_arch.adoc
> +* If you need to back up your managed cluster namespace or the resources under it, you must restore the namespace or resources after you create the managed cluster resources. When you restore your na
I think the `cluster.open-cluster-management.io/backup: cluster-activation` label is set for backup the resource not restore.

2024-03-14 02:54 UTC, zhujian7 commented
Hi @birsanv, could you help take a review of this PR? Thanks.

2024-03-14 13:39 UTC, oafischer commented on business_continuity/backup_restore/backup_arch.adoc
> +* If you need to back up your managed cluster namespace or the resources under it, you must restore the namespace or resources after you create the managed cluster resources. When you restore your na
Let's find a way to avoid directional language (`under`)

2024-03-14 13:52 UTC, birsanv commented on business_continuity/backup_restore/backup_arch.adoc
> +* Secrets and config maps are restored when passive resources are restored, regardless of the `cluster.open-cluster-management.io/backup` label value. Because the `cluster-activation` value is ignore
Oliver, please remove this section from ACM 2.10 , now secrets and configmap behave the same as the other resources.

_Secrets and config maps are restored when passive resources are restored, regardless of the `cluster.open-cluster-management.io/backup` label value. Because the `cluster-activation` value is ignored in this case, set the `cluster.open-cluster-management.io/backup: cluster-activation` value to the resources using these secrets and config maps instead. This way, the resources are not restored until the activation step._

2024-03-14 14:16 UTC, birsanv requested changes

2024-03-14 14:16 UTC, birsanv commented on business_continuity/backup_restore/backup_arch.adoc
> +* If you need to back up your managed cluster namespace or the resources under it, you must restore the namespace or resources after you create the managed cluster resources. When you restore your na
Any resource in the ManagedCluster namespace must be restored at cluster activation step.
For this reason, if you need to add to the backup a resource created in the ManagedCluster namespace, make sure you use the `cluster-activation` value for the `cluster.open-cluster-management.io/backup` label.

2024-03-15 16:06 UTC, jc-berger commented
@birsanv does this PR look good to merge now after I applied your feedback?

2024-03-15 16:08 UTC, birsanv approved these changes
lgtm

2024-03-15 17:51 UTC, merged

2024-03-16 02:31 UTC, zhujian7 commented on business_continuity/backup_restore/backup_arch.adoc
> +*Note:* For any resource in the managed cluster namespace, you must restore it at the cluster activation step. Therefore, if you need to add to the backup resource created in the managed cluster name
Can we also mention that the managed cluster namespace itself should be restored after the managed cluster is created?