https://issues.redhat.com/browse/ACM-10032
open-cluster-management/rhacm-docs pull request #6231
Opened 2024-03-14 10:28 UTC by oafischer

2024-03-14 12:44 UTC, coleenquadros commented on release_notes/whats_new.adoc
> +Observability is now enabled by default on the hub cluster and is not an add-on anymore. As a result, corresponding pods in `open-cluster-management-observability` are removed. The multicluster obser
I am not sure what we mean by `As a result, corresponding pods in `open-cluster-management-observability` are removed.` are you referring to `open-cluster-management-addon-observability`? because this namespace is no longer present in the hub. The metrics-collector and endpoint operator for the hub will be launched in `open-cluster-management-observability` namespace along with the other components in the observability stack when the multicluster observability operator is created. For the normal spokes/managed clusters we will have the metrics collector and endpoint launched in `open-cluster-management-addon-observability` as previous releases

2024-03-15 08:55 UTC, oafischer commented on release_notes/whats_new.adoc
> +Observability is now enabled by default on the hub cluster and is not an add-on anymore. As a result, corresponding pods in `open-cluster-management-observability` are removed. The multicluster obser
I've updated it, thanks!

2024-03-15 14:50 UTC, jc-berger approved these changes
/lgtm

2024-03-18 15:38 UTC, subbarao-meduri commented on observability/observability_arch.adoc
>  The `multiclusterhub-operator` enables the `multicluster-observability-operator` pod by default. You must configure the `multicluster-observability-operator` pod.
Although not part of this change, 
I am not sure if "pod enabling another pod" is the right way to describe.

What we are trying to say here is that Multicluster Observability operator pod is running in ACM by default when multicluster hub is configured.

2024-03-18 15:45 UTC, subbarao-meduri commented on observability/observability_arch.adoc
When you enable Observability service by defining a MCO custom resource, the `observability-endpoint-operator` is automatically deployed to each ~~imported or created cluster~~ managed spoke cluster. This controller _starts a metrics collector_ that in turn collects the data from {ocp} Prometheus, then sends it to the {product-title-short} hub cluster. ~~Observability is enabled by default on the hub cluster.~~ When observability service is enabled, the hub cluster is always configured to collect and send metrics to the configured Thanos instance, regardless of whether hub self-management is enabled or not. When the hub cluster is self-managed, the `disableHubSelfManagement` parameter is set to `false`, which is the default setting. Metrics and alerts for the hub cluster appear in the `local-cluster` namespace. The `local-cluster` only appears in the cluster list drop-down menu if hub self-management is enabled. Metrics for `local-cluster` metrics  can be queried via Grafana explorer option.

2024-03-18 15:52 UTC, subbarao-meduri commented on release_notes/whats_new.adoc
> +
When observability is enabled on a ACM hub, an observability add-on is  configured on all normal spoke clusters. This add-on starts an `endpoint operator` and `metrics collector` in ``open-cluster-management-addon-observability`  namespace.  This behavior remains the same for ACM 2.10 release.

Starting with ACM 2.10, when observability service is enabled, the behavior is changed for a hub cluster in the following ways
1. The hub collector metrics are always collected and sent to ACM Thanos instance
2. This is enabled by launching a `endpoint-operator` and `metrics-collector` in `open-cluster-management-observability` namespace on the hub (as opposed to `open-cluster-management-addon-observability` before
3. These pods are directly launched and managed by MCO operator and are not controlled via observability add-on  like before.

2024-03-18 15:54 UTC, subbarao-meduri requested changes
@oafischer please let me know if my comments need further clarification. Please let me know if you like to do a huddle given the EOB deadline.

2024-03-18 16:16 UTC, oafischer commented on observability/observability_arch.adoc
Updated

2024-03-18 16:28 UTC, oafischer commented on release_notes/whats_new.adoc
> +
Updated

2024-03-18 16:29 UTC, oafischer commented on observability/observability_arch.adoc
>  The `multiclusterhub-operator` enables the `multicluster-observability-operator` pod by default. You must configure the `multicluster-observability-operator` pod.
Given how close we are to GA, let's address this in a separate issue and focus on the new content we need for GA.

2024-03-18 16:30 UTC, oafischer commented
Thanks for your comments @subbarao-meduri, I've updated the PR based on your comments. Let me know if it looks good now.

2024-03-18 16:59 UTC, subbarao-meduri approved these changes
/lgtm

2024-03-18 16:59 UTC, subbarao-meduri commented on observability/observability_arch.adoc
Looks good! minor nit - `sendsthe` missing space

2024-03-18 16:59 UTC, subbarao-meduri commented on release_notes/whats_new.adoc
> +
Change: 

You can enable this by starting an `endpoint-operator` and `metrics-collector` pod in the `open-cluster-management-observability` namespace on your hub cluster. 

To 

When you enable observability, the service starts an `endpoint-operator` and `metrics-collector` pod in the `open-cluster-management-observability` namespace on your hub cluster. 

(since customer does not explicitly start these pods)

Everything else looks good

2024-03-18 17:07 UTC, oafischer commented on release_notes/whats_new.adoc
> +
Fixed!

2024-03-18 17:08 UTC, merged