ACM#9499: Document the hosting cluster capacity metrics
open-cluster-management/rhacm-docs pull request #6233
Opened 2024-03-14 11:23 UTC by xenolinux

https://issues.redhat.com/browse/ACM-9499

2024-03-18 17:32 UTC, xenolinux commented
@rokej This PR is ready to review. Thanks in advance!!

2024-03-19 13:50 UTC, rokej commented on clusters/hosted_control_planes/hosted_sizing_guidance.adoc
>  == Additional resources
Shouldn't https://github.com/stolostron/rhacm-docs/blob/metrics-hcp-210/clusters/hosted_control_planes/manage-metrics.adoc be referenced somewhere here?

2024-03-19 14:04 UTC, xenolinux commented on clusters/hosted_control_planes/hosted_sizing_guidance.adoc
>  == Additional resources
Correct! Addressed

2024-03-19 14:19 UTC, rokej approved these changes

2024-03-19 16:41 UTC, dockerymick requested changes

2024-03-19 16:41 UTC, dockerymick commented on clusters/hosted_control_planes/hosted_sizing_guidance.adoc
> +You can override the following sizing measurements and disable the metric service monitoring. For more information, see _Overriding resource utilization measurements_.
I suggest mentioning the Additional resource section so that we address users hyperlink expectation. Also what are the size measurements that you are referring to? 
```suggestion
You can override the following sizing measurements and disable the metric service monitoring. For more information, see _Overriding resource utilization measurements_ in the _Additional resources_ section.
```

2024-03-19 16:41 UTC, dockerymick commented on clusters/hosted_control_planes/hosted_sizing_guidance.adoc
> +|===
In the "Load-based limit" section there is a broken link. The word that is hyperlinked is "definition"
<img width="1547" alt="Screenshot 2024-03-19 at 10 48 33 AM" src="https://github.com/stolostron/rhacm-docs/assets/60616885/c202711c-df39-4a86-985a-b44076e0bd76">

2024-03-19 16:41 UTC, dockerymick commented on clusters/main.adoc
> +include::hosted_control_planes/manage-metrics.adoc[leveloffset=+3]
Very minor and is not required to be accepted. I just noticed that most of the file names use the underscore ( _ ) . The main goal is that the name of the file matches the filename, and your current update do match 
```suggestion
include::hosted_control_planes/manage_metrics.adoc[leveloffset=+3]
```

2024-03-19 16:41 UTC, dockerymick commented on clusters/hosted_control_planes/manage-metrics.adoc
> +If the overridden measurements are not updated properly in the `hcp-sizing-baseline ` config map, you might see the following error message in the `hypershift-addon-agent` pod logs:
alignment issue here:
<img width="1171" alt="Screenshot 2024-03-19 at 10 58 56 AM" src="https://github.com/stolostron/rhacm-docs/assets/60616885/5a3017ea-9aea-44f5-8f4a-25773bd28c78">

2024-03-20 09:13 UTC, xenolinux commented on clusters/main.adoc
> +include::hosted_control_planes/manage-metrics.adoc[leveloffset=+3]
Fixed!

2024-03-20 09:13 UTC, xenolinux commented on clusters/hosted_control_planes/hosted_sizing_guidance.adoc
> +You can override the following sizing measurements and disable the metric service monitoring. For more information, see _Overriding resource utilization measurements_.
Fixed

2024-03-20 09:14 UTC, xenolinux commented on clusters/hosted_control_planes/hosted_sizing_guidance.adoc
> +You can override the following sizing measurements and disable the metric service monitoring. For more information, see _Overriding resource utilization measurements_.
Updated - resource utilization sizing measurements

2024-03-20 09:15 UTC, xenolinux commented on clusters/hosted_control_planes/hosted_sizing_guidance.adoc
> +|===
I realised, that git page does not exisit anymore. So removed that wrong link

2024-03-20 09:16 UTC, xenolinux commented on clusters/hosted_control_planes/hosted_sizing_guidance.adoc
> +|===
Since "Load-based limit"  section was out of scope of this PR, sorry didn't realise this before

2024-03-20 09:17 UTC, xenolinux commented on clusters/hosted_control_planes/manage-metrics.adoc
> +If the overridden measurements are not updated properly in the `hcp-sizing-baseline ` config map, you might see the following error message in the `hypershift-addon-agent` pod logs:
Fixed!

2024-03-20 10:46 UTC, oafischer approved these changes
lgtm

2024-03-20 10:47 UTC, merged