added known issue for governance
open-cluster-management/rhacm-docs pull request #6240
Opened 2024-03-15 17:47 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-10268

2024-03-18 01:40 UTC, swopebe requested changes

2024-03-18 01:40 UTC, swopebe commented on release_notes/known_issues_governance.adoc
> +Because of this issue, if you try to apply the `ImageManifestVuln` policy, you receive the following violation message: "violation - couldn't find mapping resource with kind Subscription, please chec
@jake please be sure to note the deprecation here, see deprecation notes.

When you are given a message in quotation marks, you have to rewrite and code them appropriately for the doc. This should also be on its own line. (Plan to rewrite just about all drafts.)

Take out "because of this issue" because this is literally a known issue and that is not needed.

2024-03-18 01:42 UTC, swopebe commented on release_notes/known_issues_governance.adoc
> +Because of this issue, if you try to apply the `ImageManifestVuln` policy, you receive the following violation message: "violation - couldn't find mapping resource with kind Subscription, please chec
We need to tag developers @drkho because we should not have "please" in the content. I know it is too late to change it now...but if we are following content standards, we don't use please. (It is not imperative.)

2024-03-18 12:06 UTC, jc-berger commented on release_notes/known_issues_governance.adoc
> +Because of this issue, if you try to apply the `ImageManifestVuln` policy, you receive the following violation message: "violation - couldn't find mapping resource with kind Subscription, please chec
@swopebe this is a quote of what the violation message says. Can we even change that content?

2024-03-18 13:06 UTC, mprahl commented on release_notes/known_issues_governance.adoc
> +The container security operator is not available in {ocp-short} 3.11. Therefore, you cannot take the policy template of `policy-imagemanifestvuln-sub` in the `ImageManifestVuln` policy and apply it i
```suggestion
The container security operator is not available in {ocp-short} 3.11. Therefore, you cannot take the policy template of `policy-imagemanifestvuln-sub` in the `ImageManifestVuln` policy and apply it for {ocp-short} 3.11 clusters. 
```

2024-03-18 13:06 UTC, mprahl approved these changes
Just a small suggestion but otherwise, this looks good.

2024-03-18 13:38 UTC, mprahl approved these changes

2024-03-18 15:54 UTC, dockerymick requested changes
Beside the request to update the link, this looks good to me!

2024-03-18 15:54 UTC, dockerymick commented on release_notes/deprecate_remove.adoc
> +| See link:../release_notesl/known_issues_governance.adoc#container-security-operator-not-available-ocp[Container security operator is not available in {ocp-short} 3.11]
```suggestion
| See link:../release_notes/known_issues_governance.adoc#container-security-operator-not-available-ocp[Container security operator is not available in {ocp-short} 3.11]
```

2024-03-18 16:27 UTC, merged

2024-03-21 17:53 UTC, drkho commented
lgtm

2024-09-11 20:05 UTC, manravi commented
lgtm