Add note about eventing change (GRC)
open-cluster-management/rhacm-docs pull request #6264
Opened 2024-03-19 20:14 UTC by dhaiducek

Adding to "What's new" because the Bug issue is internal and won't be contained in the Errata.

ref: https://issues.redhat.com/browse/ACM-10527

2024-03-19 20:20 UTC, dockerymick requested changes

2024-03-19 20:20 UTC, dockerymick commented on release_notes/whats_new.adoc
> +* Previously if a policy were deleted and recreated with the same name, it would populate its status with the events from the deleted policy. Now, the status will only contain updates relevant to the
I recommend we take another look at the known issues. Does this currently exist in the doc? If yes, we should only remove the known issue. We do not announce fixes unless it's a part of the errata. Alternatively, we can add a note in the Governance doc that states: "The status only contain updates relevant to the current policy."

2024-03-19 20:25 UTC, dhaiducek commented on release_notes/whats_new.adoc
> +* Previously if a policy were deleted and recreated with the same name, it would populate its status with the events from the deleted policy. Now, the status will only contain updates relevant to the
It does not exist in the doc and wasn't listed as a known issue. But it also arose from an internal Errata, so it won't be visible to customers. I'll look for another spot we might put it.

2024-03-25 16:33 UTC, dockerymick commented on release_notes/whats_new.adoc
> +* Previously if a policy were deleted and recreated with the same name, it would populate its status with the events from the deleted policy. Now, the status will only contain updates relevant to the
@dhaiducek what are your thoughts about adding more details in the ["Status sync controller" description](https://github.com/stolostron/rhacm-docs/blob/2.10_stage/governance/grc_arch.adoc), specifically the third bullet point? 

"During each reconcile, the controller creates and updates the policy status for the hub cluster and managed cluster in the cluster namespace, based on the policy changes or generated events. The status only contain updates that are relevant to the policy."

2024-03-29 17:45 UTC, dhaiducek commented on release_notes/whats_new.adoc
> +* Previously if a policy were deleted and recreated with the same name, it would populate its status with the events from the deleted policy. Now, the status will only contain updates relevant to the
@dockerymick Thanks for the review--I've moved the note and tweaked your wording a little bit. Please take another look when you have a moment.

2024-03-29 19:02 UTC, dockerymick approved these changes
Looks good to me! @dhaiducek thanks for accepting my suggestion!

2024-03-29 19:45 UTC, cadawson commented on governance/grc_arch.adoc
> +* During each reconcile, the controller creates and updates the policy status for the hub cluster and managed cluster in the cluster namespace, based on the policy changes or generated events. The st
```suggestion
* During each reconcile, the controller creates and updates the policy status for the hub cluster and managed cluster in the cluster namespace, based on the policy changes or generated events. The status only contains updates that are relevant to the current policy and does not consider past statuses if the policy was deleted and recreated.
```

Interpretation of what I think I am reading to make sure: It will show you a status that only applies to the current policy if the policy was deleted and recreated. It doesn't retain the history of the past statuses from before it was blown away and recreated. Is that it? If so, looks good!

2024-03-29 19:46 UTC, dhaiducek commented on governance/grc_arch.adoc
> +* During each reconcile, the controller creates and updates the policy status for the hub cluster and managed cluster in the cluster namespace, based on the policy changes or generated events. The st
Yes, that's correct @cadawson

2024-03-29 19:46 UTC, cadawson approved these changes
I think this looks good. Thanks. I included a suggestion and a clarification of what I think this means. If I understood it right, then you are good to go. Thanks!

2024-03-29 19:48 UTC, jc-berger approved these changes
/lgtm

2024-04-01 12:21 UTC, dockerymick commented
@cadawson @jc-berger thanks for the reviews and approvals! @dhaiducek thanks for accepting my suggestion and creating the PR! Merging this PR

2024-04-01 12:21 UTC, merged