Fix the Governance RBAC documentation
open-cluster-management/rhacm-docs pull request #6271
Opened 2024-03-21 14:12 UTC by mprahl

Fixes:
https://issues.redhat.com/browse/ACM-10602

2024-03-21 14:17 UTC, mprahl commented
/cc @dhaiducek 

Could you please also review this?

2024-03-21 18:55 UTC, swopebe commented
I will take this one, some rewrite is needed. This will go into the next refresh after today.

2024-03-28 16:47 UTC, dhaiducek requested changes

2024-03-28 16:47 UTC, dhaiducek commented on access_control/rbac_implement_rhacm.adoc
> +oc create clusterrole rhacm-edit-policy --resource=policies.policy.open-cluster-management.io,placementbindings.policy.open-cluster-management.io,policyautomations.policy.open-cluster-management.io -
We could just bind to the aggregate role...
```
oc create rolebinding rhacm-edit-policy -n rhacm-policies --clusterrole=open-cluster-management:view-aggregate --user=<username>
```

Ref:
```
- apiGroups: ["policy.open-cluster-management.io"]
  resources: ["policies","policies/status","placementbindings","policyautomations", "policysets"]
  verbs: ["get", "list", "watch", "update", "patch"]
```
https://github.com/stolostron/multiclusterhub-operator/blob/69b5cb79396ce49e97fa616d201aa06392b31d55/pkg/templates/multiclusterhub/base/clusterrole-edit-aggregate.yaml#L19

(Though why `policies/status` is in there is both unknown and rather frightening?)

Alternatively, we add this role to the `multiclusterhub-operator` repo (App Lifecycle already has one there: https://github.com/stolostron/multiclusterhub-operator/tree/main/pkg/templates/multiclusterhub/base

2024-03-28 16:47 UTC, dhaiducek commented on access_control/rbac_implement_rhacm.adoc
> +oc create clusterrole rhacm-view-policy --resource=policies.policy.open-cluster-management.io --verb=get,list,watch
Same as above.
```
- apiGroups: ["policy.open-cluster-management.io"]
  resources: ["policies","policies/status","placementbindings","policyautomations", "policysets"]
  verbs: ["get", "list", "watch"]
```
https://github.com/stolostron/multiclusterhub-operator/blob/69b5cb79396ce49e97fa616d201aa06392b31d55/pkg/templates/multiclusterhub/base/clusterrole-view-aggregate.yaml#L19

2024-03-28 16:47 UTC, dhaiducek commented on access_control/rbac_implement_rhacm.adoc
> +oc create clusterrole rhacm-edit-policy --resource=policies.policy.open-cluster-management.io,placementbindings.policy.open-cluster-management.io,policyautomations.policy.open-cluster-management.io -
PolicySets is missing.

```suggestion
oc create clusterrole rhacm-edit-policy --resource=policies.policy.open-cluster-management.io,policysets.policy.open-cluster-management.io,placementbindings.policy.open-cluster-management.io,policyautomations.policy.open-cluster-management.io --verb=create,delete,get,list,patch,update,watch
```

2024-03-28 20:00 UTC, mprahl commented on access_control/rbac_implement_rhacm.adoc
> +oc create clusterrole rhacm-edit-policy --resource=policies.policy.open-cluster-management.io,placementbindings.policy.open-cluster-management.io,policyautomations.policy.open-cluster-management.io -
I think the edit role is perhaps too permissive. I'll add policy sets though. Good catch!

2024-03-28 20:02 UTC, mprahl commented on access_control/rbac_implement_rhacm.adoc
> +oc create clusterrole rhacm-view-policy --resource=policies.policy.open-cluster-management.io --verb=get,list,watch
This one is for the managed cluster namespace so policy sets wouldn't apply in this case.

2024-03-28 20:12 UTC, dhaiducek commented on access_control/rbac_implement_rhacm.adoc
> +oc create clusterrole rhacm-edit-policy --resource=policies.policy.open-cluster-management.io,placementbindings.policy.open-cluster-management.io,policyautomations.policy.open-cluster-management.io -
Okay, I think it'd be nicer if these roles existed out of the box. I'll create an issue to add it for a future release.

2024-03-28 20:20 UTC, dhaiducek commented on access_control/rbac_implement_rhacm.adoc
> +oc create clusterrole rhacm-edit-policy --resource=policies.policy.open-cluster-management.io,placementbindings.policy.open-cluster-management.io,policyautomations.policy.open-cluster-management.io -
Issue created: https://issues.redhat.com/browse/ACM-10778

2024-04-01 18:49 UTC, swopebe approved these changes

2024-04-01 19:31 UTC, dockerymick approved these changes
Thanks for the updates!

2024-04-01 20:32 UTC, dhaiducek approved these changes

2024-04-01 20:46 UTC, merged