fixedbroken link
open-cluster-management/rhacm-docs pull request #6284
Opened 2024-03-25 15:27 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-10400

2024-03-25 18:35 UTC, swopebe requested changes

2024-03-25 18:35 UTC, swopebe commented on global_hub/global_hub_overview.adoc
> +- link:https://github.com/stolostron/rhacm-docs/blob/2.10_stage/global_hub/global_hub_backup.adoc[Backup for {global-hub}]
@jc-berger this is not a link that we should be using in the docs.

2024-03-27 23:01 UTC, dockerymick commented
Verified that the links work, adding my approval to get this in before refresh

2024-03-27 23:01 UTC, dockerymick approved these changes

2024-03-27 23:01 UTC, merged