https://issues.redhat.com/browse/ACM-10611
open-cluster-management/rhacm-docs pull request #6292
Opened 2024-03-26 17:21 UTC by dockerymick

2024-03-26 17:57 UTC, mprahl commented on release_notes/known_issues_governance.adoc
> +If there is data loss to the PostgreSQL server such as restoring to a backup without the latest data, the Governance Policy Propagator on the RHACM hub must be restarted so that it can update the map
```suggestion
If there is data loss to the PostgreSQL server such as restoring to a backup without the latest data, the Governance Policy Propagator on the {product-title-short} hub must be restarted so that it can update the mapping of policies to database IDs. Until the Governance Policy Propagator is restarted, new compliance events associated with policies that once existed in the database but no longer exist will not be recorded. To restart the Governance Policy Propagator, you may use the following command on the {product-title-short} hub:
```

2024-03-26 17:58 UTC, mprahl commented on release_notes/known_issues_governance.adoc
> +kubectl -n open-cluster-management rollout restart deployment/grc-policy-propagator
```suggestion
oc -n open-cluster-management rollout restart deployment/grc-policy-propagator
```

2024-03-26 18:00 UTC, mprahl commented on troubleshooting/trouble_gov_framework.adoc
> +[#troubleshooting-gov-framework]
Could you please add context that this is referring to troubleshooting compliance events in the policy compliance history API? Without this context, a user might assume this refers to the compliance status in the policy in Kubernetes.

2024-03-26 18:01 UTC, mprahl commented on troubleshooting/trouble_postgresql.adoc
> +[#troubleshooting-postgresql]
Similar to my previous comment about the context is not clear.

2024-03-26 18:01 UTC, mprahl commented on troubleshooting/trouble_postgresql.adoc
> +When the RHACM hub has issues connecting to the PostgreSQL server, you may see Kubernetes events in the RHACM namespace with the following command:
```suggestion
When the {product-title-short} hub has issues connecting to the PostgreSQL server, you may see events in the {product-title-short} namespace with the following command:
```

2024-03-26 18:01 UTC, mprahl commented on troubleshooting/trouble_postgresql.adoc
> +== Symptom: Expired credentials for agents
This seems unrelated to ACM-10611.

2024-03-27 14:22 UTC, dockerymick commented on troubleshooting/trouble_postgresql.adoc
> +== Symptom: Expired credentials for agents
@mprahl it is, I was just creating a place holder and pulled a section from a previous topic. Still working on making updates. Thanks for your review and suggestions thus far

2024-03-27 19:54 UTC, dockerymick commented on troubleshooting/trouble_gov_framework.adoc
> += Troubleshooting the governance policy framework
```suggestion
= Troubleshooting compliance events in the compliance history API (Technology Preview)
```

2024-03-27 19:56 UTC, dockerymick commented on troubleshooting/main.adoc
> +include::trouble_gov_framework.adoc[leveloffset=+2]
```suggestion
include::trouble_compliance_history.adoc[leveloffset=+2]
```

2024-03-27 22:05 UTC, dockerymick reviewed
making suggestions and continuing to edit

2024-03-27 22:05 UTC, dockerymick commented on troubleshooting/trouble_compliance_history.adoc
> +If policy compliance events are not being recorded for a particular managed cluster, you may look at the `governance-policy-framework` logs on the affected managed cluster:
```suggestion
Some policy compliance events are not being recorded for a particular managed cluster.
```

2024-03-27 22:05 UTC, dockerymick commented on troubleshooting/trouble_compliance_history.adoc
> +//still workin on this
```suggestion
Look at the `governance-policy-framework` logs on the affected managed cluster with the following command:

----
oc -n open-cluster-management-agent-addon logs deployment/governance-policy-framework -f
----
```

2024-03-27 22:05 UTC, dockerymick commented on troubleshooting/trouble_compliance_history.adoc
> +----
```suggestion
```

2024-03-27 22:05 UTC, dockerymick commented on troubleshooting/trouble_postgresql.adoc
> += Troubleshooting the PostgreSQL connection
```suggestion
= Troubleshooting the PostgreSQL connection to the compliance history API (Technology Preview) 
```

2024-03-27 22:05 UTC, dockerymick commented on troubleshooting/trouble_postgresql.adoc
> +[#troubleshooting-postgresql]
```suggestion
[#troubleshooting-postgresql-compliance-history]
```

2024-03-27 22:19 UTC, dockerymick commented on troubleshooting/trouble_postgresql.adoc
> +//from the draft, its not as clear how the user can fix this. how can th user update the config for the connection?
@mprahl will you help here

2024-04-01 16:46 UTC, dockerymick commented on troubleshooting/trouble_postgresql.adoc
> +[#resolving-cluster-rotating-agents]
```suggestion
[#resolving-postgresql-server-connection]
```

2024-04-01 16:46 UTC, dockerymick commented on troubleshooting/trouble_postgresql.adoc
> +== Resolving the problem: Manually rotate credentials for agents
```suggestion
== Resolving the problem: PostgreSQL connection to the compliance history API (Technology Preview)
```

2024-04-01 16:47 UTC, dockerymick commented on troubleshooting/trouble_postgresql.adoc
> +[#symptom-cluster-rotating-agents]
```suggestion
[#symptom-failed-postgresql-connection]
```

2024-04-01 16:49 UTC, dockerymick commented on troubleshooting/trouble_postgresql.adoc
> +== Symptom: Expired credentials for agents
```suggestion
== Symptom: PostgreSQL authentication fail
```

2024-04-01 18:58 UTC, swopebe commented on troubleshooting/trouble_compliance_history.adoc
> +
I think we don't need the tech preview tag on a troubleshooting topic. The reason why: That is used in the title and nav to highlight new function. I think since we are highlighting here a work around, we may not want that tag....to me it suggests that the actual workaround is tech preview. 

You can always put a line in the content in a spot like this:

...which indicates the policy compliance history API (Technology Preview) could not be reached

2024-04-01 18:59 UTC, swopebe commented on troubleshooting/trouble_compliance_history.adoc
> +You might see a message value that is empty in the log message, which indicates the policy compliance history API could not be reached. A likely cause is the policy compliance history API URL is not
A possible cause?
Not sure we use "likely" given we don't use the word "like" much.

2024-04-01 19:00 UTC, swopebe commented on troubleshooting/trouble_compliance_history.adoc
> +
View the ....logs

2024-04-01 19:00 UTC, swopebe commented on troubleshooting/trouble_postgresql.adoc
> +The connection between PostgreSQL server and the policy compliance history API. For example, if you want to check for events where `reason=OCMComplianceEventsDBError` on your {product-title} hub clus
The connection between PostgreSQL server and the policy compliance history API.

The suspense is killing me...

2024-04-01 19:01 UTC, swopebe commented on troubleshooting/trouble_postgresql.adoc
> +Limited details are provided and you are instructed to view the `governance-policy-propagator` logs for further details. Run the following command to check the `governance-policy-propagator` logs:
imited details are provided. You can view the.....for more information.

2024-04-01 19:02 UTC, swopebe commented on troubleshooting/trouble_postgresql.adoc
> +The connection between PostgreSQL server and the policy compliance history API. For example, if you want to check for events where `reason=OCMComplianceEventsDBError` on your {product-title} hub clus
Same with tech preview tag, here.

2024-04-01 19:02 UTC, swopebe requested changes
few comments for consideration

2024-04-03 17:59 UTC, dockerymick commented on troubleshooting/trouble_compliance_history.adoc
> +Look at the `governance-policy-framework` logs on the affected managed cluster with the following command:
```suggestion
View the `governance-policy-framework` logs on the affected managed cluster with the following command:
```

2024-04-03 18:00 UTC, dockerymick commented
Attempted to update this PR, instead I will close this and create a new one

2024-04-03 18:00 UTC, closed without merging