added content on namespaces and import controller
open-cluster-management/rhacm-docs pull request #6314
Opened 2024-04-03 19:02 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-10536

2024-04-03 19:03 UTC, jc-berger commented on business_continuity/backup_restore/backup_arch.adoc
> +
I'm thinking it suffices to only have the bullet list. But I thought I'd start with more content, since it's easy to remove content. 

Anyway, reviewers, let me know if you think these sentences can be removed: 

```
Because of the absence of the `managedCluster` custom resource (CR), the import controller can delete your namespace, even after you have restored it. If you restore the `managedCluster` CR, then the registration controller automatically creates a namespace.
```

2024-04-03 20:11 UTC, oafischer commented on business_continuity/backup_restore/backup_arch.adoc
> +
Since the paragraph repeats info that is already in the bullets, I would just go with the bullets if they have sufficient info for the reader.

2024-04-04 03:15 UTC, zhujian7 commented on business_continuity/backup_restore/backup_arch.adoc
> +
yes, simple is good. For me, "For any resource in the managed cluster namespace and the managed cluster namespace itself, you must restore it at the cluster activation step." is straightforward.

2024-04-04 03:15 UTC, zhujian7 commented on business_continuity/backup_restore/backup_arch.adoc
> +* If you restore the namespace, then the import controller deletes the namespace.
Not sure if we need to hide the internal component names? the `import controller` and `registration controller`

2024-04-04 14:14 UTC, jc-berger commented on business_continuity/backup_restore/backup_arch.adoc
> +* If you restore the namespace, then the import controller deletes the namespace.
I think it's fine as is.

2024-04-07 04:07 UTC, zhujian7 commented on business_continuity/backup_restore/backup_arch.adoc
> +* If you restore the namespace, then the import controller deletes the namespace.
the exact components are: `managedcluster-import-controller` and `cluster-manager-registration-controller`

Some details may not need to be reflected in the final document, just for better understanding:
- when we say the managed cluster namespace, it is a namespace with the same name as the managed cluster and the label `cluster.open-cluster-management.io/managedCluster`.
- `managedcluster-import-controller` only deletes the managed cluster namespace(for other namespaces, it does not care) if there is no ManagedCluster CR in the cluster.

2024-04-09 01:29 UTC, zhujian7 commented on business_continuity/backup_restore/backup_arch.adoc
> +* If you restore the namespace, then the import controller deletes the namespace.
```suggestion
* If you restore the namespace, then the managedcluster-import-controller deletes the namespace. 
```

2024-04-09 01:29 UTC, zhujian7 commented on business_continuity/backup_restore/backup_arch.adoc
> +* If you restore the `managedCluster` custom resource (CR), then the registration controller creates the namespace.
```suggestion
* If you restore the `managedCluster` custom resource (CR), then the cluster-manager-registration-controller creates the namespace. 
```

2024-04-09 01:29 UTC, zhujian7 commented on business_continuity/backup_restore/backup_arch.adoc
> +To understand the exact internal components, see the following:
Use the following components names in the above section, so we can delete this.

~To understand the exact internal components, see the following:~

~* `managedcluster-import-controller`~
~* `cluster-manager-registration-controller`~

2024-04-09 01:31 UTC, zhujian7 commented
@birsanv could you help take a look at this PR?

2024-04-09 15:05 UTC, birsanv requested changes

2024-04-09 15:05 UTC, birsanv commented on business_continuity/backup_restore/backup_arch.adoc
> +
Remove this sentence : After you create the managed cluster, restore the managed cluster namespace.

Reason : The user doesn't  control the order in which the managed cluster or the ns is being restored. So it will be confusing to see these instructions ( we, under the cover, restore the managed cluster global resource first )

2024-04-11 12:40 UTC, dockerymick approved these changes
Left a suggestion. We typically write "customer resource"

2024-04-11 12:40 UTC, dockerymick commented on business_continuity/backup_restore/backup_arch.adoc
> +* If you restore the `managedCluster` custom resource (CR), then the `cluster-manager-registration-controller` creates the namespace.
```suggestion
*Note:* For any managed cluster namespace, or any resource in it, you must restore either one at the cluster activation step. Therefore, if you need to add to the backup resource created in the managed cluster namespace, then use the `cluster-activation` value for the `cluster.open-cluster-management.io/backup` label. To understand the restore process, see the following information: 

* If you restore the namespace, then the `managedcluster-import-controller` deletes the namespace. 
* If you restore the `managedCluster` custom resource, then the `cluster-manager-registration-controller` creates the namespace. 
```

2024-04-11 19:48 UTC, jc-berger commented
@birsanv and/or @zhujian7 now that I've applied y'alls and Doc's feedback, would you please let me know if you think this PR is good to merge? Thanks :)

2024-04-11 20:04 UTC, birsanv approved these changes
lgtm

2024-04-11 20:04 UTC, birsanv commented on business_continuity/backup_restore/backup_arch.adoc
> +* If you restore the namespace, then the `managedcluster-import-controller` deletes the namespace.
Replace line 96 and 97  with:
 The `ManagedCluster` global custom resource (CR) is restored at cluster activation data, before any other resources are being restored.
If you restore the managed cluster namespace or any resource from the managed cluster namespace before the cluster activation step, so before the `ManagedCluster` global custom resource (CR) is restored, the `managedcluster-import-controller` deletes the namespace and all the resources under it.

2024-04-12 02:20 UTC, zhujian7 commented
lgtm

2024-04-12 16:42 UTC, merged