https://issues.redhat.com/browse/ACM-10611 update verification compliance history
open-cluster-management/rhacm-docs pull request #6319
Opened 2024-04-04 16:49 UTC by dockerymick

https://issues.redhat.com/browse/ACM-10611

2024-04-04 18:27 UTC, cadawson reviewed
Looks good. Alternate example added and a typo fix. Thanks!

2024-04-04 18:27 UTC, cadawson commented on governance/compliance_history.adoc
> +* If it is not successful, the curl command might return either of the two messages:
```suggestion
* If it is not successful, the curl command might return either of these two messages:
```

2024-04-04 18:27 UTC, cadawson commented on governance/compliance_history.adoc
> +* If it is not successful, the curl command might return either of the two messages:
Alternate thought here to approach it in a less formal way. For example:

If it is not successful, the curl command might return an error message indicating an unavailable database or an internal error. If this happens, view the Kubernetes events in the `open-cluster-management` namespace with the following command:
+
[source,bash]
----
oc -n open-cluster-management get events --field-selector reason=OCMComplianceEventsDBError
----

Follow the instructions to view the `governance-policy-propagator` logs to determine if it is a password issue.

2024-04-04 19:02 UTC, mprahl commented on governance/compliance_history.adoc
> +//Is this info about success and failure important to the user? If we only provide 1 verification step to check if the password is specified correctly, can the user skip this?
Yes, it's important because an invalid password is just one potential issue.

2024-04-04 19:04 UTC, mprahl commented on governance/compliance_history.adoc
> +.. Instructions are displayed for you to view the `governance-policy-propagator` logs. Run the following command:
Can we word it similar to this?
```suggestion
.. The event may instruct to view the `governance-policy-propagator` logs. In this case, run the following command:
```

2024-04-04 19:05 UTC, mprahl commented on governance/compliance_history.adoc
> +//where can the user update the password specification? Do they update the compliance history API YAML?
The password was specified in the `oc -n open-cluster-management create secret generic governance-policy-database` command from above. I think instructing them to update the `governance-policy-database` `Secret` that was created above if this is the issue is sufficient.

2024-04-04 19:06 UTC, mprahl commented on governance/compliance_history.adoc
> +.. You might see a similar error message, which indicates that the password is not correctly specified:
```suggestion
.. You might see a similar error message, which indicates that the user, password, or database is not correctly specified:
```

2024-04-04 19:06 UTC, mprahl commented on governance/compliance_history.adoc
> +[#enable-single-managed-cluster]
Separating out the options is much better. Thanks!

2024-04-05 13:51 UTC, dockerymick commented on governance/compliance_history.adoc
> +//Is this info about success and failure important to the user? If we only provide 1 verification step to check if the password is specified correctly, can the user skip this?
```suggestion
```

2024-04-05 13:51 UTC, dockerymick commented on governance/compliance_history.adoc
> +.. Instructions are displayed for you to view the `governance-policy-propagator` logs. Run the following command:
```suggestion
.. You might receive instructions from the event to view the `governance-policy-propagator` logs. In this case, run the following command:
```

2024-04-05 13:51 UTC, dockerymick commented on governance/compliance_history.adoc
> +//where can the user update the password specification? Do they update the compliance history API YAML?
```suggestion
+
.. Update the `governance-policy-database` `Secret` resource with the following command:
+
[source,bash]
----
oc -n open-cluster-management create secret generic governance-policy-database
----
```

2024-04-05 16:24 UTC, mprahl commented on governance/compliance_history.adoc
> +oc -n open-cluster-management create secret generic governance-policy-database
```suggestion
oc -n open-cluster-management edit secret governance-policy-database
```

2024-04-05 16:26 UTC, mprahl commented on governance/compliance_history.adoc
> +//How can users fix this connection error?
If the policy compliance history API URL is incorrect, you may edit the URL on the hub cluster with this command:
```yaml
oc -n open-cluster-management edit AddOnDeploymentConfig governance-policy-framework
```

2024-04-05 16:36 UTC, dockerymick commented on governance/compliance_history.adoc
> +//How can users fix this connection error?
What about the network communication? or are we saying that the incorrect URL indicates that there is a network communication issue?

2024-04-05 16:37 UTC, dockerymick commented on governance/compliance_history.adoc
> +//How can users fix this connection error?
```suggestion
+
.. If the policy compliance history API URL is incorrect, edit the URL on the hub cluster with the following command:
+
[source,bash]
----
oc -n open-cluster-management edit AddOnDeploymentConfig governance-policy-framework
----
```

2024-04-05 16:47 UTC, mprahl commented on governance/compliance_history.adoc
> +//How can users fix this connection error?
@dockerymick the network communication is out of the scope of ACM so that would be up to the user to diagnose based on their network infrastructure.

2024-04-05 17:47 UTC, dockerymick commented on governance/compliance_history.adoc
> +* If it is not successful, the curl command might return either of the two messages:
Thanks for the suggestion Chris. In my opinion this is wordy. The error messages are clear

2024-04-05 17:47 UTC, dockerymick commented on governance/compliance_history.adoc
> +.. To address the connection failure, view the Kubernetes events in the `open-cluster-management` namespace with the following command:
```suggestion
.. If this happens, view the Kubernetes events in the `open-cluster-management` namespace with the following command:
```

2024-04-05 17:52 UTC, dockerymick commented on governance/compliance_history.adoc
> +//How can users fix this connection error?
@mprahl thanks for agreeing with my suggestion. Heads up, that i did make edits to the suggestion. I added a note to let the user know they are responsible for resolving the  connection issue. Let me know your thoughts

2024-04-05 18:22 UTC, mprahl commented on governance/compliance_history.adoc
> +//How can users fix this connection error?
@dockerymick sounds great.

2024-04-05 20:02 UTC, jc-berger approved these changes
/lgtm

2024-04-05 20:22 UTC, swopebe commented on governance/compliance_history.adoc
>  +
these is self-referential, consider "of the following" -- IBM Style manual mentions not using self-referential that we all should review, I will find it for our standards meeting. @jc-berger @dockerymick

2024-04-05 20:22 UTC, swopebe commented on governance/compliance_history.adoc
>  +
If these are two different messages, they need to be broken up.

2024-04-05 20:23 UTC, swopebe commented on governance/compliance_history.adoc
> +.. If this happens, view the Kubernetes events in the `open-cluster-management` namespace with the following command:
If this happens,

After you receive a message, 

If you receive a message, 

again -- referential

2024-04-05 20:24 UTC, swopebe commented on governance/compliance_history.adoc
> +.. You might receive instructions from the event to view the `governance-policy-propagator` logs. In this case, run the following command:
Please remove _In this case_

See guidance for concise writing and wordiness. Again, I will raise this in our meeting and we can look at some examples.

2024-04-05 20:26 UTC, swopebe commented on governance/compliance_history.adoc
> +.. You might see a similar error message, which indicates that the user, password, or database is not correctly specified:
It is not clear that I might see a similar message that is coming up in this section.

a message similar to the following message?

2024-04-05 20:26 UTC, swopebe commented on governance/compliance_history.adoc
> ++
perfect!

2024-04-05 20:28 UTC, swopebe commented on governance/compliance_history.adoc
> +
needs a description...what is this and why do it... you repeat the title in the step -- it may be that the description in the step is what is after the header....we need some sort of description after every header.

2024-04-05 20:28 UTC, swopebe commented on governance/compliance_history.adoc
> +
same here

2024-04-05 20:29 UTC, swopebe commented on governance/compliance_history.adoc
>  +
Looks like there may need to be a space here before line 157?

2024-04-05 20:29 UTC, swopebe commented on governance/compliance_history.adoc
Throughout this PR, there are spacing issues that you can see by what is grayed out and what is not....this needs to be addressed in peer reviews. Remember a simple space corrects this.

2024-04-05 20:30 UTC, swopebe requested changes
See comments, this needs a bit more work.

2024-04-05 20:31 UTC, swopebe commented on release_notes/known_issues_governance.adoc
> +If you create or update a new policy during a database outage, any compliance events sent for this new policy cannot be recorded since the mapping of policies to database IDs cannot be updated. Once
@jc-berger we need to not use "once" so that does not pass peer review. 

"After"

2024-04-05 20:46 UTC, mprahl commented on governance/compliance_history.adoc
> +.. You might receive instructions from the event to view the `governance-policy-propagator` logs. In this case, run the following command:
The purpose of "In this  case" is to let the user know they should only run that command if the previous sentence was what they observed since that sentence says "might".

How do we still keep a qualifier without it being wordy?

2024-04-05 21:04 UTC, dockerymick commented on governance/compliance_history.adoc
> +*Note:* If you experience a network communication issue, you must diagnose the problem based on your network infrastructure.
```suggestion
+
*Note:* If you experience a network communication issue, you must diagnose the problem based on your network infrastructure.
```

2024-04-05 21:05 UTC, dockerymick commented on governance/compliance_history.adoc
> +* If it is not successful, the curl command might return either of these two messages:
```suggestion
* If it is not successful, the curl command might return either of the two messages:
```

2024-04-05 21:08 UTC, dockerymick commented on governance/compliance_history.adoc
> +.. If this happens, view the Kubernetes events in the `open-cluster-management` namespace with the following command:
```suggestion
.. If you receive a message, view the Kubernetes events in the `open-cluster-management` namespace with the following command:
```

2024-04-05 21:10 UTC, dockerymick commented on governance/compliance_history.adoc
> +.. You might receive instructions from the event to view the `governance-policy-propagator` logs. In this case, run the following command:
```suggestion
.. You might receive instructions from the event to view the `governance-policy-propagator` logs. Run the following command:
```

2024-04-05 21:10 UTC, dockerymick commented on governance/compliance_history.adoc
> +.. You might see a similar error message, which indicates that the user, password, or database is not correctly specified:
Here is the message in the example, "The database connection failed: pq: password authentication failed for user "rhacm-policy-compliance-history""

2024-04-05 21:12 UTC, dockerymick commented on governance/compliance_history.adoc
> +Complete the following steps:
```suggestion
Set the policy compliance history API URL to enable the feature on managed clusters. Complete the following steps:
```

2024-04-05 21:13 UTC, dockerymick commented on governance/compliance_history.adoc
>  . Set the policy compliance history API URL. To enable the feature on managed clusters, retrieve the external URL of the policy compliance history API with the following command:
```suggestion
. Retrieve the external URL of the policy compliance history API with the following command:
```

2024-04-05 21:15 UTC, dockerymick commented on governance/compliance_history.adoc
> +Complete the following steps:
```suggestion
Enable the compliance history API on all managed clusters to receive compliance events from your managed clusters. Complete the following steps:
```

2024-04-05 21:15 UTC, dockerymick commented on governance/compliance_history.adoc
> +. To enable the compliance history API on all managed clusters, configure the `governance-policy-framework` `ClusterManagementAddOn` object to use the `AddOnDeploymentConfig` with the following comma
```suggestion
.  Configure the `governance-policy-framework` `ClusterManagementAddOn` object to use the `AddOnDeploymentConfig` with the following command:
```

2024-04-05 21:17 UTC, dockerymick commented on governance/compliance_history.adoc
> +Complete the following steps:
```suggestion
Enable the compliance history API on a single managed cluster to receive compliance events from the managed cluster. Complete the following steps:
```

2024-04-05 21:17 UTC, dockerymick commented on governance/compliance_history.adoc
>  . To enable the policy compliance history API on a single managed cluster, configure the `governance-policy-framework` `ManagedClusterAddOn` resource in the managed cluster namespace. Run the followi
```suggestion
. Configure the `governance-policy-framework` `ManagedClusterAddOn` resource in the managed cluster namespace. Run the following command from your {product-title-short} hub cluster with the following command: 
```

2024-04-05 21:21 UTC, dockerymick commented on release_notes/known_issues_governance.adoc
> +If you create or update a new policy during a database outage, any compliance events sent for this new policy cannot be recorded since the mapping of policies to database IDs cannot be updated. Once
@swopebe when I did a search, the word "after" only appears in the **Configuration policy listed complaint when namespace is stuck in Terminating state**. I can update that portion of the file, but I can see how it was missed. Thanks for bringing it to our attention.
<img width="1118" alt="Screenshot 2024-04-05 at 5 20 53 PM" src="https://github.com/stolostron/rhacm-docs/assets/60616885/96de4969-941c-425d-92f0-12d918bf590b">

2024-04-05 21:40 UTC, swopebe commented on release_notes/known_issues_governance.adoc
> +If there is data loss to the PostgreSQL server such as restoring to a backup without the latest data, the governance policy propagator on the {product-title-hsort} hub cluster must be restarted so th
Please break this paragraph up...."to restart" begins a task for the user and it is embedded in a paragraph at the moment.

2024-04-05 21:40 UTC, swopebe commented on governance/compliance_history.adoc
> +
space issue

2024-04-05 21:40 UTC, swopebe commented on governance/compliance_history.adoc
> ++
space issue

2024-04-05 21:40 UTC, swopebe commented on governance/compliance_history.adoc
> +.. You might receive instructions from the event to view the `governance-policy-propagator` logs. In this case, run the following command:
Much of this can just be a simple rewrite to one step; we should always start off a step with the verb anyway. Something like:

Run the following command if you receive instructions from the event to view the `governance-policy-propagator` logs:

or 

If you....., then run....

2024-04-05 21:40 UTC, swopebe commented on governance/compliance_history.adoc
> +.. You might receive instructions from the event to view the `governance-policy-propagator` logs. In this case, run the following command:
@dockerymick I didn't want to dictate how you would write it but we can almost always be this clear and concise ^^^^^ if you want to try one of those options with @mprahl

2024-04-05 21:40 UTC, swopebe commented on governance/compliance_history.adoc
> +.. You might see a similar error message, which indicates that the user, password, or database is not correctly specified:
meaning the line, if I were using a screen reader, does not make it clear to me that something "similar" is following.

2024-04-05 21:40 UTC, swopebe commented on release_notes/known_issues_governance.adoc
> +If you create or update a new policy during a database outage, any compliance events sent for this new policy cannot be recorded since the mapping of policies to database IDs cannot be updated. Once
The standard is here:

_once adverb
Use only to mean one time. Do not use as a conjunction to mean after or when._

https://www.ibm.com/docs/en/ibm-style?topic=word-usage

It's fine, I typically review and would think most of the time we review all the green in the PR, it could be I can see the no-no words quickly at this point lol.

2024-04-05 21:40 UTC, swopebe commented on release_notes/known_issues_governance.adoc
> +If there is data loss to the PostgreSQL server such as restoring to a backup without the latest data, the governance policy propagator on the {product-title-hsort} hub cluster must be restarted so th
also there is a once here

2024-04-05 21:57 UTC, dockerymick commented on governance/compliance_history.adoc
> +
I'm not sure what spacing issue you are referring to. This is what I see when I preview the file:
<img width="1115" alt="Screenshot 2024-04-05 at 5 56 10 PM" src="https://github.com/stolostron/rhacm-docs/assets/60616885/1f37d9ee-bbc2-47cd-a2a6-527dab49fc54">

2024-04-05 21:59 UTC, dockerymick commented on release_notes/known_issues_governance.adoc
> +If there is data loss to the PostgreSQL server such as restoring to a backup without the latest data, the governance policy propagator on the {product-title-hsort} hub cluster must be restarted so th
```suggestion
If there is data loss to the PostgreSQL server such as restoring to a backup without the latest data, the governance policy propagator on the {product-title-hsort} hub cluster must be restarted so that it can update the mapping of policies to database IDs. Until you restart the governance policy propagator, new compliance events associated with policies that once existed in the database are no longer recorded. 

To restart the governance policy propagator, run the following command on the {product-title-short} hub cluster:
```

2024-04-05 22:00 UTC, dockerymick commented on release_notes/known_issues_governance.adoc
> +If you create or update a new policy during a database outage, any compliance events sent for this new policy cannot be recorded since the mapping of policies to database IDs cannot be updated. Once
```suggestion
If you create or update a new policy during a database outage, any compliance events sent for this new policy cannot be recorded since the mapping of policies to database IDs cannot be updated. When the database is back online, the mapping is automatically updated and future compliance events from those policies are recorded.
```

2024-04-05 22:04 UTC, dockerymick commented on governance/compliance_history.adoc
> +.. You might see a similar error message, which indicates that the user, password, or database is not correctly specified:
```suggestion
.. You might see an error message that indicates the user, password, or database is incorrectly specified. See the following message example:
```

2024-04-08 13:23 UTC, mprahl commented on governance/compliance_history.adoc
> +.. Update the `governance-policy-database` `Secret` resource with the following command:
Could we clarify that you only need to update if you did see the previous error message?
```suggestion
.. Update the `governance-policy-database` `Secret` resource with the correct connection settings with the following command:
```

2024-04-08 13:25 UTC, mprahl commented on governance/compliance_history.adoc
> +Enable the compliance history API on all managed clusters to receive compliance events from your managed clusters. Complete the following steps:
```suggestion
Enable the compliance history API on all managed clusters to record compliance events from your managed clusters. Complete the following steps:
```

2024-04-08 13:25 UTC, mprahl commented on governance/compliance_history.adoc
> +Enable the compliance history API on a single managed cluster to receive compliance events from the managed cluster. Complete the following steps:
```suggestion
Enable the compliance history API on a single managed cluster to record compliance events from the managed cluster. Complete the following steps:
```

2024-04-08 13:29 UTC, mprahl commented on release_notes/known_issues_governance.adoc
> +When you have a configuration policy that is configured with `mustnothave` for the `complianceType` parameter and `enforce` for the `remediationAction` parameter, the policy is listed as compliant wh
In the future, I'd suggest separating unrelated documentation changes to separate PRs. It keeps the reviews shorter and the reviewers may be different based on the different content being updated.

2024-04-08 18:18 UTC, mprahl approved these changes

2024-04-08 19:34 UTC, swopebe approved these changes

2024-04-08 23:13 UTC, merged