Update the governance architecture section
open-cluster-management/rhacm-docs pull request #6326
Opened 2024-04-05 16:19 UTC by mprahl

2024-04-10 14:23 UTC, dockerymick requested changes
@mprahl thanks for your updates on the component descriptions. I left some comments

2024-04-10 14:23 UTC, dockerymick commented on governance/grc_arch.adoc
> +- *Policy propagator controller:* Runs on the {product-title-short} hub and is responsible for generating the replicated policies in the managed cluster namespaces on the hub based on the placements
I recommend that we say initiating or starting; We avoid using language such as "trigger" for translation.
```suggestion
- *Policy propagator controller:* Runs on the {product-title-short} hub and is responsible for generating the replicated policies in the managed cluster namespaces on the hub based on the placements bound to the root policy. It also aggregates compliance status from replicated policies to the root policy status. It is also responsible for initiating automations based on policy automations bound to the root policy.
```

2024-04-10 14:23 UTC, dockerymick commented on governance/grc_arch.adoc
> +- *Governance policy addon controller:* Runs on the {product-title-short} hub and is responsible for managing the installation of policy controllers on managed clusters.
I have concerns with changing the name here because the image does not show "Governance policy addon controller". 
```suggestion
- *Spec sync controller also known as Governance policy add-on controller:* Runs on the {product-title-short} hub and is responsible for managing the installation of policy controllers on managed clusters.
```

2024-04-10 14:23 UTC, dockerymick commented on governance/grc_arch.adoc
> +- *Governance policy framework:* Runs as the `governance-policy-framework` pod on managed clusters and contains the following controllers.
Similar concern that the terms "Governance policy framework" is not labeled in the image. From my perspective, the entire image is the framework. If we move forward with updating the image in 2.11, would it make sense for the framework to have the hub cluster and managed cluster enclosed by a box titled "Governance policy framework? 

```suggestion
- *Governance policy framework:* The previous image represents the framework that runs as the `governance-policy-framework` pod on managed clusters and contains the following controllers:
```

2024-04-10 14:23 UTC, dockerymick commented on governance/grc_arch.adoc
> +** *Spec sync controller:* Responsible for synchronizing the replicated policy in the managed cluster namespace on the hub to the managed cluster namespace on the managed cluster.
```suggestion
** *Spec sync controller:* Responsible for synchronizing the replicated policy in the managed cluster namespace on the hub cluster to the managed cluster namespace on the managed cluster.
```

2024-04-10 14:23 UTC, dockerymick commented on governance/grc_arch.adoc
> +** *Status sync controller:* Responsible for recording compliance events from policy controllers in the replicated policies on the hub and managed cluster. The status only contains updates that are r
```suggestion
** *Status sync controller:* Responsible for recording compliance events from policy controllers in the replicated policies on the hub and managed cluster. The status only contains updates that are relevant to the current policy and does not consider past statuses if the policy is deleted and recreated.
```

2024-04-10 14:23 UTC, dockerymick commented on governance/grc_arch.adoc
> +** *Template sync controller:* Responsible for creating, updating, and deleting objects in the managed cluster namespace on the managed cluster based on the definitions in replicated policy `spec.pol
```suggestion
** *Template sync controller:* Responsible for creating, updating, and deleting objects in the managed cluster namespace on the managed cluster based on the definitions from the replicated policy `spec.policy-templates` entries.
```

2024-04-10 14:23 UTC, dockerymick commented on governance/grc_arch.adoc
> +- *Certificate policy controller:* Evaluates certificate policies to inform on certificates stored in `Secret` objects based on organization requirements such as expiring certificates.
Similar concerns, the controllers are not listed in the image. I recommend that we do not include them at this point.

2024-04-10 14:58 UTC, mprahl commented on governance/grc_arch.adoc
> +- *Governance policy addon controller:* Runs on the {product-title-short} hub and is responsible for managing the installation of policy controllers on managed clusters.
It's not changing the name. It just looks that way from the diff. It's actually a separate component just not showed on the image. The spec sync controller is still listed but under the "governance policy framework" section.

2024-04-10 14:59 UTC, mprahl commented on governance/grc_arch.adoc
> +- *Governance policy framework:* Runs as the `governance-policy-framework` pod on managed clusters and contains the following controllers.
It's just grouping the controllers based around the container name they see running on the managed cluster. Each controller within this grouping is listed as bullets underneath which are in the image.

2024-04-10 15:01 UTC, mprahl commented on governance/grc_arch.adoc
> +- *Certificate policy controller:* Evaluates certificate policies to inform on certificates stored in `Secret` objects based on organization requirements such as expiring certificates.
The configuration policy controller and certificate policy controller are under the "policy controllers" box in the image. If I make them bullets underneath a "Policy Controllers" bullet, would that be sufficient?

2024-04-10 15:02 UTC, mprahl commented on governance/grc_arch.adoc
> +- *Governance policy addon controller:* Runs on the {product-title-short} hub and is responsible for managing the installation of policy controllers on managed clusters.
I'm also hesitant to include this in the image since the image is already very complex. It's just part of the installation flow so it's not as critical that it's in image, however, I think it's useful for the customer to be aware that it exists and what its purpose is.

2024-04-10 23:35 UTC, dockerymick commented on governance/grc_arch.adoc
> +- *Certificate policy controller:* Evaluates certificate policies to inform on certificates stored in `Secret` objects based on organization requirements such as expiring certificates.
I agree that placing a description as part of the Policy controllers. It is not clear that those exact policy controllers are behind the term Policy controllers. I am on the side of not adding the Policy controller descriptions and add a link to the Policy controllers topic from the Additional resources section.

2024-04-11 13:15 UTC, mprahl commented
@dockerymick great suggestions! Could you please take another look?

2024-04-11 14:12 UTC, dockerymick approved these changes
I applied my suggestions and checked the links. This looks good to me, thanks Matt!

2024-04-11 14:18 UTC, mprahl commented
@dockerymick this looks good to me! Feel free to merge when ready.

2024-04-11 15:21 UTC, jc-berger approved these changes
/lgtm

2024-04-11 15:21 UTC, jc-berger commented on governance/grc_arch.adoc
> +- *Policy propagator controller:* Runs on the {product-title-short} hub and is responsible for generating the replicated policies in the managed cluster namespaces on the hub based on the placements
optional:

for consistency of verb tense, we can make both verbs active (runs and generates) & (aggregates and initiates) instead of active and passive (runs and is) & (aggregates and is)

```suggestion
- *Policy propagator controller:* Runs on the {product-title-short} hub and generates the replicated policies in the managed cluster namespaces on the hub based on the placements bound to the root policy. It also aggregates compliance status from replicated policies to the root policy status and initiates automations based on policy automations bound to the root policy.
```

2024-04-11 15:21 UTC, jc-berger commented on governance/grc_arch.adoc
> +- *Governance policy addon controller:* Runs on the {product-title-short} hub and is responsible for managing the installation of policy controllers on managed clusters.
Same as above, and likewise, optional as the original wording is good :) 

```suggestion
- *Governance policy addon controller:* Runs on the {product-title-short} hub and manages the installation of policy controllers on managed clusters.
```

2024-04-11 15:21 UTC, jc-berger commented on governance/grc_arch.adoc
> +** *Spec sync controller:* Responsible for synchronizing the replicated policy in the managed cluster namespace on the hub cluster to the managed cluster namespace on the managed cluster.
In your previous bullet list, you started each definition with the action that the technology does (runs), so for consistency, I would follow the same sentence structure here:

```suggestion
** *Spec sync controller:* Synchronizes  the replicated policy in the managed cluster namespace on the hub cluster to the managed cluster namespace on the managed cluster.
```

2024-04-11 15:21 UTC, jc-berger commented on governance/grc_arch.adoc
> +** *Status sync controller:* Responsible for recording compliance events from policy controllers in the replicated policies on the hub and managed cluster. The status only contains updates that are r
```suggestion
** *Status sync controller:* Records compliance events from policy controllers in the replicated policies on the hub and managed cluster. The status only contains updates that are relevant to the current policy and does not consider past statuses if the policy is deleted and recreated.
```

2024-04-11 15:21 UTC, jc-berger commented on governance/grc_arch.adoc
> +** *Template sync controller:* Responsible for creating, updating, and deleting objects in the managed cluster namespace on the managed cluster based on the definitions from the replicated policy `sp
```suggestion
** *Template sync controller:* Creates, updates, and deletes objects in the managed cluster namespace on the managed cluster based on the definitions from the replicated policy `spec.policy-templates` entries.
```

2024-04-11 15:21 UTC, jc-berger commented on governance/grc_arch.adoc
> +** *Gatekeeper sync controller:* Responsible for recording Gatekeeper constraint audit results as compliance events in corresponding {product-title-short} policies.
```suggestion
** *Gatekeeper sync controller:* Records Gatekeeper constraint audit results as compliance events in corresponding {product-title-short} policies.
```

2024-04-11 15:49 UTC, dockerymick commented on governance/grc_arch.adoc
> +- *Governance policy addon controller:* Runs on the {product-title-short} hub and manages the installation of policy controllers on managed clusters.
```suggestion
- *Governance policy add-on controller:* Runs on the {product-title-short} hub cluster and manages the installation of policy controllers on managed clusters.
```

2024-04-11 15:49 UTC, dockerymick commented on governance/grc_arch.adoc
> +- *Policy propagator controller:* Runs on the {product-title-short} hub and generates the replicated policies in the managed cluster namespaces on the hub based on the placements bound to the root po
```suggestion
- *Policy propagator controller:* Runs on the {product-title-short} hub cluster and generates the replicated policies in the managed cluster namespaces on the hub based on the placements bound to the root policy. It also aggregates compliance status from replicated policies to the root policy status and initiates automations based on policy automations bound to the root policy.
```

2024-04-11 15:50 UTC, dockerymick commented
@jc-berger thanks for your review and suggestions. I agree and appreciate the reminder about active tone. Thanks @mprahl for initiating the PR, and working through this together. merging this PR

2024-04-11 15:50 UTC, merged