https://issues.redhat.com/browse/ACM-10939 Subm known issue
open-cluster-management/rhacm-docs pull request #6342
Opened 2024-04-12 11:12 UTC by oafischer

2.10 and 2.9

2024-04-15 07:21 UTC, vthapar commented
/approve

2024-04-15 07:22 UTC, vthapar commented
/lgtm

2024-04-15 07:22 UTC, vthapar approved these changes

2024-04-22 17:42 UTC, dockerymick requested changes

2024-04-22 17:42 UTC, dockerymick commented on release_notes/known_issues_network.adoc
> +The Submariner add-on installation fails on VMware vSphere running an {ocp-short} 4.15 and later hub cluster because of a missing broker secret for `ManagedClusters` on the hub cluster. Only the `sub
is it a `ManagedCluster` resource?

2024-04-22 17:42 UTC, dockerymick commented on release_notes/known_issues_network.adoc
> +. Log in to the hub cluster
```suggestion
. Log in to the hub cluster.
```

2024-04-23 05:28 UTC, vthapar commented on release_notes/known_issues_network.adoc
> +The Submariner add-on installation fails on VMware vSphere running an {ocp-short} 4.15 and later hub cluster because of a missing broker secret for `ManagedClusters` on the hub cluster. Only the `sub
It is a SubmarinerAddon resource created on hub for each ManagedCluster. Not sure if it counts as `ManagedCluster` resource or SubmarinerAddon resource.

2024-04-23 15:19 UTC, dockerymick commented on release_notes/known_issues_network.adoc
> +The Submariner add-on installation fails on VMware vSphere running an {ocp-short} 4.15 and later hub cluster because of a missing broker secret for `ManagedClusters` on the hub cluster. Only the `sub
@vthapar thanks for confirming! I recommend that "ManagedCluster" not be monospaced and lower-case (managed cluster). @oafischer can you explain the intention for monospacing managed cluster that I might not be aware of?

2024-04-23 16:05 UTC, oafischer commented on release_notes/known_issues_network.adoc
> +The Submariner add-on installation fails on VMware vSphere running an {ocp-short} 4.15 and later hub cluster because of a missing broker secret for `ManagedClusters` on the hub cluster. Only the `sub
@dockerymick There is no additional reason for monospacing it. I will remove the monospace, thanks for the revire@

2024-04-24 09:46 UTC, merged