Document to backup the governance-policy-database secret
open-cluster-management/rhacm-docs pull request #6356
Opened 2024-04-16 20:05 UTC by mprahl

2024-04-16 20:05 UTC, mprahl commented
@dockerymick this was something I overlooked in the initial rough draft.

2024-04-30 13:45 UTC, dockerymick commented
@mprahl excuse the delay on my review. I missed this PR. Here is the link to the related issue: https://issues.redhat.com/browse/ACM-10052

Approving this PR and will add it to 2.11

2024-04-30 13:50 UTC, dockerymick requested changes

2024-04-30 13:50 UTC, dockerymick commented on governance/compliance_history.adoc
>  <1> The `ca` data field must specify the Certificate Authority certificate file that is used to sign the TLS certificate used by PostgreSQL. If you do not provide this value, you must change the _ssl
```suggestion
<1> You must specify the Certificate Authority certificate file in the `ca` data field, which is used to sign the TLS certificate of the PostgreSQL. If you do not provide this value, you must change the _sslmode_ value accordingly, though it is not recommended since it reduces the security of the database connection.
```

2024-04-30 13:50 UTC, dockerymick commented on governance/compliance_history.adoc
> +<2> The `cluster.open-cluster-management.io/backup` label is to backup the `Secret` resource for a {product-title-short} hub cluster restore operation.
```suggestion
<2> Use the `cluster.open-cluster-management.io/backup` label to backup the `Secret` resource for a {product-title-short} hub cluster restore operation.
```

2024-04-30 13:58 UTC, oafischer commented on governance/compliance_history.adoc
> +. Create the `governance-policy-database` `Secret` resource in the namespace where {product-title-short} is installed. This is the `open-cluster-management` namespace by default and the example comma
A little long for a step, I wonder if we can break this up somehow

2024-04-30 14:31 UTC, mprahl commented on governance/compliance_history.adoc
>  <1> The `ca` data field must specify the Certificate Authority certificate file that is used to sign the TLS certificate used by PostgreSQL. If you do not provide this value, you must change the _ssl
@dockerymick this text wasn't changed in this PR so as a rule of thumb, that should be a separate PR to not block this update. If you'd like to change this though, I like your suggestion.

2024-04-30 14:38 UTC, dockerymick requested changes
@oafischer @mprahl thoughts?

2024-04-30 14:38 UTC, dockerymick commented on governance/compliance_history.adoc
> +. Create the `governance-policy-database` `Secret` resource in the namespace where {product-title-short} is installed. This is the `open-cluster-management` namespace by default and the example comma
I agree, I can imagine adding more sample references

[source,bash]
----
oc -n open-cluster-management create secret generic governance-policy-database \ <1>
    --from-literal="user=rhacm-policy-compliance-history" \
    --from-literal="password=rhacm-policy-compliance-history" \
    --from-literal="host=<replace with host name of the Postgres server>" \ <2>
    --from-literal="dbname=ocm-compliance-history" \
  --from-literal="sslmode=verify-full" \
    --from-file="ca=<replace>" <3>
oc -n open-cluster-management label secret governance-policy-database cluster.open-cluster-management.io/backup="" <4>
----
+
<1> Add the namespace where {product-title-short} is installed. By default, the `Secret` resource is installed in the `open-cluster-management` namespace.
<2> Add the host name of the PostgresQL server. If you deployed the PostgreSQL server on the {product-title-short} hub cluster and it is not exposed outside of the cluster, you can use the `Service` object for the host value. The format is `<service name>.<namespace>.svc`.
<3> You must specify the Certificate Authority certificate file in the `ca` data field, which is used to sign the TLS certificate of the PostgreSQL. If you do not provide this value, you must change the _sslmode_ value accordingly, though it is not recommended since it reduces the security of the database connection.
<4> Use the `cluster.open-cluster-management.io/backup` label to backup the `Secret` resource for a {product-title-short} hub cluster restore operation.

2024-04-30 14:38 UTC, dockerymick commented on governance/compliance_history.adoc
> +. Create the `governance-policy-database` `Secret` resource in the namespace where {product-title-short} is installed. This is the `open-cluster-management` namespace by default and the example comma
Excuse the formatting, but i am using the same .adoc syntax
<img width="776" alt="Screenshot 2024-04-30 at 10 35 34 AM" src="https://github.com/stolostron/rhacm-docs/assets/60616885/a77c1398-bf61-42b7-8ef2-3a75b9183db4">

2024-04-30 14:38 UTC, dockerymick commented on governance/compliance_history.adoc
> +. Create the `governance-policy-database` `Secret` resource in the namespace where {product-title-short} is installed. This is the `open-cluster-management` namespace by default and the example comma
In addition to my previous suggestion ^
```suggestion
. Create the `governance-policy-database` `Secret` resource to use this database for the policy compliance history API. Note, this approach depends on the network policies of the {product-title-short} hub cluster. Run the following commands:
``` hub cluster. Run the following commands:
```

2024-04-30 14:49 UTC, oafischer commented on governance/compliance_history.adoc
> +. Create the `governance-policy-database` `Secret` resource in the namespace where {product-title-short} is installed. This is the `open-cluster-management` namespace by default and the example comma
Are we able to use the call-outs in commands? I think it's a good idea to keep the additional explanations out of the step itself.

2024-04-30 15:04 UTC, dockerymick commented on governance/compliance_history.adoc
> +. Create the `governance-policy-database` `Secret` resource in the namespace where {product-title-short} is installed. This is the `open-cluster-management` namespace by default and the example comma
Resolving this. I made updates

2024-04-30 15:04 UTC, dockerymick commented on governance/compliance_history.adoc
> +. Create the `governance-policy-database` `Secret` resource in the namespace where {product-title-short} is installed. This is the `open-cluster-management` namespace by default and the example comma
Applied this change

2024-04-30 15:05 UTC, dockerymick commented on governance/compliance_history.adoc
> +. Create the `governance-policy-database` `Secret` resource in the namespace where {product-title-short} is installed. This is the `open-cluster-management` namespace by default and the example comma
Made updates, resolving this

2024-04-30 15:05 UTC, dockerymick approved these changes

2024-04-30 15:06 UTC, oafischer approved these changes

2024-04-30 15:07 UTC, dockerymick commented on governance/compliance_history.adoc
> +oc -n open-cluster-management label secret governance-policy-database cluster.open-cluster-management.io/backup="" <4>
This seems like another command. Will the user copy this entire thing or do they need to run commands separately?

2024-04-30 15:08 UTC, mprahl commented on governance/compliance_history.adoc
> +oc -n open-cluster-management label secret governance-policy-database cluster.open-cluster-management.io/backup="" <4>
Both approaches work fine.

2024-04-30 15:10 UTC, mprahl commented on governance/compliance_history.adoc
> +. Create the `governance-policy-database` `Secret` resource to use this database for the policy compliance history API. Note, this approach depends on the network policies of the {product-title-short
The sentence with `Note...` must be kept with the `If the PostgreSQL server ...` sentence. The current PR puts this sentence out of context.

2024-04-30 15:11 UTC, mprahl commented on governance/compliance_history.adoc
> +<1> Add the namespace where {product-title-short} is installed. By default, the `Secret` resource is installed in the `open-cluster-management` namespace.
```suggestion
<1> Add the namespace where {product-title-short} is installed. By default, {product-title-short} is installed in the `open-cluster-management` namespace.
```

2024-04-30 15:12 UTC, mprahl commented on governance/compliance_history.adoc
> +<2> Add the host name of the PostgresQL server. If you deployed the PostgreSQL server on the {product-title-short} hub cluster and it is not exposed outside of the cluster, you can use the `Service`
```suggestion
<2> Add the host name of the PostgresQL server. If you deployed the PostgreSQL server on the {product-title-short} hub cluster and it is not exposed outside of the cluster, you can use the `Service` object for the host value. The format is `<service name>.<namespace>.svc`. Note, this approach depends on the network policies of the {product-title-short} hub cluster.
```

2024-04-30 15:12 UTC, mprahl commented on governance/compliance_history.adoc
> +. Create the `governance-policy-database` `Secret` resource to use this database for the policy compliance history API. Note, this approach depends on the network policies of the {product-title-short
```suggestion
. Create the `governance-policy-database` `Secret` resource to use this database for the policy compliance history API. Run the following commands:
```

2024-04-30 15:12 UTC, mprahl commented on governance/compliance_history.adoc
> +<3> You must specify the Certificate Authority certificate file in the `ca` data field, which is used to sign the TLS certificate of the PostgreSQL. If you do not provide this value, you must change
```suggestion
<3> You must specify the Certificate Authority certificate file in the `ca` data field, which is used to sign the TLS certificate of the PostgreSQL server. If you do not provide this value, you must change the _sslmode_ value accordingly, though it is not recommended since it reduces the security of the database connection.
```

2024-04-30 15:26 UTC, dockerymick commented on governance/compliance_history.adoc
> +. Create the `governance-policy-database` `Secret` resource to use this database for the policy compliance history API. Run the following commands:
```suggestion
. Create the `governance-policy-database` `Secret` resource to use this database for the policy compliance history API. Run the following command:
```

2024-04-30 15:28 UTC, dockerymick commented
@mprahl thanks for confirming about the commands. I decided to pull the second command out.

2024-04-30 17:57 UTC, mprahl commented on governance/compliance_history.adoc
> +<3> You must specify the Certificate Authority certificate file in the `ca` data field, which is used to sign the TLS certificate of the PostgreSQL server. If you do not provide this value, you must
```suggestion
<3> You must specify the Certificate Authority certificate file in the `ca` data field that signed the TLS certificate of the PostgreSQL server. If you do not provide this value, you must change the _sslmode_ value accordingly, though it is not recommended since it reduces the security of the database connection.
```

2024-05-01 13:51 UTC, dockerymick commented
@mprahl thanks for your suggestion. I accepted your suggestion. With approvals from myself and Oliver, I am comfortable with merging this PR

2024-05-01 13:52 UTC, merged

2024-05-01 13:52 UTC, dockerymick commented
Also making the update for 2.11