ACM#11233: Part 2: Simplify user-replaced values and commands
open-cluster-management/rhacm-docs pull request #6359
Opened 2024-04-20 11:58 UTC by xenolinux

https://issues.redhat.com/browse/ACM-11233

2024-04-22 12:45 UTC, jparrill requested changes
Dropped some comments

2024-04-22 12:45 UTC, jparrill commented on clusters/hosted_control_planes/disable_hosted.adoc
> +<1> The default `MultiClusterEngine` resource instance name is `multiclusterengine`. You can get the `MultiClusterEngine` instance name from your hosting cluster by running the `$ oc get mce` command
Could you please change `hosting` by `hosted`?

2024-04-22 12:45 UTC, jparrill commented on clusters/hosted_control_planes/disable_hosted.adoc
> +<1> The default `MultiClusterEngine` resource instance name is `multiclusterengine`. You can get the `MultiClusterEngine` name from your hosting cluster by running the `$ oc get mce` command.
Could you please change `hosting` by `hosted`?

2024-04-22 12:45 UTC, jparrill commented on clusters/hosted_control_planes/disconnected_intro.adoc
> +* Key: `<registry-dns-domain-name>..<port>`
Could you please remark emphasis on the ".." (the two dots after the registry name) in order to let the customer know that is replacing the ":"?

2024-04-22 14:18 UTC, jparrill approved these changes
/lgtm

2024-05-06 21:21 UTC, swopebe approved these changes
This looks great, obviously it was much needed.

2024-05-07 04:07 UTC, merged