Fix the operator policy documentation
open-cluster-management/rhacm-docs pull request #6371
Opened 2024-04-26 14:05 UTC by mprahl

The instructions were incorrect on how to install an operator using OperatorPolicy since we never recommend deploying a policy template directly. We must always use a Policy object to deliver it.

After correcting this, the documentation was pretty much the same as the policy_operator.adoc file, so I decided to remove it.

This also fixes a syntax error in the "Operator policy YAML table" to allow a list to be rendered correctly in the spec.subscription table cell.

2024-04-26 15:44 UTC, dockerymick commented on governance/policy_operator.adoc
> +            sourceNamespace: openshift-marketplace
@mprahl I recall you stated how the sample was exactly the same, and that if we want to keep the install_operator.adoc file as the task file, you recommend to remove the sample from the policy_operator.adoc file. Instead of removing the entire sample, I recommend that the sample be empty. We do that throughout the Governance doc and then link them to the samples. This way, we can keep the concept and task separate. Thoughts?

2024-04-26 17:17 UTC, mprahl commented on governance/policy_operator.adoc
> +            sourceNamespace: openshift-marketplace
I think this is now covered in my latest update.

I still think the what's new bullet that I removed is duplicate information, so I'd prefer if that was remained deleted.

2024-04-26 17:58 UTC, JustinKuli approved these changes
lgtm

2024-04-29 17:57 UTC, dockerymick requested changes

2024-04-29 17:57 UTC, dockerymick commented on governance/install_operator.adoc
> +After the Governance Policy Framework applies the `OperatorPolicy` policy template, the controller creates the `operatorGroup` and `subscription` objects on the cluster. This prompts OLM to handle th
Removing Anthropomorphism
```suggestion
After you add the `OperatorPolicy` policy template, the operatorGroup` and `subscription` objects are created on the cluster by using the controller. This prompts the OLM to complete the rest of the installation process. You can view the health of owned resources in the `.status.Conditions` and `.status.relatedObjects` fields of the `OperatorPolicy` resource on the managed cluster.
```

2024-04-29 17:57 UTC, dockerymick commented on governance/policy_operator.adoc
> +The operator policy controller allows you to monitor and install Operator Lifecycle Manager (OLM) operators across your clusters. Use the operator policy controller to monitor the health of various p
It is best to use lower-case based on the IBM style guide to use sentence style capitalization, https://www.ibm.com/docs/en/ibm-style?topic=grammar-capitalization

However, I can understand capitalizing the component name (Governance framework)

```suggestion
The operator policy controller allows you to monitor and install Operator Lifecycle Manager (OLM) operators across your clusters. Use the operator policy controller to monitor the health of various pieces of the operator and to specify how you want to automatically handle updates to the operator. You can also distribute an operator policy to managed clusters by using the governance framework and adding the policy to the `policy-templates` field of a policy on the hub cluster.
```

2024-04-29 18:59 UTC, jc-berger approved these changes
/lgtm

2024-04-30 14:26 UTC, mprahl commented on governance/install_operator.adoc
> +After you add the `OperatorPolicy` policy template, the operatorGroup` and `subscription` objects are created on the cluster by using the controller. This prompts the OLM to complete the rest of the
```suggestion
After you add the `OperatorPolicy` policy template, the `operatorGroup` and `subscription` objects are created on the cluster by using the controller. This prompts the OLM to complete the rest of the installation process. You can view the health of owned resources in the `.status.Conditions` and `.status.relatedObjects` fields of the `OperatorPolicy` resource on the managed cluster.
```

2024-04-30 14:28 UTC, mprahl commented on governance/install_operator.adoc
> +After you add the `OperatorPolicy` policy template, the `operatorGroup` and `subscription` objects are created on the cluster by using the controller. This prompts the OLM to complete the rest of the
```suggestion
After you add the `OperatorPolicy` policy template, the `operatorGroup` and `subscription` objects are created on the cluster by using the controller. This prompts OLM to complete the rest of the installation process. You can view the health of owned resources in the `.status.Conditions` and `.status.relatedObjects` fields of the `OperatorPolicy` resource on the managed cluster.
```

2024-05-01 13:45 UTC, dockerymick commented on governance/install_operator.adoc
> +After you add the `OperatorPolicy` policy template, the `operatorGroup` and `subscription` objects are created on the cluster by using the controller. This prompts the OLM to complete the rest of the
Updating to remove anthropomorphism. https://www.ibm.com/docs/en/ibm-style?topic=grammar-anthropomorphism

Does OLM complete the installation automatically or is the user prompted from the OLM tool to complete the installation? 
```suggestion
After you add the `OperatorPolicy` policy template, the `operatorGroup` and `subscription` objects are created on the cluster by using the controller. As a result, the rest of the installation is complete by OLM. You can view the health of owned resources in the `.status.Conditions` and `.status.relatedObjects` fields of the `OperatorPolicy` resource on the managed cluster.
```

2024-05-01 13:48 UTC, mprahl commented on governance/install_operator.adoc
> +After you add the `OperatorPolicy` policy template, the `operatorGroup` and `subscription` objects are created on the cluster by using the controller. This prompts the OLM to complete the rest of the
Could you please change `complete` to `completed`?

OLM automatically handles the installation.

2024-05-01 14:32 UTC, mprahl commented
@dockerymick this looks good to me!

2024-05-01 15:39 UTC, dockerymick commented on governance/policy_operator.adoc
> +* See the link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.15/html-single/operators/index#olm-adding-operators-to-a-cluster[Adding Operators to a cluster] documentati
"If we need to point to the OCP documentation, know that we document the lowest OCP version that was tested with ACM/MCE and is in full support. That means the 2.10 version of the doc will point to the 4.13 version of OCP doc, unless a component is new or was not tested on that version." : https://docs.google.com/document/d/1YTqpZRH54Bnn4WJ2nZmjaCoiRtqmrc2w6DdQxe_yLZ8/edit#heading=h.9fvyr2rdriby 

```suggestion
* See the link:https://docs.openshift.com/container-platform/4.13/operators/understanding/olm/olm-understanding-olm.html#olm-subscription_olm-understanding-olm[Subscription] topic in the {ocp-short} documentation.

* See the link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.13/html-single/operators/index#olm-adding-operators-to-a-cluster[Adding Operators to a cluster] documentation for general information on OLM.
```

2024-05-01 16:21 UTC, dockerymick approved these changes
Updated a link and will make changes for 2.11. Approving and merging this PR

2024-05-01 16:21 UTC, merged