https://issues.redhat.com/browse/ACM-10994 Add control plane node topic
open-cluster-management/rhacm-docs pull request #6377
Opened 2024-04-30 14:54 UTC by oafischer

2024-05-02 15:35 UTC, dockerymick requested changes

2024-05-02 15:35 UTC, dockerymick commented on clusters/cluster_lifecycle/scale_managed_intro.adoc
> +* xref:../cluster_lifecycle/scale_nodes_ctrl_plane.adoc#adding-ctrl-nodes-managed[Adding control plane nodes to managed clusters]
Broken links 
<img width="1063" alt="Screenshot 2024-05-02 at 11 29 03 AM" src="https://github.com/stolostron/rhacm-docs/assets/60616885/82164fd1-dcb6-4221-ac5a-4dfefa05deda">

2024-05-02 15:35 UTC, dockerymick commented on clusters/cluster_lifecycle/scale_node_ctrl_plane.adoc
> +----
```suggestion
. Set the agent to `master` before you approve the agent by running the following command:

+
[source,bash]
----
oc patch agent <AGENT-NAME> -p '{"spec":{"role": "master"}}' --type=merge
----
```

2024-05-02 15:35 UTC, dockerymick commented on clusters/cluster_lifecycle/scale_node_ctrl_plane.adoc
> +
I recommend adding a verification step. Can the user simply run a command to verify ? Will the user see a list of healthy managed clusters?

2024-05-02 15:35 UTC, dockerymick commented on clusters/cluster_lifecycle/scale_node_ctrl_plane.adoc
> +----
```suggestion
. Set the agent to `master` before you approve the agent by running the following command:

+
[source,bash]
----
oc patch agent <AGENT-NAME> -p '{"spec":{"role": "master"}}' --type=merge
----
```

2024-05-02 15:35 UTC, dockerymick commented on clusters/cluster_lifecycle/scale_node_ctrl_plane.adoc
> +
Similar suggestion, add a verification step

2024-05-02 16:25 UTC, oafischer commented on clusters/cluster_lifecycle/scale_node_ctrl_plane.adoc
> +
The verification is already in the linked steps, I think it would be better not to duplicate it.

2024-05-02 17:55 UTC, dockerymick commented on clusters/cluster_lifecycle/scale_node_ctrl_plane.adoc
> +. Follow the steps in link:https://access.redhat.com/documentation/en-us/assisted_installer_for_openshift_container_platform/2024/html/installing_openshift_container_platform_with_the_assisted_instal
A couple of more broken links:
<img width="1704" alt="Screenshot 2024-05-02 at 1 55 20 PM" src="https://github.com/stolostron/rhacm-docs/assets/60616885/61acf192-1ee6-466a-911e-cbdb9af2f40b">

2024-05-06 13:32 UTC, chadcrum commented
cc @carbonin

2024-05-06 13:55 UTC, oafischer commented
Links should be fixed @dockerymick

2024-05-06 14:14 UTC, dockerymick approved these changes
Looks good !

2024-05-06 14:36 UTC, chadcrum commented
/lgtm

2024-05-07 14:59 UTC, merged