added workaround steps
open-cluster-management/rhacm-docs pull request #6379
Opened 2024-04-30 18:02 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-11383

2024-04-30 20:16 UTC, xiangjingli commented on release_notes/known_issues_application.adoc
> +When you create a service account in {ocp} 4.15 provisioned by IBM VMware, the account does not automatically create a secret. Therefore, the {product-title-short} `gitopsCluster` controller fails to
When you create a service account in {ocp} 4.15 provisioned by **some cloud providers such as IBM VMware, Bare Metal**, the account does not automatically create a secret. Therefore, the {product-title-short} `gitopsCluster` controller fails to generate the managed cluster secret for the Argo CD push model. {ocp} 4.14 provisioned by IBM VMware and {ocp} 4.15 with **other providers such as AWS**, do not observe this issue.  This issue is delivered in {product-title-short} 2.10.3 and in {product-title-short} 2.9.4.

2024-04-30 20:17 UTC, xiangjingli reviewed
The rest looks good

2024-05-01 17:06 UTC, swopebe requested changes
See comments please.

2024-05-01 17:06 UTC, swopebe commented on release_notes/known_issues_application.adoc
> +. Go to your managed cluster.
We usually say "log in to your managed cluster" and sometimes even have a command here, please change step 1.

2024-05-01 17:06 UTC, swopebe commented on release_notes/known_issues_application.adoc
> +. Retrieve the token from your created secret, by running the following command:
Remove this comma.

2024-05-01 17:06 UTC, swopebe commented on release_notes/known_issues_application.adoc
> +----
You are using source, yaml for something that is not YAML. YAML is a file that users have to create often while using the product. This is a command, we just spoke about this in our team meeting, if you remember. I am not sure why YAML is used here? 
Bash, terminal, or shell I would understand, but what are we asking the user to do here?

2024-05-01 19:53 UTC, swopebe reviewed
It seems I somehow lost two of my early comments. :-/ Sorry.

2024-05-01 19:53 UTC, swopebe commented on release_notes/known_issues_application.adoc
> +When you create a service account in {ocp} 4.15 provisioned by some cloud providers, such as IBM VMware and Bare Metal, then the account does not automatically create a secret. Therefore, the {produc
I had a comment here but it disappeared. This has to be broken up a bit, and we need relative pronouns--always. And please change this: provisioned by the cloud provider, AWS. We have to write as concise as possible, you will almost always need to rewrite these lines when you get them: `provisioned by AWS` or `provisioned by the AWS cloud provider.` This is standard for concise writing, I will drop resources in another comment.

2024-05-01 19:53 UTC, swopebe commented on release_notes/known_issues_application.adoc
> +When you create a service account in {ocp} 4.15 provisioned by some cloud providers, such as IBM VMware and Bare Metal, then the account does not automatically create a secret. Therefore, the {produc
https://www.ibm.com/docs/en/ibm-style?topic=grammar-pronouns#relative-pronouns

2024-05-02 15:49 UTC, merged

2024-05-02 18:52 UTC, swopebe commented on release_notes/known_issues_application.adoc
> +When you create a service account in {ocp} 4.15 provisioned by some cloud providers, such as IBM VMware and Bare Metal, then the account does not automatically create a secret. Therefore, the {produc
It looks like maybe it was merged before that fix, so probably too late now but this is the grammar/style manual piece of our writing standards.
_Use that, without a comma, to introduce a restrictive clause. A restrictive clause is essential to the meaning of the sentence. If the restrictive clause is removed, the meaning of the sentence changes._
This can be viewed as OCP 4.15 provisioned
We need to write:
**{ocp} 4.15 that is provisioned**