[ACM-2.11] ACM#10464: Extracting OpenShift release image digest
open-cluster-management/rhacm-docs pull request #6392
Opened 2024-05-03 09:43 UTC by xenolinux

https://issues.redhat.com/browse/ACM-10464

2024-05-03 23:34 UTC, CrystalChun commented on clusters/hosted_control_planes/create_cluster_bm.adoc
> +Replace `<hosted_cluster_namespace>` with your hosted cluster namespace name, for example, `clusters`. Replace `<hosted-cluster-name>` with your hosted cluster name.
```suggestion
Replace `<hosted_cluster_namespace>` with your hosted cluster namespace name, for example, `clusters`. Replace `<hosted_cluster_name>` with your hosted cluster name.
```
I'd guess you'd want this variable with underscores too?

2024-05-04 10:19 UTC, xenolinux commented on clusters/hosted_control_planes/create_cluster_bm.adoc
> +Replace `<hosted_cluster_namespace>` with your hosted cluster namespace name, for example, `clusters`. Replace `<hosted-cluster-name>` with your hosted cluster name.
Yes correct

2024-05-06 13:28 UTC, CrystalChun commented
/lgtm

2024-05-06 13:32 UTC, CrystalChun approved these changes

2024-05-06 16:32 UTC, dockerymick requested changes

2024-05-06 16:32 UTC, dockerymick commented on clusters/hosted_control_planes/create_cluster_bm.adoc
>  ----
```suggestion
[source,bash]
----
```

2024-05-06 16:32 UTC, dockerymick commented on clusters/hosted_control_planes/create_cluster_bm.adoc
>  hcp create cluster agent \
https://github.com/stolostron/rhacm-docs/pull/6394#discussion_r1591192196

2024-05-06 16:32 UTC, dockerymick commented on clusters/hosted_control_planes/disconnected_intro.adoc
>  . You configure infrastructure services, including the registry certificate deployment with TLS support, web server, and DNS, to ensure that the disconnected deployment works.
```suggestion
. Configure infrastructure services, including the registry certificate deployment with TLS support, web server, and DNS, to ensure that the disconnected deployment works.
```

2024-05-06 16:32 UTC, dockerymick commented on clusters/hosted_control_planes/disconnected_intro.adoc
> +. You create a config map in the `openshift-config` namespace. In this example, the config map is named `registry-config`. The content of the config map is the Registry CA certificate. The data field
```suggestion
. Create a config map in the `openshift-config` namespace. In this example, the config map is named `registry-config`. The content of the config map is the Registry CA certificate. The data field of the config map must contain the following key/value:
```

2024-05-06 16:45 UTC, xenolinux commented on clusters/hosted_control_planes/create_cluster_bm.adoc
>  hcp create cluster agent \
This is a continuous one command. Added [source,bash] for this command too.

2024-05-06 17:15 UTC, dockerymick approved these changes
Thanks for the updates. This looks good to me!

2024-05-06 17:17 UTC, dockerymick commented on clusters/hosted_control_planes/create_cluster_bm.adoc
>  . Verify that you have a default storage class configured for your cluster. Otherwise, you might see pending PVCs. See the following example:
Can you change this to read, "Run the following command."

2024-05-06 17:20 UTC, xenolinux commented on clusters/hosted_control_planes/create_cluster_bm.adoc
>  . Verify that you have a default storage class configured for your cluster. Otherwise, you might see pending PVCs. See the following example:
Fixed

2024-05-06 17:21 UTC, dockerymick approved these changes

2024-05-06 17:24 UTC, xenolinux commented on clusters/hosted_control_planes/create_cluster_bm.adoc
>  . Verify that you have a default storage class configured for your cluster. Otherwise, you might see pending PVCs. See the following example:
Updated PRs with this change for all versions - 2.9, 2.10, and 2.11

2024-05-06 17:25 UTC, merged