[ACM-2.10] ACM#10464: Extracting OpenShift release image digest
open-cluster-management/rhacm-docs pull request #6393
Opened 2024-05-03 09:48 UTC by xenolinux

https://issues.redhat.com/browse/ACM-10464

2024-05-03 23:35 UTC, CrystalChun commented on clusters/hosted_control_planes/create_cluster_bm.adoc
> +Replace `<hosted_cluster_namespace>` with your hosted cluster namespace name, for example, `clusters`. Replace `<hosted-cluster-name>` with your hosted cluster name.
```suggestion
Replace `<hosted_cluster_namespace>` with your hosted cluster namespace name, for example, `clusters`. Replace `<hosted_cluster_name>` with your hosted cluster name.
```

2024-05-06 13:29 UTC, CrystalChun approved these changes
/lgtm

2024-05-06 15:56 UTC, dockerymick requested changes

2024-05-06 15:56 UTC, dockerymick commented on clusters/hosted_control_planes/create_cluster_bm.adoc
>  ----
```suggestion
[source,bash]
----
```

2024-05-06 15:56 UTC, dockerymick commented on clusters/hosted_control_planes/create_cluster_bm.adoc
>  ----
similar question from my other review

2024-05-06 15:56 UTC, dockerymick commented on clusters/hosted_control_planes/create_cluster_bm.adoc
>  ----
```suggestion
[source,bash]
----
```

2024-05-06 16:57 UTC, xenolinux commented on clusters/hosted_control_planes/create_cluster_bm.adoc
>  ----
This is a continuous one command. Added [source,bash] for this command too.

2024-05-06 17:30 UTC, merged