[ACM-2.9] ACM#10464: Extracting OpenShift release image digest
open-cluster-management/rhacm-docs pull request #6394
Opened 2024-05-03 09:53 UTC by xenolinux

https://issues.redhat.com/browse/ACM-10464

2024-05-03 23:36 UTC, CrystalChun commented on clusters/hosted_control_planes/create_cluster_bm.adoc
> +Replace `<hosted_cluster_namespace>` with your hosted cluster namespace name, for example, `clusters`. Replace `<hosted-cluster-name>` with your hosted cluster name.
```suggestion
Replace `<hosted_cluster_namespace>` with your hosted cluster namespace name, for example, `clusters`. Replace `<hosted_cluster_name>` with your hosted cluster name.
```

2024-05-06 13:31 UTC, CrystalChun approved these changes
/lgtm

2024-05-06 15:54 UTC, dockerymick requested changes

2024-05-06 15:54 UTC, dockerymick commented on clusters/hosted_control_planes/create_cluster_bm.adoc
>  ----
```suggestion
[source,bash]
----
```

2024-05-06 15:54 UTC, dockerymick commented on clusters/hosted_control_planes/create_cluster_bm.adoc
>  hcp create cluster agent \
Is the user expected to run this command in order to receive the configuration details? Or is this one command?

2024-05-06 15:54 UTC, dockerymick commented on clusters/hosted_control_planes/create_cluster_bm.adoc
>  ----
```suggestion
[source,bash]
----
```

2024-05-06 15:54 UTC, dockerymick commented on clusters/hosted_control_planes/disconnected_intro.adoc
> +. Add the `additionalTrustedCA` field with a value of `name: registry-config` in the `images.config.openshift.io` custom resource (CR).
Earlier i recall that the team agreed to not use the abbreviation for custom resource. I also remember the conversation coming up again in a meeting. Let's bring it up to the team to confirm. 
```suggestion
. Add the `additionalTrustedCA` field with a value of `name: registry-config` in the `images.config.openshift.io` custom resource.
```

2024-05-06 15:54 UTC, dockerymick commented on clusters/hosted_control_planes/disconnected_intro.adoc
> +** `HostedCluster`: The `HostedCluster` resource defines the configuration for your hosted cluster.
```suggestion
** `HostedCluster` resource: The `HostedCluster` resource defines the configuration for your hosted cluster.
```

2024-05-06 15:54 UTC, dockerymick commented on clusters/hosted_control_planes/disconnected_intro.adoc
>  ** `NodePool`: The `NodePool` resource identifies the node pool that references the machines to use for the data plane.
```suggestion
** `NodePool` resource: The `NodePool` resource identifies the node pool that references the machines to use for the data plane.
```

2024-05-06 15:54 UTC, dockerymick commented on clusters/hosted_control_planes/disconnected_intro.adoc
> +. The Metal3 Operator tries to connect and start the BMCs by using the `LiveISO` and `RootFS` values. You can specify the `LiveISO` and `RootFS` values through the `AgentServiceConfig` CR in the {mce
https://www.ibm.com/docs/en/ibm-style?topic=grammar-anthropomorphism
```suggestion
. Specify the `LiveISO` and `RootFS` values through the `AgentServiceConfig` CR in the {mce-short} namespace  to connect and start the BMCs with the Metal3 Operator.
```

2024-05-06 15:54 UTC, dockerymick commented on clusters/hosted_control_planes/disconnected_intro.adoc
> +. The Metal3 Operator in the `openshift-machine-api` namespace inspects the new bare metal hosts.
This seems like it should not be a step from my perspective. What is the task that should be complete by the user

2024-05-06 15:54 UTC, dockerymick commented on clusters/hosted_control_planes/disconnected_intro.adoc
> +. After the worker nodes of the `HostedCluster` resource are ready, an Agent container starts running.
```suggestion
. After the worker nodes of the `HostedCluster` resource are ready, the Agent container automatically start.
```

2024-05-06 16:50 UTC, xenolinux commented on clusters/hosted_control_planes/disconnected_intro.adoc
> +. The Metal3 Operator in the `openshift-machine-api` namespace inspects the new bare metal hosts.
Agree. Removed as a step

2024-05-06 16:55 UTC, xenolinux commented on clusters/hosted_control_planes/create_cluster_bm.adoc
>  hcp create cluster agent \
This is a continuous one command. Added [source,bash] for this command too.

2024-05-06 17:30 UTC, xenolinux commented
Mistakenly closed the PR.

2024-05-06 17:30 UTC, merged