Configure Metallb artifacts on a guest cluster for BM and non BM
open-cluster-management/rhacm-docs pull request #6409
Opened 2024-05-06 14:56 UTC by xenolinux

https://issues.redhat.com/browse/ACM-11730

2024-05-17 18:21 UTC, xenolinux commented
@jparrill Can you PTAL into this?

2024-05-20 11:54 UTC, jparrill requested changes

2024-05-20 11:54 UTC, jparrill commented on clusters/hosted_control_planes/handle_ingress_bm.adoc
> +. Set up MetalLB. After creating a service of the `LoadBalancer` type, MetalLB adds an external IP address for the service.
Could we use a sample here to guide the customers in a better way?

- sample:

```yaml
---
kind: Service
apiVersion: v1
metadata:
  annotations:
    metallb.universe.tf/address-pool: ipv6-virtual-network
  name: metallb-ingress
  namespace: openshift-ingress
spec:
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  selector:
    ingresscontroller.operator.openshift.io/deployment-ingresscontroller: default
  type: LoadBalancer
```

2024-05-20 12:18 UTC, jparrill commented
/lgtm

2024-05-20 13:16 UTC, xenolinux commented on clusters/hosted_control_planes/handle_ingress_bm.adoc
> +. Set up MetalLB. After creating a service of the `LoadBalancer` type, MetalLB adds an external IP address for the service.
Addressed per the slack discussion. Thank you for the review :)

2024-05-20 17:58 UTC, dockerymick requested changes

2024-05-20 17:58 UTC, dockerymick commented on clusters/hosted_control_planes/config_metallb_bm.adoc
> +*Note:* Perform the following steps on your guest cluster.
I would not make this a note. I expect to prompt the user for the steps
```suggestion
Perform the following steps to configure MetalLB on your guest cluster:
```

2024-05-20 17:58 UTC, dockerymick commented on clusters/hosted_control_planes/config_metallb_bm.adoc
>  +
reminder to add the type of source the example is. For example, `[source,yaml]`

2024-05-20 17:58 UTC, dockerymick commented on clusters/hosted_control_planes/handle_ingress_bm.adoc
> +To set up a load balancer and wildcard DNS record for the `*.apps` domain, you need to perform the following actions:
```suggestion
To set up a load balancer and wildcard DNS record for the `*.apps` domain, you need to perform the following actions on your guest cluster:
```

2024-05-20 17:58 UTC, dockerymick commented on clusters/hosted_control_planes/handle_ingress_bm.adoc
> +. Create a YAML file that contains the configuration for the MetalLB Operator:
```suggestion
. Deploy MetalLB by creating a YAML file that contains the configuration for the MetalLB Operator:
```

2024-05-20 17:58 UTC, dockerymick commented on clusters/hosted_control_planes/handle_ingress_bm.adoc
> +.. To set up the load balancer service that routes ingress traffic to the ingress deployment, create a YAML file named `metallb-loadbalancer-service.yaml`:
Configuring a new load balancer service that routes to the ingress deployment
```suggestion
.. Configure a new load balancer service that routes ingress traffic to the ingress deployment by creating a YAML file named `metallb-loadbalancer-service.yaml`:
```

2024-05-20 17:58 UTC, dockerymick commented on clusters/hosted_control_planes/handle_ingress_bm.adoc
> +* Assigning a wildcard DNS entry to the load balancer IP address.
I recommend that you remove the bullet points and incorporate them in the tasks

2024-05-20 18:44 UTC, xenolinux commented on clusters/hosted_control_planes/handle_ingress_bm.adoc
> +* Assigning a wildcard DNS entry to the load balancer IP address.
I think this can all go away. In the next steps, this is anyway mentioned.

2024-05-21 10:12 UTC, oafischer commented on clusters/hosted_control_planes/handle_ingress_bm.adoc
>  ----
Add source block here

2024-05-21 10:12 UTC, oafischer commented on clusters/hosted_control_planes/handle_ingress_bm.adoc
> +<1> Specifies the `IPAddressPool` resource name.
If the user is expected to add their own values here, then let's rephrase these as prompts (Specify... or Replace...)

2024-05-21 10:13 UTC, oafischer commented on clusters/hosted_control_planes/handle_ingress_bm.adoc
>  ----
Add source block here

2024-05-21 10:14 UTC, oafischer commented on clusters/hosted_control_planes/ingress_non_bm.adoc
> +<1> Specifies the `IPAddressPool` resource name.
Same comment as before about prompts

2024-05-21 10:14 UTC, oafischer approved these changes
Couple of comments, I'll approve for now so I don't need to see this again.

2024-05-21 10:41 UTC, xenolinux commented
Addressed all of the suggestions. Merging this PR.

2024-05-21 10:41 UTC, merged