added workaround section for troubleshooting
open-cluster-management/rhacm-docs pull request #6418
Opened 2024-05-10 12:56 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-11539

2024-05-10 13:03 UTC, hchenxa commented on add-ons/configure_nodeselector_tolerations_addons.adoc
> +. To ensure your configuration for the add-on tolerations get pushed to your managed cluster, create a  `cluster-proxy add-on supportconfig` by using the following template:
what does the `cluster-proxy addon supportconfig` mean here?

2024-05-13 17:55 UTC, jc-berger commented on add-ons/configure_nodeselector_tolerations_addons.adoc
> +. To ensure your configuration for the add-on tolerations get pushed to your managed cluster, create a  `cluster-proxy add-on supportconfig` by using the following template:
@FDewaleyne I believe this is the type of config that users need to create, yes? 

If I'm incorrect, I'll make any changes you recommend.

2024-05-16 14:36 UTC, FDewaleyne commented on add-ons/configure_nodeselector_tolerations_addons.adoc
> +. To ensure your configuration for the add-on tolerations get pushed to your managed cluster, create a  `cluster-proxy add-on supportconfig` by using the following template:
this is a config that should be there by default but could be abscent for unknown reasons.
It does not cause errors, but instead part of the cluster-proxy addon will ignore the change in toleration and keep running on the compute nodes. no error.

2024-05-20 15:05 UTC, swopebe commented on add-ons/configure_nodeselector_tolerations_addons.adoc
> +[source,yaml]
formatting issue here.

2024-05-20 19:06 UTC, swopebe commented on add-ons/configure_nodeselector_tolerations_addons.adoc
> +. To ensure your configuration for the add-on tolerations get pushed to your managed cluster, create a  `cluster-proxy add-on supportconfig` by using the following template:
Formatting issues are still there in this PR, but also since this appears to be only related to a certain use-case, we should treat it as _troubleshooting._ The main doc is for all users and t-shooting is for these types of cases.

2024-05-20 19:52 UTC, swopebe requested changes
I think we need to look at this as troubleshooting.

2024-05-20 19:54 UTC, swopebe commented on add-ons/configure_nodeselector_tolerations_addons.adoc
> +. To ensure your configuration for the add-on tolerations get pushed to your managed cluster, create a  `cluster-proxy add-on supportconfig` by using the following template:
The way this is written, it is a workaround that goes into troubleshooting, that is how the official doc would categorize workarounds.

That said, if this needs to be part of the process, then we build it in to the task, not as a workaround, but a required step.

2024-05-21 18:59 UTC, swopebe commented on troubleshooting/trouble_cluster_proxy_addon_ignoring_addon_toleration.adoc
> ++
please create a space between paragraph and file sample to fix the formatting. If the code is not grayed out, that shows there is a formatting issue.

2024-05-21 19:02 UTC, swopebe requested changes
1. Make clear the symptom and get developers to review it. See the other files to see what I mean.
2. Formatting issue.
3. Rewrite "looks like"

Other than this, it looks good.

2024-05-21 19:02 UTC, swopebe commented on troubleshooting/trouble_cluster_proxy_addon_ignoring_addon_toleration.adoc
> +After you configure the add-on toleration, then by default, the cluster-proxy add-ons should run on your managed clusters and use the new add-on toleration. For unknown reasons, the cluster-proxy add
This is not necessarily a symptom, see how the other files hit the user with a symptom right away. SO read through this and sift through the symptom, since we are not giving a description like a main topic. Start with the symptom.

2024-05-21 19:02 UTC, swopebe commented on troubleshooting/trouble_cluster_proxy_addon_ignoring_addon_toleration.adoc
> ++
Please do not use: looks like

2024-05-21 19:02 UTC, swopebe commented on troubleshooting/trouble_cluster_proxy_addon_ignoring_addon_toleration.adoc
> ++
Same format issue here.

2024-05-23 14:42 UTC, swopebe approved these changes

2024-05-23 14:42 UTC, swopebe commented on troubleshooting/trouble_cluster_proxy_addon_ignoring_addon_toleration.adoc
> ++
Look at other topics for how we introduce samples.

2024-05-23 14:42 UTC, swopebe commented on troubleshooting/trouble_cluster_proxy_addon_ignoring_addon_toleration.adoc
> ++
So the symptom is something that the user sees right away, like a fail status or increased loads. We need a symptom. 

This is the result of the problem: affecting costs, adding loads on the infra and master nodes, and making these nodes less charged.

How does the user known there is a problem, do they have some kind of alert and error message. That is what we mean by symptom. I will approve but we need a clear symptom, then you can let that other content after the symptom.

2024-05-23 14:45 UTC, oafischer commented on troubleshooting/trouble_cluster_proxy_addon_ignoring_addon_toleration.adoc
> +[source,bash]
This doesn't look like a terminal command

2024-05-23 17:01 UTC, swopebe commented on troubleshooting/trouble_cluster_proxy_addon_ignoring_addon_toleration.adoc
> ++
Need to add headers here, I didn't see that until now.

2024-05-23 17:02 UTC, swopebe commented on troubleshooting/trouble_cluster_proxy_addon_ignoring_addon_toleration.adoc
> ++
Also, please cut down this filename, also just noticed that. We have shown examples in meetings about how we need to reduce filenames, this one is too long. We don't need the title in the filename, look at other topics for examples.

2024-05-23 17:03 UTC, swopebe requested changes

2024-05-23 17:03 UTC, swopebe commented on troubleshooting/trouble_cluster_proxy_addon_ignoring_addon_toleration.adoc
> +[#troubleshooting-cluster-proxy-addon-ignoring-addon-toleration]
Please cut down this anchor. I just posted an example of reducing anchor words on Slack for an example, and we have discussed this in training.

2024-05-30 18:46 UTC, swopebe requested changes
I thought I submitted this is a past review and on Slack but maybe not. Please change filenames and anchors to more concise and usable lengths.

2024-05-30 18:48 UTC, swopebe commented on add-ons/configure_nodeselector_tolerations_addons.adoc
> +The new configuration that you referenced in the add-on `ManagedClusterAddon` overrides the global default configuration that you previously defined in the `ClusterManagementAddon` add-on.
this is OK.

2024-05-30 18:48 UTC, swopebe commented on troubleshooting/trouble_cluster_ignoring_addon_toleration.adoc
> +----
content looks good

2024-05-30 18:48 UTC, swopebe commented on troubleshooting/troubleshooting_intro.adoc
> +- xref:../troubleshooting/trouble_cluster_ignoring_addon_toleration.adoc#troubleshooting-cluster-ignoring-addon-toleration[Troubleshooting the cluster proxy add-on ignoring the add-on toleration]
anchor and filename should be more concise

2024-05-30 19:13 UTC, swopebe approved these changes

2024-05-30 19:18 UTC, merged