ACM#11578: Update the services exposed on management control plane
open-cluster-management/rhacm-docs pull request #6424
Opened 2024-05-13 17:28 UTC by xenolinux

https://issues.redhat.com/browse/ACM-11578

2024-05-23 14:53 UTC, jparrill reviewed
small nit, otherwise LGTM

2024-05-23 14:53 UTC, jparrill commented on clusters/hosted_control_planes/enable_ext_dns_aws.adoc
> +You can deploy `external-dns` alongside the HyperShift Operator in the `hypershift` namespace of the management cluster. External DNS watches for `Services` or `Routes` that have the `external-dns.al
I would mention that this External DNS is only suitable on cloud environments, in other cases you will need to handle the DNS manually and add the proper entries for the relevant services.

2024-05-23 15:17 UTC, jparrill commented
/lgtm

2024-05-23 17:20 UTC, lahinson requested changes
@xenolinux Thanks so much for improving these docs! I left a few suggestions as well as some questions that I'm hoping @jparrill can answer.

2024-05-23 17:20 UTC, lahinson commented on clusters/hosted_control_planes/bm_intro.adoc
> +* Use firewall rules, security groups, or other access controls to restrict access to only required sources. Avoid exposing ports publicly unless necessary.
```suggestion
Use firewall rules, security groups, or other access controls to restrict access to only required sources. Avoid exposing ports publicly unless necessary.
```
Because line 58 was rewritten to no longer function as a lead-in sentence to a list, lines 62 and 63 can stand alone as sentences rather than be formatted as list items.

2024-05-23 17:20 UTC, lahinson commented on clusters/hosted_control_planes/bm_intro.adoc
> +* For production deployments, use a load balancer to simplify access through a single IP address.
```suggestion
For production deployments, use a load balancer to simplify access through a single IP address.
```

2024-05-23 17:20 UTC, lahinson commented on clusters/hosted_control_planes/bm_intro.adoc
> +** The `OAuthServer` service runs on port 443 by default when exposed by using the route and ingress.
Line 74 is a bit unclear. Does it mean that the service is exposed by using the route and ingress, or does it mean that the service runs on port 443 by using the route and ingress? cc @jparrill

2024-05-23 17:20 UTC, lahinson commented on clusters/hosted_control_planes/bm_intro.adoc
> +** The `Konnectivity` service runs on port 443 by default when exposed by using the route and ingress.
Similar question here as I have on line 74. Does this sentence mean that the service is exposed by using the route and ingress, or does it mean that the service runs on port 443 by using the route and ingress? cc @jparrill

2024-05-23 17:20 UTC, lahinson commented on clusters/hosted_control_planes/bm_intro.adoc
> +** The `Ignition` service runs on port 443 by default when exposed by using the route and ingress.
Like lines 74 and 79, the statement on line 86 could be clearer.

2024-05-23 17:20 UTC, lahinson commented on clusters/hosted_control_planes/bm_intro.adoc
> +You do not require the following services on bare metal:
```suggestion
You do not need the following services on bare metal:
```

2024-05-23 17:20 UTC, lahinson commented on clusters/hosted_control_planes/enable_ext_dns_aws.adoc
> +The control plane and the data plane are separate in hosted control planes. You can configure DNS in two independent areas:
Nice revision!

2024-05-23 17:20 UTC, lahinson commented on clusters/hosted_control_planes/enable_ext_dns_aws.adoc
> +External DNS creates name records for hosted cluster `Services` that specify a publishing type of `LoadBalancer` or `Route` and provide a hostname for that publishing type. For hosted clusters with `
```suggestion
External DNS creates name records for hosted cluster `Services` that specify a publishing type of `LoadBalancer` or `Route` and provide a hostname for that publishing type. For hosted clusters with `Private` or `PublicAndPrivate` endpoint access types, only the `APIServer` and `OAuth` services support hostnames. For `Private` hosted clusters, the DNS record resolves to a private IP address of a Virtual Private Cloud (VPC) endpoint in your VPC.
```

2024-05-23 17:20 UTC, lahinson commented on clusters/hosted_control_planes/enable_ext_dns_aws.adoc
> +Each of those services is exposed by using `servicePublishingStrategy` in the `HostedCluster` specification. By default, for the `LoadBalancer` and `Route` types of `servicePublishingStrategy`, you c
```suggestion
Each of those services is exposed by using `servicePublishingStrategy` in the `HostedCluster` specification. By default, for the `LoadBalancer` and `Route` types of `servicePublishingStrategy`, you can publish the service in one of the following ways:
```

2024-05-23 17:20 UTC, lahinson commented on clusters/hosted_control_planes/enable_ext_dns_aws.adoc
> +You can use External DNS on cloud environments only. For the other environments, you need to configure DNS and services manually.
```suggestion
You can use external DNS on cloud environments only. For the other environments, you need to manually configure DNS and services.
```
Minor edits:
- External DNS doesn't need to be capitalized unless it's at the beginning of a sentence
- Per IBM Style, try to place adverbs as close to the word that they modify as possible

2024-05-23 17:20 UTC, lahinson commented on clusters/hosted_control_planes/enable_ext_dns_aws.adoc
> +* You have created an external public domain
```suggestion
* You created an external public domain
```

2024-05-23 17:20 UTC, lahinson commented on clusters/hosted_control_planes/enable_ext_dns_aws.adoc
>  When the Control Plane Operator creates the `Services` and `Routes`, it annotates them with the `external-dns.alpha.kubernetes.io/hostname` annotation. The value is the `hostname` field in the `servi
```suggestion
When the Control Plane Operator creates the `Services` and `Routes`, it annotates them with the `external-dns.alpha.kubernetes.io/hostname` annotation. The value is the `hostname` field in the `servicePublishingStrategy` for that type. The Control Plane Operator uses that name for the service endpoints, and it expects that if the hostname is set, a mechanism exists, such as external DNS or otherwise, which can create the DNS records.
```
I'm not sure why "external DNS" is all lowercase and hyphenated. I suspect it should be "external DNS". Maybe check with @jparrill?

2024-05-23 17:20 UTC, lahinson commented on clusters/hosted_control_planes/enable_ext_dns_aws.adoc
> +You need to deploy the HyperShift Operator and the External DNS Operator when the external public hosted zone already exists.
A question for @jparrill: Does the external public hosted zone usually already exist when users reach this task? I ask because the way this line is currently written, it almost sounds like a conditional statement. Would it be correct to revise it to something like this? "If the external public hosted zone already exists, you need to deploy the HyperShift Operator and the External DNS Operator."

2024-05-23 17:20 UTC, lahinson commented on clusters/hosted_control_planes/enable_ext_dns_aws.adoc
> +    --base-domain service-consumer-domain.com \ <4>
Is `service-consumer-doman.com` a variable? Should it be `<service_provider_domain>`?

2024-05-23 17:20 UTC, lahinson commented on clusters/hosted_control_planes/enable_ext_dns_aws.adoc
> +<4> Points to the public hosted zone that the service consumer owns, for example, `service-consumer-domain.com`.
Should this be revised as follows? `Specify the public hosted zone that the service consumer owns, for example, `service-consumer-domain.com`.`

2024-05-23 17:20 UTC, lahinson commented on clusters/hosted_control_planes/enable_ext_dns_aws.adoc
> +<8> Points to the public external DNS hosted zone that the service provider owns, for example, `service-provider-domain.com`.
See comment about line 224. Should line 228 be revised to be an imperative statement?

2024-05-23 17:45 UTC, xenolinux commented on clusters/hosted_control_planes/enable_ext_dns_aws.adoc
> +    --base-domain service-consumer-domain.com \ <4>
In the older version `--base-domain` is using the consumer domain. So I think this should be `<service_consumer_domain>`

2024-05-23 17:45 UTC, xenolinux commented on clusters/hosted_control_planes/enable_ext_dns_aws.adoc
> +<4> Points to the public hosted zone that the service consumer owns, for example, `service-consumer-domain.com`.
Revised.

2024-05-23 17:47 UTC, xenolinux commented on clusters/hosted_control_planes/bm_intro.adoc
> +** The `OAuthServer` service runs on port 443 by default when exposed by using the route and ingress.
per slack discussion, imo, it means that "the service is exposed by using the route and ingress" updated the sentence accordingly. @jparrill can confirm though.

2024-05-23 17:47 UTC, xenolinux commented on clusters/hosted_control_planes/bm_intro.adoc
> +** The `Konnectivity` service runs on port 443 by default when exposed by using the route and ingress.
per slack discussion, imo, it means that "the service is exposed by using the route and ingress" updated the sentence accordingly. @jparrill can confirm though.

2024-05-27 07:44 UTC, xenolinux commented on clusters/hosted_control_planes/enable_ext_dns_aws.adoc
>  When the Control Plane Operator creates the `Services` and `Routes`, it annotates them with the `external-dns.alpha.kubernetes.io/hostname` annotation. The value is the `hostname` field in the `servi
If it should be "external-dns" then it should have been within the back ticks in the first place `external-dns`.  I feel that [1] is confusing, for eg, we are unable to say if it's some kind of an API object or just external DNS entity.

[1] The value is the `hostname` field in the `servicePublishingStrategy` for that type. The Control Plane Operator uses that name for the service endpoints, and it expects that if the hostname is set, a mechanism exists, such as external DNS or otherwise, which can create the DNS records.

2024-05-27 08:08 UTC, xenolinux commented on clusters/hosted_control_planes/enable_ext_dns_aws.adoc
> +You need to deploy the HyperShift Operator and the External DNS Operator when the external public hosted zone already exists.
Per the "Creating the public DNS hosted zone" section that is listed just above this section, the public hosted zone already exists when users reach this task. 
See https://github.com/stolostron/rhacm-docs/pull/6424/files#diff-802df7b14d46e2d93353517b7ceb4c69bf22144b4147bbe2107eb42df1de05d0L92

2024-05-27 08:10 UTC, xenolinux commented on clusters/hosted_control_planes/enable_ext_dns_aws.adoc
> +You need to deploy the HyperShift Operator and the External DNS Operator when the external public hosted zone already exists.
I believe creating public zone is not optional so users must already have this public zone, and hence must install the HyperShift Operator and the External DNS Operator. -- confirming with Juan on the channel.

2024-05-27 08:25 UTC, jparrill commented on clusters/hosted_control_planes/enable_ext_dns_aws.adoc
> +You need to deploy the HyperShift Operator and the External DNS Operator when the external public hosted zone already exists.
Creating a Public HostedZone in Route53 is optional as long as customers do not use the `PublicAndPrivate` or `Public` configurations for their HostedClusters.

2024-05-27 09:16 UTC, xenolinux commented on clusters/hosted_control_planes/enable_ext_dns_aws.adoc
> +You need to deploy the HyperShift Operator and the External DNS Operator when the external public hosted zone already exists.
Per the overall discussion, adding the following clarification sentences:
- "If you created the public DNS hosted zone, you need to deploy the HyperShift Operator and the External DNS Operator."
- "To use the `PublicAndPrivate` or `Public` endpoint access for your hosted cluster, you need to create the public DNS hosted zone."
- For more information about external DNS, see link:https://github.com/kubernetes-sigs/external-dns[external DNS].

2024-05-27 09:25 UTC, xenolinux commented on clusters/hosted_control_planes/enable_ext_dns_aws.adoc
>  When the Control Plane Operator creates the `Services` and `Routes`, it annotates them with the `external-dns.alpha.kubernetes.io/hostname` annotation. The value is the `hostname` field in the `servi
per the slack discussion - Updating to 

"The Control Plane Operator creates the `Services` and `Routes` resources and annotates them with the `external-dns.alpha.kubernetes.io/hostname` annotation. For `Services` and `Routes`, the Control Plane Operator uses a value of the `hostname` parameter in the `servicePublishingStrategy` field for the service endpoints. You can use a mechanism that creates the DNS records, such as the `external-dns` deployment."

2024-05-27 09:45 UTC, xenolinux commented
While updating, I realised the command to verify the status of EDNS Operator is missing.

2024-05-27 10:11 UTC, xenolinux commented
> While updating, I realised the command to verify the status of EDNS Operator is missing.
> 
> https://github.com/stolostron/rhacm-docs/pull/6424/files#diff-802df7b14d46e2d93353517b7ceb4c69bf22144b4147bbe2107eb42df1de05d0R204

Done. Added the command.

2024-05-27 12:44 UTC, oafischer approved these changes
Thanks for these updates and revisions! Approving, but take not that there is a broken link not related to your changes.
![Screenshot 2024-05-27 at 14-40-02 rhacm-docs_clusters_hosted_control_planes_bm_intro adoc at 9969a64ca3ff728ce95f0e4c596e1ab037185528 · stolostron_rhacm-docs](https://github.com/stolostron/rhacm-docs/assets/108426932/bff3353c-820b-4ba1-b87b-ba85654af0c3)

2024-05-27 13:04 UTC, xenolinux commented
> Thanks for these updates and revisions! Approving, but take note that there is a broken link not related to your changes. ![Screenshot 2024-05-27 at 14-40-02 rhacm-docs_clusters_hosted_control_planes_bm_intro adoc at 9969a64ca3ff728ce95f0e4c596e1ab037185528 · stolostron_rhacm-docs](https://private-user-images.githubusercontent.com/108426932/334105479-bff3353c-820b-4ba1-b87b-ba85654af0c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MTUzNjYsIm5iZiI6MTcxNjgxNTA2NiwicGF0aCI6Ii8xMDg0MjY5MzIvMzM0MTA1NDc5LWJmZjMzNTNjLTgyMGItNGJhMS1iODdiLWJhODU2NTRhZjBjMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyN1QxMzA0MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZTAzYjJjNTAyOGNiNzgxYTI5ZTg0ZWFiZGEwMjUzYjA3Yzc1YjQwY2M1N2ZmMThlMjExMDc4NjhjMWIzYWEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7sZfpfQ1OIam2uR6kKNAtVK6d5HR89vxeFoArV5AzYo)

Fixed the link.

2024-05-27 13:05 UTC, merged