added new section for oadp operator and moved content
open-cluster-management/rhacm-docs pull request #6428
Opened 2024-05-13 18:53 UTC by jc-berger

see jira: https://issues.redhat.com/browse/ACM-11182

2024-05-13 19:00 UTC, birsanv requested changes
looks good, with one update requested

2024-05-13 19:00 UTC, birsanv commented on business_continuity/backup_restore/backup_install.adoc
> +When you enable the backup option on the `MultiClusterHub`, the backup option remains in the `Pending` state until you install the OADP operator in the `open-cluster-management-backup` namespace. If
Replace : If you use the chart, the OADP operator is automatically installed. If you use the STS option, you must manually install the OADP operator.

With : If you do not have enabled the AWS Security Token Service (STS) option on your hub cluster, the OADP operator is automatically installed with the backup chart, otherwise you manually install the OADP operator.

2024-05-15 19:54 UTC, dockerymick requested changes

2024-05-15 19:54 UTC, dockerymick commented on business_continuity/backup_restore/backup_install.adoc
> +For hub clusters where you did not enable the STS option, the OADP operator is automatically installed when you installed the cluster backup and restore operator on the hub cluster.
```suggestion
For hub clusters where you did not enable the STS option, the OADP operator is automatically installed when you install the cluster backup and restore operator on the hub cluster. 
```

2024-05-15 19:54 UTC, dockerymick commented on business_continuity/backup_restore/backup_install.adoc
> +When you enable the backup option on the `MultiClusterHub`, the backup option remains in the `Pending` state until you install the OADP operator in the `open-cluster-management-backup` namespace. If
```suggestion
When you enable the backup option from the `MultiClusterHub` resource, the backup option remains in the `Pending` state until you install the OADP operator in the `open-cluster-management-backup` namespace. If you have not enabled the AWS STS option on your hub cluster, then the OADP operator is automatically installed with the backup chart. Otherwise, you must manually install the OADP operator.
```

2024-05-15 19:54 UTC, dockerymick commented on business_continuity/backup_restore/backup_install.adoc
> +* <<enabling-backup-restore,Enabling the backup and restore operator>>
The order of this file seems inconsistent. The topics listed are mentioned at the beginning of the file.

2024-05-15 19:54 UTC, dockerymick commented on business_continuity/backup_restore/backup_install.adoc
>  The cluster backup and restore operator is not installed automatically. Continue reading to learn how to install and enable the operator.
If there are more than 3 H2 sections, it is best to list after the introduction of the task. This way the user will know how many topics to expect.

2024-05-15 20:43 UTC, birsanv approved these changes
lgtm

2024-05-16 18:39 UTC, jc-berger commented on business_continuity/backup_restore/backup_install.adoc
> +* <<enabling-backup-restore,Enabling the backup and restore operator>>
Thanks, I removed it since I added a list of all the sections the user needs to complete, as you requested in your other comment.

2024-05-20 15:26 UTC, dockerymick approved these changes
Looks good to me ! Thanks Jake. I like how you let the user know that the tasks within the sections need to be done in order. I do recommend that you remove 

"* <<setting-up-hub-clusters-for-backup-and-restore-operators,Setting up hub clusters for backup and restore operators>>
* <<enabling-backup-restore,Enabling the backup and restore operator>>"

Since these are the only H2 sections, we don't need to list them. The sections are displayed from the TOC of the portal navigation menu. I am on board with you merging this PR and then let's take a look at the preview to check

2024-05-20 17:47 UTC, merged