added new troubleshooting topic for search databases
open-cluster-management/rhacm-docs pull request #6431
Opened 2024-05-14 17:45 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-11337

2024-05-14 17:48 UTC, SherinV commented on troubleshooting/trouble_search_database.adoc
> +. Restart the indexer pod.
```suggestion
. Restart the search-indexer pod in open-cluster-management namespace. 
```

2024-05-15 13:20 UTC, dockerymick requested changes

2024-05-15 13:20 UTC, dockerymick commented on troubleshooting/trouble_search_database.adoc
> +If your application topology has missing clusters, but your clusters are actually active, the issue might be that the cluster nodes are not found in the search database.
```suggestion
If you are missing clusters from application topology, but your clusters are actually active, the issue might be that the cluster nodes are not found in the search database. 
```

2024-05-15 13:20 UTC, dockerymick commented on troubleshooting/trouble_search_database.adoc
> +. Restart the search-indexer pod in open-cluster-management namespace.
How does the user restart the pod? Is it an action from the console or do they need to run a command? 
```suggestion
. Restart the `search-indexer` pod in `open-cluster-management` namespace. 
```

2024-05-15 13:20 UTC, dockerymick commented on troubleshooting/trouble_search_database.adoc
> +. Go to your application topology and verify that the clusters are there.
How do they navigate to the Topology page? I believe they select the Application tap or they can simply select the app name. @SherinV will you help verify

2024-05-16 17:59 UTC, SherinV commented on troubleshooting/trouble_search_database.adoc
> +. Go to your application topology and verify that the clusters are there.
User will go to the application page, select an application and switch to Topology view.

2024-05-16 18:00 UTC, SherinV commented on troubleshooting/trouble_search_database.adoc
> +. Restart the search-indexer pod in open-cluster-management namespace.
User will delete the existing search-indexer pod, so that it automatically restarts.

2024-05-16 19:15 UTC, dockerymick requested changes

2024-05-16 19:15 UTC, dockerymick commented on troubleshooting/trouble_search_database.adoc
> +. Go to your application page, select your application, then switch to the *Topology* view.
Application should italicized and i would separate the task
```suggestion
. Go to the  _Application_ page, select your application. 
. To verify that the cluster is displayed,  switch to the *Topology* view. 
```

2024-05-16 19:15 UTC, dockerymick commented on troubleshooting/trouble_search_database.adoc
> +. Verify that the clusters are there.
```suggestion

```

2024-05-16 19:26 UTC, SherinV commented on troubleshooting/trouble_search_database.adoc
> +If you are missing clusters from application topology, but your clusters are actually active, the issue might be that the cluster nodes are not found in the search database.
If search or the application topology are missing clusters, it could be that the search data got out of sync.

2024-05-16 19:26 UTC, SherinV commented on troubleshooting/trouble_search_database.adoc
> +. Go to your application page, select your application, then switch to the *Topology* view.
- Go to the search page and search for kind:Cluster.
- Verify the list of clusters matches your managed clusters.

2024-05-17 13:31 UTC, SherinV commented on troubleshooting/trouble_search_database.adoc
> +If you are missing clusters from application topology, but your clusters are actually active, the issue might be that the cluster nodes are not found in the search database.
```suggestion
If search or the application topology are missing clusters, it could be that the search data got out of sync.
```

2024-05-17 15:09 UTC, dockerymick commented on troubleshooting/trouble_search_database.adoc
> +If you are missing clusters from application topology, but your clusters are actually active, the issue might be that the cluster nodes are not found in the search database.
To have active tone, let's say "If search or the application topology are missing clusters, it might be that the search data is out of sync." @jc-berger thoughts??

2024-05-20 18:00 UTC, dockerymick approved these changes
This looks good to me!

2024-05-20 18:12 UTC, merged