https://issues.redhat.com/browse/ACM-11428 z-stream ACM 2.10.3
open-cluster-management/rhacm-docs pull request #6433
Opened 2024-05-14 18:59 UTC by cadawson

2024-05-15 21:14 UTC, cadawson commented
I'm assuming you are taking this one, @dockerymick, since you added yourself as a reviewer. Feel free to take a look at it. There are more on this one, and a couple might need a couple of read-throughs. Thanks!

2024-05-16 12:47 UTC, rhaignere approved these changes
LGTM, thank you!

2024-05-16 13:43 UTC, dockerymick requested changes
Made some suggestions

2024-05-16 13:43 UTC, dockerymick commented on release_notes/errata.adoc
> +* Fixes a bug where a `ConfigurationPolicy` with the `MustOnlyHave` compliance type did not factor root-level keys in the object on the cluster when comparing it to the policy definition. (link:https
```suggestion
* Fixes a bug where a `ConfigurationPolicy` resource with the `MustOnlyHave` compliance type did not factor root-level keys in the object on the cluster when comparing it to the policy definition. (link:https://issues.redhat.com/browse/ACM-10877[ACM-10877])
```

2024-05-16 13:43 UTC, dockerymick commented on release_notes/errata.adoc
> +* Fixes an issue in the Policy Generator where some placement overrides that exist outside of `policyDefaults` did not correctly override the default. (link:https://issues.redhat.com/browse/ACM-11075
```suggestion
* Fixes an issue in the Policy Generator where some placement overrides that exist outside of the `policyDefaults` parameter section did not correctly override the default. (link:https://issues.redhat.com/browse/ACM-11075[ACM-11075])
```

2024-05-16 13:43 UTC, dockerymick commented on release_notes/errata.adoc
> +* Fixes an issue that prevented the {product-title-short} `gitopsCluster` controller from automatically generating the managed cluster secret for the Argo CD push model when an application addon serv
```suggestion
* Fixes an issue that prevented the {product-title-short} `gitopsCluster` controller from automatically generating the managed cluster secret for the Argo CD push model when an application add-on service account named `application-manager` was provisioned in {ocp} 4.15 by some cloud providers. (link:https://issues.redhat.com/browse/ACM-11149[ACM-11149])
```

2024-05-16 14:24 UTC, rhaignere approved these changes
Thanks for updating! LGTM

2024-05-16 14:43 UTC, dockerymick approved these changes
Thanks Chris!

2024-05-17 14:38 UTC, merged