added content for kafka and grafana dashboards
open-cluster-management/rhacm-docs pull request #6450
Opened 2024-05-22 15:20 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-11683

2024-05-23 07:20 UTC, ldpliu commented on global_hub/global_hub_access_data.adoc
> +== Viewing Postgres information by using Grafana dashboards
The postgres dashboard is Technich preview. So it should be:
`Viewing Postgres information by using Grafana dashboards (Technology Preview)`

2024-05-23 07:23 UTC, ldpliu commented
I submitted a pr to add dashboard images to globalhub github repo. After it merged, you may need to add link to it.
https://github.com/stolostron/multicluster-global-hub/pull/937

2024-05-23 16:33 UTC, jc-berger commented
@ldpliu thanks! When your PR gets merged, I'll include the link to the dashboard images :)

2024-05-29 06:43 UTC, ldpliu commented on global_hub/global_hub_access_data.adoc
> +* {global-hub} - PostgresSQL Database
Please Add a new section for clusters.

[#global-hub-viewing-clusters-info-using-grafana-dashboards]
== Viewing Cluster information by using Grafana dashboards (Dev Preview)

This dashboard allow you to filter Managedclusters based on `hub`, `labels` and `Name` . You can see the managedcluster distribution based on `hub`, `status`, `cloud`, `version`. You could also see the Managedcluster details and events. 
In the Cluster folder, you can view the following dashboard: 

* {global-hub} - Cluster Overview

2024-05-29 06:45 UTC, ldpliu commented
Please help to add a new section about cluster, detail please see: https://github.com/stolostron/rhacm-docs/pull/6450#discussion_r1618290679
The [dashboard images](https://github.com/stolostron/multicluster-global-hub/tree/main/doc/dashboard) has merged, please also add the link to this pr.

2024-05-29 18:16 UTC, jc-berger commented on global_hub/global_hub_access_data.adoc
> +To view images of the {global-hub} dashboard, see link:https://github.com/stolostron/multicluster-global-hub/tree/main/doc/dashboard[multicluster global hub dashboard images].
Doc reviewers: 

I know we're not always keen to include links outside our docs repo. Since this is a link to a solostron doc, I thought it'd be fine. 

With that said, is there a way I can use an xref here? Or are xrefs only an option if we're linking to other docs in our specific doc repo, not the larger solostron repo?

2024-05-30 00:56 UTC, ldpliu commented on global_hub/global_hub_access_data.adoc
> +To view images of the {global-hub} dashboard, see link:https://github.com/stolostron/multicluster-global-hub/tree/main/doc/dashboard[multicluster global hub dashboard images].
> Doc reviewers:
> 
> I know we're not always keen to include links outside our docs repo. Since this is a link to a solostron doc, I thought it'd be fine.
> 
> With that said, is there a way I can use an xref here? Or are xrefs only an option if we're linking to other docs in our specific doc repo, not the larger solostron repo?

Currently, I think we do not have a separate directory to put doc. I have no idea to do this.
@clyang82 @hchenxa  Any thought?

2024-05-30 18:51 UTC, swopebe requested changes

2024-05-30 18:51 UTC, swopebe commented on global_hub/global_hub_access_data.adoc
> +
we need to cut these down a lot: `global-hub-viewing-postgres-information-using-grafana-dashboards` and `global-hub-viewing-strimzi-information-using-grafana-dashboards` --

2024-06-03 18:04 UTC, swopebe approved these changes

2024-06-03 23:37 UTC, ldpliu commented
/lgtm

2024-06-04 15:37 UTC, merged