https://issues.redhat.com/browse/ACM-11407 Add URL custom. docs
open-cluster-management/rhacm-docs pull request #6459
Opened 2024-05-27 09:57 UTC by oafischer

Train 14, 2.11 only

2024-05-28 10:39 UTC, douglascamata requested changes
@oafischer I would like to add some more details to the these docs:

1. `customObservabilityHubURL` and `customAlertmanagerHubURL` only support `https` URLs and will automatically prepend the `https://` scheme if it's not present. `http` is not supported. 
2. `customObservabilityHubURL` may include the standard path for the Remote Write API (`/api/metrics/v1/default/api/v1/receive`). If it's not included, ACM Observability will automatically add it at runtime.

2024-05-28 14:42 UTC, oafischer commented
Updated, thanks for the additional info @douglascamata. Feel free to review when ready.

2024-05-29 13:59 UTC, dockerymick approved these changes
Small suggestions. Otherwise, this looks great to me!

2024-05-29 13:59 UTC, dockerymick commented on observability/customize_observability.adoc
> +* You can include the standard path for the Remote Write API `/api/metrics/v1/default/api/v1/receive` in the `customObservabilityHubURL` spec. If you do not include the path, Observability automatica
```suggestion
* You can include the standard path for the Remote Write API, `/api/metrics/v1/default/api/v1/receive` in the `customObservabilityHubURL` `spec`. If you do not include the path, the Observability service automatically adds the path at runtime.
```

2024-05-29 16:02 UTC, douglascamata approved these changes
/lgtm

2024-05-31 11:09 UTC, merged