ACM-11775
open-cluster-management/rhacm-docs pull request #6487
Opened 2024-06-03 11:46 UTC by krishnanshruthi

Changes as suggested by Damisetti Veera
IBM Jira ticket for ref: https://jsw.ibm.com/browse/OCPONZ-4102

2024-06-03 11:47 UTC, krishnanshruthi commented
[dveerabh@redhat.com](mailto:dveerabh@redhat.com) Please review

2024-06-03 13:17 UTC, swopebe commented
@krishnanshruthi thanks for the PR. We do have a bit to do for this in peer review, is there an ACM doc issue that you have opened for us? Can you link one here...I will take it as the peer reviewer. I cannot see the IBM Issue, but we track this on the ACM side anyway.

2024-06-03 13:39 UTC, krishnanshruthi commented
@swopebe Here's the link to the jira ticket on ACM side: https://issues.redhat.com/browse/ACM-11775

I have put the PR for technical review to Veera. I would suggest a peer review post that, if thats ok.

2024-06-04 12:57 UTC, swopebe commented
@krishnanshruthi yes, the RHACM team will review it and make any changes needed, I will pull you in on those changes.

2024-06-04 14:58 UTC, swopebe requested changes

2024-06-04 14:58 UTC, swopebe commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
This will need to be built like the rest of RHACM doc with proper and concise headers, removing the bold tag unless it is clickable, (this is accessibility), files references have to be tagged, self referential language fixed, couple incorrect punctuation.

This needs to be broken out into steps instead of comments in the scripts:

----
INITRD_IMG_NAME=$(echo $INITRD_IMG_PATH | rev | cut -d '/' -f 1 | rev)
# the kernel always sits at offset 0x00
KERNEL_OFFSET=0x00000000
KERNEL_CMDLINE_OFFSET=0x00010480
INITRD_ADDR_SIZE_OFFSET=0x00010408
OFFSET_HEX=$(printf '0x%08x\n' $offset)
# Convert address and size to binary format
printf "$(printf '%016x\n' $offset)" | xxd -r -p > temp_address.bin
printf "$(printf '%016x\n' $initrd_size)" | xxd -r -p > temp_size.bin
# Concatenate address and size binaries
cat temp_address.bin temp_size.bin > "$INITRD_IMG_NAME.addrsize"
# Clean up temporary files
rm -rf temp_address.bin temp_size.bin
----

2024-06-04 15:08 UTC, swopebe commented
@lahinson has offered to take this, as she has current bandwidth.

2024-06-05 08:57 UTC, veera-damisetti commented
Discussed with @krishnanshruthi  offline and shared the required changes

2024-06-06 10:14 UTC, veera-damisetti commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +. Transfer the initrd, kernel, generic.ins , initrd.img.addrsize ,  parameter file to the File server. For details on how to transfer the files with FTP and boot, see xref:https://access.redhat.com/d
Installing in an LPAR
is not pointing to the link , if i see the file .
Can you check once @krishnanshruthi

2024-06-06 10:17 UTC, veera-damisetti commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +. Generate the .ins file
Update this line to
 Generate the .ins file and initrd.img.addrsize

2024-06-06 10:21 UTC, veera-damisetti commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +== Adding IBM Z with KVM as Agents
this heading should be 
Adding IBM Z KVM as Agents

2024-06-07 05:38 UTC, krishnanshruthi commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +. Transfer the initrd, kernel, generic.ins , initrd.img.addrsize ,  parameter file to the File server. For details on how to transfer the files with FTP and boot, see xref:https://access.redhat.com/d
Will check, thank you!

2024-06-10 06:29 UTC, veera-damisetti commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +{ocp-short} 4.16 allows you to add the Logical Partition (LPAR) on IBM Z or IBM LinuxONE as a **Compute node** in the a hosted control plane.
This should be , 
**Compute node**  to  a hosted control plane. ( instead of using 'in the')

2024-06-10 06:32 UTC, veera-damisetti commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +. Restart the machine.
It should be **Boot the machine**
as restart will change the context here

2024-06-13 16:26 UTC, lahinson commented
Shruthi notified me that this is ready for review. I will take a look soon.

2024-06-13 18:49 UTC, lahinson requested changes
@krishnanshruthi Please see my comments and let me know if you have questions. Thank you!

2024-06-13 18:49 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
>  [#hosted-bare-metal-adding-agents-ibmz-zvm]
```suggestion
[#hosted-bare-metal-adding-agents-ibmz-zvm-lpar]
```
IDs must be unique.

2024-06-13 18:49 UTC, lahinson commented on clusters/hosted_control_planes/ibmz_intro.adoc
> +. xref:../red_hat_advanced_cluster_management_for_kubernetes/2.10/html/clusters/cluster_mce_overview#hosted-control-planes-create-infraenv-ibmz[Creating an InfraEnv resource for hosted control planes
```suggestion
. xref:../hosted_control_planes/create_infraenv_ibmz.adoc#hosted-control-planes-create-infraenv-ibmz[Creating an InfraEnv resource for hosted control planes on 64-bit x86 bare metal for IBM Z compute nodes]
```

2024-06-13 18:49 UTC, lahinson commented on clusters/hosted_control_planes/scale_nodepool_hosted_ibmpower.adoc
> +To scale down the data plane to zero, see xref:../hosted_control_planes/troubleshooting-hosted-control-planes#scale-down-data-plane_hcp-troubleshooting[Scaling down the data plane to zero].
```suggestion
To scale down the data plane to zero, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.15/html/hosted_control_planes/troubleshooting-hosted-control-planes#scale-down-data-plane_hcp-troubleshooting[Scaling down the data plane to zero].
```

2024-06-13 18:49 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +== Adding IBM Z KVM as Agents
It is a best practice to describe why users might want to complete a task at the beginning of the task. Please revise line 4 to explain why someone might want to add agents in an IBM Z environment.

2024-06-13 18:49 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
>  For IBM Z with KVM, run the following command to start your IBM Z environment with the downloaded PXE images from the `InfraEnv` resource. After the Agents are created, the host communicates with the
Wherever you have variables in code that the user will replace, include callouts in the code to explain what the user should specify. For an example of how to write callouts in asciidoc, see https://github.com/stolostron/rhacm-docs/blob/2.11_stage/clusters/hosted_control_planes/create_cluster_kubevirt.adoc#creating-a-hosted-cluster.

2024-06-13 18:49 UTC, lahinson commented on clusters/hosted_control_planes/scale_nodepool_hosted_ibmz.adoc
> +[#destroying-hosted-clusted-x86bm-ibmz]
To be consistent with other documentation in this repo, this task should be moved to its own file. For an example, see https://github.com/stolostron/rhacm-docs/blob/2.11_stage/clusters/hosted_control_planes/destroy_cluster_kubevirt.adoc.

2024-06-13 18:49 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +{ocp-short} 4.16 allows you to add the Logical Partition (LPAR) on IBM Z or IBM LinuxONE as a **Compute node** to a hosted control plane.
```suggestion
You can add a Logical Partition (LPAR) on IBM Z or IBM LinuxONE as a compute node to a hosted control plane.
```
Revised to avoid anthropomorphic language, per the IBM Style guide. Why would someone want to add a LPAR as a compute node to a hosted control plane? Consider adding that information to this introduction.

2024-06-13 18:49 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +== Adding IBM Z LPAR as Agents
```suggestion
== Adding IBM Z LPAR as agents
```
The term "agent" is lowercase unless it starts a sentence or we are referring to a specific `Agent` resource.

2024-06-13 18:49 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +== Adding IBM Z KVM as Agents
```suggestion
== Adding IBM Z KVM as agents
```
The term "agent" is lowercase unless it starts a sentence or we are referring to a specific `Agent` resource.

2024-06-13 18:49 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +=== Procedure
```suggestion

```

2024-06-13 18:49 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +.Sample parameter file:
```suggestion
.Sample parameter file
```

2024-06-13 18:49 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +. Create a boot parameter file for the agents.
```suggestion
. Create a boot parameter file for the agents.
```
Does the user need to know anything else to create the file? Should we specify the file type and where the user should save the file?

2024-06-13 18:49 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +rd.neednet=1 coreos.live.rootfs_url=<rootfs_url> ip=<IP_guest_vm>::<nameserver>:255.255.255.0::<network_adaptor>:none nameserver=<nameserver> ai.ip_cfg_override=1 rd.znet=qeth,<network_adaptor_range>
- Consider formatting this sample file to be easier to scan. 
- Wherever you have variables in code that the user will replace, include callouts in the code to explain what the user should specify. For an example of how to write callouts in asciidoc, see https://github.com/stolostron/rhacm-docs/blob/2.11_stage/clusters/hosted_control_planes/create_cluster_kubevirt.adoc#creating-a-hosted-cluster.

2024-06-13 18:49 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +The .ins file is a special file that includes installation data and is present on the FTP server. It can be accessed from the HMC system.
```suggestion
The `.ins` file includes installation data and is on the FTP server. You can access the file from the HMC system.
```

2024-06-13 18:49 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +This file contains details such as mapping of the location of installation data on the disk or FTP server, the memory locations where the data is to be copied.
```suggestion
This file contains details such as the location of installation data on the disk or FTP server and the memory locations where the data is to be copied.
```

2024-06-13 18:49 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +**Note**: In {ocp-short} 4.16, the .ins file and 'initrd.img.addrsize' are not automatically generated as part of boot-artifacts from the installer. You must generate these files manually.
```suggestion
**Note**: The `.ins` file and `initrd.img.addrsize` file are not automatically generated as part of the artifacts from the installer. You must manually generate these files.
```

2024-06-13 18:49 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +.. Run the following commands to get the size of the kernel and initrd.
```suggestion
. Run the following commands to get the size of the `kernel` and `initrd` files:
```
I don't see a reason why this should be a substep instead of a step. Also, I assume that kernel and initrd are files. If my revision is technically inaccurate, feel free to tweak it.

2024-06-13 18:49 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +.. Round the kernel size up to the next MiB boundary. This will be the starting address of initrd.img.
```suggestion
. Round the kernel size up to the next mebibyte (MiB) boundary. This is the starting address of the `initrd.img` file.
```
Please revise this line to more clearly indicate what "This" refers to. Do you mean that the MiB boundary will be the starting address of the `initrd.img` file?

2024-06-13 18:49 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +.. Create the kernel binary patch file holding the initrd address and size.
```suggestion
. Create the kernel binary patch file that contains the `initrd` address and size.
```
If the user needs to know more details about the file that they are creating in this step, please add them here. What type of file should they create? Where should they save it?

2024-06-13 18:49 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +.. Create the .ins file based on the paths of these files (kernel.img, initrd.img , initrd.img.addrsize, cmdline) and the memory locations where the data is to be copied.
add a blank line between lines 109 and 110

2024-06-13 18:49 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +[source,yaml]
Be sure to add callouts for any variables that the user needs to replace.

2024-06-13 18:49 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +.. Create the .ins file based on the paths of these files (kernel.img, initrd.img , initrd.img.addrsize, cmdline) and the memory locations where the data is to be copied.
```suggestion
. Create the `.ins` file that is based on the paths of the `kernel.img`, `initrd.img`, `initrd.img.addrsize`, and `cmdline` files and the memory locations where the data is to be copied.
```

2024-06-13 18:49 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +[source,yaml]
Be sure to include callouts for any variables that the user needs to replace in this YAML file. Also, we typically omit code such as `cat > generic.ins <<EOF` and `EOF` from the docs.

2024-06-13 18:49 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +. Transfer the `initrd`, `kernel`, `generic.ins` , `initrd.img.addrsize` parameter file to the File server. For details on how to transfer the files with FTP and boot, see link:https://access.redhat.
```suggestion
. Transfer the `initrd`, `kernel`, `generic.ins`, and `initrd.img.addrsize` parameter files to the file server. For more information, see _Installing in an LPAR_.     
```
Move the link to an "Additional resources" section for this task: link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/performing_a_standard_rhel_8_installation/installing-in-an-lpar_installing-rhel[Installing in an LPAR].

2024-06-13 18:49 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +. Boot the machine.
```suggestion
. Start the machine.
```
Revising per IBM Style.

2024-06-13 18:49 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +. Repeat the procedure for all the other machines in the cluster.
```suggestion
. Repeat the procedure for all other machines in the cluster.
```

2024-06-13 18:49 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
It's unusual to introduce a task with a Note. Consider adding a line or two here to explain why someone might want to add IBM z/VM as agents.

2024-06-13 18:49 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +== Adding IBM z/VM as Agents
```suggestion
== Adding IBM z/VM as agents
```
Revising "Agents" to be lowercase, for reasons mentioned in earlier comments.

2024-06-13 18:49 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
>  *Note:*  If you want to use a static IP for z/VM guest, you must configure the `NMStateConfig` attribute for the z/VM agent so that the IP parameter persists in the second boot.
```suggestion
**Note:**  If you want to use a static IP for z/VM guest, you must configure the `NMStateConfig` attribute for the z/VM agent so that the IP parameter persists in the second boot.
```
From IBM Style: "Although _boot_ is widely recognized among technical users, where usage permits use _start_ or _turn on_."

2024-06-13 18:49 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +zfcp.allow_lun_scan=0 \
```suggestion
zfcp.allow_lun_scan=0 \  <1>
```

2024-06-13 18:49 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +rd.<disk_type>=<storage> random.trust_cpu=on \
```suggestion
rd.<disk_type>=<storage> random.trust_cpu=on \  <2>
```

2024-06-13 18:49 UTC, lahinson commented on clusters/hosted_control_planes/scale_nodepool_hosted_ibmz.adoc
> +After scaling the nodepool to 0 , the compute nodes will get detached from the hosted cluster. If the computed nodes are not detached from the hosted cluster or stuck in `Notready` state, delete the
```suggestion
After you scale the node pool to 0, the compute nodes are detached from the hosted cluster. If the compute nodes are not detached from the hosted cluster or remain in a `Notready` state, manually delete the compute nodes by running the following command: 
```

2024-06-13 18:49 UTC, lahinson commented on clusters/hosted_control_planes/scale_nodepool_hosted_ibmz.adoc
> +. Run the following command to scale the `NodePool` object to zero (0) nodes:
```suggestion
. Run the following command to scale the `NodePool` object to 0 nodes:
```

2024-06-13 18:49 UTC, lahinson commented on clusters/hosted_control_planes/scale_nodepool_hosted_ibmz.adoc
> +oc -n ${clusters_namespace} scale nodepool ${nodepool_name} --replicas 0
Be sure to format user-replaced variables correctly. Are `${clusters_namespace}` and ${nodepool_name}` supposed to be XML? You can see guidance about how to format user-replaced values in the Red Hat supplementary style guide: https://redhat-documentation.github.io/supplementary-style-guide/#user-replaced-values-xml

2024-06-13 18:49 UTC, lahinson commented on clusters/hosted_control_planes/scale_nodepool_hosted_ibmz.adoc
> +oc --kubeconfig ${hosted_clusted_name}.kubeconfig delete node <comopute_node_name>
See previous comment about user-replaced variables.

2024-06-13 18:49 UTC, lahinson commented on clusters/hosted_control_planes/scale_nodepool_hosted_ibmz.adoc
> +. Verify the compute nodes status by entering the following command:
```suggestion
. Verify the status of the compute nodes by entering the following command:
```

2024-06-13 18:49 UTC, lahinson commented on clusters/hosted_control_planes/scale_nodepool_hosted_ibmz.adoc
> +. Delete the agents from the cluster
```suggestion

```

2024-06-13 18:49 UTC, lahinson commented on clusters/hosted_control_planes/scale_nodepool_hosted_ibmz.adoc
> +oc -n ${hosted_control_plane_namespace} delete agent <agent_name>
See previous comment about user-replaced variables.

2024-06-13 18:49 UTC, lahinson commented on clusters/hosted_control_planes/scale_nodepool_hosted_ibmz.adoc
> +
```suggestion
+
After the compute nodes are detached from the hosted cluster, the status of the agents changes to `auto-assign`.
```

2024-06-13 18:49 UTC, lahinson commented on clusters/hosted_control_planes/scale_nodepool_hosted_ibmz.adoc
> +After the compute nodes are detached from the hosted cluster, the status of the agents is changed to `auto-assign`.
```suggestion

```

2024-06-13 18:49 UTC, lahinson commented on clusters/hosted_control_planes/scale_nodepool_hosted_ibmz.adoc
> ++
```suggestion

```

2024-06-13 18:49 UTC, lahinson commented on clusters/hosted_control_planes/scale_nodepool_hosted_ibmz.adoc
> +Delete the agents from the cluster by running the following command:
```suggestion
. Delete the agents from the cluster by running the following command:
```

2024-06-13 18:49 UTC, lahinson commented on clusters/hosted_control_planes/scale_nodepool_hosted_ibmz.adoc
> +**Note:** You can delete the Virtual Machines that you created as agents after deleting the agents from the cluster.
```suggestion
**Note:** You can delete the virtual machines that you created as agents after you delete the agents from the cluster.
```

2024-06-13 18:49 UTC, lahinson commented on clusters/hosted_control_planes/scale_nodepool_hosted_ibmz.adoc
> +. Destroy the hosted control plane.
```suggestion

```

2024-06-13 18:49 UTC, lahinson commented on clusters/hosted_control_planes/scale_nodepool_hosted_ibmz.adoc
> ++
```suggestion

```

2024-06-13 18:49 UTC, lahinson commented on clusters/hosted_control_planes/scale_nodepool_hosted_ibmz.adoc
> +Run the following command using the hypershift command-line to destroy the hosted control plane:
```suggestion
. Run the following command to destroy the hosted control plane:
```
The hypershift CLI is not supported in the official documentation. Do you mean the hosted control planes `hcp` command line interface?

2024-06-13 18:49 UTC, lahinson commented on clusters/hosted_control_planes/scale_nodepool_hosted_ibmz.adoc
> +hcp destroy cluster agent --name ${hosted_cluster_name} --namespace ${clusters_namepsace}
See earlier comment about properly formatting user-replaced variables.

2024-06-27 06:52 UTC, krishnanshruthi commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +. Create a boot parameter file for the agents.
@veera-damisetti As i had suggested earlier, do we need to add details such as 'Create a .txt file' and save it in <> location? Pls suggest

2024-06-27 07:01 UTC, veera-damisetti commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +. Create a boot parameter file for the agents.
The user can save any where. lets say ( generic.prm ) 
as the parmfile and boot artifacts will be sent to FTP server later on

2024-06-27 07:07 UTC, krishnanshruthi commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +.. Run the following commands to get the size of the kernel and initrd.
Checked with @veera-damisetti at the time of drafting content,, this should be a sub-step.

2024-06-27 07:12 UTC, veera-damisetti commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +[source,yaml]
In this case, better to keep cat > generic.ins <<EOF and EOF , as this helps to creates the file with the variables populated

2024-06-27 14:02 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +[source,yaml]
Understood. However, in the official documentation, we rewrite code blocks like this to be clearer. If we keep the code as it is, this PR will not pass the required peer review for quality. In cases like this, we usually rewrite the procedure to something like this:
1. Create a YAML file that contains the following content...
2. Save the file...
3. Apply the configuration from the YAML file by entering the following command...

You can see an example in the bare metal docs: https://github.com/stolostron/rhacm-docs/blob/2.11_stage/clusters/hosted_control_planes/handle_ingress_bm.adoc

2024-06-28 07:06 UTC, veera-damisetti commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +[source,yaml]
oh okay or else we can use the way you are saying earlier .
remove cat and EOF statements 
and we can mention file content as 

$KERNEL_IMG_PATH $KERNEL_OFFSET
$INITRD_IMG_PATH $OFFSET_HEX
$INITRD_IMG_NAME.addrsize $INITRD_ADDR_SIZE_OFFSET
$CMDLINE_PATH $KERNEL_CMDLINE_OFFSET

2024-06-28 14:14 UTC, lahinson reviewed
@krishnanshruthi Thanks so much for all your work to provide quality content here! I had a few more suggestions, and then I think this will be ready to move forward.

2024-06-28 14:14 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +To attach Compute nodes to hosted control plane, you must create agents that will help you to scale the node pool. Adding agents in an IBM Z environment requires additional steps, which are described
```suggestion
To attach compute nodes to a hosted control plane, you create agents that help you to scale the node pool. Adding agents in an IBM Z environment requires additional steps, which are described in detail in this section. 
```
A couple minor revisions here to comply with IBM Style.

2024-06-28 14:14 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +<2> Specify the location where the `kernel_initrd_image` file is present.
```suggestion
<2> Specify the location of the `kernel_initrd_image` file.
```

2024-06-28 14:14 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +<3> Specify the disk image path
```suggestion
<3> Specify the disk image path.
```

2024-06-28 14:14 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +<4> Specify the Mac address
```suggestion
<4> Specify the MAC address.
```

2024-06-28 14:14 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +<2> Specify the name of the Mac address.
```suggestion
<2> Specify the MAC address.
```

2024-06-28 14:14 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +{ocp-short} 4.16 allows you to add the Logical Partition (LPAR) on IBM Z or IBM LinuxONE as a **Compute node** to a hosted control plane.
```suggestion
With {ocp-short} 4.16, you can add the Logical Partition (LPAR) on IBM Z or IBM LinuxONE as a compute node to a hosted control plane.
```
Revised to comply with IBM Style guidelines.

2024-06-28 14:14 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +=== Procedure
```suggestion

```
The ACM documentation does not use the Procedure heading.

2024-06-28 14:14 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +.. Create the kernel binary patch file holding the initrd address and size.
Please review the suggested revision, which updates the text to comply with IBM Style guidance.

2024-06-28 14:14 UTC, lahinson commented on clusters/hosted_control_planes/destroying-hosted-clusted-x86bm-ibmz.adoc
> +After scaling the nodepool to 0 , the compute nodes will get detached from the hosted cluster. If the computed nodes are not detached from the hosted cluster or stuck in `Notready` state, delete the
```suggestion
After the node pool is scaled to 0, the compute nodes are detached from the hosted cluster. If the compute nodes are not detached from the hosted cluster or are stuck in the `Notready` state, delete the compute nodes manually by running the following command: 
```

2024-06-28 14:14 UTC, lahinson commented on clusters/hosted_control_planes/destroying-hosted-clusted-x86bm-ibmz.adoc
> +Run the following command using the `hcp` command-line to destroy the hosted control plane:
```suggestion
Run the following command by using the `hcp` command-line to destroy the hosted control plane:
```

2024-06-28 14:14 UTC, lahinson commented on clusters/hosted_control_planes/scale_nodepool_hosted_ibmpower.adoc
> +To scale down the data plane to zero, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.15/html//hosted_control_planes/troubleshooting-hosted-control-planes#scale-
```suggestion
To scale down the data plane to zero, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.15/html/hosted_control_planes/troubleshooting-hosted-control-planes#scale-down-data-plane_hcp-troubleshooting[Scaling down the data plane to zero].
```

2024-07-01 09:47 UTC, krishnanshruthi commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +[source,yaml]
@lahinson There are not variables now, as this snippet is converted to source, bash.

2024-07-01 14:25 UTC, SNiemann15 reviewed
LGTM

2024-07-01 15:51 UTC, lahinson reviewed
@krishnanshruthi Thanks for all your work on this! I reviewed the latest updates and had a few more suggestions to ensure this passes peer review with the RHACM doc team.

2024-07-01 15:51 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +<1> For the `coreos.live.rootfs_url` artifact, specify the matching `rootfs` artifact for the `kernel` and `initramfs` that you are booting. Only HTTP and HTTPS protocols are supported.
```suggestion
<1> For the `coreos.live.rootfs_url` artifact, specify the matching `rootfs` artifact for the `kernel` and `initramfs` that you are starting. Only HTTP and HTTPS protocols are supported.
```
From IBM Style: "Although _boot_ is widely recognized among technical users, where usage permits use _start_ or _turn on_."

2024-07-01 15:51 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +<2> For the `ip` parameter, assign manually assign the IP address, as described in "Installing a cluster with z/VM on {ibm-z-name} and {ibm-linuxone-name}".
```suggestion
<2> For the `ip` parameter, manually assign the IP address, as described in _Installing a cluster with z/VM on IBM Z and IBM LinuxONE_.
```
The RHACM docs repo does not contain attributes for IBM Z and IBM LinuxONE.

2024-07-01 15:51 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +<3> For installations on DASD-type disks, use `rd.dasd` to specify the DASD where {op-system-first} is to be installed. For installations on FCP-type disks, use `rd.zfcp=<adapter>,<wwpn>,<lun>` to sp
The RHACM repo does not contain the `{op-system-first}` or the `{op-system}` attributes. 
```suggestion
<3> For installations on DASD-type disks, use `rd.dasd` to specify the DASD where Red Hat Enterprise Linux CoreOS (RHCOS) is to be installed. For installations on FCP-type disks, use `rd.zfcp=<adapter>,<wwpn>,<lun>` to specify the FCP disk where RHCOS is to be installed.
```

2024-07-01 15:51 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +<4> Specify this parameter when using an OSA network adapter or Hipersockets.
```suggestion
<4> Specify this parameter when you use an Open Systems Adapter (OSA) or HiperSockets.
```

2024-07-01 15:51 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +The .ins file is a special file that includes installation data and is present on the FTP server. It can be accessed from the HMC system.
```suggestion
The `.ins` file includes installation data and is present on the FTP server. It can be accessed from the HMC system.
```

2024-07-01 15:51 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +**Note**: In {ocp-short} 4.16, the .ins file and 'initrd.img.addrsize' are not automatically generated as part of boot-artifacts from the installer. You must generate these files manually.
```suggestion
*Note*: In {ocp-short} 4.16, the `.ins` file and 'initrd.img.addrsize' are not automatically generated as part of boot-artifacts from the installer. You must manually generate these files.
```

2024-07-01 15:51 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +.. Run the following commands to get the size of the kernel and initrd.
```suggestion
.. Run the following commands to get the size of the `kernel` and `initrd`:
```

2024-07-01 15:51 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +.. Round the kernel size up to the next MiB boundary. This will be the starting address of initrd.img.
```suggestion
.. Round the `kernel` size up to the next MiB boundary. This value is the starting address of `initrd.img`.
```
A couple small revisions to comply with IBM Style (making pronouns clear, using present tense instead of future tense).

2024-07-01 15:51 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +.. Create the kernel binary patch file holding the `initrd` address and size by running the following commands:
```suggestion
.. Create the kernel binary patch file that contains the `initrd` address and size by running the following commands:
```

2024-07-01 15:51 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +.. Convert address and size to binary format by running the following commands:
```suggestion
.. Convert the address and size to binary format by running the following commands:
```

2024-07-01 15:51 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +printf "$(printf '%016x\n' $initrd_size)" | xxd -r -p > temp_size.bin
```suggestion

```

2024-07-01 15:51 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
```suggestion
+
[source,bash]
----
printf "$(printf '%016x\n' $initrd_size)" | xxd -r -p > temp_size.bin
----
```

2024-07-01 15:51 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> ++
Per documentation guidelines, do not include more than one command in a code block. I revised lines 123 - 132 below to split the two commands into two separate code blocks.

2024-07-01 15:51 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +.. Concatenate address and size binaries
```suggestion
.. Concatenate the address and size binaries by running the following command:
```

2024-07-01 15:51 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +.. Clean up temporary files
```suggestion
.. Clean up temporary files by running the following command:
```

2024-07-01 15:51 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +.. Create the .ins file based on the paths of these files (kernel.img, initrd.img , initrd.img.addrsize, cmdline) and the memory locations where the data is to be copied.
```suggestion
.. Create the `.ins` file. The file is based on the paths of the `kernel.img`, `initrd.img`, `initrd.img.addrsize`, and `cmdline` files and the memory locations where the data is to be copied.
```

2024-07-01 15:51 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +. Transfer the `initrd`, `kernel`, `generic.ins` and the `initrd.img.addrsize` parameter files* to the File server. For details on how to transfer the files with FTP and boot, see link:https://access
```suggestion
. Transfer the `initrd`, `kernel`, `generic.ins`, and `initrd.img.addrsize` parameter files to the File server. For more information about how to transfer the files with FTP and boot, see link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/performing_a_standard_rhel_8_installation/installing-in-an-lpar_installing-rhel[Installing in an LPAR].    
```
In this step, is "File" the name of the server, or is this more of a reference to a generic file server? If it's the latter, make "File" lowercase.

2024-07-01 15:51 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +If you want to use a static IP for z/VM guest, you must configure the `NMStateConfig` attribute for the z/VM agent so that the IP parameter persists in the second boot.
```suggestion
If you want to use a static IP for z/VM guest, you must configure the `NMStateConfig` attribute for the z/VM agent so that the IP parameter persists in the second start.
```
Per IBM Style, replace _boot_ with _start_ or _turn on_.

2024-07-01 15:51 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +<1> For the `coreos.live.rootfs_url` artifact, specify the matching `rootfs` artifact for the `kernel` and `initramfs` that you are booting. Only HTTP and HTTPS protocols are supported.
```suggestion
<1> For the `coreos.live.rootfs_url` artifact, specify the matching `rootfs` artifact for the `kernel` and `initramfs` that you are starting. Only HTTP and HTTPS protocols are supported.
```

2024-07-01 15:51 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +<2> For the `ip` parameter, assign manually assign the IP address, as described in "Installing a cluster with z/VM on {ibm-z-name} and {ibm-linuxone-name}".
```suggestion
<2> For the `ip` parameter, manually assign the IP address, as described in _Installing a cluster with z/VM on IBM Z and IBM LinuxONE_.
```

2024-07-01 15:51 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +<3> For installations on DASD-type disks, use `rd.dasd` to specify the DASD where {op-system-first} is to be installed. For installations on FCP-type disks, use `rd.zfcp=<adapter>,<wwpn>,<lun>` to sp
```suggestion
<3> For installations on DASD-type disks, use `rd.dasd` to specify the DASD where Red Hat Enterprise Linux CoreOS (RHCOS) is to be installed. For installations on FCP-type disks, use `rd.zfcp=<adapter>,<wwpn>,<lun>` to specify the FCP disk where RHCOS is to be installed.
```

2024-07-01 15:51 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +<4> Specify this parameter when using an OSA network adapter or Hipersockets.
```suggestion
<4> Specify this parameter when you use an Open Systems Adapter (OSA) or HiperSockets.
```

2024-07-01 15:51 UTC, lahinson commented on clusters/hosted_control_planes/destroying-hosted-clusted-x86bm-ibmz.adoc
> +oc -n ${clusters_namespace} scale nodepool ${nodepool_name} --replicas 0
```suggestion
oc -n <clusters_namespace> scale nodepool <nodepool_name> --replicas 0
```

2024-07-01 15:51 UTC, lahinson commented on clusters/hosted_control_planes/destroying-hosted-clusted-x86bm-ibmz.adoc
> +oc --kubeconfig ${hosted_clusted_name}.kubeconfig delete node <comopute_node_name>
```suggestion
oc --kubeconfig <hosted_clusted_name>.kubeconfig delete node <comopute_node_name>
```

2024-07-01 15:51 UTC, lahinson commented on clusters/hosted_control_planes/destroying-hosted-clusted-x86bm-ibmz.adoc
> +. Delete the agents from the cluster
```suggestion
. Delete the agents from the cluster by running the following command:
```

2024-07-01 15:51 UTC, lahinson commented on clusters/hosted_control_planes/destroying-hosted-clusted-x86bm-ibmz.adoc
> +
```suggestion
After the compute nodes are detached from the hosted cluster, the status of the agents is changed to `auto-assign`.
```
Move this line up from line 34.

2024-07-01 15:51 UTC, lahinson commented on clusters/hosted_control_planes/destroying-hosted-clusted-x86bm-ibmz.adoc
> +Delete the agents from the cluster by running the following command:
```suggestion

```

2024-07-01 15:51 UTC, lahinson commented on clusters/hosted_control_planes/destroying-hosted-clusted-x86bm-ibmz.adoc
> +After the compute nodes are detached from the hosted cluster, the status of the agents is changed to `auto-assign`.
```suggestion

```

2024-07-01 15:51 UTC, lahinson commented on clusters/hosted_control_planes/destroying-hosted-clusted-x86bm-ibmz.adoc
> +oc -n ${hosted_control_plane_namespace} delete agent <agent_name>
```suggestion
oc -n <hosted_control_plane_namespace> delete agent <agent_name>
```

2024-07-01 15:51 UTC, lahinson commented on clusters/hosted_control_planes/destroying-hosted-clusted-x86bm-ibmz.adoc
> +**Note:** You can delete the virtual machines that you created as agents after you delete the agents from the cluster.
```suggestion
*Note:* You can delete the virtual machines that you created as agents after you delete the agents from the cluster.
```

2024-07-01 15:51 UTC, lahinson commented on clusters/hosted_control_planes/destroying-hosted-clusted-x86bm-ibmz.adoc
> +. Destroy the hosted control plane.
```suggestion

```

2024-07-01 15:51 UTC, lahinson commented on clusters/hosted_control_planes/destroying-hosted-clusted-x86bm-ibmz.adoc
> +hcp destroy cluster agent --name ${hosted_cluster_name} --namespace ${clusters_namepsace}
```suggestion
hcp destroy cluster agent --name <hosted_cluster_name> --namespace <clusters_namepsace>
```

2024-07-01 15:51 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +<4> Specify the Operating system version that you are using.
```suggestion
<4> Specify the operating system version that you are using.
```

2024-07-01 18:24 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +To attach compute nodes to a hosted control plane, create agents that will help you to scale the node pool. Adding agents in an IBM Z environment requires additional steps, which are described in det
```suggestion
To attach compute nodes to a hosted control plane, create agents that help you to scale the node pool. Adding agents in an IBM Z environment requires additional steps, which are described in detail in this section. 
```
Removing future tense, per IBM Style.

2024-07-01 18:26 UTC, lahinson commented on clusters/hosted_control_planes/destroying-hosted-clusted-x86bm-ibmz.adoc
> += Destroying a hosted cluster on `x86` bare metal with IBM Z compute nodes
```suggestion
= Destroying a hosted cluster on x86 bare metal with IBM Z compute nodes
```
Do not use monospace formatting in titles and headings.

2024-07-02 18:33 UTC, swopebe commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +[source,yaml]
@lahinson yes the formatting is off around this line, likely due to spacing issue.

2024-07-02 18:34 UTC, swopebe commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +This file contains details such as mapping of the location of installation data on the disk or FTP server, the memory locations where the data is to be copied.
@lahinson recommend we remove self-referential "This file contains" -- this is wordy and against IBM style manual.

2024-07-02 18:35 UTC, swopebe commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +*Note*: In {ocp-short} 4.16, the .ins file and 'initrd.img.addrsize' are not automatically generated as part of boot-artifacts from the installer. You must manually generate these files.
.ins needs to be tagged, as all references to files do.

2024-07-02 18:35 UTC, swopebe commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +.. Concatenate the address and size binaries by running the following command:
Concatenate? Wonder if there is a better word for this step.

2024-07-02 18:36 UTC, swopebe commented on .vscode/settings.json
> +}
@lahinson this is the error^^

2024-07-02 18:45 UTC, swopebe commented
@lahinson asked me to do a glance-over. 

These files do need some work; I made a couple comments to carry over and I am recommending with her t**hat we merge this and start new with clean up,** (though please look at the `.json` error that has need entered, as it is impacting our linter at times).


All of IBM and RH uses the [IBM Style Guide for writing.](https://www.ibm.com/docs/en/ibm-style). We all have access; IBM ID teams should be using these, as well--I relied on it heavily as an IBMer, though I know not all teams are this vigilant. 

We follow those standards, as well as accessibility and globalization standards, and ensuring the doc comes from "one voice." The feedback and requests for improvements largely surround general tech writing standards. The more the PRs align with the IBM Style Manual, the faster the reviews.

If there are no writers familiar with these standards, it may be best to give the RH writers a draft outside of a PR in the future so we can build the content a little easier. It can be very hard to edit and format large PRs.

2024-07-02 18:51 UTC, swopebe approved these changes
Approving with conditional requirement for continued clean up before July 9th deadline.

2024-07-02 18:59 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +*Note*: In {ocp-short} 4.16, the .ins file and 'initrd.img.addrsize' are not automatically generated as part of boot-artifacts from the installer. You must manually generate these files.
Will fix in a general review of formatting after this PR is merged.

2024-07-02 18:59 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +[source,yaml]
Will fix in a general review of formatting after this PR is merged.

2024-07-02 19:00 UTC, lahinson commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +.. Concatenate the address and size binaries by running the following command:
Maybe "combine"?

2024-07-02 19:17 UTC, lahinson approved these changes
I will approve and merge, under the condition that I will address @swopebe's feedback in a separate PR. Thank you for all of your work to contribute these docs, @krishnanshruthi !

2024-07-02 19:19 UTC, merged

2024-07-03 12:39 UTC, SNiemann15 commented on clusters/hosted_control_planes/add_agents_ibmz.adoc
> +.. Concatenate the address and size binaries by running the following command:
How about "merge". I think that's what it does merge the contents of the two files.