moved iam policy to deprecate and remove api doc
open-cluster-management/rhacm-docs pull request #6501
Opened 2024-06-05 18:12 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-11650

2024-06-05 19:15 UTC, dockerymick commented on release_notes/deprecate_remove.adoc
> +[#iam-policy-controller]
Reminder delete the iam_policy_ctrl.adoc file, remove IAM Policy from the deprecated table, and add the row to the Removals table. Also complete a Find and search in VSC to see where IAM policy is mentioned. During our huddle, we discovered there were mentions in the hosted_cluster and observability folder.

2024-06-05 20:03 UTC, swopebe commented on release_notes/deprecate_remove.adoc
a little confused here, we deprecated in 2.9, so we cannot say we removed in 2.9. Are we trying to say we are removing in 2.11, from a previous deprecation? (I think that is the intention)

2024-06-05 20:03 UTC, swopebe requested changes
I think we mean 2.11 (?)

2024-06-05 20:53 UTC, swopebe commented on release_notes/deprecate_remove.adoc
> +[#iam-policy-controller]
Be sure to pull in developers from those areas so they know we are removing IAM from that section, unless they are already aware from the Issue.

2024-06-05 20:55 UTC, swopebe commented on release_notes/deprecate_remove.adoc
> +[#iam-policy-controller]
Typically these removals can be done in multiple PRs; I would handle the release note in one PR and the doc removals/build changes, or it can get overwhelming with reviews and links and such.

2024-06-06 16:05 UTC, dockerymick commented on release_notes/deprecate_remove.adoc
> +| 2.9
```suggestion
| 2.11
```

2024-06-06 18:28 UTC, dockerymick approved these changes

2024-06-07 14:54 UTC, mprahl approved these changes

2024-06-07 16:54 UTC, dockerymick approved these changes

2024-06-10 17:31 UTC, merged