added info about oadp
open-cluster-management/rhacm-docs pull request #6502
Opened 2024-06-05 18:31 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-11618

2024-06-05 18:32 UTC, jc-berger commented on business_continuity/backup_restore/backup_install.adoc
> +When the cluster is in the STS mode, the backup chart creates a ConfigMap named `acm-redhat-oadp-operator-subscription` under the `open-cluster-management-backup`. This ConfigMap also contains the OA
Am I correct that it's the Config map that contains the OADP channel and environment information? Or does the `open-cluster-management-backup` contain this info?

2024-06-05 18:48 UTC, birsanv approved these changes
lgtm

2024-06-12 20:44 UTC, dockerymick requested changes

2024-06-12 20:44 UTC, dockerymick commented on business_continuity/backup_restore/backup_install.adoc
> +When the cluster is in the STS mode, the backup chart creates a ConfigMap named `acm-redhat-oadp-operator-subscription` under the `open-cluster-management-backup`. This ConfigMap also contains the OA
```suggestion
When the cluster is in the STS mode, the backup chart creates a config map named `acm-redhat-oadp-operator-subscription` in the `open-cluster-management-backup` namespace. This config map also contains the OADP channel and environment information. Use this config map to get the OADP version that you need to install and to get any environment options to be set on the OADP subscription.
```

2024-06-14 15:11 UTC, merged