added known issue for observability
open-cluster-management/rhacm-docs pull request #6503
Opened 2024-06-05 19:31 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-11048

2024-06-06 09:46 UTC, douglascamata requested changes
I think we should improve a little bit the first paragraph, it's not super easy to understand what's happening.

2024-06-06 09:46 UTC, douglascamata commented on release_notes/known_issues_observability.adoc
> +For {product-title-short} 2.11, the down sampling levels has a default retention of 365 days (365d). This 365d default retention means there is now a 1 hour resolution retention, but earlier, the res
"downsampling" is a single word and should not be separated.

I think we can reframe this sentence become easier to understand. Here's an idea:

```suggestion
For {product-title-short} 2.11, the default retention for all resolution levels (raw, 5 minutes, 1 hour) is being updated to  365 days (365d). This effective means that the default retention for 1 hour resolution has been decreased from "indefinite" (0d) to 365 days. If you did not set an explicit value for the resolution retention in your `MultiClusterObservability` `spec.advanced.retentionConfig`, then this new default retention applies to you.
```

2024-06-06 17:23 UTC, douglascamata approved these changes
/lgtm

2024-06-06 20:26 UTC, dockerymick requested changes

2024-06-06 20:26 UTC, dockerymick commented on release_notes/known_issues_observability.adoc
> +== Default retention is 365 days
It is not clear to me what the issue is. Do error messages appear bc the default retention is 365? Do users lose data  bc the retention duration changed?

2024-06-06 20:26 UTC, dockerymick commented on release_notes/known_issues_observability.adoc
> +For {product-title-short} 2.11, the default retention for all resolution levels, such as `raw,` 5 minutes, or 1 hour, is updated to 365 days (365d). This 365d default retention means that the the def
If the user does not explicitly define the value, what happens? Does the user lose the retention configuration? Is the configuration automatically deleted? I'm confused when you say "this new default retention", is this an enhancement or known issue? 
```suggestion
For {product-title-short} 2.11, the default retention for all resolution levels, such as `raw,` 5 minutes, or 1 hour, is updated to 365 days (365d). This 365d default retention means that the the default retention for a 1 hour resolution has been decreased from `indefinite` (`0d`) to `365d`. If you did not set an explicit value for the resolution retention in your `MultiClusterObservability` `spec.advanced.retentionConfig` parameter, then this new default retention applies to you.
```

2024-06-06 20:26 UTC, dockerymick commented on release_notes/known_issues_observability.adoc
> +If you upgraded from an earlier version and want to keep that version's retention configuration, complete the following steps:
Remove possessive here

2024-06-06 20:26 UTC, dockerymick commented on release_notes/known_issues_observability.adoc
> +. Go to your `MultiClusterObservability` resource.
How does the user get to this resource?

2024-06-07 09:19 UTC, douglascamata commented on release_notes/known_issues_observability.adoc
> +== Default retention is 365 days
There shouldn't be error messages. 

Customers might lose data because of the retention change.

2024-06-07 09:22 UTC, douglascamata commented on release_notes/known_issues_observability.adoc
> +For {product-title-short} 2.11, the default retention for all resolution levels, such as `raw,` 5 minutes, or 1 hour, is updated to 365 days (365d). This 365d default retention means that the the def
If the user doesn't specify a value, the default applies. The default retention for the 1 hour resolution is changing. Previously it was indefinite (`0d`), now it will be 365 days (`365d`).

2024-06-07 15:13 UTC, dockerymick commented on release_notes/known_issues_observability.adoc
> +== Default retention is 365 days
Thanks for confirming @douglascamata I recommend that we mention data loss in the title

2024-06-10 17:49 UTC, jc-berger commented on release_notes/known_issues_observability.adoc
> +. Go to your application `MultiClusterObservability` resource.
Not sure exactly how the user gets to the resource. Does it help that I specify the resource within the application? 

@douglascamata is this correct what I have documented in this step? Is there a specific way we can direct users to access the `MultiClusterObservability` resource?

2024-06-11 14:46 UTC, dockerymick commented
I took a look at the issue and the request is to add information to Customizing observability configuration. The issue doesn't mention it as a known issue. I am confused here. It seems like the configuration update should be made to the topic, [Adding advanced configuration for retention](https://github.com/stolostron/rhacm-docs/blob/2.11_stage/observability/customize_observability.adoc#adding-advanced-config)

2024-06-11 18:48 UTC, douglascamata commented on release_notes/known_issues_observability.adoc
> +. Go to your application `MultiClusterObservability` resource.
@jc-berger I think navigating through the UI to get to it is slightly cumbersome:

- Click on Home
- Click on API Explorer
- Search for "MultiClusterObservability", then click on it.
- Finally, click on the Instances tab and open the single instance that should exist. 

So maybe it's fine if we recommend people to use the command line? It's doable with the `oc` binary tool: `oc edit mco observability`.

2024-06-11 19:03 UTC, douglascamata approved these changes

2024-06-11 19:09 UTC, dockerymick requested changes

2024-06-11 19:09 UTC, dockerymick commented on observability/customize_observability.adoc
> +For {product-title-short} 2.11, the default retention for all resolution levels, such as `raw,` 5 minutes, or 1 hour, is updated to 365 days (365d). This 365d default retention means that the default
I recommend that you remove this subsection. Based on the explanation, it seems like the parameter values in the sample (line 207) should have the value, `365d`. Also that you move the following statement to line 196: "The default retention for all resolution levels, such as `retentionResolutionRaw,` retentionResolution5m`, or `retentionResolution1h` is 365 days (`365d`).  

At first I didn't understand where `raw`, 5 minutes, and 1 hour came from. For consistency, let's use the entire parameter name. We typically do not mention the version either.

```suggestion
The default retention for all resolution levels, such as `retentionResolutionRaw,` retentionResolution5m`, or `retentionResolution1h`, is 365 days (365d). You must set an explicit value for the resolution retention in your `MultiClusterObservability` `spec.advanced.retentionConfig` parameter.
```

2024-06-11 19:09 UTC, dockerymick commented on observability/customize_observability.adoc
> +. Go to your application `MultiClusterObservability` resource.
I think the user is able to simply search for the resource from the ACM console and then update it. @douglascamata please confirm

2024-06-12 20:21 UTC, dockerymick commented on release_notes/known_issues_observability.adoc
> +. Go to your application `MultiClusterObservability` resource.
@douglascamata I took a look at the ACM Console and do not see the API Explorer. Are you referring to OCP?

2024-06-12 20:39 UTC, dockerymick requested changes

2024-06-12 20:39 UTC, dockerymick commented on observability/customize_observability.adoc
> +=== Keeping retention configuration
```suggestion
```

2024-06-12 20:39 UTC, dockerymick commented on observability/customize_observability.adoc
> +The default retention for all resolution levels, such as `retentionResolutionRaw,` retentionResolution5m`, or `retentionResolution1h`, is 365 days (365d). You must set an explicit value for the resol
```suggestion
The default retention for all resolution levels, such as `retentionResolutionRaw`, `retentionResolution5m`, or `retentionResolution1h`, is 365 days (`365d`). You must set an explicit value for the resolution retention in your `MultiClusterObservability` `spec.advanced.retentionConfig` parameter.
```

2024-06-12 20:39 UTC, dockerymick commented on observability/customize_observability.adoc
> +The default retention for all resolution levels, such as `retentionResolutionRaw,` retentionResolution5m`, or `retentionResolution1h`, is 365 days (365d). You must set an explicit value for the resol
@douglascamata since the default is now `365d`, should the parameter values in the sample be changed to reflect that? @jc-berger I would move this info (lines 232-246) to line 224

2024-06-13 16:12 UTC, douglascamata approved these changes
/lgtm

2024-06-13 16:44 UTC, dockerymick approved these changes
Add updates for spacing and syntax. After committing this, it looks good to me!

2024-06-13 16:44 UTC, dockerymick commented on observability/customize_observability.adoc
> +----
```suggestion
. Go to your `MultiClusterObservability` resource by running the following `oc` binary in your CLI: 

+
[source,bash]
----
edit mco observability
----

. In the `spec.advanced.retentionConfig` parameter, apply the following configuration: 

+
[source,bash]
----
spec:
  advanced:
    retentionConfig:
      retentionResolutionRaw: 30d
      retentionResolution5m: 180d
      retentionResolution1h: 0d
----
```

2024-06-13 17:00 UTC, dockerymick commented on release_notes/known_issues_observability.adoc
> +For {product-title-short} 2.11, the default retention for all resolution levels, such as `raw,` 5 minutes, or 1 hour, is updated to 365 days (365d). This 365d default retention means that the default
Is the parameter value indefinite? if no, let's only monospace "0d"
```suggestion
For {product-title-short} 2.11, the default retention for all resolution levels, such as `raw,` 5 minutes, or 1 hour, is updated to 365 days (`365d`). This 365d default retention means that the default retention for a 1 hour resolution has decreased from indefinite (`0d`) to `365d`. This retention change might cause you to lose data. If you did not set an explicit value for the resolution retention in your `MultiClusterObservability` `spec.advanced.retentionConfig` parameter, then this new default retention applies to you, and you might lose data.  
```

2024-06-13 17:01 UTC, dockerymick commented on release_notes/known_issues_observability.adoc
> +For {product-title-short} 2.11, the default retention for all resolution levels, such as `raw,` 5 minutes, or 1 hour, is updated to 365 days (365d). This 365d default retention means that the default
My bad Jake, will you ensure that the resolution levels are presented correctly

2024-06-13 17:03 UTC, dockerymick reviewed
My apologies for the back and forth. A few more changes

2024-06-13 17:03 UTC, dockerymick commented on release_notes/known_issues_observability.adoc
> +For {product-title-short} 2.11, the default retention for all resolution levels, such as `raw,` 5 minutes, or 1 hour, is updated to 365 days (365d). This 365d default retention means that the default
```suggestion
The default retention for all resolution levels, such as `retentionResolutionRaw`, `retentionResolution5m`, or `retentionResolution1h`, is 365 days (`365d`). This 365d default retention means that the default retention for a 1 hour resolution has decreased from indefinite, `0d` to `365d`. This retention change might cause you to lose data. If you did not set an explicit value for the resolution retention in your `MultiClusterObservability` `spec.advanced.retentionConfig` parameter, you might lose data.  
```

2024-06-14 17:30 UTC, dockerymick approved these changes
Thank you!

2024-06-14 17:32 UTC, merged