https://issues.redhat.com/browse/ACM-11375
open-cluster-management/rhacm-docs pull request #6504
Opened 2024-06-05 20:22 UTC by dockerymick

2024-06-06 16:27 UTC, dockerymick reviewed
@JustinKuli will you help by addressing my comments

2024-06-06 16:27 UTC, dockerymick commented on governance/policy_operator.adoc
> +| Specifies whether the described operator should (use value "musthave") or should not (use value "mustnothave) be on the managed cluster.
```suggestion
| Specifies whether the operator should use `musthave` or not use `mustnothave` value on the managed cluster.
```

2024-06-06 16:27 UTC, dockerymick commented on governance/policy_operator.adoc
> +| Determines whether certain resource types should be kept or removed when enforcing an OperatorPolicy with `complianceType: mustnothave`; has no effect when `complianceType` is set to `musthave`. Th
There is already a row for subscriptions. I recommend that. we move the following statement to line 62: The subfields for `subscriptions`, and `clusterServiceVersions` can be set to either "Keep" or "Delete", and default to "Delete".

It also seems like we need to add another row for `customResourceDefinitions`

```suggestion
| Determines which resource types need to be kept or removed when you enforce an `OperatorPolicy` resource with `complianceType: mustnothave` defined. There is no effect when `complianceType` is set to `musthave`. The subfield for `operatorGroups` can be set to `Keep` or `DeleteIfUnused`. The default value is `DeleteIfUnused` which remove only the `OperatorGroup` resource if it is not used by any other operators. The subfields for `subscriptions`, and `clusterServiceVersions` can be set to either "Keep" or "Delete", and default to "Delete". The subfield for `customResourceDefinitions` can be set to "Keep" or "Delete", and defaults to "Keep". 
```

2024-06-06 16:27 UTC, dockerymick commented on governance/policy_operator.adoc
> +//still reviewing
```suggestion
```

2024-06-06 16:27 UTC, dockerymick commented on governance/policy_operator.adoc
> +//still reviewing
```suggestion
```

2024-06-06 17:29 UTC, JustinKuli commented on governance/policy_operator.adoc
> +| Specifies whether the described operator should (use value "musthave") or should not (use value "mustnothave) be on the managed cluster.
I think I phrased this confusingly when I first drafted it.
```suggestion
| Describes the desired state of the operator on the cluster. If set to `musthave`, the policy will have a violation if the operator is missing from the cluster. If set to `mustnothave`, the policy will have a violation if the operator is found on the cluster.
```
Or
```suggestion
| Specifies the desired state of the operator on the cluster. If set to `musthave`, the policy will only be Compliant if the operator is found. If set to `mustnothave`, the policy will be NonCompliant if the operator is found.
```

2024-06-06 17:29 UTC, JustinKuli commented on governance/policy_operator.adoc
> +| Determines whether certain resource types should be kept or removed when enforcing an OperatorPolicy with `complianceType: mustnothave`; has no effect when `complianceType` is set to `musthave`. Th
My thought was that each row in this table corresponds to a section of the resource definition (YAML). So the `subscriptions` part here is not the same as the `spec.subscription` section we already have a row for. Maybe this example helps:
```yaml
apiVersion: policy.open-cluster-management.io/v1beta1
kind: OperatorPolicy
metadata:
  name: oppol-mustnothave
spec:
  remediationAction: inform
  severity: medium
  complianceType: mustnothave
  subscription:
    channel: stable-3.10
    name: project-quay
    namespace: operator-policy-testns
  versions:
    - quay-operator.v3.10.0
  upgradeApproval: Automatic
  removalBehavior:
    operatorGroups: DeleteIfUnused
    subscriptions: Delete
    clusterServiceVersions: Delete
    customResourceDefinitions: Delete
```

Maybe it also helps to split the subfields as well:
```suggestion
a| Determines which resource types need to be kept or removed when you enforce an `OperatorPolicy` resource with `complianceType: mustnothave` defined. There is no effect when `complianceType` is set to `musthave`. 

- `operatorGroups` can be set to `Keep` or `DeleteIfUnused`. The default value is `DeleteIfUnusued` which only removes the `OperatorGroup` resource if it is not used by any other operators.
- `subscriptions` can be set to `Keep` or `Delete`. The default value is `Delete`.
- `clusterServiceVersions` can be set to `Keep` or `Delete`. The default value is `Delete`.
- `customResourceDefinitions` can be set to `Keep` or `Delete`. The default value is `Keep`. If you set this to `Delete`,  the `CustomResourceDefintion` resources on the managed cluster are removed and can cause data loss.
```

2024-06-11 18:42 UTC, dockerymick commented on governance/policy_operator.adoc
> +| Specifies whether the described operator should (use value "musthave") or should not (use value "mustnothave) be on the managed cluster.
```suggestion
| Specifies the desired state of the operator on the cluster. If set to `musthave`, the policy is compliant when the operator is found. If set to `mustnothave`, the policy becomes non-compliant when the operator is not found.
```

2024-06-11 19:14 UTC, dockerymick commented on governance/policy_operator.adoc
> +| Determines which resource types need to be kept or removed when you enforce an `OperatorPolicy` resource with `complianceType: mustnothave` defined. There is no effect when `complianceType` is set
```suggestion
a| Determines which resource types need to be kept or removed when you enforce an `OperatorPolicy` resource with `complianceType: mustnothave` defined. There is no effect when `complianceType` is set to `musthave`. 
- `operatorGroups` can be set to `Keep` or `DeleteIfUnused`. The default value is `DeleteIfUnusued` which only removes the `OperatorGroup` resource if it is not used by any other operators.
- `subscriptions` can be set to `Keep` or `Delete`. The default value is `Delete`.
- `clusterServiceVersions` can be set to `Keep` or `Delete`. The default value is `Delete`.
- `customResourceDefinitions` can be set to `Keep` or `Delete`. The default value is `Keep`. If you set this to `Delete`,  the `CustomResourceDefintion` resources on the managed cluster are removed and can cause data loss.
```

2024-06-11 19:16 UTC, dockerymick commented
@JustinKuli thanks for your patience. I have made some edits based on your feedback. When you have an opportunity, let me know your thoughts

2024-06-11 21:09 UTC, JustinKuli requested changes
Just one thing, but the rest looks good to me!

2024-06-11 21:09 UTC, JustinKuli commented on governance/policy_operator.adoc
> +| Specifies the desired state of the operator on the cluster. If set to `musthave`, the policy is compliant when the operator is found. If set to `mustnothave`, the policy becomes non-compliant when
I think we have an accidental double negation here, so either
```suggestion
| Specifies the desired state of the operator on the cluster. If set to `musthave`, the policy is compliant when the operator is found. If set to `mustnothave`, the policy becomes non-compliant when the operator is found.
```
Or
```suggestion
| Specifies the desired state of the operator on the cluster. If set to `musthave`, the policy is compliant when the operator is found. If set to `mustnothave`, the policy is compliant when the operator is not found.
```

2024-06-12 16:56 UTC, JustinKuli approved these changes

2024-06-13 15:16 UTC, jc-berger approved these changes
/lgtm

2024-06-13 15:19 UTC, merged