[ACM-12000] Updated uninstall topic for MCH
open-cluster-management/rhacm-docs pull request #6515
Opened 2024-06-07 17:17 UTC by dislbenn

In ACM, when preparing to remove the MCH resources there is a prereq step that needs to be taken. This PR will add the missing step for the `AgentServiceConfig` resource that needs to be removed before MCH can be safely removed.

Related issue: https://issues.redhat.com/browse/ACM-12000
/cc @swopebe

2024-06-07 17:23 UTC, dislbenn commented
@swopebe would it be possible to cherry pick this PR into earlier release docs? This step is relevant for those releases as well.

2024-06-18 17:04 UTC, dislbenn commented
@swopebe @dockerymick any comments or concerns in regards to the changes for this PR?

2024-06-18 17:59 UTC, dockerymick commented
@dislbenn excuse the delay, I will review soon

2024-06-18 18:42 UTC, dockerymick requested changes

2024-06-18 18:42 UTC, dockerymick commented on install/uninstall.adoc
> +----
```suggestion
+
[source,bash]
----
```

2024-06-18 18:42 UTC, dockerymick commented on install/uninstall.adoc
> +* If you have agent service configs attached, you might see the following message.
```suggestion
* If you have agent service configs attached, you might see the following message:
```

2024-06-18 18:42 UTC, dockerymick commented on install/uninstall.adoc
> +- To disable and remove the `AgentServiceConfig` using the terminal, see the following procedure:
```suggestion
- To disable and remove the `AgentServiceConfig` from by using the command line interface, complete the following steps:
```

2024-06-18 18:42 UTC, dockerymick commented on install/uninstall.adoc
> +----
```suggestion
.. Delete the `AgentServiceConfig` custom resource by entering the following command:
+
[source,bash]
----
$ oc delete agentserviceconfig --all
----
```

2024-06-20 14:28 UTC, dockerymick requested changes
Thanks @dislbenn for accepting the previous suggestions. I left a few more

2024-06-20 14:28 UTC, dockerymick commented on install/uninstall.adoc
> +- To disable and remove the `AgentServiceConfig` from by using the command line interface, complete the following steps:
```suggestion
- To disable and remove the `AgentServiceConfig` resource by using the command line interface, complete the following steps:
```

2024-06-20 14:28 UTC, dockerymick commented on install/uninstall.adoc
> +* If you have agent service configs attached, you might see the following message:
```suggestion
* If you have agent service configurations attached, you might see the following message:
```

2024-06-20 16:15 UTC, dislbenn commented
Thanks @dockerymick for the review! I added the latest changes you've suggested.

2024-06-21 01:51 UTC, swopebe commented
Sorry I am just seeing this @dislbenn I have 140 git notifications to sift through lol, we can cherry pick but with many commits, it may be more difficult. I can copy and paste if needed. The issue is for fix version 2.11, so add if it needs to go to 2.9 and 2.10.

2024-06-21 17:33 UTC, dislbenn commented
@swopebe I updated the issue to reflect that it requires updates to 2.9 and 2.10.

2024-06-24 17:27 UTC, jc-berger commented on install/uninstall.adoc
> +.. Log in to your hub cluster.
Why are these sub-steps, (..) ? 

Shouldn't it be one bullet ( .) since it's steps 1 and 2?

2024-06-24 17:27 UTC, jc-berger approved these changes
/lgtm

2024-06-24 17:46 UTC, swopebe commented on install/uninstall.adoc
> +.. Log in to your hub cluster.
I will look at this, I didn't build the content, so there may be a reason or it could be oversight, but that is not on the engineer. This should come to me as the install writer. I have just been swamped. Let me look at the structure.

2024-06-24 17:50 UTC, swopebe commented on install/uninstall.adoc
> +.. Log in to your hub cluster.
@dockerymick @jc-berger this content could be built better and is missing key UX standards, like anchors and descriptions under headers. For the sake of the release, we now have to edit for accuracy. Since this was created before we implemented peer reviews, it just has not been updated. This can be considered tech debt for next release.

2024-06-24 17:51 UTC, swopebe approved these changes
The format here that was added is simply matching the one that already exists. Slated for better UX next release.

2024-06-24 19:42 UTC, dockerymick commented on install/uninstall.adoc
> +.. Log in to your hub cluster.
@jc-berger @swopebe thanks to you both for the review. I had not examined the entire file. I just made some format updates. I hope that helps with moving forward in the next refresh.

2024-06-24 19:45 UTC, merged