expanded observability note with config settings getting replaced
open-cluster-management/rhacm-docs pull request #6518
Opened 2024-06-10 18:05 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-11724

See earlier PR for expanded notes for observability: https://github.com/stolostron/rhacm-docs/pull/6002/files

2024-06-12 19:24 UTC, dockerymick requested changes

2024-06-12 19:24 UTC, dockerymick commented on observability/observability_enable.adoc
> +- When you import an {ocp-short} managed cluster into the hub cluster, {product-title-short} removes all the configuration settings in that {ocp-short} managed cluster `cluster-monitoring-config` con
Can we use something different from "passed down". Does the console take the action of replacing the configuration settings or does the user have to remove it? Removing anthropomorphism and removed directional phrase

```suggestion
- When you import an {ocp-short} managed cluster onto the hub cluster, {product-title-short} removes all the configuration settings from the `cluster-monitoring-config` config map of the {ocp-short} managed cluster. When the configuration settings are removed, {product-title-short} replaces it with the settings from the hub cluster.  
```

2024-06-14 20:26 UTC, dockerymick approved these changes

2024-06-14 20:27 UTC, dockerymick commented
We still need development to review. Added @subbarao-meduri and @douglascamata as reviewers

2024-06-17 10:59 UTC, douglascamata requested changes

2024-06-17 10:59 UTC, douglascamata commented on observability/observability_enable.adoc
> +- When you import an {ocp-short} managed cluster onto the hub cluster, {product-title-short} removes all the configuration settings from the `cluster-monitoring-config` config map of the {ocp-short}
This is not correct. The only thing being overwritten is the `retentionSize` configuration under the `prometheusK8s` section of the config map. 

We should probably document this as a known issue.

2024-06-17 16:47 UTC, douglascamata approved these changes
/lgtm

2024-06-17 17:51 UTC, swopebe commented on observability/observability_enable.adoc
> +- When you import an {ocp-short} managed cluster onto the hub cluster, {product-title-short} overwrites the `retentionSize` configuration under the `prometheusK8s` section of the config map.
Let's not use "under" --- reason:

Let's say we were to run an accessibility test on content, this is a word that could get flagged as a directional word that could confuse a user with a screen reader...then one would have to go justify the use of the word. It's kinder to the user not to use it and it reduces overhead to change or explain.

2024-06-17 17:52 UTC, swopebe commented on observability/observability_enable.adoc
> +- When you import an {ocp-short} managed cluster onto the hub cluster, {product-title-short} overwrites the `retentionSize` configuration under the `prometheusK8s` section of the config map.
I sometimes change to "from the ___section" "Within the section" something that is not directional.

2024-06-17 17:53 UTC, swopebe requested changes

2024-06-17 17:53 UTC, swopebe commented on release_notes/known_issues_observability.adoc
> +When you import an {ocp-short} managed cluster onto the hub cluster, {product-title-short} overwrites the `retentionSize` configuration under the `prometheusK8s` section of the config map. There is c
Same with under but now I have to ask, why are we documenting a known issue with the same content that we put in the task? (Usually it is one or the other, the task is more official and widely used, the known issue is something that will be fixed in an upcoming release (typically).

2024-06-17 18:18 UTC, jc-berger commented on release_notes/known_issues_observability.adoc
> +When you import an {ocp-short} managed cluster onto the hub cluster, {product-title-short} overwrites the `retentionSize` configuration under the `prometheusK8s` section of the config map. There is c
@douglascamata you suggested including it as a known issue as well. Do you think this content should _only_ exist as a known issue? 

If you want it as a note in the observability doc and as a known issue, do we have workaround steps?

2024-06-18 13:25 UTC, coffeegoesincodecomesout commented on observability/observability_enable.adoc
> +- When you import an {ocp-short} managed cluster onto the hub cluster, {product-title-short} removes all the configuration settings from the `cluster-monitoring-config` config map of the {ocp-short}
@douglascamata I have a case attached to the following knowledge base article [1]
that details an issue a CU had with additional alertmanager secrets [2]being removed when importing a managed cluster into ACM - hence the ask to expand this statement in the documentation 


[1] - https://access.redhat.com/solutions/7070731 
[2] - https://access.redhat.com/documentation/de-de/openshift_container_platform/4.14/html-single/monitoring/index#monitoring-adding-a-secret-to-the-alertmanager-configuration_configuring-the-monitoring-stack

2024-06-18 15:51 UTC, douglascamata commented on release_notes/known_issues_observability.adoc
> +When you import an {ocp-short} managed cluster onto the hub cluster, {product-title-short} overwrites the `retentionSize` configuration under the `prometheusK8s` section of the config map. There is c
We can have this content as a known issue only. There's no workaround or any action from the user that will prevent the configuration from being overwritten.

2024-06-18 16:02 UTC, douglascamata commented on observability/observability_enable.adoc
> +- When you import an {ocp-short} managed cluster onto the hub cluster, {product-title-short} removes all the configuration settings from the `cluster-monitoring-config` config map of the {ocp-short}
@coffeegoesincodecomesout let me double check what's the situation for that alertmanager configuration. The root cause is more generic and can involve other fields of the config map being reset to their default values.

2024-06-18 16:13 UTC, douglascamata commented on observability/observability_enable.adoc
> +- When you import an {ocp-short} managed cluster onto the hub cluster, {product-title-short} removes all the configuration settings from the `cluster-monitoring-config` config map of the {ocp-short}
@coffeegoesincodecomesout in the `alertmanagerMain` section of the config map, these are the fields that **will not** be overwritten:

* `enabled`
* `enableUserAlertmanagerConfig`
* `logLevel`
* `nodeSelector`
* `tolerations`
* `resources`
* `volumeClaimTemplate`

Everything else will be gone. As you can see, the `secrets` key is not one of the configurations that will stay.

2024-06-18 16:26 UTC, douglascamata commented on observability/observability_enable.adoc
> +- When you import an {ocp-short} managed cluster onto the hub cluster, {product-title-short} removes all the configuration settings from the `cluster-monitoring-config` config map of the {ocp-short}
@coffeegoesincodecomesout it's hard to document everything that will or will not be overwritten from this config map, as it's quite extensive. 

Basically the MCO is locked to the configuration from the commit `20fcb9f6ef4e00ccde05a13347bddfabe24e8c4c` of the CMO: https://github.com/openshift/cluster-monitoring-operator/blob/20fcb9f6ef4e00ccde05a13347bddfabe24e8c4c/pkg/manifests/config.go#L95. Only fields present in that version of the `ClusterMonitoringConfiguration` will persist.

2024-06-20 19:36 UTC, jc-berger commented
@douglascamata and @coffeegoesincodecomesout thank you both for devoting time to this PR! As you said, Douglas, it's tedious to document all the fields that do and do not get overwritten, and that can be problematic to maintain. 

Therefore, please let me know what you think of my newest commit, where I specified only the retention field in Prometheus is guaranteed to be overwritten, and how only fields in the cluster monitoring config are guaranteed to persist.

2024-06-21 11:20 UTC, douglascamata commented
@jc-berger honestly the new text reads more confusing to me than the previous, even though the previous one is incomplete. :/

2024-06-21 15:42 UTC, jc-berger commented
@douglascamata and @coffeegoesincodecomesout Nigel suggested over Slack that we focus on the known issue. For the observability notes here, he said we could keep the original content, but I did keep my small change to specify it's the retention field getting removed in the Prometheus matrix. 

What do y'all think?

2024-06-21 16:18 UTC, coffeegoesincodecomesout commented
@jc-berger /lgtm

2024-06-21 18:12 UTC, dockerymick approved these changes

2024-06-21 18:21 UTC, merged