added another note about backup collision
open-cluster-management/rhacm-docs pull request #6520
Opened 2024-06-11 18:15 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-12065

2024-06-11 18:26 UTC, birsanv approved these changes
lgtm ; thanks !

2024-06-12 20:56 UTC, dockerymick requested changes

2024-06-12 20:56 UTC, dockerymick commented on business_continuity/backup_restore/backup_schedule.adoc
> +. The administrator tests a disaster scenario by making Hub2 a primary hub cluster, without stopping Hub1 first, causing the following conditions:
Can we use something different from Hub1 and Hub2? Can Hub1 be considered the initial hub cluster?

2024-06-12 21:00 UTC, birsanv commented on business_continuity/backup_restore/backup_schedule.adoc
> +. The administrator tests a disaster scenario by making Hub2 a primary hub cluster, without stopping Hub1 first, causing the following conditions:
Hub1 is primary hub, Hub2 is passive hub

2024-06-13 01:45 UTC, dockerymick commented on business_continuity/backup_restore/backup_schedule.adoc
> +. The administrator tests a disaster scenario by making Hub2 a primary hub cluster, without stopping Hub1 first, causing the following conditions:
@birsanv thanks for clarifying, i recommend that we use those terms instead of Hub1 and Hub2

2024-06-13 12:22 UTC, birsanv commented on business_continuity/backup_restore/backup_schedule.adoc
> +. The administrator tests a disaster scenario by making Hub2 a primary hub cluster, without stopping Hub1 first, causing the following conditions:
thank you @dockerymick ; just note this is a part of a bullet section and Hub1, Hub2 has been used in the other bullets too. If we change this here we need to change in the other bullets I think

2024-06-13 14:14 UTC, dockerymick commented on business_continuity/backup_restore/backup_schedule.adoc
> +. The administrator tests a disaster scenario by making Hub2 a primary hub cluster, without stopping Hub1 first, causing the following conditions:
@birsanv I agree with changing the instances from Hub1 to **primary hub cluster** and Hub2 to **passive hub cluster**

2024-06-14 17:30 UTC, birsanv commented on business_continuity/backup_restore/backup_schedule.adoc
> +- The primary hub cluster unexpectedly starts working again.
We are overloading the primary and passive cluster naming .. 
@dockerymick the reason we got with using names for the hubs like Hub1 , Hub2 was that they would change states, from primary becoming secondary and back again. So a hub can be primary and then becomes passive. So it's confusing to just call it primary or passive

If Hub1, Hub2 is not pallatable, can we use some other naming convention, but stay away from just saying primary or passive hub ?

2024-06-18 19:31 UTC, birsanv approved these changes
lgtm

2024-06-20 14:17 UTC, dockerymick approved these changes

2024-06-20 14:17 UTC, dockerymick commented on business_continuity/backup_restore/backup_schedule.adoc
> +. The administrator tests a disaster scenario by making Hub2 a primary hub cluster, without stopping Hub1 first, causing the following conditions:
```suggestion
. The administrator tests a disaster scenario by making the passive hub cluster a primary hub cluster, without stopping the primary hub first, causing the following conditions: 
```

2024-06-20 14:17 UTC, dockerymick commented on business_continuity/backup_restore/backup_schedule.adoc
> +- Since the `BackupSchedule.cluster.open-cluster-management.io` resource is still enabled on Hub1, it writes backups at the same storage location which corrupts the backup data. For example, any hub
```suggestion
- Primary hub cluster is still running.
- Primary hub cluster backup data is restored on the passive hub cluster, including managed clusters backup. Therefore, the passive hub cluster is now the active cluster.
- Since the `BackupSchedule.cluster.open-cluster-management.io` resource is still enabled on the primary hub cluster, it writes backups at the same storage location which corrupts the backup data. For example, any hub cluster restoring the latest backups from this location might use the primary hub cluster data instead of the passive hub cluster data. To avoid data corruption, the primary hub cluster `BackupSchedule` resource status automatically changes to `BackupCollision`. In this scenario, to avoid getting into this backup collision state, stop the primary hub cluster first or delete the `BackupSchedule.cluster.open-cluster-management.io` resource on the primary hub cluster before restoring managed clusters data on the passive hub cluster.
```

2024-06-20 14:17 UTC, dockerymick commented on business_continuity/backup_restore/backup_schedule.adoc
> +- The primary hub cluster unexpectedly starts working again.
Sure, what naming do you have in mind?

2024-06-21 18:20 UTC, merged