deleted iam policy docs and references to iam policy in other docs
open-cluster-management/rhacm-docs pull request #6527
Opened 2024-06-12 18:11 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-11650 

See PR for changes in the release notes for iam policy: https://github.com/stolostron/rhacm-docs/pull/6501

2024-06-12 18:20 UTC, mprahl commented on clusters/hosted_control_planes/deploy_aws_private_clusters.adoc
> -[#create-aws-private-hosted-cluster]
This is a different IAM Policy and not related to the ACM IamPolicy kind that we removed. I would keep this section.

2024-06-12 18:21 UTC, mprahl commented on observability/observability_enable.adoc
> -. Create an IAM policy that limits access to an S3 bucket.
This looks to be related to IAM in AWS and not IamPolicy so I'd keep this.

2024-06-14 20:23 UTC, dockerymick commented on clusters/hosted_control_planes/deploy_aws_private_clusters.adoc
> -[#create-aws-private-hosted-cluster]
@jc-berger

2024-06-18 16:55 UTC, mprahl commented on clusters/hosted_control_planes/deploy_aws_private_clusters.adoc
> -* <<create-aws-private-hosted-cluster,Creating a private hosted cluster on AWS>>
This file should be left as is since it's not policy related.

2024-06-18 17:43 UTC, dockerymick requested changes

2024-06-18 17:43 UTC, dockerymick commented on clusters/hosted_control_planes/deploy_aws_private_clusters.adoc
> -* <<create-aws-private-hosted-cluster,Creating a private hosted cluster on AWS>>
@jc-berger reminder to add this child link back to the file

2024-06-18 17:43 UTC, dockerymick commented on clusters/hosted_control_planes/deploy_aws_private_clusters.adoc
> -- `*.apps.<hosted-cluster-name>.hypershift.local`
I'm not sure why this was changed. I recommend that you add the asterisks back

2024-06-21 16:20 UTC, dockerymick approved these changes

2024-06-21 17:19 UTC, merged