added known issue for MCO and CMO
open-cluster-management/rhacm-docs pull request #6542
Opened 2024-06-18 15:49 UTC by jc-berger

see jira: https://issues.redhat.com/browse/ACM-12213

2024-06-18 17:32 UTC, douglascamata approved these changes
/lgtm

2024-06-18 17:39 UTC, swopebe requested changes

2024-06-18 17:39 UTC, swopebe commented on release_notes/known_issues_observability.adoc
> +
We don't typically do this for the resources in the doc: (MCO) 

You can remove those, use the resource name enough for the user but you don't have to repeat it a lot.

Please remove` "it causes the following symptom,` it's extra here. 

Just write concisely (example):

_The previous_ (take out the word old, can use _earlier_ as well) _version prevents the `cluster-monitoring-config` config map from updating to the other configurations within observability.

_ (You do not need to put RHACM here because that is understood...observability is a RHACM feature.)

2024-06-18 17:39 UTC, swopebe commented on release_notes/known_issues_observability.adoc
> +
When the CMO tries to turn the configurations into text, it causes the following symptom: the `cluster-monitoring-config` config maps might get reset to their type's value of `0`.

Recommend:

When `MultiClusterObservability` configures to text, the `cluster-monitoring-config` config maps might reset `type` to a `0` value.

_Please remove possessives and as much anthropomorphism as possible. We don't use pronouns for the function, for example._

2024-06-18 17:39 UTC, swopebe commented on release_notes/known_issues_observability.adoc
> +. Go to your CMO stack inside your `cluster-monitoring-configuration` config map.
Don't need to say RHACM deployment, that is understood. Observability is a RHACM feature.

2024-06-18 17:39 UTC, swopebe commented on release_notes/known_issues_observability.adoc
> +. Go to your CMO stack inside your `cluster-monitoring-configuration` config map.
Again, we normally don't abbreviate the resources, but if you feel strongly about this, can you show me where it is done within the text of our doc (not the code text, but the text) and we can discuss?

2024-06-18 17:41 UTC, swopebe commented on release_notes/known_issues_observability.adoc
> +. Go to your CMO stack inside your `cluster-monitoring-configuration` config map.
please link the doc task to the PR. I think this is in our internal docs, as well, but you can do 

`git cm -m "url_for_doc_jira -- quick description" `before you `git push` to add your Doc Jira or do it after in the comments, but we link doc PRs to doc issues.

2024-06-21 16:30 UTC, swopebe approved these changes

2024-06-21 17:17 UTC, merged