simplified manually running summarization steps
open-cluster-management/rhacm-docs pull request #6545
Opened 2024-06-18 18:11 UTC by jc-berger

Jira: https://issues.redhat.com/browse/ACM-11921

2024-06-18 18:31 UTC, swopebe commented on global_hub/global_hub_compliance.adoc
>  ----
@JakobGray why `kubectl` here? I mentioned in a few meetings lately that we need to have all doc on `oc`. I can meet if this needs clarification.

2024-06-18 18:32 UTC, swopebe requested changes

2024-06-18 18:32 UTC, swopebe commented on global_hub/global_hub_compliance.adoc
> +You can use clients such as pgAdmin and tablePlush to connect to the {global-hub} database. Or, you can directly connect to the database on the cluster by running the following command:
Please code these items: pgAdmin and tablePlush

2024-06-19 08:35 UTC, oafischer commented on global_hub/global_hub_compliance.adoc
> +Find the local compliance job failure information from the dashboard metrics or the table, `history.local_compliance_job_log`. In this example, the date is, `2023-07-07`, so you know that `2023-07-06
```suggestion
Find the local compliance job failure information from the dashboard metrics or the table, `history.local_compliance_job_log`. In this example, the date is `2023-07-07`, so you know that `2023-07-06` is the date when you need to manually run the summary processes.
```

2024-06-19 08:36 UTC, oafischer requested changes
Make sure to double check if `kubectl ` is required, should be `oc` as Brandi mentioned.

2024-06-19 09:42 UTC, yanmxa commented on global_hub/global_hub_compliance.adoc
> +You can manually run the summarization process to help you investigate a problem or get a report sooner than the next scheduled routine. To manually run the summarization process complete the followi
You can manually run the summarization process to restore the initial compliance state of the day when the job isn't triggered or running failed. To do this, follow these steps:

2024-06-19 09:46 UTC, yanmxa commented on global_hub/global_hub_compliance.adoc
> +. Use the earlier day's history as the initial state for the recover day's history.
suggest: ". Use the earlier day's compliance history as the initial state for the recovery day's history."

2024-06-19 09:50 UTC, yanmxa commented on global_hub/global_hub_compliance.adoc
> +Find the local compliance job failure information from the dashboard metrics or the table, `history.local_compliance_job_log`. In this example, the date is, `2023-07-07`, so you know that `2023-07-06
need change the date from `2023-07-07` to `2023-07-06`

2024-06-19 09:54 UTC, yanmxa commented on global_hub/global_hub_compliance.adoc
>  ----
-- call the func to generate the initial data of '2023-07-06' by inheriting '2023-07-05'
CALL history.generate_local_compliance('2024-07-06');

2024-06-21 00:24 UTC, yanmxa commented on global_hub/global_hub_compliance.adoc
>  ----
Hi @jc-berger! The only one that needs to be updated is the date that I commented on.

2024-06-21 07:48 UTC, oafischer approved these changes

2024-06-21 15:31 UTC, merged

2024-06-21 15:32 UTC, jc-berger commented on global_hub/global_hub_compliance.adoc
>  ----
@yanmxa it looks like I made that change, so I went ahead and merged the PR. Let me know if I missed something. I'll hold off on closing the Jira in case I need to make a follow-up PR.