changed note about velero crds
open-cluster-management/rhacm-docs pull request #6572
Opened 2024-06-26 16:22 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-11818

2024-06-26 16:24 UTC, birsanv requested changes

2024-06-26 16:24 UTC, birsanv commented on business_continuity/backup_restore/backup_install.adoc
> +- Starting with {product-title-short} 2.11, when you create the `MultiClusterHub` resource, the Velero custom resource definitions (CRDs) do not automatically install on the hub cluster. When you ins
Replace :Still, the Velero CRDs resources are no longer reconciled and updated by the `MultiClusterHub` resource.

with:

As a result, the Velero CRDs resources are no longer reconciled and updated by the `MultiClusterHub` resource.

2024-06-27 15:13 UTC, dockerymick requested changes

2024-06-27 15:13 UTC, dockerymick commented on business_continuity/backup_restore/backup_install.adoc
> +- Starting with {product-title-short} 2.11, when you create the `MultiClusterHub` resource, the Velero custom resource definitions (CRDs) do not automatically install on the hub cluster. When you ins
It's best to not mention the version number, from my perspective it's clear that the user is reading v2.11
```suggestion
- When you create the `MultiClusterHub` resource, the Velero custom resource definitions (CRDs) do not automatically install on the hub cluster. When you install the OADP operator, the Velero CRDs are installed on the hub cluster. As a result, the Velero CRD resources are no longer reconciled and updated by the `MultiClusterHub` resource. 
```

2024-06-27 19:01 UTC, dockerymick approved these changes
Looks good! Thanks Jake!

2024-07-01 13:55 UTC, merged