modified notes about excluded crds
open-cluster-management/rhacm-docs pull request #6573
Opened 2024-06-26 19:13 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-12297

2024-06-26 19:30 UTC, birsanv requested changes

2024-06-26 19:30 UTC, birsanv commented on business_continuity/backup_restore/backup_arch.adoc
> +- Use the `cluster.open-cluster-management.io/backup` label for any other resources that you want to be backed up and are not included in the previously mentioned criteria or are not part of the excl
update : or are not part of the excluded API groups. See the following example:

with : or are part of the excluded API groups. See the following example:

2024-06-27 14:50 UTC, birsanv approved these changes
lgtm

2024-06-27 15:06 UTC, dockerymick requested changes

2024-06-27 15:06 UTC, dockerymick commented on business_continuity/backup_restore/backup_arch.adoc
> +- Exclude all resources that are a part of the included API groups, but are either not needed or are being recreated by owner resources that are also backed up: `clustermanagementaddon.addon.open-clu
```suggestion
- Exclude all of the following resources that are a part of the included API groups, but are either not needed or are being recreated by owner resources that are also backed up: `clustermanagementaddon.addon.open-cluster-management.io` ,`backupschedule.cluster.open-cluster-management.io`, `restore.cluster.open-cluster-management.io`, `clusterclaim.cluster.open-cluster-management.io`, `discoveredcluster.discovery.open-cluster-management.io`.
```

2024-06-27 15:06 UTC, dockerymick commented on business_continuity/backup_restore/backup_arch.adoc
>  +
```suggestion

+
```

2024-06-27 15:06 UTC, dockerymick commented on business_continuity/backup_restore/backup_arch.adoc
>  +
@jc-berger will you also add a new line break on line 43?

2024-06-27 18:57 UTC, dockerymick approved these changes
Thanks Jake, will you add a break line on 44: https://github.com/stolostron/rhacm-docs/pull/6573/files#r1657311846

Otherwise, this looks good

2024-07-01 14:17 UTC, merged