added backupstatus table
open-cluster-management/rhacm-docs pull request #6577
Opened 2024-06-27 17:13 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-11880

2024-06-27 17:15 UTC, jc-berger commented on business_continuity/backup_restore/backup_schedule.adoc
> +For descriptions of the various `BackupSchedule` statuses, see the following table:
I can make this content its own section, including a heading and anchor, but what do you think about it being documented as the second table under the `Scheduling a cluster backup` section?

2024-06-27 17:16 UTC, jc-berger commented on business_continuity/backup_restore/backup_schedule.adoc
> +|===
I can add a link to the `Avoiding backup collision section` as suggested in the Jira. But if we do end up keeping the table here, I don't think we need to link users to that section since it's next section they'd read.

2024-06-27 17:20 UTC, birsanv approved these changes
lgtm thanks !

2024-06-28 19:43 UTC, dockerymick commented on business_continuity/backup_restore/backup_schedule.adoc
> +For descriptions of the various `BackupSchedule` statuses, see the following table:
I think that's a great idea @jc-berger and makes sense. I will review after you move the table. @birsanv do you agree with this suggestion?

2024-07-01 13:53 UTC, jc-berger commented on business_continuity/backup_restore/backup_schedule.adoc
> +For descriptions of the various `BackupSchedule` statuses, see the following table:
@dockerymick thanks, Mikela! I currently have it documented as the second table in this doc section. So do you think it looks good to merge? :)

2024-07-02 15:26 UTC, dockerymick requested changes
I recommend that you monospace the statuses before merging. I also see that the `cluster-backup-operator` samples link points to our upstream repo (`stolostron`). That needs to be replaced with the equivalent link from the `open-cluster-management` repo. Will you check with development to see if there is a different link that we can use?

2024-07-02 15:26 UTC, dockerymick commented on business_continuity/backup_restore/backup_schedule.adoc
> +| _Enabled_
Since these are YAML values, I recommend that you add the backticks to monospace the value. In the tables that I have completed, I usually monospace the parameters, parameter values, and status messages
```suggestion
| _Enabled_
```

2024-07-03 12:19 UTC, dockerymick requested changes

2024-07-03 12:19 UTC, dockerymick commented on business_continuity/backup_restore/backup_schedule.adoc
> +| `Credentials backup`
I'm a little confused now with the resource. Is this the `kind` in the YAML example? Should there be a space between "Credentials" and "backup" or should this be CamelCased? I'm not sure, just need to be consistent. If its CamelCase, I would imagine that it is displayed as the following example: `CredentialsBackup`. If not, maybe use the suggestion. If this is not the `kind` of the YAML I am fine with you using italics for the "Resource groups table"
```suggestion
| `Credentials` backup
```

2024-07-03 12:19 UTC, dockerymick commented on business_continuity/backup_restore/backup_schedule.adoc
> +| `Resources backup`
```suggestion
| `Resources` backup
```

2024-07-03 12:19 UTC, dockerymick commented on business_continuity/backup_restore/backup_schedule.adoc
> +| `Managed clusters backup`
Same question here
```suggestion
| `ManagedClusters` backup
```

2024-07-03 12:19 UTC, dockerymick commented on business_continuity/backup_restore/backup_schedule.adoc
> +.Sample Yaml 1
```suggestion
.Sample YAML 1
```

2024-07-03 12:19 UTC, dockerymick commented on business_continuity/backup_restore/backup_schedule.adoc
> +.Sample Yaml 2
```suggestion
.Sample YAML 2
```

2024-07-03 12:19 UTC, dockerymick commented on business_continuity/backup_restore/backup_schedule.adoc
> -- See the link:https://github.com/stolostron/cluster-backup-operator/tree/release-2.8/config/samples[_cluster-backup-operator_] samples.
I assume there was not another link that could be used? I see there are only two sample, but I also encourage you to the `open-cluster-management` link if there is one. We try to avoid adding exact samples in case the sample changes in the developer repo

2024-07-03 14:53 UTC, merged

2024-07-03 14:54 UTC, dockerymick approved these changes

2024-07-03 14:54 UTC, dockerymick commented on business_continuity/backup_restore/backup_schedule.adoc
>  - Return to <<using-backup-restore,Scheduling and restoring backups>>
Let's remove this link since it takes the user back to the beginning of the file. Let's direct the user to the intro topic