https://issues.redhat.com/browse/ACM-10866
open-cluster-management/rhacm-docs pull request #6581
Opened 2024-06-28 03:02 UTC by dockerymick

2024-07-02 19:07 UTC, dockerymick commented on clusters/discovery/discovery_import.adoc
> +
Only ROSA and HyperShift (MCE HCP) support automatic 

For ROSA, we have to go through the OCP console
Which controller handles this for HyperShift? Check to see if this is already documented in MCE or do we need to link to external HyperShift docs?

2024-07-02 19:09 UTC, dockerymick commented on clusters/discovery/discovery_config_ui.adoc
Confirmed with Disiah that this section should remain. Add a small paragraph to introduce the steps

2024-07-02 19:11 UTC, dockerymick commented on clusters/discovery/discovery_import.adoc
> +//* You nmust have access to the namespaces that were used to configure Discovery.
```suggestion
== Prerequisites

* You must access the cluster as the cluster administrator.
* You must have access to the namespaces that were used to configure Discovery.
```

2024-07-02 19:13 UTC, dockerymick commented on clusters/discovery/discovery_import.adoc
> +. Log in to your hub cluster.
Users can log in through the terminal (by using a command) and through the Discovery page from the console.

2024-07-02 19:30 UTC, dockerymick commented on clusters/discovery/discovery_import.adoc
> +. Log in to your hub cluster.
Add another section to complete this task from the console

2024-07-02 19:33 UTC, dockerymick commented on clusters/discovery/discovery_import.adoc
> +. Log in to your hub cluster.
```suggestion
. Log in to your hub cluster from the console.
. Select *Search* from the navigation menu. 
. From the search bar, enter the following query: `DiscoveredCluster`
. The `DiscoveredCluster` resource results appears.
```
Or possibly add this step if we want to add the CLI option

2024-07-02 19:34 UTC, dockerymick commented on clusters/discovery/discovery_import.adoc
> +. Go to the `DiscoveredCluster` resource and set `importAsManagedCluster` to `true`. By setting the field to `true`, the `discovery-operator` imports the `DiscoveredCluster` resource, and creates a `
```suggestion
. Set  the `importAsManagedCluster` parameter to `true`. By setting the field to `true`, the `discovery-operator` imports the `DiscoveredCluster` resource, and creates a `ManagedCluster`, `KlusterletAddOnConfig`, (only if {product-title-short} is installed) and automatically imports `Secret` resources for your cluster.
```

2024-07-02 19:37 UTC, dockerymick commented on clusters/discovery/discovery_import.adoc
> +. To verify that the `ManagedCluster` resource is imported, see...
```suggestion
. To verify that the `DiscoveredCluster` resource is imported, go to the *Clusters* page. Verify that the cluster is listed in the _Cluster list_ tab.
```

2024-07-02 19:37 UTC, dockerymick commented on clusters/discovery/discovery_import.adoc
> +//is there a message that appears for the user? Would the managed cluster resource appear somewhere else in the console?
Got the verification step
```suggestion
```

2024-07-02 19:38 UTC, dockerymick commented on clusters/discovery/discovery_import.adoc
> +
Go through Brandi's PR and be sure to link to that topic from here in the Additional resources section

2024-07-02 19:38 UTC, dockerymick commented on clusters/discovery/discovery_import.adoc
> +//2. we need to replace this link with an link to open-clsuter-management repo
```suggestion
```

2024-07-02 19:39 UTC, dockerymick commented on clusters/discovery/discovery_manage.adoc
> +* <<import-rosa-policy,Importing ROSA cluster bu using a policy>>
```suggestion
```

2024-07-02 19:39 UTC, dockerymick commented on clusters/discovery/discovery_manage.adoc
> +Review the following sections to learn more about detaching managed cluster instances, importing ROSA cluster by using a policy, and importing non-ROSA clusters.
```suggestion
Review the following sections to learn more about detaching managed cluster instances and importing non-ROSA clusters.
```

2024-07-02 19:40 UTC, dockerymick commented on clusters/discovery/discovery_manage.adoc
> +The application management functions provide you with unified and simplified options for constructing and deploying applications and application updates. With these functions, your developers and Dev
```suggestion
```

2024-07-02 19:40 UTC, dockerymick commented on clusters/discovery/discovery_manage.adoc
> +Detach managaed clusters for Discovey to prevent reimporting automatically. Complete the following steps:
```suggestion
Detach managed clusters for Discovey to prevent reimporting automatically. Complete the following steps:
```

2024-07-02 19:46 UTC, dockerymick commented on clusters/discovery/discovery_manage.adoc
> +Detach managaed clusters for Discovey to prevent reimporting automatically. Complete the following steps:
```suggestion
Detach managaed clusters for Discovey to prevent reimporting automatically. When you detach your cluster, it is also deleted. Complete the following steps:
```

2024-07-02 19:49 UTC, dockerymick commented on clusters/discovery/discovery_manage.adoc
> +. To prevent reimport, add the following annotation, `discovery.open-cluster-management.io/previously-auto-imported: 'true'`.
```suggestion
. To detach your cluster, select the *Action menu* icon. 
. Select *Detach cluster*. The `discovery-operator` adds the following annotation, `discovery.open-cluster-management.io/previously-auto-imported: 'true'`.
```

2024-07-02 19:50 UTC, dockerymick commented on clusters/discovery/discovery_manage.adoc
> +. To verify that the `DiscoveredCluster` resource is not reimported automatically, check for the following message during your reimport attempt:
Make sure this is clear

2024-07-02 19:53 UTC, dockerymick commented on clusters/discovery/discovery_manage.adoc
> +If you want to automatically import a non-ROSA cluster, the import does not initiate. You must import other `DiscoveredCluster` resources manually. You must directly apply Kubernetes configurations t
```suggestion
If you want to automatically import a non-ROSA cluster, the import does not initiate. You must import other infrastructure provider `DiscoveredCluster` resources manually. You must directly apply Kubernetes configurations to the other types of `DiscoveredCluster` resources. If you enable the `importAsManagedCluster` field from the `DiscoveredCluster` resource, it is not imported due to the Discovery webhook. 
```

2024-07-02 19:54 UTC, dockerymick commented on clusters/discovery/discovery_manage.adoc
> +*Note:* If there is a `MultiClusterEngineHCP` type for the `DiscoveredCluster` resource you can automatically import it. However, the `DiscoveredCluster` resource is provided through only HyperShift.
Might remove, but keeping for now.

2024-07-02 19:56 UTC, dockerymick commented on clusters/discovery/discovery_manage.adoc
> +*Note:* If there is a `MultiClusterEngineHCP` type for the `DiscoveredCluster` resource you can automatically import it. However, the `DiscoveredCluster` resource is provided through only HyperShift.
HyperShift also has a policy that can be configured to automatically import clusters. Might want to point to that info if it exists.

2024-07-03 12:35 UTC, dockerymick commented on clusters/discovery/discovery_manage.adoc
> +//*Note:* If there is a `MultiClusterEngineHCP` type for the `DiscoveredCluster` resource you can automatically import it. However, the `DiscoveredCluster` resource is provided through only HyperShif
Found the file that mentions the automatic import for Hosted control plane clusters: https://github.com/stolostron/rhacm-docs/blob/2.11_stage/clusters/hosted_control_planes/create_hosted_aws.adoc

2024-07-03 12:35 UTC, dockerymick commented on clusters/release_notes/whats_new.adoc
> +- The `discovery-operator` now automatically imports ROSA clusters into {product-title-short} hub clusters. See, link:../discovery/discovery_import.adoc#discovery_import[Import Discovered clusters au
```suggestion
- The `discovery-operator` now automatically imports {rosa} clusters into {product-title-short} hub clusters. See, link:../discovery/discovery_import.adoc#discovery_import[Import Discovered clusters automatically for {rosa} clusters].
```

2024-07-05 16:19 UTC, dockerymick commented on clusters/discovery/discovery_manage.adoc
> += Importing using the Discovery s
```suggestion
= Importing by using Discovery
```

2024-07-05 16:27 UTC, dockerymick commented on clusters/discovery/discovery_manage.adoc
> +//need content here
```suggestion
The following procedure is an example of how to import your discovered {rosa} clusters automatically by using the `discovery-operator`.
```

2024-07-09 16:24 UTC, swopebe commented on clusters/discovery/discovery_manage.adoc
> += Importing by using Discovery
Enabling a discovered cluster for management, filename **enable_discovered_cluster.adoc**

2024-07-09 16:25 UTC, swopebe commented on clusters/discovery/discovery_manage.adoc
> +* You must have permission to import your cluster to enable automatic import.
remove

2024-07-09 16:26 UTC, swopebe commented on clusters/discovery/discovery_manage.adoc
> +* You must have permission to import your cluster to enable automatic import.
You need discovery enabled

2024-07-10 10:43 UTC, swopebe commented on clusters/acm_integration/acm_integration_intro.adoc
>  If you are using {mce-short} with {product-title-short} installed, you can access more multicluster management features, such as _Observability_ and _Policy_.
No, the new file that you set up would not be here. This is ACM-MCE integration only. The new discovery doc that we reviewed, remember is **MCE only.** We wouldn't add other MCE only docs here; otherwise, we lose the separation, which is the point of this new folder.

2024-07-10 10:44 UTC, swopebe commented on clusters/acm_integration/acm_integration_intro.adoc
> +//if we agree to updating the title, it needs to be updated here | MJ | 07/02
This section will remain as is, minus the new docs I am writing with Roke.

2024-07-10 10:45 UTC, swopebe commented on clusters/acm_integration/integration_import_rosa.adoc
>  Automate the import of {rosa} clusters by using {product-title-short} policy enforcement for faster cluster management, without manually importing individual clusters.
Can consider this in my work with Roke.

2024-07-10 10:46 UTC, swopebe commented on clusters/main.adoc
> +include::discovery/discovery_manage.adoc[leveloffset=+3]
filename change here for new file based on meeting yesterday

2024-07-10 10:48 UTC, swopebe commented on clusters/release_notes/whats_new.adoc
> +- The `discovery-operator` now automatically imports {rosa} clusters into {product-title-short} hub clusters. See, link:../discovery/discovery_import.adoc#discovery_import[Import Discovered clusters
Your entry would be only about enabling within MCE, and start with something like _You can now enable..._

Pull a little bit from here:

Automatically import supported clusters into your hub cluster with the `discovery-operator` for faster cluster management, without manually importing individual clusters

2024-07-10 10:48 UTC, swopebe requested changes
see comments

2024-07-10 13:42 UTC, dockerymick commented on clusters/acm_integration/acm_integration_intro.adoc
> +//based on my question in the discovery file, discovery_import, it seems like we should also list Discovery here| MJ | 07/02
```suggestion

```

2024-07-10 13:42 UTC, dockerymick commented on clusters/acm_integration/acm_integration_intro.adoc
> +//if we agree to updating the title, it needs to be updated here | MJ | 07/02
```suggestion

```

2024-07-10 13:43 UTC, dockerymick commented on clusters/acm_integration/integration_import_rosa.adoc
> +//Seems like we should explicitly state that this is for policies in the title and use the conref
```suggestion

```

2024-07-10 13:44 UTC, dockerymick commented on clusters/main.adoc
> +include::discovery/discovery_manage.adoc[leveloffset=+3]
```suggestion
include::discovery/enable_discovery_management.adoc[leveloffset=+3]
```

2024-07-10 13:49 UTC, dockerymick commented on clusters/release_notes/whats_new.adoc
> +- The `discovery-operator` now automatically imports {rosa} clusters into {product-title-short} hub clusters. See, link:../discovery/discovery_import.adoc#discovery_import[Import Discovered clusters
```suggestion
- You can now enable a discovered cluster to automatically import supported clusters into your hub cluster with the `discovery-operator`. Import clusters for faster cluster management. See, link:../discovery/enable_discovery_management.adoc#enable-discovered[Enabling a discovered cluster for management].
```

2024-07-10 13:54 UTC, dockerymick commented on clusters/discovery/enable_discovery_management.adoc
> +* You must have access to the namespaces that were used to configure the discovery service.
```suggestion
* Discovery is enabled by default. If you changed default settings, you need to enable Discovery.
```

2024-07-10 13:55 UTC, dockerymick commented on clusters/discovery/enable_discovery_management.adoc
> +* <<detach-managed-cluster,Detaching managed clusters for Discovery>>
```suggestion

```

2024-07-10 13:57 UTC, dockerymick commented on clusters/discovery/enable_discovery_management.adoc
> +=== Prerequisites
```suggestion
=== Prerequisite
```

2024-07-10 14:06 UTC, dockerymick commented on clusters/discovery/discovery_intro.adoc
> +* xref:../discovery/discovery_manage.adoc#managing-discovery[Manage the Discovery service]
```suggestion
* xref:../discovery/enable_discovery_management.adoc#enable-discovery[Enabling a discovered cluster for management]
```

2024-07-10 14:06 UTC, dockerymick commented on clusters/discovery/enable_discovery_management.adoc
> +=== Prerequisite
```suggestion
== Prerequisite
```

2024-07-10 14:54 UTC, dockerymick commented on clusters/discovery/enable_discovery_management.adoc
> +//need to follow up on this
@dislbenn will you confirm that line 27 is correct?

2024-07-11 14:46 UTC, dislbenn commented on clusters/discovery/enable_discovery_management.adoc
> +//need to follow up on this
@dockerymick yep, this is correct.

2024-07-11 14:47 UTC, dislbenn commented on clusters/discovery/enable_discovery_management.adoc
> +. To verify that the `DiscoveredCluster` resource is not reimported automatically, check for the following message in the `Discovery-Operator` logs, where `"rosa-dc"` is this discovered cluster:
```suggestion
. To verify that the `DiscoveredCluster` resource is not reimported automatically, check for the following message in the `discovery-operator` logs, where `"rosa-dc"` is this discovered cluster:
```

2024-07-11 15:29 UTC, dockerymick commented on clusters/discovery/enable_discovery_management.adoc
> +//need to follow up on this
```suggestion
```

2024-07-11 15:49 UTC, dockerymick commented
Received approval through Slack 
<img width="916" alt="Screenshot 2024-07-11 at 11 46 09 AM" src="https://github.com/stolostron/rhacm-docs/assets/60616885/5b67174e-a118-4f43-961b-28459ec2652f">

2024-07-11 16:06 UTC, swopebe commented on clusters/discovery/enable_discovery_management.adoc
> +[#enable-discovered]
I think you can drop management from the file name, since is seems we are enabling _management_ here, something to consider but I won't block it.

2024-07-11 16:06 UTC, swopebe approved these changes

2024-07-11 16:11 UTC, dockerymick commented on clusters/main.adoc
> +include::discovery/enable_discovery_management.adoc[leveloffset=+3]
```suggestion
include::discovery/enable_discovery.adoc[leveloffset=+3]
```

2024-07-11 16:12 UTC, dockerymick commented on clusters/release_notes/whats_new.adoc
> +- You can now enable a discovered cluster to automatically import supported clusters into your hub cluster with the `discovery-operator`. Import clusters for faster cluster management. See, link:../d
```suggestion
- You can now enable a discovered cluster to automatically import supported clusters into your hub cluster with the `discovery-operator`. Import clusters for faster cluster management. See, link:../discovery/enable_discovery.adoc#enable-discovered[Enabling a discovered cluster for management].
```

2024-07-11 16:13 UTC, dockerymick commented
@swopebe @dislbenn thanks for the reviews and approval! Merging this PR

2024-07-11 16:14 UTC, merged