business continuity 2.11 known issues
open-cluster-management/rhacm-docs pull request #6603
Opened 2024-07-01 16:31 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-11766

2024-07-01 17:38 UTC, dockerymick approved these changes
Added a suggestion, otherwise this looks good to me!

2024-07-01 17:38 UTC, dockerymick commented on release_notes/known_issues_continuity.adoc
> +To work around this issue, ensure that the managed `BareMetalHost` resources on the primary hub cluster are no longer backed up with the managed cluster backup
```suggestion
To work around this issue, ensure that the managed `BareMetalHost` resources on the primary hub cluster are no longer backed up with the managed cluster backup.
```

2024-07-02 13:29 UTC, birsanv requested changes

2024-07-02 13:29 UTC, birsanv commented on release_notes/known_issues_continuity.adoc
> +=== Bare metal hub resources not backed up by
This looks incomplete .. I expect to see this content here ( from the linked jirra )

Title : 

Bare metal hub resource no longer being backed up by the managed clusters backup

Description:
If the resources for the bare metal cluster are backed up and restored to a secondary hub cluster by using the {product-title-short} back up and restore feature, the managed cluster reinstalls on the nodes, which destroys the existing managed cluster.
Note: This only affects bare metal clusters that were deployed by using zero touch provisioning, meaning that they have BareMetalHost resources that manage powering on and off bare metal nodes and attaching virtual media for booting. If a BareMetalHost resource was not used in the deployment of the managed cluster, there is no negative impact.
 

To work around this issue, the managed BareMetalHost resources on the primary hub cluster are no longer backed up with the managed cluster backup. 

 

If you have a usecase different than the above and you want the managed BareMetalHost resources on the primary hub cluster to be backed up, add the backup label to the BareMetalHost resources on the primary hub cluster: cluster.open-cluster-management.io/backup.

Read this section to learn about using this backup label to backup generic resources. https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.10/html/business_continuity/business-cont-overview#resources-that-are-backed-up

2024-07-02 13:29 UTC, birsanv commented on release_notes/known_issues_continuity.adoc
>  If the resources for the bare metal cluster are backed up and restored to a secondary hub cluster by using the {product-title-short} back up and restore feature, the managed cluster reinstalls on the
Line 51-62 should be replaced by the section in comment above

2024-07-02 15:27 UTC, jc-berger commented on release_notes/known_issues_continuity.adoc
>  If the resources for the bare metal cluster are backed up and restored to a secondary hub cluster by using the {product-title-short} back up and restore feature, the managed cluster reinstalls on the
We typically don't have a header, like `Description` 

If you want, I can do something like:

[#symptom-managed-clusters-destroyed]
=== Symptom: Managed clusters get destroyed 

If the resources for the bare metal cluster are backed up....

However, we typically have that structure for Troubleshooting content. But I can add it here in the Known issues as well!

2024-07-03 14:05 UTC, birsanv requested changes
just one small update, everything else looks good

2024-07-03 14:05 UTC, birsanv commented on release_notes/known_issues_continuity.adoc
> +To learn more about using this backup label to backup generic resources, see the topic, link:../business_continuity/backup_restore/backup_arch.adoc#resources-that-are-backed-up[Cleaning the hub clust
The name of the link is incorrect ( Cleaning the hub cluster after restore ) 

It should be : Resources that are backed up

2024-07-03 14:49 UTC, birsanv approved these changes
lgtm

2024-07-03 14:50 UTC, merged