modified clustermanagementaddon
open-cluster-management/rhacm-docs pull request #6606
Opened 2024-07-01 17:43 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-12261

2024-07-01 19:45 UTC, swopebe requested changes
Comment for possible tech debt if not now, comment for concise language and asking for clearer description.

2024-07-01 19:45 UTC, swopebe commented on business_continuity/backup_restore/backup_arch.adoc
> +- Exclude all of the following resources that are a part of the included API groups, but are either not needed or are being recreated by owner resources that are also backed up: `backupschedule.clust
This line is really confusing. 

1st, this should be a list (consider that for tech debt if we cannot fix it now, that should not be entered like this but I recognize you didn't create that)
2nd, the description of this list is not clear right off the bat and very wordy.

2024-07-01 19:45 UTC, swopebe commented on business_continuity/backup_restore/backup_arch.adoc
> +- *Note:* If you modify `ClusterManagementAddon`, add the label, `cluster.open-cluster-management.io/backup` to trigger the backup.
please remove _trigger_ and turn around this sentence for clarity:

**If you modify `ClusterManagementAddon`, add the `cluster.open-cluster-management.io/backup` label to start the backup.** (or similar)

Anytime there is a `name, comma situation`, see if you can make it more concise and clearer.

2024-07-01 21:03 UTC, swopebe commented on business_continuity/backup_restore/backup_arch.adoc
> +- Exclude all resources from the following API groups:
This is so much easier to digest.

2024-07-01 21:03 UTC, swopebe approved these changes
the list is a game changer. TY

2024-07-01 21:05 UTC, swopebe commented on business_continuity/backup_restore/backup_arch.adoc
> +- *Note:* If you change `ClusterManagementAddon`, add the label, `cluster.open-cluster-management.io/backup` to initiate the backup.
```suggestion
- *Note:* If you change `ClusterManagementAddon`, add the `cluster.open-cluster-management.io/backup` label to initiate the backup. 
```

2024-07-02 02:34 UTC, zhujian7 commented on business_continuity/backup_restore/backup_arch.adoc
> +**  `action.open-cluster-management.io`
```suggestion
** `action.open-cluster-management.io`
```

2024-07-02 02:34 UTC, zhujian7 commented
/cc @birsanv

2024-07-02 13:20 UTC, birsanv requested changes
sorry for the late reply but I just saw this change request

The changes are not needed; any doc update for the addon backup change has been covered here https://issues.redhat.com/browse/ACM-12297
PR https://github.com/stolostron/rhacm-docs/pull/6573

There are no other changes needed for the main hub backup doc

@zhujian7 any doc update left to be done is for the hypershift backup doc, which I think is addressed by @rokej with another PR

2024-07-02 14:44 UTC, jc-berger commented
Closing this PR as these efforts are unneeded for Business Continuity. We can use the Jira to discuss similar changes but to the Hypershift Docs. Thank you all for your patience :)

2024-07-02 14:44 UTC, closed without merging