WIP: https://issues.redhat.com/browse/ACM-11562--writing process from YAML…
open-cluster-management/rhacm-docs pull request #6629
Opened 2024-07-03 15:36 UTC by swopebe

… for Discover and Manage HCP and AUTO import

2024-07-03 15:47 UTC, swopebe commented on clusters/acm_integration/manage_discovered_hcp.adoc
> +//This is a step.
340 I have not broken out into the step, that has to be done.

2024-07-03 15:48 UTC, swopebe commented on clusters/acm_integration/manage_discovered_hcp.adoc
> +## Enabling the hypershift add-ons for {mce-short}
This need to be changed to a task

2024-07-03 15:48 UTC, swopebe commented on clusters/acm_integration/manage_discovered_hcp.adoc
> +
340-380 I have not started to edit

2024-07-03 15:49 UTC, swopebe commented on clusters/acm_integration/manage_discovered_hcp.adoc
> +[#import-discover-hcp]
384 and on I think is it's own file.

2024-07-03 15:55 UTC, rokej commented on clusters/acm_integration/manage_discovered_hcp.adoc
> +If you have {mce-short} clusters that are hosting many hosted clusters, you can bring these hosted clusters to a {product-title-short} hub cluster for management.
Line 4 and 6 can be combined to be like...

If you have MCE clusters that are hosting many hosted clusters, you can bring this hosted clusters to a ACM hub cluster to mange them USING ACM management components such as application lifecycle and Governance.

2024-07-03 15:55 UTC, rokej commented on clusters/acm_integration/manage_discovered_hcp.adoc
> +You can have those hosted clusters automatically discovered and imported as managed clusters.
This section describes how you can have those MCE hosted clusters automatically discovered and imported as managed clusters by an ACM hub cluster.

2024-07-03 15:55 UTC, rokej commented on clusters/acm_integration/manage_discovered_hcp.adoc
> +* You need one or more {mce-short} hosting clusters that are _managed_ clusters. These clusters are not {ocp} or {product-title-short} clusters because {mce-short} installs other operators, such as H
You need one or more {mce-short} hosting clusters that are _managed_ clusters. These clusters are not {ocp} or {product-title-short} clusters because {mce-short} installs other operators, such as Hypershift, Hive and BareMetal infrastructure operators that you need for hosting hosted clusters.

2024-07-03 15:55 UTC, rokej commented on clusters/acm_integration/manage_discovered_hcp.adoc
> +== Scaling
This scaling section can go into the intro section to describe why users might want to do this entire discovery thing.   We can say...

Since the hosted control planes run on the managed {mce-short} cluster nodes, the number of hosted control planes the cluster can host is determined by the resource availability of managed {mce-short} cluster nodes, as well as the number of managed {mce-short} clusters. You can add more nodes or managed clusters to host more hosted control planes.

2024-07-03 18:08 UTC, rokej commented on clusters/acm_integration/manage_discovered_hcp.adoc
> +== Configuring for import
The purpose of these steps in this section is to make users aware the current installation locations and status of the addons we are about to configure differently in order to import MCEs.

2024-07-03 18:08 UTC, rokej commented on clusters/acm_integration/manage_discovered_hcp.adoc
> +{mce-short} has a self-managed cluster called `local-cluster` and the default add-ons are enabled for this managed cluster.
{mce-short} has a self-managed cluster called `local-cluster` and the default add-ons are enabled for this managed cluster. Run the following command to check where the MCE addons are currently installed before configuring them.

2024-07-03 18:08 UTC, rokej commented on clusters/acm_integration/manage_discovered_hcp.adoc
> +//we  define this as hub that is managed in the doc
Remove line 61 ~ 83.

2024-07-03 18:08 UTC, rokej commented on clusters/acm_integration/manage_discovered_hcp.adoc
> +. Run the following command to get the `managedclusteradd-ons` status for your `local-cluster`:
Run the following command to get the list of MCE addons for 'local-cluster'

2024-07-03 18:09 UTC, rokej commented on clusters/acm_integration/manage_discovered_hcp.adoc
> +== Configuring for import
We might not need a separate section for this. We can merge it with the next section that actually talks about "Configuring for import". The step in this section is about "checking the current state before Configuring for import".

2024-07-10 17:42 UTC, swopebe commented on clusters/acm_integration/acm_discover_hosted.adoc
> +//find this link
Wed: line 18 we said we would get a link.

2024-07-10 17:43 UTC, swopebe commented on clusters/acm_integration/acm_discover_hosted.adoc
> +. Run the following command to get your add-ons:
Line 52 and line 61, let's explain what they are doing and looking for?

2024-07-10 17:43 UTC, swopebe commented on clusters/acm_integration/acm_discover_hosted.adoc
> +. Update the existing `ClusterManagementadd-ons` resources for the add-ons so that the `add-onsDeploymentConfig` resource have the `agentInstallNamespace` namespace that you created.
please look at this little section?

2024-07-10 17:44 UTC, swopebe commented on clusters/acm_integration/acm_discover_hosted.adoc
> +. Update the existing `ClusterManagementadd-ons` resources for the add-ons so that the `add-onsDeploymentConfig` resource have the `agentInstallNamespace` namespace that you created.
comment on line 98

2024-07-10 17:44 UTC, swopebe commented on clusters/acm_integration/acm_discover_hosted.adoc
> +//we need to apply the file.
apply file command, right?

2024-07-10 17:44 UTC, swopebe commented on clusters/acm_integration/acm_discover_hosted.adoc
> +//??
Is this a verification step, mine 203?

2024-07-10 17:45 UTC, swopebe commented on clusters/acm_integration/acm_discover_hosted.adoc
> +//still struggling with this
is this clear, you think?

2024-07-10 17:45 UTC, swopebe commented on clusters/acm_integration/acm_discover_hosted.adoc
> +. Create a `KlusterletConfig` using the following example:
Is this the correct way to describe this step? line 233 and after?

2024-07-10 17:45 UTC, swopebe commented on clusters/acm_integration/acm_discover_hosted.adoc
> +//apply?
apply?

2024-07-10 17:46 UTC, swopebe commented on clusters/acm_integration/acm_discover_hosted.adoc
> +
I used callouts for this, please check?

2024-07-10 17:46 UTC, swopebe commented on clusters/acm_integration/acm_discover_hosted.adoc
> +????
Verification?

2024-07-10 19:17 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +//find this link
Here is the actual command to install `clusteradm` . We were going to remove `oc` from the pre-req.

```
curl -L https://raw.githubusercontent.com/open-cluster-management-io/clusteradm/main/install.sh | bash
```

2024-07-10 19:17 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +. Run the following command to get your add-ons:
This is for checking that the add ons are installed in the default namespace `open-cluster-management-agent-addons` (the namespace in line 58 is wrong. addons, not add-ons) before making changes to the addon installation namespace configuration.

2024-07-10 19:17 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +. Update the existing `ClusterManagementadd-ons` resources for the add-ons so that the `add-onsDeploymentConfig` resource have the `agentInstallNamespace` namespace that you created.
This is still a part of the first high level step of configuring ACM to import MCE.

2024-07-10 19:17 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +//we need to apply the file.
No applying file. Line 173 says add the `addondeploymentconfig` section to the existing resource. Also I noticed that you replaced all `addons` with `add-ons`. In line 195, it should be `addondeploymentconfigs`

2024-07-10 19:17 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +//??
Yes it is a verification step.

2024-07-10 19:17 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +//still struggling with this
Lines 226 ~ 230, I want to say...

When you install an MCE, the MCE hub cluster imports itself as `local-cluster` to be self managed and it installs a klusterlet named `kusterlet` for `local-cluster`. When you import an MCE cluster, ACM installs a klusterlet named `klusterlet` in the MCE cluster by default and it will conflict with the existing MCE local-cluster klusterlet. 

Create a `KlusterletConfig` resource that is used by the `ManagedCluster` resource to import {mce-short} clusters so that ACM installs the klusterlet with a different name. When the following `KlusterletConfig` is used, the klusterlet will be named `klusterlet-mce-import`.

2024-07-10 19:18 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +//apply?
Yes apply.

```
$ cat <<EOF | oc apply -f -
kind: KlusterletConfig
apiVersion: config.open-cluster-management.io/v1alpha1
metadata:
  name: mce-import-klusterlet-config
spec:
  installMode:
    type: noOperator
    noOperator:
       postfix: mce-import
EOF
```

2024-07-10 19:20 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +
Looks good

2024-07-10 20:20 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +. Create a `KlusterletConfig` using the following example:
yes

2024-07-10 23:34 UTC, swopebe commented on clusters/acm_integration/acm_discover_hosted.adoc
> +//we need to apply the file.
That was to catch the text, I forgot to exclude the code, that is fixed now.

2024-07-11 20:03 UTC, swopebe commented on clusters/acm_integration/acm_discover_hosted.adoc
> +* You need the `clusteradm` CLI in addition to `oc`.
We need a link for that, yes?

2024-07-11 20:04 UTC, swopebe commented on clusters/acm_integration/acm_integrate_import_hcp.adoc
> +//We only have the integrated console, right? Are we saying you cannot manage from outside the "local cluster" console? The cluster switcher is a drop-down menu that initially displays `local-cluster
See line 7 for console question

2024-07-11 20:10 UTC, swopebe commented on clusters/acm_integration/acm_discover_hosted.adoc
> +//still struggling with this
I will come back to this Friday.

2024-07-11 20:10 UTC, swopebe commented on clusters/acm_integration/acm_discover_hosted.adoc
> +//apply?
ok, will catch this up. TY

2024-07-12 11:24 UTC, swopebe commented on clusters/acm_integration/acm_discover_hosted.adoc
> +//apply?
@rokej we would add the command and the YAML separately to the doc, taking out `$ cat <<EOF`, do you mind showing what that should look like?

2024-07-12 14:21 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +* You need one or more {mce-short} hosting clusters that are _managed_ clusters. These clusters are not {ocp} or {product-title-short} clusters because {mce-short} installs other operators, such as H
You need one or more {mce-short} clusters.   (Let's keep it simple)

2024-07-12 14:21 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +curl -L https://raw.githubusercontent.com/open-cluster-management-io/clusteradm/main/install.sh | bash
We need a description for this command. "Install the clusteradm CLI by running the following command.".

2024-07-12 14:21 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +== Configuring {product-title-short} to import hosted clusters
Configuring {product-title-short} to import MCE clusters

2024-07-12 14:21 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +{mce-short} has a `local-cluster`, which is a hub cluster that is managed. The default addons are enabled for this `local-cluster`. Complete the following procedure to configure your local cluster to
Let's remove line 32 ~ 74. This could be confusing. I will add a summary of all these lines at the beginning of the next section.

2024-07-12 14:21 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +
Add this at the beginning of this section.

{mce-short} has a `local-cluster`, which is a hub cluster that is managed. The following default addons are enabled for this `local-cluster` in `open-cluster-management-agent-addon` namespace.

- cluster-proxy
- managed-serviceaccount
- work-manager

2024-07-12 14:21 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +----
```
cat <<EOF | oc apply -f -
apiVersion: addons.open-cluster-management.io/v1alpha1
kind: addonsDeploymentConfig
metadata:
  name: addons-ns-config
  namespace: multicluster-engine
spec:
  agentInstallNamespace: open-cluster-management-agent-addons-discovery
EOF
```

2024-07-12 14:21 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +[source,yaml]
[source,bash]

2024-07-12 14:21 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +. Update the existing `ClusterManagementaddons` resources for the addons so that the addonsDeploymentConfig` resource have the `agentInstallNamespace` namespace that you created.
Update the existing `ClusterManagementaddons` resources for the addons so that the addons are installed in `open-cluster-management-agent-addons-discovery` namespace specified in the `addonsDeploymentConfig` resource you created.

2024-07-12 14:21 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +See the following `ClusterManagementaddons` example resource for the `work-manager` addon:
Remove line 101 ~ 120.

2024-07-12 14:21 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +. Add the `addonsDeploymentConfig` to the `ClusterManagementaddons`. See the following example:
Step 3.a (a sub-step of line 98)

2024-07-12 14:21 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +. Add the `addonsDeploymentConfig` to the `managed-serviceaccount`. See the following example:
Step 3.b (a sub-step of line 98)

2024-07-12 14:21 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +. Add the `addonsDeploymentConfig` to the `cluster-proxy` addons. See the following example:
Step 3.c (a sub-step of line 98)

2024-07-12 14:21 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +The addons for the {product-title-short} `local-cluster` and all other managed clusters are re-installed into the namespace that you specified.
The addons for the {product-title-short} `local-cluster` are re-installed into the namespace that you specified.

2024-07-12 14:21 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +
Add this at the beginning of this section.

{mce-short} has a local-cluster, which is a hub cluster that is managed. A klusterlet resource named `klusterlet` is created for this local-cluster.

When your {mce-short} is imported into {product-title-short}, {product-title-short} installs the klusterlet with the same name `klusterlet` to manage the {mce-short} which will conflict with MCE's klusterlet for its local-cluster.

Install those addons in a different {mce-short} namespace so that the {mce-short} can self-manage with the `local-cluster` addons while  {product-title-short} manages {mce-short} at the same time. Complete the following proce

2024-07-12 14:21 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +When a `ManagedCluster` references the `KlusterletConfig` resource, the managed cluster `klusterlet` is installed in the namespace that you specified in the `KlusterletConfig`.
Remove this line.

2024-07-12 14:21 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +Create a `KlusterletConfig` resource that is used by `ManagedCluster` resources to import {mce-short} clusters.
Create a `KlusterletConfig` resource that is used by `ManagedCluster` resources to import {mce-short} clusters so that the klusterlet is installed with a different name to avoid the conflict.

2024-07-12 14:21 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +You can import the {product-title-short} klusterlet to be installed in a different namespace than the {mce-short} klusterlet for the {mce-short} `local-cluster`.
Remove this line.

2024-07-12 14:21 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +. Create a `KlusterletConfig` using the following example:
Create a `KlusterletConfig` using the following example. When this `KlusterletConfig` is referenced in a `ManagedCluster`, the value in the `spec.installMode.noOperator.postfix`  field is used as a suffix to the klusterlet name. e.g. `klusterlet-mce-import`

2024-07-12 14:21 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +----
```
cat <<EOF | oc apply -f -
kind: KlusterletConfig
apiVersion: config.open-cluster-management.io/v1alpha1
metadata:
  name: mce-import-klusterlet-config
spec:
  installMode:
    type: noOperator
    noOperator:
       postfix: mce-import
EOF
```

2024-07-12 14:21 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +<1> The `mce-import-klusterlet-config` annotation references the `KlusterletConfig` resource that you created in the previous step to install the {product-title-short} klusterlet into a different nam
<1> The `mce-import-klusterlet-config` annotation references the `KlusterletConfig` resource that you created in the previous step to install the {product-title-short} klusterlet with a different name in {mce-short}.

2024-07-12 14:21 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +. Create a secret that references the `kubeconfig`` file of the cluster. Go to xref:../cluster_lifecycle/import_cli.adoc#importing-clusters-auto-import-secret [Importing a cluster by using the auto i
Create the `auto-import-secret` secret that references the `kubeconfig` of the {mce-short} cluster.

2024-07-12 14:35 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +----
```
NAME                                 READY   UP-TO-DATE   AVAILABLE   AGE
cluster-proxy-proxy-agent            1/1     1            1           24h
klusterlet-addons-workmgr           1/1     1            1           24h
hypershift-addons-agent             1/1     1            1           24h
managed-serviceaccount-addons-agent 1/1     1            1           24h
```

2024-07-12 14:35 UTC, rokej commented on clusters/acm_integration/acm_integrate_import_hcp.adoc
> +//We only have the integrated console, right? Are we saying you cannot manage from outside the "local cluster" console? The cluster switcher is a drop-down menu that initially displays `local-cluster
Line 6 is to say that the discovered hosted clusters are automatically imported into ACM by the policy from this doc but ALSO they are auto-imported into MCE (where they are actually located). Since the hosted cluster is imported into both ACM and MCE, you can access this imported hosted cluster from two different consoles: ACM console and MCE console. The hosted cluster life-cycle management such as scaling worker nodes, upgrading the OCP version... can only be done through the MCE console where the hosted cluster is physically located.

2024-07-12 14:40 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +[source,yaml]
[source,bash]

```
cat <<EOF | oc apply -f -
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  annotations:
    agent.open-cluster-management.io/klusterlet-config: mce-import-klusterlet-config <1>
  name: mce-a <2>
spec:
  hubAcceptsClient: true
  leaseDurationSeconds: 60
EOF
```

2024-07-12 17:36 UTC, swopebe commented on clusters/acm_integration/acm_discover_hosted.adoc
> +curl -L https://raw.githubusercontent.com/open-cluster-management-io/clusteradm/main/install.sh | bash
I must have lost that in the copy/paste, it was there lol

2024-07-12 18:17 UTC, swopebe commented on clusters/acm_integration/acm_discover_hosted.adoc
> +See the following `ClusterManagementaddons` example resource for the `work-manager` addon:
@rokej the step does not match the YAML so we have to tell the user what the YAML example is for. I can play with it but cannot remove it.

2024-07-12 20:57 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +{mce-short} has a `local-cluster`, which is a hub cluster that is managed. The following default `addons` are enabled for this `local-cluster` in the `open-cluster-management-agent-addon` namespace:
Move line 35 ~ 39 to the beginning of `Configuring addons` section (in line 43).

2024-07-12 20:57 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +Install those addons in a _different_ {mce-short} namespace so that the {mce-short} can self-manage with the `local-cluster` addons, while {product-title-short} manages {mce-short} at the same time.
Remove this line.

2024-07-12 22:02 UTC, swopebe commented on clusters/acm_integration/acm_discover_hosted.adoc
> +{mce-short} has a `local-cluster`, which is a hub cluster that is managed. The following default `addons` are enabled for this `local-cluster` in the `open-cluster-management-agent-addon` namespace:
@rokej If I do that, that leaves no text between headers and we cannot do that for accessibility reasons, we have to have content between headers. Willing to take suggestions tho.

2024-07-13 00:41 UTC, swopebe commented on clusters/acm_integration/acm_integrate_import_hcp.adoc
> +//brandi to open an issue to get this description updated
I need to open an issue for this, I will later and remove this comment.

2024-07-13 00:42 UTC, swopebe commented on clusters/acm_integration/acm_integrate_import_hcp.adoc
> +
This section is not rendering right and I am too tired to keep fighting with it, mind looking at it?

2024-07-13 00:42 UTC, swopebe commented on clusters/acm_integration/acm_integrate_import_rosa.adoc
let's keep policy out of it because neither team mentioned adding it to the titles.

2024-07-13 00:43 UTC, swopebe commented on clusters/acm_integration/acm_integrate_import_rosa.adoc
Built this part better since i changed from a task, and based on something Oliver said in another PR.

2024-07-15 18:53 UTC, dockerymick commented on clusters/acm_integration/acm_discover_hosted.adoc
> +Install those add-ons in a different {mce-short} namespace so that the {mce-short} can self-manage with the `local-cluster` add-ons while  {product-title-short} manages {mce-short} at the same time.
```suggestion
Install those add-ons in a different {mce-short} namespace so that the {mce-short} can self-manage with the `local-cluster` add-ons while {product-title-short} manages {mce-short} at the same time. Complete the following procedure:
```

2024-07-15 21:07 UTC, dockerymick requested changes

2024-07-15 21:07 UTC, dockerymick commented on clusters/acm_integration/acm_discover_hosted.adoc
> +.. Add the `addonsDeploymentConfigs` to the `ClusterManagementaddons`. See the following example:
```suggestion
.. Add the parameter value, `addonsDeploymentConfigs` to the `ClusterManagementaddons` resource. See the following example:
```

2024-07-15 21:07 UTC, dockerymick commented on clusters/acm_integration/acm_discover_hosted.adoc
> +.. Add the `addonsDeploymentConfig` to the `managed-serviceaccount`. See the following example:
```suggestion
.. Add the `addonsdeploymentconfigs` value to the `ClusterManagementaddons` specification named `managed-serviceaccount`. See the following example:
```

2024-07-15 21:07 UTC, dockerymick commented on clusters/acm_integration/acm_discover_hosted.adoc
> +.. Add the `addonsDeploymentConfig` to the `cluster-proxy` add-ons. See the following example:
```suggestion
.. Add the `addonsdeploymentconfigs` value to the `ClusterManagementaddons` resource named, `cluster-proxy`. See the following example:
```

2024-07-15 21:07 UTC, dockerymick commented on clusters/acm_integration/acm_discover_hosted.adoc
> +. Run the following command to verify that the add-ons for the {product-title-short} `local-cluster` are re-installed into the namespace that you specified.:
Extra period
```suggestion
. Run the following command to verify that the add-ons for the {product-title-short} `local-cluster` are re-installed into the namespace that you specified:
```

2024-07-15 21:07 UTC, dockerymick commented on clusters/acm_integration/acm_discover_hosted.adoc
> +----
Slight spacing issue

<img width="965" alt="Screenshot 2024-07-15 at 3 05 54 PM" src="https://github.com/user-attachments/assets/79a08ad4-b682-414e-a3a5-15ecfd6ee11d">

```suggestion
See the following output example:

+
[source,bash]
----
NAME                                 READY   UP-TO-DATE   AVAILABLE    AGE
cluster-proxy-proxy-agent             1/1     1            1           24h
klusterlet-addons-workmgr             1/1     1            1           24h
managed-serviceaccount-addons-agent   1/1     1            1           24h
----
```

2024-07-15 21:07 UTC, dockerymick commented on clusters/acm_integration/acm_discover_hosted.adoc
> +When your {mce-short} is imported into {product-title-short}, {product-title-short} installs the klusterlet with the same name, `klusterlet`, to manage the {mce-short}, which conflicts with the {mce-
Long statement 
```suggestion
When your {mce-short} is imported into {product-title-short}, {product-title-short} installs the klusterlet with the same name, `klusterlet`, to manage the {mce-short}. This conflicts with the {mce-short} local-cluster klusterlet.
```

2024-07-15 21:07 UTC, dockerymick commented on clusters/acm_integration/acm_discover_hosted.adoc
> +. Create a `KlusterletConfig` using the following example. When this `KlusterletConfig` is referenced in a `ManagedCluster`, the value in the `spec.installMode.noOperator.postfix` field is used as a
```suggestion
. Create a `KlusterletConfig` resource using the following example. When this `KlusterletConfig` resource is referenced in a managed cluster, the value in the `spec.installMode.noOperator.postfix` field is used as a suffix to the klusterlet name, such as `klusterlet-mce-import`:
```

2024-07-15 21:07 UTC, dockerymick commented on clusters/acm_integration/acm_discover_hosted.adoc
> +Since you installed {product-title-short} , you can also use the _Backup and restore_ feature.
```suggestion
Since you installed {product-title-short}, you can also use the _Backup and restore_ feature.
```

2024-07-15 21:07 UTC, dockerymick commented on clusters/acm_integration/acm_discover_hosted.adoc
> +Add `backup=true` to enable backup. See the following steps for each add-on:
```suggestion
Add the `backup=true` label to enable backup. See the following steps for each add-on:
```

2024-07-15 21:07 UTC, dockerymick commented on clusters/acm_integration/acm_discover_hosted.adoc
> +* For your addons-ns-config`, run the following command:
```suggestion
* For your `addons-ns-config`, run the following command:
```

2024-07-15 21:07 UTC, dockerymick commented on clusters/acm_integration/acm_discover_hosted.adoc
> +
Is there a verification step?

2024-07-15 21:07 UTC, dockerymick commented on clusters/acm_integration/acm_discover_hosted.adoc
> +
Short description needed

2024-07-15 21:07 UTC, dockerymick commented on clusters/acm_integration/acm_discover_hosted.adoc
> +
```suggestion

To manually import an {mce-short} cluster from your {product-title-short} cluster, complete the following procedure:
```

2024-07-15 21:07 UTC, dockerymick commented on clusters/acm_integration/acm_discover_hosted.adoc
> +. From your {product-title-short} cluster, create a `ManagedCluster` resource manually to import an {mce-short} cluster. See the following file example:
```suggestion
.  Create a `ManagedCluster` resource manually to import an {mce-short} cluster. See the following file example:
```

2024-07-15 21:07 UTC, dockerymick commented on clusters/acm_integration/acm_discover_hosted.adoc
> +See following example output with the status and example urls of managed clusters:
```suggestion
See following example output with the status and example URLs of managed clusters:
```

2024-07-15 21:07 UTC, dockerymick commented on clusters/acm_integration/acm_discover_hosted.adoc
> +After all your {mce-short} clusters are imported into {product-title-short}, you need to enable the hypershift add-on for those managed {mce-short} clusters to discover the hosted clusters.
```suggestion
After all your {mce-short} clusters are imported into {product-title-short}, you need to enable the HyperShift add-on for those managed {mce-short} clusters to discover the hosted clusters.
```

2024-07-15 21:07 UTC, dockerymick commented on clusters/acm_integration/acm_discover_hosted.adoc
> +Default add-ons are installed in to a different namespace in the previous procedures. Similarly, you install the `hypershift-addons` in to a different namespace in {mce-short} so that the add-ons age
```suggestion
Default add-ons are installed into a different namespace in the previous procedures. Similarly, you install the `hypershift-addons` into a different namespace in {mce-short} so that the add-ons agent for {mce-short} local-cluster and the agent for {product-title-short} can work in {mce-short}. 
```

2024-07-15 21:07 UTC, dockerymick commented on clusters/acm_integration/acm_discover_hosted.adoc
> +oc patch addonsdeploymentconfig hypershift-addons-deploy-config -n multicluster-engine --type=merge -p '{"spec":{"agentInstallNamespace":"open-cluster-management-agent-addons-discovery"}}'
```suggestion
Complete the following procedure:

. Run the following command to set the `agentInstallNamespace` namespace of the add-on to `open-cluster-management-agent-addons-discovery`:

+
[source,bash]
----
oc patch addonsdeploymentconfig hypershift-addons-deploy-config -n multicluster-engine --type=merge -p '{"spec":{"agentInstallNamespace":"open-cluster-management-agent-addons-discovery"}}'
```

2024-07-15 21:07 UTC, dockerymick commented on clusters/acm_integration/acm_discover_hosted.adoc
> +. Run the following command to disable metrics and to disable the hypershift operator management:
```suggestion
. Run the following command to disable metrics and to disable the HyperShift operator management:
```

2024-07-15 21:07 UTC, dockerymick commented on clusters/acm_integration/acm_discover_hosted.adoc
> +. Log into {mce-short} clusters and verify that the hypershift add-on is installed in the namespace that you specified. Run the following command:
```suggestion
. Log into {mce-short} clusters and verify that the HyperShift add-on is installed in the namespace that you specified. Run the following command:
```

2024-07-15 21:07 UTC, dockerymick commented on clusters/acm_integration/acm_discover_hosted.adoc
> +See the following example output that lists the add-ons:
fixing alignment
```suggestion
+
See the following example output that lists the add-ons:
```

2024-07-15 21:07 UTC, dockerymick commented on clusters/acm_integration/acm_discover_hosted.adoc
> +You can view your discovered clusters in the console.
Should this be a new section or should it be considered a verification step? If verification, I also recommend that the order steps become substeps

2024-07-15 21:07 UTC, dockerymick commented on clusters/acm_integration/acm_discover_hosted.adoc
> +Next, visit xref:../acm_integrate_import_hcp.adoc#auto-import-hcp[Automating import for discovered hosted clusters] to learn how to automatically import clusters.
Is this a part of the steps? If not, I recommend that this be added to an Additional resources section in this file

2024-07-15 21:07 UTC, dockerymick commented on clusters/acm_integration/acm_discover_hosted.adoc
> +Next, visit xref:../acm_integrate_import_hcp.adoc#auto-import-hcp[Automating import for discovered hosted clusters] to learn how to automatically import clusters.
Also this link is broken 
```suggestion
Next, visit xref:../acm_integration/acm_integrate_import_hcp.adoc#auto-import-hcp[Automating import for discovered hosted clusters] to learn how to automatically import clusters.
```

2024-07-15 21:07 UTC, dockerymick commented on clusters/acm_integration/acm_integrate_import_hcp.adoc
> +== Configure settings for automatic import
Other sections, you use gerunds. Recommending for consistency:

```suggestion
== Configuring settings for automatic import
```

2024-07-15 21:07 UTC, dockerymick commented on clusters/acm_integration/acm_integrate_import_hcp.adoc
> +Configure your `DiscoveredCluster` to import all your discovered hosted clusters automatically. Log in to your hub cluster from the CLI to complete the following procedure:
```suggestion
Configure your `DiscoveredCluster` custom resource to import all your discovered hosted clusters automatically. Log in to your hub cluster from the CLI to complete the following procedure:
```

2024-07-15 21:07 UTC, dockerymick commented on clusters/acm_integration/acm_integrate_import_hcp.adoc
> +
How can the user verify that it was created?

2024-07-15 21:07 UTC, dockerymick commented on clusters/acm_integration/acm_integrate_import_hcp.adoc
> +You need to create a placement definition that specifies the managed cluster for the policy deployment.
```suggestion
You need to create a placement definition that specifies the managed cluster for the policy deployment. Complete the following procedure:
```

2024-07-15 21:07 UTC, dockerymick commented on clusters/acm_integration/acm_integrate_import_hcp.adoc
> +
Same here, any verification step?

2024-07-15 21:07 UTC, dockerymick commented on clusters/acm_integration/acm_integrate_import_hcp.adoc
> +After you create the policy and the placement, you need to connect the two resources.
```suggestion
After you create the policy and the placement, you need to connect the two resources. Complete the following steps:
```

2024-07-15 21:07 UTC, dockerymick commented on clusters/acm_integration/acm_integrate_import_hcp.adoc
> +. Connect the resources by using a `PlacementBinding`. See the following example where `placementRef` points to the `Placement` that you created, and `subjects` points to the `Policy` that you create
```suggestion
. Connect the resources by using a `PlacementBinding` resource. See the following example where `placementRef` points to the `Placement` that you created, and `subjects` points to the `Policy` that you created:
```

2024-07-15 21:07 UTC, dockerymick commented on clusters/acm_integration/acm_integrate_import_hcp.adoc
> +----
Plus sign is not needed here because you are not using an ordered list
```suggestion
[source,bash]
----
  annotations:
    discovery.open-cluster-management.io/previously-auto-imported: "true"
----
```

2024-07-15 21:07 UTC, dockerymick commented on clusters/acm_integration/acm_integrate_import_hcp.adoc
> +If you want the detached discovered cluster to be reimported, remove this annotation.
I recommend an Additional resources section at the end of this file

2024-07-15 21:07 UTC, dockerymick commented on clusters/acm_integration/acm_integrate_import_rosa.adoc
> += Automating import for discovered {rosa} on AWS clusters
{rosa}: OpenShift Service on AWS

so from stage it will read as, "Automating import for discovered OpenShift Service on AWS on AWS clusters"

Seems like the second "on AWS" should be removed
```suggestion
= Automating import for discovered {rosa} clusters
```
If the suggestion is applied, it would read as:
Automating import for discovered OpenShift Service on AWS clusters

2024-07-15 21:07 UTC, dockerymick commented on clusters/acm_integration/acm_integrate_intro.adoc
> +* xref:../clusters/acm_integration/integration_observe.adoc#mce-acm-observability[Observability integration]
Broken links, not sure why. Most of the link syntax look correct. I did see that some of the anchors did not match. Some filenames also didn't maatch. Maybe if we use `link:` it will resolve it. On the other hand, i can also imagine that you probably wanted to shorten the file name and intended to remove the "acm" part in the last part of the file path, but the clusters/main.adoc file has "acm" listed. 
```suggestion
See the following procedures for {mce-short} and {product-title-short} multicluster management:

* link:../clusters/acm_integration/acm_discover_hosted.adoc#discover-hosted-acm[Discovering {mce-short} hosted clusters in {product-title-short}]
* link:../clusters/acm_integration/acm_integrate_import_hcp.adoc#auto-import-hcp[Automating import for discovered hosted clusters]
* link:../clusters/acm_integration/acm_integrate_import_rosa.adoc#import-discover-rosa[Automating import for discovered {rosa} clusters]
* link:../clusters/acm_integration/acm_integrate_observe.adoc#mce-acm-observability[Observability integration]
```

2024-07-15 21:07 UTC, dockerymick commented on clusters/release_notes/whats_new.adoc
> +You can now discover and automate the import of hosted clusters, as well. Configure  {product-title-short} to import {mce-short} clusters and then use policy enforcement for automation. Learn more at
Broken links here and need to match title
```suggestion
* You can now automate the import of {rosa} clusters by using {product-title-short} policy enforcement with {mce-short} for faster cluster management. Learn more at link:../clusters/acm_integration/acm_integration_import_rosa.adoc#import-discover-rosa[Automating import for discovered {rosa} clusters].

* You can now discover and automate the import of hosted clusters, as well. Configure  {product-title-short} to import {mce-short} clusters and then use policy enforcement for automation. Learn more at xref:../clusters/acm_integration/acm_discover_hosted.adoc#discover-hosted-acm[Automating import for discovered hosted clusters].
```

2024-07-15 21:07 UTC, dockerymick commented on release_notes/whats_new.adoc
> +* The documentation for {mce-short} (cluster) is in the _Cluster Lifecycle_ section of the product documentation.
```suggestion
* The documentation for {mce-short} (cluster) is in the _Cluster lifecycle_ section of the product documentation.
```

2024-07-16 01:47 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +{mce-short} has a `local-cluster`, which is a hub cluster that is managed. The following default `addons` are enabled for this `local-cluster` in the `open-cluster-management-agent-addon` namespace:
@swopebe OK. In that case, let's add one more line to give the reader a little more context. We can say..

This section describes how to configure these addons so that they are installed in a different namespace prior to importing MCEs.

2024-07-16 01:47 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +
The verification step would be to check the `KlusterletConfig` resource to ensure the label is added.

2024-07-16 01:49 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +//apply?
Taking out the `cat` command, it looks like this which is what you already have up there.

```
kind: KlusterletConfig
apiVersion: config.open-cluster-management.io/v1alpha1
metadata:
  name: mce-import-klusterlet-config
spec:
  installMode:
    type: noOperator
    noOperator:
       postfix: mce-import
```

2024-07-16 11:40 UTC, swopebe commented on clusters/acm_integration/acm_discover_hosted.adoc
> +.. Add the `addonsDeploymentConfigs` to the `ClusterManagementaddons`. See the following example:
I usually eliminate the need for extra words and commas in these in peer reviews. So:

Add the parameter value, `addonsDeploymentConfigs` to the `ClusterManagementaddons` resource. See the following example:

becomes

Add `addonsDeploymentConfigs` to the `ClusterManagementaddons` specification. See the following example:

or 

Add the `addonsDeploymentConfigs` value to the `ClusterManagementaddons` specification. See the following example:

This is for conciseness, and because I often see misuse of commas when I see this. (Here we would have to put one after the value as well, so it ends up being too many commas.)

2024-07-16 11:40 UTC, swopebe commented on clusters/acm_integration/acm_discover_hosted.adoc
> +.. Add the `addonsDeploymentConfigs` to the `ClusterManagementaddons`. See the following example:
I will add one of those examples.

2024-07-16 11:40 UTC, swopebe commented on clusters/acm_integration/acm_discover_hosted.adoc
> +.. Add the `addonsDeploymentConfig` to the `managed-serviceaccount`. See the following example:
same here

2024-07-16 11:42 UTC, swopebe commented on clusters/acm_integration/acm_discover_hosted.adoc
> +        resource: addonsdeploymentconfigs
@dockerymick we cannot ever change the YAML that is give to us without talking to development because this is used. If not the same then the content changes before the code or we check with engineering.

2024-07-16 11:42 UTC, swopebe commented on clusters/acm_integration/acm_discover_hosted.adoc
> +.. Add the `addonsDeploymentConfig` to the `cluster-proxy` add-ons. See the following example:
same here.

2024-07-16 11:42 UTC, swopebe commented on clusters/acm_integration/acm_discover_hosted.adoc
> +        resource: addonsdeploymentconfigs
same

2024-07-16 11:46 UTC, swopebe commented on clusters/acm_integration/acm_integrate_import_hcp.adoc
> +If you want the detached discovered cluster to be reimported, remove this annotation.
@dockerymick not here because it is intentionally a next procedure to automate; I created the other file as the next procedure. Additional resources should be other areas to explore or links cited in the doc, but not next steps.

I will raise this in my meeting, though.

2024-07-16 11:46 UTC, swopebe commented on clusters/acm_integration/acm_integrate_import_rosa.adoc
> += Automating import for discovered {rosa} on AWS clusters
good catch!

2024-07-16 11:47 UTC, swopebe commented on clusters/release_notes/whats_new.adoc
> +You can now discover and automate the import of hosted clusters, as well. Configure  {product-title-short} to import {mce-short} clusters and then use policy enforcement for automation. Learn more at
good catch, I changed them in the main but forgot to go here

2024-07-16 11:48 UTC, swopebe commented on clusters/acm_integration/acm_discover_hosted.adoc
> +Add `backup=true` to enable backup. See the following steps for each add-on:
YES!! That is how the ones above should be without the extra need for commas. Great suggestion.

2024-07-16 11:53 UTC, swopebe commented on clusters/acm_integration/acm_discover_hosted.adoc
> +After all your {mce-short} clusters are imported into {product-title-short}, you need to enable the hypershift add-on for those managed {mce-short} clusters to discover the hosted clusters.
@dockerymick this is intentionally written in proper format. If we do not put it in code as improper, if improper in code, this needs to be written the same as the title. I almost always double check. This is correct:

https://docs.redhat.com/en/documentation/openshift_container_platform/4.15/html/hosted_control_planes/hosted-control-planes-overview#hosted-control-planes-benefits_hcp-overview

It could also be coded, but not improper in this case.

2024-07-16 11:54 UTC, swopebe commented on clusters/acm_integration/acm_discover_hosted.adoc
> +Default add-ons are installed in to a different namespace in the previous procedures. Similarly, you install the `hypershift-addons` in to a different namespace in {mce-short} so that the add-ons age
great catch

2024-07-16 11:57 UTC, swopebe commented on clusters/acm_integration/acm_discover_hosted.adoc
> +Next, visit xref:../acm_integrate_import_hcp.adoc#auto-import-hcp[Automating import for discovered hosted clusters] to learn how to automatically import clusters.
@dockerymick this change I have a question about. Usually if we are in the same book, which we are, we don't need the extra path, we just go back into the folder (../) and down to the file. (?)

2024-07-16 11:57 UTC, swopebe commented on clusters/acm_integration/acm_integrate_import_hcp.adoc
> +== Configure settings for automatic import
YES!

2024-07-16 11:57 UTC, swopebe commented on clusters/acm_integration/acm_integrate_import_hcp.adoc
> +Configure your `DiscoveredCluster` to import all your discovered hosted clusters automatically. Log in to your hub cluster from the CLI to complete the following procedure:
Yes, thank you!!

2024-07-16 13:07 UTC, dockerymick commented on clusters/acm_integration/acm_discover_hosted.adoc
> +.. Add the `addonsDeploymentConfigs` to the `ClusterManagementaddons`. See the following example:
That makes sense. Thanks for the reminder. I like the second option

2024-07-16 13:10 UTC, dockerymick commented on clusters/acm_integration/acm_discover_hosted.adoc
> +        resource: addonsdeploymentconfigs
Understood, I updated my other suggestion. Please ignore this

2024-07-16 13:11 UTC, dockerymick commented on clusters/acm_integration/acm_discover_hosted.adoc
> +.. Add the `addonsDeploymentConfig` to the `cluster-proxy` add-ons. See the following example:
Updated the suggestion

2024-07-16 13:13 UTC, dockerymick commented on clusters/acm_integration/acm_discover_hosted.adoc
> +
@rokej thanks, will you also share the command that the user needs to run to see the `KlusterletConfig`?

2024-07-16 13:35 UTC, dockerymick commented on clusters/acm_integration/acm_discover_hosted.adoc
> +After all your {mce-short} clusters are imported into {product-title-short}, you need to enable the hypershift add-on for those managed {mce-short} clusters to discover the hosted clusters.
Ok, throughout our doc i saw HyperShift

2024-07-16 13:40 UTC, dockerymick commented on clusters/acm_integration/acm_discover_hosted.adoc
> +Next, visit xref:../acm_integrate_import_hcp.adoc#auto-import-hcp[Automating import for discovered hosted clusters] to learn how to automatically import clusters.
Yes, I agree but it appeared as broken when I ran the tool 
<img width="1126" alt="Screenshot 2024-07-16 at 9 40 20 AM" src="https://github.com/user-attachments/assets/9b8093b0-6b98-447b-ba18-75407febb249">

2024-07-16 13:58 UTC, rokej reviewed
@swopebe There are a lot of places where the resource names or kinds are technically incorrect with `addons` (plurals). Please refer to YAMLs in https://github.com/stolostron/hypershift-addon-operator/blob/main/docs/discovering_hostedclusters.md

2024-07-16 13:58 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +oc label addonsdeploymentconfig addons-ns-config -n multicluster-engine cluster.open-cluster-management.io/backup=true
addonsdeploymentconfig -> addondeploymentconfig (remove s)

addons-ns-config -> addon-ns-config

2024-07-16 13:58 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +oc label addonsdeploymentconfig hypershift-addons-deploy-config -n multicluster-engine cluster.open-cluster-management.io/backup=true
addonsdeploymentconfig -> addondeploymentconfig (remove s)

hypershift-addons-deploy-config -> hypershift-addon-deploy-config

2024-07-16 13:58 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +oc label clustermanagementaddons work-manager cluster.open-cluster-management.io/backup=true
clustermanagementaddons -> clustermanagementaddon (remove s)

2024-07-16 13:58 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +oc label clustermanagementaddons cluster-proxy cluster.open-cluster-management.io/backup=true
clustermanagementaddons -> clustermanagementaddon (remove s)

2024-07-16 13:58 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +oc label clustermanagementaddons managed-serviceaccount cluster.open-cluster-management.io/backup=true
clustermanagementaddons -> clustermanagementaddon (remove s)

2024-07-16 13:58 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +* For your addons-ns-config`, run the following command:
addons-ns-config -> addon-ns-config

2024-07-16 13:58 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +managed-serviceaccount-addons-agent   1/1     1            1           24h
managed-serviceaccount-addons-agent  -> managed-serviceaccount-addon-agent

2024-07-16 13:58 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +klusterlet-addons-workmgr             1/1     1            1           24h
klusterlet-addons-workmgr -> klusterlet-addon-workmgr

2024-07-16 13:58 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +oc get deployment -n open-cluster-management-agent-addons-discovery
open-cluster-management-agent-addons-discovery -> open-cluster-management-agent-addon-discovery

2024-07-16 13:58 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +        name: addons-ns-config
addons-ns-config -> addon-ns-config

2024-07-16 13:58 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +kind: ClusterManagementaddons
ClusterManagementaddons -> ClusterManagementAddOn

2024-07-16 13:58 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +apiVersion: addons.open-cluster-management.io/v1alpha1
addons.open-cluster-management.io/v1alpha1 -> addon.open-cluster-management.io/v1alpha1

2024-07-16 13:58 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +  addonsMeta:
addonsMeta -> addonMeta

2024-07-16 13:58 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +.. Add the `addonsDeploymentConfig` to the `cluster-proxy` add-ons. See the following example:
addonsDeploymentConfig -> addonDeploymentConfig

2024-07-16 14:15 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +. Create the `addonsDeploymentConfig` resource to specify a different add-on installation namespace. See the following example where `agentInstallNamespace` points to `open-cluster-management-agent-a
`addonsDeploymentConfig` -> `AddOnDeploymentConfig `

`open-cluster-management-agent-addons-discovery` -> `open-cluster-management-agent-addon-discovery`

2024-07-16 14:15 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +apiVersion: addons.open-cluster-management.io/v1alpha1
```
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: AddOnDeploymentConfig
```

2024-07-16 14:15 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +  name: addons-ns-config
`name: addons-ns-config` -> `name: addon-ns-config`

2024-07-16 14:15 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +  agentInstallNamespace: open-cluster-management-agent-addons-discovery
`  agentInstallNamespace: open-cluster-management-agent-addons-discovery` -> `  agentInstallNamespace: open-cluster-management-agent-addon-discovery`

2024-07-16 14:15 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +. Update the existing `ClusterManagementaddons` resources for the add-ons so that the add-ons are installed in the `open-cluster-management-agent-addons-discovery` namespace that is specified in the
`ClusterManagementaddons` -> `ClusterManagementAddOn `
`open-cluster-management-agent-addons-discovery` -> `open-cluster-management-agent-addon-discovery`
`addonsDeploymentConfig ` -> `AddOnDeploymentConfig`

2024-07-16 14:15 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +kind: ClusterManagementaddons
`ClusterManagementaddons` -> `ClusterManagementAddOn`

2024-07-16 14:15 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +apiVersion: addons.open-cluster-management.io/v1alpha1
`addons` -> `addon`

2024-07-16 14:15 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +  addonsMeta:
`addonsMeta` -> addonMeta

2024-07-16 14:15 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +.. Add the `addonsDeploymentConfigs` to the `ClusterManagementaddons`. See the following example:
`addonsDeploymentConfigs` -> `AddOnDeploymentConfig`
`ClusterManagementaddons` -> `ClusterManagementAddOn`

2024-07-16 14:15 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +apiVersion: addons.open-cluster-management.io/v1alpha1
```
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ClusterManagementAddOn
metadata:
  name: work-manager
spec:
  addOnMeta:
    displayName: work-manager
  installStrategy:
    placements:
    - name: global
      namespace: open-cluster-management-global-set
      rolloutStrategy:
        type: All
      configs:
      - group: addon.open-cluster-management.io
        name: addon-ns-config
        namespace: multicluster-engine
        resource: addondeploymentconfigs
    type: Placements
```

addons -> remove `s`

2024-07-16 14:15 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +.. Add the `addonsDeploymentConfig` to the `managed-serviceaccount`. See the following example:
`addonsDeploymentConfig` -> `AddOnDeploymentConfig`

2024-07-16 14:15 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +apiVersion: addons.open-cluster-management.io/v1alpha1
```
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ClusterManagementAddOn
metadata:
  name: managed-serviceaccount
spec:
  addOnMeta:
    displayName: managed-serviceaccount
  installStrategy:
    placements:
    - name: global
      namespace: open-cluster-management-global-set
      rolloutStrategy:
        type: All
      configs:
      - group: addon.open-cluster-management.io
        name: addon-ns-config
        namespace: multicluster-engine
        resource: addondeploymentconfigs
    type: Placements
```

Replace the whole YAML, do not change addon -> addons

2024-07-16 14:15 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +        name: addons-ns-config
Just replace the whole YAML with this and do not change anything in the YAML

```
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ClusterManagementAddOn
metadata:
  name: cluster-proxy
spec:
  addOnMeta:
    displayName: cluster-proxy
  installStrategy:
    placements:
    - name: global
      namespace: open-cluster-management-global-set
      rolloutStrategy:
        type: All
      configs:
      - group: addon.open-cluster-management.io
        name: addon-ns-config
        namespace: multicluster-engine
        resource: addondeploymentconfigs
    type: Placements
```

2024-07-16 14:15 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +* For your `addons-ns-config`, run the following command:
addons-ns-config -> addon-ns-config

2024-07-16 14:15 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +* For your `hypershift-addons-deploy-config`, run the following command:
hypershift-addons-deploy-config -> hypershift-addon-deploy-config

2024-07-16 14:15 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +. Run the following command to set the `agentInstallNamespace` namespace of the add-on to `open-cluster-management-agent-addons-discovery`:
`open-cluster-management-agent-addons-discovery` -> `open-cluster-management-agent-addon-discovery`

2024-07-16 14:15 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +oc patch addonsdeploymentconfig hypershift-addons-deploy-config -n multicluster-engine --type=merge -p '{"spec":{"agentInstallNamespace":"open-cluster-management-agent-addons-discovery"}}'
oc patch addondeploymentconfig hypershift-addon-deploy-config -n multicluster-engine --type=merge -p '{"spec":{"agentInstallNamespace":"open-cluster-management-agent-addon-discovery"}}'

2024-07-16 14:15 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +oc patch addonsdeploymentconfig hypershift-addons-deploy-config -n multicluster-engine --type=merge -p '{"spec":{"customizedVariables":[{"name":"disableMetrics","value": "true"},{"name":"disableHOMan
oc patch addondeploymentconfig hypershift-addon-deploy-config -n multicluster-engine --type=merge -p '{"spec":{"customizedVariables":[{"name":"disableMetrics","value": "true"},{"name":"disableHOManagement","value": "true"}]}}'

2024-07-16 14:15 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +clusteradm addons enable --names hypershift-addon --clusters <managed-cluster-names>
clusteradm addon enable --names hypershift-addon --clusters <managed-cluster-names>

2024-07-16 14:15 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +oc get deployment -n open-cluster-management-agent-addons-discovery
oc get deployment -n open-cluster-management-agent-addon-discovery

2024-07-16 14:15 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +klusterlet-addons-workmgr            1/1     1            1           24h
klusterlet-addon-workmgr

2024-07-16 14:15 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +hypershift-addons-agent              1/1     1            1           24h
hypershift-addon-agent

2024-07-16 14:15 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +managed-serviceaccount-addons-agent  1/1     1            1           24h
managed-serviceaccount-addon-agent

2024-07-16 17:51 UTC, rokej commented on clusters/acm_integration/acm_discover_hosted.adoc
> +
In this entire backup and restore section, we added the backup label to six resources in three different resource kinds. To verify that the backup label is added to all six resources, you can run these commands.

```
oc get addondeploymentconfig -l 'cluster.open-cluster-management.io/backup=true' -A
oc get clustermanagementaddon -l 'cluster.open-cluster-management.io/backup=true' -A
oc get KlusterletConfig -l 'cluster.open-cluster-management.io/backup=true' -A
```

2024-07-16 19:01 UTC, swopebe commented on clusters/acm_integration/acm_discover_hosted.adoc
> +.. Add the `addonsDeploymentConfig` to the `cluster-proxy` add-ons. See the following example:
Perfect! Looks great.

2024-07-16 20:11 UTC, swopebe commented
I did not mean to add and S to those addons -- first I tried to catch the content up with IBM standards, but that changed all your YAML, in turning it back, I accidentally added an s.

2024-07-16 20:26 UTC, swopebe commented on clusters/acm_integration/acm_discover_hosted.adoc
> +----
but this is not grayed out like it should be so that is another issue here

2024-07-16 20:33 UTC, swopebe commented on clusters/acm_integration/acm_discover_hosted.adoc
> +. From your {product-title-short} cluster, create a `ManagedCluster` resource manually to import an {mce-short} cluster. See the following file example:
@dockerymick I see you are trying to make this concise. In an ACM topic, you are right to get rid of unnecessary instructions bc the user is in their ACM cluster, but here we have ACM and MCE....it is an integration topic. I think this needs to stay, as it was designed to orient the user.

2024-07-16 20:55 UTC, swopebe commented on clusters/acm_integration/acm_discover_hosted.adoc
> +Next, visit xref:../acm_integrate_import_hcp.adoc#auto-import-hcp[Automating import for discovered hosted clusters] to learn how to automatically import clusters.
@dockerymick Ok. I think it is best to understand _why_ when these things pop up, that is why I asked. Seems we don't have an answer right now.

2024-07-16 20:55 UTC, swopebe commented on clusters/acm_integration/acm_discover_hosted.adoc
> +You can view your discovered clusters in the console.
This is not a verification step.

2024-07-16 20:56 UTC, swopebe commented on clusters/acm_integration/acm_discover_hosted.adoc
> +After all your {mce-short} clusters are imported into {product-title-short}, you need to enable the hypershift add-on for those managed {mce-short} clusters to discover the hosted clusters.
Good to catch these. 

To give you some context:

This was my draft to work off of, but the issue had numerous links to start from and we changed it a lot.

 https://github.com/stolostron/hypershift-addon-operator/blob/main/docs/discovering_hostedclusters.md#auto-importing-the-discovered-hosted-clusters

2024-07-16 21:00 UTC, swopebe commented on clusters/acm_integration/acm_discover_hosted.adoc
> +You can view your discovered clusters in the console.
Keeping as-is, I can look at organization again in the future.

2024-07-16 21:04 UTC, swopebe commented on clusters/acm_integration/acm_integrate_import_hcp.adoc
> +----
Not sure, I will look at it in the source, though.

2024-07-16 21:08 UTC, swopebe commented on clusters/acm_integration/acm_discover_hosted.adoc
> +
I cannot get this in today.

2024-07-16 21:10 UTC, swopebe commented on clusters/acm_integration/acm_integrate_import_hcp.adoc
> +
This is not the time to add it, I created all the verification steps I could from the draft and asked for them last week, but we will have to push and add later if needed. We don't always have them.

2024-07-16 21:10 UTC, swopebe commented on clusters/acm_integration/acm_integrate_import_hcp.adoc
> +
see above

2024-07-16 21:10 UTC, swopebe commented on clusters/acm_integration/acm_integrate_import_hcp.adoc
> +
This is still an issue.

2024-07-16 21:14 UTC, swopebe commented on clusters/acm_integration/acm_integrate_import_hcp.adoc
> +
This is showing green but it is not rendering correctly in VS Code.

2024-07-16 21:41 UTC, dockerymick commented on clusters/acm_integration/acm_discover_hosted.adoc
> +
@swopebe no worries, like you mentioned you can get this is later

2024-07-16 21:49 UTC, dockerymick commented on clusters/acm_integration/acm_discover_hosted.adoc
> +
```suggestion
To manually import an {mce-short} cluster from your {product-title-short} cluster, complete the following procedure:

. From your {product-title-short} cluster, create a `ManagedCluster` resource manually to import an {mce-short} cluster. See the following file example:

```

2024-07-16 21:50 UTC, dockerymick commented on clusters/acm_integration/acm_discover_hosted.adoc
> +----
```suggestion
 +
See the following example output that lists the add-ons:

+
[source,bash]
----
NAME                                 READY   UP-TO-DATE   AVAILABLE   AGE
cluster-proxy-proxy-agent            1/1     1            1           24h
klusterlet-addon-workmgr            1/1     1            1           24h
hypershift-addon-agent              1/1     1            1           24h
managed-serviceaccount-addon-agent  1/1     1            1           24h
----
```

2024-07-16 21:56 UTC, dockerymick commented on clusters/acm_integration/acm_integrate_import_hcp.adoc
> +
Just took a look and it looks good from my end: 
<img width="1436" alt="Screenshot 2024-07-16 at 5 55 54 PM" src="https://github.com/user-attachments/assets/87ecafa9-b8ec-4248-88a0-ed1278c6bd88">

2024-07-16 21:59 UTC, dockerymick commented on clusters/acm_integration/acm_integrate_intro.adoc
> +* link:../clusters/acm_integration/acm_integrate_observe.adoc#mce-acm-observability[Observability integration]
<img width="1126" alt="Screenshot 2024-07-16 at 5 58 24 PM" src="https://github.com/user-attachments/assets/aac1971d-48d4-40db-8c65-13c0f90def16">

2024-07-16 22:00 UTC, dockerymick commented on clusters/acm_integration/acm_integrate_intro.adoc
> +* link:../clusters/acm_integration/acm_integrate_observe.adoc#mce-acm-observability[Observability integration]
Filenames are correct, I believe we just need the absolute path
```suggestion
See the following procedures for {mce-short} and {product-title-short} multicluster management:

* link:../../clusters/acm_integration/acm_discover_hosted.adoc#discover-hosted-acm[Discovering {mce-short} hosted clusters in {product-title-short}]
* link:../../clusters/acm_integration/acm_integrate_import_hcp.adoc#auto-import-hcp[Automating import for discovered hosted clusters]
* link:../../clusters/acm_integration/acm_integrate_import_rosa.adoc#import-discover-rosa[Automating import for discovered {rosa} clusters]
* link:../../clusters/acm_integration/acm_integrate_observe.adoc#mce-acm-observability[Observability integration]
```

2024-07-16 22:01 UTC, dockerymick commented on clusters/acm_integration/acm_integrate_intro.adoc
> +* link:../clusters/acm_integration/acm_integrate_observe.adoc#mce-acm-observability[Observability integration]
Confirmed that this suggestion will work:
<img width="1646" alt="Screenshot 2024-07-16 at 6 01 00 PM" src="https://github.com/user-attachments/assets/3f63eec2-6c5d-47ef-b0ba-164478166b50">

2024-07-16 22:04 UTC, dockerymick commented on clusters/release_notes/whats_new.adoc
> +* You can now discover and automate the import of hosted clusters, as well. Configure  {product-title-short} to import {mce-short} clusters and then use policy enforcement for automation. Learn more
same suggestion about adding `../`
```suggestion
* You can now automate the import of {rosa} clusters by using {product-title-short} policy enforcement with {mce-short} for faster cluster management. Learn more at link:../../clusters/acm_integration/acm_integration_import_rosa.adoc#import-discover-rosa[Automating import for discovered {rosa} clusters].

* You can now discover and automate the import of hosted clusters, as well. Configure  {product-title-short} to import {mce-short} clusters and then use policy enforcement for automation. Learn more at xref:../../clusters/acm_integration/acm_discover_hosted.adoc#discover-hosted-acm[Automating import for discovered hosted clusters].
```

2024-07-16 22:05 UTC, dockerymick commented on clusters/release_notes/whats_new.adoc
> +* You can now automate the import of {rosa} clusters by using {product-title-short} policy enforcement with {mce-short} for faster cluster management. Learn more at link:../../clusters/acm_integratio
```suggestion
* You can now automate the import of {rosa} clusters by using {product-title-short} policy enforcement with {mce-short} for faster cluster management. Learn more at link:../../clusters/acm_integration/acm_integrate_import_rosa.adoc#import-discover-rosa[Automating import for discovered {rosa} clusters].
```

2024-07-16 22:07 UTC, dockerymick approved these changes
Went through and resolved conversations, and checked all links. Made updates where necessary with @cadawson

THIS LOOKS GREAT!

2024-07-17 13:05 UTC, swopebe commented on clusters/acm_integration/acm_discover_hosted.adoc
> +
I have to open an issue for a diagram anyway.

2024-07-17 13:25 UTC, swopebe commented on clusters/acm_integration/acm_integrate_intro.adoc
> +* link:../clusters/acm_integration/acm_integrate_observe.adoc#mce-acm-observability[Observability integration]
These are green. I actually forgot to check these yesterday, but was more focused on the two major files, but green now. Thanks for your help. I want to check to see how these should be built in the same book.

2024-07-17 14:09 UTC, rokej reviewed
@swopebe Everything looks good. Thank you so much. I just have one more thing I want to add.

2024-07-17 14:09 UTC, rokej commented on clusters/acm_integration/acm_integrate_import_hcp.adoc
> +
I want to give a little more context about why a user is doing this step which is documented herehttps://github.com/rokej/hypershift-addon-operator/blob/main/docs/discovering_hostedclusters.md#auto-importing-the-discovered-hosted-clusters. We can change that a little bit and say...

Discovered hosted clusters from managed MCE clusters are represented by `DiscoveredCluster` custom resources located in the managed MCE cluster's namespace in ACM. It looks like this for example.

```
apiVersion: discovery.open-cluster-management.io/v1
kind: DiscoveredCluster
metadata:
  creationTimestamp: "2024-05-30T23:05:39Z"
  generation: 1
  labels:
    hypershift.open-cluster-management.io/hc-name: hosted-cluster-1
    hypershift.open-cluster-management.io/hc-namespace: clusters
  name: hosted-cluster-1
  namespace: mce-1
  resourceVersion: "1740725"
  uid: b4c36dca-a0c4-49f9-9673-f561e601d837
spec:
  apiUrl: https://a43e6fe6dcef244f8b72c30426fb6ae3-ea3fec7b113c88da.elb.us-west-1.amazonaws.com:6443
  cloudProvider: aws
  creationTimestamp: "2024-05-30T23:02:45Z"
  credential: {}
  displayName: mce-1-hosted-cluster-1
  importAsManagedCluster: false
  isManagedCluster: false
  name: hosted-cluster-1
  openshiftVersion: 0.0.0
  status: Active
  type: MultiClusterEngineHCP
```

These discovered hosted clusters are not automatically imported into ACM until the `spec.importAsManagedCluster` field is set to `true`. This section describes how to use an ACM policy to automatically set this field to true for all `MultiClusterEngineHCP` type `DiscoveredCluster` resources so that discovered hosted clusters are immediately automatically imported into ACM.

2024-07-17 14:09 UTC, rokej commented on clusters/acm_integration/acm_integrate_import_hcp.adoc
> +Configure your `DiscoveredCluster` custom resource to import all your discovered hosted clusters automatically. Log in to your hub cluster from the CLI to complete the following procedure:
Configure your `DiscoveredCluster` custom resource  ---> Configure your policy

2024-07-17 14:42 UTC, dockerymick commented on clusters/acm_integration/acm_integrate_import_hcp.adoc
> +These discovered hosted clusters are not automatically imported into {product-title-short} until the `spec.importAsManagedCluster` field is set to `true`. Learn how to use a {product-title-short} pol
```suggestion
These discovered hosted clusters are not automatically imported into {product-title-short} until the `spec.importAsManagedCluster` field is set to `true`. Learn how to use a {product-title-short} policy to automatically set this field to `true` for all `type.MultiClusterEngineHCP` within `DiscoveredCluster` resources so that discovered hosted clusters are immediately automatically imported into {product-title-short}.
```

2024-07-17 14:46 UTC, rokej commented on clusters/acm_integration/acm_integrate_import_hcp.adoc
> +Discovered hosted clusters from managed {mce-short} clusters are represented in `DiscoveredCluster` custom resources, which are located in the managed {mce-short} cluster namespace in {product-title-
See the following `DiscoveredCluster` resource as an example:

2024-07-17 14:47 UTC, swopebe commented on clusters/acm_integration/acm_integrate_import_hcp.adoc
> +Discovered hosted clusters from managed {mce-short} clusters are represented in `DiscoveredCluster` custom resources, which are located in the managed {mce-short} cluster namespace in {product-title-
we should have caught that.

2024-07-17 14:48 UTC, merged