https://issues.redhat.com/browse/ACM-12584 Errata for ACM 2.10.4 and …
open-cluster-management/rhacm-docs pull request #6640
Opened 2024-07-09 17:19 UTC by cadawson

…MCE 2.5.5

2024-07-09 20:20 UTC, swopebe requested changes

2024-07-09 20:20 UTC, swopebe commented on clusters/release_notes/errata.adoc
> +* Fixes an issue that caused single-node OpenShift managed clusters to show an `unknown` status after upgrading to {product-title-short} version 2.10.3. (link:https://issues.redhat.com/browse/ACM-125
@cadawson should we be discussing ACM in the MCE release notes?

2024-07-09 20:28 UTC, cadawson commented on clusters/release_notes/errata.adoc
> +* Fixes an issue that caused single-node OpenShift managed clusters to show an `unknown` status after upgrading to {product-title-short} version 2.10.3. (link:https://issues.redhat.com/browse/ACM-125
Good point. It happens when you move up to ACM 2.10.3, but that might be because of the MCE 2.5.3 and 2.5.4. If so, better to mention MCE only.

2024-07-09 20:38 UTC, swopebe commented on clusters/release_notes/errata.adoc
> +* Fixes an issue that caused single-node OpenShift managed clusters to show an `unknown` status after upgrading to {product-title-short} version 2.10.3. (link:https://issues.redhat.com/browse/ACM-125
Is that a question you are raising before this entry and also, remember there is a cluster section of the ACM release notes for the cross-functional things that we have used in the past.

2024-07-10 16:05 UTC, swopebe commented on release_notes/errata.adoc
> +* Added a YAML separator to separate the `Subscription` and `PlacementRule` YAML content, which caused the content to be incorrectly parsed. (link:https://issues.redhat.com/browse/ACM-12133[ACM-12133
@cadawson the verbs you write here should align with the rest of the doc. Most if us are using present here, as per the IBM style manual. Notice that you switch to past and present here.

2024-07-10 16:07 UTC, swopebe commented on release_notes/errata.adoc
> +* Added a YAML separator to separate the `Subscription` and `PlacementRule` YAML content, which caused the content to be incorrectly parsed. (link:https://issues.redhat.com/browse/ACM-12133[ACM-12133
Tense
Write in the simple present tense as much as possible.

Incorrect example When you open the latch, the panel will slide forward.
Correct example When you open the latch, the panel slides forward.

Use past or future tense only when you cannot use present tense or it does not make sense to use present tense.

https://www.ibm.com/docs/en/ibm-style?topic=grammar-verbs#tense

2024-07-10 16:21 UTC, rhaignere approved these changes
LGTM, thanks for helping to ensure that we are documenting everything correctly!

2024-07-10 16:44 UTC, cadawson commented on clusters/release_notes/errata.adoc
> +* Fixes an issue that caused single-node OpenShift managed clusters to show an `unknown` status after upgrading to {product-title-short} version 2.10.3. (link:https://issues.redhat.com/browse/ACM-125
Updated this to be MCE-specific.

2024-07-10 16:47 UTC, cadawson commented on release_notes/errata.adoc
> +* Added a YAML separator to separate the `Subscription` and `PlacementRule` YAML content, which caused the content to be incorrectly parsed. (link:https://issues.redhat.com/browse/ACM-12133[ACM-12133
You are right. I fixed that. Thanks!

2024-07-10 17:05 UTC, swopebe approved these changes

2024-07-11 03:55 UTC, dockerymick reviewed
small update

2024-07-11 03:55 UTC, dockerymick commented on clusters/release_notes/errata.adoc
> +* Fixes an issue that caused single-node OpenShift managed clusters to show an `unknown` status after upgrading to {mce-short} version 2.5.3 or version 2.5.4. (link:https://issues.redhat.com/browse/A
Use conref
```suggestion
* Fixes an issue that caused {sno} managed clusters to show an `unknown` status after upgrading to {mce-short} version 2.5.3 or version 2.5.4. (link:https://issues.redhat.com/browse/ACM-12584[ACM-12584])
```

2024-07-11 08:28 UTC, oafischer commented
Is this ready to be merged? Asking for refresh reasons.

2024-07-11 13:03 UTC, merged

2024-07-11 13:04 UTC, cadawson commented
This is now merged. Yes, these are out.