improved and added steps for restore hub
open-cluster-management/rhacm-docs pull request #6647
Opened 2024-07-10 16:02 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-12627

2024-07-10 16:04 UTC, jc-berger commented on business_continuity/backup_restore/backup_install.adoc
> +. The restore hub cluster must use the same {product-title-short} version that the backup hub cluster uses. You cannot restore a backup on a hub cluster with a {product-title-short} version older tha
Given how many sub steps there are here, perhaps we should have a designated section for the restore hub and backup hub cluster versions. Something like: 

= Ensuring  restore and backup hub clusters use the same version 

The restore hub cluster must use the same {product-title-short} version that the backup hub cluster uses. You cannot restore a backup on a hub cluster with a {product-title-short} version older than the one used by the backup hub cluster. If you want to run the restore operation on a hub cluster that has a {product-title-short} version newer than the cluster hub where the backup was created, complete the following: 

1. On the restore hub....
2. Continue with all the sub steps. 

Thoughts?

2024-07-10 18:50 UTC, swopebe commented on business_continuity/backup_restore/backup_install.adoc
> +. The restore hub cluster must use the same {product-title-short} version that the backup hub cluster uses. You cannot restore a backup on a hub cluster with a {product-title-short} version older tha
Substeps are OK only if the higher step has a #2 -- similar to bullets. We want a peer to match it.

2024-07-10 20:40 UTC, birsanv approved these changes
lgtm

2024-07-11 13:28 UTC, swopebe requested changes
Mostly we need brevity on this procedure, and there are some small corrections I have requested.

2024-07-11 13:28 UTC, swopebe commented on business_continuity/backup_restore/backup_install.adoc
> +. The restore hub cluster must use the same {product-title-short} version that the backup hub cluster uses. You cannot restore a backup on a hub cluster with a {product-title-short} version older tha
Goodness this content is long. This goes back to the "walls of text" that is in the content feedback I showed you guys. I see an entire procedure in this:

`Manually install the cluster backup and restore operator. Enable the cluster backup and restore operator (`cluster-backup`). Edit the `MultiClusterHub` resource by setting the `cluster-backup` parameter to `true`. If this hub cluster does not have the AWS Security Token Service (STS) option enabled, the OADP operator is also installed in the same namespace with the backup component. For hub clusters where the STS option is enabled, you must manually install the OADP operator.`

2024-07-11 13:28 UTC, swopebe commented on business_continuity/backup_restore/backup_install.adoc
> +.. On the restore hub, install the {product-title-short} operator at the same version as the {product-title-short} hub where the backup was created.
we don't say hub, but rather hub cluster. Hub can mean multiple things when translated. The word _hub_ is the modifier of the noun, _cluster_.

2024-07-11 13:28 UTC, swopebe commented on business_continuity/backup_restore/backup_install.adoc
> +.. On the restore hub, install the {product-title-short} operator at the same version as the {product-title-short} hub where the backup was created.
this is throughout this set of steps.

2024-07-11 13:28 UTC, swopebe commented on business_continuity/backup_restore/backup_install.adoc
> +.. On the restore hub, use the {product-title-short} upgrade operation to upgrade {product-title-short} to the version you want to use.
you only need to use the product name here once...they are already in the product upgrade procedure and in the product doc. This line can be more concise.

2024-07-11 13:28 UTC, swopebe commented on business_continuity/backup_restore/backup_install.adoc
>  .. Manually configure the hub cluster and install all operators on the active hub cluster and in the same namespace as the active hub cluster.
line 36 can be reduced and condensed, as well

2024-07-11 13:28 UTC, swopebe commented on business_continuity/backup_restore/backup_install.adoc
>  .. Verify that other operators, like: {aap-short}, {ocp} GitOps, or certificate manager, are installed. By verifying, you ensure that the new hub cluster is configured the same way as the initial hub
line 37 remove colon, don't use "like", punctuate with the comma and use "such as," and please use the short form of the conref or this line becomes much longer than needed. We need brevity all throughout this file but we can start with these steps.

For instance, you can remove: _By verifying, you_

2024-07-11 13:28 UTC, swopebe commented on business_continuity/backup_restore/backup_install.adoc
>  .. Ensure that the passive hub cluster uses the same namespace name as the initial hub cluster when you install the backup and restore operator and any operators that are configured on the previous h
you can just say: uses the same namespace, this line could also use some condensing. It's a bit hard to follow.

2024-07-11 17:35 UTC, swopebe commented on business_continuity/backup_restore/backup_install.adoc
> +.. On the restore hub, install the {product-title-short} operator at the same version as the {product-title-short} hub where the backup was created.
oh, we don't say "older" either -- I raised this a while a go. Remember? Negative connotations about versioning.

Earlier, previous, later,

2024-07-15 15:12 UTC, birsanv approved these changes
lgtm

2024-07-15 15:33 UTC, oafischer approved these changes

2024-07-15 15:45 UTC, merged