added known issue for grafana
open-cluster-management/rhacm-docs pull request #6655
Opened 2024-07-11 15:53 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-12592

2024-07-11 16:05 UTC, dockerymick requested changes

2024-07-11 16:05 UTC, dockerymick commented on release_notes/known_issues_global.adoc
> +== The {global-hub} grafana console cannot open with the enabled FIPS environment
```suggestion
== The {global-hub} Grafana console cannot open in a FIPS-enabled environment
```

2024-07-11 16:05 UTC, dockerymick commented on release_notes/known_issues_global.adoc
> +If {global-hub} is running on {ocp-short} 4.16 with the enabled Federal Information Processing Standard (FIPS) environment, you cannot access the grafana console due to the wrong `oauth-proxy` image.
```suggestion
If {global-hub} is running on a FIPS-enabled {ocp-short} 4.16 environment, you cannot access the Grafana console due to the wrong `oauth-proxy` image. {product-title-short} 2.10.4 supports {ocp-short} 4.16, enabling you to get the `oauth-proxy` image from {product-title-short} 2.10.4. 
```

2024-07-11 16:05 UTC, dockerymick commented on release_notes/known_issues_global.adoc
> +. Find the value for `RELATED_IMAGE_OAUTH_PROXY` and replace it with the output you received from Step 1.
Updates for alignment and also is there a verification step? 
```suggestion

. Get the correct `oauth-proxy` image from the `mch-image-manifest-xxx` by running the following:

+
[source,bash]
----
oc get cm -n open-cluster-management mch-image-manifest-xxx -ojsonpath={.data.oauth_proxy_416_and_up} 
----

. Update the deployment image in the {global-hub} `clusterserviceversion` (CSV) with the correct image by running the following command: 

+
[source,bash]
----
oc edit csv multicluster-global-hub-operator-rh.v1.1.1 -n multicluster-global-hub 
----

. Find the value for `RELATED_IMAGE_OAUTH_PROXY` and replace it with the output you received from Step 1. 
```

2024-07-12 00:37 UTC, ldpliu commented on release_notes/known_issues_global.adoc
> +If {global-hub} is running on {ocp-short} 4.16 with the enabled Federal Information Processing Standard (FIPS) environment, you cannot access the grafana console due to the wrong `oauth-proxy` image.
I think it's better to use 2.10.X instead of 2.10.4, for future Z-stream release, we do not need to update this version any more.

2024-07-12 00:37 UTC, ldpliu commented on release_notes/known_issues_global.adoc
> +oc edit csv multicluster-global-hub-operator-rh.v1.1.1 -n multicluster-global-hub
It's better to update v1.1.1 to v1.1.x

2024-07-12 06:48 UTC, hchenxa commented on release_notes/known_issues_global.adoc
> +If {global-hub} is running on {ocp-short} 4.16 with the enabled Federal Information Processing Standard (FIPS) environment, you cannot access the grafana console due to the wrong `oauth-proxy` image.
may be use start from 2.10.4? since the issue only exists on 2.10.4+ ACM version.

2024-07-12 14:02 UTC, dockerymick requested changes
Thanks for accepting the suggestions. I have one more suggestion

2024-07-12 14:02 UTC, dockerymick commented on release_notes/known_issues_global.adoc
> +If {global-hub} is running on a FIPS-enabled {ocp-short} 4.16 environment, you cannot access the Grafana console due to the wrong `oauth-proxy` image. {product-title-short} 2.10.x supports {ocp-short
Based on messaging from earlier about specifying OCP versions and to simplify the doc 
```suggestion
If {global-hub} is running on the latest {ocp-short} environment that is FIPS-enabled, you cannot access the Grafana console due to the wrong `oauth-proxy` image. {product-title-short} 2.10.x supports the latest {ocp-short} version, enabling you to get the `oauth-proxy` image from {product-title-short} 2.10.x. 
```

2024-07-15 12:32 UTC, dockerymick requested changes

2024-07-15 12:32 UTC, dockerymick commented on release_notes/known_issues_global.adoc
> +To access your grafana console, manually update the `oauth-proxy` image with the {product-title-short} bundle image. To update the `oauth-proxy` image, complete the following steps:
```suggestion
To access your Grafana console, manually update the `oauth-proxy` image with the {product-title-short} bundle image. To update the `oauth-proxy` image, complete the following steps: 
```

2024-07-15 12:32 UTC, dockerymick commented on release_notes/known_issues_global.adoc
> +. Get the correct `oauth-proxy` image from the `mch-image-manifest-xxx` by running the following:
```suggestion
. Get the correct `oauth-proxy` image from the `mch-image-manifest-xxx` by running the following command. Replace `<.data.oauth_proxy_latestocp>` with your {ocp-short} version:
```

2024-07-15 12:32 UTC, dockerymick commented on release_notes/known_issues_global.adoc
> +oc get cm -n open-cluster-management mch-image-manifest-xxx -ojsonpath={.data.oauth_proxy_416_and_up}
I usually see the less than and greater than signs rather than the curly brackets 
```suggestion
oc get cm -n open-cluster-management mch-image-manifest-xxx -ojsonpath=<.data.oauth_proxy_latestocp> 
```

2024-07-15 15:20 UTC, dockerymick approved these changes
Thanks Jake!

2024-07-15 15:33 UTC, merged