added tech preview content for rbac in observability
open-cluster-management/rhacm-docs pull request #6656
Opened 2024-07-11 17:13 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-12524

2024-07-12 12:41 UTC, jacobbaungard commented on observability/customize_observability.adoc
> +   Verbs: # represents namespaces of managed clusters
```suggestion
   verbs: # represents namespaces of managed clusters
```

Should be lowercase

2024-07-12 15:43 UTC, dockerymick requested changes

2024-07-12 15:43 UTC, dockerymick commented on observability/customize_observability.adoc
> +To restrict metrics access to specific namespaces within the cluster, use fine-grain role based access control (RBAC). Using fine-grain RBAC, you can allow application teams to only view the metrics
From my perspective, metric access (singular) is the subject and restrict is the verb. i would change metrics to metric
```suggestion
To restrict metric access to specific namespaces within the cluster, use fine-grain role-based access control (RBAC). Using fine-grain RBAC, you can allow application teams to only view the metrics for the namespaces that you give them permission to access. 
```

2024-07-12 15:43 UTC, dockerymick commented on observability/customize_observability.adoc
> +You must configure metrics access control on the hub cluster for the users of that hub cluster. On this hub cluster, a `ManagedCluster` custom resource represents every managed cluster. To configure
```suggestion
You must configure metric access control on the hub cluster for the users of that hub cluster. On this hub cluster, a `ManagedCluster` custom resource represents every managed cluster. To configure RBAC and to choose the allowed namespaces, use the rules and action verbs specified in the `ManagedCluster` custom resources. 
```

2024-07-12 15:43 UTC, dockerymick commented on observability/customize_observability.adoc
> +For example, you have an application named, `my-awesome-app`, and this application is on two different managed clusters, `devcluster1` and `devcluster2`. Consequently, the application is deployed int
I recommend monospacing admin or writing out "administrative"
```suggestion
For example, you have an application named, `my-awesome-app`, and this application is on two different managed clusters, `devcluster1` and `devcluster2`. Consequently, the application is deployed into two namespaces on the managed clusters: `AwesomeAppNS1` and `AwesomeAppNS2`. You have an `admin` user group named, `my-awesome-app-admins`, and you want to restrict this user group to only have access to metrics from only these two namespaces on the hub cluster. 
```

2024-07-12 15:43 UTC, dockerymick commented on observability/customize_observability.adoc
> +
```suggestion
. Define a `ClusterRole` resource with permissions to access metrics. Your resource might resemble the following YAML: 

+
[source,yaml]
----
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
 name: awesome-app-metrics-role
rules:
 - apiGroups:
     - "cluster.open-cluster-management.io"
   resources:
     - managedclusters # fixed
   resourceNames: # represents list of managed clusters
     - devcluster1
     - devcluster2
   Verbs: # represents namespaces of managed clusters
     - metrics/AwesomeAppNS1
     - metrics/AwesomeAppNS2
----

. Define a `ClusterRoleBinding` resource that binds the group, `my-awesome-app-admins`, with the `ClusterRole` resource for the `awesome-app-metrics-role`. Your resource might resemble the following YAML: 

+
[source,yaml]
----
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: awesome-app-metrics-role-binding
subjects:
 - kind: Group
   apiGroup: rbac.authorization.k8s.io
   name: my-awesome-app-admins
roleRef:
 apiGroup: rbac.authorization.k8s.io
 kind: ClusterRole
 name: awesome-app-metrics-role
----

. Define separate `ClusterRoles` and `ClusterRoleBindings` resources to represent the different managed clusters in the namespaces. 

```

2024-07-12 15:43 UTC, dockerymick commented on observability/customize_observability.adoc
> +* Users can only select managed clusters and namespaces specified in the `ClusterRole`.
```suggestion
* Users can only select managed clusters and namespaces specified in the `ClusterRole` resource.   
```

2024-07-12 15:43 UTC, dockerymick commented on release_notes/whats_new.adoc
> +* *Technology Preview:* You can configure fine-grain role based access control (RBAC) to restrict metrics access. For an example on how to use RBAC, see link:../observability/customize_observability.
```suggestion
* *Technology Preview:* You can configure fine-grain role-based access control (RBAC) to restrict metric access. For an example on how to use RBAC, see link:../observability/customize_observability.adoc#configure-fine-grain-rbac[Configuring fine-grain RBAC (Technology Preview)].
```

2024-07-12 18:21 UTC, dockerymick commented on observability/customize_observability.adoc
> +   verbs: # represents namespaces of managed clusters
let's also make these callouts instead of keeping them as hashtags. I'm not sure about  the "fixed" comment. I would ask for clarification and delete if it's unnecessary

2024-07-12 18:45 UTC, dockerymick commented on observability/customize_observability.adoc
> +
```suggestion
     - managedclusters: <1>
   resourceNames: <2>
     - devcluster1
     - devcluster2
   verbs: <3> 
     - metrics/AwesomeAppNS1
     - metrics/AwesomeAppNS2
----
<1> The supported parameter values are `fixed` and ... "Im not sure what other parameter value is supported. What does fixed mean?"
<2> Represents the list of managed clusters.
<3> Represents the namespaces of the managed clusters.
```

2024-07-15 14:58 UTC, ch-stark commented on observability/customize_observability.adoc
> +<1> The supported parameter values are `fixed` and ... "Im not sure what other parameter value is supported. What does fixed mean?"
is this sentence expected?  What does fixed mean

2024-07-15 15:19 UTC, jc-berger commented on observability/customize_observability.adoc
> +<1> The supported parameter values are `fixed` and ... "Im not sure what other parameter value is supported. What does fixed mean?"
Thanks @ch-stark for reviewing :) 

The "fixed" comment is kind of a point of confusion for all of us, lol 

What do you think of my new revision where I simply say: 

< 1 > Represents the parameter values for the managed clusters.

2024-07-15 15:22 UTC, ch-stark commented on observability/customize_observability.adoc
> +<1> The supported parameter values are `fixed` and ... "Im not sure what other parameter value is supported. What does fixed mean?"
@jc-berger lgtm thank you

2024-07-15 15:29 UTC, dockerymick commented on observability/customize_observability.adoc
> +. Define a `ClusterRoleBinding` resource that binds the group, `my-awesome-app-admins`, with the `ClusterRole` resource for the `awesome-app-metrics-role`. Your resource might resemble the following
```suggestion

. Define a `ClusterRoleBinding` resource that binds the group, `my-awesome-app-admins`, with the `ClusterRole` resource for the `awesome-app-metrics-role`. Your resource might resemble the following YAML: 
```

2024-07-15 15:30 UTC, dockerymick approved these changes
This looks good to me, I recommend that you get a developer from observability to confirm that the callout descriptions are accurate

2024-07-16 21:45 UTC, dockerymick commented
We will hold on merging this PR until we have a developer approval. @ch-stark thanks for providing your approval! Thanks for your work @jc-berger

2024-07-17 13:32 UTC, jacobbaungard commented on observability/customize_observability.adoc
> +. Define separate `ClusterRoles` and `ClusterRoleBindings` resources to represent the different managed clusters in the namespaces.
For the example scenario I believe no additional resources needs to be added? I think this sentence could be confused to mean that one needs to add more resources to setup fine-grained rbac for the scenario.

If the sentence is meant to explain that one can add similar CR/CRB to setup a different set of user access, I think it the language can be improved a little and we should move it to the end of the section, so that we don't break focus on the specific scenario.

2024-07-17 15:02 UTC, moadz approved these changes
LGTM pending other comments.

2024-07-17 15:02 UTC, moadz commented on observability/customize_observability.adoc
> +For example, you have an application named, `my-awesome-app`, and this application is on two different managed clusters, `devcluster1` and `devcluster2`. The application is deployed into two namespac
nit: Might be clearer that both clusters have the same namespace (as that is more likely) the example gets a little tricky to follow with multiple namespaces like this, and the final effect is the same.

2024-07-25 17:33 UTC, dockerymick approved these changes
@jc-berger I see there are a couple of comments left from development. But this looks good to me

2024-07-25 19:10 UTC, dockerymick commented on observability/customize_observability.adoc
> +For example, you have an application named, `my-awesome-app`, and this application is on two different managed clusters, `devcluster1` and `devcluster2`. These clusters have the same namespace, `Awes
```suggestion
For example, you have an application named, `my-awesome-app`, and this application is on two different managed clusters, `devcluster1` and `devcluster2`. Both clusters are in the `AwesomeAppNS` namespace. You have an `admin` user group named, `my-awesome-app-admins`, and you want to restrict this user group to only have access to metrics from only these two namespaces on the hub cluster. 
```

2024-07-25 19:10 UTC, dockerymick approved these changes
Left a suggestion for you, thanks Jake!

2024-07-25 19:14 UTC, merged