added section for migrating storage
open-cluster-management/rhacm-docs pull request #6657
Opened 2024-07-11 17:55 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-12482

2024-07-11 18:24 UTC, swopebe commented on observability/observability_alerts.adoc
> +.. *Note:* You might need to delete then recreate the `MultiClusterObservability` Operator Pod so that you can create the new `StatefulSet`.
missing punctuation line 169

2024-07-11 18:25 UTC, swopebe commented on observability/observability_alerts.adoc
> +*Note:* Continuing to the next step, you have a risk of loosing ephemeral data. If you want to ensure you do not loose any data, see link:https://access.redhat.com/solutions/6922821[Migrate persisten
losing is misspelled

2024-07-11 18:28 UTC, swopebe commented on observability/observability_alerts.adoc
> +*Note:* Continuing to the next step, you have a risk of loosing ephemeral data. If you want to ensure you do not loose any data, see link:https://access.redhat.com/solutions/6922821[Migrate persisten
A better word here for simplicity, replace ephemeral?

Please write these, just in general, in the clearer format:

**set the `.spec.storageConfig.storageClass` field.** line 160. 

Remove the need for comma by just getting straight to the point. This is a general comment for all the doc.

Line 161 seems off, like a longer command that we should separate?

2024-07-11 18:33 UTC, swopebe requested changes

2024-07-11 18:33 UTC, swopebe commented on observability/observability_alerts.adoc
> +
double check capitalization here with **pod**, I am not sure off the top of my head how we treat that in the doc.

2024-07-11 18:33 UTC, swopebe commented on observability/observability_alerts.adoc
> +.. *Note:* You might need to delete then recreate the `MultiClusterObservability` Operator Pod so that you can create the new `StatefulSet`.
Notes are not steps, but they can append a step if needed. Since you have this built as a step, either can make it imperative or make it a note.

IMO: deleting a pod to recreate a stateful set seems to me like more than a note...how do they know when or if they need to do this?

2024-07-11 18:38 UTC, swopebe commented on observability/observability_alerts.adoc
> +*Note:* Continuing to the next step, you have a risk of loosing ephemeral data. If you want to ensure you do not loose any data, see link:https://access.redhat.com/solutions/6922821[Migrate persisten
loose? (I realize this may be in the drafts from dev, but that is why we have to rewrite our drafts almost all the time -- especially since they don't always have an English background.

Please rewrite this for conciseness:

*Note:* Continuing to the next step, you have a risk of loosing ephemeral data. If you want to ensure you do not loose any data, see....

This should go _with_ the next step, we don't need to preannounce that they are continuing. Simply add it as part of the next step and remove filler words, there are a bunch here:

Example rewrite: 

**To reduce the risk of losing data, see ....**

2024-07-11 18:44 UTC, swopebe requested changes

2024-07-11 18:44 UTC, swopebe commented on observability/observability_alerts.adoc
> +
Other things: We should be capitalizing Observability as a major component of our product. We need to NOT use the word old or older, remember this sends negative connotation to customers about the version they are on or were on. (Previous, earlier)

2024-07-12 10:59 UTC, douglascamata reviewed
In general I think this documentation has to be very clear in stating that it talks about the storage for the PVs (Persistent Volumes) used by the Observability pods.

It cannot be confused with the object storage that is used to store the metrics collected from the clusters.

2024-07-12 16:20 UTC, douglascamata approved these changes
/lgtm

2024-07-15 15:29 UTC, oafischer commented on observability/observability_alerts.adoc
> +.. *Note:* You might need to delete then re-create the `MultiClusterObservability` operator pod so that you can create the new `StatefulSet`.
```suggestion
.. *Note:* You might need to delete, then re-create, the `MultiClusterObservability` operator pod so that you can create the new `StatefulSet`. 
```

2024-07-15 15:30 UTC, oafischer approved these changes
One small suggestion, otherwise looks good

2024-07-15 15:43 UTC, merged

2024-07-22 18:54 UTC, cadawson commented on observability/observability_alerts.adoc
> +. Change the `reclaimPolicy` to `"Retain": `oc patch pv <your-pv-name> -p '{"spec":{"persistentVolumeReclaimPolicy":"Retain"}}'`.
@jc-berger Can you take a quick look at the tics in line 165 and make sure that they look ok? Looks like you might have one extra, but I might be wrong. Thanks!

2024-07-24 14:53 UTC, jc-berger commented on observability/observability_alerts.adoc
> +. Change the `reclaimPolicy` to `"Retain": `oc patch pv <your-pv-name> -p '{"spec":{"persistentVolumeReclaimPolicy":"Retain"}}'`.
@cadawson thanks, Chris! I think we're good. I'm looking at the file in VS Code, as that's a bit easier to see the tics, and it looks good to me: 
![Uploading Screenshot 2024-07-24 at 10.53.47 AM.png…]()