added context to known issue
open-cluster-management/rhacm-docs pull request #6681
Opened 2024-07-16 16:29 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-12722

2024-07-17 13:29 UTC, swopebe commented on clusters/release_notes/known_issues.adoc
> +The converged flow is the default process of provisioning. When you use the `BareMetalHost` resource for the Bare Metal Operator (BMO) to connect your host to a live ISO, the ironic agent runs. First
Please break out the paragraph above. The first, then can even be bullets. See the feedback that Stephanie sent us where engineers want "scannable" text.

2024-07-17 13:33 UTC, swopebe commented on clusters/release_notes/known_issues.adoc
>  . Create the following ConfigMap on the hub cluster:
Double check ConfigMap here

2024-07-17 13:42 UTC, swopebe requested changes

2024-07-17 13:42 UTC, swopebe commented on clusters/release_notes/known_issues.adoc
>  . Create the following ConfigMap on the hub cluster:
Either code, or write as the manual calls us to write. If the file/resource is below, coding it is acceptable.

2024-07-17 13:42 UTC, swopebe commented on clusters/release_notes/known_issues.adoc
> +<1> When you set the parameter value to "false", you also disable any features enabled by the ironic agent.
Please code the value on 410. Almost never (I have never seen it) do we have quotation marks outside of the code. A value is always coded, even if it has these attached to it.

2024-07-17 13:42 UTC, swopebe commented on clusters/release_notes/known_issues.adoc
>  . Create the following ConfigMap on the hub cluster:
Please lowercase the IMPORTANT here. See the way we doc this throughout the doc. 

I am actually working to get this removed from our process. You may recall we discussed this in a doc meeting, and I sent an article/standard on Slack to our team about how this violates accessibility to write in all caps.

2024-07-18 06:23 UTC, dmoessne commented on clusters/release_notes/known_issues.adoc
> +*Important:* When you disable the converged flow, only the Assisted Installer agent runs in the live ISO, reducing the number of open ports and disabling any features enabled by the ironic agent.
Looking at https://github.com/stolostron/rhacm-docs/pull/6684 I think we should rename "ironic agent" to "Ironic Python Agent" to keep the docs consistent.

I wonder if it would be possible to explain which port numbers are needed with and without disabling the converged flow so customers know which ports they need to enable/disable in which direction. 
Looking at the networking requirements table in https://github.com/stolostron/rhacm-docs/blob/8f0504efc01043945573cda2b7195471a2c9b289/clusters/about/mce_networking.adoc we possible can refer to this, given the lines mentioning the "Ironic Python Agent" are the ports in question

2024-07-18 06:37 UTC, dmoessne commented on clusters/release_notes/known_issues.adoc
> +<1> When you set the parameter value to `false`, you also disable any features enabled by the ironic agent.
as mention above "Ironic Python Agent", see https://github.com/stolostron/rhacm-docs/pull/6684

I think it would be helpful to mention what this exactly means with regards to the installation. From the mail thread attached to the Jira issue : " it will also disable any features currently enabled by using the ironic agent (things like preprovisioning disk cleaning, iPXE boot, and BIOS configuration among others). "
I think we should specify which features are disabled and perhaps we can also clarify the "among others" as well to help understanding the impact

2024-07-18 06:40 UTC, dmoessne commented on clusters/release_notes/known_issues.adoc
> +The converged flow is the default process of provisioning. When you use the `BareMetalHost` resource for the Bare Metal Operator (BMO) to connect your host to a live ISO, the ironic agent does the fo
Looking at #6684 I think we should rename "ironic agent" to "Ironic Python Agent" to keep the docs consistent.

2024-07-18 18:51 UTC, dtthuynh approved these changes

2024-07-18 18:53 UTC, dtthuynh commented on clusters/release_notes/known_issues.adoc
> +*Important:* When you disable the converged flow, only the Assisted Installer agent runs in the live ISO, reducing the number of open ports and disabling any features you enabled with the  Ironic Pyt
I think `Ironic Python Agent` is clear enough without specifying agent again afterwards.

2024-07-22 18:50 UTC, dtthuynh approved these changes

2024-07-23 18:47 UTC, merged