https://issues.redhat.com/browse/ACM-12788
open-cluster-management/rhacm-docs pull request #6697
Opened 2024-07-18 17:24 UTC by dockerymick

2024-07-24 07:50 UTC, coleenquadros approved these changes

2024-07-24 09:01 UTC, douglascamata requested changes

2024-07-24 09:01 UTC, douglascamata commented on release_notes/known_issues_observability.adoc
> +If a managed hub cluster with Observability enabled imports an {ocp-short} 3.11 cluster (deprecated) as managed cluster, the metrics are only displayed from the managed cluster.
According to the information in the JIRA, the issue at hand is that metrics from managed clusters running OCP 3.11 won't be collected by ACM Observability and thus they won't be visible from the Hub in any way. 

They will still be collected by the Cluster Monitoring Operator that runs inside the OCP cluster.

2024-07-24 09:01 UTC, douglascamata commented on release_notes/known_issues_observability.adoc
> +//are users able to make updates to change this outcome?
We expect a fix for this to be released in 2.11.1. There's no action required from the customer side besides doing the upgrade when it is available.

2024-07-25 15:11 UTC, dockerymick commented on release_notes/known_issues_observability.adoc
> +If a managed hub cluster with Observability enabled imports an {ocp-short} 3.11 cluster (deprecated) as managed cluster, the metrics are only displayed from the managed cluster.
```suggestion
Metrics from an {ocp-short} 3.11 managed cluster (deprecated) are not displayed from the hub cluster because the metrics are not collected from your {product-title-short} hub cluster.
```

2024-07-25 15:11 UTC, dockerymick commented on release_notes/known_issues_observability.adoc
> +//are users able to make updates to change this outcome?
```suggestion
```

2024-07-25 15:11 UTC, dockerymick commented on release_notes/known_issues_observability.adoc
> +== Metrics are only displayed from {ocp-short} 3.11 managed clusters
```suggestion
== Metrics from {ocp-short} 3.11 managed clusters are not displayed from the hub cluster
```

2024-07-25 15:13 UTC, dockerymick commented
@coleenquadros @douglascamata thanks for the reviews. I made updates based on Douglas' suggestions. When either of you have an opportunity, will you re-review the PR

2024-07-25 18:38 UTC, douglascamata approved these changes
/lgtm

2024-07-30 16:30 UTC, swopebe approved these changes

2024-07-30 16:31 UTC, merged