added context
open-cluster-management/rhacm-docs pull request #6736
Opened 2024-07-31 18:43 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-12867

2024-07-31 18:44 UTC, birsanv approved these changes
lgtm

2024-07-31 19:14 UTC, swopebe commented on business_continuity/backup_restore/backup_validate.adoc
> +If a cluster hub is managed by a global hub cluster, or if it is installed on a managed cluster instance, the self managing option might be disabled by setting the  `disableHubSelfManagement=true`. I
...policy on the cluster hub. Why do we say _cluster hub_ @jc-berger ?

`might be disabled by setting the  `disableHubSelfManagement=true` (meaning might already be, or the user _can_ disable?)

Extra words here so please make concise
`Do this by setting the .....  ` -- Just make this imperative with active voice. `Do this` is also self-referential and can be eliminated. `Set the `is-hub=true` label on the `ManagedCluster`....

Also:

` that represents the managed hub cluster` -- can we just say _local cluster_ here?

While we are here, I think we say this differently in the doc, line 6:

A hub cluster is automatically imported and managed by itself by using the `local-cluster` managed cluster.

I hub cluster that is imported and managing itself is a `local-cluster`, a hub cluster that is managed by itself. "by using the `local-cluster` managed cluster." is a bit confusing to me. (??) We may want to clarify there.

2024-07-31 19:15 UTC, swopebe requested changes
few questions and comments.

2024-08-05 18:43 UTC, jc-berger commented on business_continuity/backup_restore/backup_validate.adoc
> +*Note:* A hub cluster is automatically imported and managed by itself if it uses the `local-cluster` managed cluster. If you disable this by setting `disableHubSelfManagement=true` on the `MultiClust
@birsanv Brandi said the original sentence here was confusing. Am I right that the hub cluster only is automatically imported and manages itself _if_ the hub cluster uses a local-cluster managed cluster?

2024-08-05 19:19 UTC, swopebe commented on business_continuity/backup_restore/backup_validate.adoc
> +*Note:* A hub cluster is automatically imported and managed by itself if it uses the `local-cluster` managed cluster. If you disable this by setting `disableHubSelfManagement=true` on the `MultiClust
@jc-berger we describe a `local-cluster` as a hub that is self-managed. The installation creates a namespace called local-cluster that is reserved for a self-managed hub. (It could be that was not understood at the time of building the content or that this means something else.) 

I see this described different ways, but the simplest is to look at the setting and what it means, then describe it that way:

A hub cluster is automatically imported and self-managed as the `local-cluster`. If you disable self-management by setting `disableHubSelfManagement` to `true`...

Now it could be that we are trying to say: if it uses the `local-cluster` _namespace_?

2024-08-05 19:36 UTC, dockerymick approved these changes
Left comments based on Brandi's review. Otherwise, this looks good to me

2024-08-05 19:36 UTC, dockerymick commented on business_continuity/backup_restore/backup_validate.adoc
> +*Note:* A hub cluster is automatically imported and managed by itself if it uses the `local-cluster` managed cluster. If you disable this by setting `disableHubSelfManagement=true` on the `MultiClust
Based on Brandi's suggestions
```suggestion
*Note:* A hub cluster is automatically imported and self-managed by as the `local-cluster`. If you disable self-management by setting `disableHubSelfManagement` to `true` on the `MultiClusterHub` resource, the `backup-restore-enabled` policy is not placed on the hub cluster and the policy templates do not produce any reports.
```

2024-08-05 19:36 UTC, dockerymick commented on business_continuity/backup_restore/backup_validate.adoc
> +If a hub cluster is managed by a global hub cluster, or if it is installed on a managed cluster instance, the self managing option might get disabled by setting the  `disableHubSelfManagement=true`.
```suggestion
If a hub cluster is managed by a global hub cluster, or if it is installed on a managed cluster instance, the self-management option might get disabled by setting the  `disableHubSelfManagement` to `true`. In this instance, you can still enable the `backup-restore-enabled` policy on the hub cluster. Set the `is-hub=true` label on the `ManagedCluster` resource that represents the local cluster. 
```

2024-08-06 13:25 UTC, dockerymick approved these changes

2024-08-06 14:21 UTC, merged