https://issues.redhat.com/browse/ACM-13088
open-cluster-management/rhacm-docs pull request #6770
Opened 2024-08-08 19:54 UTC by jc-berger

2024-08-08 19:58 UTC, jc-berger commented on governance/gatekeeper_operator/release_notes.adoc
> +
The Jira asks for the `release notes` to be a new file within the new `gatekeeper_operator` folder. 

I didn't see any content for Gatekeeper operator release notes. So for Dev or Doc reviewers, let me know if you have suggestions to expand this content or make it more relevant to users.

2024-08-08 19:59 UTC, jc-berger commented on governance/gatekeeper_operator/requirements.adoc
> +== What's new in {gk-operator} v{gk-version}
Dev reviewers:

The Dev PR had the `What's New` content with this heading. I kept it as it was orginally written. 

Do you think we can simplify it to `What's New`?

2024-08-08 20:01 UTC, jc-berger commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
> +To create, view, and update your {gk-operator} policies, complete the following sections:
Dev reviewers:

Is the content here in the doc, `Managing Gatekeeper operator policies` good? 

There was significant changes to this content within this Dev PR I was given: https://github.com/dhaiducek/rhacm-docs/commit/6aff0a10669ba6f42425fe05fcf64bbf1c5fe755 

Not sure if we can keep this content mostly how the Doc team currently has it within our repo or if it needs to be more like the content provided within the Dev PR.

2024-08-09 02:16 UTC, dockerymick commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
> +Use the {gk-operator} policy to install the {gk-operator} and Gatekeeper on a managed cluster.
This conref doesn't exist
```suggestion
Use the Gatekeeper operator policy to install the Gatekeeper operator and Gatekeeper on a managed cluster. 
```

2024-08-09 02:17 UTC, dockerymick commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
> +- F or an explanation of the optional parameters that can be used for the Gatekeeper operator policy, see link:https://github.com/open-policy-agent/gatekeeper/blob/master/charts/gatekeeper/README.md[
```suggestion
- For an explanation of the optional parameters that can be used for the Gatekeeper operator policy, see link:https://github.com/open-policy-agent/gatekeeper/blob/master/charts/gatekeeper/README.md[Gatekeeper Helm Chart].
```

2024-08-09 02:22 UTC, dockerymick commented on governance/gatekeeper_operator/release_notes.adoc
> +
@jc-berger my mistake, I didn't add the correct note in the description of your issue. The Release notes should include the Operator versioning topic (most likely renamed to Operator versions) and list what's new for GK 3.11, GK 3.14, and GK 3.15

2024-08-09 02:23 UTC, dockerymick commented on governance/gatekeeper_operator/requirements.adoc
> +- <<whats-new-{gk-tag},What's new in {gk-operator} v{gk-version}>>
Reminder, we do not have a conref for Gatekeeper.

2024-08-09 02:24 UTC, dockerymick commented on governance/gatekeeper_operator/channels.adoc
> +The {gk-operator} version aligns with the Open Policy Agent Gatekeeper version, reserving the z-stream for operator updates. For example, a newly released {gk-operator} might start with a version of
This section should be moved to the Release notes based on my comment here: https://github.com/stolostron/rhacm-docs/pull/6770/files#r1710584279

2024-08-09 02:26 UTC, dockerymick commented on governance/gatekeeper_operator/gatekeeper_policy_constraints.adoc
> +- xref:../governance/grc_intro.adoc#governance[Governance].
these links are broken
```suggestion
- xref:../../governance/create_config_pol.adoc#managing-configuration-policies[Managing configuration policies].

- xref:../../governance/grc_intro.adoc#governance[Governance]. 
```

2024-08-09 16:28 UTC, swopebe commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
> +Use the {gk-operator} policy to install the {gk-operator} and Gatekeeper on a managed cluster.
I will work on this conref, please be sure not to copy and paste this from the dev PR.

2024-08-13 19:40 UTC, dhaiducek commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
> +To create, view, and update your {gk-operator} policies, complete the following sections:
@jc-berger That's a point of discussion. From our perspective, using ACM Policies (whether to install the Gatekeeper Operator or deploy Gatekeeper Constraints and ConstraintTemplates) is an ACM topic rather than a Gatekeeper Operator topic.

2024-08-13 19:45 UTC, dhaiducek commented on governance/gatekeeper_operator/requirements.adoc
> +== What's new in {gk-operator} v{gk-version}
Simplifying it is fine, but it looks like the version attributes are being omitted, but we'll need to have some sort of versioned headings since the Gatekeeper Operator isn't released in the same cadence as RHACM, so we'll have multiple versions of the Gatekeeper Operator documented here that will be synced to the supported versions of RHACM.

2024-08-13 19:46 UTC, dhaiducek commented on governance/gatekeeper_operator/requirements.adoc
> +- Operator versioning alignment with the equivalent Open Policy Agent Gatekeeper for greater transparency.
This needs versioned headings, maybe something like:
```suggestion
=== v3.11
- Major upgrade from the previous {gk-operator} version, bringing the equivalent Open Policy Agent Gatekeeper version up to v3.11.
- Operator versioning alignment with the equivalent Open Policy Agent Gatekeeper for greater transparency.

=== v3.14
```

2024-08-13 19:47 UTC, dhaiducek commented on governance/gatekeeper_operator/requirements.adoc
> +- Operator versioning alignment with the equivalent Open Policy Agent Gatekeeper for greater transparency.
And perhaps swap the order to have the most recent version on top?

2024-08-13 19:48 UTC, dhaiducek commented on governance/gatekeeper_operator/requirements.adoc
> +To understand the support you receive from the Gatekeeper operator, see the following lists:
```suggestion
To understand the support you receive from the Gatekeeper operator, see the following list:
```

2024-08-19 18:08 UTC, jc-berger commented on governance/gatekeeper_operator/gatekeeper_operator_overview.adoc
> +The {gate} version aligns with the Open Policy Agent Gatekeeper version, reserving the z-stream for operator updates. For example, a newly released {gate} might start with a version of `v1.2.2` to al
@dhaiducek Doc review suggested moving the == Operator versions section to this overview doc. 

What do you think about adding a link to the release notes here? Something like 

== Operator versions 
< the content > 

For more information about the {gate} and updates to its versions, see the Release Notes(link to release notes)

2024-08-19 18:09 UTC, jc-berger commented on governance/gatekeeper_operator/requirements.adoc
> +== What's new in {gk-operator} v{gk-version}
Thanks, Dale! Let me know what you think of the new organization of this doc and the new heading titles.

2024-08-19 18:11 UTC, jc-berger commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
> +To create, view, and update your {gk-operator} policies, complete the following sections:
@dhaiducek 

Thanks, Dale! 

If it's within the ACM docs, I decided to work with the existing content we have here. 

I edited and revised a lot of it to make it more user focused and adhere to RH style guides. Let me know if you think any content needs updating or changing to be technically accurate.

2024-08-22 18:04 UTC, dhaiducek requested changes
Thanks, @jc-berger! I've left a variety of questions/comments (probably to varied to summarize here 😬 ).

Also, the `governance/gatekeeper_operator/` directory is missing the `modules/` symlink (required to pick up the attributes correctly). You can copy/paste the `modules/` from `governance/` to add it.

2024-08-22 18:04 UTC, dhaiducek commented on governance/gatekeeper_operator/gatekeeper_operator_overview.adoc
> +Gatekeeper is a validating webhook with auditing capabilities. Install Gatekeeper on your {ocp} managed cluster by using the {gate} policy that then installs Gatekeeper on your managed cluster by usi
Primarily this is an operator doc, so I think I'd prefer to raise that path first with the RHACM path after.
```suggestion
Gatekeeper is a validating webhook with auditing capabilities. You can install Gatekeeper on a {ocp} cluster from the {ocp} operator catalog. With {rhacm}, you can install Gatekeeper on your {ocp} managed cluster by using the {gate} policy to install the Red Hat {gate}. After you install Gatekeeper, use it for the following benefits: 
```

2024-08-22 18:04 UTC, dhaiducek commented on governance/gatekeeper_operator/gatekeeper_operator_overview.adoc
> +The {gate} version aligns with the Open Policy Agent Gatekeeper version, reserving the z-stream for operator updates. For example, a newly released {gate} might start with a version of `v1.2.2` to al
Rather than here, maybe move it to the `requirements.adoc` or `channels.adoc` file? It seems to me it'd flow better to have the support statement and then this operator versions content, followed by the release notes link(s), followed by the channels content?

2024-08-22 18:04 UTC, dhaiducek commented on governance/gatekeeper_operator/requirements.adoc
> +== What's new in the {gk-operator} different versions
The attribute needs to be updated. But also should "different" come first?
```suggestion
== What's new in the different {gate} versions
```

2024-08-22 18:04 UTC, dhaiducek commented on governance/gatekeeper_operator/requirements.adoc
> + To understand the requirements for the Gatekeeper operator, see the following resources:
Extra leading space (it's causing `asciidoc` to format it as a code block).

```suggestion
To understand the requirements for the Gatekeeper operator, see the following resources:
```

2024-08-22 18:04 UTC, dhaiducek commented on governance/gatekeeper_operator/requirements.adoc
> +- <<whats-new-{gk-tag},What's new in the {gate} different versions>>
As I understand it, the `{gk-tag}` attribute isn't being used?

2024-08-22 18:04 UTC, dhaiducek commented on governance/gatekeeper_operator/gatekeeper_policy_constraints.adoc
It'd be good to also link to the `gatekeeper_policy_contraints.adoc` file from the "Gatekeeper compliance policy" row of the supported policies:
https://github.com/stolostron/rhacm-docs/blob/8da39b9a50a1b1a971ed89f74d5839f4f3c10aab/governance/supported_policies.adoc?plain=1#L52-L56

2024-08-22 18:04 UTC, dhaiducek commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
> += Managing Gatekeeper operator policies
(Optional) There seem to be instances throughout this file that could use the attribute?
```suggestion
= Managing {gate} policies
```

2024-08-22 18:04 UTC, dhaiducek commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
> +=== Gatekeeper operator custom resource
This section about the Gatekeeper custom resource along with "Configuring _auditFromCache_ for sync details" should be its own section that comes before and lives outside anything about ACM policies.

2024-08-22 18:04 UTC, dhaiducek commented on governance/main.adoc
> +include::gatekeeper_operator/manage_gatekeeper.adoc[leveloffset=+3]
These two need to be switched since the Constraints/ConstraintTemplates are only relevant after Gatekeeper is installed.
```suggestion
include::gatekeeper_operator/manage_gatekeeper.adoc[leveloffset=+3]
include::gatekeeper_operator/gatekeeper_policy_constraints.adoc[leveloffset=+3]
```

2024-08-22 18:04 UTC, dhaiducek commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
> +<3> To manage your webhook operations, use the following values for the `operations` parameter, `"CREATE"`, `"UPDATE"`, `"CONNECT"`, and `"DELETE"`.
These all need a caveat/note that this is available in v3.14+. Maybe lead the footnote with "(Added in v3.14)"?

2024-08-22 18:04 UTC, dhaiducek commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
> +=== Configuring _auditFromCache_ for sync details
This also needs the version caveat.
```suggestion
=== Configuring _auditFromCache_ for sync details (for v3.14+)
```

2024-08-22 18:04 UTC, dhaiducek commented on governance/gatekeeper_operator/gatekeeper_policy_constraints.adoc
>  - The _Related resources_ section is only available when the audit results are generated by Gatekeeper version 3.9 or newer.
The blank line above this is missing the `+` to flow these bullets under the footnotes. (Either that or the `+` needs to be removed before "Notes:" so that the heading flows with the bullets.)

2024-08-22 18:04 UTC, dhaiducek commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
> += Managing Gatekeeper operator policies
It might be clearer to have either RHACM in the title or a word like "installation" in there, like "Managing Gatekeeper operator installation policies" or "Managing the Gatekeeper operator with RHACM policies".
```suggestion
[#managing-rhacm-gatekeeper-operator-policies]
= Managing {acm-short} Gatekeeper operator policies
```

2024-08-22 18:04 UTC, dhaiducek commented on governance/gatekeeper_operator/gatekeeper_policy_constraints.adoc
>  = Integrating Gatekeeper constraints and constraint templates
Maybe add RHACM to the title for clarity (or add this as a section in `manage_gatekeeper.adoc`) so that users can context switch properly?
```suggestion
= Integrating Gatekeeper constraints and constraint templates with {acm-short}
```

2024-08-26 19:06 UTC, jc-berger commented on governance/gatekeeper_operator/gatekeeper_policy_constraints.adoc
>  = Integrating Gatekeeper constraints and constraint templates
@dhaiducek thanks! We try to make titles short. I specified in the first sentence that it's for ACM, do you think that works? 

Also, I can move this content to `manage_gatekeeper.adoc` and remove this as an individual file. However, looking at the Jira, it seems we want users to complete this task (integrating constraints and templates_ _before_ moving onward to the `managing gatekeeper` 

That's not to say we can't change the order. But before I deleted this file and references to it, I wanted to see if you think the change I made here provides enough clarification for the users.

2024-08-26 19:07 UTC, jc-berger commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
> +<3> To manage your webhook operations, use the following values for the `operations` parameter, `"CREATE"`, `"UPDATE"`, `"CONNECT"`, and `"DELETE"`.
Again, we want to keep titles brief. I added this note right at the beginning of the first sentence of this section. 

Does that clarify? I'm happy to work more on it!

2024-08-26 19:09 UTC, jc-berger commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
> +- <<working-custom-resource,Working a {gate} custom resource>>
@dhaiducek like you said, I made these sections on `custom resource` and `configuring sync details` come first, and before the sections on policies. 

Your initial comment said they should "live outside" ACM policies. With that said, do you want me to make these sections as their own, individual docs?

2024-08-26 19:53 UTC, dhaiducek commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
> +<3> To manage your webhook operations, use the following values for the `operations` parameter, `"CREATE"`, `"UPDATE"`, `"CONNECT"`, and `"DELETE"`.
The rest of the YAML does apply to earlier versions--each of these three footnotes happen to be added in 3.14.

2024-08-26 21:46 UTC, dhaiducek reviewed
Thanks for the effort on this, @jc-berger! I've left a few more comments for consideration. Let me know whether it makes sense.

2024-08-26 21:46 UTC, dhaiducek commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
> +- <<working-custom-resource,Working a {gate} custom resource>>
Yes, it'd be best if the "custom resource" and "configuring auditFromCache" were separate from the other sections (they can really be in the same file though since they both involve the Gatekeeper operator custom resource). Prior to the "custom resource" section, there should be some wording to show what the custom resource is for.

For context, the install flow for the Gatekeeper Operator is (without ACM):
- Install from the operator catalog (this installs the operator controller that looks for the custom resource)
- Create the Gatekeeper operator custom resource (this kicks off the Gatekeeper installation using the configuration)

So really the Gatekeeper operator custom resource is an installation configuration. Maybe move/reuse the wording from farther down in the doc?


> Gatekeeper operator is available in the {ocp-short} catalog. See _Adding Operators to a cluster_ in the link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html/operators/administrator-tasks#olm-adding-operators-to-a-cluster[{ocp-short} documentation] for more information.

2024-08-26 21:46 UTC, dhaiducek commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
> +- <<working-custom-resource,Working a {gate} custom resource>>
```suggestion
- <<working-custom-resource,Working with the {gate} custom resource>>
```

2024-08-26 21:46 UTC, dhaiducek commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
> +To install the Gatekeeper operator policy, use the configuration policy controller. During the install, the operator group and subscription pull the Gatekeeper operator to install it in your managed
```suggestion
To install the Gatekeeper operator with {rhacm-short}, use the governance framework. Gatekeeper operator is available in the {ocp-short} catalog. See _Adding Operators to a cluster_ in the link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html/operators/administrator-tasks#olm-adding-operators-to-a-cluster[{ocp-short} documentation] for more information.

To install the Gatekeeper operator policy, use the configuration policy controller. During the install, the operator group and subscription pull the Gatekeeper operator to install it in your managed cluster. Then, the Gatekeeper operator creates a Gatekeeper custom resource to configure Gatekeeper. See the <<gatekeeper-operator-sample,Gatekeeper operator custom resource>> sample.
```

2024-08-26 21:46 UTC, dhaiducek commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
> +To view the status of the Gatekeeper operator policy, see the {acm-short} configuration policy controller because it checks the Gatekeeper operator policy and supports the  `enforce` remediation acti
```suggestion
To view the status of the Gatekeeper operator policy, see the {acm-short} configuration policy controller because it checks the Gatekeeper operator policy and supports the  `enforce` remediation action. When you set the controller to `enforce` it automatically creates the Gatekeeper operator objects on the managed cluster. 
```

2024-08-26 21:46 UTC, dhaiducek commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
> +. Change the value for `complianceType` of the `ConfigurationPolicy` template to `mustnothave`.
```suggestion
. Locate the template that you used to create the Gatekeeper `Constraint` and `ConstraintTemplate`.
. Delete the entries from the list of templates. (Or delete the policy if they're the only templates.)
```

2024-08-26 21:46 UTC, dhaiducek commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
> +. Change the value for `complianceType` of the `ConfigurationPolicy` template to `mustnothave`.
```suggestion
. Locate the `OperatorPolicy` template that you used to create the Subscription CR.
. Change the value for `complianceType` of the `OperatorPolicy` template to `mustnothave`.
```

2024-08-26 21:46 UTC, dhaiducek commented on governance/supported_policies.adoc
>  | Gatekeeper is an admission webhook that enforces custom resource definition-based policies that are run by the Open Policy Agent (OPA) policy engine. See the link:https://open-policy-agent.github.i
```suggestion
| Gatekeeper is an admission webhook that enforces custom resource definition-based policies that are run by the Open Policy Agent (OPA) policy engine. See the link:https://open-policy-agent.github.io/gatekeeper/website/docs/[Gatekeeper] documentation. The {gate} is available for installing Gatekeeper. For more information, see the xref:../gatekeeper_operator/gatekeeper_operator_overview.adoc[{gate} overview]
```

2024-08-26 21:46 UTC, dhaiducek commented on governance/supported_policies.adoc
> +| After deploying Gatekeeper to the clusters, deploy this sample Gatekeeper policy that ensures namespaces that are created on the cluster are labeled as specified. For more information, see, xref:..
```suggestion
| After deploying Gatekeeper to the clusters, deploy this sample Gatekeeper policy that ensures namespaces that are created on the cluster are labeled as specified. For more information, see xref:../gatekeeper_operator/gatekeeper_policy_constraints.adoc#gatekeeper-policy[Integrating Gatekeeper constraints and constraint templates].
```

2024-08-29 20:45 UTC, dhaiducek reviewed
Looking good! This is definitely a giant effort, so I appreciate your enthusiasm and continued endurance in this! I've left some more review comments. Let me know if I'm repeating myself from previously or if anything is unclear!

2024-08-29 20:45 UTC, dhaiducek commented on governance/main.adoc
> +include::gatekeeper_operator/gatekeeper_operator_overview.adoc[leveloffset=+2]
I could be mistaken, but I think this all should be adjusted back up a level so that the Gatekeeper Operator remains its own section rather than embedding it in "Governance"?

```suggestion
include::gatekeeper_operator/gatekeeper_operator_overview.adoc[leveloffset=+1]
```

2024-08-29 20:45 UTC, dhaiducek commented on governance/gatekeeper_operator/gatekeeper_operator_overview.adoc
> +- xref:../gatekeeper_operator/manage_gatekeeper.adoc#managing-gatekeeper-operator-installation-policies[Managing Gatekeeper operator policies]
It looks like I've mentioned this before, so sorry if I'm being repetitive or objectionable. I'd prefer the Gatekeeper custom resource as its own section, and the "Integrating constraints" can come last (since it's a post-install task), so I'm thinking something like:
- Requirements
- Operator channels
- Configuring the Gatekeeper operator
  - Working with the Gatekeeper operator custom resource
  - Configuring auditFromCache for sync details
- Managing Gatekeeper operator policies
  - Installing/Creating/Upgrading/Updating/Deleting policy
- Integrating Gatekeeper constraints and constraint templates

2024-08-29 20:45 UTC, dhaiducek commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
> +To install the Gatekeeper operator with {rhacm-short}, use the governance framework. Gatekeeper operator is available in the {ocp-short} catalog. See _Adding Operators to a cluster_ in the link:https
I think this bit can lead the section, especially if it's a new parent section "Configuring the Gatekeeper operator" (or similarly named) section that contains the "custom resource" and "auditFromCache" sections. That way there's some context to install the operator and then create the custom resource.
```suggestion
To install the Gatekeeper operator with {rhacm-short}, use the governance framework. The {gate} is available in the {ocp-short} catalog. See _Adding Operators to a cluster_ in the link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.16/html/operators/administrator-tasks#olm-adding-operators-to-a-cluster[{ocp-short} documentation] for more information.
```

2024-08-29 20:45 UTC, dhaiducek commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
> +The {gate} custom resource starts the Gatekeeper installation by using the configuration of the operator. If you want to work with a {gate} custom resource, use the following sample YAML:
I've added/swapped some words around here--let me know what you think.
```suggestion
The {gate} custom resource tells the {gate} to start the Gatekeeper installation on the cluster using the given configuration. If you want to work with a {gate} custom resource, use the following sample YAML: 
```

2024-08-29 20:45 UTC, dhaiducek commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
> +*Note:* For versions 3.14 or later, you cam implement the following features to this YAML:
Nice--this works for me!

2024-08-29 20:45 UTC, dhaiducek commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
> +. Save and apply the policy.
Missing a line break, causing the list to run with the paragraph. Also replace "operator" with "constraint"

And sorry if this was my fault, but "constraint" is a category of objects and not an actual API kind, so that particular one shouldn't be surrounded by backticks, only `ConstraintTemplate` should.
```suggestion
To remove the Gatekeeper constraint and `ConstraintTemplate` from your managed cluster, complete the following steps:

. Edit your Gatekeeper constraint or `ConstraintTemplate` policy. 
. Locate the template that you used to create the Gatekeeper `Constraint` and `ConstraintTemplate`.
. Delete the entries from the list of templates. (Or delete the policy if they're the only templates.)
. Save and apply the policy.
```

2024-08-29 20:45 UTC, dhaiducek commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
> +To install the Gatekeeper operator policy, use the configuration policy controller. During the install, the operator group and subscription pull the Gatekeeper operator to install it in your managed
For reference, I worked this out because this invalid reference is noted in the build logs in the PR:
```
asciidoctor: INFO: possible invalid reference: gatekeeper-operator-sample
```
ref: https://github.com/stolostron/rhacm-docs/actions/runs/10581401679/job/29318577426?pr=6770#step:4:5

Looks like there might be another one there that's missing the underscores around `_GitOpsCluster_`
```suggestion
To install the Gatekeeper operator policy, use the configuration policy controller. During the install, the operator group and subscription pull the Gatekeeper operator to install it in your managed cluster. Then, the Gatekeeper operator creates a Gatekeeper custom resource to configure Gatekeeper. See the <<working-custom-resource,Gatekeeper operator custom resource>> sample.
```

2024-08-29 20:45 UTC, dhaiducek commented on governance/gatekeeper_operator/requirements.adoc
> +- <<whats-new,What's new in the {gate} different versions>>
```suggestion
- <<whats-new,What's new in the different {gate} versions>>
- <<operator-versions,Operator versions>>
```

2024-08-29 20:45 UTC, dhaiducek commented on governance/gatekeeper_operator/gatekeeper_operator_overview.adoc
> +*Prerequisite:* You need a {acm} or {ocp} Plus subscription to install Gatekeeper and apply Gatekeeper policies to your cluster. Gatekeeper is only supported on {ocp-short} versions, except for versi
I heard ACM 2.12 is removing support for OCP 3.11, so that portion can be removed.
```suggestion
*Prerequisite:* You need a {acm} or {ocp} Plus subscription to install Gatekeeper and apply Gatekeeper policies to your cluster. Gatekeeper is only supported on {ocp-short} versions, except for version 3.11.
```

2024-08-29 20:45 UTC, dhaiducek commented on governance/gatekeeper_operator/requirements.adoc
> += Requirements
(Optional) I don't have a strong opinion on it, but I'm wondering about the "Requirements" title since we have "Support", "What's new", and "versioning" sections here which to me aren't all "requirements" per se. In ACM this is called "Release notes"--is that what we should call it here?

2024-08-29 20:45 UTC, dhaiducek commented on governance/gatekeeper_operator/requirements.adoc
> +== What's new in the different {gate} versions
We owe you a link for this section. Sorry for the delay on that. 😞

2024-08-29 20:45 UTC, dhaiducek commented on governance/supported_policies.adoc
> +| After deploying Gatekeeper to the clusters, deploy this sample Gatekeeper policy that ensures namespaces that are created on the cluster are labeled as specified. For more information, see xref:../
Nice! The links are great. 😄

2024-08-29 20:45 UTC, dhaiducek commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
> +For versions 3.14 or later, the {gate} exposes a disabled setting in the custom resource definition within the `auditFromCache` audit. If you enable `auditFromCache`, then set `config.gatekeeper.sh`
Looks like there might have been some details that were unclear/lost in translation.
```suggestion
For versions 3.14 or later, the {gate} exposes a setting in the {gate} custom resource for the audit configuration with the parameter `auditFromCache`, which is disabled by default. If you enable `auditFromCache`, then you need to set `config.gatekeeper.sh` with the objects to sync to the cache. For more information, see link:https://open-policy-agent.github.io/gatekeeper/website/docs/audit/#configuring-audit[Configuring Audit] in the Gatekeeper documentation.
```

2024-08-29 20:45 UTC, dhaiducek commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
> +The {gate} collects resources from constraints, and you can install and insert those resources into your config resource. If resources do not exist, use the operator to create config resources.
```suggestion
When `auditFromCache` is set to "Automatic", the {gate} collects resources from constraints and inserts those resources into your config resource. If the config resource does not exist, the operator will create the config resource.
```

2024-08-29 20:45 UTC, dhaiducek commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
> +To configure the `auditFromCache`, complete the following steps:
```suggestion
To configure `auditFromCache` with "Automatic", complete the following steps: 
```

2024-08-29 20:45 UTC, dhaiducek commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
> +. Use the {gate} to add the  `syncOnlys` parameter section to your config file. See the following example:
```suggestion
. See the {gate} adds the `syncOnly` parameter section to your config file. See the following example:
```

2024-08-29 20:45 UTC, dhaiducek commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
> +. Get the explanation of the `sync` setting by running the following command from your terminal:
```suggestion
. Get the explanation of the `auditFromCache` setting by running the following command from your terminal:
```

2024-09-04 12:43 UTC, jc-berger commented on governance/gatekeeper_operator/configure_gatekeeper_operator.adoc
> += Configuring the {gate}
@dhaiducek new config doc added, great suggestion, and apologies I didn't incorporate this change sooner. 

Please let me know what you think :)

2024-09-04 12:44 UTC, jc-berger commented on governance/gatekeeper_operator/requirements.adoc
> += Requirements
Doc reviewers:

Since the Jira explicitly asks for a `Requirements` doc, I've kept it. 

To Dale's point, we don't typically have a `Requirements` doc. Do you want this content to be a `Prerequisite` section in the overview doc?

2024-09-04 12:45 UTC, jc-berger commented on governance/main.adoc
> +include::gatekeeper_operator/gatekeeper_operator_overview.adoc[leveloffset=+1]
Doc reviewers:

Please confirm if my leveloff settings are correct here, thank you :)

2024-09-05 19:14 UTC, dhaiducek reviewed
Thanks! This looks great to me, and I like the new flow with the Gatekeeper custom resource having its own section. I just have a couple minor comments.

2024-09-05 19:14 UTC, dhaiducek commented on governance/gatekeeper_operator/configure_gatekeeper_operator.adoc
> +To install the Gatekeeper operator with {rhacm-short}, use the governance framework. The {gate} is available in the {ocp-short} catalog. See _Adding Operators to a cluster_ in the link:https://access
I think this paragraph can be moved up to lead this section.

2024-09-05 19:14 UTC, dhaiducek commented on governance/gatekeeper_operator/configure_gatekeeper_operator.adoc
> += Configuring the {gate}
Thanks! I really like the new flow. 😄

2024-09-05 19:14 UTC, dhaiducek commented on governance/gatekeeper_operator/configure_gatekeeper_operator.adoc
> +To install the Gatekeeper operator with {rhacm-short}, use the governance framework. The {gate} is available in the {ocp-short} catalog. See _Adding Operators to a cluster_ in the link:https://access
```suggestion
To install the {gate} with {rhacm-short}, use the governance framework. The {gate} is available in the {ocp-short} catalog. See _Adding Operators to a cluster_ in the link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.16/html/operators/administrator-tasks#olm-adding-operators-to-a-cluster[{ocp-short} documentation] for more information.
```

2024-09-05 19:14 UTC, dhaiducek commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
Not sure whether you want to replace all the instances of "Gatekeeper Operator" with the "{gate}" attribute here?

2024-09-05 19:14 UTC, dhaiducek commented on governance/gatekeeper_operator/configure_gatekeeper_operator.adoc
> +Before you can start the {gate} installation, you must configure the {gate} custom resource.
This is a nuanced change, but the operator and Gatekeeper itself are sort of separate installs. Given that, let me know whether this makes sense to you (I'm assuming it'll follow the "To install the Gatekeeper operator..." paragraph):
```suggestion
Once the {gate} is installed, to install Gatekeeper you must configure the {gate} custom resource.
```

2024-09-09 14:54 UTC, dockerymick requested changes

2024-09-09 14:54 UTC, dockerymick commented on governance/gatekeeper_operator/channels.adoc
> +With the `y-stream version` channel, you can access all the z-streams for a particular y-stream. For example, the channel `1.2` could have `v1.2.0`, `v1.2.1`, `v1.2.2`, and more, but it would not inc
I'm a little confused with this file. Maybe we can create a table of the supported z-stream and y-stream for the channels, but I still have concerns about specifying the versions. In the future, it may be difficult to maintain. Maybe we can say something like: "With the `stable` channel, you can access the latest available version, including earlier z-streams if relevant. Y-stream versions that are released after the latest version are not included in the `stable` channel."

There a few statements that are not in present tense.

2024-09-09 14:54 UTC, dockerymick commented on governance/gatekeeper_operator/configure_gatekeeper_operator.adoc
> +Before you can start the {gate} installation, you must configure the {gate} custom resource.
I'm a little confused here too. Do users install the Gatekeeper operator from OCP and then configure the Gatekeeper operator to install Gatekeeper on the hub cluster? 


If yes, I recommend that you write:

"To install Gatekeeper on your hub cluster, install the {gate} from the {ocp} catalog and configure the {acm-short} `Gatekeeper` policy by using the governance framework. The  to start the Gatekeeper installation on your cluster."

2024-09-09 14:54 UTC, dockerymick commented on governance/gatekeeper_operator/configure_gatekeeper_operator.adoc
> +The {gate} custom resource tells the {gate} to start the Gatekeeper installation on the cluster, using the given configuration. To work with a {gate} custom resource, use the following sample YAML:
Based on my previous comment, I recommend that this subsection be renamed to "`Gatekeeper` custom resource sample"

I would also remove this statement, "To configure the {gate}, complete the following sections:" and the TOC  because there are not 3 or more subsections. Earlier, the doc team agreed to only list a child TOC if there were 3 or more sections.

2024-09-09 14:54 UTC, dockerymick commented on governance/gatekeeper_operator/configure_gatekeeper_operator.adoc
> +*Note:* For versions 3.14 or later, you cam implement the following features to this YAML:
Is it necessary to mention the Gatekeeper version here? Just concerned about having to maintain in later acm doc versions. Last I recall in a previous convo, the supported Gatekeeper versions are listed in the description from the console. Wouldn't it mention that Gatekeeper 3.13 is not supported for ACM 2.12? If i am correct, I recommend that this note be removed.

2024-09-09 14:54 UTC, dockerymick commented on governance/gatekeeper_operator/configure_gatekeeper_operator.adoc
> +<1> Enable the `auditEventsInvolvedNamespace` parameter to manage the namespace audit event you want to create. When you enable this parameter, the Gatekeeper controller deployment gets the following
Is the Gatekeeper controller something different or are you referring to the resource?

2024-09-09 14:54 UTC, dockerymick commented on governance/gatekeeper_operator/configure_gatekeeper_operator.adoc
> +<2> Enable the `admissionEventsInvolvedNamespace` parameter to manage the  namespace admission event you want to create. When you enable this parameter, the Gatekeeper controller deployment gets the
Same question here and there is an extra space between "the namespace"

2024-09-09 14:54 UTC, dockerymick commented on governance/gatekeeper_operator/configure_gatekeeper_operator.adoc
> +To install the Gatekeeper operator with {rhacm-short}, use the governance framework. The {gate} is available in the {ocp-short} catalog. See _Adding Operators to a cluster_ in the link:https://access
I agree with Dale and have made earlier comments to help with this. I also recommend that you move this link to end of the file. You can still mention and italicize the title of the reference link, but the actual link should be placed in an "Additional resources" section to reduce the number of inline links in the file. Which OCP version is the Gatekeeper operator tested? Based on the OCP linking guidance in the playbook, we should be pointing to OCP 4.15: https://docs.google.com/document/d/1YTqpZRH54Bnn4WJ2nZmjaCoiRtqmrc2w6DdQxe_yLZ8/edit#heading=h.9fvyr2rdriby

2024-09-09 14:54 UTC, dockerymick commented on governance/gatekeeper_operator/configure_gatekeeper_operator.adoc
> +For versions 3.14 or later, the {gate} exposes a setting in the {gate} custom resource for the audit configuration with the parameter `auditFromCache`, which is disabled by default. If you enable `au
Similar to my earlier comments about specifying the Gatekeeper version. We should avoid this if the supported versions are described from the console. I recommend the following, "The {gate} exposes a setting in the `Gatekeeper` policy for the audit configuration with the parameter `auditFromCache`, which is disabled by default. If you enable `auditFromCache`, then you need to set `config.gatekeeper.sh` with the objects to sync to the cache. For more information, see _Configuring Audit_ in the Gatekeeper documentation.

Reminder to move this link to the "Additional resources" section to reduce the number of inline links.

2024-09-09 14:54 UTC, dockerymick commented on governance/gatekeeper_operator/configure_gatekeeper_operator.adoc
> +When `auditFromCache` is set to "Automatic", the {gate} collects resources from constraints and inserts those resources into your config resource. If the config resource does not exist, the operator
When you set the `auditFromCache` parameter to `Automatic`, the {gate} collects resources from constraints and inserts those resources into your Gatekeeper `Config` resource. If the resource does not exist, the {gate} creates the `Config` resource.

2024-09-09 14:54 UTC, dockerymick commented on governance/gatekeeper_operator/configure_gatekeeper_operator.adoc
> +To configure `auditFromCache` with "Automatic", complete the following steps:
```suggestion
To configure the `auditFromCache` parameter for resource collection from constraints, complete the following steps: 
```

2024-09-09 14:54 UTC, dockerymick commented on governance/gatekeeper_operator/configure_gatekeeper_operator.adoc
> ++
You can remove this plus sign

2024-09-09 14:54 UTC, dockerymick commented on governance/gatekeeper_operator/configure_gatekeeper_operator.adoc
> +. See the {gate} adds the `syncOnly` parameter section to your config file. See the following example:
How does the user access their Gatekeeper `Config` resource? I would add something like, "To verify that the resources are added to your `Config` resource, view that the `syncOnly` parameter section is added. Run the following command:
+
Your `Config` resource might resemble the following example:

2024-09-09 14:54 UTC, dockerymick commented on governance/gatekeeper_operator/configure_gatekeeper_operator.adoc
> +. Get the explanation of the `auditFromCache` setting by running the following command from your terminal:
Why is the explanation needed here? Will it show that it's set to Automatic? Will it show the config resource?

2024-09-09 14:54 UTC, dockerymick commented on governance/gatekeeper_operator/gatekeeper_operator_overview.adoc
> += Gatekeeper operator overview
You can use the conref here: {gate} overview

2024-09-09 14:54 UTC, dockerymick commented on governance/gatekeeper_operator/gatekeeper_operator_overview.adoc
> +Gatekeeper is a validating webhook with auditing capabilities. Install Gatekeeper on a {ocp} cluster from the {ocp} operator catalog. With {acm}, you can install Gatekeeper on your {ocp} managed clus
```suggestion
Gatekeeper is a validating webhook with auditing capabilities. Install Gatekeeper on a {ocp} cluster from the {ocp} operator catalog. With {acm}, you can install Gatekeeper on your {ocp} managed cluster by using the `Gatekeeper` policy to install the Red Hat {gate}. After you install Gatekeeper, use it for the following benefits: 
```

2024-09-09 14:54 UTC, dockerymick commented on governance/gatekeeper_operator/gatekeeper_operator_overview.adoc
> +*Prerequisite:* You need a {acm} or {ocp} Plus subscription to install Gatekeeper and apply Gatekeeper policies to your cluster. Gatekeeper is only supported on {ocp-short} versions, except for versi
Since OCP 3.11 will be removed this released, we don't need to mention it here.

2024-09-09 14:54 UTC, dockerymick commented on governance/gatekeeper_operator/gatekeeper_operator_overview.adoc
> +- xref:../gatekeeper_operator/manage_gatekeeper.adoc#managing-gatekeeper-operator-installation-policies[Managing Gatekeeper operator policies]
Use the conref here: Managing {gate} policies

2024-09-09 14:54 UTC, dockerymick commented on governance/gatekeeper_operator/gatekeeper_policy_constraints.adoc
> +In {acm-short}, if you want to create Gatekeeper policies, write them by using `ConstraintTemplates` and constraints. Add them both to the `policy-templates` of a {product-title-short} `Policy`. View
To create `Gatekeeper` policies, use `ConstraintTemplates` and constraints. Add templates and constraints to the `policy-templates` of a `Policy` resource. View the following YAML examples that use Gatekeeper constraints in {acm-short} policies:

2024-09-09 14:54 UTC, dockerymick commented on governance/gatekeeper_operator/gatekeeper_policy_constraints.adoc
> +- `ConstraintTemplates` and constraints: Use the Gatekeeper integration feature by using {acm-short} policies for multicluster distribution of Gatekeeper constraints and Gatekeeper audit results aggr
I see only one YAML example so we don't need to created an unordered list here. I recommend that you add the asterisk back because the other example is being listed under the Notes.

<img width="1084" alt="Screenshot 2024-09-09 at 10 26 56 AM" src="https://github.com/user-attachments/assets/58488181-7210-4516-9a09-d877d1efa8a5">

* `ConstraintTemplates` and constraints: Use the Gatekeeper integration feature by using {acm-short} policies for multicluster distribution of Gatekeeper constraints and Gatekeeper audit results aggregation on the hub cluster. The following example defines a Gatekeeper `ConstraintTemplate` and the `K8sRequiredLabels` constraint to ensure the `gatekeeper` label is set on all namespaces:

2024-09-09 14:54 UTC, dockerymick commented on governance/gatekeeper_operator/gatekeeper_policy_constraints.adoc
>  With the previous policy, you might receive the following policy status message: `warn - you must provide labels: {"gatekeeper"} (on Namespace default); warn - you must provide labels: {"gatekeeper"}
Change: Once a policy containing Gatekeeper constraints or `ConstraintTemplates` is deleted, the constraints and `ConstraintTemplates` are also deleted from the managed cluster.

TO

When you delete Gatekeeper constraints or `ConstraintTemplates` from a policy, the constraints and `ConstraintTemplates` are also deleted from your managed cluster.

2024-09-09 14:54 UTC, dockerymick commented on governance/gatekeeper_operator/gatekeeper_policy_constraints.adoc
> +- `policy-gatekeeper-admission`: Use the `policy-gatekeeper-admission` configuration policy within a {acm-short} policy to check for Kubernetes API requests denied by the gatekeeper admission webhook
Need to add a break line here and use a asterisks. The example is listed in the Notes

<img width="1084" alt="Screenshot 2024-09-09 at 10 26 56 AM" src="https://github.com/user-attachments/assets/793a1af2-88f6-4da2-baf2-e97131112373">

2024-09-09 14:54 UTC, dockerymick commented on governance/gatekeeper_operator/gatekeeper_policy_constraints.adoc
> +*Note:*
```suggestion
*Notes:* 
```

2024-09-09 14:54 UTC, dockerymick commented on governance/gatekeeper_operator/gatekeeper_policy_constraints.adoc
> +- `policy-gatekeeper-admission`: Use the `policy-gatekeeper-admission` configuration policy within a {acm-short} policy to check for Kubernetes API requests denied by the gatekeeper admission webhook
```suggestion
- `policy-gatekeeper-admission`: Use the `policy-gatekeeper-admission` configuration policy within a {acm-short} policy to check for Kubernetes API requests denied by the Gatekeeper admission webhook. View the following example:
```

2024-09-09 14:54 UTC, dockerymick commented on governance/gatekeeper_operator/gatekeeper_policy_constraints.adoc
>  [#additional-resources-gk]
I was unable to add a comment for the YAML example, but be sure to create callouts for the hidden comments. The hidden comments, which are not really hidden, start with the hashtag. Replace each hashtag with a callout please.

2024-09-09 14:54 UTC, dockerymick commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
> +. <<uninstalling-gatekeeper,Uninstalling Gatekeeper policy, Gatekeeper, and {gate} policy>>
Not sure why these are listed as steps. Is that intentional? I recommend that use the dash to create an unordered list. Also we do not need all the steps for creating the policy from the console. It is straightforward. I recommend only mentioning that the user needs to set their remediation action to `enforce` to install Gatekeeper

2024-09-09 14:54 UTC, dockerymick commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
> +Update the {gate} policy by completing the following:
I know i was the one who organized the file this way. Let's remove this section, remove " <<viewing-gatekeeper-operator-policy-from-the-console,Viewing {gate} policy from the console>>
- <<disabling-gatekeeper-operator-policy,Disabling {gate} policy>>" as childlinks, and make Viewing and Disabling H2 subsections. Reminder about reducing the console steps and to update the TOC on lines 10-15

2024-09-09 14:54 UTC, dockerymick commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
> +If you need to delete your the {gate} policy, you can do so from the CLI or the console.
Remove this line

2024-09-09 14:54 UTC, dockerymick commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
> +----
```suggestion
. Delete {gate} policy by running the following command:

+
[source,bash]
----
oc delete policies.policy.open-cluster-management.io <policy-gatekeeper-operator-name> -n <namespace>
----
```

2024-09-09 14:54 UTC, dockerymick commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
> ++
Remove this plus sign

2024-09-09 14:54 UTC, dockerymick commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
> +----
```suggestion
 . Verify that you deleted your policy by running the following command:

+
[source,bash]
----
oc get policies.policy.open-cluster-management.io <policy-gatekeeper-operator-name> -n <namespace>
----
```

2024-09-09 14:54 UTC, dockerymick commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
> +. From the _Remove policy_ dialog box, click *Remove policy*.
```suggestion
To delete your {gate} policy from the console, click the *Actions* icon for the `policy-gatekeeper-operator` policy and select *Remove*.
```

2024-09-09 14:54 UTC, dockerymick commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
> +To uninstall Gatekeeper policy, complete the following:
```suggestion
To uninstall Gatekeeper policy, complete the steps in the following sections:
```

2024-09-09 14:54 UTC, dockerymick commented on governance/gatekeeper_operator/requirements.adoc
> += Requirements
Based on the issue description, I see that we requested for a Release notes file to include Operator versions and what's new for Gatekeeper 3.11, 3.14, and 3.15. The Gatekeeper requirements file should only include the General support statement.

2024-09-09 14:54 UTC, dockerymick commented on governance/supported_policies.adoc
> +| Gatekeeper is an admission webhook that enforces custom resource definition-based policies that are run by the Open Policy Agent (OPA) policy engine. See the link:https://open-policy-agent.github.i
Reminder to use the conrefs

2024-09-09 14:58 UTC, dhaiducek commented on governance/gatekeeper_operator/channels.adoc
> +With the `y-stream version` channel, you can access all the z-streams for a particular y-stream. For example, the channel `1.2` could have `v1.2.0`, `v1.2.1`, `v1.2.2`, and more, but it would not inc
The version numbers are hypothetical--they aren't actual version numbers and are only there for illustration.

2024-09-09 15:00 UTC, dhaiducek commented on governance/gatekeeper_operator/configure_gatekeeper_operator.adoc
> +*Note:* For versions 3.14 or later, you cam implement the following features to this YAML:
This note is necessary because it's not available in Gatekeeper 3.11. As previously discussed, we plan to sync the Gatekeeper operator doc content to all supported ACM versions (since the Gatekeeper versions don't have an alignment with ACM versions).

2024-09-09 15:02 UTC, dhaiducek commented on governance/gatekeeper_operator/configure_gatekeeper_operator.adoc
> +<1> Enable the `auditEventsInvolvedNamespace` parameter to manage the namespace audit event you want to create. When you enable this parameter, the Gatekeeper controller deployment gets the following
It's different. The argument it's referring to is applied to the Gatekeeper deployment itself.

2024-09-09 15:04 UTC, dhaiducek commented on governance/gatekeeper_operator/configure_gatekeeper_operator.adoc
> +For versions 3.14 or later, the {gate} exposes a setting in the {gate} custom resource for the audit configuration with the parameter `auditFromCache`, which is disabled by default. If you enable `au
With my previous comment, the version caveat is necessary since this doc will be synced to all supported ACM versions.

2024-09-09 15:50 UTC, dhaiducek commented on governance/gatekeeper_operator/configure_gatekeeper_operator.adoc
> +. See the {gate} adds the `syncOnly` parameter section to your config file. See the following example:
Good idea--in that case, the command would be:
```
oc get configs.config.gatekeeper.sh config -n openshift-gatekeeper-system
```

2024-09-09 16:04 UTC, dhaiducek commented on governance/gatekeeper_operator/configure_gatekeeper_operator.adoc
> +. Get the explanation of the `auditFromCache` setting by running the following command from your terminal:
`oc explain` is the command to use to view the descriptions from the CRD that we updated in the code. For this one, it shows:

```
GROUP:      operator.gatekeeper.sh
KIND:       Gatekeeper
VERSION:    v1alpha1

FIELD: auditFromCache <string>

DESCRIPTION:
    AuditFromCache sets whether a cache is used for auditing. The parameter value options are
    Enabled, Disabled, and Automatic. If you set the parameter to Automatic, the Gatekeeper
    operator manages the syncOnly field in the Config resource. It is not recommended to use
    Automatic when using referential constraints since those are not detected.
    See https://open-policy-agent.github.io/gatekeeper/website/docs/sync/#replicating-data-with-config.
```

2024-09-09 16:05 UTC, dhaiducek commented on governance/gatekeeper_operator/gatekeeper_operator_overview.adoc
> +Gatekeeper is a validating webhook with auditing capabilities. Install Gatekeeper on a {ocp} cluster from the {ocp} operator catalog. With {acm}, you can install Gatekeeper on your {ocp} managed clus
I think this should stay as "Gatekeeper operator policy". While it does contain the `Gatekeeper` custom resource, it also contains an OperatorPolicy to install the operator.

2024-09-09 18:47 UTC, jc-berger commented on governance/supported_policies.adoc
> +| Gatekeeper is an admission webhook that enforces custom resource definition-based policies that are run by the Open Policy Agent (OPA) policy engine. See the link:https://open-policy-agent.github.i
Thanks, Mikela! Looks like I used the conref here, unless I'm overlooking something?

2024-09-09 18:48 UTC, jc-berger commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
> +Update the {gate} policy by completing the following:
Cool, let me know what you think of the newly edited and renamed section.

2024-09-09 18:49 UTC, jc-berger commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
> +. <<uninstalling-gatekeeper,Uninstalling Gatekeeper policy, Gatekeeper, and {gate} policy>>
The intent was for users to do them in sequential order, hence, like a procedure with steps to follow. I made them an unordered bullet list :) I also removed most of the content from the `creating policy from the console` section.

2024-09-09 18:50 UTC, jc-berger commented on governance/gatekeeper_operator/gatekeeper_policy_constraints.adoc
>  [#additional-resources-gk]
Hey Mikela, I don't see any hashtags. Not sure what you want me to call out here?

2024-09-09 18:50 UTC, jc-berger commented on governance/gatekeeper_operator/gatekeeper_policy_constraints.adoc
> +- `policy-gatekeeper-admission`: Use the `policy-gatekeeper-admission` configuration policy within a {acm-short} policy to check for Kubernetes API requests denied by the gatekeeper admission webhook
Made them asterisks. The spacing looks fine to me. What do you mean by line break?

2024-09-09 18:52 UTC, jc-berger commented on governance/gatekeeper_operator/requirements.adoc
> += Requirements
Thanks, Mikela, given your comment, you only want the `General Support Statement` content to remain in this `Requirements` doc? 

Did you want the others sections and their content moved elsewhere?

2024-09-09 19:33 UTC, dockerymick requested changes

2024-09-09 19:33 UTC, dockerymick commented on governance/gatekeeper_operator/channels.adoc
> +With the `y-stream version` channel, you can access all the z-streams for a particular y-stream. For example, the channel `1.2` could have `v1.2.0`, `v1.2.1`, `v1.2.2`, and more, but it would not inc
Since it's hypothetical, I highly recommend the following statement: 

"With the stable channel, you can access the latest available version, including earlier z-streams if relevant. Y-stream versions that are released after the latest version are not included in the stable channel."

2024-09-09 19:33 UTC, dockerymick commented on governance/gatekeeper_operator/configure_gatekeeper_operator.adoc
> +After you install the {gate}, to install Gatekeeper you must configure the {gate} custom resource.
Based on the YAML example, I would say Gatekeeper custom resource instead of {gate} custom 
```suggestion
To install Gatekeeper on your hub cluster, install the {gate} from the {ocp} catalog and configure {acm-short} Gatekeeper policy by using the governance framework.
```

2024-09-09 19:33 UTC, dockerymick commented on governance/gatekeeper_operator/gatekeeper_policy_constraints.adoc
> +- `policy-gatekeeper-admission`: Use the `policy-gatekeeper-admission` configuration policy within a {acm-short} policy to check for Kubernetes API requests denied by the gatekeeper admission webhook
There needs to be a new empty line. The `policy-gatekeeper-admission` should start on line 78

2024-09-09 19:33 UTC, dockerymick commented on governance/gatekeeper_operator/configure_gatekeeper_operator.adoc
> +To install the {gate} with {rhacm-short}, use the governance framework. The {gate} is available in the {ocp-short} catalog. See _Adding Operators to a cluster_ in the link:https://access.redhat.com/d
wrong conref being used here (rham-short should be acm-short), but it also seems repetitive to the intro. It seems like we should remove this statement and link to OCP version 4.15.

2024-09-09 19:33 UTC, dockerymick commented on governance/gatekeeper_operator/configure_gatekeeper_operator.adoc
> +For versions 3.14 or later, the {gate} exposes a setting in the {gate} custom resource for the audit configuration with the parameter `auditFromCache`, which is disabled by default. If you enable `au
Thanks for confirming @jc-berger we still need to move the link to the Additional resources section.

2024-09-09 19:33 UTC, dockerymick commented on governance/gatekeeper_operator/configure_gatekeeper_operator.adoc
> +----
Remove this as a step and align after the command

```suggestion
[source,bash]
----
oc get configs.config.gatekeeper.sh config -n openshift-gatekeeper-system
----
+
Your `Config` resource might resemble the following example:

+
[source,yaml]
----
apiVersion: config.gatekeeper.sh/v1alpha1
kind: Config
metadata:
 name: config
 namespace: "openshift-gatekeeper-system"
spec:
 sync:
   syncOnly:
   - group: ""
     version: "v1"
     kind: "Namespace"
   - group: ""
     version: "v1"
     kind: "Pod"
----
```

2024-09-09 19:33 UTC, dockerymick commented on governance/gatekeeper_operator/configure_gatekeeper_operator.adoc
> +. Get the explanation of the `auditFromCache` setting by running the following command from your terminal:
```suggestion
. Get the explanation of the `auditFromCache` setting to view the description of the custom resource by running the following command:
```

2024-09-09 19:33 UTC, dockerymick commented on governance/gatekeeper_operator/gatekeeper_operator_overview.adoc
> +Gatekeeper is a validating webhook with auditing capabilities. Install Gatekeeper on a {ocp} cluster from the {ocp} operator catalog. With {acm}, you can install Gatekeeper on your {ocp} managed clus
Ok thanks for confirming. If I were the user, I probably would be looking for the resource to read "GatekeeperOperator". That's why I made that suggestion

2024-09-09 19:33 UTC, dockerymick commented on governance/gatekeeper_operator/gatekeeper_policy_constraints.adoc
>  [source,yaml]
```suggestion
- The Gatekeeper audit runs every minute by default. Audit results are sent back to the hub cluster to be viewed in the {acm-short} policy status of the managed cluster.

* `policy-gatekeeper-admission`: Use the `policy-gatekeeper-admission` configuration policy within a {acm-short} policy to check for Kubernetes API requests denied by the Gatekeeper admission webhook. View the following example:

+
[source,yaml]
```

2024-09-09 19:33 UTC, dockerymick commented on governance/gatekeeper_operator/gatekeeper_policy_constraints.adoc
> +* The _Related resources_ section is only available when the Gatekeeper version 3.9 or newer generates the audit results.
```suggestion
- The _Related resources_ section is only available when the Gatekeeper version 3.9 or newer generates the audit results. 
```

2024-09-09 19:33 UTC, dockerymick commented on governance/gatekeeper_operator/gatekeeper_policy_constraints.adoc
>  [#additional-resources-gk]
There is a hashtag on line 87 and 95

2024-09-09 19:33 UTC, dockerymick commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
> +To install the {gate} policy, use the configuration policy controller. During the install, the operator group and subscription pull the {gate} to install it in your managed cluster. Then, the {gate}
```suggestion
To install the {gate} policy, use the configuration policy controller. During the install, the operator group and subscription pull the {gate} to install it in your managed cluster. Then, the {gate} creates a Gatekeeper custom resource to configure Gatekeeper.
```

2024-09-09 19:33 UTC, dockerymick commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
> +To view the status of the {gate} policy, see the {acm-short} configuration policy controller because it checks the {gate}policy and supports the  `enforce` remediation action. When you set the contro
```suggestion
To view the status of the {gate} policy, see the {acm-short} configuration policy controller because it checks the {gate} policy and supports the  `enforce` remediation action. When you set the controller to `enforce` it automatically creates the {gate} objects on the managed cluster. 
```

2024-09-09 19:33 UTC, dockerymick commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
> +== Viewing and disabling {gate} policy
Sorry for the back and forth. Reminder to reduce the console steps here, but let's also move this section after "Creating a Gatekeeper policy from the console" on line 29. Let's also revert the header to H3 for Viewing the {gate} policy. I didn't mean for you to combine it with the disabling section. Disabling {gat} policy should still be its own H2 subsection with reduced console steps.

2024-09-09 19:33 UTC, dockerymick commented on governance/gatekeeper_operator/requirements.adoc
> += Requirements
That's correct and no

2024-09-09 19:33 UTC, dockerymick commented on governance/main.adoc
> +include::gatekeeper_operator/gatekeeper_operator_overview.adoc[leveloffset=+1]
This looks fine, reminder to add the release note file

2024-09-09 19:33 UTC, dockerymick commented on governance/supported_policies.adoc
> +| Gatekeeper is an admission webhook that enforces custom resource definition-based policies that are run by the Open Policy Agent (OPA) policy engine. See the link:https://open-policy-agent.github.i
I see Gatekeeper operator on line 52

2024-09-09 19:39 UTC, dhaiducek commented on governance/gatekeeper_operator/gatekeeper_operator_overview.adoc
> +Gatekeeper is a validating webhook with auditing capabilities. Install Gatekeeper on a {ocp} cluster from the {ocp} operator catalog. With {acm}, you can install Gatekeeper on your {ocp} managed clus
Yeah, I agree `GatekeeperOperator` would make way more sense and cause less confusion. Unfortunately changing its name is nontrivial so we're kind of stuck with it. 😕

2024-09-10 14:43 UTC, dhaiducek commented on governance/gatekeeper_operator/channels.adoc
> +With the `y-stream version` channel, you can access all the z-streams for a particular y-stream. For example, the channel `1.2` could have `v1.2.0`, `v1.2.1`, `v1.2.2`, and more, but it would not inc
If the hypothetical versioning is problematic, I can take a stab at describing it without the versions. Would something like this work?

>With the {gate}, you have access to two types of channels to help you make upgrades. These channels are the `stable` channel and the `y-stream version` channel.
>
>With the `stable` channel, you can access the latest available version, regardless of whether it's an x-stream, y-stream, or z-stream. The previous `y-stream` channel versions that are released after the latest version are not included the `stable` channel.
>
>With the `y-stream` version channel, you can access all the z-stream versions for a particular y-stream.

2024-09-10 16:55 UTC, jc-berger commented on governance/main.adoc
> +include::gatekeeper_operator/gatekeeper_operator_overview.adoc[leveloffset=+1]
@dockerymick thank you :) Brandi, Dale, and I discussed and agreed that devs would write a release note, and we'd link to that release notes in the `Requirements` doc. 

Is that cool with you?

2024-09-10 17:21 UTC, dockerymick commented on governance/main.adoc
> +include::gatekeeper_operator/gatekeeper_operator_overview.adoc[leveloffset=+1]
if its been discussed already thats fine

2024-09-10 17:44 UTC, jc-berger commented on governance/gatekeeper_operator/requirements.adoc
> += Requirements
@dockerymick thanks, so I removed the content. I'm thinking maybe we should rename this file to `General support` instead of `Requirements`

What do you think? 

As a reminder, this is the file where we agreed we'd link to the release note that devs will provide, and I can edit.

2024-09-10 18:22 UTC, dockerymick commented on governance/gatekeeper_operator/requirements.adoc
> += Requirements
Yea, i'm cool with you renaming the file to general_support.adoc

2024-09-10 18:27 UTC, dockerymick commented on governance/gatekeeper_operator/configure_gatekeeper_operator.adoc
> +See _Adding Operators to a cluster_ in the link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.16/html/operators/administrator-tasks#olm-adding-operators-to-a-cluster[{o
Move the link to Additional resources, but move the statement earlier before the Required access

2024-09-10 18:29 UTC, dockerymick commented on governance/gatekeeper_operator/configure_gatekeeper_operator.adoc
> +After you install the {gate}, to install Gatekeeper you must configure the Gatekeeper custom resource.
```suggestion
After you install the {gate}, you must configure the `Gatekeeper` custom resource to install Gatekeeper.
```

2024-09-10 22:01 UTC, dockerymick requested changes
The finish line is near Jake!

2024-09-10 22:01 UTC, dockerymick commented on governance/gatekeeper_operator/configure_gatekeeper_operator.adoc
> +To install Gatekeeper on your hub cluster, install the {gate} from the {ocp} catalog. Configure the {acm-short} Gatekeeper policy by using the governance framework. Then, you can start the Gatekeeper
Would it be helpful to mention that when the policy is set to enforce, the Gatekeeper installation starts? 
```suggestion
To install Gatekeeper on your hub cluster, install the {gate} from the {ocp} catalog. See _Adding Operators to a cluster_ in the {ocp-short} documentation. Configure the {acm-short} Gatekeeper policy by using the governance framework.
```

2024-09-10 22:01 UTC, dockerymick commented on governance/gatekeeper_operator/configure_gatekeeper_operator.adoc
> +The {gate} custom resource tells the {gate} to start the Gatekeeper installation on the cluster, using the given configuration. To work with a {gate} custom resource, use the following sample YAML:
```suggestion
== Gatekeeper custom resource sample

The {gate} custom resource tells the {gate} to start the Gatekeeper installation on the cluster, using the given configuration. To work with a {gate} custom resource, use the following sample YAML: 
```

2024-09-10 22:01 UTC, dockerymick commented on governance/gatekeeper_operator/configure_gatekeeper_operator.adoc
> +. To verify that the resources are added to your `Config` resource, view that the `syncOnly` parameter section is added. Run the following command:
```suggestion
----

. To verify that the resources are added to your `Config` resource, view that the `syncOnly` parameter section is added. Run the following command:
```

2024-09-10 22:01 UTC, dockerymick commented on governance/gatekeeper_operator/configure_gatekeeper_operator.adoc
> +For versions 3.14 or later, the {gate} exposes a setting in the {gate} custom resource for the audit configuration with the parameter `auditFromCache`, which is disabled by default. If you enable `au
```suggestion
For versions 3.14 or later, the {gate} exposes a setting in the {gate} custom resource for the audit configuration with the `auditFromCache` parameter, which is disabled by default. If you enable `auditFromCache`, you need to set `config.gatekeeper.sh` with the objects to sync to the cache. For more information, see _Configuring Audit_ in the Gatekeeper documentation.
```

2024-09-10 22:01 UTC, dockerymick commented on governance/gatekeeper_operator/configure_gatekeeper_operator.adoc
> + For more information, see link:https://open-policy-agent.github.io/gatekeeper/website/docs/audit/#configuring-audit[Configuring Audit] in the Gatekeeper documentation.
```suggestion
[#additional-resources]
== Additional resources 

- See _Adding Operators to a cluster_ in the link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.15/html/operators/administrator-tasks#olm-adding-operators-to-a-cluster[{ocp-short} documentation].
- For more information, see link:https://open-policy-agent.github.io/gatekeeper/website/docs/audit/#configuring-audit[Configuring Audit] in the Gatekeeper documentation.
```

2024-09-10 22:01 UTC, dockerymick commented on governance/gatekeeper_operator/gatekeeper_operator_overview.adoc
> +- xref:../gatekeeper_operator/gatekeeper_policy_constraints.adoc#integrating-gatekeeper-constraints-templates[Integrating Gatekeeper constraints and constraint templates]
Reminder to add the link for the General support file

2024-09-10 22:01 UTC, dockerymick commented on governance/gatekeeper_operator/gatekeeper_policy_constraints.adoc
> +- `policy-gatekeeper-admission`: Use the `policy-gatekeeper-admission` configuration policy within a {acm-short} policy to check for Kubernetes API requests denied by the Gatekeeper admission webhook
```suggestion
* `policy-gatekeeper-admission`: Use the `policy-gatekeeper-admission` configuration policy within a {acm-short} policy to check for Kubernetes API requests denied by the Gatekeeper admission webhook. View the following example:
```

2024-09-10 22:01 UTC, dockerymick commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
> +. Select the *Actions* icon for the `policy-gatekeeper-operator` policy.
```suggestion
[#disabling-gatekeeper-operator-policy]
== Disabling {gate} policy

To disable your `policy-gatekeeper-operator` policy, select the *Disable* option from the _Actions_ menu.
```

2024-09-10 22:01 UTC, dockerymick commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
> +. Click *Disable policy*.
```suggestion
```

2024-09-10 22:01 UTC, dockerymick commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
> +To delete your {gate} policy from the console, click the *Actions* icon for the `policy-gatekeeper-operator` policy and select *Remove*.
In another PR, the @drkho let me know that the option to delete a policy is "Delete". Derek can you help confirm? 
```suggestion
To delete your {gate} policy from the console, click the *Actions* icon for the `policy-gatekeeper-operator` policy and select *Delete*.
```

2024-09-10 22:01 UTC, dockerymick commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
> +. Locate the `ConfigurationPolicy` template that you used to create the Gatekeeper custom resource.
Based on Dale's previous comments
```suggestion
. Locate the `ConfigurationPolicy` template that you used to create the {gate} custom resource.
```

2024-09-10 22:01 UTC, dockerymick commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
> +- For a list of topics to integrate third-party policies with the product, see xref:../governance/third_party_policy_intro.adoc#integrate-third-party-policy-controllers[Integrate third-party policy c
This link came up as broken
```suggestion
- For a list of topics to integrate third-party policies with the product, see xref:../../governance/third_party_policy_intro.adoc#integrate-third-party-policy-controllers[Integrate third-party policy controllers]. 
```

2024-09-10 22:01 UTC, dockerymick commented on governance/gatekeeper_operator/requirements.adoc
> += Requirements
Just a reminder that we agreed to update this file title and name
```suggestion
= General support
```

2024-09-10 22:01 UTC, dockerymick commented on governance/main.adoc
> +include::gatekeeper_operator/gatekeeper_operator_overview.adoc[leveloffset=+1]
Add this link to the grc_intro.adoc file after "Secure the hub cluster".  This way, we know the user will at least see that Gatekeeper is apart of Governance.

Also remove the Gatekeeper operator link from the third_party_policy_intro.adoc file. Alternatively, you can hide the link for the Gatekeeper operator file because this is one of the changes requested in the following issue: https://issues.redhat.com/browse/ACM-13093

2024-09-12 17:58 UTC, dockerymick commented on governance/main.adoc
> +include::gatekeeper_operator/gatekeeper_operator_overview.adoc[leveloffset=+1]
@jc-berger

2024-09-13 15:08 UTC, dockerymick requested changes
Just a few more suggestions.

2024-09-13 15:08 UTC, dockerymick commented on governance/gatekeeper_operator/configure_gatekeeper_operator.adoc
> +The {gate} custom resource tells the {gate} to start the Gatekeeper installation on the cluster, using the given configuration. To work with a {gate} custom resource, use the following sample YAML:
```suggestion
The {gate} custom resource tells the {gate} to start the Gatekeeper installation on the cluster. Use the following YAML to install Gatekeeper: 
```

2024-09-13 15:08 UTC, dockerymick commented on governance/gatekeeper_operator/configure_gatekeeper_operator.adoc
> +When you set the `auditFromCache` parameter to `Automatic`, the {gate} collects resources from constraints and inserts those resources into your Gatekeeper `Config` resource. If the resource does not
mentioning the benefit of configuring the parameter earlier and did some reordering for the flow. Let me know your thoughts.

```suggestion
For versions 3.14 or later, the {gate} exposes a setting in the {gate} custom resource for the audit configuration with the `auditFromCache` parameter, which is disabled by default. Configure the `auditFromCache` parameter to collect resources from constraints.

When you set the `auditFromCache` parameter to `Automatic`, the {gate} collects resources from constraints and inserts those resources into your Gatekeeper `Config` resource. If the resource does not exist, the {gate} creates the `Config` resource.

If you enable `auditFromCache`, you need to set `config.gatekeeper.sh` with the objects to sync to the cache. For more information, see _Configuring Audit_ in the Gatekeeper documentation.
```

2024-09-13 15:08 UTC, dockerymick commented on governance/gatekeeper_operator/gatekeeper_operator_overview.adoc
> += The {gate} overview
I recommend removing "The". I did see it in the global hub doc but didn't see that with other operator doc. 
```suggestion
= {gate} overview 
```

2024-09-13 15:08 UTC, dockerymick commented on governance/gatekeeper_operator/gatekeeper_operator_overview.adoc
> +Gatekeeper is a validating webhook with auditing capabilities. Install Gatekeeper on a {ocp} cluster from the {ocp} operator catalog. With {acm}, you can install Gatekeeper on your {ocp} managed clus
Making changes based on the configuring topic. @dhaiducek is my suggestion accurate? 
```suggestion
Gatekeeper is a validating webhook with auditing capabilities. Install the {gate} on a {ocp} cluster from the {ocp} operator catalog. With {acm}, you can install Gatekeeper on your hub cluster by using the {gate} policy. After you install Gatekeeper, use it for the following benefits: 
```

2024-09-13 15:08 UTC, dockerymick commented on governance/gatekeeper_operator/general_support.adoc
> +To understand the support you receive from the Gatekeeper operator, see the following list:
```suggestion
To understand the support you receive from the {gate}, see the following list:
```

2024-09-13 15:08 UTC, dockerymick commented on governance/gatekeeper_operator/general_support.adoc
> +- The {gate} is not supported on {ocp-short} versions that are under extended support or have reached their end-of-life status.
Based on the [style guide for lists](https://www.ibm.com/docs/en/ibm-style?topic=format-lists#definition-lists), I suggest the following changes. I would also recommend that we remove the last bullet point since this is a list about what's supported. Since ocp versions that receive standard support is mentioned we might not need to call out what's not supported. The bullet point seems inconsistent with the list. Alternatively, we can keep the statement and add it as a note:
```suggestion
- Supports current version of the {gate}, preceding versions, and all z-stream releases of those versions.
- Receive maintenance support and relevant security vulnerability fixes for preceding and current versions. 
- Support for all {ocp} versions that receive standard support.
- The {gate} is not supported on {ocp-short} versions that are under extended support or have reached their end-of-life status.
```

OR

```suggestion
- Supports current version of the {gate}, preceding versions, and all z-stream releases of those versions.
- Receive maintenance support and relevant security vulnerability fixes for preceding and current versions. 
- Support for all {ocp} versions that receive standard support.
*Note*: The {gate} is not supported on end-of-life {ocp-short} versions or versions that receive extended support.
```

2024-09-13 15:08 UTC, dockerymick commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
> +To install the {gate} policy, use the configuration policy controller. During the install, the operator group and subscription pull the {gate} to install it in your managed cluster. Then, the {gate}
```suggestion
To install the {gate} policy, use the configuration policy controller. During the install, the operator group and subscription pull the {gate} to install it on your managed cluster. Then, the {gate} creates a Gatekeeper custom resource to configure Gatekeeper. 
```

2024-09-13 15:08 UTC, dockerymick commented on governance/grc_intro.adoc
> +* xref:../governance/gatekeeper_operator/gatekeeper_operator_overview.adoc#gatekeeper-operator-overview[The {gate} overview]
To align with my other suggestion to remove "The" from the title
```suggestion
* xref:../governance/gatekeeper_operator/gatekeeper_operator_overview.adoc#gatekeeper-operator-overview[{gate} overview]
```

2024-09-13 17:32 UTC, jc-berger commented on governance/gatekeeper_operator/gatekeeper_operator_overview.adoc
> +Gatekeeper is a validating webhook with auditing capabilities. Install Gatekeeper on a {ocp} cluster from the {ocp} operator catalog. With {acm}, you can install Gatekeeper on your {ocp} managed clus
I committed the suggestion, but @dhaiducek, to Mikela's point, let me know if you want me to change this rewrite up some if it's inaccurate.

2024-09-13 17:55 UTC, dockerymick requested changes
Based Brandi's reminder about reducing the length of anchors and filenames, I made more suggestions. @swopebe will you chime in here about some of the filename suggestions that i made

2024-09-13 17:55 UTC, dockerymick commented on governance/gatekeeper_operator/configure_gatekeeper_operator.adoc
> +[#configure-gatekeeper-operator]
can we also reduce the length of the filename and anchor?

maybe: config_gk_operator.adoc and the anchor: #config-gk-operator

2024-09-13 17:55 UTC, dockerymick commented on governance/gatekeeper_operator/configure_gatekeeper_operator.adoc
> +[#configuring-audit-sync]
based on other suggestion
```suggestion
[#config-audit-sync]
```

2024-09-13 17:55 UTC, dockerymick commented on governance/gatekeeper_operator/configure_gatekeeper_operator.adoc
> +[#additional-resources]
```suggestion
[#gk-add-resources]
```

2024-09-13 17:55 UTC, dockerymick commented on governance/gatekeeper_operator/gatekeeper_operator_overview.adoc
> +[#gatekeeper-operator-overview]
maybe change the filename to `gk_operator_overview.adoc` and sorry for the back and forth. Brandi let me know that yall agreed to using "The {gate} overview"
```suggestion
[#gk-operator-overview]
```

2024-09-13 17:55 UTC, dockerymick commented on governance/gatekeeper_operator/gatekeeper_policy_constraints.adoc
> +[#integrating-gatekeeper-constraints-templates]
For filename, maybe `gk_constraint.adoc`
```suggestion
[#integrate-gk-constraints-templates]
```

2024-09-13 17:55 UTC, dockerymick commented on governance/gatekeeper_operator/gatekeeper_policy_constraints.adoc
>  [#additional-resources-gk]
```suggestion
[#constraint-add-resources]
```

2024-09-13 17:55 UTC, dockerymick commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
> +[#managing-gatekeeper-operator-installation-policies]
```suggestion
[#manage-gk-policies]
```

2024-09-13 18:01 UTC, swopebe commented on governance/gatekeeper_operator/configure_gatekeeper_operator.adoc
> +[#additional-resources]
This one we do need to specify because I am pretty sure it breaks the build to just write `additional resources` -- agreed.

2024-09-13 18:03 UTC, swopebe commented on governance/gatekeeper_operator/gatekeeper_policy_constraints.adoc
>  [#additional-resources-gk]
not sure this was caught:

@jc-berger: Overwritten by `remediationAction` in the parent policy.  (This is not a complete sentence.)

The __whatever the spec is__ is overwritted by....

2024-09-13 18:04 UTC, swopebe commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
> +[#managing-gatekeeper-operator-installation-policies]
this could be also _managing_ or _manage_, but agree it can be reduced.

2024-09-13 18:05 UTC, swopebe commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
> +[#managing-gatekeeper-operator-installation-policies]
Thanks for simplifying where we can. I don't think I need to approve, since there has otherwise been a lot of review.

2024-09-13 18:16 UTC, dockerymick commented on governance/gatekeeper_operator/configure_gatekeeper_operator.adoc
> +[#additional-resources]
Yea for sure, we will get an internal link error from pantheon

2024-09-13 18:17 UTC, dockerymick commented on governance/gatekeeper_operator/gatekeeper_policy_constraints.adoc
>  [#additional-resources-gk]
Good catch!

2024-09-13 18:18 UTC, dockerymick commented on governance/gatekeeper_operator/gatekeeper_policy_constraints.adoc
> +<1> Overwritten by `remediationAction` in the parent policy.
```suggestion
<1> The `ConfigurationPolicy` `remediationAction` parameter is overwritten by `remediationAction` in the parent policy. 
```

2024-09-13 18:31 UTC, dockerymick requested changes

2024-09-13 18:31 UTC, dockerymick commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
> +[#installing-gatekeeper-operator-policy]
```suggestion
[#installing-gk-operator-policy]
```

2024-09-13 18:31 UTC, dockerymick commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
> +[#creating-a-gatekeeper-policy-from-the-console]
How can the user create from the CLI? If we have steps for that I recommend we add a section named "Creating a {gate} policy" (H2), then make the option to configure from the console as a subsection of it. So make it H3
```suggestion
[#creating-gk-operator-console]
```

2024-09-13 18:31 UTC, dockerymick commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
> +[#viewing-gatekeeper-operator-policy]
```suggestion
[#viewing-gk-operator-policy]
```

2024-09-13 18:31 UTC, dockerymick commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
> +[#upgrading-gatekeeper-gatekeeper-operator]
```suggestion
[#upgrading-gk-and-gk-operator]
```

2024-09-13 18:31 UTC, dockerymick commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
> +[#disabling-gatekeeper-operator-policy]
```suggestion
[#disabling-gk-operator-policy]
```

2024-09-13 18:31 UTC, dockerymick commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
> +[#deleting-gatekeeper-operator-policy]
```suggestion
[#deleting-gk-operator-policy]
```

2024-09-13 18:31 UTC, dockerymick commented on governance/gatekeeper_operator/manage_gatekeeper.adoc
> +== Uninstalling Gatekeeper policy, Gatekeeper, and {gate} policy
Based on the TOC, i suggest the following:
```suggestion
[#uninstalling-gk]
== Uninstalling Gatekeeper constraint, Gatekeeper instance, and {gate} policy
```

if it's removed, is it also uninstalled and is the operator deleted?

2024-09-13 18:31 UTC, dockerymick commented on governance/supported_policies.adoc
> +| Gatekeeper is an admission webhook that enforces custom resource definition-based policies that are run by the Open Policy Agent (OPA) policy engine. See the link:https://open-policy-agent.github.i
as you make the filenames concise, remember to update other link references

2024-09-13 18:31 UTC, dockerymick commented on governance/supported_policies.adoc
> +| After deploying Gatekeeper to the clusters, deploy this sample Gatekeeper policy that ensures namespaces that are created on the cluster are labeled as specified. For more information, see xref:../
same suggestion about updating references

2024-09-13 19:36 UTC, dhaiducek reviewed
I still need to give the "manage_gatekeeper" section a review, but wanted to leave the review comments I did have so far.

2024-09-13 19:36 UTC, dhaiducek commented on governance/gatekeeper_operator/channels.adoc
> +With the `stable` channel, you can access the latest available version, whether it is an `x-stream`, `y-stream`, or `z-stream`. The `stable` channel only includes the current version of the `y-stream
Including the word "only" here is technically inaccurate.
```suggestion
With the `stable` channel, you can access the latest available version, whether it is an `x-stream`, `y-stream`, or `z-stream`. The `stable` channel includes the latest version of the latest `y-stream` channel.
```

2024-09-13 19:36 UTC, dhaiducek commented on governance/gatekeeper_operator/configure_gatekeeper_operator.adoc
> +To install Gatekeeper on your hub cluster, install the {gate} from the {ocp} catalog. See _Adding Operators to a cluster_ in the {ocp-short} documentation. Configure the {acm-short} Gatekeeper policy
I guess from here users will know to look at "Additional resources"?

2024-09-13 19:36 UTC, dhaiducek commented on governance/gatekeeper_operator/configure_gatekeeper_operator.adoc
> +    disabledBuiltins: - http.send
```suggestion
    disabledBuiltins:
     - http.send
```

2024-09-13 19:36 UTC, dhaiducek commented on governance/gatekeeper_operator/configure_gatekeeper_operator.adoc
> +The {gate} custom resource tells the {gate} to start the Gatekeeper installation on the cluster. Use the following YAML to install Gatekeeper:
Not sure how this should be conveyed, but this YAML isn't intended to be used directly--it's mostly filled in with default values so that users understand the options and whether they might want to specify them. In reality users will likely start with a manifest that's mostly empty and use these default values.

```suggestion
The {gate} custom resource tells the {gate} to start the Gatekeeper installation on the cluster. View the following YAML to install Gatekeeper, which has been filled in with sample and default values:
```

2024-09-13 19:36 UTC, dhaiducek commented on governance/gatekeeper_operator/configure_gatekeeper_operator.adoc
> +      auditEventsInvolvedNamespace: Enabled <1>
```suggestion
    auditEventsInvolvedNamespace: Enabled <1>
```

2024-09-13 19:36 UTC, dhaiducek commented on governance/gatekeeper_operator/configure_gatekeeper_operator.adoc
> +If you enable `auditFromCache`, you need to set `config.gatekeeper.sh` with the objects to sync to the cache. For more information, see _Configuring Audit_ in the Gatekeeper documentation.
```suggestion
When you set the `auditFromCache` parameter to `Automatic`, the {gate} collects resources from constraints and inserts those resources into your Gatekeeper `Config` resource. If the resource does not exist, the {gate} creates the `Config` resource.

If you set the `auditFromCache` parameter to `Enabled`, you need to manually set the Gatekeeper `Config` resource with the objects to sync to the cache. For more information, see _Configuring Audit_ in the Gatekeeper documentation.
```

2024-09-13 19:36 UTC, dhaiducek commented on governance/gatekeeper_operator/configure_gatekeeper_operator.adoc
> +  audit: replicas: 2
```suggestion
  audit:
    replicas: 2 
```

2024-09-13 19:36 UTC, dhaiducek commented on governance/gatekeeper_operator/gatekeeper_policy_constraints.adoc
> +- link:https://github.com/open-cluster-management-io/policy-collection/blob/main/stable/CM-Configuration-Management/policy-gatekeeper-operator-downstream.yaml[`policy-gatekeeper-operator.yaml`].
I think the trailing period is unintentional?

```suggestion
- link:https://github.com/open-cluster-management-io/policy-collection/blob/main/stable/CM-Configuration-Management/policy-gatekeeper-operator-downstream.yaml[`policy-gatekeeper-operator.yaml`]
```

2024-09-13 19:36 UTC, dhaiducek commented on governance/gatekeeper_operator/gatekeeper_policy_constraints.adoc
> +- link:https://www.openpolicyagent.org/docs/latest/kubernetes-introduction/#what-is-opa-gatekeeper[What is OPA Gatekeeper].
(Same as above)
```suggestion
- link:https://www.openpolicyagent.org/docs/latest/kubernetes-introduction/#what-is-opa-gatekeeper[What is OPA Gatekeeper]
```

2024-09-13 19:36 UTC, dhaiducek commented on governance/gatekeeper_operator/gatekeeper_policy_constraints.adoc
> +- xref:../../governance/grc_intro.adoc#governance[Governance].
(Same as above)
```suggestion
- xref:../../governance/create_config_pol.adoc#managing-configuration-policies[Managing configuration policies]

- xref:../../governance/grc_intro.adoc#governance[Governance]
```

2024-09-13 19:46 UTC, dockerymick commented on governance/gatekeeper_operator/configure_gatekeeper_operator.adoc
> +The {gate} custom resource tells the {gate} to start the Gatekeeper installation on the cluster. Use the following YAML to install Gatekeeper:
How about: View the following sample YAML to install Gatekeeper, which is filled in with sample and default values:

2024-09-16 17:02 UTC, dockerymick approved these changes
Made some suggestions that are simple, and one more comment about a link. Otherwise, this looks great Jake! You did it! After you make the updates based on my suggestions and receive approval from Dale, feel free to merge!

2024-09-16 17:02 UTC, dockerymick commented on governance/gatekeeper_operator/channels.adoc
> +[#channels]
changing this because we have a `#channels` anchor that exists in the Applications folder. This change is to prevent broken links in Pantheon
```suggestion
[#operator-channels]
```

2024-09-16 17:02 UTC, dockerymick commented on governance/gatekeeper_operator/gk_policy_constraints.adoc
> +- link:https://www.openpolicyagent.org/docs/latest/kubernetes-introduction/#what-is-opa-gatekeeper[What is OPA Gatekeeper]
Made this suggestion bc there is a question mark in the title
```suggestion
- link:https://www.openpolicyagent.org/docs/latest/kubernetes-introduction/#what-is-opa-gatekeeper[What is OPA Gatekeeper?]
```

2024-09-16 17:02 UTC, dockerymick commented on governance/grc_intro.adoc
> +* xref:../governance/gatekeeper_operator/gatekeeper_operator_overview.adoc#gatekeeper-operator-overview[{gate} overview]
This link came up broken. I believe this will help since we renamed the file
```suggestion
* xref:../governance/gatekeeper_operator/gk_operator_overview.adoc#gk-operator-overview[{gate} overview]
```

2024-09-16 17:02 UTC, dockerymick commented on governance/supported_policies.adoc
> +| After deploying Gatekeeper to the clusters, deploy this sample Gatekeeper policy that ensures namespaces that are created on the cluster are labeled as specified. For more information, see xref:../
This links came up broken, maybe add `governance` into the path? The filenames look correct from my perspective.
<img width="1154" alt="Screenshot 2024-09-16 at 12 59 05 PM" src="https://github.com/user-attachments/assets/775be9d5-7c81-4241-814c-921cd59e641d">

2024-09-16 17:14 UTC, jc-berger commented on governance/supported_policies.adoc
> +| After deploying Gatekeeper to the clusters, deploy this sample Gatekeeper policy that ensures namespaces that are created on the cluster are labeled as specified. For more information, see xref:../
Great suggestions, that did the trick, at least it works in the VS Code preview feature!

2024-09-16 17:16 UTC, dockerymick commented on governance/supported_policies.adoc
> +| After deploying Gatekeeper to the clusters, deploy this sample Gatekeeper policy that ensures namespaces that are created on the cluster are labeled as specified. For more information, see xref:../
Links are now fixed!

2024-09-16 17:16 UTC, dockerymick approved these changes
Reapproving after checking links

2024-09-16 18:15 UTC, dhaiducek reviewed
Almost there! I have some more minor comments/questions.

2024-09-16 18:15 UTC, dhaiducek commented on governance/gatekeeper_operator/manage_gk.adoc
> +- <<uninstalling-gatekeeper,Uninstalling Gatekeeper policy, Gatekeeper, and {gate} policy>>
These all need to be updated to match the new tags (these are also noted in the CI):
```
asciidoctor: INFO: possible invalid reference: installing-gatekeeper-operator-policy
asciidoctor: INFO: possible invalid reference: creating-a-gatekeeper-policy-from-the-console
asciidoctor: INFO: possible invalid reference: upgrading-gatekeeper-gatekeeper-operator
asciidoctor: INFO: possible invalid reference: disabling-gatekeeper-operator-policy
asciidoctor: INFO: possible invalid reference: deleting-gatekeeper-operator-policy
asciidoctor: INFO: possible invalid reference: uninstalling-gatekeeper
```
ref: https://github.com/stolostron/rhacm-docs/actions/runs/10888730503/job/30213839121?pr=6770#step:4:8

2024-09-16 18:15 UTC, dhaiducek commented on governance/gatekeeper_operator/config_gk_operator.adoc
> +*Note:* For versions 3.14 or later, you cam implement the following features to this YAML:
```suggestion
*Note:* For versions 3.14 or later, you can implement the following features from this YAML:
```

2024-09-16 18:15 UTC, dhaiducek commented on governance/gatekeeper_operator/config_gk_operator.adoc
> +<2> Enable the `admissionEventsInvolvedNamespace` parameter to manage the namespace admission event you want to create. When you enable this parameter, the Gatekeeper controller deployment gets the f
```suggestion
<1> Enable the `auditEventsInvolvedNamespace` parameter to manage the namespace audit event you want to create. When you enable this parameter, the Gatekeeper controller deployment is run with the following argument: `--audit-events-involved-namespace=true`.
<2> Enable the `admissionEventsInvolvedNamespace` parameter to manage the namespace admission event you want to create. When you enable this parameter, the Gatekeeper controller deployment is run with the following argument: `--admission-events-involved-namespace=true`.
```

2024-09-16 18:15 UTC, dhaiducek commented on governance/gatekeeper_operator/config_gk_operator.adoc
> +<3> To manage your webhook operations, use the following values for the `operations` parameter, `"CREATE"`, `"UPDATE"`, `"CONNECT"`, and `"DELETE"`.
```suggestion
<3> To manage your webhook operations, you can use the following values for the `operations` parameter, `"CREATE"`, `"UPDATE"`, `"CONNECT"`, and `"DELETE"`.
```

2024-09-16 18:15 UTC, dhaiducek commented on governance/gatekeeper_operator/config_gk_operator.adoc
> +. Get the explanation of the `auditFromCache` setting to view the description of the custom resource by running the following command:
(Optional) This is more of a note than an additional step in the process (though it's also fine as it is).
```suggestion
**NOTE:** You can view the explanation of the `auditFromCache` setting from the description of the {gate} custom resource by running the following command:
```

2024-09-16 18:15 UTC, dhaiducek commented on governance/gatekeeper_operator/manage_gk.adoc
> +To install the {gate} policy, use the configuration policy controller. During the install, the operator group and subscription pull the {gate} to install it on your managed cluster. Then, the {gate}
```suggestion
To install the {gate} policy, use the configuration policy controller. During the install, the operator group and subscription pull the {gate} to install it on your managed cluster. Then, the policy creates a Gatekeeper custom resource to configure Gatekeeper. 
```

2024-09-16 18:15 UTC, dhaiducek commented on governance/gatekeeper_operator/manage_gk.adoc
> +To view the status of the {gate} policy, see the {acm-short} configuration policy controller because it checks the {gate} policy and supports the  `enforce` remediation action. When you set the contr
These feel like extra words to me.
```suggestion
The {acm-short} configuration policy controller checks the {gate} policy and supports the  `enforce` remediation action. When you set the controller to `enforce` it automatically creates the {gate} objects on the managed cluster. 
```

2024-09-16 18:15 UTC, dhaiducek commented on governance/gatekeeper_operator/manage_gk.adoc
> +When you create a Gatekeeper policy from the console, you must set your remediation `enforce` to install Gatekeeper. By default, the operator generates the values.
I'm not sure what this is getting at, so maybe just take it out?
```suggestion
When you create a Gatekeeper policy from the console, you must set your remediation `enforce` to install Gatekeeper.
```

2024-09-16 18:15 UTC, dhaiducek commented on governance/gatekeeper_operator/manage_gk.adoc
> +If you set `upgradeApproval` to `Manual`, you must manually approve the upgrade for each cluster of the {gate}.
```suggestion
If you set `upgradeApproval` to `Manual`, you must manually approve the upgrade for each cluster where the {gate} is installed.
```

2024-09-16 18:15 UTC, dhaiducek commented on governance/gatekeeper_operator/manage_gk.adoc
> +To disable your `policy-gatekeeper-operator` policy, select the *Disable* option from the _Actions_ menu.
```suggestion
To disable your `policy-gatekeeper-operator` policy, select the *Disable* option from the _Actions_ menu in the console, or set `spec.disabled: true` from the CLI.
```

2024-09-16 18:15 UTC, dhaiducek commented on governance/gatekeeper_operator/manage_gk.adoc
> +- <<removing-gatekeeper-operator,Removing {gate}>>
Not sure if you wanted these to also be `gk` rather than `gatekeeper`?

2024-09-16 18:15 UTC, dhaiducek commented on governance/gatekeeper_operator/manage_gk.adoc
> +=== Removing Gatekeeper _Constraint_
It's nuanced, but `ConstraintTemplate` is a kind, but constraint is not.
```suggestion
=== Removing Gatekeeper constraints
```

2024-09-16 18:15 UTC, dhaiducek commented on governance/gatekeeper_operator/manage_gk.adoc
> +. Save and apply the policy.
I think a clarification here would be good.
```suggestion
. Save and apply the policy.

**NOTE:** This assumes the constraint and `ConstraintTemplate` are provided directly under `policy-templates` and are not wrapped in a `ConfigurationPolicy`.
```

2024-09-16 18:15 UTC, dhaiducek commented on governance/gatekeeper_operator/manage_gk.adoc
> +. Change the value for `complianceType` of the `ConfigurationPolicy` template to `mustnothave`.
```suggestion
. Change the value for `complianceType` of the `ConfigurationPolicy` template to `mustnothave`.
. This will delete the {gate} custom resource and clean up the Gatekeeper deployment.
```

2024-09-16 18:15 UTC, dhaiducek commented on governance/gatekeeper_operator/manage_gk.adoc
> +=== Viewing the {gate} policy
Is it intentional to have this as a subheading of the "Creating" section? It's fine as it is--I'm just curious.

2024-09-16 18:45 UTC, dockerymick commented on governance/gatekeeper_operator/config_gk_operator.adoc
> +. Get the explanation of the `auditFromCache` setting to view the description of the custom resource by running the following command:
We do not need to use double asterisk to bold. Reminder for @jc-berger we also do not capitalize note. It seems like it would be more appropriate to use "*Optional:*"

2024-09-16 18:46 UTC, dockerymick commented on governance/gatekeeper_operator/manage_gk.adoc
> +When you create a Gatekeeper policy from the console, you must set your remediation `enforce` to install Gatekeeper. By default, the operator generates the values.
We need a brief description for the section

2024-09-16 18:47 UTC, dockerymick commented on governance/gatekeeper_operator/manage_gk.adoc
> +- <<removing-gatekeeper-operator,Removing {gate}>>
If the anchors are updated for these sections to have gk, we should

2024-09-16 18:50 UTC, dockerymick commented on governance/gatekeeper_operator/manage_gk.adoc
> +. Save and apply the policy.
Reminder about how we label notes. Also avoid directional terms like "under". What does it mean to be "wrapped"? Included? Reminder that this should be in present tense @jc-berger I would also remove "This assumes"

2024-09-16 18:51 UTC, dockerymick commented on governance/gatekeeper_operator/manage_gk.adoc
> +. Change the value for `complianceType` of the `ConfigurationPolicy` template to `mustnothave`.
Does this need to be another step? Reminder to maintain present tense

2024-09-16 18:51 UTC, dockerymick commented on governance/gatekeeper_operator/manage_gk.adoc
> +=== Viewing the {gate} policy
Yes this is intentional

2024-09-16 19:13 UTC, dockerymick commented on governance/gatekeeper_operator/config_gk_operator.adoc
> +**NOTE:** You can view the explanation of the `auditFromCache` setting from the description of the {gate} custom resource by running the following command:
```suggestion
+
[source,bash]
----
oc get configs.config.gatekeeper.sh config -n openshift-gatekeeper-system
----
+
Your `Config` resource might resemble the following example:

+
[source,yaml]
----
apiVersion: config.gatekeeper.sh/v1alpha1
kind: Config
metadata:
 name: config
 namespace: "openshift-gatekeeper-system"
spec:
 sync:
   syncOnly:
   - group: ""
     version: "v1"
     kind: "Namespace"
   - group: ""
     version: "v1"
     kind: "Pod"
----
+
*Note:* You can view the explanation of the `auditFromCache` setting from the description of the {gate} custom resource by running the following command:
```

2024-09-16 19:13 UTC, dhaiducek commented on governance/gatekeeper_operator/manage_gk.adoc
> +. Save and apply the policy.
So something like this?

>**NOTE:** In these steps, the constraint and `ConstraintTemplate` are provided directly as items of `policy-templates` and are not contained in a `ConfigurationPolicy`.

2024-09-16 19:17 UTC, dhaiducek commented on governance/gatekeeper_operator/manage_gk.adoc
> +. Change the value for `complianceType` of the `ConfigurationPolicy` template to `mustnothave`.
Updated my comment to present tense (and added some clarifications). There could be an additional step like `Check that the policy status is "Compliant"`, but I'm not sure that's necessary--at least we didn't do that for the other steps here.

2024-09-16 19:19 UTC, dhaiducek commented on governance/gatekeeper_operator/manage_gk.adoc
> +When you create a Gatekeeper policy from the console, you must set your remediation `enforce` to install Gatekeeper. By default, the operator generates the values.
I don't mean the whole paragraph--I mean the sentence "By default, the operator generates the values."

2024-09-16 20:18 UTC, dhaiducek reviewed
Couple more minor polishes

2024-09-16 20:18 UTC, dhaiducek commented on governance/gatekeeper_operator/config_gk_operator.adoc
> +----
Missing colon and has an extra `+` (I _think_ the plus is no longer necessary since it's no longer in the list?)
```suggestion
*Optional:* You can view the explanation of the `auditFromCache` setting from the description of the {gate} custom resource by running the following command:

[source,bash]
----
```

2024-09-16 20:18 UTC, dhaiducek commented on governance/gatekeeper_operator/manage_gk.adoc
> +- <<uninstalling-gk,Uninstalling Gatekeeper policy, Gatekeeper, and {gate} policy>>
Consistent with the heading
```suggestion
- <<uninstalling-gk,Uninstalling Gatekeeper constraints, Gatekeeper instance, and {gate} policy>>
```

2024-09-16 20:18 UTC, dhaiducek commented on governance/gatekeeper_operator/manage_gk.adoc
> +== Uninstalling Gatekeeper constraint, Gatekeeper instance, and {gate} policy
```suggestion
== Uninstalling Gatekeeper constraints, Gatekeeper instance, and {gate} policy
```

2024-09-16 20:18 UTC, dhaiducek commented on governance/gatekeeper_operator/manage_gk.adoc
> +- <<removing-gk-constraint,Removing Gatekeeper _Constraint_>>
```suggestion
- <<removing-gk-constraint,Removing Gatekeeper constraints>>
```

2024-09-16 20:18 UTC, dhaiducek commented on governance/gatekeeper_operator/manage_gk.adoc
> +=== Removing Gatekeeper _Constraints_
```suggestion
=== Removing Gatekeeper constraints
```

2024-09-16 20:18 UTC, dhaiducek commented on governance/gatekeeper_operator/manage_gk.adoc
> +*Norw:* The constraint and `ConstraintTemplate` are provided in the `policy-templates` instead of the `ConfigurationPolicy`.
```suggestion
*Note:* The constraint and `ConstraintTemplate` are provided directly in the `policy-templates` instead of inside of a `ConfigurationPolicy`.
```

2024-09-16 20:18 UTC, dhaiducek commented on governance/gatekeeper_operator/gk_policy_constraints.adoc
> +- The _Related resources_ section is only available when the Gatekeeper version 3.9 or newer generates the audit results.
Sorry I didn't catch this before--all the supported versions of Gatekeeper are beyond 3.9, so the version caveat can be removed.
```suggestion
- The _Related resources_ section is only available when Gatekeeper generates audit results. 
```

2024-09-17 03:44 UTC, dockerymick commented on governance/gatekeeper_operator/manage_gk.adoc
> +*Norw:* The constraint and `ConstraintTemplate` are provided in the `policy-templates` instead of the `ConfigurationPolicy`.
...instead of within a `ConfigurationPolicy`

2024-09-17 03:45 UTC, dockerymick commented on governance/gatekeeper_operator/manage_gk.adoc
> +When you create a Gatekeeper policy from the console, you must set your remediation `enforce` to install Gatekeeper. By default, the operator generates the values.
ohhh gotchu, sorry read through too quickly lol

2024-09-17 13:51 UTC, drkho commented
Hi, @jc-berger, I have a general question for this PR.

I suppose the goal here is to add related `gatekeeper` _and_ `gatekeeper-operator` content. However, does the variable {gate} refer to `gatekeeper` or `gatekeeper-operator`? If former, some information to me does not apply. For example, in `governance/gatekeeper_operator/channels.adoc`, channel content applies to gatekeeper operator only, not to gatekeeper. There are also some other areas that I have similar confusion with. Though the name of a file is gatekeeper-operator, the content is about the gatekeeper.

cc: @dhaiducek

2024-09-17 13:56 UTC, jc-berger commented
@drkho thanks for your feedback! {gate} refers `gatekeeper operator` 

Are you opposed with files named `gatekeeper operator` also discussing `gatekeeper`? Or do you want to see those files more specifically discuss `gatekeeper operator` and in more detail?

2024-09-17 14:15 UTC, drkho commented
> @drkho thanks for your feedback! {gate} refers `gatekeeper operator`
> 
> Are you opposed with files named `gatekeeper operator` also discussing `gatekeeper`? Or do you want to see those files more specifically discuss `gatekeeper operator` and in more detail?

To me, the intent is clearer if `gatekeeper operator` files discusses gatekeeper operator and `gatekeeper` files discuss gatekeeper. 🙂

2024-09-17 14:34 UTC, dhaiducek commented
> To me, the intent is clearer if `gatekeeper operator` files discusses gatekeeper operator and `gatekeeper` files discuss gatekeeper. 🙂

@drkho Could you point to an example of where this is confusing? I ask this with the point that in general, the goal here is to document the Gatekeeper Operator, not Gatekeeper.

2024-09-17 20:32 UTC, dhaiducek approved these changes
LGTM! Thanks for all the work on this, @jc-berger!

Goodness--it's been 40 days! 😬

2024-09-17 20:40 UTC, merged

2024-09-18 14:54 UTC, drkho commented
> > To me, the intent is clearer if `gatekeeper operator` files discusses gatekeeper operator and `gatekeeper` files discuss gatekeeper. 🙂
> 
> @drkho Could you point to an example of where this is confusing? I ask this with the point that in general, the goal here is to document the Gatekeeper Operator, not Gatekeeper.

Sorry, I missed your question, @dhaiducek . For example, majority of content in `governance/gatekeeper_operator/gk_operator_overview.adoc` and `governance/gatekeeper_operator/config_gk_operator.adoc` are about gatekeeper instead. But I was confused with the file name and titles which point to gk operator.

Just a minor observation. The content is good though.

2024-09-18 15:46 UTC, dhaiducek commented
> For example, majority of content in `governance/gatekeeper_operator/gk_operator_overview.adoc` and `governance/gatekeeper_operator/config_gk_operator.adoc` are about gatekeeper instead. But I was confused with the file name and titles which point to gk operator.

Ah, it's a good point. The "Overview" could lead with a comment about the fact that the operator _installs_ Gatekeeper and then we can carry on with the rest of the content describing Gatekeeper--perhaps that'd be less confusing.

But the `config_gk_operator.adoc` file is very much about the operator. The `Gatekeeper` kind is specific to the operator and is used to configure the way the operator installs Gatekeeper, so its options are propagated to Gatekeeper. But maybe there could be a similar statement there.

2024-09-18 15:57 UTC, jc-berger commented
@dhaiducek and/or @drkho thanks! I made a PR adding a brief statement about gatekeeper operator installing the gatekeeper in the overview file. Happy to expand on it, unless y'all think that brief statement is enough. Thanks! 

https://github.com/stolostron/rhacm-docs/pull/6949