https://issues.redhat.com/browse/ACM-13348
open-cluster-management/rhacm-docs pull request #6805
Opened 2024-08-20 17:49 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-13348

2024-08-20 17:51 UTC, jc-berger commented on release_notes/known_issues_global.adoc
> +There are three topics named `spec`, `status` and `event` in your Kafka cluster. You can configure these Kafka topics after you upgrade Kafka to {global-hub} 1.3 or later. After this upgrade, you onl
Dev reviewers:

The file in the multicluster-global-hub repo says `Global Hub operand` Am I incorrect to user `Global Hub Operator` here? 

If `Global Hub operand` is a separate thing, may we do a brief definition or explanation of it here?

2024-08-20 17:53 UTC, jc-berger commented on release_notes/known_issues_global.adoc
> +== The {global-hub} Operator does not use Kafka topics
Dev reviewers:

It seems to me that the known issue is that users have to manually configure the Global Hub operator (or operand) to use the Kafka topics. That is, after the upgrade to Global Hub 1.3 or later, users lose some Kafka topics, and Global Hub does not automatically use it. 

If I am incorrect, please correct me, and I'llmake changes to this content. Thanks :)

2024-08-22 12:04 UTC, jc-berger commented on release_notes/known_issues_global.adoc
> +There are three topics named `spec`, `status` and `event` in your Kafka cluster. You can configure these Kafka topics after you upgrade Kafka to {global-hub} 1.3 or later. After this upgrade, you onl
Update: 

After doing some reading, I see the difference between `operand` and `operator`. thank you for your patience :) 

Since I didn't know the distinction, I did add a sentence explaining it. If you think this sentence is unneeded because our users would know the difference, let me know, and I'll remove it.

2024-08-22 12:04 UTC, jc-berger commented on release_notes/known_issues_global.adoc
> +...
Dev reviewers:

Do we need the `... ` here?

2024-08-26 03:35 UTC, yanmxa commented on release_notes/known_issues_global.adoc
> +There are three topics named `spec`, `status` and `event` in your Kafka cluster. You can configure these Kafka topics after you upgrade Kafka to {global-hub} 1.3 or later. After this upgrade, you onl
I think `gh-status` and `gh-event` both make sense. But @clyang82 prefers to use `gh-event` and @hchenxa [seems like](https://github.com/stolostron/multicluster-global-hub/pull/1053#discussion_r1719197679) to use `gh-status`.

/cc @clyang82 @hchenxa

2024-08-26 03:39 UTC, yanmxa commented on release_notes/known_issues_global.adoc
> +The {global-hub} operand provides the data and values for the {global-hub} operator to work. After upgrading {global-hub}, align the topics between your Kafka clusters and the {global-hub} operand. Y
As above, it should be consistent with the item `gh-status` of `gh-event`.

2024-08-26 03:40 UTC, yanmxa commented on release_notes/known_issues_global.adoc
> +...
Since there are other fields behind `...`. I think we can keep it :)

2024-08-26 03:46 UTC, yanmxa commented on release_notes/known_issues_global.adoc
> +There are three topics named `spec`, `status` and `event` in your Kafka cluster. You can configure these Kafka topics after you upgrade Kafka to {global-hub} 1.3 or later. After this upgrade, you onl
> Global Hub operand

The `Global Hub operand` is the API or resources of the system. but the `Global Hub Operator` is the controller. So we can't replace the it with the later

2024-08-26 03:49 UTC, yanmxa commented on release_notes/known_issues_global.adoc
> +There are three topics named `spec`, `status` and `event` in your Kafka cluster. You can configure these Kafka topics after you upgrade Kafka to {global-hub} 1.3 or later. After this upgrade, you onl
`Align these topics between your Kafka clusters and the {global-hub} Operator` -> `Align these topics between your Kafka clusters and the {global-hub} Operand`
`or you can modify the {global-hub} Operator` -> `or you can modify the {global-hub} Operand`
`For example, you can update the {global-hub} Operator` -> `For example, you can update the {global-hub} Operand`

2024-08-26 03:51 UTC, yanmxa commented on release_notes/known_issues_global.adoc
> +== The {global-hub} Operator does not use Kafka topics
` Global Hub operator` -> ` Global Hub operand` 

You are right about the upgrade case!

2024-08-28 02:51 UTC, hchenxa commented on release_notes/known_issues_global.adoc
> +There are three topics named `spec`, `status` and `event` in your Kafka cluster. You can configure these Kafka topics after you upgrade Kafka to {global-hub} 1.3 or later. After this upgrade, you onl
yes, since the spec name is `status`, so I prefer to use `gh-status` as the default value.

2024-08-28 02:55 UTC, hchenxa commented on release_notes/known_issues_global.adoc
> +== The {global-hub} operand does not use Kafka topics
I think the issue only happen when use the BYO kafka.

2024-08-28 03:39 UTC, yanmxa commented on release_notes/known_issues_global.adoc
> +== The {global-hub} operand does not use Kafka topics
Yes. It only appears in the BYO case.

2024-08-28 03:42 UTC, yanmxa commented on release_notes/known_issues_global.adoc
> +There are three topics named `spec`, `status` and `event` in your Kafka cluster. You can configure these Kafka topics after you upgrade Kafka to {global-hub} 1.3 or later. After this upgrade, you onl
@jc-berger After discussing with @clyang82 and @hchenxa. Our final conclusion is to use `gh-status`.

2024-08-28 03:43 UTC, yanmxa commented on release_notes/known_issues_global.adoc
> +
change `event` to `status`

2024-08-28 03:44 UTC, yanmxa commented on release_notes/known_issues_global.adoc
> +        statusTopic: event
also need change the `event` to `status`

2024-09-03 18:14 UTC, swopebe requested changes
See comments.

2024-09-03 18:14 UTC, swopebe commented on release_notes/known_issues_global.adoc
> +
From what I can tell BYO is not part of a product or technology name. It could be seen as colloquial. Please check on that.

Also, we want to avoid abbreviations unless they are necessary (translation issue)

"bring your own" -- quotation marks used as emphasis
https://www.ibm.com/docs/en/ibm-style?topic=punctuation-quotation-marks

Please do not ever use quotation marks in technical documentation unless we are citing a document, which we never do (I have not seen in my 9 years). This is an accessibility issue.

2024-09-03 18:14 UTC, swopebe commented on release_notes/known_issues_global.adoc
> +
**these** BYO Kafka topics
**this** upgrade

Self-referential, these can be rewritten.

Simple change: After you upgrade. (this also should replace _After upgrading global-hub_)

But honestly, you don't even need to say that; if you look at the line before it, you already say "after you upgrade"

You can scan through to see where that can be more concise.

2024-09-03 18:14 UTC, swopebe commented on release_notes/known_issues_global.adoc
> +...
We should not have these in here; @jc-berger we need clean YAML file samples, you are correct! TY.

We do not add these to the samples in the doc.

2024-09-05 14:51 UTC, yanmxa commented on release_notes/known_issues_global.adoc
> +There are three topics named `spec`, `status` and `event` in your own Kafka that you brought. You can configure your own Kafka topics after you upgrade your Kafka to {global-hub} 1.3 or later. Then,
"You can configure your own Kafka topics after you upgrade your Kafka to {global-hub} 1.3 or later. Then, you only have two topics in the system: one for `spec` path and one for `status` path. The default external topic is `gh-status`. " 

-> "After upgrade your {global-hub} to 1.3 or later. We only keep two topics in the system: one for the `spec` path and one for the `status` path. The {global-hub} operand can configure these 2 topics. And the default topics are `gh-spec` and `gh-status` for the BYO case."

2024-09-05 15:02 UTC, yanmxa commented on release_notes/known_issues_global.adoc
> +The {global-hub} operand is the API or resource of your system, and the {global-hub} operator is the controller. After upgrading {global-hub}, align the topics between your specific Kafka clusters an
suggestion1: "your specific Kafka clusters" -> "your own kafka clusters"
suggestion2: "You can either create the `gh-status` topic in your Kafka cluster" -> "You can either create the `gh-spec` and `gh-status` topics in your Kafka cluster"
suggestion3: "or you can change the {global-hub} operand to use the existing topics, such as: `spec` and `status`." -> "or you can change the {global-hub} operand to use the existing `spec` and `status` topics"

2024-09-09 14:46 UTC, swopebe reviewed
Looks great, thank you!

2024-09-09 14:46 UTC, swopebe approved these changes

2024-09-09 19:04 UTC, merged

2024-09-10 06:00 UTC, yanmxa commented
Thanks @jc-berger !