https://issues.redhat.com/browse/ACM-13263
open-cluster-management/rhacm-docs pull request #6808
Opened 2024-08-20 18:41 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-13263

2024-08-20 19:28 UTC, birsanv requested changes

2024-08-20 19:28 UTC, birsanv commented on business_continuity/backup_restore/backup_schedule.adoc
> +When you run a restore operation in a controlled environment, like a disaster recovery test operation, you can avoid a backup collision. Before you restore the resources on the new hub cluster, pause
Would it be possible to expand on this and add : 
When you run a restore operation in a controlled environment, like a disaster recovery test operation, you can avoid a backup collision **when you use the BackupSchedule `paused` property on the backup hub cluster.**
Without this it feels a bit unclear to me .. more like a riddle 

Everything else looks good

2024-08-21 19:09 UTC, birsanv approved these changes
lgtm 
thanks !

2024-08-21 19:21 UTC, swopebe commented on business_continuity/backup_restore/backup_schedule.adoc
> +When you run a restore operation in a controlled environment, like a disaster recovery test operation, you can avoid a backup collision when you use the `BackupSchedule` `paused` property on the back
like a disaster recovery

Please change, see the standard in the IBM Style manual:

https://www.ibm.com/docs/en/ibm-style?topic=word-usage#l

Use with caution like conjunction
Do not use to mean such as.

2024-08-21 19:46 UTC, swopebe commented on business_continuity/backup_restore/backup_schedule.adoc
> +Since the `BackupSchedule.cluster.open-cluster-management.io` resource is still enabled on the secondary hub cluster, it writes backups at the same storage location that corrupts the backup data. Any
This may have already been here but since we are editing...

This can be misread and three is a standard for this:

"Any hub cluster restoring" becomes

"Any hub cluster that restores." (with the relative pronoun, active)
(In the rare occasion that we do use the gerund, you need "that is" for clarity: Any hub cluster _that is_ restoring. 
Standard: https://www.ibm.com/docs/en/ibm-style?topic=grammar-pronouns#relative-pronouns)

Then I recommend making the remaining content user/task-centered, active, imperative voice. Similar to the following, with the comma needed:

_Stop the secondary hub cluster first, or pause the `BackupSchedule.cluster.open-cluster-management.io` resource on the secondary hub cluster before you start the initial hub cluster to the backup collision issue._

RH Guide as well: "Use active voice and present tense."
https://redhat-documentation.github.io/supplementary-style-guide/#conversational-style
https://www.ibm.com/docs/en/ibm-style?topic=medium-tone#importance-of-tone

2024-08-21 19:47 UTC, swopebe requested changes
Couple comments/recommendations with the standards linked

2024-08-29 17:25 UTC, birsanv requested changes

2024-08-29 17:25 UTC, birsanv commented on business_continuity/backup_restore/backup_schedule.adoc
> +Since the `BackupSchedule.cluster.open-cluster-management.io` resource is still enabled on the secondary hub cluster, it writes backups at the same storage location that corrupts the backup data. Any
a typo here : 
resource on the secondary hub cluster before you start the initial hub cluster to the backup collision issue.

should be 

resource on the secondary hub cluster before you start the initial hub cluster to **avoid** the backup collision 
issue.

everything else if good ! 
I'll approve after this change

2024-09-03 18:34 UTC, dockerymick approved these changes
Left one suggestion. I also resolved the conflict bc I cleared the What's new topic in a different PR. Otherwise, approving

2024-09-03 18:34 UTC, dockerymick commented on business_continuity/backup_restore/backup_schedule.adoc
> +| If you paused the {acm-short} backup schedule by using the `BackupSchedule.paused` property, the Velero schedules created by the `BackupSchedule` resources get deleted, and no new hub backups get g
```suggestion
| If you paused the {acm-short} backup schedule by using the `BackupSchedule.paused` property, the Velero schedules created by the `BackupSchedule` resources get deleted and no new hub backups get generated. If you update the `BackupSchedule.paused` property to `False`, the `BackupSchedule` resource status returns to `Enabled` and the Velero schedules get recreated. 
```

2024-09-09 12:49 UTC, merged