Add concept modules for SiteConfig
open-cluster-management/rhacm-docs pull request #6819
Opened 2024-08-26 15:54 UTC by amolnar-rh

Issue: https://issues.redhat.com/browse/TELCODOCS-1875

2024-08-26 20:29 UTC, swopebe commented
This is a large PR that will need some more review. Let's pause here if possible and make the changes that I have mentioned. I will add to this later, but it may be easier for me to check out the branch and edit. I will schedule a meeting before we add more to the PR.

2024-08-26 20:39 UTC, swopebe requested changes
I am still working on this, but have some comments that can be addressed in the meantime. Thank you.

2024-08-26 20:39 UTC, swopebe commented on modules/common-attributes.adoc
>  :sno: single-node OpenShift
We need to double check the naming guidance here, most RH operators are lower case "operator"

2024-08-26 20:39 UTC, swopebe commented on siteconfig/cluster-templates.adoc
> +.Using .toYaml in the ClusterInstance.Spec.Proxy field
We don't use modules, I think that is what line 19 is?

2024-08-26 20:39 UTC, swopebe commented on siteconfig/cluster-templates.adoc
> +[IMPORTANT]
We don't use all caps for special tagging. This is an accessibility issue. See https://stolostron.github.io/rhacm-docs/special_tag_guidance. Additionally, the interruption that RH docs creates has been cause for concern based on some user feedback, so we don't add the boxes to the doc in this manner.

2024-08-26 20:39 UTC, swopebe commented on modules/common-attributes.adoc
>  :sno: single-node OpenShift
For diagrams, see our internal doc for that procedure if this did not go through the design team, it will need to go through that process.

2024-08-26 20:39 UTC, swopebe commented on siteconfig/cluster-templates.adoc
> +[IMPORTANT]
RH is behind on accessibility, but I have taken this to ContentX:

https://www.bdadyslexia.org.uk/advice/employers/creating-a-dyslexia-friendly-workplace/dyslexia-friendly-style-guide

Here we decided not to do this.

2024-08-26 20:39 UTC, swopebe commented on siteconfig/clusterinstance-cr-reference.adoc
> +[#siteconfig-clusterinstance-cr]
We are trying to simplify our filenames to make like a little easier when building links.

`clusterinstance_cr.adoc` should suffice and notice the underscore.

2024-08-26 20:39 UTC, swopebe commented on siteconfig/ref-clusterinstance-cr.adoc
> +.Reference ClusterInstance CR
This is an API doc, see how ours are built.

2024-08-26 20:39 UTC, swopebe commented on siteconfig/siteconfig_intro.adoc
> +[role="_additional-resources"]
all of these are just headers, see the repo for examples.

2024-08-26 20:40 UTC, swopebe commented on modules/common-attributes.adoc
>  :sno: single-node OpenShift
If this went through design, that's fine, we just have to make sure it appears as our other diagrams:

https://stolostron.github.io/rhacm-docs/insert_images

2024-08-26 20:40 UTC, swopebe commented on siteconfig/cluster-templates.adoc
> +[IMPORTANT]
https://accessibility.huit.harvard.edu/design-readability

2024-08-26 20:42 UTC, swopebe commented on siteconfig/ref-clusterinstance-cr.adoc
> +.Reference ClusterInstance CR
https://github.com/stolostron/rhacm-docs/tree/2.12_stage/apis (there is history here, since we came from markdown and had a tool to use at IBM, but we should make it the same. Recently Oliver took this on so he may be able to help. There is a VS Code plugin that we used.

2024-08-27 07:15 UTC, amolnar-rh commented on modules/common-attributes.adoc
>  :sno: single-node OpenShift
Re Operator: In OCP, we use capitalized Operator in the docs. I wanted to make sure that it's not just OCP, and according to the style guide, it needs to be capitalized: https://redhat-documentation.github.io/supplementary-style-guide/#operator

Re diagram: I opened a [ticket](https://issues.redhat.com/browse/DIAGRAMS-454) when the feature went dev preview and set myself a reminder that this must be updated once it's done :) There's a possibility that it'll be done after GA, unfortunately. The current diagram is just a placeholder.

2024-08-27 07:52 UTC, amolnar-rh commented on siteconfig/cluster-templates.adoc
> +.Using .toYaml in the ClusterInstance.Spec.Proxy field
For me, modules are separate files that are referenced in an assembly so I'm not sure. However, this is supposed to be a title for an example codeblock. This is how it looks like in the KB article:
![Screenshot from 2024-08-27 08-47-48](https://github.com/user-attachments/assets/3e46d953-b6b6-4de9-8b73-cb3dda911251)

Now looking at this, if you do use titles in example code snippets, I should rephrase the title, something like Example use of...

2024-08-28 11:54 UTC, swopebe commented on modules/common-attributes.adoc
>  :sno: single-node OpenShift
Ok, I can tell by the font @amolnar-rh that this is likely going to be an accessibility issue so if we don't have a new diagram for GA, I don't want to publish this one. 

I will open an issue for the design team while you are out.

2024-08-28 12:04 UTC, amolnar-rh commented on modules/common-attributes.adoc
>  :sno: single-node OpenShift
I know, the font is not final! I'll remove the diagram for now to avoid accidentally including it.

Please, use the open ticket for any communication with the design team: https://issues.redhat.com/browse/DIAGRAMS-454
I already nicely asked for an earlier completion date but the backlog didn't allow for it :(

2024-09-05 20:51 UTC, swopebe commented on modules/common-attributes.adoc
>  :sno: single-node OpenShift
@oafischer is following up on this design for completion for GA, but we may need to add it in a refresh.

2024-09-06 12:36 UTC, oafischer commented on modules/common-attributes.adoc
>  :sno: single-node OpenShift
The design team has a long backlog, might be a few weeks before we get the diagram.

2024-09-09 00:33 UTC, swopebe commented on siteconfig/siteconfig_intro.adoc
> +include::../siteconfig/clusterinstance-cr-reference.adoc              |
We use underscore for naming files, so wanted to mention that, but I also a not sure we need these, since we ca just point to the API doc.

2024-09-09 00:35 UTC, swopebe commented on siteconfig/siteconfig_intro.adoc
> +* xref:../../installing/installing_on_prem_assisted/installing-on-prem-assisted.adoc#installing-on-prem-assisted[Installing an on-premise cluster using the {ai-full}]
We can work with @oafischer for the conref bc he has an issue to fix ours in our doc, previously set by original author.

{ai-full}

2024-09-09 00:36 UTC, swopebe commented on modules/common-attributes.adoc
>  :sno: single-node OpenShift
If that is the case, then we need to remove the image and wait for it. Our GA is likely moving up, so we will keep the image issue open. Thank you @oafischer

2024-09-09 10:37 UTC, amolnar-rh commented on siteconfig/siteconfig_intro.adoc
> +include::../siteconfig/clusterinstance-cr-reference.adoc              |
Thanks! These are removed but I checked all the remaining file names to only include underscores, should be all correct now.

2024-09-09 14:52 UTC, oafischer commented on siteconfig/siteconfig_intro.adoc
> +* xref:../../installing/installing_on_prem_assisted/installing-on-prem-assisted.adoc#installing-on-prem-assisted[Installing an on-premise cluster using the {ai-full}]
{ai} would make the most sense if we follow the other conrefs that we already have.

2024-09-12 20:41 UTC, swopebe approved these changes
We still have some things to address, indicated in comments. Let's merge, place, then keep working on it.

2024-09-12 20:45 UTC, merged

2024-10-21 10:39 UTC, mpmaruthu commented
Telco RAN QE: Looks good to me.
/Peri M