Add ClusterInstance API docs for SiteConfig Operator
open-cluster-management/rhacm-docs pull request #6828
Opened 2024-08-28 10:46 UTC by amolnar-rh

Issue: https://issues.redhat.com/browse/TELCODOCS-1875

2024-08-28: Everything below line 226 can be peer-reviewed. Everything above it needs SME review.

2024-09-05 20:40 UTC, swopebe approved these changes

2024-09-12 20:39 UTC, swopebe commented
We still need a tech review for this, right?

2024-09-13 08:32 UTC, amolnar-rh commented
> We still need a tech review for this, right?
@swopebe Yes, that's correct. I had a meeting with the SME yesterday to go through a few questions I had. I started implementing them in my local repo but I haven't pushed as of this morning. This is WIP and should be in the PR by the time you come online!

2024-09-27 12:57 UTC, sakhoury requested changes

2024-09-27 12:57 UTC, sakhoury commented on apis/clusterinstance.json.adoc
> +* `clusterinstance/yaml`
Should `clusterinstance/yaml` this be `clusterinstance/json`?

2024-09-27 12:57 UTC, sakhoury commented on apis/clusterinstance.json.adoc
> +Create installation manifests.
The description and section heading are the same. Perhaps we can elaborate a bit more here?

2024-09-27 12:57 UTC, sakhoury commented on apis/clusterinstance.json.adoc
> +* `clusterinstance/yaml`
Same comment as before - should this be `json`?

2024-09-27 12:57 UTC, sakhoury commented on apis/clusterinstance.json.adoc
> +                "cpuset": "2-19,22-39",
This should be removed!

2024-09-27 12:57 UTC, sakhoury commented on apis/clusterinstance.json.adoc
> +        "ignitionConfigOverride": "igen",
I think we should provide a more intuitive example here for `ignitionConfigOverride`. See the nodes example below...

2024-09-27 12:57 UTC, sakhoury commented on apis/clusterinstance.json.adoc
> +|*Header*|*COOKIE* +
Should we not add the `clusterinstance_namespace` and `clusterinstance_name` parameters mentioned above?

2024-09-27 12:57 UTC, sakhoury commented on apis/clusterinstance.json.adoc
> +__required__|Name of the cluster that you want to query.|string
This parameter is not for `ClusterInstance`. We should probably add `clusterinstance_namespace` and `clusterinstance_name` parameters...

2024-09-27 12:57 UTC, sakhoury commented on apis/clusterinstance.json.adoc
> +__optional__|Tracks the observed generation of manifests to avoid unnecessary reconciliation.|integer
```suggestion
__optional__|Tracks the observed generation of the `ClusterInstance`.|integer
```

2024-09-27 12:57 UTC, sakhoury commented on apis/clusterinstance.json.adoc
> +__required__|The specification of the `ClusterInstance`. |<<_rhacm-docs_apis_clusterinstance_jsoncluster_status,status>> object
```suggestion
__required__|The status of the `ClusterInstance`. |<<_rhacm-docs_apis_clusterinstance_jsoncluster_status,status>> object
```

2024-09-27 12:57 UTC, sakhoury commented on apis/clusterinstance.json.adoc
> +__optional__|Specify a list of cluster-level manifests to remove.|array
Perhaps we should mention here that `apiVersion` and `Kind` need to specified for each manifest that needs to be pruned?

2024-09-27 12:57 UTC, sakhoury commented on apis/clusterinstance.json.adoc
> +__optional__|Specify a list of node-level manifests to remove.|array
Perhaps we should mention here that apiVersion and Kind need to specified for each manifest that needs to be pruned?

2024-09-27 12:57 UTC, sakhoury commented on apis/clusterinstance.json.adoc
> +Adding custom labels or roles during installation makes the deployment process more effective and prevents the need for additional reboots after the installation is complete.
I think this needs to be reworded to avoid confusing the user with other fields such as `extraLabels`, `extraAnnotations` and `role`.

2024-09-30 09:24 UTC, amolnar-rh commented on apis/clusterinstance.json.adoc
> +        "ignitionConfigOverride": "igen",
Can I use the same value that's in the nodes.ignitonConfigOverride?
"ignitionConfigOverride": "{\"ignition\": {\"version\": \"3.1.0\"}, \"storage\": {\"files\": [{\"path\": \"/etc/containers/registries.conf\", \"overwrite\": true, \"contents\": {\"source\": \"data:text/plain;base64,foobar==\"}}]}}",

2024-09-30 09:32 UTC, amolnar-rh commented on apis/clusterinstance.json.adoc
> +* `clusterinstance/yaml`
I'm not sure... Checking the other APIs, it looks like most use yaml and still have a request body in json. For example:

* https://docs.redhat.com/en/documentation/red_hat_advanced_cluster_management_for_kubernetes/2.11/html/apis/apis#rhacm-docs_apis_mch_jsoncreatemch
* https://docs.redhat.com/en/documentation/red_hat_advanced_cluster_management_for_kubernetes/2.11/html/apis/apis#rhacm-docs_apis_placement_jsoncreateplacement
* https://docs.redhat.com/en/documentation/red_hat_advanced_cluster_management_for_kubernetes/2.11/html/apis/apis#rhacm-docs_apis_discoveryconfig_jsoncreatediscoveryconfig
* https://docs.redhat.com/en/documentation/red_hat_advanced_cluster_management_for_kubernetes/2.11/html/apis/apis#rhacm-docs_apis_discoveredcluster_jsoncreatediscoveredcluster

I found that only this API says that it consumes json:
* https://docs.redhat.com/en/documentation/red_hat_advanced_cluster_management_for_kubernetes/2.11/html/apis/apis#rhacm-docs_apis_policy_jsoncreatepolicy

2024-09-30 09:36 UTC, amolnar-gh commented on apis/clusterinstance.json.adoc
> +Adding custom labels or roles during installation makes the deployment process more effective and prevents the need for additional reboots after the installation is complete.
Can we chat about this to clarify the differences? Reading all description now, it gets confusing. FYI, the `nodeLabels` description was used from the siteconfigv1 install reference: https://docs.openshift.com/container-platform/4.16/edge_computing/ztp-deploying-far-edge-sites.html#ztp-sno-siteconfig-config-reference_ztp-deploying-far-edge-sites

2024-10-01 18:23 UTC, sakhoury commented on apis/clusterinstance.json.adoc
> +* `clusterinstance/yaml`
Please confirm with other ACM docs folks as well then. I'm okay with `yaml`. I am curious, do we test the API endpoints?

2024-10-01 18:23 UTC, sakhoury commented on apis/clusterinstance.json.adoc
> +        "ignitionConfigOverride": "igen",
Sure!

2024-10-01 18:31 UTC, sakhoury commented on apis/clusterinstance.json.adoc
> +Adding custom labels or roles during installation makes the deployment process more effective and prevents the need for additional reboots after the installation is complete.
I saw that you obtained the description from the original siteconfig-v1 docs... hence I was suggesting rephrasing the description here to avoid nomenclature that would confuse the reader / user. How about replacing "custom labels or roles" with "custom node label"?

2024-10-02 10:16 UTC, amolnar-rh commented on apis/clusterinstance.json.adoc
> +* `clusterinstance/yaml`
@swopebe Could you please take a look?

2024-10-02 10:20 UTC, amolnar-rh commented on apis/clusterinstance.json.adoc
> +Adding custom labels or roles during installation makes the deployment process more effective and prevents the need for additional reboots after the installation is complete.
WDYT?
> Specify custom node labels for your nodes in your managed clusters. These are additional labels that are not used by any {product-title} components, only by the user. When you add a custom node label, it can be associated with a custom machine config pool that references a specific configuration for that label. Adding custom node labels during installation makes the deployment process more effective and prevents the need for additional reboots after the installation is complete.

2024-10-02 15:30 UTC, swopebe commented on apis/clusterinstance.json.adoc
> +* `clusterinstance/yaml`
please leave as json for the repo, this content was converted from markdown and this is how the ACM team build the APIs; there has been no time to rewrite them.

2024-10-03 13:45 UTC, sakhoury commented on apis/clusterinstance.json.adoc
> +Adding custom labels or roles during installation makes the deployment process more effective and prevents the need for additional reboots after the installation is complete.
sgtm :)

2024-10-03 13:56 UTC, sakhoury reviewed
/lgtm

2024-10-03 15:46 UTC, merged