https://issues.redhat.com/browse/ACM-13627 for 2.12
open-cluster-management/rhacm-docs pull request #6834
Opened 2024-08-28 18:05 UTC by dockerymick

2024-08-29 17:22 UTC, swopebe requested changes

2024-08-29 17:22 UTC, swopebe commented on release_notes/release_notes.adoc
> +The documentation team links to the earliest supported {ocp} versions that are tested by Quality Engineering, but later versions are supported. See the link:https://access.redhat.com/support/policy/u
We don't want to point to the humans doing the work here; in a more informal doc we can. 

I would say "The documentation references the earliest ........., unless the component in the documentation is created and tested with only a specific version of {ocp-short}. For full support information, see (add support matrix first) and (add lifecycle).


This should go in both ACM and MCE release notes introductions.

2024-08-29 18:26 UTC, dockerymick commented on release_notes/release_notes.adoc
> +The documentation team links to the earliest supported {ocp} versions that are tested by Quality Engineering, but later versions are supported. See the link:https://access.redhat.com/support/policy/u
```suggestion
The documentation references the earliest supported {ocp} versions, unless the component in the documentation is created and tested with only a specific version of {ocp-short}. For full support information, see the link:https://access.redhat.com/articles/7073065[Support matrix] and the link:https://access.redhat.com/support/policy/updates/advanced-cluster-management[Lifecycle & Update Policies for {acm}].
```

2024-08-29 18:27 UTC, dockerymick commented on release_notes/release_notes.adoc
> +The documentation references the earliest supported {ocp} versions, unless the component in the documentation is created and tested with only a specific version of {ocp-short}. For full support infor
```suggestion
The documentation references the earliest supported {ocp} versions, unless the component in the documentation is created and tested with only a specific version of {ocp-short}. For full support information, see the link:https://access.redhat.com/articles/7073065[Support matrix] and the link:https://access.redhat.com/support/policy/updates/advanced-cluster-management[Lifecycle and update policies for {acm}].
```

2024-09-03 18:31 UTC, swopebe commented on clusters/install_upgrade/install_intro.adoc
> +The documentation references the earliest supported {ocp} versions, unless the component in the documentation is created and tested with only a specific version of {ocp-short}. For full support infor
```suggestion
The documentation references the earliest supported {ocp-short} versions, unless a specific component or function is introduced and tested only on a more recent version of {ocp-short}.

For full support information, see the link:https://access.redhat.com/articles/7073030[Support matrix]. For life cycle information, see link:https://access.redhat.com/support/policy/updates/openshift[{ocp} Lifecycle policy].
```

2024-09-03 18:53 UTC, dockerymick commented on clusters/release_notes/release_notes_intro.adoc
> +The documentation references the earliest supported {ocp} versions, unless the component in the documentation is created and tested with only a specific version of {ocp-short}. For full support infor
```suggestion
The documentation references the earliest supported {ocp-short} version, unless a specific component or function is introduced and tested only on a more recent version of {ocp-short}.

For full support information, see the link:https://access.redhat.com/articles/7073030[Support matrix]. For lifecycle information, see link:https://access.redhat.com/support/policy/updates/openshift[{ocp} Life Cycle policy].
```

2024-09-03 18:53 UTC, dockerymick commented on install/install_overview.adoc
> +The documentation references the earliest supported {ocp} versions, unless the component in the documentation is created and tested with only a specific version of {ocp-short}. For full support infor
```suggestion
The documentation references the earliest supported {ocp-short} version, unless a specific component or function is introduced and tested only on a more recent version of {ocp-short}.

For full support information, see the link:https://access.redhat.com/articles/7073065[Support matrix] and the link:https://access.redhat.com/support/policy/updates/advanced-cluster-management[Lifecycle and update policies for {acm}].
```

2024-09-03 18:53 UTC, dockerymick commented on release_notes/release_notes.adoc
> +The documentation references the earliest supported {ocp} versions, unless the component in the documentation is created and tested with only a specific version of {ocp-short}. For full support infor
```suggestion
The documentation references the earliest supported {ocp} versions, unless the component in the documentation is created and tested with only a specific version of {ocp-short}.

 For full support information, see the link:https://access.redhat.com/articles/7073065[Support matrix] and the link:https://access.redhat.com/support/policy/updates/advanced-cluster-management[Lifecycle and update policies for {acm}].
```

2024-09-03 19:49 UTC, swopebe approved these changes

2024-09-03 20:03 UTC, merged