https://issues.redhat.com/browse/ACM-13484
open-cluster-management/rhacm-docs pull request #6836
Opened 2024-08-28 19:02 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-13484

2024-08-28 19:03 UTC, jc-berger commented on business_continuity/backup_restore/backup_arch.adoc
> +When you add the `cluster.open-cluster-management.io/backup` label to a resource, the resource is automatically backed up in the `acm-resources-generic-schedule` backup. Except for the resources, `Se
Dev reviewers: 

I made some additional changes here to make this content a bit tighter and more user focused. let me know what you think.

2024-08-28 19:04 UTC, jc-berger commented on business_continuity/backup_restore/backup_hub_config.adoc
> +If you want to deploy a new hub cluster at the time the disaster happens and restore all your primary hub cluster data on this new hub cluster instead of building an `active-passive` configuration, s
I'm happy to make this a simple 3 point bullet list. Seems like we could divide into two sections like I did, so let me know what you think.

2024-08-28 19:05 UTC, jc-berger commented on business_continuity/backup_restore/backup_restore.adoc
> +. Go to your hub cluster and create a `restore.cluster.open-cluster-management.io` resource.
Dev reviewers:

I see in the Jira that it asked to move this content down. This is a pretty short section, so I turned into several steps. Let me know what you think.

2024-08-28 19:06 UTC, jc-berger commented on business_continuity/backup_restore/backup_schedule.adoc
> +<3> *Optional:* If you set it to `true`, it enables the automatic import feature, importing clusters in a restore operation.
Do we need *Optional:* here?

2024-08-28 19:06 UTC, jc-berger commented on business_continuity/backup_restore/backup_schedule.adoc
> +** `useManagedServiceAccount` is an optional property which can enable the automatic import feature, importing clusters in a restore operation.
Do we need this bullet list of the properties? Seems like we have it all in the YAML? 

Conversely, we can remove the < 1 -4 > in the YAML and just have this list of properties here.

2024-08-28 19:07 UTC, jc-berger commented on business_continuity/backup_restore/backup_schedule.adoc
> -. As a reminder, the restore operation is run on a different hub cluster for restore scenarios. To initiate a restore operation, create a `restore.cluster.open-cluster-management.io` resource on the
I want to make sure I deleted all the proper sections. 

Correct me if I either deleted something I shouldn't have or overlooked content that needs to be deleted :)

2024-08-28 19:47 UTC, birsanv requested changes
thank you Jake for all the quick turnaround , I didn't expect to have this done this soon :) 

I have a few request changes but most of it looks great

2024-08-28 19:47 UTC, birsanv commented on business_continuity/backup_restore/backup_arch.adoc
> +When you add the `cluster.open-cluster-management.io/backup` label to a resource, the resource is automatically backed up in the `acm-resources-generic-schedule` backup. Except for the resources, `Se
This 
Except for the resources, `Secrets` and `ConfigMap` which you can always find under the `backup acm-credentials-schedule-`.

Should be 
Except for  `Secrets` and `ConfigMap` resources, which are always baced up under the `backup acm-credentials-schedule-`.

2024-08-28 19:47 UTC, birsanv commented on business_continuity/backup_restore/backup_hub_config.adoc
> +If you want to deploy a new hub cluster at the time the disaster happens and restore all your primary hub cluster data on this new hub cluster instead of building an `active-passive` configuration, s
looks good

2024-08-28 19:47 UTC, birsanv commented on business_continuity/backup_restore/backup_restore.adoc
> +. Go to your hub cluster and create a `restore.cluster.open-cluster-management.io` resource.
It's a bit confusing since the required step ( create restore resource ) is combined with the optional steps ( verify restore worked ) :) 

Can we have the following content : 

Use the restore-acm sample below if you want to restore all data at once.

apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Restore
metadata:
  name: restore-acm
  namespace: open-cluster-management-backup
spec:
  cleanupBeforeRestore: CleanupRestored
  veleroManagedClustersBackupName: latest
  veleroCredentialsBackupName: latest
  veleroResourcesBackupName: latest

After you create the restore.cluster.open-cluster-management.io resource on the hub cluster, run the following command to get the status of the restore operation:

oc **describe** -n open-cluster-management-backup restore-acm

2024-08-28 19:47 UTC, birsanv commented on business_continuity/backup_restore/backup_schedule.adoc
> +useManagedServiceAccount: true <3>
This needs to be indented, should go under veleroTtl, like this ( same for paused ) - aligned with the name, namespace.. 

apiVersion: cluster.open-cluster-management.io/v1beta1
kind: BackupSchedule
metadata:
  name: schedule-acm
  namespace: open-cluster-management-backup
spec:
  veleroSchedule: 0 */2 * * * 
  veleroTtl: 120h 
  useManagedServiceAccount: true <3>
  paused: false <4>

2024-08-28 19:47 UTC, birsanv commented on business_continuity/backup_restore/backup_schedule.adoc
> +. Since the restore operation runs on a different hub cluster for restore scenarios, initiate a restore operation by creating a `restore.cluster.open-cluster-management.io` resource on the hub cluste
Delete all from line 46 to line 112

2024-08-28 19:47 UTC, birsanv commented on business_continuity/backup_restore/backup_restore.adoc
> +* Only one `restore.cluster.open-cluster-management.io` can run at one moment.
Maybe this 
Only one `restore.cluster.open-cluster-management.io` can run at one moment.

should be 
Only one `restore.cluster.open-cluster-management.io` can run at one **time**.

2024-09-05 14:25 UTC, birsanv commented on business_continuity/backup_restore/backup_schedule.adoc
> +<3> *Optional:* If you set it to `true`, it enables the automatic import feature, importing clusters in a restore operation.
yes, this is an optional property

2024-09-05 14:27 UTC, birsanv commented on business_continuity/backup_restore/backup_schedule.adoc
> +** `useManagedServiceAccount` is an optional property which can enable the automatic import feature, importing clusters in a restore operation.
The list explains what the properties do , so yes, we need the bullet list

And I think the 1-4 in the YAML maps the props from the yaml to the explanation in the bulleted list

2024-09-05 14:28 UTC, birsanv commented on business_continuity/backup_restore/backup_schedule.adoc
> +. Since the restore operation runs on a different hub cluster for restore scenarios, initiate a restore operation by creating a `restore.cluster.open-cluster-management.io` resource on the hub cluste
@jc-berger this is not done yet

2024-09-05 14:29 UTC, birsanv commented on business_continuity/backup_restore/backup_schedule.adoc
> +useManagedServiceAccount: true <3>
@jc-berger this is still outstanding, the useManagedServiceAccount and paused properties are not indented properly

2024-09-05 14:29 UTC, birsanv commented on business_continuity/backup_restore/backup_restore.adoc
> +* Only one `restore.cluster.open-cluster-management.io` can run at one moment.
@jc-berger still outstanding

2024-09-05 14:30 UTC, birsanv commented on business_continuity/backup_restore/backup_restore.adoc
> +. Go to your hub cluster and create a `restore.cluster.open-cluster-management.io` resource.
@jc-berger this was not addressed

2024-09-05 14:30 UTC, birsanv commented on business_continuity/backup_restore/backup_arch.adoc
> +When you add the `cluster.open-cluster-management.io/backup` label to a resource, the resource is automatically backed up in the `acm-resources-generic-schedule` backup. Except for the resources, `Se
@jc-berger this was not addressed

2024-09-09 14:04 UTC, jc-berger commented on business_continuity/backup_restore/backup_schedule.adoc
> +. Since the restore operation runs on a different hub cluster for restore scenarios, initiate a restore operation by creating a `restore.cluster.open-cluster-management.io` resource on the hub cluste
@birsanv thanks! Forgive me if I didn't delete all the necessary lines. It seems like I did delete those lines, but looking at the lines of the new file, are you saying you want the follow content removed to? `avoiding backup collisons` ?

2024-09-09 15:24 UTC, birsanv approved these changes
lgtm thanks!

2024-09-10 14:13 UTC, dockerymick requested changes

2024-09-10 14:13 UTC, dockerymick commented on business_continuity/backup_restore/backup_arch.adoc
> +You can use a {acm-short} schedule to backup hub resources, which are grouped in separate backup files, based on the resource type or label annotations.
```suggestion
You can use a {acm-short} schedule to backup hub cluster resources, which are grouped in separate backup files, based on the resource type or label annotations.
```

2024-09-10 14:13 UTC, dockerymick commented on business_continuity/backup_restore/backup_arch.adoc
> +When you add the `cluster.open-cluster-management.io/backup` label to a resource, the resource is automatically backed up in the `acm-resources-generic-schedule` backup, except for the `Secrets` and
directional language is being used ("under"). Can the following statement be shortened to "When you add the `cluster.open-cluster-management.io/backup` label to a resource, the resource is automatically backed up in the `acm-resources-generic-schedule` backup, except for the `Secrets` and `ConfigMap` resources which are always back up under the `backup acm-credentials-schedule-`" 

TO 
"When you add the `cluster.open-cluster-management.io/backup` label to a resource, the resource is automatically backed up in the `acm-resources-generic-schedule` backup, except for the `Secrets` and `ConfigMap` resources." 

Is the part that I'm suggesting to remove needed? 

I would also change "Doing this, you ensure.." to "When you set the `cluster.open-cluster-management.io/backup` label to `cluster-activation`, this ensures that the resource is not restored unless you activate the managed cluster. View the following example:"

2024-09-10 14:13 UTC, dockerymick commented on business_continuity/backup_restore/backup_arch.adoc
> +*Note:* Use the `cluster-activation` value for the `cluster.open-cluster-management.io/backup` label if you want the resources to be restored when the managed clusters activation resources are restor
Reminder to use present tense, change "Restoring the managed clusters..." to "When you restore the managed clusters activation resources, restore starts for managed clusters that are actively managed by the hub cluster." 

or something similar

2024-09-10 14:13 UTC, dockerymick commented on business_continuity/backup_restore/backup_hub_config.adoc
> +For more information about passive resources, see the following restore options
```suggestion
For more information about passive resources, see the following restore options:
```

2024-09-10 14:13 UTC, dockerymick commented on business_continuity/backup_restore/backup_hub_config.adoc
> +- xref:../backup_restore/backup_restore.adoc#restore-all-resources[Restoring all resources].
```suggestion
- If you want to deploy a new hub cluster at the time the disaster happens and restore all your primary hub cluster data on this new hub cluster instead of building an `active-passive` configuration, see the xref:../backup_restore/backup_restore.adoc#restore-all-resources[Restoring all resources] topic.
```

2024-09-10 14:13 UTC, dockerymick commented on business_continuity/backup_restore/backup_restore.adoc
> +----
I also noticed that the command to get the status of a restore resource is different from the one mentioned on line 11

```suggestion
After you create the `restore.cluster.open-cluster-management.io` resource on the hub cluster, get the status of the restore operation by running the following command: 

[source,bash]
----
oc describe -n open-cluster-management-backup restore-acm
----
```

2024-09-10 14:13 UTC, dockerymick commented on business_continuity/backup_restore/backup_restore.adoc
> +To restore all the data, use the following `restore-acm` sample:
Since there are more than 3 H2 headers, I recommend that you add a TOC in the file. Since there were no changes earlier in the file, I am unable to make the comment on an earlier line. This will be beneficial for the user. On line 18 can probably be the start of a new section named "Backup types for restoring resources.


The following details seem misplaced: 

"After you create a `restore.cluster.open-cluster-management.io` resource on the hub cluster, you can run the following command to get the status of the restore operation: 
----
oc get restore -n open-cluster-management-backup
----
You can also verify that the backed up resources that are contained by the backup file are created.

*Note:* The `restore.cluster.open-cluster-management.io` resource runs once unless you use the `syncRestoreWithNewBackups` option and set it to `true`, as mentioned in the <<restore-passive-resources,Restore passive resources>> section. If you want to run the same restore operation again after the restore operation is complete, you must create a new `restore.cluster.open-cluster-management.io` resource with the same `spec` options."

It seems like its important to mention that the "restore resource is run once by default" earlier in the file. If the following statement is mentioned in the "Restore passive resources", we probably don't need the note: "The `restore.cluster.open-cluster-management.io` resource runs once unless you use the `syncRestoreWithNewBackups` option and set it to `true`" and "If you want to run the same restore operation again after the restore operation is complete, you must create a new `restore.cluster.open-cluster-management.io` resource with the same `spec` options."

Since the following command is mentioned later in the file (line 203), it seems like we don't need to mention it so early in the file: `oc get restore -n open-cluster-management-backup`.  

If you agree with my suggestion, I recommend the you introduce the new TOC on line 8

2024-09-10 14:13 UTC, dockerymick commented on business_continuity/backup_restore/backup_restore.adoc
>  == Using other restore samples
These suggestions are to improve the code in the file:

* I would change "View the following Restore section to view the YAML examples to restore different types of backed up files." TO "View the following YAML examples to restore different types of backed up files:"
* We should remove the double asterisks, let's just use one.
* Remember to add a new line break before the plus sign so that the YAML explain is grayed out correctly.
* The plus signs that are between each example are not necessary, i would delete those

2024-09-10 14:13 UTC, dockerymick commented on business_continuity/backup_restore/backup_schedule.adoc
> +Complete the following steps to schedule backups:
I recommend that you add a statement explaining the benefit of scheduling backups

2024-09-10 14:13 UTC, dockerymick commented on business_continuity/backup_restore/backup_schedule.adoc
>  +
```suggestion

+
[source,bash]
```

2024-09-10 14:13 UTC, dockerymick commented on business_continuity/backup_restore/backup_schedule.adoc
>  +
Reminder to add a new line break on line 13. the plus sign is not required before the callouts. Please start the callout on line 27
```suggestion
```

2024-09-10 14:13 UTC, dockerymick commented on business_continuity/backup_restore/backup_schedule.adoc
> +<1> Creates a backup every 2 hours
```suggestion
<1> Creates a backup every 2 hours.
```

2024-09-10 14:13 UTC, dockerymick commented on business_continuity/backup_restore/backup_restore.adoc
>  *Notes*:
```suggestion
*Notes:*
```

2024-09-10 14:13 UTC, dockerymick commented on business_continuity/backup_restore/backup_schedule.adoc
> +** `paused` is an optional property which can pause the backup schedule, deleting all Velero schedules created by the resource.
I recommend that you move the parameter descriptions to the callouts. Then remove the content on lines 32-38. For example:

<1> The `veleroSchedule` is a required property and defines a cron job for scheduling the backups. In the previous example, it is defined to create a backup every 2 hours.

2024-09-10 14:13 UTC, dockerymick commented on business_continuity/backup_restore/backup_schedule.adoc
>  +
```suggestion

+
[source,bash]
```

2024-09-12 17:53 UTC, jc-berger commented on business_continuity/backup_restore/backup_arch.adoc
> +When you add the `cluster.open-cluster-management.io/backup` label to a resource, the resource is automatically backed up in the `acm-resources-generic-schedule` backup, except for the `Secrets` and
Thanks, Mikela! Talking to Valentina, I don't think it's a good idea to remove the content you suggested because we want users to know that the specified resources are always in that designated place. I did remove the directional language so please let me know what you think :)

2024-09-12 18:55 UTC, jc-berger commented on business_continuity/backup_restore/backup_schedule.adoc
> +** `paused` is an optional property which can pause the backup schedule, deleting all Velero schedules created by the resource.
When I was talking to Valentina about this, she did prefer to have a list of callouts and a separate list of descriptions. 

Are you cool if we keep it as is? Or do you have major concerns with how the content currently reads?

2024-09-12 20:33 UTC, dockerymick commented on business_continuity/backup_restore/backup_schedule.adoc
> +** `paused` is an optional property which can pause the backup schedule, deleting all Velero schedules created by the resource.
My main concern is just the structure of the doc. From my perspective, it makes sense to explain the parameters in the callouts and we would also be using less lines in the file. We do not have a max number of lines that we adhere to, but it just seems like it will be convenient for the user to read the description, with a brief explanation of the value. 
<img width="1274" alt="Screenshot 2024-09-12 at 4 29 14 PM" src="https://github.com/user-attachments/assets/065ef115-af4c-455b-b5ee-ee1cf8300791">

2024-09-12 20:35 UTC, dockerymick commented on business_continuity/backup_restore/backup_restore.adoc
> +To restore all the data, use the following `restore-acm` sample:
@jc-berger

2024-09-13 11:00 UTC, jc-berger commented on business_continuity/backup_restore/backup_schedule.adoc
> +** `paused` is an optional property which can pause the backup schedule, deleting all Velero schedules created by the resource.
Thanks, @dockerymick ! 

@birsanv would you please take a look at my new commit, applying Mikela's feedback, and let me know what you think? Thanks :)

2024-09-13 15:14 UTC, dockerymick approved these changes
One suggestion. Some of the files still have walls of text, but I would like for us to work on that in a tech debt issue so that you can address other train issues.

2024-09-13 15:14 UTC, dockerymick commented on business_continuity/backup_restore/backup_arch.adoc
> +When you add the `cluster.open-cluster-management.io/backup` label to a resource, the resource is automatically backed up in the `acm-resources-generic-schedule` backup, except for the `Secrets` and
```suggestion
When you add the `cluster.open-cluster-management.io/backup` label to a resource, the resource is automatically backed up in the `acm-resources-generic-schedule` backup, except for the `Secrets` and `ConfigMap` resources which are backed up in the `backup acm-credentials-schedule-`. Set the label value to `cluster-activation` if you need to restore any of the resources after you move the managed clusters to the new hub cluster, and when you use the `veleroManagedClustersBackupName:latest` on the restored resource.

When you set the `cluster.open-cluster-management.io/backup` label to `cluster-activation`, you ensure that the resource is not restored unless you activate the managed cluster. View the following example:
```

2024-09-16 13:51 UTC, birsanv commented on business_continuity/backup_restore/backup_schedule.adoc
> +** `paused` is an optional property which can pause the backup schedule, deleting all Velero schedules created by the resource.
looks good , thanks !

2024-09-16 13:52 UTC, merged