https://issues.redhat.com/browse/ACM-13654
open-cluster-management/rhacm-docs pull request #6842
Opened 2024-08-29 13:39 UTC by dockerymick

2024-08-29 14:02 UTC, saswatamcode reviewed
Thanks a lot for taking this up! Attaching comments from our call

2024-08-29 14:02 UTC, saswatamcode commented on observability/observe_environments_intro.adoc
> +// I need help with understanding the cost savings, how does observability help the user save costs?
When I mention cost savings, I mean,
- Not having to maintain dedicated complex Observability tooling on your own
- Not having to have SRE-personas work and be on-call to maintain that system and instead use RH support
- Not having to pay costly Observability vendors (check with PM)

2024-08-29 14:02 UTC, saswatamcode commented on observability/observe_environments_intro.adoc
> +//What other open source components are being used? The only thing mentioned was Thanos. Is Alertmanager and Prometheus also open source?
Yes! Thanos, Prometheus, Prometheus-Operator, Alertmanager are being used, and all of these are open source.

We could mention something like "All of your Observability is powered by open source. We use existing and widely-adopted observability tooling from the upstream communities, to provide you with an great Observability service.

- Thanos
- Prometheus
- Alertmanager

And link to them with maybe a line each about why we use them?"

2024-08-29 14:02 UTC, saswatamcode commented on observability/observe_environments_intro.adoc
> +The observability component is a service you can use to understand the health and utilization of clusters and your workloads across your fleet. By default, multicluster observability operator is enab
Addition - When you are managing multiple clusters, automating and managing Observability for those clusters is hard. With ACM observability service, we leverage the powers of ACM to give you an automatic monitoring setup experience for all the clusters you manage.

2024-08-29 14:02 UTC, saswatamcode commented on observability/observe_environments_intro.adoc
> -The observability component is a service you can use to understand the health and utilization of clusters across your fleet. By default, multicluster observability operator is enabled during the inst
Why you need Observability or why observability is important?

2024-08-29 14:02 UTC, saswatamcode commented on observability/observe_environments.adoc
> +//should info from the archcitecture be added here?
So I would add some link to architecture section here, mostly so reader can go back and forth between them and understand what config affects what components. Will raise tickets around this!

2024-09-10 14:46 UTC, dockerymick commented on observability/observe_environments.adoc
> +//should info from the archcitecture be added here?
Instead of having the user go back and forth, we should see what arch info is needed. We can absolutely link it in the additional resources section though

2024-09-10 14:50 UTC, dockerymick commented on observability/observe_environments_intro.adoc
> +//Why is Observability important on a multi-cluster level?
```suggestion
Observability can help you identify and assess performance problems without additional testing. 
```

2024-09-10 15:08 UTC, dockerymick commented on observability/observe_environments_intro.adoc
> +The observability component is a service you can use to understand the health and utilization of clusters and your workloads across your fleet. By using the observability service, you are able to aut
```suggestion
Observability can help you identify and assess performance problems without additional tests and support. The {acm} observability component is a service you can use to understand the health and utilization of clusters, and workloads across your fleet.

By using the observability service, you are able to automate and manage the components that are within observability. By default, multicluster observability operator is enabled during the installation of {acm-short}.
```

2024-09-10 15:09 UTC, dockerymick commented on observability/observe_environments_intro.adoc
> +// I need help with understanding the cost savings, how does observability help the user save costs?
Hoping that my changes on lines 4-6 answered these questions. Resolving this convo for now

2024-09-10 15:09 UTC, dockerymick commented on observability/observe_environments_intro.adoc
> +// I need help with understanding the cost savings, how does observability help the user save costs?
```suggestion
```

2024-09-10 15:22 UTC, dockerymick commented on observability/observe_environments_intro.adoc
> +When you enable the observability service, the `observability-endpoint-operator` is automatically deployed to each imported or created managed cluster. This controller starts a metrics collector that
```suggestion
Observability can help you identify and assess performance problems without additional tests and support. The {acm} observability component is a service you can use to understand the health and utilization of clusters, and workloads across your fleet. By using the observability service, you are able to automate and manage the components that are within observability. 

By default, multicluster observability operator is enabled during the installation of {acm-short}. The `observability-endpoint-operator` is automatically deployed to each imported or created managed cluster. This controller starts a metrics collector that collects the data from {ocp} Prometheus, then sends the data to the {acm-short} hub cluster.
```

2024-09-10 15:24 UTC, dockerymick commented on observability/observe_environments_intro.adoc
> +//What other open source components are being used? The only thing mentioned was Thanos. Is Alertmanager and Prometheus also open source?
Would you be opposed to describing the open source components in the arch file?

2024-09-12 14:35 UTC, saswatamcode commented on observability/observe_environments_intro.adoc
> +//What other open source components are being used? The only thing mentioned was Thanos. Is Alertmanager and Prometheus also open source?
Not opposed, we would need to include them in arch file anyway, just wanted to have it in intro

2024-09-12 14:35 UTC, saswatamcode commented on observability/observability_arch.adoc
> +- Thanos: Thanos is a tool you can use to perform global querying across multiple Prometheus instances. You can also use it to store data from Prometheus disl to S3 compatible storage. The following
```suggestion
- Thanos: Thanos is a tool you can use to perform global querying across multiple Prometheus instances. You can also use it to store data from Prometheus to any S3 compatible storage for long term. Thanos is a toolkit of components that allow you to compose a highly available and scalable metrics system.
```

2024-09-12 14:35 UTC, saswatamcode commented on observability/observability_arch.adoc
> +- Prometheus: Prometheus is a monitoring and alerting toolkit that you can use to collect and store metrics as time series data. You can store all scraped samples locally and run rules to aggregrate
```suggestion
- Prometheus: Prometheus is a monitoring and alerting tool that you can use to collect metrics from your application and store these metrics as time series data. You can store all scraped samples locally and run rules to aggregrate or record new time series from existing data, or generate alerts.
```

2024-09-12 14:35 UTC, saswatamcode commented on observability/observability_arch.adoc
> +- Alertmanager: Alertmanager is a component of Prometheus that you can use to receive alerts from client applications. You can deduplicate, group, and route alerts to receiver integrations such as em
```suggestion
- Alertmanager: Alertmanager, as the name suggests, is used to manage alerts from Prometheus. You can use it to receive alerts from multiple Prometheii. You can deduplicate, group, and route alerts to your integrations such as email, Slack, and PagerDuty. You can also configure Alertmanager to silence and inhibit specific alerts.
```

2024-09-12 14:35 UTC, saswatamcode commented on observability/observability_arch.adoc
> +When the Observability service is enabled, the hub cluster is always configured to collect and send metrics to the configured Thanos instance, regardless of whether hub self-management is enabled or
Not entirely sure what this section is talking about

2024-09-12 14:35 UTC, saswatamcode commented on observability/observe_environments.adoc
> +When the Observability service is enabled, the hub cluster is always configured to collect and send metrics to the configured Thanos instance, regardless of whether hub self-management is enabled or
Again kind of confused about this section.

2024-09-12 15:05 UTC, dockerymick commented on observability/observability_arch.adoc
> +When the Observability service is enabled, the hub cluster is always configured to collect and send metrics to the configured Thanos instance, regardless of whether hub self-management is enabled or
This can go into the configuration file

2024-09-12 15:15 UTC, dockerymick commented on observability/observability_arch.adoc
> +- Prometheus: Prometheus is a monitoring and alerting tool that you can use to collect metrics from your application and store these metrics as time series data. You can store all scraped samples loc
```suggestion
- Thanos: Thanos is a tool you can use to perform global querying across multiple Prometheus instances. You can also use it for long-term storage of Prometheus data and persist it in any S3 compatible storage. Thanos is a toolkit of components that allow you to compose a highly-available and scalable metrics system.

- Prometheus: Prometheus is a monitoring and alerting tool that you can use to collect metrics from your application and store these metrics as time series data. You can store all scraped samples locally and run rules to aggregrate or record new time series from existing data, or generate alerts.
```

2024-09-12 15:19 UTC, dockerymick commented on observability/observe_environments_intro.adoc
> +By default, multicluster observability operator is enabled during the installation of {acm-short}. The `observability-endpoint-operator` is automatically deployed to each imported or created managed
```suggestion
Observability service uses existing and widely-adopted observability tools from the open source community. By default, multicluster observability operator is enabled during the installation of {acm-short}. Thanos is deployed within the hub cluster for long-term metrics storage. The `observability-endpoint-operator` is automatically deployed to each imported or created managed cluster. This controller starts a metrics collector that collects the data from {ocp} Prometheus, then sends the data to the {acm-short} hub cluster.
```

2024-09-12 15:20 UTC, dockerymick commented on observability/observe_environments_intro.adoc
> +//What other open source components are being used? The only thing mentioned was Thanos. Is Alertmanager and Prometheus also open source?
```suggestion
```

2024-09-12 15:24 UTC, dockerymick commented on observability/observability_arch.adoc
> +When the Observability service is enabled, the hub cluster is always configured to collect and send metrics to the configured Thanos instance, regardless of whether hub self-management is enabled or
```suggestion
```

2024-09-12 15:32 UTC, saswatamcode approved these changes

2024-09-12 15:52 UTC, dockerymick commented on observability/observe_environments.adoc
> +When the observability service is enabled, the hub cluster is always configured to collect and send metrics to the configured Thanos instance, regardless of whether hub self-management is enabled or
```suggestion
When the observability service is enabled, the hub cluster is always configured to collect and send metrics to the configured Thanos instance, regardless of whether hub self-management is enabled or not. When the hub cluster is self-managed, the `disableHubSelfManagement` parameter is set to `false`, which is the default setting. The `multiclusterhub-operator` enables the `multicluster-observability-operator` pod by default. You must configure the `multicluster-observability-operator` pod.

Metrics and alerts for the hub cluster appear in the `local-cluster` namespace. The `local-cluster` is only available if hub self-management is enabled. You can query the `local-cluster` metrics in the Grafana explorer. View the following topics to learn more:
```

2024-09-12 15:53 UTC, dockerymick commented on observability/observability_arch.adoc
> +Observability service uses exisiting and widely-adopted observabiliity tools from the open source community. View the following descriptions of the tools that are apart of the product observability s
```suggestion
Observability service uses open source observability tools from community. View the following descriptions of the tools that are apart of the product observability service:
```

2024-09-12 16:13 UTC, swopebe commented on observability/customize_observability.adoc
>  Customize the observability configuration to the specific needs of your environment, after you enable observability.
remove extra comma, not needed here. If you wanted to make that a clause, place it at the beginning of the sentence and then use comma.

2024-09-12 16:13 UTC, swopebe commented on observability/customize_observability.adoc
>  Customize the observability configuration to the specific needs of your environment, after you enable observability.
Which may be clearer^^

2024-09-12 16:14 UTC, swopebe commented on observability/main.adoc
> +include::use_observability.adoc[leveloffset=+2]
Is "Use" in the title on this? Is that the best verb over: Enable, Observe?

2024-09-12 16:29 UTC, swopebe commented on observability/observability_arch.adoc
> +- Thanos: Thanos is a tool you can use to perform global querying across multiple Prometheus instances. You can also use it for long-term storage of Prometheus data and persist it in any S3 compatibl
This is a definition list, please see the manual for how to build that. 

And we typically don't repeat the word in the definition, you could break these out so they are easier to read, and reduce some of the length of text.

For all of these, the descriptions can be more concise without as many "it" and repeated words like "You can":

**Thanos:** A monitoring and alerting tool that you can use to collect metrics from your application

Store metrics as time series data. Store all scrapped samples locally. Run rules to aggregate (_misspelled?_) or record new time series from existing data, or generate alerts. (_is it OR and not AND? generate alerts_)

something to consider: https://brainly.com/question/46524136 (given that time and series are joined to describe "data". If not, it could be read as time series-data.

2024-09-12 16:29 UTC, dockerymick commented on observability/main.adoc
> +include::use_observability.adoc[leveloffset=+2]
The title is Using observability. We haven't come up with a better title yet.

2024-09-12 16:29 UTC, swopebe commented on observability/observability_arch.adoc
> +
same for all these, could be reduced and build as a definition list with a paragraph indented below each one.

2024-09-12 16:30 UTC, swopebe commented on observability/observe_environments.adoc
>  = Observability configuration
In a couple, we need filenames, anchors, titles to be similar, concise, but similar

2024-09-12 16:31 UTC, swopebe requested changes
See comments.

2024-09-12 16:31 UTC, swopebe commented on observability/main.adoc
> +include::use_observability.adoc[leveloffset=+2]
Let's look at this after the rest is al built, then.

2024-09-12 16:33 UTC, swopebe commented on observability/observability_arch.adoc
> +- Thanos: Thanos is a tool you can use to perform global querying across multiple Prometheus instances. You can also use it for long-term storage of Prometheus data and persist it in any S3 compatibl
https://www.ibm.com/docs/en/ibm-style?topic=format-lists#definition-lists

2024-09-12 16:45 UTC, dockerymick commented on observability/observe_environments.adoc
>  = Observability configuration
Ok, that was avoided in the earlier restructure because I needed to update all of the link instances.

2024-09-12 17:19 UTC, dockerymick commented
@swopebe thanks for your feedback and review. I updated one of the file names. let me know if you ave other thoughts

2024-09-13 16:23 UTC, swopebe requested changes
nailed it

2024-09-13 16:24 UTC, swopebe approved these changes

2024-09-13 16:28 UTC, saswatamcode approved these changes
Thanks! Small comment

2024-09-13 16:28 UTC, saswatamcode commented on observability/observability_arch.adoc
> +- *Thanos:* A query tool you can use to perform global querying across multiple Prometheus instances, and for long-term storage of Prometheus data and persist it in any S3 compatible storage. You can
```suggestion
- *Thanos:* A toolkit of components you can use to perform global querying across multiple Prometheus instances, and for long-term storage of Prometheus data by persisting it in any S3 compatible storage. You can compose a highly-available and scalable metrics system.
```

2024-09-13 16:39 UTC, swopebe commented on observability/observability_arch.adoc
> +- *Thanos:* A query tool you can use to perform global querying across multiple Prometheus instances, and for long-term storage of Prometheus data and persist it in any S3 compatible storage. You can
I think this is a really long sentence. If we are to keep it, for translation and accessibility purposes we need the following:

A toolkit of components **_that_** you can use to perform global querying across multiple Prometheus instances, 

-----
"and for long-term storage of Prometheus data by persisting it in any S3 compatible storage."

This line reads very confusing. I think this needs to be a stand-alone thought.

2024-09-13 16:40 UTC, swopebe commented on observability/observability_arch.adoc
> +- *Thanos:* A query tool you can use to perform global querying across multiple Prometheus instances, and for long-term storage of Prometheus data and persist it in any S3 compatible storage. You can
@dockerymick I had to re-peer review with this change, FYI. I had approved but we need to work on line 16.

2024-09-13 16:43 UTC, saswatamcode commented on observability/observability_arch.adoc
> +- *Thanos:* A query tool you can use to perform global querying across multiple Prometheus instances, and for long-term storage of Prometheus data and persist it in any S3 compatible storage. You can
Yes, sorry, just wanted the terminology to be correct. I'm fine splitting sentences!

2024-09-13 16:46 UTC, swopebe commented on observability/observability_arch.adoc
> +- *Thanos:* A query tool you can use to perform global querying across multiple Prometheus instances, and for long-term storage of Prometheus data and persist it in any S3 compatible storage. You can
_For long-term storage of Prometheus data, persist it in any S3 compatible storage._

2024-09-13 16:48 UTC, swopebe commented on observability/observability_arch.adoc
> +- *Thanos:* A query tool you can use to perform global querying across multiple Prometheus instances, and for long-term storage of Prometheus data and persist it in any S3 compatible storage. You can
If that works @saswatamcode, that is my only recommended change. We try not to have longer sentences in the doc because a non-sighted user with a screen reader would have a lot to digest.

2024-09-13 16:48 UTC, swopebe commented on observability/observability_arch.adoc
> +- *Thanos:* A query tool you can use to perform global querying across multiple Prometheus instances, and for long-term storage of Prometheus data and persist it in any S3 compatible storage. You can
no need to apologize :-)

2024-09-13 18:36 UTC, dockerymick commented
I applied yall comments, thanks again! Merging this PR

2024-09-13 18:48 UTC, merged