https://issues.redhat.com/browse/ACM-13244 missing host docs
open-cluster-management/rhacm-docs pull request #6876
Opened 2024-09-03 09:20 UTC by oafischer

2.11, 2.10, 2.9 and 2.8

2024-09-03 16:25 UTC, CrystalChun requested changes
Thanks for adding these changes in! The new content looks great, however, it's most relevant under this topic: https://github.com/stolostron/rhacm-docs/blob/2.10_stage/clusters/cluster_lifecycle/cim_auto_add_host.adoc since the converged flow affects hosts that are added automatically via BMH

2024-09-05 09:26 UTC, oafischer commented
Moved the section and updated the PR @CrystalChun, thanks!

2024-09-05 14:54 UTC, CrystalChun approved these changes
/lgtm
Thanks Oliver!

2024-09-05 16:00 UTC, dockerymick requested changes

2024-09-05 16:00 UTC, dockerymick commented on clusters/cluster_lifecycle/cim_auto_add_host.adoc
> +. Create the following ConfigMap on the hub cluster:
```suggestion
. Create the following config map on the hub cluster:
```

2024-09-05 16:00 UTC, dockerymick commented on clusters/cluster_lifecycle/cim_auto_add_host.adoc
> +----
```suggestion
+
[source,bash]
----
oc annotate --overwrite AgentServiceConfig agent unsupported.agent-install.openshift.io/assisted-service-configmap=my-assisted-service-config
----
```

2024-09-05 16:00 UTC, dockerymick commented on clusters/cluster_lifecycle/cim_auto_add_host.adoc
> +- To learn more about converged flow, see xref:../clusters/release_notes/known_issues.adoc#deploy-managed-stuck-pending[Managed cluster stuck in _Pending_ status after deployment].
This link is broken

2024-09-05 17:49 UTC, oafischer commented on clusters/cluster_lifecycle/cim_auto_add_host.adoc
> +- To learn more about converged flow, see xref:../clusters/release_notes/known_issues.adoc#deploy-managed-stuck-pending[Managed cluster stuck in _Pending_ status after deployment].
Should be fixed now, thanks for the review!

2024-09-05 19:22 UTC, dockerymick approved these changes
2 more comments and the link works! Thanks Oliver. Besides my suggestions, this looks good to me. Approving!

2024-09-05 19:22 UTC, dockerymick commented on clusters/cluster_lifecycle/cim_auto_add_host.adoc
> +. Create the following config map on the hub cluster:
```suggestion
. Create the following config map on your hub cluster:
```

2024-09-05 19:22 UTC, dockerymick commented on clusters/cluster_lifecycle/cim_auto_add_host.adoc
> +. Apply the ConfigMap by running the following command:
```suggestion
. Apply the config map by running the following command:
```

2024-09-06 14:52 UTC, merged