https://issues.redhat.com/browse/ACM-13640 import managedhub in hosted mode
open-cluster-management/rhacm-docs pull request #6898
Opened 2024-09-10 01:00 UTC by ldpliu

2024-09-10 01:22 UTC, hchenxa commented on global_hub/global_hub_import_hub_hosted.adoc
> +3. Change addons `work-manager`,`cluster-proxy`,`managed-serviceaccount` namespace to `open-cluster-management-global-hub-agent-addon`
will this impact the existing clusters? or it only impact the new managed hub clusters?

2024-09-10 01:23 UTC, hchenxa commented on global_hub/global_hub_import_hub_hosted.adoc
> +1. Import all the new managedhub clusters in hosted mode.
change managedhub clusters -> managed hub clusters

2024-09-10 01:23 UTC, hchenxa commented on global_hub/global_hub_import_hub_hosted.adoc
> +2. Disable addons `applicationManager` `certPolicyController` `policyController` in all new managedhub clusters namespaces.
change managedhub clusters -> managed hub clusters

2024-09-10 07:09 UTC, ldpliu commented on global_hub/global_hub_import_hub_hosted.adoc
> +3. Change addons `work-manager`,`cluster-proxy`,`managed-serviceaccount` namespace to `open-cluster-management-global-hub-agent-addon`
all managedhub related addons will be impacted, changed.

2024-09-10 08:38 UTC, hchenxa commented on global_hub/global_hub_import_hub_hosted.adoc
> += Importing a managed hub cluster in the hosted mode (Technology Preview)
we should add a per-condition since this feature required the global hub control plane have `local-cluster` enabled since the `local-cluster` will be used as the hosting cluster.

2024-09-11 17:28 UTC, jc-berger requested changes

2024-09-11 17:28 UTC, jc-berger commented on global_hub/global_hub_import_hub_hosted.adoc
> += Importing a managed hub cluster in the hosted mode (Technology Preview)
What do you guys think about creating a "why would I do this?"  or "benefit of doing this?" statement here, right after the title? Something like the following: 

```suggestion
= Importing a managed hub cluster in the hosted mode (Technology Preview)

Import a managed hub cluster in the hosted mode to import any managed hub cluster you want and change the `addons` in the namespace. 
```

2024-09-11 17:28 UTC, jc-berger commented on global_hub/global_hub_import_hub_hosted.adoc
> +- You must enable `local-cluster` in global hub cluster.
```suggestion
- Enable `local-cluster` in the {global-hub} cluster. 
```

2024-09-11 17:28 UTC, jc-berger commented on global_hub/global_hub_import_hub_hosted.adoc
> +To import existing hub cluster which has `local-cluster` enabled, you must use hosted mode to import it.
```suggestion
To import existing hub cluster which has `local-cluster` enabled, complete the following steps: 
```

2024-09-11 17:28 UTC, jc-berger commented on global_hub/global_hub_import_hub_hosted.adoc
> +Set the annotation `global-hub.open-cluster-management.io/import-cluster-in-hosted=true` to globalhub cr will importing all the new managed hub clusters in hosted mode.
```suggestion
. Use the hosted mode to import the existing hub cluster. 
. Set the annotation `global-hub.open-cluster-management.io/import-cluster-in-hosted=true` to `global hub`.  
. Use the custom resource to import all the new managed hub clusters in the hosted mode.
```

2024-09-11 17:28 UTC, jc-berger commented on global_hub/global_hub_import_hub_hosted.adoc
> +With this annotation, globalhub controller will do the following things:
```suggestion
With this annotation, you can use the {global-hub} controller to do the following features: 
```

2024-09-11 17:28 UTC, jc-berger commented on global_hub/global_hub_import_hub_hosted.adoc
> +1. Import all the new managed hub clusters in hosted mode.
```suggestion
- Import all the new managed hub clusters in hosted mode.
```

2024-09-11 17:28 UTC, jc-berger commented on global_hub/global_hub_import_hub_hosted.adoc
> +2. Disable addons `applicationManager` `certPolicyController` `policyController` in all new managed hub clusters namespaces.
```suggestion
- Disable the following `addons` in the new managed hub clusters namespaces: `applicationManager`, `certPolicyController`, and `policyController`.  
```

2024-09-11 17:28 UTC, jc-berger commented on global_hub/global_hub_import_hub_hosted.adoc
> +3. Change addons `work-manager`,`cluster-proxy`,`managed-serviceaccount` namespace to `open-cluster-management-global-hub-agent-addon`(All managed hub clusters related addons will be updated to new n
```suggestion
- Change the managed hub clusters `addons` that are related to the new namespace, including:  `work-manager`,`cluster-proxy`, and `managed-serviceaccount`. Change these namespaces to `open-cluster-management-global-hub-agent-addon`. 
```

2024-09-11 17:28 UTC, jc-berger commented on global_hub/global_hub_import_hub_hosted.adoc
> +
```suggestion
[#global-hub-importing-prereq]
```

2024-09-11 17:28 UTC, jc-berger commented on global_hub/global_hub_import_hub_hosted.adoc
> +Notes: In this mode, we support import managed hub clusters using kubeconfig or api token. RHACM will use this kubeconfig or api token to generate the `auto-import-secret`, which used to connect to m
```suggestion
*Notes:*
- In the hosted mode, you only get support for import managed hub clusters that use `kubeconfig` or API tokens. {acm} uses this `kubeconfig` or API token to generate the `auto-import-secret`, which connects to the managed hub cluster.
- Make sure this `kubeconfig` or API token is always usable. If it expires,  regenerate the `auto-import-secret` in the managed hub namespace, `oc create secret generic auto-import-secret --from-file=kubeconfig=./managedClusterKubeconfig -n cluster1`
```

2024-09-11 17:28 UTC, jc-berger commented on global_hub/global_hub_import_hub_hosted.adoc
> +`oc create secret generic auto-import-secret --from-file=kubeconfig=./managedClusterKubeconfig -n cluster1`
remove this line if you apply my previous comment.

2024-09-12 00:45 UTC, ldpliu commented on global_hub/global_hub_import_hub_hosted.adoc
> += Importing a managed hub cluster in the hosted mode (Technology Preview)
added the line

2024-09-12 00:46 UTC, ldpliu commented on global_hub/global_hub_import_hub_hosted.adoc
> +- You must enable `local-cluster` in global hub cluster.
done

2024-09-12 00:48 UTC, ldpliu commented on global_hub/global_hub_import_hub_hosted.adoc
> +To import existing hub cluster which has `local-cluster` enabled, you must use hosted mode to import it.
removed this line

2024-09-12 00:56 UTC, ldpliu commented on global_hub/global_hub_import_hub_hosted.adoc
> +Notes: In this mode, we support import managed hub clusters using kubeconfig or api token. RHACM will use this kubeconfig or api token to generate the `auto-import-secret`, which used to connect to m
done

2024-09-12 00:56 UTC, ldpliu commented on global_hub/global_hub_import_hub_hosted.adoc
> +
done

2024-09-12 00:56 UTC, ldpliu commented on global_hub/global_hub_import_hub_hosted.adoc
> +3. Change addons `work-manager`,`cluster-proxy`,`managed-serviceaccount` namespace to `open-cluster-management-global-hub-agent-addon`(All managed hub clusters related addons will be updated to new n
done

2024-09-12 00:56 UTC, ldpliu commented on global_hub/global_hub_import_hub_hosted.adoc
> +2. Disable addons `applicationManager` `certPolicyController` `policyController` in all new managed hub clusters namespaces.
done

2024-09-12 00:56 UTC, ldpliu commented on global_hub/global_hub_import_hub_hosted.adoc
> +1. Import all the new managed hub clusters in hosted mode.
done

2024-09-12 00:57 UTC, ldpliu commented on global_hub/global_hub_import_hub_hosted.adoc
> +With this annotation, globalhub controller will do the following things:
The logic is not like this, I changed it, and please review again.

2024-09-13 13:00 UTC, jc-berger requested changes

2024-09-13 13:00 UTC, jc-berger commented on global_hub/global_hub_import_hub_hosted.adoc
> +Import a managed hub cluster in the hosted mode to import any managed hub clusters you want to have `local-cluster` enabled.
```suggestion
Import a managed hub cluster in the hosted mode to import any managed hub clusters where you want to have `local-cluster` enabled. 
```

2024-09-13 13:00 UTC, jc-berger commented on global_hub/global_hub_import_hub_hosted.adoc
> +. Set the annotation `global-hub.open-cluster-management.io/import-cluster-in-hosted=true` to globalhub cr.
```suggestion

. Set the annotation `global-hub.open-cluster-management.io/import-cluster-in-hosted=true` to globalhub cr.
```

2024-09-13 13:00 UTC, jc-berger commented on global_hub/global_hub_import_hub_hosted.adoc
> +. Set the annotation `global-hub.open-cluster-management.io/import-cluster-in-hosted=true` to globalhub cr.
Basically, we need an empty line on line 11 in between `Complete the following steps` and `Set the annotation...`

So it'd be:

Complete the following steps:

1. Set the annotation...

2024-09-13 13:00 UTC, jc-berger commented on global_hub/global_hub_import_hub_hosted.adoc
> +With this annotation, {global-hub} will do the following things:
```suggestion
With this annotation, {global-hub} does the following actions:
```

2024-09-14 00:47 UTC, ldpliu commented on global_hub/global_hub_import_hub_hosted.adoc
> +With this annotation, {global-hub} will do the following things:
done

2024-09-14 00:47 UTC, ldpliu commented on global_hub/global_hub_import_hub_hosted.adoc
> +. Set the annotation `global-hub.open-cluster-management.io/import-cluster-in-hosted=true` to globalhub cr.
done

2024-09-14 00:47 UTC, ldpliu commented on global_hub/global_hub_import_hub_hosted.adoc
> +Import a managed hub cluster in the hosted mode to import any managed hub clusters you want to have `local-cluster` enabled.
done

2024-09-14 00:47 UTC, ldpliu commented on global_hub/global_hub_import_hub_hosted.adoc
> +`oc create secret generic auto-import-secret --from-file=kubeconfig=./managedClusterKubeconfig -n cluster1`
done

2024-09-16 14:12 UTC, merged