https://issues.redhat.com/browse/ACM-14146 Fix taint command
open-cluster-management/rhacm-docs pull request #6917
Opened 2024-09-16 10:27 UTC by oafischer

2.12 and 2.11

2024-09-18 02:25 UTC, haoqing0110 requested changes

2024-09-18 02:25 UTC, haoqing0110 commented on clusters/cluster_lifecycle/taints_tolerations.adoc
> +oc patch managedcluster cluster1 -p '{"spec":{"taints":[{"effect":"NoSelect","key":"cluster.open-cluster-management.io/unreachable"}]}}' --type=merge
If the `taints` section doesn't exist, you can add a taint to a managed cluster by entering a command that resembles the following example:
```
oc patch managedcluster <managed_cluster_name> -p '{"spec":{"taints":[{"key": "key", "value": "value", "effect": "NoSelect"}]}}' --type=merge
```
Or append a taint to the existing taints with the following example: 
```
oc patch managedcluster <managed_cluster_name> --type='json' -p='[{"op": "add", "path": "/spec/taints/-", "value": {"key": "key", "value": "value", "effect": "NoSelect"}}]'

```

2024-09-18 08:43 UTC, oafischer commented on clusters/cluster_lifecycle/taints_tolerations.adoc
> +oc patch managedcluster cluster1 -p '{"spec":{"taints":[{"effect":"NoSelect","key":"cluster.open-cluster-management.io/unreachable"}]}}' --type=merge
Updated

2024-09-20 08:11 UTC, oafischer commented on clusters/cluster_lifecycle/taints_tolerations.adoc
> +oc patch managedcluster cluster1 -p '{"spec":{"taints":[{"effect":"NoSelect","key":"cluster.open-cluster-management.io/unreachable"}]}}' --type=merge
@haoqing0110

2024-09-20 09:11 UTC, haoqing0110 commented
/lgtm

2024-09-20 10:35 UTC, swopebe approved these changes

2024-09-23 14:30 UTC, merged