https://issues.redhat.com/browse/ACM-13640
open-cluster-management/rhacm-docs pull request #6927
Opened 2024-09-16 17:02 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-13640 

See PRs where we added the new import doc: 

https://github.com/stolostron/rhacm-docs/pull/6921 
https://github.com/stolostron/rhacm-docs/pull/6898

2024-09-18 00:34 UTC, ldpliu approved these changes

2024-09-23 17:07 UTC, swopebe requested changes

2024-09-23 17:07 UTC, swopebe commented on release_notes/whats_new.adoc
> +* If you want to have your managed hub clusters to have `local-cluster` enabled, import that managed hub cluster in the hosted mode. See link:../global_hub/global_hub_import_hub_hosted.adoc#global-hu
_If you want to have your managed hub clusters to have `local-cluster` enabled_, (this is off a bit; I think to many "have"?

Do you mean:

If you want your managed hub clusters to have _the_ `local-cluster` enabled, (?)

If so, please change that if it is written in the main documentation, as well. 

Since this is a _release note_, it should be more about  what you can do (active) with the new function. Something like:

You can now have the local-cluster enabled on your managed hub clusters by importing your managed hub cluster in hosted mode. (If that is what you mean here, but it seems hosted mode is the new function so maybe....

You can now import a managed hub cluster in hosted mode to enable your local-cluster. (more active, concise, and emphasizes the new function)

These are just some examples for conciseness and clarity.

2024-09-24 06:27 UTC, ldpliu commented on release_notes/whats_new.adoc
> +* If you want to have your managed hub clusters to have `local-cluster` enabled, import that managed hub cluster in the hosted mode. See link:../global_hub/global_hub_import_hub_hosted.adoc#global-hu
I think `You can now have the local-cluster enabled on your managed hub clusters by importing your managed hub cluster in hosted mode. ` is good to me.

2024-09-24 15:12 UTC, swopebe approved these changes

2024-09-24 15:12 UTC, swopebe commented on release_notes/whats_new.adoc
> +* If you want to have your managed hub clusters to have `local-cluster` enabled, import that managed hub cluster in the hosted mode. See link:../global_hub/global_hub_import_hub_hosted.adoc#global-hu
```suggestion
* You can now have the `local-cluster` enabled on your managed hub clusters by importing your managed hub cluster in hosted mode. See link:../global_hub/global_hub_import_hub_hosted.adoc#global-hub-importing-in-hosted-mode[Importing a managed hub cluster in the hosted mode (Technology Preview)]. 
```

2024-09-24 15:12 UTC, swopebe commented on release_notes/whats_new.adoc
> +* If you want to have your managed hub clusters to have `local-cluster` enabled, import that managed hub cluster in the hosted mode. See link:../global_hub/global_hub_import_hub_hosted.adoc#global-hu
approving based on the developer feedback above so I don't hold it up.

2024-09-24 17:25 UTC, merged