https://issues.redhat.com/browse/ACM-13415 Unknown state troubleshoot
open-cluster-management/rhacm-docs pull request #6936
Opened 2024-09-17 10:09 UTC by oafischer

2.10 only

2024-09-27 01:50 UTC, elgnay commented on clusters/support_troubleshooting/trouble_install_rosa_hcp.adoc
> += Troubleshooting installation status stuck at `Installing` on a {rosa} hosted cluster
What's the official name of ROSA HCP? {rosa} hosted cluster or {rosa} with HCP cluster?

2024-09-27 03:07 UTC, elgnay commented on clusters/support_troubleshooting/trouble_install_rosa_hcp.adoc
> +10 minutes after installing {mce-short}, the `local-cluster` remains in the `Unknown` state. When you check the `klusterlet-agent` pod log in the `open-cluster-management-agent` namespace on your man
on your managed cluster -> on your hub cluster

The managed cluster, in this case, is the hub cluster itself.

2024-09-27 03:14 UTC, elgnay commented on clusters/support_troubleshooting/trouble_install_rosa_hcp.adoc
> +----
All those can be done by a singe command
```
oc get secret local-cluster-import -n local-cluster -o jsonpath='{.data.import\.yaml}' | base64 --decode > import.yaml
```

2024-09-27 03:18 UTC, elgnay commented on clusters/support_troubleshooting/trouble_install_rosa_hcp.adoc
> +oc annotate --overwrite <cluster_name> local-cluster agent.open-cluster-management.io/klusterlet-config='isrg-root-x1-ca'
```
oc annotate --overwrite managedcluster local-cluster agent.open-cluster-management.io/klusterlet-config='isrg-root-x1-ca'
```

2024-09-27 03:19 UTC, elgnay commented on clusters/support_troubleshooting/trouble_unknown_rosa_hcp.adoc
> +oc annotate --overwrite <cluster_name> local-cluster agent.open-cluster-management.io/klusterlet-config='isrg-root-x1-ca'
```
oc annotate --overwrite managedcluster <cluster_name> agent.open-cluster-management.io/klusterlet-config='isrg-root-x1-ca'
```

2024-09-27 03:22 UTC, elgnay commented on clusters/support_troubleshooting/trouble_unknown_rosa_hcp.adoc
> +----
Replace with command below
```
oc get secret <cluster_name>-import -n <cluster_name> -o jsonpath='{.data.import\.yaml}' | base64 --decode > <cluster_name>-import.yaml
```

2024-09-27 03:23 UTC, elgnay commented on clusters/support_troubleshooting/trouble_unknown_rosa_hcp.adoc
> +. Apply the file by running the following command. Replace values where needed:
. Apply the file by running the following command on the managed cluster. Replace values where needed:

2024-09-27 03:25 UTC, elgnay commented on clusters/support_troubleshooting/trouble_unknown_rosa_hcp.adoc
> +. Apply the resource by running the following command:
. Apply the resource by running the following command on the hub cluster:

2024-09-27 03:26 UTC, elgnay commented on clusters/support_troubleshooting/trouble_install_rosa_hcp.adoc
> +. If the `local-cluster` state does not recover in 1 minute, export the `import.yaml` file by running the following command:
. If the `local-cluster` state does not recover in 1 minute, export the `import.yaml` file by running the following command on the hub cluster:

2024-09-27 03:27 UTC, elgnay commented on clusters/support_troubleshooting/trouble_install_rosa_hcp.adoc
> +. Apply the resource by running the following command:
. Apply the resource by running the following command on the hub cluster:

2024-09-27 03:28 UTC, elgnay commented on clusters/support_troubleshooting/trouble_install_rosa_hcp.adoc
> +. Annotate your managed cluster by running the following command. Replace values where needed:
. Annotate your managed cluster by running the following command on the hub cluster:

2024-09-27 03:29 UTC, elgnay commented on clusters/support_troubleshooting/trouble_install_rosa_hcp.adoc
> +. Apply the file by running the following command:
. Apply the file by running the following command on the hub cluster:

2024-09-27 03:30 UTC, elgnay commented on clusters/support_troubleshooting/trouble_unknown_rosa_hcp.adoc
> +. Annotate your managed cluster by running the following command. Replace values where needed:
. Annotate your managed cluster by running the following command on the hub cluster. Replace values where needed:

2024-09-27 03:31 UTC, elgnay commented on clusters/support_troubleshooting/trouble_unknown_rosa_hcp.adoc
> +. For managed clusters that remain `Unknown`, export the `import.yaml` file from the hub cluster by running the following command. Replace values where needed:
. For managed clusters that remain `Unknown`, export the `import.yaml` file from the hub cluster by running the following command on the hub cluster. Replace values where needed:
Comment

2024-09-27 14:27 UTC, oafischer commented on clusters/support_troubleshooting/trouble_install_rosa_hcp.adoc
> += Troubleshooting installation status stuck at `Installing` on a {rosa} hosted cluster
@lahinson might know the answer here, can you chime in?

2024-09-27 15:00 UTC, lahinson commented on clusters/support_troubleshooting/trouble_install_rosa_hcp.adoc
> += Troubleshooting installation status stuck at `Installing` on a {rosa} hosted cluster
The official full name is a mouthful: "Red Hat OpenShift Service on AWS (ROSA) with hosted control planes (HCP)". The full name is used for the first mention. For subsequent mentions, you can use "ROSA with HCP".

2024-09-27 15:01 UTC, lahinson commented on clusters/support_troubleshooting/trouble_install_rosa_hcp.adoc
> += Troubleshooting installation status stuck at `Installing` on a {rosa} hosted cluster
In this case, since the name is in a heading, I'd use "ROSA with HCP", but use the full name on its first instance in the body text.

2024-09-27 15:04 UTC, oafischer commented on clusters/support_troubleshooting/trouble_install_rosa_hcp.adoc
> +----
We generally need to separate individual commands in the docs if they do different things

2024-09-27 15:05 UTC, oafischer commented on clusters/support_troubleshooting/trouble_install_rosa_hcp.adoc
> +oc annotate --overwrite <cluster_name> local-cluster agent.open-cluster-management.io/klusterlet-config='isrg-root-x1-ca'
Updated

2024-09-27 15:05 UTC, oafischer commented on clusters/support_troubleshooting/trouble_install_rosa_hcp.adoc
> +10 minutes after installing {mce-short}, the `local-cluster` remains in the `Unknown` state. When you check the `klusterlet-agent` pod log in the `open-cluster-management-agent` namespace on your man
Updated

2024-09-27 15:05 UTC, oafischer commented on clusters/support_troubleshooting/trouble_unknown_rosa_hcp.adoc
> +oc annotate --overwrite <cluster_name> local-cluster agent.open-cluster-management.io/klusterlet-config='isrg-root-x1-ca'
Updated

2024-09-27 15:06 UTC, oafischer commented on clusters/support_troubleshooting/trouble_unknown_rosa_hcp.adoc
> +----
Same thing here, we generally want to separate commands but I can ask the team and get some feedback

2024-09-27 15:07 UTC, oafischer commented on clusters/support_troubleshooting/trouble_unknown_rosa_hcp.adoc
> +. Apply the file by running the following command. Replace values where needed:
Updated

2024-09-27 15:07 UTC, oafischer commented on clusters/support_troubleshooting/trouble_unknown_rosa_hcp.adoc
> +. Apply the resource by running the following command:
Updated

2024-09-27 15:08 UTC, oafischer commented on clusters/support_troubleshooting/trouble_install_rosa_hcp.adoc
> +. If the `local-cluster` state does not recover in 1 minute, export the `import.yaml` file by running the following command:
Updated

2024-09-27 15:09 UTC, oafischer commented on clusters/support_troubleshooting/trouble_install_rosa_hcp.adoc
> +. Apply the resource by running the following command:
Updated

2024-09-27 15:09 UTC, oafischer commented on clusters/support_troubleshooting/trouble_install_rosa_hcp.adoc
> +. Annotate your managed cluster by running the following command. Replace values where needed:
Updated

2024-09-27 15:10 UTC, oafischer commented on clusters/support_troubleshooting/trouble_install_rosa_hcp.adoc
> +. Apply the file by running the following command:
Updated

2024-09-27 15:11 UTC, oafischer commented on clusters/support_troubleshooting/trouble_unknown_rosa_hcp.adoc
> +. Annotate your managed cluster by running the following command. Replace values where needed:
Updated

2024-09-27 15:11 UTC, oafischer commented on clusters/support_troubleshooting/trouble_unknown_rosa_hcp.adoc
> +. For managed clusters that remain `Unknown`, export the `import.yaml` file from the hub cluster by running the following command. Replace values where needed:
Updated

2024-09-27 15:12 UTC, oafischer commented
Thanks for the review @elgnay, I made some updates, feel free to review again. @lahinson will also take a look at the naming again.

2024-09-27 15:23 UTC, lahinson approved these changes
Just a couple minor things to fix.

2024-09-27 15:23 UTC, lahinson commented on clusters/support_troubleshooting/trouble_unknown_rosa_hcp.adoc
>  == Symptom: All managed clusters become `Unknown` on a {rosa} hosted cluster
```suggestion
== Symptom: All managed clusters become `Unknown` on a ROSA with HCP cluster
```

2024-09-27 15:23 UTC, lahinson commented on clusters/support_troubleshooting/trouble_unknown_rosa_hcp.adoc
>  == Symptom: All managed clusters become `Unknown` on a {rosa} hosted cluster
I don't seem to be able to comment on lines 9 and 17, but I'd replace `{rosa} hosted cluster` with `ROSA with HCP cluster`.

2024-09-30 02:08 UTC, elgnay commented on clusters/support_troubleshooting/trouble_install_rosa_hcp.adoc
> +----
In my opinion, the commands are executed with a single goal – to export the import.yaml for a specific managed cluster. Therefore, it's more efficient to pipe them into a single command. However, if you still feel it's necessary to separate them, please refer to the content below:

---

5. If the local-cluster state does not recover in 1 minute, export the import.yaml file by running the following command on the hub cluster:
```
oc get secret local-cluster-import -n local-cluster -o jsonpath='{.data.import\.yaml}' > import-encoded.yaml
```
6.Decode the file by running the following command:
```
base64 --decode import-encoded.yaml > import.yaml
```
7....

2024-09-30 02:23 UTC, elgnay commented on clusters/support_troubleshooting/trouble_unknown_rosa_hcp.adoc
> +----
Similarly, if you believe it's necessary to separate them, please refer to the content below:

---

5. For managed clusters that remain Unknown, export the import.yaml file from the hub cluster by running the following command on the hub cluster. Replace values where needed:
```
oc get secret <cluster_name>-import -n <cluster_name> -o jsonpath='{.data.import\.yaml}' > <cluster_name>-import-encoded.yaml
```
6. Decode the file by running the following command. Replace values where needed:
```
base64 --decode > <cluster_name>-import-encoded.yaml > <cluster_name>-import.yaml
```
7. ...

2024-09-30 08:32 UTC, oafischer commented on clusters/support_troubleshooting/trouble_unknown_rosa_hcp.adoc
> +----
I asked the team again but generally it is required that we separate commands. I'll get back to you on this

2024-09-30 15:30 UTC, oafischer commented on clusters/support_troubleshooting/trouble_install_rosa_hcp.adoc
> +----
After discussing with the team we can make it a single command, thanks for the patience

2024-09-30 15:32 UTC, swopebe commented on clusters/support_troubleshooting/trouble_install_rosa_hcp.adoc
> +----
We separate when we have, for example, two `oc` commands together but for two actions. We should make those into two steps. For this, I think it is very common to append a command with base64:


`Base64 is a generic term for a number of similar encoding schemes that encode binary data by treating it numerically and translating it into a base-64 representation. The Base64 term originates from a specific MIME-content transfer encoding.`

https://www.base64encode.org/

2024-09-30 15:33 UTC, oafischer commented on clusters/support_troubleshooting/trouble_unknown_rosa_hcp.adoc
> +----
We can combine it

2024-10-01 15:05 UTC, elgnay commented on clusters/support_troubleshooting/trouble_install_rosa_hcp.adoc
> +oc get secret local-cluster-import -n local-cluster -o jsonpath={.data.import .yaml} | base64 --decode > import.yaml
Use `jsonpath={.data.import\.yaml}` instead. The backslash (\) is needed to escape the dot (.) in the jsonpath.

2024-10-01 15:06 UTC, elgnay commented on clusters/support_troubleshooting/trouble_unknown_rosa_hcp.adoc
> +oc get secret <cluster_name>-import -n <cluster_name> -o jsonpath={.data.import .yaml} | base64 --decode > <cluster_name>-import.yaml
Use `jsonpath={.data.import\.yaml}` instead.

2024-10-01 15:08 UTC, oafischer commented on clusters/support_troubleshooting/trouble_install_rosa_hcp.adoc
> +oc get secret local-cluster-import -n local-cluster -o jsonpath={.data.import .yaml} | base64 --decode > import.yaml
Updated

2024-10-01 15:08 UTC, oafischer commented on clusters/support_troubleshooting/trouble_unknown_rosa_hcp.adoc
> +oc get secret <cluster_name>-import -n <cluster_name> -o jsonpath={.data.import .yaml} | base64 --decode > <cluster_name>-import.yaml
Updated

2024-10-04 14:12 UTC, oafischer commented
@elgnay Once you are back, let me know if everything looks good and I'll go ahead and merge the PR.

2024-10-04 14:34 UTC, dockerymick requested changes

2024-10-04 14:34 UTC, dockerymick commented on clusters/support_troubleshooting/trouble_install_rosa_hcp.adoc
> += Troubleshooting installation status stuck at `Installing` on a ROSA with HCP cluster
In 2.10, I did not see mentions of "HCP". HCP is also listed as a unapproved acronym. There is no short form approved based on the product names list.

2024-10-04 14:34 UTC, dockerymick commented on clusters/support_troubleshooting/trouble_install_rosa_hcp.adoc
> +When installing {mce} on a Red Hat OpenShift Service on AWS (ROSA) with hosted control planes (HCP) cluster, {mce-short} becomes stuck at the `Installing` step and the `local-cluster` remains in the
```suggestion
When you install {mce} on a Red Hat OpenShift Service on AWS (ROSA) with hosted control planes cluster, {mce-short} becomes stuck at the `Installing` step and the `local-cluster` remains in the `Unknown` state.
```

2024-10-04 14:34 UTC, dockerymick commented on clusters/support_troubleshooting/trouble_install_rosa_hcp.adoc
> +10 minutes after installing {mce-short}, the `local-cluster` remains in the `Unknown` state. When you check the `klusterlet-agent` pod log in the `open-cluster-management-agent` namespace on your hub
It just seems a little odd to start with the number. What do you think about this suggestion?
```suggestion
The `local-cluster` remains in the `Unknown` state 10 minutes after installing {mce-short}. When you check the `klusterlet-agent` pod log in the `open-cluster-management-agent` namespace on your hub cluster, you see an error that resembles the following: 
```

2024-10-04 14:34 UTC, dockerymick commented on clusters/support_troubleshooting/trouble_install_rosa_hcp.adoc
> +----
I believe we agreed to not use `[source,bash]` for error messages and other messages that did not need to be copy. I'm not sure tho, I'm fine with leaving it as is

2024-10-04 14:34 UTC, dockerymick commented on clusters/support_troubleshooting/trouble_install_rosa_hcp.adoc
> +. Create a `KlusterletConfig` resource add your encoded CA certificate to the `spec`. See the following example:
```suggestion
. Create a `KlusterletConfig` resource by adding your encoded CA certificate to the `spec` parameter section. See the following example:
```

2024-10-04 14:34 UTC, dockerymick commented on clusters/support_troubleshooting/trouble_unknown_rosa_hcp.adoc
> += Troubleshooting all managed clusters become `Unknown` on a ROSA with HCP cluster
Same comment, HCP should be written out to hosted control planes

2024-10-04 14:34 UTC, dockerymick commented on clusters/support_troubleshooting/trouble_unknown_rosa_hcp.adoc
> +On a Red Hat OpenShift Service on AWS (ROSA) with hosted control planes (HCP) cluster, the state of all managed clusters might switch to `Unknown`.
```suggestion
On a Red Hat OpenShift Service on AWS (ROSA) with hosted control planes cluster, the state of all managed clusters might switch to `Unknown`.
```

2024-10-04 14:34 UTC, dockerymick commented on clusters/support_troubleshooting/trouble_install_rosa_hcp.adoc
> +When installing {mce} on a Red Hat OpenShift Service on AWS (ROSA) with hosted control planes (HCP) cluster, {mce-short} becomes stuck at the `Installing` step and the `local-cluster` remains in the
I also didn't see Red Hat OpenShift Service on AWS listed in the product list, but I do see that ROSA is used in the product docs here: https://docs.redhat.com/en/documentation/red_hat_openshift_service_on_aws/4/html/introduction_to_rosa/index

So it should be fine

2024-10-04 14:34 UTC, dockerymick commented on clusters/support_troubleshooting/trouble_unknown_rosa_hcp.adoc
> +The state of all managed cluster on a {rosa} hosted cluster suddenly becomes `Unknown`. When you check the `klusterlet-agent` pod log in the `open-cluster-management-agent` namespace on your managed
```suggestion
The state of all managed cluster on a {rosa} hosted cluster suddenly becomes `Unknown`. When you check the `klusterlet-agent` pod log in the `open-cluster-management-agent` namespace on your managed cluster, you see the following error message: 
```

2024-10-04 14:34 UTC, dockerymick commented on clusters/support_troubleshooting/trouble_unknown_rosa_hcp.adoc
> +. Create a `KlusterletConfig` resource and add your encoded CA certificate to the `spec`. See the following example:
```suggestion
. Create a `KlusterletConfig` resource and add your encoded CA certificate to the `spec` parameter section. See the following example:
```

2024-10-04 14:34 UTC, dockerymick commented on clusters/support_troubleshooting/troubleshooting_mce_intro.adoc
> + * xref:../support_troubleshooting/trouble_unknown_rosa_hcp.adoc#trouble-state-unknown-rosa-hcp[Troubleshooting all managed clusters become `Unknown` on a ROSA with HCP cluster]
Reminder to update the titles

2024-10-04 15:01 UTC, oafischer commented on clusters/support_troubleshooting/trouble_install_rosa_hcp.adoc
> +----
Talked with Brandi about this recently, I was wrong and we actually need to add it to all terminal messages.

2024-10-07 13:16 UTC, dockerymick approved these changes
2 more comments here. Otherwise, this looks good to me ! Thanks Oliver

2024-10-07 13:16 UTC, dockerymick commented on clusters/support_troubleshooting/trouble_install_rosa_hcp.adoc
> +The `local-cluster` remains in the `Unknown` state 10 minutes after installing {mce-short}. When you check the `klusterlet-agent` pod log in the `open-cluster-management-agent` namespace on your hub
The following what? What do you think about this suggestion? 
```suggestion
The `local-cluster` remains in the `Unknown` state 10 minutes after installing {mce-short}. When you check the `klusterlet-agent` pod log in the `open-cluster-management-agent` namespace on your hub cluster, you see the following error message: 
```

2024-10-07 13:16 UTC, dockerymick commented on clusters/support_troubleshooting/trouble_unknown_rosa_hcp.adoc
> +The state of all managed cluster on a {rosa} hosted cluster suddenly becomes `Unknown`. When you check the `klusterlet-agent` pod log in the `open-cluster-management-agent` namespace on your managed
The {rosa} conref needs to be removed from this line because we don't have a conref created for 2.10.

https://github.com/stolostron/rhacm-docs/blob/2.10_stage/modules/common-attributes.adoc

2024-10-07 15:35 UTC, oafischer commented on clusters/support_troubleshooting/trouble_unknown_rosa_hcp.adoc
> +The state of all managed cluster on a {rosa} hosted cluster suddenly becomes `Unknown`. When you check the `klusterlet-agent` pod log in the `open-cluster-management-agent` namespace on your managed
Wow where's the melting face emote when you need it, thanks for catching that

2024-10-07 19:09 UTC, dockerymick commented on clusters/support_troubleshooting/trouble_unknown_rosa_hcp.adoc
> +The state of all managed cluster on a {rosa} hosted cluster suddenly becomes `Unknown`. When you check the `klusterlet-agent` pod log in the `open-cluster-management-agent` namespace on your managed
No worries!

2024-10-07 19:15 UTC, dockerymick commented on clusters/support_troubleshooting/troubleshooting_mce_intro.adoc
> + * xref:../support_troubleshooting/trouble_install_rosa_hcp.adoc#trouble-install-stuck-rosa-hcp[Troubleshooting installation status stuck at `Installing` on a ROSA with hosted control planes cluster]
Even though line 6 wasn't a part of this change, it appeared as broken when I ran the link check tool

2024-10-10 08:59 UTC, elgnay commented
LGTM

2024-10-10 09:17 UTC, merged