https://issues.redhat.com/browse/ACM-13088
open-cluster-management/rhacm-docs pull request #6949
Opened 2024-09-18 15:56 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-13088

2024-09-18 16:10 UTC, dhaiducek commented
This looks good--thanks for the quick update, @jc-berger!

Similarly, could you also update this line in the `config_gk_operator.adoc`?

https://github.com/stolostron/rhacm-docs/blob/2b1041f2fda221c15df0c5aa292e8a5382d8999d/governance/gatekeeper_operator/config_gk_operator.adoc?plain=1#L4

Maybe something like this?

> Install the {gate} from the {ocp} catalog to install Gatekeeper on your cluster. See _Adding Operators to a cluster_ in the {ocp-short} documentation in the _Additional resources_ section. With {acm-short} you can use a policy to install the {gate} by using the governance framework.

2024-09-18 18:58 UTC, drkho commented
Sounds good to me. Thanks, all.

2024-09-23 17:17 UTC, dockerymick approved these changes
This looks good to me! Thanks Jake!

2024-09-23 17:23 UTC, swopebe requested changes

2024-09-23 17:23 UTC, swopebe commented on governance/gatekeeper_operator/config_gk_operator.adoc
> +Install the {gate} from the {ocp} catalog to install Gatekeeper on your cluster. See _Adding Operators to a cluster_ in the {ocp-short} documentation and go to the _Additional resources_ section. Wit
"install to install", do we mean this or do we mean to _Access the catalog to install_? 

Please remove the citation from the short description, as this is only a description and should not interrupt the user. This trail to the OCP doc and then to additional info is very odd to me at the beginning of the topic. Should this be appended to a step if it is something the user needs? Or a prereq?

Also, throughout the doc, I think we mean _OLM catalog._ (see the rest of the doc for how we write that, I don't think we call anything the OCP catalog)

2024-09-23 17:23 UTC, swopebe commented on governance/gatekeeper_operator/gk_operator_overview.adoc
> +The {gate} installs Gatekeeper which is a validating webhook with auditing capabilities. Install the {gate} on a {ocp} cluster from the {ocp} operator catalog. With {acm}, you can install Gatekeeper
missing comma here:

Gatekeeper, which


and again, please look at the name of the catalog here and throughout.

2024-09-23 17:23 UTC, swopebe commented on governance/gatekeeper_operator/config_gk_operator.adoc
> +Install the {gate} from the {ocp} catalog to install Gatekeeper on your cluster. See _Adding Operators to a cluster_ in the {ocp-short} documentation and go to the _Additional resources_ section. Wit
For some reason we don't have a prereq section, which we discussed a few meetings ago. All the tasks generally need that and it may be where you put your citations or links.

2024-09-23 17:32 UTC, swopebe requested changes

2024-09-23 17:32 UTC, swopebe commented on governance/gatekeeper_operator/gk_operator_overview.adoc
> +The {gate} installs Gatekeeper which is a validating webhook with auditing capabilities. Install the {gate} on a {ocp} cluster from the {ocp} operator catalog. With {acm}, you can install Gatekeeper
@dhaiducek can you check into this? I think we mean the OLM Catalog?

2024-09-23 17:44 UTC, swopebe commented on governance/gatekeeper_operator/gk_operator_overview.adoc
> +The {gate} installs Gatekeeper which is a validating webhook with auditing capabilities. Install the {gate} on a {ocp} cluster from the {ocp} operator catalog. With {acm}, you can install Gatekeeper
See here where we point to OLM: https://github.com/stolostron/rhacm-docs/blob/64fecc1cc6932390eb7f411d4c5243b43e4c69c7/governance/ansible_grc.adoc#prerequisites

2024-09-25 16:02 UTC, dhaiducek commented on governance/gatekeeper_operator/config_gk_operator.adoc
> +Install the {gate} from the {ocp} catalog to install Gatekeeper on your cluster. See _Adding Operators to a cluster_ in the {ocp-short} documentation and go to the _Additional resources_ section. Wit
@swopebe You're correct, it's the OLM catalog.

The "install to install" is technically correct. The flow is that the operator is installed on the cluster through OLM resources, after which the creation of the custom Gatekeeper operator resource on the cluster tells the Gatekeeper operator to install Gatekeeper.

2024-09-25 20:16 UTC, dhaiducek approved these changes
LGTM! Thanks for the update!

2024-09-26 19:13 UTC, swopebe commented on governance/gatekeeper_operator/config_gk_operator.adoc
Is this a prereq to configuring? I am still a bit confused about why the user needs to go to this link. TY for using the correct version of the link and thinking ahead there!

2024-09-26 19:17 UTC, swopebe commented on governance/gatekeeper_operator/config_gk_operator.adoc
This looks really good! Making it clear if or why this is a prereq is my only remaining comment. (If it is not a prereq and just supplemental info, then we don't need the section. I just wanted to make sure we did not place this in the short description.

- *Required access*: Cluster administrator. (Can be in the prereqs but it can also stand alone if you have no actual prereqs.)

2024-09-26 19:18 UTC, swopebe approved these changes

2024-09-26 21:12 UTC, merged