Swope brandi install updated (wtg on developer)
open-cluster-management/rhacm-docs pull request #6968
Opened 2024-09-23 17:53 UTC by swopebe

2024-09-23 17:55 UTC, swopebe commented on install/install_connected.adoc
> +. Click to find that your operator is listed.
@cameronmwall we had a note to add a verification step during our doc test, but I forgot the thing they need to click and I didn't write it down.

Can you get me a better verification step here for them to see the MCH resource?

2024-10-10 17:37 UTC, cameronmwall commented on install/install_connected.adoc
> +. Click to find that your operator is listed.
so, if we want for them to be able to be sure that their installation was successful I think we can say something along the lines of "clicking the 'MultiClusterHub' tab will show a list of resources which includes the MCH resource just created. When the status becomes 'Running', the installation is complete"

2024-10-10 20:38 UTC, swopebe commented on install/cluster_size.adoc
> +| See the link:https://cloud.google.com/docs/quotas/view-manage#managing_your_quota_console[View and manage quotas] for more information about quotas.
These links are third part and were not correct.

2024-10-10 20:38 UTC, swopebe commented on install/install_connected.adoc
> +Install {acm} through {olm}, which manages the installation, upgrade, and removal of the components that encompass the {acm-short} hub cluster. When you install the {acm-short} operator, you create t
This is the explanation that we need to tell the user how MCE is installed with the MCH resource.

2024-10-10 20:39 UTC, swopebe commented on install/install_connected.adoc
present tense

2024-10-10 20:40 UTC, swopebe commented on install/install_connected.adoc
>  ----
obvious change here

2024-10-10 21:01 UTC, swopebe commented on install/uninstall.adoc
> +When you use the {ocp} console to uninstall, you remove the `MultiClusterHub` resource to delete the object. Wait for the status, then delete the operator. Complete the following steps to uninstall b
@cameronmwall can you check this line 145?

2024-10-10 21:01 UTC, swopebe commented on install/uninstall.adoc
> +Delete the `MultiClusterHub` custom resource and remove artifacts.
added this description @cameronmwall

2024-10-10 21:02 UTC, swopebe commented on install/uninstall.adoc
> +* If you have managed clusters attached, you need to detach them. *Note:* This does not include the `local-cluster`, which is your self-managed hub cluster. For more information about detaching clust
@cameronmwall this is where we removed the errors and instead wrote it to prevent errors.

2024-10-10 21:02 UTC, swopebe commented on install/uninstall.adoc
> +- The custom resource removal is the first and most basic type of uninstall that removes the custom resource of the `MultiClusterHub` instance, but leaves other required operator resources. This leve
formatting only

2024-10-10 21:03 UTC, swopebe commented on install/install_overview.adoc
> +* xref:../install/cluster_size.adoc#sizing-your-cluster[Sizing your cluster]
change in order to place install first

2024-10-10 21:03 UTC, swopebe commented on install/install_overview.adoc
> +Install {acm} through {olm}, which manages the installation, upgrade, and removal of the components that encompass the {acm-short} hub cluster. When you install the {acm-short} operator, you create t
Description changed in the overview.

2024-10-10 21:04 UTC, swopebe commented on install/install_disconnected.adoc
This can just be a step, there were some h4 headers in this file for some reason.

2024-10-11 14:18 UTC, cameronmwall commented on install/install_connected.adoc
> +Install {acm} through {olm}, which manages the installation, upgrade, and removal of the components that encompass the {acm-short} hub cluster. When you install the {acm-short} operator, you create t
I actually think we don't need to go into details on how the MCE is installed. All of that is happening under the covers and the specific mechanisms are not relevant to most of our customers

2024-10-11 14:18 UTC, cameronmwall commented on install/uninstall.adoc
> +* If you have managed clusters attached, you need to detach them. *Note:* This does not include the `local-cluster`, which is your self-managed hub cluster. For more information about detaching clust
this looks good to me

2024-10-11 14:18 UTC, cameronmwall commented on install/uninstall.adoc
> +Delete the `MultiClusterHub` custom resource and remove artifacts.
I think this is helpful

2024-10-11 14:18 UTC, cameronmwall commented on install/uninstall.adoc
> +When you use the {ocp} console to uninstall, you remove the `MultiClusterHub` resource to delete the object. Wait for the status, then delete the operator. Complete the following steps to uninstall b
I think we may want to adjust the phrasing here. I think we should emphasize deleting the MCH to remove the object and then say uninstall the operator. This might be personal preference on my part but seems more intuitive

2024-10-13 22:38 UTC, swopebe commented on install/install_connected.adoc
> +Install {acm} through {olm}, which manages the installation, upgrade, and removal of the components that encompass the {acm-short} hub cluster. When you install the {acm-short} operator, you create t
I get that, but we get questions from people using OCP and not ACM, so we are attempting to explain it for others using the doc. I would like explain it a bit better here.

2024-10-13 23:01 UTC, swopebe commented on install/uninstall.adoc
> +When you use the {ocp} console to uninstall, you remove the `MultiClusterHub` resource to delete the object. Wait for the status, then delete the operator. Complete the following steps to uninstall b
changed.

2024-10-14 13:27 UTC, oafischer commented on install/install_connected.adoc
> +Verify that a {product-title-short} hub cluster is not already installed on your {ocp-short} cluster.You cannot have more than one hub cluster.
```suggestion
Verify that a {product-title-short} hub cluster is not already installed on your {ocp-short} cluster. You cannot have more than one hub cluster. 
```
Small typo (missing space)

2024-10-14 13:48 UTC, oafischer approved these changes
Looks great, just one typo

2024-10-14 14:25 UTC, dockerymick requested changes
Thanks Brandi for your effort here. i left suggestions and questions

2024-10-14 14:25 UTC, dockerymick commented on install/cluster_size.adoc
> +Each {acm} cluster is unique and the following guidelines give sample deployment sizes for you. Recommendations are classified by size and purpose. {acm-short} applies the following dimensions for si
When i read "dimensions", I thought that I would see a table first instead of the list of definitions. These seem like data component definitions. Can you help me understand why these are mentioned as dimensions? Otherwise, the definitions look good to me.

2024-10-14 14:25 UTC, dockerymick commented on install/cluster_size.adoc
>  | {ocp-short} on Microsoft Azure
I noticed in the Creating and managing single node {ocp-short} clusters section that there was repeated information such as: 

"Availability zones isolate potential fault domains across the cluster. Typical clusters have an equal worker node capacity in three or more availability zones. High availability is not supported.

Important: For {ocp-short}, distribute the master nodes of the cluster across three availability zones."

And there is only one row for the table. 

This file seems like a concept file from my perspective, so maybe the Creating and managing single node {ocp-short}. Reminder that there is a conref for single node OpenShift ({sno})

2024-10-14 14:25 UTC, dockerymick commented on install/install_connected.adoc
> +Install {acm} through {olm}, which manages the installation, upgrade, and removal of the components that encompass the {acm-short} hub cluster. When you install the {acm-short} operator, you create t
Strong description !

2024-10-14 14:25 UTC, dockerymick commented on install/install_connected.adoc
> +**Required access:** Cluster administrator
```suggestion
*Required access:* Cluster administrator
```

2024-10-14 14:25 UTC, dockerymick commented on install/install_connected.adoc
> +**{ocp-short} Dedicated environment required access:** You need `cluster-admin` permissions. By default the `dedicated-admin` role does not have the required permissions to create namespaces in the {
```suggestion
*{ocp-short} Dedicated environment required access:* You need `cluster-admin` permissions. By default the `dedicated-admin` role does not have the required permissions to create namespaces in the {ocp-short} Dedicated environment. 
```

2024-10-14 14:25 UTC, dockerymick commented on install/install_connected.adoc
>  - By default, the hub cluster components are installed on worker nodes of your {ocp-short} cluster without any additional configuration. You can install the hub cluster on worker nodes by using the {
Should there be a space in OperatorHub? Should it be Operator Hub ?

2024-10-14 14:25 UTC, dockerymick commented on install/install_connected.adoc
> +Verify that a {product-title-short} hub cluster is not already installed on your {ocp-short} cluster.You cannot have more than one hub cluster.
Reminder that the conref changed for the product name. The title of this section should also be changed to "Confirming"
```suggestion
Verify that a {acm-short} hub cluster is not already installed on your {ocp-short} cluster. You cannot have more than one hub cluster. 
```

2024-10-14 14:25 UTC, dockerymick commented on install/install_connected.adoc
> +{acm-short} allows only one single {acm-short} hub cluster installation on each {ocp-short} cluster. Continue with the following steps if there is no {acm-short} hub cluster installed:
```suggestion
You can only have one single {acm-short} hub cluster installation on each {ocp-short} cluster. Continue with the following steps if there is no {acm-short} hub cluster installed:
```

2024-10-14 14:25 UTC, dockerymick commented on install/install_connected.adoc
> +oc -n openshift-console get route
Reminder to add the [source,bash] syntax for this command and any others that might be missing it

2024-10-14 14:25 UTC, dockerymick commented on install/install_connected.adoc
> +* <<installing-from-the-cli,Installing from the {ocp-short} CLI>>
These child links can be removed since you already list them in the TOC on lines 20-24

2024-10-14 14:25 UTC, dockerymick commented on install/install_connected.adoc
> +**Best practice:** From the _Administrator_ view in your console, install the OperatorHub web console interface that is provided with {ocp-short}.
```suggestion
*Best practice:* From the _Administrator_ view in your console, install the OperatorHub web console interface that is provided with {ocp-short}.
```

2024-10-14 14:25 UTC, dockerymick commented on install/install_connected.adoc
>  . Select *Install* to apply your changes and create the operator.
MultiClusterHub on line 108, should be monospaced because it's introduced as a resource name

2024-10-14 14:25 UTC, dockerymick commented on install/install_connected.adoc
> +. Click to `MultiClusterHub` tab to see the list of resources where your operator is listed.
This should be italicized since it is the name of tab in the console
```suggestion
. Click to _MultiClusterHub_ tab to see the list of resources where your operator is listed.
```

2024-10-14 14:25 UTC, dockerymick commented on install/install_connected.adoc
> +. Select *Create* to initialize the custom resource. It can take up to 10 minutes for the {product-title-short} hub cluster to build and deploy components.
Reminder that the conref for the product name was changed to acm and acm-short
```suggestion
. Select *Create* to initialize the custom resource. It can take up to 10 minutes for the {acm-short} hub cluster to build and deploy components.
```

2024-10-14 14:25 UTC, dockerymick commented on install/install_connected.adoc
> +After the {product-title-short} hub cluster is created, the `MultiClusterHub` resource status displays _Running_ from the _MultiClusterHub_ tab of the {product-title-short} operator details.
```suggestion
After the {acm-short} hub cluster is created, the `MultiClusterHub` resource status displays _Running_ from the _MultiClusterHub_ tab of the {acm-short} operator details. 
```

2024-10-14 14:25 UTC, dockerymick commented on install/install_connected.adoc
> +To gain access to the console, see the link:../console/console_access.adoc#accessing-your-console[Accessing your console] topic.
I can understand why this link is added, but I recommend moving it to the Additional resources section. Let me know your thoughts

2024-10-14 14:25 UTC, dockerymick commented on install/install_connected.adoc
> +Install the operator and the objects.
```suggestion
Install the operator and the objects. Complete the following steps:
```

2024-10-14 14:25 UTC, dockerymick commented on install/install_connected.adoc
> +If you receive the following error, the resource process is still running. Run the `oc apply` command again in a few minutes when the resources are created:
Reminder to add the [source,bash] syntax for the terminal message

2024-10-14 14:25 UTC, dockerymick commented on install/install_connected.adoc
> +- A namespace called `local-cluster` is reserved for the {product-title-short} hub cluster when it is self-managed. This is the only `local-cluster` namespace that can exist in the product.
```suggestion
- A namespace called `local-cluster` is reserved for the {acm-short} hub cluster when it is self-managed. This is the only `local-cluster` namespace that can exist in the product. 
```

2024-10-14 14:25 UTC, dockerymick commented on install/install_connected.adoc
> +
I understand that this section was not apart of your changes, but I recommend that Add infrastructure nodes to the {ocp-short} cluster be changed to Adding infrastructure nodes to the {ocp-short} cluster

2024-10-14 14:25 UTC, dockerymick commented on install/install_connected.adoc
> +
I also see that there is a link to Troubleshooting in the Installing from the {ocp-short} CLI section. If we want to keep it, let's move it to the Additional resources section

2024-10-14 14:25 UTC, dockerymick commented on install/install_disconnected.adoc
> +**Required access:** Cluster administrator
```suggestion
*Required access:* Cluster administrator
```

2024-10-14 14:25 UTC, dockerymick commented on install/install_disconnected.adoc
>  == Confirm your {ocp-short} installation
```suggestion
== Confirming your {ocp-short} installation
```

2024-10-14 14:25 UTC, dockerymick commented on install/install_disconnected.adoc
> +While you are connected, verify that a {product-title-short} hub cluster is not already installed on your {ocp-short} cluster.
```suggestion
While you are connected, verify that a {acm-short} hub cluster is not already installed on your {ocp-short} cluster.
```

2024-10-14 14:25 UTC, dockerymick commented on install/install_disconnected.adoc
> +You cannot have more than one hub cluster. {acm-short} allows only one single {acm-short} hub cluster installation on each {ocp-short} cluster.
```suggestion
You can only have one single {acm-short} hub cluster installation on each {ocp-short} cluster. 
```

2024-10-14 14:25 UTC, dockerymick commented on install/install_disconnected.adoc
>  == Confirm availability of a local image registry
```suggestion
== Confirming the availability of a local image registry
```

2024-10-14 14:25 UTC, dockerymick commented on install/install_disconnected.adoc
>  == Configure {olm}
```suggestion
== Configuring {olm}
```

2024-10-14 14:25 UTC, dockerymick commented on install/install_disconnected.adoc
> +. When you complete the previous procedure, note the following requirements that are also specific to {acm}:
This is appearing as a step, is that intentional?

2024-10-14 14:25 UTC, dockerymick commented on install/install_disconnected.adoc
> +. As described in the procedures in the {ocp} documentation, you need to add a `CatalogSource` resource to your disconnected cluster. *Important:* Take note of the value of the `metadata.name` field,
```suggestion
. As described in the procedures in the {ocp} documentation, you need to add a `CatalogSource` resource to your disconnected cluster. *Important:* Take note of the value of the `metadata.name` field, which you need to use later.
```

2024-10-14 14:25 UTC, dockerymick commented on install/install_disconnected.adoc
> ++
Is line 137 also a step that the user needs to complete? Or should it be a substep?

2024-10-14 14:25 UTC, dockerymick commented on install/install_disconnected.adoc
>  [#verify-required-package]
Change the title from Verify required packages are available to Verifying required packages are available

2024-10-14 14:25 UTC, dockerymick commented on install/install_disconnected.adoc
> +If you create the resource by using the OperatorHub console, switch to the _YAML view_ and insert the annotation as previously displayed. *Important:* There is no field in the OperatorHub console for
```suggestion
If you create the resource by using the OperatorHub console, switch to the _YAML view_ and insert the annotation as previously displayed. *Important:* There is no field in the OperatorHub console for the annotation in the _Field view_ panel to create the `MulticlusterHub` resource.
```

2024-10-14 14:25 UTC, dockerymick commented on install/install_overview.adoc
> +Install {acm} through {olm}, which manages the installation, upgrade, and removal of the components that encompass the {acm-short} hub cluster. When you install the {acm-short} operator, you create t
This description is also mentioned in the install_connected.adoc file

2024-10-14 14:25 UTC, dockerymick commented on install/install_overview.adoc
> +* xref:../install/cluster_size.adoc#sizing-your-cluster[Sizing your cluster]
Reminder to ensure the titles match for each link reference

2024-10-14 14:25 UTC, dockerymick commented on install/uninstall.adoc
> +* If you use Discovery, you need to disable the function. From the console, go to the `Discovered Clusters` table and click *Disable cluster discovery*. Confirm that you want to remove the service. Y
```suggestion
* If you use Discovery, you need to disable the function. From the console, go to the _Discovered Clusters_ table and click *Disable cluster discovery*. Confirm that you want to remove the service. You can also use the terminal to disable Discovery with the following command:
```

2024-10-14 14:25 UTC, dockerymick commented on install/uninstall.adoc
> +* If you use Agent Service Configuration, disable and remove the `AgentServiceConfig` resource.Complete the following steps:
```suggestion
* If you use Agent Service Configuration, disable and remove the `AgentServiceConfig` resource. Complete the following steps:
```

2024-10-14 14:25 UTC, dockerymick commented on install/uninstall.adoc
> +== Removing _multiclusterhub_ resources by using commands
```suggestion
== Removing _MultiClusterHub_ resources by using commands
```

2024-10-14 14:25 UTC, dockerymick commented on install/uninstall.adoc
> +Delete the `MultiClusterHub` custom resource and remove artifacts.
```suggestion
Delete the `MultiClusterHub` custom resource and remove artifacts. Complete the following steps:
```

2024-10-14 14:25 UTC, dockerymick commented on install/uninstall.adoc
>  .. Run the script to remove any possible artifacts that remain from the previous installation. If there are no remaining artifacts, a message is returned that no resources were found.
I recall we didn't want to have scripts in the doc, but we can revisit this in a refresh

2024-10-14 14:25 UTC, dockerymick commented on install/uninstall.adoc
> +Next you can uninstall the`MultiClusterHub` operator. *Note:* If you plan to reinstall the same {product-title-short} version, you do not need to uninstall the operator.
Should this be listed as a step instead of saying "Next"?
```suggestion
. Uninstall the`MultiClusterHub` operator. *Note:* If you plan to reinstall the same {acm-short} version, you do not need to uninstall the operator.
```

2024-10-14 14:33 UTC, swopebe commented on install/cluster_size.adoc
> +Each {acm} cluster is unique and the following guidelines give sample deployment sizes for you. Recommendations are classified by size and purpose. {acm-short} applies the following dimensions for si
Since this work is only for formatting @dockerymick, I would have to revisit that another time. I only brought the sentence up and placed it in the description, but dimensions are for recommended sizing, in general. The topic has tables with those recommendations.

2024-10-14 14:35 UTC, swopebe commented on install/cluster_size.adoc
>  | {ocp-short} on Microsoft Azure
OK, this file cannot be rewritten or revisited for content in this PR, this is only to fix the link that was broken via the linter. If you want to open an issue to revisit that as tech debt, I support that fully.

2024-10-14 14:38 UTC, swopebe commented on install/install_connected.adoc
> +* <<installing-from-the-cli,Installing from the {ocp-short} CLI>>
These were already there, the only change I had was to remove the extra line that is obvious.

2024-10-14 14:41 UTC, swopebe commented on install/install_connected.adoc
>  - By default, the hub cluster components are installed on worker nodes of your {ocp-short} cluster without any additional configuration. You can install the hub cluster on worker nodes by using the {
I will have to look. I didn't write it, so I didn't think to research that.

2024-10-14 14:41 UTC, swopebe commented on install/install_connected.adoc
> +{acm-short} allows only one single {acm-short} hub cluster installation on each {ocp-short} cluster. Continue with the following steps if there is no {acm-short} hub cluster installed:
This one is OK either way, using **have** too much is also frowned upon. My only change here was taking out the redundant line before it. This file had too much content.

2024-10-14 14:42 UTC, swopebe commented on install/install_connected.adoc
>  - By default, the hub cluster components are installed on worker nodes of your {ocp-short} cluster without any additional configuration. You can install the hub cluster on worker nodes by using the {
I will have to look. I didn't write it, so I didn't think to research that.

2024-10-14 14:44 UTC, swopebe commented on install/install_connected.adoc
> +* <<installing-from-the-cli,Installing from the {ocp-short} CLI>>
Given the length of this file, I don't mind it and I noticed that Alexandra does this, as well as other team. I think this can stay because it can help orient the user in a topic that has a lot going on.

2024-10-14 14:49 UTC, swopebe commented on install/install_connected.adoc
> +- By default, the OperatorHub console installation process creates a namespace that is titled `open-cluster-management`. *Best practice:* Continue to use the `open-cluster-management` namespace if it
The important thing here is that they keep it `open-cluster-management` and I think that is not as clear now. The second way makes it seem to me that it is a _general_ name, but it is a specific name. (would use "an" here)

hmmm, I think we need to word "titled" here for that clarity??

2024-10-14 14:51 UTC, swopebe commented on install/install_connected.adoc
> +oc -n openshift-console get route
@dockerymick much of the file is missing all of that--across the book. I didn't clean up all those instances due to time. I can change this one but it is not the only one. I only made the command correct.

2024-10-14 14:56 UTC, swopebe commented on install/install_connected.adoc
>  . Select *Install* to apply your changes and create the operator.
@dockerymick since it is UI Control, and already bolded, I am not sure we would do that here. (?) When we bold something in the UI, it is to make it look _exactly_ like the UI, at least as much as possible, so the button itself I don't think has it monospaced. Not sure I have even asked this question to myself. 

In the UI, I think (would have to confirm another time) that it looks just like this: **MultiClusterHub**

2024-10-14 14:56 UTC, swopebe commented on install/install_connected.adoc
>  . Select *Install* to apply your changes and create the operator.
@dockerymick since it is UI Control, and already bolded, I am not sure we would do that here. (?) When we bold something in the UI, it is to make it look _exactly_ like the UI, at least as much as possible, so the button itself I don't think has it monospaced. Not sure I have even asked this question to myself. 

In the UI, I think (would have to confirm another time) that it looks just like this: **MultiClusterHub** and the other way we are saying it would look like _**MultiClusterHub**_. Good observation; not sure.

2024-10-14 15:05 UTC, swopebe commented on install/install_connected.adoc
> +To gain access to the console, see the link:../console/console_access.adoc#accessing-your-console[Accessing your console] topic.
I didn't add the link, only separated it out...it could be a follow on step even, because at this point the user goes to the UI. I will add it.

2024-10-14 17:17 UTC, dockerymick commented on install/install_connected.adoc
> +* <<installing-from-the-cli,Installing from the {ocp-short} CLI>>
Ok, I think this is something worth bringing up in a future doc arch call

2024-10-14 17:19 UTC, dockerymick commented on install/install_connected.adoc
> +. Click to _MultiClusterHub_ tab to see the list of resources where your operator is listed.
```suggestion
. Click the _MultiClusterHub_ tab to see the list of resources where your operator is listed.
```

2024-10-14 17:40 UTC, joeg-pro commented on install/install_connected.adoc
> +Install {acm} through {olm}, which manages the installation, upgrade, and removal of the components that encompass the {acm-short} hub cluster. When you install the {acm-short} operator, you create t
@swopebe I think this is where you were looking for input while Cameron is OOTO.  I understand your point that customers are asking about the MCE operator/MCE resource tht automatically appear when they install ACM, so it is fine to have info here that says that is going to happen.     Maybe it would be helpful to add a little "why?" rationale here, namely stating that ACM depends on and uses MCE.   So perhaps something like this (please edit/fix the terminology/placeholders)...

Because Advanced Cluster Management for Kubernetes  depends on and uses multicluster engine, after you create the `MultiClusterHub` resource, the {acm-short} operator automatically installs the {mce} operator and creates the `MultiClusterEngine` resource. 

You must have a supported version of {ocp-short} to install {acm-short}.

2024-10-14 18:02 UTC, swopebe commented on install/install_connected.adoc
>  - By default, the hub cluster components are installed on worker nodes of your {ocp-short} cluster without any additional configuration. You can install the hub cluster on worker nodes by using the {
We are correct in the naming: https://docs.redhat.com/en/documentation/openshift_container_platform/4.14/html/operators/understanding-operators

2024-10-14 18:05 UTC, swopebe commented on install/install_overview.adoc
> +* xref:../install/cluster_size.adoc#sizing-your-cluster[Sizing your cluster]
Not sure what this one means. For this, I only moved the link--I didn't change any content. Much of this was formatting only.

2024-10-14 18:08 UTC, swopebe commented on install/uninstall.adoc
> +Next you can uninstall the`MultiClusterHub` operator. *Note:* If you plan to reinstall the same {product-title-short} version, you do not need to uninstall the operator.
This content changes if I can ever get this PR merged because of the rewrites for uninstall. I will leave for now.

2024-10-14 18:32 UTC, swopebe commented on install/install_connected.adoc
> +Install {acm} through {olm}, which manages the installation, upgrade, and removal of the components that encompass the {acm-short} hub cluster. When you install the {acm-short} operator, you create t
updated to match the overview

2024-10-14 18:40 UTC, swopebe commented on install/install_overview.adoc
> +Install {acm} through {olm}, which manages the installation, upgrade, and removal of the components that encompass the {acm-short} hub cluster. Because {acm-short} depends on and uses the {mce-short}
New description from Joe's feedback.

2024-10-14 18:41 UTC, joeg-pro commented on install/install_overview.adoc
> +Install {acm} through {olm}, which manages the installation, upgrade, and removal of the components that encompass the {acm-short} hub cluster. Because {acm-short} depends on and uses the {mce-short}
Looks great.

2024-10-14 18:43 UTC, swopebe commented on install/install_disconnected.adoc
>  [#verify-required-package]
I didn't plan on changing the headers for legacy content unless I had to rewrite them but I don't think it is wrong as it is. These headers just need to be clearly linked to the title. I sometimes will use the shorter verb case in headers.

2024-10-14 18:51 UTC, dockerymick commented on install/install_overview.adoc
> +* xref:../install/cluster_size.adoc#sizing-your-cluster[Sizing your cluster]
This was in case you decided to update the title, Install on disconnected networks to Installing on disconnected networks

2024-10-14 18:56 UTC, swopebe commented on install/install_connected.adoc
> +
Ok; I brought this up in the call one time recently as an example of what **not** to do. 

This is the work that this PR is holding up--rewriting this. 

We definitely don't even want to get in the habit of linking to troubleshooting at all, even in additional resources. Only in cases where we don't have a choice, but in this case, we got a few customer bugs, one requesting more troubleshooting, other requesting more info in the install doc. 

I am answering that by taking out the script and the link to t-shooting in an issue: https://issues.redhat.com/browse/ACM-14343

But I cannot start on it while this PR is still out. The link is going away, for sure. It should not have been placed here, and in another topic, the script is placed in the steps....so it is a but of a mess that I didn't write but inherited.

I will catch the infra node work in the next PR. Thanks for catching that.

2024-10-14 19:00 UTC, swopebe commented on install/install_overview.adoc
> +* xref:../install/cluster_size.adoc#sizing-your-cluster[Sizing your cluster]
oh ok, I will look at that in the next round. I tend to keep the file names without ing you are right about titles--should be gerunds.

2024-10-14 19:00 UTC, swopebe commented on install/install_overview.adoc
> +Install {acm} through {olm}, which manages the installation, upgrade, and removal of the components that encompass the {acm-short} hub cluster. When you install the {acm-short} operator, you create t
added and changed.

2024-10-14 19:02 UTC, swopebe commented on install/uninstall.adoc
>  .. Run the script to remove any possible artifacts that remain from the previous installation. If there are no remaining artifacts, a message is returned that no resources were found.
Yes, there is a whole other issue for this and the main reason for starting to clean up this file. You are right, though I think we have to have it in this case, it just should be part of another process and not embedded here. Also, it is in a troubleshooting file. 

This is a result of just patching up the doc as told, without understanding or revisiting the big picture. So when I get all this in, the next issue takes care of this. You are right.

2024-10-14 19:11 UTC, swopebe commented on install/install_disconnected.adoc
> ++
This is a weird one. I didn't rewrite much of this file--we didn't test it. Just tried to fix some formatting. 

I will revisit but I think Find and Add could be the same step. (Find was a deep header)

If I cannot get the answer, I will change it back. This whole file needs a lot of work.

2024-10-14 19:29 UTC, dockerymick commented on install/install_connected.adoc
> +Verify that a {product-title-short} hub cluster is not already installed on your {ocp-short} cluster. You cannot have more than one hub cluster.
```suggestion
Verify that a {acm-short} hub cluster is not already installed on your {ocp-short} cluster. You cannot have more than one hub cluster. 
```

2024-10-14 19:30 UTC, dockerymick approved these changes
I made a commit where I saw {product-title-short}. Thanks for receiving my suggestions and clarifying questions that I had. This looks good to me

2024-10-14 19:40 UTC, merged