added header for global hub importing hub cluster tech preview
open-cluster-management/rhacm-docs pull request #6971
Opened 2024-09-24 19:26 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-13640

2024-09-25 00:02 UTC, ldpliu approved these changes

2024-09-25 11:40 UTC, swopebe commented on global_hub/global_hub_import_hub_hosted.adoc
> +- Changes these namespaces to `open-cluster-management-global-hub-agent-addon`.
These italics are a result of the comments and will render when we delete those.

2024-09-25 11:46 UTC, swopebe commented on global_hub/global_hub_import_hub_hosted.adoc
> +- Changes these namespaces to `open-cluster-management-global-hub-agent-addon`.
For a task with values that the user needs to change, it's important to show and tell them where to make those changes. This is also in the overall feedback for contentX where people ask for examples and samples. Throughout the doc you can see we guide them similar to this example:

https://github.com/stolostron/rhacm-docs/blob/2.12_stage/clusters/cluster_lifecycle/ansible_config_hosted_cluster.adoc

2024-09-25 12:12 UTC, swopebe commented on global_hub/global_hub_import_hub_hosted.adoc
Below:

extra spaces, subject/verb agreement edits made and committed

2024-09-25 12:13 UTC, swopebe commented on global_hub/global_hub_import_hub_hosted.adoc
> +//Should this be earlier in the file for better UX? Maybe as a prereq?
comment added for consideration

2024-09-25 14:45 UTC, jc-berger commented on global_hub/global_hub_import_hub_hosted.adoc
> +- Changes these namespaces to `open-cluster-management-global-hub-agent-addon`.
@ldpliu looking at Brandi's comment. 

Can we "show and tell users where to make those changes" ? 

Or do we want to say something more like: 

With this annotation, you can use {global-hub} to do any of the following actions:

< list of actions > 

```suggestion
With this annotation, you can use {global-hub} to do any of the following actions:
< list of actions > 
```

It seemed to me that it was more of a list of capabilities the users have.

2024-09-26 06:54 UTC, ldpliu commented on global_hub/global_hub_import_hub_hosted.adoc
> +Enabling a `local-cluster` on your managed hub clusters can make it easier and faster for you to manage your hub clusters. To enable a `local-cluster`, import a managed hub cluster in the hosted mode
I think we do not need to explain "enabling `local-cluster`" it's default ACM behavior. 
And in this line, we wan just want to let user known that: if the managedhub cluster enabled the 'local-cluster', it must be imported as hosted mode.

2024-09-26 06:56 UTC, ldpliu commented on global_hub/global_hub_import_hub_hosted.adoc
> +- Make sure this `kubeconfig` or API token is always usable. If it expires, regenerate the `auto-import-secret` in the managed hub cluster namespace, `oc create secret generic auto-import-secret --fr
I still suggest put this line in note.
This is just a behavior of importing cluster of ACM, in our doc, we want to high light this 'kubeconfig' should be always usable, and if it expired, user need to update it.

2024-09-26 07:02 UTC, ldpliu commented on global_hub/global_hub_import_hub_hosted.adoc
> +. Go to your managed hub cluster with `local-cluster` enabled.
It's not necessary, remove this line

2024-09-26 07:06 UTC, ldpliu commented on global_hub/global_hub_import_hub_hosted.adoc
> +- Changes these namespaces to `open-cluster-management-global-hub-agent-addon`.
With this annotation, globalhub controller will do these actions when user import a managedhub cluster.
User should do nothing more.
We want to let user known what happens when importing a managedhub int his mode.

2024-09-27 04:29 UTC, ldpliu approved these changes

2024-09-27 15:25 UTC, dockerymick requested changes
Couple more comments and questions

2024-09-27 15:25 UTC, dockerymick commented on global_hub/global_hub_import_hub_hosted.adoc
> +- Changes the managed hub clusters `addons` that are related to the new namespace, including: `work-manager`,`cluster-proxy`, and `managed-serviceaccount`.
```suggestion
- Changes the following managed hub clusters `addons` that are related to the new namespace: `work-manager`,`cluster-proxy`, and `managed-serviceaccount`. 
```

2024-09-27 15:25 UTC, dockerymick commented on global_hub/global_hub_import_hub_hosted.adoc
> +- Make sure this `kubeconfig` or API token is always usable. If it expires, regenerate the `auto-import-secret` in the managed hub cluster namespace, `oc create secret generic auto-import-secret --fr
We need to introduce the command and maybe consider moving this to the Prereq section? 
```suggestion
- Make sure this `kubeconfig` or API token is always usable. If it expires, regenerate the `auto-import-secret` in the managed hub cluster namespace with the following command: `oc create secret generic auto-import-secret --from-file=kubeconfig=./managedClusterKubeconfig -n <Managedhub Namespace>`. 
```

2024-09-27 15:25 UTC, dockerymick commented on global_hub/global_hub_import_hub_hosted.adoc
> + To enable `local-cluster` on your managed hub cluster, you must import it in the hosted mode.
```suggestion
To enable `local-cluster` on your managed hub cluster, you must import it in the hosted mode.  
```

2024-09-27 15:25 UTC, dockerymick commented on global_hub/global_hub_import_hub_hosted.adoc
>  == Prerequisites
Since there is only one prereq
```suggestion
== Prerequisite
```

2024-09-27 15:25 UTC, dockerymick commented on global_hub/global_hub_import_hub_hosted.adoc
> +- Changes these namespaces to `open-cluster-management-global-hub-agent-addon`.
Is it changing the name of the namespaces?

2024-09-27 15:25 UTC, dockerymick commented on global_hub/global_hub_import_hub_hosted.adoc
>  - In the hosted mode, you only get support for import managed hub clusters that use `kubeconfig` or API tokens. {acm} uses this `kubeconfig` or API token to generate the `auto-import-secret`, which c
I would move this bullet point to the short description on line 14

2024-09-27 18:18 UTC, dockerymick commented on global_hub/global_hub_import_hub_hosted.adoc
>  - Enable `local-cluster` in the {global-hub} cluster.
```suggestion
Enable `local-cluster` in the {global-hub} cluster.
```

2024-09-27 18:19 UTC, dockerymick commented on global_hub/global_hub_import_hub_hosted.adoc
> +- Make sure this `kubeconfig` or API token is always usable. If it expires, regenerate the `auto-import-secret` in the managed hub cluster namespace with the following command: `oc create secret gene
@jc-berger thanks for explaining through Slack why this wasn't a prereq. What are your thoughts about moving this Note before you instruct users to complete the steps? It just seems odd ending the file with a Note.

2024-09-27 18:20 UTC, dockerymick commented
Reminder to add a what's new entry for this

2024-09-27 20:25 UTC, dockerymick approved these changes
Thanks Jake! This looks good to me!

2024-09-27 20:28 UTC, merged