https://issues.redhat.com/browse/ACM-14268
open-cluster-management/rhacm-docs pull request #6974
Opened 2024-09-25 16:21 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-14268 

See Gdoc where we collaborated: https://docs.google.com/document/d/1hmayCAmkt2Zu1u8OIrjsFwHh3aJTE8vlWf63tWCSxZA/edit

2024-09-25 18:07 UTC, birsanv requested changes

2024-09-25 18:07 UTC, birsanv commented on business_continuity/backup_restore/backup_existing_hub.adoc
> +* If an earlier backup created the `ManagedCluster` resources, then they have the `velero.io/backup-name: backupName` label annotation set. Therefore, if the user runs a restore operation and uses th
This is incorrect
Change

Therefore, if the user runs a restore operation and uses the `cleanupBeforeRestore=CleanupRestored` option, then these `ManagedCluster` resources are not part of the restored backup. The clusters are detached and the data is cleaned up on those managed clusters.

With:

Therefore, if the user runs a restore operation and uses the `cleanupBeforeRestore=CleanupRestored` option, then the clusters are detached and the data is cleaned up on those  on those managed clusters, if these managed clusters resources are not part of the restored backup.

2024-09-25 18:07 UTC, birsanv commented on business_continuity/backup_restore/backup_existing_hub.adoc
> +* When the  `velero.io/backup-name: backupName` label annotation exists, the managed clusters were created by an earlier backup and are no longer part of the restored backup. As a result, the managed
Remove line 15, it says the same thing as line 14

2024-09-25 18:07 UTC, birsanv commented on business_continuity/backup_restore/backup_existing_hub.adoc
> +* If the `ManagedCluster` resource does not have the `velero.io/backup-name: backupName` label annotation, these managed clusters continue to be managed by this hub, even though these clusters were n
Change line 15 with : 

If the `ManagedCluster` resource does not have the `velero.io/backup-name: backupName` label annotation, user runs a restore operation and uses the `cleanupBeforeRestore=CleanupRestored` option, these managed cluster resources are not cleaned up since they were not created by a previous backup. Therefore, these managed clusters continue to be managed by this hub, even though these clusters were not managed by the backup hub; this hub does not match the content of the backup hub.

2024-09-25 18:07 UTC, birsanv commented on business_continuity/backup_restore/backup_existing_hub.adoc
> +If your restore operation uses a hub with earlier created user data, then the restore operation results in a hub that does not have the exact content as the primary hub. The user data includes the fo
This 
The user data includes the following properties

Should be
The user data includes the following **resources**

2024-09-25 18:07 UTC, birsanv commented on business_continuity/backup_restore/backup_existing_hub.adoc
> +* Update the `DataProtectionApplication` resource and set the storage location to a new, temporary location. You do not want to have this backup in the same location with the backup hub, so make sure
Change
Update the `DataProtectionApplication` resource and set the storage location to a new, temporary location. You do not want to have this backup in the same location with the backup hub, so make sure you set the storage location to a different location.

With ( I was trying to make this more clear: 1. you run on the restore hub, 2. we are talking about the backup generated by the Tagging resources section ):

**On the restore hub**, update the `DataProtectionApplication` resource and set the storage location to a new, temporary location. You do not want to create the backup **used to tag the restore hub resources** in the same **storage** location with the backup hub, **so before you run the next step** make sure you set the storage location to a different location than the backup hub.

2024-09-25 18:07 UTC, birsanv commented on business_continuity/backup_restore/backup_existing_hub.adoc
> +To tag resources with the `velero.io/backup-name: backupName` label, complete the following steps:
Change  : 

 To tag resources with the `velero.io/backup-name: backupName` label, complete the following steps:

With 

To tag **user created resources on the restore hub** with the `velero.io/backup-name: backupName` label, **on the restore hub** complete the following steps:

2024-09-25 18:07 UTC, birsanv commented on business_continuity/backup_restore/backup_existing_hub.adoc
> +. Pause the `BackupSchedule` schedule and stop generating backups by setting the property `paused=true` on the `schedule-acm-msa BackupSchedule`.
Add this before Line 52 (ask the user to verify they got a hub backup ) : 


. Verify that the BackupSchedule has created the hub Backup resources and their status is Completed.

2024-09-25 18:07 UTC, birsanv commented on business_continuity/backup_restore/backup_existing_hub.adoc
> +You can now use the hub as a restore cluster and update the `DataProtectionApplication` storage location to point to the storage location of the backup hub. Any restore operation that you set the `cl
Please change line 81 with

You can now use the hub as a restore cluster. Update the `DataProtectionApplication` storage location to point to the storage location of the backup hub **so you can run a restore operation using the hub backup resources**.  All the restore hub resources are tagged now with the `velero.io/backup-name` label, so they show as being generated by an earlier restore. Therefore, any restore operation **that you run on this hub cluster** using the `cleanupBeforeRestore` option set to `CleanupRestored` cleans up the data that is not part of the restored backup.

2024-09-25 18:07 UTC, birsanv commented on business_continuity/backup_restore/backup_existing_hub.adoc
> +=== Understanding the resources
I am not sure Understanding the resources is a proper title, what resources are we referring to ?..

Maybe : Understanding the procedure 
( assuming we are referring to this tagging of resources procedure )

2024-09-25 18:07 UTC, birsanv commented on business_continuity/backup_restore/backup_existing_hub.adoc
> +*Important:*
- Remove lines 85 and 86
- Move line 91 to be first on the **Important** section

2024-09-25 18:07 UTC, birsanv commented on business_continuity/backup_restore/backup_existing_hub.adoc
> +* Having this constraint, you could use an existing hub for a restore operation in the following situations:
Change
Having this constraint, you could use an existing hub for a restore operation in the following situations:

With
Having this constraint, you could use an existing **hub as a restore hub** in the following situations:

2024-10-01 14:15 UTC, birsanv commented on business_continuity/backup_restore/backup_existing_hub.adoc
> +* If an earlier backup created the `ManagedCluster` resources, then they have the `velero.io/backup-name: backupName` label annotation set. Therefore, if the user runs a restore operation and uses th
typo : iff 
content is good !

2024-10-01 14:23 UTC, birsanv commented on business_continuity/backup_restore/backup_existing_hub.adoc
> +* If the `ManagedCluster` resource does not have the `velero.io/backup-name: backupName` label annotation, the user must run a restore operation and use the `cleanupBeforeRestore=CleanupRestored` opt
Line 15 is still incorrect .. we changed the meaning .. what I meant to say: is the resource has the label **and** the user runs a restore operation using the CleanupRestored option, **then** the managed clusters are not cleaned up, as they should, because they don't have that label.

Please change line 15 with 

If the `ManagedCluster` resource does not have the `velero.io/backup-name: backupName` label annotation **and** the user runs a restore operation **with** the `cleanupBeforeRestore` option set to `CleanupRestored`, **then** these managed cluster resources are not cleaned up since they were not created by an earlier backup. Therefore, these managed clusters continue to be managed by this hub, even though these clusters were not managed by the backup hub, and this hub does not match the content of the backup hub.

2024-10-01 14:25 UTC, birsanv commented on business_continuity/backup_restore/backup_existing_hub.adoc
> +If you intend to use an existing hub for a restore hub configuration and expect that the hub has the same content as the backup after the restore is completed, tag any resource that would be part of
small change here : 
This : and expect that the hub has the same content as the backup 
Should be : and expect that the hub has the same content as the backup **hub**

2024-10-01 14:27 UTC, birsanv requested changes
almost done , 2 more updates

2024-10-01 14:54 UTC, birsanv approved these changes
lgtm

2024-10-02 15:59 UTC, dockerymick requested changes

2024-10-02 15:59 UTC, dockerymick commented on business_continuity/backup_restore/backup_existing_hub.adoc
> += Using an existing hub as a restore hub
Reminder to add this to the business_continuity/main.adoc file

2024-10-02 15:59 UTC, dockerymick commented on business_continuity/backup_restore/backup_existing_hub.adoc
> += Using an existing hub as a restore hub
```suggestion
= Using an existing hub cluster as a restore hub cluster
```

2024-10-02 15:59 UTC, dockerymick commented on business_continuity/backup_restore/backup_existing_hub.adoc
> +If you use a restore hub as a cluster with resources that a user created before the restore operation, you must understand the following constraints:
Let's add a short description before this. Something like, "When you use a restore hub cluster with resources that you created before running the restore operation, you can tag user-created resources on the restore hub cluster with the `velero.io/backup-name: backupName` label."

then go into the constraints.

2024-10-02 15:59 UTC, dockerymick commented on business_continuity/backup_restore/backup_existing_hub.adoc
> +* The restore hub can have more resources than the backup hub.
```suggestion
* The restore hub cluster can have more resources than the backup hub cluster.
```

2024-10-02 15:59 UTC, dockerymick commented on business_continuity/backup_restore/backup_existing_hub.adoc
> +* If the `ManagedCluster` resource does not have the `velero.io/backup-name: backupName` label annotation, and the user runs a restore operation with the `cleanupBeforeRestore` option set to `Cleanup
Based on the contents of this section, it seems like you are describing how the resources are cleaned or not cleaned with the user has the parameter set. It seems like when you say detached, you are saying that the contents of the backup hub cluster and restore hub cluster do not match. 

Is it more accurate to rename the section title to "Outcomes for existing managed clusters during the restore process"?

2024-10-02 15:59 UTC, dockerymick commented on business_continuity/backup_restore/backup_existing_hub.adoc
> +* If an earlier backup created the `ManagedCluster` resources, then they have the `velero.io/backup-name: backupName` label annotation set. Therefore, if the user runs a restore operation and uses th
```suggestion
* If an earlier backup created the `ManagedCluster` resources, then the `velero.io/backup-name: backupName` label annotation is set. Therefore, if you run a restore operation and use the `cleanupBeforeRestore=CleanupRestored` option, the clusters are detached and the data is cleaned up on the managed clusters. This only occurs if the backup managed clusters resources are not part of the restored backup.
```

2024-10-02 15:59 UTC, dockerymick commented on business_continuity/backup_restore/backup_existing_hub.adoc
> +* If the `ManagedCluster` resource does not have the `velero.io/backup-name: backupName` label annotation, and the user runs a restore operation with the `cleanupBeforeRestore` option set to `Cleanup
The following statement is long:

Therefore, these managed clusters continue to be managed by this hub, even though these clusters were not managed by the backup hub, and this hub does not match the content of the backup hub.

What is "this hub"? Is it the restore hub cluster? 

```suggestion
* If the `ManagedCluster` resource does not have the `velero.io/backup-name: backupName` label annotation, and you run a restore operation with the `cleanupBeforeRestore` option set to `CleanupRestored`, then the managed cluster resources are not cleaned up since they were not created by an earlier backup. Therefore, the managed clusters continue to be managed by this hub cluster, even though the clusters were not managed by the backup hub cluster, and this hub does not match the content of the backup hub cluster.
```

2024-10-02 15:59 UTC, dockerymick commented on business_continuity/backup_restore/backup_existing_hub.adoc
> +== Restore hub can have more resources than the backup hub
Similar to my earlier comment, can it be renamed?

2024-10-02 15:59 UTC, dockerymick commented on business_continuity/backup_restore/backup_existing_hub.adoc
> +* On the restore hub, update the `DataProtectionApplication` resource and set the storage location to a new, temporary location. You do not want to create the backup used to tag the restore hub resou
The statement "Before you tag the resources, make sure you set the storage location to a different location than the backup hub." seems like another prereq

2024-10-02 15:59 UTC, dockerymick commented on business_continuity/backup_restore/backup_existing_hub.adoc
> +After tagging the resources, you can use the hub as a restore cluster. Update the `DataProtectionApplication` storage location to point to the storage location of the backup hub so you can run a rest
It seems like this should be moved earlier in the Tagging resources section, rather than be a new subsection

2024-10-02 17:54 UTC, jc-berger commented on business_continuity/backup_restore/backup_existing_hub.adoc
> +* If the `ManagedCluster` resource does not have the `velero.io/backup-name: backupName` label annotation, and the user runs a restore operation with the `cleanupBeforeRestore` option set to `Cleanup
Thanks! I made the change. I changed the title to "Understanding.." to be consistent with how most of our docs start with a gerund. 

@birsanv please let me know if you agree with this title change.

2024-10-02 17:55 UTC, jc-berger commented on business_continuity/backup_restore/backup_existing_hub.adoc
> +== Restore hub can have more resources than the backup hub
I can make the change if you want. These are more possible outcomes, hence saying, "can have more..." 

If you really don't like it, I can think of something else :)

2024-10-02 17:57 UTC, jc-berger commented on business_continuity/backup_restore/backup_existing_hub.adoc
> +After tagging the resources, you can use the hub as a restore cluster. Update the `DataProtectionApplication` storage location to point to the storage location of the backup hub so you can run a rest
Valentina and I did talk about putting this earlier, for instance, part of the intro for === Tagging resources

However, this content is only applicable _after_ users tag the resource. Given the Doc's team's recent discussions of using more headings to organize content, I made it its own section. 

However, if you think it's best, I can remove the heading, === Understanding the tagged resources 

That way users see this content right after competing the task/procedure. Thoughts?

2024-10-02 19:44 UTC, thuyn-581 approved these changes
lgtm

2024-10-04 21:44 UTC, dockerymick requested changes
Thanks for your patience, this one is a little tricky to review

2024-10-04 21:44 UTC, dockerymick commented on business_continuity/backup_restore/backup_existing_clusters.adoc
> +When you use a restore hub cluster with resources that a user created before running the restore operation, you can tag user-created resources on the restore hub cluster with the `velero.io/backup-na
Suggesting to organize this more cohesively based on the Tone guidance: https://www.ibm.com/docs/en/ibm-style?topic=medium-tone 

From my perspective, the intention of this file is to help users know what to expect if they decide to restore existing managed clusters. The statement, "When you use a restore hub cluster with resources that a user created before running the restore operation, you can tag user-created resources on the restore hub cluster with the `velero.io/backup-name: backupName` label." seems out of place. In my later suggestions, you can see i recommend to add it in the Tagging resources file.

```suggestion
Before you run the restore operation for existing hub clusters, understand the following constraints: 
```

2024-10-04 21:44 UTC, dockerymick commented on business_continuity/backup_restore/backup_existing_clusters.adoc
> +* The existing managed cluster can be detached during the restore process.
Why do we say "can be"? It makes it seem like a task for the user but it's a constraint
```suggestion
* Existing managed cluster are detached during the restore process.
```

2024-10-04 21:44 UTC, dockerymick commented on business_continuity/backup_restore/backup_existing_clusters.adoc
> +* The restore hub cluster can have more resources than the backup hub cluster.
Based on my previous question:
```suggestion
* There are more resources on the restore hub cluster than the backup hub cluster.
```

2024-10-04 21:44 UTC, dockerymick commented on business_continuity/backup_restore/backup_existing_clusters.adoc
> +== Existing managed clusters can be detached during the restore process
```suggestion
== Existing managed clusters are detached during the restore process
```

2024-10-04 21:44 UTC, dockerymick commented on business_continuity/backup_restore/backup_existing_clusters.adoc
> +* If the `ManagedCluster` resource does not have the `velero.io/backup-name: backupName` label annotation, and you run a restore operation with the `cleanupBeforeRestore` option set to `CleanupRestor
This is also related to the Tone guidance and the descriptions were a little confusing for me. The statement, "if you run a restore operation and use the `cleanupBeforeRestore=CleanupRestored` option.." was repeated in both bullet points so I thought it might be best to mention it once to simplify the descriptions. 

```suggestion
When you run a restore operation on your hub cluster that already manages some clusters and the `cleanupBeforeRestore` option set to `CleanupRestored`, the following outcomes occur:  

* Only when an earlier backup creates the `ManagedCluster` resources, the `velero.io/backup-name: backupName` label annotation is set, and the backup managed clusters are not part of the restored backup, managed clusters are detached and the data is cleaned on the managed clusters.
 
* When the `ManagedCluster` resources are not created by an earlier backup and do not have the `velero.io/backup-name: backupName` label annotation, `ManagedCluster` resources are not cleaned up. The managed clusters continue to be managed by your hub cluster and does not match the content of the backup hub cluster.
```

Does "detach" mean that the content of a managed clusters do not match the contents of the backup hub cluster? If yes, maybe we should start with explaining what detached is since we told the user that's what occurs. We can remove the explanation from the last bullet point.


```suggestion
A detached managed cluster has content that does not match the content of the backup hub cluster. When you run a restore operation on your hub cluster that already manages some clusters and the `cleanupBeforeRestore` option set to `CleanupRestored`, the following outcomes occur:  

* Only when an earlier backup creates the `ManagedCluster` resources, the `velero.io/backup-name: backupName` label annotation is set, and the backup managed clusters are not part of the restored backup, managed clusters are detached and the data is cleaned on the managed clusters.
 
* When the `ManagedCluster` resources are not created by an earlier backup and do not have the `velero.io/backup-name: backupName` label annotation, `ManagedCluster` resources are not cleaned up. The managed clusters continue to be managed by your hub cluster.
```

2024-10-04 21:44 UTC, dockerymick commented on business_continuity/backup_restore/backup_existing_clusters.adoc
> +== Restore hub can have more resources than the backup hub
```suggestion
== Restore hub cluster has more resources than the backup hub cluster
```

2024-10-04 21:44 UTC, dockerymick commented on business_continuity/backup_restore/backup_tag_resources.adoc
> +If you intend to use an existing hub for a restore hub configuration and expect that the hub has the same content as the backup hub after the restore is completed, tag any resource that would be part
Making this suggestion to add the benefit/reason of tagging the resources
```suggestion

Tag user-created resources on the restore hub cluster to use the existing hub cluster as a restore cluster. This helps you ensure that you have the same content between the restore hub cluster and the backup hub cluster.

When you use an existing hub cluster for a restore hub cluster configuration, tag any resource that you want to be part of the hub cluster backup with the `velero.io/backup-name: backupName` label annotation. Tagging the resources with the Velero annotation marks them as being generated by an earlier restore.
```

2024-10-04 21:44 UTC, dockerymick commented on business_continuity/backup_restore/backup_existing_clusters.adoc
> +If you intend to use an existing hub for a restore hub configuration and expect that the hub has the same content as the backup hub after the restore is completed, tag any resource that would be part
Should the second paragraph mention managed cluster instead of hub cluster? I just thought yes because this file mentions understanding outcomes for "existing managed clusters". Maybe also consider placeing 

```suggestion
When you restore a hub cluster with earlier user-created data and the `cleanupBeforeRestore` option is set to `CleanupRestored` for the restore operation, the resources of your restore hub cluster do not match the resources of the primary hub cluster. The user data includes the following resources: `policy`, `application`, `credential`, or any custom resource defined by the user. The resources are not cleaned because they are created by the users and not created by an earlier backup.

If you intend to use an existing hub cluster for a restore hub cluster configuration and expect for the hub cluster to have the same content as the backup hub cluster after the restore is completed, tag any resource that you want to be part of a hub cluster backup. See xref:../backup_restore/backup_tag_resources.adoc#backup-tagging-resources[Tagging resources] for more information.
```

2024-10-04 21:44 UTC, dockerymick commented on business_continuity/backup_restore/backup_existing_clusters.adoc
> += Understanding outcomes for existing managed clusters during the restore process
When I looked at the Google doc, the title is "Using an existing hub as a restore hub"

But should read as: "Using an existing hub cluster as a restore hub cluster"

It seems like this should be changed back to the title. Apologies if my suggestions in the first review were misleading. But should read as: "Using an existing hub cluster as a restore hub cluster". I was just confused before because I thought it was intended to be a task file.

2024-10-04 21:44 UTC, dockerymick commented on business_continuity/backup_restore/backup_tag_resources.adoc
> +* Before you tag the resources, make sure you set the storage location to a different location than the backup hub.
Please be sure to update each instance of "hub" to "hub cluster"

2024-10-04 21:44 UTC, dockerymick commented on business_continuity/backup_restore/backup_tag_resources.adoc
> +. Verify that the `BackupSchedule` has created the hub backup resources and their status is `Completed`.
How does the user do this? 
```suggestion
. Verify that the `BackupSchedule` created the hub cluster backup resources and the resource status is `Completed`.
```

2024-10-04 21:44 UTC, dockerymick commented on business_continuity/backup_restore/backup_tag_resources.adoc
> +.. *Note:* You cannot run a restore operation on the hub cluster if the `BackupSchedule` is enabled, so you pause the `BackupSchedule` to run a restore operation.
This note is appearing as a substep and the second part of the note seems unnecessary
```suggestion
. Pause the `BackupSchedule` schedule and stop generating backups by setting the property `paused=true` on the `schedule-acm-msa BackupSchedule`.
+
*Note:* You cannot run a restore operation on the hub cluster if the `BackupSchedule` is enabled.
```

2024-10-04 21:44 UTC, dockerymick commented on business_continuity/backup_restore/backup_tag_resources.adoc
> +. Run a restore operation by using the following yaml:
```suggestion
. Run a restore operation by using the following YAML: 
```

2024-10-04 21:44 UTC, dockerymick commented on release_notes/whats_new.adoc
> +* You can now use a restore hub as a cluster with resources that a user created before the restore operation. You can tag user created resources on the restore hub with the `velero.io/backup-name: ba
This entry is confusing. Should it be the following:

```suggestion
* You can now use an existing hub cluster as a restore hub cluster by tagging user-created resources on the restore hub cluster with the `velero.io/backup-name: backupName` label. See link:../business_continuity/backup_restore/backup_existing_clusters.adoc#backup-existing-clusters[Understanding outcomes for existing managed clusters during the restore process] and link:../backup_restore/backup_tag_resources.adoc#backup-tagging-resources[Tagging resources].
```

2024-10-04 21:44 UTC, dockerymick commented on business_continuity/backup_restore/backup_tag_resources.adoc
> +After tagging the resources, you can use the hub as a restore cluster. Update the `DataProtectionApplication` storage location to point to the storage location of the backup hub so you can run a rest
Should the following statement be a part of the procedure: 

Update the `DataProtectionApplication` storage location to point to the storage location of the backup hub so you can run a restore operation using the hub backup resources.

2024-10-04 21:44 UTC, dockerymick commented on business_continuity/backup_restore/backup_tag_resources.adoc
> +* Do not use the restore operation with the `cleanupBeforeRestore` option set to `CleanupRestored` if you have managed clusters on this hub created by an earlier restore operation which are not part
It seems like this note can be moved to the `backup_existing_clusters.adoc` file in the `#existing-clusters-detached` section

2024-10-04 21:44 UTC, dockerymick commented on business_continuity/backup_restore/backup_tag_resources.adoc
> +** The names of the managed clusters from the restore hub do not collide with any of the managed cluster names from the backup hub.
Should these be mentioned earlier as a description for Using an existing hub cluster as a restore hub cluster?

2024-10-07 13:55 UTC, birsanv commented on business_continuity/backup_restore/backup_existing_clusters.adoc
> +[#backup-existing-clusters]
@jc-berger I am sorry if I missed this in the initial review .. 

This section talks about : Using an existing hub cluster as a restore hub cluster , so the link should be matching somehow the content .. it is not about backing up existing clusters
I would probably use : #restore-using-existing-clusters

2024-10-07 13:56 UTC, birsanv commented on business_continuity/backup_restore/backup_existing_clusters.adoc
> += Understanding outcomes for existing managed clusters during the restore process
This title is not matching what we are talking about here, I don't remember seeing it on the first review

Should this be : Using an existing hub cluster as a restore hub cluster ?

2024-10-07 14:00 UTC, birsanv commented on business_continuity/backup_restore/backup_existing_clusters.adoc
> +Before you run the restore operation for existing hub clusters, understand the following constraints:
I find this confusing, I don't remember seeing it on the initial review ( Before you run the restore operation for existing hub clusters, understand the following constraints: )
The point I tried to make : If you use as a restore hub a cluster with resources you created before the restore operation, you must understand the following constraints: etc )

2024-10-07 20:15 UTC, dockerymick commented on business_continuity/backup_restore/use_existing_hub_cluster.adoc
> += Using an existing hub cluster as a restore hub cluster
@jc-berger the main thing is the title. It might be confused to be a task. Since this is a concept task can we brainstorm a different title? Maybe just "Existing hub cluster as a restore hub cluster"? idk though. maybe even "Use an existing hub cluster as a restore hub cluster", but I'm worried that it would still be confused as a task.

2024-10-07 20:25 UTC, dockerymick commented on business_continuity/backup_restore/tag_resources.adoc
> +** The names of the managed clusters from the restore hub cluster do not collide with any of the managed cluster names from the backup hub cluster.
There are a couple of run-on statements here. When you say "this hub cluster" is it the restore hub cluster? What is "they" ? Are you referring to the managed clusters? 

What is "..this constraint"? Are you referring to what's getting detached? 
```suggestion
* If you have managed clusters on the restore hub cluster created by an earlier restore operation which are not part of the restored backup, do not use the restore operation with the `cleanupBeforeRestore` option set to `CleanupRestored`. Otherwise, they get detached from the hub cluster and managed cluster resources are deleted. 
* Having this constraint, you could use an existing hub cluster as a restore hub cluster in the following situations:
** There are no managed clusters on this restore hub cluster. 
** There are managed clusters on the restore hub cluster and you do not expect the restore hub cluster user data to be the same with the one available with the restored backup.
** The names of the managed clusters from the restore hub cluster do not collide with any of the managed cluster names from the backup hub cluster.
```

2024-10-07 20:26 UTC, birsanv commented on business_continuity/backup_restore/use_existing_hub_cluster.adoc
> += Using an existing hub cluster as a restore hub cluster
@dockerymick what about "Options for using an existing hub cluster as a restore hub cluster"
or "Considerations when using an existing hub cluster as a restore hub cluster"

2024-10-07 20:36 UTC, dockerymick commented on business_continuity/backup_restore/use_existing_hub_cluster.adoc
> += Using an existing hub cluster as a restore hub cluster
I like "Considerations when using an existing hub cluster as a restore hub cluster"

2024-10-07 20:48 UTC, birsanv commented on business_continuity/backup_restore/tag_resources.adoc
> +** The names of the managed clusters from the restore hub cluster do not collide with any of the managed cluster names from the backup hub cluster.
@dockerymick - There are a couple of run-on statements here. When you say "this hub cluster" is it the restore hub cluster? What is "they" ? Are you referring to the managed clusters? 
answer : **hub** cluster always refers to the hub cluster, not to a managed cluster. **this hub cluster** is the cluster where the operation is executed , the hub where you run the restore op. The sentence before ( you could use an existing hub cluster as a restore hub cluster in the following situations: ) clarifies *this hub cluster* - we are talking about the existing hub cluster you are trying to use in a restore operation.

2024-10-07 20:50 UTC, birsanv commented on business_continuity/backup_restore/tag_resources.adoc
> +** The names of the managed clusters from the restore hub cluster do not collide with any of the managed cluster names from the backup hub cluster.
@dockerymick Having this constraint, = having this limitation

2024-10-07 22:19 UTC, dockerymick requested changes

2024-10-07 22:19 UTC, dockerymick commented on business_continuity/backup_restore/tag_resources.adoc
> +After you complete these steps, the operator goes over each resource which is part of the hub cluster backup and tags it with the `velero.io/backup-name: backupName` , where `backupName` is the name
```suggestion
After you complete these steps, the operator goes through each resource that is part of the hub cluster backup and tags it with the `velero.io/backup-name: backupName`, where `backupName` is the name of the latest backup. 
```

2024-10-07 22:19 UTC, dockerymick commented on business_continuity/backup_restore/tag_resources.adoc
> +After tagging the resources, you can use the hub cluster as a restore cluster. You can update the DataProtectionApplication storage location to point to the storage location of the backup hub cluster
Wall of text 
```suggestion
After you tag the resources, you can use the hub cluster as a restore cluster. Update the `DataProtectionApplication` storage location to point to the storage location of the backup hub cluster, so you can run a restore operation using the hub cluster backup resources. 

All the restore hub cluster resources are tagged now with the `velero.io/backup-name label`, so they show as being generated by an earlier restore. Therefore, any restore operation that you run on the existing hub cluster using the `cleanupBeforeRestore` option set to `CleanupRestored` cleans up the data that is not part of the restored backup.
```

2024-10-07 22:19 UTC, dockerymick commented on business_continuity/backup_restore/tag_resources.adoc
> +* Having this constraint, you can use an existing hub cluster as a restore hub cluster in the following situations:
"Having this constraint..." can we specify the constraint? Is it one of the two mentioned in "Considerations when using an existing hub cluster as a restore hub cluster" or are we referring to the previous bullet point? Looking back at the google doc, maybe this will help: 

```suggestion
* When there are more resources on the restore hub cluster than the backup hub cluster, you can use an existing hub cluster as a restore hub cluster in the following situations:
```

2024-10-07 22:22 UTC, dockerymick commented on business_continuity/backup_restore/use_existing_hub_cluster.adoc
> +When you restore a hub cluster with earlier user-created data and the `cleanupBeforeRestore` option is set to `CleanupRestored` for the restore operation, the resources of your restore hub cluster do
```suggestion
When you restore a hub cluster with earlier user-created data and the `cleanupBeforeRestore` option is set to `CleanupRestored` for the restore operation, the resources of your restore hub cluster do not match the resources of the primary hub cluster. The user data includes the following resources: `policy`, `application`, `credential`, or any custom resource defined by the user. The resources are not cleaned because the resources are created by the users and not created by an earlier backup.
```

2024-10-08 13:18 UTC, dockerymick commented on business_continuity/backup_restore/tag_resources.adoc
> +All the restore hub cluster resources are tagged now with the `velero.io/backup-name label`, so the hub clusters show as being generated by an earlier restore. Therefore, any restore operation that y
@birsanv One more question. Since @jc-berger moved forward with my suggestion, is it accurate to add the statement as a step in the procedure, "After you tag the resources, you can use the hub cluster as a restore cluster.  Update the `DataProtectionApplication` storage location to point to the storage location of the backup hub cluster, so you can run a restore operation using the hub cluster backup resources."? 

```suggestion
. Verify that the `BackupSchedule` created the hub cluster backup resources and the resource status is `Completed`.
. Pause the `BackupSchedule` schedule and stop generating backups by setting the property `paused=true` on the `schedule-acm-msa BackupSchedule`.
+
*Note:* You cannot run a restore operation on the hub cluster if the `BackupSchedule` is enabled.

. Run a restore operation by using the following YAML: 

+
[source,yaml]
----
kind: Restore
metadata:
name: restore-acm
namespace: open-cluster-management-backup
spec:
cleanupBeforeRestore: None
veleroManagedClustersBackupName: latest
veleroCredentialsBackupName: latest
veleroResourcesBackupName: latest
excludedResources: # exclude managed cluster resources
 - ManagedCluster
excludedNamespaces: # exclude managed cluster namespaces
  - managed-cls-1
  - managed-cls-2
  - managed-cls-n
----
+
The operator goes through each resource that is part of the hub cluster backup and tags it with the `velero.io/backup-name: backupName`, where `backupName` is the name of the latest backup. 

. After you tag the resources, you can use the hub cluster as a restore cluster. Update the `DataProtectionApplication` storage location to point to the storage location of the backup hub cluster, so you can run a restore operation using the hub cluster backup resources. 

All the restore hub cluster resources are tagged now with the `velero.io/backup-name label`, so the hub clusters show as being generated by an earlier restore. Therefore, any restore operation that you run on the existing hub cluster using the `cleanupBeforeRestore` option set to `CleanupRestored` cleans up the data that is not part of the restored backup.
```

2024-10-08 19:39 UTC, birsanv approved these changes
lgtm

2024-10-08 20:06 UTC, dockerymick approved these changes
Just a few more suggestions. Moving forward with the approval. Thanks !

2024-10-08 20:06 UTC, dockerymick commented on business_continuity/backup_restore/tag_resources.adoc
> +The operator goes through each resource that is part of the hub cluster backup and tags it with the `velero.io/backup-name: backupName`, where `backupName` is the name of the latest backup.
```suggestion
<2> Namespaces that you want to exclude. For this example, managed cluster namespaces are excluded.

The operator goes through each resource that is part of the hub cluster backup and tags it with the `velero.io/backup-name: backupName`, where `backupName` is the name of the latest backup. 
```

2024-10-08 20:06 UTC, dockerymick commented on business_continuity/backup_restore/tag_resources.adoc
> +After you tag the resources, you can use the hub cluster as a restore cluster. You are now ready to restore the data from the primary hub cluster by updating the `DataProtectionApplication` storage l
```suggestion
After you tag the resources, you can use the hub cluster as a restore cluster. You can now restore the data from the primary hub cluster by updating the `DataProtectionApplication` storage location to point to the storage location of the backup hub cluster, so you can run a restore operation that uses the hub cluster backup resources. 
```

2024-10-08 20:06 UTC, dockerymick commented on business_continuity/backup_restore/tag_resources.adoc
> +All the restore hub cluster resources are tagged now with the `velero.io/backup-name label`, so the hub clusters show as being generated by an earlier restore. Therefore, any restore operation that y
```suggestion
All the restore hub cluster resources are tagged with the `velero.io/backup-name label`, so the hub clusters show as being generated by an earlier restore. Therefore, any restore operation that you run on the existing hub cluster using the `cleanupBeforeRestore` option set to `CleanupRestored` cleans up the data that is not part of the restored backup.
```

2024-10-08 20:06 UTC, dockerymick commented on business_continuity/backup_restore/tag_resources.adoc
> +* If you have managed clusters on the restore hub cluster created by an earlier restore operation which are not part of the restored backup, do not use the restore operation with the `cleanupBeforeRe
```suggestion
* If you have managed clusters on the restore hub cluster created by an earlier restore operation that are not part of the restored backup, do not use the restore operation with the `cleanupBeforeRestore` option set to `CleanupRestored`. Otherwise, the managed clusters on the restore hub cluster get detached from the hub cluster and the managed cluster resources are deleted. 
```

2024-10-08 21:25 UTC, merged