https://issues.redhat.com/browse/ACM-14156
open-cluster-management/rhacm-docs pull request #6993
Opened 2024-10-02 16:21 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-14156

2024-10-02 18:22 UTC, birsanv approved these changes
lgtm

2024-10-07 13:57 UTC, dockerymick requested changes

2024-10-07 13:57 UTC, dockerymick commented on business_continuity/backup_restore/backup_install.adoc
> +[source,bash]
this should be [source,yaml] since this for a resource

2024-10-07 13:57 UTC, dockerymick commented on business_continuity/backup_restore/backup_install.adoc
> +*Warning:* If you use this option to get a different OADP version than the one installed by default by the backup and restore operator, make sure this version is supported on the OpenShift version us
"Warning" is not a special tag that we use. Refer to the Special tag guidance: https://stolostron.github.io/rhacm-docs/special_tag_guidance

We might want to use Note or Important

2024-10-07 13:57 UTC, dockerymick commented on business_continuity/backup_restore/backup_install.adoc
> +----
It seems like the override part is a step. Is that correct? I'm not sure.

```suggestion
Setting an annotation on your `MultiClusterHub` allows you to customize the OADP version for your specific needs. Complete the following steps:

. To override the OADP version installed by the backup and restore operator, use the following annotation on the `MultiClusterHub` resource:

+
[source,bash]
----
installer.open-cluster-management.io/oadp-subscription-spec: '{"channel": "stable-1.4"}'
----
```

2024-10-07 13:57 UTC, dockerymick commented on business_continuity/backup_restore/backup_install.adoc
> +----
```suggestion
. For example, install the OADP 1.5 version by setting your annotation. Your `MultiClusterHub` resource might resemble the following example: 
+
[source,yaml]
----
apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  annotations:
    installer.open-cluster-management.io/oadp-subscription-spec: '{"channel": "stable-1.5","installPlanApproval": "Automatic","name":
      "redhat-oadp-operator","source": "redhat-operators","sourceNamespace": "openshift-marketplace"}'
  name: multiclusterhub
spec: {}
---- 
```

2024-10-07 13:57 UTC, dockerymick commented on release_notes/whats_new.adoc
> +* You can now customize the OADP version by setting an annotation on your `MultiClusterHub`. See link:../business_continuity/backup_restore/backup_install.adoc#installing-custom-oadp[Installing a cus
```suggestion
* You can now customize the OADP version by setting an annotation on your `MultiClusterHub` resource. See link:../business_continuity/backup_restore/backup_install.adoc#installing-custom-oadp[Installing a custom OADP version].
```

2024-10-07 19:19 UTC, dockerymick commented on business_continuity/backup_restore/backup_install.adoc
> +. Enable the `cluster-backup` option on the `MultiClusterHub` resource.
How does the user do this? What would be the parameter value?

2024-10-07 19:26 UTC, birsanv commented on business_continuity/backup_restore/backup_install.adoc
> +. Enable the `cluster-backup` option on the `MultiClusterHub` resource.
@dockerymick the MCH resource has an option named `cluster-backup`. Line 105 asks to enable ( set to true that option ) .
This is also documented here ( how to enable backup on MCH ) https://docs.redhat.com/en/documentation/red_hat_advanced_cluster_management_for_kubernetes/2.11/html/business_continuity/business-cont-overview#enabling-the-backup-operator

2024-10-07 19:44 UTC, dockerymick commented on business_continuity/backup_restore/backup_install.adoc
> +. Enable the `cluster-backup` option on the `MultiClusterHub` resource.
```suggestion
. Enable the `cluster-backup` option on the `MultiClusterHub` resource by setting `cluster-back` to `true`. 
```

2024-10-07 19:44 UTC, dockerymick commented on business_continuity/backup_restore/backup_install.adoc
> +. Enable the `cluster-backup` option on the `MultiClusterHub` resource.
Thanks!

2024-10-10 15:56 UTC, jc-berger commented
To avoid merge conflicts and rebase, I'm closing this PR so we can focus here on this new one: https://github.com/stolostron/rhacm-docs/pull/7042

2024-10-10 15:56 UTC, closed without merging