Cluster management changes
open-cluster-management/rhacm-docs pull request #6996
Opened 2024-10-02 19:26 UTC by swopebe

2024-10-07 19:04 UTC, dockerymick requested changes

2024-10-07 19:04 UTC, dockerymick commented on clusters/about/mce_intro.adoc
> += About Cluster management with {mce-short}
To use sentence-style or is it capitalized because its a product component?
```suggestion
= About cluster management with {mce-short}
```

2024-10-07 19:04 UTC, dockerymick commented on clusters/cluster_mce_overview.adoc
> +* xref:about/mce_intro.adoc#mce-intro[About Cluster management with {mce-short}]
Related to my previous comment
```suggestion
* xref:about/mce_intro.adoc#mce-intro[About cluster management with {mce-short}]
```

2024-10-07 19:04 UTC, dockerymick commented on clusters/install_upgrade/install_intro.adoc
>  *Important:* If you are using {acm-short}, then {mce} is already installed on the cluster.
on line 23, the link to {acm-short} integration appeared as broken
<img width="606" alt="Screenshot 2024-10-07 at 2 45 47 PM" src="https://github.com/user-attachments/assets/ba921142-8937-4fbe-8299-facbc0d1bac4">

since is a diifferent folder, it needs to be `link:`

2024-10-07 19:04 UTC, dockerymick commented on clusters/release_notes/mce_deprecate_remove.adoc
> += Deprecations and removals for Cluster management with {mce-short}
```suggestion
= Deprecations and removals for cluster management with {mce-short}
```

2024-10-07 19:04 UTC, dockerymick commented on clusters/release_notes/mce_errata.adoc
> += Errata updates for Cluster management with {mce-short}
```suggestion
= Errata updates for cluster management with {mce-short}
```

2024-10-07 19:04 UTC, dockerymick commented on clusters/release_notes/mce_known_issues.adoc
> += Known issues and limitations for Cluster management with {mce-short}
```suggestion
= Known issues and limitations for cluster management with {mce-short}
```

2024-10-07 19:04 UTC, dockerymick commented on clusters/release_notes/mce_release_notes.adoc
> += Release notes for Cluster management with {mce-short}
```suggestion
= Release notes for cluster management with {mce-short}
```

2024-10-07 19:04 UTC, dockerymick commented on clusters/release_notes/mce_release_notes.adoc
> +* xref:../release_notes/mce_deprecate_remove.adoc#deprecations-removals-cluster-mce[Deprecations and removals for Cluster management with {mce-short}]
If you agree with using sentence style, remember to update the title names of the link references.

2024-10-07 19:04 UTC, dockerymick commented on clusters/release_notes/mce_release_notes.adoc
> +Best practice:: Upgrade to the most recent version.
Were you intending to use the definition syntax or just to bold? This is how it appears: 

<img width="1113" alt="Screenshot 2024-10-07 at 2 57 38 PM" src="https://github.com/user-attachments/assets/15a4fbe8-f6b6-48a4-9c8c-e0e47d156f71">

2024-10-07 19:04 UTC, dockerymick commented on clusters/release_notes/mce_whats_new.adoc
> += What's new for Cluster management with {mce-short}
Same comment about sentence style

2024-10-07 19:04 UTC, dockerymick commented on release_notes/acm_known_issues_intro.adoc
> +=  Known issues and limitations for {acm-short}
```suggestion
= Known issues and limitations for {acm-short}
```

2024-10-07 19:04 UTC, dockerymick commented on release_notes/acm_release_notes.adoc
> +* xref:../release_notes/acm_errata.adoc##errata-acm[Errata updates for {acm-short}]
```suggestion
* xref:../release_notes/acm_errata.adoc#errata-acm[Errata updates for {acm-short}]
```

2024-10-07 19:04 UTC, dockerymick commented on release_notes/acm_release_notes.adoc
> +Best practice:: Upgrade to the most recent version.
Same question about using this syntax. i thought we were only using it for definition lists. Do you mean to just bold these?

2024-10-07 20:50 UTC, swopebe commented on clusters/cluster_mce_overview.adoc
> +* xref:about/mce_intro.adoc#mce-intro[About Cluster management with {mce-short}]
I think we need to keep it as-is, it is like the Feature "Observability"

2024-10-07 20:51 UTC, swopebe commented on clusters/install_upgrade/install_intro.adoc
>  *Important:* If you are using {acm-short}, then {mce} is already installed on the cluster.
Ok, that is part of other work that I have to catch later.

2024-10-07 20:52 UTC, swopebe commented on clusters/release_notes/mce_release_notes.adoc
> +Best practice:: Upgrade to the most recent version.
ok, I will look at it, no I wanted just bold.

2024-10-07 20:52 UTC, swopebe commented on clusters/release_notes/mce_whats_new.adoc
> += What's new for Cluster management with {mce-short}
This is the name of the function, same as it was before

2024-10-07 20:53 UTC, swopebe commented on release_notes/acm_release_notes.adoc
> +Best practice:: Upgrade to the most recent version.
Yes

2024-10-07 20:53 UTC, swopebe commented on release_notes/acm_release_notes.adoc
> +Best practice:: Upgrade to the most recent version.
I can change it back. I have a lot to do in these files.

2024-10-07 20:54 UTC, swopebe commented on clusters/release_notes/mce_release_notes.adoc
> +* xref:../release_notes/mce_deprecate_remove.adoc#deprecations-removals-cluster-mce[Deprecations and removals for Cluster management with {mce-short}]
The syntax doesn't change here

2024-10-07 20:54 UTC, swopebe commented on clusters/release_notes/mce_release_notes.adoc
> += Release notes for Cluster management with {mce-short}
The name of the function is still Cluster

2024-10-07 20:55 UTC, swopebe commented on clusters/release_notes/mce_known_issues.adoc
> += Known issues and limitations for Cluster management with {mce-short}
This is the name of the function

2024-10-07 21:53 UTC, dockerymick commented on clusters/about/mce_intro.adoc
> += About Cluster management with {mce-short}
@swopebe explained that this should remain the same

2024-10-07 21:56 UTC, dockerymick commented on clusters/cluster_mce_overview.adoc
> +* xref:about/mce_intro.adoc#mce-intro[About Cluster management with {mce-short}]
i don't always capitalize Observability. Like I usually say "observability components". Maybe that's another discussion as I improve the book in the future. I'm fine with you leaving as is.

2024-10-07 21:58 UTC, dockerymick commented on clusters/install_upgrade/install_intro.adoc
>  *Important:* If you are using {acm-short}, then {mce} is already installed on the cluster.
Yup your change fixed it!

2024-10-07 22:01 UTC, dockerymick commented on clusters/release_notes/mce_release_notes.adoc
> +Best practice:: Upgrade to the most recent version.
Ok just need to use the asterisk then

2024-10-07 22:01 UTC, dockerymick commented on clusters/release_notes/mce_release_notes.adoc
> +Best practice:: Upgrade to the most recent version.
```suggestion
*Best practice* Upgrade to the most recent version.
```

2024-10-07 22:01 UTC, dockerymick commented on clusters/release_notes/mce_release_notes.adoc
> +Deprecated:: {mce-short} 2.2 and earlier versions are no longer supported. The documentation might remain available, but without any Errata or other updates.
```suggestion
*Deprecated:* {mce-short} 2.2 and earlier versions are no longer supported. The documentation might remain available, but without any Errata or other updates.
```

2024-10-07 22:03 UTC, dockerymick commented on release_notes/acm_release_notes.adoc
> +Best practice:: Upgrade to the most recent version.
```suggestion
*Deprecated:* {acm-short} 2.7 and earlier versions are no longer supported. The documentation might remain available, but without any Errata or other updates.

*Best practice:* Upgrade to the most recent version.
```

2024-10-07 23:31 UTC, swopebe commented on clusters/cluster_mce_overview.adoc
> +* xref:about/mce_intro.adoc#mce-intro[About Cluster management with {mce-short}]
Yeah, we should be capitalizing our components, I didn't know folks weren't. Cluster lifecycle, I am just using "Cluster" here, if that is confusing, I may change it back, Application lifecycle, Governance, Observability.

2024-10-08 14:52 UTC, dockerymick approved these changes
Left a few suggestions earlier, approving

2024-10-09 14:14 UTC, merged