https://issues.redhat.com/browse/ACM-14568: doo not support API token to import cluster
open-cluster-management/rhacm-docs pull request #7021
Opened 2024-10-08 03:44 UTC by ldpliu

2024-10-08 13:09 UTC, jc-berger approved these changes
/lgtm

2024-10-08 13:30 UTC, swopebe commented on global_hub/global_hub_import_hub_hosted.adoc
> +To import an existing hub cluster that has `local-cluster` enabled, you must use the hosted mode. In the hosted mode, you only get support for import managed hub clusters that use `kubeconfig`. {acm}
should this be import_ed_ managed hub clusters?

2024-10-08 13:31 UTC, swopebe requested changes
Couple comments.

2024-10-08 13:31 UTC, swopebe commented on global_hub/global_hub_import_hub_hosted.adoc
> +- Make sure this `kubeconfig` is always usable. If it expires, regenerate the `auto-import-secret` in the managed hub cluster namespace with the following command: `oc create secret generic auto-impo
take a look at this, the command is long and embedded in the paragraph, which is reduced UX. This prob should be moved below and coded, as we do with most commands.

2024-10-08 18:32 UTC, jc-berger commented on global_hub/global_hub_import_hub_hosted.adoc
> +- Make sure this `kubeconfig` is always usable. If it expires, regenerate the `auto-import-secret` in the managed hub cluster namespace with the following command: `oc create secret generic auto-impo
```suggestion
- Make sure this `kubeconfig` is always usable. If it expires, regenerate the `auto-import-secret` in the managed hub cluster namespace with the following command:
+
----
oc create secret generic auto-import-secret --from-file=kubeconfig=./managedClusterKubeconfig -n <Managedhub Namespace>
----
```

2024-10-08 18:32 UTC, jc-berger commented on global_hub/global_hub_import_hub_hosted.adoc
> +- Make sure this `kubeconfig` is always usable. If it expires, regenerate the `auto-import-secret` in the managed hub cluster namespace with the following command: `oc create secret generic auto-impo
@ldpliu if you like this suggestion, I'll go ahead and commit it!

2024-10-08 18:33 UTC, jc-berger commented on global_hub/global_hub_import_hub_hosted.adoc
> +To import an existing hub cluster that has `local-cluster` enabled, you must use the hosted mode. In the hosted mode, you only get support for import managed hub clusters that use `kubeconfig`. {acm}
@ldpliu would it be as Brandi suggests? Or how it's currently written, " In the hosted mode, you only get support for import managed hub clusters that use `kubeconfig`. "

2024-10-08 19:12 UTC, swopebe commented on global_hub/global_hub_import_hub_hosted.adoc
> +To import an existing hub cluster that has `local-cluster` enabled, you must use the hosted mode. In the hosted mode, you only get support for import managed hub clusters that use `kubeconfig`. {acm}
that doesn't make sense as-is if you read the line before it, we as writers can change this

2024-10-08 19:27 UTC, swopebe commented on global_hub/global_hub_import_hub_hosted.adoc
> +- Make sure this `kubeconfig` is always usable. If it expires, regenerate the `auto-import-secret` in the managed hub cluster namespace with the following command: `oc create secret generic auto-impo
This is also a change we make as writers responsible for the doc; you can merge this. It's the same command just on another line.

2024-10-08 19:39 UTC, swopebe approved these changes
approving pending merge of changes

2024-10-09 00:51 UTC, ldpliu commented on global_hub/global_hub_import_hub_hosted.adoc
> +To import an existing hub cluster that has `local-cluster` enabled, you must use the hosted mode. In the hosted mode, you only get support for import managed hub clusters that use `kubeconfig`. {acm}
How about change this line to:

`To import an existing hub cluster that has `local-cluster` enabled, you must use 'kubeconfig' to import managed hub clusters in hosted mode.`

2024-10-09 00:52 UTC, ldpliu commented on global_hub/global_hub_import_hub_hosted.adoc
> +- Make sure this `kubeconfig` is always usable. If it expires, regenerate the `auto-import-secret` in the managed hub cluster namespace with the following command: `oc create secret generic auto-impo
It looks good to me.

2024-10-09 13:19 UTC, swopebe commented on global_hub/global_hub_import_hub_hosted.adoc
> +To import an existing hub cluster that has `local-cluster` enabled, you must use the hosted mode. In the hosted mode, you only get support for import managed hub clusters that use `kubeconfig`. {acm}
This is confusing.

First line: _To import an existing hub cluster_ , then second line of the same sentance says `you must use 'kubeconfig' to import managed hub clusters in hosted mode.`

I think the writers need to understand function, then we can work on this line so it makes sense. @jc-berger FYI.

2024-10-09 13:21 UTC, swopebe requested changes
Request changes for newest lines because it's not clear what we are trying to say we are importing here.

2024-10-09 13:36 UTC, swopebe commented on global_hub/global_hub_import_hub_hosted.adoc
> +To import an existing hub cluster that has `local-cluster` enabled, you must use the hosted mode. In the hosted mode, you only get support for import managed hub clusters that use `kubeconfig`. {acm}
Use `kubeconfig` to import managed hub clusters in hosted mode, then you can import an existing hub cluster that has` local-cluster `enabled. (????) 

(Again, I am not sure what we are trying to say here. The short description is not clear on this either.)

For writer: **kubeconfig** is a file, so we need to refer to it as we do files; standard is in the manual:

https://www.ibm.com/docs/en/ibm-style?topic=elements-files-directories

2024-10-09 15:43 UTC, jc-berger commented on global_hub/global_hub_import_hub_hosted.adoc
> +To import an existing hub cluster that has `local-cluster` enabled, you must use the hosted mode. In the hosted mode, you only get support for import managed hub clusters that use `kubeconfig`. {acm}
```suggestion
To import an existing managed hub cluster that has `local-cluster` enabled, you must use the hosted mode. In the hosted mode, you only get support for imported managed hub clusters that use a `kubeconfig` file. {acm} uses this `kubeconfig` file to generate the `auto-import-secret`, which connects to your managed hub cluster. 
```

2024-10-09 15:43 UTC, jc-berger commented on global_hub/global_hub_import_hub_hosted.adoc
> +To import an existing hub cluster that has `local-cluster` enabled, you must use the hosted mode. In the hosted mode, you only get support for import managed hub clusters that use `kubeconfig`. {acm}
@ldpliu please let me know what you think of this revised description. If you approve, I'll commit the suggestion!

2024-10-10 00:32 UTC, ldpliu commented on global_hub/global_hub_import_hub_hosted.adoc
> +To import an existing hub cluster that has `local-cluster` enabled, you must use the hosted mode. In the hosted mode, you only get support for import managed hub clusters that use `kubeconfig`. {acm}
It looks good to me. Thanks

2024-10-10 14:40 UTC, swopebe commented on global_hub/global_hub_import_hub_hosted.adoc
> +- Make sure this `kubeconfig` is always usable. If it expires, regenerate the `auto-import-secret` in the managed hub cluster namespace with the following command:
Make sure this `kubeconfig` is always usable.

This will need to also change...line 18

2024-10-10 14:41 UTC, swopebe approved these changes

2024-10-10 15:09 UTC, jc-berger commented on global_hub/global_hub_import_hub_hosted.adoc
> +- Make sure this `kubeconfig` is always usable. If it expires, regenerate the `auto-import-secret` in the managed hub cluster namespace with the following command:
```suggestion
- Make sure this `kubeconfig` file is always usable. If it expires, regenerate the `auto-import-secret` in the managed hub cluster namespace with the following command:
```

2024-10-10 15:09 UTC, merged