https://issues.redhat.com/browse/ACM-14070
open-cluster-management/rhacm-docs pull request #7039
Opened 2024-10-09 17:50 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-14070 

See Gdoc with beginning stages of collaboration and edits: https://docs.google.com/document/d/1ryz4KV6CNbNgLI0r7dcyBgo4-O1dZzNV9_frDEe_U9M/edit?usp=sharing

2024-10-09 17:55 UTC, jc-berger commented on business_continuity/backup_restore/backup_return_hub.adoc
> + veleroSchedule: 0 */1*
@birsanv the original line here was ` 0 */1 * * * ` 

That made some weird bolding issues. Anyway, I'm trying to fix it, but before I make too many commits, I wanted to see how the format of this yaml line must be before I continue to make changes to it.

2024-10-09 18:03 UTC, birsanv commented on business_continuity/backup_restore/backup_return_hub.adoc
> + veleroSchedule: 0 */1*
@jc-berger this is the format https://github.com/stolostron/cluster-backup-operator/blob/main/config/samples/cluster_v1beta1_backupschedule_msa.yaml

2024-10-09 18:05 UTC, swopebe commented on business_continuity/backup_restore/backup_return_hub.adoc
> + veleroSchedule: 0 */1*
https://stolostron.github.io/rhacm-docs/special_considerations see if the answer is in internal docs @jc-berger -- we have had to document this.

2024-10-09 18:06 UTC, swopebe commented on business_continuity/backup_restore/backup_return_hub.adoc
> + veleroSchedule: 0 */1*
there are some other formatting issues later in the file that can be fixed with a space.

2024-10-09 18:09 UTC, birsanv approved these changes
lgtm

2024-10-09 18:11 UTC, birsanv requested changes
please update the BackupSchedule yaml and use   veleroSchedule: 0 */1 * * *

2024-10-09 18:11 UTC, birsanv commented on business_continuity/backup_restore/backup_return_hub.adoc
> + veleroSchedule: 0 */1*
sorry, I lgtm, but this needs to be fixed first, it should be 
  veleroSchedule: 0 */1 * * *

2024-10-09 18:11 UTC, birsanv commented on business_continuity/backup_restore/backup_return_hub.adoc
> + veleroSchedule: 0 */1*
same here, it should be

  veleroSchedule: 0 */1 * * *

2024-10-09 18:30 UTC, jc-berger commented
@birsanv thank you for such a prompt review! I made your change and added content to the `what's new` doc. Thanks!

2024-10-09 19:15 UTC, birsanv requested changes

2024-10-09 19:15 UTC, birsanv commented on business_continuity/backup_restore/backup_return_hub.adoc
> + veleroSchedule: `0 */1 * * *`
tic is not a valid content for the yaml @jc-berger 
Can you use instead "0 */1 * * *" ?  This is valid

2024-10-10 15:52 UTC, birsanv approved these changes
lgtm

2024-10-11 15:12 UTC, thuyn-581 approved these changes
lgtm

2024-10-11 19:35 UTC, dockerymick requested changes
Thanks for your patience Jake!

2024-10-11 19:35 UTC, dockerymick commented on business_continuity/backup_restore/backup_return_hub.adoc
> +In this scenario, run a disaster recovery test by simulating a disaster that makes the primary hub cluster unusable, requiring you to restore hub data on a new hub cluster. In this simulation, the ba
```suggestion
In this scenario, run a disaster recovery test by simulating a disaster that makes the primary hub cluster unusable, requiring you to restore hub cluster data on a new hub cluster. In this simulation, the backup data is restored to a new hub cluster, and you must verify that all the data is recovered successfully.
```

2024-10-11 19:35 UTC, dockerymick commented on business_continuity/backup_restore/backup_return_hub.adoc
> +After you complete all the required tests, return to the initial hub cluster by using the primary hub cluster as the active hub cluster. To do this, restore the data back to the initial hub cluster.
```suggestion
After you complete all the required tests, return to the initial hub cluster by using the primary hub cluster as the active hub cluster. To do this, restore the data back to the initial hub cluster. This action is known as controlled recovery operation because you are able to control the timing of the recovery operation. You can run any required steps to prepare the primary hub cluster, so that you can reuse the hub cluster after completing the disaster recovery test. 
```

2024-10-11 19:35 UTC, dockerymick commented on business_continuity/backup_restore/backup_return_hub.adoc
> +* To prepare the backup hub cluster for the restore operation and to run the restore, complete the following documentation: xref:../backup_restore/backup_active_restore.adoc##keep-hub-active-restore[
```suggestion
[#return-initial-prereq]
== Prerequisite 

To prepare the backup hub cluster for the restore operation and to run the restore, complete the following documentation: xref:../backup_restore/backup_active_restore.adoc#keep-hub-active-restore[Keeping the primary hub cluster active during a restore process]. 
```

2024-10-11 19:35 UTC, dockerymick commented on business_continuity/backup_restore/backup_return_hub.adoc
> +. Run the restore operation on the new hub cluster to make it the active hub cluster.
I understand that the topic "Running the restore operation exist, but I was considering the back and forth or clicks that the user might have to do. 
```suggestion
. To make the new hub cluster the active hub cluster, run the restore operation on the new hub cluster by applying the `restore-acm.yaml` file.
```

2024-10-11 19:35 UTC, dockerymick commented on business_continuity/backup_restore/backup_return_hub.adoc
> +. Verify that the managed clusters are now connected to the new hub cluster.
How does the user do this? Do they only need to look at the `restore-acm.yaml` file to confirm a parameter value?

2024-10-11 19:35 UTC, dockerymick commented on business_continuity/backup_restore/backup_return_hub.adoc
> +. Run your disaster recovery simulation tests on this hub cluster.
Is there a command that the user has to run?

2024-10-11 19:35 UTC, dockerymick commented on business_continuity/backup_restore/backup_return_hub.adoc
> +After your disaster recovery tests complete, you are ready to return to the primary hub  cluster and make it the active hub cluster that manages the cluster fleet. To do this, complete the following
```suggestion
After your disaster recovery tests complete, you can return to the primary hub cluster and make it the active hub cluster that manages the cluster fleet. To do this, complete the following sections to return to the primary cluster:
```

2024-10-11 19:35 UTC, dockerymick commented on business_continuity/backup_restore/backup_return_hub.adoc
> +kind: BackupSchedule
```suggestion
. On the restore hub cluster, apply the following resource:

+
[source,yaml]
----
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: BackupSchedule
```

2024-10-11 19:35 UTC, dockerymick commented on business_continuity/backup_restore/backup_return_hub.adoc
> +. Make sure the {prod-short} backups are generated and have the `Completed` status.
I didn't see prod-short in the common-attributes file. Did you mean acm-short?
```suggestion
. Make sure the {acm-short} backups are generated and have the `Completed` status.
```

2024-10-11 19:35 UTC, dockerymick commented on business_continuity/backup_restore/backup_return_hub.adoc
> +. Add the `import.open-cluster-management.io/disable-auto-import: '' annotation to all  ManagedCluster` resources so they do not connect back to this hub cluster after being moved back to the primary
```suggestion
. To ensure the `ManagedCluster` resources do not connect back to the initial hub cluster after getting moved back to the primary hub cluster, add the `import.open-cluster-management.io/disable-auto-import: ''` annotation to all `ManagedCluster` resources.
```

2024-10-11 19:35 UTC, dockerymick commented on business_continuity/backup_restore/backup_return_hub.adoc
> +metadata:
```suggestion
. Restore all the resources from the secondary hub cluster backup by applying the following restore resource: 

+
[source,yaml]
----
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Restore
metadata:
```

2024-10-11 19:35 UTC, dockerymick commented on business_continuity/backup_restore/backup_return_hub.adoc
> +*Note:* Since the `cleanupBeforeRestore` property has the `CleanupRestored` value, a cleanup operation runs after all resources are restored. This cleanup operation removes any hub resource that is n
```suggestion
 veleroCredentialsBackupName: latest
 veleroResourcesBackupName: latest
----
+
*Note:* When you set the `cleanupBeforeRestore` property to `CleanupRestored`, a cleanup operation runs after all resources are restored. This cleanup operation removes any hub resource that is not part of the restored backup. 
```

2024-10-11 19:35 UTC, dockerymick commented on business_continuity/backup_restore/backup_return_hub.adoc
> +Now that the initial hub cluster is the primary hub cluster again, enable the backup schedule on the primary hub cluster by completing the following step:
```suggestion
Now that the initial hub cluster is the primary hub cluster again, enable the backup schedule on the primary hub cluster by completing the following steps:
```

2024-10-11 19:35 UTC, dockerymick commented on business_continuity/backup_restore/backup_return_hub.adoc
> +*Note:* The second hub can be used again as the secondary hub cluster in the `active-passive` configuration.
```suggestion
. Go to the primary hub cluster.
. Apply the following `BackupSchedule` resource: 

+
[source,yaml]
----
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: BackupSchedule
metadata:
 name: schedule-acm-msa
 namespace: open-cluster-management-backup
spec:
 veleroSchedule: "0 */1 * * *"
 veleroTtl: 120h
 useManagedServiceAccount: true
 paused: false
----
+
*Note:* The second hub cluster can be used again as the secondary hub cluster in the `active-passive` configuration.
```

2024-10-11 19:35 UTC, dockerymick commented on release_notes/acm_whats_new.adoc
> +* You now have a scenario where you can run a disaster recovery test. By simulating a disaster, you can practice the following actions: restoring hub data on a new hub cluster, verifying that data ha
```suggestion
* You now have a scenario where you can run a disaster recovery test. By simulating a disaster, you can practice the following actions: restoring hub cluster data on a new hub cluster, verifying that data is recovered, and returning to the initial hub cluster by using the primary hub cluster as a the active hub cluster. See link:../business_continuity/backup_restore/backup_return_hub.adoc#return-initial-hub[Returning to the initial hub cluster after a restore].
```

2024-10-11 19:46 UTC, birsanv commented on business_continuity/backup_restore/backup_return_hub.adoc
> +. Verify that the managed clusters are now connected to the new hub cluster.
@dockerymick the user should check the status of the managed clusters in the clusters UI - this is how you can see if a managed cluster is connected with the hub

2024-10-15 16:50 UTC, dockerymick commented on business_continuity/backup_restore/backup_return_hub.adoc
> +. Run your disaster recovery simulation tests on this hub cluster.
@jc-berger @birsanv how does the user do this?

2024-10-15 17:21 UTC, birsanv commented on business_continuity/backup_restore/backup_return_hub.adoc
> +. Run your disaster recovery simulation tests on this hub cluster.
@dockerymick there is no command in particular, should use the console ui to check that the clusters status is ready. Any other way of checking that the clusters are connected are outside of this documentation and should be covered by the acm console doc

2024-10-15 18:46 UTC, dockerymick requested changes

2024-10-15 18:46 UTC, dockerymick commented on business_continuity/backup_restore/backup_return_hub.adoc
> +. To verify that the managed clusters are now connected to the new hub cluster, check the status of the managed clusters in the cluster UI.
```suggestion
. To verify that the managed clusters are now connected to the new hub cluster, check the status of the managed clusters from the cluster console. 
```

2024-10-15 18:46 UTC, dockerymick commented on business_continuity/backup_restore/backup_return_hub.adoc
> +. Run your disaster recovery simulation tests on this hub cluster.
Based on @birsanv explanation, @jc-berger what are your thoughts about my suggestion here:
```suggestion
. Verify that the clusters have the `Ready` status, which indicates a successful connection. Run your disaster recovery simulation tests on your new hub cluster.
```

2024-10-16 17:24 UTC, birsanv requested changes
one comment, everything else looks good

2024-10-16 17:24 UTC, birsanv commented on business_continuity/backup_restore/backup_return_hub.adoc
> +. To make the new hub cluster the active hub cluster, run the restore operation on the new hub cluster by applying the `restore-acm.yaml` file.
There is no `restore-acm.yaml` file mentioned until now .. 

This sentence should convey that you can now run the restore operation ( it does not matter what yaml file you restore, this is outside the scope here ) 
This needs to be changed , I suggest 

- You can now run the restore operation on the new hub cluster to make it the active hub cluster.

2024-10-17 15:34 UTC, dockerymick commented on business_continuity/backup_restore/backup_return_hub.adoc
> +. Run your disaster recovery simulation tests on this hub cluster.
@birsanv @jc-berger Can we clarify "this hub cluster". Is it suppose to be the new hub cluster or active hub cluster?

2024-10-17 16:13 UTC, dockerymick commented on business_continuity/backup_restore/backup_return_hub.adoc
> +. Run your disaster recovery simulation tests on this new hub cluster.
```suggestion
. Run your disaster recovery simulation tests on the new hub cluster.
```

2024-10-17 16:15 UTC, dockerymick approved these changes
Looks good to me! Thanks Jake

2024-10-17 18:53 UTC, merged