https://issues.redhat.com/browse/ACM-14156
open-cluster-management/rhacm-docs pull request #7042
Opened 2024-10-10 15:56 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-14156

See PR that had Dev approval and thorough Doc review: See Jira: https://github.com/stolostron/rhacm-docs/pull/6993 

That PR had complicated merge conflicts due to changes in the "what's new" doc, so I think it's easier to focus our attention on this new, clean PR, thanks!

2024-10-10 16:01 UTC, birsanv approved these changes
lgtm

2024-10-11 14:42 UTC, dockerymick requested changes

2024-10-11 14:42 UTC, dockerymick commented on business_continuity/backup_restore/backup_install.adoc
> +*Important:* If you use this option to get a different OADP version than the one installed by default by the backup and restore operator, make sure this version is supported on the OpenShift version
@jc-berger I think we should use the OCP conref for "OpenShift"

2024-10-11 14:42 UTC, dockerymick commented on release_notes/acm_whats_new.adoc
>  * You can now use an existing hub cluster as a restore hub cluster by tagging user-created resources on the restore hub cluster with the `velero.io/backup-name: backupName` label. See link:../backup_
The two links here appeared as broken
<img width="1107" alt="Screenshot 2024-10-11 at 10 30 38 AM" src="https://github.com/user-attachments/assets/306e25eb-9dfe-4dcd-bc2c-e00144d20b12">
```suggestion
* You can now use an existing hub cluster as a restore hub cluster by tagging user-created resources on the restore hub cluster with the `velero.io/backup-name: backupName` label. See link:../business_continuity/backup_restore/use_existing_hub_cluster.adoc#using-existing-hub[Considerations when using an existing hub cluster as a restore hub cluster] and link:../business_continuity/backup_restore/tag_resources.adoc#tagging-resources[Tagging resources]. 
```

Will you also fix the link to the ACM Release notes? Will you change "* See more release notes, such as _Known Issues and Limitations_ in the {acm-short} xref:../release_notes/release_notes.adoc#release-notes[Release notes]." TO "* See more release notes, such as _Known Issues and Limitations_ in the xref:../release_notes/acm_release_notes.adoc#acm-release-notes[Release notes for {acm-short}] ."

2024-10-11 14:42 UTC, dockerymick commented on release_notes/acm_whats_new.adoc
>  * You can now use an existing hub cluster as a restore hub cluster by tagging user-created resources on the restore hub cluster with the `velero.io/backup-name: backupName` label. See link:../backup_
There is another broken link, but that is for the Support matrix and we expect for that to be broken because it isn't published yet

2024-10-14 14:36 UTC, dockerymick commented on business_continuity/backup_restore/backup_install.adoc
> +Setting an annotation on your `MultiClusterHub` allows you to customize the OADP version for your specific needs. Complete the following steps:
```suggestion
Setting an annotation on your `MultiClusterHub` resource allows you to customize the OADP version for your specific needs. Complete the following steps:
```

2024-10-14 14:43 UTC, dockerymick requested changes

2024-10-14 14:43 UTC, dockerymick commented on business_continuity/backup_restore/backup_install.adoc
> +//are these suppose to be multiple important notes?
@jc-berger I left a hidden comment here bc this part of the file was not appearing

2024-10-14 14:43 UTC, dockerymick commented on business_continuity/backup_restore/backup_install.adoc
> +[source,bash]
I added the [source,bash] syntax here because @oafischer let me know that it is needed for terminal messages too

2024-10-14 15:06 UTC, dockerymick approved these changes
this looks good to me, thanks Jake!

2024-10-14 15:36 UTC, merged