https://issues.redhat.com/browse/ACM-14631
open-cluster-management/rhacm-docs pull request #7047
Opened 2024-10-10 19:47 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-14631

2024-10-10 19:48 UTC, jc-berger commented on gitops/gitops_registering.adoc
> +== Registering non-_ocp-short_ clusters to GitOps
@xiangjingli let me know what you think about me making this content its own section.

2024-10-10 19:49 UTC, jc-berger commented on gitops/gitops_registering.adoc
> +. Go to the API server URL in the non-{ocp-short} `ManagedCluster` spec and validate it by running the following command:
@xiangjingli maybe this would be better for a QE reviewer, but let me know what you think about these steps. 

From reading the Jira, it seems like some of the content was more knowledge for the user rather than actions to take. Hence, I made a "Notes" section and made the steps for the users more concise. 

Let me know what you think, thanks :)

2024-10-10 20:44 UTC, xiangjingli commented on gitops/gitops_registering.adoc
> +** The non-{ocp-short} cluster was manually imported to the {acm-short} hub in version 2.12.
The non-{ocp-short} cluster was manually imported to the {acm-short} hub in version 2.12. 
=============>
The non-{ocp-short} cluster was manually imported to the {acm-short} hub in version 2.12 via the import mode "Run import commands manually"

The import mode "Run import commands manually" is the term used in Ui when importing clusters. We may highlight it here so that users clearly know what the manual import means.

2024-10-10 20:50 UTC, xiangjingli commented on gitops/gitops_registering.adoc
> +== Registering non-_ocp-short_ clusters to GitOps
Yeah, it looks good to append a new section after the existing section 
`1.2.2. Registering managed clusters to GitOps`

So the 1.2.2 is the general introduction for registering all OCP and Non OCP clusters. The new section is additional steps and checks for registering Non OCP clusters.

2024-10-10 20:51 UTC, xiangjingli commented on gitops/gitops_registering.adoc
> +. Go to the API server URL in the non-{ocp-short} `ManagedCluster` spec and validate it by running the following command:
Yeah, it looks good to me

2024-10-10 20:56 UTC, xiangjingli commented on gitops/gitops_registering.adoc
> +When you integrate with the GitOps operator, for every managed cluster that is bound to the GitOps namespace through the placement and `ManagedClusterSetBinding` custom resources, a secret with a tok
a secret with a token to access the `ManagedCluster` is created in the namespace.
=============>
a secret with a token to access the `ManagedCluster` is created in the GitOps instance server namespace.

2024-10-11 14:17 UTC, oafischer commented on gitops/gitops_registering.adoc
> +You can now use the {acm-short} `GitOpsCluster` to register a non-{ocp-short} cluster to a GitOps cluster. With this capability, you can deploy application resources to the non-{ocp-short} cluster th
```suggestion
You can now use the {acm-short} `GitOpsCluster` to register a non-{ocp-short} cluster to a GitOps cluster. With this capability, you can deploy application resources to the non-{ocp-short} cluster by using the {gitops-short} UI. To register a non-{ocp-short} cluster to a GitOps cluster, complete the following steps:
```

Just removing some directional language

2024-10-11 14:18 UTC, oafischer commented on gitops/gitops_registering.adoc
> +NAME    HUB ACCEPTED   MANAGED CLUSTER URLS                                                      JOINED   AVAILABLE   AGE
This looks like an output? I assume it's not part of the command

2024-10-11 14:19 UTC, oafischer commented on gitops/gitops_registering.adoc
> +  - caBundle: ZW1wdHlDQWJ1bmRsZQo=                =====> this is a fake base64 encoded string "emptyCABundle"
Optional: We usually avoid comments in code samples. If it's a replaceable variable you can add a callout, otherwise I'd add any comments in a seperate Note tag.

2024-10-11 14:23 UTC, oafischer commented on gitops/gitops_registering.adoc
> +When you integrate with the GitOps operator, for every managed cluster that is bound to the GitOps namespace through the placement and `ManagedClusterSetBinding` custom resources, a secret with a tok
Optional: Might be worth separating since this paragraph is a little long.

2024-10-11 14:42 UTC, oafischer approved these changes
Feel free to address the comments as you see fit, I don't need to see this again so I'll approve for now.

2024-10-11 16:43 UTC, jc-berger commented on gitops/gitops_registering.adoc
> +  - caBundle: ZW1wdHlDQWJ1bmRsZQo=                =====> this is a fake base64 encoded string "emptyCABundle"
Thanks, Oliver, good catch! Looking more closely at it, I simply removed it, as I don't think this content is necessary. 

@xiangjingli if you thin they're particularly helpful to the user, I can add them back in, but as callouts, as Oliver suggested, thanks!

2024-10-11 20:21 UTC, xiangjingli commented on gitops/gitops_registering.adoc
> +  - caBundle: ZW1wdHlDQWJ1bmRsZQo=                =====> this is a fake base64 encoded string "emptyCABundle"
ok, it is good to simply remote it.  the caBundle content could be any valid base64 encoded string. Users won't hit any issue if they keep using our sample caBundle string.

2024-10-11 21:13 UTC, dockerymick commented on gitops/gitops_registering.adoc
> +== Registering non-_ocp-short_ clusters to GitOps
```suggestion
== Registering non-_{ocp-short}_ clusters to GitOps
```

2024-10-11 21:15 UTC, dockerymick commented on gitops/gitops_registering.adoc
> +----
Seems like there is a command and YAML snippet together. We usually separate these. Is the rest of the spec info intended to be presented in the command like this? 
```suggestion
.. To complete the API server URL, edit the `MangedCluster` resource `spec` by running the following command: 

+
[source,bash]
----
oc edit managedclusters eks-1
spec:
  managedClusterClientConfigs:
  - caBundle: ZW1wdHlDQWJ1bmRsZQo=          
    url: https://5E336C922AB16684A332C10535B8D407.gr7.us-east-2.eks.amazonaws.com
    cluster
----
```

2024-10-11 21:16 UTC, dockerymick commented on gitops/gitops_registering.adoc
> +[source,bash]
```suggestion
.. Save the changes then validate that the API server is completed by running the following command: 

+
[source,bash]
```

2024-10-11 21:18 UTC, dockerymick commented on gitops/gitops_registering.adoc
> +* With {acm-short} 2.12 or later, the API server URL for all types of non-{ocp-short} `ManagedCluster` renders automatically if you use the following importing modes:
```suggestion
. To verify that the cluster secret is generated, go to the `openshift-gitops` namespace and confirm that that `GitOpsCluster` resource status reports, `successful`. 
+
*Notes:* 

* With {acm-short} 2.12 or later, the API server URL for all types of non-{ocp-short} `ManagedCluster` renders automatically if you use the following importing modes:
```

2024-10-11 21:21 UTC, dockerymick commented on gitops/gitops_registering.adoc
> +== Registering non-_ocp-short_ clusters to GitOps
There was also an extra plus sign that appeared in the Registering managed clusters to GitOps section
<img width="1252" alt="Screenshot 2024-10-11 at 5 21 28 PM" src="https://github.com/user-attachments/assets/40f5c64d-d9e8-4534-ab7a-1b227f9fbf0b">

2024-10-11 21:27 UTC, dockerymick commented on release_notes/acm_whats_new.adoc
> +* You can now use the {acm-short} `GitOpsCluster` to register a non-{ocp-short} cluster to a GitOps cluster, giving you more ways to deploy your application. For more information, see: link:../gitops
Conref missing brackets
```suggestion
* You can now use the {acm-short} `GitOpsCluster` to register a non-{ocp-short} cluster to a GitOps cluster, giving you more ways to deploy your application. For more information, see: link:../gitops/gitops_registering.adoc#register-non-ocp[Registering non-_{ocp-short}_ clusters to GitOps].
```

2024-10-11 21:36 UTC, dockerymick commented on release_notes/acm_whats_new.adoc
> +* You can now use the {acm-short} `GitOpsCluster` to register a non-{ocp-short} cluster to a GitOps cluster, giving you more ways to deploy your application. For more information, see: link:../gitops
I saw @oafischer comment about removing "through" because it was directional. From my perspective through is acceptable. When I looked up directional language, words and phrases such as up, down, left, right, straight on, forward, backwards, turn around, next to, and in front appeared. I didn't see it specified in the IBM Style Guide though. I think this is worth bringing up with the team. There are many instances throughout the doc where we use "through"

2024-10-11 23:07 UTC, oafischer commented on release_notes/acm_whats_new.adoc
> +* You can now use the {acm-short} `GitOpsCluster` to register a non-{ocp-short} cluster to a GitOps cluster, giving you more ways to deploy your application. For more information, see: link:../gitops
Maybe directional is the wrong classification, but it definitely has an ambiguous meaning and can be difficult to translate. I usually avoid using it but we can definitely discuss it at our next meeting

2024-10-14 15:05 UTC, jc-berger commented on gitops/gitops_registering.adoc
> +[#register-non-ocp]
@dtthuynh or other QE reviewers, please let me know if you have concerns about me using the conref, `{gitops}`

2024-10-15 15:16 UTC, ruici-h commented on gitops/gitops_registering.adoc
> +[#register-non-ocp]
lgtm

2024-10-15 15:25 UTC, dockerymick commented on gitops/gitops_registering.adoc
> +[#register-non-ocp]
@ruici-h just a heads up, the value for the variable {gitops} is Red Hat OpenShift GitOps

2024-10-15 15:33 UTC, xiangjingli commented on gitops/gitops_registering.adoc
> +    cluster
@jc-berger  Just noticed the line 79 is not necessary. You can remove it

2024-10-15 16:35 UTC, ruici-h commented
/lgtm

2024-10-15 17:08 UTC, dockerymick requested changes

2024-10-15 17:08 UTC, dockerymick commented on gitops/gitops_registering.adoc
> +You can now use the {acm-short} `GitOpsCluster` to register a non-{ocp-short} cluster to a GitOps cluster. With this capability, you can deploy application resources to the non-{ocp-short} cluster by
every reference to GitOps should be replaced with the conref. We also do not use UI. If there are any other instances, please update it to read either console or write out user interface.
```suggestion
You can now use the {acm-short} `GitOpsCluster` to register a non-{ocp-short} cluster to a {gitops-short} cluster. With this capability, you can deploy application resources to the non-{ocp-short} cluster by using the {gitops-short} console. To register a non-{ocp-short} cluster to a {gitops-short} cluster, complete the following steps:
```

2024-10-15 17:08 UTC, dockerymick commented on gitops/gitops_registering.adoc
> +----
```suggestion
. Go to the API server URL in the non-{ocp-short} `ManagedCluster`  resource `spec` and validate it by running the following command.

+
[source,bash]
----
oc get managedclusters eks-1
----
+
You might receive the following output:

+
[source,bash]
----
NAME    HUB ACCEPTED   MANAGED CLUSTER URLS                                                      JOINED   AVAILABLE   AGE
eks-1   true           https://5E336C922AB16684A332C10535B8D407.gr7.us-east-2.eks.amazonaws.com  True     True        37m 
----
```

2024-10-15 17:08 UTC, dockerymick commented on gitops/gitops_registering.adoc
> +. If the API server URL in the non-{ocp-short} `MangedCluster` spec is empty, update it manually by completing the following steps:
```suggestion
. If the API server URL in the non-{ocp-short} `MangedCluster` resource `spec` is empty, update it manually by completing the following steps: 
```

2024-10-15 17:08 UTC, dockerymick commented on gitops/gitops_registering.adoc
> +  - caBundle: ZW1wdHlDQWJ1bmRsZQo=
It seems like there is a command and an example of the YAML. This should be separated. Similar to my previous suggestion on line 66

2024-10-15 17:08 UTC, dockerymick commented on gitops/gitops_registering.adoc
> +----
```suggestion
.. Save the changes then validate that the API server is completed by running the following command: 

+
[source,bash]
----
oc get managedclusters eks-1
----
+
You might receive the following output:

+
[source,bash]
----
NAME     HUB ACCEPTED  MANAGED CLUSTER URLS                                                      JOINED   AVAILABLE   AGE
eks-1    true          https://5E336C922AB16684A332C10535B8D407.gr7.us-east-2.eks.amazonaws.com  True     True        37m 
----
```

2024-10-15 17:08 UTC, dockerymick commented on gitops/gitops_registering.adoc
> +* With {acm-short} 2.12 or later, the API server URL for all types of non-{ocp-short} `ManagedCluster` renders automatically if you use the following importing modes:
```suggestion
* With {acm-short} 2.12 or later, the API server URL for all types of non-{ocp-short} `ManagedCluster` resources renders automatically if you use the following importing modes:
```

2024-10-15 17:08 UTC, dockerymick commented on gitops/gitops_registering.adoc
> +* The following cases can make the API server URL empty for one of the `ManagedClusters`:
```suggestion
* The following cases can make the API server URL empty for one of the `ManagedClusters` resources:
```

2024-10-15 17:08 UTC, dockerymick commented on gitops/gitops_registering.adoc
> +** The non-{ocp-short} cluster was imported to the {acm-short} hub before version 2.12.
Why don't we use the conref for the product version? 
```suggestion
** The non-{ocp-short} cluster is imported to the {acm-short} hub cluster before version 2.12. 
```

2024-10-15 17:08 UTC, dockerymick commented on gitops/gitops_registering.adoc
> +** The non-{ocp-short} cluster was manually imported to the {acm-short} hub in version 2.12 through the import mode, `Run import commands`.
```suggestion
** The non-{ocp-short} cluster is manually imported to the {acm-short} hub cluster in version 2.12 through the import mode, `Run import commands`. 
```

2024-10-15 17:08 UTC, dockerymick commented on gitops/gitops_registering.adoc
> +== GitOps token
As mentioned, each reference of GitOps should be replaced with the conref

2024-10-15 17:08 UTC, dockerymick commented on release_notes/acm_whats_new.adoc
> +* You can now use the {acm-short} `GitOpsCluster` to register a non-{ocp-short} cluster to a GitOps cluster, giving you more ways to deploy your application. For more information, see: link:../gitops
This entry should be in the ACM What's new section. I say this because GitOps is not apart of MCE to my knowledge. We can ask the doc channel for guidance and opinions

2024-10-15 19:23 UTC, dockerymick commented on gitops/gitops_registering.adoc
> +== Registering non-_{ocp-short}_ clusters to _{gitops}_
Why is the gitops conref italicized?

2024-10-15 19:23 UTC, dockerymick commented on gitops/gitops_registering.adoc
> +. Go to the API server URL in the non-{ocp-short} `ManagedCluster`  resource `spec` and validate it by running the following command:
there is an extra space before "resource"

2024-10-15 19:24 UTC, dockerymick commented on gitops/gitops_registering.adoc
> +.. Verify that your output resembles the following:
```suggestion
.. Verify that your YAML resembles the following file: 
```

2024-10-15 19:24 UTC, dockerymick commented on gitops/gitops_registering.adoc
> +. Verify that your output resembles the following:
```suggestion
. Verify that your output resembles the following information:
```

2024-10-15 19:24 UTC, jc-berger commented on gitops/gitops_registering.adoc
> +== Registering non-_{ocp-short}_ clusters to _{gitops}_
I thought we supposed to use _ _ instead of brackets in titles, lol 

Anyway, I did that to be consistent with the {ocp-short} conref that's italicized, I can remove it :)

2024-10-15 19:25 UTC, dockerymick commented on gitops/gitops_registering.adoc
> +.. Verify that your output resembles the following:
```suggestion
.. Verify that your output resembles the following information: 
```

2024-10-15 19:25 UTC, dockerymick commented on gitops/gitops_registering.adoc
> +== _{gitops}_ token
not sure why this is italicized now

2024-10-15 19:25 UTC, dockerymick commented on gitops/gitops_registering.adoc
> +When you integrate with the {gitops} operator, for every managed cluster that is bound to the {gitops} namespace through the placement and `ManagedClusterSetBinding` custom resources, a secret with a
there is also a {gitops-short} conref. After you use the full.

2024-10-15 19:27 UTC, dockerymick commented on gitops/gitops_registering.adoc
> +== Registering non-_{ocp-short}_ clusters to _{gitops}_
The brackets are required for the variable to work in the product

2024-10-15 22:28 UTC, dockerymick commented on gitops/gitops_registering.adoc
>  See the link:../clusters/cluster_lifecycle/create_clusterset.adoc#creating-a-managedclusterset[Creating a _ManagedClusterSet_] documentation for more information.
Can you check if this should be a prereq? The link interrupts the steps.

i know this isn't apart of the changes you made, but will you also update other instances of GitOps by using the conref? I see OpenShift GitOps in the title and on line 4. Please also update this statement: "To configure GitOps with the Push model, you can register a set of one or more {acm} managed clusters to an instance of {ocp} GitOps operator." 

TO

To configure {gitops} with the Push model, you can register a set of one or more {acm} managed clusters to an instance of {gitops-short} operator.

2024-10-15 22:28 UTC, dockerymick commented on release_notes/acm_whats_new.adoc
> +* You can now use the {acm-short} `GitOpsCluster` to register a non-{ocp-short} cluster to a {gitops} cluster, giving you more ways to deploy your application. For more information, see: link:../gito
```suggestion
* You can now use the {acm-short} `GitOpsCluster` to register a non-{ocp-short} cluster to a {gitops} cluster, giving you more ways to deploy your application. For more information, see: link:../gitops/gitops_registering.adoc#register-non-ocp[Registering non-{ocp-short} clusters to {gitops}].
```

2024-10-16 19:39 UTC, dockerymick approved these changes
Few more suggestions. Please check the suggestions before merging

2024-10-16 19:39 UTC, dockerymick commented on gitops/gitops_registering.adoc
> +. In the namespace that is used in managed cluster set binding, create a `Placement` custom resource to select a set of managed clusters to register to an {ocp-short} {gitops-short} operator instance
The ocp conref isn't required here since the value for {gitops} is Red Hat OpenShift GitOps
```suggestion
. In the namespace that is used in managed cluster set binding, create a `Placement` custom resource to select a set of managed clusters to register to an {gitops-short} operator instance. Use the `multicloud-integration` placement example as a template. See _Using ManagedClusterSets with Placement_ for placement information. 
```

2024-10-16 19:39 UTC, dockerymick commented on gitops/gitops_registering.adoc
> +- Only {ocp-short} clusters are registered to an {ocp} {gitops-short}  operator instance, not other Kubernetes clusters.
```suggestion
- Only {ocp-short} clusters are registered to an {gitops-short}  operator instance, not other Kubernetes clusters.
```

2024-10-16 19:39 UTC, dockerymick commented on gitops/gitops_registering.adoc
> +You can now use the {acm-short} `GitOpsCluster` to register a non-{ocp-short} cluster to a {gitops-short} cluster. With this capability, you can deploy application resources to the non-{ocp-short} cl
```suggestion
You can now use the {acm-short} `GitOpsCluster` resource to register a non-{ocp-short} cluster to a {gitops-short} cluster. With this capability, you can deploy application resources to the non-{ocp-short} cluster by using the {gitops-short} console. To register a non-{ocp-short} cluster to a {gitops-short} cluster, complete the following steps:
```

2024-10-16 19:39 UTC, dockerymick commented on gitops/gitops_registering.adoc
> +The {gitops-short} controller needs this secret to sync resources to the managed cluster. By default, the service account application manager works with the cluster admin permissions on the managed c
```suggestion
The {gitops-short} controller needs this secret to sync resources to the managed cluster. By default, the service account application manager works with the cluster administrator permissions on the managed cluster to generate the {gitops-short} cluster secret in the {gitops-short} instance server namespace. The default namespace is `openshift-gitops`. 
```

2024-10-16 20:02 UTC, merged