https://issues.redhat.com/browse/ACM-14521
open-cluster-management/rhacm-docs pull request #7067
Opened 2024-10-14 18:42 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-14521

2024-10-15 13:40 UTC, birsanv commented on business_continuity/backup_restore/backup_restore.adoc
> +[source,yaml]
The sample should be


apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Restore
metadata:
  name: restore-filter-sample
  namespace: open-cluster-management-backup
spec:
  cleanupBeforeRestore: None 
  veleroCredentialsBackupName: latest 
  veleroResourcesBackupName: latest  
  veleroManagedClustersBackupName: latest 
  excludedResources:
    - ManagedCluster
  orLabelSelectors:
    - matchExpressions:
        - values:
            - vb-managed-cls-2
          key: name
          operator: In

2024-10-15 13:41 UTC, birsanv commented on business_continuity/backup_restore/backup_restore.adoc
> +
Add this section : 

You can set the following velero restore spec options when creating the ACM restore resource:
  includedResources
  includedNamespaces
  excludedResources
  excludedNamespaces
  LabelSelector
  OrLabelSelector

2024-10-15 13:42 UTC, birsanv requested changes
please update sample and add the list of filters

2024-10-15 13:43 UTC, birsanv approved these changes
lgtm

2024-10-15 13:43 UTC, birsanv requested changes
sorry, need to make requested updates

2024-10-15 15:44 UTC, birsanv approved these changes
lgtm

2024-10-15 18:38 UTC, dockerymick requested changes

2024-10-15 18:38 UTC, dockerymick commented on business_continuity/backup_restore/backup_restore.adoc
> +**  The `restore.cluster.open-cluster-management.io` resource is still active if the phase is `Enabled` or `Running`. The resource execution is completed if the phase changes to `Finished`. After the
Can we use a different word than "execution"?

2024-10-15 18:38 UTC, dockerymick commented on business_continuity/backup_restore/backup_restore.adoc
> +* Use the advanced options with velero restore to filer out resources you want to restore. Use the following sample with velero restore spec options to restore resources only from the `vb-managed-cis
Is velero supposed to be capital ? Or are you referencing a resource? spec should also be monospaced or you should write out specification

2024-10-15 18:38 UTC, dockerymick commented on business_continuity/backup_restore/backup_restore.adoc
> +* Set the following velero restore spec options when you create the {acm-short} restore resource:
Same thing here, is velero suppose to be capital?

2024-10-15 18:38 UTC, dockerymick commented on business_continuity/backup_restore/backup_restore.adoc
> +----
Should `spec` be added to this YAML snippet?

2024-10-15 18:38 UTC, dockerymick commented on business_continuity/backup_restore/backup_restore.adoc
> +** When you set any of these velero restore filters, set the `cleanupBeforeRestore` to `None` to avoid cleaning up hub resources that are part of the restored backup but are not being restored becaus
Should velero be capitalized. Reminder to write hub cluster

2024-10-15 18:38 UTC, dockerymick commented on release_notes/acm_whats_new.adoc
> +* With {acm-short} restore resources, you can set more velero restore spec options. See link:../business_continuity/backup_restore/backup_restore.adoc#more-restore-samples[Using other restore samples
Since you are mentioning resources, should restore be capitalized?

2024-10-15 18:53 UTC, birsanv commented on business_continuity/backup_restore/backup_restore.adoc
> +* Use the advanced options with velero restore to filer out resources you want to restore. Use the following sample with velero restore spec options to restore resources only from the `vb-managed-cis
we can say velero.io.restore

2024-10-15 18:53 UTC, birsanv commented on business_continuity/backup_restore/backup_restore.adoc
> +* Set the following velero restore spec options when you create the {acm-short} restore resource:
we can say velero.io.restore

2024-10-15 18:53 UTC, birsanv commented on business_continuity/backup_restore/backup_restore.adoc
> +** When you set any of these velero restore filters, set the `cleanupBeforeRestore` to `None` to avoid cleaning up hub resources that are part of the restored backup but are not being restored becaus
yes, Velero is the product name

2024-10-15 22:32 UTC, dockerymick requested changes

2024-10-15 22:32 UTC, dockerymick commented on business_continuity/backup_restore/backup_restore.adoc
> +* Use the advanced options with `velero.io.restore` to filer out resources you want to restore. Use the following sample with `velero.io.restore` spec options to restore resources only from the `vb-m
```suggestion
* Use the advanced options with `velero.io.restore` to filer out resources you want to restore. Use the following sample with `velero.io.restore` `spec` options to restore resources only from the `vb-managed-cis-2` managed cluster namespace and to exclude global `MultiCluster` resources: 
```

2024-10-15 22:32 UTC, dockerymick commented on business_continuity/backup_restore/backup_restore.adoc
> +* Set the following `velero.io.restore` spec options when you create the {acm-short} restore resource:
```suggestion
* Set the following `velero.io.restore` `spec` options when you create the {acm-short} restore resource: 
```

2024-10-15 22:32 UTC, dockerymick commented on release_notes/acm_whats_new.adoc
> +* With {acm-short} restore resources, you can set more `velero.io.restore` spec options. See link:../business_continuity/backup_restore/backup_restore.adoc#more-restore-samples[Using other restore sa
```suggestion
* With {acm-short} restore resources, you can set more `velero.io.restore` `spec` options. See link:../business_continuity/backup_restore/backup_restore.adoc#more-restore-samples[Using other restore samples].
```

2024-10-16 17:11 UTC, birsanv commented on business_continuity/backup_restore/backup_restore.adoc
> +* Use the advanced options with `velero.io.restore` to filer out resources you want to restore. Use the following sample with `velero.io.restore` `spec` options to restore resources only from the `vb
this is a typo: it should be vb-managed-cls-2, not vb-managed-cis-2

2024-10-16 17:26 UTC, birsanv approved these changes
lgtm

2024-10-16 17:44 UTC, dockerymick approved these changes
Thanks, this looks good to me

2024-10-16 19:51 UTC, merged