https://issues.redhat.com/browse/ACM-14947
open-cluster-management/rhacm-docs pull request #7092
Opened 2024-10-17 16:05 UTC by jc-berger

Fix incorrect content. See Jira: https://issues.redhat.com/browse/ACM-14947

2024-10-17 16:07 UTC, jc-berger commented on business_continuity/backup_restore/use_existing_hub_cluster.adoc
> +* If the `ManagedCluster` resources were created by a restored backup, then these resources have the `velero.io/backup-name: backupName` label annotation set. If the user runs a restore operation and
@birsanv of course I want to maintain your original content and its technical accuracy. 

Looking at the Jira, I see the Doc review wants the bullets more user focused and concise. 

Please let me know what you think of this current rewrite, where we say what the earlier users of the managed clusters did, while telling our users/reader of this doc what to expect.

2024-10-17 17:28 UTC, birsanv requested changes

2024-10-17 17:28 UTC, birsanv commented on business_continuity/backup_restore/use_existing_hub_cluster.adoc
> +* If the `ManagedCluster` resources were created by a restored backup, then these resources have the `velero.io/backup-name: backupName` label annotation set. If the user runs a restore operation and
@jc-berger I really like your update ! exactly what I meant

Still one change : 
This : 
expect the managed clusters to detach and no longer be part of the current restored backup.

Should say: 

expect the managed clusters to be detached from the cluster hub and workloads to be cleaned up on these managed clusters.

2024-10-17 19:47 UTC, birsanv approved these changes
lgtm

2024-10-18 18:39 UTC, dockerymick requested changes

2024-10-18 18:39 UTC, dockerymick commented on business_continuity/backup_restore/use_existing_hub_cluster.adoc
> +* If the user created the `ManagedCluster` resources, then these resources do not have the `velero.io/backup-name: backupName` label annotation set. If the user runs a restore operation and uses the
Are we saying "user" because anyone can run the restore operation? Is there a reason why we should say "user" instead of using "you" (second person according to IBM Style guide)? https://www.ibm.com/docs/en/ibm-style?topic=medium-tone

```suggestion
* If the `ManagedCluster` resources are created by a restored backup, then the resources have the `velero.io/backup-name: backupName` label annotation set. If a user runs a restore operation and uses the `cleanupBeforeRestore=CleanupRestored` option, the managed clusters are detached from the hub cluster and workloads are cleaned up on these managed clusters.
* If a user created the `ManagedCluster` resources, then the resources do not have the `velero.io/backup-name: backupName` label annotation set. If a user runs a restore operation and uses the `cleanupBeforeRestore=CleanupRestored` option, the managed cluster resources are not cleaned up even if they are not part of the current restored backup. 
```

2024-10-18 18:53 UTC, birsanv commented on business_continuity/backup_restore/use_existing_hub_cluster.adoc
> +* If the user created the `ManagedCluster` resources, then these resources do not have the `velero.io/backup-name: backupName` label annotation set. If the user runs a restore operation and uses the
looks good @dockerymick

2024-10-18 18:58 UTC, dockerymick commented on business_continuity/backup_restore/use_existing_hub_cluster.adoc
> +* If the user created the `ManagedCluster` resources, then these resources do not have the `velero.io/backup-name: backupName` label annotation set. If the user runs a restore operation and uses the
@birsanv is it ok if we say "you" instead of "a/the user"?

2024-10-18 19:04 UTC, birsanv commented on business_continuity/backup_restore/use_existing_hub_cluster.adoc
> +* If the user created the `ManagedCluster` resources, then these resources do not have the `velero.io/backup-name: backupName` label annotation set. If the user runs a restore operation and uses the
@dockerymick 
for this I think we should stick with `a user` ( because it can be any other user , not the one trying to run the restore operation )
If **a user** created the `ManagedCluster` resources, then the resources do not have the `velero.io/backup-name: backupName` label annotation set.

For this I think we can use 'you' since it's about the current operation
If a user runs a restore... ( If **you** run a restore .. )

2024-10-21 14:47 UTC, dockerymick commented on business_continuity/backup_restore/use_existing_hub_cluster.adoc
> +* If a user created the `ManagedCluster` resources, then the resources do not have the `velero.io/backup-name: backupName` label annotation set. If you run a restore operation and use the `cleanupBef
```suggestion
* If a user created the `ManagedCluster` resources, then the resources do not have the `velero.io/backup-name: backupName` label annotation set. If you run a restore operation and use the `cleanupBeforeRestore=CleanupRestored` option, the managed cluster resources are not cleaned up even if the resources are not part of the current restored backup. 
```

2024-10-21 14:48 UTC, dockerymick approved these changes

2024-10-21 14:51 UTC, merged