https://issues.redhat.com/browse/ACM-13460
open-cluster-management/rhacm-docs pull request #7093
Opened 2024-10-17 16:38 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-13460

2024-10-17 17:24 UTC, birsanv requested changes

2024-10-17 17:24 UTC, birsanv commented on business_continuity/backup_restore/backup_arch.adoc
> +- Back up all resources from: `argoproj.io`, `app.k8s.io`, `core.observatorium.io`, `hive.openshift.io`. These resources are backed up within the `acm-resources-schedule` backup, with the exception o
looks good, one typo : `**}}{{**acm-managed-clusters-schedule` should be `acm-managed-clusters-schedule`

2024-10-18 18:46 UTC, dockerymick requested changes

2024-10-18 18:46 UTC, dockerymick commented on business_continuity/backup_restore/backup_arch.adoc
> +- Back up all resources from: `argoproj.io`, `app.k8s.io`, `core.observatorium.io`, `hive.openshift.io`. These resources are backed up within the `acm-resources-schedule` backup, with the exception o
Are these domains, API groups, or resources? @birsanv @jc-berger 
```suggestion
- Back up all resources from the following API groups: `argoproj.io`, `app.k8s.io`, `core.observatorium.io`, `hive.openshift.io`. The resources are backed up within the `acm-resources-schedule` backup, with the exception of the resources from the `agent-install.openshift.io` API group. Resources from the `agent-install.openshift.io` API group are backed up within the `acm-managed-clusters-schedule` backup. The following `hive.openshift.io` and `hiveinternal.openshift.io` resources are also backed up by the `**}}{{**acm-managed-clusters-schedule should be acm-managed-clusters-schedule` backup: 
```

Based on the answer of my previous question:

```suggestion
- Back up all resources from the following API groups: `argoproj.io`, `app.k8s.io`, `core.observatorium.io`, `hive.openshift.io`. The resources are backed up within the `acm-resources-schedule` backup, with the exception of the resources from the `agent-install.openshift.io` API group. Resources from the `agent-install.openshift.io` API group are backed up within the `acm-managed-clusters-schedule` backup. The following resources from `hive.openshift.io` and `hiveinternal.openshift.io` API groups are also backed up by the `**}}{{**acm-managed-clusters-schedule` and the `acm-managed-clusters-schedule` backup: 
```

2024-10-18 19:00 UTC, birsanv commented on business_continuity/backup_restore/backup_arch.adoc
> +- Back up all resources from: `argoproj.io`, `app.k8s.io`, `core.observatorium.io`, `hive.openshift.io`. These resources are backed up within the `acm-resources-schedule` backup, with the exception o
@dockerymick `hiveinternal.openshift.io` is api group, clusterdeployment.hive.openshift.io is resource

btw, this is incorrect ( the addition of the and the `acm-managed-clusters-schedule` backup )

Incorrect
.. API groups are also backed up by the `**}}{{**acm-managed-clusters-schedule` **and the `acm-managed-clusters-schedule`** backup:

Should be
..API groups are also backed up by the `acm-managed-clusters-schedule`  backup:

2024-10-18 19:05 UTC, dockerymick commented on business_continuity/backup_restore/backup_arch.adoc
> +- Back up all resources from: `argoproj.io`, `app.k8s.io`, `core.observatorium.io`, `hive.openshift.io`. These resources are backed up within the `acm-resources-schedule` backup, with the exception o
Thanks for clarifying, I wasn't sure what the `**}}{{**` was for

2024-10-18 19:07 UTC, birsanv commented on business_continuity/backup_restore/backup_arch.adoc
> +- Back up all resources from: `argoproj.io`, `app.k8s.io`, `core.observatorium.io`, `hive.openshift.io`. These resources are backed up within the `acm-resources-schedule` backup, with the exception o
it was a typo .. :)

2024-10-21 14:43 UTC, dockerymick approved these changes

2024-10-21 14:51 UTC, merged