https://issues.redhat.com/browse/ACM-13207
open-cluster-management/rhacm-docs pull request #7094
Opened 2024-10-17 16:46 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-13207

2024-10-17 17:21 UTC, birsanv requested changes

2024-10-17 17:21 UTC, birsanv commented on business_continuity/backup_restore/backup_schedule.adoc
> +* If the hub cluster changes status from a passive to primary hub cluster, or from a primary to passive hub cluster.
This is not correct, it implies the collision happens If the hub cluster changes status. That is not enough.
If the hub cluster changes status AND other hub clusters back up data at the same storage location.

Can we keep the initial content ? Replace 94-97 with the proposed : 
 _Backup collisions might occur if the hub cluster changes status from passive to primary hub cluster, or from primary to passive, and different hub clusters back up data at the same storage location._

( note that line 99 is a continuation of this sentence; that will not make sense with these changes )

2024-10-17 19:45 UTC, birsanv approved these changes
lgtm

2024-10-18 17:23 UTC, dockerymick approved these changes

2024-10-18 17:56 UTC, merged