https://issues.redhat.com/browse/ACM-14456
open-cluster-management/rhacm-docs pull request #7162
Opened 2024-10-23 15:53 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-14456

2024-10-23 15:54 UTC, jc-berger commented on business_continuity/backup_restore/backup_hub_config.adoc
> +- Process 2 in the earlier diagram is manual. If the administrator does not create a backup schedule on the new primary hub cluster, the `backup-restore-enabled policy` shows a violation, using the `
Dev reviewers

Am I correct that the template validates the primary hub cluster?

2024-10-23 15:55 UTC, jc-berger commented on business_continuity/backup_restore/backup_hub_config.adoc
> +- Process 2 in the earlier diagram is manual. If the administrator does not create a backup schedule on the new primary hub cluster, the `backup-restore-enabled policy` shows a violation, using the `
Dev reviewers:

Am I correct the `:aap:` job automates the cron job? 

The original content said `automates this step` and I wasn't sure what the `step` was referring to.

2024-10-23 16:01 UTC, birsanv requested changes

2024-10-23 16:01 UTC, birsanv commented on business_continuity/backup_restore/backup_hub_config.adoc
> +- Process 2 in the earlier diagram is manual. If the administrator does not create a backup schedule on the new primary hub cluster, the `backup-restore-enabled policy` shows a violation, using the `
small typo 

1. `backup-restore-enabled policy` should be:  `backup-restore-enabled` policy
2. `a`cm-validation-policy-schedule` template should be:  `backup-schedule-cron-enabled` policy template
3. The administrators can also use the policy integration with `:aap:` jobs should be: The administrators can also use the policy integration with `Ansible` jobs

2024-10-23 17:13 UTC, birsanv requested changes

2024-10-23 17:13 UTC, birsanv commented on business_continuity/backup_restore/backup_hub_config.adoc
> +- Process 2 in the earlier diagram is manual. If the administrator does not create a backup schedule on the new primary hub cluster, the `backup-restore-enabled` policy shows a violation, using the `
This is incorrect : The administrators can also use the policy integration with `Ansible` jobs to automate _the cron job_ by making it run when the template reports violations.

What I was trying to say :  an ansible job ( and not the above mentioned cron job ) would run when the template reports a violation

Suggestion to change : The administrator can use the policy integration with Ansible and define an Ansible job, which would run when the `backup-schedule-cron-enabled` template reports violation.

2024-10-23 18:53 UTC, birsanv approved these changes
lgtm

2024-10-23 19:45 UTC, swopebe commented on business_continuity/backup_restore/backup_hub_config.adoc
> +- Process 1 in the earlier diagram is not automated because the administrator must decide if the primary hub cluster has failed and needs to be replaced, or if there is a network communication error
Previous

2024-10-23 19:46 UTC, swopebe commented on business_continuity/backup_restore/backup_hub_config.adoc
> +- Process 2 in the earlier diagram is manual. If the administrator does not create a backup schedule on the new primary hub cluster, the `backup-restore-enabled` policy shows a violation, using the `
Previous, can I ask why we changed this? We typically use previous.

2024-10-23 19:48 UTC, swopebe commented on business_continuity/backup_restore/backup_hub_config.adoc
> +- Process 1 in the earlier diagram is not automated because the administrator must decide if the primary hub cluster has failed and needs to be replaced, or if there is a network communication error
For numbers, unless you are referencing something in code or the UI that would be coded, please follow the "under 10 use the word" rule:

https://www.ibm.com/docs/en/ibm-style?topic=measurement-numerals-versus-words

2024-10-23 19:50 UTC, swopebe commented on business_continuity/backup_restore/backup_hub_config.adoc
> +- Process 2 in the earlier diagram is manual. If the administrator does not create a backup schedule on the new primary hub cluster, the `backup-restore-enabled` policy shows a violation, using the `
I have a question about why we are going with "the administrator" and not sticking with the voice and tone of the doc that is user-centered?

2024-10-23 19:53 UTC, swopebe commented on business_continuity/backup_restore/backup_hub_config.adoc
> +- Process 2 in the earlier diagram is manual. If the administrator does not create a backup schedule on the new primary hub cluster, the `backup-restore-enabled` policy shows a violation, using the `
This is feedback for most of the B and R doc. We should break up the walls of text here. There are many lines here that need to be pulled out of this paragraph. We have gone over the feedback from the content strategists where users complain about the long paragraphs. Generally we want our content chunked up in to smaller bits of information.

2024-10-23 19:58 UTC, swopebe commented on business_continuity/backup_restore/backup_hub_config.adoc
> +- Process 2 in the earlier diagram is manual. If the administrator does not create a backup schedule on the new primary hub cluster, the `backup-restore-enabled` policy shows a violation, using the `
I will work on Process 1 to see how we can reduce these paragraphs for both UX and accessibility. This is just general industry standards, but also covered in various places in the manuals that we can look at.

2024-10-23 20:07 UTC, swopebe commented on business_continuity/backup_restore/backup_hub_config.adoc
> +- Process 2 in the earlier diagram is manual. If the administrator does not create a backup schedule on the new primary hub cluster, the `backup-restore-enabled` policy shows a violation, using the `
Please see the changes to the first process paragraph.

2024-10-23 20:23 UTC, swopebe commented on business_continuity/backup_restore/backup_hub_config.adoc
> +- Process 2 in the earlier diagram is manual. If the administrator does not create a backup schedule on the new primary hub cluster, the `backup-restore-enabled` policy shows a violation, using the `
Check IBM Style manual for common terms, words, and practices:

[Use of **earlier** is here](https://www.ibm.com/docs/en/ibm-style?topic=word-usage). This is why we use previous, but also, naming the image is beneficial for UX:

**Preferred earlier adverb
Use to refer to a previous software version or fix level.**

 I almost daily review something in these manuals...I find them very helpful.

2024-10-23 20:24 UTC, swopebe requested changes
https://github.com/stolostron/rhacm-docs/pull/7162/files#r1813463501

2024-10-24 18:21 UTC, birsanv commented on business_continuity/backup_restore/backup_hub_config.adoc
> +When the primary hub cluster fails, if you have administration qualifications, you can select a passive hub cluster to take over the managed clusters. In the following _Disaster recovery diagram_, se
I think it's better to say : as a hub administrator
instead of : if you have administration qualifications

There is no description of administration qualifications in the docs.. this would be confusing

2024-10-24 18:43 UTC, birsanv approved these changes
lgtm

2024-10-24 21:27 UTC, swopebe commented on business_continuity/backup_restore/backup_hub_config.adoc
> +* You can use the `backup-schedule-cron-enabled` policy template to validate if the new primary hub cluster has backups running as a cron job.
Just a question should like 40 and the one after be sub bullets...if they were all originally part of the second process?

2024-10-25 15:18 UTC, jc-berger commented on business_continuity/backup_restore/backup_hub_config.adoc
> +* You can use the `backup-schedule-cron-enabled` policy template to validate if the new primary hub cluster has backups running as a cron job.
@swopebe great question :) Meeting with Valentina, she said line 40, using a backup scheduled cron enabled policy template to validate, is more of a separate user action. She and I were thinking if it's a sub bullet, it might be construed that users can only do this _if_ they did not create a backup schedule on the new primary hub cluster. 

What do you think?

2024-10-25 17:26 UTC, swopebe commented on business_continuity/backup_restore/backup_hub_config.adoc
> +* You can use the `backup-schedule-cron-enabled` policy template to validate if the new primary hub cluster has backups running as a cron job.
@jc-berger I am asking this because originally, that content was in one paragraph. If you see what I changed above, I pulled out the important information from the first paragraph and made them sub bullets.

You have two processes here described in a paragraph. Now we have the first process described with sub bullets. You have the second process no longer connected.

2024-10-25 17:31 UTC, swopebe commented on business_continuity/backup_restore/backup_hub_config.adoc
> +* You can use the `backup-schedule-cron-enabled` policy template to validate if the new primary hub cluster has backups running as a cron job.
So now this is confusing. 

The first process in the earlier Disaster recovery diagram is not automated because of the following reasons:

- sub bullets


**Original:** 

- Process 1 in the previous diagram is not automated because the administrator must decide if the primary hub cluster has failed and needs to be replaced, or if there is a network communication error between the hub cluster and the managed clusters. The administrator also decides which passive hub cluster becomes the primary hub cluster. The policy integration with :aap: jobs can help you automate this step by making a job run when the backup policy reports backup errors. 

Please notice that I pulled out the important info from the first process, introduced with with a basic line.

Looking for a similar format for the second process.

2024-10-25 17:35 UTC, swopebe commented on business_continuity/backup_restore/backup_hub_config.adoc
> +* You can use the `backup-schedule-cron-enabled` policy template to validate if the new primary hub cluster has backups running as a cron job.
This is the original paragraph for process 2:

`Process 2 in the earlier diagram is manual. If the administrator does not create a backup schedule on the new primary hub cluster, the `backup-restore-enabled` policy shows a violation, using the `backup-schedule-cron-enabled` policy template. The administrator can use this template to validate if the new primary hub cluster has backups running as a cron job. The administrators can also use the policy integration with `Ansible` and define an `Ansible` job that can run when the `backup-schedule-cron-enabled` policy template reports violations. For more details about the `backup-restore-enabled` policy templates, see xref:../backup_restore/backup_validate.adoc#backup-validation-using-a-policy[Validating your backup or restore configurations].  `

It's too large and needs some structure, but the info still pertains to the second process.

2024-10-25 17:38 UTC, swopebe commented on business_continuity/backup_restore/backup_hub_config.adoc
> +* You can use the `backup-schedule-cron-enabled` policy template to validate if the new primary hub cluster has backups running as a cron job.
The content does not change here, just how it is delivered by the writer.

2024-10-25 17:40 UTC, swopebe commented on business_continuity/backup_restore/backup_hub_config.adoc
> +* You can use the `backup-schedule-cron-enabled` policy template to validate if the new primary hub cluster has backups running as a cron job.
If these bullets are all peers, then we are no longer presenting Process 1 info, then Process 2 info.

2024-10-25 17:42 UTC, swopebe commented on business_continuity/backup_restore/backup_hub_config.adoc
> +* You can use the `backup-schedule-cron-enabled` policy template to validate if the new primary hub cluster has backups running as a cron job.
![preview](https://github.com/user-attachments/assets/aa9b2d83-c69e-4067-806c-c8fac9dd9dde)

2024-10-25 18:05 UTC, birsanv approved these changes
lgtm

2024-10-25 18:06 UTC, jc-berger commented on business_continuity/backup_restore/backup_hub_config.adoc
> +* You can use the `backup-schedule-cron-enabled` policy template to validate if the new primary hub cluster has backups running as a cron job.
@swopebe thanks, Brandi! Please see my revisions which have been re-approved by Valentina, thanks!

2024-10-25 18:18 UTC, swopebe commented on business_continuity/backup_restore/backup_hub_config.adoc
> +* You can use the `backup-schedule-cron-enabled` policy template to validate if the new primary hub cluster has backups running as a cron job.
Ok, so it seems we are sticking with main bullet- sub bullet for descriptions.

2024-10-25 18:24 UTC, swopebe commented on business_continuity/backup_restore/backup_hub_config.adoc
> +** Use the `backup-schedule-cron-enabled` policy template to validate if the new primary hub cluster has backups running as a cron job.
I will approve not to hold this us, but I just caught this now (since now it is easier to read):

If you did not create a backup schedule on the new primary hub cluster, the `backup-restore-enabled` policy shows a violation**,** (last fix: not sure if this should be **"by using"** and remove the comma, or what the comma is for otherwise. I think we mean "by using" and the comma is not needed/confusing, ) **using** the `backup-schedule-cron-enabled` policy template.

Please see standard about using "by using." This is industry standard for globalization, especially and in the IBM style guide:

```
Use with caution using noun
To avoid ambiguity, replace this gerund with either **by using** or **that uses.**

To refer to something using one thing or another is often ambiguous. For example, the sentence Back up the server using ABC might mean Back up the server **by using** ABC or Back up the server **that uses** ABC. **This advice also applies to gerunds other than using.** 

For more information, see the style and grammar tips in the [Global audiences](https://www.ibm.com/docs/en/ibm_style/global-audiences.html) topic in IBM Style.
```

2024-10-25 18:25 UTC, swopebe approved these changes
Please see comment on line 39.

2024-10-25 18:31 UTC, swopebe commented on business_continuity/backup_restore/backup_hub_config.adoc
> +** Use the `backup-schedule-cron-enabled` policy template to validate if the new primary hub cluster has backups running as a cron job.
`the `backup-restore-enabled` policy shows a violation by using the `backup-schedule-cron-enabled` policy template.`

?

2024-10-25 18:33 UTC, merged