https://issues.redhat.com/browse/ACM-15075
open-cluster-management/rhacm-docs pull request #7180
Opened 2024-10-24 17:15 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-15075

See Dev PR where I took this content: https://github.com/stolostron/rhacm-docs/pull/7177/files

2024-10-24 17:16 UTC, jc-berger commented on release_notes/acm_known_issues_intro.adoc
> +* xref:../release_notes/known_issues_network.adoc#known-issues_submariner[Networking known issues]
Looking at the newtorking doc, they use the anchor, #known-issue_submariner , so that's what I used here.

2024-10-24 17:16 UTC, jc-berger commented on release_notes/known_issues_global.adoc
> +If you installed your {mce-short} into a customized namespace, then you cannot enable the {global-hub} search, because in this case, the search operator failed to add the `globalSearchFeatureFlag`.
Dev reviewers:

Please let em know if I am correct that this is a result of the user action -- if the user installed the mce short into the customized namespace, and then, the user cannot enable the global hub serach.

2024-10-24 17:17 UTC, jc-berger commented on release_notes/known_issues_global.adoc
> +[#search-not-enabled]
Dev reviewers:

Looking at the original PR, I shortened the anchor to make it a bit easier to find. And typically, we want the latest known issues at the top of the doc, instead of the bottom. Let me know what you think :)

2024-10-24 17:18 UTC, jc-berger commented on release_notes/known_issues_global.adoc
> +There is currently no workaround for this issue.
Correct me if there are in fact workaround steps we can provide users, thanks!

2024-10-24 18:19 UTC, jlpadilla commented on release_notes/known_issues_global.adoc
> +There is currently no workaround for this issue.
Workaround is to manually patch the console-mce-config ConfigMap in the correct namespace.

```
oc patch configmap console-mce-config -n {{MCE_NAMESPACE}} -p '{"data": {"globalSearchFeatureFlag": "enabled"}}'
```

2024-10-25 07:09 UTC, hchenxa commented on release_notes/known_issues_global.adoc
> +If you installed your {mce-short} into a customized namespace, then you cannot enable the {global-hub} search, because in this case, the search operator failed to add the `globalSearchFeatureFlag`.
yes, the search operator will failed to update the console-mce-config configmap by adding the `globalSearchFeatureFlag=true`.

2024-10-25 18:34 UTC, dockerymick requested changes

2024-10-25 18:34 UTC, dockerymick commented on release_notes/known_issues_global.adoc
> +== The {global-hub} search is not enabled
```suggestion
== The {global-hub} Search is not enabled 
```

2024-10-25 18:34 UTC, dockerymick commented on release_notes/known_issues_global.adoc
> +If you installed your {mce-short} into a customized namespace, then you cannot enable the {global-hub} search. In this case, the search operator fails to update the `console-mce-config` config map be
```suggestion
If you installed your {mce-short} into a customized namespace, then you cannot enable the {global-hub} Search. In this case, the search operator fails to update the `console-mce-config` config map because the `globalSearchFeatureFlag=true` flag is added, preventing you from enabling the {global-hub} Search.
```

2024-10-25 18:34 UTC, dockerymick commented on release_notes/known_issues_global.adoc
> +----
```suggestion
[source,bash]
----
oc patch configmap console-mce-config -n {{MCE_NAMESPACE}} -p '{"data": {"globalSearchFeatureFlag": "enabled"}}'
----
```

2024-10-28 14:24 UTC, merged