https://issues.redhat.com/browse/ACM-14686
open-cluster-management/rhacm-docs pull request #7189
Opened 2024-10-28 16:30 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-14686

2024-10-28 16:31 UTC, jc-berger commented on troubleshooting/trouble_submariner_tests.adoc
> +If the test succeeds with this small packet size, you can prevent more test failures by using Submariner to customize the transmission control protocol (TCP) minimum security standards (MSS) `clampin
Dev and QA reviewers, reading the Jira, I understood this customization as a way to prevent further end to end test failures, please correct me if I am wrong.

2024-10-28 16:32 UTC, jc-berger commented on troubleshooting/trouble_submariner_tests.adoc
> +After running Submariner end-to-end tests, you might get failures. Use the following sections to help you troubleshoot these end-to-end test failures.
Dev and QA reviewers, 

There were a lot of acronyms I was unfamiliar with. Please correct me if I was wrong about any of their full names and titles.

2024-10-28 16:32 UTC, jc-berger commented on troubleshooting/trouble_submariner_tests.adoc
> +. Set the MSS `clamping` value set by annotating the `GW` node. For example, run the following command with a value of `1200`:
I couldn't determine what GW stands for. Does anyone know?

2024-10-28 16:34 UTC, jc-berger commented on troubleshooting/trouble_submariner_tests.adoc
> +* The `inter-cluster` tunnel is healthy.
Dev and QA reviewers, reading the Jira, it seems to me that the test might fail in the bare metal cluster due to the following reasons. Is that right? IT seems odd to say it could fail because the tunnel is healthy. 

Anyway, please correct me if I'm wrong.

2024-10-29 14:07 UTC, aswinsuryan commented on troubleshooting/trouble_submariner_tests.adoc
> +When the end-to-end data plane tests fails, the Submariner tests shows a successful connection even though the pods remain in the `listening` phase.
Something like this would be better "the Submariner tests show that connector pod can connect to listener pod, but later the pod get stuck in the listening phase"

2024-10-29 14:08 UTC, aswinsuryan commented on troubleshooting/trouble_submariner_tests.adoc
> +. Set the MSS `clamping` value set by annotating the `GW` node. For example, run the following command with a value of `1200`:
it stands for gateway

2024-10-29 14:09 UTC, aswinsuryan commented on troubleshooting/trouble_submariner_tests.adoc
> +If the test succeeds with this small packet size, you can prevent more test failures by using Submariner to customize the transmission control protocol (TCP) minimum security standards (MSS) `clampin
Can be modified as "you can resolve the connection issues  by using Submariner to customize the transmission control protocol"

2024-10-29 14:10 UTC, aswinsuryan commented on troubleshooting/trouble_submariner_tests.adoc
> +If the test succeeds with this small packet size, you can prevent more test failures by using Submariner to customize the transmission control protocol (TCP) minimum security standards (MSS) `clampin
MSS stands for maximum segment size

2024-10-29 14:16 UTC, aswinsuryan commented on troubleshooting/trouble_submariner_tests.adoc
> +* The `inter-cluster` tunnel is healthy.
it should be like end to end to test fails even when the inter-cluster` tunnel is healthy and the if the VXLAN tunnels are used. It is like try the check sum disable step only when the above two pre-requisite are met.

2024-10-29 14:31 UTC, yboaron commented on troubleshooting/trouble_submariner_tests.adoc
> +The maximum transmission unit (MTU) can cause the end-to-end data plane test failure. Verify if the MTU causes the failure by running an end-to-end data plane test that uses a small packet size. To r
Maybe we should elaborate on MTU issues, something like 
`Inter-cluster traffic over IPSec tunnel may fail because of MTU (Maximum Transmission Unit) issues, Verify if the MTU causes the failure by running .....`

2024-10-29 15:00 UTC, oafischer commented on troubleshooting/trouble_submariner_tests.adoc
> ++
@jc-berger I'll let you address dev comments first but just a heads up that there is a formatting issue here as well

2024-10-29 15:44 UTC, yboaron commented on troubleshooting/trouble_submariner_tests.adoc
> +subctl verify --verbose --connectivity only --context <from_context> --tocontext <to_context> --image-override submariner-nettest=quay.io/submariner/nettest:devel --packet-size 200
should be 

 `--only connectivity` instaed of `--connectivity only`

2024-10-29 15:46 UTC, yboaron commented on troubleshooting/trouble_submariner_tests.adoc
> +
This  section can be deleted

2024-10-29 15:51 UTC, yboaron commented on troubleshooting/trouble_submariner_tests.adoc
> +* The `inter-cluster` tunnel is healthy.
This issue is relevant only if CNI is OpenShiftSDN or VxLAN is used for inter-cluster tunnels.

2024-10-29 15:54 UTC, yboaron commented on troubleshooting/trouble_submariner_tests.adoc
> +* The container network interface (CNI) is OpenShift software-defined networking (SDN).
Should be

`The container network interface (CNI) is OpenShiftSDN`

2024-10-29 15:56 UTC, yboaron commented on troubleshooting/trouble_submariner_tests.adoc
> +A bug in the User Datagram Protocal (UDP) can be the root cause for these reasons contributing to the end-to-end data plane test failures for bare metal clusters. To troubleshoot this bug complete th
`A bug in the User Datagram Protocal (UDP) checksum calculation by HW can be the root cause ...`

2024-10-29 15:57 UTC, yboaron commented on troubleshooting/trouble_submariner_tests.adoc
> +* In your UDP, disable the hardware offloading by applying the following YAML:
We can remove `In your UDP,`

2024-10-29 18:33 UTC, aswinsuryan commented on troubleshooting/trouble_submariner_tests.adoc
> +The end-to-end data plane tests might fail for the bare-metal cluster if the container network interface (CNI) is OpenShift software-defined networking (SDN), or if the virtual extensible local-area
```suggestion
The end-to-end data plane tests might fail for the bare-metal cluster if the container network interface (CNI) is OpenShiftSDN, or if the virtual extensible local-area network (VXLAN) is used for the `inter-cluster` tunnels.
```

2024-10-29 18:42 UTC, aswinsuryan approved these changes

2024-10-30 08:09 UTC, yboaron commented on troubleshooting/trouble_submariner_tests.adoc
> +. Set the TCP MSS `clamping` value set by annotating the gateway node. For example, run the following command with a value of `1200`:
```suggestion
. Set the TCP MSS `clamping` value by annotating the gateway node. For example, run the following command with a value of `1200`: 
```

2024-10-30 10:46 UTC, oafischer commented on troubleshooting/trouble_submariner_tests.adoc
> +When the end-to-end data plane tests fails, the Submariner tests show that the connector pod can connect to the listener pod, but later the connector pod gets stuck in the `listening` phase.
```suggestion
When the end-to-end data plane test fails, the Submariner tests show that the connector pod can connect to the listener pod, but later the connector pod gets stuck in the `listening` phase. 
```

2024-10-30 10:47 UTC, oafischer commented on troubleshooting/trouble_submariner_tests.adoc
> +== Resolving the problem: Running a data plane test with a small packet size
Resolving should always have the same title as the Symptom that its trying to resolve.

2024-10-30 10:51 UTC, oafischer commented on troubleshooting/trouble_submariner_tests.adoc
> +* In your Submariner workspace, run the following test:
I don't think we need all this for just a single step. We don't have this kind of formatting anywhere else in our doc that I could find, so maybe do something like:

`To run this type of test, run the following command command in your Submariner worksapce:`

Then remove the bullet point.

2024-10-30 10:53 UTC, oafischer commented on troubleshooting/trouble_submariner_tests.adoc
> ++
There needs to be an empty line between steps and the +. We do this everywhere in our doc to avoid formatting issues.

2024-10-30 10:53 UTC, oafischer commented on troubleshooting/trouble_submariner_tests.adoc
> +== Resolving the problem: Disabling the hardware offloading
Resolving sections should have the same title as the Symptom.

2024-10-30 10:54 UTC, oafischer commented on troubleshooting/trouble_submariner_tests.adoc
> +== Symptom: Submariner end-to-end test fails for bare-metal clusters
It seems we are packing multiple symptoms and resolutions into a file. I'm not opposed to this given that it's all around the same topic, but I'd be interested to hear some other views on this.

2024-10-30 10:56 UTC, oafischer commented on troubleshooting/trouble_submariner_tests.adoc
> +* Disable the hardware offloading by applying the following YAML:
There is still a formatting issue here. Also, same as before, we don't use single bullet points as per the style guide, so I would just merge the content here with the last sentence from the previous paragraph.

"To troubleshoot this bug, disable the hardware offloading by applying the following YAML content:"

2024-10-30 14:05 UTC, prachiyadav approved these changes

2024-11-01 15:37 UTC, dockerymick requested changes
Left a comment and couple of suggestions

2024-11-01 15:37 UTC, dockerymick commented on troubleshooting/trouble_submariner_tests.adoc
> +When the end-to-end data plane test fails, the Submariner tests show that the connector pod can connect to the listener pod, but later the connector pod gets stuck in the `listening` phase.
is "connector" and "listener" the name of the pods? If yes, we should monospace those words

2024-11-01 15:37 UTC, dockerymick commented on troubleshooting/trouble_submariner_tests.adoc
> +. Restart all the `RouteAgent` pods by running the following commands:
```suggestion
. Restart all the `RouteAgent` pods by running the following command: 
```

2024-11-01 15:37 UTC, dockerymick commented on troubleshooting/trouble_submariner_tests.adoc
> +A bug in the User Datagram Protocal (UDP) checksum calculation by the hardware can be the root cause for the end-to-end data plane test failures for bare-metal clusters. To troubleshoot this bug, dis
```suggestion
A bug in the User Datagram Protocal (UDP) checksum calculation by the hardware can be the root cause for the end-to-end data plane test failures for bare-metal clusters. To troubleshoot this bug, disable the hardware offloading by applying the following YAML file:  
```

2024-11-01 15:48 UTC, dockerymick approved these changes
this looks good to me! I made a commit to fix one of the links. Approving. Thanks Jake!

2024-11-01 15:50 UTC, merged