https://issues.redhat.com/browse/ACM-14574 as well as known issue for…
open-cluster-management/rhacm-docs pull request #7192
Opened 2024-10-28 23:35 UTC by swopebe

… install ACM13553: Identify old release notes, better integration with MCE/Cluster/ACM release notes

2024-10-29 13:15 UTC, swopebe commented on release_notes/known_issues_install.adoc
>  == Deprecated resources remain after upgrade to Errata releases
@dislbenn can you look here?

2024-10-29 13:15 UTC, swopebe commented on release_notes/known_issues_install.adoc
>  == Pods might not come back up after upgrading {acm-short}
and here @dislbenn please look

2024-10-29 13:15 UTC, swopebe commented on release_notes/known_issues_install.adoc
I plan to remove this bc it is OCPs.

2024-10-29 13:15 UTC, swopebe commented on release_notes/known_issues_install.adoc
>  == Create MultiClusterEngine button not working
and here.

2024-10-29 15:04 UTC, swopebe commented on clusters/release_notes/mce_known_issues.adoc
> +Review the known issues and limitations for _Cluster lifecycle with {mce-short}_ for this release, or known issues that continued from the previous release.
making it clearer that it is for clc with mce in known issues intro.

2024-10-29 15:04 UTC, swopebe commented on clusters/release_notes/mce_known_issues.adoc
> +Cluster management known issues and limitations are part of the _Cluster lifecycle with {mce-short}_ documentation. Known issues for {mce-short) integrated _with_ {acm-short} are documented in the li
We have to make sure we distinguish here what is MCE only and MCE with ACM install

2024-10-29 15:05 UTC, swopebe commented on clusters/release_notes/mce_known_issues.adoc
> +*Important:* {ocp-short} release notes are not documented in this product documentation. For your {ocp-short} cluster, see link:https://docs.redhat.com/documentation/en-us/openshift_container_platfor
Need to better get users to look for OCP release notes in the OCP doc.

2024-10-29 15:05 UTC, swopebe commented on clusters/release_notes/mce_known_issues.adoc
> +//??this is not a major feature of MCE is it?
?

2024-10-29 15:07 UTC, swopebe commented on release_notes/known_issues_install.adoc
Because users may not know about the new doc, I left this here but pointed to the new doc.

2024-10-30 17:30 UTC, swopebe commented on release_notes/known_issues_install.adoc
this is misplaced, but also is it still valid?

2024-11-01 13:01 UTC, dislbenn commented on release_notes/known_issues_install.adoc
@swopebe We can remove this topic. The issue with creating the MCE instance should be resolved in the console.

2024-11-01 13:04 UTC, dislbenn commented on release_notes/known_issues_install.adoc
>  == Deprecated resources remain after upgrade to Errata releases
@swopebe I think we can remove this topic since those releases are EOL.

2024-11-01 13:04 UTC, dislbenn commented on release_notes/known_issues_install.adoc
>  == Pods might not come back up after upgrading {acm-short}
Similarly here, I believe we can remove this topic as well.

2024-11-04 16:18 UTC, swopebe commented on release_notes/known_issues_cluster.adoc
> +// 2.1:5636 -//very old, we need to consider removing
notes to address post GA.

2024-11-04 16:47 UTC, dockerymick requested changes
Few broken links that need to be addressed

2024-11-04 16:47 UTC, dockerymick commented on clusters/release_notes/mce_known_issues.adoc
> +Cluster management known issues and limitations are part of the _Cluster lifecycle with {mce-short}_ documentation. Known issues for {mce-short) integrated _with_ {acm-short} are documented in the li
This link came up as broken 
```suggestion
Cluster management known issues and limitations are part of the _Cluster lifecycle with {mce-short}_ documentation. Known issues for {mce-short) integrated _with_ {acm-short} are documented in the link:../../release_notes/acm_release_notes.adoc#acm-release-notes[Release notes for {acm-short}]. 
```

2024-11-04 16:47 UTC, dockerymick commented on release_notes/acm_known_issues_intro.adoc
> +*Note:* Cluster management or _Cluster lifecycle_ is provided by the {mce-short} with or without {acm-short}. The following known issues and limitations for cluster management that apply to {acm-shor
This link was also broken. Heads up that the title for the file is: `Known issues and limitations for Cluster lifecycle with {mce-short}`
```suggestion
*Note:* Cluster management or _Cluster lifecycle_ is provided by the {mce-short} with or without {acm-short}. The following known issues and limitations for cluster management that apply to {acm-short}, or {mce-short} that is later integrated with {acm-short}. Other Cluster lifecycle known issues are located in the link:../clusters/release_notes/mce_known_issues.adoc#known-issues-mce[Cluster lifecyle known issues and limitations]. 
```

2024-11-04 16:47 UTC, dockerymick commented on release_notes/known_issues_cluster.adoc
> +For Cluster lifecycle with the {mce} known issues, see link:../clusters/release_notes/known_issues.adoc#known-issues-mce[Cluster lifecycle known issues and limitations] in the {mce-short} documentati
Similar to my previous comment, the title for the mce_known_issues.adoc file is `Known issues and limitations for Cluster lifecycle with {mce-short}`
```suggestion
For Cluster lifecycle with the {mce} known issues, see link:../clusters/release_notes/mce_known_issues.adoc#known-issues-mce[Cluster lifecycle known issues and limitations] in the {mce-short} documentation.
```

2024-11-04 16:47 UTC, dockerymick commented on release_notes/known_issues_install.adoc
> +Follow the link:../cleanup_reinstall.adoc#cleanup-reinstall[Cleaning up artifacts before reinstalling] procedure to prevent this problem.
Broken link
```suggestion
Follow the link:../install/cleanup_reinstall.adoc#cleanup-reinstall[Cleaning up artifacts before reinstalling] procedure to prevent this problem.
```

2024-11-04 17:33 UTC, dockerymick approved these changes

2024-11-04 17:48 UTC, merged