SiteConfig: fix rendering issues
open-cluster-management/rhacm-docs pull request #7209
Opened 2024-11-01 13:21 UTC by amolnar-rh

Preview links with issues:
- [Adding ClusterInstance API to the API main.adoc and updating relevant links](https://content-stage.docs.redhat.com/en/documentation/red_hat_advanced_cluster_management_for_kubernetes/2.12/html-single/multicluster_engine_operator_with_red_hat_advanced_cluster_management/index#default-templates) - added ClusterInstance API to the API main.adoc.
- [Rendering issue (+) in Deprovisioning SNO clusters](https://content-stage.docs.redhat.com/en/documentation/red_hat_advanced_cluster_management_for_kubernetes/2.12/html-single/multicluster_engine_operator_with_red_hat_advanced_cluster_management/index#deprovision-steps)
- [Missing space before `hostname` in Pruning the BareMetalHost resource of the worker node](https://content-stage.docs.redhat.com/en/documentation/red_hat_advanced_cluster_management_for_kubernetes/2.12/html-single/multicluster_engine_operator_with_red_hat_advanced_cluster_management/index#scale-in-prunemanifests)
- [Removing whitespaces before + in Verifying worker node addition](https://content-stage.docs.redhat.com/en/documentation/red_hat_advanced_cluster_management_for_kubernetes/2.12/html-single/multicluster_engine_operator_with_red_hat_advanced_cluster_management/index#scale-in-prunemanifests)

2024-11-01 13:34 UTC, dockerymick requested changes
Left one comment and verified that the links work. Were the steps not rendering correctly in siteconfig_scale_out_worker_nodes.adoc?

2024-11-01 13:34 UTC, dockerymick commented on mce_acm_integration/siteconfig/siteconfig_scale_out_worker_nodes.adoc
> +.. Verify that the `Node` resources are removed by running the following command on the hub cluster:
I recommend that you revert the change here. There should be a new line between the step and plus sign

2024-11-01 17:07 UTC, amolnar-rh commented on mce_acm_integration/siteconfig/siteconfig_scale_out_worker_nodes.adoc
> +.. Verify that the `Node` resources are removed by running the following command on the hub cluster:
It doesn't look right and I'm checking the preview in my local editor. The only way to resolve the issue of the codeblocks is by removing the extra space.
![Screenshot from 2024-11-01 17-05-50](https://github.com/user-attachments/assets/2d82e821-4385-4b74-a88f-66c282c20d34)

![Screenshot from 2024-11-01 13-16-05](https://github.com/user-attachments/assets/7d9bb394-02e7-4742-aaed-d01afbefa528)

2024-11-01 17:09 UTC, amolnar-rh commented on mce_acm_integration/siteconfig/siteconfig_scale_out_worker_nodes.adoc
> +.. Verify that the `Node` resources are removed by running the following command on the hub cluster:
Anyway, I had to change this section but there are other steps where it's not rendering right:
![Screenshot from 2024-11-01 17-08-31](https://github.com/user-attachments/assets/58aca24a-9de6-4104-8817-5bf4224ba726)

2024-11-01 17:45 UTC, dockerymick requested changes
Thanks for your hard work on this! I left a few suggestions

2024-11-01 17:45 UTC, dockerymick commented on apis/clusterinstance.json.adoc
> +* link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.17/html/edge_computing/image_base_install/ibi_deploying_sno_clusters/ibi-edge-image-based-install[Deploying managed {sno
This appeared as a broken link: 
<img width="829" alt="Screenshot 2024-11-01 at 1 05 26 PM" src="https://github.com/user-attachments/assets/3b22a832-276d-48c8-978d-8c9cb6076ae0">

2024-11-01 17:45 UTC, dockerymick commented on mce_acm_integration/siteconfig/ibio_intro.adoc
> +For more information about, and to learn how to enable the {ibio}, see https://docs.redhat.com/en/documentation/openshift_container_platform/4.17/html/edge_computing/image_base_install/ibi_deploying_
this link is also broken we also need `link:` for the syntax. I think that is not the reason why the link is broken, just making the suggestion so that the link references are consistent

2024-11-01 17:45 UTC, dockerymick commented on mce_acm_integration/siteconfig/siteconfig_enable.adoc
> +. Optional. Verify that you have the default installation templates by running the following command on the hub cluster:
throughout the doc we bold Optional
```suggestion
. *Optional:* Verify that you have the default installation templates by running the following command on the hub cluster:
```

2024-11-01 17:45 UTC, dockerymick commented on mce_acm_integration/siteconfig/siteconfig_install_clusters.adoc
> +** To learn about and install the {ibio} for {sno}, see link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.17/html/edge_computing/image_base_install/ibi_deploying_sno_cluste
broken link

2024-11-01 17:45 UTC, dockerymick commented on mce_acm_integration/siteconfig/siteconfig_install_clusters.adoc
> +* <<install-clusters-reconcile-clusterinstance,Rendering the installation manifests>>
Since you are documenting these as steps, I was expecting an ordered list: 
```suggestion
Complete the following steps to install a cluster with the {sco}:

. <<install-clusters-target-ns,Creating the target namespace>>
. <<install-clusters-pull-secret,Creating the pull secret>>
. <<install-clusters-bmc-secret,Creating the BMC secret>>
. <<install-clusters-extra-manifests,Optional: Creating the extra manifests>>
. <<install-clusters-reconcile-clusterinstance,Rendering the installation manifests>>
```

2024-11-01 17:45 UTC, dockerymick commented on mce_acm_integration/siteconfig/siteconfig_install_clusters.adoc
> +* <<install-clusters-reconcile-clusterinstance,Rendering the installation manifests>>
Or you can say, Complete the steps in the following sections if they don't need to be in order

2024-11-01 17:45 UTC, dockerymick commented on mce_acm_integration/siteconfig/siteconfig_installation_templates.adoc
> +The {sco} supports the following types of installation templates:
lines 6-12 are displayed as new lines. What are your thoughts about the statement on line 6 being mover to line 4? And then maybe the statement in 12 moved to line 10?

2024-11-01 17:45 UTC, dockerymick commented on mce_acm_integration/siteconfig/siteconfig_scale_in_worker_nodes.adoc
> +Complete the following steps to scale in a cluster with the {sco}:
Similar to my earlier comment, I recommend that you say, "Complete the steps in the following sections:"

Alternatively, we can decide to not list them because there are only 2 sections. We usually use childlinks when there are more than 2 sections.

2024-11-01 17:45 UTC, dockerymick commented on mce_acm_integration/siteconfig/siteconfig_scale_in_worker_nodes.adoc
> +. Add an annotation in the `extraAnnotations` field of the worker node entry in the `ClusterInstance` custom resource that was used to provision your cluster:
Making this statement present tense
```suggestion
. Add an annotation in the `extraAnnotations` field of the worker node entry in the `ClusterInstance` custom resource that is used to provision your cluster:
```

2024-11-01 17:45 UTC, dockerymick commented on mce_acm_integration/siteconfig/siteconfig_scale_in_worker_nodes.adoc
> +oc get bmh -n <clusterinstance_namespace>  worker-node2.example.com -ojsonpath='{.metadata.annotations}' | jq
seems like there is an extra space before `worker-node2.example.com`. is that intentional?

2024-11-01 17:45 UTC, dockerymick commented on mce_acm_integration/siteconfig/siteconfig_scale_in_worker_nodes.adoc
> -[source,terminal]
Is there a reason why this was removed? I also recommend that the plus sign be added to help with alignment

2024-11-01 17:45 UTC, dockerymick commented on mce_acm_integration/siteconfig/siteconfig_scale_in_worker_nodes.adoc
>  [#scale-in-annotation]
I recommend that the anchor for this be updated to `add-annotation-worker-node` or something similar. Maybe even `scale-add-annotation`

2024-11-01 17:45 UTC, dockerymick commented on mce_acm_integration/siteconfig/siteconfig_scale_in_worker_nodes.adoc
>  [#scale-in-prunemanifests]
I recommend changing this anchor to `delete-baremetal-host-resource` or something similar

2024-11-01 17:45 UTC, dockerymick commented on mce_acm_integration/siteconfig/siteconfig_scale_in_worker_nodes.adoc
> +. Update the node object that you want to delete in your existing `ClusterInstance` CR with the following configuration:
```suggestion
. Update the node object that you want to delete in your existing `ClusterInstance` custom resource with the following configuration:
```

2024-11-01 17:45 UTC, dockerymick commented on mce_acm_integration/siteconfig/siteconfig_scale_out_worker_nodes.adoc
> +Add a worker node by updating your `ClusterInstance` CR that was used to provision your cluster.
```suggestion
Add a worker node by updating your `ClusterInstance` custom resource that is used to provision your cluster.
```

2024-11-01 17:45 UTC, dockerymick commented on mce_acm_integration/siteconfig/siteconfig_scale_out_worker_nodes.adoc
> +. Define a new node object in the existing `ClusterInstance` CR:
```suggestion
. Define a new node object in the existing `ClusterInstance` custom resource:
```

2024-11-01 18:09 UTC, amolnar-rh commented on mce_acm_integration/siteconfig/siteconfig_installation_templates.adoc
> +The {sco} supports the following types of installation templates:
Thanks for pointing out, they should be 2 paragraphs:
Line 4, 6, 8 are on line 4 now, and line 10-12 are on one line (line 6).

2024-11-01 18:12 UTC, amolnar-rh commented on mce_acm_integration/siteconfig/siteconfig_scale_in_worker_nodes.adoc
> +oc get bmh -n <clusterinstance_namespace>  worker-node2.example.com -ojsonpath='{.metadata.annotations}' | jq
I believe it's intentional but @shakoury please confirm!

2024-11-01 18:14 UTC, amolnar-gh commented on mce_acm_integration/siteconfig/siteconfig_scale_in_worker_nodes.adoc
> -[source,terminal]
It looks like I removed it because I forgot to add `[source,terminal]` before the output. Otherwise, it was just rephrased a bit to fit the step better

2024-11-01 18:16 UTC, amolnar-rh commented on mce_acm_integration/siteconfig/siteconfig_scale_in_worker_nodes.adoc
> +Complete the following steps to scale in a cluster with the {sco}:
Okay, I removed this part

2024-11-01 18:40 UTC, dockerymick requested changes
Couple more comments

2024-11-01 18:40 UTC, dockerymick commented on mce_acm_integration/siteconfig/siteconfig_install_clusters.adoc
>  [#install-clusters-target-ns]
My bad, I should've caught this in the first review. Similar suggestion about updating the anchor. maybe to `create-target-ns` or something similar

2024-11-01 18:40 UTC, dockerymick commented on mce_acm_integration/siteconfig/siteconfig_install_clusters.adoc
> +== Rendering the installation manifests
I also suggest to update this anchor, maybe to `render-installation-manifests`

2024-11-01 18:40 UTC, dockerymick commented on mce_acm_integration/siteconfig/siteconfig_installation_templates.adoc
> +Installation templates are data-driven templates that are used to generate the set of installation artifacts. These templates follow the Golang `text/template` format, and they are instantiated by us
```suggestion
Installation templates are data-driven templates that are used to generate the set of installation artifacts. These templates follow the Golang `text/template` format, and are instantiated by using data from the `ClusterInstance` custom resource. This enables dynamic creation of installation manifests for each target cluster that has similar configurations, but with different values.
```

2024-11-01 18:40 UTC, dockerymick commented on mce_acm_integration/siteconfig/siteconfig_scale_out_worker_nodes.adoc
>  . Apply the changes.
```suggestion
. Apply the following changes.
```

2024-11-01 18:59 UTC, amolnar-rh commented on mce_acm_integration/siteconfig/siteconfig_scale_out_worker_nodes.adoc
>  . Apply the changes.
We actually have something similar in scale in:
`. Apply the changes. See the following options:`

So I added the second sentence instead

2024-11-01 19:03 UTC, amolnar-rh commented on mce_acm_integration/siteconfig/ibio_intro.adoc
> +For more information about, and to learn how to enable the {ibio}, see https://docs.redhat.com/en/documentation/openshift_container_platform/4.17/html/edge_computing/image_base_install/ibi_deploying_
For visibility, I'm commenting here as well that the link will be broken until the content is released in the OCP docs that should happen at the same time as the ACM 2.12 GA. This link might need a fix after release

2024-11-01 19:36 UTC, dockerymick commented on mce_acm_integration/siteconfig/siteconfig_scale_out_worker_nodes.adoc
> +.. Verify that the `Node` resources are removed by running the following command on the hub cluster:
Ok, let's leave it for now and. we can revisit in a refresh

2024-11-01 19:40 UTC, dockerymick approved these changes
Besides the comment about the command, this looks good to me!

2024-11-04 15:51 UTC, sakhoury requested changes
Thanks for the great work @amolnar-rh 🎉 🚀

2024-11-04 15:51 UTC, sakhoury commented on apis/clusterinstance.json.adoc
> +*Important:* Certain fields are only relevant to a specific installation flow. Verify which fields are applicable to your choice of installation method by checking the relevant documentation. For {ai
> For {ai} and Image Based Install, see the following documentation:

We reference AI and then IBI, but the links are first IBI and then AI. Maybe we can align on the ordering of the links to match the text?

2024-11-04 15:51 UTC, sakhoury commented on mce_acm_integration/siteconfig/siteconfig_scale_in_worker_nodes.adoc
> +oc get bmh -n <clusterinstance_namespace>  worker-node2.example.com -ojsonpath='{.metadata.annotations}' | jq
The additional space is not required - good catch @dockerymick!

2024-11-04 15:51 UTC, sakhoury commented on mce_acm_integration/siteconfig/siteconfig_scale_in_worker_nodes.adoc
> +oc get agents -n <clusterinstance_namespace> --watch --kubeconfig <hub_cluster_kubeconfig_filename>
```suggestion
oc get agents -n <clusterinstance_namespace> --kubeconfig <hub_cluster_kubeconfig_filename>
```
We can do without the `watch` here since we ask that the user verifies the removal of the agent corresponding to `worker-node2.example.com` by observing that it does not exist in the output of the command.

2024-11-04 15:51 UTC, sakhoury commented on mce_acm_integration/siteconfig/siteconfig_scale_out_worker_nodes.adoc
> +. Verify that the `BareMetalHost` resources are added by running the following command on the hub cluster:
```suggestion
. Verify that a new `BareMetalHost` resource is added by running the following command on the hub cluster:
```

2024-11-04 15:51 UTC, sakhoury commented on mce_acm_integration/siteconfig/siteconfig_scale_out_worker_nodes.adoc
> +. Verify that the `Agent` resources are added by running the following command on the hub cluster:
```suggestion
. Verify that a new `Agent` resource is added by running the following command on the hub cluster:
```

2024-11-04 15:51 UTC, sakhoury commented on mce_acm_integration/siteconfig/siteconfig_scale_out_worker_nodes.adoc
> +. Verify that the `Node` resources are added by running the following command on the managed cluster:
```suggestion
. Verify that a new `Node` resource is added by running the following command on the managed cluster:
```

2024-11-04 16:21 UTC, merged