https://issues.redhat.com/browse/ACM-14417 Ver. Strategy doc
open-cluster-management/rhacm-docs pull request #7222
Opened 2024-11-07 16:54 UTC by oafischer

Train 19

2024-11-12 15:42 UTC, zhujian7 commented
@oafischer can we also mention the strategy when provision/importing a cluster, if it is a ROSA-HCP cluster, should check if the `UseSystemTruststore` configured, example:

[1.6.4 Cluster creation](https://docs.redhat.com/en/documentation/red_hat_advanced_cluster_management_for_kubernetes/2.11/html/clusters/cluster_mce_overview#create-intro)
Add a pre-flight for the cluster creation
If your hub cluster API server certificate is issued by a public CA(e.g. Let’s Encrypt). For example, ROSA-HCP. Please refer to 1.6.18.1 to check if the hub server verification strategy is configured to `UseSystemTruststore`.

[1.6.5 Cluster import](https://docs.redhat.com/en/documentation/red_hat_advanced_cluster_management_for_kubernetes/2.11/html/clusters/cluster_mce_overview#import-intro)
Add a pre-flight for the cluster import
If your hub cluster API server certificate is issued by a public CA(e.g. Let’s Encrypt). For example, ROSA-HCP. Please refer to 1.6.18.1 to check if the hub server verification strategy is configured to `UseSystemTruststore`.

2024-11-12 15:48 UTC, zhujian7 commented on clusters/cluster_lifecycle/adv_config_cluster.adoc
> +If your automatically detected certificate does not work, you can manually configure a strategy configuration in the `KlusterletConfig` resource. Manually configuring the a strategy allows you to con
```suggestion
If your automatically detected certificate does not work, you can manually configure a strategy configuration in the `KlusterletConfig` resource. Manually configuring the strategy allows you to control how you verify the hub cluster `KubeAPIServer` certificate.
```

2024-11-12 15:48 UTC, zhujian7 commented on clusters/cluster_lifecycle/adv_config_cluster.adoc
> +You can use `UseCustomCABundles` if you lknow the CA of the hub cluster API server and do not want {mce-short} to automatically detect it. For this strategy, {mce-short} adds your configured certific
```suggestion
You can use `UseCustomCABundles` if you know the CA of the hub cluster API server and do not want {mce-short} to automatically detect it. For this strategy, {mce-short} adds your configured certificates from `trustedCABundles` to the managed clusters. See the following examples to learn how to use `UseCustomCABundles`:
```

2024-11-12 15:49 UTC, zhujian7 commented
@elgnay please help take a review, thx!

2024-11-12 16:59 UTC, oafischer commented
@zhujian7 We can add the pre-flight info but I'm not sure where a good spot for it would be. In our creating and import doc, we do not have anything related to ROSA.

HCP content has also moved to OCP docs entirely in 2.12, so we don't have any HCP docs left in ACM docs where this could fit in either.

When reading pre-flight info, it sounds like it applies to more than just ROSA HCP. Is that the case?

2024-11-13 07:33 UTC, zhujian7 commented
> HCP content has also moved to OCP docs entirely in 2.12, so we don't have any HCP docs left in ACM docs where this could fit in either.

If so, I think it's OK without the pre-flight info. @elgnay WDYT?

2024-11-13 08:29 UTC, elgnay commented
@oafischer @zhujian7 I still think we need to add one more item to the prerequisites of cluster creation and cluster importing:
- https://docs.redhat.com/en/documentation/red_hat_advanced_cluster_management_for_kubernetes/2.12/html/clusters/cluster_mce_overview#create-a-cluster-prereq
- https://docs.redhat.com/en/documentation/red_hat_advanced_cluster_management_for_kubernetes/2.12/html/clusters/cluster_mce_overview#import-gui-prereqs
Since the default strategy 'UseAutoDetectedCABundle' may not work always, it necessary for the user to review the hub API server certificate verification strategy before they start creating or importing managed clusters.

2024-11-13 16:31 UTC, oafischer commented
@zhujian7 @elgnay Thanks for the feedback, I've added the requested info to the general prereq sections for import and create. I think it works well there. Let me know if it looks good now. Thanks!

2024-11-14 01:03 UTC, elgnay commented
LGTM

2024-11-14 07:03 UTC, zhujian7 commented
/lgtm

2024-11-15 16:17 UTC, dockerymick requested changes

2024-11-15 16:17 UTC, dockerymick commented on clusters/cluster_lifecycle/adv_config_cluster.adoc
> +[#config-hub-kube-api-server-detect]
I would update this anchor
```suggestion
[#config-hub-strategy-auto-detect-ca]
```

2024-11-15 16:17 UTC, dockerymick commented on clusters/cluster_lifecycle/adv_config_cluster.adoc
> +`UseAutoDetectedCABundle` is the default strategy. The {mce-short} automatically detects the certificate on the hub cluster and merges the certificate configured in the `trustedCABundles` list of Con
Let's try to not start the sentence with the parameter value. Since there are a few back-to-back statements that start with "the", I can understand why you might keep it as is. 
```suggestion
The default configuration strategy is `UseAutoDetectedCABundle`. The {mce-short} automatically detects the certificate on the hub cluster and merges the certificate configured in the `trustedCABundles` list of config map references to the real CA bundles, if there are any.
```

2024-11-15 16:17 UTC, dockerymick commented on clusters/cluster_lifecycle/adv_config_cluster.adoc
> +The following example merges the automatically detected certificates from the hub cluster, and the certificates that you configured in the `new-ocp-ca` ConfigMap, and adds them to the managed cluster
Are both the automatically detected certificates and configured certificates merged?

```suggestion
The following example merges the automatically detected certificates from the hub cluster and the certificates that you configured in the `new-ocp-ca` config map, and adds them to the managed cluster:
```

2024-11-15 16:17 UTC, dockerymick commented on clusters/cluster_lifecycle/adv_config_cluster.adoc
> +You can use `UseCustomCABundles` if you know the CA of the hub cluster API server and do not want {mce-short} to automatically detect it. For this strategy, {mce-short} adds your configured certifica
```suggestion
You can use `UseCustomCABundles` if you know the CA of the hub cluster API server and do not want {mce-short} to automatically detect it. For this strategy, {mce-short} adds your configured certificates from the `trustedCABundles` parameter to the managed clusters. See the following examples to learn how to use `UseCustomCABundles`:
```

2024-11-15 16:17 UTC, dockerymick commented on clusters/cluster_lifecycle/adv_config_cluster.adoc
> +With `UseSystemTruststore`, {mce-short} does not detect any certificate and ignores the certificates configured in the `trustedCABundles`. This configuration does not pass any certificate to the mana
Suggestion based on tone and removing anthropomorphism. From my perspective, using "their" is an example of using anthropomorphism. But let me know your perspective. Is "Let's Encrypt" a parameter value? When I googled, I saw that it was a CA. Were you trying to add emphasis to the name? 

```suggestion
With `UseSystemTruststore`, {mce-short} does not detect any certificate and ignores the certificates configured in the `trustedCABundles` parameter section. This configuration does not pass any certificate to the managed clusters. Instead, the managed clusters use certificates from the system trusted store of the managed clusters to verify the hub cluster API server. This applies to situations where a public CA, such as `Let's Encrypt`, issues the hub cluster certificate. See the following example that uses `UseSystemTruststore`:
```

2024-11-15 16:17 UTC, dockerymick commented on clusters/cluster_lifecycle/adv_config_cluster.adoc
> +[#config-hub-kube-api-server-system]
```suggestion
[#config-hub-strategy-system-truststore]
```

2024-11-15 16:17 UTC, dockerymick commented on clusters/cluster_lifecycle/adv_config_cluster.adoc
> +[#config-hub-kube-api-server-custom]
```suggestion
[#config-hub-strategy-custom-ca]
```

2024-11-15 16:17 UTC, dockerymick commented on clusters/cluster_lifecycle/adv_config_cluster.adoc
> +
Some of the examples are pretty similar with the exception of a different `serverVerificationStrategy` value. What do you think about creating a definition list for the options instead of having a new sub section for each one? Just wanted to know your thoughts. I figured it might reduce some lines, but maybe not lol

2024-11-15 16:23 UTC, oafischer commented on clusters/cluster_lifecycle/adv_config_cluster.adoc
> +The following example merges the automatically detected certificates from the hub cluster, and the certificates that you configured in the `new-ocp-ca` ConfigMap, and adds them to the managed cluster
@zhujian7 Can you help clarify? I'm not sure if both are merged

2024-11-15 16:26 UTC, oafischer commented on clusters/cluster_lifecycle/adv_config_cluster.adoc
> +With `UseSystemTruststore`, {mce-short} does not detect any certificate and ignores the certificates configured in the `trustedCABundles`. This configuration does not pass any certificate to the mana
I agree, we can just say `the` instead of `their`.

Let's Encrypt is a name as you already found out. To prevent translation issues I wanted it to be monospaced. Let me know if that makes sense, or if there is a better way to do this.

2024-11-15 16:28 UTC, oafischer commented on clusters/cluster_lifecycle/adv_config_cluster.adoc
> +
Do you have an example? I agree that it's a little long. I wanted to do bullet points at first but remembered that we can't use those for headings due to accessibility. Maybe a definition list is what I was thinking of needing. If you have a good example in mind I'll try and see if I can restructure this section.

2024-11-15 16:53 UTC, dockerymick commented on clusters/cluster_lifecycle/adv_config_cluster.adoc
> +=== Configuring the strategy with `UseAutoDetectedCABundle`
Here's an example of what I was talking about. Related comment: https://github.com/stolostron/rhacm-docs/pull/7222/files#r1844139775

The tricky part is adding callouts to describe the values in the YAML sample. We can probably still keep the examples, and the only line reduction would come from removing the anchors and titles

```suggestion
See the examples in one of the following three strategies to learn how to manually configure a strategy:

`UseAutoDetectedCABundle`:: The default configuration strategy is `UseAutoDetectedCABundle`. The {mce-short} automatically detects the certificate on the hub cluster and merges the certificate configured in the `trustedCABundles` list of config map references to the real CA bundles, if there are any.

`UseSystemTruststore`:: With `UseSystemTruststore`, {mce-short} does not detect any certificate and ignores the certificates configured in the `trustedCABundles` parameter section. This configuration does not pass any certificate to the managed clusters. Instead, the managed clusters use certificates from the system trusted store of the managed clusters to verify the hub cluster API server. This applies to situations where a public CA, such as `Let's Encrypt`, issues the hub cluster certificate.

`UseCustomCABundles`:: You can use `UseCustomCABundles` if you know the CA of the hub cluster API server and do not want {mce-short} to automatically detect it. For this strategy, {mce-short} adds your configured certificates from the `trustedCABundles` parameter to the managed clusters.
```

2024-11-16 10:57 UTC, zhujian7 commented on clusters/cluster_lifecycle/adv_config_cluster.adoc
> +The following example merges the automatically detected certificates from the hub cluster, and the certificates that you configured in the `new-ocp-ca` ConfigMap, and adds them to the managed cluster
yes, both are merged, and then pass them to the managed cluster.

2024-11-18 16:17 UTC, oafischer commented on clusters/cluster_lifecycle/adv_config_cluster.adoc
> +=== Configuring the strategy with `UseAutoDetectedCABundle`
Thanks for sharing an example. As you mentioned, integrating the YAML samples will be difficult. I'm almost leaning more to keeping the titles, since those make it a bit clearer that there are steps that the user needs to do. Since there are only 3 titles , are you OK with just keeping it as is?

2024-11-18 19:18 UTC, dockerymick approved these changes

2024-11-21 09:31 UTC, merged

2024-12-04 06:18 UTC, zhujian7 commented on clusters/cluster_lifecycle/create_clusterset.adoc
> +[#creating-managedclusterset-prereq]
HI @oafischer  the prerequisite is NOT for "create_clusterset", but for "create cluster", because the strategy is used for importing a cluster, and after a cluster is created, it will be imported to the hub by default. so we may need to:

- delete the prerequisite here
- instead, add the prerequisite in create_cluster_cli.adoc and create_cluster_on_prem.adoc
- add the prerequisite in "import_cli.adoc" and "import_gui.adoc" as well

2024-12-04 06:19 UTC, zhujian7 commented on clusters/cluster_lifecycle/create_clusterset.adoc
> +[#creating-managedclusterset-prereq]
I created a task for this https://issues.redhat.com/browse/ACM-16098

2024-12-04 10:29 UTC, oafischer commented on clusters/cluster_lifecycle/create_clusterset.adoc
> +[#creating-managedclusterset-prereq]
Thanks for creating the issue, I'll take care of it