https://issues.redhat.com/browse/ACM-15508 - provide more info about extraLabels for SiteConfig
open-cluster-management/rhacm-docs pull request #7243
Opened 2024-11-18 11:26 UTC by amolnar-rh

2024-11-26 19:49 UTC, dockerymick approved these changes
This looks good to me !

2024-12-02 14:14 UTC, sakhoury requested changes

2024-12-02 14:14 UTC, sakhoury commented on mce_acm_integration/siteconfig/siteconfig_installation_templates.adoc
> +  "vendor": "auto-detect"
The following lines can be omitted from the sample output:
```
"cluster.open-cluster-management.io/clusterset": "default",
"siteconfig.open-cluster-management.io/owned-by": "example-sno_example-sno",
```
These can be replaced with 
```
 "common": "true",
  "group-du": "",
  etc
   ...
```

2024-12-02 14:14 UTC, sakhoury commented on mce_acm_integration/siteconfig/siteconfig_installation_templates.adoc
> +[source,json]
Perhaps provide the `oc` command used to obtain the `ManagedCluster` label output?

2024-12-02 14:14 UTC, sakhoury commented on mce_acm_integration/siteconfig/siteconfig_installation_templates.adoc
> +  "siteconfig.open-cluster-management.io/owned-by": "example-sno_example-sno",
These two lines can be omitted and replaced with ellipses.

2024-12-02 14:14 UTC, sakhoury commented on mce_acm_integration/siteconfig/siteconfig_installation_templates.adoc
> +[source,json]
Again, let's add the `oc` command used to generate the output below.

2024-12-02 14:14 UTC, sakhoury commented on apis/clusterinstance.json.adoc
> +__optional__|Specify additional cluster-level labels to be applied to the rendered templates by using the following format: +
Perhaps we can use this PR to also expand on the `ExtraAnnotations` as it is very similar to `ExtraLabels`.

2024-12-02 16:29 UTC, sakhoury commented on mce_acm_integration/siteconfig/siteconfig_installation_templates.adoc
> +== Configuration of custom labels and annotations
```suggestion
== Configuration of additional annotations and labels
```
I think we can sort the elements alphabetically, i.e. annotations and then labels.

2024-12-02 16:29 UTC, sakhoury commented on apis/clusterinstance.json.adoc
> +__optional__|Specify additional cluster-level labels to be applied to the rendered templates by using the following format: +
Can we add the `__optional__|Specify additional cluster-level annotations to be applied to the rendered templates by using the following format:` to the `extraAnnotations` as well to be consistent?

2024-12-02 16:46 UTC, sakhoury commented on apis/clusterinstance.json.adoc
> +----
```suggestion
[source,yaml]
----
extraAnnotations:
  ClusterDeployment:
    myClusterAnnotation: success
----
```
Fix indentation

2024-12-02 16:46 UTC, sakhoury commented on mce_acm_integration/siteconfig/siteconfig_installation_templates.adoc
> +You can configure additional additional annotations and labels to both cluster-level and node-level installation manifests by using the `extraLabels` and `extraAnnotations` fields in the `ClusterInst
```suggestion
You can configure additional annotations and labels to both cluster-level and node-level installation manifests by using the `extraAnnotations` and `extraLabels` fields in the `ClusterInstance` API.
```

2024-12-02 16:46 UTC, sakhoury commented on mce_acm_integration/siteconfig/siteconfig_installation_templates.adoc
> +When creating your additional annotations and labels, you must specify a manifest type to allow the {sco} to apply your them to the appropriate manifest.
Can we fix this sentence: `... to apply your them to the appropriate manifest.`

2024-12-03 13:40 UTC, sakhoury commented on mce_acm_integration/siteconfig/siteconfig_installation_templates.adoc
> +However, the annotations and labels are arbitrary and you can set any key and value pairs.
```suggestion
However, the annotations and labels are arbitrary and you can set any key and value pairs that are meaningful to your application.
```

2024-12-03 13:40 UTC, sakhoury commented on mce_acm_integration/siteconfig/siteconfig_installation_templates.adoc
> +.Example application of extraLabels
```suggestion
.Example application of extraAnnotations and extraLabels
```

2024-12-03 13:40 UTC, sakhoury commented on mce_acm_integration/siteconfig/siteconfig_installation_templates.adoc
> +.Example applied labels
Does this line `.Example applied labels` belong somewhere else perhaps above the line?
```
. You can verify that your additional labels are applied by running the following command:
```

2024-12-03 15:11 UTC, sakhoury approved these changes

2024-12-03 15:43 UTC, cwilkers commented on mce_acm_integration/siteconfig/siteconfig_installation_templates.adoc
> +You can configure additional additional annotations and labels to both cluster-level and node-level installation manifests by using the `extraAnnotations` and `extraLabels` fields in the `ClusterInst
'additional' is duplicated here

2024-12-03 16:06 UTC, amolnar-rh commented on mce_acm_integration/siteconfig/siteconfig_installation_templates.adoc
> +You can configure additional additional annotations and labels to both cluster-level and node-level installation manifests by using the `extraAnnotations` and `extraLabels` fields in the `ClusterInst
Thanks, updated!

2024-12-03 16:49 UTC, cwilkers reviewed
Looks good, I just had one typo comment and a small clarification

2024-12-03 16:49 UTC, cwilkers commented on mce_acm_integration/siteconfig/siteconfig_installation_templates.adoc
> +However, the annotations and labels are arbitrary and you can set any key and value pairs that are meaningful to your applications.
I like giving the first order label a name of 'manifest type'.

I don't think we need to point out that the annotations and labels themselves are arbitrary, but it is useful to point out that the 'manifest type' itself is an arbitrary label. Especially since all the examples use the `Kind` of the targeted manifest as the 'manifest type' label, but this is only a convention.

2024-12-03 17:11 UTC, sakhoury commented on mce_acm_integration/siteconfig/siteconfig_installation_templates.adoc
> +However, the annotations and labels are arbitrary and you can set any key and value pairs that are meaningful to your applications.
Note that the manifest type is not an arbitrary label in this context. The manifest type specifies the resource `kind` for which annotations / labels must be applied to. However, the manifest type in the installation templates can be an arbitrary label - this though is unrelated.

2024-12-03 17:13 UTC, sakhoury commented on mce_acm_integration/siteconfig/siteconfig_installation_templates.adoc
> +You can configure additional additional annotations and labels to both cluster-level and node-level installation manifests by using the `extraAnnotations` and `extraLabels` fields in the `ClusterInst
Looks like it was not addressed here https://github.com/stolostron/rhacm-docs/pull/7243#discussion_r1866208457.

2024-12-03 17:55 UTC, amolnar-rh commented on mce_acm_integration/siteconfig/siteconfig_installation_templates.adoc
> +However, the annotations and labels are arbitrary and you can set any key and value pairs that are meaningful to your applications.
My understanding is if the first order label doesn't match the target manifest type, the SiteConfig operator won't apply the annotation/label to the intended manifest(s)

```  
extraAnnotations: 
  ClusterDeployment: #this must match the target manifest type, this is the resource that the SiteConfig operator applies the annotation to
    myClusterAnnotation: success #this is the annotation that'll be applied, it can be whatever you'd like
```

Same for labels.

2024-12-03 18:01 UTC, cwilkers commented on mce_acm_integration/siteconfig/siteconfig_installation_templates.adoc
> +However, the annotations and labels are arbitrary and you can set any key and value pairs that are meaningful to your applications.
That is important to clear up, thanks for the explanation, @sakhoury and @amolnar-rh . In this case, the documentation as provided is good as it appears in this PR.

2024-12-03 18:21 UTC, dockerymick requested changes

2024-12-03 18:21 UTC, dockerymick commented on mce_acm_integration/siteconfig/siteconfig_install_clusters.adoc
> +<5> Reference the `name` of the cluster-level templates under the `spec.templateRefs` field. If you are using a default installation template, the `namespace` must match the namespace where the {sco}
```suggestion
<5> Reference the `name` of the cluster-level templates for the `spec.templateRefs` field. If you are using a default installation template, the `namespace` must match the namespace where the {sco} is installed.
```

2024-12-03 18:21 UTC, dockerymick commented on mce_acm_integration/siteconfig/siteconfig_install_clusters.adoc
> +<7> Reference the `name` of the node-level templates under the `spec.nodes.templateRefs` field. If you are using a default installation template, the `namespace` must match the namespace where the {s
```suggestion
<7> Reference the `name` of the node-level templates for the `spec.nodes.templateRefs` field. If you are using a default installation template, the `namespace` must match the namespace where the {sco} is installed.
```

2024-12-03 18:21 UTC, dockerymick commented on mce_acm_integration/siteconfig/siteconfig_installation_templates.adoc
> +<2> These are node-level annotations and labels that the {sco} applies to the `BareMetalHost` manifest.
```suggestion
<1> This field supports cluster-level annotations and labels that the {sco} applies to the the `ManagedCluster` and `ClusterDeployment` manifests.
<2> This field supports node-level annotations and labels that the {sco} applies to the `BareMetalHost` manifest.
```

2024-12-03 18:21 UTC, dockerymick commented on mce_acm_integration/siteconfig/siteconfig_installation_templates.adoc
> +[source,yaml]
I like how you created a title that explains what the sample is. However, we usually prompt the user for the example by saying the following statement: 

View the following example application of `extraAnnotations` and `extraLabels`:
```suggestion
However, the annotations and labels are arbitrary and you can set any key and value pairs that are meaningful to your applications.

.Example application of extraAnnotations and extraLabels
[source,yaml]
```

2024-12-03 18:21 UTC, dockerymick commented on mce_acm_integration/siteconfig/siteconfig_installation_templates.adoc
> +----
Is it your intention to make this a step? From my perspective this seems like a concept section and not a task. What do the two dashes do ? We also typically remove the dollar sign in the commands. 

```suggestion
. You can verify that your additional labels are applied by running the following command:

+
[source,terminal]
----
oc get managedclusters example-sno -ojsonpath='{.metadata.labels}' | jq
----
```

2024-12-03 18:21 UTC, dockerymick commented on mce_acm_integration/siteconfig/siteconfig_installation_templates.adoc
> +.Example applied labels
Similar comment, I like how you use the alt text to describe the YAML, but we typically introduce the example to the user. 

"View the following example of applied labels:"

2024-12-03 18:21 UTC, dockerymick commented on mce_acm_integration/siteconfig/siteconfig_installation_templates.adoc
> +--
Not sure what the dashes are for 
```suggestion
```

2024-12-03 18:21 UTC, dockerymick commented on mce_acm_integration/siteconfig/siteconfig_installation_templates.adoc
> +--
```suggestion
. You can verify that your additional annotations are applied by running the following command:

+
[source,terminal]
----
oc get bmh example-sno.example.redhat.com -n example-sno -ojsonpath='{.metadata.annotations}' | jq
----

.Example applied annotation
[source,json]
----
{
  "myNodeAnnotation": "success",
  ...
}
----
```

2024-12-05 14:31 UTC, sakhoury commented on mce_acm_integration/siteconfig/siteconfig_installation_templates.adoc
> +The {sco} applies your additional annotations and labels to the manifests that you specify in the `ClusterInstance` additional resource.
Can this be rephrased?
> The {sco} applies your `additional` ... in the ClusterInstance `additional` resource.

2024-12-05 14:32 UTC, amolnar-rh commented on mce_acm_integration/siteconfig/siteconfig_installation_templates.adoc
> +--
Sorry, I was jumping between ACM and OCP PRs, I'm not even sure this works in the ACM build.

Btw, it groups together paragraphs/code snippets that would have different level of indentation without it, which would make it look like one is in the next step. I often have to use the dashes instead of the `+` signs when they just stop working. I find it's much more reliable than playing around with the `+`. I attached two pictures from my local preview, hopefully that demonstrates it better :)

- Without dashes:
![Screenshot From 2024-12-05 14-30-07](https://github.com/user-attachments/assets/84bc8c7e-f2ff-4311-a174-e761fed16ae3)

- With dashes:
![Screenshot From 2024-12-05 14-30-35](https://github.com/user-attachments/assets/ddb9fc8f-8bc7-436a-a4ea-0ba086b043ca)

2024-12-05 14:33 UTC, amolnar-rh commented on mce_acm_integration/siteconfig/siteconfig_installation_templates.adoc
> +The {sco} applies your additional annotations and labels to the manifests that you specify in the `ClusterInstance` additional resource.
Updated!

2024-12-05 14:39 UTC, amolnar-rh commented on mce_acm_integration/siteconfig/siteconfig_installation_templates.adoc
> +----
It is a concept section but we need to include how to verify that the labels/annotations are applied. Applying extraAnnotations/extraLabels is not part of any of the procedures so not sure how to better structure it :/

2024-12-05 14:53 UTC, sakhoury commented
/lgtm

2024-12-06 15:14 UTC, dockerymick requested changes
Sorry I reviewed this yesterday but forgot to click Submit review

2024-12-06 15:14 UTC, dockerymick commented on mce_acm_integration/siteconfig/siteconfig_installation_templates.adoc
> +View the following example application of extraAnnotations and extraLabels:
```suggestion
View the following example application of `extraAnnotations` and `extraLabels`:
```

2024-12-06 15:14 UTC, dockerymick commented on mce_acm_integration/siteconfig/siteconfig_installation_templates.adoc
> +----
Thanks for explaining why you use the two dashes. It's best to skip a line for the command to render correctly. As it relates to the step, maybe we can use a bullet point instead of an ordered step? What are your thoughts?
```suggestion
. You can verify that your additional labels are applied by running the following command:

+
[source,terminal]
----
oc get managedclusters example-sno -ojsonpath='{.metadata.labels}' | jq
----
```

2024-12-06 16:11 UTC, amolnar-rh commented on mce_acm_integration/siteconfig/siteconfig_installation_templates.adoc
> +----
I like it, updated it with bullet points!

2024-12-06 17:44 UTC, dockerymick commented on mce_acm_integration/siteconfig/siteconfig_installation_templates.adoc
> +--
```suggestion
[source,terminal]
----
oc get bmh example-sno.example.redhat.com -n example-sno -ojsonpath='{.metadata.annotations}' | jq
----

View the following example of applied annotations:

.Example applied annotation
[source,json]
----
{
  "myNodeAnnotation": "success",
  ...
}
----
```

2024-12-06 17:50 UTC, dockerymick commented on mce_acm_integration/siteconfig/siteconfig_installation_templates.adoc
> +----
So I made a commit to remove the two dashes. After doing that, the alignment appears as this now
<img width="1129" alt="Screenshot 2024-12-06 at 12 48 06 PM" src="https://github.com/user-attachments/assets/0aa5931a-3b38-41f7-a6f5-31995a8f9858">

maybe we should add the dashes back

2024-12-06 17:59 UTC, dockerymick approved these changes

2024-12-06 17:59 UTC, dockerymick commented on mce_acm_integration/siteconfig/siteconfig_installation_templates.adoc
> +----
```suggestion
+
--
[source,terminal]
----
oc get managedclusters example-sno -ojsonpath='{.metadata.labels}' | jq
----

View the following example of applied labels:

.Example applied labels
[source,json]
----
{
  "common": "true",
  "group-du": "",
  ...
}
----
--

* You can verify that your additional annotations are applied by running the following command:

+
--
[source,terminal]
----
oc get bmh example-sno.example.redhat.com -n example-sno -ojsonpath='{.metadata.annotations}' | jq
----

View the following example of applied annotations:

.Example applied annotation
[source,json]
----
{
  "myNodeAnnotation": "success",
  ...
}
----
--
```

2024-12-09 15:26 UTC, amolnar-gh commented on mce_acm_integration/siteconfig/siteconfig_installation_templates.adoc
> +----
Added them back in, should look good now.

2024-12-09 15:27 UTC, merged

2024-12-09 15:31 UTC, dockerymick commented on mce_acm_integration/siteconfig/siteconfig_installation_templates.adoc
> +View the following example application of extraAnnotations and extraLabels:
@amolnar-rh will you monospace the parameters here?