https://issues.redhat.com/browse/ACM-13028
open-cluster-management/rhacm-docs pull request #7247
Opened 2024-11-18 19:38 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-13028

2024-11-18 20:23 UTC, sahare requested changes

2024-11-18 20:23 UTC, sahare commented on release_notes/known_issues_continuity.adoc
> +
Based on the table here https://github.com/stolostron/cluster-backup-operator?tab=readme-ov-file#oadp-version-relationship , ACM 2.10.4 uses OADP 1.4. ACM 2.10 uses OADP 1.3 so I think this text needs to be updated according to the instructions in the Jira issue.

2024-11-19 19:18 UTC, sahare approved these changes
Looks good, Thanks!

2024-11-20 19:01 UTC, swopebe requested changes

2024-11-20 19:01 UTC, swopebe commented on release_notes/known_issues_continuity.adoc
> +
**Comma here:**

_1.4, which_

**Recommend changing:**

To use the supported backup and restore function, move to...

Use **{acm-short}** this deep into the file (for conciseness)

2024-11-20 19:04 UTC, swopebe commented on release_notes/known_issues_continuity.adoc
> +
I would put the OCP and ACM version in the title and also use the shortened version of the conref. Since this is a known issue on a fix, it is worth mentioning early.

2024-12-02 14:58 UTC, oafischer approved these changes

2024-12-02 15:05 UTC, merged

2024-12-02 15:19 UTC, swopebe commented on release_notes/known_issues_continuity.adoc
> +
This has not changed in one spot:

Use {acm-short} this deep into the file (for conciseness)

Otherwise this looks good.

2024-12-02 15:24 UTC, swopebe commented on release_notes/known_issues_continuity.adoc
> +
Looks like it was merged without my review, so will bring that up on slack. This is a small change; I will jsut remind that we use the shortened version of conrefs in the files this long--though I think this is in the guides.

2024-12-02 18:43 UTC, jc-berger commented on release_notes/known_issues_continuity.adoc
> +
@swopebe I can make changes before closing the Jira. 

All the conrefs I've used here in this content are the short conrefs. Am I missing something?

2024-12-05 16:54 UTC, swopebe commented on release_notes/known_issues_continuity.adoc
> +
line 39: `{acm} 2.10.4.` and after we shorten the ones before.