https://issues.redhat.com/browse/ACM-15155
open-cluster-management/rhacm-docs pull request #7281
Opened 2024-11-25 19:08 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-15155

2024-11-25 19:19 UTC, swopebe requested changes

2024-11-25 19:19 UTC, swopebe commented on clusters/release_notes/mce_errata.adoc
> +* Fixes an issue where the `Spokes` continue to display in Discovery UI. (https://issues.redhat.com/browse/ACM-15010[ACM-15010])
We don't use UI in ACM, we use "console" and we also don't write Spokes, these are managed clusters. The developers will write this, we have to know to change the terms.

2024-11-25 19:19 UTC, swopebe commented on clusters/release_notes/mce_errata.adoc
> +
Let's reduce the same robotic language "Fixes an issue where" so not each of these sound the same. Also are these actual code elements?

2024-11-25 19:19 UTC, swopebe commented on clusters/release_notes/mce_errata.adoc
> +* Fixes an issue where the `Spokes` continue to display in Discovery UI. (https://issues.redhat.com/browse/ACM-15010[ACM-15010])
DISCOVERY UI? I am not sure that is what we mean here.

2024-11-25 19:19 UTC, swopebe commented on clusters/release_notes/mce_errata.adoc
> +* Fixes an issue where the *Clear all filters* button does not work. (https://issues.redhat.com/browse/ACM-15277[ACM-15277])
Fixes an error with the  *Clear all filters* button. (An example of re-wording)

2024-11-25 19:19 UTC, swopebe commented on clusters/release_notes/mce_errata.adoc
> +* Fixes an issue where the `Spokes` continue to display in Discovery UI. (https://issues.redhat.com/browse/ACM-15010[ACM-15010])
DO we mean discovery page?

2024-11-25 19:19 UTC, swopebe commented on clusters/release_notes/mce_errata.adoc
> +
We switch tense here at times. Please see previous release notes. 

is stuck in a type of `progressing` state. (really weird line, what are we trying to say here?)

Stuck in the `progressing` status (or stage)... is usually how tech writers would word a status.

Again, you have to rewrite most of what you get to make it understandable to the user...and that means we have to have some level of understanding about what we are trying to say.

2024-11-25 19:25 UTC, swopebe commented on clusters/release_notes/mce_errata.adoc
> +* Fixes an issue where the `Spokes` continue to display in Discovery UI. (https://issues.redhat.com/browse/ACM-15010[ACM-15010])
I really don't understand this, because do we not want managed clusters to show on the Discovery page (?). Let's check on that by looking deeper at the developer bug.

**Fixes problem with managed clusters erroneously displaying on the Discovery page in the console.** (???)

But again, let's see what we are trying to say here because is the error that they appear or that they were removed and they appear. If that is the case, we need to specify.

2024-11-25 19:25 UTC, swopebe commented on clusters/release_notes/mce_errata.adoc
> +* Fixes an issue where the `Spokes` continue to display in Discovery UI. (https://issues.redhat.com/browse/ACM-15010[ACM-15010])
see above comment on this; it's confusing to me :-)

2024-11-25 19:27 UTC, swopebe commented on clusters/release_notes/mce_errata.adoc
> +
Check in the issue, but I think we are trying to say that the `cluster-proxy-addon` resource(??) is stuck in the `Progressing` state.

2024-11-25 20:15 UTC, jc-berger commented on clusters/release_notes/mce_errata.adoc
> +
Thanks, Brandi! So, I think the revision works, let me know what you think. 

Reading the Jira, it says the state is "progressing... mca and work configs mismatch" 

I've never seen a state that long nor a state with ellipses in it. Anyway, I think `Progressing` captures what it means and the JIra can give the user more detail, but let me know if you think the rewrite fixes your concern with it being confusing.

2024-11-25 22:47 UTC, dockerymick commented on clusters/release_notes/mce_errata.adoc
> +* Prevents the managed clusters from being displayed in the Discovery tab in the console after updating valid OpenShift Cluster Manager (OCM) credentials to invalid ones. (https://issues.redhat.com/b
@jc-berger Could you also remove "(OCM). There is also a conref for this product name
```suggestion
* Prevents the managed clusters from being displayed in the _Discovery_ tab in the console after updating valid {ocm} credentials to invalid ones. (https://issues.redhat.com/browse/ACM-15010[ACM-15010])
```

2024-11-25 22:47 UTC, dockerymick commented on clusters/release_notes/mce_errata.adoc
> +* Fixes an error with the  *Clear all filters* button. (https://issues.redhat.com/browse/ACM-15277[ACM-15277])
Removing extra space
```suggestion
* Fixes an error with the *Clear all filters* button. (https://issues.redhat.com/browse/ACM-15277[ACM-15277])
```

2024-11-26 00:11 UTC, swopebe commented on clusters/release_notes/mce_errata.adoc
> +* Stops the `Detach clusters` action from deleting hosted clusters.  (https://issues.redhat.com/browse/ACM-15018[ACM-15018])
```suggestion
* Stops the `Detach clusters` action from deleting hosted clusters. (https://issues.redhat.com/browse/ACM-15018[ACM-15018])
```

2024-11-26 00:12 UTC, swopebe approved these changes

2024-11-26 00:32 UTC, merged

2024-11-26 02:23 UTC, rhaignere commented
/approve