ACM-14360: importing cluster resources
open-cluster-management/rhacm-docs pull request #7294
Opened 2024-11-28 11:45 UTC by danielerez

Following https://github.com/stolostron/rhacm-docs/pull/7121, added further information and steps for the flow of moving a managed cluster between ACM hubs (i.e. by importing cluster resources).

2024-11-28 11:47 UTC, danielerez commented
/cc @jc-berger 
/cc @carbonin
/cc @ddmitrie

2024-12-02 19:55 UTC, swopebe commented
@danielerez thanks for the PR. We normally like to move doc ourselves because it impacts the build and we set up each book as similarly as possible to the larger collection. We welcome smaller PRs from developers, for sure.

Can you point us to the issue where this move was requested? We also want to understand what we are doing to the content and why, so that is why we are asking for the issue.

**Please see the playbook for the ACM Team (Doc section) here:** https://docs.google.com/document/d/1YTqpZRH54Bnn4WJ2nZmjaCoiRtqmrc2w6DdQxe_yLZ8/edit?tab=t.0#heading=h.9fvyr2rdriby

I think @oafischer (who may already have your issue; but if not, please open one?) needs to be aware of this PR as the writer for this area to ensure it is tracked in the issue, written within standards. We can leave Jake to finalize with the peer review.

2024-12-02 22:02 UTC, danielerez commented
> @danielerez thanks for the PR. We normally like to move doc ourselves because it impacts the build and we set up each book as similarly as possible to the larger collection. We welcome smaller PRs from developers, for sure.
> 
> Can you point us to the issue where this move was requested? We also want to understand what we are doing to the content and why, so that is why we are asking for the issue.

So this change is required for expanding the details and steps of the flow.
I.e. addressing the content added prior feature completeness: https://github.com/stolostron/rhacm-docs/pull/7121/files#r1816294651
@oafischer Let me know if we need to create a new ticket specifically for that. Or, can we just reuse the original [issue](https://issues.redhat.com/browse/ACM-14360)? 

> 
> **Please see the playbook for the ACM Team (Doc section) here:** https://docs.google.com/document/d/1YTqpZRH54Bnn4WJ2nZmjaCoiRtqmrc2w6DdQxe_yLZ8/edit?tab=t.0#heading=h.9fvyr2rdriby
> 
> I think @oafischer (who may already have your issue; but if not, please open one?) needs to be aware of this PR as the writer for this area to ensure it is tracked in the issue, written within standards. We can leave Jake to finalize with the peer review.
> 
> (I see a closed issue connected to a different PR, but we do need an active issue on such content changes.)

2024-12-02 22:46 UTC, swopebe commented
To move content after the doc issue is closed, yes, we do need a new issue. If it was a small change, no biggie. Moving content impacts the build and the writer has more editing (usually) in these cases. This is especially true if it spans versions. Thanks so much.

2024-12-02 23:33 UTC, danielerez commented
> To move content after the doc issue is closed, yes, we do need a new issue. If it was a small change, no biggie. Moving content impacts the build and the writer has more editing (usually) in these cases. This is especially true if it spans versions. Thanks so much.

Sure, created a new ticket for this change: https://issues.redhat.com/browse/ACM-16051

2024-12-03 10:36 UTC, oafischer commented on clusters/cluster_lifecycle/import_ocp.adoc
> +- `Secret` (admin-kubeconfig and bmc-secret)
Are these 3 different resources, or what do the brackets indicate in this case?

2024-12-03 10:44 UTC, oafischer commented on clusters/cluster_lifecycle/import_ocp.adoc
> +=== Store resources from the source hub
What is the goal with the 4 new topics you added? Are these all the steps required to import the cluster resources and then clean up the remaining ones on the source hub? If so, these 4 topics need to be converted to steps and added to two topics, one for importing and one for deleting.

If you don't mind I can go ahead and rearrange it directly in the PR.

2024-12-03 10:49 UTC, oafischer requested changes
Thanks for creating the PR and the new issue @danielerez. The content looks good, but we need to rearrange and edit a bunch of stuff to conform with style and company guidelines. We need overarching topics that describe the user goals.

In this case I can see 2 goals, one being importing the resource, and the second one being deleting/cleaning up. The topics you added would be considered steps to reach those goal, so we need to add them to those 2 topics I mentioned.

I'm happy to do this directly in the PR if you don't mind.

2024-12-03 10:56 UTC, danielerez commented on clusters/cluster_lifecycle/import_ocp.adoc
> +- `Secret` (admin-kubeconfig and bmc-secret)
So these are just for implying the names of the secrets.
I.e. for a managed cluster in namespace 'spoke':
* Secret with name 'spoke-admin-kubeconfig'
* Secret with name 'spoke-bmc-secret' (optional - if using BMH)
Not sure if we need to include these full details, so added the brackets as a hint to store all required secrets.

2024-12-03 11:00 UTC, danielerez commented on clusters/cluster_lifecycle/import_ocp.adoc
> +=== Store resources from the source hub
Sure, this is just a suggestion, feel free to rearrange it as you see fit.
Anyway, right, maybe it can be converted into an import step and a cleanup step (destroy cluster).
Though I suppose the import step should still include these inner-steps, just to make it clearer.
I.e.
1. import:
1.1. store
1.2. modify
1.3. detach
1.4. apply on target
2. cleanup (destroy)

2024-12-03 11:03 UTC, oafischer commented on clusters/cluster_lifecycle/import_ocp.adoc
> +- `Secret` (admin-kubeconfig and bmc-secret)
We generally try avoid brackets as per our style guide, though if necessary we can keep them.

Are those 2 secrets the only ones you can import? Meaning there are more but you can only import those 2?

Or are we just listing the 2 that exist for clarity?

2024-12-03 11:04 UTC, oafischer commented on clusters/cluster_lifecycle/import_ocp.adoc
> +=== Store resources from the source hub
Sounds good, I'll go ahead and rearrange it as needed and make some edits while I'm at it. I'll let you know when I'm done so you can take another look afterwards.

2024-12-03 11:11 UTC, danielerez commented
> Thanks for creating the PR and the new issue @danielerez. The content looks good, but we need to rearrange and edit a bunch of stuff to conform with style and company guidelines. We need overarching topics that describe the user goals.
> 
> In this case I can see 2 goals, one being importing the resources, and the second one being deleting/cleaning up. The topics you added would be considered steps to reach those goal, so we need to add them to those 2 topics I mentioned.
> 
> I'm happy to do this directly in the PR if you don't mind. Just let me know what you prefer.

Sure, this is just a suggestion, feel free to rearrange it as you see fit.
Anyway, right, maybe it can be converted into an import step and a cleanup step (destroy cluster).
Though I suppose the import step should still include these inner-steps, just to make it clearer.
E.g.
1. Import step:
1.1. Store resources
1.2. Modify resources
1.3. Detach cluster from source hub
1.4. Apply resources on target hub
2. Cleanup
Destroy cluster on source hub

2024-12-03 11:24 UTC, danielerez commented on clusters/cluster_lifecycle/import_ocp.adoc
> +- `Secret` (admin-kubeconfig and bmc-secret)
Potentially there could be more secrets, depending on the exact deployment.
I've emphasized these secrets just for clarity indeed, especially as the `admin-kubeconfig` Secret is always mandatory.
Feel free to illustrate it in a more conventional way instead of the brackets:) Maybe a short note is more adhering to our style guide(?)

2024-12-03 11:37 UTC, oafischer commented on clusters/cluster_lifecycle/import_ocp.adoc
> +- `Secret` (admin-kubeconfig and bmc-secret)
A note might be better but I need to play around with it a bit and see what works best. I'll tackle this along with the rearranging.

2024-12-03 17:02 UTC, danielerez commented on clusters/cluster_lifecycle/import_ocp.adoc
> +=== Copying and applying managed cluster resources
nit: instead of 'Copying', maybe 'Storing' or 'Saving' is a clearer terminology?

2024-12-03 17:02 UTC, danielerez commented on clusters/cluster_lifecycle/import_ocp.adoc
>  . Get the `Agent` resource from your source hub cluster by running the following command. Replace values where needed:
Can we emphasize here that it should be performed for all resources? I.e. just since, in first glance, it looks like only 'Agent' is required.

2024-12-03 17:03 UTC, oafischer commented on clusters/cluster_lifecycle/import_ocp.adoc
>  . Get the `Agent` resource from your source hub cluster by running the following command. Replace values where needed:
Good call, I'll add that.

2024-12-03 17:07 UTC, oafischer commented on clusters/cluster_lifecycle/import_ocp.adoc
>  . Get the `Agent` resource from your source hub cluster by running the following command. Replace values where needed:
Just to clarify, does every resource have to be copied or are there cases where a user might only need to or want to copy some resources?

What do you think about making the resource name in the command a variable as well?

2024-12-03 17:12 UTC, oafischer commented on clusters/cluster_lifecycle/import_ocp.adoc
> +=== Copying and applying managed cluster resources
I'm OK with storing or saving. We should build a connection to the previous paragraph where we explain this feature. We used copying there, but I can change that to storing as well if it's more accurate.

2024-12-03 17:14 UTC, danielerez commented on clusters/cluster_lifecycle/import_ocp.adoc
> +=== Copying and applying managed cluster resources
Sure, makes sense.

2024-12-03 17:16 UTC, danielerez commented on clusters/cluster_lifecycle/import_ocp.adoc
>  . Get the `Agent` resource from your source hub cluster by running the following command. Replace values where needed:
Yeah, good idea. Some of the resources are mandatory, a few are optional depending on the env (e.g. NMStateConfig, AgentClassification). So right, we can simply use a var for the name.

2024-12-03 17:21 UTC, oafischer commented on clusters/cluster_lifecycle/import_ocp.adoc
>  . Get the `Agent` resource from your source hub cluster by running the following command. Replace values where needed:
If some are mandatory we need to state that. We usually use a table with a column that reads optional or required for that. I will convert the resource list to table and add that column. For the resources where it depends on the environment, can you provide a one or two sentence explanation of what it depends on? We can add that to a Description column in the table.

2024-12-03 17:34 UTC, danielerez commented on clusters/cluster_lifecycle/import_ocp.adoc
>  . Get the `Agent` resource from your source hub cluster by running the following command. Replace values where needed:
Well, not sure if it's the right place to explain this thoroughly, as every resource has its responsibility.
But let's see:
- `Agent` - Mandatory
- `AgentClassification` - Optional (requires to classify Agents by providing a filter query)
- `AgentClusterInstall` - Mandatory
- `BareMetalHost` - Optional (required when using `baremetal` platform)
- `ClusterDeployment` - Mandatory
- `InfraEnv` - Mandatory
- `NMStateConfig` - Optional (network configuration to apply on the hosts)
- `ManagedCluster` - Mandatory
- `Secret` - `admin-kubeconfig` is Mandatory, `bmc-secret` is Optional (required when using BareMetalHosts)

2024-12-03 17:41 UTC, oafischer commented on clusters/cluster_lifecycle/import_ocp.adoc
>  . Get the `Agent` resource from your source hub cluster by running the following command. Replace values where needed:
Thanks for the list, let me know if the table looks good to you.

2024-12-03 17:46 UTC, danielerez commented
Looks good to me. Thanks @oafischer !

2024-12-03 17:49 UTC, oafischer commented
I'll hand this over for peer review now and approve it once any last comments are addressed. I'll let you know when you can go ahead and merge.

2024-12-03 17:50 UTC, danielerez commented
> I'll hand this over for peer review now and approve it once any last comments are addressed. I'll let you know when you can go ahead and merge.

Sounds good. Many thanks again!

2024-12-03 18:32 UTC, jc-berger approved these changes
/lgtm

2024-12-03 18:32 UTC, jc-berger commented on clusters/cluster_lifecycle/import_ocp.adoc
> +. Get your resources from your source hub cluster by running the following command. Repeat the command for every resource you want to import by replacing `<resource_name>` with the name of the resour
These seem like several steps because there's multiple actions listed here. What do you think about this? 

```suggestion
. Get your resources from your source hub cluster by running the following command:
```

2024-12-03 18:32 UTC, jc-berger commented on clusters/cluster_lifecycle/import_ocp.adoc
> +. Remove the `ownerReferences` property from the following resources by running the following commands:
```suggestion
. Repeat the command for every resource you want to import by replacing `<resource_name>` with the name of the resource. Replace other values where needed.
. Remove the `ownerReferences` property from the following resources by running the following commands:
```

2024-12-03 18:32 UTC, jc-berger commented on clusters/cluster_lifecycle/import_ocp.adoc
> +. Remove the `ownerReferences` property from the following resources by running the following commands:
I see why you had "Get resources, repeat command, replace other values" all as one command, so feel free to keep it as one. See if you think this flow makes it a little easier to read. 

We could also make the "Repeat the. command for every resource..." as a substep, like this: 
```suggestion
.. Repeat the command for every resource you want to import by replacing `<resource_name>` with the name of the resource. Replace other values where needed.
. Remove the `ownerReferences` property from the following resources by running the following commands:
```

2024-12-03 18:32 UTC, jc-berger commented on clusters/cluster_lifecycle/import_ocp.adoc
> +. Get your resources from your source hub cluster by running the following command. Repeat the command for every resource you want to import by replacing `<resource_name>` with the name of the resour
Reading the rest of the procedure, I see you often end a step with "replace other values where needed" which is good for consistency. 

So to determine if it should be multiple steps, I guess we need to decide if "Repeat the command for every resource you want to import by replacing `<resource_name>` with the name of the resource." is a separate action or part of the one action where users get their resources from the source hub cluster. 

It seems to me like a second action, so maybe it should be its own step, thoughts?

2024-12-04 10:46 UTC, oafischer commented on clusters/cluster_lifecycle/import_ocp.adoc
> +. Remove the `ownerReferences` property from the following resources by running the following commands:
I can see it both ways, but I like your sub-step solution. I think I'll go with that.

2024-12-04 10:57 UTC, oafischer approved these changes
All comments addressed, feel free to merge @danielerez.

2024-12-04 12:24 UTC, danielerez commented
/approve

2024-12-04 12:28 UTC, danielerez commented
> All comments addressed, feel free to merge @danielerez.

@oafischer Seems I'm missing the `approved` label for merge. Can you maybe approve?

2024-12-04 12:37 UTC, oafischer commented
/approve

2024-12-04 12:38 UTC, oafischer commented
I can just merge it as well if you are happy with everything @danielerez

2024-12-04 12:42 UTC, merged