https://issues.redhat.com/browse/ACM-16124
open-cluster-management/rhacm-docs pull request #7340
Opened 2024-12-11 19:48 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-16124

2024-12-11 19:49 UTC, jc-berger commented on clusters/cluster_lifecycle/release_image_connected.adoc
> +  caCerts: <building a secure HTTPS connection>
Dev reviewers, 

To be consistent with the other data fields where we give values, I wanted to provide a value for the CaCert. Is this correct?

2024-12-11 19:59 UTC, xiangjingli commented on clusters/cluster_lifecycle/release_image_connected.adoc
> +  caCerts: <building a secure HTTPS connection>
Yeah, it looks good to provide a value for the caCert filed. How about this description

```
caCert: < The CA certificates for building a secure HTTPS connection>
```

2024-12-11 20:05 UTC, jc-berger commented on clusters/cluster_lifecycle/release_image_connected.adoc
> +  caCerts: <building a secure HTTPS connection>
Great, I'll make that change shortly, thank you!

2024-12-11 20:45 UTC, xiangjingli commented
/lgtm

2024-12-12 18:41 UTC, dockerymick requested changes

2024-12-12 18:41 UTC, dockerymick commented on clusters/cluster_lifecycle/release_image_connected.adoc
>  ----
Its unusual to have two values for a parameter. I suggest that you use callouts here 
```suggestion
  channel: <1>
  insecureSkipVerify: <2> 
  caCerts: <3> 
  ----
  <1> Choose to use either of the supported values `fast` or `stable`.
  <2> Specify `insecureSkipVerify` to `true` for building the insecure connection. The supported values are `true` or `false`.
  <3> List the certified authority (CA) certificates for building a secure HTTPS connection.
```

2024-12-12 18:41 UTC, dockerymick commented on clusters/cluster_lifecycle/release_image_connected.adoc
> +.. Specify the `caCerts` for building the secure HTTPS connection.
Since these are now mentioned in the suggested callout, is it necessary to add this info here as steps?

2024-12-12 19:08 UTC, dockerymick commented on clusters/cluster_lifecycle/release_image_connected.adoc
> +  <3> List the certified authority (CA) certificates for building a secure HTTPS connection.
the parameter on line 20 should also be a callout. There are some alignment issues too. Seems like there should be a plus sign on line 12 then the YAML begins on line 13. the lines at the end of the yaml is not aligned with the beginning either
<img width="991" alt="Screenshot 2024-12-12 at 2 05 58 PM" src="https://github.com/user-attachments/assets/bf33978f-6a19-49fd-8a16-f00b9a2d3bca" />

2024-12-12 19:16 UTC, dockerymick commented on clusters/cluster_lifecycle/release_image_connected.adoc
> +.. Specify the `caCerts` for building the secure HTTPS connection.
@xiangjingli

2024-12-12 19:49 UTC, xiangjingli commented on clusters/cluster_lifecycle/release_image_connected.adoc
> +  <3> List the certified authority (CA) certificates for building a secure HTTPS connection.
yes, it looks good to me

2024-12-12 20:41 UTC, dockerymick commented on clusters/cluster_lifecycle/release_image_connected.adoc
>  ----
Need to skip a line here
```suggestion

+
[source,yaml]
----
```

2024-12-12 20:43 UTC, dockerymick commented on clusters/cluster_lifecycle/release_image_connected.adoc
>  ----
Add a new line break on line 42 and add the `[source,bash]` after the plus sign

2024-12-12 20:49 UTC, dockerymick commented on clusters/cluster_lifecycle/release_image_connected.adoc
> +[source,bash]
```suggestion

+
[source,bash] 
```

2024-12-12 20:56 UTC, dockerymick approved these changes
this looks good to me. After you receive dev approval, feel free to merge

2024-12-12 21:55 UTC, jc-berger commented on clusters/cluster_lifecycle/release_image_connected.adoc
> +<1> Get this URL by forking the `acm-hive-openshift-releases` repository URL.
@xiangjingli am I correct that users get the URL by forking the repo URL? Thanks!

2024-12-12 22:11 UTC, xiangjingli commented on clusters/cluster_lifecycle/release_image_connected.adoc
> +<1> Get this URL by forking the `acm-hive-openshift-releases` repository URL.
The use case is this 

Here is the default acm-hive-openshift-release repo. It provides all available  clusterImageSet resources with default visible settings. when provisioning a new cluster, users can choose which OCP version to be installed. 
https://github.com/stolostron/acm-hive-openshift-releases
 
If user want to customize the default clusterImageSet visible properties so that they can choose different ocp versions 

They need to do
- fork the default acm-hive-openshift-release repo to another repo they own,
- Then they are able to update clusterImageSet properties 
- specify the new forked acm-hive-openshift-release repo in the configmap

2024-12-13 16:17 UTC, merged