https://issues.redhat.com/browse/ACM-15832 Obs note update
open-cluster-management/rhacm-docs pull request #7342
Opened 2024-12-12 14:32 UTC by oafischer

Also for 2.12, 2.11, and 2.10.

2024-12-13 11:19 UTC, jacobbaungard approved these changes
/lgtm

2024-12-17 14:56 UTC, dockerymick requested changes

2024-12-17 14:56 UTC, dockerymick commented on observability/observability_alerts.adoc
> +- To silence a {acm-short} alert, you must have access to the `alertmanager` pods, for example, `observability-alertmanager-0`, in the `open-cluster-management-observability` namespace. For example,
There are quite a few commas. @oafischer what do you think about this suggestion? I imagine the command might also need to be updated since it's a specific example. I'm not sure how the command might change tho.
```suggestion
- To silence a {acm-short} alert, you must have access to the `alertmanager` pods in the `open-cluster-management-observability` namespace. For example, enter the following command in the `observability-alertmanager-0` pod terminal to silence `SampleAlert`: 

+
[source,bash]
----
amtool silence add --observability-alertmanager-0.url="http://localhost:9093" --author="user" --comment="Silencing sample alert" alertname="SampleAlert"
----
```

2024-12-17 15:29 UTC, oafischer commented on observability/observability_alerts.adoc
> +- To silence a {acm-short} alert, you must have access to the `alertmanager` pods, for example, `observability-alertmanager-0`, in the `open-cluster-management-observability` namespace. For example,
I like your suggestion, I'll go with that. Thanks!

2024-12-17 15:29 UTC, oafischer commented on observability/observability_alerts.adoc
> +- To silence a {acm-short} alert, you must have access to the `alertmanager` pods, for example, `observability-alertmanager-0`, in the `open-cluster-management-observability` namespace. For example,
@jacobbaungard Let us know if the command needs to be updated as well.

2024-12-17 16:43 UTC, dockerymick approved these changes
Thanks for considering my suggestion! Let's just double check the command with @jacobbaungard. Approving this PR

2024-12-18 08:42 UTC, jacobbaungard requested changes

2024-12-18 08:42 UTC, jacobbaungard commented on observability/observability_alerts.adoc
> +amtool silence add --observability-alertmanager-0.url="http://localhost:9093" --author="user" --comment="Silencing sample alert" alertname="SampleAlert"
The original command is the correct one. This here is incorrect.

2024-12-18 15:31 UTC, oafischer commented on observability/observability_alerts.adoc
> +amtool silence add --observability-alertmanager-0.url="http://localhost:9093" --author="user" --comment="Silencing sample alert" alertname="SampleAlert"
Updated

2024-12-18 15:34 UTC, jacobbaungard commented on observability/observability_alerts.adoc
> +amtool silence add --alertmanager.url="http://localhost:9093" --author="user" --comment="Silencing sample alert" alertname="SampleAlert"
We're repeating this command twice, here and on L211 below.

2024-12-18 15:43 UTC, jacobbaungard approved these changes

2024-12-18 15:48 UTC, merged