https://issues.redhat.com/browse/ACM-16028
open-cluster-management/rhacm-docs pull request #7348
Opened 2024-12-16 19:47 UTC by jc-berger

See Jira: https://issues.redhat.com/browse/ACM-15051

2024-12-17 17:36 UTC, rhaignere approved these changes
lgtm
thanks!

2024-12-17 17:47 UTC, swopebe commented on release_notes/acm_errata.adoc
> +* Resolves how the policy shows an unknown status for the local cluster.  (link:https://issues.redhat.com/browse/ACM-13720[ACM-13720])
If the status is unknown--we should code it, unless you mean in general an unknown status (not something we typically see in tech doc).

2024-12-17 17:47 UTC, swopebe commented on release_notes/acm_errata.adoc
> +* Resolves how the policy shows an unknown status for the local cluster.  (link:https://issues.redhat.com/browse/ACM-13720[ACM-13720])
Throughout the doc here there are a few double spaces, so please check for that.

2024-12-17 17:48 UTC, swopebe commented on release_notes/acm_errata.adoc
> +* Prevents the *observability-rbac-query-proxy-**  pods from crashing with an unrecoverable error. (link:https://issues.redhat.com/browse/ACM-15051[ACM-15051])
check your coding on the resource here, please?

2024-12-17 17:50 UTC, swopebe commented on release_notes/acm_errata.adoc
> +* Makes the `OperatorPolicy` compliant so that it can approve all comma-separated values (CSVs) in the install plan. (link:https://issues.redhat.com/browse/ACM-14540[ACM-14540])
install we cannot use as a noun/adjective, so let's revisit the style manual here: https://www.ibm.com/docs/en/ibm-style?topic=word-usage#i

2024-12-17 17:50 UTC, swopebe commented on release_notes/acm_errata.adoc
> +* Updates the image, `osImageVersion` in the infrastructure operator environment so that it can update the `isoDownloadURL`. (link:https://issues.redhat.com/browse/ACM-14600[ACM-14600])
missing comma after image name

2024-12-17 17:51 UTC, swopebe commented on release_notes/acm_errata.adoc
> +* Configure the Alertmanager high availability (HA) so that Prometheus can send requests to all Alertmanagers. (link:https://issues.redhat.com/browse/ACM-16212[ACM-16212])
Configures? Coding missng on Alertmanager? (Also please check the case on that one--same for both instances)

2024-12-17 17:52 UTC, swopebe requested changes
number of comments to address. TY fro taking this.

2024-12-17 18:48 UTC, rhaignere requested changes
Team requested that ACM-13201 be removed from the ACM 2.11.4 advisory - additional issues found. Please remove the text for this Jira from the release notes. Thank you!!

2024-12-17 19:45 UTC, jc-berger commented on release_notes/acm_errata.adoc
> +* Configure the Alertmanager high availability (HA) so that Prometheus can send requests to all Alertmanagers. (link:https://issues.redhat.com/browse/ACM-16212[ACM-16212])
Looking at our Observability Docs, we write it as Alertmanager, no monospace/coding: https://docs.redhat.com/en/documentation/red_hat_advanced_cluster_management_for_kubernetes/2.12/html-single/observability/index#obs-open-components 

In the Observability Docs, we link to the Prometheus Alertmanager documentation which also writes it as Alertmanager: https://prometheus.io/docs/alerting/latest/alertmanager/ 

However, in the Observability docs, when we refer to it as a component area, we will write it as `alertmanager`: https://docs.redhat.com/en/documentation/red_hat_advanced_cluster_management_for_kubernetes/2.12/html-single/observability/index#persistent-stores-observability 

I think in this instance, it would be Alertmanager high availability (HA), but let me know if you think otherwise, thanks!

2024-12-17 19:49 UTC, jc-berger commented on release_notes/acm_errata.adoc
> +* Prevents the *observability-rbac-query-proxy-**  pods from crashing with an unrecoverable error. (link:https://issues.redhat.com/browse/ACM-15051[ACM-15051])
Yes, this was tricky, the asterisks is needed within the monospace, but it gave me rendering errors when I wrote out, `observability-rbac-query-proxy-*` 

When I used the * * to make it bold, it rendered fine and I thought that was allowed in this instance? 

Let me play around with it some more in my next commit, thanks!

2024-12-17 20:18 UTC, jc-berger commented on release_notes/acm_errata.adoc
> +* Prevents the *observability-rbac-query-proxy-**  pods from crashing with an unrecoverable error. (link:https://issues.redhat.com/browse/ACM-15051[ACM-15051])
Looking at some of our docs, in the yaml files we'll use quotes around text that ends in *, so it'd be, "observability-rbac-query-proxy-*" but I thought that'd only be for content within a yaml sample 

Anyway, I added the \ to help with spacing, as I read that as a workaround. If you don't like that, I'll continue to troubleshoot!

2024-12-17 20:45 UTC, swopebe commented on release_notes/acm_errata.adoc
> +* Prevents the *observability-rbac-query-proxy-**  pods from crashing with an unrecoverable error. (link:https://issues.redhat.com/browse/ACM-15051[ACM-15051])
@jc-berger why are we doing anything more than `this` on the name of the pod? Is this a pod name?

No, we would not normally need to use quotation marks-- that is only is the quotation marks are part of the actual code. 

I am not sure what the goal is here, other than to code the pod name?

2024-12-17 20:54 UTC, swopebe commented on release_notes/acm_errata.adoc
> +* Configure the Alertmanager high availability (HA) so that Prometheus can send requests to all Alertmanagers. (link:https://issues.redhat.com/browse/ACM-16212[ACM-16212])
Ok, we don't need to use HA here, but we code alert manager in the paragraph you linked.
(If we aren't coding it in the tables, that is probably because they were created before peer reviews. Anything that is not simple English and part of code needs to be coded for globalization and accessibility. No one is gonna know that word when translated.)

So alertmanager needs to be coded. The only question is of the case, which engineers are sometimes also not consistent with. I will look at their PR.

2024-12-17 20:56 UTC, swopebe commented on release_notes/acm_errata.adoc
> +* Configure the Alertmanager high availability (HA) so that Prometheus can send requests to all Alertmanagers. (link:https://issues.redhat.com/browse/ACM-16212[ACM-16212])
When we do commits on the doc here, we should link to our doc issue. I see a developer bug is attached to the PR. Note for next time.

2024-12-17 21:04 UTC, swopebe commented on release_notes/acm_errata.adoc
> +* Configure the Alertmanager high availability (HA) so that Prometheus can send requests to all Alertmanagers. (link:https://issues.redhat.com/browse/ACM-16212[ACM-16212])
So while they are not always consistent with how they name it in their source, their resource:
https://github.com/stolostron/multicluster-observability-operator/blob/a3b803d90cfe4f8b88163afebf0474561e953511/operators/multiclusterobservability/manifests/base/alertmanager/kustomization.yaml#L12

`alertmanager` so we can just go with that. I will bring up the instances where we are not `coding` where we should in the next meeting as tech debt to fix.

2024-12-17 21:09 UTC, swopebe commented on release_notes/acm_errata.adoc
> +* Configure the Alertmanager high availability (HA) so that Prometheus can send requests to all Alertmanagers. (link:https://issues.redhat.com/browse/ACM-16212[ACM-16212])
https://github.com/stolostron/multicluster-observability-operator/tree/a3b803d90cfe4f8b88163afebf0474561e953511/operators/multiclusterobservability/manifests/base/alertmanager

Since it is the ACM alert manager, I think coding is best: https://github.com/stolostron/multicluster-observability-operator/tree/a3b803d90cfe4f8b88163afebf0474561e953511/operators/multiclusterobservability/manifests/base/alertmanager

2024-12-17 21:38 UTC, swopebe commented on release_notes/acm_errata.adoc
> +* Configures the Alertmanager high availability (HA) so that Prometheus can send requests to all Alertmanagers. (link:https://issues.redhat.com/browse/ACM-16212[ACM-16212])
```suggestion
* Configures the `alertmanager` high availability so that Prometheus can send requests to all _Alertmanagers_. (link:https://issues.redhat.com/browse/ACM-16212[ACM-16212]) 
```

2024-12-17 21:40 UTC, swopebe commented on release_notes/acm_errata.adoc
> +* Configures the Alertmanager high availability (HA) so that Prometheus can send requests to all Alertmanagers. (link:https://issues.redhat.com/browse/ACM-16212[ACM-16212])
Did we add high availability or was that part of the comment they left. Highlighted the proper name for now, but I want to see how ACM code is referring to the alert managers (plural).

2024-12-18 13:10 UTC, swopebe approved these changes

2024-12-18 13:14 UTC, swopebe commented on release_notes/acm_errata.adoc
> +* Prevents the `observability-rbac-query-proxy` pod from crashing with an unrecoverable error. (link:https://issues.redhat.com/browse/ACM-15051[ACM-15051])
Added the name here, but removed the wildcard *. If the user is not copying that, do we need it? Without knowing the purpose for it, we were adding it but it was messing up the format.

2024-12-18 13:35 UTC, merged