starting on RBAC updates for 2.0
open-cluster-management/rhacm-docs pull request #863
Opened 2020-07-08 19:00 UTC by dockerymick

https://github.com/open-cluster-management/backlog/issues/3214

2020-07-15 18:46 UTC, ckandag requested changes

2020-07-15 18:46 UTC, ckandag commented on security/rbac.adoc
> +Red Hat Advanced Cluster Management for Kubernetes supports several roles. Your role determines the actions that you can perform. Kubernetes offers role-based access control (RBAC) authorization mech
Red Hat Advanced Cluster Management for Kubernetes supports role based access control. Your role determines the actions that you can perform.  RBAC is based on the mechanisms provided in Kubernetes (openshift). For more information about RBAC, see the OpenShift _RBAC_ overview in the link:https://docs.openshift.com/container-platform/4.3/authentication/using-rbac.html[OpenShift Container Platform documentation]

Note To Mikela:  Can you pls change the whole para at line 4 to like above,  it appears we  carried over  some of this from mcm like  "grouping into teams", which is not correct anymore.

2020-07-15 18:46 UTC, ckandag commented on security/rbac.adoc
> +View the following RBAC tables for components in Red Hat Advanced Cluster Management for Kubernetes:
View the following RBAC tables for roles supported and access control enforced on them by components in Red Hat Advanced Cluster Management for Kubernetes:

2020-07-15 18:46 UTC, ckandag commented on security/rbac.adoc
> +| An user with cluster-wide binding to the cluster-manager-admin role is a Red Hat Advanced Cluster Management for Kubernetes super user, who can perform any action on the product resources.
An user with cluster-wide binding to the cluster-manager-admin role is a Red Hat Advanced Cluster Management for Kubernetes super user, who has all access to  product resources.

Note To Mikela:  trying to keep the wording similar to the cluster-admin  role

2020-07-15 18:46 UTC, ckandag commented on security/rbac.adoc
> +Some product resources are cluster-scoped and some are namespace-scoped. Users can create projects from OpenShift Container Platform, which gives administrator role permissions for the namespace. Vie
Some product resources are cluster-scoped and some are namespace-scoped. View the table list of the following role definitions that are supported in Red Hat Advanced Cluster Management for Kubernetes:

Note To Mikela :  I think the part about "Users can create projects from OpenShift Container Platform, which gives administrator role permissions for the namespace. "  should be in a seperate note by itself , perhaps at the end of this "Overview of roles" section

2020-07-15 18:46 UTC, ckandag commented on security/rbac.adoc
> +| An user with cluster binding to the managed-cluster-x role, has administrator access to `ManagedCluster “X”` resources.
An user with cluster binding to the managed-cluster-x role, has administrator access to `ManagedCluster “X”` custom resource.

Note to Mikela:  please change the "resources" at the end to "custom resource". ,  resource is singular.

2020-07-15 18:46 UTC, ckandag commented on security/rbac.adoc
> +| An user with cluster-wide binding to the managed-cluster-x role, has view access to `ManagedCluster “X”` resources.
An user with cluster binding to the managed-cluster-x role, has view access to `ManagedCluster “X”` custom resource.

Note to Mikela:  please change the "resources" at the end to "custom resource". ,  resource is singular.

2020-07-15 18:46 UTC, ckandag commented on security/rbac.adoc
> +| Users and groups with the subscription-admin role can create Git subscriptions that deploy resources to multiple namespaces. The resources are specified in Kubernetes resource YAMLs in the subscrib
Note to Mikela : If we are going to say "Users and groups" here for this role , then may be we should do the same for all the above roles in the table.  because the same applies to any or all roles

Also the note about "Project creator" here as below 
Any user  can create projects from OpenShift Container Platform, as creator of the project user is given  administrator role permissions to the project's namespace.

2020-07-15 18:46 UTC, ckandag commented on security/rbac.adoc
> +
We are missing the admin / edit / view roles  in the table

2020-07-15 18:46 UTC, ckandag commented on security/rbac.adoc
> +RBAC is implemented as APIs. When a user attempts an action and the `retrieve` API resource succeeds, the console displays the result. The default roles for `managedcluster` resources are admin, edit
Note To Mikela:   admin/edit/view roles need to be put in the table  of roles above  in "Overview of roles" section ,   to make it clear what all roles are used to work with ACM.  I strongly think just  a line like this inside a  para is not enough,  to make it apparent to the user. 

Perhaps , the entire param about RBAC enforcement could be removed and replaced with  a NOTE under "overview of roles" sections , under the note about "Project Creator"

2020-07-15 18:46 UTC, ckandag commented on security/rbac.adoc
> +
Note to Mikela : I know its repetitive right now , but there could be other resources added in future that may not have the same set of permissions.  So I would prefer to leave it like that.. especially because we have similar tables for other lifecycles and would like to keep it the same  across components

2020-07-15 18:46 UTC, ckandag commented on security/rbac.adoc
> +To perform cluster lifecycle operations, users must have access to the `managedcluster` namespace and resources. View the following console and API RBAC tables for Cluster lifecycle:
To perform cluster lifecycle operations, users must have access to the `managedcluster` custom resource and its namespace. View the following console and API RBAC tables for Cluster lifecycle:

Note To Mikela : in the above changed  "resources" to "custom resource" , pls note singular for resource

2020-07-15 18:46 UTC, ckandag commented on security/rbac.adoc
> +To perform Governance lifecylce operations, users must have access to the namespace where a policy is created, and access to the `managedcluster` namespace where a policy is created. A user with clus
To perform Governance lifecylce operations, users must have access to the namespace where a policy is created, and access to the `managedcluster` namespace where  policy is applied.

Note to Mikela: Please note the "applied" at the end.  and the rest of it probably not needed here.

2020-07-15 18:46 UTC, ckandag commented on security/rbac.adoc
> +To perform Application lifecycle operations, users must have access to namespace where the Application is created and access to the `managedcluster` namespace. When you create an application, the `su
When you create an application, the `subscription` namespace is created and the configuration map is created in the subscription namespace.

Note To Mikela: The first part of the sentence is not needed, (my apologies).  Only the second sentence is enough.

2020-07-15 18:46 UTC, ckandag commented on security/rbac.adoc
> +//not usre about adding the YAML examples. Are these examples of an application or subscription?
Looks like Roke Jung this ,  lets not include any of the yaml stuff here in the same page.  Perhaps a task  could be adde later to explore this

2020-07-15 18:46 UTC, ckandag commented on security/rbac.adoc
> +
Note To Mikela :   Please also add this note here ,  A user with cluster-wide binding to admin or view roles, has admin or view access to all all management clusters and namespaces.


Given  RBAC for cluster lifecycle is  different and a bit more complex,  I really want to add a task here for the example scenarios  in the RBAC details doc,  in order to reduce the confusion

2020-07-15 18:46 UTC, ckandag commented on security/rbac.adoc
> +//should the role names be enclosed with the codeblock tick marks?
Umm, I Am not sure , what do you suggest?

2020-07-15 20:01 UTC, dockerymick commented on security/rbac.adoc
> +//should the role names be enclosed with the codeblock tick marks?
I am asking if we treat the role names similar to commands. For example. `cluster-admin` vs. cluster-admin (without codeblok marks **`**

2020-07-15 20:21 UTC, dockerymick commented on security/rbac.adoc
> +RBAC is implemented as APIs. When a user attempts an action and the `retrieve` API resource succeeds, the console displays the result. The default roles for `managedcluster` resources are admin, edit
Good catch, that was a mistake as i was reorganizing the doc

2020-07-16 05:19 UTC, ckandag commented on security/rbac.adoc
> +//should the role names be enclosed with the codeblock tick marks?
Looked at Openshift doc,  in a similar roles table names appear to be just bold  .. like here. .. https://docs.openshift.com/container-platform/3.7/architecture/additional_concepts/authorization.html#roles

And  Else where in the doc when referring to the roles .. they are in code blocks. like her https://docs.openshift.com/container-platform/3.7/admin_guide/manage_rbac.html#cluster-and-local-role-bindings

2020-07-16 19:18 UTC, dockerymick commented on security/rbac.adoc
> +
@ckandag so far I have only displayed the examples for the Cluster lifecycle. The information that we are providing in the example seems to be repetitive. I think a diagram might be more helpful if we are able to produce one. We can use the diagram the agree to use for the blogs maybe what do you think?

2020-07-16 19:19 UTC, dockerymick commented on security/rbac.adoc
> +
Or we can add the diagram later as an enhancement to the doc

2020-07-16 20:31 UTC, dockerymick commented on security/rbac.adoc
> +//should the role names be enclosed with the codeblock tick marks?
Thank you! I decided to bold the names in the table

2020-07-20 17:32 UTC, ckandag commented on security/rbac.adoc
> +
Admin, edit, and view are the default OCP roles. An user with a namespace binding  has access to `open-cluster-management` resources in that namespace. An user with cluster-wide binding to the roles has access to all managed-clusters and  `open-cluster-management` resources in all namespaces. Please refer to the tables under each lifecycle  below for details on the "level" access each role to different resources and operations

2020-07-20 17:54 UTC, ckandag commented on security/rbac.adoc
> +| | create, read, update, delete
@dockerymick : This is showing up incorrectly when I view the file as a whole.  Looks like you have extra "|" character on this line "170", that causing it to go off

2020-07-23 15:14 UTC, dockerymick commented
@ckandag I am going to move forward with merging this PR because I don't want to create merge conflicts.

2020-07-23 15:15 UTC, merged